### ISSUE TITLE
StreamInfoAsync Exception

### ISSUE THREAD

**Issue by jbrunken** [StackExchange/StackExchange.Redis#1007]
Using Redis 5 Stream...

``` csharp
var streamInfo = await redis.StreamInfoAsync("mystream");
```

I'm getting the following error:

**Unexpected response to XINFO: MultiBulk: 14 items**

Based on the docs, it looks like the result should have 14 items.

```
> XINFO STREAM mystream
 1) length
 2) (integer) 2
 3) radix-tree-keys
 4) (integer) 1
 5) radix-tree-nodes
 6) (integer) 2
 7) groups
 8) (integer) 2
 9) last-generated-id
10) 1538385846314-0
11) first-entry
12) 1) 1538385820729-0
    2) 1) "foo"
       2) "bar"
13) last-entry
14) 1) 1538385846314-0
    2) 1) "field"
       2) "value"
```

**Comment by mgravell** [comment]
This is already addressed https://github.com/StackExchange/StackExchange.Redis/commit/e8340280b7ced18ee8d1af4d55ed8d8a6bd9d826 - I will see if we can do a build/deploy

**Comment by mgravell** [comment]
deployed, 2.0.519
