### ISSUE TITLE
Exceptions thrown after retargeting to netcoreapp2.1

### ISSUE THREAD

**Issue by ivansams** [StackExchange/StackExchange.Redis#1009]
I have just retargeted our ASP.NET Web API application from .NET Framework 4.7.1 to .NET Core 2.1. We use Azure Redis for our distributed cache as our application is hosted on the Azure App Service. This application has been working fine up until the upgrade. 

Our application runs normally on our DEV environment, which has next to no data in it. However our application throws a number of Redis exceptions in our TEST environment, which is a mirror of PROD including a very large data set stored in our Redis cache. 

We experience a number of these exceptions thrown at application startup and in general usage, some of which reference a particular entity that we have cached but most are thrown from our cache class. 

An example of these exceptions with the stacktrace:

> 2018-11-26 14:10:48.723 +00:00 [Error] FooApi.Infrastructure.Modules.Caching.Aggregates.FooApi.FooApiAggregateCache: Exception thrown in backing cache's 'get'.
> StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL, inst: 38, queue: 213, qu: 0, qs: 213, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0, clientName: RD00155D8D9A7A, serverEndpoint: Unspecified/fooapi-test-redis.redis.cache.windows.net:6380, keyHashSlot: 3155 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
>    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
>    at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
>    at StackExchange.Redis.RedisDatabase.ScriptEvaluate(Byte[] hash, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1079
>    at CacheManager.Redis.RedisCacheHandle`1.Eval(ScriptType scriptType, RedisKey redisKey, RedisValue[] values, CommandFlags flags)
>    at CacheManager.Redis.RedisCacheHandle`1.<>c__DisplayClass48_0.<GetCacheItemAndVersion>b__0()
>    at CacheManager.Redis.RetryHelper.Retry[T](Func`1 retryme, Int32 timeOut, Int32 retries, ILogger logger)
>    at CacheManager.Redis.RedisCacheHandle`1.Retry[T](Func`1 retryme)
>    at CacheManager.Redis.RedisCacheHandle`1.GetCacheItemAndVersion(String key, String region, Int32& version)
>    at CacheManager.Redis.RedisCacheHandle`1.GetCacheItemInternal(String key, String region)
>    at CacheManager.Core.Internal.BaseCache`1.GetCacheItem(String key, String region)
>    at CacheManager.Core.BaseCacheManager`1.GetCacheItemInternal(String key, String region)
>    at CacheManager.Core.Internal.BaseCache`1.GetCacheItem(String key, String region)
>    at CacheManager.Core.Internal.BaseCache`1.Get(String key, String region)
>    at CacheManager.Core.Internal.BaseCache`1.Get[TOut](String key, String region)
>    at FooApi.Infrastructure.Modules.Caching.Aggregates.Base.DualCache`1.Get(String key) in C:\agents\HephaestusForge\_work\25\s\src\FooApi.Infrastructure\Modules\Caching\Aggregates\Base\DualCache.cs:line 173

We also have a thread pool logger that keeps track of our connections to Redis. These logs during these exceptions look like this:

> IOCP: (Busy=0, Min=200, Max=1000), WORKER: (Busy=10, Min=200, Max=682)

Since Busy < Min, this does not seem to be a problem. 

We are quite stuck on this issue and we cannot proceed with making our application cross platform without being able to resolve it. Any advice?

**Comment by mgravell** [comment]
Can you clarify what library version you are working? It doesn't include a version in the error message, which makes me confident that it isn't "latest". Note that we did a *lot* of work in v2 to help network stability in particular targeting things like .NET Core, so: if you are able to try a v2.* library version - please do.

**Comment by MichaCo** [comment]
@mgravell In the docs you mentioned that v2 has a new log format ;)
This is clearly v1.x. 

I already asked @ivansams to [test the beta version of CacheManager 2.0](https://github.com/MichaCo/CacheManager/issues/261) which uses the new StackExchange.Redis client. I'm currently testing it in production and it seem to work much better in terms of those timeouts (not getting any anymore)! 
That's a very broad/general statement and might only be true for my use cases, but just wanted to say thank you and good job!

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.
