### ISSUE TITLE
Help with TIMEOUT in StackExchange.Redis 2.0 ?

### ISSUE THREAD

**Issue by Onasss** [StackExchange/StackExchange.Redis#1016]
After deploying updated version to production we are facing many TIMEOUT errors while connecting to REDIS server. We updated the default ThreadPool size, but the exception is repeatedly comming in unpredictable intervals.. Can something interesting / relevant be found in the error message?

System.Exception: StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL (5000ms), inst: 0, qs: 4934, in: 65536, serverEndpoint: 127.0.0.1:6379, mgr: 10 of 10 available, clientName: app_server, IOCP: (Busy=402,Free=598,Min=4,Max=1000), WORKER: (Busy=2,Free=32765,Min=4,Max=32767), v: 2.0.519.65453 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by soalexmn** [comment]
We got the same issue.**in: 65536** - Socket buffer limit and many waits **qs: 4934**.  Looks like library sometimes stops process answers . Nowadays we realized connection pool (as advise in https://stackexchange.github.io/StackExchange.Redis/Timeouts). We'll try connection pool on production in January.

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.

**Comment by Smoothfu** [comment]
> similar question, and I'm using version 2.0.519
> 
> ```
> An unhandled exception has occurred while executing the request
> StackExchange.Redis.RedisTimeoutException: Timeout performing EXISTS vote:3:vote-items (5000ms), inst: 0, qs: 1459, in: 0, serverEndpoint: Unspecified/zy-dev01.redis.cache.chinacloudapi.cn:6380, mgr: 10 of 10 available, clientName: DESKTOP-2169HK5, IOCP: (Busy=0,Free=1000,Min=128,Max=1000), WORKER: (Busy=1460,Free=31307,Min=2048,Max=32767), v: 2.0.519.65453 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
>    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2197
>    at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
>    at StackExchange.Redis.RedisDatabase.KeyExists(RedisKey key, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 649
> ```

https://www.cnblogs.com/ShaYeBlog/p/11375179.html

**Comment by Smoothfu** [comment]
1.Operate the redis via StackExcahnge in asynchronous;
2.ThreadPool.SetMinThreads(200, 200);
