### ISSUE TITLE
AsyncTimeout has low resolution

### ISSUE THREAD

**Issue by joaocpaiva** [StackExchange/StackExchange.Redis#1020]
Due to our SLAs, our service enforces client side timeouts of 200ms for all async calls to Redis. 

We were excited to find out there was a new timeout mechanism for async operations in v2 however @mgravell, you informed me that currently the library uses a polling mechanism with an hardcoded frequency of 1 second. Obviously this will not work for us because the polling frequency is higher than our timeout.

Any chance the polling frequency can be configurable (perhaps using an override) by callers in the next release, so we different consumers can tweak as they need?

**Comment by NickCraver** [comment]
We could do this more often, but it would be expensive - will ping Marc for thoughts when we're back in action next week.

**Comment by NickCraver** [comment]
Collapsing this into #1160 to get discussion in one place. We're discussing the tradeoffs there :)
