### ISSUE TITLE
Improve TPL usage

### ISSUE THREAD

**Issue by sergii-s** [StackExchange/StackExchange.Redis#1022]
**Improvement proposal** 

Reduce Tasks creation when possible

**Scenario** 
In the case of Redis cluster I'm using multiple get operations when it's impossible to use MGet operation (cannot use key hash tags) :
```C#
var client = GetRedisClient();
var keys = Enumerable.Range(0, 1000).Select(x => $"key_{x}");
var values = await Task.WhenAll(keys.Select(key => client.StringGetAsync(key)));
```

**Problem**
One Task is created for each `StringGetAsync` operation, which provoke a high CPU usage.

**Proposal**
We could create only one Task for multiple get/set operations to reduce CPU usage and task allocations (possible usage) : 
```C#
var keys = Enumerable.Range(0, 1000).Select(x => $"key_{x}").ToList();
var results = new string[1000];

var client = GetRedisClient();

var multiOperation = client.CreateMultiOperation();
for (int i = 0; i < keys.Count; i++)
{
	multiOperation.StringGet(keys[i], res => results[i] = res);
}
await multiOperation.ExecuteAsync();

return results;
```

I've made fast and ugly (but working) [implementation ](https://github.com/sergii-s/StackExchange.Redis/commit/599bbd597186e12826fd2f711288d8254446ffee) for multiple `StringGetAsync` calls to show the idea.

I can generalize implementation and prepare the PR If you are OK with proposal and with final syntax.

**Comment by mgravell** [comment]
If we think specifically of `StringGet`, it should be noted that there is already a varadic overload here:

```c#
Task<RedisValue[]> StringGetAsync(RedisKey[] keys, CommandFlags flags = CommandFlags.None);
RedisValue[] StringGet(RedisKey[] keys, CommandFlags flags = CommandFlags.None);
```

It would seem that the most obvious change here would be: to use that?

**Comment by sergii-s** [comment]
Hello @mgravell, thank you for fast feed-back

Yes, you are right, there is an overload available, but as far as I know I doesn't work in redis _cluster_ conext, isn't it ?

that's what i meant by 
> when it's impossible to use MGet operation (cannot use key hash tags)

**Comment by mgravell** [comment]
Ah, right; so... that's a fun one. Theoretically, the library could do all this internally, i.e.

- partition the varadic form by resolved server (much more efficient than using hash slots)
- issue per-server queries
- wait (or `await`) all of them completing
- stitch everything back together into the correct places

This could be done *relatively* efficiently; alternatively, we could offer some kind of more general purpose "partition by server" method, i.e.

```c#
IGrouping<EndPoint, RedisKey> PartitionByServer(IEnumerable<RedisKey>) // optional flags for replica?
```

which is *much* of the same, but defers the interesting pieces to the caller - while also making it usable in more ways, and simpler. What are your thoughts on something like the `PartitionByServer` method above?

**Comment by sergii-s** [comment]
I dont know the library code well, I had first look on it few days ago, but I don't see the gain of grouping by cluster slot before issuing the requests if we are using pipelining.

Could you clarify a little bit so I could start implementing this ?

You want to expose this method for clients or use it internally only ?
What is the usage would be like for library clients ?
The idea is to use `MGet` method after partitioning or to use pipelining ?

If MGet then we cannot do the following  :
```C#
var multiOperation = client.CreateMultiOperation();
multiOperation.HashSet("hash", "h1", "v1");
multiOperation.StringSet("key1", "val1");
multiOperation.StringGet("key2");
await multiOperation.ExecuteAsync();
```

Thanks

**Comment by mgravell** [comment]
My thought there is for the consumer to issue an mget per server... although actually I think we already prevent that internally with a *shard* check; let me think a bit more about how we can do this most usefully - however: note that the existing batch API *already* uses the async/TPL approach, so : it wouldn't reduce TPL load unless we can switch to task-per-key (your current scenario) to task-per-server. Again, let me think.

**Comment by sergii-s** [comment]
Hello @mgravell , do you have some idea on this ?

On my side I've created a branch of the library based on 1.6.0 and have implemented the logic for `StringGetAsync(RedisKey[])` method only.
I've got a nice garbage collection time improvement and threads count was reduced as well. 

I think it could be really useful for scenarios like mine. I can implement it as soon as we decide how to generalize this logic.

**Comment by NickCraver** [comment]
Collapsing this into #1650 - same feature request overall so let's track in one place.
