### ISSUE TITLE
redis stream support

### ISSUE THREAD

**Issue by rk2012** [StackExchange/StackExchange.Redis#1023]
Does the latest codebase support redis streams ?

**Comment by manigandham** [comment]
Yes. It's not documented but you can look at the tests for sample code:

https://github.com/StackExchange/StackExchange.Redis/blob/master/tests/StackExchange.Redis.Tests/Streams.cs

**Comment by sangloe** [comment]
Apologies if I'm overlooking this in the test file linked above.  Are there plans to support blocking consumers/groups?

**Comment by manigandham** [comment]
It's not supported yet, check this issue: https://github.com/StackExchange/StackExchange.Redis/issues/1158

**Comment by kijanawoodard** [comment]
Looks like this can be closed based on #1158?

**Comment by NickCraver** [comment]
Folding into #1158 - thanks all.
