### ISSUE TITLE
Unable to get the latest key updated in a specific bucket.

### ISSUE THREAD

**Issue by shaunsmithivendi** [StackExchange/StackExchange.Redis#1031]
I'm using Redis along with a .netcore mvc project. We want to be able to look into a bucket and take the last key that was updated. As we store many keys, over 100k in this instance that are persistent. We want to be able to retrieve the last one that one of other system updated. My current solution is to key all the keys in the bucket and then loop through the keys checking the time stamps contained within the values. 

I thought there would be a way to looks at all the transaction to the bucket and from that ascertain the last one updated. But it would  seem I am unable to do that. Wondering if anyone know of any solutions to this. Out side of writing a report to another Redis button every time we execute the software that deals with the keys.

**Comment by mgravell** [comment]
Can you be specific what you mean by a "bucket" here, as that isn't a specific redis structure. I would imagine that a sorted-set keyed by time, or a "stream" (if using redis 5.*+) would be useful if you need to query new/latest

**Comment by mgravell** [comment]
Closing due to lack of clarification; happy to re-open if that context is added.
