### ISSUE TITLE
Add options to customize write buffer threshold to reduce potential thread starving and timeout problems

### ISSUE THREAD

**Issue by zackliu** [StackExchange/StackExchange.Redis#1033]
We're using Redis on Azure and encounter a lot of timeout or even thread starving problems.
After digging deep, we found there's a potential thread starving in the pipeline library
https://github.com/mgravell/Pipelines.Sockets.Unofficial/blob/6cba3f22f553e12f1f70043477eb2add5406ba4d/src/Pipelines.Sockets.Unofficial/StreamConnection.AsyncStreamPipe.cs#L168
The `SSLStream.WriteAsync()` will be scheduled on default thread pool and if the the load of default thread pool is high,  then `FlushAsync()` will be blocked.
https://github.com/StackExchange/StackExchange.Redis/blob/d9a5ee7fc4f1d4daef10bce4fc33e1188d6a8db2/src/StackExchange.Redis/PhysicalConnection.cs#L850
Then all the thread will be blocked at
https://github.com/StackExchange/StackExchange.Redis/blob/d9a5ee7fc4f1d4daef10bce4fc33e1188d6a8db2/src/StackExchange.Redis/PhysicalBridge.cs#L558
`SSLStream.WriteAsync()` will never end and we will get a lot of timeout exception.

We tried to add the write buffer then never get timeout at high load again. Otherwise, if we reduce the buffer, the timeout and thread starving happens more frequently.
https://github.com/StackExchange/StackExchange.Redis/blob/d9a5ee7fc4f1d4daef10bce4fc33e1188d6a8db2/src/StackExchange.Redis/SocketManager.cs#L91

So, it will be fine if we can customize the pipeline write buffer (We have to build private package now). Or schedule `SSLStream.WriteAsync()` on a dedicated thread.

**Comment by mgravell** [comment]
I'm already looking into other problems that may be impacting this, but : to avoid tight-coupling to the pipelines API in the signature, I propose to add a loose API based on a dictionary to allow more control over these options - for example (API does not exist, this is just for discussion):

``` c#
var mgr = new SocketManager("foo", new Dictionary<string,string> {
    {"sendOptions": new PipeOptions {...}}
});
```

The other approach we could *potentially* use is to have a concrete sub-type that *uses* the pipe API (`PipeSocketManager : SocketManager`), but IMO this still embeds a lot of intractible things into the API that we wouldn't be able to remove later if we were using a different implementation, so despite it looking grungy, in many ways I prefer *not* to do that.

Thoughts?

**Comment by NickCraver** [comment]
On the flip side, a simple object let's us properly obsolete things and alert the user properly they were removed - I'd err on the type side here. Less error prone, more intuitive, allows for XMLDoc, etc.

**Comment by mgravell** [comment]
I just worry that there's an absolute ton of options available if we wanted to expose them explicitly; at that point, it would seem more pragmatic to just take a `PipeOptions` (or two) on the API, but that ties the API to implementation. That ties back into the sub-class stuff - we could then `[Obsolete]` an entire sub-type.

**Comment by NickCraver** [comment]
I could see a version hell situation if Pipelines changes their settings underneath, yeah this could go both ways. The only safe way is the messy one: layer between their everything, but I agree that's not ideal to maintain either.

**Comment by NickCraver** [comment]
Given this hasn't come up again and the surface area for adding these APIs is not insignificant, I'm going to close this out. If it becomes a problem not addressed in other ways, we can add more config, but as stated above it's a pretty brittle thing to add and we'd like to avoid this if possible.
