### ISSUE TITLE
How execute ZCOUNT key min max command?

### ISSUE THREAD

**Issue by goldenspb** [StackExchange/StackExchange.Redis#1034]
I am struggling to figure out how I can execute the following redis command:

https://redis.io/commands/zcount

The following code does not seems to work:

```
var count = await _redisCache.Cache.ExecuteAsync("ZCOUNT",
	new object[]
	{
		(RedisKey)"myset",
		"(10",
		"+inf"
	},
	CommandFlags.None);
```

Please advice, what I am doing wrong here?

**Comment by ttingen** [comment]
Use `SortedSetLength` or `SortedSetLengthAsync`. The `max` input parameter defaults to Positive Infinity.

`
var count = await redis.SortedSetLengthAsync("myset", min: 10);
`

**Comment by NickCraver** [comment]
@ttingen thanks for the help!
