### ISSUE TITLE
Setting Min IO Threads Pool on SE.Redis 2.x

### ISSUE THREAD

**Issue by joudot** [StackExchange/StackExchange.Redis#1035]
I am looking for setting the min IO threads pool for production ASP.NET Core applications.

The Timeout doc says 
> In .Net Core, add Environment Variable COMPlus_ThreadPool_ForceMinWorkerThreads to overwrite default MinThreads.

However I thought SE.Redis 2.x would rely on a dedicated thread pool that we could control by setting MinIOThread (and not MinWorkerThread). I know we can set this variable by using ThreadPool.SetMinThreads(…) but I would like to know if there is any way to do it using an environment variable instead (to be able to set it from a Powershell script). 

If we just set MinWorkerThread, will this really affect the Redis performance? 

Finally, is there any recommendation for a default value? (we use 25 for our IIS based applications (not Redis related)).

**Comment by mgravell** [comment]
Ooh, interesting question; indeed `COMPlus_ThreadPool_ForceMinWorkerThreads` is likely to have *less* impact in 2.*, because (as you say) it uses a dedicated thread-pool for most of it's internals; you can still control the size of the dedicated thread-pool, but not via this (or any) environment variable. I need to think a bit more on what to advise here...

**Comment by paveliak** [comment]
@mgravell can you elaborate on 

> you can still control the size of the dedicated thread-pool

From what I understand thread pool size is configured via `SocketManager` .ctor but overload that accepts `workerCount` is private. Even more, by instantiating custom `SocketManager` instance the amount of worker threads drops twice comparing to using the shared SocketManager instance.

Could you share some insights under what circumstances one would benefit from having multiple multiplexers with dedicated and shared socket managers in 2.X?

**Comment by NickCraver** [comment]
This was made possible in #1115 (thanks @naile!) and will be available on NuGet soon as 2.1.x - closing out to cleanup :)
