### ISSUE TITLE
Random SocketFailures; Threads low, Redis CPU/ServerLoad low

### ISSUE THREAD

**Issue by exhaustedcoder** [StackExchange/StackExchange.Redis#1038]
We are randomly seeing the below error after migrating to version 2.*. We are using a pool of connection multiplexers and utilizing a round robin approach, soon to be be least loaded. It seems to be very random and doesn't really correlate to anything else that we have been able to find. Any assistance would be greatly appreciated as this is causing site slowness on an eCommerce platform that heavily uses Redis. Using default configs except for threads.

Error Message: No connection is available to service this operation: HGET storeadmincollection; SocketClosed on *connectionstring*/Subscription, Idle, last: PING, origin: ReadFromPipe, outstanding: 0, last-read: 57473s ago, last-write: 59s ago, unanswered-write: 57473s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, in: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.0.519.65453; IOCP: (Busy=2,Free=998,Min=500,Max=1000), WORKER: (Busy=10,Free=32757,Min=700,Max=32767), Local-CPU: n/a
Inner Message 1: SocketClosed on *connectionstring*/Subscription, Idle, last: PING, origin: ReadFromPipe, outstanding: 0, last-read: 57473s ago, last-write: 59s ago, unanswered-write: 57473s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, in: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.0.519.65453

**Comment by mgravell** [comment]
Unfortunately, a bug (fixed already in the code, available next deploy) means that this message is less helpful than it is meant to be; unfortunately our `last-read` tracking wasn't updating, which means it is hard to have confidence in trying to understand the context here. Can I ask that we revisit this after the next deploy, to see what the message tells us then? (assuming it isn't addressed by any other changes in that deploy)

**Comment by mgravell** [comment]
We are aware of a problem here (relating to a race condition in the write-lock); we're dogfooding a fix locally, and hope to deploy an update in the next day or two.

**Comment by exhaustedcoder** [comment]
Thanks for the update Marc.

**Comment by NickCraver** [comment]
A release for this issue (and better debugging information) went up quite a while ago. Please update to the latest 2.x if you haven't already!
