### ISSUE TITLE
Question: Is it possible to specify SendPipeOptions via configuration or code?

### ISSUE THREAD

**Issue by kristianjaeger** [StackExchange/StackExchange.Redis#1043]
Question: Is it possible to specify SendPipeOptions via configuration or code?  Should this be done via the ConfigurationOptions?  It looks like SendPipeOptions is private??  Thanks.

**Comment by kristianjaeger** [comment]
Thanks @mgravell !  Sorry about the duplicate question.  Appreciate your input.  Cheers.

**Comment by NickCraver** [comment]
Closing as a dupe of #1033 :) Please continue discussion there!
