### ISSUE TITLE
NRediSearch's client exceptions

### ISSUE THREAD

**Issue by zscaiosi** [StackExchange/StackExchange.Redis#1045]
**Environment**:
Windows 10
.NETFramework,Version=v4.6.1

When I use the NRediSearch.Client.GetInfo() function it throws me the following Exception:
**Source**: "StackExchange.Redis"
**Message**: "Specified cast is not valid."
**StackTrace**: 
"   at StackExchange.Redis.RedisResult.ArrayRedisResult.AsRedisValue()\r\n   at StackExchange.Redis.RedisResult.ArrayRedisResult.<>c.<AsRedisValueArray>b__23_0(RedisResult x)\r\n   at StackExchange.Redis.ConvertHelper.<>c__DisplayClass0_0`2.<ConvertAll>b__0(TInput item)\r\n   at System.Array.ConvertAll[TInput,TOutput](TInput[] array, Converter`2 converter)\r\n   at StackExchange.Redis.ConvertHelper.ConvertAll[TInput,TOutput](TInput[] source, Func`2 selector)\r\n   at StackExchange.Redis.RedisResult.ArrayRedisResult.AsRedisValueArray()\r\n   at NRediSearch.Client.ParseGetInfo(RedisResult value)\r\n   at NRediSearch.Client.GetInfo()\r\n   at Atlas.Queue.RedisSearch.Program.CheckAndCreateIndex(Client cli) in C:\\Projetos\\VSWorkspaces\\Repos\\AtlasV2_Backend\\Atlas.Queue.RedisSearch\\Program.cs:line 211\r\n   at Atlas.Queue.RedisSearch.Program.Main() in C:\\Projetos\\VSWorkspaces\\Repos\\AtlasV2_Backend\\Atlas.Queue.RedisSearch\\Program.cs:line 116"

**Code**:
`//Configs
public static List<Content> contents = new List<Content>();
public static ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("<ip>:6379,name=<username>,password=<pass>,abortConnect=false,allowAdmin=true,connectTimeout=10000");

public static IDatabase db = redis.GetDatabase();

NRediSearch.Client cli = new NRediSearch.Client("ix_someindex", db);
`
`

               //Within a function I am using the client. Came as NRediSearch.Client cli.
               //Here it throws the Exception
                var ix_info = cli.GetInfo();

                if (ix_info.Count() == 0)
                {

                    Schema sc = new Schema()
                        .AddSortableTextField("contentId", 1.0)
                        .AddTextField("body", 1.0)
                        .AddNumericField("price");

                
                    if(cli.CreateIndex(sc, NRediSearch.Client.IndexOptions.Default))
                    {
                        return cli.GetInfo();
                    }
                    else
                    {
                        return new Dictionary<string, RedisValue>();
                    }
                }
                else
                {
                    return ix_info;
                }
`

Does anyone know what might be happening?
Thanks!

**Comment by NickCraver** [comment]
Thanks for the heads up! This is fixed in the latest module and client. I was hitting the same locally and fixed it up in #1383. Ultimately, this was an API change by NRediSearch that required adapting to. This is available on MyGet latest now, and will be in the 2.1.x release.
