### ISSUE TITLE
"ERR This instance has cluster support disabled" under load with master/slave

### ISSUE THREAD

**Issue by dbrink** [StackExchange/StackExchange.Redis#1047]
When using 2.0.519 we're seeing strange errors during load tests.  Exceptions are thrown with message "ERR This instance has cluster support disabled".  This error looks to be bubbled up out of redis if the CLUSTER, ASKING, or READONLY commands are issued without clustering enabled.  Redis is configured as master/slave/slave with three sentinels.  As far as I can tell we're not issuing any of these commands directly.  Should we disable this commands via the connection string?  What might cause this to happen?

Thanks.

**Comment by NickCraver** [comment]
Question (I know it's way late - I'm sorry) Were you using authentication with your instances? More recently #1367 fixed a race issue here which affected reconnect and likely would have caused your issue.
