### ISSUE TITLE
"No connection is available" - tcpping fine, server is up, etc

### ISSUE THREAD

**Issue by kierenj** [StackExchange/StackExchange.Redis#1051]
This happens sometimes after several days, other times immediately following a new version deployment.

The fix is to re-deploy the app (presumably, a process restart fixes it).

In each case, `tcpping` to the redis server is fine, and other clients to the server have the same issue.

Very latest nuget pkg version at time of writing.

```c#
No connection is available to service this operation: RPOPLPUSH prism-livesaff_wqitem_PRSM_Production_evt; UnableToConnect on redacted.redis.cache.windows.net:6380/Interactive, Initializing, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, unanswered-write: 267677s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.519.65453; IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=4,Free=32763,Min=4,Max=32767), Local-CPU: n/a, retrying after 0.100s | -
-- | --
```

**Comment by NickCraver** [comment]
We're seeing this happen in cloud environments with a lot of duplicates of what is ultimately the same issue. I'm closing this just to consolidate and link it to #1120. A fix s underway in #1374 that should help curb this "stuck" bad state for good in these scenarios.
