### ISSUE TITLE
ConnectionMultiplexer.TryCompleteHandler silently discards exceptions from callbacks

### ISSUE THREAD

**Issue by gooseserbus** [StackExchange/StackExchange.Redis#1061]
The current implemetation of ConnectionMultiplexer.TryCompleteHandler silently discards exceptions from callbacks:

[https://github.com/StackExchange/StackExchange.Redis/blob/master/src/StackExchange.Redis/RedisSubscriber.cs#L24](https://github.com/StackExchange/StackExchange.Redis/blob/master/src/StackExchange.Redis/RedisSubscriber.cs#L24 )

```
try
{ sub.Invoke(sender, args); }
catch
{ }
```

Is there any way to allow this exception to be passed back to the application so that it can be caught by the unhandled exception handler for the app rather than being silently discarded.

Alternatively, we could provide a logger interface of some kind so that the exception can be logged by the application.

**Comment by mgravell** [comment]
The problem we get into here is: it gets really really common that loggers
can't keep up with data. What do we do if the logger blocks? Or throws?
Today: the callback can already catch their own exception and handle it any
way they want...

**Comment by gooseserbus** [comment]
That's only if you remember to add that exception handler, I can understand your objections though. I'm not sure I have another suggestion.

Maybe you could mention this in the documentation for the pub/sub?

https://stackexchange.github.io/StackExchange.Redis/Basics#using-redis-pubsub

It might save someone some time in the future.

**Comment by NickCraver** [comment]
I've added a documentation note in https://github.com/StackExchange/StackExchange.Redis/commit/c501ba4b1c66f663cbb94b3f17045936cc7e1198 (...and a typo fix after):
> Note: exceptions are caught and discarded by StackExchange.Redis here, to prevent cascading failures. To handle failures, use a `try`/`catch` inside your handler to do as you wish with any exceptions.

Thanks for the issue and suggestion! If that's unclear, I'm happy to tweak just let us know :)
