### ISSUE TITLE
HSCAN Timeout with no other cache activity

### ISSUE THREAD

**Issue by CDargis** [StackExchange/StackExchange.Redis#1063]
> StackExchange.Redis.RedisTimeoutException: 'Timeout performing HSCAN myhashkey (1000ms), inst: 0, qs: 1, in: 0, serverEndpoint: Unspecified/master.pp-app-cache.6koqgr.use1.cache.amazonaws.com:6379, mgr: 10 of 10 available, clientName: DESKTOP-MMMEL45, IOCP: (Busy=0,Free=1000,Min=250,Max=1000), WORKER: (Busy=0,Free=8191,Min=300,Max=8191) (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)'

StackExchange.Redis version is `2.0.495`

I am seeing this error 1/10 times. Otherwise the operation completes and I can pull back all the keys. I am using CachingFramework.Redis to do the scan so I have no control over the page size. Number of keys is 218. I can use HGETALL but I would rather not. Any idea why this is happening?

**Comment by mgravell** [comment]
Well, there's one thing sent pending a response, and nothing on the inbound
socket. To me that suggests server or network stall. But: are you using a
recent version? And is this involving TLS?

**Comment by CDargis** [comment]
StackExchange.Redis version is 2.0.495, using AWS Redis ElastiCache with engine compatibility version 3.2.6.   With respect to TLS: Connection string specifies `ssl=true` but not specifying which protocol via `sslProtocols`. Would the protocol used then depend on what the server supports? Is a property on the connection mulitplexer that would tell me which protocol?

**Comment by CDargis** [comment]
Also if it matters - nothing else in the system would be using the same keys. The keys were unique to the code I was developing.

**Comment by CDargis** [comment]
Apologies, did not mean to close.

**Comment by mgravell** [comment]
We are aware of a problem here (relating to a race condition in the write-lock); we're dogfooding a fix locally, and hope to deploy an update in the next day or two.

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.

**Comment by yuzhangyi** [comment]
@mgravell, recently I upgrade StackExchange.Redis to be version "2.0.601", it is easy to meet timeout in hashscan, could you help give some suggestion? The data is cache is small.

StackExchange.Redis.RedisTimeoutException: Timeout performing HSCAN (5000ms), next: HSCAN FFE8A6C8-1D59-467C-8404-F24615AF0818@DATAMOVEMENTACTIVITY, inst: 35, qu: 0, qs: 15, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: Unspecified/testtong.redis.cache.windows.net:6380, mgr: 10 of 10 available, clientName: ZHANGYI2016, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=16,Free=32751,Min=12,Max=32767), v: 2.0.601.3402
