### ISSUE TITLE
Spread load over master and slave

### ISSUE THREAD

**Issue by titilon** [StackExchange/StackExchange.Redis#1072]
Hi

We are working with one master and one slave (StackExchange.Redis version 2.0.519).
We wondered if there is a way to spread the load, when the user reads data, over both the master and the slave (and not only the master/slave like when CommandFlags.PreferMaster/PreferSlave is used)?

Thanks

**Comment by mgravell** [comment]
To clarify: you want to round-robin between the primary and the replica?
That isn't currently an inbuilt option, but we could presumably do
something if it seemed a common scenario. Right now, you'd have to rotate
the preference option at the call site. Presumably that can be done as an
'xor' if you so choose.

**Comment by NickCraver** [comment]
Labelling this with `pooling` just thinking we should keep it in mind when visiting vNexgt.

**Comment by NickCraver** [comment]
Never got clarification on this one, so closing out to tidy up.
