### ISSUE TITLE
Connection interval support

### ISSUE THREAD

**Issue by ralfius** [StackExchange/StackExchange.Redis#1073]
Hi guys,

I would be great to have ConnectionInterval along with ConnectRetry property so the ConnectionMultiplexer waits this interval time between attempts to connect to Redis repeating ConnectRetry times.
In this case ConnectionMultiplexer can give more predictable and reliable in terms of retry functionality behavior when for example interval = 5 seconds with retry = 10 times would give predictable 50 seconds of connection retry.

**Comment by NickCraver** [comment]
I'm revisiting requests in the backlog - do you have a use case for this? Most people want to reconnect to Redis and restore functionality ASAP. I'm curious when you want to delay that for such a long duration - can you help us out with the use case here?
