### ISSUE TITLE
No connection is available to service this operation: HKEYS

### ISSUE THREAD

**Issue by DmitryMorozov228** [StackExchange/StackExchange.Redis#1082]
Hi, guys! I faced with the following issue:
No connection is available to service this operation: HKEYS ; UnableToConnect on my-azure-redis-cache-server-host/Interactive, Initializing, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 5s ago, last-write: 5s ago, unanswered-write: 1019408s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.513.63329; IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=5,Free=677,Min=1,Max=682), Local-CPU: n/a

I'm using StackExchange.Redis nuget package version 2.0.513.
Thank's for help.

**Comment by NickCraver** [comment]
Collapsing this into #1120 and #1374 - this looks to be get another manifestation of the state hang issue we aim to resolve with the 2.1.x release soon.
