### ISSUE TITLE
Connection Leak when using ConnectionMultiplexer

### ISSUE THREAD

**Issue by TristanHam123** [StackExchange/StackExchange.Redis#1084]
I am using a static dictionary that maps the connection string to a ConnectionMultiplexer. We only have one connection string right now, so there is only ever one ConnectionMultiplexer created at the moment. 

I added logging directly before I call ConnectionMultiplexer.Connect( options ), and I'm seeing that it only gets called one time in my code. However, I found through monitoring the "client list" on the Redis console, that my application is creating an additional connection to Redis every couple of minutes, which adds up over time and eventually breaks our Redis by opening too many connections. 

I have added locking to make sure there's not multiple threads creating the one initial redis connection at the same time. The additional connections that get opened are not being opened by my code as far as I can tell, because setting break points, as well as logging, shows only a single time when my code to open a redis connection is ran.

Also, this is for webjobs. I don't actually have to call my webjobs and run through their flow. Connections continue to be created even when my webjobs sit idle. 

Please help.

**Comment by NickCraver** [comment]
So we've seen this a lot too - the thing is: redis *never* clears dead sockets from that list if not configured to. If your socket is dropping due to network or inactivity for example, ConnectionMultiplexer will re-connect but redis may not be killing the stale ones. What is your server config for `tcp-keepalive`? Note: this can also happen if you've set the heartbeat over the server's `timeout` (seconds) property.

You can verify the overall behavior by running a `netstat` on the client machine and seeing if the ports are *actually* in use, my bet is only 1 to a few of the ones listed on the redis server side are actually active on the client machine.

**Comment by TristanHam123** [comment]
I found that my issue is being caused by a failed connection that keeps persisting to reconnect but it's not dropping the bad connections prior. I tried setting the keepalive and timeout option to many different values, and tested, but it didn't stop the connections from growing. Eventually, I cloned the entire StackExchange.Redis code, and added in a line of code that quits all servers when a connection fails. I'm no longer getting the rapid growth in connections after this. Is there any issue with my change?

**Comment by MaximKojine** [comment]
Hi @TristanHam123 
Do you mind to share that "a line of code"?

**Comment by NickCraver** [comment]
@TristanHam123 Can you share what you did here?

**Comment by dzmitry-lahoda** [comment]
I have leaking sockets. I have added to resources, http client and redis and official k8s client. Http used as before, so there is k8s client and redis which may leak. Redis is singleton holding multiplexed connection.

**Comment by dxynnez** [comment]
I think we might hit a similar issue - we accidentally use an invalid connection string to initialize the ConnectionMultiplexer and that seems to start leaking sockets on every GetDatabase call.

@NickCraver is there a way to tell ConnectionMultiplexer to reuse the existing socket, or , to clear dead sockets so the number of sockets wouldn't increase unboundedly?

**Comment by NickCraver** [comment]
@dxynnez So: not really - we simply don't control that, it's an OS-level decision for cleanup. It does happen, but the durations (e.g. time spent sitting in TIME_WAIT) is an OS configuration (shared for all apps) and only it will cleanup. If you had more info about what was happening in your case though, e.g. did it retry forever? And how? The multiplexer itself has a retry limit of 3 which should be drastically under any OS limits here (generally 10,000+), but if you have wrapper logic retrying indefinitely, that we wouldn't control.

Can you elaborate more on what was retrying so much in your case?

**Comment by dxynnez** [comment]
@NickCraver we are on azure app service and as part of the healthcheck we check the redis conenctivity (do a write & read). I believe app service would make healthcheck ping every 1 min. According to the azure metrics, those sockets seem to stay in the TIME_WAIT state forever until we fix the connection string.

I have 2 questions regarding this:
1) Does ConnectionMultiplexer somehow send keepalive message to keep the connection open?
2) Is there a way to do connection pooling with ConnectionMultiplexer, something similar to [HttpClientHandler.MaxConnectionsPerServer](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.maxconnectionsperserver?view=netcore-3.1)?

**Comment by NickCraver** [comment]
@dxynnez That description makes me think a new ConnectionMultiplexer is made each time - is that correct? What's the lifetime of your multiplexer?

On the questions:
1. Yes, while active we have a heartbeat so the socket doesn't die (any persistent connection needs this, so the OS doesn't kill it), but that ceases when closing or disposing the multiplexer.
2. See above - I'm not sure what "each retry" looks like here - need to know lifetimes. Each connect it'll...connect :)
3. It's not designed like that - it's a pipelined connection when means 1 multiplexer can be used by hundreds of things at once - you don't need multiple to begin with.

**Comment by dxynnez** [comment]
> @dxynnez That description makes me think a new ConnectionMultiplexer is made each time - is that correct? What's the lifetime of your multiplexer?
> 
> On the questions:
> 
> 1. Yes, while active we have a heartbeat so the socket doesn't die (any persistent connection needs this, so the OS doesn't kill it), but that ceases when closing or disposing the multiplexer.
> 2. See above - I'm not sure what "each retry" looks like here - need to know lifetimes. Each connect it'll...connect :)
> 3. It's not designed like that - it's a pipelined connection when means 1 multiplexer can be used by hundreds of things at once - you don't need multiple to begin with.

That would be interesting... We reuse the same ConnectionMultiplexer - we DI a singleton ConnectionMultiplexer with
```
  services.AddSingleton<IConnectionMultiplexer>(sp => ConnectionMultiplexer.Connect(#CONNECTION_STRING#));
```
and use it for the lifetime of the application. We then simply do IConnectionMultiplexer#GetDatabase() and IDatabase#StringSetAsync / StringGetAsync each time.

> 3. It's not designed like that - it's a pipelined connection when means 1 multiplexer can be used by hundreds of things at once - you don't need multiple to begin with.
If that's the case, in what case the multiplexer would open a new socket?

**Comment by dxynnez** [comment]
Hi @NickCraver , did you get a chance to look into this? Or I should open a new issue instead since this one had been marked as closed?

**Comment by dxynnez** [comment]
Hi @NickCraver , I was able to repro this locally with below code:
```
            var multiplexer = ConnectionMultiplexer.Connect("#A VALID REDIS HOST#:6380,password=,ssl=True,abortConnect=False");
            for (int i = 0; i < 1000; i++)
            {
                try
                {
                    multiplexer.GetDatabase();
                }
                catch (Exception ex)
                {
                    Console.Out.WriteLine(ex.Message);
                }
            }
```

Seems like the GetDatabase call would try to establish the connection everytime since we set 'abortConnect=False' when connect. I guess this is somehow expected as none of the connections could be established and it just keep opening new ones which sooner ends in TIME_WAIT?

Do you happen to know why the abortConnect is default to false on Azure? I am wondering if I should just set it to true and enable retry when trying to connect.
