### ISSUE TITLE
Minimum supported request timeout

### ISSUE THREAD

**Issue by paveliak** [StackExchange/StackExchange.Redis#1085]
Hi @mgravell 

Some time earlier you mentioned that StackExchange uses 1 sec timeout and default is 5 sec. I am looking for _decreasing_ the timeout as much as possible and wonder how far we can go from your experience.

We run ASP.NET based service in Azure and use Azure Redis as a cache. For better user experience we would prefer Redis timing out instead of waiting for 1 sec or more and getting response back (which could be a cache miss). If Redis times out we will simply make a request to the "source of truth".

We decreased the timeout to 500 msec and it looks good, 99,9% requests do not time out. However after we decreased it further to 200 msec we started observing unusual noise of Timeout exceptions. The interesting thing about them is they have all zeros in the diagnostics data - `queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0`

- Having all zeros does it mean that request was not even queued? What could cause that?
- Also are we stressing library too much? Ideally we want to go down to 100 msec timeout.

CPU on the VMs looks good as well as thread pool.
We are using v1.2.6 and vast majority of our requests use synchronous API.

Thank you,
Pavel

**Comment by mgravell** [comment]
On the synchronous API, it can probably go arbitrarily small. The problem
is *async* timeouts - accurately doing async timeouts is a massive pain.

I can't comment on much 1.* these days, but if this was 2.*, I'd imagine
that the error you'd be seeing is something about "the operation timed out
out before it could be written, and it was not sent*

**Comment by paveliak** [comment]
Thanks. We attempted to move to v2.0.513 but had to rollback due to high cpu issues.

From what I understand it’s a known issue. We will certainly try again once you think it’s resolved.

Pavel

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.
