### ISSUE TITLE
No connection is available to service this operation: SET

### ISSUE THREAD

**Issue by rahulNandan** [StackExchange/StackExchange.Redis#1088]
I am trying to connect AWS Elasticache SSL enabled endpoint using C# and StackExchange.Redis v2.0.519 from AWS Lambda (All required Security Groups are in place as I tested it using python works as expected), Below is the code snippet.

                Console.WriteLine("Started...");
                //string RedisConnectionString = Environment.GetEnvironmentVariable("RedisEndpoint");
                //var addresses = Dns.GetHostAddressesAsync(RedisConnectionString.Split(':')[0]).Result;

                //var ip4Adresses = addresses.Select(x => x.MapToIPv4()).Distinct().ToList();
                var config = new ConfigurationOptions
                {
                    EndPoints = { { "master.************.amazonaws.com", 6379 } },
                    AllowAdmin = true,
                    AbortOnConnectFail = false,
                    Ssl = true,
                    SyncTimeout = 3000,
                    KeepAlive = 10
                };

                //ip4Adresses.ForEach(ip => config.EndPoints.Add(ip, Int32.Parse(RedisConnectionString.Split(':')[1])));

                Console.WriteLine("Configured...");

                using (var conn = ConnectionMultiplexer.Connect(config))
                {
                    Console.WriteLine("Connected..");
                    var db = conn.GetDatabase(0);
                    db.StringSet("hello", "world");
                    Console.WriteLine(db.StringGet("hello")); // writes: world
                }
But it throws error as below.
No connection is available to service this operation: SET hello; It was not possible to connect to the redis server(s). To create a disconnected multiplexer, disable AbortOnConnectFail. ConnectTimeout; IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=4,Free=32763,Min=2,Max=32767), Local-CPU: n/a

**Comment by rahulNandan** [comment]
Hi Team, Did you get a chance to look at this issue?

**Comment by NickCraver** [comment]
Hey @rahulNandan apologies for not getting to duplicates of the same issue - several SSL issues were fixed in the later 2.0.x releases - are you seeing any trouble with latest? We don't have AWS as a test endpoint but other users are using it without issue so it is supported and should be working with the right config on latest.

**Comment by ashiahakim** [comment]
@rahulNandan  I am also facing the same problem. Is this issue resolved for you?

**Comment by NickCraver** [comment]
Without more info here - closing this out to cleanup.
