### ISSUE TITLE
Set lifetime Expiry or no expiry time for Redis cache C#?

### ISSUE THREAD

**Issue by yadavparveen** [StackExchange/StackExchange.Redis#1095]
0

I am working on .Net core application and there I have to store some date in Redis cache without any expiry timing, that means I want to store this data for a lifetime.

This is the current implementation:-

``` var db = await GetDatabase();
                expires = expires ??
                TimeSpan.FromSeconds(_defaultCacheDurationSeconds);

                if (db != null && expires.Value.TotalSeconds > 0)
                {
                    await db.StringSetAsync(key, val, expires);
                }```
so here I want to pass life time value so it never expire

`await db.StringSetAsync(key, val, expires);`

help would be appreciated :)

Thanks in Advance for looking into this.

**Comment by mgravell** [comment]
If you don't want it to expire ... don't specify an expitation? Note:
depending on your server configuration, that doesn't quite mean "will never
be removed" - if the server is configured for LRU flush on memory full, for
example, things can still go.

**Comment by mgravell** [comment]
Closing due to lack of feedback; if I've misunderstood the problem and my earlier response doesn't apply: just let me know and we can reopen etc
