### ISSUE TITLE
Type “ConfigurationOptions” Exist in “StackExchange.Redis.StrongName” and “StackExchange.Redis”中

### ISSUE THREAD

**Issue by mrbeans** [StackExchange/StackExchange.Redis#1096]
类型“ConfigurationOptions”同时存在于“StackExchange.Redis.StrongName, Version=1.2.4.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46”和“StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46”中

I have notice  there are so many people got this error,but now this problem is still there,so i want to know when will this error will be fixed,or is there have any solution（besides [StackExchange.Redis Issues](https://github.com/StackExchange/StackExchange.Redis/issues/697) or [Nuget Issues](https://github.com/NuGet/Home/issues/4989) ）? thank you!

**Comment by mgravell** [comment]
Having the lib from two packages is a very bad idea. Do you need the old
version? Is that coming from another downstream dependency? If so: you
should stick with that version until the other version removes/updates it's
dependencies.

**Comment by FrankDupree** [comment]
I had the same issue, The solution is either tweaking your .csproj file or installing one over the other. We really need a permanent fix. It turns out a project depended on another project that depended on the strongname version. took me three days to fix this one.

**Comment by mcheung610** [comment]
@FrankDupree do you mind sharing your fix for the poor soul who is trying to upgrade `stackexchange.redis` in netcoreapp 2.x?

**Comment by wuchang** [comment]
<PackageReference Include="Microsoft.Extensions.Caching.Redis" Version="2.2.0" />
改为
<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="3.1.0" />

**Comment by wuchang** [comment]
用新装  Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="3.1.0"
