### ISSUE TITLE
Keys method pageSize usage guidance

### ISSUE THREAD

**Issue by adamkjonesmesh** [StackExchange/StackExchange.Redis#1098]
Hello,

We found when executing the Keys function (IServer.Keys) against a Redis cache repository containing many hundreds of thousands of keys, the performance was deplorable.  We have since discovered, through another github issues page (https://github.com/StackExchange/StackExchange.Redis/issues/259), that the Keys function scans 10 keys per page by default; however, the user can override the default pageSize by passing in an int of pageSize.  My question, then, is directed at performance.

Is there guidance on how big to set the pageSize?  What if the Redis respository is small (say a few hundred keys) and one passes in a large pageSize (say 10000).  Is there a negative performance impact?

Is there a max limit for the pageSize?

Thanks.

**Comment by mgravell** [comment]
This is fundamentally a server question, I think. So the only answer I can
give is: "whatever works with your workload" (adding the caveat: you should
be avoiding keys/scan *anyway*, as per the redis documentation).

Note, however, that I have speculatively increased the default by a good
amount in a branch looking at async enumerables. I agree with you that the
default is too small, even if it does match the server's default.

**Comment by adamkjonesmesh** [comment]
If avoiding Keys/Scans is ideal, then do you know what the ideal usage pattern is in order to find all exact keys based on a pattern?  For example, when given some pattern, say, *|text1|text2|* where matching keys may be prefix1|text1|text2|suffix1, prefix2|text1|text2|suffix2.  Thanks.

**Comment by adamkjonesmesh** [comment]
Before the |text1 and after text2| there were supposed to be asterisks denoting wildcards.

**Comment by mgravell** [comment]
I would say: if possible, out the keys that you need for that kind of feature in a set or hash if possible.

If you need to scan, you need to scan - just: please understand the implications of that for the server.

**Comment by adamkjonesmesh** [comment]
Ok, thanks.  I will close this.  Thanks for your help and guidance.
