### ISSUE TITLE
Timeout performing PSETEX

### ISSUE THREAD

**Issue by No0Vad** [StackExchange/StackExchange.Redis#110]
Been playing with Redis and C# for some hours now. But I've noticed that sometimes, when StringSet is called, a Timeout Exception is thrown.

```
[TimeoutException: Timeout performing PSETEX c2cbc817d14b825e7b40b9c8e41bffd1__-1753266091, inst: 1, mgr: ExecuteSelect, queue: 2, qu=0, qs=2, qc=0, wr=1/1, in=0/0]
   StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl(Message message, ResultProcessor`1 processor, ServerEndPoint server) +919
   StackExchange.Redis.RedisBase.ExecuteSync(Message message, ResultProcessor`1 processor, ServerEndPoint server) +66
   StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable`1 expiry, When when, CommandFlags flags) +95
   TestSite.RedisCachingProvider.Set(String cacheKey, Object entry, DateTime utcExpiry) in c:\TestSite\RedisCachingProvider.cs:125
   System.Web.Caching.OutputCache.InsertResponse(String cachedVaryKey, CachedVary cachedVary, String rawResponseKey, CachedRawResponse rawResponse, CacheDependency dependencies, DateTime absExp, TimeSpan slidingExp) +682
   System.Web.Caching.OutputCacheModule.OnLeave(Object source, EventArgs eventArgs) +93
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69
```

Part of my code:

``` C#
public override object Add(string cacheKey, object entry, DateTime utcExpiry)
{
    var cachedEntry = Get(cacheKey);

    if (cachedEntry == null)
    {
        Set(cacheKey, entry, utcExpiry);
        return entry;
    }

    return cachedEntry;
}

public override object Get(string cacheKey)
{
    var storageDetails = GetStorageDetails(cacheKey);
    var redis = storageDetails.Database;
    var cachedBytes = redis.StringGet(storageDetails.Key);

    return cachedBytes.IsNull
        ? null
        : DeserializeObject(cachedBytes);
}

public override void Set(string cacheKey, object entry, DateTime utcExpiry)
{
    var storageDetails = GetStorageDetails(cacheKey);
    var redis = storageDetails.Database;
    var newBytes = SerializeObject(entry);

    redis.StringSet(storageDetails.Key, newBytes, utcExpiry.Subtract(DateTime.UtcNow));
}

private static StorageDetails GetStorageDetails(string cacheKey)
{
    return new StorageDetails
    {
        Database = ConnectionMultiplexer.GetDatabase(),
        Key = TransformKey(cacheKey)
    };
}
```

The redis.conf has not been modified and I'm running Redis 2.8.4 on Ubuntu 14.04.1

Something I'm missing, or is it a bug?

**Comment by turowicz** [comment]
Having a similar problem, any news?

**Comment by Xhanti** [comment]
+1

**Comment by nmehlei** [comment]
Based on your posted exception message, you seem to be using an older version of StackExchange.Redis. I would try an update.

Though I have to admit, I also have occasional timeouts and connection problems, even with the newest version :/

**Comment by No0Vad** [comment]
I never really found a solution. Only a work-around. Example on the **Get** method.

	public override object Get(string cacheKey)
	{
	    var storageDetails = GetStorageDetails(cacheKey);
	    var redis = storageDetails.Database;
	    RedisValue cachedBytes
	    
	    try
	    {
	        cachedBytes = redis.StringGet(storageDetails.Key);
	    }
	    catch (TimeoutException)
	    {
	        // Wait... then try again
	        Thread.Sleep(100);

	        cachedBytes = redis.StringGet(storageDetails.Key);
	    }

	    return cachedBytes.IsNull
	        ? null
	        : DeserializeObject(cachedBytes);
	}

This solved my Timeout errors when I was playing with Redis and learning how to use it.

I have not tried the latest version of Redis.

**Comment by mgravell** [comment]
Ultimately this is impossible to answer in isolation. There are *lots* of
variables:

- what is the size of the serialized object / payload?
- what else is on that connection at the moment?
- what is going on at the server? Anything in slowlog or the server log?
- any network blockages?
- what is going on at the client? Is it saturated?
- what is the timeout configured as?

There are a number of ways of investigating a blip, but it is somewhat
contextual to the most likely issue...

**Comment by turowicz** [comment]
Solution for me was not to make so many connections (of any type), my app was having 2000 simultaneous connections and the sockets were timing out. After fixing that redis went back to normal. Debugging stackexchange.redis has highlighted this as solution easily.

**Comment by mgravell** [comment]
Dapper goes out of its way to *not* require lots of connections; most apps
should be fine with a single multiplexer.

**Comment by mgravell** [comment]
I'm sorry, ignore my "dapper" there - I of course meant SE.Redis; I'm
having a brain-free day. Other than the noun, my comment stands.

**Comment by Xhanti** [comment]
Found this for anyone experiencing something similar:
http://azure.microsoft.com/blog/2015/02/10/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/

**Comment by NickCraver** [comment]
Looking at the the original issue, I see I missed this part: `System.Web.Caching.OutputCache.InsertResponse`. For anyone else hitting this with output cache (as Marc lists above, we had lots of possible reasons and a lot of these have improved the last few years), bear in mind that massive objects (e.g. 50+KB pages) take a while, and if you're inserting those into redis (or fetching) you'll want to up the timeouts quite a bit to accommodate that. I wouldn't recommend using Redis for output cache with pages of significant size in general though.

Going to close this one out since it's isolated and quite old...trying to get a handle on current issues in the repo.
