### ISSUE TITLE
SocketFailure on node/Interactive [Azure Redis]

### ISSUE THREAD

**Issue by dantheman999301** [StackExchange/StackExchange.Redis#1100]
Hey,

I've seen an intermittent issue when connecting to Azure Redis where it takes absolutely ages to try and connect and then we eventually get the following message (just under an hour)

```
SocketFailure on my-redis.redis.cache.windows.net:6380/Interactive, 
Idle, 
last: INFO, 
origin: ReadFromPipe, 
outstanding: 2, 
last-read: 2368s ago, 
last-write: 0s ago, 
unanswered-write: 2368s ago, 
keep-alive: 60s, 
state: ConnectedEstablished, 
mgr: 8 of 10 available, 
in: 0, 
last-heartbeat: 0s ago, 
last-mbeat: 0s ago, 
global: 0s ago, 
v: 2.0.519.65453
```

Honestly not that experienced with Redis so this has stumped me. Found a few similar issues but they say they have been fixed by releases from over half a year ago. Not sure if I'm doing something stupid!

Any help would be greatly appreciated.

**Comment by NickCraver** [comment]
We've seen a few overlapping issues here, but not being in Azure normally we haven't seen it first hand. A cause for the bad state persisting has been identified in #1120 and #1374. Collapsing this into the #1120 discussion to keep it in one place - for anyone else hitting this look out for the 2.1.x release soon.
