### ISSUE TITLE
V2.0.571.20511 Timeouts, error message has low qs and busy threads, but high qu value

### ISSUE THREAD

**Issue by ConnorL33t** [StackExchange/StackExchange.Redis#1105]
`The timeout was reached before the message could be written to the output buffer, and it was not sent, timeout: 5000, phys: Idle, outbound: 220KiB, inbound: 101KiB, inst: 220, qu: 31, qs: 0, in: 0, serverEndpoint:<redacted>:6379, mgr: 9 of 10 available, clientName:<redacted>, IOCP: (Busy=0,Free=1000,Min=1000,Max=1000), WORKER: (Busy=3,Free=679,Min=100,Max=682), `

Over the past few months I've repeatedly seen this error on our Azure Redis cache. AFAIK we comply well with the "Best practices" of using StackExchange.Redis. 

Our Redis instance is only using 10% of cache size (1gb cache size), and rarely has CPU spikes over 20%, total throughput is ~200/KiBs. Client server is not seeing resource exhaustion / pressure either.   

As far as I can tell CPU spikes do not coincide with the timeouts. 

I'm at a loss, as I don't know what regular values are for "inbound", "outbound", "inst", "qu" or what we can try further to get rid of these errors without scaling up the redis instance, because it seems like we're not even close to pushing this server to it's limits

**Comment by mgravell** [comment]
We are aware of a problem here (relating to a race condition in the write-lock); we're dogfooding a fix locally, and hope to deploy an update in the next day or two.

**Comment by ConnorL33t** [comment]
Thank you for the update @mgravell

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.
