### ISSUE TITLE
Redis Cache TimeOut Exceptions

### ISSUE THREAD

**Issue by amitgoel2k6** [StackExchange/StackExchange.Redis#1106]
![image](https://user-images.githubusercontent.com/49087454/55271983-12034e00-52dc-11e9-9a01-86f2771cafb9.png)

**Comment by mgravell** [comment]
We are aware of a problem here (relating to a race condition in the write-lock); we're dogfooding a fix locally, and hope to deploy an update in the next day or two.

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.
