### ISSUE TITLE
After Update Version  then RedisTimeoutException

### ISSUE THREAD

**Issue by dezheng** [StackExchange/StackExchange.Redis#1107]
After update StackExchange.Redis from  2.0.544 to 2.0.560, I got RedisTimeoutException.
And if I revert the version, this exception can not see anymore.
Pls hep,thanks..

Exception code
`The timeout was reached before the message could be written to the output buffer, and it was not sent, 
timeout: 5000, phys: Idle, outbound: 444KiB, inbound: 69KiB, inst: 386, qu: 31, qs: 0, in: 0, 
serverEndpoint: Unspecified/XXXXXXXXXX, mgr: 9 of 10 available, 
clientName: XXXXXXX, 
IOCP: (Busy=0,Free=1000,Min=200,Max=1000), 
WORKER: (Busy=31,Free=32736,Min=200,Max=32767), 
v: 2.0.560.47694 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

**Comment by mgravell** [comment]
We are aware of a problem here (relating to a race condition in the write-lock); we're dogfooding a fix locally, and hope to deploy an update in the next day or two.

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.

**Comment by dezheng** [comment]
> The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.

Thanks，I‘ll try this.’
