### ISSUE TITLE
ArgumentOutOfRangeException when accessing ConnectionMultiplexer log

### ISSUE THREAD

**Issue by paveliak** [StackExchange/StackExchange.Redis#1108]
Hi

I got an `ArgumentOutOfRangeException` exception when calling ToString() for the ConnectionMultiplexer log. From the code it looks like all writes to the TextWriter object are synchronized inside the StackExchange.Redis code so the only thing that comes into my mind is that writes might continue after Connect() method returns and then ToString() method collides with those writes. Does it sound plausible?

FWIW we are using v1.2.6.

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength

at System.Text.StringBuilder.ToString()
at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
...

Here is our code:

```
var log = new StringWriter();
ConnectionMultiplexer mux = ConnectionMultiplexer.Connect(configurationOptions, log);
Trace($"ConnectionMultiplexerCreated: id={m_id}, log={log}");
```

Thanks,
Pavel

**Comment by mgravell** [comment]
My guess here is that there was a delayed operation in a race condition; suggested workaround:

``` c#
var log = new StringWriter();
ConnectionMultiplexer mux = ConnectionMultiplexer.Connect(configurationOptions, log);
string logText;
lock (log) { logText = log.ToString(); }
Trace($"ConnectionMultiplexerCreated: id={m_id}, log={logText}");
```

**Comment by paveliak** [comment]
Thanks @mgravell although I am puzzled how locking on StringWriter object would help here because ConnectionMultiplexer locks on `LogSyncLock` (different) object when writing into "log".

**Comment by mgravell** [comment]
Oh, you're right - my bad; I incorrectly remembered what it locked on - I thought it locked on the log. So, er... yeah, that's a fun problem. Let me think on that.

**Comment by mgravell** [comment]
(for context: from distant memory, I suspect that at one point it *did* lock on the log instance, and then we hit a problem where someone else was *also* locking on the log instance, and ... well, bad things)

**Comment by mgravell** [comment]
I *think* what I'm going to have to do here is create a proxy to the log object, so that I can wipe it *once* (inside the lock etc) before leaving `Connect`/`ConnectAsync`, and then immediately: any future attempts to write to the log will fail. That's my plan, anyways!

**Comment by paveliak** [comment]
Sounds good. Meanwhile I will wrap ToString() with try/catch.
