### ISSUE TITLE
Subscriber unsubscribes after subscribing on reconnect

### ISSUE THREAD

**Issue by shellicar** [StackExchange/StackExchange.Redis#1110]
## Issue
Subscriber very occasionally unsubscribes after subscribing after the subscriber connection is restored from a hard disconnect (port being closed).
This seems to be related to issue: #273
But I can still reproduce this.

## Version
Reproduced with the following versions.
1.2.6
2.0.519
2.0.588

## Behaviour
using redis-monitor on the server, the following is observed.
```
1554338345.603361 [0 127.0.0.1:10441] "SUBSCRIBE" "__Booksleeve_MasterChanged"
1554338345.620982 [0 127.0.0.1:10441] "SUBSCRIBE" "Channel1"
1554338345.621008 [0 127.0.0.1:10441] "SUBSCRIBE" "Channel2"
1554338345.629399 [0 127.0.0.1:10441] "UNSUBSCRIBE" "Channel1"
1554338345.629421 [0 127.0.0.1:10441] "UNSUBSCRIBE" "Channel2"
```

## Expected/Normal Behaviour
```
1554338954.604720 [0 127.0.0.1:11370] "SUBSCRIBE" "__Booksleeve_MasterChanged"
1554338954.609184 [0 127.0.0.1:11370] "UNSUBSCRIBE" "Channel1"
1554338954.609228 [0 127.0.0.1:11370] "UNSUBSCRIBE" "Channel2"
1554338954.609439 [0 127.0.0.1:11370] "SUBSCRIBE" "Channel1"
1554338954.609456 [0 127.0.0.1:11370] "SUBSCRIBE" "Channel2"
```
OR
```
1554338956.418663 [0 127.0.0.1:11372] "SUBSCRIBE" "__Booksleeve_MasterChanged"
1554338956.419116 [0 127.0.0.1:11372] "SUBSCRIBE" "Channel1"
1554338956.419133 [0 127.0.0.1:11372] "SUBSCRIBE" "Channel2"
```

**Comment by shellicar** [comment]
Any information on this?
I should add that the internal subscribers dictionary still thinks its subscribed.

This makes the library unusable for us as the subscriptions are unreliable.

**Comment by mgravell** [comment]
I haven't had chance to look (all support here comes from our personal
time, etc), but I agree it looks incorrect. My suspicion is that it
*thinks* it is unsubscribing from the old primary - most likely what I need
to do here is track the endpoint currently subscribed, and make sure we
include that in all routing decisions.

**Comment by shellicar** [comment]
No problem, I appreciate any work done in peoples personal time.

I would have thought it was an error with how the events were invoked/queued, as they are correct, just occur out of order.

**Comment by NickCraver** [comment]
@mgravell interesting race to note as we dig on this area - tagging for #1912

**Comment by NickCraver** [comment]
This is drastically improved in #1947 and will be in the 2.5 release - thank you for the detail!
