### ISSUE TITLE
HashValues

### ISSUE THREAD

**Issue by VitorCioletti** [StackExchange/StackExchange.Redis#1123]
Does the library offer me something like this? (I have not found anything similar in the official documentation) 

````
db.HashValues<MyType>(myKey)
````

I mean, do I really need to get my values through an `RedisValue[]` index?
I am facing a problem where values of my hash are not in a defined order, so get them by index does not work properly. I do not want to call `db.HashKeys(myKey)` to get how they are organized.

If there is no way to perform what I would like, why is not implemented?

Thanks in advance.

:)

**Comment by mgravell** [comment]
You probably want:

``` c#
var hash = db.HashGetAll(myKey).ToDictionary();
```

which will give you a `Dictionary<RedisValue, RedisValue>` that is keyed by hash field name. There is also a `ToStringDictionary()` that gives a `Dictionary<string,string>`, or you can use regular LINQ to do anything else more exotic.

If I'm missing the point: please let me know how you want to access them, and I'll probably be able to advise more.

**Comment by VitorCioletti** [comment]
Thanks, it helps. :D
