### ISSUE TITLE
StackExchange.Redis.RedisServerException 

### ISSUE THREAD

**Issue by Parth6288** [StackExchange/StackExchange.Redis#1127]
HI,
Off recently we are seeing multiple redis server exception from our web servers (around 5000 errors in span of 30 mins)  mainly the below one:

> Endpoint   10.10.52.42:6379 serving hashslot 11317 is not reachable at this point of   time. Please check connectTimeout value. If it is low, try increasing it to   give the ConnectionMultiplexer a chance to recover from the network   disconnect.  IOCP:   (Busy=0,Free=4000,Min=400,Max=4000), WORKER:   (Busy=200,Free=3800,Min=400,Max=4000), Local-CPU: n/a

This happened in 2 of our servers recently in a weeks time and we have to manual failover to get it working both the times.

Redis server v=3.2.0 sha=00000000:0 malloc=libc bits=64 build=a692e7130236b69d
Client version : Redis.StrongName : 1.2.6

**Comment by mgravell** [comment]
There are a number of known connection stability issues in the 1.* network code, enough that the network core needed a massive overhaul - one of many reasons that 2.* exists. If possible, then: try 2.* and see if the issue still exists.

The 2.* overhaul cannot viably be backported to 1.*.

**Comment by Parth6288** [comment]
@mgravell We are using Redis for AspNet sessions using Microsoft.Web.Redis.RedisSessionStateProvider (v2.2.6.344) which internally uses StackExchange.Redis.StrongName (v1.2.6) library. We are already using latest version.

**Comment by mgravell** [comment]
Understood. We can't control how/if/when upstream intermediary libraries update to v2.

**Comment by NickCraver** [comment]
@Parth6288 the newer version of Microsoft.Web.Redis.RedisSessionStateProvider (4.0.1) uses StackExchange.Redis 2.x, and you can safely use our very latest with it.

**Comment by Parth6288** [comment]
Will ask developers to check this out. Btw we are now seeing below error:
UnableToConnect on TELXREDIS01:6379/Interactive, origin: ResetNonConnected, input-buffer: 0, outstanding: 0, last-read: 5s ago, last-write: 5s ago, unanswered-write: 34110s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 6s ago, mgr: ExecuteSelect, err: never

SocketFailure on TELXREDIS07:6379/Interactive, origin: CheckForStaleConnection, input-buffer: 0, outstanding: 4, last-read: 48s ago, last-write: 0s ago, unanswered-write: 1s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: RecordConnectionFailed_ReportFailure, err: never
 We are unsure what is causing this..
