### ISSUE TITLE
Timeout performing SET error 

### ISSUE THREAD

**Issue by MehranMazhar** [StackExchange/StackExchange.Redis#1129]
Timeout performing SET *key* (1000ms), inst: 0, qu: 0, qs: 0, in: 0, serverEndpoint: ip:6379, mgr: 10 of 10 available, clientName: IS-77602, IOCP: (Busy=7,Free=993,Min=40,Max=1000), WORKER: (Busy=26,Free=32741,Min=40,Max=32767), v: 2.0.571.20511 (Please take a look at this article for some common client-side issues that can cause timeouts

How can I fix this?
Thank you.

**Comment by mgravell** [comment]
This sounds like the bug fixed in 588 (see https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes). I would recommend updating to latest, ideally 601.
