### ISSUE TITLE
Single big request vs multiple smaller ones

### ISSUE THREAD

**Issue by paveliak** [StackExchange/StackExchange.Redis#1131]
Hi

Suppose I need to set multiple keys such that overall amount of data transmitted in a single Redis command would be over 10Mb (we are talking about ~10,000 keys with 1Kb average key size). What would be the right way of doing it to have best performance but at the same time not abusing the library?

1) Send everything in one command (which would result in one huge MSET)
2) Pipeline individual "set" commands (one for each key)
3) Pipeline several smaller MSETs (making sure that each batch is <=1Mb or whatever threshold) 

No 1 would probably be fastest but has a risk of hogging the connection and timing out the concurrent commands.

No 2 seems to be more friendly to the concurrent commands but it's not clear if a storm of smaller commands is better then a single uber command assuming that we do not inject "pauses" between the individual commands (which would be a performance killer).

No 3 seems like a good tradeoff but might not be worth the complexity.

Picking this or that feels like performance vs scalability tradeoff and perhaps I better have two connections for smaller and larger payloads using approach No 1 and No 2 respectively.

What do you think?

Thanks,
Pavel

**Comment by mgravell** [comment]
Ultimately it is a choice between 2 and 3 - you're right about 1 potentially causing problems. 3 probably minimises overhead, but you could use the code from https://github.com/StackExchange/StackExchange.Redis/issues/1089 and just experiment and run your own comparisons?

**Comment by paveliak** [comment]
We implemented approach #3 with 256Kb threshold. Works like a charm.

Thanks for your help.
