### ISSUE TITLE
HashSetAsync --> When.Always --> return false except for the first call

### ISSUE THREAD

**Issue by ScorpioReloaded** [StackExchange/StackExchange.Redis#1133]
HashSetAsync --> When.Always --> return false except for the first call

db.HashSetAsync(DUMMY_KEY, DUMMY_KEY, DUMMY_VALUE, When.Always, CommandFlags.None).Result;

**Comment by NickCraver** [comment]
This is the expected behavior of `HSET` (the Redis command being called: https://redis.io/commands/hset). Note that the `n` or `0` is *the number of fields added*, not the number modified. If you overwrite the same key with the same value or another one, it'll be zero, indicating a field was not *added* to the hash. I've added a test to illustrate it in c7cb6df94d09cd6ea78194aa7f90f217d0736449 in hopes it helps!

**Comment by MaDeRkAn** [comment]
Task<bool> HashSetAsync<T>(
      string hashKey,
      string key,
      T value,
      bool nx = false,
      CommandFlags flag = CommandFlags.None); The signature of the method is that why it's boolean then ? Don't return anything and throw exception on error than.

**Comment by MaDeRkAn** [comment]
> This is the expected behavior of `HSET` (the Redis command being called: https://redis.io/commands/hset). Note that the `n` or `0` is _the number of fields added_, not the number modified. If you overwrite the same key with the same value or another one, it'll be zero, indicating a field was not _added_ to the hash. I've added a test to illustrate it in [c7cb6df](https://github.com/StackExchange/StackExchange.Redis/commit/c7cb6df94d09cd6ea78194aa7f90f217d0736449) in hopes it helps!

```
Task<bool> HashSetAsync<T>(
      string hashKey,
      string key,
      T value,
      bool nx = false,
      CommandFlags flag = CommandFlags.None)
```
This is the signature of the method. Why there is boolean ? Put integer there then.

**Comment by mgravell** [comment]
The number there applies to the varadic case; this is the non-varadic API of the same, which can thus return either `0` or `1`. Which we can represent here as `bool`

**Comment by MaDeRkAn** [comment]
> The number there applies to the varadic case; this is the non-varadic API of the same, which can thus return either `0` or `1`. Which we can represent here as `bool`

So do you mean client will understand your represantation by looking return value and then re represent boolean as integer ? Sorry, but I am not that smart.

**Comment by mgravell** [comment]
To rephrase: this API only allows us to send a single value pair, so the returned value can *only* be `0` or `1`. The client library will interpret `0` as `false`, and `1` as `true` (if the server reports an error, the library will throw an exception)

**Comment by JustDre** [comment]
Is there any way to tell if the API *failed*, other than to make another request for the value?
