### ISSUE TITLE
release notes missing for 2.0.601?

### ISSUE THREAD

**Issue by WeihanLi** [StackExchange/StackExchange.Redis#1136]
ReleaseNotes missing for 2.0.601?Can not find the release note for 2.0.601

**Comment by kierenj** [comment]
It looks to be just this commit, by the way: https://github.com/StackExchange/StackExchange.Redis/commit/4a0d3538da09fc1ddba120efaaefd5787533a1e0

**Comment by WeihanLi** [comment]
yeah, thanks @kierenj , I'm wondering that it should append to the release note

**Comment by mgravell** [comment]
it should indeed be update, and will be - when I get a moment

**Comment by NickCraver** [comment]
Release notes and tags are added for v2.0.601, thanks for the poke!
