### ISSUE TITLE
Migrating from StackExchangeRedisCacheClient to RedisCacheClient?

### ISSUE THREAD

**Issue by ffMathy** [StackExchange/StackExchange.Redis#1137]
`StackExchangeRedisCacheClient` is obsolete, so I am trying to migrate it to `RedisCacheClient`. However, we are currently creating a `StackExchangeRedisCacheClient` from a `ConnectionMultiplexer` instance, and there seems to be no constructor arguments for `RedisCacheClient` to do the same.

Essentially I just want to be able to get a `RedisCacheClient` object from a connection string.

I couldn't find anything about it in the documentation.

**Comment by mgravell** [comment]
k; what/where are `StackExchangeRedisCacheClient` and `RedisCacheClient`? they don't sound like part of this library, so I want to be absolutely clear on where they are defined before I try and jump in.
