### ISSUE TITLE
Timeout again for StackExchange.Redis in 2.0.601.3402 when at low/reasonable (but concurrent) load

### ISSUE THREAD

**Issue by cjt321** [StackExchange/StackExchange.Redis#1138]
In the last month, our version was 2.0.571, and timeout errors were often found.After checking, we have upgraded to the latest 2.0.601.But sometimes there are timeout errors.But there are fewer errors than in the previous version.
We found timeout bug fix in version 588: https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes.

Here is the detail:
Timeout awaiting response (outbound=1KiB, inbound=0KiB, 5563ms elapsed, timeout is 5000ms), command=SETEX, next: SETEX ssoauth:otherwechatuser:xxx:Mp:xxx, inst: 0, qu: 0, qs: 7, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/xxx.cloudapp.cloudapi.cn:6980, mgr: 10 of 10 available, clientName: 172_17_0_6, IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=1,Free=32766,Min=200,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

Any Help?

**Comment by vreboton** [comment]
Gcgug 
 

Sent from my iPhone

> On 5 May 2019, at 9:14 AM, alun_public <notifications@github.com> wrote:
> 
> In the last month, our version was 2.0.571, and timeout errors were often found.After checking, we have upgraded to the latest 2.0.601.But sometimes there are timeout errors.But there are fewer errors than in the previous version.
> We found timeout bug fix in version 588: https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes.
> 
> Here is the detail:
> Timeout awaiting response (outbound=1KiB, inbound=0KiB, 5563ms elapsed, timeout is 5000ms), command=SETEX, next: SETEX ssoauth:otherwechatuser:xxx:Mp:xxx, inst: 0, qu: 0, qs: 7, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/xxx.cloudapp.cloudapi.cn:6980,
> 
 W
I bet

**Comment by cjt321** [comment]
> Gcgug
> Sent from my iPhone
> On 5 May 2019, at 9:14 AM, alun_public ***@***.***> wrote: In the last month, our version was 2.0.571, and timeout errors were often found.After checking, we have upgraded to the latest 2.0.601.But sometimes there are timeout errors.But there are fewer errors than in the previous version. We found timeout bug fix in version 588: https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes. Here is the detail: Timeout awaiting response (outbound=1KiB, inbound=0KiB, 5563ms elapsed, timeout is 5000ms), command=SETEX, next: SETEX ssoauth:otherwechatuser:xxx:Mp:xxx, inst: 0, qu: 0, qs: 7, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/xxx.cloudapp.cloudapi.cn:6980,
> W I bet
> […](#)
> mgr: 10 of 10 available, clientName: 172_17_0_6, IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=1,Free=32766,Min=200,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) Any Help? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Hello vreboton, GC BUG? You say that is .net Core Bug? I use .net core 2.1.

**Comment by cjt321** [comment]
> Gcgug
> Sent from my iPhone
> On 5 May 2019, at 9:14 AM, alun_public ***@***.***> wrote: In the last month, our version was 2.0.571, and timeout errors were often found.After checking, we have upgraded to the latest 2.0.601.But sometimes there are timeout errors.But there are fewer errors than in the previous version. We found timeout bug fix in version 588: https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes. Here is the detail: Timeout awaiting response (outbound=1KiB, inbound=0KiB, 5563ms elapsed, timeout is 5000ms), command=SETEX, next: SETEX ssoauth:otherwechatuser:xxx:Mp:xxx, inst: 0, qu: 0, qs: 7, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/xxx.cloudapp.cloudapi.cn:6980,
> W I bet
> […](#)
> mgr: 10 of 10 available, clientName: 172_17_0_6, IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=1,Free=32766,Min=200,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) Any Help? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

And how can i mute the thread? The underlying mechanism is stackexchange.redis

**Comment by mgravell** [comment]
Looking at this, you have:

>  inst: 0, qu: 0, qs: 7, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0

That means that data has been sent to the server, and nothing has come back (`in: 0` means there's nothing on the socket, and `in-pipe: 0` means there's nothing in the read-buffer between the socket layer and the protocol parser). There's literally nothing the code can do here other than time out.

I would suggest investigating either a server or network stall, or: if this is expected latency (cloud / remote server): increase the timeout.

**Comment by cjt321** [comment]
> Looking at this, you have:
> 
> > inst: 0, qu: 0, qs: 7, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0
> 
> That means that data has been sent to the server (7 messages worth - the next of which being `SETEX`), and nothing has come back (`in: 0` means there's nothing on the socket, and `in-pipe: 0` means there's nothing in the read-buffer between the socket layer and the protocol parser). There's literally nothing the code can do here other than time out.
> 
> I would suggest investigating either a server or network stall, or: if this is expected latency (cloud / remote server): increase the timeout. I don't know how big your `ssoauth:otherwechatuser:xxx:Mp:xxx` key is that you're assigning, but if it is _biiiig_, this could also be simply a bandwidth problem, i.e. you're sending a 200MB payload down a narrow pipe, and it is taking a while. The `out-pipe: 0` tells me that it has all gone to the outbound socket layer, at least.

Thanks for the reply. 
ssoauth:otherwechatuser:xxx:Mp:xxx  no more than 100 characters. And redis values is 420 bytes. 
We used azure vm to build our own redis.  Does Azure vm disconnects actively may have this problem?
AS you say 'The out-pipe: 0 tells me that it has all gone to the outbound socket layer, at least.'. Sorry, I don't quite understand what it means.

**Comment by mgravell** [comment]
>  you say 'The out-pipe: 0 tells me that it has all gone to the outbound socket layer, at least.'. Sorry, I don't quite understand what it means.

basically, we use the "pipelines" API when reading and writing - I'm simply noting that there isn't a backlog of data in the "pipelines" layer that hasn't yet been sent to the socket.

Yes, a socket disconnect could be a cause here; it is notoriously hard to spot all disconnects without an  active probe, which is why we issue a heartbeat `PING` periodically (if nothing else is happening). And yes, socket disconnects are more common with cloud providers.

**Comment by cjt321** [comment]
> > you say 'The out-pipe: 0 tells me that it has all gone to the outbound socket layer, at least.'. Sorry, I don't quite understand what it means.
> 
> basically, we use the "pipelines" API when reading and writing - I'm simply noting that there isn't a backlog of data in the "pipelines" layer that hasn't yet been sent to the socket.
> 
> Yes, a socket disconnect could be a cause here; it is notoriously hard to spot all disconnects without an active probe, which is why we issue a heartbeat `PING` periodically (if nothing else is happening). And yes, socket disconnects are more common with cloud providers.

Thanks, we will check it. And close this issues.
