### ISSUE TITLE
About HashSet

### ISSUE THREAD

**Issue by BillCoding** [StackExchange/StackExchange.Redis#1139]
Why did the string data I inserted become binary data?

**Comment by BillCoding** [comment]
This picture is my own operation
![2](https://user-images.githubusercontent.com/21271780/57518049-c5834780-734a-11e9-8b31-d19cf57e38e2.png)

This picture was used by StackExchange.Redis
![2](https://user-images.githubusercontent.com/21271780/57518173-0b401000-734b-11e9-9ae9-ade40d2b5c7e.png)

**Comment by BillCoding** [comment]
aaaa

**Comment by mgravell** [comment]
Let me know if you have any remaining doubts here.
