### ISSUE TITLE
RedisConnectionException: No connection is available to service this operation: GET

### ISSUE THREAD

**Issue by siimv** [StackExchange/StackExchange.Redis#1140]
I just upgraded some of our services to V2 because of the frequent timeout problems in V1 that affected us (in a client with very heavy load).

My setup is following:
One VM which host two independent services - *Service A* and *Service B*. Both of them use redis on *redis_host*, but they use different databases (1 and 2 for example). And somehow the connection on *Service A* receives some kind of response which is meant for *Service B*.
Both of them are .NET 4.6.1 WebApi services. Redis server is on version 5.0.4

I use only synchronous access, ConnectionMultiplexer is configured as singleton and IDatabase is configured as transient (in both services).

Error I get:
```
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: GET <service_a_key>; Received response with no message waiting: SimpleString: 1557487110.334361 [9 10.200.227.16:49904] "SETEX" "<service_b_key>" "300" "<service_b_key>"; IOCP: (Busy=1,Free=999,Min=200,Max=1000), WORKER: (Busy=0,Free=32767,Min=2,Max=32767), Local-CPU: n/a ---> StackExchange.Redis.RedisConnectionException: InternalFailure (None, last-recv: 2120) on <redis_host>/Interactive, Idle/Faulted, last: UNKNOWN, origin: ReadFromPipe, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, in: 0, in-pipe: 2120, out-pipe: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.0.601.3402 ---> System.InvalidOperationException: Received response with no message waiting: SimpleString: 1557487110.334361 [9 10.200.227.16:49904] "SETEX" "<service_b_key>" "300" "<service_b_response>"
   at StackExchange.Redis.PhysicalConnection.MatchResult(RawResult& result)
   at StackExchange.Redis.PhysicalConnection.ProcessBuffer(ReadOnlySequence`1& buffer)
   at StackExchange.Redis.PhysicalConnection.<ReadFromPipe>d__110.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)
```

And I'm not sure what it means. I request key **service_a_key** from redis, for some reason it cannot fetch it and it shows totally unrelated operation response **service_b_response** for key **service_b_key** - which is related to different application and different DB index.

Is there some issue with the physical connection so it wants to share it (even between application)? Or is it affected somehow by some redis server configuration?

**Comment by mgravell** [comment]
The key part in here is:

> Received response with no message waiting

Now the question is ... how did we get that? I genuinely have no clue without looking - AFAIK we enqueue the response token *before* we write the request (in case the reply is super fast). I will have to think about ways we could achieve this.

**Comment by NickCraver** [comment]
Was this in a cloud scenario? Several providers we've found are doing failovers behind the scenes which combined with a bug being resolved in #1374 (details in #1120) caused a persistent failure. The momentary failure is expected since the connection _is_ severed, but not the lingering.

**Comment by jananiva** [comment]
I tried to repro the issue discussed [here](https://github.com/StackExchange/StackExchange.Redis/pull/1374) using a console app that constantly reads and writes to REDIS. I killed the client connection when this console app was running. Tried this with both v2.0.601 and v2.1.30.

In both versions, I see that as soon as I kill the connection, there's a bunch of "No connection is active/available to service this operation".

How do I effectively repro the bug in v2.0.601 and the fix in v2.1.30?

**Comment by siimv** [comment]
> Was this in a cloud scenario? Several providers we've found are doing failovers behind the scenes which combined with a bug being resolved in #1374 (details in #1120) caused a persistent failure. The momentary failure is expected since the connection _is_ severed, but not the lingering.

Not a cloud scenario, meaning that we don't use any managed redis service and don't have any primary/secondary setups, currently.

**Comment by thelgevold** [comment]
I am seeing this issue intermittently as well. 

In my case I am running in K8 with a redis cluster where I have 1 primary + 2 secondary replication nodes.

The interesting part is that it seems to recover on its own, but it happens periodically.

**Comment by thelgevold** [comment]
@NickCraver To follow up on your comment above. In my case I am running in K8 using the helm chart `redis-ha` with 3 pods in the cluster (1 primary and 2 secondaries).

You said in your comment above that momentary failure is expected. My failures are kind of random, but I have noticed that it can often happen right after a new deployment of the asp.net core app connected to the cluster. It's pretty unpredictable though so it's hard to find a clear pattern.

Not sure if it helps, but my issue seems to only happen on writes. Specifically this particular write:

``` await connectionMultiplexer.GetDatabase().StringSetAsync("my-key", "val", lockTimeout, When.NotExists)```

Are you suggesting we use some sort of re-connect strategy to deal with expected momentary failure?

At this point it's a bit unclear to me if this is an issue with StackExchange.Redis or a more fundamental issue with how my Redis cluster is configured. 

Seems like this bug is a dup: https://github.com/StackExchange/StackExchange.Redis/issues/1140

**Comment by thelgevold** [comment]
Update:
I have made two small updates and it seems to have helped fix this issue on my end.

Changes:
1) Change connection to use a sentinel connection since my cluster is sentinel enabled
2) Upgrade StackExchange.Redis from v2.1.30 to v2.1.58

Still testing, but have not seen this error in 24 hours now. Before making these changes the error occurred very frequently.

**Comment by thelgevold** [comment]
Update:
I have made two changes and it seems to have helped fix this issue on my end.

Changes:
1) Change connection to use a sentinel connection since my cluster is sentinel enabled
2) Upgrade StackExchange.Redis from v2.1.30 to v2.1.58

Still testing, but have not seen this error in 24 hours now. Before making these changes the error occurred very frequently.

**Comment by siimv** [comment]
In version 2.1.58 I still see similar error time to time:

```
StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: GET cookie-session:sso:ab7fb98f-5e16-4291-89ef-cdbf02eec141; Received response with no message waiting: SimpleString: 1605740070.441557 [0 <ip>:<port>] "SELECT" "17", mc: 1/1/0, mgr: 10 of 10 available, clientName: <name>, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767), v: 2.1.58.34321
 ---> StackExchange.Redis.RedisConnectionException: InternalFailure (None, last-recv: 57) on <ip>:<port>/Interactive, Idle/Faulted, last: UNKNOWN, origin: ReadFromPipe, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, in: 0, in-pipe: 57, out-pipe: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.1.58.34321
 ---> System.InvalidOperationException: Received response with no message waiting: SimpleString: 1605740070.441557 [0 <ip>:<port>] "SELECT" "17"
   at StackExchange.Redis.PhysicalConnection.MatchResult(RawResult& result) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1428
   at StackExchange.Redis.PhysicalConnection.ProcessBuffer(ReadOnlySequence`1& buffer) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1555
   at StackExchange.Redis.PhysicalConnection.ReadFromPipe() in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1486
```

And I have no clue what could cause it. 
`SELECT 17` indicates database selection, but again, database 17 is for another application and the one which got the error, doesn't know nothing about it (but these applications run on the same server).

I don't know the internals of the Redis server and StackExchange.Redis, but can be there some TCP connection sharing (between applications on the same machine) or buggy/misconfigured Redis issue?

**Comment by NickCraver** [comment]
Missed this issue in closing after the Sentinel updates. For anyone hitting this, please grab the latest version of the client. There have been tons of improvements around Sentinel and no known lingering connection issues there. We appreciate everyone's help in tracking these down and improving them!
