### ISSUE TITLE
An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by emgrig** [StackExchange/StackExchange.Redis#1143]
` "System.AggregateException: One or more errors occurred. (Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.) ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)\r\n   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at StackExchange.Redis.PhysicalConnection.EndReading(Task`1 result) in c:\\code\\StackExchange.Redis\\StackExchange.Redis\\StackExchange\\Redis\\PhysicalConnection.cs:line 844\r\n---> (Inner Exception #0) System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)\r\n   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)<---\r\n",`

The error message is : 'SocketFailure on EVAL'.

**Comment by NickCraver** [comment]
This is expected when the connection is severed from the other end for whatever reason. Could be a network failure or a redis restart or...really anything in-between the client and server. In Azure for example, this can happen when a failover happens behind the scenes.

In general: this is expected when the network has an issue!

**Comment by emgrig** [comment]
That make sense. 
Thank you.
