### ISSUE TITLE
Timeout exceptions when using Synchronous API in a multi-threaded application

### ISSUE THREAD

**Issue by darcon77** [StackExchange/StackExchange.Redis#1144]
[Program.txt](https://github.com/StackExchange/StackExchange.Redis/files/3174519/Program.txt)

Attached please find a repro of the issues we're seeing with StackExchange.Redis v 2.x, however the issue is not present in 1.2.6;

Weird behavior when trying to access cache from multiple threads. If the above code is ran in debug mode, we see timeouts on all operations, no keys are added to cache. However if we run the same exact code without a debugger attached, the code seems to be working and adding keys to cache. As soon as i wrap the cache access methods in try/catch to see if the timeout exceptions are still present in non-debug mode, the code stops working and starts throwing more timeouts and nothing gets added to cache.

Could you please look into this?

Thank you

**Comment by darcon77** [comment]
Anyone stumbling upon this problem, it is only present if you use Azure Redis Cache. The redis version they are running is 3.x Tested the same exact code on my

**Comment by mgravell** [comment]
I had this on my queue to look at today, but you seem to have got somewhere. I'm kinda surprised that it behaves *particularly* different between azure / not, and I'd still be open to taking a look if you get ongoing problems.

**Comment by darcon77** [comment]
@mgravell Do you have any explanation about why would it work without debugger attached, but fail when debugging?

**Comment by mgravell** [comment]
I'm assuming you don't have anything like:

``` c#
#if DEBUG
    options.SyncTimeout *= 100; // in case we break-point
#endif
```

but other than that... no, and I'm very curious! maybe something to do with sync context perhaps? what kind of app is it? web? desktop? (ideally down to ".NET 4.5.2 WPF desktop app on Windows 10", for example)

**Comment by darcon77** [comment]
The attached repro is a console app. I stripped out the exact code from the production application that was having the issues. The production application is a Windows service, .NET 4.6.2 running on Windows Server 2012.
