### ISSUE TITLE
Timeout when server is executing long-running scripts via EVAL

### ISSUE THREAD

**Issue by Jerome2606** [StackExchange/StackExchange.Redis#1145]
Hello,

I upgraded this sunday my production environment to version 2.0.601.
But I see I still have issues with sometimes timeout like this:

> ERROR : EQL.Data.Redis.Common.RedisCacheClient - Timeout performing GET (5000ms), next: EVAL, inst: 0, qu: 0, qs: 5, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/srv-cah.xxx.com:6379, mgr: 10 of 10 available, clientName: SRV-XXX, IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=7,Free=32760,Min=100,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), next: EVAL, inst: 0, qu: 0, qs: 5, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/srv-cah.xxx.com:6379, mgr: 10 of 10 available, clientName: SRV-XXX, IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=7,Free=32760,Min=100,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2239
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 2281
   at EQL.Data.Redis.Common.RedisCacheClient.GetOrDefault(String key) in D:\TFS2018Agent2\_work\2\s\EQL\EQL.Data.Redis\Common\RedisCacheClient.cs:line 88
   at EQL.Data.Core.Caching.CacheClientBase.GetOrDefaultAsync(String key) in D:\TFS2018Agent2\_work\2\s\EQL\EQL.Data.Core\Caching\CacheClientBase.cs:line 166
   at EQL.Data.Core.Caching.CacheClientBase.<GetAsync>d__22.MoveNext() in D:\TFS2018Agent2\_work\2\s\EQL\EQL.Data.Core\Caching\CacheClientBase.cs:line 108

or this one (that make my CPU to 100%):

> ERROR : EQL.Data.Redis.Common.RedisCacheClient - Timeout performing GET (5000ms), next: EVAL, inst: 0, qu: 0, qs: 41, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/srv-cah.xxx.com:6379, mgr: 10 of 10 available, clientName: SRV-XXX, IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=48,Free=32719,Min=100,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), next: EVAL, inst: 0, qu: 0, qs: 41, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/srv-cah.xxx.com:6379, mgr: 10 of 10 available, clientName: SRV-XXX, IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=48,Free=32719,Min=100,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2239
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 2281
   at EQL.Data.Redis.Common.RedisCacheClient.GetOrDefault(String key) in D:\TFS2018Agent2\_work\2\s\EQL\EQL.Data.Redis\Common\RedisCacheClient.cs:line 88
   at EQL.Data.Core.Caching.CacheClientBase.GetOrDefaultAsync(String key) in D:\TFS2018Agent2\_work\2\s\EQL\EQL.Data.Core\Caching\CacheClientBase.cs:line 166
   at EQL.Data.Core.Caching.CacheClientBase.<GetAsync>d__22.MoveNext() in D:\TFS2018Agent2\_work\2\s\EQL\EQL.Data.Core\Caching\CacheClientBase.cs:line 108

And sometimes I have my Redis server CPU to 100%, in that case I need to restart the server.
I was hoping that upgrading to 2.0.601 get off my problems.

I don't know how to read the issue and how I can investigate in my code for this timeout and CPU 100%.
I will see to install more node of Redis server but there should be something wrong with the way I use Redis.

**Comment by mgravell** [comment]
The line:

> inst: 0, qu: 0, qs: 5, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0,

(combined with your 100% server CPU notes) tells me that this is most likely a server stall; that says "there are 5 messages that I've sent to the server that are awaiting replies, nothing is waiting to be sent, there's no data available on the socket, and no data buffered between the socket and protocol-parser layers" - or more tersely: "I'm waiting for the server". The thing at the front of the line (so to speak) is an `EVAL`, so *one* place to look would be to investigate an `ScriptEvaluate` to see what they're doing. However, it may be pragmatic to look at the server's ["slow log"](https://redis.io/commands/slowlog) (there is also an API for this in the library, IIRC).

Redis is normally very low CPU, so if you're seeing 100% CPU on the redis server (or even just 100% on a single core being used by redis), there's almost certainly a problem in how you're using the server. Can I ask what your `EVAL` code looks like? For example, the Lua script is doing things like `KEYS` or `SCAN`, then yeah... that'll pretty much break your server.

**Comment by mgravell** [comment]
Just to add an explicit point: if the problem is genuinely server-side (or network-based), the client can't stand a chance except via enlarging the timeout.

**Comment by Jerome2606** [comment]
My calls are pretty small so timeout is far larger than I'm expect.
Call was a StringGet with this urn: urn:Entity:72584:lng/2

I'm using KEYS in part of my invalidation cache mechanism:

`database.ScriptEvaluate(@"
                local keys = redis.call('keys', ARGV[1]) 
                for i=1,#keys,5000 do 
                redis.call('del', unpack(keys, i, math.min(i+4999, #keys)))
                end", values: new RedisValue[] { prefix });`

This code helps my to clean namespace when there is import or update on my cache objects.
prefix looks like: urn:Link:7785:*

**Comment by Jerome2606** [comment]
Here is the slowlog get 5 result:

> 
1) 1) (integer) 3482
   2) (integer) 1557823621
   3) (integer) 607707
   4) 1) "EVAL"
      2) "\r\n                local keys = redis.call('keys', ARGV[1]) \r\n                                                                                                                             for i=1,#keys,5000 do \r\n                redis.call(... (69 more byt                                                                                                             es)"
      3) "0"
      4) "urn:User:UserRoles:*"
   5) "10.X.X.X:50740"
   6) "SRV-XXX"
2) 1) (integer) 3481
   2) (integer) 1557823621
   3) (integer) 607606
   4) 1) "keys"
      2) "urn:User:UserRoles:*"
   5) "?:0"
   6) ""
3) 1) (integer) 3480
   2) (integer) 1557823620
   3) (integer) 632264
   4) 1) "EVALSHA"
      2) "6e2b0b542b385f3da4fe80fa70cbba2c469cc3b3"
      3) "0"
      4) "urn:User:UserRoles:*"
   5) "10.X.X.X:50740"
   6) "SRV-XXX"
4) 1) (integer) 3479
   2) (integer) 1557823620
   3) (integer) 631826
   4) 1) "keys"
      2) "urn:User:UserRoles:*"
   5) "?:0"
   6) ""
5) 1) (integer) 3478
   2) (integer) 1557823619
   3) (integer) 659752
   4) 1) "EVALSHA"
      2) "fea3235e8ce23bcab0e0ad87c68f38d7b03cda64"
      3) "0"
      4) "urn:User:UserIdentity:*"
   5) "10.X.X.X:50740"
   6) "SRV-XXX"

**Comment by mgravell** [comment]
> I'm using KEYS in part of my invalidation cache mechanism:

called it!

>  For example, if the Lua script is doing things like KEYS or SCAN, then yeah... that'll pretty much break your server.

Basically, all I can say is "don't do that, that's a very bad idea, and redis isn't designed to do that". It *looks* like each of those is taking nearly a second, so *actually* you're getting off relatively lightly here - it could have been much much worse - but I strongly suggest finding a new way of doing that.

From a **cursory glance**, it looks like you have a pattern of strings that all need to die at once; there are two common solutions for this that *do not* involve crawling the keyspace:

1. move from n `string` to a single `hash` with n key/value pairs, i.e. `hset` - then just delete the entire key as a single operation
2. when adding the n key/values (in whatever form), also add the key to a `set` that describes that group, i.e. `sadd` - then when you need to remove everything, you can enumerate that set - which will always be more efficient that walking the keyspace

**Comment by mgravell** [comment]
Renamed for clarity, although I should emphasize that in this scenario the scripts are in conjunction, i.e. it is a `GET` (or whatever) that is failing because it is blocked *behind* an `EVAL`, which could be on the same connection or a different connection.

**Comment by Jerome2606** [comment]
I changed my code to use:

```

            foreach (var key in server.Keys(pattern: prefix, pageSize: 250, database: database.Database))
            {
                database.KeyDelete(key);
            }
```

I will think about your second solution, Keep a trace of existing keys in a particular set.
With the code above, I don't have trace in slowlog.

How can I use sadd in StackExchange.Redis ?

**Comment by mgravell** [comment]
Nice; I should call out that this is less "atomic", but I don't think you can avoid that in the current implementation without burning the server. There is also a varadic `KeyDelete` that you might find useful.

Re `sadd`: that is `.SetAdd(...)`

**Comment by Jerome2606** [comment]
Just to be sure, my StringSet will look like this:

```

        public override void Set(string key, object value, TimeSpan? slidingExpireTime = null, TimeSpan? absoluteExpireTime = null)
        {
            if (value == null) return; 

            _database.StringSet(
                GetLocalizedKey(key),
                _serializer.Serialize(value, value.GetType()),
                absoluteExpireTime ?? slidingExpireTime ?? DefaultAbsoluteExpireTime ?? DefaultSlidingExpireTime,
                When.Always,
                CommandFlags.FireAndForget
            );

            _database.SetAdd("urn:allkeyset", GetLocalizedKey(key));
        }
```

The set add will allow me to get a list of key to delete, and then I will use:

KeyDelete({list of key from urn:basekeyset})

right ?

**Comment by mgravell** [comment]
Exactly, yes, via either `SetScan` (`sscan`) or `SetMembers` (`smembers`), you can get a set of keys to dump.

**Comment by Jerome2606** [comment]
After updating my production environment this night I now have two new kind of exception:

> ERROR : EQL.Data.Redis.Common.RedisCacheClient - The timeout was reached before the message could be written to the output buffer, and it was not sent, command=GET, timeout: 5000, outbound: 641573KiB, inbound: 5074KiB, inst: 28654, qu: 539665, qs: 0, aw: True, bw: RecordingTimeout, rs: ReadAsync, ws: Flushed, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/srv-cah.xxx.com:6379, mgr: 9 of 10 available, clientName: SRV-XXX, IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=18,Free=32749,Min=100,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
StackExchange.Redis.RedisTimeoutException: The timeout was reached before the message could be written to the output buffer, and it was not sent, command=GET, timeout: 5000, outbound: 641573KiB, inbound: 5074KiB, inst: 28654, qu: 539665, qs: 0, aw: True, bw: RecordingTimeout, rs: ReadAsync, ws: Flushed, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/srv-cah.xxx.com:6379, mgr: 9 of 10 available, clientName: SRV-XXX, IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=18,Free=32749,Min=100,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EQL.Data.Redis.Common.RedisCacheClient.<GetOrDefaultAsync>d__7.MoveNext() in D:\TFS2018Agent2\_work\2\s\EQL\EQL.Data.Redis\Common\RedisCacheClient.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EQL.Data.Core.Caching.CacheClientBase.<GetAsync>d__22.MoveNext() in D:\TFS2018Agent2\_work\2\s\EQL\EQL.Data.Core\Caching\CacheClientBase.cs:line 108

And:

> ERROR : EQL.Data.Redis.Common.RedisCacheClient - Timeout awaiting response (outbound=0KiB, inbound=3KiB, 6812ms elapsed, timeout is 5000ms), command=GET, next: SETEX urn:Entity:541448965000998594, inst: 0, qu: 0, qs: 4, aw: False, rs: DequeueResult, ws: Idle, in: 0, in-pipe: 6883, out-pipe: 121, serverEndpoint: Unspecified/srv-cah.xxx.com:6379, mgr: 7 of 10 available, clientName: SRV-XXX, IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=25,Free=32742,Min=100,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=3KiB, 6812ms elapsed, timeout is 5000ms), command=GET, next: SETEX urn:Entity:541448965000998594, inst: 0, qu: 0, qs: 4, aw: False, rs: DequeueResult, ws: Idle, in: 0, in-pipe: 6883, out-pipe: 121, serverEndpoint: Unspecified/srv-cah.xxx.com:6379, mgr: 7 of 10 available, clientName: SRV-XXX, IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=25,Free=32742,Min=100,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EQL.Data.Redis.Common.RedisCacheClient.<GetOrDefaultAsync>d__7.MoveNext() in D:\TFS2018Agent2\_work\2\s\EQL\EQL.Data.Redis\Common\RedisCacheClient.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EQL.Data.Core.Caching.CacheClientBase.<GetAsync>d__22.MoveNext() in D:\TFS2018Agent2\_work\2\s\EQL\EQL.Data.Core\Caching\CacheClientBase.cs:line 108

I don't think I was getting message like that before.
Any idea?

**Comment by mgravell** [comment]
The two look very different; the first is a half-million outbound requests that haven't been sent yet - it looks like you're absolutely flooding the outbound with requests; is this some kind of massively parallel (but non-awaited) write?

the second looks like a marginal trip - the reader is actively trying to dequeue the next response (a SETEX) at the same time that the GET is timing out; could be load based?

**Comment by Jerome2606** [comment]
1) This is due to the clearing of cache after a modification from the user -> I'm using the code above to clear the keys and there are 500k keys in this urn. One problem in my code is that it tries to clear the cache 3 times. But I definitively need to take the time to implement the solution you suggested

2) This error occured when my application pool was recycling. No more investigations from me for this error

for the 1) it seems the keyDelete with the code implemented is not ok with the amount of keys I have.
what I need to delete is the urn like : App:App.ClientName:Client1:urn:Property:*
Any easy and fast fix ?

**Comment by mgravell** [comment]
it sounds like you're doing something like:

``` c#
foreach (var key in db.SetScan(whatever)) {
    db.KeyDelete(key);
}
```

is that about right? I would suggest batching this a bit - for example, with the `Batchify` method below, the following should work (untested)?

``` c#
foreach (var batch in db.SetScan(whatever).Batchify()) {
    db.KeyDelete(batch);
}
```

?

extension method:

``` c#
    static IEnumerable<T[]> Batchify<T>(this IEnumerable<T> source, int count = 100)
    {
        var list = new List<T>(count);
        foreach (var item in source)
        {
            list.Add(item);
            if (list.Count == count)
            {
                var arr = list.ToArray();
                list.Clear();
                yield return arr;
            }
        }
        if (list.Count != 0) yield return list.ToArray();
    }
```

**Comment by Jerome2606** [comment]
I'm using this:

```
 foreach (var key in server.Keys(pattern: prefix, pageSize: 250, database: database.Database))
            {
                database.KeyDelete(key);
            }

I put the batch size to 250, behing the scene it's using SCAN
```

**Comment by mgravell** [comment]
What I was trying to reduce here was the number of `DEL` operations; the page-size on `Keys` won't impact that - please try:


``` c#
foreach (var keys in server.Keys(pattern: prefix, pageSize: 250, database: database.Database).Batchify()){
         database.KeyDelete(keys);
}
```

this collects matches until it has some amount (`100` by default) to issue a single `DEL` for multiple keys at once, to reduce the number of round-trips, however, and I must emphasize this: if you're trying to invalidate a half-million keys, it is ultimately going to be a **lot** of work under **any** approach. Sadly, what you're trying to do isn't something that fits naturally into how redis is designed to work. The reality is that `SCAN` and `KEYS` are not things that you're meant to use for your regular work; the only real sanctioned usage of those is for database analysis or migration tools - i.e. things that you use periodically to find out *about* your database.

If you're running multiple concurrent `SCAN` + `DEL` sweeps, your server is going to hurt, and I don't think there's much I can do to help with that from a client. You're simply *doing a ton of stuff that isn't cheap*.

**Comment by Jerome2606** [comment]
Ok thanks for your help, I will batchify the deletes by 100 keys.

I'm thinking how to reduce the amount of deletes while invalidating the cache.

**Comment by mgravell** [comment]
again, my strong suggestion here, if you're using `SET` (i.e. redis strings) is to switch to hashes and a single key `del` (or `unlink` on more recent servers)

**Comment by Jerome2606** [comment]
Can elaborate the solution because I don't get it plz ?
Replace StringGet by ?
Hashes means a regroup of keys ? 

Today after update I have big issues with slow cache

Slowlog display:

1) 1) (integer) 463
   2) (integer) 1557996671
   3) (integer) 14051
   4) 1) "scan"
      2) "1330559"
      3) "MATCH"
      4) "*"
      5) "COUNT"
      6) "10000"
   5) "10.0.30.139:53552"
   6) ""
2) 1) (integer) 462
   2) (integer) 1557996671
   3) (integer) 17495
   4) 1) "scan"
      2) "338367"
      3) "MATCH"
      4) "*"
      5) "COUNT"
      6) "10000"
   5) "10.0.30.139:53552"
   6) ""
3) 1) (integer) 461
   2) (integer) 1557996671
   3) (integer) 14278
   4) 1) "scan"
      2) "269887"
      3) "MATCH"
      4) "*"
      5) "COUNT"
      6) "10000"
   5) "10.0.30.139:53552"
   6) ""
4) 1) (integer) 460
   2) (integer) 1557996670
   3) (integer) 13753
   4) 1) "scan"
      2) "1620703"
      3) "MATCH"
      4) "*"
      5) "COUNT"
      6) "10000"
   5) "10.0.30.139:53552"
   6) ""
5) 1) (integer) 459
   2) (integer) 1557996670
   3) (integer) 14070
   4) 1) "scan"
      2) "2292831"
      3) "MATCH"
      4) "*"
      5) "COUNT"
      6) "10000"
   5) "10.0.30.139:53552"
   6) ""

My clear on urn:Entity:* takes seconds :(

**Comment by Jerome2606** [comment]
I think I get something more stable

Here is my Set:

```
var hashField = GetHashField(key); // Return urn:EntityHash for key urn:Entity:...
            if (!hashField.HasValue)
                await _database.StringSetAsync(
                    GetLocalizedKey(key),
                    _serializer.Serialize(value, value.GetType()),
                    absoluteExpireTime ?? slidingExpireTime ?? DefaultAbsoluteExpireTime ?? DefaultSlidingExpireTime,
                    When.Always,
                    CommandFlags.FireAndForget
                );
            else
                await _database.HashSetAsync(
                    GetLocalizedKey(hashField),
                    key,
                    _serializer.Serialize(value, value.GetType()),
                    When.Always,
                    CommandFlags.FireAndForget
                );
```

And my Clear is now:

```
if (IsHashField(namespaceToClear)) // can be called directly to remove the hash urn:EntityHash
            {
                _database.KeyDelete(GetLocalizedKey(namespaceToClear), CommandFlags.FireAndForget);
                return;
            }
            
            var hashField = GetHashField(namespaceToClear); // Return urn:EntityHash for key urn:Entity:...
            if (hashField.HasValue)
            {
                var keys = _database.HashScan(GetLocalizedKey(hashField), namespaceToClear, 1000);
                var redisKeys = keys.Select(k => k.Name).ToArray();
                _database.HashDelete(GetLocalizedKey(hashField), redisKeys, CommandFlags.FireAndForget);
            }
            else
            {
                _database.KeyDeleteWithPrefix(_server, GetLocalizedKey(namespaceToClear));
            }
```

HSCAN appears in slowlog but are less harmfull than KEYS or SCAN

For the 500K deletes, I remove the hash in one call

Thanks for your help
