### ISSUE TITLE
[Question] Problem Sending Large Commands to Redis for RedisGraph Module

### ISSUE THREAD

**Issue by tombatron** [StackExchange/StackExchange.Redis#1148]
Hey there!

While trying to mess around with the [RedisGraph](https://oss.redislabs.com/redisgraph/) module I encountered a 23 byte limit when trying to execute an admittedly large command using `ExecuteAsync`. 

```
RedisResult result;

using (var connectionMultiplexer = ConnectionMultiplexer.Connect("localhost"))
{
    var database = connectionMultiplexer.GetDatabase();

    var query = "GRAPH.QUERY MotoGP \"CREATE (:Rider {name:'Valentino Rossi'})-[:rides]->(:Team {name:'Yamaha'}), (:Rider {name:'Dani Pedrosa'})-[:rides]->(:Team {name:'Honda'}), (:Rider {name:'Andrea Dovizioso'})-[:rides]->(:Team {name:'Ducati'})\"";

    result = await database.ExecuteAsync(query);
}
```

My question is, is there another recommended way to send comically large commands to Redis?

Thanks,

Tom

**Comment by mgravell** [comment]
The *command* here is just `GRAPH.QUERY`, with the parameters sent separately. There is a `params object[] args` for this purpose. Note that anything that is classed as a *key* should be sent as `RedisKey` values, to ensure routing works correctly, especially on "cluster".

**Comment by mgravell** [comment]
I think this means, in your case:

``` c#
result = await database.ExecuteAsync("GRAPH.QUERY",
    (RedisKey)"MotoGP", "CREATE...");
```

so, one command with two arguments, the first of which is a key.

**Comment by tombatron** [comment]
Welp I feel a bit foolish. 

In any case, thank you for your assistance!

**Comment by mgravell** [comment]
No problem. If you hit any more stumbling blocks, please let us know. If
anything, it means we're not making the API obvious enough
