### ISSUE TITLE
Adding community package redis-roaring

### ISSUE THREAD

**Issue by nhaberl** [StackExchange/StackExchange.Redis#1153]
What's the easiest way to add community package to the client ?
[https://github.com/aviggiano/redis-roaring](https://github.com/aviggiano/redis-roaring)

Any guide for this or extension points ?

**Comment by mgravell** [comment]
Depending on the complexity, either:

- (simple scenarios) write a package that adds C# extension methods to IDatabase[Async], using Execute[Async] to call the underlying redis method
- (complex scenarios) write a package that wraps one or more of the redis objects in your own client abstraction

That work?

**Comment by mgravell** [comment]
Example of the latter: NRediSearch, although it also shows how to use Execute[Async], of course

**Comment by nhaberl** [comment]
Nice, I will give it a shot.
Sorry for delay!

**Comment by NickCraver** [comment]
Closing out to cleanup, thanks!
