### ISSUE TITLE
Unable to determine Batch execution result

### ISSUE THREAD

**Issue by sabujsen** [StackExchange/StackExchange.Redis#1157]
I have used this Code to import a big data set into Redis DB, It working fine. But the issue is that we can not track the all keys are successfully pushed into redis or not, basically  we can not track any missed hit if happened. Any one have any idea how track it or how get a confirmation that all keys are successfully created in redis. 

``` c#
IBatch batch = redisDB.CreateBatch();
List<Task> taskStatus = new List<Task>();
foreach (DataRow dr in dt.Rows)
{
    // create keys & valus as per bussiness logic & add keys into batch
    Task addAsync = batch.HashSetAsync(hashKeyName, hashListVoter.ToArray());
    taskStatus.Add(addAsync);
}
batch.Execute();

// Pipelining
Task[] tasks = taskStatus.ToArray();
               
// get the all tasks in quee
var retTasks = tasks.Where(c => c.IsCompleted == false);
var retTasksCount = retTasks.Count();

// distributes tasks
while (retTasksCount != 0)
{
    Task.WaitAll(tasks, 1000);
    var retTasksinLoop = tasks.Where(c => c.IsCompleted == false);
    retTasksCount = retTasksinLoop.Count();
}

**Comment by mgravell** [comment]
can you clarify - what is `taskStatus` there? I don't see it being populated, so I'm unsure how to interpret the code

**Comment by sabujsen** [comment]
> can you clarify - what is `taskStatus` there? I don't see it being populated, so I'm unsure how to interpret the code

I have updated the code

**Comment by mgravell** [comment]
can you clarify: is everything here going into one hash? and what is `hashListVoter`? it doesn't seem to be related to the row - is this using the `HashEntry[]` API? i.e. is each one multiple items? and: what kind of volume overall are we talking about here?

**Comment by sabujsen** [comment]
> `hashKeyName`

yes hashKeyName is constant for a row in dataset and hashListVoter is same as HashEntry[], It used for multiple values for a key like:

  hashListVoter.Add(new HashEntry(Key 1, value);
  hashListVoter.Add(new HashEntry(Key 2, value);
  hashListVoter.Add(new HashEntry(Key 3, value);

                        Task addAsync = batchWbVoter.HashSetAsync(hashKeyNameforVoter, hashListVoter.ToArray());
it look likes
![image](https://user-images.githubusercontent.com/21103343/58968632-fb91db00-87d3-11e9-94cf-9fdcc8a2f904.png)

**Comment by NickCraver** [comment]
@sabujsen If the command returns without error, that's success :)

Hoping this was long since resolved and closing out to tidy up, but happy to reopen if not!
