### ISSUE TITLE
Stream with Block parameter

### ISSUE THREAD

**Issue by hiteshpersonal** [StackExchange/StackExchange.Redis#1158]
How can I run XRead with block parameter with code? I am trying to replace pub/sub with the stream data type so that our clients don't lose messages. Is it intentionally not supported by the driver?

 Xread BLOCK 100 STREAMS channel1 $

Thanks,
Hitesh

**Comment by mgravell** [comment]
This is deliberate; see this paragraph: https://stackexchange.github.io/StackExchange.Redis/PipelinesMultiplexers.html#multiplexing

We're aware that people want this option - it needs some internal work to make it supportable, however. Additional links:

https://github.com/StackExchange/StackExchange.Redis/issues/1155
https://github.com/StackExchange/StackExchange.Redis/issues/1117
https://github.com/StackExchange/StackExchange.Redis/issues/886

**Comment by veedeo** [comment]
Not sure why it was closed
this code runs in loop with empty messages
```
            while (!stoppingToken.IsCancellationRequested)
            {
                _logger.LogInformation("Reading Stream from Redis");
                var res = await redisDb.StreamReadAsync("events", "0-0", count: 1000);
                _logger.LogInformation("Recieved", res.FirstOrDefault().Values);
            }
```

**Comment by mgravell** [comment]
Literally everything in my previous reply is saying why it is closed.

Until we ship a pool-based, rather than multiplexed, core (or more likely: a dual core that *allows you* to use pool-based mechanisms), this isn't viable.

**Comment by veedeo** [comment]
Got you, thanks
