### ISSUE TITLE
Support for non-readonly slaves

### ISSUE THREAD

**Issue by stepaside** [StackExchange/StackExchange.Redis#116]
WriteMessageToServer method in PhysicalBridge.cs checks for a slave role but does not verify whether that slave is readonly. 

In my particular scenario I separate reads from writes. Replication is setup with writer as a master and multiple readers as slaves with reads being somewhat computationally intensive (have to perform various set and zset operations). In order to utilize MULTI/EXEC constructs I should be able to store temporary results on the reader slave. redis-cli does allow write operations on non-readonly slaves. I can send a pull request with the fix.

**Comment by NickCraver** [comment]
Fixed via #117.
