### ISSUE TITLE
Timeout in async operations is not accurate

### ISSUE THREAD

**Issue by serhatkiyak** [StackExchange/StackExchange.Redis#1160]
I've done some testing around the timeout behavior introducing some network delay. Timeout for sync operations is accurate, whereas the async operations do not respect the timeout value as accurate. The timeout for async operations seems to be in seconds granularity, even though the configuration is in milliseconds. For example, any SyncTimeout (or AsyncTimeout) value between 0-1000ms times out at 1 second, between 1001-2000ms times out at 2 seconds, etc. Example exception message:

Timeout awaiting response (outbound=0KiB, inbound=0KiB, 1000ms elapsed, timeout is 900ms), command=GET, next: GET key, inst: 0, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: Unspecified/sekiyak-test.redis.cache.windows.net:6380, mgr: 10 of 10 available, clientName: SERHAT-PC, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=1,Free=1022,Min=12,Max=1023), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by mgravell** [comment]
Yes, this is a complex one. We can't sensibly create full timeout tokens/timers per message, so it uses a shared sweep that checks for overdue async items and flags them. We could perhaps increase the resolution on this sweep and/or make it configurable, but I don't think we can reasonable make it millisecond accurate.

I am actually more open to inventing some way of passing in cancellation tokens (not as extra params, though - but I have an idea here). Perhaps this is more suitable for your purpose?

**Comment by serhatkiyak** [comment]
I agree that cancellation tokens would be the ideal implementation to enforce timeouts on async operations. Note that this is not very critical for our case, as 1 second of timeout is still acceptable; but an improvement in this piece would be beneficial for others as well.

**Comment by joaocpaiva** [comment]
I have brought this up before and in our case we need 200ms timeouts. Currently we have an unconventional workaround that it is far from being ideal.

**Comment by serhatkiyak** [comment]
Actually, we need more fine granularity in the async timeouts as we need to reduce our timeout threshold. Is there any plans to address this to make it more accurate (at least in order of 100ms)?

**Comment by NickCraver** [comment]
Right now all of this happens in the heartbeat, which is controlled by:
```c#
internal const int MillisecondsPerHeartbeat = 1000;
```
Divesting this behavior for a dedicated timer loop on the async timeouts is something I'm not sure is worth doing for the very few requests we get for it (it'd make every `ConnectionMultiplexer` less efficient). In this case...I'm not sure it's worth the cost. The alternative is to make the heartbeat configurable, which is possible but lets users break things in other ways as well.

*If* we made the heartbeat configurable and it ran every say 100-200ms here by your choosing...would you _want_ that behavior? Doing extra work so often? I'm only asking the question for now.

**Comment by Psybax** [comment]
Any method to work around this? We want to confiture asynctimeout as 200ms. Tried to use polly's timeout policy, but it does not work.
