### ISSUE TITLE
Exception on trying to open connection related to Unsafe

### ISSUE THREAD

**Issue by greyhoundgames** [StackExchange/StackExchange.Redis#1161]
I am having similar problems as this following person:
https://github.com/StackExchange/StackExchange.Redis/issues/1128

Going back to the version he mentions also solves the problem for me.
Was this supposed to be fixed in the latest version? I noticed the assembly entires for web.config are present automatically in my web.config so that part seems updated.

**Comment by NickCraver** [comment]
This is something we've reduced the occurrences of with additional builds in the 2.x release line, but it's fundamentally a .NET Framework assembly loading issue. I've written up something I hope helps for anyone hitting this at https://nickcraver.com/blog/2020/02/11/binding-redirects/. That should give a background on what's happening as well as how to resolve it. Hope that helps!
