### ISSUE TITLE
Subscription connection not reconnecting

### ISSUE THREAD

**Issue by westrope** [StackExchange/StackExchange.Redis#1163]
We upgraded from Redis 1.2.6 to 2.0.593. Since the upgrade we have adding tracking to ConnectionFailed and ConnectionRestored events. 

What we are seeing is that we will have some kind of network blip that causes a number of ConnectionFailed events shortly followed by the same number of ConnectionRestored events. After this we expect that everything should be reconnected, but we sometimes see that the subscription connection is still not connected. Currently we have to reboot those role instances to reconnect. 

Seems like it could be related to [Subscriber unsubscribes after subscribing on reconnect ](https://github.com/StackExchange/StackExchange.Redis/issues/1110)

**Comment by NickCraver** [comment]
Agreed this looks to be the same issue as #1110 - collapsing into one thread and we'll take a look after after the connection state issues which may be adding to this in #1374.
