### ISSUE TITLE
Unable to Connect to Azure Redis using StackExchange

### ISSUE THREAD

**Issue by shabirjan** [StackExchange/StackExchange.Redis#1166]
I am trying to access my live Azure Redis Cache Instance inside Visual Studio for locally debugging, I am using `StackExchange.Redis` but I am getting this error whenever i try to access my cache value 

   

 `StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: GET 100014; UnableToConnect on
cache.redis.cache.windows.net:6380/Interactive, Initializing/NotStarted`

I have enabled Non SSL on my Redis cache on port 6379 as well, I have tried running my WebApi Locally with SSL as well (Enabled in Visual Studio). 
The weird part is I am able to connect to same Redis instance using Console application but not with my .Net Core Web APi Project.

    private static Lazy<ConnectionMultiplexer> lazyConnection = new Lazy<ConnectionMultiplexer>(() =>
        {
            string cacheConnection = "connection string";
            return ConnectionMultiplexer.Connect(cacheConnection);
        });

        public static ConnectionMultiplexer Connection
        {
            get
            {
                return lazyConnection.Value;
            }
        }

[![Azure Redis Cache Settings in Azure Portal][1]][1]

  [1]: https://i.stack.imgur.com/2cfNm.png

More weird part is I am able to connect to same Redis instance using Redis Cli.

**Comment by ryankelley** [comment]
@shabirjan What ended up being the fix?

**Comment by m1is** [comment]
I would love to know the fix as well!

**Comment by cjjohansen** [comment]
Have this error too

**Comment by shabirjan** [comment]
I have to open ports on our network in order to connect to redis. So make sure the ports are opened on your network, as this is how i solved my issue.

**Comment by m1is** [comment]
For me the issue was the TLS version.
