### ISSUE TITLE
Performance issues in Redis Pub-Sub 

### ISSUE THREAD

**Issue by ghost** [StackExchange/StackExchange.Redis#1167]
Hi Team,
[CacheManager.zip](https://github.com/StackExchange/StackExchange.Redis/files/3333051/CacheManager.zip)

We are storing user details and other static details in Memory cache and Redis cache. And cache value goes empty or old value in Memory cache when the server scale-out happens, so we have implemented the pub-sub logic to update the cache value in all scaled out servers and working fine but this impacting the system or application's performance very much.

After Implemented the publish & subscription logic only the performance issue is coming so we have analyzed found that when publish count is  250 to 300, then the subscribers are more than 5k. So why the Redis subscription called too much? I am not sure that subscriptions is the problem but application taking 50 to 60 seconds to load a page after implementing the pub-sub logic, so where we did go wrong, could you please check the attached source and help me on this?

**Comment by NickCraver** [comment]
I can't tell from your app exactly, but I'd wager that `UseMockRedisCache` is called from somewhere multiple times. If so, it's subscribing _every time_, adding another listener. Instead, you want to attach the listener (e.g. subscribe) just once when spinning up the connection.

**Comment by NickCraver** [comment]
Without more info here - closing this out to cleanup.
