### ISSUE TITLE
Question: Is it safe to use ArrayPool?

### ISSUE THREAD

**Issue by kripergvg** [StackExchange/StackExchange.Redis#1177]
I want to use a buffer with HashSetAsync. Could you say if it is safe to write code like this?

            var size = 100;
            var buffer = ArrayPool<byte>.Shared.Rent(100);

            await _mDb.HashSetAsync(
                _actorsStateHash,
                nodeId,
                new Memory<byte>(buffer, 0, size));

            ArrayPool<byte>.Shared.Return(buffer);

**Comment by mgravell** [comment]
Yes, absolutely. That is the exact reason why there is now support for `ReadOnlyMemory<byte>` - so you can use oversized / rented buffers. The important caveat - which you have done correctly in the example above - is: don't return it until *after* you've got the response. It doesn't create an internal copy of the data.

**Comment by kripergvg** [comment]
Thanks :)

**Comment by kripergvg** [comment]
Thanks :)
