### ISSUE TITLE
Confused by seemingly random timeouts...

### ISSUE THREAD

**Issue by tombatron** [StackExchange/StackExchange.Redis#1179]
I got a timeout this morning during a period of super low activity and I'm at a loss as to how to explain it. 

`Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5325ms elapsed, timeout is 5000ms), command=RPOP, next: RPOP ActionList, inst: 0, qu: 0, qs: 3, aw: True, rs: DequeueResult, ws: Writing, in: 0, in-pipe: 14, out-pipe: 0, serverEndpoint: Unspecified/redis.internal:6379, mgr: 8 of 10 available, clientName: client1, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

The application that received this timeout exception was mostly idle when the timeout occurred. I say "mostly" because it does poll a list using the `RPOP` command which you can see from the following screen shot is completing fairly quickly on the server. 

![image](https://user-images.githubusercontent.com/119369/60968745-dec55780-a2eb-11e9-9c4b-70c8a986ab40.png)

So how do I explain what's going on here? If this is an actual issue with the StackExchange.Redis library what additional information should I gather in an effort to help diagnose and possibly resolve it?

**Comment by tombatron** [comment]
I forgot to mention, we are gathering Redis metrics using the [Prometheus Exporter for Redis](https://github.com/oliver006/redis_exporter) and graphing that data using Grafana.

**Comment by marafiq** [comment]
IncludePerformanceCountersInExceptions=True and IncludeDetailInExceptions=True on multiplexer, increase your Min IO  in the machine config 
<processModel autoConfig="false" minIoThreads="250" />

**Comment by tombatron** [comment]
As suggested I have enabled `IncludePerformanceCountersInExceptions` and `IncludeDetailInExceptions`...

```csharp
var muxr = ConnectionMultiplexer.Connect(configOptions);
muxr.IncludePerformanceCountersInExceptions = true;
muxr.IncludeDetailInExceptions = true;
```

...as well as setting minimum worker threads to 100 via the  `COMPlus_ThreadPool_ForceMinWorkerThreads ` environment variable.

This morning the following exception was present in out Sentry server:

`Timeout awaiting response (outbound=0KiB, inbound=0KiB, 7222ms elapsed, timeout is 5000ms), command=RPOP, next: RPOP ActionList, inst: 0, qu: 0, qs: 2, aw: False, rs: DequeueResult, ws: Idle, in: 0, in-pipe: 9, out-pipe: 0, serverEndpoint: Unspecified/redis.internal:6379, mgr: 9 of 10 available, clientName: client1, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=100,Max=32767), Local-CPU: unavailable, v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

![image](https://user-images.githubusercontent.com/119369/61870177-7e1d4980-aeab-11e9-8173-73109d21f25c.png)

The region of the above chart surrounded by the red rectangle represents when the exception had occurred. 

Since it appears that the CPU utilization couldn't be gathered for the exception, the following is a chart of the server's CPU utilization during the time of the exception:

![image](https://user-images.githubusercontent.com/119369/61871132-01d83580-aeae-11e9-86c1-73ef54914501.png)

Some additional details, the application is implemented with ASP.NET Core 2.2 running on CentOS 7.6.

**Comment by tombatron** [comment]
I should add, that these timeouts are occurring during periods of inactivity. There is a simple message queue loop that queries (`RPOP`) a specific key for a work item, when these time outs occur there is no application activity therefore the lists are empty (or non-existent).

**Comment by marafiq** [comment]
I recently was able to fix all Redis time out under load. 
Hints:
- Timeout value, 5 seconds, 10 seconds or less?
- What is the size of data you are storing? 
-- Redis is designed to store small values, not for MB values if the size is large you must increase timeout values and monitor your network pipe performance. 
-- I was using large values, i used Gzip compression at an optimal level to reduce network traffic, hence latency. Do not forget Redis is single-threaded. 
- What is GC Suspension ratio when time out occurs?
-- Find out what is causing high suspension ratio, fix that, you will see the impact on less number of time outs.
- How may GC collections happen?
-- If a large number of GC collections are happening, GC might suspend all threads, it does not play nicely with Redis. 
- Are you using Redis Session State Module as well?
-- Yes, adjust connect timeout, retry count, and sync timeout values.
- Connect Timeout and retry count? 
-- For me, 10 seconds with 5 linear retires worked great.
- Are you using sync methods?
-- Try to convert to async where possible/
- Are you using sync with your own task.wait, instead use db.wait (for some reason, it plays nicely with sync timeouts, even works better where async over sync.
- Log when the multiplexer is trying to connect & dispose, it might co-relate with timeouts.

Note: Abbreviations used stack trace error messages, i submitted PR with the explanation here 
https://github.com/StackExchange/StackExchange.Redis/pull/1190

**Comment by tombatron** [comment]
We isolated the issue to another process using all available memory, being killed and everything returning to normal. 

So uh. 

No issues here, just some other app wrecking my testing.
