### ISSUE TITLE
Under some conditions async methods from StackExchange.Redis won't return

### ISSUE THREAD

**Issue by miraer** [StackExchange/StackExchange.Redis#1180]
Under some conditions code awaiting on StackExchange.Redis API won't return.
It could happen if under some condition StackExchange.Redis code won't set result or exception to TaskCompletionSource it returns back.

It makes TaskCompletionSource object not referenced by anything and it gets GarbageCollected.

As a result state machines created by async-await methods in your code and awaiting on that TaskCompletionSource get garbage collected too, as the only reference to them was from TaskCompletionSource they were awaited from Redis.

Finally you have in you code await that will never get a callback to continue.

**Comment by mgravell** [comment]
OK; have you identified a specific scenario in which this occurs? some kind of repro?

**Comment by miraer** [comment]
No, as service is processing a lot of parallel requests.
But we noticed that state machine awaiting Redis is not in the heap already and was GC-ed, so task that was returned by StateMachine method will be never set to neither Completed nor Faulted.

It should be something like this:

using System;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        // Trigger GC periodically
        Task.Run(() =>
        {
            while (true)
            {
                GC.Collect();
                Thread.Sleep(100);
            }
        });
            

        Task<int> t = A();  // We will await forever if DoCalculate fails
        Console.WriteLine(t.Result);
        Console.ReadKey();
    }

    static async Task<int> A()  // State machine generated by this method will be present on the heap as it will be referenced by continuation of delay task
    {
        var tb = B();
        var td = Task.Delay(TimeSpan.FromSeconds(10));
        await Task.WhenAll(new[] {tb, td});
        return tb.Result;
    }

    static Task<int> B() // State machine generated by this method will be GC-ed and won't be on the heap as nothing is referencing it, as a result tcs was never set and tcs is also GC-ed
    {
        TaskCompletionSource<int> tcs = new TaskCompletionSource<int>();
        Task.Run(()=>DoCalculate(tcs));
        return tcs.Task;

    }

    private static void DoCalculate(TaskCompletionSource<int> tcs)
    {
        throw new Exception();
        tcs.SetResult(5);
    }
}

/*
 0:000> !DumpHeap -type Program+
         Address               MT     Size
00000273d0be2d60 00007fface525b30       24     
00000273d0bec2f0 00007fface529d08       72     

Statistics:
              MT    Count    TotalSize Class Name
00007fface525b30        1           24 Program+<>c
00007fface529d08        1           72 Program+<A>d__1
Total 2 objects
0:000> !DumpHeap -type TaskCompletionSource
         Address               MT     Size

Statistics:
              MT    Count    TotalSize Class Name
Total 0 objects

*/

**Comment by miraer** [comment]
But in that place we do with Redis
```
var transaction = cache.CreateTransaction();
var taskA = transaction.HashGetAsync("", id);
var taskB = transaction.StringGetAsync("");
await transaction.ExecuteAsync();
await taskA;
await taskB;
```
and 

```
   var transaction = cache.CreateTransaction();
   var versionKey = "";
   transaction.AddCondition(Condition.StringEqual(versionKey, expectedVersion));
   obj.LastReportedTimestamp = clock.CurrentUtcTime;
   var serializedEntity = JsonConvert.SerializeObject(obj);

   transaction.HashSetAsync("", id, serializedEntity).Forget();
   var taskB = transaction.StringIncrementAsync("");
   transaction.SortedSetAddAsync("", id, entity.LastReportedTimestamp.UtcTicks).Forget();

   var result = await transaction.ExecuteAsync();
   var version = await taskB;
```

**Comment by mgravell** [comment]
OK, can we take a step back here? Nothing in your example let's me see why you think this is happening. I'm not saying that it is or isn't - I'm saying: I can't tell that from here. What you've shown is just - a transaction.

So - can I assume that the gist here is that occasionally things will just disappear? And that couldn't be explained by an exception being swallowed in the calling code? Internally we maintain a backlog queue, so for that to happen would mean there is some scenario in which we dequeue and just drop (rather than mark as complete/cancelled/etc). That seems unlikely, but it is possible. But I'd really rather focus on the symptoms, unless you have a demonstrable repro that points in a particular direction.

So: please talk me through *what you're seeing*.

**Comment by mgravell** [comment]
BTW, if Forget() here is just to make the compiler happy: see "discards" in current C#:

``` c#
_ = blah.Whatever(); // no complaints about not doing things with results
```

**Comment by miraer** [comment]
Sure, usage was only provided to show what Redis code we execute at the moment this is happening. 
Just from usage it's not clear why it's happening. I provided you usage to locate possible places in your code.

Yes, to that to happen you should miss setting result/exception/cancellation back to TCS.

Symptoms are that we are awaiting an asynchronous method, that is running two transactions above.
Method never returns and state-machine object that is corresponding to calling that two transcations above is garbage collected (not present in the heap in taken dump).

P.S. Forget(); is not just forget, but forget and log :-)

**Comment by mgravell** [comment]
And to ask an obvious question that is necessary because I see this a lot:
you're absolutely sure it wasn't just swallowed by an exception handler in
the calling code?

**Comment by miraer** [comment]
What exact scenario you mean with Exception in the calling code? In that case that Task that we await forever would finish with Faulted state with Exception.

It looks like this in simplified form: 
private async Task RunRedisTransations() {
 // here is code of 2 transactions
}

somewhere later
await RunRedisTransations();   - this await never returns and RunRedisTransaction state machine is gone from the heap.

If any unhandled exception happens in RunRedisTransaction it would set faulted that awaiting task.

**Comment by miraer** [comment]
@mgravell , could you please point me in the code where exactly queuing/equipping of tcs that you mentioned above happens?

**Comment by NickCraver** [comment]
I've just read through to catch up. This _really_ sounds like an unawaited task has gone off and died in the background leaving things in a deadlocked state, not running the continuations you expect. Can you expound on what `Forget()` does?

We've seen all sorts of crazy through the years with the exact way continuations are handled and I'm just relaying that _really_ seems like the case here.
