### ISSUE TITLE
StackExchange.Redis wrong IPv6 address resolution?

### ISSUE THREAD

**Issue by mtreske** [StackExchange/StackExchange.Redis#1183]
Hi,

i'am using StackExchange.Redis v.2.0.601 in an .NETCore2.2 Project. When i try to connect async to our redis cluster Server (v5.05)  i get a log like this:

2a01:9820:1:24::1:1:6379,password=*****,resolveDns=True,defaultDatabase=0

Connecting 2a01:9820:1:24::1:1:6379/Interactive...
BeginConnect: 2a01:9820:1:24::1:1:6379
1 unique nodes specified
Connected Interactive/2a01:9820:1:24::1:1:6379
Requesting tie-break from 2a01:9820:1:24::1:1:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=2,Free=998,Min=8,Max=1000), WORKER: (Busy=0,Free=32767,Min=8,Max=32767)
Server handshake
Authenticating (password)
Setting client name: ...
Auto-configure...
Sending critical tracer: Interactive/2a01:9820:1:24::1:1:6379
Writing to Interactive/2a01:9820:1:24::1:1:6379: ECHO
Flushing outbound buffer
Starting read
connection failed: 2a01:9820:1:24:0:1:4:6379 (Interactive, UnableToConnect): UnableToConnect on 2a01:9820:1:24:0:1:4:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
connection failed: 2a01:9820:1:24:0:1:6:6379 (Interactive, UnableToConnect): UnableToConnect on 2a01:9820:1:24:0:1:6:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
connection failed: 2a01:9820:1:24:0:1:2:6379 (Interactive, UnableToConnect): UnableToConnect on 2a01:9820:1:24:0:1:2:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
Response from Interactive/2a01:9820:1:24::1:1:6379 / ECHO: BulkString: 16 bytes
Writing to Interactive/2a01:9820:1:24::1:1:6379: PING
Writing to Interactive/2a01:9820:1:24::1:1:6379: GET __Booksleeve_TieBreak
Response from Interactive/2a01:9820:1:24::1:1:6379 / PING: SimpleString: PONG
Response from Interactive/2a01:9820:1:24::1:1:6379 / GET __Booksleeve_TieBreak: Error: MOVED 6202 2a01:9820:1:24::1:2:6379
All tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=2,Free=32765,Min=8,Max=32767)
2a01:9820:1:24::1:1:6379 returned with success
Requesting tie-break from 2a01:9820:1:24:0:1:4:6379 > __Booksleeve_TieBreak...
Requesting tie-break from 2a01:9820:1:24:0:1:2:6379 > __Booksleeve_TieBreak...
connection failed: 2a01:9820:1:24:0:1:3:6379 (Interactive, UnableToConnect): UnableToConnect on 2a01:9820:1:24:0:1:3:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
Requesting tie-break from 2a01:9820:1:24:0:1:3:6379 > __Booksleeve_TieBreak...
connection failed: 2a01:9820:1:24:0:1:1:6379 (Interactive, UnableToConnect): UnableToConnect on 2a01:9820:1:24:0:1:1:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
Requesting tie-break from 2a01:9820:1:24:0:1:1:6379 > __Booksleeve_TieBreak...
Requesting tie-break from 2a01:9820:1:24:0:1:6:6379 > __Booksleeve_TieBreak...
connection failed: 2a01:9820:1:24:0:1:5:6379 (Interactive, UnableToConnect): UnableToConnect on 2a01:9820:1:24:0:1:5:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
Requesting tie-break from 2a01:9820:1:24:0:1:5:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:04.7940000 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=2,Free=32765,Min=8,Max=32767)
Not all tasks completed cleanly (from ReconfigureAsync#1524, timeout 4794ms), IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=32766,Min=8,Max=32767)
2a01:9820:1:24:0:1:4:6379 did not respond
2a01:9820:1:24:0:1:2:6379 did not respond
2a01:9820:1:24:0:1:3:6379 did not respond
2a01:9820:1:24:0:1:1:6379 did not respond
2a01:9820:1:24:0:1:6:6379 did not respond
2a01:9820:1:24:0:1:5:6379 did not respond
Cluster: 16384 of 16384 slots covered
2a01:9820:1:24::1:1:6379: Cluster v5.0.5, slave; 16 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
2a01:9820:1:24::1:1:6379: int ops=16, qu=0, qs=0, qc=0, wr=0, socks=1, non-pref=2; sub ops=4, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
Circular op-count snapshot; int: 0+16=16 (1,60 ops/s; spans 10s); sub: 0+4=4 (0,40 ops/s; spans 10s)
2a01:9820:1:24:0:1:4:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: n/a; not in use: DidNotRespond
2a01:9820:1:24:0:1:4:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0
Circular op-count snapshot; int: 0 (0,00 ops/s; spans 10s); sub:
2a01:9820:1:24:0:1:2:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: n/a; not in use: DidNotRespond
2a01:9820:1:24:0:1:2:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0
Circular op-count snapshot; int: 0 (0,00 ops/s; spans 10s); sub:
2a01:9820:1:24:0:1:6:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: n/a; not in use: DidNotRespond
2a01:9820:1:24:0:1:6:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0
Circular op-count snapshot; int: 0 (0,00 ops/s; spans 10s); sub:
2a01:9820:1:24:0:1:3:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: n/a; not in use: DidNotRespond
2a01:9820:1:24:0:1:3:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0
Circular op-count snapshot; int: 0 (0,00 ops/s; spans 10s); sub:
2a01:9820:1:24:0:1:1:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: n/a; not in use: DidNotRespond
2a01:9820:1:24:0:1:1:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0
Circular op-count snapshot; int: 0 (0,00 ops/s; spans 10s); sub:
2a01:9820:1:24:0:1:5:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: n/a; not in use: DidNotRespond
2a01:9820:1:24:0:1:5:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0
Circular op-count snapshot; int: 0 (0,00 ops/s; spans 10s); sub:
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Starting heartbeat...

The returned ConnectionMultiplexer is valid and the IsConnected flag ist true.
When i try to set an key with KeyExpireAsync(...) or...StringSetAsync(...) i get an Exception like this:

No connection is available to service this operation: EXPIRE ecs_113786753221_595398; UnableToConnect on 2a01:9820:1:24:0:1:4:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402; IOCP: (Busy=1,Free=999,Min=8,Max=1000), WORKER: (Busy=5,Free=32762,Min=8,Max=32767), Local-CPU: n/a

It seems, that the Ipv6 Address is not resolved in a correct way:
2a01:9820:1:24::1:1:6379 
should be translated in [2a01:9820:1:24:0:0:1:1]:6379
but is 2a01:9820:1:24:0:1:1:6379 witch is a valid IPv6 Address but not in our Network.
6379 shold be a port not an segment in the address.

**Comment by mgravell** [comment]
It wouldn't amaze me to find that ipv6 hasn't seen a ton of usage, so there could be links that need looking at, indeed. Definitely needs attention, thanks for the report.

**Comment by NickCraver** [comment]
Took a look - this isn't a bug in the library, but in the connection string specified. Since `2a01:9820:1:24::1:1:6379` _is_ a valid IPv6 address, it's treated as such. For the intended use case here, the connection string should be `"[2a01:9820:1:24::1:1]:6379"`. Those are the rules of IPv6's formatting, rather than our own.

I added a test to demonstrate this in #1384. Hope this helps!
