### ISSUE TITLE
No connection is available to service this operation

### ISSUE THREAD

**Issue by sarvabowmen** [StackExchange/StackExchange.Redis#1184]
I am getting this error on a particular environment while connecting to AzureRedisCache

Client Version: StackExchange.Redis.StrongName (1.2.6)

I am getting this follwoing error,
No connection is available to service this operation: HSETNX "Key Name"
 SocketClosed on SERVER-URL/Interactive, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, 
 last-read: 0s ago, last-write: 0s ago, unanswered-write: 280531s ago, keep-alive: 60s, pending: 0, 
 state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: Inactive, err: never; IOCP: (Busy=1,Free=999,Min=8,Max=1000), WORKER: (Busy=2,Free=32765,Min=8,Max=32767), Local-CPU: n/a

Note: I am getting this error in the primary instance, not in secondary though

**Comment by NickCraver** [comment]
This can happen when Azure performs a failover behind the scenes. The handling is more graceful in 2.x with another fix going in #1374, but there will be no more updates to the 1.x line of StackExchange.Redis. If you are in a position to upgrade, I recommend trying the 2.1.x release likely later this week.
