### ISSUE TITLE
Is it OK to create a binding redirect from System.Buffers 4.0.2 to 4.0.3 when using StackExchange.Redis?

### ISSUE THREAD

**Issue by christopherliu** [StackExchange/StackExchange.Redis#1185]
We're running a .NET 4.7.2 app that references StackExchange.Redis v2. According to the [release notes](https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes#20513), there was a reference to System.Buffers 4.0.3.0 that was rolled back to 4.0.2.0 to address an issue where a [binding redirect](https://github.com/dotnet/corefx/issues/32511) wasn't being generated.

We are seeing the same issue now despite having the latest version of StackExchange.Redis:

> The assembly for System.Buffers could not be loaded; this usually means a missing assembly binding redirect - try checking this, and adding any that are missing; note that it is not always possible to add this redirects - for example 'azure functions v1'; it looks like you may need to use 'azure functions v2' for that - sorry, but that's out of our control

My theory is that we have another library that references 4.0.3.0, and the binding redirect is not being generated again, only this time it's StackExchange.Redis that has the lower version.

1. Can someone confirm that this is not impossible?
2. If this is the case, is there anything in StackExchange.Redis that would break if we added a binding redirect from 4.0.2.0 to 4.0.3.0, as shown below?

```xml
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="4.0.2.0-4.0.3.0" newVersion="4.0.3.0"/>
      </dependentAssembly>
```

Thanks!

**Comment by mgravell** [comment]
It should be fine as long as you have the binding redirect. Right now, binding redirects on .NET Framework are my hell. Pick one: "buffers", "unsafe", "numerics" - 95% of problems will be one of those! I'm *really* looking forward to when they drop the next set of nuget packages, as I think that moves a couple of blockages.

But yes: you should be fine. There aren't any problems with either version, other than the brittle binding generation. Let me know how it goes!

**Comment by christopherliu** [comment]
Thanks @mgravell !
