### ISSUE TITLE
How to configure RedisCacheOptions.ConfigurationOptions.EndPoints from appsetting.json

### ISSUE THREAD

**Issue by bidianqing** [StackExchange/StackExchange.Redis#1187]
https://github.com/aspnet/Extensions/issues/2055

**Comment by mgravell** [comment]
That's not an API we provide. If the lib you've linked to does: great

**Comment by NickCraver** [comment]
Closing this out to cleanup - you've already asked in the right place at https://github.com/aspnet/Extensions/issues/2055 :)
