### ISSUE TITLE
No connection is available to service this operation: RPOP

### ISSUE THREAD

**Issue by maximdx** [StackExchange/StackExchange.Redis#1189]
Hi,

We meet an issue while trying to do right pop from a channel in a .Net Core 2.2 hosted service generic host.
The detailed exception stack is show as following:

```
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: RPOP BookingCreated; IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=0,Free=32767,Min=1,Max=32767), Local-CPU: n/a
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2192
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.ListRightPop(RedisKey key, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 979
```

The code segment trying to execute the right pop is as following:
```
var subscriber = _connection.GetSubscriber();
subscriber.Subscribe(***SubscribeChannelName***, (channel, message) =>
{
    try
    {
        var popResult = _connection.GetDatabase().ListRightPop(channel.ToString());
...
```  

where _connection is initialized by
`
ConnectionMultiplexer.Connect(***RedisConnectionString***)
`
in the class constructor. The class is injected as the Hosted Service.

This work perfectly fine at local or any windows environment with single node redis server. But when move to the kubernetes environment, the above exception is thrown, where redis cluster is installed from helm chart stable/redis-ha.

I have tried to redis-cli connect to the redis service from the pod that running the app as well, it can connect to the service and interacting with the cluster is also without any problem.

The version of StackExchange.Redis library we are currently using is 2.0.513.

Could any help me to debug this issue further please?

**Comment by maximdx** [comment]
It’s strange that it can subscribe from the channel but have problem pop from the list.

**Comment by NickCraver** [comment]
I was looking for other reports of this but can't find any - could this be an issue with the proxy in play? I'm not sure how your cluster is exposed across k8s. Does this still happen in 2.0.601?
