### ISSUE TITLE
NRediSearch set return parameter of search

### ISSUE THREAD

**Issue by oruchreis** [StackExchange/StackExchange.Redis#1198]
Hi,
We can use `infields` parameter to filter the used fields in the query with `LimitFields` method. Could you implement also `RETURN {num} {field}` parameter to limit returned fields in the result? It is very useful if you have documents that have a lot of fields and you don't need all fields in every query result.

**Comment by NickCraver** [comment]
Fixed in #1199, thank you for the contribution!
