### ISSUE TITLE
Repeated timeout issues - cross post from SO

### ISSUE THREAD

**Issue by akabak** [StackExchange/StackExchange.Redis#120]
We've got several web and worker roles in Azure connecting to our Azure Redis cache via the StackExchange.Redis library, and we're receiving regular timeouts. An example of one of them is below:

```
System.TimeoutException: Timeout performing GET stream:459, inst: 4, mgr: Inactive, queue: 12, qu=0, qs=12, qc=0, wr=0/0, in=65536/0 at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\58bc9a6df18a3782\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line
  1785    at StackExchange.Redis.RedisBase.ExecuteSync[T](Message
  message, ResultProcessor1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\58bc9a6df18a3782\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 79 at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\TeamCity\buildAgent\work\58bc9a6df18a3782\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1346 at OptiRTC.Cache.RedisCacheActions.<>c__DisplayClass41.<Get>b__3() in
  c:\dev\OptiRTCAzure\OptiRTC.Cache\RedisCacheActions.cs:line 104    at
  Polly.Retry.RetryPolicy.Implementation(Action action, IEnumerable1 shouldRetryPredicates, Func`1 policyStateFactory) at OptiRTC.Cache.RedisCacheActions.Get[T](String key, Boolean allowDirtyRead) in c:\dev\OptiRTCAzure\OptiRTC.Cache\RedisCacheActions.cs:line 107 at OptiRTC.Cache.RedisCacheAccess.d__e4.MoveNext() in c:\dev\OptiRTCAzure\OptiRTC.Cache\RedisCacheAccess.cs:line 1196; TraceSource 'WaWorkerHost.exe' event
```

All the timeouts have different queue, qs, and the first in numbers, but the rest of the messages are consistent. These StringGet calls are across different keys in the cache. In each of our services, we use a singleton cache access class with a single ConnectionMultiplexer that is registered with our IoC container in the web or worker role startup:

``` C#
container.RegisterInstance<ICacheAccess>(cacheAccess);
```

In our implementation of ICacheAccess, we're creating the multiplexer as follows:

``` C#
ConfigurationOptions options = new ConfigurationOptions();
options.EndPoints.Add(serverAddress);
options.Ssl = true;
options.Password = accessKey;                    
options.ConnectTimeout = 1000;
options.SyncTimeout = 2500;
redis = ConnectionMultiplexer.Connect(options);
```

where the redis object is used throughout the instance. We've got about 20 web and worker role instances connecting to the cache via this ICacheAccess implementation, but the management console shows an average of 200 concurrent connections to the cache.

I've seen other posts that reference using version 1.0.333 of StackExchange.Redis, which we're doing via NuGet, but when I look at the actual version of the StackExchange.Redis.dll reference added, it shows 1.0.316.0. We've tried adding and removing the NuGet reference as well as adding it to a new project, and we always get the version discrepancy. A few more observations about this version mis-match:
- when details of the files are viewed in, say, Windows Explorer, I see version 1.0.333, but visual studio always says 1.0.316
- when I use the nuget package management console to try to install specific versions, say 1.0.329, visual studio still shows 1.0.316

Any insight would be appreciated. Thanks.

**Comment by akabak** [comment]
I have some more information about this issue. When I run a service with fewer instances and a higher CPU, I get significantly more of these timeout errors than when instances are running at lower CPUs. More specifically, I pulled some numbers from our services this morning. When they were running at around 30% CPU, I saw very few timeout issues - just 42 over 30 minutes. When I removed half the instances and they started to run at around 60-65% CPU, the rate increased 10-fold to 536 over 30 minutes.

Any ideas? Obviously, we don't want to run more instances than we have to on Azure. I will also update the SO post.

**Comment by mikeharder** [comment]
I wouldn't expect CPU utilization to have an impact until it gets closer to 100%.  You might be network bound on your client.  What size are your client instances, and what is the network utilization (send/receive Mbps)?

Another possibility is that requests are timing out because their response is stuck behind other responses in the queue.  Each instance of ConnectionMultiplexer uses a single TCP connection.  You could try creating multiple instances of ConnectionMultiplexer per client process and distribute your requests across them.

**Comment by akabak** [comment]
We're using a series of small Azure VMs, and we see up to around 2 Mbps at the higher end, usually more like 800 Kbps. I don't think that should be a problem.

Would having responses stuck behind other responses lead to the in=####/0 error we're seeing? We've been really careful about using a singleton object with a single ConnectionMultiplexer because that was what we saw recommended. **How can we determine if this is actually the problem?** We average about 20 calls to the cache per second across our platform, and those calls are made primarily half in one set of services with 3 instances/ConnectionMultiplexers then a quarter to each of two other services (one of which has 6 instances and one of which has 4 - the one I've been experimenting on with CPU utilization and for which I've reported the network utilization, above).

**Comment by chriskopec** [comment]
@akabak - Did you solve the issues you described here? 

We are running into similar issues on azure using their azure redis cache. We've been working for a while with the microsoft support group without much luck. In our last test we ran a network trace and enabled System.Net trace logs. What we see is when the Timeouts occur nothing is being sent from the client. Rather it seems the client becoming blocked causing the requests to backup and all timeout. 

Here is an example of the TimeoutExceptions we are seeing: 

> System.TimeoutException: Timeout performing SET device-or-camera:001f920078f1-1:last-activity-time, inst: 1, mgr: Inactive, queue: 24, qu=0, qs=24, qc=0, wr=0/0, in=921/0; at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server); at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server); at StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable`1 expiry, When when, CommandFlags flags); at VideoIQ.Cloud.Core.Caching.RateLimitingCache.RecordDeviceOrCameraActivity(String deviceOrCameraId)
> System.TimeoutException: Timeout performing SET device-or-camera:001f92008850-0:last-activity-time, inst: 1, mgr: Inactive, queue: 24, qu=0, qs=24, qc=0, wr=0/0, in=958/0; at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server); at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server); at StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable`1 expiry, When when, CommandFlags flags); at VideoIQ.Cloud.Core.Caching.RateLimitingCache.RecordDeviceOrCameraActivity(String deviceOrCameraId)
> System.TimeoutException: Timeout performing SET device-or-camera:001f92008eba-1:last-activity-time, inst: 1, mgr: Inactive, queue: 26, qu=0, qs=26, qc=0, wr=0/0, in=1048/0; at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server); at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server); at StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable`1 expiry, When when, CommandFlags flags); at VideoIQ.Cloud.Core.Caching.RateLimitingCache.RecordDeviceOrCameraActivity(String deviceOrCameraId)

**Comment by akabak** [comment]
Nope, we didn't solve it. We didn't want to go down the road of trying to
create our internal load balancer to the connection multiplexer, which
seemed to be what was last suggested. Instead, after a bunch of A-B load
and stress testing, we ended up going with the ServiceStack.Redis library.

After months and months of timeout issues and a cache we couldn't rely on,
now things are rock solid.

On Wed, May 13, 2015 at 11:07 AM, chriskopec <notifications@github.com>
wrote:

> @akabak <https://github.com/akabak> - Did you solve the issues you
> described here?
>
> We are running into similar issues on azure using their azure redis cache.
> We've been working for a while with the microsoft support group without
> much luck. In our last test we ran a network trace and enabled System.Net
> trace logs. What we see is when the Timeouts occur nothing is being sent
> from the client. Rather it seems the client becoming blocked causing the
> requests to backup and all timeout.
>
> Here is an example of the TimeoutExceptions we are seeing:
>
> System.TimeoutException: Timeout performing SET
> device-or-camera:001f920078f1-1:last-activity-time, inst: 1, mgr: Inactive,
> queue: 24, qu=0, qs=24, qc=0, wr=0/0, in=921/0; at
> StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImplT; at
> StackExchange.Redis.RedisBase.ExecuteSyncT; at
> StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value,
> Nullable1 expiry, When when, CommandFlags flags); at
> VideoIQ.Cloud.Core.Caching.RateLimitingCache.RecordDeviceOrCameraActivity(String
> deviceOrCameraId)
> System.TimeoutException: Timeout performing SET
> device-or-camera:001f92008850-0:last-activity-time, inst: 1, mgr: Inactive,
> queue: 24, qu=0, qs=24, qc=0, wr=0/0, in=958/0; at
> StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message
> message, ResultProcessor1 processor, ServerEndPoint server); at
> StackExchange.Redis.RedisBase.ExecuteSyncT; at
> StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value,
> Nullable1 expiry, When when, CommandFlags flags); at
> VideoIQ.Cloud.Core.Caching.RateLimitingCache.RecordDeviceOrCameraActivity(String
> deviceOrCameraId)
> System.TimeoutException: Timeout performing SET
> device-or-camera:001f92008eba-1:last-activity-time, inst: 1, mgr: Inactive,
> queue: 26, qu=0, qs=26, qc=0, wr=0/0, in=1048/0; at
> StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message
> message, ResultProcessor1 processor, ServerEndPoint server); at
> StackExchange.Redis.RedisBase.ExecuteSyncT; at
> StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value,
> Nullable`1 expiry, When when, CommandFlags flags); at
> VideoIQ.Cloud.Core.Caching.RateLimitingCache.RecordDeviceOrCameraActivity(String
> deviceOrCameraId)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/120#issuecomment-101726492>
> .
>



-- 

Amanda Kabak

Sr. Software Architect


active intelligence | clean water

o. 844.678.4782 ext.105

optirtc.com | @optirtc <https://twitter.com/optirtc>

**Comment by NickCraver** [comment]
Apologies on poking this very old issue, but trying to gather what's left to resolve - is anyone here still hitting this on the latest libs? (1.2.6+)

**Comment by mgravell** [comment]
Closing; please see #871
