### ISSUE TITLE
Query Large Dataset in Redis using StackExchange.Redis

### ISSUE THREAD

**Issue by sunil-vtm** [StackExchange/StackExchange.Redis#1206]
Hi,

I have read through all the documentation of Redis and StackExchange.Redis Usages for integrate/communicate to Redis which had nice features. But, I  didnot come across anything regards to read or query a data from Redis in flexible fashion, I mean fulltext search or non-key attributes filtering.

For Example, I have 100 K+ POCOs in a .Net List. What is an approach to store this large amount of data into Redis?  and How to query or filter the data by using nonkey field values? 
As I mentioned below JSON, how to filter the employees by the region is CA and jobTitleName is Developer?
Could you please show some light on this?

**Example:**
{
"Employees" : [
{
"userId":"rirani",
"jobTitleName":"Developer",
"firstName":"Romin",
"lastName":"Irani",
"preferredFullName":"Romin Irani",
"employeeCode":"E1",
"region":"CA",
"phoneNumber":"408-1234567",
"emailAddress":"romin.k.irani@gmail.com"
},
{
"userId":"jayesh",
"jobTitleName":"Analyst",
"firstName":"jayesh",
"lastName":"kumar",
"preferredFullName":"jayesh",
"employeeCode":"E2",
"region":"EU",
"phoneNumber":"408-1111111",
"emailAddress":"jayesh.test@gmail.com"
},
{
"userId":"kumar",
"jobTitleName":"Developer",
"firstName":"sr",
"lastName":"kumar",
"preferredFullName":"sri kumar",
"employeeCode":"E2",
"region":"CA",
"phoneNumber":"408-1111111",
"emailAddress":"srikumar@gmail.com"
}
]
}

**Comment by mgravell** [comment]
If the question here is "how do I store data in redis such that it is
queryable by multiple values" - that's quite a complex topic, because in
redis you usually need to build your own index manually. The details of
that are complex; SE.Redis exposes the primitives for he redis commands,
but doesn't attempt to encapsulate the concept of indexing.

If you don't want to learn the grungy details of doing it "the hard way",
you might be interested in RediSearch, a redis "module" that does this for
you similarly to "elastic". NRediSearch can be used to query it
(NRediSearch sits on top of SE.Redis)

**Comment by sunil-vtm** [comment]
Thanks for your quick response and suggestion. yes, I agree that it  very complex in terms of maintaining such index on Redis(Looks have to bulid multiple indexes using Sorted Sets, but still not going to be true search that we are getting, some limitations...)

We have built ElastiCache Redis  cluster on AWS cloud. I didn't see anything related support of RediSearch in AWS documentation. As per the documentation Redis and RediSearch both are two different clusters isn't it?
if not,  can we query Redis cluster data using RediSearch Library(NRediSearch)? 
Please Advise!

Thanks & Regards,
Sunilkumar.V

**Comment by mgravell** [comment]
RediSearch is a module that can run on regular redis (standalone or cluster, IIRC), but I believe the license for the optional RediSearch module (a RedisLabs thing) means it might not be available on AWS - I think the license makes it hard for AWS to offer it as a hosted service.

**Comment by sunil-vtm** [comment]
Ok, got it...Thanks for clarification...
