### ISSUE TITLE
It was not possible to connect to the redis server(s). UnableToConnect on 192.168.6.11:6379/Interactive, Initializing/NotStarted, last: NONE

### ISSUE THREAD

**Issue by liugt34** [StackExchange/StackExchange.Redis#1209]
### when many users connect at the same time ,it meet this problem

> 
> Connection id "0HLP1TNNPMN3B", Request id "0HLP1TNNPMN3B:00000001": An unhandled exception was thrown by the application.
> StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on 192.168.6.11:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 5 of 10 available, last-heartbeat: never, global: 8s ago, v: 2.0.601.3402
>    at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Object configuration, TextWriter log) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 955
>    at ARchGLCloud.Domain.Core.Cache.RedisStore`1..ctor(IConfiguration configuration, Int32 dbNumber, String prefix) in D:\ARchGLCloud-0701\ARchGLCloud.Domain.Core\Cache\RedisStore.cs:line 26
>    at lambda_method(Closure , ServiceProviderEngineScope )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
>    at lambda_method(Closure , IServiceProvider , Object[] )
>    at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
>    at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
> 

```

public abstract class RedisStore<TEntity> : IRedisStore<TEntity> where TEntity : RedisAggregateRoot
    {
        private readonly string _primary_key_prefix = "";
        private readonly ConnectionMultiplexer _redis;
        private readonly int _dbNumber = 1;

        protected readonly IConfiguration _configuration;
        protected readonly IDatabase _db;

        public RedisStore(IConfiguration configuration, int dbNumber, string prefix)
        {
            this._configuration = configuration;
            this._dbNumber = dbNumber;
            this._primary_key_prefix = prefix;

            this._redis = ConnectionMultiplexer.Connect(configuration.GetSection("IdentityOptions:Redis").Value);
            this._db = _redis.GetDatabase(_dbNumber);
        }
}

```

**Comment by mgravell** [comment]
> when many users connect at the same time

Are you spinning up a multiplexer per request? Per user? Or...?

Basically, multiplexers are *expensive*. You must consider them a shared / pooled resource. You shouldn't be calling Connect frequently.

Is that the issue here?

**Comment by liugt34** [comment]
@mgravell   i used jmeter for a performance testing，the config like the image below
![image](https://user-images.githubusercontent.com/8056013/63147931-37e28280-c032-11e9-80bd-1e74a2250962.png)

**Comment by NickCraver** [comment]
@liugt34 I'm trying to understand - did the singleton solve your issue? (that would be our expectation and the recommended usage), or are you saying it happens in spite of the singleton?

**Comment by firephantomassasin** [comment]
@liugt34 did you resolve your issue? If yes then how? We are encountering the same issue as yours, we are already using singleton pattern (Lazy instantiation approach).

**Comment by liugt34** [comment]
> @liugt34 did you resolve your issue? If yes then how? We are encountering the same issue as yours, we are already using singleton pattern (Lazy instantiation approach).

use singleton to  solve this problem

**Comment by firephantomassasin** [comment]
@liugt34 how did you create your singleton? Is the above code still applicable like you implemented it by using lock? Have you tried using Lazy pattern?

**Comment by liugt34** [comment]
> @liugt34 how did you create your singleton? Is the above code still applicable like you implemented it by using lock? Have you tried using Lazy pattern?

just a double lock singlton, not lazy pattern

**Comment by NickCraver** [comment]
Glad you're all set with the singleton - closing out!

**Comment by mohan023** [comment]
I'm facing the same issue with Redis 3.2.100. With older version of Redis 3.0.504, my application is working fine. When I upgraded Redis to 3.2.100, problem started. How this could be fixed? is this a known issue with this version of Redis?

**Comment by mohan023** [comment]
It was not possible to connect to the redis server(s). UnableToConnect on EA1S2-APP:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 6s ago, v: 2.0.593.37019

What the work interactive referring here? I didn't put it anywhere.
