### ISSUE TITLE
Authenticating Azure cache for redis (StackExchange.Redis library )with certificate

### ISSUE THREAD

**Issue by nivazri** [StackExchange/StackExchange.Redis#1211]
Is there a way to Authenticate Azure cache for redis with a certificate? ( Instead of using password)

I didn't see a option in StackExchange.Redis library

**Comment by dmytrohridin** [comment]
@nivazri 
https://stackexchange.github.io/StackExchange.Redis/Configuration#configuration-options
due to documentation you can provide ssl host with servers's certificate. Is this what you try to find?

**Comment by nivazri** [comment]
I specific ask about authenticate to redis. 
I got this answer on Microsoft StackOverflow

Redis (and Azure Cache for Redis) does not support cert-based authentication. Redis only supports password authentication via the AUTH command. Clients like StackExchange.Redis will automatically and periodically send this command with the password in the connection string.
