### ISSUE TITLE
RecordingTimeout Exception

### ISSUE THREAD

**Issue by dezheng** [StackExchange/StackExchange.Redis#1212]
What's the meaning of 'qu'? Could you please help my check?Thanks.

> {
    "Value": null,
    "Exception": {
        "ClassName": "StackExchange.Redis.RedisTimeoutException",
        "Message": "The timeout was reached before the message could be written to the output buffer, and it was not sent, command=ZRANGEBYSCORE, timeout: 5000, outbound: 14KiB, inbound: 47KiB, inst: 14, qu: 459, qs: 0, aw: True, bw: RecordingTimeout, rs: ReadAsync, ws: Flushed, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/xxxxxxxxx, mgr: 9 of 10 available, clientName: myredisservice\r\n/MYSERVER, IOCP: (Busy=204,Free=796,Min=1000,Max=1000), WORKER: (Busy=652,Free=32115,Min=1000,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)",
        "Data": {
            "Redis-Message": "ZRANGEBYSCORE TESTKEYKEYKEY",
            "Redis-Timeout": "5000",
            "Redis-Write-State": "Flushed",
            "Redis-Read-State": "ReadAsync",
            "Redis-OutboundDeltaKB": "14KiB",
            "Redis-InboundDeltaKB": "47KiB",
            "Redis-OpsSinceLastHeartbeat": "14",
            "Redis-Queue-Awaiting-Write": "459",
            "Redis-Queue-Awaiting-Response": "0",
            "Redis-Active-Writer": "True",
            "Redis-Backlog-Writer": "RecordingTimeout",
            "Redis-Inbound-Bytes": "0",
            "Redis-Inbound-Pipe-Bytes": "0",
            "Redis-Outbound-Pipe-Bytes": "0",
            "Redis-Server-Endpoint": "Unspecified/xxxxxxxxx",
            "Redis-Manager": "9 of 10 available",
            "Redis-Client-Name": "myredisservice\r\n/MYSERVER",
            "Redis-ThreadPool-IO-Completion": "(Busy=204,Free=796,Min=1000,Max=1000)",
            "Redis-ThreadPool-Workers": "(Busy=652,Free=32115,Min=1000,Max=32767)",
            "Redis-Busy-Workers": "652",
            "Redis-Version": "2.0.601.3402",
            "redis-command": "ZRANGEBYSCORE TESTKEYKEYKEY",
            "request-sent-status": 1,
            "redis-server": "xxxxxxxxx"
        },
        "InnerException": null,
        "HelpURL": "https://stackexchange.github.io/StackExchange.Redis/Timeouts",
        "StackTraceString": "   ",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": null,
        "HResult": -2146233083,
        "Source": "System.Private.CoreLib",
        "WatsonBuckets": null,
        "commandStatus": 1
    },
    "Message": "The timeout was reached before the message could be written to the output buffer, and it was not sent, command=ZRANGEBYSCORE, timeout: 5000, outbound: 14KiB, inbound: 47KiB, inst: 14, qu: 459, qs: 0, aw: True, bw: RecordingTimeout, rs: ReadAsync, ws: Flushed, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/xxxxxxxxx, mgr: 9 of 10 available, clientName: myredisservice\r\n/MYSERVER, IOCP: (Busy=204,Free=796,Min=1000,Max=1000), WORKER: (Busy=652,Free=32115,Min=1000,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)",
    "Success": false,
    "ElapsedMilliseconds": 13085,
    "RealKey": "TESTKEYKEYKEY"
}

**Comment by dmytrohridin** [comment]
Hello @dezheng 
Please, check this documentation. It's related to Azure, but there are descriptions for params
https://azure.microsoft.com/es-es/blog/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/

**Comment by mgravell** [comment]
"qu" is the unsent message queue; things that the library wants the server to respond to, but which haven't even been written to the outbound socket yet; if "qu" us high, the most common explanation is that there are very large payloads blocking the pipe, i.e. a huge "set {key} {value}" could block a lot of operations. Or the socket could be broken.

**Comment by dezheng** [comment]
> "qu" is the unsent message queue; things that the library wants the server to respond to, but which haven't even been written to the outbound socket yet; if "qu" us high, the most common explanation is that there are very large payloads blocking the pipe, i.e. a huge "set {key} {value}" could block a lot of operations. Or the socket could be broken.

Thanks. In my codes,I had open thousands threads to consumer some message from kafka, so if I change the redis method from "async" to "sync", is it work?

**Comment by NickCraver** [comment]
In general here, that's a huge amount of concurrent threads and inbound work. If the CPU can't keep up then we'll get a timeout (regardless of API used). If you have extremely spiky work like this, it's probably worth considering upping the timeout to accomodate the backlog you're processing...or slow the request rate down so the CPU isn't in a state that it gets far behind.

**Comment by NickCraver** [comment]
If there are more questions, happy to re-open - I'm trying to consolidate the duplicate issues down after explanations and causes are added.

**Comment by Andrey2G** [comment]
I'm also facing into the problem with "qu", when the timeout error got appear first time the value of qu is about 300, and then getting timeouts (they are like avalanche) the qu value is increasing in each next timeout error to 500-1000-3000 and even more.
I  saw the comment above from @mgravell "the most common explanation is that there are very large payloads blocking the pipe, i.e. a huge "set {key} {value}" could block a lot of operations" but that's not in my case.
Could you please give me any suggestions about what else may cause increasing qu value?
Servers with Redis cluster nodes are not even loaded (CPU is about 25-30%).
But if I close connection and start again - everything back to normal.
This is a sample of the error:
Timeout performing HGET (15000ms), next: HGET {prt}:key, inst: 40, qu: 3136, qs: 1, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: 10.1.2.3:6543, mc: 1/1/0, mgr: 10 of 10 available, PerfCounterHelperkeyHashSlot: 16320, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=15,Free=32752,Min=8,Max=32767), v: 2.1.58.34321
I'm using .Net Framework 4.8
Redis Cluster: version 6.0.8 3 master+3 slaves

**Comment by SwatiLiyaBasecone** [comment]
Timeout awaiting response (outbound=0KiB, inbound=2KiB, 5000ms elapsed, timeout is 5000ms), command=SETEX, next: SET session:01J2963J4NNQTFSZYKWG3F83XY, inst: 0, qu: 0, qs: 0, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 641, last-in: 1, cur-in: 0, sync-ops: 337, async-ops: 812, serverEndpoint: znlwe-d002-b198-rdc-d1-fis1.redis.cache.windows.net:6380, conn-sec: 14783.12, aoc: 0, mc: 1/1/0, mgr: 10 of 10 available, clientName: znlwe-d002-b198-cap-d1-dlvyapi01--qevhyq5-85c4d5ccd6-fnk5b(SE.Redis-v2.7.17.27058), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=10,Free=32757,Min=1,Max=32767), POOL: (Threads=10,QueuedItems=5,CompletedItems=70758,Timers=23), v: 2.7.17.27058 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) 

I am getting above exception and used async method
