### ISSUE TITLE
Write to kubernetes redis cluster with 3 masters and 3 slaves

### ISSUE THREAD

**Issue by khteh** [StackExchange/StackExchange.Redis#1214]
I follow https://github.com/sanderploegsma/redis-cluster to run redis cluster on AWS EKS. This ends up with one `Service` and 6 `Pod`s with 3 masters and 3 slaves. How does the C# client find out the master redis cluster node in order to write to the cache? Thanks.

**Comment by dmytrohridin** [comment]
@khteh 
If I'm correct, C# client do not detecting such things by default. You just pass connection string to your Redis service and this service should manage connections to nodes.
Or you can write your own manager which will be responsible for connecting to different nodes

**Comment by dmytrohridin** [comment]
also you can provide several endpoints
https://stackexchange.github.io/StackExchange.Redis/Configuration#automatic-and-manual-configuration
so my previous comment can be wrong

**Comment by khteh** [comment]
Hi, I am using `ConnectionMultiplexer` with Kubernetes `Service` which connects to a `StatefulSet` with  ` replicas: 6`. So, it is not certain which of the pods are master and which are slave and this is determined at runtime. Is there any difference between configuring `ConnectionMultiplexer` with just one connection string to the Kubernetes `Service` and configuring it with 6 `Endpoint`s to the 6 pods? Would it work one way or another? How about performance wise?

**Comment by dmytrohridin** [comment]
https://stackexchange.github.io/StackExchange.Redis/Basics.html#accessing-individual-servers
due to this document you can access individual server, so seems managing should be done by you

**Comment by khteh** [comment]
Hi, as far as I know, write operation can only be performed to the Master node and the role of the pods are only determined at runtime. Should I configure the ConnectionMultiplexer with a single connection string to the Kubernetes Service or should I use 6 individual Endpoint's to the pods? Is there any difference in terms of functionality and/or performance?

**Comment by dmytrohridin** [comment]
It's hard to answer from my perspective. But, ideally master/slave should be managed by service itself. Not by client

**Comment by mgravell** [comment]
If the cluster is a proper cluster in the redis sense, then the library has the knowledge of how to ask the cluster for the topology and shard distribution. Just let it know *an* endpoint (preferably more than one, for reliability), and it'll figure out the details for you
