### ISSUE TITLE
What is the bottleneck cause of RedisTimeoutException?

### ISSUE THREAD

**Issue by macchmie3** [StackExchange/StackExchange.Redis#1217]
Hi,

I am using Redis Server as a cache for my app service in Azure. App service is running in multiple instances. Sometimes I have troubles, beacause connection to redis is getting overflowed - this almost always happens on single instance, the rest is running OK. I usually have 2-5 instances of my app service. When one of the instance is getting clogged I have a following exception:

StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL (1000ms), next: EVAL, inst: 26, qu: 0, qs: 2227, aw: False, rs: ReadAsync, ws: Idle, in: 65536, in-pipe: 507155, out-pipe: 419813, serverEndpoint: Unspecified/powelgeminicacheprod.redis.cache.windows.net:6379, mgr: 10 of 10 available, clientName: RD0003FF54CDA0, IOCP: (Busy=5,Free=995,Min=256,Max=1000), WORKER: (Busy=163,Free=8028,Min=1024,Max=8191), v: 2.0.601.3402 

Im having troubles reading the exception. I was wondering what is the bottleneck here? The app service itself? I am not sure as CPU on the instance that is getting clogged gets from 20% to 100% in seconds and it's only connected to redis timing out. Is it Redis server that is too slow? I am not so sure either as not all instances are getting timeoutexceptions. Currently I am using Standard tier C2 plan, but Redis metrics do not show any CPU spikes. Is there anything useful that can be read from the above email?

It is worth noting that our traffic is quite stable -- around 100,000 requests per hour. I would say that each request uses cache once on average, so the traffic may be stable, but noticibly big.

I may provide more information if it is needed. I just need to know if I need to consider scaling the cache, scaling the application that uses cache, or maybe do some coding related to the cache itself.

**Comment by macchmie3** [comment]
Right now I downgraded to 1.2.6 and I do not see any performance issues.

**Comment by macchmie3** [comment]
Is there any fix for this optimization problem in the preview of next version?

**Comment by NickCraver** [comment]
Hey @macchmie3 sorry this was lost with other issues - we've slowly improved performance (on top of the correctness) in 2.x and the upcoming 2.5 release is finally on par or better than 1.2.6 in every scenario we're aware of. I hope this helps anyone finding this issue later.

I'm closing out the duplicate performance issues to tidy up but if you're still seeing issues on 2.5.x vs. 1.2.6 I'll of course re-open but we'll need a repro of your scenario to chase that specific case down. Thanks for the details here, I didn't respond to every issue (time is the enemy) but all this data helped track down gaps!
