### ISSUE TITLE
Socket exceptions thrown when closing a ConnectionMultiplexer with Sentinel endpoints

### ISSUE THREAD

**Issue by dmusicant-dk** [StackExchange/StackExchange.Redis#1218]
When I create a `ConnectionMultiplexer` (see below), everything works properly. I'm able to connect to it, find the master redis node and make requests. However, when I call `sentinelMultiplexer.Close()` or `sentinelMultiplexer.Close(false)` it throws the following exceptions:

> Exception thrown: 'System.ObjectDisposedException' in System.Net.Sockets.dll
> Exception thrown: 'System.Net.Sockets.SocketException' in Pipelines.Sockets.Unofficial.dll
> Exception thrown: 'System.ObjectDisposedException' in System.Net.Sockets.dll
> Exception thrown: 'System.InvalidOperationException' in System.IO.Pipelines.dll
> Exception thrown: 'System.InvalidOperationException' in System.IO.Pipelines.dll
> Exception thrown: 'System.ObjectDisposedException' in System.Net.Sockets.dll
> Exception thrown: 'System.InvalidOperationException' in System.IO.Pipelines.dll 

Creating with this code:

```c#
ConfigurationOptions options = new ConfigurationOptions()
{
    CommandMap = CommandMap.Sentinel,
    AllowAdmin = true,
    TieBreaker = "",
    ServiceName = "Sentinel",
    SyncTimeout = 5000,
    AbortOnConnectFail = false
};

//Add endpoints
nodes.ForEach(
    node =>
    {
        options.EndPoints.Add(node.Host, node.Port);
    }
);

IConnectionMultiplexer sentinelMultiplexer = ConnectionMultiplexer.Connect(options);
```

I close it like this:

```c#
try
 {
        sentinelMultiplexer.Close(false);

        //UNCOMMENTING THIS MAKES NO DIFFERENCE
        //sentinelMultiplexer.Dispose();
    }
    catch (Exception e)
    {
        //THIS IS NEVER REACHED, NO EXCEPTION HERE
        System.Diagnostics.Debug.WriteLine("Unable to close? " + e);
    }
```

How do I prevent all these errors from being thrown?

**Comment by NickCraver** [comment]
This shouldn't be happening on the latest version, can you confirm you're on 2.0.601 or higher please?

**Comment by zulander1** [comment]
> This shouldn't be happening on the latest version, can you confirm you're on 2.0.601 or higher please?

I still have this issue on 2.2.4
