### ISSUE TITLE
Timeout performing SET {Key}, inst: 0, mgr: Inactive, queue: 2, qu=1, qs=1, qc=0, wr=1/1, in=0/0

### ISSUE THREAD

**Issue by ravi032** [StackExchange/StackExchange.Redis#122]
I am trying to save a 90 KB pdf file  into Azure Redis Cache using StackExchange.Redis client. I have converted that file into byte array and tried to save it using stringSet method and received error. 

Code:

byte[] bytes = File.ReadAllBytes("ABC.pdf");
cache.StringSet(info.Name, bytes);   --> This Line throws exception "Timeout performing SET {Key}, inst: 0, mgr: Inactive, queue: 2, qu=1, qs=1, qc=0, wr=1/1, in=0/0".

Kindly Help.

**Comment by NickCraver** [comment]
@ravi032 any update here? If there's no additional info or current issue in the next few days I'll close this out.
