### ISSUE TITLE
Why Empty string value is treated as no value

### ISSUE THREAD

**Issue by JacekSmi** [StackExchange/StackExchange.Redis#1220]
Hi Team,

We are storing some settings in Redis cache, some of them got are empty value, but while I want to read them I got null instead of an empty string. 
Is there any reason for that? or maybe this could be changed to returns empty string

We are using Microsoft.Extensions.Caching.StackExchangeRedis where they returns value only when HasValue property is true
https://github.com/aspnet/Caching/blob/b7cda012bca34704e5a835ace53a0f879b5f2a2d/src/Microsoft.Extensions.Caching.StackExchangeRedis/RedisCache.cs#L292

but HasValue property for a string value return true only when string.Length > 0 with in my case string is empty but still it is a value 
https://github.com/StackExchange/StackExchange.Redis/blob/55a4e0906098785c72edeb60d48eb8f656f1af33/src/StackExchange.Redis/RedisValue.cs#L133

https://github.com/StackExchange/StackExchange.Redis/blob/55a4e0906098785c72edeb60d48eb8f656f1af33/src/StackExchange.Redis/RedisValue.cs#L124

**Comment by NickCraver** [comment]
In Redis, it's all bytes - so whether it's empty or null...there are no bytes. At the storage layer, there is no difference, so we cannot differentiate a result from it - does that make sense?

**Comment by JacekSmi** [comment]
Yes, thanks for the explanation.
