### ISSUE TITLE
Consider SearchResult<T>

### ISSUE THREAD

**Issue by brunomasantos** [StackExchange/StackExchange.Redis#1222]
Hi,

Did you consider, or think it makes sense to have a `SearchResult<T>` in the NRediSearch package that instead of returning a `List<Document>` returns a `List<T>`?

I think it would be a nice add-on to the library.

Thanks.

**Comment by mgravell** [comment]
OK, but:

- what is the difference between `SearchResult<T>` and `List<T>`?
- what is the relationship between `Document` and `T`?
- what is the relationship between the underlying raw data and `T`? how is it marshalled?
- etc

In principle: fine - but it needs a lot of consideration to understand the details.

**Comment by brunomasantos** [comment]
Of course, there is a lot to consider. I wanted to make sure the discussing made sense before starting:

In my case I find myself having SearchResults typed as `Document` and then converting them to specific objects in my application. It would be nice if I could have the SearchResult list typed with my specific type.

About the relationship, I imagine, for instance, the user of the library being able to define the deserializer to use.

If in principle it's fine I can try to do some draft work and propose and we can discuss it from there

**Comment by NickCraver** [comment]
They may be best as an extension method on top of the base library (which keeps serialization options separate) then an addition to the base client. @brunomasantos any thoughts on that front?

**Comment by NickCraver** [comment]
Without more info, closing out to cleanup here.
