### ISSUE TITLE
We have a timeout in the docker environment

### ISSUE THREAD

**Issue by lzghuluwa** [StackExchange/StackExchange.Redis#1223]
We're using the latest version(StackExchange  v2.0601),With docker deployment, the following timeouts occur, and we are looking forward to providing solutions accordingly。

The situation is as follows
One or more errors occurred. (Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5003ms elapsed, timeout is 5000ms), command=GET, next: GET docker_Test, inst: 0, qu: 0, qs: 15, aw: False, rs: ReadAsync, ws: Idle, in: 4662, in-pipe: 0, out-pipe: 0, serverEndpoint: Unspecified/r-2zea7bea848d30c4.redis.rds.aliyuncs.com:6379, mgr: 10 of 10 available, clientName: AP03_City, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=15,Free=32752,Min=2,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)) at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

**Comment by NickCraver** [comment]
It looks like you're connecting to a remote cloud endpoint - what size payloads are we talking about? The thread count of 15 doesn't appear that busy (but might be if there's very little CPU power to the container) - it seems more likely you have a general latency issue to the provider and 5000ms may be too low for your needs.
