### ISSUE TITLE
Maintain message ordering for multiple channels

### ISSUE THREAD

**Issue by erik-neumann** [StackExchange/StackExchange.Redis#1224]
We're using `Subscribe(channel).OnMessage()` to subscribe to multiple channels by individual calls to Subscribe() per channel. Now it seems that for each channel subscription a separate message queue is maintained. Which is technically correct, but we're missing the possibility to have multiple channels to be handled via one MessageQueue.

Don't know if this would make sense. The reason why I'm asking is that the message ordering for messages of one channel is maintained, while ordering across channels is not. But we would like to achieve that all messages of all specified channels are handled in (received) order.

The only possibility I'm seeing right now is to subscribe to '*' and then filter received topics on our end. But this is not really a nice solution, as we would get a lot of messages that would be received but thrown away.

According to Redis docs (https://redis.io/topics/pubsub), `Subscribers express interest in one or more channels`. Is there any possibility to achieve this?

**Comment by mgravell** [comment]
That isn't a use-case that we actively target, except for the wildcard solution that you've already discussed. We could potentially add an API for this, but it doesn't exist today. Also note that it won't scale to "cluster".

I wonder whether a redis stream might be a better fit for your needs. Or simply: use a single pub/sub channel.

**Comment by erik-neumann** [comment]
Ok, good to know. Thanks for the reply.

**Comment by NickCraver** [comment]
Given there's no further activity here - going to close the request out. If we get more in the future we'll re-consider if this functionality is something we should add...but I think existing tech Marc points to above covers the use case far better.
