### ISSUE TITLE
using "StackExchange.Redis.IDatabase.Execute" to run WAIT operation

### ISSUE THREAD

**Issue by impeham** [StackExchange/StackExchange.Redis#1225]
is it possible to use Execute to simulate the "WAIT" operation? i need to write a key and wait for it to be written to all redis replicas in a special use case related to session id - you can see my post in - https://stackoverflow.com/questions/57871559/stackexchange-redis-lacks-the-wait-support/57872825#57872825

**Comment by mgravell** [comment]
I've updated my answer on that post to illustrate, but please pay attention to the key point about blocking operations not being supported. In advance: if it causes stability problems: "yes, that's why it isn't exposed".

**Comment by impeham** [comment]
Thanks :)

**Comment by impeham** [comment]
a new question about this issue: https://stackoverflow.com/questions/57944952/using-net-stackexchange-redis-with-wait-isnt-working-as-expected

wait doesn't seem to work as expected - maybe i'm missing something there?

**Comment by mgravell** [comment]
Ultimately I have explained why this is not supported. I gave a workaround that might have worked, with huge caveats: if it doesn't work it doesn't work.

At this point, all I can say is: "yes, as I said: this scenario ***is not supported**".

**Comment by impeham** [comment]
Thanks

**Comment by NickCraver** [comment]
Closing out to cleanup :)

**Comment by mgravell** [comment]
@LirazShay anything that blocks a connection is likely to cause problems; I am actively working on some changes to enable this scenario, but: I do not recommend attempting to hack it in yourself right now. The library tries to detect stalled connections: this will qualify as stalled.

**Comment by LirazShay** [comment]
@mgravell 
Thanks a lot for the quick response!!
Also thank you for working on allowing it
This is very important for us, since as explained [here](https://stackoverflow.com/questions/33629339/can-the-wait-command-provide-strong-consistency-in-redis)
 the only way to achieve strong consistency in Redis is by using the WAIT command, (not for all scenarios but for few critical flows)

**Comment by LirazShay** [comment]
Can we open feature request to add the WAIT command to the API of your library?

**Comment by mgravell** [comment]
If is just one example of a category of blocking operations that I'm
already very aware of for the pool work. I'd say "no for now"

**Comment by kharabasz** [comment]
@mgravell came across this thread and wanted to ask if you were able to refactor the library to allow for scenarios that use wait?

**Comment by Existente** [comment]
@mgravell , @NickCraver : I also came across this thread and wanted to ask if you were able to refactor the library to allow for scenarios that use wait?
