### ISSUE TITLE
Timeout performing for sync call for version 2.0.601

### ISSUE THREAD

**Issue by humayun-ahmed** [StackExchange/StackExchange.Redis#1227]
--All calls are sync
--"StackExchange.Redis" version="2.0.601"
--Aws Redis: In aws redis CloudWatch didn't notice any problem

But very often getting timeout error

Error:
----------------------------------------------
Timeout performing UNLINK (1000ms), next: HGETALL DivisionSettingsData_93617, inst: 15, qu: 0, qs: 3, aw: False, rs: ReadAsync, ws: Idle, in: 5, in-pipe: 3226, out-pipe: 0, serverEndpoint: 172.26.103.219:6379, mgr: 10 of 10 available, clientName: NLC1DEOL147, PerfCounterHelperkeyHashSlot: 8934, IOCP: (Busy=1,Free=999,Min=8,Max=1000), WORKER: (Busy=40,Free=32727,Min=8,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts):
Timeout performing UNLINK (1000ms), next: HGETALL DivisionSettingsData_93617, inst: 15, qu: 0, qs: 3, aw: False, rs: ReadAsync, ws: Idle, in: 5, in-pipe: 3226, out-pipe: 0, serverEndpoint: 172.26.103.219:6379, mgr: 10 of 10 available, clientName: NLC1DEOL147, PerfCounterHelperkeyHashSlot: 8934, IOCP: (Busy=1,Free=999,Min=8,Max=1000), WORKER: (Busy=40,Free=32727,Min=8,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
at System.Environment.get_StackTrace()

Error:
------------------------------------------------
Timeout performing GET (1000ms), next: *** inst: 0, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 378134, out-pipe: 0, serverEndpoint: 172.26.102.216:6379, mgr: 10 of 10 available, clientName: NLC1DEOL121, PerfCounterHelperkeyHashSlot: 3805, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=2046,Min=8,Max=2047), v: 2.0.601
Stack trace

**Comment by tnachshon** [comment]
https://github.com/StackExchange/StackExchange.Redis/issues/1226#issuecomment-540778415

**Comment by NickCraver** [comment]
From your errors we can see the inbound pipe has a 378K payload in there - that's _huge_. It looks like you're pulling back a very large hashset all at once, and that's delaying the other operations behind it on the pipe.

Your best options are generally:
1. Not do that, be more selectively get less data from Redis in that single operation.
2. Use a separate `ConnectionMultiplexer` for big and bulky operations (with a higher timeout).
3. Use a higher timeout for everything, and accept a brief stall on the shared pipe when this huge fetch happens.

Does that help?

**Comment by NickCraver** [comment]
Without more info here - closing this out to cleanup.
