### ISSUE TITLE
2 Redis server connections per ConnectionMultiplexer

### ISSUE THREAD

**Issue by kgoderis** [StackExchange/StackExchange.Redis#1228]
I use StackExchange.Redis to access an Azure Redis Cache server, which is a service that is bound to a maximum of number of connections depending on the service level paid for.

We have noticed that for each ConnectionMultiplexer 2 connections are maintained to the Redis Server, thereby effectively limiting us to half the service level we pay for. This problem also occurs with the equivalent AWS service. 

More details and a discussion can be found here https://github.com/imperugo/StackExchange.Redis.Extensions/issues/185#issuecomment-531673187

**Comment by muhamad-ahsan** [comment]
I have the same problem and need to reduce the number of connections. This very crucial especially if you are using the Redis cache as PAS (platform as a service).

**Comment by mgravell** [comment]
The two connections are because a combination of:

1. the API subscribes to some config pub/sub channels by default
2. RESP v2 doesn't allow pub/sub and interactive commands on the same connection

At some point we will look at RESP v3 (Redis v6+), which may help us avoid the first point, but in combination there's *increasing* pressure for us to implement pooled / dedicated connections, which would act *contrary* to your goals here (note to self: ensure that we make this configurable).

But: to disable this, just set the `ConfigurationChannel` to an empty string in the `ConfigurationOptions` (note: not `null`; it must be `""`); or `configChannel=;` in the configuration string.

Alternatively, and perhaps more robustly: you can disable pub/sub *completely* by telling the config to disable the `SUBSCRIBE` command; this is a little more complex as it involves "command maps" - so: try setting the config channel to `""` first.

**Comment by kgoderis** [comment]
@mgravell FYI, we ar already use the connection pool manager of StackExchange.Redis.Extensions. Even then, we notice in some or our applications that we need at pools of at least 100+ connections in order to avoid time-outs (that is on Azure) and alike.

**Comment by mgravell** [comment]
I can make no comment in relation to `StackExchange.Redis.Extensions`; I know nothing about that, and it isn't mine.

**Comment by kgoderis** [comment]
> I can make no comment in relation to `StackExchange.Redis.Extensions`; I know nothing about that, and it isn't mine.

It works rather well, it implements a pool of ConnectionMultiplexers that are ranked based on the number of operations that occur on them, and so, load-balance themselves each time a client requests a connection. 

I will give your suggestion a go

**Comment by msyihchen** [comment]
https://stackoverflow.com/questions/28145865/stackexchange-redis-why-does-connectionmultiplexer-connect-establishes-two-clien

**Comment by NickCraver** [comment]
Looks like we're answered and good here - closing out to tidy up!

**Comment by rodzac** [comment]
Hey @mgravell, I didn't have success setting `ConfigurationChannel = "",` on my ConfigurationOptions. The lib is still creating 2 connections after calling the connect method. 

I'm running dotnet 7 and StackExchange.Redis 2.6.122.

Code:
```dotnet

using StackExchange.Redis;

var config = new ConfigurationOptions
{
    EndPoints = { "localhost:6379" },
    SocketManager = SocketManager.Shared,
    ConfigurationChannel = "",
};

var connection = ConnectionMultiplexer.Connect(config);

Thread.Sleep(5000);

Console.WriteLine("-----> test is done");
```

redis output
```
127.0.0.1:6379> client list
id=34 addr=172.17.0.1:38854 laddr=172.17.0.2:6379 fd=9 name=pop-os(SE.Redis-v2.6.122.38350) age=2 idle=2 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=22400 events=r cmd=info user=default redir=-1 resp=2 lib-name=SE.Redis lib-ver=2.6.122.38350
id=35 addr=172.17.0.1:38866 laddr=172.17.0.2:6379 fd=10 name=pop-os(SE.Redis-v2.6.122.38350) age=2 idle=2 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=22400 events=r cmd=echo user=default redir=-1 resp=2 lib-name=SE.Redis lib-ver=2.6.122.38350
```

Is there anything that I've missed?

**Comment by mgravell** [comment]
You can disable `subscribe`; the easiest way to do that is via the config string approach - append `,$subscribe=` to your existing string; you can also do this via the code API via `CommandMap`

**Comment by mgravell** [comment]
Note that we hope to have RESP3 support soon - which pushes pub/sub onto the single primary connection - but this won't help on a V2 server
