### ISSUE TITLE
Support HSTRLEN command

### ISSUE THREAD

**Issue by eitanhs** [StackExchange/StackExchange.Redis#1238]
Hi,
I see that there is currently no implementation of the [HSTRLEN](https://redis.io/commands/hstrlen) command.
IMHO, it should be trivial to implement.
If you wish, I can provide PR with implementation.
Thanks!

**Comment by mgravell** [comment]
PR with tests would be great

**Comment by eitanhs** [comment]
> PR with tests would be great
#1241
