### ISSUE TITLE
System.ObjectDisposedException Object name: 'System.Net.Sockets.Socket'.

### ISSUE THREAD

**Issue by sanpate** [StackExchange/StackExchange.Redis#1244]
We are seeing several RedisConnectionExceptions particularly when our service is restarted. The root cause is:
**Unable to write data to the transport connection: Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket'**

Looking further into stacktrace it appears that exception is getting thrown when actual Redis operation is performed (as opposed to during initial connection). We are disposing connections on our side (calling Dispose on ConnectionMultiplexer instance inside Dispose method of IDisposable service class). What could be the reason for Redis ConnectionMultiplexer to use disposed socket objects? 

Here is the detailed stacktrace:
<pre>
[{"outerId":"0","message":"An error occurred while reading the key ring.",
"parsedStack":[
{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=","method":"StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl","level":0,"line":2232,"fileName":"C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\ConnectionMultiplexer.cs"},
{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=","method":"StackExchange.Redis.RedisBase.ExecuteSync","level":1,"line":54,"fileName":"C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\RedisBase.cs"},
{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=","method":"StackExchange.Redis.RedisDatabase.ListRange","level":2,"line":955,"fileName":"C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\RedisDatabase.cs"},
{"assembly":"Microsoft.AspNetCore.DataProtection.StackExchangeRedis, Version=2.2.5.0, Culture=neutral, PublicKeyToken=","method":"Microsoft.AspNetCore.DataProtection.StackExchangeRedis.RedisXmlRepository+<GetAllElementsCore>d__4.MoveNext","level":3,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.Collections.Generic.List`1.AddEnumerable","level":4,"line":0},
{"assembly":"System.Linq, Version=4.2.0.0, Culture=neutral, PublicKeyToken=","method":"System.Linq.Enumerable.ToList","level":5,"line":0},
{"assembly":"Microsoft.AspNetCore.DataProtection.StackExchangeRedis, Version=2.2.5.0, Culture=neutral, PublicKeyToken=","method":"Microsoft.AspNetCore.DataProtection.StackExchangeRedis.RedisXmlRepository.GetAllElements","level":6,"line":0},
{"assembly":"Microsoft.AspNetCore.DataProtection, Version=2.2.0.0, Culture=neutral, PublicKeyToken=","method":"Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys","level":7,"line":0},
{"assembly":"Microsoft.AspNetCore.DataProtection, Version=2.2.0.0, Culture=neutral, PublicKeyToken=","method":"Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore","level":8,"line":0},
{"assembly":"Microsoft.AspNetCore.DataProtection, Version=2.2.0.0, Culture=neutral, PublicKeyToken=","method":"Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing","level":9,"line":0},
{"assembly":"Microsoft.AspNetCore.DataProtection, Version=2.2.0.0, Culture=neutral, PublicKeyToken=","method":"Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore","level":10,"line":0}],"type":"StackExchange.Redis.RedisConnectionException","id":"63747649","severityLevel":"Error"},{"outerId":"63747649","message":"SocketFailure (0-read, 0-sent) on <redis endpoint>:6380/Interactive, Flushing/NotStarted, last: CONFIG, origin: OnEstablishingAsyncAwaited, outstanding: 3, last-read: 6s ago, last-write: 0s ago, keep-alive: 180s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.0.601.3402",

"parsedStack":[
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":0,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":1,"line":0},
{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=","method":"StackExchange.Redis.TaskExtensions+<TimeoutAfter>d__9.MoveNext","level":2,"line":49,"fileName":"C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\TaskExtensions.cs"},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":3,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":4,"line":0},
{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=","method":"StackExchange.Redis.ConnectionMultiplexer+<WaitAllIgnoreErrorsAsync>d__72.MoveNext","level":5,"line":672,"fileName":"C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\ConnectionMultiplexer.cs"}],"type":"StackExchange.Redis.RedisConnectionException","id":"58595508","severityLevel":"Error"},{"outerId":"58595508","message":"Unable to write data to the transport connection: Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket'..",

"parsedStack":[
{"assembly":"System.Net.Sockets, Version=4.2.0.0, Culture=neutral, PublicKeyToken=","method":"System.Net.Sockets.NetworkStream.WriteAsync","level":0,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Stream.WriteAsync","level":1,"line":0},{"assembly":"System.Net.Security, Version=4.1.0.0, Culture=neutral, PublicKeyToken=","method":"System.Net.Security.SslStreamInternal.StartWriting","level":2,"line":0},
{"assembly":"System.Net.Security, Version=4.1.0.0, Culture=neutral, PublicKeyToken=","method":"System.Net.Security.SslStreamInternal.ProcessWrite","level":3,"line":0},
{"assembly":"System.Net.Security, Version=4.1.0.0, Culture=neutral, PublicKeyToken=","method":"System.Net.Security.SslStream.BeginWrite","level":4,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Stream+<>c.<BeginEndWriteAsync>b__55_0","level":5,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.Threading.Tasks.TaskFactory`1.FromAsyncTrim","level":6,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Stream.BeginEndWriteAsync","level":7,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Stream.WriteAsync","level":8,"line":0},{"assembly":"Pipelines.Sockets.Unofficial, Version=1.0.0.0, Culture=neutral, PublicKeyToken=","method":"Pipelines.Sockets.Unofficial.StreamConnection+AsyncStreamPipe.WriteBuffer","level":9,"line":190,"fileName":"C:\\Code\\Pipelines.Sockets.Unofficial\\src\\Pipelines.Sockets.Unofficial\\StreamConnection.AsyncStreamPipe.cs"},{"assembly":"Pipelines.Sockets.Unofficial, Version=1.0.0.0, Culture=neutral, PublicKeyToken=","method":"Pipelines.Sockets.Unofficial.StreamConnection+AsyncStreamPipe+<CopyFromWritePipeToStream>d__20.MoveNext","level":10,"line":148,"fileName":"C:\\Code\\Pipelines.Sockets.Unofficial\\src\\Pipelines.Sockets.Unofficial\\StreamConnection.AsyncStreamPipe.cs"},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":11,"line":0},
{"assembly":"System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Pipelines.PipeCompletion.ThrowLatchedException","level":12,"line":0},
{"assembly":"System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Pipelines.Pipe.GetFlushResult","level":13,"line":0},
{"assembly":"System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Pipelines.Pipe.FlushAsync","level":14,"line":0},
{"assembly":"System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Pipelines.Pipe+DefaultPipeWriter.FlushAsync","level":15,"line":0},
{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=","method":"StackExchange.Redis.PhysicalConnection.FlushAsync","level":16,"line":907,"fileName":"C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\PhysicalConnection.cs"},
{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=","method":"StackExchange.Redis.PhysicalBridge.WriteMessageTakingWriteLockSync","level":17,"line":736,"fileName":"C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\PhysicalBridge.cs"},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":18,"line":0},
{"assembly":"System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Pipelines.PipeCompletion.ThrowLatchedException","level":19,"line":0},
{"assembly":"System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Pipelines.Pipe.GetFlushResult","level":20,"line":0},
{"assembly":"System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Pipelines.Pipe.FlushAsync","level":21,"line":0},
{"assembly":"System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.IO.Pipelines.Pipe+DefaultPipeWriter.FlushAsync","level":22,"line":0},
{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=","method":"StackExchange.Redis.PhysicalConnection.FlushAsync","level":23,"line":289,"fileName":"C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\PhysicalConnection.cs"},
{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=","method":"StackExchange.Redis.ServerEndPoint+<HandshakeAsync>d__112.MoveNext","level":24,"line":802,"fileName":"C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\ServerEndPoint.cs"},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":25,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":26,"line":0},
{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=","method":"StackExchange.Redis.ServerEndPoint+<OnEstablishingAsyncAwaited>d__91.MoveNext","level":27,"line":491,"fileName":"C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\ServerEndPoint.cs"}],"type":"System.IO.IOException","id":"57719578","severityLevel":"Error"},{"outerId":"57719578","message":"Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket'.",

"parsedStack":[
{"assembly":"System.Net.Sockets, Version=4.2.0.0, Culture=neutral, PublicKeyToken=","method":"System.Net.Sockets.Socket.SendAsync","level":0,"line":0},
{"assembly":"System.Net.Sockets, Version=4.2.0.0, Culture=neutral, PublicKeyToken=","method":"System.Net.Sockets.Socket.SendAsync","level":1,"line":0},
{"assembly":"System.Net.Sockets, Version=4.2.0.0, Culture=neutral, PublicKeyToken=","method":"System.Net.Sockets.NetworkStream.WriteAsync","level":2,"line":0}],"type":"System.ObjectDisposedException","id":"16413634","severityLevel":"Error"}]
</pre>

**Comment by NickCraver** [comment]
This indeed was a potential issue and was fixed in later releases, please grab the latest 2.x to resolve :)
