### ISSUE TITLE
[Question] Do LoadedLuaScripts get cached on all redis endpoints?

### ISSUE THREAD

**Issue by bynho** [StackExchange/StackExchange.Redis#1246]
Hi I have been trying to find out whether we need to load lua scripts for all endpoints in order for it to be cached against all of them,  is it needed?  I have found this question on stackoverflow but no answers: https://stackoverflow.com/questions/31531637/storing-lua-scripts-with-stackexchange-redis

**Comment by mgravell** [comment]
Lua is per-server, yes. The standard API on the library should track where
it thinks it is cached, and deal with it automatically.
