### ISSUE TITLE
Limit to the amount of items added 

### ISSUE THREAD

**Issue by stevetayloruk** [StackExchange/StackExchange.Redis#1247]
Hi, 

I'm using `SortedSetAddAsync(key, docs.ToArray()), where docs is about 2200 items.  But i'm only getting 1797 items added to redis. 

I'm using version 1.2.6 of the library.  If i upgrade, will it solve the issue? or do i need it add in another way?

Thanks

Steve

**Comment by mgravell** [comment]
Are you perhaps as doing duplicate keys? We issue a single varadic zadd
command to redis. There isn't much we can do to impact it in any direction.
My only guess here is: either some of the keys already existed in the
sorted set, or : you have duplicates in the data you're sending.

**Comment by stevetayloruk** [comment]
Yes, that was it. Thanks @mgravell
