### ISSUE TITLE
After upgrade frequently receiving "Timeout performing DEL" and "active" key is irrelevant

### ISSUE THREAD

**Issue by nmathurbkn** [StackExchange/StackExchange.Redis#1249]
We recently upgraded our .NET Framework from  4.6 to 4.7 and did not apply any change in Redis. All was working very smoothly. 

After two days we took our next step and upgraded Redis, now our site is running very slow. We are frequently getting "Timeout performing DEL". The error message is also showing the keys(active:) which is not related to the particular call. 

This is one of the error message: - the call is performing an update to ledgers and the key where we are getting the exception is: "Ledger:101"  (We tracked this from an internal log)

> Timeout performing DEL (3000ms), active: GET Assets:152, next: GET Ledger:503, inst: 1, qu: 0, qs: 62, aw: False, rs: CompletePendingMessage, ws: Idle, in: 0, in-pipe: 27804, out-pipe: 37, serverEndpoint: Unspecified/****-redis.redis.cache.windows.net:6379, mgr: 9 of 10 available, clientName: *********, IOCP: (Busy=0,Free=1000,Min=250,Max=1000), WORKER: (Busy=13,Free=32754,Min=250,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)*

1. RedisSessionStateProvider -> 
_version="2.2.6" targetFramework="net461"_ to
 **version="4.0.1" targetFramework="net47"**

2. StackExchange.Redis ->
 _version "2.0.519" targetFramework="net461"_ to 
**version "2.0.601" targetFramework="net47"**

Redis on production is -> **version 3.2.7**

I can say that in this call "GET Ledger:503" is a valid one (one of the keys we are getting) .. but the key which is showing as "active:" (Assets:152) is from completely different request. 

Can anyone help with this exception, we cannot downgrade the redis version. We also faced [this ](https://github.com/Azure/aspnet-redis-providers/issues/104)issue after the deploy.

**Comment by NickCraver** [comment]
It looks like you have a decently-sized payload on the inbound pipe coming back from Redis ahead of the delete command that's timing out. Is that ledger fairly large? If so, we're talking about not getting to the next until until after we should have (dictated by the timeout). If the large Ledger is acceptable and you're in the cloud, a 3000ms timeout may just be too low. Unfortunately you're at the mercy of a third-party network and there is latency involved, that's the default timeouts for Azure connections are higher to compensate.
