### ISSUE TITLE
Scoring in RediSearch

### ISSUE THREAD

**Issue by jjchiw** [StackExchange/StackExchange.Redis#1251]
Hi!

Do you have any plans to add Scoring to NRediSearch?

`FT.SEARCH myIndex "foo" SCORER TFIDF.DOCNORM`

https://oss.redislabs.com/redisearch/Scoring.html

I can submit a PR....

Thanks for the great library :)

**Comment by caiomarruda** [comment]
Hi @jjchiw , what the version of StackExchange.redis that you are using now?
I am trying to use the latest version (2.0.601) but can´t work.

**Comment by NickCraver** [comment]
Resolved in #1254 - thanks all!
