### ISSUE TITLE
Timeout Exception message doesn't state which thread-pool statistics are describing in 2.0

### ISSUE THREAD

**Issue by thwagne** [StackExchange/StackExchange.Redis#1252]
I have been receiving a number of Timeout Exceptions with messages like “EVAL; IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=28,Free=32739,Min=1,Max=32767), Local-CPU: n/a". I see from [this doc page](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Timeouts.md#are-you-seeing-high-number-of-busyio-or-busyworker-threads-in-the-timeout-exception) that this data could be describing either the dedicated Redis.StackExchange thread pool or the .Net global thread pool. Since it appears to me that my issue could be resolved by increasing the minimum number of worker threads I would like to know which thread pool this is so that I can make a fix targeting that thread pool, but I don't see how I could make that judgement from this error message.

**Comment by daniel-elsner** [comment]
@thwagne  Did you ever figure this out? I'm in the exact same situation and I'm not sure which threadpool needs expanding.

**Comment by thwagne** [comment]
@daniel-elsner from what I was able to gather this error message is reporting on the global threadpool
https://github.com/StackExchange/StackExchange.Redis/blob/3f7e5466c6bbff96a3ed1130b637a097d21f3fed/src/StackExchange.Redis/PerfCounterHelper.cs#L67

But I'm not sure that's the threadpool you'll want to expand.
https://github.com/mgravell/Pipelines.Sockets.Unofficial/blob/master/src/Pipelines.Sockets.Unofficial/DedicatedThreadPoolPipeScheduler.cs

**Comment by NickCraver** [comment]
There is only one global thread pool, so yep - that's it! Closing this out to cleanup, thanks @thwagne for getting to this early.
