### ISSUE TITLE
NRediSearch don´t work with latest version

### ISSUE THREAD

**Issue by caiomarruda** [StackExchange/StackExchange.Redis#1253]
Hello Everyone,
I am testing NRediSearch with StackExchange.Redis in my application and NRediSearch is not working on the latest version of StackExchange.Redis (2.0.601), works only on version 1.2.6.0.

![image](https://user-images.githubusercontent.com/7254083/66922376-dbdeaf00-f01e-11e9-8401-a5ffcfdcec41.png)

Can someone help me understand if redisearch has been discontinued in the current version?

Thank you.

**Comment by gkorland** [comment]
@caiomarruda did you manage to make it work?

**Comment by caiomarruda** [comment]
Hi @gkorland I have installed the alpha version (2.0.0-alpha.169) and worked fine with the latest version of StackExchange.
In my github I´ve developed a repository of that.

**Comment by caiomarruda** [comment]
> @caiomarruda did you manage to make it work?

Hi @gkorland I have installed the alpha version (2.0.0-alpha.169) and worked fine with the latest version of StackExchange.
In my github I´ve developed a repository of that.

**Comment by mgravell** [comment]
Hi; I'll try to make sure an updated version of this gets deployed to nuget. mea cupla.

**Comment by caiomarruda** [comment]
> Hi; I'll try to make sure an updated version of this gets deployed to nuget. mea cupla.

Hi @mgravell , nice! I am waiting to test it :)
