### ISSUE TITLE
KEYS IEnumerable .. potential duplicates handled?

### ISSUE THREAD

**Issue by chrisaut** [StackExchange/StackExchange.Redis#1255]
Sorry I could not find these answers in the docs.

I need to iterate via Keys(...) ... (yes, I know of the blocking/perf implications).
My understanding is internally this usually maps to SCAN whenever possible, which is basically always for a modern redis instance.

Does the IEnumerable yield keys as soon as any one page has been retrieved, or does it only start yielding when they all have been retrieved?
And does it internally handle (aka avoid/filter) the possible duplicate keys that SCAN may return?

May I suggest these details be included in the documentation [here?](https://stackexchange.github.io/StackExchange.Redis/KeysScan)

Thanks

**Comment by mgravell** [comment]
> Does the IEnumerable yield keys as soon as any one page has been retrieved, or does it only start yielding when they all have been retrieved?

The first one

> And does it internally handle (aka avoid/filter) the possible duplicate keys that SCAN may return?

No. If you want that, use LINQ's `Distinct()` or similar, but understand that for large data sets *this has cost*

Additionally, note that we'll add an `IAsyncEnumerable<T>` version of these as soon as I'm in the code next

**Comment by chrisaut** [comment]
Thanks for the quick answers, appreciated.

> Additionally, note that we'll add an `IAsyncEnumerable<T>` version of these as soon as I'm in the code next

Unfortunately we're still on 2.2 for a while longer, but good to know for the future. Thanks

**Comment by mgravell** [comment]
2.2 here meaning `netcoreapp2.2`? that's fine: you can still use it; we'll add a dependency to [Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/), which makes the APIs available for use *basically* everywhere.
