### ISSUE TITLE
Some timeout cases

### ISSUE THREAD

**Issue by czd890** [StackExchange/StackExchange.Redis#1256]
After switching from `ServiceStack.Redis` to `StackExchange.Redis`, there have been some timeout cases.

Server: aws fargate (2CPU,4GB)
Reqeusts: 10+/s
Server CPU(AVG): 20% or less

Timeout exceptions:
[timeout.xlsx](https://github.com/StackExchange/StackExchange.Redis/files/3754726/timeout.xlsx)

My application service CPU:
![image](https://user-images.githubusercontent.com/4011549/67274579-50b85a00-f4f3-11e9-86bb-de6631ac73ed.png)
Redislab db:
![image](https://user-images.githubusercontent.com/4011549/67274687-8fe6ab00-f4f3-11e9-9e5f-9b43ee47f226.png)

**Comment by NickCraver** [comment]
It looks like your timeouts are generally in the 2-3 second range.

What was your timeout (or was there one?) on the old configuration, and what is it on the new configuration? If there wasn't a timeout before and we're adding one now, it may just be a timeout _you don't want_, and the 2-3,000 milliseconds is fine. If that's the case, we just need to adjust your timeout on the connection string and call it a day.

**Comment by czd890** [comment]
My connectionstr is "***,12415,connectTimeout=2000,responseTimeout=2000,syncTimeout=2000";
And get keys and response datas for each request are small.

Root reason: exists slow querys. `keys ***` in shell. 😓
