### ISSUE TITLE
In the case of debugging, the method used in the instant window gets the value exception.

### ISSUE THREAD

**Issue by caisimongit** [StackExchange/StackExchange.Redis#1258]
"IDatabase" works fine when the program is running normally, but when I open debugging, I will get an exception when I want to get a value in Redis temporarily. This problem will also occur when using fast monitoring, "IDatabase" Can't I work in debug mode? Or am I overlooking other settings?

I don't know if you can understand what I mean? I am translating through Google Translate, I hope I can get help, thank you very much!

v 2.0.601

```
IConnectionMultiplexer = connectionMultiplexer;
            var db= IConnectionMultiplexer.GetDatabase();
            var name = db.StringGet("name");
```

```
db.StringGet("name")
'db.StringGet("name")' threw an exception of type 'StackExchange.Redis.RedisTimeoutException'
    Commandstatus: Sent
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233083
    HelpLink: "https://stackexchange.github.io/StackExchange.Redis/Timeouts"
    InnerException: null
    Message: "Timeout performing GET (5000ms), next: GET name, inst: 1, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 23, serverEndpoint: Unspecified/localhost:6379, mgr: 10 of 10 available, clientName: DESKTOP-CH4V9V8, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=4,Free=32763,Min=8,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)"
    Source: "StackExchange.Redis"
    StackTrace: "   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\ConnectionMultiplexer.cs:line 2258\r\n   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\RedisBase.cs:line 54\r\n   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in C:\\projects\\stackexchange-redis\\src\\StackExchange.Redis\\RedisDatabase.cs:line 2281"
    TargetSite: {T ExecuteSyncImpl[T](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor`1[T], StackExchange.Redis.ServerEndPoint)}
```

**Comment by mgravell** [comment]
Can I clarify the question here; are you saying that *when paused in the
debugger*, you are issuing commands, which then don't work?

Unfortunately, I don't think that is something we can achieve readily.
Because the API is designed for concurrency, there is a lot of machinery
going on relating to threading. If all of the interesting threads are in a
pause state: the right things aren't going to happen.

We have discussed the possibility of leasing dedicated connections from a
pool; this doesn't exist today, but that *might* support this scenario.

**Comment by caisimongit** [comment]
I see. I'm looking forward to supporting this situation. Thank you for your reply.

**Comment by NickCraver** [comment]
Going to close this out for now to tidy up - in general this is a tradeoff with a pipelined client and a "nature of the beast" situation. The only viable workaround at the moment is a sky-high timeout if you want to step through in this manner.
