### ISSUE TITLE
client behaviour after cluster update

### ISSUE THREAD

**Issue by neilwashere** [StackExchange/StackExchange.Redis#1259]
We have a 2 node redis instance in AWS which we connect to using a single address. Both nodes were updated, one at a time. Afterwards the redis client would seem to randomly be unable to retrieve values that were just set a moment before. No errors (that I can see). Restarting the service (and re-establishing a connection to the cluster) resolved the issue.

Despite using a single address it seemed like we had lost access to one of the nodes. What is happening in the client and what configuration would be required to guard against this in the future?

**Comment by NickCraver** [comment]
Looks like you're hitting the issue in #1120 to be resolved by #1374 - folding this issue into those. Look out for a 2.1.x release with fixes soon!
