### ISSUE TITLE
Healthcheck for pub/sub ?

### ISSUE THREAD

**Issue by ideapad** [StackExchange/StackExchange.Redis#1261]
If I already have [healthcheck ](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks)for Redis connection, do I need have it for pub/sub too ?
Does connection checking cover pub/sub functionality ?

**Comment by NickCraver** [comment]
The healthcheck (heartbeat) inside the library is handling this. So checking `.IsConnected` would cover both scenarios here.

Closing out just to cleanup but if there are more questions I'm happy to re-open :)
