### ISSUE TITLE
Timeouts when system runs out of memory

### ISSUE THREAD

**Issue by TomGullen** [StackExchange/StackExchange.Redis#1262]
We're trying to diagnose and solve a problem where Redis locks up and continually times out for all requests.  The only way to resolve this issue is to reboot the server.  We're using StackExchange.Redis 2.0.601

We've spent a long time looking and trying to solve this issue, and we think the cause of this issue is triggered when the machine runs out of memory and starts paging the memory.

Are there any known bugs when a system encounters this that might cause Redis to lock up, lose its connection state etc?

We've tried the following:

- Following all best practises in guides (lazy connections etc)
- Experimenting with increasing max/min thread counts on machines
- Not having one Redis connection but a small pool of them which are cycled through
 - Upgrading system disks to premium SSD's on Azure

None of these seem to help.  Only increasing the RAM on the machine seems to keep these errors at bay, but this is expensive and unnecessary, our application can run on much lower powered machines.

Here are some of the event viewer logs for the most recent outage:

> Windows successfully diagnosed a low virtual memory condition. The following programs consumed the most virtual memory: w3wp.exe (1820) consumed 5598658560 bytes, MonitoringHost.exe (2800) consumed 153264128 bytes, and MsMpEng.exe (756) consumed 143536128 bytes.

> Data was found in the output, but has been dropped because the Event Policy for the process started at 4:08:25 PM has detected errors.   The 'ExitCode' policy expression:
> 	[^0]+
>  matched the following output:
> 	3 
> 
> Command executed:	"C:\Windows\system32\cscript.exe" /nologo "MonitorKnowledgeDiscovery.vbs"
> Working Directory:	C:\Program Files\Microsoft Monitoring Agent\Agent\Health Service State\Monitoring Host Temporary Files 31\517\ 
> 
> One or more workflows were affected by this.  
> 
> Workflow name: Microsoft.SystemCenter.Advisor.AgentHealth.KnowledgeDiscoveryMonitor 
> Instance name:  
> Instance ID: {E56F54A9-1A18-0E2F-D86D-467DD9F5457F} 
> Management group: AOI-2777d049-4123-42f2-bd3c-a096cf6d637d

> The Windows logon process has unexpectedly terminated.

Then around a minute later, lots of events in this form:

> Event code: 3005 
> Event message: An unhandled exception has occurred. 
> Event time: 10/28/2019 4:10:35 PM 
> Event time (UTC): 10/28/2019 4:10:35 PM 
> Event ID: 086835b74bff4308a8088e2c39d22041 
> Event sequence: 135153 
> Event occurrence: 176 
> Event detail code: 0 
>  
> Application information: 
>     Application domain: /LM/W3SVC/1/ROOT-1-132167498911804292 
>     Trust level: Full 
>     Application Virtual Path: / 
>     Application Path: C:\inetpub\wwwroot\ 
>     Machine name: PRD-VM-WEB-2 
>  
> Process information: 
>     Process ID: 1820 
>     Process name: w3wp.exe 
>     Account name: IIS APPPOOL\DefaultAppPool 
>  
> Exception information: 
>     Exception type: TimeoutException 
>     Exception message: The operation has timed out.
>    at StackExchange.Redis.ConnectionMultiplexer.Wait(Task task) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 539

> Thread information: 
>     Thread ID: 652 
>     Thread account name: IIS APPPOOL\DefaultAppPool 
>     Is impersonating: False 
>     Stack trace:    at StackExchange.Redis.ConnectionMultiplexer.Wait(Task task) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 539
>    at StackExchange.Redis.RedisSubscriber.StackExchange.Redis.ISubscriber.Subscribe(RedisChannel channel, Action`2 handler, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisSubscriber.cs:line 471
>    at C3.Code.Controls.Application.Caching.Redis.PubSub.PubSubController.SubscribeToCacheKey(RedisChannel cacheKey, Action`2 onMessageReceived) in 

> 
> Event code: 3005 
> Event message: An unhandled exception has occurred. 
> Event time: 10/28/2019 4:12:36 PM 
> Event time (UTC): 10/28/2019 4:12:36 PM 
> Event ID: c8c08c1b0651433d92602fcaf6aa8964 
> Event sequence: 137769 
> Event occurrence: 930 
> Event detail code: 0 
>  
> Application information: 
>     Application domain: /LM/W3SVC/1/ROOT-1-132167498911804292 
>     Trust level: Full 
>     Application Virtual Path: / 
>     Application Path: C:\inetpub\wwwroot\ 
>     Machine name: PRD-VM-WEB-2 
>  
> Process information: 
>     Process ID: 1820 
>     Process name: w3wp.exe 
>     Account name: IIS APPPOOL\DefaultAppPool 
>  
> Exception information: 
>     Exception type: RedisTimeoutException 
>     Exception message: Timeout performing GET (5000ms), next: GET ArcadeGame.402.VersionRecordIDs, inst: 267, qu: 0, qs: 27, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: Unspecified/Construct3.redis.cache.windows.net:6380, mgr: 10 of 10 available, clientName: PRD-VM-WEB-2, IOCP: (Busy=0,Free=1200,Min=600,Max=1200), WORKER: (Busy=627,Free=15373,Min=600,Max=16000), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
>    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2239
>    at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
>    at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 2281

> Thread information: 
>     Thread ID: 186 
>     Thread account name: IIS APPPOOL\DefaultAppPool 
>     Is impersonating: False 
>     Stack trace:    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2239
>    at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
>    at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 2281

**Comment by TomGullen** [comment]
Fixing the underlying memory leak on our application has resolved this issue.  However, I think it may still be a bug that when the system runs low on memory and starts creating page files, it does appear to cause the above error which can only be resolved by restarting the application.

Not sure if this should be considered a bug or not.

**Comment by NickCraver** [comment]
In general, running out of memory is going to cause _tons_ of issues and timeouts. Either from GC stalls (ever-increasing as you approach the hard limit), or general inability to allocate once you hit it. The fact that you saw Redis issues here with tasks is likely because that's what you're doing the most of (or the most of that has an error log). For example, others will see SQL issues or general granting issues, etc. My point is: once you run out of memory, all bets are off and no behavior is either reasonable or unreasonable: it will be a mix of races for memory, CPU against GC, and really just general chaos.

I'm really glad you fixed the issue with your app! The above is to provide more context for anyone hitting memory issues and finding this in the future, but going to close this out since it's not an issue with the library itself :)
