### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException trying to determine meaning of log data, documentation anywhere?

### ISSUE THREAD

**Issue by john-baker-springshot** [StackExchange/StackExchange.Redis#1263]
We're seeing a growing number of timeout issues with our redis server when performing HGETALL on a hash key, here is an error message from our logs:

"StackExchange.Redis.RedisTimeoutException: Timeout performing HGETALL (5000ms), next: HGETALL keynamehere, inst: 17, qu: 0, qs: 48, aw: False, rs: ReadAsync, ws: Idle, in: 16183, in-pipe: 677, out-pipe: 3354, serverEndpoint: servername, mgr: 10 of 10 available, clientName: clientname, IOCP: (Busy=47,Free=953,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)"

I'm trying to figure out the meaning of some of the higher numbers, mainly in:, in-pipe:, and out-pipe:, but I can't seem to find any documentation anywhere to explain them to help identify the problem, any help/advice is appreciated.

**Comment by NickCraver** [comment]
The pipe counts are telling us specifically what's on the outbound and inbound pipelines vs. the sockets (e.g. where things are being help up). In your case, I'm seeing a large number of active threads, a 5 second timeout, and a full hash fetch. Is it possible that hash is _huge_ and needs a larger timeout in general?
