### ISSUE TITLE
Redis High Availability

### ISSUE THREAD

**Issue by davidop** [StackExchange/StackExchange.Redis#1264]
Hello, first of all thank you for the great work you are doing with this library. I've been using it for a while with a single Redis master (in windows service mode). Given the large influx of connections my APIs are receiving, we are going to mount a balancer with two machines. I have seen that your library has a problem with Redis Sentinel so I would like you to give me your opinion on what would be the best option for the environment that I propose (redis cluster, redis sentinel, redis master / slave). I need Redis to always be available even if any of my production nodes fall.

**Comment by davidop** [comment]
I've seen your failover test and I could more or less fit in, but I just didn't adapt your test to a connection within my application. Does anyone have an example of how to use the MakeMaster () function?

**Comment by davidop** [comment]
Any ideas or examples of use?

**Comment by NickCraver** [comment]
Redis primary and replicas are supported as well as Sentinel now. If you want to use Redis you can use primary/replica, cluster, or a sentinel environment. All are supported by the library - going to close this out to cleanup :)
