### ISSUE TITLE
Lot of operations while retrieving value

### ISSUE THREAD

**Issue by sarkarstanmoy** [StackExchange/StackExchange.Redis#1268]
I want my redis key will never expire so I have given a big expire number

await _redisDatabase.StringSetAsync(key, serializedObject, TimeSpan.FromSeconds(Int32.MaxValue), When.NotExists);

But after every 30 min when every I am trying to retrieve the values in redis cache it is showing multiple operations and taking time.

"subscribe" "Booksleeve_MasterChanged"
1572964169.258388 [0 10.0.1.123:37602] "get" "Booksleeve_TieBreak"
1572964169.258395 [0 10.0.1.123:37602] "get" "Booksleeve_TieBreak"
1572964169.258400 [0 10.0.1.123:37602] "info" "replication"
1572964169.258411 [0 10.0.1.123:37602] "ping"
1572964169.258413 [0 10.0.1.123:37602] "ping"
1572964169.279451 [0 10.0.1.123:37602] "get" "3118"
1572964171.281458 [0 10.0.1.123:37602] "get" "sr-dev-Countries"
1572964185.990889 [0 10.0.2.175:29181] "info" "replication"
1572964185.990960 [0 10.0.2.175:20613] "unsubscribe" "\xab\x1a\xfb\xa5\x8a]RB\x8

**Comment by mgravell** [comment]
there are a number of things involved in establishing a connection with redis, including checking server capabilities (info), and hooking to some pub/sub APIs; for that reason, a `ConnectionMultiplexer` should be considered a long-lived object, and not connected/dispoosed per operation - it should be retained for re-use. The object from `GetDatabase` can be considered cheap.

So: is this because of connect overheads?

**Comment by sarkarstanmoy** [comment]
We are using AWS redis cache and lambda. In my opinion whenever a new lambda spawns a new connection created. Is there any way to make ConnectionMultiplexer global in C# ?

**Comment by SnakyBeaky** [comment]
@sarkarstanmoy every lambda is initialized once and after serving the request, it sticks around serving other requests (AWS will shut down the lambda if no requests are sent in a while).

Also, the amount of lambdas you may have at any time is defined by your function's concurrency setting.

If you wanted to use the same ConnectionMultiplexer throughout the lambda lifetime, you should have it in a static field or if you're using DI (e.g. in AspNetCore), you should register it as a singleton, so all requests share the same instance and it is only created once for each lambda, as @mgravell says.

Singleton's in AspNetCore DI: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.0#singleton

**Comment by NickCraver** [comment]
@SnakyBeaky thanks for detailing that out!

Closing out to cleanup.
