### ISSUE TITLE
WithKeyPrefix randomly complains argument is null

### ISSUE THREAD

**Issue by worldspawn** [StackExchange/StackExchange.Redis#1270]
Hi, I'm having a super weird randomly occurring issue when calling `WithKeyPrefix`. Sometimes (about ~5% of the time) I get an ArgumentException with `"Value cannot be null. Parameter name: keyPrefix"`.

The call is happening in an MS DI service lambda:

```
var redisPrefix = Environment.GetEnvironmentVariable("RedisPrefix");
//...
builder.Services.AddSingleton(p => ConnectionMultiplexer.Connect($"{redisHost},abortConnect=false,ssl=true,password={redisAccesskey}"));
builder.Services.AddScoped(p => .GetService<ConnectionMultiplexer>().GetDatabase().WithKeyPrefix(redisPrefix) );
```

I have added logging and confirmed that 100% of the time redisPrefix is _not null_. Its never null... I've put logs in the lambda itself to confirm before the call its not null yet in some tiny percentage of cases I get this null argument exception.

On the same host it is working _almost_ all of the time. Same host (same instance, config etc) will work 99 times then fail once then continue to work. I cannot account for it at all and in all my logs indicate that I am *never* passing null to WithKeyPrefix.

```
Microsoft.Azure.WebJobs.FunctionFailedException: The activity function 'EventNotify' failed: "Value cannot be null. Parameter name: keyPrefix". See the function execution logs for additional details. ---> System.ArgumentNullException: Value cannot be null. Parameter name: keyPrefix at StackExchange.Redis.KeyspaceIsolation.DatabaseExtensions.WithKeyPrefix(IDatabase database, RedisKey keyPrefix) in 
C:\projects\stackexchange-redis\src\StackExchange.Redis\KeyspaceIsolation\DatabaseExtension.cs:line 49 at Drawboard.SourceFileProcessing.StartUp.<>c__DisplayClass0_0.<Configure>b__8(IServiceProvider p) in /src/dotnet-function-app/Startup.cs:line 44 at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r) in /azure-functions-host-47c594d8ba823cf5a2db5475fbfcbb6d83e7deca/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/DryIocAdapter.cs:line 156 at DryIoc.Registrator.
```

Super confused!

**Comment by mgravell** [comment]
Does `redisPrefix` ever get changed *after* that line? since it is a captured variable, changes after the `AddScoped` will still be observed later

**Comment by worldspawn** [comment]
Hi @mgravell I'm going to close this, its almost certainly something weird going on in my environment. I completely coded away the DI of IDatabase and I still sometimes get an exception from that same line. I think I have a rogue process somewhere... As you were 😄
