### ISSUE TITLE
Timeout performing SETEX

### ISSUE THREAD

**Issue by subodhsubujee** [StackExchange/StackExchange.Redis#1271]
Hey,

Could you please help me with below the error. I often get this error while getting my cached object 'CacheObject_-MasterTenant-PublishedContractType'. But this gets resolved for a while once I flush the cache.

Error  :
StackExchange.Redis.RedisTimeoutException\\\",\\\"Message\\\":\\\"Timeout performing SETEX CacheObject_-MasterTenant-PublishedContractTypes, inst: 2, mgr: Inactive, err: never, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: ijnjtr0vrmwebrl, serverEndpoint: Unspecified/ijnjtr0rdsprmry.redis.cache.windows.net:6380, keyHashSlot: 6360, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=3,Free=32764,Min=16,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)\\\",\\\"Data\\\":{\\\"redis-command\\\":\\\"SETEX CacheObject_-MasterTenant-PublishedContractTypes\\\",\\\"request-sent-status\\\":2,\\\"redis-server\\\":\\\"ijnjtr0rdsprmry.redis.cache.windows.net:6380\\\",\\\"Redis-Message\\\":\\\"SETEX CacheObject_-MasterTenant-PublishedContractTypes\\\",\\\"Redis-Instantaneous\\\":\\\"2\\\",\\\"Redis-Manager-State\\\":\\\"Inactive\\\",\\\"Redis-Last-Error\\\":\\\"never\\\",\\\"Redis-Queue-Length\\\":\\\"2\\\",\\\"Redis-Queue-Outstanding\\\":\\\"0\\\",\\\"Redis-Queue-Awaiting-Response\\\":\\\"2\\\",\\\"Redis-Queue-Completion-Outstanding\\\":\\\"0\\\",\\\"Redis-Active-Writers\\\":\\\"0\\\",\\\"Redis-Write-Queue\\\":\\\"0\\\",\\\"Redis-Inbound-Bytes\\\":\\\"0\\\",\\\"Redis-Active-Readers\\\":\\\"0\\\",\\\"Redis-Client-Name\\\":\\\"ijnjtr0vrmwebrl\\\",\\\"Redis-Server-Endpoint\\\":\\\"Unspecified/ijnjtr0rdsprmry.redis.cache.windows.net:6380\\\",\\\"Redis-Key-HashSlot\\\":\\\"6360\\\",\\\"Redis-ThreadPool-IO-Completion\\\":\\\"(Busy=0,Free=1000,Min=16,Max=1000)\\\",\\\"Redis-ThreadPool-Workers\\\":\\\"(Busy=3,Free=32764,Min=16,Max=32767)\\\",\\\"Redis-Busy-Workers\\\":\\\"3\\\"},\\\"InnerException\\\":null,\\\"HelpURL\\\":\\\"http://stackexchange.github.io/StackExchange.Redis/Timeouts\\\",\\\"StackTraceString\\\":\\\"   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)\\\\r\\\\n   at StackExchange.Redis.RedisBase.ExecuteSync

**Comment by NickCraver** [comment]
Which version of the library were you on here? The latest release should show the timeout involved (it's possible it's too low for your cloud environment), but I can't tell from this dump so it appears you're on an older version. Can you tell us what your version and timeout is?
