### ISSUE TITLE
NRedisSearch or filter inside Redis cache with .net core

### ISSUE THREAD

**Issue by Tameenk** [StackExchange/StackExchange.Redis#1272]
Hello, first of all thank you for the great work i am new in Redis and i trying to use NRedisSearch to make query in our data cached using NRedisSearch so i'll be thankful if anyone give me an exmaple to how to create index and make full text search query in data

**Comment by mgravell** [comment]
The API is deliberately a port of JRediSearch, so any and all examples from
https://github.com/RediSearch/JRediSearch should translate essentially 1:1,
except for the initial connection. Any use?

**Comment by Tameenk** [comment]
thanks i have read it and i applied it on .net core but when i cache data i using datanase.StringSet("key","my json string");
so my question now is it possible to make query in this cache directly instead of create manual index and then insert data as document then make a query ?

**Comment by mgravell** [comment]
if you mean "can I use RediSearch against existing arbitrary redis contents", then: no, that isn't how it works. You can use [`FT.ADDHASH`](https://oss.redislabs.com/redisearch/Commands.html#ftaddhash) to index a pre-existing redis *hash* as a RediSearch document, but I'm not aware of any command to work directly against a json string. Ultimately, the features of RediSearch [are here](https://oss.redislabs.com/redisearch/Commands.html) - and the features of the module aren't impacted hugely by which client you are using.

**Comment by mgravell** [comment]
you can of course load the JSON, and use `FT.ADD` to add it to the index

**Comment by Tameenk** [comment]
@mgravell thanks for you help i'll try it

**Comment by Tameenk** [comment]
@mgravell can you give my example in code to using addhash using JRediSearch ?

**Comment by mgravell** [comment]
Can you expand on what your example scenario is? So far, it has all been very vague, so the only answers I can give are likewise very vague.

**Comment by Tameenk** [comment]
@mgravell  I using .net core with redis
For example 
 public class Quotation
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }

        public List<Product> Products { get; set; }
    }

    public class Product
    {
        public int Id { get; set; }
        public int QuotationId { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }

        public List<Benefit> Benefits { get; set; }
    }

    public class Benefit
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
    }

i have quotations in cache 100K record  every week 
code like this

 connection = this.serviceProvider.GetRequiredService<IConnectionMultiplexer>();
 database = connection.GetDatabase();
 database.StringGet('quotations ');
var result = JsonConvert.DeserializeObject<List<Quotations>>(result);

so i can here make filter after DeserializeObject like this
var output = result.where(x=> x.Products.Select(p=>p.Benefits.Select(b=>b.price > 100) ));

I need to using NRedisSearch to filter and search inside  database.StringGet('quotations '); before get string and DeserializeObject

**Comment by Tameenk** [comment]
anyone can help me in this question ?

**Comment by mgravell** [comment]
so; you'd create a `new Schema` adding text and numeric fields for the properties; you'd populate the data using `AddDocument`, and you'd query using a `Query.NumericFilter`;  it is actually pretty similar to [ExampleUsage.cs](https://github.com/StackExchange/StackExchange.Redis/blob/master/tests/NRediSearch.Test/ExampleUsage.cs), no?

**Comment by NickCraver** [comment]
Closing out due to inactivity - lots of new examples are in place and the latest code is updated for the latest library as well.
