### ISSUE TITLE
StackExchange.Redis.RedisServerException: Key has MOVED to Endpoint error

### ISSUE THREAD

**Issue by gitexo** [StackExchange/StackExchange.Redis#1274]
Hi! We're currently using `StackExchange.Redis(v2.0.601)`. We have a Redis cluster with 3 shards each containing 3 nodes. (3 master, 6 slaves). When there's low activity, everything seems to be running smoothly, however, when there's a lot of new data being inserted into Redis when I end up calling  `SortedSetRangeByScoreAsync` within my c# code, I am getting this exception:

`StackExchange.Redis.RedisServerException: Key has MOVED to Endpoint ... and hashslot ... but CommandFlags.NoRedirect was specified - redirect not followed for ZRANGEBYSCORE`

I'm not sure why this would be happening as I thought StackExchange.Redis would handle the MOVED error coming from Redis. I'm not sure if it is related to the problem, but I specified `CommandFlags.PreferSlave` for the `SortedSetRangeByScoreAsync` call. I haven't specified `CommandFlags.NoRedirect` in my code so I guess this comes from `StackExchange.Redis(v2.0.601)`

Do you have a guess what could happen there? Been looking for a while for the solution and I would appreciate if you'd have an idea that could point me toward the solution? Could it be possible that it tries to get the data from Redis once, gets redirected, tries again but this time sets `CommandFlags.NoRedirect` internally. Now, since there's a lot of new data, Redis resharded again and thus gets a second redirect which would raise the exception?

Thanks!

**Comment by shimingwu** [comment]
Inside the code, the `NoRedirect` is actually sent when the client tries to re-send the request again if the previous request receives the "MOVED" message.

**Comment by gitexo** [comment]
Ah ok I see, so then it's as I thought and my hypothesis is correct.

However, how can I avoid this error? I would like to get the data, no matter if it moved or not? How can I tell the client that? Basically, avoiding the `NoRedirect` being set internally

**Comment by mgravell** [comment]
The library *does* handle the MOVED response. However, it makes the reasonable assumption that data won't be re-sharding faster than we can follow the redirect.

I'm hearing you that there is something not quite right here, but: we shouldn't be leaping to "just follow unbounded redirects" - we should instead first try to understand the what and why here. Was this, for example, a case where this connection was "new", and had not fully completed the initial handshakes (including the shard topology)? Was something particularly unusual happening? Was it using a RESP-aware proxy that made the library think it was talking to one server, when behind the scenes the balancer changed endpoint? Etc

**Comment by gitexo** [comment]
Good point, I agree it shouldn't blindly follow redirect but I was wondering if there was a way to do a few redirect before throwing the error instead of just one.

That being said, I looked further into it with what you said and I think it is related with the creation of new connection. I'm using a Lazy pooling of `ConnectionMultiplexer` which gets new connection as long as some are available. Once it's been through all, then It start to re-use some already created. I've added `Thread.Sleep(1000);` right after opening up a new connection and since then everything is fine. I'll keep an eye out in the next days to be sure though.

With that in mind, how can we properly make sure the initial hanshakes (including the shard topology) is done and finished before moving on? It doesn't seem as though the `Thread.Sleep(1000);` is the ideal solution.. what do you think?

**Comment by NickCraver** [comment]
@gitexo Are you using an authenticated Redis instance? A critical reconnect but was found and fixed in #1367, which if so: that's your cause and the fix will be included in the 2.1.x release soon.
