### ISSUE TITLE
No connection is available to service this operation

### ISSUE THREAD

**Issue by sumit4bansal** [StackExchange/StackExchange.Redis#1275]
I am trying to access Redis(hosted on docker container) in a window service written in C#.net, I am using StackExchange.Redis SDK to access Redis, Whenever I try to access Redis, I am getting following error

> StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: FLUSHDB; UnableToConnect (None, last-recv: 23) on 10.0.5.122:57457/Interactive, Flushed/ReadAsync, last: ECHO, origin: ResetNonConnected, outstanding: 0, last-read: 5s ago, last-write: 5s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.0.601.3402; IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=0,Free=32767,Min=2,Max=32767), Local-CPU: n/a ---> StackExchange.Redis.RedisConnectionException: UnableToConnect (None, last-recv: 23) on 10.0.5.122:57457/Interactive, Flushed/ReadAsync, last: ECHO, origin: ResetNonConnected, outstanding: 0, last-read: 5s ago, last-write: 5s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.0.601.3402\r\n --- End of inner exception stack trace ---\r\n

I am using latest version of StackExchange.Redis, I also tried by downgrading version as suggested in couple of articles but no luck, I am also setting AbortOnConnectFail as false. Redis server is up and working fine, I can do telnet and also can see all keys through a tool(Redis React)

Strange things is that, same code is working fine when using in a website with same Redis server but **not from window service**.

Please guide. Thanks

**Comment by sumit4bansal** [comment]
@mgravell Please help

**Comment by mgravell** [comment]
Is this intermittent? Or does it never connect at all? If the latter it sounds like an assembly binding problem hiding between the exception - most likely "Buffers", "Vectors" or "Unsafe" (3 Microsoft libraries that are notoriously brittle).

Can I guess that this is .NET Framework? If so which version?

**Comment by sumit4bansal** [comment]
@mgravell It doesn't connect at all, yes its .Net framework 4.6.1

This is what I have in app.config

```
<dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.InteropServices.RuntimeInformation" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.4.1" newVersion="4.0.4.1" />
      </dependentAssembly>
    </assemblyBinding>
```

**Comment by sumit4bansal** [comment]
@mgravell For some reason System.Numerics.Vectors.dll was not present in output folder, I copied this manually and it started working, Thank you so much for giving clue. You saved lot of my time

**Comment by mgravell** [comment]
Yeah, the deploy stuff for Vectors is just wrong. Out of my control. I'm
going to try updating all deps to latest and see if it improves, bit I
doubt it - the Microsoft view there is "yes, we fixed that along with a few
other things; the fix is called .NET Framework 4.7.2"
