### ISSUE TITLE
[Question] Do transactions block all other commands in the same connection?

### ISSUE THREAD

**Issue by SnakyBeaky** [StackExchange/StackExchange.Redis#1276]
I'm evaluating whether the use of transactions fits the needs of an application, and I haven't been able to find in the documentation the internals of how it works in StackExchange.Redis.

In [Transactions.md](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Transactions.md) there's a brief section which mentions:

> This is all done in a way that prevents the commands being mixed together with other callers.

And also in https://github.com/StackExchange/StackExchange.Redis/issues/247#issuecomment-401188953 @mgravell mentions:

> There is a reason they aren't exposed via a runtime pluggable API - specifically, the point when they would be to be called is in a critical region when we absolutely do not want to call into user code, as it could jam the pipe.

Does this mean that the "pre-canned" conditions block other commands (which don't relate to the transaction) that use the same ConnectionMultiplexer?

To put it in a simple way, if I made a transaction with a condition that for some reason takes 5 seconds, during those 5 seconds nobody using the ConnectionMultiplexer would get anything back from their commands?

Thanks.

**Comment by mgravell** [comment]
Yes, it means exactly that - although note that the conditions exposed are deliberately constrained to operations that should usually be fast. I guess it you used an equality test on something that was actually a 1GiB string, you're going to hurt.

An alternative would be to use Lua (ScriptEvaluate). This allows you to do any logic you like server-side, without any client-server latency issues, or bandwidth issues *for data that now doesn't need to go between client and server* (obviously you still need to "pay" for data that actually needs to be exchanged as parameters or results)

**Comment by SnakyBeaky** [comment]
That answers the question perfectly, thanks.

So if I know I will be having lots of transactions in advance (with a few conditions each), is it worth considering having two ConnectionMultiplexers, one for normal operations and the other for transactions?

Also, thanks for the quick answer!

**Comment by mgravell** [comment]
I have no knowledge of what your expected load and throughput requirements are. It might work just fine even with the transactions. However: if it were me, I'd probably write the transaction code in Lua instead. It is easier to write and maintain, and usually avoids any performance concerns.

**Comment by SnakyBeaky** [comment]
Sounds good, take a closer look at scripts, I was trying to avoid them whenever possible to keep a full C# codebase but this might be an exception.

Many thanks for your time 👍
