### ISSUE TITLE
Identifying update failure in Redis.

### ISSUE THREAD

**Issue by Vijay27anand** [StackExchange/StackExchange.Redis#128]
mgravell,

we are trying to use redis for our application which involves 100000 read/writes per hour. We are have SQL DB as persistent storage and will use Redis as cache only, so any update we will do in Redis and DB, any read we will use Redis first and if not available we go to DB and update Redis. 

So we like to know if we will have any chance if an update fails in Redis and success in DB we will have out of sync issue. 

Is there a way to identify if any update to Redis is failed, will the redis client return any error code if save/update is failed.

**Comment by NickCraver** [comment]
Closing this out as answered.
