### ISSUE TITLE
ERR wrong number of arguments for 'sadd' command

### ISSUE THREAD

**Issue by omeaart** [StackExchange/StackExchange.Redis#1282]
Not entirely sure if this is expected behaviour, but it surprised me. When the SetAdd(Async) methods are used with an empty array of values, there is a broken call made to redis.

To reproduce:
```
var redisConnection = ConnectionMultiplexer.Connect("localhost");
redisConnection.GetDatabase().SetAdd("set1", new RedisValue[0]);
```

This also fails for SetAddAsync.

Version: 2.0.601
Tested with dotnetcore 2.2 and 3.0

**Comment by mgravell** [comment]
Agreed - we should detect that and no-op it (avoiding the redis call
completely, whenever possible)

**Comment by omeaart** [comment]
This was resolved in https://github.com/StackExchange/StackExchange.Redis/pull/1283
