### ISSUE TITLE
The 'To create a disconnected multiplexer, disable AbortOnConnectFail' message is confusing

### ISSUE THREAD

**Issue by TimLovellSmith** [StackExchange/StackExchange.Redis#1287]
I just want to give some feedback that this error message is confusing people:

"No connection is available to service this operation: GET 0C2F1DC9-FEED-4AE6-91F2-6FE736613BB3_MUSTCHANGEPASSWORD; It was not possible to connect to the redis server(s). To create a disconnected multiplexer, disable AbortOnConnectFail. ConnectTimeout; IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=100,Max=32767), Local-CPU: n/a"

The reason I think its confusing is that 'disable AbortOnConnectFail' sounds like you should set that 'AbortOnConnectFail=false' to _disable_ it. But AFAICS thats not really what the error message means, since you will only see that error message if it was _already false_:

```if (!muxer.RawConfig.AbortOnConnectFail) sb.Append(" To create a disconnected multiplexer, disable AbortOnConnectFail.");```

**Comment by TimLovellSmith** [comment]
One other thing I find unclear about the message is it is unclear whether it is prescriptive. Is it meant to be teaching people that creating disconnected multiplexers is a really good thing to do? Or is it just saying that 'if you use a different config from what you have now, you can see different behavior'? And if the latter, why is it important?

**Comment by NickCraver** [comment]
I agree the phrasing of this is bad. We'll get something clearer in and I'll update here.

**Comment by NickCraver** [comment]
How about:
> "Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code."

cc @mgravell - thoughts on the above phrasing?
