### ISSUE TITLE
Create advanced method for manual reconnection to server

### ISSUE THREAD

**Issue by AlexeiScherbakov** [StackExchange/StackExchange.Redis#1290]
Behavior:

1. Disconnect from server (even if connection is ok)
2. Connect again

This solution helps to overcome situation in "redis behind HAProxy" cases of issue https://github.com/StackExchange/StackExchange.Redis/issues/1120

**Comment by NickCraver** [comment]
You are free to implement this outside of `ConnectionMultiplexer` (e.g. spinning up a new one and swapping the reference), but we'd rather fix the core of the issue. #1120 should be addressed by #1374 - look out for a 2.1.x release soon here :)

**Comment by AlexeiScherbakov** [comment]
Yes, we already make wrapper for our production code, but it will be much more simple if it can be placed in one library call inside in HealthCheck
