### ISSUE TITLE
How to use both Primary and Secondary Azure Redis connection string

### ISSUE THREAD

**Issue by JagatheeshMenon** [StackExchange/StackExchange.Redis#1293]
Dear all,

There is a requirement to rotate primary key in an application. Any help how can I handle both Primary key and Secondary key together in an application to avoid down time when the primary key gets changed.

**Comment by Plasma** [comment]
I think you want to migrate to the secondary key on the app, then rotate the primary.

Then when you want to rotate again, update the app to move to primary key, then rotate secondary to invalidate it.

I don’t think you want or can make the app itself know about both keys at once.

**Comment by NickCraver** [comment]
Agree with the above - closing out to cleanup here.
