### ISSUE TITLE
ValueTask support

### ISSUE THREAD

**Issue by yruson** [StackExchange/StackExchange.Redis#1295]
api add to return ValueTask<T>,  thx.

**Comment by mgravell** [comment]
Now... this is a topic I know quite a bit about, but I still have to ask the question: what do *you* (as the person requesting the change) see as the reason for this? There are many perspectives here, some which apply and some which so not, but : fundamentally this would be a very large change. So: what do *you* see as the reasons for this?

**Comment by NickCraver** [comment]
Closing out due to inactivity

**Comment by HudsonAkridge** [comment]
I know this is already closed, but let me voice an opinion to the opposition of `ValueTask<T>`.

Having `Task<T>` and/or `Task` as the return type is more useful for the compatibility and utility we get of using the `Task.*` library, e.g. `Task.WhenAll(taskParams)` which cannot be done without calling `.ToTask()` on every `ValueTask` returned.

So, in conclusion, the way it is right now is more useful to me and less irritating than if the library was returning `ValueTask` everywhere.

🙂
