### ISSUE TITLE
Connection throwing exception on latest versions

### ISSUE THREAD

**Issue by EricWu91** [StackExchange/StackExchange.Redis#1296]
I'm trying to use StackExchange.Redis in the 2.+ versions, and a 

`Unable to load assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. File could not be found.`

exception is thrown on `ConnectionMultiplexer.Connect();`

This exception is thrown on both ASP.NET WebForms and WCF (both 4.7.2) applications. LINQPad 5 connects correctly.

Using the version 1.2.6 in WCF succeeds in connecting, but throws different exceptions on WebForms (probably a different issue).

**Comment by geniussandy** [comment]
I was able to overcome this error by adding following to the app.config

```
<dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1"/>
      </dependentAssembly>
```

However after that I started to see more run time errors. Added following more binding redirects in app.config

```
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" xmlns="urn:schemas-microsoft-com:asm.v1"/>
        <bindingRedirect oldVersion="4.0.2.0-4.0.3.0" newVersion="4.0.3.0" xmlns="urn:schemas-microsoft-com:asm.v1"/>
      </dependentAssembly>
	  <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="B03F5F7F11D50A3A" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0"/>
      </dependentAssembly>
```

**Comment by sandeepag** [comment]
@EricWu91 :

Add following to your app.config.

```
			<dependentAssembly>
				<assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
			</dependentAssembly>
```

**Comment by NickCraver** [comment]
For binding redirects, please see https://nickcraver.com/blog/2020/02/11/binding-redirects/ for background, why it happens, and a few options for resolving it. It's not specific to this library, but we want to help people out - that post has the solution options.
