### ISSUE TITLE
Timeout awaiting response

### ISSUE THREAD

**Issue by zhanghaiboshiwo** [StackExchange/StackExchange.Redis#1297]
Hi, I have been experiencing the following errors recently using StackExchangeRedis (2.0.601) in net core3.0

Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5500ms elapsed, timeout is 5000ms), command=GET, next: GET string:ExportService_lock, inst: 0, qu: 0, qs: 11, aw: False, rs: ReadAsync, ws: Idle, in: 1454, in-pipe: 0, out-pipe: 0, serverEndpoint: 10.66.159.138:125, mgr: 9 of 10 available, clientName: iZ28hm4qpy3Z, IOCP: (Busy=4,Free=996,Min=2,Max=1000), WORKER: (Busy=141,Free=32626,Min=2,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts

**Comment by KamranShahid** [comment]
check https://github.com/StackExchange/StackExchange.Redis/issues/1248

**Comment by NickCraver** [comment]
Judging by the client name it looks like you're possible in Azure? Based on the busy worker count, it looks like that application is _very_ busy and your timeout of 5.5 seconds may be too low. If there are 141 concurrent threads active, that indicates that your CPU is slammed and things like processing Redis results are likely waiting in queue.
