### ISSUE TITLE
General exception handling strategy

### ISSUE THREAD

**Issue by ps-tb** [StackExchange/StackExchange.Redis#1299]
I have written some code using the library recently and made an assumption that `RedisException` was wrapping exceptions that could be thrown so that I could avoid catching `Exception` in my application code. That wasn't a successful strategy as I'm seeing `ArgumentException` at times. Is there a general strategy for handling the various exceptions that could be seen? My concern with catching `Exception` is that I may not be able to handle that broad exception type and will be catching something that I shouldn't. I appreciate any input or suggestions.

**Comment by ps-tb** [comment]
Is there any input that can be provided?

**Comment by mgravell** [comment]
Ultimately, the answer here is that all manner of exceptions are possible in basically any code. In terms of general exception strategy, there is no utility in trying to limit yourself to just catching, say, `RedisException` - and the library makes no attempt to limit you to any particular flavor of exceptions.

Any additional exception types that the library offers are *additional context only*. For example, `RedisServerException` is explicitly the server shouting at you, not the library, network, framework, etc. But an `ArgumentException` probably means your code did something demonstrably bad with the inputs before it did anything.

**Comment by ps-tb** [comment]
@mgravell thanks for the help. I was inferring this but wanted to make sure that I understood correctly. 

I've chosen to catch `Exception` but the problem then becomes do we `throw;` from inside the catch block as expected or just continue? I've chosen to continue because the exception could be a `RedisException`, which could be caused by a temporary lack of connection. We'll then query the primary source of data instead of relying on the cache; we don't want the entire request to fail because the cache isn't functioning. My concern is that that we're swallowing an exception that the framework should handle but I am willing to forgo this in lieu of the request continuing. Would you consider this to be a correct flow?
