### ISSUE TITLE
Getting a RedisTimeoutException : No data being written to the output buffer.

### ISSUE THREAD

**Issue by polinenibharat** [StackExchange/StackExchange.Redis#1305]
Any help is greatly appreciated! :)

I use this library with an Azure Redis instance. Stepping through the following debug FAQs from StackExchange and Azure, I validated that we do follow everything that is prescribed. They dont talk about the particular way we see this exception.
https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Timeouts.md
https://azure.microsoft.com/en-us/blog/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/

I upgraded to the latest nuget package 2.0.601 as per https://github.com/StackExchange/StackExchange.Redis/issues/1105

There is a constant hum of these exceptions with about a 1:100 failure rate. Copying the exception details below (hiding out irrelevant details).

{
"ClassName":"StackExchange.Redis.RedisTimeoutException",
"Message":"The timeout was reached before the message could be written to the output buffer, and it was not sent, command=EXPIRE, timeout: 0, outbound: 0KiB, inbound: 0KiB, next: SADD "{some-key}", inst: 20, qu: 1, qs: 13, aw: True, bw: RecordingTimeout, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: Unspecified/mrc-store-prod.redis.cache.windows.net:6380, mgr: 4 of 10 available, clientName: {some-client-name}, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=12,Free=32755,Min=16,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)",
"Data":{
"Redis-Message":"EXPIRE {some-key}",
"Redis-Timeout":"0",
"Redis-Write-State":"Idle",
"Redis-Read-State":"ReadAsync",
"Redis-OutboundDeltaKB":"0KiB",
"Redis-InboundDeltaKB":"0KiB",
"Redis-Message-Next":"SADD {some-key}",
"Redis-OpsSinceLastHeartbeat":"20",
"Redis-Queue-Awaiting-Write":"1",
"Redis-Queue-Awaiting-Response":"13",
"Redis-Active-Writer":"True",
"Redis-Backlog-Writer":"RecordingTimeout",
"Redis-Inbound-Bytes":"0",
"Redis-Server-Endpoint":"{some-endpoint}",
"Redis-Manager":"4 of 10 available",
"Redis-Client-Name":"{some-client name}",
"Redis-ThreadPool-IO-Completion":"(Busy=0,Free=1000,Min=16,Max=1000)",
"Redis-ThreadPool-Workers":"(Busy=12,Free=32755,Min=16,Max=32767)",
"Redis-Busy-Workers":"12",
"Redis-Version":"2.0.601.3402",
"redis-command":"EXPIRE {some-key}",
"request-sent-status":1,
"redis-server":"{some-server}",
"IsLogged":true
},
"InnerException":null,
"HelpURL":"https://stackexchange.github.io/StackExchange.Redis/Timeouts",
"StackTraceString":" at {some-code-path},
"RemoteStackTraceString":null,
"RemoteStackIndex":0,
"ExceptionMethod":null,
"HResult":-2146233083,
"Source":"System.Private.CoreLib",
"WatsonBuckets":null,
"commandStatus":1
}

**Comment by KamranShahid** [comment]
similar thing is happening to me. https://github.com/StackExchange/StackExchange.Redis/issues/1303
There seems some strange behavior that my same code connecting to remote redis working perfectly fine on windows instance but when executing it from ubuntu 18 instance i am getting these frequent timeout error. May be some tweak needed in connection management option or on ubuntu linux instance

**Comment by polinenibharat** [comment]
Found the issue. We were configuring the SyncTimeout wrong to be 0ms. Fixing that dropped the errors.
Closing this issue.

Thanks.
