### ISSUE TITLE
More app instances reduce Timeouts?

### ISSUE THREAD

**Issue by riiight** [StackExchange/StackExchange.Redis#1307]
Hello. I am developing an ASP.NET Core app running as an Azure App Service which interacts with an Azure Redis instance via the StackExchange.Redis library. I dependency inject a singleton ConnectionMultiplexer into the classes where I need it. 

When I put some load on a single instance of my app, I see many of these types of timeout errors:

`2019-12-17 21:14:09.908 +00:00 [Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=65826KiB, inbound=15KiB, 5860ms elapsed, timeout is 5000ms), command=SETEX, active: MGET, next: SELECT, inst: 0, qu: 0, qs: 33, aw: False, rs: ComputeResult, ws: Idle, in: 65536, serverEndpoint: Unspecified/_____.redis.cache.windows.net:6380, mgr: 9 of 10 available, clientName: RD2818780E30FC, IOCP: (Busy=4,Free=996,Min=4,Max=1000), WORKER: (Busy=5,Free=32762,Min=4,Max=32767), Local-CPU: unavailable, v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

However, if I bump it to 2 instances of my app, these errors seem to go away. Can anyone tell me:
1) Why do two instances of my app make these errors go away? They are both hitting a single instance of Redis, so the fact that they no longer timeout when the caller load is divided between two machines doesn't make sense to me.
2) Does "outbound=65826KiB" mean my app was trying to send  ~65MB of data to Redis? Knowing what my app is supposed to be doing, that doesn't make sense, either.
3) What does "inbound=15KiB" mean? If the call timed out, how did anything come inbound?

Thanks in advance.

**Comment by NickCraver** [comment]
Indeed the `outbound=65826KiB` means there's 65MB on the way to Redis - that's a _huge_ thing to cache, and not a good idea to do with a single connection (as it's a pipeline and will block others). If that's not expected...that's the cause and the rest is a symptom. I highly, _highly_ recommend not putting 65MB on a single payload in Redis - it's just not friendly to a pipeline scenario at all.
