### ISSUE TITLE
Why error No connection is available to service this operation: SETEX while writing to Redis Cache in C# console application and how to solve it

### ISSUE THREAD

**Issue by viveknuna** [StackExchange/StackExchange.Redis#1308]
I am trying to write records from a dictionary with around 5000 records to a Redis cache. But sometimes I get the below exception, I have no clue why I am getting this error, I have checked on the internet but could not find any solution or root cause of this issue.
```

using (ConnectionMultiplexer redis = ConnectionMultiplexer.Connect(_configuration.GetConnectionString("redis_server")))
            {
                IDatabase db = redis.GetDatabase();


                foreach (KeyValuePair<string, string> keyValuePair in _dictAllData)
                {
                    db.StringSet(keyValuePair.Key, keyValuePair.Value, TimeSpan.FromMinutes(30));
                }

        }
```

**Exception:**

> No connection is available to service this operation: SETEX 747712; IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=0,Free=32767,Min=4,Max=32767), Local-CPU: n/a

**StackExchange.Redis Version: 2.0.601**

**Comment by NickCraver** [comment]
This should be resolved by #1374 (we'll get it merged in this week) and available in the 2.1.x release. Closing this out just to consolidate duplicates and link them all to that PR.
