### ISSUE TITLE
Expose _connection as public field in RedisCache

### ISSUE THREAD

**Issue by jjxtra** [StackExchange/StackExchange.Redis#1310]
I want to use `IDistributedCache`, but also hook into the connection multiplexer. This is in net core 3 and I am using `AddStackExchangeRedisCache`.

Right now I use reflection to pull out the _connection property after casting IDistributedCache to `RedisCache`. Is there a better way or do we need to make this field public?

**Comment by mgravell** [comment]
Are those types/methods/etc in this library? They don't sound familiar - you may need to consult with whatever library actually defines those things.

**Comment by jjxtra** [comment]
No it's not a problem with this repo, it is Microsoft's issue not exposing the needed properties. Fortunately with reflection there is a work-around.
