### ISSUE TITLE
API improvement suggestion

### ISSUE THREAD

**Issue by bnayae** [StackExchange/StackExchange.Redis#1314]
Add the following overloads to StreamAddAsync
for better usability.

```
Task<RedisValue> StreamAddAsync(RedisKey key, params NameValueEntry[] streamPairs);
Task<RedisValue> StreamAddAsync(RedisKey key, bool useApproximateMaxLength 
 params NameValueEntry[] streamPairs);
```
It will enable a cleaner API call

```
RedisValue value = await StreamAddAsync("A", new NameValueEntry("A", 1), new NameValueEntry("B", 2));
```
Rather

```
RedisValue value = await StreamAddAsync("A", new [] {new NameValueEntry("A", 1), new NameValueEntry("B", 2)});
```

**Comment by NickCraver** [comment]
Sorry this sat in the backlog - we can't get to everything and votes that come along help prioritize the time we have. Given that ultimately a user is still allocating the array no matter what, and newer C# language features like `new()` make things shorter, e.g. 
```
RedisValue value = await StreamAddAsync("A", new NameValueEntry[] {new("A", 1), new("B", 2)});
```
...I don't think we want to add a lot of overloads like this (to be consistent, it'd have to be added in a lot of other variadic places. Having the array makes the call more obvious as to what's happening as well.

What's more likely here is that the .NET team is considering adding an `IEnumerable` version of `params` which may appear in a future version and make these things usable without API changes and overload supports for all, but for now: the array overload is consistent with the rest of the API and the only thing supported.

Going to close out to tidy up here (trying to get through a lot of pending issues), but happy to re-open if anyone wants to discuss further!
