### ISSUE TITLE
Seem like a bug: await _db.StreamCreateConsumerGroupAsync

### ISSUE THREAD

**Issue by bnayae** [StackExchange/StackExchange.Redis#1315]
The following code don't create the stream (if not exist).

`
await _db.StreamCreateConsumerGroupAsync("events_stream", "events_consumer_group", StreamPosition.NewMessages);
`
The documentation suggest that it should (see  [Consumer Groups section](https://stackexchange.github.io/StackExchange.Redis/Streams.html))

> The following creates a consumer group and tells Redis from which position within the stream to begin reading. If you call the method prior to first creating the stream, the StreamCreateConsumerGroup method will create the stream for you by default. You can override this default behavior by passing false for the createStream optional parameter.

It don't it create the stream, and the API don't have overload which get "createStream optional parameter"

**Comment by bnayae** [comment]
It's seem related to pull request #1141

**Comment by gale93** [comment]
I confirm #1141 solved the issue, this can be closed

**Comment by NickCraver** [comment]
Closing out to cleanup - thanks all!
