### ISSUE TITLE
Bloom filter

### ISSUE THREAD

**Issue by markjoin123** [StackExchange/StackExchange.Redis#1319]
How to realize the bloon filter？

**Comment by NickCraver** [comment]
@markjoin123 Can you clarify what's being asked here?

**Comment by NickCraver** [comment]
If there's a clearer question here, please shout - since there's almost nothing to go on, going to close this until then :)

**Comment by mgravell** [comment]
If the question is RedisBloom, then: that is usable, but we don't support many modules directly (the exception being RediSearch, which we added to test module support). Basically, the answer here would be "use Execute to invoke the module"
