### ISSUE TITLE
RedisTimeoutException missing IOCP and WORKER in log

### ISSUE THREAD

**Issue by bmasnec** [StackExchange/StackExchange.Redis#1321]
Hi,
I'm using .Net Core app 2.2 with explicit reference to Netstandard 2.0.3 library.

For some reason there is no IOCP and WORKER stats in log. 
From documentation the log part should be present 
> IOCP and WORKER threads will not be shown on .NET Core if using netstandard < 2.0

I'm using Netstandard 2.0.3 which is latest available. Microsoft.Extensions.Caching.Redis SDK version in use is 2.2.0 
And here is log that i get

ExceptionStackExchange.Redis.RedisTimeoutException: Timeout performing EVAL, inst: 14, queue: 42, qu: 0, qs: 42, qc: 0, wr: 0, wq: 0, in: 11373, ar: 0, clientName: ActivityService, serverEndpoint: Unspecified/cache.amazonaws.com:6379, keyHashSlot: 15753 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)

Can you advise me or point me in right direction

**Comment by bmasnec** [comment]
Can anybody help on this issue? Microsoft.Extensions team have stated that they are not configuring anything regarding logging and that StackExchange team is the team to ask. You can see their response here https://github.com/dotnet/extensions/issues/2870

**Comment by NickCraver** [comment]
Ah, I see the confusion. There are 2 packages here, `Microsoft.Extensions.Caching.Redis` uses the old 1.x version of our client. You want the newer `Microsoft.Extensions.Caching.StackExchangeRedis` which uses the 2.x version (and you can manually reference latest). See this issue for context: https://github.com/dotnet/extensions/issues/2313

**Comment by NickCraver** [comment]
Closing out to cleanup!
