### ISSUE TITLE
RedisCache connection Issue.

### ISSUE THREAD

**Issue by sathwikkrishna** [StackExchange/StackExchange.Redis#1322]
Hi,

I was using Azure Redis cache for bot service. I was facing the issue when set or get the data.

**It was not possible to connect to the redis server(s). UnableToConnect on AzureRedisCacheConnectionString:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 1s ago, v: 2.0.601.3402**

Thanks.

**Comment by maxisam** [comment]
I have the same issue too. But I use it on a different server locally. And it only happens in the very first time. I wonder if we can have an event that we can listen to, so it doesn't throw exception.

**Comment by NickCraver** [comment]
Are you using `abortConnect=false` flag that Azure recommends in the connection string here? It's the cloud, there are transient failures you won't have control over...so that's the recommendation from everyone in tolerating this at spin-up.
