### ISSUE TITLE
Question: How to project to a dictionary<RedisKey, RedisValue> based on list of redisKeys

### ISSUE THREAD

**Issue by arabelaa** [StackExchange/StackExchange.Redis#1324]
I have the following scenario I would like to achieve. (i am using stringSetAsync construct for saving  keys)

1. Get a list of keys that match a pattern (for that I am using server.Keys call).
2. With the resulting keys I would like to retrieve the correspondent values and project the result to a Dictionary<key,value>. 
3. Apply a predicate on the resulting Dictionary and return the list of keys 

I didn't find a way to project to a Dictionary and it feels that I am trying to do something that Redis was not intended to support.

Any hints are appreciated. Thanks.

**Comment by mgravell** [comment]
Ok; you're right in that here is no single "get me the keys and their
string values" API. The simple but sub-optimal way to do this would be a
per-string get, i.e.

var dict = (
    from key in server.Keys(...)
    select (key, value = db.StringGet(key))
    ).ToDictionary(
        x => x.key, x => v.value);

(I'm using mobile/email here, so there may well be minor syntax errors in
the above; I can correct them if needed - mainly showing the flavor here)

A faster but more complex way would be to batchify the key sequence into
chunks of, say, 100 keys, then use mget (i.e. the array-based version of
StringGet), and manually unroll the results from the key/value arrays
calling Add. Much more complex, but far fewer round trips.

Either of those help?

**Comment by mgravell** [comment]
(fixed the syntax errors)

``` c#
var dict = (
    from key in server.Keys(0, pattern)
    select (key, value: db.StringGet(key))
    ).ToDictionary(x => x.key, x => x.value);
```

**Comment by arabelaa** [comment]
I wanted to avoid doing a round-trip per key (I can have 10000 keys. I'll measure the performance to see the impact). 
Based on the results I'll have a look on the mget approach.

Thanks for the hints (didn't expect such a fast response).

**Comment by mgravell** [comment]
Also: increase the page size on the call to keys. The default is way too
small. I've already increased the defaults in the async-iteraroe branch,
but that isn't merged yet. Try 1024 or something like that.
