### ISSUE TITLE
Blocking operation problem as suggested

### ISSUE THREAD

**Issue by TomerW** [StackExchange/StackExchange.Redis#1333]
Hello, 

In this [Pipelining And Multiplexing](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/PipelinesMultiplexers.md#multiplexing) article, it is noted that Blocking operations are intentionally not implemented by StackExchange.Redis client...  
Instead, there is a suggested solution:

```
sub.Subscribe(channel, delegate {
    string work = db.ListRightPop(key);
    if (work != null) Process(work);
});
//...
db.ListLeftPush(key, newWork, flags: CommandFlags.FireAndForget);
sub.Publish(channel, "");
```

which in my opinion is failing for the following reason:  
Consider a constant flow of jobs pushed to the queue.  
In the given design suggestion, that means multiple Publish events to `channel`.

Now, the subscriber, wished to process each work-item synchronously,  
but if its processing time is longer then the interval of published events,  
it gets parallel calls to it's delegate, each pulling from queue, and parallel processing the work.

In order to make it work, one would think to add a simple lock as:

```
sub.Subscribe(channel, delegate {
   lock(lockContext){
      string work = db.ListRightPop(key);
      if (work != null) Process(work);
  }
});
```
but that would lead to an eventual timeout on the subscriber.

**Any suggestions on how to create a synchronous worker?**

**Comment by TomerW** [comment]
@mgravell Please take note, i think the example in https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/PipelinesMultiplexers.md#multiplexing should be updated.

**Comment by mgravell** [comment]
For this kind of synchronous worker we essentially need a pool and lease -
probably sat in top of "streams". I'm open to looking into this, but it is
going to take a non-trivial amount of effort, and I need to block out the
time to do it, so: it hasn't happened to date.

**Comment by NickCraver** [comment]
Collecting existing issues here - for anyone in this situation please follow #1961 where we're going to figure out how to best expose this behavior. Closing this just to consolidate discussion!
