### ISSUE TITLE
Timeout performing GET

### ISSUE THREAD

**Issue by nebojsapop** [StackExchange/StackExchange.Redis#1334]
Timeout performing GET (5000ms), next: GET MyKey, inst: 0, qu: 0, qs: 7, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: myIP, mgr: 10 of 10 available, clientName: WIN-1, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=7,Free=32760,Min=1000,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts))

 at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)

Anyone has same problem? Does this indicates that library setting is fine and the problem is on redis server (Worker - busy 7 Min 1000)?

**Comment by NickCraver** [comment]
It appears the worker is trying to process what's coming in off the socket, but there is nothing at the moment and 7 requests are pending. It looks like a legitimate "we're waiting on results from Redis" scenario. What's the setup here, is it possible to have high latency from Redis? e.g. a cloud deployment?

**Comment by nebojsapopovicwm** [comment]
Hi Nick,

Sorry for late response. No its not in cloud, our client has his own servers where we host application.
I'll check with our devops team for latency.

Also we have tried with async methods of client

Inner Exception: The timeout was reached before the message could be written to the output buffer, and it was not sent, command=GET, timeout: 5000, outbound: 822KiB, inbound: 256KiB, next: GET 8e89850d0189febed03b871644a80cf0, inst: 10423, qu: 284, qs: 1318, aw: True, bw: RecordingTimeout, rs: ReadAsync, ws: Flushed, in: 65536, in-pipe: 23545, out-pipe: 0, serverEndpoint: 192.168.38.38:6379, mgr: 9 of 10 available, clientName: S1-WIN-FE3,IOCP (Busy=0,Free=1000,Min=10,Max=1000), WORKER: (Busy=1618,Free=31149,Min=1000,Max=32767), v: 2.0.601.3402 
 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by nebojsapopovicwm** [comment]
Also we have 2 more applications on same windows server using same redis server without errors. They are using same version of redis client 2.0.601. Latency would cause errors on other 2 apps i guess.

**Comment by NickCraver** [comment]
Whoa, there is a big red flag in there: `Busy=1618,Free=31149,Min=1000,Max=32767` That means you're running 1,618 threads *actively*, it's just absolutely slammed with work when this timeout happens. Your CPU isn't able to keep up with the load. Is it normally that busy, or comes in spikes maybe? The solution here would be to either try and prevent the spike (smoothing out the load and not kicking off so many threads), or to up the timeout to just suck it up and allow it to continue, though delayed.

Normally we'd see this when say queuing _tons_ of tasks on the thread pool. Given it grows at 1-2 per second, it must be like this for quite some time to build up that high.

**Comment by nebojsapopovicwm** [comment]
It is news portal so it comes in spikes. 
Since busy is higher than min, maybe I should set higher number of threads on startup so I avoid creating new ones when it passes 1000?

**Comment by nebojsapopovicwm** [comment]
But I guess that it will be the same problem. We have 12 core processor on server.

**Comment by nebojsapopovicwm** [comment]
Also other 2 apps (on same windows server) were working just fine, on same processor and same redis server.

**Comment by Xiaobaicoder-pixel** [comment]
No connection is available to service this operation: GET 7421319680814056b12c4254dce21af4; IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=4,Free=32763,Min=4,Max=32767), Local-CPU: n/a，nuget version:2.0.600;
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2258
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54

**Comment by dceravigupta** [comment]
@Xiaobaicoder-pixel these issues are fixed on latest nuget.

**Comment by NickCraver** [comment]
Agreed, please try a later version of the library (we've fixed many issues since 2.0.600) and see if this persists.
