### ISSUE TITLE
Question: How to optimally and efficiently iterate through Redis Cache keys using Keys()?

### ISSUE THREAD

**Issue by cenh** [StackExchange/StackExchange.Redis#1335]
I have a Redis with a whole bunch of keys, and I want to loop through them to get all values. I used to have my page size to 100, but it would sometimes not find anything so I increased it to 1000 and it served as a temporary fix, however I want to find a more sustainable solution, so I have tried to loop using the scanning cursor, but it seems the cursor stops progressing and never terminates.

I have the following code:
```
IServer server = redis.GetServer("localhost", 6379);
var tmp = server .Keys((int)redisDatabase, redisValue, pageSize);
var iter = tmp.GetEnumerator();
var scanningCursor = (IScanningCursor)tmp;
var redisKeys = new RedisKey[1] { iter.Current };

while (iter.MoveNext())
{
    redisKeys.Concat(new RedisKey[1] { iter.Current });
}

while (scanningCursor != null && scanningCursor.Cursor != 0)
{
    tmp = server.Keys((int)redisDatabase, redisValue, pageSize, cursor: scanningCursor.Cursor);
    scanningCursor = (IScanningCursor)tmp;
    iter = tmp.GetEnumerator();
    while (iter.MoveNext())
    {
        redisKeys.Concat(new RedisKey[1] { iter.Current });
    }
}
return redisKeys
```
However it keeps looping forever, as it seems that the cursor never gets set to 0 when it terminates. Is my logic here wrong, and if it is then how should I use the Keys() to make sure that I look through all the keys in my Redis?

**Comment by mgravell** [comment]
hmmm; I'd need to check on what is happening re the enumerable, but fundamentally, the `ToArary()` here should already be doing all of your iteration for you; I believe that if you *do* want access to the cursor, the enumerator API should be reliable (i.e. `var iter = tmp.GetEnumerator()`, etc) - but: it *looks* like this code does everything twice. Is there a problem you were having with just the `ToArray()` here?

**Comment by mgravell** [comment]
yeah, the *enumerable's* cursor info is only valid while an iteration is in progress; it doesn't really apply in your case since each time you're looking *before* it really gets going - but: without understanding what you're *trying to do here*, I'm unclear what to advise. All you should need here is:

``` c#
var redisKeys = = server.Keys((int)redisDatabase, redisValue, pageSize)).ToArray(); // or similar
```

**Comment by cenh** [comment]
So this is exactly what I had before:

`var redisKeys = = server.Keys((int)redisDatabase, redisValue, pageSize).ToArray();`

But there was a key in my Redis that I was not finding, at that point I had a pageSize of 1, I then increased the pageSize to 100 and it started working again. But I figured it was an unsustainable solution to my problem, and then tried to implement a new solution (as per the original post in this issue).

**Comment by NickCraver** [comment]
@cenh Which version of the client and server are you using? This should work by calling SCAN underneath today but maybe there's a bad assumption vs. an older codebase or server version here.
