### ISSUE TITLE
Is there a way to get all keys from a database with expiry less than a value ?

### ISSUE THREAD

**Issue by ghetze** [StackExchange/StackExchange.Redis#1338]
Hi.
I have the following situation in a .net core console app.
I want to get all keys from a redis database and to process the ones which have the expiry period < 1.
Currently i use the following solution:
```
ConnectionMultiplexer _connectionRedisRepository = ConnectionMultiplexer.Connect("redis_server");
var db = _connectionRedisRepository1.GetDatabase(10);
//get all keys from db:10
var allkeys = db.Execute("keys", "*");
if (msisdnPlatformIdMessageIdDBKeys != null && msisdnPlatformIdMessageIdDBKeys.Length > 0)
{
foreach (var key in allkeys)
{
     RedisValueWithExpiry value = await db.StringGetWithExpiryAsync((RedisKey)key);
     //check the expiry 
     if (value.Expiry.Value_ < 1)
    {
        //do some processing
     }
}
}
```
Is there a way to run some command on db.Execute or is there another method to get only keys with expiry < 1 (to get the keys already filtered).
Thanks.

**Comment by mgravell** [comment]
Ultimately, the problem here is that what you want *doesn't exist as a feature in redis*. Yes, you could hack it over the top like in your code, but: it isn't going to be efficient. And there isn't anything better you could do because again: that feature doesn't exist on the server.

**Comment by ghetze** [comment]
Thank's for the reply... Isn't there another way to paginate the keys or to process somehow in batches, so i won't get all keys from the database at once.

**Comment by mgravell** [comment]
Absolutely. You shouldn't run `keys`. The method you are looking for is on `IServer`: https://stackexchange.github.io/StackExchange.Redis/KeysScan.html

**Comment by ghetze** [comment]
After some research and reading  the following link:
https://stackoverflow.com/questions/51522162/stackexchange-redis-scan-x-amount-of-keys/51522874#51522874

I've implemented the following solution.
Please advise if this is the right way , thanks.

public void ProcessRedisKeys()
{
var _connectionRedisRepository = ConnectionMultiplexer.Connect("localhost:6359,allowAdmin=true,syncTimeout=60000");
//get all endpoints defined for this redis connection.
var endPoints = _connectionRedisRepository.GetEndPoints();
IServer _server = null;
if (endPoints.Length > 1)
            {
                foreach (var endPoint in endPoints)
                {
                    if (!_connectionRedisRepository.GetServer(endPoint).IsSlave)
                    {
                        //get the master
                        _server = _connectionRedisRepository.GetServer(endPoint);
                        break;
                    }
                }
            }
 if(_server == null)
{
//otherwhise get the only endpoint defined.
_server = _connectionRedisRepository.GetServer(endPoints.First());
}
//processing on batches of 100 records
ExecuteInBatches(_server.Keys(), 100, batch => ProcessKeyBatch(batch));
}

public void ExecuteInBatches<T>(IEnumerable<T> source, int batchSize,
        Action<List<T>> action)
        {
            List<T> batch = new List<T>();
            foreach (var item in source)
            {
                batch.Add(item);
                if (batch.Count == batchSize)
                {
                    action(batch);
                    batch = new List<T>();
                }
            }
            if (batch.Count != 0)
            {
                action(batch);
            }
        }

**Comment by mgravell** [comment]
That will batch things. I can't see what you're doing with each batch,
though, so it is a little hard to comment on how it will behave.

**Comment by ghetze** [comment]
I've added the method that processes  the batch..it inserts some stuff to kafka and deletes the key from redis.

**Comment by mgravell** [comment]
Right; if you're just going to `foreach` over the keys, there's really no point batching - you'll be doing exactly the same amount of work. There *is* a multi-key `StringGet`, but: it won't include the expiry info. Unfortunately there is no multi-key version of `TTL` / `PTTL`.

Perhaps the thing to do in this case is to consider writing some Lua (`EVAL` / `ScriptEvaluate`) that takes a bunch of keys and returns their contents and ttl? this will reduce round-trips. If you do *that*, then batching is worthwhile. Without it: there's no point batching anything. If the performance is acceptable without batching: fine.

**Comment by ghetze** [comment]
The idea was that i don't want to get all keys from a redis db and process all of them.
By batching i will keep in memory only an amount of 100 keys, process them and then process the next batch..

**Comment by mgravell** [comment]
The `Keys()` method on `IServer` *already does that* (unless you're on an old server that pre-dates `SCAN`); the `IEnumerable<RedisKey>` that it gives you is a scanning cursor that retains a page of data from `SCAN`, handing out new data when needed, and dealing with the semantics of requesting new pages from the server. It *does not* just load everything into an array that it hands back to you.

Batching is only useful and necessary for performing bulk operations on groups of keys, which is not what you are doing here. `foreach` is fine.

**Comment by ghetze** [comment]
Thanks a lot for the details.
