### ISSUE TITLE
Interacting with Redis modules in an ITransaction. 

### ISSUE THREAD

**Issue by tombatron** [StackExchange/StackExchange.Redis#1340]
Hi there, 

Outside of an `ITransaction` we can interact with Redis modules (or other non-standard commands) by using `Execute` and `ExecuteAsync`. However, those similarly named methods on the `ITransaction` interface would have the transaction be called and completed. 

My question is, am I missing something or is the ability to execute arbitrary Redis commands not on `ITransaction` yet?

Thanks for your time.

**Comment by mgravell** [comment]
It was an unfortunate oversight that the names overlap, but: they are
completely different overloads. Calling ExecuteAsync and passing a command
name / args should work fine and should not conflict at all with completing
the transaction.

I'll check this when I'm at my desk, but: I'm not aware of a gap here.

**Comment by mgravell** [comment]
confirmed, this works fine:

``` c#
using var muxer = await ConnectionMultiplexer.ConnectAsync("127.0.0.1:6379");
var db = muxer.GetDatabase();
RedisKey key = "abc";
var tran = db.CreateTransaction();
_ = tran.StringSetAsync(key, "def");
// this execute is the arbitrary-commands one (modules, etc)
var pending = tran.ExecuteAsync("get", new object[] { key });
// this execute is the transaction one
await tran.ExecuteAsync();
var val = await pending;
Console.WriteLine((string)val);
```

If you're seeing something that *doesn't* work, please provide an example.

**Comment by tombatron** [comment]
Well I'll be...

Right on. 

Thanks for the quick answer!
