### ISSUE TITLE
RedisTimoutException on saving string of length 92516952

### ISSUE THREAD

**Issue by SignASure** [StackExchange/StackExchange.Redis#1341]
StackExchange.Redis version 2.0.0.0

We are getting the following exception when saving string of length = 92516952 :

30-Jan-20 21:46:39 [7] ERROR DebugLogger: RedisTimeoutException

Timeout performing SETEX 433344c5-c84d-442c-94ac-1a93020e2a9b : GetWorkItemTypesAndFieldsInfoJob (10000ms), inst: 0, qs: 1, in: 0, serverEndpoint: Unspecified/localhost:6379, mgr: 10 of 10 available, clientName: PA-TFS-INTEG1, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=3,Free=32764,Min=2,Max=32767), v: 2.0.519.65453 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2197
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
   at inteGREAT.Web.Common.RedisHelper.SaveInCache(String key, String value, Nullable`1 expiry)

Regards,
Mursaleen

**Comment by mgravell** [comment]
Well, to point out the obvious; that's a 88MiB string *at least* (possibly more depending on UTF8, if it is a "string" string); it may be *slightly* prone to delays. Have you tried increasing the timeout to see what it actually takes, so we can compare and contrast that to what we might reasonably expect? Also: is this a local server? cloud? Obviously the bandwidth matters for such a payload. You might also want to look at the *append* options, i.e. send the payload in chunks.

**Comment by SignASure** [comment]
Thanks for the quick response.

Well, this is local server. Can you please let me know how to increase timeout? [**Have you tried increasing the timeout to see what it actually takes, so we can compare and contrast that to what we might reasonably expect?**]

**Comment by mgravell** [comment]
The timeout is specified when you call `Connect` or `ConnectAsync` - this can be done either in the configuration string, or in the `ConfigurationOptions` object. The details are [shown here](https://stackexchange.github.io/StackExchange.Redis/Configuration#configuration-options)

**Comment by NickCraver** [comment]
Answered above - closing out to cleanup!
