### ISSUE TITLE
Downgrading StackExchange.Redis version 2.0.601 to version 2.0.519 fixes StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: 

### ISSUE THREAD

**Issue by WillTierney** [StackExchange/StackExchange.Redis#1344]
Downgrading StackExchange.Redis version 2.0.601 to version 2.0.519 fixes
   message: Failed to add entry to distributed cache for XXXXXXXXXXXXXXXXXXXXXXXXXX0d718620-93ca-439f-9023-d20ae51d143c4599967900 in 0.0010s due to StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: SETEX XXXXXXXXXXXXXXXXXXXX0d718620-93ca-439f-9023-d20ae51d143c4599967900; SocketClosed on XXXXXXXXX.redis.cache.windows.net:6380/Interactive, Idle/MarkProcessed, last: SETEX, origin: ReadFromPipe, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, in: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.0.601.3402; IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=2,Free=32765,Min=37,Max=32767), Local-CPU: n/a ---> StackExchange.Redis.RedisConnectionException: SocketClosed on XXXXXXXXX.redis.cache.windows.net:6380/Interactive, Idle/MarkProcessed, last: SETEX, origin: ReadFromPipe, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, in: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.0.601.3402 --- End of inner exception stack trace --- at XXXXXXXXX.Caching.Redis.RedisContext.PutItemAsync[T](String key, T item, Nullable`1 timeToLive, SerializationMethod serializationMethod) at XXXXXXXXX.Framework.Caching.XXXXRedisCache.AddEntryToCacheAsync[TE,TI](TE entry, Nullable`1 timeToLive) at XXXXXXXXXFramework.Caching.XXXXXXXXXBaseDistributedCache.AddEntryAsync[TE,TI](TE entry, Nullable`1 timeToLive).

**Comment by NickCraver** [comment]
I think we've now identified this issue in #1374 - going to close this out and we'll get a fix in 2.1.x I hope this week.
