### ISSUE TITLE
Timeout when using Tls12

### ISSUE THREAD

**Issue by angelacalborean** [StackExchange/StackExchange.Redis#1346]
In my **.NET Framework 4.5.1** application I am using StackExchange.Redis.StrongName 1.2.6 to connect to Azure Redis. This is the code

```
    public RedisContext(string connectionString = null)
    {
        if (connectionString == null) return;

        Lazy<ConfigurationOptions> lazyConfiguration
            = new Lazy<ConfigurationOptions>(() => ConfigurationOptions.Parse(connectionString));

        var configuration = lazyConfiguration.Value;
        configuration.SslProtocols = SslProtocols.Tls12;//just added
        configuration.AbortOnConnectFail = false;

        Lazy<ConnectionMultiplexer> lazyConnection =
            new Lazy<ConnectionMultiplexer>(() => ConnectionMultiplexer.Connect(configuration));
        _connectionMultiplexer = lazyConnection.Value;

        LogProvider.IsDisabled = true;

        var connectionEndpoints = _connectionMultiplexer.GetEndPoints();
        _lockFactory = new RedisLockFactory(connectionEndpoints.Select(endpoint => new RedisLockEndPoint
        {
            EndPoint = endpoint,
            Password = configuration.Password,
            Ssl = configuration.Ssl
        }));
    }
```

In Azure, I have changed the Redis resource to use TLS1.2 and in code I have added this line:

configuration.SslProtocols = SslProtocols.Tls12;//just added

And now, nothing works anymore. This is the error I get in Application Insights:

Error connecting to Redis. It was not possible to connect to the redis server(s); ConnectTimeout

I have also tried to add ",ssl=True,sslprotocols=tls12" to the redis connection string, but with the same result.

For Ping command, I receive this:
**No connection is available to service this operation: PING; It was not possible to connect to the redis server(s); ConnectTimeout; IOCP: (Busy=4,Free=996,Min=128,Max=1000), WORKER: (Busy=1,Free=32766,Min=256,Max=32767), Local-CPU: n/a It was not possible to connect to the redis server(s); ConnectTimeout**

**Comment by Plasma** [comment]
Are you testing against a Basic Azure Redis instance by chance? It seems changing the minimum TLS version will reboot the (one and only, due to being Basic) instance within a few minutes and be offline for about 5 minutes from my testing.

The reboot also happens to Standard/Premium, but since its got a replica, you remain connected while the secondary gets rebooted (and then experience a short disconnect during the promotion).

If you just wait 10 mins it should actually connect OK. This caught me out too.

**Comment by NickCraver** [comment]
@angelacalborean did the above help? This isn't something we're familiar with, so @Plasma's advice is as good as anything I've got here. I do suggest upgrading to a newer framework version if at all possible due to changes in default to the TLS innards though.

**Comment by NickCraver** [comment]
Without more info here - closing this out to cleanup.
