### ISSUE TITLE
Documentation pages are 404-ing

### ISSUE THREAD

**Issue by sfilipi** [StackExchange/StackExchange.Redis#1347]
Links in https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/index.md  like

https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Basics 
don't resolve, they seem to lack the ,md file extension in the url

**Comment by mgravell** [comment]
that's because they're meant to be accessed [via here](https://stackexchange.github.io/StackExchange.Redis/); if there's something we can do to make it work in the source as well as the processed version, I'm all ears
