### ISSUE TITLE
Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by Cabanig28** [StackExchange/StackExchange.Redis#1349]
[git.txt](https://github.com/StackExchange/StackExchange.Redis/files/4202998/git.txt)
See here my Packages and App.Config

**Comment by Cabanig28** [comment]
Can anyone help me, I'm working on .NET Framework version 4.5.
I'm trying to add the data connection of PostgreSQL but this message came out.
"Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."
I tried different version but it didn't work.

**Comment by mgravell** [comment]
Hi; PostgreSQL sounds like ... completely unrelated. And your packages don't actually include StackExchange.Redis at all. Are you perhaps asking on the wrong project? However, the information you are looking for is probably this: https://nickcraver.com/blog/2020/02/11/binding-redirects/

**Comment by Cabanig28** [comment]
@mgravell Hello, What is StackExchange.Redis? do I need that?

**Comment by mgravell** [comment]
@Cabanig28 it is a tool for talking to redis. I don't know whether you are using redis. Since you came hee talking about postgresql,  I'm not sure what to think, honestly.

**Comment by Cabanig28** [comment]
@mgravell I see well Thank You so much for the reference.
Well appreciated.

**Comment by mgravell** [comment]
Closing this as I don't *think* there's anything for us to do here; if I'm wrong about that, please can you be *really specific* as to what you're asking?
