### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException : Timeout awaiting response

### ISSUE THREAD

**Issue by dpak1170** [StackExchange/StackExchange.Redis#1350]
I am trying to test about 2500 parellel calls trying to download the one key with data of 26Kb. I am not able to find a similar issue on github in the sense of the two parameters outbound/inbound. Can someone help me understand the two parameter and what should I be looking at...

StackExchange.Redis.RedisTimeoutException : Timeout awaiting response (outbound=2641KiB, inbound=14KiB, 15750ms elapsed, timeout is 15000ms), command=HGET, next: HGET KEY1, inst: 0, qu: 0, qs: 195, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: redisServer:6380, mgr: 10 of 10 available, clientName: ABC123, IOCP: (Busy=9,Free=991,Min=250,Max=1000), WORKER:

**Comment by mgravell** [comment]
question: is this over TLS or not? the most important number to me is "in: 0"; unfortunately this is largely meaningless if TLS is in the mix, hence the question.

As for the fundamental scenario; yes, we're aware of some problems with very high load, and I am actively exploring work we can do to get around this, *in conjunction with* the needed RESP3 work for redis v6; I'm increasingly of the opinion that in the mid-future we'll switch to a leased pool mode (without necessary changes to the caller), which should avoid all the problems of bulky operations vs concurrent load.

**Comment by dpak1170** [comment]
Yes this is TLS...

**Comment by dpak1170** [comment]
What will be the workaround in the interim for this?

**Comment by mgravell** [comment]
*right now*, the nature of the multiplexer is that it is going to try and throw all that data down a single pipe, which *in scenarios like above* is going to have backlog problems.

If you were just having *some* of the connections saturating the pipe, a common approach is to have a "fast muxer" and a "slow muxer", i.e. send all the big bulky operations down one pipe (with a higher timeout), and send the fast small operations down a different pipe.

In your case, I imagine multiple "equal" muxers would help spread the load, although ultimately you're *doing a lot here*. Maybe the *short term* workaround is simply: spawn a bunch (10?) of muxers, and round-robin through them for load.

---

The server can keep up, though; if we look purely at the theoreticals:

``` txt
redis-benchmark -d 26624 -c 2500 -t get
```

manages 33k rps, while:

``` txt
redis-benchmark -d 26624 -c 1 -t get -d 10
```

manages 14k rps

but all of this is based on running **LOCALLY**, and **without** TLS. How that works over TLS to an external server: big unknown.

**Comment by dpak1170** [comment]
This is what I am getting even with a pool of 50 mux but since parallely processed. Correction to the above question is doing 10000 calls instead of 2500. What is outbound and inbound in the exception message above and anything in the code that I can do to optimize for TLS connections?

Thank you for all your help...

**Comment by mgravell** [comment]
k; can I clarify a sec? is that 10k *operations* over a much more limited pool of workers (whether tasks or threads), or 10k *workers* (whether tasks or threads) all working independently asking for 1 request each? The inbound and outbound here can't be taken too literally; they're mostly to help me understand that data is flowing. It is essentially the amount of data that has flown through the pipe since that message was enqueued.

Ultimately, if you're saturating the pipe's capabilities: some things will time out. It is very hard to know what your physical limits are here. It is very much our intent to look into scenarios in which it can back up, and help resolve them. I don't have a magic wand for you today.

**Comment by dpak1170** [comment]
Its 10,000 tasks all queued at the same time and awaited using Task.WhenAll. I understand things will timeout eventually if there is too much to do but here the time out is not coming from the server but internal physical limit so a confusing exception if that.

**Comment by mgravell** [comment]
Ok. And in this situation, are you trying to simulate:

A) I genuinely will have 10k independent flows who are trying to
communicate at the same time, or
B) I want 10k answers, so I'm spawning 10k tasks to get them

If B, this really isn't a good way to solve this, and you'd be much better
off sending batches of say, 100, at a time. Or alternatively, spawn a small
number of tasks (10? 50?) who each get things (perhaps using StringGet
taking multiple keys, i.e. mget) until all 10k have been fetched.

**Comment by dpak1170** [comment]
Its A and I really trying to understand the limitations and what workarounds I can put in place other than increasing timeouts or retrying...

**Comment by mgravell** [comment]
Right; for A, what I would do is limit the concurrency through the pipe; there is *really no point* putting everything into the pipe at once; a semaphore depth of, say, 50 or 100 (although: play with the number) should be *more* than sufficient to ensure that the pipe (in particular, the return pipe) is kept busy; example (completely untested):

``` c#
        SemaphoreSlim _semaphore = new SemaphoreSlim(0, 100); // max concurrency
        public async Task<RedisValue> Get(RedisKey key)
        {
            await _semaphore.WaitAsync().ConfigureAwait(false);
            try
            {
                return await _db.StringGetAsync(key).ConfigureAwait(false);
            }
            finally
            {
                _semaphore.Release();
            }
        }
```

**Comment by NickCraver** [comment]
@dpak1170 does the above get you sorted? Our general advice will always be around optimizing the pipe here which Marc illustrates how to do :)

**Comment by dpak1170** [comment]
I have been able to circumvent this by using a connection pool instead and it has been holding for now. Thank you again for all your help guys...
