### ISSUE TITLE
RedisConnectionException: Internal failure

### ISSUE THREAD

**Issue by DavidSSL** [StackExchange/StackExchange.Redis#1354]
Here is the exception message we're getting

> InternalFailure (WriteException, 0-read, 0-sent, last-recv: 0) on localhost:6379/Interactive, Flushing, last: CLIENT, origin: OnEstablishingAsync, outstanding: 7, last-read: 4s ago, last-write: 4s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 4s ago, v: 2.0.519.65453

This a very weird error in the sense that we have 2 projects in solution which are both using the same version of the Redis client. The 1 project which is a console application will connect write and get values from the cache without any problem.

The project which is failing is an ASP.NET MVC project. 

As far as the code is concerned, we're simply calling 

``` csharp
var redis = ConnectionMultiplexer.Connect("localhost");
```

Upon stepping into the Redis Client code, the task is ending up as Faulted for whatever reason which I can't quite figure out. 

Any ideas what I can do to debug/resolve this?

We've also used the latest version of Redis i.e. 2.0.601 and still experience the same problem.

**Comment by mgravell** [comment]
internal failure sounds like an assembly binding problem; assembly binding is a huge PITA in every way; is there any inner-exception on this by any chance?

**Comment by DavidSSL** [comment]
Hi Marc,

You're absolutely right. It was indeed an assembly binding problem. There wasn't any inner exception but by ensuring that my IDE would break on every exception I was able to find that it was related to this https://github.com/StackExchange/StackExchange.Redis/issues/1130 where I'll post my solution.
