### ISSUE TITLE
Timeout awaiting response version: 2.0.601.3402

### ISSUE THREAD

**Issue by arabelaa** [StackExchange/StackExchange.Redis#1355]
Using StackExchange.Redis 2.0.601 inside .netstandard 2.0 library with a docker redis image redis:5.0.5  

Have noticed some Timeout exceptions and checked the link suggested - https://stackexchange.github.io/StackExchange.Redis/Timeouts 
My scenario fits in "Are you seeing a high number of busyio or busyworker threads in the timeout exception?" (see some examples below)

While reading I stumbled upon this remark

> Note that You shouldn’t need a much fine-tuning of this from 2.0, since the dedicated thread-pool should be servicing most of the load.

So I don't need to use the environment variable  `COMPlus_ThreadPool_ForceMinWorkerThreads` to adjust the MinThreads setting (for 2.0 version). 

Not sure how to proceed in this case.
Any hints are appreciated?

```

StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 9070ms elapsed, timeout is 5000ms),
command=UNLINK, next: UNLINK FIELDOPENRQ/BE-AN-MI-OUT-1, inst: 0, qu: 0, qs: 1, aw: False, rs: DequeueResult, ws: Idle, in: 0, in-pipe: 4, out-pipe: 0,
serverEndpoint: Unspecified/redis:6379, mgr: 6 of 10 available, clientName: d26883ca3545,
IOCP: (Busy=0,Free=1000,Min=4,Max=1000),
WORKER: (Busy=4,Free=32763,Min=4,Max=32767),
v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)


Timeout awaiting response (outbound=0KiB, inbound=0KiB, 72286ms elapsed, timeout is 5000ms),
command=SET, next: SET LASTINTERPRETED/NL-AV-BP-OUT-2, inst: 1, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0,
serverEndpoint: Unspecified/redis:6379, mgr: 10 of 10 available, clientName: f49a27c48f65,
IOCP: (Busy=0,Free=1000,Min=4,Max=1000),
WORKER: (Busy=10,Free=32757,Min=4,Max=32767), 
v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
```

**Comment by bklooste** [comment]
How are you using it , I just had this  issue with a continueswith when i removed it problem went away.

**Comment by NickCraver** [comment]
How big is the payload you are sending here, and what environment are you in? (e.g. high latency? cloud?)

**Comment by arabelaa** [comment]
The biggest key is around 720 KB. And sometimes we experience networking issues on the devices where the docker containers are deployed.

**Comment by NickCraver** [comment]
@arabelaa For your networking issues, are we talking about drops, or stalls?
- For stalls you'd either need a sufficiently high timeout to cope with such stalls.
- For drops, you'd need to retry (but we don't know if the message dropped on the way _to_ Redis or the response dropped on the way _from_ Redis...so keep in mind: this isn't safe to do blindly).

Ultimately, we're just alerting you _that there was an issue_. If that issue is outside the library, the best we can do is advise on workarounds :)

**Comment by arabelaa** [comment]
@NickCraver It's usually drops. Is there a way to see if the message was dropped on the way _to_ or _from_ Redis (in an easy way)?  
And thanks a lot for your responses.  

I already increase the timeout  - it was the only idea I had (and meanwhile I am monitoring the impact).

**Comment by NickCraver** [comment]
@arabelaa There's no way to connect that. Picture it this way: we sent someone to pick up something from the store 10 miles away and they never came back. Never seen or heard from again! Probably aliens. In any case, we don't know if they disappeared before or after exchanging money for goods and services.

The only way you could check for this would be _sometimes_ and very specifically. For example: you tried to set a string - you could check if it's there. But something else like "increment a string" isn't so easy to check. So overall: there's no global way to do this, even for _most_ cases. If it's a get/fetch and not a mutating operation, you could just run it again - _those_ are safe, but mutations are not.

Sorry I don't have better news there, that's just the reality of the situation :-/

**Comment by arabelaa** [comment]
Point taken. Thanks!
