### ISSUE TITLE
The type initializer for 'Npgsql.TypeMapping.GlobalTypeMapper' threw an exception.

### ISSUE THREAD

**Issue by Cabanig28** [StackExchange/StackExchange.Redis#1356]
Using Visual Studio 2017  try using the Server Explorer to add a connection to a Postgres database. Click Test connection. The issue An error is shown with: The type initializer for 'Npgsql.TypeMapping.GlobalTypeMapper' threw an exception.

Before that I installed System.Runtime.CompilerServices.Unsafe v4.5.2 and System.Numerics.Vectors v4.4.0 to fix the error message "Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1" and Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0.

I have no idea to fix this "The type initializer for 'Npgsql.TypeMapping.GlobalTypeMapper' threw an exception."

.NET framework 4.5
Npgsql version 4.1.1.2

**Comment by mgravell** [comment]
This is not the npgsql project. To put it in simple terms, you've wandered into a bakery to ask about the steering on you car being a bit iffy. You're probably looking for https://github.com/npgsql/npgsql

**Comment by mgravell** [comment]
Genuine question: how did you end up *here specifically*? I don't mean that rudely - I'm trying to see if there's a broken link or some confusing guidance somewhere that has led you here (twice), so that we can fix it (or ask for it to be fixed, as it is probably outside of our direct control).

(cross reference, for tracking purposes: https://github.com/StackExchange/StackExchange.Redis/issues/1349)

**Comment by Cabanig28** [comment]
@mgravell I'm sorry man, I just want to add the connection of PostgreSQL database to Visual Studio 2017. I already have a database in postgres... I don't know what I'm going to install first to add that connection.

After I installed Npgsql PostgresSQL Integration in Visual Studio=>Tools=> Extension and update, I created new project and go directly to Manage Nuget Packages and installed System.Runtime.CompilerServices.Unsafe v4.5.2 and System.Numerics.Vectors v4.4.0. 
And I directly tried to add the connection in Server Explorer.

Again I'm sorry, bare with me. I have no idea to this. I just want to add the data connection of postgres in visual studio so that I can add ADO.NET Entity Data model.

**Comment by mgravell** [comment]
I appreciate you're having a coding issue here. What I'm trying to emphasize is that you're asking in the wrong place.

Right now, we're talking in the issue list of a specific library, StackExchange.Redis, which is a tool for communicating with Redis in .NET. If you had a question or problem using StackExchange.Redis, I'd be all over that.

However, the thing you're asking about is Npgsql, an ADO.NET provider for talking to postgres. I am not a postgres / Npgsql user, let alone expert, and frankly: even if I were, this *isn't the place to have that conversation*.

What you need to do is: head over to https://github.com/npgsql/npgsql, which is where that happens, and discuss it *there*, with people who actually know what they're talking about.
