### ISSUE TITLE
Converting RedisValue to byte[]

### ISSUE THREAD

**Issue by thomasd3** [StackExchange/StackExchange.Redis#1358]
How can this be done?

I see that there is a byte[] operator and also that there is a non public method (DirectObject), but I can't find how to get a byte[] out of the RedisValue object.

I posted a thread on SO with issue as well: https://stackoverflow.com/questions/60351343/with-stackexchange-redis-how-do-i-convert-a-redisvalue-to-byte-in-f

**Comment by mgravell** [comment]
I see you've closed this. I assume that means you found an answer, but: if
there is an API we could add to make this easier for F#, I'm open to
suggestions.

**Comment by thomasd3** [comment]
I think the API is not a problem, it’s well done but maybe a couple F# examples would help: The issue in my case was that the byte[] operator is implicit, which is very straightforward to use on C# but you can’t use the implicit operator directly in F# so it’s a bit convoluted to use. Similarly, when you want to pass key / value, in F# you need to specify the types explicitly which makes the code a lot more verbose. But it’s also something you need to find through forums, etc as it’s not obvious at the beginning.
Examples would help or a small F# shim but then it turns into a maintenance issue.

**Comment by mgravell** [comment]
I dabble with F#, but I'm not an expert. If there is some set of
methods/etc that we could add to complement the operators, to make it more
usable from F#, then that is something very valuable.

Would you care to suggest something that would be idiomatic in terms of
what you would expect/prefer to have available?

**Comment by thomasd3** [comment]
This is an example of a call in F#:

    member this.Set (key : string, value : string) =
        db.StringSet(RedisKey.op_Implicit key, RedisValue.op_Implicit value) |> ignore

we have to explicitly convert the key and value to the proper types.

now, for the type conversion, this is more complex:

    member this.GetByteArray (key : string) : byte[] option =
        let d = db.StringGet(RedisKey.op_Implicit key)
        match d with
        | _ when d.HasValue ->
            let inline (!>) (x:^a) : ^b = ((^a or ^b) : (static member op_Implicit : ^a -> ^b) x)
            Some (!> d)
        | _ -> None

in this case the important line is:

        let inline (!>) (x:^a) : ^b = ((^a or ^b) : (static member op_Implicit : ^a -> ^b) x)

it defines an operator to be able to use the implicit C# operator, and this part applies it:

    !> d

the only way to make it less verbose in F# would be to add a shim where the types would be explicit so that there is not need to explicitly state them at every step.
this could possibly be generated automatically through reflection as well.

Unfortunately, I've only a few months of F# experience so it would be good to bring this discussion to StackOverflow to get feedback from experienced F# programmers about what the best way to proceed would be.

**Comment by mgravell** [comment]
Would a bunch of methods like AsByteArray, AsInt64 work better?

**Comment by thomasd3** [comment]
yes, this would certainly work as the typing would be handled by the method's signature. The main thing to remember is that F# doesn't do implicit conversions. It does infer the types when there is ambiguity, but in the case of a very friendly C# api, like the one you have done, it becomes more verbose.

For the get, having typed methods would be a lot easier. I guess the set is similar. Can the key be of different types, or is it always a string?

**Comment by mgravell** [comment]
Keys are not quite as flexible as values (we don't bother with numeric
support), but it still supports a range of both string and buffer sources,
since redis keys are technically binary safe, and any combination of bytes
is a valid key. Most people use strings, though :)

**Comment by thomasd3** [comment]
I guess if the "type explicit" methods take strings, it will probably fit most people's use case.
