### ISSUE TITLE
The stream responses are cumbersome compared to other stream libs  

### ISSUE THREAD

**Issue by bklooste** [StackExchange/StackExchange.Redis#1359]
eg getting field by field names is awkward , then you need null checks etc..  Something like JItem indexers would be much more flexible and you can have thousands of these in a code base.  The following are from integration / end to end tests.  Is it possible to cast to a valuetuple as that may be cleaner ? 

```
           var streamResult = await redisConnection.StreamRangeAsync(streamName, "0-0", "+", 1000);
            var evntJson = streamResult
                .Select(x => x.Values)
                .Select(x => Encoding.UTF8.GetString(x.First(field => field.Name == "msg").Value))
                .Select(json => (dynamic)JsonConvert.DeserializeObject<System.Dynamic.ExpandoObject>(json))
                .ToList();
```

vs
```
 var streamResult = await eventStoreConnection.ReadStreamEventsForwardAsync(streamName, 0, 1000, false);
            var evntJson = streamResult
                .Select(x => x.Values)
                .Select(x => Encoding.UTF8.GetString(evnt.Event.Data)
                .Select(json => (dynamic)JsonConvert.DeserializeObject<System.Dynamic.ExpandoObject>(json))
                .ToList();
```

**Comment by mgravell** [comment]
Firstly, I must note that I *think* you're making that harder than it needs to be:

- the "from start to end" is the implicit defaults; the only optional parameter you need is `count`
- the conversion to `string` via UTF8 is implicit

However; looking at the code you're showing, I suspect that an indexer on `StreamEntry` makes a lot of sense here. Just by adding the indexer, we can do:

``` c#
var streamResult = await db.StreamRangeAsync(streamName, count: 1000);
var evntJson = streamResult
    .Select(x => (dynamic)JsonConvert.DeserializeObject(x["msg"]))
    .ToList();
```

Thoughts?

**Comment by mgravell** [comment]
also, I'm a little confused in your comparison example; you had:

``` c#
.Select(x => Encoding.UTF8.GetString(evnt.Event.Data)
```

but ... that doesn't seem to make sense? a: `evnt` is not defined, and b: it isn't clear how that is fetching the field called `"msg"` (which is what you do in the first example)

**Comment by mgravell** [comment]
I'm also a little confused as to what you mean here:

> Is it possible to cast to a valuetuple as that may be cleaner ?

Question: which bit would you propose exposing as a value-tuple?

(additional note: value-tuples are generally not a good idea in an API - **especially** when that API touches something that isn't .NET Core, due to assembly binding problems; however, I am open to making things decomposable, *when that makes sense* - I'd need to understand the scenario to see whether it makes sense, though)

**Comment by mgravell** [comment]
indexer addition is merged

**Comment by NickCraver** [comment]
@bklooste Does the above help?

**Comment by bklooste** [comment]
Sorry for the delay but as you said the indexer makes sense it it would help a lot .  Generally the other solutions i have used have been more traditional event based eg a body bytes  , metadata bytes a type field  etc ..

Redis streams is intriguing that it allows a destructed rather than json message ( and the indexer would be even nicer)  , alas the current project messages are too big for this for this but extracting the message as per above would be a benefit to all.

**Comment by mgravell** [comment]
the indexer has been there since something like 2.1.0 - possibly 2.0601 - it seems to have missed the release notes, but: it is there
