### ISSUE TITLE
Reading from read replica nodes are not working for cluster enabled mode

### ISSUE THREAD

**Issue by humayun-ahmed** [StackExchange/StackExchange.Redis#1363]
Hello guys,
We are using Aws Redis where 2 shards, each shard contain 1 primary node and 1 replica node. 

What we have noticed that only the 2 primary nodes are using, replica nodes are never using. Where replica nodes should be use for reading purpose.

Can anybody give the information whether this is a bug or I should do something like change any configuration in coding side or cluster setup?

**Comment by mgravell** [comment]
There is an optional flags parameter on all commands that allows you to control replica usage; the default is "prefer master"; have you specified "prefer slave" to push work to the replica when you don't need guaranteed fresh data?

**Comment by humayun-ahmed** [comment]
> prefer master

Thank you mgravell, I'll try that and get back soon

**Comment by humayun-ahmed** [comment]
Its working :)
