### ISSUE TITLE
Subscriptions to slaves not allowed

### ISSUE THREAD

**Issue by piccit** [StackExchange/StackExchange.Redis#137]
In `Subscription.SubscribeToServer`, `multiplexer.SelectServer` is using `DemandMaster`. (also present in `RedisSubscriber.IsConnected`)

redis itself replicates publishes from masters to slaves and allows for subscriptions to be made on the slave. Therefore, it should be a valid use case for StackExchange.Redis to place a subscription against a slave.

Unless I'm missing something that would explain the `DemandMaster`, I'm thinking it should be `PreferMaster` instead?

Thanks

**Comment by mckenzieg1** [comment]
An even better solution would be to have `Subscription.SubscribeToServer` use the supplied `CommandFlags` for server selection as well as for the command itself. This allows the client to specify the desired selection mode.

I am about to submit a PR with this fix.

**Comment by piccit** [comment]
Same as issue #321 which has some discussion on. Not sure if there is a "merge issue" option or if someone wants to close one to the other

**Comment by NickCraver** [comment]
Merging with #321 since it has more info - we'll indeed have to address the reconnect issue.
