### ISSUE TITLE
Achieving Strong durability and consistency in writes.

### ISSUE THREAD

**Issue by Raghavendra-Kandi** [StackExchange/StackExchange.Redis#1373]
https://docs.redislabs.com/latest/rs/concepts/data-access/consistency-durability/

This Doc mentions WAIT command for better consistency and Durability. I did not find WAIT command equivalent exposed in IDatabaseAsync interface in stackexchange.redis.

The only option I see is to use Execute("WAIT", {args}).

While I am evaluating the performance vs data consistency trade off for my project, Is that the only option for wait command or I am I missing something here?

**Comment by mgravell** [comment]
WAIT comes under the heading of "blocking operations"; we have a plan
there, but today that is not supported because it breaks the multiplexer.
Watch this space!

**Comment by NickCraver** [comment]
Folding into #1961 for designing for blocking ops!
