### ISSUE TITLE
Question, Why PhysicalConnection is  a WeakReference object?

### ISSUE THREAD

**Issue by n1l** [StackExchange/StackExchange.Redis#1375]
Hi, I'm investigating an issue with closed socket during active redis work process.
And I've found an interesting pice of code:

```
        private readonly WeakReference _bridge;
        public PhysicalBridge BridgeCouldBeNull => (PhysicalBridge)_bridge.Target;
```

in PhysicalConnection.cs

My guess is, a weak refrence to PhysicalBridge, can dispose PhysicalConnection accidentally during garbage collection.

because of
```
            try
            {
                var tmp = physical;
                physical = null;
                tmp?.Shutdown();
            }
```
in
```
~PhysicalBridge()
{
```

So can you please share some thoughts about it?

**Comment by mgravell** [comment]
The topology *should* mean that this is never an issue; however, a solid case could be made that it shouldn't' be talking to *any* other objects in a finalizer; I'll see if I can remember what the reasons were here

**Comment by NickCraver** [comment]
This was one of the changes in our allocations investigation, especially before `ConnectionMultiplexer` reuse in unit tests. Here's the commit: 7171938db3cb2972dd9e040396b8a1aa9e3be302

**Comment by n1l** [comment]
Thank you, @NickCraver , but it still not clear for me from your message, why it's a WeakReference object?

**Comment by NickCraver** [comment]
@n1l So that when we go to dispose from the other side, it's not rooted in a loop here. Because people hold onto the multiplexer, this reference rooting can happen :)

**Comment by n1l** [comment]
@NickCraver please do not close the issue for now, I need to check one thing, and may be I'll ask more questions here.

**Comment by NickCraver** [comment]
@n1l Roger - happy to answer!

**Comment by NickCraver** [comment]
No further question posted, so closing this out :)
