### ISSUE TITLE
How to use StackExchange.Redis to access multiple Redis

### ISSUE THREAD

**Issue by DrDao** [StackExchange/StackExchange.Redis#1388]
hi,
My partners and I are using StackExchange.Redis as a client to access Redis. This is a great library, but we encountered a problem that was tricky and hardly found documentation or instructions.
The reason is that we have multiple Redis servers, and they each cache different data. Our API has to go to different Redis servers, but I don't know how to use StackExchange.Redis to access different cache servers?
Since the environment we are using is .NET CORE 3.1 and DI can only operate one implementation class for one interface, what should be done for multiple implementation classes?

Thank you

**Comment by mgravell** [comment]
As far as the library is concerned: you just use different connection strings to indicate different servers.

If sounds like the real question here is the DI aspect. I can't advise on that - that's not part of this library.

**Comment by DrDao** [comment]
> 就库而言：您仅使用不同的连接字符串来指示不同的服务器。
> 
> 如果听起来像是真正的问题，那么这里是DI方面。我对此不建议-这不是该库的一部分。


Thank you very much for your help, I have solved the problem from the community. Thank you

**Comment by DrDao** [comment]
> As far as the library is concerned: you just use different connection strings to indicate different servers.
> 
> If sounds like the real question here is the DI aspect. I can't advise on that - that's not part of this library.

Thank you very much for your help, I have solved the problem from the community. Thank you

**Comment by KamranShahid** [comment]
> > As far as the library is concerned: you just use different connection strings to indicate different servers.
> > If sounds like the real question here is the DI aspect. I can't advise on that - that's not part of this library.
> 
> Thank you very much for your help, I have solved the problem from the community. Thank you

Share your solution
