### ISSUE TITLE
when async && thread.sleep ,there're something interestring happend.

### ISSUE THREAD

**Issue by cysnet** [StackExchange/StackExchange.Redis#1404]
when i operate redis asyncchronously, if there is a time-consuming operation after the asynchronous operation， differen requests will be executed one by one. 

>            
            var connectionMultiplexer = ConnectionMultiplexer.Connect(redisOptions.RedisConnectString);
            services.AddScoped<IDatabase>(service =>
            {
                return connectionMultiplexer.GetDatabase();
            });

> 
        [HttpGet("redis")]
        public async Task<IActionResult> GetRedisAsync(string a)
        {
            logger.LogError($"in {DateTime.Now.ToString()}");
            await mQTransRedis.LockTakeAsync(a, a,TimeSpan.FromSeconds(10));
            logger.LogError($"end {DateTime.Now.ToString()}");
            Thread.Sleep(1000 * 5);
            return Ok(DateTime.Now);
        }

**Comment by mgravell** [comment]
What library version and framework version are we talking about here?

**Comment by cysnet** [comment]
> What library version and framework version are we talking about here?

net core 3.1

stackexchange.redis 1.2.6

**Comment by mgravell** [comment]
k; the first thing I'm going to say here, then, is "try a more recent library version"

**Comment by jessehouwing** [comment]
Use `Task.Wait()` instead of `Thread.Sleep()`.

**Comment by mgravell** [comment]
@jessehouwing `Task.Delay`?

**Comment by jessehouwing** [comment]
Yes of course.

**Comment by NickCraver** [comment]
Without more info here - closing this out to cleanup.
