### ISSUE TITLE
Question: what is the limit of maxim hits and how to setup maxmemory-reserved, and maxfragmentationmemory-reserved

### ISSUE THREAD

**Issue by hshazli** [StackExchange/StackExchange.Redis#1409]
I used Azure Redis cache i need to know if there is limit to hits per second
and also what is the safe range for maximum hits
also what is the suitable value for maxmemory-reserved, and maxfragmentationmemory-reserved

**Comment by mgravell** [comment]
Those sound like azure redis switches, is that right? If so, that is an
interesting topic, but probably not one that I should weigh in on. You
might refer to https://stackoverflow.com/q/42170200/23354

**Comment by hshazli** [comment]
yes it is  azure redis , i see this article but no one tell me what the exact value should i set for both

**Comment by mgravell** [comment]
I appreciate your frustration there, but: that setting is not really anything to do with this library. This is a server / provider question.

**Comment by dceravigupta** [comment]
We typically use 5% of total memory of a shard. So if we are using P4 cache, i.e. 53GB shard size, we configure both of them as 2650 each.

**Comment by NickCraver** [comment]
Since this is a server issue only, closing out to cleanup.
