### ISSUE TITLE
Question: What happened to version 2.1.0?

### ISSUE THREAD

**Issue by jose3m** [StackExchange/StackExchange.Redis#1411]
Hi all.

Some days ago it was released the version 2.1.0 but only in a few days it was removed (I have found nothing about the reason).
This new version had a lot of fixes and new adds ant I was expecting it since the las released version was from about 1 year ago and has important issues.
The question is, Is it expected to re-release it and when?

Thank you very much for you time and your work.
Regards

**Comment by mgravell** [comment]
There were some stability glitches in the new sentinal API; we're about to re-release, probably later today; the CI build is available on myget at https://www.myget.org/F/stackoverflow/api/v3/index.json

Release notes have been updated here: https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes

**Comment by jose3m** [comment]
Great news !!!
Thanks.
