### ISSUE TITLE
Request for option to connect async after getting a ConnectionMultiplexer

### ISSUE THREAD

**Issue by jesperkristensen** [StackExchange/StackExchange.Redis#1412]
I am currently registering ConnectionMultiplexer in CI like this:
`services.AddSingleton(_ => ConnectionMultiplexer.Connect(redisConnectionString))`

But it causes errors when Redis is not responding at the moment my service starts. I am adding `abortConnect=false` to handle that, but it seems that even with that option, the Connect method only returns when the initial connection has been attempted.
I would like to complete my DI configuration in before or concurrently with connecting to Redis, so my application startup does not depend on Redis.
I could wrap the ConnectionMultiplexer like below, but I think it would be nicer if it was handled within ConnectionMultiplexer.

```
services.AddSingleton(_ => ConnectionMultiplexer.ConnectAsync(redisConnectionString))

public class MyService
{
	private readonly Task<ConnectionMultiplexer> c;
	public MyService(Task<ConnectionMultiplexer> c) => this.c = c;
	public async Task MyMethod(string key) => await (await c).GetDatabase().StringGetAsync(key);
}
```

vs.

```
services.AddSingleton(_ => ConnectionMultiplexer.Connect(redisConnectionString))

public class MyService
{
	private readonly ConnectionMultiplexer c;
	public MyService(ConnectionMultiplexer c) => this.c = c;
	public async Task MyMethod(string key) => await c.GetDatabase().StringGetAsync(key);
}
```

**Comment by NickCraver** [comment]
Apologies for missing this one - the solution for this would be to use a `Lazy<T>` around the multiplexer to control when it spins up.

**Comment by NickCraver** [comment]
Happy to reopen this if anyone has further questions, closing out to tidy up for now.
