### ISSUE TITLE
RedisTimeoutException

### ISSUE THREAD

**Issue by Coder2005** [StackExchange/StackExchange.Redis#1415]
We are using Redis to store sessions , all worked fine till we were pointing to .net framework 4.5.1 , now we have upgraded everything to 4.7.2 and upgraded the redis package from 1.2.6 to 2.0.6 and tried various version even the latest version released yesterday we keep on getting below exception and cpu usage peaks too.

Timeout performing GET (3000ms), 
active: GET person:xyzz@gmail.com,
 next: SETEX person:xyzz@gmail.com ** possible thread-theft indicated;
 see https://stackexchange.github.io/StackExchange.Redis/ThreadTheft ** , inst: 1, qu: 0, qs: 16, aw: False, 
 rs: CompletePendingMessageSync, ws: Idle, in: 0, in-pipe: 39, out-pipe: 1634, serverEndpoint: testcloud.redis.cache.windows.net:6379, mc: 1/1/0, 
 mgr: 9 of 10 available, clientName: OpenSpaceGUI_IN_0, IOCP: (Busy=14,Free=986,Min=2,Max=1000), WORKER: (Busy=0,Free=32767,Min=2,Max=32767), v: 2.1.28.64774 
(Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

StackExchange.Redis.RedisTimeoutException: Timeout performing SETEX (3000ms), next: SETEX person:24828, inst: 0, qu: 0, qs: 20, aw: False, rs: ReadAsync, ws: Idle, in: 1055, in-pipe: 0, out-pipe: 768, serverEndpoint: testcloud.redis.cache.windows.net:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: xyxxGUI_IN_0, IOCP: (Busy=31,Free=969,Min=2,Max=1000), WORKER: (Busy=2,Free=32765,Min=2,Max=32767), v: 2.1.28.64774 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at Iris.OpenSpace.Redis.Implementation.RedisCache.StringSet(String key, Object obj, TimeSpan expiry, Int32& objectLength, CommandFlags commandFlags)
   at Iris.OpenSpace.Cache.Infrastructure.Impl.CacheLayer.AddObjectToCache(String cacheName, Int32 id, Object objectToAdd)

Any help will be appreciated .

Thanks,
Renu

**Comment by mgravell** [comment]
The error message says that it has detected a possible thread-theft scenario; have you read the link that it points you to, to see if that applies in your case?

**Comment by Coder2005** [comment]
Thanks @mgravell i did try both option as per in mentioned thread , that have reduced the number of timeout exception but still I get the Redis time out exception even when I fire 35 threads .

**Comment by mgravell** [comment]
What is the 35 threads in this context? I'm unclear what you mean there.
And did you check read the thread-theft link and try the remediation for
unfriendly sync-contexts?

**Comment by Coder2005** [comment]
We have to roll over the code twice from production because of Redis timeout , so now I am running load test and if I run 35 and over threads parallel I get few time outs previously I was getting loads of timeouts , but we are still are not certain that upgrading to latest Redis library and adding configuration setting as above and setting the connectoon multiplexer  in app start as the thread left link.

**Comment by mgravell** [comment]
OK, can I try and play back my understanding of that (because I'm unclear):

You're running a stress test, and it is becoming unstable at 35 concurrent
callers. Is that right? If so, what is the workload here? (What sorts of
commands, payload sizes, etc) And the server topology? (Talking to a 40
node cluster setup is different to talking to a single redis-server node,
for example). Can your workload and setup perhaps be demonstrated in a
minimal repro that we could run locally to see what you're seeing?

**Comment by KamranShahid** [comment]
@Coder2005  what type of application it is ?
We ahve recently faced similar thing and in the end dedicated more minimum thread in our .net core 3.1 application

**Comment by NickCraver** [comment]
If we had more info and this is still occurring on latest, happy to reopen and advise but this is one of many system-overloaded issues open so closing to cleanup old issues in this case.
