### ISSUE TITLE
What is the best practice filtering redis values after Keys command

### ISSUE THREAD

**Issue by yusuf-kayikci** [StackExchange/StackExchange.Redis#1416]
Hello

I have clustered redis(3 instance) and I need to search some values.I have a key model so I know that I need a key pattern and I do it like below

I do that with with parallel foreach because I have about 2000 keys that has same key pattern.
```
            List<RedisKey> keys = new List<RedisKey>();
            List<T> result = new List<T>();
            Task[] tasks = null;
            var t = Task.Run(() => {
                Parallel.ForEach(redisConnection.GetEndPoints(), ep => {
                    var server = redisConnection.GetServer(ep);
                    var foundedKeys = server.Keys(pattern: "xxxx*");
                    if (foundedKeys != null)
                        foreach (var item in foundedKeys)
                        {
                            var device = RedisHelper.GetData<T>(item); // Im getting values one by one
                            if (device != null)
                                result.Add(device); // I stored my redis values
                        }
                    //GET KEYS ASYNC FOR MORE PERFORMANCE
                });
            });
            t.GetResult();
```
As you see I get all redis values that matched with keypattern and Im getting one by one values asking again redis. I dont like it so much because when there are much key , its not good about performance getting all keys and again asking to redis for values.
Is there any better way to do this?
Thanks ..

**Comment by mgravell** [comment]
Frankly, the moment you're using `SCAN` (it won't be using `KEYS` here), you need to accept that it is going to be suboptimal. However, you can improve the performance here by batching - consider building groups of, so, 50 or 100 keys, and using multi-get to fetch them in one go; you could borrow `Batchify` from [here](https://github.com/StackExchange/StackExchange.Redis/issues/1145#issuecomment-492592923), and do something like:

``` c#
foreach (var batch in foundedKeys.Batchify(100)) {
    var devices = ...
    foreach(var device in devices)
    {
        if (device != null) result.Add(device);
    }
}
```

Note also that your existing code is not thread safe; `List<T>` cannot be used from parallel code without synchronization.

I can't tell you what the `var devices = ...` should be, since `RedisHelper` is presumably yours, not mine; but: there are multi-get APIs in SE-Redis.

**Comment by yusuf-kayikci** [comment]
Thanks @mgravell 
Scan is looking better than Keys also about performance.My final code at below
As you said `List<T>` was not thread safe .I use `ConcurretBag<T>` instead of `List<T>` for thread safe
```
            ConcurrentBag<T> result = new ConcurrentBag<T>();
            Parallel.ForEach(redisConnection.GetEndPoints(), ep =>
            {
                int nextCursor = 0;
                do
                {
                    var server = redisConnection.GetServer(ep);
                    var redisResult = server.Execute("SCAN", new object[] { nextCursor.ToString(), "MATCH", keypattern, "COUNT", "10000" });
                    var innerResult = (RedisResult[])redisResult;
                    nextCursor = int.Parse((string)innerResult[0]);
                    IEnumerable<string> resultLines = ((string[])innerResult[1]);
                    foreach (var item in resultLines)
                    {
                        var device = GetData<T>(item);
                        if (device != null)
                            result.Add(device);
                    }
                }
                while (nextCursor != 0);
            }).AsTaskResult();
```

**Comment by mgravell** [comment]
I think you misunderstood me. The library already uses SCAN internally. You
didn't need to change that part. The only change I was suggesting was the
batching.

**Comment by NickCraver** [comment]
Closing out to cleanup here.
