### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException on Azure

### ISSUE THREAD

**Issue by SergeyZubatkin** [StackExchange/StackExchange.Redis#1426]
Hi All,
Could anybody help to identify the root cause of the RedisTimeoutException on Azure using on StackExchange.Redis version 2.0.601.3402
Azure Redis Metrics are OK, Threads count and Memory consumption on the app are OK, no deadlocks detected on the dump.

13184 13:58:09 ERROR GetItem=> StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL (5000ms), next: EVAL, inst: 42, qu: 0, qs: 26, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: Unspecified/XXXXXXXX.redis.cache.windows.net:6380, mgr: 10 of 10 available, clientName: RD000AC00B0A0A, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=30,Free=32737,Min=4,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2239
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 1134

**Comment by mgravell** [comment]
well, you're doing a lot of `EVAL`s there; any chance your Lua scripts are just slow? does azure provide access to the `slowlog`?

**Comment by SergeyZubatkin** [comment]
@mgravell yes, a lot of EVALs.
slowlog get returns next data, I remove data seems to be app specific for security reasons
As I understand 3) means time takes in microseconds and it seems not be huge
1) 1) (integer) 16
    2) (integer) 1586421375
    3) (integer) 17374
 2) 1) (integer) 15
    2) (integer) 1586394349
    3) (integer) 33011
 3) 1) (integer) 14
    2) (integer) 1586387285
    3) (integer) 39045
 4) 1) (integer) 13
    2) (integer) 1586360922
    3) (integer) 10490
 5) 1) (integer) 12
    2) (integer) 1586359998
    3) (integer) 14379
 6) 1) (integer) 11
    2) (integer) 1586358189
    3) (integer) 10659
 7) 1) (integer) 10
    2) (integer) 1586358189
    3) (integer) 10634
 8) 1) (integer) 9
    2) (integer) 1586341287
    3) (integer) 10757
 9) 1) (integer) 8
    2) (integer) 1586326349
    3) (integer) 48825
10) 1) (integer) 7
    2) (integer) 1586313222
    3) (integer) 12805

**Comment by SergeyZubatkin** [comment]
@mgravell The same is for StackExchange.Redis 2.0.519 version, we upgraded to the latest (2.0.601) after start receiving this errors.

**Comment by mgravell** [comment]
indeed, 3 is microseconds; I don't have an immediate explanation - is it reproducible on demand? is there something I could do with my own azure instance to readily see the same thing?

**Comment by SergeyZubatkin** [comment]
Sorry but it could be reproducible only on our app. 
We have a lot of parallel requests to the Redis for the same keys (EVAL+Get+Set). 
Previous version of our app does not have such problems with timeout for the same scenario/installation.
We have not changed the functionality which works with Redis since last version of our app.

**Comment by mgravell** [comment]
all of this simply continues to reinforce to me that I need to emphasize finishing up the work to move to the new back-end; essentially, I have some "v3" work in progress that should allow us to radically fix a ton of performance / stall problems; the problem at the moment is that it is whack-a-mole: if we push too hard on one side to prevent scenario A, then scenario B happens; the new code is *much much* simpler, and tidily avoids all of the scenarios that can lead to stalls; it also increases throughput at the same time.

My internal debate is: how much time to spend trying to keep massaging v2 vs how much time to spend working on getting the v3 bits tested and "in".

**Comment by SergeyZubatkin** [comment]
@mgravell thank you for everything you are doing!
What do you think if we try to upgrade to 2.1.30 version, can this help or there was no any changes related to the timeouts since 2.0.601?

**Comment by SergeyZubatkin** [comment]
@mgravell we figured out the problem, two month ago we removed ThreadPool.SetMinThreads from one of our components, reverting this line solves the problem with RedisTimeoutException.
Although dumps have not shown thread starvation, it is clear from error message 
WORKER: (**Busy=30**,Free=32737,**Min=4**,Max=32767)
Adding new thread to the pool takes 500ms.
