### ISSUE TITLE
StackExchange.Redis dependency conflicts for System.IO.Pipelines

### ISSUE THREAD

**Issue by aravindyeduvaka** [StackExchange/StackExchange.Redis#1432]
Dependencies for SE.Redis 2.1.30:
Pipelines.Sockets.Unofficial (>= 2.1.6)
**System.IO.Pipelines (>= 4.7.0)**

But the only version of Pipelines.Sockets.Unofficial (>= 2.1.6) available is https://www.nuget.org/packages/Pipelines.Sockets.Unofficial/2.1.8 (I think 2.1.6 has been pulled?) And the dependency for Pipelines.Sockets.Unofficial 2.1.8 is **System.IO.Pipelines (>= 4.7.1)**

So the dependencies should be updated for SE.Redis as well.

**Comment by mgravell** [comment]
Well, it should work with 4.7.1, but yes: I agree we should bump this.

**Comment by etuzel** [comment]
Hi @mgravell,

It doesn't work with 4.7.1. I got errors like this:

Could not load file or assembly 'System.IO.Pipelines, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.
at StackExchange.Redis.SocketManager..ctor(String name, Int32 workerCount, SocketManagerOptions options)

Then I downgraded to Pipelines.Sockets.Unofficial.2.1.6. Now it works. But 2.1.6 is unlisted on NuGet. Should I go with this or is there any other solution?

**Comment by mgravell** [comment]
I'll try and get a new build out with all matching dependencies

**Comment by mgravell** [comment]
2.1.39 should be on nuget shortly (it'll be hidden for a couple of days, but: it is there) https://www.nuget.org/packages/StackExchange.Redis/2.1.39

**Comment by etuzel** [comment]
@mgravell Thanks, I'm able to install it from the NuGet Package Manager but why it's still unlisted on the web page of NuGet?

**Comment by geforce-hisa0904** [comment]
@mgravell I think so, too. If possible, could you also display the NuGet web page?

**Comment by KamranShahid** [comment]
https://github.com/StackExchange/StackExchange.Redis/issues/1452
