### ISSUE TITLE
Thread was being aborted during the GET

### ISSUE THREAD

**Issue by anandan84** [StackExchange/StackExchange.Redis#1437]
We are frequently receiving the Thread abort exception during the GET and SET operation and we have to reset the IIS to bring the application back. Please find below for more details.

**Error** :    System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)     at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)     at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)     at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)     at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) 

**Stackexchange Version :** 
package id="StackExchange.Redis" version="1.2.3" targetFramework="net471"
package id="StackExchange.Redis.Extensions.Core" version="2.3.0" targetFramework="net471"
package id="StackExchange.Redis.Extensions.Newtonsoft" version="2.3.0" argetFramework="net471" 

**.Net version:** 4.7.1

**Code snippets:**
static readonly Lazy<IConnectionMultiplexer> LazyConnection = new Lazy<IConnectionMultiplexer>(() =>
         {
             var config = new ConfigurationOptions
             {
                 EndPoints = { { RedisConfigurationManager.Config.Host.ToString(), int.Parse(RedisConfigurationManager.Config.Port.ToString()) } },
                 AllowAdmin = true,
                 ConnectTimeout = RedisConfigurationManager.Config.ConnectionTimeOut,
                 Password = RedisConfigurationManager.Config.Password,
                 DefaultDatabase = RedisConfigurationManager.Config.Database,
                 Ssl = RedisConfigurationManager.Config.Ssl,
                 AbortOnConnectFail = RedisConfigurationManager.Config.AbortOnConnectFail,
                 ConnectRetry = RedisConfigurationManager.Config.ConnectionRetry,
                 SslProtocols = System.Security.Authentication.SslProtocols.Tls12
             };
                         return ConnectionMultiplexer.Connect(config);
         });
        readonly Lazy<StackExchangeRedisCacheClient> LazyCacheClient = new Lazy<StackExchangeRedisCacheClient>(() =>
        {
            var serializer = new NewtonsoftSerializer();
            return new StackExchangeRedisCacheClient(LazyConnection.Value, serializer);
        });
**Config:**
RedisConfigurationSection host="xxxx-xxx" port="xxx" password="xxx" 
                             defaultDatabase="0" ssl="true" connectionTimeOut="1000000" connectRetry= "3" abortOnConnectFail="false"

We are not disposing of the connection on every operation, we are keeping a single shared connection for all operations. 

Please help me to resolve this issue as we are currently blocked due to this.

**Comment by NickCraver** [comment]
In short: you're on a _very_ old version of StackExchange.Redis, years behind. Please upgrade to a much newer release (we're on 2.x now) to get all of the improvements we're made, especially around connections!
