### ISSUE TITLE
Question: RedisGraph support

### ISSUE THREAD

**Issue by dandago** [StackExchange/StackExchange.Redis#1439]
Hi,

I just wanted to ask what support exists for interacting with [RedisGraph](https://oss.redislabs.com/redisgraph/), and whether there are any plans to develop this further.

I don't see StackExchange.Redis (or any .NET client, for that matter) listed in the RedisGraph [clients list](https://oss.redislabs.com/redisgraph/clients/), but I have come across a [question](https://github.com/StackExchange/StackExchange.Redis/issues/1148) here showing an example of how queries could be run using StackExchange.Redis.

Thanks in advance.

**Comment by DvirDukhan** [comment]
hi @dandago 
There is this one, which I personally haven't yet tried, but it is looking really promising, esplcially if you are familiarized with JRedisGraph:
https://github.com/tombatron/NRedisGraph
I should add it to the clients list in the official docs.
If there will be enough demand, and my availability allows it, I will create an "official" RedisGraph .Net client.

**Comment by mgravell** [comment]
Thanks @DvirDukhan. In the more general case: the `Execute[Async]` API allows arbitrary commands to be executed without the library needing to know about them in advance. Useful for modules or just new commands.

**Comment by NickCraver** [comment]
Advice above - closing out!
