### ISSUE TITLE
why LockTake always return false?

### ISSUE THREAD

**Issue by leslietoo** [StackExchange/StackExchange.Redis#144]
I used LockTake as you answered on http://stackoverflow.com/questions/25127172/stackexchange-redis-locktake-lockrelease-usage :

```C#
RedisValue token = Environment.MachineName;
if(db.LockTake(key, token, duration)) {
    try {
        // you have the lock do work
    } finally {
        db.LockRelease(key, token);
    }
}
```

but `LockTake` always return false in my test, whatever the key/token/duration is. I am sure the key/token parameters are correct. Why so? Is this method deprecated?

**Comment by mgravell** [comment]
It is expected that the lock key *does not exist* prior to this operation.
The lock key should be distinct from from the key of the data.

What is your setup here? Are you talking to an old old server? or via
twemproxy? or just direct to redis? and if so, which version?

Marc

On 6 January 2015 at 09:15, leslietoo <notifications@github.com> wrote:

> I used LockTake as you answered on
> http://stackoverflow.com/questions/25127172/stackexchange-redis-locktake-lockrelease-usage
> :
>
> ...
> RedisValue token = Environment.MachineName;
> if(db.LockTake(key, token, duration)) {
> try {
> // you have the lock do work
> } finally {
> db.LockRelease(key, token);
> }
> }
> ...
>
> but LockTake always return false in my test, whatever the
> key/token/duration is. I am sure the key/token parameters are correct. Why
> so? Is this method deprecated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/144>.
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment]
@leslietoo I'll close this out since the other issue is open and separate (I'm going through many old issues). The short version for others finding this is: don't set the key yourself. It's not taking a long *on the key*, it's taking a lock *by setting the key*. The key itself is the locking mechanism in use.
