### ISSUE TITLE
Pipelined operations are sent out of order

### ISSUE THREAD

**Issue by kennygea** [StackExchange/StackExchange.Redis#1440]
Following the pipelining approach [here](https://stackexchange.github.io/StackExchange.Redis/PipelinesMultiplexers.html#pipelining), we often pipeline requests (Setting and then getting) in our application. We noticed after upgrading to StackExchange.Redis 2.1.30 that the order of requests would very infrequently not be respected and that the get operation would return the old redis value, despite having pipelined the set operation first.

We update a hash and the retrieve the hash following pipelining guidelines. [Here](https://github.com/kennygea/redis-pipeline-bug) is a sample application that does this repeatedly in a loop.

The relevant part of the code:

```c#
long i = 0;
while (true)
{
    int val = random.Next();
    var a = db.HashSetAsync("foo", new[] { new HashEntry("a", val) });
    var b = db.HashGetAllAsync("foo");
    await Task.WhenAll(a, b);
    var foo = await b;
    var test = foo.ToDictionary(i => i.Name, i => i.Value);
    if (test["a"] != val) // problem occurs here
        throw new Exception($"Wrong value {val}")
    if (++i % 100_000 == 0)
         Console.WriteLine($"{i:N0} successful iterations");
 }
```

The application will after a while return the incorrect value which indicates that the `HashSetAsync` did not occur before we retrieved the value using `HashGetAllAsync`

````
Unhandled exception. System.Exception: Wrong value 1315285639
   at RedisTest.Program.Main(String[] args) in C:\work\RedisTest\RedisTest\Program.cs:line 26
   at RedisTest.Program.<Main>(String[] args
````

I've tested this with `StringSetAsync` and `StringGetAsync` and the same issue occurs after a number of runs.

This is pretty critical issue in a production environment as this causes our applications to be in incorrect state. To circumvent this, we've started using batching to batch the two requests together which seems to so far alleviate the problem.

**Comment by mgravell** [comment]
That's really interesting. I can't think of a way to make that out of order, but: to guarantee it more:

``` c#
int val = random.Next();
var batch = dB.CreateBatch();
var a = batch.HashSetAsync("foo", new[] { new HashEntry("a", val) });
var b = batch.HashGetAllAsync("foo");
batch.Execute();
await Task.WhenAll(a, b);
```

**Comment by kennygea** [comment]
@mgravell 

That is the approach we've updated our applications to use as a quick temporarily fix. 

The concern is that pipelining requests like this should work without having to batch.

https://stackexchange.github.io/StackExchange.Redis/PipelinesMultiplexers.html#pipelining

**Comment by mgravell** [comment]
Ooh, I think I've figured out the hypothetical way of causing an out-of-order sequence from your current code:

- first write gets a back from the mutex and is placed in the queue
- second write sneaks in defying the queue

It isn't a *strictly fair* queue, and this would be a very rare event, but is technically possible.

Oddly, just this week I've been looking at a new opt-in API that would absolutely *not* guarantee the order of the code without the batch, but it is interesting to.me.that perhaps even now it isn't guaranteed, but just "it'll usually work". It should always work if you use the batch API. If it fails with that, then that is 100% a "needs fix" bug.

I'm in two minds as to whether the queue not being 100% "fair" needs a fix. I need to think!

**Comment by mgravell** [comment]
As it happens, I wrote a 100% fair implementation the other day, but I haven't allocation optimized it yet. Let me see what impact this would have.

**Comment by mgravell** [comment]
benchmarking shows no negative consequences in the uncontested case, and frankly it is irrelevant what happens in the contested case (any extra time there is irrelevant noise) - in fact it is marginally faster:

``` txt
|                        Method |  Job | Runtime |      Mean |     Error |    StdDev |       Min |       Max | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------ |----- |-------- |----------:|----------:|----------:|----------:|----------:|------:|------:|------:|----------:|
|          MutexSlimUncontested |  Clr |     Clr |  50.66 ns | 0.2414 ns | 0.2140 ns |  50.23 ns |  50.95 ns |     - |     - |     - |         - |
|     MutexSlimUncontestedAsync |  Clr |     Clr |  78.75 ns | 1.5704 ns | 2.5359 ns |  75.15 ns |  84.19 ns |     - |     - |     - |         - |
|      FairMutexSlimUncontested |  Clr |     Clr |  46.98 ns | 0.6789 ns | 0.6018 ns |  46.08 ns |  48.07 ns |     - |     - |     - |         - |
| FairMutexSlimUncontestedAsync |  Clr |     Clr |  72.63 ns | 0.8070 ns | 0.6739 ns |  71.37 ns |  73.81 ns |     - |     - |     - |         - |
| SemaphoreSlimUncontestedAsync |  Clr |     Clr | 114.86 ns | 1.2639 ns | 1.1823 ns | 113.08 ns | 117.18 ns |     - |     - |     - |         - |
|      SemaphoreSlimUncontested |  Clr |     Clr | 121.47 ns | 1.8135 ns | 1.6963 ns | 119.68 ns | 125.48 ns |     - |     - |     - |         - |
|          MutexSlimUncontested | Core |    Core |  47.24 ns | 0.2933 ns | 0.2744 ns |  46.63 ns |  47.57 ns |     - |     - |     - |         - |
|     MutexSlimUncontestedAsync | Core |    Core |  76.18 ns | 0.7554 ns | 0.7066 ns |  74.96 ns |  77.19 ns |     - |     - |     - |         - |
|      FairMutexSlimUncontested | Core |    Core |  44.89 ns | 0.3194 ns | 0.2831 ns |  44.52 ns |  45.66 ns |     - |     - |     - |         - |
| FairMutexSlimUncontestedAsync | Core |    Core |  70.07 ns | 0.4988 ns | 0.4666 ns |  69.17 ns |  71.05 ns |     - |     - |     - |         - |
| SemaphoreSlimUncontestedAsync | Core |    Core |  58.30 ns | 0.5513 ns | 0.5157 ns |  57.27 ns |  58.82 ns |     - |     - |     - |         - |
|      SemaphoreSlimUncontested | Core |    Core |  52.55 ns | 0.3876 ns | 0.3626 ns |  52.07 ns |  52.92 ns |     - |     - |     - |         - |
```

Switching code impl to fair.

**Comment by mgravell** [comment]
trying to get the CI going for this, but github is having a bad day (and I use github for the federated auth from our CI server); working on it!

**Comment by mgravell** [comment]
2.1.39 should be available on nuget shortly: https://www.nuget.org/packages/StackExchange.Redis/2.1.39 - it will be hidden for a couple of days, but I'd be grateful if you could validate that it fixes this

**Comment by kennygea** [comment]
Thanks for fixing this! Will test and post back with results

**Comment by kennygea** [comment]
@mgravell 

I updated the test project I had to `2.1.39` and the issue still persists, and generally under 1,000,000 iterations.

Just to sanity check, I ran the project with version `1.2.6`  and confirmed there are no issues there after multiple millions of iterations

**Comment by mgravell** [comment]
dammit; OK, I'll need take a longer look at this, then; the batching API is definitely an uber-fix for this, but I agree that this should work "as is"; I'll try to set aside some time to look in much more detail

**Comment by TimLovellSmith** [comment]
> Ooh, I think I've figured out the hypothetical way of causing an out-of-order sequence from your current code:
> 
> * first write gets a back from the mutex and is placed in the queue
> * second write sneaks in defying the queue
> 

Were you talking about the queue in the old implementation of DedicatedThreadPoolPipeScheduler here?
