### ISSUE TITLE
Failover handling with sentinel

### ISSUE THREAD

**Issue by MarkJamesStevenson** [StackExchange/StackExchange.Redis#1441]
Hi,
Is there a recommended way to handle failover using sentinel when the master node disconnects? 

Below is the only way I've been able to get this to work so far and means that I have to remove the previous master endpoint from the list of endpoints otherwise I was getting a RedisConnectionException.

From other examples I have seen, it seems to be expected to call GetSentinelMasterConnection before every time we call GetDatabase but this creates a new ConnectionMultiplexer every time which seems very slow.

I am using version 2.1.30.

    _sentinelConfig = new ConfigurationOptions
    {
    };
    _sentinelConfig.ServiceName = config.ServiceName;
    databaseNumber = config.DatabaseNumber;

    foreach (var endpoint in config.SentinelEndpointsList)
    {
        _sentinelConfig.EndPoints.Add(endpoint);
    }
    _sentinelConfig.TieBreaker = "";
    _sentinelConfig.DefaultVersion = new Version(5, 0, 08);
    _sentinelConfig.CommandMap = CommandMap.Sentinel;

    _sentinelConnection = ConnectionMultiplexer.Connect(_sentinelConfig, Console.Out);
    _masterConfig = new ConfigurationOptions { ServiceName = config.ServiceName };
    _master = _sentinelConnection.GetSentinelMasterConnection(_masterConfig, Console.Out);
    _masterEndPoint = _master.GetDatabase().IdentifyEndpoint();

    ...            

    try
    {
        var db = _master.GetDatabase(databaseNumber);
        HashEntry[] fields = db.HashGetAll(key);
    }
    catch (RedisConnectionException e)
    {
        // reconnect
        _sentinelConfig.EndPoints.Remove(_masterEndPoint);
        _sentinelConnection = ConnectionMultiplexer.Connect(_sentinelConfig, Console.Out);
        _master = _sentinelConnection.GetSentinelMasterConnection(_masterConfig, Console.Out);
        _masterEndPoint = _master.GetDatabase().IdentifyEndpoint();
    }
    catch (RedisTimeoutException e)
    {
        // reconnect
        _sentinelConfig.EndPoints.Remove(_masterEndPoint);
        _sentinelConnection = ConnectionMultiplexer.Connect(_sentinelConfig, Console.Out);
        _master = _sentinelConnection.GetSentinelMasterConnection(_masterConfig, Console.Out);
        _masterEndPoint = _master.GetDatabase().IdentifyEndpoint();
    }

Thanks

**Comment by NickCraver** [comment]
Please try the latest release here, there were further fixed in #1431 around this and other scenarios that should make life automatic.

**Comment by NickCraver** [comment]
Closing this out to tidy up - anyone using Sentinel the advice remains the same: grab latest client version as we've done a lot (with community help!) to improve Sentinel behavior.
