### ISSUE TITLE
Xamarin.Forms android can not resolve reference: `System.Diagnostics.PerformanceCounter`, referenced by `StackExchange.Redis`

### ISSUE THREAD

**Issue by tomasfabian** [StackExchange/StackExchange.Redis#1442]
Hi,
I have a Xamarin.Forms.Droid build problem:

_Severity	Code	Description	Project	File	Line	Suppression State
Error		Can not resolve reference: `System.Diagnostics.PerformanceCounter`, referenced by `StackExchange.Redis`. Please add a NuGet package or assembly reference for `System.Diagnostics.PerformanceCounter`, or remove the reference to `StackExchange.Redis`.	Xamarin.Sample.Android_			
			
I also tried to include System.Diagnostics.PerformanceCounter package:
```
    <PackageReference Include="StackExchange.Redis">
      <Version>2.1.30</Version>
    </PackageReference>
    <PackageReference Include="System.Diagnostics.PerformanceCounter">
      <Version>4.7.0</Version>
    </PackageReference>
```

Is it possible to use StackExchange.Redis with Xamarin.Forms apps?

Thank you, Tomas

**Comment by Filipowicz251** [comment]
I have the same issue. Adding NuGet package doesn't solve anything

**Comment by Filipowicz251** [comment]
Most probably this is correlated with nuget package reference and this bug especially: https://github.com/xamarin/xamarin-android/issues/2674

Going back to packages.config fix the issue (i just read it - i will right now try it;) )

**Comment by andrev121** [comment]
> I have the same issue. Adding NuGet package doesn't solve anything
> 
> [UPDATE]
> 
> Most probably this is correlated with nuget package reference and this bug especially: [xamarin/xamarin-android#2674](https://github.com/xamarin/xamarin-android/issues/2674)
> 
> Going back to packages.config fix the issue (i just read it - i will right now try it;) )

Tried install both of packages in shared and droid projects. Placed packages.config with reference on PerfomanceCounter in root of droid project. Nothing worked. How to fix this issue? Does redis unusable with forms?

**Comment by SouJack** [comment]
See pullrequest #1702

**Comment by SHuygh** [comment]
@mgravell Would it be possible to remove the reference to the performance counter based on @SouJack PR for MonoAndroid10  and Xamarin.iOS10 (cfr. https://docs.microsoft.com/nl-be/xamarin/cross-platform/app-fundamentals/nuget-manual) to be able to use these within Xamarin Forms and Xamarin Native projects.

**Comment by mgravell** [comment]
Is there a TFM that Xamarin and monodroid would pick up, more specific than
the current TFMs? Adding a TFM is a practical option.

**Comment by SHuygh** [comment]
MonoAndroid10 and Xamarin.iOS10 are the TFM targeting Android 1.0 + and IOS 1.0+ (e.g. [AzureAD ](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/bc9b6cc15ad271c1f4f9f1ccdbad6360b826080f/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Microsoft.IdentityModel.Clients.ActiveDirectory.csproj) also uses multi targeting to remove a certain part of the API for Android and IOS)
I hope this help.

**Comment by AmmarSaleh45** [comment]
Any update on this issue please, Is it possible to use StackExchange.Redis with Xamarin.Forms apps?

**Comment by mgravell** [comment]
I am going to look at what is involved in using those TFMs in terms of
build servers etc; but no, it isn't "done" yet. Probably look Tuesday (long
family weekend).

**Comment by SriramSakthivel** [comment]
I'm also looking to use StackExchange.Redis with Xamarin.Forms app. Any update on this one please?

**Comment by NickCraver** [comment]
I'm looking at TFMs since adding `net6.0` here for other reasons. I'm not sure what the landscape looks like though - if we added a build for `net6.0-ios` and `net6.0-android`...would that work for people in having a build without this dependency/functionality?

**Comment by NickCraver** [comment]
Can anyone here chime in on if such TFMs would be useful? If so we could add and conditional the reference but it adds maintenance so I'd like to see if we're actually solving a problem still :)

**Comment by NickCraver** [comment]
I'm going to close this out since there doesn't seem to be a current need. If the above new TFMs do help someone I'm wide open to adding them, but with no responses I'm reading that this isn't a current issue or at least a pressing one at not worth adding.
