### ISSUE TITLE
Redis handle the channel message many times that captured on the specific redis channel

### ISSUE THREAD

**Issue by BlackHoleInYourPocket** [StackExchange/StackExchange.Redis#1443]
Listen to the messages that publish on the channel named "server" on the Redis server with the following c # code.

        logsBll.Redis().GetSub().Subscribe("server", (channel, redisMessage) =>
        {
            if (!redisMessage.IsNullOrEmpty)
            {
             switch(redisMessage.ToString())
               {
               case :
               . 
               . 
               .
               }
            }
When a message which related with switch-case block, is publish on the channel, code is starting to running. My redis-server.exe running on Windows Server 2012 R2. If redis-server.exe running under the C:/File/File/etc.., code block above, execute switch-case statement only one time. When i execute redis-server.exe on desktop(C:/myusername/Desktop) Windows Server 2012 R2, code block above running and handle the redis message many times like 10 15 times. When i monitored, i checked message published only one time. But on the desktop redis-server.exe, code running many times. What could be the reason for this ?

**Comment by NickCraver** [comment]
It sounds like your code above, adding a subscription handler may be running many times. What context is it running in, and are you certain it only executes once?
