### ISSUE TITLE
Publishing CUD operations from SQL Server

### ISSUE THREAD

**Issue by kubusCdr** [StackExchange/StackExchange.Redis#1445]
How is it possible to send Create, Update and Delete operations from SQL Server via StackExchange.Redis?

Thank you

**Comment by mgravell** [comment]
It ... isn't? StackExchange.Redis talks exclusively to redis servers (or servers that talk RESP, the redis protocol). It has nothing to do with SQL databases or TDS/TSQL (that's the SQL Server protocols and variants).

**Comment by kubusCdr** [comment]
Maybe it ... is? Sorry for that question, but it seems that it is.
Finally I found a repository Joker.Redis, which uses StackExchange.Redis on Github for exactly this purpose:
https://github.com/tomasfabian/SqlTableDependency.Extensions

thx anyway @mgravell
