### ISSUE TITLE
API doesn't start when trying to init StackExchange.Redis ConnectionMultiplexer (using RedLock too)

### ISSUE THREAD

**Issue by weare8** [StackExchange/StackExchange.Redis#1446]
Having built a 3 node Redis cluster with Sentinel in front and using StackExchange.Redis with the below configuration.

```
"Redis": {
    "Password": "super_secret_password",
    "AllowAdmin": true,
    "Ssl": false,
    "ConnectTimeout": 3000,
    "ConnectRetry": 2,
    "Database": 0,
    "Hosts": [
      {
        "Host": "redis-1.domain.com",
        "Port": 26379
      },
      {
        "Host": "redis-2.domain.com",
        "Port": 26379
      },
      {
        "Host": "redis-3.domain.com",
        "Port": 26379
      }
    ]
  }
```

Configuring the DI container.

```
var redisConfiguration = configuration.GetSection(redisSettingsJsonSection).Get<RedisConfiguration>();
services.AddSingleton(redisConfiguration);
services.AddSingleton<IRedisCacheClient, RedisCacheClient>();
services.AddSingleton<IRedisCacheConnectionPoolManager, RedisCacheConnectionPoolManager>();
services.AddSingleton(_ => new Utf8JsonSerializer());
services.AddSingleton(provider =>
                provider.GetService<IRedisCacheClient>().GetDbFromConfiguration());

// Setting up RedLock for distributed locking support, not sure if the below is correct

services.AddSingleton<IDistributedLockFactory>(provider =>
                RedLockFactory.Create(new List<RedLockMultiplexer>()
                {
                    new RedLockMultiplexer(
                        (ConnectionMultiplexer) provider.GetRequiredService<IRedisCacheConnectionPoolManager>()
                            .GetConnection())
                })
            );
```

When I start the ASP.NET Core API 3.1 I get the below messages and it just hangs.

> dbug: StackExchange.Redis.Extensions.Core.Implementations.RedisCacheConnectionPoolManager[0]
>       Checking if there are any invalid connections...
> dbug: StackExchange.Redis.Extensions.Core.Implementations.RedisCacheConnectionPoolManager[0]
>       The pool size is 5 and it requires new 5 connections.
> dbug: StackExchange.Redis.Extensions.Core.Implementations.RedisCacheConnectionPoolManager[0]
>       Creating new Redis connection.

All nugget packages are the latest.

**Comment by mgravell** [comment]
The problem here is: almost none of that relates to SE.Redis!

- Extensions.Core.Implementations.RedisCacheConnectionPoolManager: not us
- IRedisCacheConnectionPoolManager: not us
- RedisCacheClient: not us
- IRedisCacheClient: not us
- RedLockMultiplexer: not us
- IDistributedLockFactory: not us

If there's a problem with anything in SE.Redis's domain - happy to help, but for anything *not in our package*: you're going to have to find the package owner for that and ask them.

As a quick "common problem" thing: if this is cloud, check your TLS config - you might need to specify an appropriate TLS level in the connection string to SE.Redis

**Comment by weare8** [comment]
@mgravell sorry about that, you are absolutely correct, I am using the extensions package. I will refer to the appropriate repository if they support Sentinel configuration.

Meanwhile, I got the below configuration so far to start it up.

```
ConfigurationOptions sentinelConfig = new ConfigurationOptions();
sentinelConfig.ServiceName = "mymaster";
sentinelConfig.EndPoints.Add("redis-1.prod.prod02.aws.weare8.com", 26379);
sentinelConfig.EndPoints.Add("redis-2.prod.prod02.aws.weare8.com", 26379);
sentinelConfig.EndPoints.Add("redis-3.prod.prod02.aws.weare8.com", 26379);\
sentinelConfig.TieBreaker = "";
sentinelConfig.DefaultVersion = new Version(4, 0, 11);                 
// its important to set the Sentinel commands supported
sentinelConfig.CommandMap = CommandMap.Sentinel;
            
// Get sentinel connection
ConnectionMultiplexer sentinelConnection = ConnectionMultiplexer.Connect(sentinelConfig, Console.Out);
// Create master service configuration
ConfigurationOptions masterConfig = new ConfigurationOptions { ServiceName = "mymaster" };
masterConfig.Password = "super_secret_passoword";
// other Redis configuration...
// Get master Redis connection
services.AddSingleton(_ => sentinelConnection.GetSentinelMasterConnection(masterConfig));
            services.AddSingleton(provider => provider.GetRequiredService<ConnectionMultiplexer>().GetDatabase());
```

I had to jump to this discussion to figure it out, https://github.com/StackExchange/StackExchange.Redis/pull/1067, am I missing some Sentinel documentation?

**Comment by NickCraver** [comment]
The Sentinel bits are being improved in #1431, we'll get some docs on connection strings there...it should need a lot less documentation after it's made easier to use via those changes.

**Comment by weare8** [comment]
Awesome!

**Comment by NickCraver** [comment]
#1431 is in, so closing this out.
