### ISSUE TITLE
LPUSHX/RPUSHX support for multiple values

### ISSUE THREAD

**Issue by Badabum** [StackExchange/StackExchange.Redis#1450]
Currently there are `ListLeftPush/ListRightPush` methods with 2 signatures: 
1. Accepting single value and condition, commandoptions: 
`(string key, RedisValue value, When, ComandOptions)`
2. Accepting key, multiple values and command options:
 `(string key, RedisValue[] value, CommandOptions options)`

According to Redis docs - starting from v4.0 the `LPUSHX/RPUSHX` accepts multiple elements. Is there any chance support will be added to the library?

**Comment by mgravell** [comment]
Yep, this checkout out; so, I guess we need:

``` c#
// new API
long ListLeftPush(RedisKey key, RedisValue[] values, When when = When.Always, CommandFlags flags = CommandFlags.None);
// remove default parameter on existing API
long ListLeftPush(RedisKey key, RedisValue[] values, CommandFlags flags);
```

- and the core implementation (should be trivial)
- and the database wrapper implementation
- and the same for async
- and tests

Any takers?

**Comment by Badabum** [comment]
I could make a try :)

**Comment by dmytrohridin** [comment]
Hey @mgravell, trying to implement this but do not understand why we should remove default parameter `CommandFlags` from  `long ListLeftPush(RedisKey key, RedisValue[] values, CommandFlags flags = CommandFlags.None);`
Does it mean that not all `CommandFlags` value should be acceptable?
Thank you

**Comment by mgravell** [comment]
> why we should remove default parameter 

Context? What are we talking about here?

**Comment by dmytrohridin** [comment]
>  // remove default parameter on existing API
long ListLeftPush(RedisKey key, RedisValue[] values, CommandFlags flags);
About this. You mentioned this earlier in this issue

**Comment by mgravell** [comment]
No, this has no crossover whatsoever with any flags. What we're trying to do here is make the API backwards compatible but prefer the new API, nothing more.

**Comment by kijanawoodard** [comment]
Looks like this one is done given the merge?

**Comment by NickCraver** [comment]
Yup, closing this out :)
