### ISSUE TITLE
Feature request - add command: ROLE

### ISSUE THREAD

**Issue by NickCraver** [StackExchange/StackExchange.Redis#1451]
This command isn't yet in the lib and is useful for a few scenarios - came up in #1431.

Min version: 2.8.12
Docs: https://redis.io/commands/role

**Comment by zmj** [comment]
I would like to take a shot at this! A couple questions:

* Result type: it seems like there's not much shared between the results for each node type. I was thinking to return a base Role type with some subtypes for master, replica, and sentinel?
* Tests: it seems like the use case for this command is mostly around configurations with sentinels? Is that a sensible place to put tests for this command?

**Comment by mgravell** [comment]
Given that the shape changes so radically, inheritance is probably the best
option here, agreed. There is also an enum for the same purpose, but to be
honest I don't think we need the discrimiant once we have split it into
types. The intent is also perfectly valid in primary/replica scenarios, so
all 3 result types probably need testing. We should also consider what to
return when the type isn't recognised ... an exception? A RoleUnknown
subtype? I'd also recommend looking for the string "replica" in addition to
"slave", in case that ever swaps over.

Looking forward to it!

**Comment by NickCraver** [comment]
Added in #1551, closing out!
