### ISSUE TITLE
Getting exception UnableToConnect on 192.168.1.1:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 180s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.1.30.38891

### ISSUE THREAD

**Issue by KamranShahid** [StackExchange/StackExchange.Redis#1453]
I have following implementation of RedisManager (single method for get is given for reference)
I am using .net core 3.1 with redis version 5.0.3 on redhat linux

I am getting following error 

**UnableToConnect on 127.0.0.1:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 180s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.1.30.38891**

Even if server able to connect to the redis but i am keep getting this error.
Any idea what needed to be done. At the moment I am using password less connection

```
    public static class RedisManager
    {
        private static readonly ILog Logger = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        //todo: Any public static members of this type are thread safe. Any instance members are not guaranteed to be thread safe.



        
        //http://gigi.nullneuron.net/gigilabs/setting-up-a-connection-with-stackexchange-redis/
        //https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Configuration.md
        private static readonly Lazy<ConfigurationOptions> ConfigOptions = new Lazy<ConfigurationOptions>(() =>
        {
            ConfigurationOptions configOptions = null;

            try
            {
						var redisInfo = GetOptionsFrom Configuration();
                        configOptions = new ConfigurationOptions();
                        configOptions.EndPoints.Add(redisInfo.RedisServerNameOrIp + ":" + redisInfo.RedisServerPort);
                        configOptions.ClientName = "SafeRedisConnection_" + DateTime.Now.ToString();
                        if (redisInfo.ConnectTimeout != 0)
                        {
                            configOptions.ConnectTimeout = redisInfo.ConnectTimeout * 1000;
                        }
                        if (redisInfo.SyncTimeout != 0)
                        {
                            configOptions.SyncTimeout = redisInfo.SyncTimeout * 1000;
                        }
                        configOptions.AbortOnConnectFail = false;
                        if (redisInfo.KeepAliveDuration != 0)
                        {
                            configOptions.KeepAlive = redisInfo.KeepAliveDuration;
                        }
                        configOptions.DefaultDatabase = redisInfo.RedisDefaultDatabase;
                        if (!string.IsNullOrWhiteSpace(redisInfo.RedisServerPassword))
                        {
                            configOptions.Password = redisInfo.RedisServerPassword;
                        }
                    
            }
            catch (Exception ex)
            {
                Logger.Fatal(ex, ex);
            }
            return configOptions;
        });
		
        private static readonly Lazy<ConnectionMultiplexer> Conn = new Lazy<ConnectionMultiplexer>(
            () =>
            {
                try
                {
                    if (ConfigOptions != null && ConfigOptions.Value != null)
                    {
                        return ConnectionMultiplexer.Connect(ConfigOptions.Value);
                    }
                    return null;

                }
                catch (Exception ex)
                {
                    Logger.Fatal(ex.Message, ex);
                    return null;
                }
            });

        private static ConnectionMultiplexer Muxer => Conn.Value;

        public static string GetStringItem(string key)
        {
            string val = null;
            try
            {
                IDatabase getDatabase;
                if (Muxer != null  && (getDatabase = Muxer.GetDatabase()) != null)
                {
                    val = getDatabase.StringGet(key);
                    getDatabase = null;
                }
            }
            catch (Exception ex)
            {
                Logger.Fatal(ex.Message, ex);
            }
            return val;
        }
    }

```

**Comment by KamranShahid** [comment]
Anyone else faced similar error on Redhat Linux problem. Problems was related to some firewalld settings but manually disabling should have allowed the connectivity. I were able to telnet the reis server ip port after disabling firewall but error still coming in app.

**Comment by mgravell** [comment]
Was redis-cli able to talk to the server?

**Comment by mgravell** [comment]
Also: if this is .net framework, it is possible that it is actually an
assembly binding redirect problem masquerading as a network problem. What
framework are you targeting here?

**Comment by KamranShahid** [comment]
It is with .net core 3.1 application on redhat linux 8.
I were able to connect to redis using redis desktop manager

**Comment by lilmidnit** [comment]
I receive the same error. A working project, upgrade from 2.0.601 and can no longer connect and get this error. Using 4.7.2 .NET. Redis is on this machine, unable to connect after upgrade

**Comment by KamranShahid** [comment]
> I receive the same error. A working project, upgrade from 2.0.601 and can no longer connect and get this error. Using 4.7.2 .NET. Redis is on this machine, unable to connect after upgrade

Give bit details.
Like Redis version X on (Linux flavor Y or Windows)
.net core 3.1 or .net framework 4.7.2
e.t.c.

**Comment by lilmidnit** [comment]
Well I don't believe my redis version matters, hence why I left it out. Each of our environments use something different - but once we upgraded from 2.0.601 to 2.1.30 - they ALL lost ability to connect via the application. But to answer your question, for local development I am using the redis-64 nuget package. Nothing else in the app has change, simply upgraded StackExchange.Redis through nuget, ran the app, nothing will connect to the localhost redis. Move the code to any of our environments and likewise, no connectivity. Downgrade back to 2.0.601 and it works again. I also just tried 2.1.28 and it also does not work in our app.

I suspect its something like mgravell hinted at - incompatible libraries loaded. Our app is huge and some if it could be forcing it.

**Comment by KamranShahid** [comment]
> Well I don't believe my redis version matters, hence why I left it out. Each of our environments use something different - but once we upgraded from 2.0.601 to 2.1.30 - they ALL lost ability to connect via the application. But to answer your question, for local development I am using the redis-64 nuget package. Nothing else in the app has change, simply upgraded StackExchange.Redis through nuget, ran the app, nothing will connect to the localhost redis. Move the code to any of our environments and likewise, no connectivity. Downgrade back to 2.0.601 and it works again. I also just tried 2.1.28 and it also does not work in our app.
> 
> I suspect its something like mgravell hinted at - incompatible libraries loaded. Our app is huge and some if it could be forcing it.

I agree with @mgravell may be some library incompatibility/  nuget package dependency problem

**Comment by lilmidnit** [comment]
I got mine working, It was binding redirect issues. It would be SUPER helpful if it reported an error that didn't distract from the actual problem.

**Comment by CredibleAshok** [comment]
Try localhost instead of 127.0.0.1:6379

**Comment by mgravell** [comment]
> Try localhost instead of 127.0.0.1

I can think of no scenarios where that would help, sorry.

**Comment by syh-rapha** [comment]
I've got a similar error trying to connect to Elasticache on AWS and in the end the problem was a missing `ssl=true` on the connection string. This took me a while to solve since the error message didn't mention anything related to SSL.

**Comment by NickCraver** [comment]
For anyone debugging here, using the text logger in your `.Connect()` or `.ConnectAsync()` calls can tell you what's wrong connecting here, and Marc's done work to also try and detect and log binding redirect/load issues around assemblies as well, so this log will also be informative on that front.

**Comment by NickCraver** [comment]
Update: we've also done work here to improve things (and logging - see above) in the v2.2.50 release. I'm going to close this out since we've likely resolved this, but if still hitting the same error (tracking down all dupes here), please ping and I'll re-open.

**Comment by alexandis** [comment]
I am unable to run Redis with the same error message. NET 6 project, Win 10. Actually running Redis as a part of ABP framework, but not sure it matters.

**Comment by wub** [comment]
@alexandis Try a few other settings, using the StackExchange.Redis configuration options: https://stackexchange.github.io/StackExchange.Redis/Configuration.html

Example: `foo-staging-redis.internal:6379,password=foobar,resolveDns=true,abortConnect=false`

Also, try adding `resolveDns=true` and see if that helps your timeout (if you're not using a loopback address).

**Comment by KamranShahid** [comment]
@wub I think @alexandis must have resolved it by now as it is around 4.5 months since he posted it

**Comment by wub** [comment]
@KamranShahid It was mainly for other people stumbling on this thread from Google, like I did, not so much for alexandis. Thanks for the input?

**Comment by MussaratAziz** [comment]
Still unable to connect using .NET 7  StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 5s ago, last-write: 5s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 15s ago, v: 2.2.4.27433

**Comment by NickCraver** [comment]
@MussaratAziz That's a generic exception - you'll want to pass a logger into the connect call and also upgrade versions :) Hopefully the log is apparent as to what's happening, but if not please open an issue!

**Comment by MussaratAziz** [comment]
@NickCraver Currently i am using "Microsoft.Extensions.Caching.StackExchangeRedis" Version="7.0.1"

**Comment by NickCraver** [comment]
@MussaratAziz I'd try connecting with us directly, also using a package that depends on us doesn't preclude upgrading the version of StackExchange.Redis you're using - just reference this package directly and I'd go for the latest version. It's still compatible.

**Comment by MussaratAziz** [comment]
OK I will give a try following dependencies **Microsoft.Extensions.Caching.StackExchangeRedis" Version="7.0.1"**
[Microsoft.Extensions.Caching.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Caching.Abstractions/) (>= 7.0.0)
[Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/) (>= 7.0.0)
[Microsoft.Extensions.Options](https://www.nuget.org/packages/Microsoft.Extensions.Options/) (>= 7.0.0)
**[StackExchange.Redis](https://www.nuget.org/packages/StackExchange.Redis/) (>= 2.2.4)**

**Comment by MussaratAziz** [comment]
@NickCraver  StackExchange.Redis.RedisConnectionException: 'It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.'  After connecting directly using your package. I am lost... redis is running locally.

**Comment by NickCraver** [comment]
@MussaratAziz to the .Connect() and .ConnectAsync() methods, you can pass a text logger, please do so and we can see what's up - let's open a new issue with that though please, this is spamming a lot of other people for an unrelated case :)
