### ISSUE TITLE
DefaultDatabase ignored for initial connection

### ISSUE THREAD

**Issue by lauraseidler** [StackExchange/StackExchange.Redis#1460]
I'm calling `ConnectionMultiplexer.Connect` like so:

```csharp
var options = new ConfigurationOptions
{
    EndPoints = {"endpoint"},
    DefaultDatabase = 10,
};

var connectionMultiplexer = ConnectionMultiplexer.Connect(options);

// ...
```

When later calling `connectionMultiplexer.GetDatabase()`, the `DefaultDatabase` is respected correctly for any following operations.

However, the initial connection when calling `ConnectionMultiplexer.Connect` is still made to db number `0`, only switching over to `10` after `GetDatabase` is called. This is not ideal, as we have multiple applications connecting to Redis on different dbs, and seeing applications connecting to db `0`, which they're not supposed to use, even if it's just for the time until the first operations run, is confusing.

How can I avoid this? I would've expected `DefaultDatabase` to be the setting to set this, but it's not working as expected.

**Comment by mgravell** [comment]
It doesn't change database until a command is issued because a single multiplexer can service *multiple* databases, switching as required; the default database only impacts what happens if you call GetDatabase *without* passing an override.

Could the system change pre-emptively to the default at connect: yes, it could; but perhaps the simpler thing for today in your case is to simply *issue an operation* after connect? (Maybe "dbsize" as a cheap operation that doesn't impact anything)

**Comment by lauraseidler** [comment]
@mgravell thanks for the quick reply! Yeah, we might indeed do that, to avoid confusion on our side.

If it's welcome, I might open a PR to clarify the documentation that `DefaultDatabase` is only used for the `GetDatabase` call? We've also noticed that a few other commands (e.g. the mentioned 
`DatabaseSize`) are using `0` if no db is given, where I also would've expected `DefaultDatabase` to also apply.

**Comment by mgravell** [comment]
Hmmm, yes; there are indeed possibly a few commands on the server API that
should be tweaked here if they are default zero. I agree we should change
those to default -1 and interpret -1 as "use the default" - that's what we
did with GetDatabase, after all.

**Comment by mgravell** [comment]
Fix for `IServer` commands: https://github.com/StackExchange/StackExchange.Redis/pull/1468

**Comment by NickCraver** [comment]
Cleaning up after #1468 here.
