### ISSUE TITLE
Possible deadlocks on async implementations and missing wait

### ISSUE THREAD

**Issue by jrlost** [StackExchange/StackExchange.Redis#1462]
Like others we've been running into some periodic timeouts and connection issues.  When diving into the library source to investigate how connections get re-established, I stumbled on a few things that caught my eye.  Just curious if I'm missing something.

https://github.com/StackExchange/StackExchange.Redis/blob/master/src/StackExchange.Redis/ConnectionMultiplexer.cs#L1399

`return await ReconfigureAsync(false, true, logProxy, null, "configure").ObserveErrors();`

https://github.com/StackExchange/StackExchange.Redis/blob/master/src/StackExchange.Redis/LoggingPipe.cs#L57

`var result = await from.ReadAsync();`

As the title suggests, near as I can tell, these should have `.ForAwait()` on them. 

Also,
https://github.com/StackExchange/StackExchange.Redis/blob/master/src/StackExchange.Redis/ConnectionMultiplexer.cs#L1381

`ReconfigureAsync(false, reconfigureAll, null, blame, cause, publishReconfigure, flags).ObserveErrors();`

Should this have `.Wait()`?

Anyways, let me know if you agree with these or not.  I can always drop in a PR to update these if you need.

**Comment by mgravell** [comment]
The `ForAwait()` here is just a shim to `ConfigureAwait(false)` - it *should probabably have them*, but lacking them shouldn't cause deadlocks unless the sync-context being used is fundamentally not task-friendly; at worst, it might just cause additional unnecessary context switches (and in UI scenarios: running code on the UI thread that doesn't *need* to run on the UI thread).

Note that `ReadAsync` is not your average awaitable, and `ConfigureAwait` does not apply.

Happy to see additions for any that are missing, but: I'm not convinced that this is related to any deadlocking you are seeing.

**Comment by jrlost** [comment]
Yeah, I had seen that this was a wrapper to ConfigureAwait(false). My
initial concern came from the fact they were behind public interfaces and
there were a lot of synchronous blocking calls in front of similar code. I
did not dive deep enough to discover if these were specifically being
called from blocking calls or not.
