### ISSUE TITLE
Problem with HashSet/HashSetAsync

### ISSUE THREAD

**Issue by matteoPhre** [StackExchange/StackExchange.Redis#1467]
Hi guys, thanks for all!
I have a problem with HashSet and HashSetAsync:
when i try to set values (with HashEntry[] or iterating through it) i cannot see the change in redis client until my application write it again.

For example: i have a channel like A:B:C:OUT, and i want to store a key-value pair like "12345" : {json.stringify}. At first run i can log the operation result of write a single value, and is true (but i cannot see on client). But at the second run, when it writes that single value is again true (And now i can see on client the inserted record).

Am i missing something? Thanks in advance

**Comment by mgravell** [comment]
Can you be more specific? Are you perhaps using some code *in front of* SE-Redis that caches the data in a dictionary or similar, and it is *that* that isn't being updated? because: SE-Redis doesn't perform any local caching, so you *should* be going direct to the server, which means you *should* get the correct value. Example code that shows (ideally as a repro) what you are seeing would be great.

**Comment by mgravell** [comment]
example code that works fine:

``` c#
    static async Task Main()
    {
        using var conn = await ConnectionMultiplexer.ConnectAsync("127.0.0.1");
        var db = conn.GetDatabase();
        RedisKey key = "issue1467";
        RedisValue field = "12345";
        var value = Guid.NewGuid().ToString("N");
        Console.WriteLine($"setting '{key}:{field}' to '{value}'...");
        await db.HashSetAsync(key, field, value);
        Console.WriteLine("done; fetching value...");

        var result = await db.HashGetAsync(key, field);
        Console.WriteLine(result);
    }
```

Do you have some code that *doesn't* work, that we can discuss?

**Comment by matteoPhre** [comment]
Hi, i'm going to close this issue. Forgive the waste of time. There was a cron job, started on docker-compose up, that moved the data on a mqtt queue and cleaning up the channel (nobody had told me about this cron).
