### ISSUE TITLE
More then one Instance of the ConnectionMultiplexer causes timeouts ? 

### ISSUE THREAD

**Issue by Tazer** [StackExchange/StackExchange.Redis#147]
Hello,

I'm using the Redis cache myself where we have a singleton. for all requests.  
But we are also using Microsoft's https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider. And this one is "config-only", I can't inject my singleton ConnectionMultiplexer. And when having those two instances of the ConnectionMultiplexer we seem to run into GET timeouts.  

So my real question is , Is it possible to run more then one instance of ConnectionMultiplexer without getting into problems ,within the same app/request?

**Comment by deepakverma** [comment]
Hi, There could be other reasons that might be making it timeout. 
with two connection multiplexer you might be using more bandwidth, can you check if you are getting network bound or CPU bound on the client?

**Comment by nmehlei** [comment]
Might be related: https://github.com/SignalR/SignalR/issues/3383

**Comment by NickCraver** [comment]
This shouldn't inherently cause any trouble, no. Multiple connections are generally fine. Do you have the exact exceptions happening? The counts will tell us which parts of the pipe are getting jammed up.
