### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by anandan84** [StackExchange/StackExchange.Redis#1470]
We are getting the below exception after upgrading to the latest version.

System.InvalidOperationException: Sequence contains no matching element     at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)     at StackExchange.Redis.Extensions.Core.Implementations.RedisCacheConnectionPoolManager.GetConnection()     at StackExchange.Redis.Extensions.Core.Abstractions.RedisCacheClient.GetDb(Int32 dbNumber, String keyPrefix) 

Code 

 public class RedisConnectionHandler : IRedisConnectionHandler
    {
        readonly Lazy<RedisCacheClient> LazyCacheClient = new Lazy<RedisCacheClient>(() =>
        {
            var serializer = new NewtonsoftSerializer();

            var redisConfig = new RedisConfiguration
            {
                Hosts = new[] {
                     new RedisHost{ Host = RedisConfigurationManager.Config.Host.ToString(),
                         Port =int.Parse(RedisConfigurationManager.Config.Port.ToString()),
                          }
                     },
                Password = RedisConfigurationManager.Config.Password,
                PoolSize = 100,
                Ssl = RedisConfigurationManager.Config.Ssl,
                ConnectTimeout = RedisConfigurationManager.Config.ConnectionTimeOut,
                AbortOnConnectFail = RedisConfigurationManager.Config.AbortOnConnectFail,
                AllowAdmin = RedisConfigurationManager.Config.AllowAdmin,
                Database = RedisConfigurationManager.Config.Database
            };

            redisConfig.CertificateValidation += (sender, cert, chain, errors) =>
            {
                return true;
            };

            IRedisCacheConnectionPoolManager redisCacheConnectionPoolManager = new RedisCacheConnectionPoolManager(redisConfig);
            return new RedisCacheClient(redisCacheConnectionPoolManager, serializer, redisConfig);
        });

        public IRedisCacheClient RedisCacheClient => LazyCacheClient.Value;
    }

Please help me on this.

**Comment by dmytrohridin** [comment]
Hey @anandan84 
The code that you provided seems not from this library, but from that one (Extensions):
https://github.com/imperugo/StackExchange.Redis.Extensions

**Comment by anandan84** [comment]
Thank you, let me create the bug in the extensions.

**Comment by NickCraver** [comment]
Since this is an extensions issue, closing out.
