### ISSUE TITLE
unit test and Moq

### ISSUE THREAD

**Issue by pratibha777** [StackExchange/StackExchange.Redis#1479]
Please help.
how do I test redis part here. eg IDatabaseAsync and HAshSetAsync. basically this method is getting countries and writing them in Redis. I am stuck with testing writing part??

public async Task Handle(CountryNotification notification, CancellationToken cancellationToken)
        {            
            var countries = await _queryService.AllAsync();
            var redis = _manager.Connection;
            IDatabaseAsync db = redis.GetDatabase(_redisConfig.DatabaseIndex);
            
            foreach (var country in countries)
            {
                await db.HashSetAsync($"{CacheConst.CountryKey}:{country.Id.ToString()}", country.ToHashEntries());
            }
        }

**Comment by mgravell** [comment]
Can you clarify the question here? If you're asking how to get Moq to do something specific: that's a question for the Moq folks. If you asking for API tweaks to make it more mockable, I'd need more specifics. What problem are you seeing currently?

**Comment by pratibha777** [comment]
HI, I want to add unit test for this Handler (Async Task Handle(.................
I can mock queryService to return hardcoded Countries.
But How do I all in all test this handler? that its writing correctly or is being called properly.
Do no want to use real Redis database here. better if its mocked.

**Comment by pratibha777** [comment]
My main problem is not being able to mock/fake connection. so its always null.

var redis = _manager.Connection;
IDatabase db = redis.GetDatabase(_redisConfig.DatabaseIndex);

**Comment by mgravell** [comment]
Context: I don't routinely use Moq, although I understand what it is. So: is there something *preventing* you using Moq here? I want to be very clear about the problem.

**Comment by pratibha777** [comment]
yes I am using Moq.

**Comment by NickCraver** [comment]
Looks like the interface was found here - closing out to cleanup!
