### ISSUE TITLE
Exception in SearchKeysAsync

### ISSUE THREAD

**Issue by anandan84** [StackExchange/StackExchange.Redis#1481]
While trying to remove all the keys from the redis DB using the key pattern. we are getting the following exception

System.OverflowException: Value was either too large or too small for an Int32.     
at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)     at StackExchange.Redis.Extensions.Core.Implementations.RedisDatabase.<SearchKeysAsync>d__38.MoveNext()

**Code** : 

  var keys = RedisCacheClient.GetDbFromConfiguration().SearchKeysAsync(string.Format("{0}*", key)).Result;

The value passed in the key is 2046595881.

Please help us with this.

**Comment by mgravell** [comment]
"extensions" is nothing to do with his library or the maintainers. However, key scanning is fully available in SE-Redis, via IServer (GetServer). What are you trying to do, exactly? I'm not going to try and support random code by "not me", but if you tell me what you're trying to *do* I can probably help with that.

**Comment by anandan84** [comment]
Thank you for the response. I am looking for deleting all the keys for an employee. In order to do that, I am passing the employee ID as input and try to get all the keys available for that employee.

For example, my keys as follows,
2046595881_PersData
2046595881_TransData

At some point, I need to clear all the keys for the given employee. To achieve this, I wrote the code like below,

 public void RemoveAll(string key)
        {

            var keys = RedisCacheClient.GetDbFromConfiguration().SearchKeysAsync(string.Format("{0}*", key)).Result;
            RedisCacheClient.GetDbFromConfiguration().RemoveAllAsync(keys);

        }

Here, the key is the employee ID (2046595881). I am getting the following exception at this code.

System.OverflowException: Value was either too large or too small for an Int32.     
at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)     at StackExchange.Redis.Extensions.Core.Implementations.RedisDatabase.<SearchKeysAsync>d__38.MoveNext()

I hope, I have given adequate details on my use-case. Please let me know if you need any specific details.

**Comment by mgravell** [comment]
I can only give advice re the API from *this* library (emphasis: you're using a different library that *wraps* this one), but: if you had a multiplexer:

``` c#
var pattern = employeeId + "*";
var db = mixer.GetDatabase(dbNumber);
var server = muxer.GetServer(yourServer);
foreach (var key in server.Keys(dbNumber, pattern))
{
    db.KeyDelete(key);
}
```

Despite the name `Keys`, this will use `SCAN` if it is available.

**Comment by anandan84** [comment]
Thank you, I have found where the issue is. When I SCAN for the keys, I am getting the following result which is not in the given pattern and the value is 281474976710656.

StackExchange.Redis.RedisResult.SingleRedisResult

And, it's failing in this line  nextCursor = int.Parse((string)innerResult[0]); as the value is not int32.

But, my question is I am getting this data even after flushing the DB.

Can you pls suggest me what is StackExchange.Redis.RedisResult.SingleRedisResult? And what type of data I can store.

**Comment by mgravell** [comment]
`SingleRedisResult` is a single (one) value - as opposed to an array, etc. It represents a single regular redis type - which could be a redis string, or a single hash value, set element, etc. It can be... well, just about anything. It will perform suitable casting as required. you might want to try casting it to `long` if it is outside of the `int` range.

**Comment by mgravell** [comment]
I don't see any code in "master" that starts `nextCursor =`, and you shouldn't need to crawl the cursors yourself - the library does that for you. Can you be more specific about what you're actually doing here? maybe a code sample?

**Comment by anandan84** [comment]
I am using the extension StackExchange.Redis.Extensions.Core.Implementations and the following code causing the issue. 
   public async Task<IEnumerable<string>> SearchKeysAsync(string pattern)
        {
            pattern = $"{keyPrefix}{pattern}";
            var keys = new HashSet<string>();

            var multiplexer = Database.Multiplexer;
            var servers = ServerIteratorFactory.GetServers(connectionPoolManager.GetConnection(), serverEnumerationStrategy).ToArray();

            if (!servers.Any())
                throw new Exception("No server found to serve the KEYS command.");

            foreach (var server in servers)
            {
                var nextCursor = 0;
                do
                {
                    var redisResult = await Database.ExecuteAsync("SCAN", nextCursor.ToString(), "MATCH", pattern, "COUNT", "1000").ConfigureAwait(false);
                    var innerResult = (RedisResult[])redisResult;

                    nextCursor = int.Parse((string)innerResult[0]); -- **My value is too large and it causing the filures here**

                    var resultLines = ((string[])innerResult[1]).ToArray();
                    keys.UnionWith(resultLines);
                }
                while (nextCursor != 0);
            }

            return !string.IsNullOrEmpty(keyPrefix) ? keys.Select(k => k.Substring(keyPrefix.Length)) : keys;
        }

**Comment by mgravell** [comment]
Once again: *that's now my code*. If you want support with that particular method, you should speak to whoever wrote it - presumably https://github.com/imperugo/StackExchange.Redis.Extensions

However: that method is also completely unnecessary (in addition to being buggy). SE-Redis has a fully working keys scanning API including pattern matching etc, as per the code sample above.

**Comment by anandan84** [comment]
Thank you for the suggestion. I have modified my code like below and it's working fine. Can you pls suggest if there is any issues in my code.
public IEnumerable<string> SearchKeys(string pattern)
        {
            pattern = string.Format("{0}*", pattern);
            var keys = new List<string>();

            try
            {
                var multiplexer = RedisCacheClient.GetDbFromConfiguration().Database.Multiplexer;
                var servers = ServerIteratorFactory.GetServers(multiplexer, serverEnumerationStrategy).ToArray();

                if (servers.Any())
                {
                    foreach (var server in servers)
                    {
                        foreach (var value in server.Keys(0, pattern))
                        {
                            keys.Add(value);

                        }
                    }
                }
                return keys;
            }
            catch (Exception ex)
            {
                
                throw;
            }

        }

public void RemoveAll(string key)
        {
            var keys = SearchKeys(key);
            RedisCacheClient.GetDbFromConfiguration().RemoveAllAsync(keys);

        }

**Comment by mgravell** [comment]
Looks fine at a glance. Does it work?

**Comment by anandan84** [comment]
Yes, it' working fine for me.

One of the Redis technical support executives mentioned like we should not use keys instead we should use only the SCAN.  As per your comment, I understood that the server.keys is executing only the SCAN command. Please correct me if my understanding is incorrect.

**Comment by mgravell** [comment]
It uses SCAN if it believes it to be available, and uses KEYS as a
fallback. In your case it is almost certainly using SCAN, but if you want
to be sure, use MONITOR. You could also simply disable (or rename) the KEYS
command at the server.

**Comment by NickCraver** [comment]
This one seems answered on the end - closing out to cleanup!
