### ISSUE TITLE
Timeout performing SCAN 

### ISSUE THREAD

**Issue by karthickj25** [StackExchange/StackExchange.Redis#1482]
We are facing the below exception on LIVE servers.

Redis hosted on linux : docker
Client Asp.net 4.6 windows 2016 docker.

```
Timeout performing SCAN (2000ms), inst: 1, qu: 0, qs: 0, aw: False, 
rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, 
serverEndpoint: 10.x.x.x:6379, mc: 1/1/0, mgr: 10 of 10 available, 
clientName: 378198E74D13, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=15,Free=32752,Min=4,Max=32767), 
v: 2.1.28.64774 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
at StackExchange.Redis.CursorEnumerable`1.Wait[TResult](Task`1 pending, Message message) in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 78
   at StackExchange.Redis.CursorEnumerable`1.Enumerator.SlowNextSync() in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 200
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```

LIVE server was not having much traffic application is working for now.

We tried to replicated issue in our test environment, the application collapsed after a while. Second run went through fine.

This behavior is hard to predict. Is anything can be done to resolve this issue.

PS: Total keys in redis is less than 200. I looked into /timeouts page but it did not help much

Appreciate any help.

**Comment by mgravell** [comment]
A timeout on `Wait` *sounds* like a sync-over-async / sync-context problem. You say asp.net 4.6 - any chance it is running with the legacy sync-context implementation? i.e. `<add key="aspnet:UseTaskFriendlySynchronizationContext" value="false" />` ?

The *ideal* fix here would be to switch to `KeysAsync`, but I don't know what compiler version you're using (requires C# 8). Note: as a general rule:

- you shouldn't usually use `KEYS`/`SCAN` in production as regular app code; those are *bad things*; they're fine to use from analytic tools, but you should usually design around scenarios that require you to use them routinely
- if you *do* have to use them, you *probably* shouldn't try throwing the results into an array/list - it is much better to treat it as an open unbounded sequence

**Comment by karthickj25** [comment]
Thanks @mgravell , After more testing it for found out the issue always happens on `SCAN` . I guess, as you suggested, will try avoiding `SCAN` where possible.
