### ISSUE TITLE
Timeouts caused by throttled thread injection

### ISSUE THREAD

**Issue by skurik** [StackExchange/StackExchange.Redis#1486]
Hi,

we have recently started using Azure Cache for Redis and soon after deploying, we started observing intermittent timeouts.

We are using the synchronous API.

Typically it looks like this

```
Timeout performing HINCRBY (5000ms), next: HINCRBY 9c15778a-7ad2-447d-bf77-abcd00a792df/9F5D4523E7E444739A4CABCD00E0490E-C41FBDB1E79623281AE95346316B95D
inst: 9, qu: 0, qs: 48, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: server.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: RD2818782207AE,
IOCP: (Busy=0,Free=1000,Min=4,Max=1000),
WORKER: (Busy=32,Free=32735,Min=4,Max=32767), v: 2.1.30.38891
```

First we thought we allocated too small of a tier in Azure, but after benchmarking it against higher tiers, it didn't prove to be the (primary) issue.

After reading the timeout guide and putting it together with __WORKER: (Busy=32,Min=4)__, I of course tried raising the CLR thread pool's min thread count and with that, I got rid of timeouts completely. I was able to achieve sustained 6000 ops/sec. even on a low tier with a client connecting from outside of the Azure network.

Then it occurred to us that another solution could be to use the asynchronous API, that it could solve the thread exhaustion problem as well. And it does. However, that led to a question:

We never had (or seemed to have) thread exhaustion problems before in our application caused by e.g. Entity Framework. And that even considering that

1 web request to our application = just 1 Redis call
1 web request to our application = typically tens of database calls (synchronous)

What is the special thing or design aspect of __StackExchange.Redis__ that it is susceptible to the thread exhaustion issues much more than other SDKs which I would say are comparable (e.g. Entity Framework)? 

I would like to know the answer because going async would be a huge undertaking for our application (we so far managed without it) and I don't have a bulletproof argument for "But why is it _necessary_ in this case?".

Also, don't timeout exceptions like the one above go against what is said in the timeout guide: "Note that You shouldn’t need a much fine-tuning of this from 2.0, since the dedicated thread-pool should be servicing most of the load."

Thank you very much for any insights.

**Comment by mgravell** [comment]
One factor here is that SE-Redis is doing something quite different - it is multiplexing data over a single connection, which is complex; we have a plan to refactor this to an alternative model that is much simpler and should avoid a *whole range* of problems - we just need to implement it. Right now, it is very hard for me to say what the underlying cause of this timeout is, as there are so many possible moving parts. That is one of the big things that the refactor will solve - and frankly: I am hopeful it will solve a huge number of common stall scenarios. I plan to start working on this pretty much "now".

**Comment by NickCraver** [comment]
Since this issue, additional things have come about. If you're in a position to get to `net6.0` or higher, there are threadpool changes that basically increment a counter when a wait is about to happen (stalling a thread indefinitely) and a decrement when it comes out. When the runtime sees a spike, it will more aggressively grow the thread pool _specifically for these cases_ which may help you here.

In general, I'll always recommend async for async things (like I/O off box especially), but short of that: some runtime improvements like the above should help. Going to close this out to tidy up, hope the advice here and above helps.
