### ISSUE TITLE
Obsolete responseTimeout in docs

### ISSUE THREAD

**Issue by suslovk** [StackExchange/StackExchange.Redis#1490]
ResponseTimeout is marked as obsolete and is not in use anymore, but it is not obvious from [docs](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Configuration.md). It was bit confusing to me, because I was using it as connectionString parameter and haven't seen any warnings. What do you think of marking it as obsolete in docs (or even remove it from docs)?

**Comment by NickCraver** [comment]
Absolutely! Trying to catch up in general - marking it as up for grabs :)
