### ISSUE TITLE
Endless cycle in srv.Keys by pattern / proper way to delete keys by mask?

### ISSUE THREAD

**Issue by xumix** [StackExchange/StackExchange.Redis#1493]
I have implemented method to delete keys by mask like this, but sometimes it gets stuck inside the method forever:
```csharp
public virtual async Task<long> DeleteByKeyMask<T>(string mask)
        {
            var res = await Policy.Handle<RedisConnectionException>()
               .RetryAsync(3, (exception, i) => HandleRedisConnectionError())
               .ExecuteAsync(async () =>
                {
                    var endPoints = redis.Value.GetEndPoints();
                    var database = redis.Value.GetDatabase();
                    var pattern = CreateKey<T>(mask);
                    long totalDeleted = 0;

                    foreach (var ee in endPoints)
                    {
                        var srv = redis.Value.GetServer(ee);
                        var keys = srv.Keys(database.Database, pattern, 1000).ToArray();

                        while (keys.Length > 0)
                        {
                            var deleted = await database.KeyDeleteAsync(keys);
                            totalDeleted += deleted;
                            keys = srv.Keys(database.Database, pattern, 1000).ToArray();
                        }
                    }

                    return totalDeleted;
                });

            return res;
        }
```

It looks like redis keeps returning cursor for SCAN..MATCH so srv.Keys keeps returning non zero.
What is the proper way to handle this problem?

**Comment by mgravell** [comment]
which bit is looping forever? note:

``` c#
var keys = srv.Keys(database.Database, pattern, 1000).ToArray();
```

does *not* mean "get the first 1000 matches" - it means "get all the matches, using a page size of 1000"; for very large keyspaces, this could take a while - as will a huge delete.

If this was me, I'd try:

``` c#
var batch= new List<RedisKey>();
const int BATCH_SIZE = 512;
int totalDeleted = 0;
await foreach (var key in srv.Keys(database.Database, pattern))
{
    batch.Add(key);
    if (buffer.Count == BATCH_SIZE)
    {
        totalDeleted  += await database.KeyDeleteAsync(batch.ToArray());
        batch.Clear();
    }
}
if (batch.Any())
{
    totalDeleted  += await database.KeyDeleteAsync(batch.ToArray());
}
```

**Comment by xumix** [comment]
@mgravell thanks for your answer!
This basically means that page size only limits how much data is sent to client in a batch, but does not limit the actual search?
So, I don't need to do a `while()` and `var keys = srv.Keys(database.Database, pattern).ToArray();` will return ALL the found keys?

**Comment by mgravell** [comment]
> As for the loop this looks more like a redis bug/problem, it keeps returning nonzero cursor even after all keys have been deleted by mask

Returning a non-zero cursor is not actually expected; the important question is: does is *become* zero if you iterate it enough.

In fact, even "page size" is the wrong word: the way `SCAN` works is that it doesn't guarantee *anything* in any particular result; you give it a hint of how much time to spend looking, and it looks *some amount* through the keyspace, and returns a token as to where it got to. This is to avoid a scenario where it has to perform a long (blocking) operation when you `SCAN` a **huge** keyspace for a pattern that *doesn't exist* (or exists near the end). The idea is that you'd basically get a whole pile of nothings:

```
> scan 0
1) "3452935"
2) (nil/empty)
> scan "3452935"
1) "1235815"
2) (nil/empty)
> scan "1235815"
1) "8915124"
2) (nil/empty)
> ...etc etc, until finally
> scan "1235815"
1) "0"
2) (nil/empty)

it is that final `"0"` that means you reached the end.

**Comment by mgravell** [comment]
note: increasing the `COUNT` increases the amount of time it spends looking in each iteration, and reduces the number of round-trips involved; but `COUNT` does **not** mean "get this number each time" - you can get nothing each time (which does *not* mean you've reached the end), and you can theoretically get *more* than you requested; see the docs: [The COUNT option](https://redis.io/commands/scan#the-count-option)

**Comment by NickCraver** [comment]
Advice above - closing out with no more activity.
