### ISSUE TITLE
Read/write splitting

### ISSUE THREAD

**Issue by kDanil** [StackExchange/StackExchange.Redis#1494]
Hello,

how correctly configure library to send write queries to masters and read queries to masters or slaves randomly?
Similar how "ioredis" library supporting it with flag "all" - https://github.com/luin/ioredis#read-write-splitting

None of CommandFlags options seems to help and I see no combination of these flags which can do a trick.

Thanks.

**Comment by NickCraver** [comment]
Without more info here - closing this out to cleanup.
