### ISSUE TITLE
request module not working with get

### ISSUE THREAD

**Issue by tsheringtashi** [StackExchange/StackExchange.Redis#1497]
I have imported requests module on the pycharm. 

GET doesn't work with the import request as follow

import requests

r = requests.get('https://imgs.xkcd.com/comics')

with open('comics.png','wb') as f:
    f.write(r.content)

error: AttributeError: partially initialized module 'requests' has no attribute 'get' (most likely due to a circular import)

**Comment by NickCraver** [comment]
Hey there - I'm not sure which project you're having an issue with (seems like Python?) but it is not related to the StackExchange.Redis library that this repository is for :)
