### ISSUE TITLE
sometimes we get slow response

### ISSUE THREAD

**Issue by roccobarbaresco** [StackExchange/StackExchange.Redis#150]
Hi,
we are having some issues performing an HashSet (but in general with all the Redis commands) on a Ubuntu machine (on x86 platform) using your library with mono.
We could reproduce the problem with a simple solution that I post here.
Note that we have deployed the same solution on a Yocto (arm platform) and we do not have any problem. 
We tested also an Ubuntu 64bit machine (on x86) and we still have problems. 
We tested also on Windows with no problems.
The problem seems to be when we make the calls from Ubuntu (we have problems using both the local redis-server (on Ubuntu) and the remote redis-server (on Yocto).
If we do the same calls from Yocto (both to the localhost redis-server and to the Ubuntu redis-server) we have no problems at all.
We use the same mono version (3.10.0) and the same redis-server version (2.8.4).

Here you have a console program that writes to the console "HSET SLOW" when we have more a wait of more than 300 msec.

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;
using System.Threading.Tasks;
using StackExchange.Redis;

namespace Stressone {
	class Program {
		static ConnectionMultiplexer redis;
		static void Main(string[] args) {
			int n = 2;
			var host = "127.0.0.1";
			if (args.Length > 0)
				host = args[0];
			redis = ConnectionMultiplexer.Connect(new ConfigurationOptions { AllowAdmin = true, ResolveDns = true, EndPoints = { {host, 6379 } }, KeepAlive = 60, ConnectTimeout = 60000, SyncTimeout = 60000 });
			var tasks = new List<Task>();
			for (int i = 0; i < n; i++) {
				tasks.Add(new Task((x) => {
					Loop((int)x);
				}, i));
				tasks[i].Start();
			}
			Console.WriteLine("Press CR to close");
			Console.ReadLine();
		}

		static async void Loop(int i) {
			while (true) {
				SingleLoop(i);
				await Task.Delay((new Random().Next(20) + 2) * 20);
			}
		}

		static string RandomString(string pfx) {
			return string.Format("{0}{1}", pfx, new Random().Next(200));
		}

		static void SingleLoop(int i) {
			IDatabase db = redis.GetDatabase();
			var k = RandomString("identificatore");
			var f = string.Format("{0}", i);
			var v = RandomString("valore");
			var dt = DateTime.Now;
			Stopwatch sw = Stopwatch.StartNew();
			db.HashSet(k, f, v);
			sw.Stop();
			if (sw.ElapsedMilliseconds > 300) Console.WriteLine("{1} HSET SLOW!! {0}", sw.ElapsedMilliseconds, dt.ToString("hh:mm:ss"));
		}
	}
}
```

**Comment by roccobarbaresco** [comment]
discard this description, changing parameters we found problems also on Yocto!
See new issue description for a new test (run the test program with 50 tasks).
Thanks.

**Comment by xiexin36** [comment]
I also find this problem on mac, can you tell me how to avoid this?

**Comment by roccobarbaresco** [comment]
Hello xiexin36,
we had to change the redis client because we could not solve this issue.
We switched to CSRedit client (it has a little different api) and we solved all our issues (and it works ok for us).
bye Rocco

**Comment by NickCraver** [comment]
Closing to merge with #151
