### ISSUE TITLE
Simple code sample that works with Azure Redis Cache please

### ISSUE THREAD

**Issue by pooran** [StackExchange/StackExchange.Redis#1502]
{"Could not load file or assembly 'System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.":"System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"}

{"The assembly for System.Buffers + System.Runtime.CompilerServices.Unsafe could not be loaded; this usually means a missing assembly binding redirect - try checking this, and adding any that are missing; note that it is not always possible to add this redirects - for example 'azure functions v1'; it looks like you may need to use 'azure functions v2' for that - sorry, but that's out of our control"}

I simply want to use Azure Redis Cache with StackExchange.Redis ... spent more time on this than writing other important pieces.. it gives hope that it works.. then it gives an error next day.

Can we just have one working code sample that connects to Azure Redis Cache

**Comment by mgravell** [comment]
This is a binding redirect problem on .NET Framework (more info here: https://nickcraver.com/blog/2020/02/11/binding-redirects/) - largely outside of our control (although we have recently managed to convince MS to take another attempt at fixing the tools here, but no ETA on that).

Take a look at the article linked above - if that doesn't help, let me know exactly what framework version you're using, and I'll get a working demo with the right assembly binding config.

**Comment by pratyushaadavalli** [comment]
Hi, is this an issue on .netcore app as well. I have referenced the system.IO.Pipelines explicitly but still it fails to load the file or assembly reference
Using stack exchange redis 2.2.4
Thank you

**Comment by gonsergey** [comment]
I also faced similar issue: **Could not load file or assembly 'System.IO.Pipelines, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified**.

Environment:
Microsoft.NET.Sdk.Functions v3.0.11
FUNCTIONS_EXTENSION_VERSION: ~3
StackExchange.Redis v2.2.4

With StackExchange.Redis v2.1.58  my Azure func works fine.

**Comment by dceravigupta** [comment]
@gonsergey did you looked at https://github.com/StackExchange/StackExchange.Redis/issues/1637?

**Comment by gonsergey** [comment]
This is exactly what I need. Thanks @dceravigupta

**Comment by NickCraver** [comment]
Looks like we're resolved above - closing this out!
