### ISSUE TITLE
Question: SortedSetRankAsync return type is long?

### ISSUE THREAD

**Issue by dszryan** [StackExchange/StackExchange.Redis#1506]
why is the return type long and not UInt32?

since the documentation does state it is an integer: https://redis.io/commands/zrank

or am I missing something?

thanks in advance

**Comment by mgravell** [comment]
"integer" doesn't mean `int` / `Int32`; all of `byte`, `sbyte`, `short`, `ushort`, `char`, `int`, `uint`, `long` and `ulong` are "integer" types. As for why to choose `long` over others? The RESP documentation defines what it means by "integer":

> However, the returned integer is guaranteed to be in the range of a signed 64 bit integer.

Interestingly perhaps, the documentation *does* talk about bounds on a few data types [here](https://redis.io/topics/data-types), but it doesn't say anything about the limits on sorted sets. Plus limits have a habit of changing over time anyway! So *in the absence of formal documentation to the contrary*, we should allow for the possibility that the range is outside of the 32-bit scale. Allowing 64-bit on the API covers this without any particular inconvenience.

As for signed vs unsigned: while unsigned has a certain expressive quality, in reality unsigned integer types (with the exceptions of `byte` and `char`) are relatively rare in .NET APIs. One reason for this is that unsigned integers are not "CLS compliant". How much that matters is subjective, but as an API designer I try to allow for the very real possibility that not all of my users are in C#.

**Comment by dszryan** [comment]
thanks for the exhaustive response.
