### ISSUE TITLE
RedisValue[] HashGet method documentation incorrect?

### ISSUE THREAD

**Issue by SpiritBob** [StackExchange/StackExchange.Redis#1507]
The XML documentation for the argument `hashFields` states the following: 

> The fields in the hash to delete.

Shouldn't it be the same as in `RedisValue HashGet` method call?

> The field in the hash to get.

**Comment by mgravell** [comment]
Sounds like a copy/paste error. Fixes welcome, or I'll get to it when I get
a moment.
