### ISSUE TITLE
Question: rollback transaction

### ISSUE THREAD

**Issue by dszryan** [StackExchange/StackExchange.Redis#1508]
excerpt from here: [And in StackExchange.Redis?](https://stackexchange.github.io/StackExchange.Redis/Transactions.html#and-in-stackexchangeredis)

```
try {
  var newId = CreateNewId();
  var tran = db.CreateTransaction();
  tran.AddCondition(Condition.HashNotExists(custKey, "UniqueID"));
  tran.HashSetAsync(custKey, "UniqueID", newId);
  throw new Exception();
  bool committed = tran.Execute();
  //   ^^^ if true: it was applied; if false: it was rolled back
}
catch {
  // assuming the connection would be reused
  // what needs to be done here to dispose the transaction?
}
```

**Comment by tombatron** [comment]
@dszryan When you say "connection" are you talking about the instance of `IDatabase` that you used to create the instance of `ITransaction`, then you don't really need to do anything. 

Why?

Because there is no spoon... er... object pool. By default (currently) the `ConnectionMultiplexer` creates a single connection to Redis and `IDatabase` is a "lightweight pass-thru" that you use to interact with that connection.

**Comment by dszryan** [comment]
> @dszryan When you say "connection" are you talking about the instance of `IDatabase` that you used to create the instance of `ITransaction`, then you don't really need to do anything.
> 
> Why?
> 
> Because there is no spoon... er... object pool. By default (currently) the `ConnectionMultiplexer` creates a single connection to Redis and `IDatabase` is a "lightweight pass-thru" that you use to interact with that connection.

refined the question.

**Comment by mgravell** [comment]
> what needs to be done here to dispose the transaction?

Nothing at all. Until you call `Execute`, it is just a local buffer of pending operations - those don't need to be cleaned up: they are either executed (via `Execute[Async]`, or they aren't). If they aren't: they can just be garbage collected. If they are: everything that needs to happen has already happened, or is in progress. So: there is nothing to do.

Did you have a specific concern?

**Comment by dszryan** [comment]
the concern was around when an exception was thrown and the connection is being reused - ensure the queued "instructions"  not persisted.

which has been addressed. thank you.
