### ISSUE TITLE
No logging or rethrowing on GetReplicasForService in ConnectionMultiplexer

### ISSUE THREAD

**Issue by ThomasTosik** [StackExchange/StackExchange.Redis#1512]
Hi!

I was trying out the new Sentinel support and had some issues. 
`Exception thrown: 'System.NullReferenceException' in StackExchange.Redis.dll: 'Object reference not set to an instance of an object.'
Stack trace:
at StackExchange.Redis.ConnectionMultiplexer.GetSentinelMasterConnection(ConfigurationOptions config, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2401`

I started to dig and found out that i had no chance to get to the real issues due to missing logging or rethrowing.
https://github.com/StackExchange/StackExchange.Redis/blob/f52cba7bbe4f22a47a9a7d9c84c9f2824465cae7/src/StackExchange.Redis/ConnectionMultiplexer.cs#L2530

Is this intentional? After a tedious debug session i got at least my exception that i was looking for...

**Comment by mgravell** [comment]
"intentional" is complex, but I'm going to assume "probably not", but since the code here is parallel, logging becomes... trickier; what is the scenario that caused this to fail in this way, out of curiosity?

**Comment by ThomasTosik** [comment]
So the exception that i got was:
``Exception thrown: 'StackExchange.Redis.RedisConnectionException' in StackExchange.Redis.dll: 'Unexpected response to SENTINEL: MultiBulk: 0 items'
Stack trace:
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2826``

Some background: I was using the bitnami redis/sentinel setup in my docker tests. I had only one redis master (first naive try). After i added a real redis slave this issue was gone.

**Comment by azharmahmood** [comment]
Hello, I am getting same error, I have only one remote sentinel master in my test environment. So is the issue resolved by adding a sentinel slave? Please confirm?

**Comment by ThomasTosik** [comment]
> 
> 
> Hello, I am getting same error, I have only one remote sentinel master in my test environment. So is the issue resolved by adding a sentinel slave? Please confirm?

I got it to work with one Sentinel, one Redis Master and one Redis Slave.

**Comment by NickCraver** [comment]
Thanks for the additional info! The root of the problem here is in `SentinelGetSentinelAddressesProcessor` I believe, specifically: https://github.com/StackExchange/StackExchange.Redis/blob/f52cba7bbe4f22a47a9a7d9c84c9f2824465cae7/src/StackExchange.Redis/ResultProcessor.cs#L2069-L2075

The result processor treats "no endpoints" as an invalid state, e.g. in this case where there simply are no replicas. I pushed up a PR for this in #1527.

**Comment by NickCraver** [comment]
Fixed via #1527
