### ISSUE TITLE
IEnumerable<HashEntry> HashScan(RedisKey key, RedisValue pattern = default, int pageSize = 250, long cursor = 0, int pageOffset = 0, CommandFlags flags = CommandFlags.None);

### ISSUE THREAD

**Issue by wjhmiss** [StackExchange/StackExchange.Redis#1513]
the HashScan mothed is bug。cant return pageSize 250，but return all。wrong

**Comment by mgravell** [comment]
can you define "bug" and "wrong" in this? what are you seeing? what makes you think something is wrong? how could I see this wrongness?

**Comment by mgravell** [comment]
I'm going to have to close this if you can't give me any more context as to what you're seeing.

**Comment by Victor-Tseng** [comment]
I guess that what he is trying to say is

"The HashScan method has a bug. It does not return 250 items when pageSize=250 but return the entire result, which is wrong behavior.

Maybe he is hitting https://github.com/StackExchange/StackExchange.Redis/issues/729 ?

**Comment by mgravell** [comment]
It sounds like it, but: that is the *correct* behaviour :)

The intent of the `pageSize` is *not* to restrict the number of returned items - it is to control how the data fetch happens; the entire space is still iterated in all scenarios. If you want to limit the number of items: the LINQ `Take` method is useful for that.

(as a side note: even at the redis server: the meaning of this parameter is not "give me exactly this amount" - it is more a hint about the amount of work to do)
