### ISSUE TITLE
StringSetAsync method is very slow

### ISSUE THREAD

**Issue by MasiumDev** [StackExchange/StackExchange.Redis#1515]
My application is run on 4 machines and I process something then save its in Redis through StackExchange.Redis with the await StringSetAsync method. 
```cs
 var watch = new Stopwatch();
 watch.Start();
 await CacheProvider.UpdateOrCreateAsync(instrumentId, instTrade);
 watch.Stop();
 Logger.Info($"{instrumentId}: {watch.ElapsedMilliseconds}");
```

My UpdateOrCreateAsync method
```cs 
var expiryTimeSpan = absoluteExpiration?.Subtract(DateTime.Now);
return await Redis.StringSetAsync(key, JsonConvert.SerializeObject(value, CustomJsonSettings.GetJsonSerializerSettings(false)), expiryTimeSpan);
```

The result of time (ms) and count: [log.txt](https://github.com/StackExchange/StackExchange.Redis/files/4856188/log.txt)
I run Redis benchmark with command `redis-benchmark -h 10.0.0.147 -a ******* -t set,get -d 4000` and result: [redis-benchmark.txt](https://github.com/StackExchange/StackExchange.Redis/files/4856189/redis-benchmark.txt)

**_why I have very high latency on some operations, but it's not in redis benchmark?!_**

**Comment by NickCraver** [comment]
Just checking what the comparison here is: is the benchmark being run between the same set of machines? If so, are the under the same load?

I don't know what `CacheProvider.UpdateOrCreateAsync` is doing - that's not our code. It looks like there's overhead in there, and possibly locking. Can you elaborate on what's happening? If it's not a direct call to our library, I can't advise of bottlenecks above that...but with more info we may be able to help :)

**Comment by NickCraver** [comment]
Without more info, going to close this one out.
