### ISSUE TITLE
Sentinel tries to connect to down replica in ConnectAsync

### ISSUE THREAD

**Issue by mchandler-manticore** [StackExchange/StackExchange.Redis#1516]
Having redis setup with 3 sentinel's and 2 replica's, if one of the replicas is not online sentinel shows it as having the flag `s_down` but when calling `ConnectionMultiplexer.ConnectAsync` SE  still tries to connect to the down replica throwing an `RedisConnectionException: UnableToConnect` exception and failing the connect.

I would expect ConnectAsync to ignore down replicas as if a service using SE restarts while a replica is down it will no longer be able to connect to redis.

```
127.0.0.1:26379> sentinel replicas backend
1)  1) "name"
    2) "10.240.0.165:6379"
    3) "ip"
    4) "10.240.0.165"
    5) "port"
    6) "6379"
    7) "runid"
    8) "c6cf787bc84f3022f443576b790ca19801a090b7"
    9) "flags"
   10) "slave"
   ...
2)  1) "name"
    2) "10.240.0.57:6379"
    3) "ip"
    4) "10.240.0.57"
    5) "port"
    6) "6379"
    7) "runid"
    8) "6c59ea2709a32f37ffa99a33859ae803fbb72c79"
    9) "flags"
   10) "s_down,slave"
   ...
```

**Comment by NickCraver** [comment]
The Sentinel's state data is forever in a race here, so we attempt to connect to all servers it tells us about (and the multiplexer continues to attempt connecting in the background). To ignore downed servers in the initial connection, please use `abortOnConnectFail=false` so things will carry on despite not connecting to all intended nodes at the start :)
