### ISSUE TITLE
Web application stops responding under load when using StackExchange.Redis

### ISSUE THREAD

**Issue by jmazurpl** [StackExchange/StackExchange.Redis#1522]
I'm running into strange situation when using StackExchange.Redis (2.0.593) in the web application made in .NET Core 3.1 that I'm currentely working on.

When there is low traffic on the server evertything seems to work fine, but when there is some load the whole application hangs and stops to respond. I had same issue when running it on Windows Server with IIS and on linux containers on Kubernetes. What is more in both cases when I switch IDistributedCache to use in-memory storage (so no connection to Redis) everything is working fine even under heavy load. 

Even when application is not responding I'm able to connect to Redis from command line and post queries there. The only way to make tha application to work again is to restart IIS or container.

Enyone had such problems?

**Comment by NickCraver** [comment]
Are you seeing any error messages? It sounds like thread pool exhaustion on the surface, but any data would help diagnose here. Also, have you tried more recent versions of the library where we're tweaked thread theft a bit further?

**Comment by spoony2020** [comment]
Hi, did you find the reason or get any solution? I've got the same issue in net core 3.1 with StackExchange.Redis(2.0.519). The docker container is still work, but the dotnet process is hang and cpu become 0% the only way is  restart the container.

**Comment by jmazurpl** [comment]
Unfortunately not. Because of the lack of solution we decided not to use redis in the project.

**Comment by NickCraver** [comment]
A few deadlocks were found and fixed in the 2.1+ line, but seems like this issue is one for closing out. For anyone finding this, please use the latest version with a few deadlock situation fixes.
