### ISSUE TITLE
StackExchangeRedis timeout hazard

### ISSUE THREAD

**Issue by JHeLiu** [StackExchange/StackExchange.Redis#1524]
StackExchange.Redis (2.1.30)
StackExchangeRedis timeout was very severe on.net CORE version 3.1x,5000MS 1000MS 2000MS May timeout，this affected the production version,

StackExchange.Redis (2.0.601)
if I switch to.NET CORE 2.1 is normal

**Comment by moshegutman** [comment]
Do you experience the same issue on .NET Core 3.1 with StackExchange.Redis (2.0.601)? I'm having a similar problem

**Comment by JHeLiu** [comment]
@moshegutman  Yes

**Comment by NickCraver** [comment]
Do you have some example exception messages? They detail a lot of info specifically for communicating to us what is going wrong.

**Comment by NickCraver** [comment]
Without more info - can't do much here. Closing out to cleanup.
