### ISSUE TITLE
Lot of IOCP threads with single connection multiplexer 

### ISSUE THREAD

**Issue by PrasannaVelisetti** [StackExchange/StackExchange.Redis#1529]
Hi, 

I am seeing timeouts with StackExchange.Redis client in my API showing IOCP threads around 400 while the minimum setting is 16. We have throttling enabled in the API to 10 requests and we are using single connection multiplexer with synchronous GET/SET requests. Can you please clarify why the IOCP thread count so high?

**Comment by mgravell** [comment]
Are you sure you only have the one multiplexer? We don't touch IOCP
directly - we just have two async socket handlers per multiplexer.

**Comment by PrasannaVelisetti** [comment]
yeah, we are having single multiplexer. With a single API request, we have around 300 SET operations. Is it likely that this is the issue?

**Comment by mgravell** [comment]
It shouldn't. Is this cloud or local? Is TLs involved? And you say you're
using synchronous calls?

**Comment by PrasannaVelisetti** [comment]
Local and synchronous calls

**Comment by NickCraver** [comment]
@PrasannaVelisetti can you post some of your exceptions? They contain the data that greatly assists in explaining the problem. There's a reason we put all those stats in there :)

**Comment by PrasannaVelisetti** [comment]
hi @NickCraver, please find the exception as given below:

Timeout performing GET (30000ms), next:  GET somekey, inst: 15, qu: 0, qs: 148, aw: False, rs: ReadAsync, ws: idle, in: 63129, in-pipe: 0, out-pipe: 0, serverEndPoint: someEndPoint, mc: 1/1/0, mgr: 9 of 10 available, clientName: someClient, IOCP: (Busy=223,Free=767,Min=16,Max=1000), WORKER: (Busy=104,Free=32663,Min=16,Max=32767), v: 2.1.30.38891 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by NickCraver** [comment]
@PrasannaVelisetti Thanks, that helps! From the exception we can see 223 threads _busy_, not just there on the IOCP side and 104 workers in the same state. That's quite a huge amount of load and context switching going on. Do you have any idea what kind of hardware this is running on? Unless it's extremely beefy, that much load (if sutained) is going to overwhelm most CPUs to the point they can't keep up.

**Comment by PrasannaVelisetti** [comment]
@NickCraver yeah, thats a lot of threads. The API receives 10 requests per second, and each request has around 300 "set" operations to do on redis. So I am wondering if the multiplexer internally spawns separate thread for each operation on redis

**Comment by NickCraver** [comment]
It's a pipeline on our side, at most you'd have a task on the pile - can you share the structure of the code loop you're calling? We may be able to advise on optimizing it greatly.

**Comment by NickCraver** [comment]
Closing out to cleanup here - can't assist without more info here. Looks like an overall workload problem and not specific to the client though.
