### ISSUE TITLE
No mux.WhenAll

### ISSUE THREAD

**Issue by Crisfole** [StackExchange/StackExchange.Redis#153]
I use `Task.WhenAll` frequently to wait for a sequence of tasks and get back the results.

I'd love for the timeout to be respected, but I can't find an equivalent on the ConnectionMultiplexer.

**Comment by NickCraver** [comment]
Can you give an example of how this would work? You can use raw `Task`s as they are today...perhaps code would clarify what you're after here.

**Comment by mgravell** [comment]
You could sort of write this right now with something like:

    var all = Task.WhenAll(tasks);
    var timeout = Task.Delay(timeout);
    var winner = await Task.WhenAny(all, timeout);
    if(winner == timeout) {
        throw new TimeoutException();
    }

(Untested etc)

Not sure there's an urgent need to expose it in SE.Redis, though.

**Comment by Crisfole** [comment]
To be honest I can't even remember what I needed it for. I've since moved on from that position.
