### ISSUE TITLE
Synchronous approach - timeout or low throughput 

### ISSUE THREAD

**Issue by gitetl2016** [StackExchange/StackExchange.Redis#1535]
hi,

I am processing a file with a few million rows, processing row-by-row.  This is happening in a Synchronous and serial manner. Despite the Redis turn-around times being very fast (in microseconds), the overall throughput is very slow. For example, when Redis database is queried in the backend by dbsize, the rate of new {key, value} pairs created is very slow , which is at the rate of few tens in every minute. The file is being read, not written as part of this experiment, so, only one IO activity is happening (disk read, no write).

Scenario 2:  Next, I modified the the programming approach to Synchronous but multithreaded.  I have spun a few tens of threads, each working on a few hundred thousand rows converting files to datatables, thus sharing the load. There are two cores each eight gig memory.   This is happening in Synchronous but multithreaded manner. And in here, I was getting timed out in Get/Set calls. I have only one ConnectionMultiplexer. To resolve timeouts due to threads involving in a race condition (possibly) I have put a GetLock and SetLock and channelled all my threads' all Get/Set calls through these locked methods,  but, it didn't solve the timeout. So, I increased synctimeout configuration setting to 60000.  In these   circumstances, throughput is slowing down very much.  During timeouts, as per error message, the qs was not very high it was only in single digit numbers. Also, IOCP Busy was 1 whereas nearly  999 free. So, was Worker Thread number, it had many free and 0 busy.  One thing noticed is both IOCP and Worker were less than the MIN settings, MIN was set to 2.  So, it doesn't look like its lack of resources - but, using these by the threads in a manner that should avoid a race condition. Despite the mode of programming being Synchronous, the timeout error message had a mention of rs=ReadAsync once and once rs=ComputeResult.  Does this signal any potential clue?

Could you share your thoughts on the root cause of slow throughput and also timeout otherwise?  Will upgrading to Asynchronous TPL mode of programming improve throughput and avoid timeouts due to race conditions? Any pseudo code could help, thank you.

**Comment by mgravell** [comment]
What is the data here? Are you sending/receiving huge blobs/clobs, for
example? If so: bandwidth is possibly the barrier. That's the only way I
can make sense of tens per minute. It should be tend of thousands per
second!

**Comment by gitetl2016** [comment]
thanks Marc.  Input data is a flat file around seven million rows, weighing a couple of giga byte.  This is being processed by nearly forty threads in a 2 core system.  Each of these threads is converting a portion of the input file into a few thousand rows, translating to in-memory Datatables worth around 20 Mb and these rows are doing a Redis lookup.  thank you

**Comment by gitetl2016** [comment]
I reduced the input file from several millions to eight hundred thousand. So, eight threads are spun each handling hundred thousand rows.  Redis throughput is 300 {key, value} pairs stored per minute as observed from dbsize (roughly 50 per sec).  I had flushed all keys from Redis cache before the run. thank you.

**Comment by mgravell** [comment]
Again, without actually being able to play with things and look at the payloads, I have no idea whether this is expected or unexpected. There are 4 costs we need to consider:

- server processing time
- bandwidth
- latency
- client processing time

The server processing time is whatever it is; we can't do much about it without sharding.

Latency can be a factor in chatty APIs, but can be amortized with SE-Redis by overlapping concurrent operations from different threads. And if your payloads are non-trivial, latency usually becomes a non-factor anyway.

Client processing time: the numbers you describe are well under what I would normally expect, and I would be surprised if this was the cause.

So that leaves bandwidth. Are you monitoring your network saturation? This would be the first place I'd look. If you're filling your available network capacity, then: yup, that'll happen.

**Comment by gitetl2016** [comment]
thanks again Marc. Client processing time:  this is almost negligible.  At the minute, I am not doing anything with retrieved value of {key,value} pair. Redis throughput is being examined in the context of threading / Synchronous programming.  Input is a 120Mb file with eight hundred thousand rows. Threads are spun for every hundred thousand rows. During the program's run the observations are : The ethernet speed is sending at 350 kbps , and receiving at 72 kbps.  Cpu 100% utilisation 2GHz.   memory is 2gb of 8gb (25%)  Disk IO is doing 100 Kbps.      thank you.

**Comment by gitetl2016** [comment]
Hi Marc, I have captured some runtime stats.  Here they go.   Within the forloop that loops through in-memory Datatable and connects to Redis, the response times as observed from Visual Studio performance profiler's CPU usage are as follows:

1) StringGet 1ms
2) If the key is not present, StringSet, which is taking roughly 350ms to 450ms

The net effect is just over 1 and under 2 rows throughput per second or roughly 100 rows per minute. Which means, a Datatable with ten thousand rows is taking around one-and-half hours to complete  its Get/Set cycle on Redis and subsequently updating the Datatable with corresponding value fetched from {key, value} pair.

Is this a normal throughput?  I believe, it is not. Any suggestions are welcome, thanks.

Both my .net code and Redis 6GB Cache are in the same geographic location on the cloud. (I see Microsoft Azure Redis documentation saying that Redis Cache 6Gb is a moderate performance tier. But a throughput of 90 minutes for ten thousand rows signals something else as the possible root cause, much less than a moderate performance)

thank you.

**Comment by mgravell** [comment]
The get time suggests strongly to me that this isn't a client library problem, and that the lib is doing whatever it needs to. The set time, therefore, is presumably some overheads at the redis implementation itself - this *could* be bandwidth, but could also be persistence or replication / consistency overheads. Either way: I'm pretty sure that this is not an overhead that I can do anything about, from the client. This all sounds like server things to me.

**Comment by gitetl2016** [comment]
thank you.   I am researching and yet to find a particular feature - Is there an option in Redis to download the full set of {key, value} pairs to user program's runtime environment, so that, network round trips are avoided?  Said otherwise, in one go we download all {key, value} pairs into the user's program in-memory working set.   Process these available values.  And, construct a list of writeTasks to Set the new {key, value} pairs and upload these by executing batch?

This approach avoids the fundamental problem with network round trips.

thanks

**Comment by NickCraver** [comment]
You can do this for a hash, but not all of Redis, at least efficiently. I would say that your use case is quite strange for Redis, and it may not be the appropriate data store to use.
