### ISSUE TITLE
Is StackExchange.Redis.StrongName maintained?

### ISSUE THREAD

**Issue by kmcclellan** [StackExchange/StackExchange.Redis#1537]
I wanted to use the strongly named assembly for my project (for compatibility with `Microsoft.Extensions.Caching.Redis`). But it's been years since a new version was published to [NuGet (v1.2.6)](https://www.nuget.org/packages/StackExchange.Redis.StrongName/).

Is this just an oversight, or is the strongly named version of this project no longer maintained? (My apologies if I'm missing documentation on this somewhere...)

**Comment by mgravell** [comment]
v2 was a breaking change, so we took the opportunity to make `StackExchange.Redis` strong-named at the same time. As such, there is no need to issue a new version of `StackExchange.Redis.StrongName`.

We *discussed* shipping it as a meta-package, i.e. an empty package that just adds a dependency to `StackExchange.Redis`, but we decided to keep it simple.

**Comment by kmcclellan** [comment]
Ah, that makes sense. Thanks for the explanation. Feel free to close.

Incidentally, I just found [`Microsoft.Extensions.Caching.StackExchangeRedis`](https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis) which uses v2 and appears to be the successor to `Microsoft.Extensions.Caching.Redis`. Wish they had just bumped their major version (would have prevented my confusion).

**Comment by NickCraver** [comment]
Ah good to hear - glad you're sorted!
