### ISSUE TITLE
StringGetAsync : Order of returned Keys Array[]

### ISSUE THREAD

**Issue by gitetl2016** [StackExchange/StackExchange.Redis#1538]
hi,

I am looking at StringGetAsync overloaded methods one of which returns an array of values.  Is the order of returned values array guaranteed to be in the same order as that of keys sent as parameter to this method? For example, does Value[n] guarantee to correspond to key[n], for every n?

thank you

**Comment by NickCraver** [comment]
Yep, that's how it works!

**Comment by NickCraver** [comment]
Closing this out since it's a quick one :)
