### ISSUE TITLE
System.NotImplementedException:“The ConnectionMultiplexer is not a Sentinel connection.”

### ISSUE THREAD

**Issue by quxin168** [StackExchange/StackExchange.Redis#1539]
System.NotImplementedException
  HResult=0x80004001
  Message=The ConnectionMultiplexer is not a Sentinel connection.
  Source=StackExchange.Redis
  StackTrace:
   在 StackExchange.Redis.ConnectionMultiplexer.GetSentinelMasterConnection(ConfigurationOptions config, TextWriter log) 在 /_/src/StackExchange.Redis/ConnectionMultiplexer.cs 中: 第 2362 行
   在 StackExchange.Redis.ConnectionMultiplexer.SentinelMasterConnect(ConfigurationOptions configuration, TextWriter log) 在 /_/src/StackExchange.Redis/ConnectionMultiplexer.cs 中: 第 1105 行
   在 StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) 在 /_/src/StackExchange.Redis/ConnectionMultiplexer.cs 中: 第 1037 行

**Comment by gxlqssjf** [comment]
the code :
 var objectPool = new Lazy<ObjectPool<T>>(() => new ObjectPool<T>(() =>
                      {
                          var point = string.Format("{0}:{1}", info.Host, info.Port);
                          var redisClient = ConnectionMultiplexer.Connect(new ConfigurationOptions()
                          {
                              EndPoints = { { info.Host, int.Parse(info.Port) } },
                              ServiceName = point,
                              Password = info.Password,
                              ConnectTimeout = connectTimeout,
                              AbortOnConnectFail = false
                          });
                          return redisClient.GetDatabase(info.DbIndex) as T;
                      }, info.MinSize, info.MaxSize));
/// <summary>
        /// 构造一个对象池
        /// </summary>
        /// <param name="func">用来初始化对象的函数</param>
        /// <param name="minSize">对象池下限</param>
        /// <param name="maxSize">对象池上限</param>
        public ObjectPool(Func<T> func, int minSize = 100, int maxSize = 100)
        {
            Check.CheckCondition(() => func == null, "func");
            Check.CheckCondition(() => minSize < 0, "minSize");
            Check.CheckCondition(() => maxSize < 0, "maxSize");
            if (minSize > 0)
                this.minSize = minSize;
            if (maxSize > 0)
                this.maxSize = maxSize;
            for (var i = 0; i < this.minSize; i++)
            {
                this.queue.Enqueue(func());
            }
            this.currentResource = this.minSize;
            this.tryNewObject = this.minSize;
            this.func = func;
        }

**Comment by DanAtkinson** [comment]
I can't see the hosts or ports you're trying to connect to but can I assume they are **26379**, rather than 6379?

**Comment by czd890** [comment]
```C#
new ConfigurationOptions(){
    //ServiceName = point, // Please remove this.
}
```

**Comment by Victor-Tseng** [comment]
It looks that your host/port points to a Master or Slave node. And when you specify `ServiceName` it will connect in Sentinel mode which your host/port must point to one or more sentinels. In Sentinel mode the driver will connect to the sentinel(s) to find the current Master first, and then connect and return the connection to Master to you.

You might revise your code depends on which mode you want to use.

**Comment by NickCraver** [comment]
Advice is correct above, you'll want to remove `ServiceName` here to get working - closing out to cleanup!
