### ISSUE TITLE
await StringGetAsync

### ISSUE THREAD

**Issue by gitetl2016** [StackExchange/StackExchange.Redis#1540]
hi,

is below the correct interface to :

1) construct a List of RedisKey type keys
2) pass this List of Keys to StringGetAsync as input parameter
3) capture the results in a RedisValue[] array, as fed back by StringGetAsync library
4) return RedisValue[] array  to the calling method

In my requirement, these steps should happen sequentially with 2nd one being an Asynchronous library function. 

Scenario is as follows:

```cs
private static async Task<RedisValue[]> GetMeValuesForMyKeys  (DataTable table)
{
var batch = new List<RedisKey> (100);

for (i = 0; i<table.Rows.Count; i++)
{
DataRow row = table.Rows[i];
batch.Add(row["keyColumn"].ToString () );
}

RedisValue[] arryOfValuesReceived = await db.StringGetAsync(batch.ToArray() );
return arryOfValuesReceived 
}
```

Calling Method:
```cs
RedisKeyValue[]  arryOfValuesReceived = await GetMeValuesForMyKeys (Datatable table);
```
----------------------------------------

Question1: Is my understanding correct that 'return arryOfValuesReceived ' instruction will wait for all keys to have been successfully fed back by StringGetAsync because of 'await' restriction? Which means, the last two program instructions should happen sequentially (blocking scenario). And if so, this is my desired behavior as well, as I need full list of Values corresponding to my Keys, before proceeding.

Question2: However, even with above 'await' setup, arryOfValuesReceived  is noticed as having all nulls (though there are keys i know are present in Redis and thus am expecting a non-null array as return value)

May I know the correct invocation of StringGetAsync, which could be the root cause of nulls for arryOfValuesReceived  ?  thank you

**Comment by NickCraver** [comment]
What you have looks like it should behave correctly, given `row["keyColumn"].ToString()` is what you think it is and the keys are there. Are you sure you're on the right database, and that the keys are what you think they are here? I'd debug dump and be checking in redis-cli. Also: be sure they're actually strings and not some other type in Redis.

**Comment by gitetl2016** [comment]
thanks Nick. I am experimenting with a small set of 3 row csv file.  I see my 3 key column values. This csv file is later is getting converted to datatable in the program. And, one of these 3 keys is confirmed as being present in Redis and other two not, using Keys * command on the console.   Also, get X of my key column is retrieving the corresponding value, as seen from the console.  But, when tried the same logic through Async programming sampled in the previous post, its not retrieving the value.

An interesting observation is made. When I put a breakpoints on both await and the return statements below, and try to evaluate one of the retrieved values as arryOfValuesReceived[0].ToString() under Add-Watch,  it is noticed that the program control is not coming to return statement.  The last successful instruction seen is the line where await is coded.

`RedisValue[] arryOfValuesReceived = await db.StringGetAsync(batch.ToArray() );
return arryOfValuesReceived`

 Could you please advise how to debug the dump or is it that the above two lines need to be revisited, thank you.

**Comment by gitetl2016** [comment]
It looks like the main UI thread is terminating before the task StringGetAsync completes.  This possible root cause was confirmed by putting a Console.Readkey () in the method that makes a call to method holding StringGetAsync functionality.  

thank you
