### ISSUE TITLE
[TimeOutExceptions]   Lazy<ConnectionMultiPlexer>

### ISSUE THREAD

**Issue by TLA020** [StackExchange/StackExchange.Redis#1542]
Hi Guys,

_Everything running @ Azure app service windows + Azure Redis Cache_

We used to have no problems, but now that more services started using our redis cache we noticed some strange behavior.
Right after the appService starts running everything works fine. But after a couple of minutes (if lucky) the appservice crashes "unavailable" or we see timeout exceptions coming from redis (as shown bottom of this post)

I started reading about this issue, and saw alot of people with the same problems, but no fixes.
I've tried different versions of the packages to see if it was an issue with my current version.

After that i've read the documentation and articles about how the ConnectionMultiplexer should be used as a singleton or as a static class to share the instance with all other services, to prevent to many open connections / concurrency issue.
This change did reduce my open connections but didn't solve the problem.

I've tested alot of examples.. but nothing worked out.

**This is my current implementation:**

```
public class RedisConnectionFactory 
{
    private static readonly Lazy<ConnectionMultiplexer> LazyConnection;

    static RedisConnectionFactory()
    {
        LazyConnection = new Lazy<ConnectionMultiplexer>(() => ConnectionMultiplexer.Connect(Startup.StaticConfig.GetValue<string>("RedisServer")));
    }

    public static ConnectionMultiplexer Connection => LazyConnection.Value;

    public static IDatabase Database => Connection.GetDatabase();
}
```

**And used in my services like:**

 ```
public class ArticleCacheService : IArticleCacheService
{
    private readonly ILogger<ArticleCacheService> _logger;
    private readonly IDatabase _redis;

    public ArticleCacheService(ILogger<ArticleCacheService> logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _redis = RedisConnectionFactory.Database;
    }

    public async Task<List<Article>> GetArticles(string key)
    {
        var value = await _redis.StringGetAsync(key);

        if (string.IsNullOrWhiteSpace(value)) 
        {
            _logger.LogInformation($"No cache for key: {key}");
            return null;
        }

        _logger.LogInformation($"Cache returned for key: {key}");
        return JsonConvert.DeserializeObject<List<Article>>(value);
    }

    public async Task SetArticles(string key, List<Article> articles)
    {
        var jss = new JsonSerializerSettings
        {
            ReferenceLoopHandling = ReferenceLoopHandling.Ignore
        };

        var serialized = JsonConvert.SerializeObject(articles, jss);

        _logger.LogInformation($"Cache set for: {key}");

        await _redis.StringSetAsync(key, serialized, new TimeSpan(0, 30, 0));
    }
}
```

**2 of the exceptions:**

![image](https://user-images.githubusercontent.com/20934868/88847453-59a72c00-d1e7-11ea-8397-e9dbaade16ff.png)

_The timeout was reached before the message could be written to the output buffer, and it was not sent, 
command=GET, 
timeout: 5000, 
outbound: 0KiB, 
inbound: 0KiB,
 active: GET GetArticles, 
next: GET getArticlesByCity-$8689, 
inst: 0,
 qu: 1,
 qs: 17,
 aw: True, 
bw: Inactive,
 rs: ComputeResult,
 ws: Writing, in: 0, 
serverEndpoint: 
private.redis.cache.windows.net:6380,
 mc: 1/1/0,
 mgr: 7 of 10 available,
 clientName: private,
 IOCP: (Busy=0,Free=1000,Min=1,Max=1000),
 WORKER: (Busy=3,Free=8188,Min=1,Max=8191),
 v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)_

Thanks in advance.

T.

**Comment by TLA020** [comment]
Nobody?

**Comment by NickCraver** [comment]
Missed this one - the weird thing about your error is the state is in `ComputeResult`, which signals something very strange or expensive in a prior fetch. Is it possible something else expensive to compute or generally huge is on the wire?

**Comment by NickCraver** [comment]
We've improved connection logging here and exceptions from it (for everyone) - if anyone's still hitting connection issues please use the latest library to get both any connection improvements themselves, but also much better logging for diagnosing the issue.
