### ISSUE TITLE
StackExchange.Redis 1.2.6 is unable to connect using .NET Framework 4.5

### ISSUE THREAD

**Issue by ankitsood07** [StackExchange/StackExchange.Redis#1546]
I need to use Azure Redis Cache in my Application built using .NET Framework 4.5.
So i created a console App in Framework 4.5 and installed compatible version 1.2.6 of StackExchange.Redis

Unfortunately, its not able to connect with Redis Cache.
However, If i change .NET Framework to 4.6 it starts working fine, keeping all code same.

Please help, as i can't change framework of my Web Application.
Below is my Code:
`

    class Program
    {
        static void Main(string[] args)
        {
            IDatabase cache = Connection.GetDatabase();
            
            string cacheCommand = "PING";
            Console.WriteLine("\nCache command  : " + cacheCommand);
            Console.WriteLine("Cache response : " + cache.Execute(cacheCommand).ToString());

            Console.ReadKey();
            lazyConnection.Value.Dispose();
        }

        private static Lazy<ConnectionMultiplexer> lazyConnection = new Lazy<ConnectionMultiplexer>(() =>
        {
            string cacheConnection = "mycache.redis.cache.windows.net:6380,password=mypassword,ssl=True,abortConnect=False";
            return ConnectionMultiplexer.Connect(cacheConnection);
        });

        public static ConnectionMultiplexer Connection
        {
            get
            {
                return lazyConnection.Value;
            }
        }
    }
`

**Comment by mgravell** [comment]
Ultimately, I'm going to say that this is a scenario covered by [this blog post](https://blog.marcgravell.com/2020/01/net-core-net-5-exodus-of-net-framework.html). In every real sense: .NET Framework 4.5 is obsolete; specifically, 4.5 has been dead for [over 4 years](https://devblogs.microsoft.com/dotnet/support-ending-for-the-net-framework-4-4-5-and-4-5-1/) (nearer 5).

Likewise, 1.2.6 of the library is obsolete.

I cannot and will not invest, out of my own free time, the **huge** effort required to support .NET 4.5 or 1.2.6. I hate to sound harsh: but it was terrible planning on (whoever runs the technical decisions there) to let yourself get into a state where you're dependent on a platform that has been dead for over 4 years. The only advice I can give you is: move to a newer platform (preferably .NET Core 3.1 or .NET 5), or accept that some things are now off limits to you as a consequence of those decisions.
