### ISSUE TITLE
Exception: ConnectionMultiplexer.Connect(configurationOptions)

### ISSUE THREAD

**Issue by pmtiesh** [StackExchange/StackExchange.Redis#1548]
Hi, I'm new in Redis implementation.
My projet is in .net 4.7 and implementing Redis by adding Nuget package Stack.Exchange.Redis v2.1.58.
Plesae find below code
---------------------------------------------------------------------
private static readonly ConnectionMultiplexer LazyConnection;

        static RedisStore()
        {
            var log = new System.IO.StreamWriter("C:\\Log.txt");
            var configurationOptions = new ConfigurationOptions
            {
                AbortOnConnectFail = false,
                EndPoints = { { "172.25.33.51", 6379 } }
                ,
                User = "administrator"
                ,
                Password = "abcd@1234"
                ,
                ConnectTimeout = 10000
                //EndPoints = { ConfigurationManager.AppSettings["RedisServerPort"] }                
            };

            //LazyConnection = new Lazy<ConnectionMultiplexer>(() => ConnectionMultiplexer.Connect(configurationOptions));
            LazyConnection = ConnectionMultiplexer.Connect(configurationOptions, log); --- At this line getting error.
        }

Please suggest what can be done to resolve this issue. I have tried to uninstall and install same package twice but not worked.
Error : 
message
![2020-08-07 at 4 05 52 PM](https://user-images.githubusercontent.com/30141496/89708930-d7fa8f80-d998-11ea-9769-82d0119601d6.jpeg)

Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, 
Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The 
located assembly's manifest definition does not match the assembly reference. (Exception 
from HRESULT: 0x80131040)

stacktrace
   at Pipelines.Sockets.Unofficial.Internal.Throw.InvalidOperation(String message) in 
/_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 16
   at Pipelines.Sockets.Unofficial.Helpers.AssertDependencies() in 
/_/src/Pipelines.Sockets.Unofficial/Helpers.cs:line 177
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions 
configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1030

**Comment by NickCraver** [comment]
This is unfortunately a common issue in the .NET Full Framework world - please see my post here on how to resolve! https://nickcraver.com/blog/2020/02/11/binding-redirects/
