### ISSUE TITLE
Is it okay to store and reuse the IDatabase object?

### ISSUE THREAD

**Issue by josh-endries** [StackExchange/StackExchange.Redis#1550]
Typically I store the multiplexer and call GetDatabase() every time I do something with Redis, as suggested in the basic usage doc, which from what I've read will likely always return the same object (but maybe not always?). Normally I only ever need to use one database ID on a server. So my question is:

Is it okay to _not_ store the multiplexer, and only store/reuse the IDatabase object?

**Comment by NickCraver** [comment]
You need to hold onto the multiplexer _so that it doesn't get disposed_ (and eaten by the garbage collector), but keeping a ref to the database: yep, absolutely fine!
