### ISSUE TITLE
pub/sub with ASP .NET Core BackgroundService

### ISSUE THREAD

**Issue by hey-red** [StackExchange/StackExchange.Redis#1552]
I have strange behavior with BackgroundService and StackExchange.Redis 2.1.58 

After 30-45min(randomly) app stop sending notifications without any exceptions. 
Through `redis-cli monitor` I can see that publish works fine.

Whats wrong with this code? Also, I make another app(simple console) and it works as expected.

netcoreapp3.1/Redis 6.0.6

```C#
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

using NotificationPublisher.Hubs;
using NotificationPublisher.Hubs.Notifications;

using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

using StackExchange.Redis;

namespace NotificationPublisher.Services
{
    public class NotificationBroker : BackgroundService
    {
        private readonly IHubContext<AppHub, IAppHub> _appHubContext;

        private readonly ILogger _logger;

        private readonly JsonSerializerOptions jsonOptions = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        };

        public NotificationBroker(
            IHubContext<AppHub, IAppHub> appHubContext, 
            ILoggerFactory loggerFactory)
        {
            _appHubContext = appHubContext;
            _logger = loggerFactory.CreateLogger(GetType());
        }

        private readonly string ServiceName = nameof(NotificationBroker);

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            _logger.LogInformation($"{ServiceName} is starting.");

            stoppingToken.Register(() =>
                _logger.LogInformation($"{ServiceName} background task is stopping."));

            ISubscriber sub = RedisConnection.Connection.GetSubscriber();

            // Subscribe to channels
            sub.Subscribe("PostAdded", async (channel, message) => {
                _logger.LogInformation($"PostAdded -> {message}");

                var notification = JsonSerializer
                    .Deserialize<PostChangedNotification>(message, jsonOptions);

                await _appHubContext.Clients
                    .Group(HubsConstants.APP_HUB)
                    .ReceivePost(notification);
            });

            sub.Subscribe("PostDeleted", async (channel, message) => {
                _logger.LogInformation($"PostDeleted -> {message}");

                var notification = JsonSerializer
                    .Deserialize<PostChangedNotification>(message, jsonOptions);

                await _appHubContext.Clients
                    .Group(HubsConstants.APP_HUB)
                    .DeletePost(notification);
            });

            await Task.Delay(Timeout.Infinite, stoppingToken);

            _logger.LogDebug($"{ServiceName} is stopping.");
        }
    }
}
```

**Comment by capomafiosoken** [comment]
Hi! Instead of storing `sub `object, try to rewrite it like `Redis.Connection.GetSubscriber().Subscribe(...)`.

**Comment by hey-red** [comment]
Hmm, it seems to be work with test app. Thank you 👍

**Comment by pawelkosi** [comment]
@hey-red Hi Mate!

I am learning about what you are essentially doing here. Would you be willing to share the rest of your code (link to repo maybe) so I can understand better how your app works and learn from it?

**Comment by hey-red** [comment]
@pawelkosi  
Hello! I'm use redis as message broker. So, my legacy app need to be send some notifications to clients throught signalr. 
I wrote small example: https://github.com/hey-red/SignalRNotificationExample

`NotificationSender -> NotificationBroker -> SignalR clients/etc`

NotificationSender is simple console app that publish notifications to redis channel. [NotificationBroker](https://github.com/hey-red/SignalRNotificationExample/blob/master/NotificationBroker/Services/NotificationBroker.cs) subscribes to redis channel, read notifications and sends it to signalr clients.
Example does not contains web part, but you can take examples from signalr docs. Also, sender and broker make logs to console, so web part is not really needed.

**Comment by pawelkosi** [comment]
> @pawelkosi
> Hello! I'm use redis as message broker. So, my legacy app need to be send some notifications to clients throught signalr.
> I wrote small example: https://github.com/hey-red/SignalRNotificationExample
> 
> `NotificationSender -> NotificationBroker -> SignalR clients/etc`
> 
> NotificationSender is simple console app that publish notifications to redis channel. [NotificationBroker](https://github.com/hey-red/SignalRNotificationExample/blob/master/NotificationBroker/Services/NotificationBroker.cs) subscribes to redis channel, read notifications and sends it to signalr clients.
> Example does not contains web part, but you can take examples from signalr docs. Also, sender and broker make logs to console, so web part is not really needed.

You are a star!!! Thank you soo much for taking your time and setting this little demo - I love your solution and I will learn a lot from it!

Cheers!
