### ISSUE TITLE
Unable to INSERT into Bloom Filter with capacity declared 

### ISSUE THREAD

**Issue by RazmikGevorgyan** [StackExchange/StackExchange.Redis#1553]
StackExchange.Redis Version 2.1.58
RedisBloom release version v2.2.4

I am trying to insert an item with the stated capacity, but I get an exception

**exceptionMessage**

 `StackExchange.Redis.RedisServerException: 'Bad capacity' `exception

**how to reproduce** 

       ```
     var configuration = ConfigurationOptions.Parse("localhost:6379", true);
     configuration.SyncTimeout = 90000;
     configuration.AbortOnConnectFail = false;
      ConnectionMultiplexer redis = ConnectionMultiplexer.Connect(configuration);
      var database = redis.GetDatabase();
     var res =  await  database.ExecuteAsync("BF.INSERT", "filter", "CAPACITY 10", "ITEMS hello");
```

**Comment by mgravell** [comment]
That message is coming directly from the server, so it isn't a *library* exception as such; I expect what you need here is:

``` c#
 var res =  await  database.ExecuteAsync("BF.INSERT", "filter", "CAPACITY", 10, "ITEMS",  "hello");
```

I also suspect that for "cluster", you should use:

``` c#
 var res =  await  database.ExecuteAsync("BF.INSERT", (RedisKey)"filter", "CAPACITY", 10, "ITEMS",  "hello");
```

to ensure that the shard is picked correctly

**Comment by RazmikGevorgyan** [comment]
Thanks a lot works as expected
