### ISSUE TITLE
Seeing this on the connection logs from a .net 4.5.2 app with StackExchange.Redis.StrongName 1.2.6

### ISSUE THREAD

**Issue by dwaragesh-balakrishnan** [StackExchange/StackExchange.Redis#1560]
master.cluster.g.use1.cache.amazonaws.com:6379,connectTimeout=5000,password=*****,ssl=True,abortConnect=False
Connecting master.cluster.g.use1.cache.amazonaws.com:6379/Interactive...
BeginConnect: master.cluster.g.use1.cache.amazonaws.com:6379
1 unique nodes specified
Requesting tie-break from master.cluster.g.use1.cache.amazonaws.com:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=4,Free=32763,Min=4,Max=32767)
EndConnect: master.cluster.g.use1.cache.amazonaws.com:6379
Configuring SSL
All tasks completed cleanly, IOCP: (Busy=2,Free=998,Min=4,Max=1000), WORKER: (Busy=6,Free=32761,Min=4,Max=32767)
master.cluster.g.use1.cache.amazonaws.com:6379 faulted: InternalFailure on PING
All tasks are already complete
master.cluster.g.use1.cache.amazonaws.com:6379 failed to nominate (Faulted)
> UnableToResolvePhysicalConnection on GET
No masters detected
master.cluster.g.use1.cache.amazonaws.com:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Connecting; sub: Connecting; not in use: DidNotRespond
master.cluster.g.use1.cache.amazonaws.com:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, sync=1, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=2
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
Connect complete: master.cluster.g.use1.cache.amazonaws.com:6379
retrying; attempts left: 2...
1 unique nodes specified
Requesting tie-break from master.cluster.g.use1.cache.amazonaws.com:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=3,Free=32764,Min=4,Max=32767)
All tasks completed cleanly, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=5,Free=32762,Min=4,Max=32767)
master.cluster.g.use1.cache.amazonaws.com:6379 faulted: InternalFailure on PING
All tasks are already complete
master.cluster.g.use1.cache.amazonaws.com:6379 failed to nominate (Faulted)
> UnableToResolvePhysicalConnection on GET
No masters detected
master.cluster.g.use1.cache.amazonaws.com:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: Connecting; not in use: DidNotRespond
master.cluster.g.use1.cache.amazonaws.com:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, sync=2, async=1, socks=3; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=3
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 1...
1 unique nodes specified
Requesting tie-break from master.cluster.g.use1.cache.amazonaws.com:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=5,Free=32762,Min=4,Max=32767)
All tasks completed cleanly, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=4,Free=32763,Min=4,Max=32767)
master.cluster.g.use1.cache.amazonaws.com:6379 faulted: InternalFailure on PING
All tasks are already complete
master.cluster.g.use1.cache.amazonaws.com:6379 failed to nominate (Faulted)
> UnableToResolvePhysicalConnection on GET
No masters detected
master.cluster.g.use1.cache.amazonaws.com:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
master.cluster.g.use1.cache.amazonaws.com:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, sync=3, async=2, socks=4; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=4
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Starting heartbeat...

**Comment by dwaragesh-mb** [comment]
Logs look fine from a .net core 2.1 app

**Comment by dwaragesh-balakrishnan** [comment]
This thing worked after explicitly adding the ssl protocols in the connection string

sslprotocols=tls12
