### ISSUE TITLE
Some way to Reproduce“No connection” exception

### ISSUE THREAD

**Issue by bealren** [StackExchange/StackExchange.Redis#1561]
our team find some way to reproduce "No connection" exception。
       

1. write a timer，loop every second to send command，just like:
`private static void OnTimedEvent(Object source, ElapsedEventArgs e)
        {
            try
            {
                if (!rh.IsConnected())
                {

                    Console.WriteLine("连接失败!"+ Spid.ToString());
                    LogHelper.WriteLog(Enumerate.CodeType.Code001, Enumerate.NLogType.Error, "连接失败!"+ Spid.ToString());
                }
                Random rd = new Random();
                rh.StringSet("dataKey_" + rd.Next(0, 120).ToString(), "model", new TimeSpan?(TimeSpan.FromDays(1.0)));
            }
            catch (Exception ex)
            {
                if(ex.Message.Contains("No connection") || ex.StackTrace.Contains("No connection"))
                {
                    string msg = string.Format("Redis设置Key-Value时异常。spid：" + Spid.ToString());
                    LogHelper.WriteLog(Enumerate.CodeType.Code001, Enumerate.NLogType.Error, msg, ex);
                }
                
            }
        }`

2. use cmd open about 100 exe，like “start D:\Debug\redistest.exe”；
3. open redis-cli.exe，connect to server，then send command “client pause 5000”，pause 5 seconds or longer，After 5 seconds, some programs cannot reconnect normally, and continue to report connection failure, and the exception message is “No connection “
@NickCraver

**Comment by bealren** [comment]
There is another way to reduce the redis maxclients setting. I tried to change it to 10, which makes it easier to trigger, but I don’t know if these two exceptions are the same.

**Comment by bealren** [comment]
By the way, I have reproduced on win7 and win2008, but not on win10; I use StackExchange 1.2.6

**Comment by bealren** [comment]
exception like this:
`[3,"StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: SETEX dataKey_16; SocketFailure on 127.0.0.1:10000/Interactive, origin: CheckForStaleConnection, input-buffer: 0, outstanding: 6, last-read: 1s ago, last-write: 0s ago, unanswered-write: 1s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: RecordConnectionFailed_ReportFailure, err: never; IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=6,Free=2041,Min=4,Max=2047), Local-CPU: n/a ---> StackExchange.Redis.RedisConnectionException: SocketFailure on 127.0.0.1:10000/Interactive, origin: CheckForStaleConnection, input-buffer: 0, outstanding: 6, last-read: 1s ago, last-write: 0s ago, unanswered-write: 1s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: RecordConnectionFailed_ReportFailure, err: never   --- 内部异常堆栈跟踪的结尾 ---   在 StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)   在 StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)   在 StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable`1 expiry, When when, CommandFlags flags)   在 redistest.TestThread.OnTimedEvent() 位置 E:\\OpenSource\\Redis\\redis测试\\redistest\\redistest\\TestThread.cs:行号 117"]`

**Comment by Gevil** [comment]
The way I managed to repro this was that I disabled my ethernet adapter with a quick batch script for just a second then turned it back on.

**Comment by bealren** [comment]
> The way I managed to repro this was that I disabled my ethernet adapter with a quick batch script for just a second then turned it back on.

How did you solve this problem?

**Comment by NickCraver** [comment]
This has been refactored quite a bit since opening (but we also do not support the 1.2.6 release any longer) - if you can great 2.2.50+ then we're certainly curious! The connect code has been further hardened in this release and this should no longer be an issue :)

**Comment by NickCraver** [comment]
Going to close out to tidy, but if you can repro a bad case on latest, will re-open!
