### ISSUE TITLE
NRedisearch : Add support for RediSearch 2.0

### ISSUE THREAD

**Issue by tgrall** [StackExchange/StackExchange.Redis#1562]
RediSearch 2.0 is close to GA and NRedisearch should be updated to support this new version and associated commands:

* https://github.com/RediSearch/RediSearch/releases

For example:
* FT.CREATE : new way to create index
* FT_LIST
* FT.DROPINDEX

**Comment by gkorland** [comment]
https://github.com/StackExchange/StackExchange.Redis/pull/1544

**Comment by mgravell** [comment]
@gkorland  that PR is still draft; is it ready for merge? also, it looks like it only covers a very small part of the above - is this citation mostly for cross-reference?

**Comment by gkorland** [comment]
@mgravell I guess now the #1544 was merged and release we can close this issue
