### ISSUE TITLE
RedisDatabase.SetPop() return an array with one element when the set is empty 

### ISSUE THREAD

**Issue by kk19371** [StackExchange/StackExchange.Redis#1564]
var result =SetPop("oneSetKey", 1);
when the "oneSetKey" is not exist or has no members, the code above will get array result with one element in it(I think this incorrect, the result should has no element).
![image](https://user-images.githubusercontent.com/28782699/91962787-9d89d580-ed3f-11ea-9192-5d50bac58634.png)

but below code will get array result with 0 element in it(I think this is right)：
var result=SetPop("oneSetKey", 2);
![image](https://user-images.githubusercontent.com/28782699/91963055-ef326000-ed3f-11ea-9e20-4fa3a1ad96c4.png)

**Comment by kk19371** [comment]
The same issue with SetPopAsync()

**Comment by NickCraver** [comment]
Indeed there's nil in both cases, the difference is in the `RedisValueArrayProcessor`:
```cs
                    case ResultType.BulkString:
                        var arr = new[] { result.AsRedisValue() };
                        SetResult(message, arr);
                        return true;
                    case ResultType.MultiBulk:
                        arr = result.GetItemsAsValues();
                        SetResult(message, arr);
                        return true;
```
So in the single case, with a `nil` reply, we are sticking it in an array. I'm not sure that's ever valid - @mgravell should we change this up to look for nil and return an empty array in that case? Happy to PR or review if so (getting late here, or I'd PR a test tonight).

**Comment by kk1937** [comment]
Hi, guys, any update on this?

**Comment by NickCraver** [comment]
Opened a PR for this in #1993, had to dig on each command but agree it should be tweaked!
