### ISSUE TITLE
KeyExpire's DateTime expiry is affected by LocalTime and test case failed

### ISSUE THREAD

**Issue by neuecc** [StackExchange/StackExchange.Redis#157]
I found KeyExpire's DateTime expiry is affected by LocalTime.

```csharp
var conn = ConnectionMultiplexer.Connect("127.0.0.1");
var db = conn.GetDatabase();
db.StringSet("test", 1);
db.KeyExpire("test", DateTime.Now); // my culture is ja-jp, +9:00
Console.WriteLine(db.KeyTimeToLive("test")); // 08:59:59.9950000
```

It come from `(when - RedisBase.UnixEpoch).Ticks`.
https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis/StackExchange/Redis/RedisDatabase.cs#L1605

I think change to `when.ToUniversalTime() - RedisBase.UnixEpoch` is good.

and test case failed in my environment at "utc = false".
https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis.Tests/Expiry.cs#L80

May need to change the test case to work in any local time.

**Comment by mgravell** [comment]
Dammit. There's times when living in GMT half the year is a real pain. Date
and time code is the main one.

**Comment by mgravell** [comment]
This is now merged; thanks
