### ISSUE TITLE
Large numbers of timeout exceptions

### ISSUE THREAD

**Issue by YusufUsmani** [StackExchange/StackExchange.Redis#1570]
Hi,

I am using Stack Exchange Redis with AZURE Redis in my solution and getting a lot of timeouts and my understanding is these timeouts due to a large number of operations in the "Queue-Awaiting-Write". Following are the example

StackExchange.Redis.RedisTimeoutException: Timeout performing HMGET (5000ms), inst: 0, qu: 18058, qs: 0, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: TestingServerEndpoint, mc: 1/1/0, mgr: 10 of 10 available, clientName: VTSP14-A, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767), v: 2.1.30.38891 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl
at StackExchange.Redis.RedisBase.ExecuteSync
at StackExchange.Redis.RedisDatabase.HashGet
at RedisCommon.RedisCacheProvider.GetHashSeFieldValuesByFieldNamesForValuesStoredAsByteArray

StackExchange.Redis.RedisTimeoutException: Timeout performing HVALS (5000ms), next: PSETEX TestingKey, inst: 8, qu: 49707, qs: 1, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: TestingServerEndpoint, mc: 1/1/0, mgr: 10 of 10 available, clientName: VTSP03-A, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=5,Free=32762,Min=8,Max=32767), v: 2.1.30.38891 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl
at StackExchange.Redis.RedisBase.ExecuteSync
at StackExchange.Redis.RedisDatabase.HashValues
at RedisCommon.RedisCacheProvider.GetAllHashSetFieldValuesAreByteArray

My application server is in NewZealand and Azure Server is in East Australia as the Azure datacenter is not available in Newzealand right now. My solution is in .net4.8. Network traffic between both servers seems not overwhelmed and CPU Consumption is not more than 1%. I am using to Sync methods of the library. 

I thought to overcome this large number of  "Queue-Awaiting-Write" in timeout by moving implementation is to async implementation. I converted all hierarchy to async code but these async methods seem to hang indefinitely without giving error or result,

please suggest about both timeout and async method hanging as we need to shift code to async.

**Comment by YusufUsmani** [comment]
StackExchange.Redis NuGet version: 2.1.30.

**Comment by gkorland** [comment]
@YusufUsmani  did you manage to overcome the issue?

**Comment by YusufUsmani** [comment]
@gkorland, Thanks for your response. No I am not able to sort the issue.

**Comment by NickCraver** [comment]
What call pattern to you have writing to Redis? Is it possible something is writing a _lot_ of ops to Redis that are about to be executed? It looks like 18-50k operations are written in a hurry to the queue so it'd be helpful to understand what's feeding into that queue. Can you share where those tens of thousands of operations are coming from, and possibly quantify how quickly they're being added?

**Comment by YusufUsmani** [comment]
Hi @NickCraver, Sorry for the late response. Previously, my application server was in New Zealand and the Redis server was in Australia and my understanding was that may be queue count increases due to network lag, so I moved the Redis server to my data center but it doesn't improve things a lot.

My application stores calendar information and we show a diary for each day in our application. Users can book appointments on these diaries, make them unavailable for booking, make them available for booking and user can cancel booked appointments as well. We saved all this information in the SQL server but due to the high volume of calls, we start caching computed data in Redis and return data on request, if Redis does return data we get data from the database.

I am saving dairy data in Hash set as one day is distributed among different slots and above-defined action get done across these slots

Following actions on Redis

In case of diary change, we delete cache entry and reload value from the database on next request.

Mark slot unavailable/available/ book appointment/ cancel appointment . we get the slot information from HashSet and update the slot in HashSet.

Please suggest,

**Comment by NickCraver** [comment]
@YusufUsmani also missed your reply here (sorry, so many notifications) - your description sounds like there aren't that many operations going against Redis, but the error message you showed had 18,000 pending in queue and these appear to be multi-gets as well. When you show a diary is it doing `n` operations? It seems like those are really piling up sometimes, or some background job with a tight loop is.

**Comment by NickCraver** [comment]
If there's more info here, happy to re-open - going to tidy up for now.
