### ISSUE TITLE
Lua script evaluation resulting array doesn't contain all members

### ISSUE THREAD

**Issue by rantrave-git** [StackExchange/StackExchange.Redis#1571]
## Description
Trying to evaluate lua script which returns array that has multiple elements doesn't success with all members after call `RedisResult.ToDictionary()`

## Steps to reproduce
```c#
// inside an async function
var multiplexer = ConnectionMultiplexer.Connect("redis:6379");
var db = multiplexer.GetDatabase(1);
await db.StringSetAsync("last", "t0");
await db.StringSetAsync("t0:s", "true");

var script = "local l=redis.call('get','last')\nlocal r={}\nr[1]=redis.call('get',l..':s')\nr[2]=l\nreturn r";
var q = LuaScript.Prepare(script);

var result = await db.ScriptEvaluateAsync(q);

Console.WriteLine(result);
Console.WriteLine(String.Join(",", result.ToDictionary().Keys));
```
Output:
```
2 element(s)
true
```

## Expected behavior
```
2 element(s)
true,t0
```
Executing redis-cli with same commands completes properly:
```
127.0.0.1:6379> set last t0
OK
127.0.0.1:6379> set t0:s true
OK
127.0.0.1:6379> eval "local l=redis.call('get','last')\nlocal r={}\nr[1]=redis.call('get',l..':s')\nr[2]=l\nreturn r" 0
1) "true"
2) "t0"
```

## Additional information
- Dotnet version: dotnet core 3.1.402
- StackExchange.Redis version: 2.1.58
- Redis version: 6.0.8

**Comment by eduardobr** [comment]
The ToDictionary() method has this description:
"Interprets a multi-bulk result with successive key/name values as a dictionary keyed by name"

So the list of keys in the collection { "true", "t0" } is correctly returning { "true" } in your case.

**Comment by rantrave-git** [comment]
What exactly "name" is in this case. And how it's supposed to get multiple results from lua dictionary?

**Comment by mgravell** [comment]
That message needs improving - the "by name" is just wrong; what it is trying (poorly) to convey is that given data [a,b,c,d,e,f,g,h] it creates the map {a=b,c=d,e=f,g=h}, so: interleaved key/value pairs. Because this is a common response format from redis.

In your case, you're not returning the keys *at all*, so it doesn't make sense to try and enumerate the keys that you aren't returning

**Comment by rantrave-git** [comment]
Correct me if I'm wrong, redis lua has no data structure as list, it's a dictionary with integer keys (and may even be not successive) so expected common response of redis is `{0: true, 1: t0}`.

**Comment by rantrave-git** [comment]
Problem I guess is in double conversion: `lua table -> redis multi-bilk -> dictionary` that gives no way to map lua table to dictionary as is.

**Comment by mgravell** [comment]
> Correct me if I'm wrong, redis lua has no data structure as list,

you're not wrong *as far as Lua goes*, but: the moment you `return r`  we're *not talking about Lua any more*; instead, the Lua object is translated into a RESP primitive (RESP being the redis data protocol), and in this case: it becomes a RESP array, which is *just* the values. The original array keys are not considered.

So; the library received *just* the values.

You can see this by using redis-cli to execute your Lua.

**Comment by mgravell** [comment]
corollary: if you want to have the keys *at the client*, then you need to interleave the keys *in the array*, i.e. `[key0, value0, key1, value1]`

**Comment by rantrave-git** [comment]
Well, I've figured how this works. Description of method requires little clarification and on my method with sequence of conversions `lua->redis->c#` seems counterintuitive, but i don't see any better solution. (Also #1471 fixed problem that prevented me to figure this out at the moment). Thanks for response.

One thing's still looking strange: exceptional situation with non even size of multi-bulk result (`int i = 0; i < arr.Length; i += 2` and `arr[i + 1]` causes out of range?).

**Comment by NickCraver** [comment]
Not sure which multi-bulk you're talking about here but some aren't even. They have have a count at the end, etc. - please refer to the https://redis.io/commands/ docs to see an example of the return for each command if you're processing it manually, it'll have an example of what the return looks like.

**Comment by NickCraver** [comment]
Closing this out to tidy up!
