### ISSUE TITLE
Is planned version for .NET 4.8 and support redis 6 new features?

### ISSUE THREAD

**Issue by lgcardonanet** [StackExchange/StackExchange.Redis#1575]

**Comment by mgravell** [comment]
Hi; it is very unlikely that we'd do a .NET 4.8 specific build, but the existing builds should *already work* on .NET 4.8 (the `net472` target should apply to `net48`); if it doesn't work: please let me know **exactly** what you're seeing.

Re redis 6 features; what specific features are you after?

- the ability to log in with a username and password for ACL support: is "in" and has been for some time
- the existing TLS support should work fine with redis 6
- the changes required to work with cluster-proxy (not officially redis 6, but related): are in

I have *not* looked at the `STRALGO` command family. For now, it should be usable with the ad-hoc command support.

Anything else?

**Comment by janek-lopez** [comment]
> Anything else?

I'd love to see server-assisted client side caching

**Comment by lgcardonanet** [comment]
No thanks

**Comment by NickCraver** [comment]
Answered here - if there are specific commands/features you'd like support for, please open issues on each so they can be reasonably tackled - we don't need to do one big bang release (which is hard time allocation wise) to get them in. PRs of course welcome on individual things like that (big bangs are also hard to review).
