### ISSUE TITLE
StringSetAsync with When.NotExists returns false when key doesn't exist

### ISSUE THREAD

**Issue by thelgevold** [StackExchange/StackExchange.Redis#1578]
I am using StackExchange.Redis with a replica cluster (3 nodes) configured to use Sentinel. 

I get multiple requests trying to update the cache with the same data, so to avoid multiple writes, I am using `When.NotExists` in `StringSetAsync`. My understanding is that this will prevent the set from happening if the key already exists. I am expecting `StringSetAsync` to only return true in cases where the set actually happened.

Example:

```
var inserted = await connectionMultiplexer.GetDatabase().StringSetAsync("my-key", "my-value", myTimeout, When.NotExists);

if(inserted == false)
{
  var keyExists = await connectionMultiplexer.GetDatabase().KeyExistsAsync("my-key");
  if(keyExists == false)
  {
    // I end up here, which I assumed should not happen. 
  }
}

```

To my surprise I am seeing that `StringSetAsync` returns false even if the key didn't already exist based on the sanity check where I manually check for the existence of the key.

Notes:
My environment uses 2 replica nodes and one primary. 
StackExchange.Redis ver: 2.1.58

**Comment by v0l** [comment]
Same issue in `2.2.4`

**Comment by v0l** [comment]
Using this for now:

```csharp
var result = await db.ExecuteAsync($"SET", Key, "NX", "PX", (long)(Expire ?? TimeSpan.FromSeconds(5)).TotalMilliseconds);
return (string)result == "OK";
```

**Comment by NickCraver** [comment]
I'm trying to reproduce this locally but am unable in any version (and going back) - adding some tests #1943 but still not able to repro this. I'm wondering if it's somehow specific to a Redis server version - any chance anyone hitting this can relay which version they're on? The only difference in issued commands vs. `"SET", Key, Value, "NX", "PX", (long)(Expire ?? TimeSpan.FromSeconds(5)).TotalMilliseconds` is the ordering, where the one issued by the lib has `NX` moved to the end. I wonder if a specific Redis server had an issue with that?

**Comment by thelgevold** [comment]
Unfortunately I no longer have access to this setup. The only detail I remember is that it didn't reproduce locally in a single node redis installation running in Docker. I only saw it when hitting a remote cluster with replicas (3 node cluster in k8). 

Could be related to server version as you say... From what I recall I was using a HA Helm installation of redis in K8, but can't remember which version of it.

**Comment by v0l** [comment]
The setup i was using was just a plain Redis cluster on Ubuntu VM's. I believe the version was in the 5.0 release. Maybe @pduffy50b can answer what version it was in STG env.

**Comment by NickCraver** [comment]
Given we can't repro this, I'm going to close out but if we have any more information that allows us to dig more, happy to reopen and hopefully we can figure out what environmental difference is in play here.

**Comment by joerneu** [comment]
@NickCraver  I can reproduce it:
```
value = db.StringGet(TestKey);
Console.WriteLine($"Value: {(value == null ? "n/a" : value)}");
if (db.StringSet(TestKey, value, TimeSpan.FromSeconds(10), When.NotExists, CommandFlags.DemandMaster))
    Console.WriteLine("Key set");
else
    Console.WriteLine("Key not set");
value = db.StringGet(TestKey);
Console.WriteLine($"Value: {(value == null ? "n/a" : value)}");
```
displays in Console:
```
Value: n/a
Key not set
Value: n/a
```
If I remove `StringGet()` it works as expected.

With a direct Redis connection it works as expected as well:
```
GET test3
$-1
SET test3 "Hello" NX
+OK
GET test3
$5
Hello
```
Redis ver. 5.0.13 (Docker) / StackExchange.Redis: 2.5.43

**Comment by joerneu** [comment]
@NickCraver Never mind my last comment. The issue was setting the value to an empty string.

**Comment by pduffy50b** [comment]
> The setup i was using was just a plain Redis cluster on Ubuntu VM's. I believe the version was in the 5.0 release. Maybe @pduffy50b can answer what version it was in STG env.

Redis server v=5.0.7
