### ISSUE TITLE
Are there any methods or extensions libraries to invoke BZPOPMIN command?

### ISSUE THREAD

**Issue by ram62836** [StackExchange/StackExchange.Redis#1581]
Hi There,

Please let me know if there are any inbuilt methods or library extensions exists to invoke BZPOPMIN command.

Thanks

**Comment by NickCraver** [comment]
There are none I know of, but these also explicitly haven't been added due to their blocking nature. I've opened #1593 as an request for these to discuss :)

**Comment by NickCraver** [comment]
Closing out, in favor of #1593 here.
