### ISSUE TITLE
Support enum for Lua Scripting parameters

### ISSUE THREAD

**Issue by daniloak** [StackExchange/StackExchange.Redis#1587]
Hi, is it possible to add support to allow send enums as parameters to the lua scripts? 
Now I am obliged to convert my enum property to int only to send to lua when I am calling 
`ScriptEvaluateAsync(LuaScript.Prepare(script), redisParameters)`

**Comment by mgravell** [comment]
In principle I'm fine with it, but if Dapper has taught me anything, it is that the moment we do this, we'll have "team integer" and "team string", competing for which way it should translate. This gives me some pause.

**Comment by daniloak** [comment]
you have a point, I wasn't thinking about it because I was "team integer". another suggestion would be to send the parameters in json, but this would required more effort to develop

**Comment by NickCraver** [comment]
Since this hasn't come up again and there's the split Marc's talking about - going to close this one out to tidy up :)
