### ISSUE TITLE
Client library inherits thread scheduler, instead of forcing thread pool scheduler.

### ISSUE THREAD

**Issue by turowicz** [StackExchange/StackExchange.Redis#159]
So, I've got some TPL + TPL Dataflow code that requires redis to do it's thing.

The code starts off by creating its own task factory based on ConcurrentExclusiveSchedulerPair (TPL). The concurrency is set to 1 in debug, and to 100 in release. Every task created on that scheduler will be doing some work + talking to redis.

After a couple of SE.Redis lib updates the debug version stopped working. Incrementing the concurrency to 2 in debug made it work again. This means that the SE.Redis library is fireing off new threads in an inherited (DEFAULT) task factory / task scheduler, instead of forcing the work to be scheduled by the thread pool scheduler.

Does this make any sense? I think SE.Redis should work on thread pool and ignore the inherited schedulers.

**Comment by turowicz** [comment]
Pull request https://github.com/StackExchange/StackExchange.Redis/pull/160 #160

**Comment by turowicz** [comment]
Can someone have look at the PR and tell me if I didn't miss anything about the threading in SE.Redis?

**Comment by mgravell** [comment]
Makes sense; multiple and competing schedulers is always going to be
problematic; this side-steps in neatly.

On 13 February 2015 at 11:43, Wojtek Turowicz <notifications@github.com>
wrote:

> Can someone have look at the PR and tell me if I didn't miss anything
> about the threading in SE.Redis?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/159#issuecomment-74241921>
> .
>



-- 
Regards,

Marc
