### ISSUE TITLE
Stackexchange.redis causes memory to fail to GC

### ISSUE THREAD

**Issue by liuyl1992** [StackExchange/StackExchange.Redis#1603]
![image](https://user-images.githubusercontent.com/16396828/97269805-105b8c80-1869-11eb-8b79-5b4a9709b9a9.png)

 the memory rises very fast;
Stackexchange.redis version is 2.1.58

**Comment by liuyl1992** [comment]
redis causes memory to never drop;
when memory rises close to 1G, no matter how many times Set is requested memory changes are not noticeable

**Comment by mgravell** [comment]
To prevent constant allocations, RawResult buffers are leased from the
array pool. I *suspect* what I happening in your case is that you are
reading some big responses (something with lots of sub-contents, maybe
HGETALL for example), which is using some largish buffers.

Them not immediately being collected does *not* necessarily indicate a
problem, though. That is normal and expected, especially if the process
isn't under memory pressure. Unless you've deliberately constrained an exe
to run with minimal memory, the GC does not aggressively constantly prune
memory, so keeping around a buffer it needed previously: is normal.

Does the memory *grow* constantly? Also, I'd be interested in what
operations (and data sizes) you're running to get this result.

**Comment by NickCraver** [comment]
Without more info here - closing this out to cleanup.
