### ISSUE TITLE
Redis cluster - read from replica when master is down

### ISSUE THREAD

**Issue by plemanach** [StackExchange/StackExchange.Redis#1604]
Hello,

I have a redis cluster with 3 masters with 3 replicas.

I am using StackExchange version 2.0.601.

I observed the library won’t read from replicas when the master is down and the failover did not happen.

Is there any config that would allow this.

Best regards,

Patrice

**Comment by plemanach** [comment]
it is still try to connect to master which id down 

`ExceptionStack = [StackExchange.Redis.RedisConnectionException: UnableToConnect on 11.182.231.90:30591/Interactive, Initializing/NotStarted, last: INFO, origin: BeginConnectAsync, outstanding: 0, last-read: 5s ago, last-write: 5s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, last-mbeat: 0s ago, global: 0s ago, v: 2.0.601.3402
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.KeyExists(RedisKey key, CommandFlags flags)
   at Rbs.Gbm.Mdx.Cache.Redis.CacheService.IsKeyExists(String key) in D:\BuildAgent\4\work\55cc9b255c286d39\source\CoreServer\Rbs.Gbm.Mdx.Cache.Redis\CacheService.cs:line 53]`

**Comment by mgravell** [comment]
`Exists` doesn't demand the primary, so it *should* (by default) work in "prefer master" mode, meaning: if it knows about the replicas, it *should* be fine to use them; this would require some investigation to figure out why it isn't selecting that - of a non-trivial (and "partially down") config, which makes it awkward.

Question: does it work if you explicitly specify `DemandReplica` or `PreferReplica`  ? (I'm not saying this is a desirable fix; I'm just trying to investigate the routing as best I can from here)

**Comment by plemanach** [comment]
> `Exists` doesn't demand the primary, so it _should_ (by default) work in "prefer master" mode, meaning: if it knows about the replicas, it _should_ be fine to use them; this would require some investigation to figure out why it isn't selecting that - of a non-trivial (and "partially down") config, which makes it awkward.
> 
> Question: does it work if you explicitly specify `DemandReplica` or `PreferReplica` ? (I'm not saying this is a desirable fix; I'm just trying to investigate the routing as best I can from here)

**Comment by plemanach** [comment]
I will give it a try, as additional information it behave like nothing happened and master was up and time to time 25% querying the replica.

**Comment by NickCraver** [comment]
Tidying up by closing out here - if there's a follow-up question, happy to re-open!
