### ISSUE TITLE
Information about the floating point precision for HashDecrementAsync method  

### ISSUE THREAD

**Issue by NTTLuke** [StackExchange/StackExchange.Redis#1607]
Hello 
I have one question related the HashDecrementAsync method behaviour.
StackExchange.Redis version 2.1.58 

I'm storing double number inside an Hash field with a key called "mykey" on Redis.
mydoublenumber : 10 

Then I use HashIncrementAsync method to decrement the number by 2.2

What I expect to find is 7.8 
What I see on redis is 7.7999999999999998

Using Redis CLI with following commands , the result is correct
```
HSET mykey mydoublenumber 10
HINCRBYFLOAT mykey mydoublenumber -2.2
"7.8"
```

Do you have some insight about that ?

I even saw that in StackExchange.Redis tests for HashDecrementAsync there is an approximation assert.
[Floating Point Test](https://github.com/StackExchange/StackExchange.Redis/blob/b0f21d3616c795ad994dd4151a5a556e9d1558b3/tests/StackExchange.Redis.Tests/FloatingPoint.cs#L88
)

Is it related to the behavior I mentioned and Is there a reason about that ? 

Thank you 
Luk3

**Comment by mgravell** [comment]
This sounds like simply floating point being floating point. You can use
the calculator here (https://www.h-schmidt.net/FloatConverter/IEEE754.html)
to see how close 2.2 can be represented in floating point - the error
observed is within that tolerance. I wonder if redis-cli is simply rounding
more aggressively?

**Comment by NTTLuke** [comment]
Hi @mgravell 

I got your point and I was just wondering why redis cli did this kind of strong approximation.
Maybe as you said cli just does a strong approximation.

Thanks for the clarification 
I will close the issue
