### ISSUE TITLE
Does  StackExchange.Redis support SSH Tunnel to connect redis server which is not publicly accessible?

### ISSUE THREAD

**Issue by mogra** [StackExchange/StackExchange.Redis#1608]
Does  StackExchange.Redis support SSH Tunnel to connect redis server which is not publicly accessible? 

Thank you.

**Comment by mgravell** [comment]
It your SSH tunnel is connected externally as a transparent tunnel that is established externally, then: it should work just as an opaque socket, and the fact that there is a tunnel should be invisible to the library - you would simply connect to the tunnel endpoint. Note that this won't work with cluster or sentinel, which negotiate *additional* connections. In this regard, there *should* be nothing additional needed from the library, and it *should* just work - but : let me know!

**Comment by mogra** [comment]
@mgravell Thank you for your prompt reply and your help. With ssh.net port forwording, I use Stackexchange.redis to connect the redis server behind the firewall. Easy and perfect.  

Thank you again.
