### ISSUE TITLE
Redis TimeoutException and the high qs parameters in the error message

### ISSUE THREAD

**Issue by ChesterZengJian** [StackExchange/StackExchange.Redis#1609]
The following is the error message
![image](https://user-images.githubusercontent.com/22461405/98921545-68062300-250c-11eb-90de-11375cb6436b.png)

The following is the server to the Redis-server Latency
![image](https://user-images.githubusercontent.com/22461405/98922068-fed2df80-250c-11eb-933f-cd9878bb2dda.png)

In my program, I use the `set`, `zadd`, `zrangebyscore`, `mget` commands. And I just see a `mget 100 arguments`  command in the  `slowlog`.

Any help will be appreciated.

Thanks,
Chester

**Comment by vipwangtian** [comment]
> The following is the error message
> ![image](https://user-images.githubusercontent.com/22461405/98921545-68062300-250c-11eb-90de-11375cb6436b.png)
> 
> The following is the server to the Redis-server Latency
> ![image](https://user-images.githubusercontent.com/22461405/98922068-fed2df80-250c-11eb-933f-cd9878bb2dda.png)
> 
> In my program, I use the `set`, `zadd`, `zrangebyscore`, `mget` commands. And I just see a `mget 100 arguments` command in the `slowlog`.
> 
> Any help will be appreciated.
> 
> Thanks,
> Chester

this doc may help
https://github.com/StackExchange/StackExchange.Redis/blob/main/docs/Timeouts.md

**Comment by NickCraver** [comment]
Finding this way late, but for anyone hitting similar later: I see a large command queue and what appears to be a very large data fetch (byte-wise) coming across the wire (which also lines up with a big `MGET` server-side). Closing out to tidy up but happy to help further if this is still an issue in latest.
