### ISSUE TITLE
Test requirements?

### ISSUE THREAD

**Issue by KevinBurton** [StackExchange/StackExchange.Redis#161]
I downloaded and ran the tests but a number of them failed or could not be run. 

The ones that failed seemed to try to connect to port 7xxx. There are a number of tests (particularly the SSL tests) that try to read in various .txt files.

So a general question would be what is the format of the .txt files and what do I need to have running in order (and configured correctly) for the tests to pass?

**Comment by mgravell** [comment]
The SSL tests are trying to read my crypto keys for various 3rd party
services. They aren't going to work, but I will try to document what is
needed. The port 7000 stuff is probably a set of nodes I have locally but
have forgotten to add to the project  - will check.

**Comment by NickCraver** [comment]
I cleaned this up a lot with the Core CLR port, though it still needs documenting the tests should be in better shape for all runners overall.

**Comment by NickCraver** [comment]
I've cleaned up testing and made it much more flexible given the range of stuff we have to test now. Documentation for much easier spin up is here: https://stackexchange.github.io/StackExchange.Redis/Testing
