### ISSUE TITLE
Subscribe with Async Handler

### ISSUE THREAD

**Issue by Turnerj** [StackExchange/StackExchange.Redis#1614]
I've been using the `Subscribe` and `SubscribeAsync` methods for a little while however it just came to my attention I've been using them wrong. Here is a snippet of my code:

```csharp
			Subscriber.Subscribe(RedisChannel, async (channel, value) =>
			{
				string cacheKey = value;
				var shouldEvictLocally = false;
				lock (FlaggedRefreshesLockObj)
				{
					shouldEvictLocally = FlaggedRefreshes.Remove(cacheKey) == false;
				}

				if (shouldEvictLocally)
				{
					await cacheStack.EvictAsync(cacheKey);
				}
			}, CommandFlags.FireAndForget);
```

Now the subtle problem is, the handler `Subscribe` takes is an `Action<RedisChannel, RedisValue>`, not a `Func<RedisChannel, RedisValue, Task>` however, my code there actually compiles without warning (I assume then acts like an async void method). I recently found out about how there is an `OnMessage` function that you can access on the `ChannelQueue` instead which can take a `Func<ChannelMessage, Task>` allowing me to be async in my handler.

The [documentation](https://stackexchange.github.io/StackExchange.Redis/PubSubOrder) strongly recommends to not use `OnMessage` if you don't have to (concurrent vs sequential handling) so I am wondering, is a `Subscribe` and `SubscribeAsync` overload to take a `Func<RedisChannel, RedisValue, Task>` a good idea?

My current solution is just going:

```csharp
Subscriber.Subscribe(RedisChannel).OnMessage(async (channelMessage) => ... );
```

But because the documentation recommends against using `OnMessage` for performance reasons, I'd rather avoid it if I can!

**Comment by NickCraver** [comment]
If the order doesn't matter, you likely just want to `Task.Run()` here to kickoff your `EvictAsync` method, and remove the `async` bits. If you do want to wait on one to complete before the next arrives, then yes: Channel. Effectively it's all about intent here: do you want to wait on ordering or not? If not, just throw it on the task queue :)

**Comment by Turnerj** [comment]
Ahhhh OK - using `Task.Run()` should work fine in my situation. Is it worthwhile having that behaviour (with `Task.Run()`) as an overload for `Subscribe` etc in-library? (Alternatively, an update to the docs to mention this?)

Happy to implement it in either case if you want.

eg.

```csharp

public void Subscribe(RedisChannel channel, Func<RedisChannel, RedisValue, Task> handler)
{
    Subscribe(channel, (channel, value) => Task.Run(handler));
}
```

**Comment by NickCraver** [comment]
I'm not sure it makes sense to add to the library _how you want to run them_ is up to you, and not something we'd want to constrain there. For example, users could easily infer that we _do_ await the result and that it's an ordered setup when it's really nothing of the sort underneath :)

**Comment by Turnerj** [comment]
Makes sense - thanks for the quick turn around getting back to me! You and Marc keep up the awesome work maintaining this project!
