### ISSUE TITLE
StackExchange is not available in Unity

### ISSUE THREAD

**Issue by Ancolie18** [StackExchange/StackExchange.Redis#1615]
My Unity version is 2019.4.2f1 (.netstandard2.0). I added the NuGet package to the C# script and used the 2.1.58 version of StackExchange.Redis. I referenced the namespace in the script, and no error occurred. But running Unity will display an error: "The type or namespace name'StackExchange' could not be found (are you missing a using directive or an assembly reference?)".

I try to add the dll file separately, but it still reports an error: Assembly'Assets/Plugins/StackExchange.Redis.dll' will not be loaded due to errors: Unable to resolve reference'System.Memory'. Is the assembly missing or incompatible with the current platform? Reference validation can be disabled in the Plugin Inspector.

Does SE support its use in Unity? Or is it the cause of issues such as version?
Hope to get your reply, thank you!

**Comment by mgravell** [comment]
I'm curious what you find, by the way
