### ISSUE TITLE
Release 2.2.2 missing on NuGet

### ISSUE THREAD

**Issue by athoscouto** [StackExchange/StackExchange.Redis#1619]
It seems that [2.2.2](https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes.html#222) has been released for a few days already, but the most recent version on [NuGet](https://www.nuget.org/packages/StackExchange.Redis/) is 2.1.58.

I wonder if there is a problem with 2.2.2 or it just need to be published there too.

**Comment by mgravell** [comment]
It isn't "missing" - it is pending. It is available on the myget feed (I would post the link, but myget seems to be having a bad morning - will update in a bit), and will go to NuGet when we've finished dogfooding it.

**Comment by mgravell** [comment]
myget feed: https://www.myget.org/F/stackoverflow/api/v3/index.json

ETA for nuget drop: possibly later today

**Comment by athoscouto** [comment]
Thanks for the explanation!
