### ISSUE TITLE
Missing sentinel test?

### ISSUE THREAD

**Issue by KevinBurton** [StackExchange/StackExchange.Redis#162]
It seems like a basic sentinel test would be to write to the master and check the read, fail the master, write to the new master and check the read. Am I missing something or could this be added to the sentinel tests? If for no other reason that to show an example of subscribing to a failover message, reconfiguring, and reconnecting to the new master. Maybe I am just not looking in the right spot?

**Comment by NickCraver** [comment]
Added in #1067, closing this out!
