### ISSUE TITLE
Call to `ListRightPushAsync` ambiguous

### ISSUE THREAD

**Issue by stefanloerwald** [StackExchange/StackExchange.Redis#1620]
With Version 2.2.3, the call to `ListRightPushAsync` with just two parameters has become ambiguous between
```cs
Task<long> ListRightPushAsync(RedisKey key, RedisValue[] values, When when = When.Always, CommandFlags flags = CommandFlags.None);
Task<long> ListRightPushAsync(RedisKey key, RedisValue[] values, CommandFlags flags = CommandFlags.None);
```

Is this a regression?

I'm calling it as
```cs
public Task<long> RightPushAsync(string key, IEnumerable<string> values)
{
    return database.ListRightPushAsync(key, values.Select(v => (RedisValue)v).ToArray());
}
```

Seems to me like the overload `Task<long> ListRightPushAsync(RedisKey key, RedisValue[] values, CommandFlags flags = CommandFlags.None);` is redundant, isn't it?

**Comment by mgravell** [comment]
Thanks. It isn't redundant due to binary compatibility reasons, but I'll
take the optional parameter away (making it mandatory), which should
resolve this.

**Comment by mgravell** [comment]
Fixed by https://github.com/StackExchange/StackExchange.Redis/commit/296b289b8d83589738ee8414584a4a6d1eb4a02c; will deploy ASAP

**Comment by mgravell** [comment]
2.2.4 is en route to NuGet

**Comment by stefanloerwald** [comment]
Thanks so much!
