### ISSUE TITLE
Verify if already subscribed to Redis Channel

### ISSUE THREAD

**Issue by sanzor** [StackExchange/StackExchange.Redis#1622]
Hello i have a flow where i keep publishing messages to a `Redis` channel.However i would like to first check if the `ISubscriber` is subscribed to the given channel and if not to add a handler to it.
I have tried `ISubscriber.IsConnected` method and it showed true all the time:

```
public void OnSomeEvent(ISubscriber subscriber ,string channel,string message)
{
   bool isSubscribedAlready= ??
   if(!isSubscribedAlready) { await   subscriber.SubscribeAsync(channel,message,(chan,msg)=>Console.Writeline("msg"));}
   subscriber.PublishAsync(channel,message);
}
```

**Comment by Linnea-cloud** [comment]
sudo apt install tcl

**Comment by NickCraver** [comment]
There isn't a way to check if you are subscribed on a specific channel, but the client will handle re-subscribing internally automatically so you never need to subscribe more than once.

If there's a need to add this we could look at an API addition to `ISubscriber`, but that's a breaking change and would require a major release (and even then, isn't friendly on an interface). Hopefully this info is helpful enough, but if not let's explore what an API change would look like.

If you wanted to track it client-side, you could for example keep a `HashSet<RedisChannel>` or `HashSet<string>` in your if statement here for what's subscribed already - given the tracking internally it'd have the same effect.

**Comment by sanzor** [comment]
Hello, thanks for your response ! I have indeed solved the isssue by storing the state on the client side (storing the subscribed channel names in a hashset).

Though i must tell you , without knowing the intricacies and complexity of what would be required to add such a feature to the existing API, it would be a very helpful feature !
