### ISSUE TITLE
Sockets/No Connection Issue with Redis in Azure

### ISSUE THREAD

**Issue by sukrti** [StackExchange/StackExchange.Redis#1631]
Recently we have upgraded StackExchange.Redis in .NET Application to 2.2.4 version and after that we are facing Redis timeout and Socket Issue. The description of both of the issues are mentioned below:

SocketFailure on DEL One or more errors occurred. (Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..) Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

No connection is available to service this operation: DEL xxx|livechatPreviousJsonID; An established connection was aborted by the software in your host machine. SocketFailure on rediscache(app id)/Interactive, origin: WriteQueue, input-buffer: 0, outstanding: 0, last-read: 705s ago, last-write: 23s ago, unanswered-write: 25s ago, keep-alive: 30s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.. An established connection was aborted by the software in your host machine.

Not sure what is causing these issue. Kindly help.

**Comment by NickCraver** [comment]
This could previously happen in a failover case we didn't observe, but since then we've put a lot of work with the Azure team into publishing and observing these events. For anyone hitting this, please grab a new library version (currently 2.2.88 but soon 2.5.x) to automatically subscribe and handle any failover events there ASAP. That should result in a much better experience and fewer errors overall :)
