### ISSUE TITLE
Seeing a lot of Redis timeouts related to Busy IO threads after upgrading to .NET Framework 4.7.2 from .NET Framework 4.6.2

### ISSUE THREAD

**Issue by omkarpatil-msft** [StackExchange/StackExchange.Redis#1634]
Hi,
We use Redis for caching at very high scale in one of our services.
We are seeing an issue arise when we moved from .NET Framework 4.6.1 to .NET Framework 4.7.2. 
We started seeing really increased busy I/O thread count after moving to .NET 4.7.2. We see the following Redis cache read/write timeout log message: 
**IOCP (Busy=382, Free=618, Min=75, Max = 1000)**

Following are some screenshot from thread profiling conducted on the faulty build with artificial load:
![image](https://user-images.githubusercontent.com/75649175/101520777-cc64a880-3939-11eb-8db2-eb20b723f07e.png)

As highlighted in the above process dumps we are seeing marked increase in threads waiting on ConnectionMultiplexer.ExecuteSyncImpl.

Note: We do have sync-async usages in our code base, however we do not run into this issue with .NET Framework 4.6.2 + Redis 1.6.2.
I am trying to see the best way forward to debug this issue/root cause it.

So far,
•	I am able to run a load test locally that results in the increase in busy I/O threads on our test environments but isn't large enough to cause Redis thread starvation and timeouts as seen with traffic on our production environment.

We also tried upgrading to the newest version of Redis `2.2.4`, but that did not fix the issue as well - Note: we did not change the sync calls to async.

**Comment by NickCraver** [comment]
Do you have a comparison snapshot against the `net462` build? The 2.x series uses more async and pool, which means if the overall process is under more contention than we'll see effects. But more importantly: the 1.x client _didn't apply timeouts to async operations at all_. It simply never reported them - if this behavior is desired then a really high timeout would have the same effect, but it depends on what you're after here: e.g. are these spikes you'd like to take as long as they take an subside, or would you rather trip the blow off valve, dump the commands, and resume operations after the load sheds off.

The timeout mechanism is entirely designed to prevent a death spiral like most, but sometimes with spike load that's just not desired and it's a spike in activity users would like to let pass...that's something about your workload that you'd have to decide (happy to help advise).

If I were debugging your application, I'd treat that thread count as _very_ high and want to look at dumps at peak load to see where all that contention is. sync over async and vice-versa definitely will contribute to pool trouble here, but often it's a lot of off-box I/O that _should_ be `async` and ultimately needs porting (and I get that's not always an easy transition - it's certainly viral). If you can take a dump of the process, I have a LinqPad script that may help: https://gist.github.com/NickCraver/d6292c0c7f93767686e8c5c89ed45c54 in reading threads at the bottom quickly to see where things are. Perhaps that would help see why so many threads are active and the backlog exists?

Happy to help spitball ideas, just limited on time overall (hence late getting to every issue here). I hope the above info helps a bit though!

If you are porting to async in more places already, I'm curious how it's going and how your thread levels are looking.

**Comment by NickCraver** [comment]
Closing this out to cleanup - best advice without more info is already above.
