### ISSUE TITLE
StackExchange.Redis (2.2.4) does not work with .NET Framework 4.8 but was working fine with .NET Framework 4.6.1

### ISSUE THREAD

**Issue by ernikg29** [StackExchange/StackExchange.Redis#1635]
After upgrading to .Net Framework  to 4.8 we are not able to connect to Redis on our VM.

Below is the sample code-

```
ConfigurationOptions option = new ConfigurationOptions
{
	EndPoints = { "localhost" },
	ResolveDns = true
};
var redis = ConnectionMultiplexer.Connect(option);
Console.WriteLine("Connection success to Redis");
if (!redis.IsConnected)
{
	Console.WriteLine("Redis is not connected");
}

```
**Below is the error we are getting -**

>Exception message: It was not possible to connect to the redis server(s). SocketFailure (None, last-recv: 2046) on localhost:6379/Interactive, Flushed/Faulted, last: ECHO, origin: ReadFromPipe, outstanding: 8, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.4.27433
Exception StackTrace:   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1163
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1032
   at PublisherConsoleDemo.Program.Main(String[] args)

And, I also tried adding **AbortOnConnectFail = false** to the ConfigurationOptions but that also did not seem to work. We are no longer getting the above exception but **redis.IsConnected** is still returning false.

Also, I would like to confirm that I the connection to the redis is working fine though the redis-cli.exe.

Any suggestion is highly appreciated.

**Comment by mgravell** [comment]
Most oddness in netfx ultimately comes down to one of:

- TLS default changing
- assembly binding redirects

If it isn't TLS, I'd guess the latter. If you pass a StringWriter into the
log parameter of Connect, any clues there?

**Comment by ernikg29** [comment]
Hi @mgravell , thanks for the reply.

After passing a StringWriter into the log parameter, I got the below log out -

`localhost:6379,abortConnect=False`

`Connecting localhost:6379/Interactive...
BeginConnect: localhost:6379
Connected Interactive/localhost:6379
Server handshake
Setting client name: w5130
Auto-configure...
Sending critical tracer: Interactive/localhost:6379
Writing to Interactive/localhost:6379: ECHO
Flushing outbound buffer
Starting read
connection failed: localhost:6379 (Interactive, SocketFailure): SocketFailure (None, last-recv: 23) on localhost:6379/Interactive, Flushed/Faulted, last: ECHO, origin: ReadFromPipe, outstanding: 8, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.4.27433`

`Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
1 unique nodes specified
Requesting tie-break from localhost:6379 > __Booksleeve_TieBreak...
connection failed: localhost:6379 (Subscription, SocketFailure): SocketFailure (None, last-recv: 56) on localhost:6379/Subscription, Flushed/Faulted, last: SUBSCRIBE, origin: ReadFromPipe, outstanding: 3, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.4.27433`

`Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=0,Free=2047,Min=4,Max=2047)
Not all tasks completed cleanly (from ReconfigureAsync#1748, timeout 5000ms), IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=2046,Min=4,Max=2047)
localhost:6379 did not respond
Waiting for tiebreakers...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=2046,Min=4,Max=2047)
Not all tasks completed cleanly (from NominatePreferredMaster#1985, timeout 50ms), IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=2046,Min=4,Max=2047)
localhost:6379 failed to nominate (WaitingForActivation)
No masters detected
localhost:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
localhost:6379: int ops=16, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=6, qu=0, qs=0, qc=0, wr=0, socks=2
Circular op-count snapshot; int: 0+16=16 (1.60 ops/s; spans 10s); sub: 0+6=6 (0.60 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 2...
1 unique nodes specified
Requesting tie-break from localhost:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=2044,Min=4,Max=2047)
Finished awaiting tasks, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=2044,Min=4,Max=2047)
localhost:6379 faulted: SocketFailure (None, last-recv: 2014) on localhost:6379/Interactive, Flushed/Faulted, last: ECHO, origin: ReadFromPipe, outstanding: 8, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 7 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.2.4.27433
Waiting for tiebreakers...
All tasks are already complete
localhost:6379 failed to nominate (Faulted)`

`SocketFailure (None, last-recv: 2014) on localhost:6379/Interactive, Flushed/Faulted, last: ECHO, origin: ReadFromPipe, outstanding: 8, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 7 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.2.4.27433
No masters detected
localhost:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
localhost:6379: int ops=24, qu=0, qs=0, qc=0, wr=0, socks=3; sub ops=9, qu=0, qs=0, qc=0, wr=0, socks=3
Circular op-count snapshot; int: 0+24=24 (2.40 ops/s; spans 10s); sub: 0+9=9 (0.90 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 1...
1 unique nodes specified
Requesting tie-break from localhost:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=2044,Min=4,Max=2047)
Finished awaiting tasks, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=2,Free=2045,Min=4,Max=2047)
localhost:6379 faulted: SocketFailure (None, last-recv: 2049) on localhost:6379/Interactive, Flushed/Faulted, last: ECHO, origin: ReadFromPipe, outstanding: 8, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.2.4.27433
Waiting for tiebreakers...
All tasks are already complete
localhost:6379 failed to nominate (Faulted)`

`SocketFailure (None, last-recv: 2049) on localhost:6379/Interactive, Flushed/Faulted, last: ECHO, origin: ReadFromPipe, outstanding: 8, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.2.4.27433
No masters detected
localhost:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
localhost:6379: int ops=32, qu=0, qs=0, qc=0, wr=0, socks=4; sub ops=12, qu=0, qs=0, qc=0, wr=0, socks=4
Circular op-count snapshot; int: 0+32=32 (3.20 ops/s; spans 10s); sub: 0+12=12 (1.20 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Starting heartbeat...`

One of the error I can see is - **Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.** but I can confirm that   I have that dll in the folder already.

**Comment by mgravell** [comment]
Assembly binding redirects. I'm on mobile and internet isn't working well
enough for me to Google it, but: Nick Craver has an excellent blog article
on this - pretty sure "Nick Craver blog assembly binding redirect" will
take you straight to it.

**Comment by ernikg29** [comment]
Sure @mgravell , I will quickly try this.

**Comment by NickCraver** [comment]
Here ya go: https://nickcraver.com/blog/2020/02/11/binding-redirects/

**Comment by ernikg29** [comment]
Its working fine after now after adding the binding redirect manually in the config file.
Thanks for the support 👍
