### ISSUE TITLE
Timeouts while LPUSH

### ISSUE THREAD

**Issue by traveazy** [StackExchange/StackExchange.Redis#1640]
We are getting intermittent timeouts while doing LPUSH.
Below is the error captured.

**Runtime environment is .NET Core 3.1 on aws Lambda with 1 GB of RAM**
We also tried setting MinThreads using ThreadPool.SetMinThreads(50, 50); still error comes. 
And its not persistent, In-case application is restarted, it works fine again.

One or more errors occurred.
(Timeout awaiting response (outbound=4KiB, inbound=0KiB, 20993ms elapsed, timeout is 5000ms), command=LPUSH, next: LPUSH some_list, inst: 0, qu: 0, qs: 2, aw: False, rs: DequeueResult, ws: Idle, in: 0, in-pipe: 10, out-pipe: 0, serverEndpoint: redis-****************************-.com:1***4, mc: 1/1/0, mgr: 9 of 10 available, clientName: 169, IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=2,Free=32765,Min=50,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts))

(Timeout awaiting response (outbound=0KiB, inbound=0KiB, 72468ms elapsed, timeout is 5000ms), command=LPUSH, next: LPUSH some_list, inst: 0, qu: 0, qs: 1, aw: False, rs: DequeueResult, ws: Writing, in: 4, in-pipe: 4, out-pipe: 0, serverEndpoint: redis-****************************-.com:1***4, mc: 1/1/0, mgr: 9 of 10 available, clientName: 169, IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=2,Free=32765,Min=50,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts))

(Timeout awaiting response (outbound=4KiB, inbound=0KiB, 20993ms elapsed, timeout is 5000ms), command=LPUSH, next: LPUSH some_list, inst: 0, qu: 0, qs: 2, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: redis-****************************-.com:1***4, mc: 1/1/0, mgr: 9 of 10 available, clientName: 169, IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=4,Free=32763,Min=50,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts))

(Timeout awaiting response (outbound=3KiB, inbound=0KiB, 36464ms elapsed, timeout is 5000ms), command=LPUSH, next: LPUSH some_list, inst: 0, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 4, in-pipe: 0, out-pipe: 0, serverEndpoint: redis-****************************-.com:1***4, mc: 1/1/0, mgr: 10 of 10 available, clientName: 169, IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=8,Free=32759,Min=50,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts))

System.ThrowHelper in ThrowAggregateException
System.Threading.Tasks.Task in WaitAllCore
System.Threading.Tasks.Task in WaitAll
TZY.ElasticAPM.Logger.Core.LoggerAgent in EnsureMessageDelivery
TZY.ElasticAPM.Logger.LambdaExtensions.APIGatewayEvents.APIGatewayEvents+<CaptureTransactionAsync>d__1 in CaptureTransactionAsync
CAUSED BY
Timeout awaiting response (outbound=4KiB, inbound=0KiB, 20993ms elapsed, timeout is 5000ms), command=LPUSH, next: LPUSH some_list, inst: 0, qu: 0, qs: 2, aw: False, rs: DequeueResult, ws: Idle, in: 0, in-pipe: 10, out-pipe: 0, serverEndpoint: redis-****************************-.com:1***4, mc: 1/1/0, mgr: 9 of 10 available, clientName: 169, IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=2,Free=32765,Min=50,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by NickCraver** [comment]
Missed this when filed - did you get to the bottom of this? The times in those messages are craaaaaazy high, where the heartbeat itself hasn't been running. This looks environment specific and I'm not sure where to start on it in that aspect (no idea about Lambda's constraints) - hope you were able to resolve.
