### ISSUE TITLE
The MillsecondsPerHeartbeat change to 5000

### ISSUE THREAD

**Issue by Jamli** [StackExchange/StackExchange.Redis#1646]
Hello:
    Our system have 120 Redis Client, and redis cluster have 252 nodes (master+slave). I have met a situation, when I stop one node of the redis cluster service manually for 120s. The Cpu of the redis node rise to 100%,and can not to recover.
when i change MillsecondsPerHeartbeat  from 1000 to 5000. The save situation,The cup of the redis node can recover quikly.

so ,i would like sovm advice,the MillsecondsPerHeartbeat change  from 1000 to 5000 have any other effects。if also want to know the reason to the cup can not recover.

we pause redis server just to Reproduce the production problem。 The situation of the production problem is the cpu of the redis culuster rise to 100% , and the Redis client send many auth commond .

**Comment by NickCraver** [comment]
Are you saying your Redis server is hanging for 120 seconds, or a client is? If your server is hanging, you'll want to check SLOWLOG as a starting point and seeing what's stalling so long.

**Comment by mgravell** [comment]
That is quite the setup! Is it your view, then, that in this topology the heartbeat frequency is contributing to the stall? Ultimately, from the perspective of any single node, it is just 1 (maybe 2) per client per heartbeat, and that is a trivial volume of traffic to a redis server. As Nick says, I'd look first at whether there's something else blocking the server before getting *too* excited about the heartbeat.

**Comment by Jamli** [comment]
> Are you saying your Redis server is hanging for 120 seconds, or a client is? If your server is hanging, you'll want to check SLOWLOG as a starting point and seeing what's stalling so long.

I  stop one node of the redis cluster service manually for 120s。

**Comment by mgravell** [comment]
What we perhaps should look at here is a graduated back off, so that it
doesn't *keep* doing a doomed heartbeat regularly, degrading *from* the
current heartbeat to something maybe an order of magnitude less frequent.

One to think about in the new year.

**Comment by NickCraver** [comment]
In the 2.2.50 release, we not back off exponentially when this happens. Cheers to @deepakverma for a contribution there.
