### ISSUE TITLE
Syntactic error in hash Store

### ISSUE THREAD

**Issue by fereidoonsavadkoohi** [StackExchange/StackExchange.Redis#1649]
Hi. I think when using HashSet/HashsetAsync/HashGet/HashGetAsync, the place of the key and the hash key is wrong. I have tested this several times and noticed this.
this is the source:
`      
        Task<bool> HashSetAsync(RedisKey key, RedisValue hashField, RedisValue value, When when = When.Always, CommandFlags flags = CommandFlags.None);
`
but for work correctly you must change "key" and "hashField" place

**Comment by NickCraver** [comment]
Do you have an example use case where this appears to be backwards? To add some clarification: `key` here refers to the Redis key (for all commands), `hashField` is the field, sometimes referred to as the key _within that hashset_. Is that the confusion perhaps?

**Comment by NickCraver** [comment]
Happy to revisit if there's an issue, but hoping this is just confusion (lots of users of this API today) - closing to cleanup for now.
