### ISSUE TITLE
Should SSL/TLS cert validation checks be controlled by a config setting - SslCertVerify=false??

### ISSUE THREAD

**Issue by mshiels** [StackExchange/StackExchange.Redis#1652]
Generally across the internet I would want SSlCertVerify=true, but within our datacenter we are connecting to machines that are not using production certificates since internal.  Yes I have done the following in our code to resolve it, but it might be a generally usefull feature?

                ConfigurationOptions CO = ConfigurationOptions.Parse(configuration: configuration);

                        CO.CertificateValidation += (sender, cert, chain, errors) =>
                        {
                            //Console.WriteLine("errors: " + errors);
                            return true;
                        };

**Comment by NickCraver** [comment]
You can add this trust today! You'll want to use the `CongiruationOptions.TrustIssuer()` calls here, to add trust to that certificate :)
