### ISSUE TITLE
Newbie getting going here and logging the crap out of things - but some weird start up errors

### ISSUE THREAD

**Issue by mshiels** [StackExchange/StackExchange.Redis#1653]
I have hooked up all the events, and the TExtWriter to grab stuff that's happening - just so we can tell what's up and down and sideways etc. 

But unknown if I should be concerned here or not.  I am running ona  decent internet link, remote to our DC, over VPN.  Cluster of 3 master, 3 slaves. - currently I think the config just lists one of the masters so I gotta adjust that too.

But there are is a timeout right at startup and the some unable to read/already shutdown socket situations.

2020/12/23 10:31:57.264  WAR6: 8f9c: XXXX - Opened Log File - XXXX
2020/12/23 10:31:57.267  INF0: 8f9c: 172.20.2.140:7000,ssl=True,sslHost=Server
2020/12/23 10:31:57.289  INF0: 8f9c: Connecting 172.20.2.140:7000/Interactive...
2020/12/23 10:31:57.388  INF0: 8f9c: BeginConnect: 172.20.2.140:7000
2020/12/23 10:31:57.439  INF0: 8f9c: 1 unique nodes specified
2020/12/23 10:31:57.458  INF0: 8f9c: Requesting tie-break from 172.20.2.140:7000 > __Booksleeve_TieBreak...
2020/12/23 10:31:57.464  INF0: 8f9c: Allowing endpoints 00:00:05 to respond...
2020/12/23 10:31:57.477  INF0: 8f9c: Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=0,Free=1023,Min=16,Max=1023)
2020/12/23 10:31:57.524  INF0: 60b0: Configuring TLS
2020/12/23 10:32:03.248  INF0: 60b0: TLS connection established successfully using protocol: Tls12
2020/12/23 10:32:03.260  INF0: 60b0: Connected Interactive/172.20.2.140:7000
2020/12/23 10:32:03.319  INF0: 60b0: Server handshake
2020/12/23 10:32:03.337  INF0: 60b0: Setting client name: MASDEV10
2020/12/23 10:32:03.892  INF0: 60b0: Auto-configure...
2020/12/23 10:32:03.912  INF0: 60b0: Sending critical tracer: Interactive/172.20.2.140:7000
2020/12/23 10:32:03.913  INF0: 60b0: Writing to Interactive/172.20.2.140:7000: ECHO
2020/12/23 10:32:03.913  INF0: 60b0: Flushing outbound buffer
2020/12/23 10:32:03.920  INF0: 60b0: Starting read
2020/12/23 10:32:04.152  INF0: 3e84: Response from Interactive/172.20.2.140:7000 / ECHO: BulkString: 16 bytes
2020/12/23 10:32:04.202  INF0: 224c: Finished awaiting tasks, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=2,Free=1021,Min=16,Max=1023)
2020/12/23 10:32:04.203  INF0: 224c: 172.20.2.140:7000 faulted: The timeout was reached before the message could be written to the output buffer, and it was not sent, command=PING, timeout: 5000, inst: 9, qu: 3, qs: 1, aw: True, bw: RecordingTimeout, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: 172.20.2.140:7000, mc: 1/0/0, mgr: 10 of 10 available, clientName: MASDEV10, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=1,Free=1022,Min=16,Max=1023), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
2020/12/23 10:32:04.216  INF0: 224c: Waiting for tiebreakers...
2020/12/23 10:32:04.216  INF0: 224c: All tasks are already complete
2020/12/23 10:32:04.216  INF0: 224c: 172.20.2.140:7000 failed to nominate (Faulted)
2020/12/23 10:32:04.217  INF0: 224c: > The timeout was reached before the message could be written to the output buffer, and it was not sent, command=GET, timeout: 5000, inst: 9, qu: 2, qs: 1, aw: True, bw: RecordingTimeout, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: 172.20.2.140:7000, mc: 1/0/0, mgr: 10 of 10 available, clientName: MASDEV10, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=2,Free=1021,Min=16,Max=1023), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
2020/12/23 10:32:04.217  INF0: 224c: No masters detected
2020/12/23 10:32:04.223  INF0: 224c: 172.20.2.140:7000: Cluster v6.0.9, master; 16 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 0 active; not in use: DidNotRespond
2020/12/23 10:32:04.227  INF0: 224c: 172.20.2.140:7000: int ops=11, qu=0, qs=3, qc=0, wr=0, socks=1; sub ops=3, qu=0, qs=1, qc=0, wr=0, socks=1
2020/12/23 10:32:04.230  INF0: 224c: Circular op-count snapshot; int: 0+11=11 (1.10 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
2020/12/23 10:32:04.230  INF0: 224c: 172.20.2.139:7000: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Connecting; sub: n/a
2020/12/23 10:32:04.230  INF0: 224c: 172.20.2.139:7000: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=0, qu=0, qs=0, qc=0, wr=0
2020/12/23 10:32:04.230  INF0: 224c: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub:
2020/12/23 10:32:04.230  INF0: 224c: 172.20.2.142:7000: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Connecting; sub: n/a
2020/12/23 10:32:04.230  INF0: 224c: 172.20.2.142:7000: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=0, qu=0, qs=0, qc=0, wr=0
2020/12/23 10:32:04.231  INF0: 224c: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub:
2020/12/23 10:32:04.231  INF0: 224c: 172.20.2.142:7001: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Connecting; sub: n/a
2020/12/23 10:32:04.231  INF0: 224c: 172.20.2.142:7001: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=0, qu=0, qs=0, qc=0, wr=0
2020/12/23 10:32:04.231  INF0: 224c: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub:
2020/12/23 10:32:04.231  INF0: 224c: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
2020/12/23 10:32:04.231  INF0: 224c: resetting failing connections to retry...
2020/12/23 10:32:04.258  INF0: 224c: retrying; attempts left: 2...
2020/12/23 10:32:04.261  INF0: 224c: 1 unique nodes specified
2020/12/23 10:32:04.261  INF0: 224c: Writing to Interactive/172.20.2.140:7000: PING
2020/12/23 10:32:04.261  INF0: 224c: Requesting tie-break from 172.20.2.140:7000 > __Booksleeve_TieBreak...
2020/12/23 10:32:04.261  INF0: 224c: Writing to Interactive/172.20.2.140:7000: GET __Booksleeve_TieBreak
2020/12/23 10:32:04.261  INF0: 224c: Allowing endpoints 00:00:05 to respond...
2020/12/23 10:32:04.261  INF0: 224c: Awaiting task completion, IOCP: (Busy=2,Free=998,Min=16,Max=1000), WORKER: (Busy=1,Free=1022,Min=16,Max=1023)
2020/12/23 10:32:04.331  INF0: 224c: connection failed: 172.20.2.139:7000 (Interactive, SocketFailure): SocketFailure on 172.20.2.139:7000/Interactive, Initializing/NotStarted, last: NONE, origin: ConnectedAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 9 of 10 available, last-heartbeat: never, global: 10s ago, v: 2.2.4.27433
2020/12/23 10:32:04.331  INF0: 224c: > Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall.
2020/12/23 10:32:04.332  INF0: 224c: > A blocking operation was interrupted by a call to WSACancelBlockingCall
2020/12/23 10:32:04.332  INF0: 8dc4: connection failed: 172.20.2.142:7001 (Interactive, SocketFailure): SocketFailure on 172.20.2.142:7001/Interactive, Initializing/NotStarted, last: NONE, origin: ConnectedAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 9 of 10 available, last-heartbeat: never, global: 10s ago, v: 2.2.4.27433
2020/12/23 10:32:04.332  INF0: 8dc4: > Unable to read data from the transport connection: A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call.
2020/12/23 10:32:04.332  INF0: 8dc4: > A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
2020/12/23 10:32:04.352  INF0: 59bc: Response from Interactive/172.20.2.140:7000 / PING: SimpleString: PONG
2020/12/23 10:32:04.352  INF0: 59bc: Response from Interactive/172.20.2.140:7000 / GET __Booksleeve_TieBreak: (null)
2020/12/23 10:32:04.353  INF0: 581c: All tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=2,Free=1021,Min=16,Max=1023)
2020/12/23 10:32:04.353  INF0: 581c: 172.20.2.140:7000 returned with success

**Comment by NickCraver** [comment]
What's odd to me here is the 5 seconds between TLS start and finish - that's an eternity for a connection. Is there a chance the certificates are wrong, or the intermediate isn't present at the destination causing an additional fetch to happen (also near the 5 second mark in duration)? These sorts of things are what I'd expect to see here based on the timings in the log.

As a workaround, you could up the connectTimeout to make it _reliable_, if slow. But the slowness definitely seems to be in the TLS negotiation phase.

**Comment by NickCraver** [comment]
Closing this out to cleanup - happy to re-open and add advice if there's more info but the TLS issue is likely certificate and intermediary, based on similar things we've seen (not just in the client here) before.
