### ISSUE TITLE
Stackexchange Redis exception: an unknown error occurred when writing the message

### ISSUE THREAD

**Issue by TestUser0811** [StackExchange/StackExchange.Redis#1654]
.net core 2.1 web-api uses below redis nuget package "StackExchange.Redis" Version="2.1.55" and connects to Azure Redis P1 tier, Redis version 4.0.14

On appsettings.config,
```
"RedisConfiguration": {
    "ConnectionString": "mycache.redis.cache.windows.net:6380,password=$$$$$$$$$F543shkerXXXXXg=,ssl=True,abortConnect=False",
  "DatabaseNumber": 1
  }

```
Receiving below exception very frequently especially when maintaining **50requests/sec.** Our application deployed on Azure service fabric cluster with 3 nodes. No processor/memory pressure observed on any of the server nodes.

```
Message":"Redis exception while setting the value to cache: An unknown error occurred when writing the message","Level":"Error","ExceptionType":"StackExchange.Redis.RedisConnectionException

"Message":"Redis exception while getting the value from cache: An unknown error occurred when writing the message","Level":"Error","ExceptionType":"StackExchange.Redis.RedisConnectionException"
```
Complete stack trace for your reference:

`"StackTrace":"   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2800\r\n   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54\r\n   at MyApplication.RedisCacheAdapter.<>c__DisplayClass21_1.<Put>b__0() in M:\\work2\\7ae5cc7915b5f803\\MyApplication\\RedisCacheAdapter.cs:line 199\r\n   at Polly.Policy.<>c__DisplayClass144_0.<Execute>b__0(Context ctx, CancellationToken ct)\r\n   at Polly.RetrySyntax.<>c__DisplayClass5_1.<Retry>b__1(Context ctx, CancellationToken ct)\r\n   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)\r\n   at Polly.RetrySyntax.<>c__DisplayClass5_0.<Retry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)\r\n   at Polly.Policy.ExecuteInternal(Action`2 action, Context context, CancellationToken cancellationToken)\r\n   at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)\r\n   at MyApplication.RedisCacheAdapter.Put(String key, Byte[] bytes, TimeSpan expirytime) in M:\\work2\\7ae5cc7915b5f803\\MyApplication\\RedisCacheAdapter.cs:line 196","Exception":"An unknown error occurred when writing the message","LoggerName":"MyApplication.RedisCacheAdapter","Message":"Redis exception while setting the value to cache: An unknown error occurred when writing the message","Level":"Error","ExceptionType":"StackExchange.Redis.RedisConnectionException"`

What would be reason for such error & how to fix this "StackExchange.Redis.RedisConnectionException"? Any change in redis connection string properties or redis version update would be useful?

**Comment by NickCraver** [comment]
I missed your issue here - can you please try using the latest 2.2.x version of the library? We had a few fixes around write contention that likely resolve your issue, and add better error logging as well.

**Comment by NickCraver** [comment]
This should be improved in the latest version. If you're still hitting the same issue after upgrading, please ping here and I'll re-open!

**Comment by jayantadas1** [comment]
@TestUser0811 - What was the resolution for this?
