### ISSUE TITLE
Azure Function App: exception Could not load System.IO.Pipelines connecting to Redis

### ISSUE THREAD

**Issue by brws70** [StackExchange/StackExchange.Redis#1655]
Created a new Function App, HTTP trigger in VS2019 (16.8.3) to connect to Azure Cache for Redis.  Added StackExchange.Redis 2.2.4 from nuget.

local.settings.json contains the key/value of RedisConnectionFromKeyVault and the Primary Connection String from Access keys from the portal. 
```
{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "RedisConnectionFromKeyVault": "<<SNIP>>.redis.cache.windows.net:6380,password=<<SNIP>>,ssl=True,abortConnect=False"
  }
}
```

Added the following lines to the default function code:

    var connectionRedis = Environment.GetEnvironmentVariable("RedisConnectionFromKeyVault", EnvironmentVariableTarget.Process);
    var cache = ConnectionMultiplexer.Connect(connectionRedis).GetDatabase();

When I run and trigger the function app locally I get the following exception on the ConnectionMultiplexer.Connect call.

```
System.Private.CoreLib: Exception while executing function: Function1. StackExchange.Redis: Could not load file or assembly 'System.IO.Pipelines, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1032
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1015
   at FunctionApp1.Function1.<Run>d__0.MoveNext() in E:\GitRepos\FunctionApp1\FunctionApp1\Function1.cs:line 26
```

Tried similar code in a console app and it works fine?

Why does the function app think it cannot find the System.IO.Pipelines assembly?

Even if I include the System.IO.Piplelines nuget package explicitly it does not find it?
Asked question here also https://stackoverflow.com/questions/65382540

**Comment by brws70** [comment]
It looks like StackExchange.Redis 2.2.3 upgraded dependency for System.IO.Pipelines from 4.7.1 to 5.0.0 which is when it fails. StackExchange.Redis 2.1.58 does not experience this same issue

**Comment by dceravigupta** [comment]
Did you look at https://github.com/StackExchange/StackExchange.Redis/issues/1637?

**Comment by brws70** [comment]
@dceravigupta #1637 does indeed appear to be the same issue. Manually editing the csproj and adding the line as suggested does indeed work. To close and for others who find this...  It appears that [https://github.com/Azure/azure-functions-host/issues/5894 ](https://github.com/Azure/azure-functions-host/issues/5894) is the root?
```
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput> <!-- *** this line is new ** -->
  </PropertyGroup>
```

**Comment by rob4bertus** [comment]
Hi all, I am using EventHubTrigger to trigger my function app. 

When I add <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput> the events do not trigger. 
And when I remove it, I get the System.IO.Pipelines assembly exception upon connection to redis. 

So now I don't know what to do. Any has an idea?
