### ISSUE TITLE
Timeout awaiting response version:   2.2.4.27433

### ISSUE THREAD

**Issue by bluetianx** [StackExchange/StackExchange.Redis#1657]
I have error when I use stackExchange, ,I have set min thread to 125 ,but not work

`
StackExchange.Redis.RedisTimeoutException: Timeout performing GET (1000ms), next: GET 5fe9a80b9827b2001535c46d, inst: 8, qu: 0, qs: 57, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: , mc: 1/1/0, mgr: 5 of 5 available, clientName: flight.policy.sync#3af9b4_1.0.28, PerfCounterHelperkeyHashSlot: 8646, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=16,Free=32751,Min=125,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
`

**Comment by bluetianx** [comment]
my app  rps is 6000,  mechine  has 16 cores,

**Comment by zhujinhu21** [comment]
@bluetianx  how did you solved it

**Comment by bluetianx** [comment]
@zhujinhu21 I do not resolve ,I think nobody can resolve it ,so I closed this

**Comment by bluetianx** [comment]
@zhujinhu21  I resolve it by using CommandFlags.FireAndForget
