### ISSUE TITLE
Cluster auto discovery doesn't update node relations after a master failover if only a single node is passed in ConfigurationOptions

### ISSUE THREAD

**Issue by dreijer** [StackExchange/StackExchange.Redis#1659]
I've been testing the StackExchange.Redis library against a Redis cluster with three shards. My topology consists of three physical nodes each running three Redis instances, i.e. one master and two replicas (for the other two shards) on each physical node, resulting in a total of nine Redis instances. Each of the physical nodes has its own public IP address and each Redis instance.

When I connect to my Redis cluster, I use a FQDN pointing to a traffic manager in Azure that just picks one of the three physical nodes for the initial auto discovery request and the library then connects directly to each of the nine Redis instances via its public IP address. The library then performs auto discovery by default every 60 seconds against the FQDN endpoint that I provided in `ConfigurationOptions`. In other words, I don't provide the library with all nine Redis endpoints -- they're auto discovered from the FQDN that I provide.

I seem to have discovered what appears to be a bug, or perhaps an unsupported scenario, after a failover of the master with this setup. Before the failover, if I attempt to read a value and pass `CommandFlags.PreferReplica`, the library properly round robins between the two replicas for the desired hash slot. However, after I manually fail over the master and the library has done auto discovery, reads now only go to the master. In fact, looking closer at `ServerSelectionStrategy`, the master `ServerEndpoint` [doesn't actually _have_ any Replicas](https://github.com/StackExchange/StackExchange.Redis/blob/6409b9d1f2afd01a7eab9498a525360d1ca2b752/src/StackExchange.Redis/ServerSelectionStrategy.cs#L254)...

After debugging through the library, it looks like the auto discovery logic doesn't correctly update the cluster config and [the `ServerEndpoint.Replicas` array](https://github.com/StackExchange/StackExchange.Redis/blob/6409b9d1f2afd01a7eab9498a525360d1ca2b752/src/StackExchange.Redis/ServerEndPoint.cs#L29) on the newly selected master remains empty.

This appears to be because the auto discovery is done against the endpoint that was passed in `ConfigurationOptions`, i.e. the FQDN, which isn't actually used by the Redis cluster itself. That is, when the response is processed by `ClusterNodesProcessor`, `ServerEndpoint.SetClusterConfiguration` is only called on the FQDN `ServerEndpoint` instance, which is a no-op since the endpoint won't match any of the nodes in the cluster (remember: they all have public IP addresses and were auto discovered through the initial bootstrap):
`var thisNode = configuration.Nodes.FirstOrDefault(x => x.EndPoint.Equals(EndPoint));`

The reason that this works initially when the library is initialized is because `ClusterNodesProcessor` is run against all the nodes in the cluster and thus `ServerEndpoint.SetClusterConfiguration` is called for each `ServerEndpoint` updating the node relationships. That means the three master `ServerEndpoints` [will have items in their Replicas array](https://github.com/StackExchange/StackExchange.Redis/blob/6409b9d1f2afd01a7eab9498a525360d1ca2b752/src/StackExchange.Redis/ServerEndPoint.cs#L216), but after the failover where ServerSelectionStrategy is properly updated with the new master `ServerEndpoint`, the `ServerEndpoint` itself isn't updated to point to its replicas.

I made a quick patch to validate this (see patch at the end of this post). It basically changes [ConnectionMultiplexer.GetEndpointsFromClusterNodes()](https://github.com/StackExchange/StackExchange.Redis/blob/6409b9d1f2afd01a7eab9498a525360d1ca2b752/src/StackExchange.Redis/ConnectionMultiplexer.cs#L1950), which currently executes the cluster nodes command against the endpoint specified in `ConfigurationOptions`, to also update the node relations for all the nodes in the `ClusterConfiguration`.

This solves the issue, although I don't know if this is the desired way to fix it since I don't know the library well enough to be able to tell if there are other implications.

I couldn't find anywhere that it's an unsupported scenario to just pass a single endpoint to `ConfigurationOptions`, so I assume it should work. Hoping to hear your insights on this.

```
diff --git a/src/StackExchange.Redis/ConnectionMultiplexer.cs b/src/StackExchange.Redis/ConnectionMultiplexer.cs
index cf3a017..a5b3c04 100644
--- a/src/StackExchange.Redis/ConnectionMultiplexer.cs
+++ b/src/StackExchange.Redis/ConnectionMultiplexer.cs
@@ -1953,7 +1953,20 @@ private async Task<EndPointCollection> GetEndpointsFromClusterNodes(ServerEndPoi
             try
             {
                 var clusterConfig = await ExecuteAsyncImpl(message, ResultProcessor.ClusterNodes, null, server).ForAwait();
-                return new EndPointCollection(clusterConfig.Nodes.Select(node => node.EndPoint).ToList());
+
+                var clusterEndpoints = new EndPointCollection(clusterConfig.Nodes.Select(node => node.EndPoint).ToList());
+
+                // Loop through all the nodes in the cluster and update each existing node's relations to the other nodes (master <-> replica).
+                foreach (EndPoint endpoint in clusterEndpoints)
+                {
+                    ServerEndPoint serverEndpoint = GetServerEndPoint(endpoint);
+                    if (serverEndpoint != null)
+                    {
+                        serverEndpoint.UpdateNodeRelations(clusterConfig);
+                    }
+                }
+
+                return clusterEndpoints;
             }
             catch (Exception ex)
             {
diff --git a/src/StackExchange.Redis/DebuggingAids.cs b/src/StackExchange.Redis/DebuggingAids.cs
index 00f8dde..36ecbcf 100644
--- a/src/StackExchange.Redis/DebuggingAids.cs
+++ b/src/StackExchange.Redis/DebuggingAids.cs
@@ -24,7 +24,10 @@ partial class ConnectionMultiplexer
         {
             lock (UniqueId)
             {
-                Trace(log.ToString(), caller); // note that this won't always be useful, but we only do it in debug builds anyway
+                if (log != null)
+                {
+                    Trace(log.ToString(), caller); // note that this won't always be useful, but we only do it in debug builds anyway
+                }
             }
         }
     }
diff --git a/src/StackExchange.Redis/ServerEndPoint.cs b/src/StackExchange.Redis/ServerEndPoint.cs
index c0da958..e91700b 100644
--- a/src/StackExchange.Redis/ServerEndPoint.cs
+++ b/src/StackExchange.Redis/ServerEndPoint.cs
@@ -193,29 +193,36 @@ public void SetClusterConfiguration(ClusterConfiguration configuration)
 
             if (configuration != null)
             {
-                Multiplexer.Trace("Updating cluster ranges...");
+                Multiplexer.Trace($"Updating cluster ranges for {EndPoint.ToString()}...");
                 Multiplexer.UpdateClusterRange(configuration);
                 Multiplexer.Trace("Resolving genealogy...");
-                var thisNode = configuration.Nodes.FirstOrDefault(x => x.EndPoint.Equals(EndPoint));
-                if (thisNode != null)
+                UpdateNodeRelations(configuration);
+                Multiplexer.Trace("Cluster configured");
+            }
+        }
+
+        public void UpdateNodeRelations(ClusterConfiguration configuration)
+        {
+            var thisNode = configuration.Nodes.FirstOrDefault(x => x.EndPoint.Equals(EndPoint));
+            if (thisNode != null)
+            {
+                Multiplexer.Trace($"Updating node relations for {thisNode.EndPoint.ToString()}...");
+
+                List<ServerEndPoint> replicas = null;
+                ServerEndPoint master = null;
+                foreach (var node in configuration.Nodes)
                 {
-                    List<ServerEndPoint> replicas = null;
-                    ServerEndPoint master = null;
-                    foreach (var node in configuration.Nodes)
+                    if (node.NodeId == thisNode.ParentNodeId)
                     {
-                        if (node.NodeId == thisNode.ParentNodeId)
-                        {
-                            master = Multiplexer.GetServerEndPoint(node.EndPoint);
-                        }
-                        else if (node.ParentNodeId == thisNode.NodeId)
-                        {
-                            (replicas ?? (replicas = new List<ServerEndPoint>())).Add(Multiplexer.GetServerEndPoint(node.EndPoint));
-                        }
+                        master = Multiplexer.GetServerEndPoint(node.EndPoint);
+                    }
+                    else if (node.ParentNodeId == thisNode.NodeId)
+                    {
+                        (replicas ?? (replicas = new List<ServerEndPoint>())).Add(Multiplexer.GetServerEndPoint(node.EndPoint));
                     }
-                    Master = master;
-                    Replicas = replicas?.ToArray() ?? Array.Empty<ServerEndPoint>();
                 }
-                Multiplexer.Trace("Cluster configured");
+                Master = master;
+                Replicas = replicas?.ToArray() ?? Array.Empty<ServerEndPoint>();
             }
         }
 
\ No newline at end of file
```

**Comment by NickCraver** [comment]
Fix landed for this in #1684 - ETA for release is this week :)
