### ISSUE TITLE
Should we be reporting 'InternalError' situations as issues - or are they "somewhat expected"?

### ISSUE THREAD

**Issue by mshiels** [StackExchange/StackExchange.Redis#1661]
In our cod elayers I hooked up Connection events and Internal error - but didn't expect to see a number of them the first time I totally took own my VPN connecting me to Redis.  I expected connection stuff, but not the InternalError - but if they are expected then I will change my mind set.  Thanks.!!

**Comment by mgravell** [comment]
Well: what does the message say? Kinda hard to comment based on that alone.

**Comment by NickCraver** [comment]
Need more info to do anything here - when reporting an error please always include the message! Closing this out, but happy to re-open with more info.
