### ISSUE TITLE
Latency spikes

### ISSUE THREAD

**Issue by skurik** [StackExchange/StackExchange.Redis#1665]
We are using Azure Cache for Redis, the client running in App Service Windows Web App in the same region.

We are going to use Redis as a storage for request quotas shared by all instances of the Web App, so we need to hit Redis at the beginning of each web/API request. Therefore, it's important for us that this does not take long. Given that we otherwise process the entire requests within ~ 150 ms, we decide to use 100 ms timeout for Redis operations and it still seems like a lot.

The only thing we are executing on Redis is a simple Lua script (touching a single key) and the Redis server basically doesn't even notice.

On average, it's fine. From the client's POV, the average latency is 1-5 ms. However, there are occasional spikes in the latency where some of the operations take as much as 2 seconds to finish. The max CPU usage during these latency spikes might be elevated (we are looking at max(CPU usage) on a per-minute basis), but it's not 100%.

I tried

* switching to .NET Core (we are running .NET Framework 4.7.2)
* async API
* multiple ConnectionMultiplexer instances and randomly assigning the commands to one of them

Nothing seemed to make any difference.

`MinThreads` are set to 1000. SNAT port exhaustion was not detected on the client either. We observe this behavior at sustained 8k requests/minute.

Typical exceptions:

```
Timeout performing EVAL (100ms), next: EVAL, inst: 61, qu: 0, qs: 5, aw: False, rs: ReadAsync, ws: Idle, in: 117, serverEndpoint: redis-server.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: wn0mdwk000011, IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=18,Free=8173,Min=200,Max=8191), Local-CPU: unavailable, v: 2.2.4.27433
Timeout performing EVAL (100ms), next: EVAL, inst: 7, qu: 0, qs: 12, aw: False, rs: ReadAsync, ws: Idle, in: 158, serverEndpoint: redis-server.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: wn0mdwk000011, IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=11,Free=8180,Min=200,Max=8191), Local-CPU: unavailable, v: 2.2.4.27433
Timeout performing EVAL (100ms), next: EVAL, inst: 6, qu: 0, qs: 11, aw: False, rs: ReadAsync, ws: Idle, in: 70, serverEndpoint: redis-server.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: wn0mdwk000011, IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=11,Free=8180,Min=200,Max=8191), Local-CPU: unavailable, v: 2.2.4.27433
Timeout performing EVAL (100ms), next: EVAL, inst: 5, qu: 0, qs: 10, aw: False, rs: ReadAsync, ws: Idle, in: 70, serverEndpoint: redis-server.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: wn0mdwk000011, IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=11,Free=8180,Min=200,Max=8191), Local-CPU: unavailable, v: 2.2.4.27433
Timeout performing EVAL (100ms), next: EVAL, inst: 4, qu: 0, qs: 9, aw: False, rs: ReadAsync, ws: Idle, in: 70, serverEndpoint: redis-server.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: wn0mdwk000011, IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=11,Free=8180,Min=200,Max=8191), Local-CPU: unavailable, v: 2.2.4.27433
Timeout performing EVAL (100ms), next: EVAL, inst: 3, qu: 0, qs: 8, aw: False, rs: ReadAsync, ws: Idle, in: 70, serverEndpoint: redis-server.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: wn0mdwk000011, IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=11,Free=8180,Min=200,Max=8191), Local-CPU: unavailable, v: 2.2.4.27433
```

I know you guys @mgravell and @NickCraver must have much higher request volume and I don't remember ever reading from you about latency spikes. Did you ever encounter issues like this one?

**Comment by NickCraver** [comment]
Is there any way for you to take a dump when the elevated CPU is happening? While I have no interest whatsoever in seeing your dump due to security reasons, I can help advise on seeing where threads are spending time in it if you can get a dump from the process. For example, you could start with my LinqPad example here: https://gist.github.com/NickCraver/d6292c0c7f93767686e8c5c89ed45c54 that's a quick way to analyze a dump including threads towards the bottom of the output.

**Comment by deepakverma** [comment]
@skurik I think I would run a benchmarking tool (such as https://redis.io/topics/benchmarks or https://github.com/RedisLabs/memtier_benchmark)  against the Cache to get a baseline for latency percentiles and then compare it with what you are seeing from the application.

**Comment by NickCraver** [comment]
Happy to reopen if there's more info here, but for no closing out lacking more info to give more specific advice.
