### ISSUE TITLE
Trying to debug into StackExchange.Redis - how to do a simple build for 4.6.1? Any ideas?

### ISSUE THREAD

**Issue by mshiels** [StackExchange/StackExchange.Redis#1666]
I have tried loading in VS 2017, 2019 but no platforms appear in target framekwork, just unsure how to kick start a build I can then debug into things.

We setup passwords and are finding a weird thign where Set string works fine, but Get just always returns 'nothing'.  Very basic but unsure what the heck to do to debug things.

**Comment by mgravell** [comment]
Do you have the .NET SDK installed? What happens if you just "dotnet build"
? Most likely, there is a global.json problem in the SDK version specified.

**Comment by mshiels** [comment]
I have every compiler from VC6 till 2019 installed but no pre-release stuff, and it seemed the code uses some pre-release language stuff?  

But yes we would like to be able to self host if needed for emergency situations etc, and would love to be able to build the code.  I was trying from within the framekwork but I can sure try command line too.

**Comment by mgravell** [comment]
No, there's no pre-release things. Again, what happened when you used "dotnet build" at the command line? In particular, I'm wondering whether perhaps it says that it can't find the specified SDK. In which case try *renaming* global.json

**Comment by mshiels** [comment]
I may also be behind but the errors I got were complaints about ‘language prerelease’ items,  but my VS 2019 is not up-to-date with the most recent stuff.  I’ll update later tonight when I get a chance to pull and try again. Sorry for any confusion.

**Comment by NickCraver** [comment]
@mshiels Did you get setup and going here?
