### ISSUE TITLE
Remove keys in Bulk 

### ISSUE THREAD

**Issue by rukhsarahmad-gep** [StackExchange/StackExchange.Redis#1667]
lets say in Azure Redis Cache, we have 3 shards ( 3 masters, 3*2 Replica). should we remove keys from all endpoints of redis cluster or StackExchange.Redis will take care to remove it from all node.

sample code 
foreach (var endpoint in clusterEndpoints)
                {
                    var server = GetServer(endpoint);
                    if (!server.IsReplica) //Deal with only Primary Server and not the Replica
                    {
                        string searchKey = userid.HasValue ? "{" + userid + "}:*" + key + "*" : $"*{key}*";
                        IEnumerable<RedisKey> keys = server.Keys(pattern: searchKey, pageSize: 5000);
                        if (keys.Any())
                        {
                            //Note: If the userid wasn't provided, then the bulk deletion may fail, if it has multiple/different keys {userid }. Since it doesn't support multi-hash/key in single operation, in that case delete items separately.
                            //Note: Ideally Keys/Scan operation is expensive and we need to avoid, if needed scan atleast by hash/key {userid } rather by string. So its better to pass always userid for RemoveAll.
                            if (!userid.HasValue)
                            {
                                List<Task> delTasks = new List<Task>();
                                foreach (var item in keys)
                                {
                                    Task<bool> keyDeleteTask = cache.KeyDeleteAsync(item, flags: RedisCommandFlags);
                                    delTasks.Add(keyDeleteTask);
                                }
                                await Task.WhenAll(delTasks);
                            }
                            else
                            {
                                await cache.KeyDeleteAsync(keys.ToArray(), flags: RedisCommandFlags);
                            }
                        }
                    }
                }

**Comment by mgravell** [comment]
The keyspace is shared, so each key only needs to be removed from a single
primary node. The library deals with routing them accordingly. I have been
toying with an extension to the delete API so that it does the grouping
internally, so it sends some number of varadic deletes to nodes based on
how they shard, but it isn't clear that this will be *significantly* faster
- just more convenient in some cases. On the case when you're using SCAN,
it wouldn't be desirable *anyway*, due to the sizes involved.

**Comment by rukhsarahmad-gep** [comment]
//redis ConnectionMultiplexer
 static Lazy<ConnectionMultiplexer> lazySessionConnection = new Lazy<ConnectionMultiplexer>(() =>
        {
            var configOptions = ConfigurationOptions.Parse(redisconnection, true);
            ConnectionMultiplexer cm = ConnectionMultiplexer.Connect(configOptions);
            cm.PreserveAsyncOrder = false;
           
            return cm;

        });
//redis connection value	
	 public static ConnectionMultiplexer RedisCon
        {
            get
            {
                return lazyConnection.Value;
            }
        }
//redis server
	public static IServer RedisServer
        {
            get
            {
                var endpoints = Caching.RedisConfig.RedisCon.GetEndPoints();
                var server = Caching.RedisConfig.RedisCon.GetServer(endpoints.First());
                return server;
            }
        }
//redis database
	 static IDatabase GetRedisDB()
        {
            return RedisConfig.RedisCon.GetDatabase();
        }
// extention method
		public static void Remove(this IDatabase cache, string key)
        {
            try
            {
                cache.KeyDelete(key, flags: demand master flag);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
		
	Is this the below code remove from all 3 masters or only from one master?
		 IDatabase rdb = GetRedisDB();
          rdb.Remove(key);

**Comment by mgravell** [comment]
Each key is only owned by one primary, so it isn't *possible* to "remove from all 3 masters" - 2 of the masters will give an error about the incorrect slot/shard being used. The library routes requests to the correct nodes.

**Comment by NickCraver** [comment]
Closing this out to cleanup - the advice above is correct: simplify to letting Redis handle it, there's no need to hit each node, etc.
