### ISSUE TITLE
dotnet5 very many Timeout

### ISSUE THREAD

**Issue by ashuai** [StackExchange/StackExchange.Redis#1669]
Hi
Redis server - 5.0.3
StackExchange.Redis (2.2.4)
Dotnet 5

The project is migrated from dotnet framework to dotnet5. The Stress Test on dotnetfx is normal, and the redis timeout frequently under dotnet5

-----
Timeout performing PING (5000ms), next: PING, inst: 1, qu: 0, qs: 15, aw: False, rs: ReadAsync, ws: Idle, in: 88, in-pipe: 0, out-pipe: 0, serverEndpoint: 127.0.0.1:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: vm10-0-0-35, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=33,Free=32734,Min=4,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)","stacktrace":"   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2817
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
-----

Timeout performing PING (5000ms), next: SETEX SELL:637465903267729708, inst: 4, qu: 0, qs: 11, aw: False, rs: ReadAsync, ws: Idle, in: 75, in-pipe: 0, out-pipe: 0, serverEndpoint: 127.0.0.1:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: vm10-0-0-35, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=27,Free=32740,Min=4,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)","stacktrace":"   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2817
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54

------

Timeout performing SETEX (5000ms), next: SETEX SELL:637465903267729708, inst: 1, qu: 0, qs: 8, aw: False, rs: ReadAsync, ws: Idle, in: 54, in-pipe: 0, out-pipe: 0, serverEndpoint: 127.0.0.1:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: vm10-0-0-35, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=27,Free=32740,Min=4,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)","stacktrace":"   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2817
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54

------

Timeout performing PING (5000ms), next: PING, inst: 2, qu: 0, qs: 30, aw: False, rs: ReadAsync, ws: Idle, in: 193, in-pipe: 0, out-pipe: 0, serverEndpoint: 127.0.0.1:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: vm10-0-0-35, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=35,Free=32732,Min=4,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)","stacktrace":"   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2817
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54

------

Timeout performing PING (5000ms), next: GET lock:dishpay:170_1610964756260, inst: 2, qu: 0, qs: 29, aw: True, rs: ReadAsync, ws: Idle, in: 192, in-pipe: 0, out-pipe: 0, serverEndpoint: 127.0.0.1:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: vm10-0-0-35, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=77,Free=32690,Min=4,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)","stacktrace":"   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2817
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54

-------------

**Comment by h0wXD** [comment]
I have received same timeout problems on a benchmark test as well on .NET core 2.1, it runs fine with ~500 bytes value entries, 1xxxx of throughput/second, but once we try the same benchmark on keys which range from few Kb up to a Mb it'll start showing many timeout errors, and performance drops dramatically, down from 5 digits to around 30 throughput/sec on a 32 core machine, it's a .NET client issue, which I was able to confirm as there were no problems with other clients retrieving any/same values of that size (even while the benchmark was running). Are you experiencing this problem on small or big sized cache entries or just all?

**Comment by pianoman4873** [comment]
@h0wXD   the other clients you tested with were not .NET clients at all  ?

**Comment by Goolyio** [comment]
I am also getting similar errors in .NET 5, have you managed to debug any of it yet? It seems to be more of an issue when more clients are connected.

**Comment by bespalov-alex** [comment]
Have you tried tuning ThreadPool.SetMinThreads? https://stackexchange.github.io/StackExchange.Redis/Timeouts.html

**Comment by NickCraver** [comment]
The commonality in the exceptions here is a high busy thread count on the worker side, which likely means your app side is overloaded in spikes here. Setting min threads (see above) may be an option to mitigate some spikes, but overloading your available compute capacity is an issue and if this is an intermittent issue that's a temporary overload, a higher peak timeout may be in order.

It'd be handy to see _why_ so many threads are busy (you could assess this with a dump), normally this is something `async`/`await` style patterns would help with - freeing up thread pool resources because so many threads are possibly idle waiting on off-box I/O and such. If you think that's the case, it'd be a good idea to async-ify all the paths most suited for it.
