### ISSUE TITLE
Timeout exception with SE.Redis version 2.2.4

### ISSUE THREAD

**Issue by shoguns6** [StackExchange/StackExchange.Redis#1671]
Am getting frequent timeout exception as below.  I have checked the CPU status of azure app service which calls the cache and the redis cache itself.

Both CPU are well below 50% usage.  Also have increased the timeout from 5sec to 15 secs as suggested in one of the blogs. 
Additionally, have implemented lazy connection mulitplexer, but still keep getting timeouts.

Any insights/suggestions are welcome..

Timeout awaiting response (outbound=0KiB, inbound=0KiB, 15813ms elapsed, timeout is 15000ms), command=SET, next: SELECT, inst: 0, qu: 0, qs: 2, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: xxxx.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: yyy, IOCP: (Busy=3,Free=997,Min=650,Max=1000), WORKER: (Busy=13,Free=32754,Min=700,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

Timeout awaiting response (outbound=0KiB, inbound=0KiB, 16500ms elapsed, timeout is 15000ms), command=SET, next: SELECT, inst: 0, qu: 0, qs: 2, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: xxxx.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: yyy, IOCP: (Busy=18,Free=982,Min=650,Max=1000), WORKER: (Busy=14,Free=32753,Min=700,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) 

Timeout awaiting response (outbound=0KiB, inbound=0KiB, 15485ms elapsed, timeout is 15000ms), command=SET, next: INFO, inst: 0, qu: 0, qs: 3, aw: False, rs: ReadAsync, ws: Idle, in: 39, serverEndpoint: xxx.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: yyy, IOCP: (Busy=5,Free=995,Min=650,Max=1000), WORKER: (Busy=27,Free=32740,Min=700,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by lxy-l** [comment]
I had the same problem. centos8+.net 5

**Comment by shoguns6** [comment]
@lxy-l ... how you sorted it? or is it still happening?

**Comment by lxy-l** [comment]
There is no solution，I'm going to change it to csrediscore

**Comment by dbraaten42** [comment]
I had this issue against AWS Elastic Cache Redis when the database number was being changed from 0.  Once we set the database number to 0 the issue went away.  In the past we received can't change database number errors when the database number was set incorrectly.

**Comment by juniormayhe** [comment]
Something similar here https://github.com/StackExchange/StackExchange.Redis/issues/1680

**Comment by NickCraver** [comment]
@deepakverma pinging for awareness, seems to be a stall in getting responses

**Comment by NickCraver** [comment]
For anyone still hitting timeout issues - please try latest where we've added additional logging (and more specific to `net5.0`+) that helps advise more on debugging. We can't say why in the environment we're waiting so long for a response, but the additional thread pool data in exceptions may help indicate if there are other app stalls in play. Going to close this out to tidy/consolidate.
