### ISSUE TITLE
Public IP Range for Redis Cache

### ISSUE THREAD

**Issue by ujwalkasth** [StackExchange/StackExchange.Redis#1672]
we are unable to connect to Redis Cache due to port 6379 and 6380 blocked on our corporate firewall. In order to unblock we need list of all ip for cache. 
Is there a way we can get the list of ips ? we have large number of redis cache instances deployed. its not possible to keep checking the ip for every cache as the ips keep changing. 
This is affecting our production environment. 
Can someone please suggest on how to resolve this issue ?

**Comment by mgravell** [comment]
Is this Azure redis cache or similar? If so, you'd presumably need to
contact your vendor and ask them for the IP ranges to cover. The library
*can* tell you the nodes topology, but that wouldn't really help you if you
need to keep unblocking them. To be honest, this sounds like an issue
between you and your vendor.

**Comment by ujwalkasth** [comment]
@mgravell this is azure redis cache. Thanks for your prompt reply. I do understand that the ip's are dynamic and they keep changing. In this case, we are not sure on how to move ahead. Do you suggest any possible way ?

**Comment by mgravell** [comment]
Again, this is a question for Azure. I can tell you how to extract the IPs
needed via the API, but that doesn't really help since they will keep
changing and you presumably can't open the ports through application code
(if you can, it makes the firewall redundant!).

**Comment by WatersJohn** [comment]
Marc's being very polite, but this is not a StackExchange.Redis library issue.  

Look at either vnet integration for your redis cache or private endpoints. More documentation is here: https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-network-isolation

These won't help though if you are accessing Azure Redis from on-prem or another cloud provider, although that's (hopefully) not what is being done given the latencies.

**Comment by NickCraver** [comment]
Agreed this one isn't for us as a client library, closing out to cleanup.
