### ISSUE TITLE
Blocking operations

### ISSUE THREAD

**Issue by lukasvosyka** [StackExchange/StackExchange.Redis#1675]
Hi Marc,

I am investigating on Redis as a reliable message broker and found BxPOP and BxMOVE not being supported by your lib as of now. Then I stumbled across a post from you on Twitter https://twitter.com/marcgravell/status/1226442958377013249 mentioning that with Redis 6 you might be able to change the multiplexing/pipelining to support blocking operations.

Do you have any updates on this whether this still planned or in the making? If so, any ETA? 

It would be great having the native blocking operations available a the C# client side instead of work around this with an additional Pub Sub mechanism to inform consumers.

Appreciate your work! It's a great library!

Cheers,
Lukas

**Comment by mgravell** [comment]
It is absolutely planned, for many reasons including this. Unfortunately I
haven't had time to look at it; this isn't my paid work, and lockdown gives
me less time for personal projects, not more.

**Comment by NickCraver** [comment]
Collapsing into #1961 where we're gathering ideas for a plan here!
