### ISSUE TITLE
Get all the keys in redis？？

### ISSUE THREAD

**Issue by GeorGeWzw** [StackExchange/StackExchange.Redis#1678]
Do you support getting all the keys in redis later?

**Comment by flybalance** [comment]
> Do you support getting all the keys in redis later?

ConnectionMultiplexer connectionMultiplexer = await ConnectionMultiplexer.ConnectAsync(configurationOptions);
var db = connectionMultiplexer.GetDatabase();
var server = connectionMultiplexer.GetServer(connectionMultiplexer.GetEndPoints()[0]);
server.Keys(db.Database, "yourkeys*");

**Comment by mgravell** [comment]
For more info of *why* this is there:
https://stackexchange.github.io/StackExchange.Redis/KeysScan.html

**Comment by omriman12** [comment]
Hi mark, is there a way to query the keys only from a slave node? like in the command flags

**Comment by mgravell** [comment]
If you're using `GetServer()`, you've already determined the node to be used, so `PreferReplica` (etc) won't have any effect. You would have to look at the various endpoints/servers and determine a node based on the `IsReplica` of each.

**Comment by omriman12** [comment]
ok great, IsReplica is good enough for me

**Comment by NickCraver** [comment]
Closing this out to cleanup!
