### ISSUE TITLE
No connection is active/available  | UnableToConnect

### ISSUE THREAD

**Issue by Vikakuma** [StackExchange/StackExchange.Redis#1681]
Trying to upgrade StackExchange.Redis from 1.2.6 to 2.2.4 on a .NET Platform v4.6.2

Consistently getting this error while connecting with Azure Redis cache.
I tried increasing the keepAlive time and 
Connection configurations are 
AbortOnConnectFail = false,
SslProtocols = TLS12 

Any pointers would be appreciated.

System.AggregateException: One or more errors occurred. ---> Microsoft.Online.CacheService.Client.CacheServiceException: RedisCacheClient exception encountered when performing a TryGetAsync operation ---> Microsoft.Online.Cache.Redis.RedisCacheClientException: Redis Connection Error. ---> StackExchange.Redis.RedisConnectionException: **No connection is active/available to service this operation:** TTL+GET {4e6be148-aff5-471d-b107-XXX+h6w5ndd8o2.YYY-XXX.com}:h6w5n9c8o2.YYY-XXX.com; UnableToConnect on XXX-YYY-onebox.redis.cache.windows.net:6380/Interactive, Flushed/ReadAsync, last: ECHO, origin: ResetNonConnected, outstanding: 0, last-read: 4s ago, last-write: 4s ago, keep-alive: 60s, **state: ConnectedEstablishing**, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.2.4.27433, mc: 1/1/0, mgr: 10 of 10 available, clientName: AZICCCXXXXXVM1, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=2,Free=32765,Min=8,Max=32767), v: 2.2.4.27433 ---> System.AggregateException: One or more errors occurred. ---> **StackExchange.Redis.RedisConnectionException: UnableToConnect on** XXX-YYY-onebox.redis.cache.windows.net:6380/Interactive, Flushed/ReadAsync, last: ECHO, origin: ResetNonConnected, outstanding: 0, last-read: 4s ago, last-write: 4s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.2.4.27433

Thanks

**Comment by webgio** [comment]
Same here, same version works with the same code in a Linqpad script but fails in a Aure Function run locally.

**Comment by webgio** [comment]
> Same here, same version works with the same code in a Linqpad script but fails in a Aure Function run locally.

Hey, sorry, just found out I just had a problem with my connection string.

**Comment by Vikakuma** [comment]
Increasing the ConnectTimeout to 1min resolves this issue.
