### ISSUE TITLE
RedisValue.TryParse(out long) successfuly parses a null value

### ISSUE THREAD

**Issue by NimaAra** [StackExchange/StackExchange.Redis#1685]
Given the following:

```
RedisValue input = new(null);
bool success = input.TryParse(out long output);
```

It successfully parses the `null` as `0`; I would expect `TryParse` to take into account `input.IsNullOrEmpty` before attempting to parse.

**Comment by mgravell** [comment]
This is deliberate and correct. Redis has ... interesting semantics, and we're trying to be comparable. A key that doesn't exist is *both* null *and* zero to redis, depending on what you do next.
