### ISSUE TITLE
StackExchange.Redis SEO can improve

### ISSUE THREAD

**Issue by tomer-w** [StackExchange/StackExchange.Redis#1686]
Hi,

I know this is super small comment but if you search for the following search terms in GitHub you won't find this important project. This is pity. I assume it is as your project description doesn't include anything like .NET or c# in its text.

To repro try:
https://github.com/search?q=.net+redis
https://github.com/search?q=c%23+redis

Thanks, 
Tomer.

**Comment by NickCraver** [comment]
We'll consider some tweaks there potentially, thanks :)
