### ISSUE TITLE
Sets don't have a way to set expirations

### ISSUE THREAD

**Issue by alowinfield** [StackExchange/StackExchange.Redis#1687]
We can give them an expiration via the EXPIRE command, which we can execute directly using the Execute() method, but having it built into the library would be great.

Here's an example showing how I'm currently adding an expiration to sets, with a String expiration for comparison.

```c#
var redis = ConnectionMultiplexer.Connect(connection_url);
var db = redis.GetDatabase();
var expiration = 100;  // for example

// storing a string with an expiration
db.StringSet(some_key, some_value, TimeSpan.FromSeconds(expiration));

// storing a set value
db.SetAdd(set_key, value_to_add_to_set);
// the set was created if it did not already exist
// now we need to manually give the set an expiration
db.Execute($"EXPIRE '{set_key}' {expiration}");
```

**Comment by mgravell** [comment]
Are you asking for `KeyExpire[Async]` ?

**Comment by mgravell** [comment]
Btw, the reason it doesn't exist as a parameter on the command is because
there's no corresponding redis command

**Comment by alowinfield** [comment]
KeyExpire is what I was looking for, thanks.

**Comment by NickCraver** [comment]
Closing out to cleanup :)
