### ISSUE TITLE
Timeout issue - Umbraco / .Net framework 4.8

### ISSUE THREAD

**Issue by lazarus-cm** [StackExchange/StackExchange.Redis#1688]
`Timeout performing GET (2000ms), next: GET direct-live-Dictionary, inst: 11, qu: 0, qs: 5, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: xxxx.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: xxx, IOCP: (Busy=2,Free=998,Min=200,Max=1000), WORKER: (Busy=96,Free=32671,Min=200,Max=32767), v: 2.2.4.27433`

I'm experiencing poor reliability with an Azure Redis Cache, accessed from a .Net Framework v4.8 site.

Looking at the exception message I don't think there are any obvious causes for this timeout so I'm not really sure what action to take. I have of course reviewed the timeout documentation.

The cache is not anywhere near memory max (1GB capacity, currently around 300MB in use) and load is minimal (0-3%).

I am not caching anything large (most items are well under 100KB, none are more than around 350KB)

I am using the recommended pattern for creating the ConnectionMultiplexer.

Notable settings:
`abortConnect=False`
`connectTimeout=9000`
`syncTimeout=2000`

Any advice greatly appreciated.

**Comment by NickCraver** [comment]
The key here is `WORKER: (Busy=96,Free=32671,Min=200,Max=32767)` that means your CPU was _very_ busy processing something, and wasn't able to get to processing the results. Note that our default timeout for Azure is 5,000ms because of the latency involved there as well, if you're lowering it to 2,000, there will be more timeouts when they have stalls as a result.

**Comment by deepakverma** [comment]
@lazarus-cm in addition to Nick's comment above, you could also take a dump of the process when timeout occurs which would likely give you an idea of what those worker threads are busy with and possibly ideas of improvement in the application.

**Comment by NickCraver** [comment]
Closing this out to cleanup - see above for anyone hitting this with slammed CPU.
