### ISSUE TITLE
Password string in ConnectionMultiplexer constructor?

### ISSUE THREAD

**Issue by KevinBurton** [StackExchange/StackExchange.Redis#169]
I have a configuration string "127.0.0.1:6379,password=password" that I am passing to the ConectionMultiplexer and I am getting an exception. I tried downloading the source to give more information but the source and the binary that I am using seem to be out of sync. Could this be looked into?

This snippet of code illustrates the problem:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using StackExchange.Redis;

namespace RedisAzure {
    class Program {
        static void Main(string[] args) {
            ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("127.0.0.1:6739,password=password");
            IDatabase db = redis.GetDatabase();
            TimeSpan elapsed = db.Ping();
            Console.WriteLine("Elapsed {0}", elapsed);
        }
    }
}

I tried adding a test to the source and it worked. Is there a possibility that the latest NuGet package does not reflect the latest source? My NuGet manger says I have 1.0.394.

**Comment by KevinBurton** [comment]
So I don't understand. I added a test to the zip of the source that I downloaded and the test worked. So I thought I will just take that DLL and put it in the package directory where the NuGet package is installed. I replaced the NuGet version of the assembly with the one that I compiled from the source and re-ran my test and it failed.

**Comment by MaximKojine** [comment]
Hi @KevinBurton
I am wondering - why did you close this issue? Is it resolved?
Thanks
