### ISSUE TITLE
Process RedisResult using XREADGROUP with Execute() fails

### ISSUE THREAD

**Issue by developez** [StackExchange/StackExchange.Redis#1691]
I connected properly, i execute the method "Execute" without exceptions, i can see the values inside de r object (RedisResult) but when I want to use "ToDictionary" I got an exception. The debugger said me that r is an ArrayRedisResult, but i cannot instanciate the object because is private.

The raw command using redis-cli is something like this:

```
127.0.0.1:6379> XREADGROUP GROUP g1 c1 COUNT 1 BLOCK 0 STREAMS logchannel1 >
1) 1) "logchannel1"
   2) 1) 1) "1613562657739-0"
         2) 1) "campo1"
            2) "112333"

```
```
try
{
    RedisResult r = redis_db.Execute("XREADGROUP", new string[] { "GROUP", "g1", "c1", "COUNT", "1", "BLOCK", "1000", "STREAMS", "logchannel1", ">" });

    if (r.IsNull)
    {
        string line = Log.compose(DateTime.Now, "ERROR", "c1", "redis result: " + r.Type + " null ", null);
        Trace.WriteLine(line);
    }
    else
    {           
        **var r = r.ToDictionary(); // FAILS**
        string line = Log.compose(DateTime.Now, "ERROR", "c1", "redis result: " + r.Type + " " + r.ToString(), null);
        Trace.WriteLine(line);
    }
}
catch(Exception ex)
{
    string line = Log.compose(DateTime.Now, "ERROR", "c1", ex.Message, null);
    Trace.WriteLine(line);
}
```

**Comment by NickCraver** [comment]
I'm trying to follow here - I want to back up first though: the latest version of the client has the `Stream*` APIs (e.g. `StreamReadGroupAsync`) to handle all of this for you - are those not working for some reason? It's a much easier path, so want to see what the friction there is first.
