### ISSUE TITLE
Multi-target .NET Core 3.1 / .NET Core 5.0 for latest package versions (2.2.x)

### ISSUE THREAD

**Issue by nmccalme** [StackExchange/StackExchange.Redis#1697]
Hello,

We're currently using package version 2.1.58, and we're running into an issue noted in [issue 1438](https://github.com/StackExchange/StackExchange.Redis/issues/1438).  This is noted as fixed in [PR 1585](https://github.com/StackExchange/StackExchange.Redis/pull/1585), which is included in package version 2.2.3.  However, 2.2.3 is targeted at .NET Core 5.0 packages, and pulls in a bunch of dependency upgrades when we try to add it to our .NET Core 3.1 projects.  Would it be possible to set up multi-targeting so that we can stay on the LTS release and still get the benefit of fixes?

**Comment by mgravell** [comment]
If you check https://www.nuget.org/packages/StackExchange.Redis/, we already milti-target, and there exists a .net core 3.1 target. So... it isn't clear to me what you would have us do differently.

If you mean additional NuGet dependencies: yes, we have taken updates. That doesn't mean that they are ".NET 5" packages. They are just additional milti-target dependencies that we've updated to the current versions.

**Comment by nuttytree** [comment]
I have to disagree on that, the 3.1.x packages were released when .NET Core 3.1 was released and the 5.0.x packages were released when .NET 5.0 was released.  And while this 5.0 package may work fine I have had issues in the past pulling in packages versioned above the current .NET Core version and having one tends to lead down a rabbit hole of getting more and more of them.

**Comment by kimschurmann** [comment]
> That doesn't mean that they are .NET 5, though

True - but there are System 5.0.0 packages that conflicts with .netcore 3.1 packages.

**Comment by NickCraver** [comment]
I think we may have a misunderstanding of how the versioning works here. Yes, the Microsoft packages are 5.x as a release number but most of ***them*** multi-target downlevel to the LTS as well. So you'd be getting the version for your target framework, not something for .NET 5.x just because it *also* contains that. In fact, the tooling shouldn't allow you to get something you can't use in your target...that's kinda the whole point of targeting: to add those assurances.

**Comment by NickCraver** [comment]
Closing this out to cleanup.
