### ISSUE TITLE
NOPERM this user has no permissions to run the 'setex' command or its subcommand after move to redis 6 with ACL

### ISSUE THREAD

**Issue by sebaim** [StackExchange/StackExchange.Redis#1699]
We moved from redis cluster 5 to redis cluster 6 with ACL and are having "NOPERM this user has no permissions to run the 'setex' command or its subcommand" after update.

We are having this issue on db.StringSet with expiration (without expiration is working fine)

As a workaround we change it to a db.StringSet without expiration and a call with db.KeyExpire after that.

We tried to add 'setex' executions permissions with "acl setuser OUR_USER +setex" but dont see changes con ACL getuser OUR_USER.

It have following command permissions:
"commands"
6) "-@all +@keyspace +@write +@set +@sortedset +@hash +@string +@fast +@connection +@transaction -dump -migrate -exec -restore -del -hvals -zunionstore -psetex -msetnx +cluster|INFO -stralgo -zinterstore -rpoplpush -hkeys -hscan -pfmerge -setrange -georadius -xtrim -bitfield -brpoplpush -georadiusbymember -getrange -linsert -lrem -bitop -lset -object -geoadd -zremrangebyscore -restore-asking -zrevrange -lastsave -blpop -client -zremrangebyrank -zremrangebylex -zrevrangebyscore -brpop -rename -xreadgroup -swapdb -hgetall -role -zrevrangebylex -pfdebug -wait -zrange -setbit -zrangebyscore +info -xgroup -substr -randomkey -scan -zscan -mset -zrangebylex -flushdb -ltrim"

We think is related with some authentication problem after node redirect.

We are using StackExchange.Redis 2.2.4 version

StackTrace:
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2815
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable`1 expiry, When when, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2536
 

Do you have any idea what could be the issue?

Thanks!

Seba

**Comment by mgravell** [comment]
This *sounds* like an ACL config issue? The fact that calling StringSet and
KeyExpire works suggests it isn't anything to do with routing/redirect,
since routing is based purely on keys. The library doesn't determine ACL
failures - that is entirely server. Does SETEX work when issued via
redis-cli when logged in as the appropriate user?

**Comment by mgravell** [comment]
Also, the -psetex is suspicious

**Comment by NickCraver** [comment]
@sebaim Can you shed more light on the above?

**Comment by sebaim** [comment]
Im Sorry, it was related with a bad ACL configuration for the user, I will close the issue.

**Comment by boozybatsMain** [comment]
maybe you share some info with us?

**Comment by jeffdyke** [comment]
Why doesn't anyone ever show their issue

**Comment by sebaim** [comment]
Hi @jeffdyke , Im sorry for it, to be honest Im not sure 100% the root cause, because it was not solver by me. But Im sure it was related to ACL, I mean user I was using didnt have permissons to write some keys, or to run some command.
I think it was because of I was using a user "X", and was trying to set a key like "Y:cache_key", and the user X didnt have these permissons. Hope it can help to solve your issue.
