### ISSUE TITLE
Order of async commands with FireAndForget

### ISSUE THREAD

**Issue by msp-abc** [StackExchange/StackExchange.Redis#1701]
Is the order of commands sent to redis guaranteed when using the async methods along with the FireAndForget flags? I tried to follow the code here in GitHub, but I failed to find the answer unfortunately.

In my case, I have the following code:

```csharp
await redisDb.HashSetAsync(key, name, value, flags: CommandFlags.FireAndForget);
await redisDb.KeyExpireAsync(key, TimeSpan.FromMinutes(5), flags: CommandFlags.FireAndForget);
```
(`redisDb` is the `IDatabase` returned by the `ConnectionMultiplexer`)

But I can see a small percentage of the keys having a TTL of -1. I'm trying to figure out if it's some rare condition in which the order of those commands are switched, or if it's a problem in our code. I couldn't see how else this case might happen, without the server crashing in between those commands.

I wonder if there's a right way of sending those commands (not using FireAndForget or run inside a transaction?)

I'm using `StackExchange.Redis 2.2.4` in a dotnetcore 3.1 web api.

Any help would be greatly appreciated.

**Comment by mgravell** [comment]
It *should* be ordered, but I'd probably waver somewhat before saying that it is an absolute guarantee. In terms of *guaranteeing* ordering, there are 3:

- wait/await all operations, i.e. don't use fire-and-forget (although this has a potential issue if the first command completes and the second disappears into the ether)
- use MULTI/EXEC (the transaction API in SE.Redis)
- use Lua (`ScriptEvaluate` etc)

**Comment by msp-abc** [comment]
Thanks for the quick response. 

I went with the first option, and removed the FireAndForget for the `HashSetAsync` and it fixed the issue.
