### ISSUE TITLE
Timeout performing EVAL

### ISSUE THREAD

**Issue by sean-redmond** [StackExchange/StackExchange.Redis#1703]
I have noticed in the error logs we hit errors like the below a few times a week, I am having trouble tracking this down and wondered if anyone had any hints of things to check. 

`Timeout performing EVAL(5000ms), next: EVAL, inst: 61, qu: 0, qs: 6, aw: False, rs: ReadAsync, ws: Idle, in: 65536, in-pipe: 0, out-pipe: 0, serverEndpoint: <<hidden>>.cache.amazonaws.com:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: <<hidden>>, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=9,Free=32758,Min=2,Max=32767), v: 2.1.30.38891 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

**Comment by NickCraver** [comment]
Is there anything funky with buffers on this system? What strikes me is 65,536 incoming bytes on the wire exactly 2^16 seems like we're hitting a 64kb buffer limit upstream _potentially_. Everything else looks calm enough, though it could be order exhaustion if we're running on 1 core. Do you have a CPU utilization level when this hits?
