### ISSUE TITLE
"The operation has timed out" issue in Redis Subscribe and unsubscribe

### ISSUE THREAD

**Issue by siva24anand** [StackExchange/StackExchange.Redis#1704]
Recently we upgraded the StackExchange.Redis from 1.2.6 to 2.1.28 and we faced the operation time out issue very frequently. we have seen this issue in latest version as well. So we downgraded back to 1.2.6 and this issue is completely stopped.

Error:
System.TimeoutException: The operation has timed out.
System.TimeoutException at StackExchange.Redis.ConnectionMultiplexer.Wait

Operation:
Subscribe(Channel)
Unsubscribe(Channel) (_error occurred mostly in this_)

Environment:
Azure Redis cache(Premium P4)

Application:
.Net Web API deployed in Azure API

**Comment by NickCraver** [comment]
Can you post the full exception? The latest versions have more info, so we also recommend using the latest release. It has a lot of data to tell us why.

**Comment by jdivy** [comment]
We are on 2.2.4 and are noticing something similar.  I just updated our unit tests to use 2.2.50 and this particular timeout doesn't seem to present anything to me other than a generic system timeout:
```
System.TimeoutException: The operation has timed out.
   at StackExchange.Redis.ConnectionMultiplexer.Wait(Task task) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 607
   at StackExchange.Redis.RedisBase.Wait(Task task) in /_/src/StackExchange.Redis/RedisBase.cs:line 37
   at StackExchange.Redis.RedisSubscriber.Unsubscribe(RedisChannel& channel, Action`2 handler, ChannelMessageQueue queue, CommandFlags flags) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 516
   at StackExchange.Redis.RedisSubscriber.StackExchange.Redis.ISubscriber.Unsubscribe(RedisChannel channel, Action`2 handler, CommandFlags flags) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 512
```

We're implementing our own version of a message bus on top of Redis lists + pub/sub.  In production we're actually seeing a subscribe call time out, not the unsubscribe I'm seeing in my test. We certainly want to actually "subscribe" or unsubscribe so not using flags.FireAndForget which looking at the code would skip the wait but presumably won't guarantee we'd be subscribed.  I'm currently in the weeds of trying to figure out exactly why we're seeing these as our production redis primary/secondary cluster isn't under any kind of crazy load.  Perhaps there is a poor assumption we're making.

**Comment by jdivy** [comment]
@NickCraver wondering if there is anything else I can do to get debug data when we hit a timeout in a subscribe or unsubscribe call?

**Comment by jdivy** [comment]
FYI turns out our main problem was a deadlock of our own doing

**Comment by Tonay** [comment]
I have the same issue in unsubscribe (timeout exception). How did you find our figure out that your problem was a deadlock. Is it in sql or other database deadlock or redis deadlock? And how can i inspect deadlocks if it from redis?

Please let us explain :)

**Comment by NickCraver** [comment]
@Tonay a memory dump when it happens and analyzing what was stuck where (e.g. Thread and Tasks view in Visual Studio) is a good approach here.

**Comment by NickCraver** [comment]
Same advice above to anyone hitting this: if it's an app deadlock, a memory dump analysis is your best bet if you're unable to repro locally in a debugger. VS has excellent tooling for this.

**Comment by kierenj** [comment]
@NickCraver Looks like this is poping up for me in production fairly regularly at the moment.

Would it be any use to detect this, and, in the catch, have the process invoke `dotnet-dump collect` on itself (https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump) ? If it's a full dump, there's a chance there might be customer data involved, so wouldn't want to post here but could go through on a screen-share or send to you direct?

The project I'm working on also uses `Microsoft.Diagnostics.Runtime` in fun ways to look at its own threads/call stacks/heap objects. If nothing else, could get stack traces for all managed threads.. although I suspect object values might be more handy?

**Comment by NickCraver** [comment]
@kenji-andoh Stacks would be awesome if you can share - if you can capture the dump then we could remotely suggest some things to check in the dump but stacks and dumps are good - I'm adding some debug diagnostic outputs to ConnectionMultiplexer as a follow-up to the current work, just getting subscriptions and backlog sorted at the moment (and there'd be decent change conflicts).

**Comment by kierenj** [comment]
Of course, since implementing automatic collection of those stats, nothing... I'll be monitoring my logs for the next few days at least. 

![image](https://user-images.githubusercontent.com/82343/150099448-3ce91fd3-1f7b-4bac-a8b1-bd4c77fe9274.png)
