### ISSUE TITLE
[QUESTION] It was not possible to connect to the redis server(s) ConnectTimeout

### ISSUE THREAD

**Issue by QianYS** [StackExchange/StackExchange.Redis#1707]
![image](https://user-images.githubusercontent.com/28479614/111124421-75f7ad80-85ab-11eb-9cb6-09b080ed3c5e.png)
StackExchange.Redis  version 2.1.58   .net Core 3.1
I have 2 service for webApi（mng and  user）
when I publish my service（mng）  It's no problem ，  but other service（user） always has problem  like the picture
restart service（user）  someTimes OK ,  someTimes  Not  
72lines: 
![image](https://user-images.githubusercontent.com/28479614/111128438-da1c7080-85af-11eb-91b4-c08d9f1adc74.png)
 in my api 
![image](https://user-images.githubusercontent.com/28479614/111128346-bce7a200-85af-11eb-8bc8-c05d823cdde3.png)

How can I solve it

**Comment by mgravell** [comment]
DNS?
Is the IP routable?
Is port 6379 open (firewall)?
Is there any TLS etc involved (especially redis 6)
Can redis-cli talk to that server from that node?

**Comment by NickCraver** [comment]
You can pass a logger into `.Connect()`, the recommendation is to do that to get a much richer log detailing what went sideways in connecting.
