### ISSUE TITLE
When opening a ConnectionMultiplexer connection without performing any other commands, I get two open connections on Redis server, is this correct?

### ISSUE THREAD

**Issue by DreyMiceli** [StackExchange/StackExchange.Redis#171]
Hi,

Just doing the below:

        private static void OpenConnection()
        {
            ConnectionMultiplexer redis = ConnectionMultiplexer.Connect(GetConfig());
        }

On Redis Server - Client List I get the two below connections one with Last CMD Ping and the other subscribe:

id=685 addr=xxx.xxx.xxx.xxx:7650 fd=7 name=App1 age=26 idle=26 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping

id=686 addr=xxx.xxx.xxx.xxx:7651 fd=8 name=App1 age=26 idle=26 flags=N db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe

Is the second connection automatically created for receiving messages from other publishers? what if I am not expecting messages and what should I set so that it does not open the 2nd connection?

Regards,

Drey

**Comment by mgravell** [comment]
Yes. The one is in anticipation of pub/sub, which requires a separate
connection.

**Comment by DreyMiceli** [comment]
If for a particular service I know I will not be using pub/sub is there any way I can configure the connection to not open a subscriber connection?

**Comment by mgravell** [comment]
Yes; IIRC setting ConfigChannel to an empty string in the config options
should suffice. Alternatively, tell it that the SUBSCRIBE command is
unavailable by mapping it to an empty string - via CommandMap on the
config-options

**Comment by DreyMiceli** [comment]
Following up,

Setting ConfigurationChannel to empty string still creates another connection with a last CMD of ECHO.

Using the CommandMap worked but I had to exclude  "SUBSCRIBE" & "PING".

Thanks.

p.s. took me a while to figure out IIRC

**Comment by mgravell** [comment]
Hmmm... You shouldn't have to exclude ping; if I get chance I'll take a
look at that.
