### ISSUE TITLE
Question about Timeout

### ISSUE THREAD

**Issue by RedaAouad** [StackExchange/StackExchange.Redis#1711]
Hi,

I am getting this timeout error in my app

`StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=728136KiB, 10796ms elapsed, timeout is 10000ms), command=ZREVRANGE, next: ZRANGEBYSCORE xxx, inst: 0, qu: 0, qs: 2784, aw: False, rs: TryParseResult, ws: Idle, in: 131072, in-pipe: 2465792, out-pipe: 0, serverEndpoint: redis.xxx.com:6379, mc: 1/1/0, mgr: 8 of 10 available, clientName: IDP-WEB, IOCP: (Busy=0,Free=1000,Min=300,Max=1000), WORKER: (Busy=2,Free=1021,Min=300,Max=1023), v: 2.1.58.34321`

What's the meaning of `inbound = 728136KiB`? Does it means that a single Redis command is expecting more than 700MB of data? Or is it an incremental number of some sort over the `qs` requests waiting to be processed?
And what's the difference between `inbound` and `in` and `in-pipe`? I know `in` and `in-pipe` are documented, but I didn't quite understand the difference, and I didn't find an info about `inbound`.

Thank you for your help :)
Reda

**Comment by NickCraver** [comment]
@RedaAouad Indeed, that means the response from some command was _huge_, which is undoubtedly the source of your problems here. Note that the reader is stuck in TryParseResult, it's trying to read a _huge_ item off the wire, and blocking many commands behind it.
