### ISSUE TITLE
RedisTimeoutException in a aks cluster to azure redis cache

### ISSUE THREAD

**Issue by worldspawn** [StackExchange/StackExchange.Redis#1712]
I am getting RedisTimeoutExceptions galore. I tried setting the thread pool to 50,50, made no difference. I've introduced connection pooling (20 connections) and again no difference.

The exception below was taken from a worker listening to messages on a session enabled queue. There is 1 worker with 1 concurrency per session and 5 sessions. This means that at any one time during my testing this worker was processing only 5 messages yet still... with 20 connections in the pool I get RedisTimeoutException.

The redis instance itself hasn't reported load exceeding 10%.

`
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 10516ms elapsed, timeout is 10000ms), command=EXEC, next: PING, inst: 0, qu: 0, qs: 21, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: xxx.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: job-command-processor-6859fffb8f-7ztgq, IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=1,Free=32766,Min=50,Max=32767)
`

The longer I let this run the higher `qs` becomes. After entering this state the worker pretty much stays broken. Unable to talk to redis.

I'm stumped.

**Comment by worldspawn** [comment]
Each job on the worker is running this:
`if (await database.KeyExistsAsync($"$Abort_{fileId}"))`

then this 

```
var transaction = _database.CreateTransaction();
			var pendingCommands = transaction.ListRangeAsync($"JobCommands-{request.JobId}");
			var cleanList = transaction.KeyDeleteAsync($"JobCommands-{request.JobId}");
			await transaction.ExecuteAsync();
			await Task.WhenAll(pendingCommands, cleanList);
```

this

```
await _database.LockTakeAsync(lockName, lockValue, lockTime, CommandFlags.DemandMaster)
```

then a StringGetAsync, StringSetAsync and a StringIncrementAsync.

**Comment by deepakverma** [comment]
@worldspawn  wondering if the list JobCommands-{request.JobId} has grown over time causing listrange to be an expensive command resulting in timeouts on the client side? Did you get a chance to look at troubleshooting docs here https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-troubleshoot-client   
https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-troubleshoot-server

**Comment by worldspawn** [comment]
Hi. Sorry this is old, i did a support call with ms and basically discovered the load on redis was maxing out its network bandwidth. TL;DR; i had a key that became larger and larger and the frequency of read/write was too much.
