### ISSUE TITLE
Question: Dependabot fails to identify latest release version

### ISSUE THREAD

**Issue by Bertk** [StackExchange/StackExchange.Redis#1717]
We use Dependabot for update nuget package updates and automatically create PR for every new nuget package (see https://github.com/acraven/azure-dependabot). 

nuget.org and myget.org are checked for new package versions and the newer version of **StackExchange.Redis** package is picked for the PR (https://www.myget.org/feed/stackoverflow/package/nuget/StackExchange.Redis).

Unfortunately the version identifier of **StackExchange.Redis** in myget.org is not using labels like "preview, pre-release, beta" which can be used to distinguish a release or pre-release (see https://semver.org/). 

Is it possible to use version identifier with labels for all packages located in myget.org?

Thank you for your help :)
Bert

**Comment by NickCraver** [comment]
It is not possible the way we release - we literally promote the same .nupkg up from MyGet to NuGet when intending to do a release. If you only want to depend on release versions, we recommend not targeting the MyGet feed at all in that process :)

**Comment by Bertk** [comment]
Thank you for suggestion :wink:

I checked some _dependabot.core_ sources e.g. [repository_finder.rb](https://github.com/dependabot/dependabot-core/blob/main/nuget/lib/dependabot/nuget/update_checker/repository_finder.rb) and could only find a reference for nuget.org ("https://api.nuget.org/v3/index.json"). My assumption about **Myget** usage seams to be wrong.

Please confirm the pre-release version of **StackExchange.Redis** are not synced to nuget.org. Thanks.

**Comment by NickCraver** [comment]
@Bertk they may or may not be, but if we consider them pre-release, they will be semantic versionly named as such :) Closing this one out to cleanup!
