### ISSUE TITLE
SSL Setup?

### ISSUE THREAD

**Issue by KevinBurton** [StackExchange/StackExchange.Redis#172]
This is a completely FAQ type of question. But, I could not find any documentation on how to go about implementing it.
I have 5 Redis servers one master, one slave, three sentinels. If I connect to the master with 'ssl=true' I get an exception on the connection attempt. It seems that the server(s) need to be supplied with some kind of certificate (for testing a self-signed cert will do). I need some cookbook instructions on how to generate a certificate and use it on a server. Do only the master/slave(s) need it? Will the handshake between the sentinels and master/slave also need to go through SSL? How does requirepass/masterauth figure into the SSL equation? Since there is no Redis documentation on SSL I am assuming that this is a StackExchange.Redis feature but I am not clear on how to set it up. Ideas?

**Comment by mgravell** [comment]
What SSL-based server are you using? Redis does not support SSL out of the box, but some providers (Azure, Redis Labs, etc) provide it as an extra. AFAIK: those providers don't expose SSL... so...

**Comment by NickCraver** [comment]
@KevinBurton the current recommendation from redis proper is still Spiped, info and links here: http://redis.io/topics/encryption
