### ISSUE TITLE
Retry not happening when connecting to redis cache

### ISSUE THREAD

**Issue by ms-akhilm** [StackExchange/StackExchange.Redis#1720]
Hi,

We are using redis cache in our project. And recently we got below exception after the deployment and restarting the function: 
It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.

We saw that all request failed at the same timw for 1-2 second and after that the request started passing. We already had  abortConnect=false in our connection string and also had ReconnectRetryPolicy = new ExponentialRetry(2000). Anything extra we need to do for retrying the connection?

**Comment by ms-akhilm** [comment]
Can anyone please help on this issue, we are seeing this issue one or twice every week.

**Comment by ms-akhilm** [comment]
@mgravell can you please help here we are using version 2.1.58 and running a .net core 3.1 Azure function. This is impacting our production environment

**Comment by mgravell** [comment]
I'm sorry that it is impacting your production usage, but the only answer I can give you is "I don't know". I can't debug it from here, and ultimately: while we try to offer help and advice when we can, no portion of your Azure money doesn't come to us for our support - we just do this in our evenings, weekends, etc. We simply don't have the time or resources to try and diagnose every connectivity issue, especially in complex cloud environments.

**Comment by deepakverma** [comment]
> And recently we got below exception after the deployment and restarting the function
@ms-akhilm is this consistently reproable when you deploy or restart the Azure function? If so, then it could be something related to Azure function's deployment model? Since you are msinternal, I am reaching out to you separately to further understand your scenario.

**Comment by deepakverma** [comment]
Spoke with @ms-akhilm and since the issue repros only on reboot or deployment of Azure functions it doesn't seem to be related to SE.Redis. akhilm is going to experiment by adding a delay on application startup to see if it helps to resolve his scenario.

**Comment by NickCraver** [comment]
@deepakverma @ms-akhilm Checking in on older issues - did y'all learn anything noteworthy here?

**Comment by NickCraver** [comment]
Since the 2.5.x prerelease it out for backlogs and there's no update here - going to close out to tidy up.
