### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by kprakesh1984** [StackExchange/StackExchange.Redis#1721]
Getting the following error from the .net core project while trying to connect the Redis server from the application

Exception has occurred: CLR/StackExchange.Redis.RedisConnectionException
Exception thrown: 'StackExchange.Redis.RedisConnectionException' in System.Private.CoreLib.dll: 'It was not possible to connect to the redis server(s). There was an authentication failure; check that passwords (or client certificates) are configured correctly. AuthenticationFailure (None, last-recv: 170) on 192.168.10.177:6379/Interactive, Flushed/ComputeResult, last: ECHO, origin: SetResult, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.593.37019'

Using NuGet package "Microsoft.Extensions.Caching.StackExchangeRedis" Version="3.1.0
donet core version 3.1

**Comment by mgravell** [comment]
Well... are you sure you're using the right auth details? How is the server configured? Does it expect auth? Are you supplying auth?

**Comment by NickCraver** [comment]
Can't tell much from the info provided here. If there was a race condition hit, please upgrade to 2.2.50 where we resolved a potential (race) ordering issue with AUTH in the pipe.
