### ISSUE TITLE
HashKeysAsync not returning values

### ISSUE THREAD

**Issue by VigneshOne** [StackExchange/StackExchange.Redis#1722]
Application using pub-sub notifications using Redis,  
 - notification service registers workers in Redis HashSet with keys as "notification-workers"
 - notification cron job will check Redis for any workers registered in HashSet by below code,
 
var workers = await redisClient.HashKeysAsync("notification-workers");

but workers is always empty.
in Redis client command line,  it shows entries for HKEY command,  but in c# function,  it was getting empty for same key - "notification-workers"

Could you please advise where could be the issue.

**Comment by NickCraver** [comment]
Are you sure you're in the same server & database for both connections?
