### ISSUE TITLE
Subscriptions get no events on aws elasticbeanstalk

### ISSUE THREAD

**Issue by seoushi** [StackExchange/StackExchange.Redis#1725]
I'm having an odd issue where if I run my server application locally that I will get subscription events but when I go to deploy the same application to aws elastivebeanstalk I can connect and subscribe with no errors but I get no subscription events. Here is the code I am using.

```
string options = string.Format("{0}:{1},password={2}", host.ToString(), port.ToString(), auth.ToString());
                
Logger.Info("connecting to redis");
ConnectionMultiplexer multiplexer = await ConnectionMultiplexer.ConnectAsync(options);
Logger.Info("connected");

multiplexer.ConnectionFailed += (sender, args) =>
{
    Logger.Info("redis connection failed", ReportingMethod.LocalOnly, ("args", args.ToString()));
};

multiplexer.ErrorMessage += (sender, args) => 
{
    Logger.Info("redis error", ReportingMethod.LocalOnly, ("args", args.ToString()));
};

multiplexer.InternalError += (sender, args) =>
{
    Logger.Info("redis internal error", ReportingMethod.LocalOnly,
        ("args", args.ToString()));
};
                
                
ISubscriber subscriber = multiplexer.GetSubscriber();

if (!subscriber.IsConnected())
{
    Logger.Error("subscriber not connected");
    return false;
}

Logger.Info("subscribing");

subscriber.Subscribe("config-notifications", (RedisChannel channel, RedisValue message) =>
    {
        OnMessage(message);
    });

Logger.Info("subscribed");

```

Is there some configuration on aws I need to look out for?
I am using stackexchange.redis 2.2.4 and dotnetcore 3.1

I did ssh into the aws machine and redis-cli worked as expected

**Comment by NickCraver** [comment]
This just isn't something we use - I have no idea if they support this or not. I'd recommend asking on their product support forums since we won't be able to investigate. Leaving this issue open in case some other AWS users may know though!

**Comment by NickCraver** [comment]
Closing this out to tidy up - I hope you were able to get this working with AWS.
