### ISSUE TITLE
Crashing .NET core 3.1 webapi

### ISSUE THREAD

**Issue by dhimanb** [StackExchange/StackExchange.Redis#1726]
I am developing an .Net core 3.1 web api.

In StartUp.cs, I am setting up the connection as 
```
public static ConnectionMultiplexer redis;
public void Configure(IApplicationBuilder app, IWebHostEnvironment env) {
            redis = ConnectionMultiplexer.Connect("localhost"); ...
```

and then later using setting up a key as
```
string value = "run at " + DateTime.Now.ToString();
IDatabase db = Startup.redis.GetDatabase();
db.StringSet("test_key", value, new System.TimeSpan(3, 0, 0));
```
Its works fine in my development environment, but in the production environment it crashes.

I get the following error
```
Faulting application name: w3wp.exe, version: 10.0.14393.0, time stamp: 0x57899135
Faulting module name: coreclr.dll, version: 4.700.20.51601, time stamp: 0x5f89f166
Exception code: 0xc0000005
Fault offset: 0x00061471
Faulting process id: 0x2f008
Faulting application start time: 0x01d73e02dc5d058e
Faulting application path: C:\Windows\SysWOW64\inetsrv\w3wp.exe
Faulting module path: C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\3.1.10\coreclr.dll
Report Id: 1104748b-7a7e-4e07-9302-a34883fada38
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by mgravell** [comment]
Well, there's not much to go on there. Did an actual exception (rather than a critical process fail) get logged anywhere?

**Comment by NickCraver** [comment]
`xc0000005` is an access violation - are you sure IIS has permissions to read the folder it's in? Sounds like it's trying to load some DLLs perhaps, but the running process account doesn't have file folder permissions.

**Comment by dhimanb** [comment]
@NickCraver If I remove the Redis reference and code, then the application runs fine. Where else would IIS need permission? Do you think its not able to access localhost:6379?

**Comment by NickCraver** [comment]
When a connection happens, it's likely spinning up a few more types from DLLs on disk. If you don't have permission to read that folder, this type of exception would happen. It needs permissions to the application folder itself - it's not granted this automatically.

**Comment by dhimanb** [comment]
I compiled it as the application `dotnet publish . -o ..\publishedAPI  -r win-x64`
then in the pool I set `Enable 32-bit application = False`

and it started working...
