### ISSUE TITLE
StackExchange.Redis.RedisConnectionException .Net IIS Web Errors - During Load Testing

### ISSUE THREAD

**Issue by mprest-a** [StackExchange/StackExchange.Redis#1728]
We've been running load testing and get one server that goes sideways with StackExchange.Redis.

Has anyone seen the same and is there any recommendations or fixes? Thanks!

StackExchange.Redis.RedisConnectionException:StackExchange.Redis.RedisConnectionException:System.Threading.ThreadAbortException
No connection is active/available to service this operation: HGET GetClientOptions__clientID=XXX__shard=D__environmentLV=XX; Thread was being aborted., mc: 1/1/0, mgr: 10 of 10 available, clientName: XXX-XXX-XXXX, IOCP: (Busy=0,Free=1200,Min=360,Max=1200), WORKER: (Busy=2,Free=1198,Min=360,Max=1200), v: 2.2.4.27433

**Comment by NickCraver** [comment]
Are you calling `Thread.Abort()` in your code somewhere? This isn't something we throw, but doing so when something is running (like SE.Redis or anything else) is going to go boom in all sorts of ways. Note that `Thread.Abort()` is marked as obsolete, for this reason. The code you're running on may be using it underneath as well.

**Comment by py224** [comment]
We see this in our ASP.NET WebForms page when the page hits the execution timeout limit (default is 90 seconds) and the timeout is on the StackExchange.Redis command similar to what is shown in the OP's error. There is no explicit code doing it - it is ASP.NET/WebForms.  ASP.NET/WebForms also does this on Response.End and Response.Redirect https://docs.microsoft.com/en-us/troubleshoot/aspnet/threadabortexception-occurs-you-use-response-end but i haven't coorelated with SE.Redis commands, just the page timeouts.

**Comment by mprest-a** [comment]
Nick,
According to our Dev team we're not doing Thread.Abort() calls.

The latest issue is one web server seems to get stuck with Redis errors. They pile up, but eventually clear.

The timeout was reached before the message could be written to the output buffer, and it was not sent, command=HGET, timeout: 3000, outbound: 0KiB, inbound: 546KiB, inst: 0, qu: 0, qs: 0, aw: True, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: redis-16667.redis-xxxx-cluster.bswift.net:16667, mc: 1/1/0, mgr: 10 of 10 available, clientName: XXX-SRV-WEBXX, IOCP: (Busy=0,Free=1200,Min=360,Max=1200), WORKER: (Busy=182,Free=1018,Min=360,Max=1200), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by mprest-a** [comment]
The other issue we're seeing is 2 minute timeouts on our web servers.  We see a lot of these on just a single server and then they eventually clear... "The timeout was reached before the message could be written to the output buffer, and it was not sent,"

**Comment by NickCraver** [comment]
@mprest-a With a thread queue that high (182), your web server is slammed with tasks and likely unable to complete in the 3 second window (note the 568k on the wire waiting to be read). I'm not sure where your _other_ tasks are coming from, but it's probably worth taking some memory dumps and see what is beating the crap out of the CPU.

**Comment by NickCraver** [comment]
Closing this out to tidy up - advice remains the same as above for anyone in this scenario.
