### ISSUE TITLE
GETDEL support

### ISSUE THREAD

**Issue by RobotGizmo** [StackExchange/StackExchange.Redis#1729]
I was wondering if there are plans to support the new GETDEL command? The docs mention that it was added in v6.2:

[](https://redis.io/commands/getdel)

Thanks!

**Comment by NickCraver** [comment]
There are no plans at the moment but adding to the API backlog and would welcome a PR!

**Comment by halllo** [comment]
As a workaround one could use `var value = await db.ExecuteAsync("GETDEL", key);`.

**Comment by RobotGizmo** [comment]
> As a workaround one could use `var value = await db.ExecuteAsync("GETDEL", key);`.

This works perfectly, thanks!

**Comment by SohaibAnwaar** [comment]
How can we use GETDEL in python?
