### ISSUE TITLE
AbortOnConnectFail=false message even though AbortOnConnectFail is already false?

### ISSUE THREAD

**Issue by genne** [StackExchange/StackExchange.Redis#1744]
I'm confused by this message - we get it even though `AbortOnConnectFail` is false - shouldn't the if case be inverted?
https://github.com/StackExchange/StackExchange.Redis/blob/f4c69fa21f93e6f9e0f067cf07294baab77de558/src/StackExchange.Redis/ExceptionFactory.cs#L347

(Also mentioned in this issue: #1287)

**Comment by philon-msft** [comment]
@genne I agree, thank you for bringing this up. Please see my linked PR.

**Comment by NickCraver** [comment]
Fixed in #1747, thanks @philon-msft!
