### ISSUE TITLE
Expose PhysicalBridge.GetOutstandingCount

### ISSUE THREAD

**Issue by alecl** [StackExchange/StackExchange.Redis#175]
On a troubleshooting page I'd love to be able to see the values of these counters to understand if there's any queuing currently, etc. This is buried so deep in chains of internals that I gave up on the idea of sorting it out even with reflection. I'd love to get at it right from ConnectionMultiplexer.

Can you consider exposing it with a big red warning not to call it in a loop because it does locking or whatever scary warning you like but let the curious ones get at it?

**Comment by mgravell** [comment]
I think this is already exposed via GetCounters(), no?

**Comment by alecl** [comment]
So it is. The names being a little different threw me off thinking it was something else. Thank you.
