### ISSUE TITLE
access redis Cluster conection string

### ISSUE THREAD

**Issue by wurangbo** [StackExchange/StackExchange.Redis#1756]
Hi guys，
When  I access redis Cluster using stackexchage.redis   using connectionstring as bellow
connectionString="142.100.16.125:6379,10.163.100.171:6379,10.163.100.72:6379,password=siteweb1!,abortConnect=false"
 data can only be write into 142.100.16.125 , how to fix it?

**Comment by NickCraver** [comment]
If you're connecting to a cluster, you only need specify one endpoint and it'll discover the rest. If there are independent primary servers, that's tie breakers at work. Hope that helps!
