### ISSUE TITLE
Timeout performing get operations with Azure cluster 

### ISSUE THREAD

**Issue by shlomico-tr** [StackExchange/StackExchange.Redis#1758]
Hi

We moved to Azure cluster, and the max server load is 20%, 
Our back server is also without a high CPU (max 30%) 
also, we use only simple operations.
but we suffered Redis timeout on get operation like:

StackExchange.Redis.RedisTimeoutException: Timeout performing MGET (5000ms), next: MGET --our key--, inst: 0, qu: 0, qs: 12, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: -----, mc: 1/1/0, mgr: 10 of 10 available, clientName: -----, PerfCounterHelperkeyHashSlot: 11250, IOCP: (Busy=2,Free=998,Min=100,Max=1000), WORKER: (Busy=132,Free=32635,Min=100,Max=32767), v: 2.1.30.38891 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

What could be the source?

Thanks!!

**Comment by slorello89** [comment]
Hi @shlomico-tr 

Is it possible you're performing an `MGET` on a large set of keys? Can you run the [SLOWLOG](https://redis.io/commands/slowlog) on your redis server to see what's taking so long. five seconds is a rather long run time - sounds like something in the command itself.

**Comment by NickCraver** [comment]
Are you sure it's at 30% when this happens? I'm seeing 132 active threads which is quite a few. Beware that monitoring can lie to you here - I've done some threads on this which may be helpful in covering what I mean by a lie there: https://twitter.com/Nick_Craver/status/1038747663636877312 - when you're seeing instantaneous load spikes but graphs and data points for cumulative CPU over a period at much higher intervals, you can easily not see short bursts of CPU.

**Comment by DarthSonic** [comment]
We suffer the same timeouts for months now with Azure App Service utilizing Azure Redis. I optimized the configuration and wrote a custom wrapper for Redis but nothing solved the problems. For days all is running smooth and suddenly there are a dozen or more timeouts on low load of app service and redis.

**Comment by SimonPapworth** [comment]
We found transient errors talking to the redis server can cause the above, our redis servers failover once a week on avg. Our K8 nodes have been overloaded at times, our code hits another service with a sync call that takes longer than the redis timeout very occasionally.

Sync calls to sql server is our main cause, they normally take 3ms - unless there is lock
