### ISSUE TITLE
How can I limit my result set 

### ISSUE THREAD

**Issue by rharwig** [StackExchange/StackExchange.Redis#1763]
I've a website where I show all the keys.
The PageSize is 50. 
The Redis DB has 1000 keys. 

So that means 20 pages in total.
The first call should give me the first 50 records.
The next call should give me the next 50 records.
And so on.

I've already tried a lot of variations also with setting the PageSize and pageOffset but nothing gives me the desired result.

Example Console application:

```
            ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost");
            IDatabase database = redis.GetDatabase();

            var endpoints = redis.GetEndPoints();
            IServer server = redis.GetServer(endpoints.First());
            int totalkeys = (int) server.DatabaseSize();
            var result = server.Keys(pattern: "*", pageSize: 50, pageOffset: 50, cursor: 0);
```

For example if I use the Redis CLI I can use: `SCAN 0 COUNT 50`

How should the code look to get 50 records at a time to populate the current webpage?
Any help will be much appreciated!

Thanks!

**Comment by tombatron** [comment]
Though I don't recommend doing this...

As long as you're tracking the `pageOffset` the extension method `.Take(50)` should snatch the first 50 items into a new IEnumerable<RedisKey>. 

What's your use case, perhaps there's a more idiomatic way to achieve what you're after?

**Comment by rharwig** [comment]
Yeah, I just found out that this will give me just a random set...

The use case is as follows:
We use Redis for correlating document responses with document requests that are sent.
In Redis we store a key (the document guid) and a value Json string (requestdatetime,doc_name)

In a .NET core webapplication we want to have an overview with the following columns:  guid, requestdatetime, doc_name.
We also want to use pagination.
The issue I'm encountering is that whenever there are a lot of keys it takes a long time to load the page. So I'm looking for a solution that I can speed this up and that the key value set only applies for the current page. Whenever the user loads a new page the next key value set should load.

Thanks in advance.

**Comment by tombatron** [comment]
Gotcha. 

My advice would be to look into a secondary index on your keys using the RediSearch module which supports pagination. 

Barring that, you would probably have to build the "indexes" yourself.

**Comment by rharwig** [comment]
Ok, but how can I do that?
Do you've a code example?

**Comment by slorello89** [comment]
So as Tom mentioned, scanning through the keys is probably not the best approach. There's probably 3 options:

1. If you don't care about any sort of querying operations, and you just need to paginate through a set of strings - you can just use a list data structure and use [LRANGE](https://redis.io/commands/lrange) to paginate through it - that would be the equivalent of using [ListRange](https://github.com/StackExchange/StackExchange.Redis/blob/v2.1.39/src/StackExchange.Redis/RedisDatabase.cs#L971)

If you either want support for Hash data structures and/or you need to be able to query something - you probably need to use redis search in which case you have two options

2. You can build a query and use the [Aggregator Cursor API](https://oss.redislabs.com/redisearch/Aggregations/#cursor_api), this will allow you to issue the query once, and redis will maintain the results of the query for a set amount of time (up to 5 minutes) for you to continue paginating through

3. You can use the FT.SEARCH API with the LIMIT option to allow you to iterate through records returned from a query, if you use this you will likely want to ensure that you have some way of making sure that new records aren't being added to the result of the query (will probably want to index a timestamp field and have your query use a time range)

I wrote a contrived example for the latter two that you can look at https://github.com/slorello89/pagination-nredisearch - as they are slightly more advanced use cases

**Comment by rharwig** [comment]
Thanks, I'll look into that!

**Comment by NickCraver** [comment]
Closing this one out to tidy up :)
