### ISSUE TITLE
SuppressMessage ImplementISerializableCorrectly

### ISSUE THREAD

**Issue by alecl** [StackExchange/StackExchange.Redis#178]
I'm trying to unit test some exception parsing/logging code and I thought I'd serialize the RedisConnectionException, etc chains to file and then load as my test data without actually having to deal with Redis in my unit test code and I found that I could not deserialize due to the missing (SerializationInfo info, StreamingContext context) constructor.

When I looked at the StackExchange code I was even more surprised to find that this message was suppressed so this was done deliberately. Why was that?

Thanks for any clarification.

**Comment by mgravell** [comment]
Mainly simply that it seemed very unlikely that anyone would be electing to serialize these exceptions - it seems a very unusual thing to want to do ;p

Added:
https://github.com/StackExchange/StackExchange.Redis/commit/c2444f458108260eee7ce5f442023c31ac6f685d

**Comment by alecl** [comment]
Thank you! :thumbsup:
