### ISSUE TITLE
ConnectTimeout seemingly with no load

### ISSUE THREAD

**Issue by espjak** [StackExchange/StackExchange.Redis#1781]
Hi,

We are having a recurring issue in some of our production environments where it looks like the connection via StackExchange.Redis enters a bad state which it does not recover from and gives following exception:
`StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: EXISTS ReplacementEntities:200ceb26-807d-3bf9-9fd6-f4f0d1ca54d4; It was not possible to connect to the redis server(s). To create a disconnected multiplexer, disable AbortOnConnectFail. ConnectTimeout; IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=0,Free=32767,Min=4,Max=32767), Local-CPU: n/a
 ---> StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). To create a disconnected multiplexer, disable AbortOnConnectFail. ConnectTimeout
   --- End of inner exception stack trace ---
   at T StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl<T>(Message message, ResultProcessor<T> processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2231
   at T StackExchange.Redis.RedisBase.ExecuteSync<T>(Message message, ResultProcessor<T> processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
   at bool CacheManager.Redis.RedisCacheHandle<TCacheValue>.Exists(string key)+() => { }
   at T CacheManager.Redis.RetryHelper.Retry<T>(Func<T> retryme, int timeOut, int retries, ILogger logger)
   at bool CacheManager.Core.BaseCacheManager<TCacheValue>.Exists(string key, string region)`

Other clients connects without issues and once we restart the service in question it works.
There are nothing in the redis log (No restarts, errors etc.) that should indicate an issue there.

For one customer it happens almost weekly. Another customer has had 1 instance that I am aware of.
The issue seems to have come after moving to .net core, we are currently using StackExchange.Redis 2.0.593. Most of our customer are running on pre .net core releases and I have yet to find an instance of this issue there.

As you can see we are using CacheManager with redis as distributed cache and in this instance the redis is running locally:
`    "redis":  {
                  "database":  3,
                  "connectionString":  "localhost:6385,abortConnect=false,ssl=false,syncTimeout=15000,allowAdmin=true"
              },`
There are multiple redis running on the same server on different ports. I have not seen the issue on the other customers running on the same server, but they are not on the .net core version (Running the older StackExhange.Redis.StrongName, 1.2.6).

The customer where it happens recurrently has a big replication job that runs in parallel which causes a burst of redis commands (via CacheManager, it runs nightly and most of the time the cached data has expired so it needs to repopulate). 
However, the other customer does not run the job in parallel and have overall much less redis traffic. 
So it seems more traffic = higher chance of its happening.

It could be a CacheManager issue, but it does not look like anything major has changed there over the years regarding its CacheManager.StackExchange.Redis handling.

Do you have any suggestions as to what could be the problem? What I should check? 
I know its not much to go on here, but we are at a loss to what the issue could be.

**Comment by mgravell** [comment]
Can you try v2.2.50 or above (released yesterday)? Some extensive work and fixed specifically related to connection stability have been released

**Comment by espjak** [comment]
We are going to update to v2.2.50 and try it on the customer that has the most issues. I will let you know how it works out.

Thanks for quick reply.

**Comment by NickCraver** [comment]
Hoping all is well here based on no updates - going to close out to tidy. If the issue did remain, happy to re-open or advise further!

**Comment by espjak** [comment]
Forgot to update the ticket, busy times.
Yes, the update seemed to resolve or at least vastly improve the situation.
