### ISSUE TITLE
RedisConnectionException : It was not possible to connect to the redis server(s). SocketClosed

### ISSUE THREAD

**Issue by paolovalladolid** [StackExchange/StackExchange.Redis#1794]
I installed Redis on a RedHat Linux VM.

My application code uses Microsoft iDistributedCache, with the AddStackExchangeRedisCache() call in my HostBuilder method.

I have an XUnit test script that I've been using to load test data into my distributed cache.  The script runs fine when I have my cache endpoint in appsettings.json set to the Memurai instance running on my local machine.  When I change the endpoint to the redis-server instance running on the RHEL 7 VM, I get this message instead:

StackExchange.Redis.RedisConnectionException : It was not possible to connect to the redis server(s). SocketClosed (ReadEndOfStream, last-recv: 0) on [VM IP address]:6379/Interactive, Flushed/MarkProcessed, last: ECHO, origin: ReadFromPipe, outstanding: 6, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.593.37019

**Comment by mgravell** [comment]
Are you using the latest library version? A *lot* of fixes for connection stability were in there. However, there's not much for us to go on here. If you were using SE-Redis directly, you can you pass a StringWriter into the optional log parameter on Connect/ConnectAsync, which gives us a *lot* more information about what happened.

As we aren't Microsoft, we don't directly provide comments on the Microsoft bits, but there are some Microsoft folks who keep an eye on things here and who may wish to opine.

But: initial thoughts:

- what library version and framework version?
- was it a TLS / ACL issue?
- was it DNS / firewall / routing?
- if netfx, was it assembly binding problems (since you mention RHEL, I'm guessing "not")

It may be worth trying the direct ConnectionMultiplexer.Connect method, just so we can get the log.

**Comment by mgravell** [comment]
I should also have noted: I see you're using Memurai - that should be fine; I'm familiar with Memurai and it should work perfectly with the library, but: there may be some configuration options that we flip automatically for some providers (based on domain names) that need enabling manually for Memurai - again, I'm thinking about things like TLS.

**Comment by paolovalladolid** [comment]
Yes, I use Memurai for development and testing on my local machine.  I proposed using Memurai on the shared development environment to our team, running on the same Windows Server 2019 VM as my Dotnet application that handles requests to the distributed cache and logic related to using the cache.  Instead, the team decided to request a separate VM - a RHEL one - install Redis on that, and use that instead of Memurai as our distributed cache.   Also, management was asking me for level of effort if the decision was made to switch to a different caching solution such as NCache, which I took as a hint to refactor my code to use Microsoft iDistributedCache instead of using StackExchange.Redis iConnectionMutiplexer directly.

The RHEL7 VM hosting Redis and the Windows Server 2019 VM are on the same network, so there should not be a DNS/firewall/router issue.   I am not familiar with TLS or ACL, sorry.  I just ran the basic make build and make install when I built Redis on RHEL7.  I figured I'd tackle the challenge of securing Redis at a later date.

Unfortunately, I did not take into account that Microsoft's Microsoft.Extensions.Caching.StackExchangeRedis package might be depending on an older version of StackExchange.Redis.  I am using v5.0.1 of that package.   I see in the docs that it is dependent on StackExchange.Redis  2.0.593 or later.

I could try switching to a preview version of Microsoft.Extensions.Caching.StackExchangeRedis, since our project is still in the development phase, and not close to production yet.  I see 6.0.0-preview.5.21301.17 has a dependency on StackExchange.Redis 2.2.4 or later.

**Comment by paolovalladolid** [comment]
The team decided to let me try running Memurai in the shared development environment, for use by my colleagues, while I work on switching to the preview version of Microsoft.Extensions.Caching.StackExchangeRedis.

Unfortunately, I still see the same error message when my application tries to connect to Memurai, using the 5.0.1 Microsoft.Extensions.Caching.StackExchangeRedis

**Comment by mgravell** [comment]
Ok. Do you have - or can you have - either redis-cli or memurai-cli on the
box you're connecting **from**? If so: can it connect? I can't give you the
exact command-line to enter without knowing your connection string.

**Comment by paolovalladolid** [comment]
Turns out that I needed to make some changes to the redis.conf file:

1. Set protected-mode to no
2. Comment out the bind loopback address line 

Now my application has no trouble communicating with Redis on the RHEL7 VM.

Thanks for the help and apologies for the confusion.  Closing the issue now.
