### ISSUE TITLE
Required ACLs to self configure

### ISSUE THREAD

**Issue by stevehipwell** [StackExchange/StackExchange.Redis#1795]
What is the minimal ACLs to self configure? We had a user with `+@all -@dangerous -@admin` trying to connect to a cluster via the configuration endpoint reporting as a standalone v2.0.0 instance. We'd like to know how we should be setting the user ACLs for this to work?

**Comment by mgravell** [comment]
Hi. This would be a great question for the redis repo, but it really isn't a client library question. From the perspective of the client library, all we provide is the ability to specify the CN/PW pair to log in *with* the ACL context. Unless there's something library-specific here, it is probably a question for https://github.com/redis/redis

**Comment by stevehipwell** [comment]
@mgravell thanks for the quick response. I was specifically thinking around the [command lookup](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/ConnectionMultiplexer.cs#L309)? I'm assuming we need all of these but I was also interested what other, if any, commands were also needed?

**Comment by mgravell** [comment]
Ah, that makes it a bit more client library related, indeed.

I'll need to think on this - interesting question. In particular, we should
ensure that we don't get any hard epic connection failures if some are
blocked. That investigation work hasn't happened to date, as far as I know.

**Comment by stevehipwell** [comment]
Thanks @mgravell I'll add the ACLs we end up with after further testing (we're currently having to use `+@all` to get this working). 

It would also be really useful if there was an example of the connection output with the keys documented so it's possible to confirm that the right connection has been made. E.g. `<ENDPOINT>:<PORT>: <TYPE> <SERVER_VERSION>...` with `TYPE` documented as, for example, `Standalone|Cluster|Sentinel`.

**Comment by NickCraver** [comment]
I've added some tests for this, but as of #1931 we should successfully connect without any of the commands enabled, with commiserate functionality not in play, for example: if `GET` is disabled we won't break, but won't be able to have a tiebreaker do anything.

@stevehipwell I'm not following on your last message here (having trouble picturing locality):
> It would also be really useful if there was an example of the connection output with the keys documented so it's possible to confirm that the right connection has been made. E.g. `<ENDPOINT>:<PORT>: <TYPE> <SERVER_VERSION>...` with `TYPE` documented as, for example, `Standalone|Cluster|Sentinel`.

Could you maybe give some psuedo code on what your ideal command/response would look like here?

**Comment by stevehipwell** [comment]
@NickCraver it's been a while since I looked as this and I've moved roles since then so am not involved with this directly. Off the top of my head I think I was suggesting that there should be some documentation showing how to validate that the connection made was the type of connection expected. I think we were trying to create a cluster connection but were only getting a connection to one of the nodes due to the ACLs we had setup.

**Comment by NickCraver** [comment]
@stevehipwell ah okay so detection of sibling nodes? We don't have a test for that at the moment - leaving this open to add one and verify what happens when various commands are disabled.

**Comment by stevehipwell** [comment]
@NickCraver I think it was more to show what the connection should look like in cluster mode, as we asked for a cluster connection but got a single node connection and needed to manually debug our use.

**Comment by NickCraver** [comment]
Update: adding this in #2225 to improve the docs for all - thanks for the follow-up here!
