### ISSUE TITLE
Redis No connection aVailable

### ISSUE THREAD

**Issue by RajasekarPR** [StackExchange/StackExchange.Redis#1799]
Hi @JonCole 

We have been facing this redis no conenction issue intermittently in our production slot. To fix this, we have upgraded our stackexchange.redis to latest version(2.2.5) where they have fixed some conenction related issues. 

In addition to the above solution, it is necessary to do the force reconnect from our code which you have suggested in below url 

https://gist.github.com/JonCole/925630df72be1351b21440625ff2671f#reconnecting-with-lazyt-pattern

Details : 

Dot Net Framework : 4.7.1

Kindly provide your feedback please.

**Comment by philon-msft** [comment]
@RajasekarPR yes, it's still a good idea to have force reconnect logic to detect and recreate any connections that get into a bad state where they cannot be recovered.

**Comment by NickCraver** [comment]
For anyone hitting issues, a _lot_ of improvements have gone into these paths based on additional scenarios and user reports, please grab the latest client to benefit from those improvements as well as better logging for any other issues you may hit. Closing this one out to tidy up.
