### ISSUE TITLE
StackExchange.Redis.RedisConnectionException:“No connection is active/available to service this operation: LPOP

### ISSUE THREAD

**Issue by icejd** [StackExchange/StackExchange.Redis#1800]
**There are multiple processes reading the queue in the project, and the following errors often appear in the error lo**

> StackExchange.Redis.RedisConnectionException:“No connection is active/available to service this operation: LPOP queue_lq_test; It was not possible to connect to the redis server(s). ConnectTimeout, mc: 1/1/0, mgr: 10 of 10 available, clientName: GamePal_LP, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=33,Free=32734,Min=12,Max=32767), v: 2.2.62.27853

**I reproduced the error with the following code**
```cs
for (int i = 0; i < 100; i++)
{
    Task.Run(() =>
    {
        while (true)
        {
            var n = QueueHelper.ListLeftPop<int>("test");
            Console.WriteLine(n + 1);
            Thread.Sleep(1);
        }
    });
}
```
**The corresponding code is as follows**
```cs
public static ConnectionMultiplexer _instance;
static IDatabase database;
public StackExchangeRedis()
{
    database = Instance.GetDatabase();
}
/// <summary>
/// Singleton
/// </summary>
public ConnectionMultiplexer Instance
{
    get
    {
        if (_instance == null)
        {
            lock (Locker)
            {
                if (_instance == null || !_instance.IsConnected)
                {
                    _instance = GetManager();
                }
            }
        }
        return _instance;
    }
}

public T ListLeftPop<T>(string key)
{
    RedisValue queueValue = database.ListLeftPop(key);
    T value = default;
    if (!queueValue.IsNull)
    {
        value = JsonConvert.DeserializeObject<T>(queueValue, jsonConfig);
    }
    return value;
}
```

**Comment by icejd** [comment]
Switching to other libraries does not have this problem
Such as
https://github.com/2881099/FreeRedis

**Comment by NickCraver** [comment]
Can you share the code for `GetManager()`? Also more details like your connection string/timeouts (without secrets of course) would help advise.

**Comment by icejd** [comment]
> Can you share the code for `GetManager()`? Also more details like your connection string/timeouts (without secrets of course) would help advise.

**Okay, I'm just messing it up a little bit, but in the test project, the slave is always 0, you don't have master slave enabled**
`private ConnectionMultiplexer GetManager()
        {
            string address = "0|192.168.0.158:6379|192.168.0.81:6379,ipass"
            string[] arrconnstr = address.Split(',');
            string[] arrhosts = arrconnstr[0].Split('|');
            string slave = arrhosts[0];//Read/write separation
            string masterhost = arrhosts[1];//Master database connection
            string password = arrconnstr[1];//password
            ConfigurationOptions options = new ConfigurationOptions(); //ConfigurationOptions.Parse(address);
            options.EndPoints.Add(masterhost);
            if (slave == "1")
            {
                string slavehost = arrhosts[2];//Slave database connection
                options.EndPoints.Add(slavehost);
            }
            options.Password = password;
            options.ClientName = "GM_XXP";
            options.AllowAdmin = true;
            options.AbortOnConnectFail = false;
            options.Ssl = false;
            options.ConnectTimeout = 5000;
            ConnectionMultiplexer connect = ConnectionMultiplexer.Connect(options);
            server = connect.GetServer(masterhost);
            return connect;
        }`

**Comment by icejd** [comment]
That's all
`using GamePal.Common;
using Newtonsoft.Json;
using StackExchange.Redis;

namespace GamePal.Queue
{
    public class StackExchangeRedis : IQueue
    {
        private static readonly object Locker = new object();
        JsonSerializerSettings jsonConfig = new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore, NullValueHandling = NullValueHandling.Ignore };
        public static ConnectionMultiplexer _instance;
        static IDatabase database;
        public StackExchangeRedis()
        {
            database = Instance.GetDatabase();
        }
        /// <summary>
        /// 单例获取
        /// </summary>
        public ConnectionMultiplexer Instance
        {
            get
            {
                if (_instance == null)
                {
                    lock (Locker)
                    {
                        if (_instance == null || !_instance.IsConnected)
                        {
                            _instance = GetManager();
                        }
                    }
                }
                return _instance;
            }
        }
        private ConnectionMultiplexer GetManager()
        {
            string key = Utils.GetMyStr(DES.encryptKey, 8, 6);
            string address = DES.Decode(JRKeys.QueueConnectionString, key);
            string[] arrconnstr = address.Split(',');
            string[] arrhosts = arrconnstr[0].Split('|');
            string slave = arrhosts[0];//是否读写分离
            string masterhost = arrhosts[1];//主库连接
            string password = arrconnstr[1];//密码
            ConfigurationOptions options = new ConfigurationOptions(); //ConfigurationOptions.Parse(address);
            options.EndPoints.Add(masterhost);
            if (slave == "1")
            {
                string slavehost = arrhosts[2];//从库连接
                options.EndPoints.Add(slavehost);
            }
            options.Password = password;
            options.ClientName = "GamePal_LP"; // only known at runtime
            options.AllowAdmin = true;
            options.AbortOnConnectFail = false;
            ConnectionMultiplexer connect = ConnectionMultiplexer.Connect(options);
            return connect;
        }
        /// <summary>
        /// 从右边插入队列
        /// </summary>
        /// <param name="key"></param>
        /// <param name="value"></param>
        /// <returns></returns>
        public long ListRightPush(string key, object value)
        {
            string jsonData = JsonConvert.SerializeObject(value);
            return database.ListRightPush(key, jsonData, flags: CommandFlags.DemandMaster);
        }
        /// <summary>
        /// 从左边读取队列
        /// </summary>
        /// <param name="key"></param>
        /// <param name="value"></param>
        /// <returns></returns>
        public T ListLeftPop<T>(string key)
        {
            RedisValue queueValue = database.ListLeftPop(key);
            T value = default;
            if (!queueValue.IsNull)
            {
                value = JsonConvert.DeserializeObject<T>(queueValue, jsonConfig);
            }
            return value;
        }
        /// <summary>
        /// 取得队列数量
        /// </summary>
        /// <param name="key"></param>
        /// <returns></returns>
        public long ListLength(string key)
        {
            return database.ListLength(key);
        }
        /// <summary>
        /// 取得指定字符串的自增ID
        /// </summary>
        /// <param name="key"></param>
        /// <returns></returns>
        public long StringIncrement(string key)
        {
            return database.StringIncrement(key);
        }
    }
}`

**Comment by icejd** [comment]
My God, this editor doesn't work very well

**Comment by NickCraver** [comment]
Your workaround is a band-aid that'll work to some degree, but the overall cause here appears to be overloaded thread pool. This is handled better in .NET 6.0+ which is worth noting, and errors are improved in the newer client library versions, but the root cause you're fighting is the same. The best diagnosis path here is getting a capture when it happens and see what all those threads are stalled on. Barring that, the band-aid of upping minimum threads does work :)
