### ISSUE TITLE
getting timeout exception reading wav files from redis cache under load or more than 50 simultaneous calls

### ISSUE THREAD

**Issue by ievdokdm** [StackExchange/StackExchange.Redis#1802]
Under load testing of my grpc app hosted under Kubernetes in azure I'm constantly getting exceptions calling azure cache for redis:
`StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms)`
`inst: 39, qu: 0, qs: 3, aw: False, rs: ReadAsync, ws: Idle, in: 396207, mc: 1/1/0, mgr: 10 of 10 available`
`IOCP: (Busy=0,Free=1000,Min=2,Max=1000), `
`WORKER: (Busy=15,Free=32752,Min=2,Max=32767), v: 2.1.58.34321`

The load is not that high it's about 50 simultaneous requests.
Though the cached objects are speech voice.

**Comment by SimonPapworth** [comment]
I believe it's the way the timeout is coded, it is as if the timeout was written for a real time system and not an IIS server underload.

Last attempt on timeout would be nice - the request data is often already waiting to be read, but the worker process has not been back to check for over the timeout period.

**Comment by NickCraver** [comment]
Happy to reopen if there are more questions here, but advice above remains for anyone pulling down a lot of bytes!

**Comment by SimonPapworth** [comment]
Hi, I can confirm that the data has already fully arrived from the redis server into the front end server, before doing a timeout it would be nice if it could actually retrieve the data from memory and process it .

Simon
