### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException .Net IIS - During Load Testing

### ISSUE THREAD

**Issue by jatin-bhatt** [StackExchange/StackExchange.Redis#1804]
Getting tons of below error while performing load testing

StackExchange.Redis.RedisTimeoutException: The timeout was reached before the message could be written to the output buffer, and it was not sent, command=GET, timeout: 10000, outbound: 8939KiB, inbound: 0KiB, next: SETEX XXX, inst: 10, qu: 68, qs: 11, aw: True, bw: RecordingTimeout, rs: ReadAsync, ws: Flushed, in: 0, in-pipe: 0, out-pipe: 404785, serverEndpoint: XXX, mc: 1/1/0, mgr: 9 of 10 available, clientName: XXX, IOCP: (Busy=0,Free=10000,Min=10000,Max=10000), WORKER: (Busy=11,Free=32756,Min=10000,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)\r\n

**Comment by mgravell** [comment]
You have a huge outbound backlog. This is probably a scenario that might
map well to the proposed leased connection mode, but right now it looks
like you're saturating the outbound pipe (the inbound pipe looks empty, but
that might also be misleading if you're using TLS)

**Comment by jatin-bhatt** [comment]
@mgravell do you have any recommendation on how this can be resolved?

**Comment by mgravell** [comment]
Without more context as to what you're doing? No. Are you sending lots of
large blobs to the server in parallel here? Or?

**Comment by jatin-bhatt** [comment]
@mgravell 

I have a .NET Core web application that writes small objects (not blobs). This particular issue comes only when we do load testing on this web app to serve for concurrent request. Each request try to get object from server but fails with timeout issue. This is the piece I am getting this error. 
`await database.StringGetAsync(key, CommandFlags.PreferSlave)`

seems like, it is coming only where there is parallel request to serve.

**Comment by mgravell** [comment]
The immediate problem here is 8MiB stuck on the outbound, so it probably
hasn't even sent that command yet. The question I have is: why is there
data stuck outbound. Rhetorical, but: is it a genuine network saturation
issue? Is there a library bug where it has stuck at flushed somehow?
Unfortunately I don't have a magic wand to automatically know exactly what
happened in a particular timeout, and ultimately we can't offer consultancy
level support on every such blip.

**Comment by SimonPapworth** [comment]
We have the same problem - the SE client is not designed to work with some coding styles. We have learned to live with it though.

More front end servers is our only fix until the whole system is rewritten. we are processing about 400 http requests per second, which each http request we generate an average of 10 redis requests.

living with it - means ensuring the front door does not allow more requests than we can cope with - nginx plus does this for us

**Comment by pianoman4873** [comment]
Hi Simon, what are the "coding styles" you refer to ?
Also, is there a plan from SE.Redis to add  connection pooling to alleviate
the frequent timeout issues people report on ?

Thanks

**Comment by SimonPapworth** [comment]
Our coding style that causes the issue is using Entity framework sync calls to SQL server backend, the workers don't get back to the Redis client in time.

So to my mind the coding style is having Sync Calls.

**Comment by jatin-bhatt** [comment]
after few rounds of investigation with IT staff, I figured out that the contention in the network is due to a performance issue with the VPN, due to which it was blocking the concurrent request during load testing. 
Thanks for looking into it
