### ISSUE TITLE
Wondering if multiple threads setting the same key would confuse the innards at all?

### ISSUE THREAD

**Issue by mshiels** [StackExchange/StackExchange.Redis#1806]
We have integrated the StackExchange.Redis module into one of our programs.  And generally it's fine, works nicely, low resource usage and no problems at all.

But then we happened to end up in a situation where multiple of our threads were trying to set the same key/possibly different values, but same key - using StringSet.  And when that happens the whole world seems to collapse.  Heap corruption and vaporization often.  

Just checking, since my understanding of the redis command structure/multiplexing it - there isn't anything to tell the difference between the commands right?  Or am I mistaken?

**Comment by mgravell** [comment]
This should have no effect whatsoever; commands are multiplexed, and
ultimately: whoever ends up in the queue last: wins

If you're seeing heap corruption, something very very odd is happening. We
don't do anything particularly gnarly in the library.
