### ISSUE TITLE
Is there any settings for SlidingExpiration for specific key, like NoslidingExpiration & NoAbsoluteExpiration in Cache ?

### ISSUE THREAD

**Issue by mohamedfarrag** [StackExchange/StackExchange.Redis#181]

**Comment by mgravell** [comment]
No, because SE.Redis acts as a 1:1 map of the underlying redis functionality. Redis offers timeouts specified either as a duration from the current time or an absolute time - nothing more.

**Comment by mohamedfarrag** [comment]
OK thank you, so I think I should implement it programmatically.
