### ISSUE TITLE
IIS Hangs during load testing - possibly very large queue of MutexSlim+SyncPendingLockTokens

### ISSUE THREAD

**Issue by py224** [StackExchange/StackExchange.Redis#1815]
We are running load tests with 30 IIS webservers. We have been experiencing this issue for a while now (perhaps all the back to 2.2.4 release) and were hoping that 2.2.62 would improve things but it has not. In around 50% of our tests typically one, sometimes two, of the 30 webservers will hang and we will record a cascade (10s of thousands) of StackExchange.Redis.RedisTimeoutExceptions from just that IIS webserver. The CPU use will typically bottom out and the IIS requests will spool up and never finish. In a couple rare cases a hung IIS process will spike to 100%, but typically CPU bottoms out. We would expect in reviewing stack dumps we would see significant SE.Redis activity as we use it heavily in the code and have tried to rule out other factors but examination of the stack dumps appear to show an issue with SE.Redis (or perhaps an issue with the way we are using SE.Redis).

I may be misunderstanding the code as far as what is normal but I can see from stack dumps when it hangs that there is a very large _queue value of MutexSlim+SyncPendingLockTokens. This is the debug of a hung IIS stack dump:

![Stack Dump Debug](https://user-images.githubusercontent.com/85200947/126840516-ed90e903-cad5-48d0-85f8-fa8e340da225.png)

Under load when IIS doesn't hang we can have around 75 to 100 busy WORKER threads. When I look at stack dumps of hung servers it is typically 125+. If we do get a hang in the test it is typically during a period of ramp up volume and not during sustained consistent volume periods. Stack dumps during hangs also indicates significantly more SET commands than GETs although in a normal use case we are doing over 99.9% more GET type commands than SETs. Also note we are doing everything sync, which perhaps is pushing something too far.

![Stack Dump Thread Summary](https://user-images.githubusercontent.com/85200947/126840590-c1c72170-ed4f-4e71-a924-f1681c618e74.png)

![SETEX Error](https://user-images.githubusercontent.com/85200947/126841218-f58e75cb-7b92-4808-8c66-4132114c8fac.png)

![SETEX Error stack](https://user-images.githubusercontent.com/85200947/126841412-a30b5ba8-2056-4005-92b1-54132fcaa55b.png)

The Redis cluster itself and the network in between IIS and the cluster appear to be in good health.

A final note is that occasionally a hung IIS process will crash (and IIS will spin up a new process "fixing" the issue) but typically when it is in this state the process continues to be hung even when volume from the load test completely removed. The IIS process must be recycled to get it back into a working state.

Please let me know any thoughts you have on this. Thanks.

**Comment by NickCraver** [comment]
I missed this coming in - I see in the screenshot sync calls into the library but ultimately that's blocking application threads from a lot of stuff waiting on remote I/O synchronously. In total, whatever method is being called upstream (e.g. a StringGet or whatever) it being called more time per second than you have thread capacity for and it eventually exhausts the thread pool.

It's not a simple move, but this is _exactly_ what `async`/`await` is made to solve, to give up those threads and let them do other work while asynchronous I/O goes on. You can either dramatically increase the number of threads (bandaid) here, or work on moving at least your hot path to async. Based on past experience, often it's one or a few paths causing _most_ of the exhaustion (though, there may be another sync call right behind that one). But, moving async isn't trivial sometimes either...but it is the path to scale here. I hope that helps!

**Comment by NickCraver** [comment]
There's a new v2.5 release that'll improve this _slightly_, but not much - going async is what you want to do here but wanted to leave this open and update on that release which does a little bit of perf improvement around the backlog!
