### ISSUE TITLE
How do I properly use scripts in cluster?

### ISSUE THREAD

**Issue by vpopescu** [StackExchange/StackExchange.Redis#1816]
I thought the following is supposed to cache the scripts as needed, but I'm still seeing it raising the NOSCRIPT exceptions after I flush the scripts cache.

```
var script = "....";
... =  await LuaScript.Prepare(script).EvaluateAsync(db, params);
```

per documentation:

_StackExchange.Redis handles Lua script caching internally. It automatically transmits the Lua script to redis on the first call to 'ScriptEvaluate'. For further calls of the same script only the hash with EVALSHA is used._

So I would expect this to be cached on every "new" server it encounters. Is my assumption wrong? How should I handle if the next call is on a different node?

Or more generally, could someone recommend a high level, reliable pattern for using scripts in a cluster?

**Comment by mgravell** [comment]
The documentation there is talking about ScriptEvaluate. Does it fail in this way when using ScriptEvaluate?

**Comment by vpopescu** [comment]
Do you mean this?

```
database.ScriptEvaluateAsync(LuaScript.Prepare(script), params);
```

Yes, it still fails. Looking at redis monitor, it issued a EVALSHA only.

**Comment by vpopescu** [comment]
I added some code to catch the NOSCRIPT issue and resubmit the query, and that seems to make it reliable. I'm not sure however what the guarantee is in this case that the retry is executing on the same server as the first try.

**Comment by mgravell** [comment]
No, I mean "stop calling LuaScript.Prepare". Just use ScriptEvaluate passing the Lua as a string, using the idiomatic KEYS and ARGV approach.

It sounds like there's a problem with the LuaScript.Prepare usage with cluster; if so: we can try and fix that - but: I'm pretty sure if you just use ScriptEvaluate with a string: it should work fine

**Comment by ilia-cy** [comment]
> 

@mgravell 
We are experiencing this behavior as well.
`LuaScript.Prepare` doesn't work very well with cluster.

Question is, what is the overhead of sending scripts as strings to the `ScriptEvaluateAsync` method upon each call?
I assume that `LuaScript` preparation was introduced to make this process more efficient.
What is the "penalty" of working with raw strings instead?

Thanks
