### ISSUE TITLE
Any plan for JSON module support

### ISSUE THREAD

**Issue by WeihanLi** [StackExchange/StackExchange.Redis#1817]
Is there some plan for JSON Module support?

RedisJson: https://github.com/RedisJSON/RedisJSON

**Comment by MikaelElkiaer** [comment]
According to this there is already somewhat support:
https://github.com/StackExchange/StackExchange.Redis/issues/1459#issuecomment-627510200

**Comment by mgravell** [comment]
There is support for modules in the generic sense. We have not specifically authored an extension library for RedisJSON, but: it would not be hard to do - the API surface exists and is validated. Ultimately, it makes sense for people close to a module - either as authors, maintainers, or consumers - to do that, so they can offer a suitable API surface, and maintain it appropriately. The SE-Redis core folks: aren't actively using that module, so I'm not sure were the best people to add it.

**Comment by WeihanLi** [comment]
@MikaelElkiaer @mgravell thanks for the info
