### ISSUE TITLE
Does StackExchange.Redis have the underlying interface for sending commands？

### ISSUE THREAD

**Issue by Super-long** [StackExchange/StackExchange.Redis#1823]
Does StackExchange.Redis have an interface similar to redisCommand in hiredis or execute_command in redis-py? I don't seem to find what I need in IDatabase.cs, which is very important to me. I will close this issue after getting help, thank you very much!

**Comment by slorello89** [comment]
You can execute arbitrary commands with one of the [IDatabase.Execute](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/RedisDatabase.cs#L1198) - primary use-case is for module commands and yet-to-be-implemented commands.

**Comment by Super-long** [comment]
Thrank you very much!
