### ISSUE TITLE
RedundantMaster and TwemProxy

### ISSUE THREAD

**Issue by rkarthick** [StackExchange/StackExchange.Redis#1828]
When we are connecting to multiple proxy instances (`n` proxies), [preferred master nomination](https://github.com/StackExchange/StackExchange.Redis/blob/56ac9a21174684f30b8aa333f8069fdca77ed4e7/src/StackExchange.Redis/ConnectionMultiplexer.cs#L1906) nullifies the benefit of having multiple proxy instances and marks `n-1` proxies as unselectable with the reason `RedundantMaster` thereby forcing the selection to choose only a single fixed node all the time. Is  the preferred master nomination supposed to kick in for twemproxy mode?  

PS: I am using TwemProxy mode for connecting to a set of envoy proxies

**Comment by rkarthick** [comment]
@mgravell are you able to help :)? Looking to see if this behavior of tagging proxies as a redundant master a legit behavior or a bug. TIA

**Comment by NickCraver** [comment]
Can you share more info on the topology? e.g. are all these proxies in front of the same servers? And what would you _want_ to happen? e.g. we issue commands to a random one? or round robin?

The current behavior is expected based on your description, but knowing what you'd _want_ to happen here would help advise :)

**Comment by rkarthick** [comment]
Hi Nick, Sorry I should tweak my notifications in github. I just saw your comment.

With Envoy proxy the configuration is such that, there will be multiple proxies fronting a set of same redis servers. The desired behavior here would be to use round robin or random for envoy proxy.  I will share the idea in a separate PR to get your comments on the concrete idea. Thanks!

**Comment by rkarthick** [comment]
https://github.com/StackExchange/StackExchange.Redis/pull/1977 Would love to get your thoughts on the PR

**Comment by NickCraver** [comment]
@rkarthick Are we good to close this one out? Thanks again for all your effort here!

**Comment by rkarthick** [comment]
Yes, we are good to close this one. Thank you for all your help in this <3
