### ISSUE TITLE
High memory allocation per request

### ISSUE THREAD

**Issue by Belorus** [StackExchange/StackExchange.Redis#1832]
Hi, 

I make many Redis requests, and i see tons of new PhysicalConnections 

![image](https://user-images.githubusercontent.com/1737207/129546894-ca9357a0-a06b-40e8-b0af-a9f9cffdd8c3.png)
And each connection creates memory buffer
![image](https://user-images.githubusercontent.com/1737207/129547685-2367e766-f5a4-4681-9637-2813a4c07795.png)

I reuse same ConnectionMultiplexer and RedisDatabase instance is cached as well (by library)

Connection string is simple: `k8s-private.rix.dev.eco2g.com:6379`

Code is simple as well:

```
var connection = await ConnectionMultiplexer.ConnectAsync(_primaryConnectionString);

for (int i = 0; !stopToken.IsCancellationRequested; i++)
{
    var db = connection.GetDatabase(0);

    await _appMetrics.TrackRedisGetKey(_name, () => db.StringGetAsync("test-latency-key"));
    await _appMetrics.TrackRedisSetKey(_name, () => db.StringSetAsync("test-latency-key", i));
    await _appMetrics.TrackRedisSetHashKey(_name, () => db.HashSetAsync("test-latency-key-hash", i % 10000, 1));

    await Task.Delay(_pollingInterval, stopToken);
}
```
Here is the code that closes existing connection:
https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/PhysicalConnection.cs#L1516

So the Q is - is that okay & expected?

**Comment by mgravell** [comment]
Multiplexers are intended to be aggressively reused, not created per request

**Comment by Belorus** [comment]
@mgravell sure, thats what i said and showed in my code example:

`I reuse same ConnectionMultiplexer and RedisDatabase instance is cached as well (by library)`

**Comment by mgravell** [comment]
The only code you've shown me creates a connection, so I have to assume that a connection is always created. You see my dilemma.

**Comment by NickCraver** [comment]
Can't help here without more info - the diagnostic looks correct to us: for one connection. If you're creating a connection _for ever request_ then that's where the issue lies and the multiplexer should be re-used. There's a conflict in data here from what's being said in the title vs. comments. If there's an actual issue, happy to re-open.

**Comment by Belorus** [comment]
Connection is REUSED. I've attached the code, and inside the loop there is no connect

**Comment by Belorus** [comment]
> The only code you've shown me creates a connection, so I have to assume that a connection is always created. You see my dilemma.

The only code i shown creates single connection and makes millions of requests in loop

**Comment by NickCraver** [comment]
@Belorus we will reconnect _when it fails_, but that's not _per request_ as the issue it stating here. If you're seeing that behavior it means your socket is closing very often and there should be exceptions associated with that. If _that's_ happening then that's the issue. Reconnect itself using resources it not unexpected, what's unexpected is it happening often and that's likely an issue of overload in your test on the client, or the server side, or bandwidth between.
