### ISSUE TITLE
match keys

### ISSUE THREAD

**Issue by wdqzdd** [StackExchange/StackExchange.Redis#1833]
my keys
order:detail:1
order:detail:2
order:detail:3
order:detail:4
order:detail:5
......
i want to get all my keys like order:detail:*
What do I do?

**Comment by mgravell** [comment]
The SCAN API is available via IServer - see
https://stackexchange.github.io/StackExchange.Redis/KeysScan.html -
however, it is important to emphasize that what you're asking for is an
expensive server operation, and it is usually preferable to find other
options. For example, you could use a hash of "order:detail" with sub-names
1/2/3 - there are APIs for getting all sub-keys (with or without values)
from a hash.
