### ISSUE TITLE
Pub sub in cluster mode, not seeing the replicas service traffic

### ISSUE THREAD

**Issue by greyhoundgames** [StackExchange/StackExchange.Redis#1835]
I had just figured out that my main redis cluster(AWS) was not using its replicas because I had failed to use 
CommandFlags.PreferReplica during reads. After adding this, the metrics data showed the traffic split nicely between the replicas. Great!
I went to my other redis cluster I have which is a chat app and I did the same thing on it. However in this case it was a pub\sub where as the first cluster was doing string gets.

I added the PreferReplica in the subscribe. However here the traffic does not seem to have been spread out evenly. Is there a problem with replicas when using pub sub?

Code used to subscribe:
ISubscriber subscriber = RedisHelpers.ConnectionChat.GetSubscriber();
subscriber.Subscribe(user.room + ChatConstants.MESSAGES_SUB, chatCallback, CommandFlags.PreferReplica);

SDK version: Nuget 2.2.62
AWS redis Engine Version Compatibility: Version compatibility of the engine that will be run on your nodes 6.0.5
Cluster config 1 shard, 3 nodes, 2 of which are replicas.

**Comment by NickCraver** [comment]
Indeed there is! We found this later (recently) following up on issues. Specifically there's a bug in sharding around a `default(RedisKey)` path that @mgravell is looking into as part of #1912. Once a fix goes in that PR (or is broken into another), we'll update here.

**Comment by NickCraver** [comment]
This is drastically improved in #1947 and will be in the 2.5 release - thank you for the detail! It'll still prefer the first replica but this should be an improvement over current. This preference is kept in mind across reconnects now as well.
