### ISSUE TITLE
Support for StringGetLease and StringGetLeaseAsync using enumerables

### ISSUE THREAD

**Issue by simonasB** [StackExchange/StackExchange.Redis#1842]
Hello Team,

First of all, thank you for your all great work and effort to develop this library. I learned a lot about the C# just by reading the library code.

I noticed a great feature called `Lease` which uses the shared byte pool to prevent allocations. I took a glance at the code and saw that it should be not that difficult to add support to return an array of leases. The issue with the array is that all the leases should be in memory and it would explode the pool immediately and there would no advantage (maybe even disadvantage) to use it.

The issue with enumerables is that such code is impossible to execute due to `struct` constraints.

```c#
        internal IEnumerable<Lease<byte>> GetItemsAsLeaseEnumerable()
        {
            foreach (var rawResult in this.GetItems())
            {
                yield return rawResult.AsLease();
            }
        }
```
Compile gives error: `foreach` statement cannot operate on enumerators of type Sequence<RawResult>.Enumerator in async or iterator.

Would it be possible to support enumerables (`IEnumerable<Lease<byte>>`, `IAsyncEnumerable<Lease<byte>>` without big breaking changes internally? Have you ever considered this?

Thank you for your time and thoughts in advance.

**Comment by NickCraver** [comment]
Hi there! Indeed this would be a breaking change. We do memory reuse internally already, so this would only serve as a breaking change on the benefits/trade-offs front. The largest problem with leased-based implementations is lifetimes, when the lifetime of a lease consumer it beyond your control, you can't really return the lease effectively (or default to GC for doing so). This makes exposing them on an API surface tricky at best and dangerous/confusing at worst :)

**Comment by simonasB** [comment]
Thank you for your response. I see, your reasoning makes sense. We wanted to optimize the allocations as much as possible and it seemed like a possibility. We are happy with the current state, just wanted to hear what you think as authors. I think this can be closed.
