### ISSUE TITLE
Async redis requests not resolved when connection fails at certain times.

### ISSUE THREAD

**Issue by johndaniels** [StackExchange/StackExchange.Redis#185]
After taking a core dump when we had issues with Redis in production, we observed that some of our threads were hanging on waiting for an asynchronous request to complete. It appears that in certain cases, if the connection has an issue, the tasks associated with those requests may fail to be resolved, leaving those threads hanging. I believe this may also causes further issues with being unable to reconnect quickly because of thread pool exhaustion, but I'm not sure.

My current hypothesis is that if OnDisconnected is called in PhysicalBridge, for example because of a slow heartbeat, we may not call RecordConnectionFailed on the PhysicalConnection. Not sure if I understand the code well enough to make that determination though.

**Comment by nmehlei** [comment]
If this is indeed the case, it could explain a bug in our application that is extremely hard to reproduce.

**Comment by mgravell** [comment]
Sounds bad. On my list to look at. This shouldn't cause thread pool
starvation, but it could definitely cause problems.

**Comment by nmehlei** [comment]
@mgravell Did you find time to take a look at this?

**Comment by NickCraver** [comment]
Is this still an issue you're seeing in current versions? A huge number of fixes in the pipeline have gone in since this was opened, and we missed updating it along the way - sorry about that :(
