### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException: Timeout performing GET 

### ISSUE THREAD

**Issue by meghaaprasad** [StackExchange/StackExchange.Redis#1858]
Hello,

I have my .net framework 4.7.2 api connecting to Redis cache hosted on AWS. Intermittently I see following error in my logs

StackExchange.Redis.RedisTimeoutException: Timeout performing GET 27_00270dd8-dcd5-4b70-a9e8-2cb205c0ab87, inst: 1, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: TEST-IIS, serverEndpoint: XXXXXXX:6379, keyHashSlot: 12013, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts) ||    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl{T}(Message message, ResultProcessor`1 processor, ServerEndPoint server) ||    at StackExchange.Redis.RedisBase.ExecuteSync{T}(Message message, ResultProcessor`1 processor, ServerEndPoint server) ||    at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)

My nuget version is 1.2.4

**Comment by mgravell** [comment]
That looks like a legit timeout to me. On later library versions, we
increased the default timeouts for obvious cloud providers, although I
don't know if we'd have caught this one in that net, but ultimately: you're
also using a *very* old library version, so... there isn't anything we
could change even if it looked like a library failure.

**Comment by meghaaprasad** [comment]
Would you suggest to just upgrading the library version?

**Comment by meghaaprasad** [comment]
So my issue here is with latest version update my application fails with following error
The assembly for System.Runtime.CompilerServices.Unsafe + System.Runtime.CompilerServices.Unsafe could not be loaded; this usually means a missing assembly binding redirect - try checking this, and adding any that are missing; note that it is not always possible to add this redirects - for example 'azure functions v1'; it looks like you may need to use 'azure functions v2' for that - sorry, but that's out of our control

Is there a way to eleviate the issue with current version?

**Comment by mgravell** [comment]
I don't know of one, but I'm not an Azure functions user - did it at least
correctly identify your scenario?

**Comment by NickCraver** [comment]
The newer release of Azure Functions has better binding support here (though .NET Core eliminates this issue completely). As far as I know, there's no way to resolve this with the old version of functions...one of the platform changes allows fixing your situation.

**Comment by NickCraver** [comment]
Closing out to cleanup!
