### ISSUE TITLE
Redis cluster?

### ISSUE THREAD

**Issue by KevinBurton** [StackExchange/StackExchange.Redis#186]
Would it be possible to add a simple example of how to get a cluster up and running with StackExchange.Redis?

**Comment by mgravell** [comment]
Good idea; with 3.0 released I need to buff up the docs for this. Will do.

**Comment by NickCraver** [comment]
This is now present in the test project itself - see there for a reference, or see the tutorial here :) https://redis.io/topics/cluster-tutorial
