### ISSUE TITLE
getting timeout exception on redis 6 as well as on redis cluster on high load

### ISSUE THREAD

**Issue by KamranShahid** [StackExchange/StackExchange.Redis#1860]
I am using .net core 3.1 with stackexchange.redis version 2.2.62
On high load i am frequently getting exception .
I have set minio thread to 5000 in my application and other setting are

"KeepAliveDuration": 180,
    "SyncTimeout": 10,
    "ConnectTimeout": 10,

StackExchange.Redis.RedisTimeoutException: Timeout performing GET (10000ms), inst: 0, qu: 4804, qs: 0, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: 10.120.2.254:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: SafeRedisConnection_AuthApi_09/17/2021 13:25:16, PerfCounterHelperkeyHashSlot: 6430, IOCP: (Busy=0,Free=32767,Min=4,Max=32767), WORKER: (Busy=4890,Free=27877,Min=5000,Max=32767), v: 2.2.62.27853 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)
   at Auth.Common.Caching.RedisManager.GetStringItem(String key)

StackExchange.Redis.RedisTimeoutException: Timeout performing ZREM (10000ms), active: GET InProcessingChangeSecretGenerationRequest_63983891179_2, next: HSCAN InProccessingMsisdnTransaction_63013933686 ** possible thread-theft indicated; see https://stackexchange.github.io/StackExchange.Redis/ThreadTheft ** , inst: 0, qu: 326, qs: 315, aw: False, bw: Inactive, rs: CompletePendingMessageSync, ws: Idle, in: 12061, in-pipe: 441977, out-pipe: 0, serverEndpoint: 10.120.2.171:6379, mc: 1/1/0, mgr: 9 of 10 available, clientName: SafeRedisConnection_AuthApi_09/17/2021 13:25:16, PerfCounterHelperkeyHashSlot: 4194, IOCP: (Busy=0,Free=32767,Min=4,Max=32767), WORKER: (Busy=4895,Free=27872,Min=5000,Max=32767), v: 2.2.62.27853 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.SortedSetRemove(RedisKey key, RedisValue member, CommandFlags flags)
what can i do to avoid these errors

**Comment by KamranShahid** [comment]
one thing i am trying out is ConnectionMultiplexer.SetFeatureFlag("preventthreadtheft", true);

**Comment by Ohad29** [comment]
same here....
i really do not understand way i get the timeout as Redis look like he has no influence and i go get it from the client.
you are running on 5000 thread? how many servers you have? connections ?

**Comment by NickCraver** [comment]
@KamranShahid my recommendation here is to get a dump of the process and see what all those threads are doing. With nearly 5000 threads busy you have a _lot_ of contention. It's either blocking or synchronous waiting most likely. A dump of this would tell you what so many threads are doing - you can pop it into Visual Studio to see what all the threads are. There's not a shortcut to fix this on the client...upstream or downstream you have a major resource issue that's hopefully one or two code paths to make async or reduce locking on to improve life greatly.

**Comment by KamranShahid** [comment]
Thanks @NickCraver 
Will try to do it in future if similar thing again occurs
