### ISSUE TITLE
 mc: 1/1/0 stands for?

### ISSUE THREAD

**Issue by RyanLiu99** [StackExchange/StackExchange.Redis#1861]
In page https://github.com/StackExchange/StackExchange.Redis/blob/main/docs/Timeouts.md

Section "Explanation for abbreviations appearing in exception messages", one thing is missing.

I saw mc: 1/1/0 from exception message, what is "mc" stands for?

Thanks!

**Comment by philon-msft** [comment]
See https://github.com/StackExchange/StackExchange.Redis/blob/51d2946b7f1499605d90b95a00bcb8f776ff0b49/src/StackExchange.Redis/ExceptionFactory.cs#L343

Add(data, sb, "Multiplexer-Connects", "mc", $"{multiplexer._connectAttemptCount}/{multiplexer._connectCompletedCount}/{multiplexer._connectionCloseCount}");

**Comment by RyanLiu99** [comment]
Thanks Philon.
