### ISSUE TITLE
more detail regarding Explanation for abbreviations appearing in exception messages

### ISSUE THREAD

**Issue by RyanLiu99** [StackExchange/StackExchange.Redis#1868]
I just hope this table can be little bit deeper:
https://stackexchange.github.io/StackExchange.Redis/Timeouts#explanation-for-abbreviations-appearing-in-exception-messages, like what is  difference between abbreviation  "in" and "in-pipe", what is pipe in Redis Client and how buffer is used? Basically more detail  how Redis client send and receive  data.

For abbreviation "rs", explain each state meaning, or better have a state chart.  CompletePendingMessageAsync is not even in "Possible values", and ReadSync shown twice.   What happens when Read-State is faulted?

**Comment by NickCraver** [comment]
@RyanLiu99 These values are for us to look in code and reason about where things were - there aren't deeper meanings than the names here, and they could change. Overall: what's the goal you're after? It'd make the table itself pretty large to have descriptions for these and I'm not sure it'd help the average user...it's primary for getting exceptions back here in Issues.

**Comment by NickCraver** [comment]
See #1892 for a proposal on how we can improve quite a bit with some effort here - closing this out to collapse into 1 thread :)
