### ISSUE TITLE
Weird bug publish returns 0 when someone is subscribed

### ISSUE THREAD

**Issue by albertjan** [StackExchange/StackExchange.Redis#187]
We're only seeing it after version 371. Is there a possibility to see a which commit actually is 371? So I can diff the two version.

**Comment by mgravell** [comment]
Hmmm; annoyingly my build internal server appears to only have history back to 408 - presumably someone upgraded the build server software and reset some things; not sure why history would be ditched. Looks like there are a *lot* of commits after the "Sep 18, 2014" commit, which presumably ties into 333. Can you repro in a sample?

**Comment by mgravell** [comment]
Also: I wonder if they are subscribed to a unique channel vs a pattern. That may make a difference, IIRC.

**Comment by albertjan** [comment]
I subscribe to a unique pattern using the sync version of `Subscribe`. And I publish as part of a `MULTI`. 

The problem is hard to reproduce. We only see it on our @appveyor builds. I kinda have the feeling it's tied into the fact those machines have only one core. But it might also be the exact .net version. 

I've tried setting the `maxthreads` flag of the test runner to 1 but one thread on a multicore machine and multiple threads on a single core machines isn't the same ofcourse. 

I could try to make a small project that triggers this on Appveyor. But I don't know if thats of any use. I was planning on sifting through the changes between 371 and 394 and see if I can find what going on by "eyeballing" the code.

**Comment by mgravell** [comment]
If you subscribe and publish at the same time, there is a race condition:
those things happen on separate TCP connections. Is this possibly related?

**Comment by albertjan** [comment]
Not exactly the same time I subscribe to three channels in the constructor and publish in a function call on the created object. I used the sync version of `Subscribe` to prevent this exact race condition from happening.

**Comment by mgravell** [comment]
That may not be sufficient in this case. Let me check the code later (I'm
in "family time" at the moment).

Marc

**Comment by albertjan** [comment]
@mgravell take your time. :smile:

**Comment by albertjan** [comment]
magically fixed in version 481
