### ISSUE TITLE
ReconnectRetryPolicy 重连策略设置无效果

### ISSUE THREAD

**Issue by aaa930811** [StackExchange/StackExchange.Redis#1871]
在程序运行中途如果redis服务出现问题导致连接断掉之后，重连策略设置不起作用，只有在第一次调用ConnectionMultiplexer.Connect的时候重连策略才起作用，我在配置文件里面设置了connectRetry次数，但是日志显示无论无何设置都只重连3次，这是我的Redis连接字符串192.168.1.234:6379,password=123456,abortConnect=false,connectRetry=10,connectTimeout=10000
~~~
        private readonly ConnectionMultiplexer _context;

        public RedisRepository(string connStr, ILoggerFactory logger)
        {
            if (_context == null || !_context.IsConnected)
            {
                ConfigurationOptions configOptions = ConfigurationOptions.Parse(connStr);
                configOptions.ReconnectRetryPolicy = new ExponentialRetry(5000);
                _context = ConnectionMultiplexer.Connect(configOptions, new TextWriterLogger(logger));
            }
        }
~~~

**Comment by NickCraver** [comment]
In the code presented here, how it is called? The way it's currently written during an initial connect for example you could have hundreds of thousands of simultaneous connections fired off before the first connected and hit socket exhaustion for example. Note that the log passed into connect _is only for the connection_, and not held on to or written to afterwards. We're looking to add a circular log buffer for the last `n` connections, but seeing a few in your log here isn't surprising. It'd help to have the contents of that connection log though, to provide any further advice.

**Comment by NickCraver** [comment]
Happy to help with more info here - if any is available happy to re-open!
