### ISSUE TITLE
resolveDns clarification pls?

### ISSUE THREAD

**Issue by jchowdown** [StackExchange/StackExchange.Redis#1878]
Hi, I found this configuration option and was wondering if anyone can provide a bit more info about what it does:

**resolveDns={bool}**
Specifies that DNS resolution should be explicit and eager, rather than implicit

Does this control whether a server address is cached or is updated periodically?

Thanks,
Jeff

**Comment by NickCraver** [comment]
Closing this out to cleanup :)
