### ISSUE TITLE
Unable to connect to Redis due to authentication - ConnectionFailureType

### ISSUE THREAD

**Issue by sagimar** [StackExchange/StackExchange.Redis#1879]
Hi,

In case the connection with Redis failed due to authentication failure (e.g. password is configured incorrectly due to key rotation),
the ConnectionFailureType that is returned is ConnectionFailureType.UnableToConnect.

My suggestion is in this case to return ConnectionFailureType.AuthenticationFailure
Thus, me as a client, can decide to disconnect Redis and retry with a new primary key that I have fetched.

The automatically retry mechanism of IMultiplexer would never success to connect with its own retry policy, but I don't want to catch any RedisConnectionException.

Is there any reason that the function returns ConnectionFailureType.UnableToConnect instead of ConnectionFailureType.AuthenticationFailure in this case?

https://github.com/StackExchange/StackExchange.Redis/blob/51d2946b7f1499605d90b95a00bcb8f776ff0b49/src/StackExchange.Redis/ExceptionFactory.cs#L392-L403

Thanks,
Sagi

**Comment by NickCraver** [comment]
Looked through the path here: there's no reason it's this way other than it hasn't been improved past that point. I think we can likely detect this can and be more specific - tagging this to take a look when time allows.
