### ISSUE TITLE
Newest release 2.2.62 is not shown in nuget.org

### ISSUE THREAD

**Issue by patspaeth** [StackExchange/StackExchange.Redis#1881]
I saw in the release notes that there is a new version 2.2.62 available: https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes.html

But I do not find it on nuget.org
https://www.nuget.org/packages/StackExchange.Redis/

Did I miss something?

Thanks
Patrick

**Comment by mgravell** [comment]
2.2.62 is currently unlisted due to some instability issues; a new deploy with remediation should be dropped soon

**Comment by patspaeth** [comment]
Thanks for clarification!
