### ISSUE TITLE
How to find out the dependent files of 【System.Diagnostics.PerformanceCounter】?

### ISSUE THREAD

**Issue by kasini3000** [StackExchange/StackExchange.Redis#1884]
on .net 5,StackExchange.Redis dependent 【System.Diagnostics.PerformanceCounter】

what files is 【System.Diagnostics.PerformanceCounter】dependent？
or none?  help to look.

.NETCoreApp 2.0
Microsoft.NETCore.Platforms (>= 5.0.1)
Microsoft.Win32.Registry (>= 5.0.0)
System.Configuration.ConfigurationManager (>= 5.0.0)
System.Memory (>= 4.5.4)
System.Security.Principal.Windows (>= 5.0.0)
.NETCoreApp 2.1
Microsoft.NETCore.Platforms (>= 5.0.1)
Microsoft.Win32.Registry (>= 5.0.0)
System.Configuration.ConfigurationManager (>= 5.0.0)
System.Security.Principal.Windows (>= 5.0.0)
.NETFramework 4.6.1
No dependencies.
.NETStandard 2.0
No dependencies.
MonoAndroid 1.0
No dependencies.
MonoTouch 1.0
No dependencies.
Xamarin.iOS 1.0
No dependencies.
Xamarin.Mac 2.0
No dependencies.
Xamarin.TVOS 1.0
No dependencies.
Xamarin.WatchOS 1.0
No dependencies.

detailed:
I stored these files in the .net5 directory, but the hashscan function still doesn't work.
MethodException: Cannot find an overload for "HashScan" and the argument count: "4".

Pipelines.Sockets.Unofficial.dll
Pipelines.Sockets.Unofficial.xml
StackExchange.Redis.dll
StackExchange.Redis.xml
System.Diagnostics.PerformanceCounter.dll
System.Diagnostics.PerformanceCounter.xml
System.IO.Pipelines.dll
System.IO.Pipelines.xml

**Comment by mgravell** [comment]
A: what makes you think these two things are related? (Genuine question, not being snarky)
B: is this powershell related?
