### ISSUE TITLE
Unexpected response to GET: MultiBulk: 1 items

### ISSUE THREAD

**Issue by IgorKrav4enko** [StackExchange/StackExchange.Redis#1889]
Hi, 
we use 2.1.58 version of Redis
this code call Redis client 

```
                var db = _connection.GetDatabase();
                var snapshotInfoKey = CreateSnapshotInfoKey(streamName);

                string json = await db.StringGetAsync(snapshotInfoKey, CommandFlags.PreferReplica);

                if (json == null) return (false, null);

                var info = JsonConvert.DeserializeObject<SnapshotInfoMessage>(json);
                return (true, info);
```
we use such connection string **redis-instance:26379,serviceName=mymaster**

and this code writes data to Redis

 ```
 var snapshotInfoKey = CreateSnapshotInfoKey(snapshot.StreamName);
                    var snapshotInfo = new SnapshotInfoMessage
                    {
                        BulkNumber = snapshot.BulkNumber,
                        ChunksCount = snapshot.Chunks.Length,
                        StreamerId = snapshot.StreamerId
                    };
                    var json = JsonConvert.SerializeObject(snapshotInfo);
                    await db.StringSetAsync(snapshotInfoKey, json);
```

also, we use such cluster settings 

```
 chart:
    repository: https://charts.bitnami.com/bitnami
    name: redis
    version: 14.1.1
  values:
    clusterDomain: cluster.local
    image:
      registry: docker.io
      repository: bitnami/redis
      tag: 6.2.3-debian-10-r0
      pullPolicy: IfNotPresent
      pullSecrets: []
      debug: false
    architecture: replication
    commonConfiguration: |-
      save 60 1000
      save 900 1
      repl-timeout 360
      appendonly no
      maxmemory 6G
    replica:
      replicaCount: 3
      configuration:
      disableCommands:
        - FLUSHDB
        - FLUSHALL
      command: []
      args: []
      preExecCmds: []
      extraFlags: []
      extraEnvVars: []
      containerPort: 6379
```

and sentinel 

```
    sentinel:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/redis-sentinel
        tag: 6.2.2-debian-10-r12
        pullPolicy: IfNotPresent
        pullSecrets: []
        debug: false
      masterSet: mymaster
      quorum: 2
      downAfterMilliseconds: 10000
      failoverTimeout: 10000
      cleanDelaySeconds: 5
      parallelSyncs: 1
      staticID: false
      configuration:
      command: []
      args: []
      preExecCmds: []
      containerPort: 26379

```

in our project, we got such an exception.
{
    "RenderedMessage": "An error has occurred while getting snapshot info from Redis. ClientId = \"OutrProjectApi-fa79cc7801994bb782115cbce3f898a6\", StreamName = \"/api/v1/machine001/sd/snapshots\"",
    "Timestamp": "2021-10-09T14:54:41.5932168+00:00",
    "Level": "Error",
    "MessageTemplate": "An error has occurred while getting snapshot info from Redis. ClientId = {ClientId}, StreamName = {StreamName}",
    "Exception": "StackExchange.Redis.RedisConnectionException: **Unexpected response to GET: MultiBulk: 1 items**\n   at OurProject.Infra.RedisClient.RedisClient.GetSnapshotInfo(String streamName) in /app/src/OurProject.Infra.RedisClient/RedisClient.cs:line 95",
    "@timestamp": "2021-10-09T14:54:41.593Z"
}

we have only one Redis instance for writing, and two instances for reading

unfortunately, we can`t reproduce this bug in tests. After that bug, we experienced some issues with the connection to Redis  Can you help us with it?

**Comment by NickCraver** [comment]
Which version of Redis server are you hitting this on?

**Comment by IgorKrav4enko** [comment]
And one more update. After investigation, we find that redis ConnectionMultiplexer property IsConnected returns true, but GetDatabase() return StackExchange.Redis.RedisConnectionException: Unexpected response to GET: MultiBulk: 1 items

**Comment by NickCraver** [comment]
Since we can't do more to help here without the info on what's happening, closing this out to cleanup. Happy to re-open if there's something to track down.
