### ISSUE TITLE
HashSet key exists assignment returns false value modified successfully

### ISSUE THREAD

**Issue by linyi888** [StackExchange/StackExchange.Redis#1897]
Hello!
We are using StackExchange.Redis version 2.2.79 in a .NET Core 3.1
HashSet key exists assignment returns false value modified successfully

 class Program
    {
        static void Main(string[] args)
        {
            var connect = ConnectionMultiplexer.Connect("127.0.0.1:6379,password=,abortConnect=False,syncTimeout = 30000,connectTimeout=30000,responseTimeout=30000,allowAdmin = true");
            IDatabase dbObj = connect.GetDatabase();

            for (int i = 0; i < 2; i++)
            {
                var issuccess = dbObj.HashSet("a", "b", "111");
                Console.WriteLine(issuccess);
            }
            Console.ReadLine();
        }
    }

**Comment by testfirstcoder** [comment]
@linyi888  See https://redis.io/commands/hset#return-value

HSET command returns the number of fields that were added and not a successful state. 

See also - https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/Interfaces/IDatabase.cs#L356

If a field already exists in the hash and the value was updated, than `false`

**Comment by linyi888** [comment]
thank you

**Comment by linyi888** [comment]
thank you But how do I judge whether the update is successful?

**Comment by NickCraver** [comment]
@linyi888 An error would be thrown if the command failed to set it at all - is that what you're trying to determine here?

**Comment by NickCraver** [comment]
I think the above covers here so closing out to tidy up, but happy to reopen if not!
