### ISSUE TITLE
net core 6.0 ERR Error running script

### ISSUE THREAD

**Issue by YongChingShieh** [StackExchange/StackExchange.Redis#1904]
option
   builder.Services.AddStackExchangeRedisCache(options =>
    {
        //options.ProfilingSession = () => new ProfilingSession();
        options.Configuration = RedisConn;
        options.InstanceName = "SampleInstance";// InstanceName;
    });
 public LoginController(IDistributedCache distributedCache)
        {
            Cache = distributedCache;
            
        }
public void Test()
{
Cache.SetString(Key, "123");
}

error log 
StackExchange.Redis.RedisServerException: ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script 
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2815
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1189
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.Set(String key, Byte[] value, DistributedCacheEntryOptions options)
   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.SetString(IDistributedCache cache, String key, String value, DistributedCacheEntryOptions options)
   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.SetString(IDistributedCache cache, String key, String value)

**Comment by fairok** [comment]
I have the same ERR after upgraded to NET6 today.

**Comment by YongChingShieh** [comment]
upgrading Redis 5.0.14(tporadowski/redis/releases) the issue was resolved.

**Comment by fairok** [comment]
> upgrading Redis 5.0.14(tporadowski/redis/releases) the issue was resolved.

Yeah, it works, Thank you!

**Comment by mgravell** [comment]
Very confused here... an error started happening when you upgraded to .net 6, but went away again when you changed *the server*? This.... Sounds very odd.

**Comment by mstavrev** [comment]
Why is this issue closed? It must not be required to upgrade the Redis server used for a deployment when switching to net core 6.0. If the library has dependency on newer Redis server functionality it must be an opt-in feature.

**Comment by YongChingShieh** [comment]
> Why is this issue closed? It must not be required to upgrade the Redis server used for a deployment when switching to net core 6.0. If the library has dependency on newer Redis server functionality it must be an opt-in feature.

seen this

> FYI it looks like the current supported version of Redis are > 5.2: https://docs.redislabs.com/latest/rs/administering/product-lifecycle

https://github.com/dotnet/aspnetcore/issues/33628

**Comment by mstavrev** [comment]
Thanks for the update. My bad, I had the issue on a CentOS 7 box where Redis is at 3.2 and there is no official update available to newer version. Box had been upgraded and issue resolved.

**Comment by BarryJame** [comment]
i have the same problems,looking forward to reslove it.

**Comment by mgravell** [comment]
Found it; here's a timeline:

- redis 2.0 had `HSET key field value` for setting individual hash fields, and `HMSET key field value [field value ...]` for setting multiple hash fields (against the same key); as you can see, there's a lot of overlap here
- redis 4.0 observes this redundancy, and adds `HSET key field value [field value ...]`, and also *marks `HMSET` as deprecated*, although it still works fine
- .NET 6 [switches to using the non-deprecated API](https://github.com/dotnet/aspnetcore/commit/bf4d9b9bd0d11e4e46924e4e09014580ec1a1449)

Unfortunately, this means that if you are using a redis server lower than 4.0, *it won't work*. Completely outside of the control of this library. I'll ping `dotnet/aspnetcore` to make the problem explicit, but it may be a "update your server" response. Not my call.

**Comment by eranda1985** [comment]
As @mgravell had mentioned, I reduced the middleware (Microsoft.Extensions.Caching.StackExchangeRedis) version down to 5.0.0  and that worked.
