### ISSUE TITLE
Performance issues in docker linux container in .NET 5

### ISSUE THREAD

**Issue by Simonsimu** [StackExchange/StackExchange.Redis#1907]
Earlier we have hosted a dotnet core web application in IIS, the app interacts with Redis using StackExchange.Redis (2.0.601) client .

For every request, it will make a Redis get & set when throughput is more than 3K calls per minute on average it took 1-3ms for each interaction

Now we have hosted the same app in docker Linux container and started facing latency in Redis when throughput is close to 1K calls per minute it's taking more than 100ms and keeps on increasing with load

I tried the following things but the issue was not resolved, 
Upgraded the StackExchange.Redis client to the latest stable version 
Verified if multiple connections to Redis are made (Using only one connection for all Redis interactions)

**Comment by andrey-chernykh** [comment]
First of all, you need to check, that you have no issue in your container. You can use [redis-cli](https://redis.io/topics/rediscli#monitoring-the-latency-of-redis-instances).
If you are using Kubernetes/docker please note, that you can face [throttling](https://medium.com/omio-engineering/cpu-limits-and-aggressive-throttling-in-kubernetes-c5b20bd8a718). (Your pod will be stopped for up to 100ms if you have exceeded the CPU limit)

**Comment by Simonsimu** [comment]
Thanks for the response, we tried running the application without any limits. when throughput is high more than 1k CPM the response times are high

**Comment by Simonsimu** [comment]
Hi team, the issue was resolved after increasing the minimum worker threads in the thread pool
program.cs -> `  ThreadPool.SetMinThreads(workerThreads, completionPortThreads); `
Actually, the reporting tool we are using (newrelic) is showing it as latency but there few redis time-outs that are happening. After increasing the worker threads even at high load the response time are under 2-3ms.

**Comment by BrunoJuchli** [comment]
@Simonsimu

Do you recall whether you need a larger ThreadPool in Linux than in Windows or whether the default size your linux docker container just was smaller than of your windows setup?
Thank you
