### ISSUE TITLE
.NET 6 target support

### ISSUE THREAD

**Issue by WeihanLi** [StackExchange/StackExchange.Redis#1909]
Any plan for adding .NET 6 target? We could get benefits from some new API introduced in .NET 6.

- `WaitAsync` for `TimeoutAfter` extensions
- `Random.Shared` for `Random` usage
- `PeriodicTimer` for `Timer` usage

maybe more ...

**Comment by NickCraver** [comment]
We may indeed do a few of these things, at the moment there's another appealing option which is to default to the shared thread pool implementation of the pipe scheduler specifically on net6.0 which has some counter and action changes around sync-over-async blocking which was one of the core reasons our custom threadpool remains today. We're going to try in the alpha changing this and looking at behavior to better scale to various size applications and core counts :)

**Comment by NickCraver** [comment]
I've got a PR for .NET 6 in #1939, but I'm not sure about the usages in the issue here - there's a code quality tradeoff because all of them are `#if NET6_0_OR_GREATER` forks in many places to make them work. If there's a significant win to take it's a good avenue, but past that we'll probably go for simple :)

**Comment by NickCraver** [comment]
Heads up: this is being reverted in #1992 due to thread pool issues so no release changes planned at this point. I'll be tracking some things down there with the .NET team.

**Comment by NickCraver** [comment]
I'm going to close this out to tidy up - after trying these things out and more importantly how .NET 6 thread pool behaves (specifically not tying into `Monitor.Wait()` as I assumed), no plans to do a .NET 6 specific build. Maybe down the road, but the split in code isn't worth another TFM :)
