### ISSUE TITLE
notRemovable equivalent in StackExchange.Redis

### ISSUE THREAD

**Issue by keertisomu** [StackExchange/StackExchange.Redis#1911]
Hi,

we are currently writing a new implementation of our caching system using StackExchange.Redis . Our in memory implementation had usages of CacheItemPriority.NotRemovable (System.Runtime.Caching). [link](https://docs.microsoft.com/en-us/dotnet/api/system.web.caching.cacheitempriority?view=netframework-4.8)

Can you please suggest how this can be implemented with Redis? Based on looking at the documentation the only closest way to implement this is by using CommandFlags.FireAndForget or CommandFlags.PreferMaster . But however i would like to get your feedback on how this can be handled.

Thanks.

**Comment by mgravell** [comment]
FireAndForget and PreferMaster are unrelated concepts; what you seem to be discussing maps most closely to the server's [eviction policy](https://docs.redis.com/latest/rs/administering/database-operations/eviction-policy/) - however, that is a server-wide setting, not a per-key setting. Either way: I think this is a redis question, not a client library question. I doubt that there is anything client-specific we can do to help here.

**Comment by mgravell** [comment]
Sorry wrong link; for most users, the [redis.conf](https://raw.githubusercontent.com/redis/redis/6.0/redis.conf) file is more relevant, referring specifically to the section on `maxmemory-policy`

**Comment by keertisomu** [comment]
thanks for the response.
