### ISSUE TITLE
Error using Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache 6.0.0

### ISSUE THREAD

**Issue by davitgr** [StackExchange/StackExchange.Redis#1917]
After upgrading from .NET 5 to .NET 6, we are unable to write to the Redis cache using IDistributedCache.SetAsync in our WebAoi project. It works in in .NET 5 but not .NET 6. Below is the error message and also the code (_cache is IDistributedCache). Please advise, as this is breaking our application currently.

    private async Task CacheSet(string key, object value, TimeSpan? expiration = null)
    {
        await _cache.SetAsync(key, value.ToByteArray(),
            new DistributedCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = expiration ?? _cacheExpiration
            }).ConfigureAwait(false);
    }
2021-11-23 15:20:32.7672||ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request. ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script
2021-11-23 15:20:32.7750||ERROR|LoggerService.LoggerManager|Something went wrong: at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.SetAsync(String key, Byte[] value, DistributedCacheEntryOptions options, CancellationToken token)

**Comment by mgravell** [comment]
OK. I can only speak on behalf of the SE-Redis library. Does *that* connect and work when used by itself? Very few of the things mentioned in the question seem directly related to the library, which makes it hard to comment.

**Comment by ISV-Kran** [comment]
Same here

**Comment by mgravell** [comment]
@ISV-Kran if you're saying that *updating the server* fixes this, then: it doesn't sound like a library issue

**Comment by NickCraver** [comment]
Updating this issue as well - see https://github.com/dotnet/aspnetcore/issues/38715 for details, this was a break in v6 of the caching layer on top of us against older Redis servers. We're aiming to get a fix in there, since there's nothing StackExchange.Redis can do with this literal LUA script in play.

**Comment by NickCraver** [comment]
When https://github.com/dotnet/aspnetcore/pull/38927 is merged and released, the latest .NET 6.0 should be working as expected on older servers again :)

**Comment by Joseph-Anthony-King** [comment]
Hi @NickCraver, I ran into this issue and reviewed the above ticket... I'm seeing that the status is still merged, is a release pending?  Sorry if this question is academic but this is my first submission on an issue and I haven't tracked this before.  Thank you

**Comment by mgravell** [comment]
@Joseph-Anthony-King that is completely out of our hands and influence. I was going to add "knowledge" to that list, but I had a look and could see no evidence of a point release on the public site. You would need to ask the owners.

**Comment by Joseph-Anthony-King** [comment]
Thank you  @mgravell, I meant to direct this to the Nick who is on that team so sorry about the confusion... the question should have been asked on the branch he mentioned.  I went ahead and asked the question there.  Thank you for following up on this.

**Comment by NickCraver** [comment]
I'm going to close this on out to cleanup - for anyone following this will be resolved in the 6.0.2 package release of the upstream https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis package - releases are approximately monthly so you can read between the lines there :)
