### ISSUE TITLE
How to make Redis read from replica and write to master?

### ISSUE THREAD

**Issue by horseznguyen** [StackExchange/StackExchange.Redis#1918]
We currently have a service using redis with a couple of replica nodes. For the client we have a .Net-Core aplication using StackExchange.Redis. How can we implement read-only from replica , and write to master node in this case? Is it just a config change?

**Comment by mgravell** [comment]
If you server has a replica, just use `CommansFlags.PreferReplica` on any read commands where you would prefer to use a replica.

**Comment by horseznguyen** [comment]
Hi @mgravell 

Many thanks.
