### ISSUE TITLE
ProtocolFailure on ITransaction.Execute with multiple clients

### ISSUE THREAD

**Issue by MichaCo** [StackExchange/StackExchange.Redis#192]
Hi,
I'm not sure if this is a bug or I'm doing something wrong or if it is an issue with the server (I'm using *Redis-64.2.8.19* Nuget atm).

But when I'm trying to update values within a "transaction" by multiple clients concurrently, I'd expect that the `transaction.Excecute()` would just return false if there is a conflict.

In fact I get a lot of exceptions like this:

	StackExchange.Redis.ConnectionFailureType.ProtocolFailure
	Unexpected response to EXEC: MultiBulk: 0 items
	   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:Zeile 1838.
	   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:Zeile 81.
	   at StackExchange.Redis.RedisTransaction.Execute(CommandFlags flags) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisTransaction.cs:Zeile 51.
	   at CacheManager.Redis.RedisCacheHandle`1.<>c__DisplayClass13.<Update>b__15() in E:\$GIT\CacheManager\src\CacheManager.StackExchange.Redis\RedisCacheHandle.cs:Zeile 252.
	   at CacheManager.Redis.RetryHelper.Retry[T](Func`1 retryme, Int32 timeOut, Int32 retries) in E:\$GIT\CacheManager\src\CacheManager.StackExchange.Redis\RetryHelper.cs:Zeile 19.
   

I'm currently simply retrying the operation on error and it works just fine, still looks not really as it would work as intended to me.

I can reproduce the behavior with this console app. 
I'm opening a new connection for each "thread" because I want to mimic multiple clients... 

    class Program
    {
        static void Main(string[] args)
        {
            var key = "myHash";
            var field = "field";

            Action<ConnectionMultiplexer> action = (connection) =>
            {
                var db = connection.GetDatabase();
                for (int iteration = 0; iteration < 10; iteration++)
                {
                    var oldValue = db.HashGet(key, field);
                    var newValue = "Some Value" + iteration;
                    Update(db, key, field, oldValue, newValue);
                }

                Console.WriteLine("Action Done...");
            };

            Enumerable.Repeat(action, 10)
                .AsParallel()
                .WithDegreeOfParallelism(8)
                .ForAll(a => a(ConnectionMultiplexer.Connect("localhost:6379")));

            Console.WriteLine("We are done...");
            Console.Read();
        }

        private static bool Update(IDatabase database, string key, string field, string oldValue, string newValue)
        {
            try
            {
                var transaction = database.CreateTransaction();
                transaction.AddCondition(Condition.HashEqual(key, field, oldValue));
                transaction.HashSetAsync(key, field, newValue);
                return transaction.Execute();
            }
            catch(RedisConnectionException ex)
            {
                Console.WriteLine("failed with " + ex.Message);
                return false;
            }
        }
    }

What do you think? Is this even the intended way to use the `database.CreateTransaction` or should I use something else instead?

Thanks,
M

**Comment by mgravell** [comment]
I'll have to look at that example in detail to see what is happening. Note
that you don't need multiple multiplexers: the multiplexer and IDatabase
are fully thread-safe. It *looks* like your transaction is only local - not
shared between any other code as the question would suggest: am I missing
something?

**Comment by MichaCo** [comment]
I created multiple Multiplexer in that example to mimic multiple clients, imagine 2 console applications trying to change the same value. The transaction condition is set to make sure Client B doesn't change the value while Client A does update it.

**Comment by mgravell** [comment]
Gotcha - makes sense. Will look. Sounds intriguing!

**Comment by bencican** [comment]
Is this the same issue as below? 
https://github.com/StackExchange/StackExchange.Redis/issues/136

**Comment by NickCraver** [comment]
I believe @bencican is right and this is taken care of separately. @MichaCo are you able to repro now that #135 has been merged in?

**Comment by MichaCo** [comment]
@NickCraver Works fine, tested with 1.0.488
