### ISSUE TITLE
SET keys - Support for KEEPTTL flag 

### ISSUE THREAD

**Issue by ilia-cy** [StackExchange/StackExchange.Redis#1920]
As detailed in [Redis documentation regarding SET operations](https://redis.io/commands/set), version 6.0 added the support for `KEEPTTL` that will modify the value of a key without modifying its TTL.

Searching the code I do not see any reference to that flag or its usage.

Is it currently supported, and if so - how is it done?
If not, can I submit a feature request?

**Comment by NickCraver** [comment]
We do not support this at the moment, but thanks for the heads up! Indeed we'd have to add support for it, though I'm not sure what the shape of this would look like. Right now there's a `When` argument that controls the `EX`/NX`/`XX` portions, but this would have to be a new argument/overload and bit of doing. It's _possible_ it could be a `CommandFlag` but I'm not sure if we go that route. The grep here is `GetStringSetMessage` to see the existing options in play.

**Comment by mgravell** [comment]
The `CommandFlags` option would be a little awkward because the option is so specific to one command, and we can't restrict what options are advertised.

**Comment by NickCraver** [comment]
@mgravell Agreed, the one usage of this is odd IMO (`CommandFlags.NoScriptCache`) - so we'd need to decide what the new overloads look like.

**Comment by var1ap-WA** [comment]
@NickCraver @mgravell 
Hi guys! This feature is still in progress?

**Comment by ronaldpetty** [comment]
Just tried on 7rc2, not working (unless I misunderstand how its to be used).

**Comment by NickCraver** [comment]
I had a laptop on the side tonight, so popped up a PR for this (needs careful eyes) in #2029 - barring any issues there, should be in the next release :)

**Comment by ronaldpetty** [comment]
Dang, that was fast, I was so proud of my typo fix in the documentation!  Thanks @NickCraver will have a look.

**Comment by NickCraver** [comment]
Alrighty, this will be in the next release, via #2029.
