### ISSUE TITLE
Question: how to unit test with StreamEntry

### ISSUE THREAD

**Issue by WeihanLi** [StackExchange/StackExchange.Redis#1922]
Hi, I'm trying to write some unit test cases with the stream command, but since the constructor of `StreamEntry`  is internal, is there a recommended way to update the instance id and values.

And could we public the constructor for the `StreamEntry`

**Comment by mgravell** [comment]
I'm ok with making it public. For now: perhaps use reflection to call the non-public constructor?

**Comment by WeihanLi** [comment]
Thanks for your help @mgravell
