### ISSUE TITLE
Removing Windows Specifc performance counter dependency with cross platfrom EventCounters 

### ISSUE THREAD

**Issue by madhub** [StackExchange/StackExchange.Redis#1924]
Currently Redis client implementation depends PerformanceCounter  class to get [CPU time](https://github.com/StackExchange/StackExchange.Redis/blob/69e0f3235f0f69d7b4fe659e9b5f3d2991c4bee0/src/StackExchange.Redis/PerfCounterHelper.cs#L27), which brings additional Windows specific nuget package ` Microsoft.Win32.Registry,System.Configuration.ConfigurationManager` each of these inturn brings additional packages creating dependency hell , instead of this it is better to use cross platform [EventCounters](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/available-counters) .
As EventCounters is available in .NET 3.1 on wards , we can use it for .NET Core 3.1 target & older targets still use the PerformanceCounter  as is.

[Sample implementation of how to get cpu-usage is from Event Counter](https://blog.ladeak.net/posts/eventlisteners-cpu)

Reference Resource
* [Event Counter Docs](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/event-counters)
* [EventCounters Design ](https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/eventcounters.md)
* [.NET Core Counters internals](https://medium.com/criteo-engineering/net-core-counters-internals-how-to-integrate-counters-in-your-monitoring-pipeline-5354cd61b42e)

**Comment by mgravell** [comment]
Sounds good to me

**Comment by NickCraver** [comment]
I may be missing it here, but I don't think this counter exists in the EventCounters space. There's a subtle but important difference: we're using `_Total`, which is total CPU by *all* processes (the goal being to see if the box is pegged and unable to handle the load). The EventCounters space is _for this process_. For example the process could be at 2% CPU while some beast beside it is eating the other 98% and the box would be pegged...but we wouldn't get a useful metric there.

If there's a way to get global in a fewer dependency way I am also all for it, just not aware of that path at the moment :)

**Comment by madhub** [comment]
Understood. let me explore a bit more

**Comment by NickCraver** [comment]
Given this approach isn't viable in the library but the over platform TFMs are on the table, I'm going to tidy up this issue and we'll remain open to adding those TFMs if needed.

**Comment by NickCraver** [comment]
Heads up: we revisited this based on issue data and me crawling old issues again to see effectiveness. Not fixed in terms of how to fetch, just removed as not-worth-it tradeoff given even more downsides with vulnerabilities downstream. Version 2.6.80+ will no longer reference System.Diagnostics.PerformanceCounter.
