### ISSUE TITLE
Exception when using KeysAsync over a huge database

### ISSUE THREAD

**Issue by alexandrutatagit** [StackExchange/StackExchange.Redis#1926]
Hi!
I have an issue: I want to check all the keys for a specific condition, once per day. In the last days, on PROD, the size of the DB has increased to 50M. I am doing the following: 
await foreach (var item in server.KeysAsync(_db)){
...
}
I have updated the connection string to use a 10 min timeout:
allowAdmin=true,connectTimeout=600000,syncTimeout=600000,asyncTimeout=600000,keepAlive=600,$INFO=,$PING=,name=...

But still after 100 sec I get this error:

StackExchange.Redis.RedisConnectionException: InternalFailure (None, last-recv: 434) on XXX:6359/Interactive, Idle/Faulted, last: TIME, origin: ReadFromPipe, outstanding: 2, last-read: 18s ago, last-write: 42s ago, unanswered-write: 103s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 7 of 10 available, in: 0, in-pipe: 396870066, out-pipe: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.2.88.56325  ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'offset')    at System.ThrowHelper.ThrowArgumentOutOfRangeException_OffsetOutOfRange()    at StackExchange.Redis.BufferReader.SnapshotPosition() in /_/src/StackExchange.Redis/BufferReader.cs:line 117    at StackExchange.Redis.PhysicalConnection.ReadBulkString(BufferReader& reader, Boolean includeDetailInExceptions, ServerEndPoint server) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1770    at StackExchange.Redis.PhysicalConnection.TryParseResult(Arena`1 arena, ReadOnlySequence`1& buffer, BufferReader& reader, Boolean includeDetilInExceptions, ServerEndPoint server, Boolean allowInlineProtocol) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1841    at StackExchange.Redis.PhysicalConnection.ReadArray(Arena`1 arena, ReadOnlySequence`1& buffer, BufferReader& reader, Boolean includeDetailInExceptions, ServerEndPoint server) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1756    at StackExchange.Redis.PhysicalConnection.TryParseResult(Arena`1 arena, ReadOnlySequence`1& buffer, BufferReader& reader, Boolean includeDetilInExceptions, ServerEndPoint server, Boolean allowInlineProtocol) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1841    at StackExchange.Redis.PhysicalConnection.ProcessBuffer(ReadOnlySequence`1& buffer) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1660    at StackExchange.Redis.PhysicalConnection.ReadFromPipe() in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1607    --- End of inner exception stack trace ---    at StackExchange.Redis.CursorEnumerable`1.SingleBlockEnumerable.AwaitedGetNextPageAsync() in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 352    at StackExchange.Redis.CursorEnumerable`1.Enumerator.AwaitedNextAsync(Boolean isInitial) in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 272    at

Server version is 5+, client version is latest, I am using dotnet core 6.0
What can I do?

**Comment by NickCraver** [comment]
Can you elaborate on what you're trying to accomplish in this operation? The problem area is backlog for sure, as you see the 396,870,066 bytes waiting to be read - which means it's getting data faster than your check is able to process it. If I understand correctly, your general setup here is "copy the entire database and check it", that's going to be really expensive with anything of size, so know what you're doing may help give some recommendations.

You _can_ do this with the client, given a lot more horsepower at the processing end (it's getting data fast enough, but not offloading it), but I still wouldn't recommend the approach if we can do it more efficiently - so more info may help advise there.

Now, all that being said: there is one thing I'm super curious about that we're doing to try with .NET 6+. Can you try tweaking your connection options and see it it makes any behavior difference at all? I'd like to see if using the base thread pool helps you at all with this massive load. You set it by adjusting the `SocketManager` before connecting, like this:
```cs
var config = ConfigurationOptions.Parse("localhost:6379");
config.SocketManager = SocketManager.ThreadPool;
var conn = ConnectionMultiplexer.Connect(config);
```

(any of the Connect/ConnectAsync/etc. methods will take a config options). Also available in short form since you're on the latest:
```cs
var conn = ConnectionMultiplexer.Connect("localhost:6379", options => options.SocketManager = SocketManager.ThreadPool);
```

**Comment by mgravell** [comment]
Interesting. In particular, this:

> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'offset') at System.ThrowHelper.ThrowArgumentOutOfRangeException_OffsetOutOfRange() at StackExchange.Redis.BufferReader.SnapshotPosition() in //src/StackExchange.Redis/BufferReader.cs:line 117 at

Now, this suggests to me one of two things:

- we're getting non-numeric tokens when we expect numeric
- we're imposing an incorrect bit size on an integer

We've seen (and resolved) something like the first when dealing with some cluster tools, so I wonder if this is the second. What I'll do is: add some logging so we can see what we're dealing with when this happens, because honestly I'm confused, and that's going to be the quickest way to understand the problem. I can probably get a build on myget later today - that work?

**Comment by alexandrutatagit** [comment]
Thanks for the fast answers! To be honest, I only partially understood what you guys said - but I will try the SocketManager option.

What I want to achieve is to do a daily cleanup of orphan entries in Redis: for all of those, do some external processing (update a status in an external system) and then delete them.
Before setting the timeout to 10 min, I would get a timeout error:

StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=1390021KiB, 60988ms elapsed, timeout is 60000ms), command=KEYS, next: KEYS, inst: 0, qu: 0, qs: 1, aw: False, rs: TryParseResult, ws: Idle, in: 0, in-pipe: 846714243, out-pipe: 0, serverEndpoint: XXX:6359, mc: 1/1/0, mgr: 9 of 10 available, clientName: MG, IOCP: (Busy=0,Free=1000,Min=40,Max=1000), WORKER: (Busy=1,Free=32766,Min=40,Max=32767), v: 2.2.88.56325 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)    at StackExchange.Redis.CursorEnumerable`1.SingleBlockEnumerable.AwaitedGetNextPageAsync() in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 352    at StackExchange.Redis.CursorEnumerable`1.Enumerator.AwaitedNextAsync(Boolean isInitial) in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 272

**Comment by alexandrutatagit** [comment]
What is weird, I get also this drops in the master redis instance

**Comment by alexandrutatagit** [comment]
Did I understand correctly, @mgravell , you want me to test with a improved logging version of the redis library?

**Comment by alexandrutatagit** [comment]
@NickCraver , did the way you said, but I still get errors:

var config = ConfigurationOptions.Parse(_redisSettings.DeliveryReportsCacheConnectionString);
config.SocketManager = SocketManager.ThreadPool;
_connectionRedisRepository = ConnectionMultiplexer.Connect(config);
//get all endpoints defined for this redis connection.
_endpoints = _connectionRedisRepository.GetEndPoints();
...
then for the server I am using the first connected && !replica server
server = _connectionRedisRepository.GetServer(_endpoint);
server.KeysAsync(..)

|StackExchange.Redis.RedisConnectionException: InternalFailure (None, last-recv: 377) on blk-node26:6359/Interactive, Idle/Faulted, last: TIME, origin: ReadFromPipe, outstanding: 1, last-read: 14s ago, last-write: 94s ago, unanswered-write: 94s ago, keep-alive: 600s, state: ConnectedEstablished, mgr: , in: 0, in-pipe: 960623299, out-pipe: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.2.88.56325  ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'offset')    at System.ThrowHelper.ThrowArgumentOutOfRangeException_OffsetOutOfRange()    at StackExchange.Redis.BufferReader.SnapshotPosition() in /_/src/StackExchange.Redis/BufferReader.cs:line 117    at StackExchange.Redis.PhysicalConnection.ReadBulkString(BufferReader& reader, Boolean includeDetailInExceptions, ServerEndPoint server) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1770    at StackExchange.Redis.PhysicalConnection.TryParseResult(Arena`1 arena, ReadOnlySequence`1& buffer, BufferReader& reader, Boolean includeDetilInExceptions, ServerEndPoint server, Boolean allowInlineProtocol) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1841    at StackExchange.Redis.PhysicalConnection.ReadArray(Arena`1 arena, ReadOnlySequence`1& buffer, BufferReader& reader, Boolean includeDetailInExceptions, ServerEndPoint server) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1756    at StackExchange.Redis.PhysicalConnection.TryParseResult(Arena`1 arena, ReadOnlySequence`1& buffer, BufferReader& reader, Boolean includeDetilInExceptions, ServerEndPoint server, Boolean allowInlineProtocol) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1841    at StackExchange.Redis.PhysicalConnection.ProcessBuffer(ReadOnlySequence`1& buffer) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1660    at StackExchange.Redis.PhysicalConnection.ReadFromPipe() in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1607    --- End of inner exception stack trace ---    at StackExchange.Redis.CursorEnumerable`1.SingleBlockEnumerable.AwaitedGetNextPageAsync() in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 352    at StackExchange.Redis.CursorEnumerable`1.Enumerator.AwaitedNextAsync(Boolean isInitial) in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 272    at SMPP.DeliveryCleanup.Redis.ExecuteInBatches[T](IAsyncEnumerable`1 source, Int32 batchSize, Func`2 action) in /src/SMPP/SMPP.DeliveryCleanup/Redis.cs:line 148    at SMPP.DeliveryCleanup.Redis.ExecuteInBatches[T](IAsyncEnumerable`1 source, Int32 batchSize, Func`2 action) in /src/SMPP/SMPP.DeliveryCleanup/Redis.cs:line 148    at SMPP.DeliveryCleanup.Redis.StartToListenForKeysAsync() in /src/SMPP/SMPP.DeliveryCleanup/Redis.cs:line 121    at SMPP.DeliveryCleanup.Redis.Start() in /src/SMPP/SMPP.DeliveryCleanup/Redis.cs:line 94    at SMPP.DeliveryCleanup.Program.Main(String[] args) in /src/SMPP/SMPP.DeliveryCleanup/Program.cs:line 60

**Comment by mgravell** [comment]
You can try, but I don't think the `SocketManager` option will help; this *looks* like something really really weird - like a protocol/data error (for example, a parse failure, or a desync, either of which would be the library's fault, i.e. "my bad"). I also don't see any way it can relate specifically to the db size or basically anything! All I can say right now is "huh, that's odd", but; ^^^ logging added; let's see if we can figure out what on earth is happening!

**Comment by alexandrutatagit** [comment]
Thank you, I will then wait for your feedback :)

**Comment by mgravell** [comment]
well, I don't have a repro, so: what we'll need to do is get you pointing to the myget feed, and try the inbound library;

For now, the myget feed is https://www.myget.org/F/stackoverflow/api/v3/index.json - there should be a new version on myget in a few minutes, something **above** (i.e. not this one) 2.2.92

Are you familiar with adding custom nuget feeds? You can do this in a nuget.config file, or in Visual Studio by:

- manage nuget packages (for a project or solution)
- in the top right, next to "Package source", click the cog
- in the popup, click the `+` button
- add a new package source with any name you like, and the URL from above, exit with "OK" etc
- make sure you have the new package source selected
- look for a newer version of the dll

**Comment by mgravell** [comment]
confirmed; 2.2.93 is now on myget

**Comment by mgravell** [comment]
(random question for @NickCraver  - do you reckon we should create a new myget etc setup?)

**Comment by alexandrutatagit** [comment]
> confirmed; 2.2.93 is now on myget

Building and deploying, I will tell you soon, thank you!

**Comment by mgravell** [comment]
It should still fail in a similar way, but bow there should be more details in the snapshotposition line in the stacktrace, telling me what kind of delta position it was trying to compute.

**Comment by mgravell** [comment]
Oh, unrelated (hopefully) - curiosity: what is the server at the end of this? Is it actually redis? If so, what version? Or: is it something redis-like? Basically, this is such a weird and unusual failure that I want to understand whether it is a potential issue for all consumers, or whether it is unique to some exotic setup.

**Comment by alexandrutatagit** [comment]
This is the error - looks the same, no? The redis server is inside docker:
# Server
redis_version:5.0.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:825c96d6c798641
redis_mode:standalone
os:Linux 3.10.0-957.12.1.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0


StackExchange.Redis.RedisConnectionException: InternalFailure (None, last-recv: 1854) on XXX:6359/Interactive, Idle/Faulted, last: ECHO, origin: ReadFromPipe, outstanding: 1, last-read: 15s ago, last-write: 88s ago, unanswered-write: 88s ago, keep-alive: 600s, state: ConnectedEstablished, mgr: , in: 0, in-pipe: 1030547262, out-pipe: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.2.93.47464  ---> System.ArgumentOutOfRangeException: Error calculating SnapshotPosition: -2147483619 of 2288453212, 2147483634+-4294967253  ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'offset')    at System.ThrowHelper.ThrowArgumentOutOfRangeException_OffsetOutOfRange()    at StackExchange.Redis.BufferReader.SnapshotPosition() in /_/src/StackExchange.Redis/BufferReader.cs:line 125    --- End of inner exception stack trace ---    at StackExchange.Redis.BufferReader.ThrowSnapshotFailure(Int64 delta, Exception innerException) in /_/src/StackExchange.Redis/BufferReader.cs:line 141    at StackExchange.Redis.BufferReader.SnapshotPosition() in /_/src/StackExchange.Redis/BufferReader.cs:line 125    at StackExchange.Redis.PhysicalConnection.ReadBulkString(BufferReader& reader, Boolean includeDetailInExceptions, ServerEndPoint server) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1770    at StackExchange.Redis.PhysicalConnection.TryParseResult(Arena`1 arena, ReadOnlySequence`1& buffer, BufferReader& reader, Boolean includeDetilInExceptions, ServerEndPoint server, Boolean allowInlineProtocol) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1841    at StackExchange.Redis.PhysicalConnection.ReadArray(Arena`1 arena, ReadOnlySequence`1& buffer, BufferReader& reader, Boolean includeDetailInExceptions, ServerEndPoint server) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1756    at StackExchange.Redis.PhysicalConnection.TryParseResult(Arena`1 arena, ReadOnlySequence`1& buffer, BufferReader& reader, Boolean includeDetilInExceptions, ServerEndPoint server, Boolean allowInlineProtocol) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1841    at StackExchange.Redis.PhysicalConnection.ProcessBuffer(ReadOnlySequence`1& buffer) in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1660    at StackExchange.Redis.PhysicalConnection.ReadFromPipe() in /_/src/StackExchange.Redis/PhysicalConnection.cs:line 1607    --- End of inner exception stack trace ---    at StackExchange.Redis.CursorEnumerable`1.SingleBlockEnumerable.AwaitedGetNextPageAsync() in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 352    at StackExchange.Redis.CursorEnumerable`1.Enumerator.AwaitedNextAsync(Boolean isInitial) in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 272

**Comment by NickCraver** [comment]
> (random question for @NickCraver - do you reckon we should create a new myget etc setup?)

Yep, I can take that one - IIRC I already prepped this but never cut over.

On the thread pool: I was mostly interested if we are over-running a 1GB buffer somewhere in the stack and if delegating to the thread pool would keep up better...looks like not that much difference since the handoff is cheap-ish and it's just a torrent of data. Very curious what's happening with the buffer - cheers for testing the thread pool settings! (for context: we're considering making this a default in 2.5x)

**Comment by alexandrutatagit** [comment]
Regarding the 1GB buffer, before increasing the timeout over 1 min, I had this error, which mentions a 1GB limit:
Timeout awaiting response (outbound=0KiB, inbound=1390021KiB, 60988ms elapsed, timeout is 60000ms), command=KEYS, next: KEYS, inst: 0, qu: 0, qs: 1, aw: False, rs: TryParseResult, ws: Idle, in: 0, in-pipe: 846714243, out-pipe: 0, serverEndpoint: blk-node27:6359, mc: 1/1/0, mgr: 9 of 10 available, clientName: MG, IOCP: (Busy=0,Free=1000,Min=40,Max=1000), WORKER: (Busy=1,Free=32766,Min=40,Max=32767), v: 2.2.88.56325 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)    at StackExchange.Redis.CursorEnumerable`1.SingleBlockEnumerable.AwaitedGetNextPageAsync() in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 352    at StackExchange.Redis.CursorEnumerable`1.Enumerator.AwaitedNextAsync(Boolean isInitial) in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 272

**Comment by NickCraver** [comment]
The thing is I wouldn't expect the buffer or inbound to get anywhere near this big with keys and a cursor, unless the key values are _huge_ or you're using a massive page size. Can you share the calling code here please?

**Comment by mgravell** [comment]
Second hypothesis: we're somehow falling back into `KEYS` mode rather than `SCAN` mode. That's pretty much the only way I can imagine that we'd have anything like this size of data! Redis 5 (from server info) should definitely be using `SCAN`. But wow, that's a huge buffer! I almost want to congratulate you!

**Comment by mgravell** [comment]
Oh, and there it is in the output:

> command=KEYS

So. What we need to figure out is *why* is it using `KEYS`! Suggestion: on the connection string and ConfigurationOptions API,  there is an option to specify the default redis version. Maybe make that 5?

Note: this should normally auto-negotiate without you doing anything, unless certain metadata commands are disabled. Anything like that going on here?

**Comment by mgravell** [comment]
Things I would recommend:

1. find out what we think the topology is:

``` c#
foreach (var ep in muxer.GetEndPoints())
{
    var server = muxer.GetServer(ep);
    var features = server.Features;
    Console.WriteLine($"{server.EndPoint}, {server.ServerType}, {nameof(server.IsReplica)}={server.IsReplica}; v{features.Version}; {nameof(features.Scan)}={features.Scan}");
}
```

This ^^^ should should the servers the multiplexer is aware of, along with their redis version / features.

2. Find out what happened during connect:

``` c#
var log = new StringWriter();
var muxer = await ConnectionMultiplexer.ConnectAsync(config, log);
var logText = log.ToString();
```

This ^^^ uses the optional `log` parameter on `Connect[Async]` to capture a lot more info about the handshakes and negotiations between servers.

Finally,

3. If we're somehow unable to auto-detect the version: tell it in advance:

If you're using a connection string:

``` c#
var config = "someserver,version=5.0";
```

Or if you're using the `ConfigurationOptions` API:

``` c#
var config = new ConfigurationOptions
{
    EndPoints = { "someserver" },
    DefaultVersion = new Version(5, 0),
};
```

(along with whatever else you're configuring)

These sets the default version as v5, as opposed to v2 we assume by default (or v3 for azure endpoints). The default version is only used when we fail to negotiate a version.

**Comment by alexandrutatagit** [comment]
> ```cs
> var server = muxer.GetServer(ep);
>     var features = server.Features;
>     Console.WriteLine($"{server.EndPoint}, {server.ServerType}, {nameof(server.IsReplica)}={server.IsReplica}; v{features.Version}; {nameof(features.Scan)}={features.Scan}");
> ```

keys are at most 20-25 bytes long. Values can be 1-2kB. What part of the code you want me to share please? - Meanwhile I will do the changes required by @mgravell  - by the way, I was suspecting the same KEYS thing - not using SCAN :)

**Comment by mgravell** [comment]
I *suspect* the "calling code" here is less relevant now that we've determined that it is `KEYS` to blame; it would be relevant if, say, you'd passed a page-size of 1 billion! But I don't think you have. What *might* be more useful, perhaps, is anything related to config/connect - in particular, if perhaps you're doing something funky with "command maps" or other exotic features. I am genuinely curious why it has decided to use `KEYS` here, and the options I can think of *basically* come down to:

1. it couldn't detect the server version, for some reason
2. you had explicitly disabled `SCAN`

The only way of achieving "2" is via a "command map" - for example, the connection-string `someserver,$SCAN=`  disables `SCAN`, but: this seems incredibly unlikely! So that leaves "1". In part, I'm curious because if we're doing something catastrophically silly here, it could be impact other people adversely.

**Comment by alexandrutatagit** [comment]
> Things I would recommend:
> 
> 1. Find out what we think the topology is:
> 
> ```cs
> foreach (var ep in muxer.GetEndPoints())
> {
>     var server = muxer.GetServer(ep);
>     var features = server.Features;
>     Console.WriteLine($"{server.EndPoint}, {server.ServerType}, {nameof(server.IsReplica)}={server.IsReplica}; v{features.Version}; {nameof(features.Scan)}={features.Scan}");
> }
> ```
> 
> This ^^^ should should the servers the multiplexer is aware of, along with their redis version / features.
> 
> 2. Find out what happened during connect:
> 
> ```cs
> var log = new StringWriter();
> var muxer = await ConnectionMultiplexer.ConnectAsync(config, log);
> var logText = log.ToString();
> ```
> 
> This ^^^ uses the optional `log` parameter on `Connect[Async]` to capture a lot more info about the handshakes and negotiations between servers.
> 
> Finally,
> 
> 3. If we're somehow unable to auto-detect the version: tell it in advance:
> 
> If you're using a connection string:
> 
> ```cs
> var config = "someserver,version=5.0";
> ```
> 
> Or if you're using the `ConfigurationOptions` API:
> 
> ```cs
> var config = new ConfigurationOptions
> {
>     EndPoints = { "someserver" },
>     DefaultVersion = new Version(5, 0),
> };
> ```
> 
> (along with whatever else you're configuring)
> 
> These are equivalent, and set the default redis version as v5, as opposed to v2 we assume by default (or v3 for azure endpoints). The default version is only used when we fail to detect the redis version.

The connection multiplexer returns:

Multiplex connection: ------->   Connecting (sync) on .NET 6.0.0-rtm.21522.10 18:23:10.8181: blk-node26:6359,blk-node27:6359,name=MG,keepAlive=600,syncTimeout=600000,asyncTimeout=600000,allowAdmin=True,connectTimeout=600000,$INFO=,$PING=  18:23:10.8263: blk-node26:6359/Interactive: Connecting... 18:23:10.8412: blk-node26:6359: BeginConnectAsync 18:23:10.8471: blk-node27:6359/Interactive: Connecting... 18:23:10.8473: blk-node27:6359: BeginConnectAsync 18:23:10.8477: 2 unique nodes specified 18:23:10.8485: blk-node26:6359: OnConnectedAsync init (State=Connecting) 18:23:10.8486: blk-node27:6359: OnConnectedAsync init (State=Connecting) 18:23:10.8487: Allowing 2 endpoint(s) 00:10:00 to respond... 18:23:10.8507: blk-node27:6359/Interactive: Connected  18:23:10.8520: blk-node26:6359/Interactive: Connected  18:23:10.8542: blk-node27:6359: Server handshake 18:23:10.8542: blk-node26:6359: Server handshake 18:23:10.8557: Awaiting 2 available task completion(s) for 600000ms, IOCP: (Busy=0,Free=1000,Min=40,Max=1000), WORKER: (Busy=13,Free=32754,Min=40,Max=32767) 18:23:10.8689: blk-node26:6359: Setting client name: MG 18:23:10.8689: blk-node27:6359: Setting client name: MG 18:23:10.8943: blk-node26:6359: Auto-configuring... 18:23:10.8943: blk-node27:6359: Auto-configuring... 18:23:10.8974: blk-node26:6359: Sending critical tracer (handshake): ECHO 18:23:10.8974: blk-node27:6359: Sending critical tracer (handshake): ECHO 18:23:10.8976: blk-node26:6359/Interactive: Writing: ECHO 18:23:10.8976: blk-node27:6359/Interactive: Writing: ECHO 18:23:10.8976: blk-node27:6359: Flushing outbound buffer 18:23:10.8976: blk-node27:6359: OnEstablishingAsync complete 18:23:10.8976: blk-node26:6359: Flushing outbound buffer 18:23:10.8976: blk-node27:6359: Starting read 18:23:10.8976: blk-node26:6359: OnEstablishingAsync complete 18:23:10.8977: blk-node26:6359: Starting read 18:23:10.9470: blk-node27:6359: Auto-configured (CONFIG) read-only replica: true 18:23:10.9471: blk-node26:6359: Auto-configured (CONFIG) read-only replica: true 18:23:10.9485: blk-node27:6359: Auto-configured (CONFIG) databases: 16 18:23:10.9485: blk-node26:6359: Auto-configured (CONFIG) databases: 16 18:23:10.9564: blk-node27:6359: Auto-configured role: replica 18:23:10.9569: Response from blk-node27:6359/Interactive / ECHO: BulkString: 16 bytes 18:23:10.9571: Response from blk-node26:6359/Interactive / ECHO: BulkString: 16 bytes 18:23:10.9587: blk-node27:6359: OnConnectedAsync completed (From command: ECHO) 18:23:10.9587: blk-node26:6359: OnConnectedAsync completed (From command: ECHO) 18:23:10.9599: All 2 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=40,Max=1000), WORKER: (Busy=2,Free=32765,Min=40,Max=32767) 18:23:10.9605: blk-node26:6359: Endpoint is ConnectedEstablished 18:23:10.9606: blk-node27:6359: Endpoint is ConnectedEstablished 18:23:10.9606: Election: Gathering tie-breakers... 18:23:10.9606: blk-node26:6359: Requesting tie-break (Key="__Booksleeve_TieBreak")... 18:23:10.9627: blk-node26:6359/Interactive: Writing: GET __Booksleeve_TieBreak 18:23:10.9631: blk-node27:6359: Requesting tie-break (Key="__Booksleeve_TieBreak")... 18:23:10.9631: blk-node27:6359/Interactive: Writing: GET __Booksleeve_TieBreak 18:23:10.9632: blk-node26:6359: Returned with success as Standalone primary (Source: From command: ECHO) 18:23:10.9632: blk-node27:6359: Returned with success as Standalone replica (Source: From command: ECHO) 18:23:10.9638: Response from blk-node26:6359/Interactive / GET __Booksleeve_TieBreak: (null) 18:23:10.9638: Response from blk-node27:6359/Interactive / GET __Booksleeve_TieBreak: (null) 18:23:10.9752: Waiting for tiebreakers... 18:23:10.9752: All tasks are already complete 18:23:10.9752: Election: blk-node26:6359 had no tiebreaker set 18:23:10.9752: Election: blk-node27:6359 had no tiebreaker set 18:23:10.9752: Election: Single master detected: blk-node26:6359 18:23:10.9752: blk-node26:6359: Clearing as RedundantMaster 18:23:10.9770: blk-node26:6359: Standalone v2.0.0, master; 16 databases; keep-alive: 00:10:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active 18:23:10.9786: blk-node26:6359: int ops=8, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1 18:23:10.9853: blk-node26:6359: Circular op-count snapshot; int: 0+8=8 (0.80 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s) 18:23:10.9853: blk-node27:6359: Standalone v2.0.0, replica; 16 databases; keep-alive: 00:10:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active 18:23:10.9853: blk-node27:6359: int ops=8, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1 18:23:10.9853: blk-node27:6359: Circular op-count snapshot; int: 0+8=8 (0.80 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s) 18:23:10.9854: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago 18:23:10.9856: Starting heartbeat... |

And the server created from the endpoint:

------------->Unspecified/blk-node26:6359, Standalone, IsReplica=False; v2.0.0; Scan=False|

**Which is weird... just version 2.0.0?**

**Comment by alexandrutatagit** [comment]
So this is it... it's disabled it seems... The CS is defined like this "ConnectionString": "blk-node26:6359,blk-node27:6359,allowAdmin=true,syncTimeout=600000,$INFO=,$PING=,name=MG

**Comment by mgravell** [comment]
Bingo. By not having access to `INFO`, we can't auto-detect the server version; so it plays safe and assumes V2. Now: if you have good reasons to disable `INFO`, that's fine - but: please also set the default server version to something suitable. It doesn't need to be exact - "5" would be fine, I suspect. I gave ways of doing this via either the string or object API earlier.

Please try setting the default server version in the connect, and let us know if that resolves everything. I suspect it will.

Also: yes, the integer overflow is a bug, and I'll fix it! But I'd also rather get you using `SCAN` :)

**Comment by alexandrutatagit** [comment]
I put v5 in config, and now logs are: INFO|------------->Unspecified/blk-node26:6359, Standalone, IsReplica=False; v5.0; Scan=True|
:)
And the code works SMOOTH.
Thank you so much guys, I really appreciate, you are very nice!!

**Comment by alexandrutatagit** [comment]
We put $INFO= because we had a lot of traffic, and wanted to reduce a little the packets. Should I enable it back? Or leave the v5 in the CS?
In the 2nd case, if we upgrade the redis server to 6, should we also update the CS to v6? or is it backwards compatible?

**Comment by mgravell** [comment]
Normally, we only issue INFO very rarely - during connect. You shouldn't be
connecting very often, so...

Also: how many bytes and hours has this cost you today :)

**Comment by alexandrutatagit** [comment]
Yes, so better to remove it.
Thanks again guys for the effort and instant availability!
