### ISSUE TITLE
"No connection is available to service this operation" without interrupted connection

### ISSUE THREAD

**Issue by nmehlei** [StackExchange/StackExchange.Redis#193]
In some cases, it seems like to be possible that a RedisConnectionException with "No connection is available to service this operation" is thrown without either ErrorMessage or ConnectionFailed events being invoked. 

Is this expected behavior? Seems very odd..

**Comment by Xhanti** [comment]
We've seen the same on our production application +1

**Comment by sobenz** [comment]
I can replicate this scenario if multiple threads attempt to start to access the redis server prior to an initial successful connection. For example if multiple threads execute TaskFunc the scenario will fail. If I execute TaskFunc once sucessfully, then all subsequent executions will succeed.
        
        private static ConnectionMultiplexer _con;
        private static void TaskFunc()
        {
            InitializeConnection();
            var db = _con.GetDatabase();
            try
            {
                db.StringSet(Guid.NewGuid().ToString(), Guid.NewGuid().ToString(), TimeSpan.FromSeconds(50), When.NotExists, CommandFlags.HighPriority);
            }
            catch(Exception e)
            {
                Console.WriteLine("Fail:{0}", e);
            }
        }

        public static void InitializeConnection()
        {
            if (_con == null)
            {
                lock (_locker)
                {
                    if (_con == null)
                    {
                        var connectionString = "localhost,password=,ssl=false,abortConnect=false,syncTimeout=5000,connectTimeout=5000,connectRetry=3,allowAdmin=true";
                        _con = ConnectionMultiplexer.Connect(connectionString);
                    }
                }
            }
        }

**Comment by nmehlei** [comment]
@mgravell Could you chime in? Is this expected behavior? If not, how can we help diagnosing and fixing this?

**Comment by gramanero** [comment]
+1 - we are dealing with this issue as well. This recently started to happen for us when we introduced a second Redis instance in a master/slave configuration. Not sure if it is related in anyway, but prior to that we had a single Redis instance and never saw this error.

**Comment by NickCraver** [comment]
A series of these bugs was fixed in later releases. The specific issue here shouldn't occur anymore, and in others where it does you'll get a much more informative message. If anyone's still hitting this, please upgrade to 1.2.6 or later :)
