### ISSUE TITLE
how to copy database to server another ?

### ISSUE THREAD

**Issue by TranNghia1998** [StackExchange/StackExchange.Redis#1934]
I'm doing copy database to server another with bulk records. Below code, It working but very slow
![image](https://user-images.githubusercontent.com/25928638/147336710-b415a445-6b59-4a7c-bad3-04454d8aa9a5.png)

I used try copy on GUI of Redis. It run very fast. Have way speed up ?

**Comment by mgravell** [comment]
I would presume a combination of batching, concurrency, and pipelining. These, however, are not trivial to explain! You can probably make a passable first stab simply by using Parallel.ForEach on the result of Keys(...), though.

**Comment by NickCraver** [comment]
I'm not sure which GUI is in play here, but I'd guess they're using the MIGRATE API probably? (this assumes server A can see server B) It has bulk modes added in later versions - not something I've used much but we do support it and I've had fun fixing the tests up around it :) Details: https://redis.io/commands/migrate

**Comment by NickCraver** [comment]
Closing this out as answered above - migrate is what you want for max speed here, regardless of the client :)
