### ISSUE TITLE
ISubscriber interface needs Unsubscribe method which takes Action<string, string> instead of Action<RedisChannel, RedisValue>

### ISSUE THREAD

**Issue by efaruk** [StackExchange/StackExchange.Redis#195]
Hi,

   RedisChannel implicitly accept string same as RedisValue so, ISubscriber.Unsubscribe can take Action&lt;string, string&gt; as second argument.

Regards...

**Comment by mgravell** [comment]
Why unsubscribe but not subscribe? Also: implicit conversions do not make signatures equivalent - and that is prominently visible when talking about delegates. You can of course *wrap* delegates, but then you get into equivalence issues which can be impossible to resolve.

So: what problem would this address? What is the expected usage?

**Comment by efaruk** [comment]
I'm trying to supply a generic messaging interface for our development team. We have implemented, UDP Multicast and TCP Broadcast, also good to have Redis Pub/Sub and you are the best person to ask ;)

How can I wrap this one out?

public void Unsubscribe(string channel, Action&lt;string, string&gt; handler) {
    var redisChannel = (RedisChannel)channel;
    var redisValue = (RedisValue)&quot;&quot;;
    var redisAction = new Action&lt;RedisChannel, RedisValue&gt;(channel, redisValue);
    _sub.Unsubscribe(redisChannel, redisAction);
}

**Comment by mgravell** [comment]
I'm confused why the focus here is unsubscribe. Subscribe has exactly the
same semantics: you can't subscribe with this type of action: to how would
you unsubscribe? There are a few ways to do what you want, but because of
delegate equality you need to be a little careful. If you can indicate how
you want to *subscribe*, I can probably indicate an appropriate way to
implement this. However, it is unlikely that the API will be changed to
accept Action<string,string>, because at the redis level: *that isn't the
API*. I can show you how to tweak around that, though.

**Comment by efaruk** [comment]
Maybe you are missing but I told that; We need both Subscribe(string channel, Action&lt;string, string&gt;, ....) and Unsubscribe(string channel, Action&lt;string, string&gt; ...). Yes I probably know about delegation equality issues, (symbol reference, clr level issues). If you don't have plans to implement this for benefit of society, I will be grateful, if you show me a better way (Other then managing handlers registrations in the wrapper, handlers += and handlers -=).

**Comment by mgravell** [comment]
My advice would be to wrap it in your calling model, via an object that has a method like:

    public void OnReceived(
       RedisChannel channel, RedisValue value)
    {
        OnReceived((string)channel, (string)value);
    }
    protected abstract void OnReceived(
        string channel, string value);

That way you can subscribe and unsubscribe with the first method without any equality issues.

**Comment by efaruk** [comment]
Thank you very much for your advice, I think we are talking about almost on same way ;)

Regards, best wishes...

**Comment by mgravell** [comment]
Of course, if you don't need to unsubscribe, you can just do:

    Subscribe(..., (x,y)=>
        ProcessMessage((string)x,(string)y);

Most people don't actually need to unsubscribe, so this works surprisingly
well.

**Comment by efaruk** [comment]
Thank you very much Marc...

Regards...
