### ISSUE TITLE
Occasional timeout error from redis

### ISSUE THREAD

**Issue by zqlovejyc** [StackExchange/StackExchange.Redis#1962]
Hi,

I'm using StackExchange.Redis, Version=2.2.88 on my aspnet core app and I get errors like the following :
```json
{
"code": 500,
"errorCode": -1,
"hasPage": false,
"message": "Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5321ms elapsed, timeout is 5000ms), command=GET, next: GET Baize:WorkFlowCenter:WFProcessWithId:178542997909147648, inst: 0, qu: 0, qs: 2, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: 10.191.19.57:8379, mc: 1/1/0, mgr: 10 of 10 available, clientName: bc1p-bz-ap01, IOCP: (Busy=0,Free=1000,Min=32,Max=1000), WORKER: (Busy=5,Free=32762,Min=32,Max=32767), v: 2.2.88.56325 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)",
"elapsedMilliseconds": 0,
"result": null
}
```
Can someone please help me understand how to fix it ?

**Comment by NickCraver** [comment]
Your threadpool doesn't seem too busy and there's not much in queue, so I'd first look at the server. On your Redis instance you can [use `SLOWLOG`](https://redis.io/commands/slowlog-get) to see if anything on that side is stalling out, it keeps a record of commands that took a while on the server side  ("a while" being configurable - defaulting to 10ms+). If you want to use our client in LinqPad or something, you're looking for `SlowLogGet()` on `IServer`.

**Comment by zqlovejyc** [comment]
> Your threadpool doesn't seem too busy and there's not much in queue, so I'd first look at the server. On your Redis instance you can [use `SLOWLOG`](https://redis.io/commands/slowlog-get) to see if anything on that side is stalling out, it keeps a record of commands that took a while on the server side ("a while" being configurable - defaulting to 10ms+). If you want to use our client in LinqPad or something, you're looking for `SlowLogGet()` on `IServer`.

I tried the `slowlog` command, and the results are as follows:
```json
xxx:0>SLOWLOG GET 10
1)  1) "6991"
    2) "1643051504"
    3) "10723"
    4) 1) "GET"
       2) "Baize:MaterialCenter:252093681673318400"

    5) "10.32.44.77:51662"
    6) "ks8p-dshbz-ap02"

2)  1) "6990"
    2) "1643051471"
    3) "12925"
    4) 1) "SETEX"
       2) "Baize:MaterialCenter:PartMasters:252093681673318400"
       3) "1242"
       4) "{"pn":"122-000000-59BH","modelId":"253100269339033600","partType":"PCBA","eecode":null,"desc1":"PCBA,LS_ESP32-WROOM-32D,MP2800,V... (682 more bytes)"

    5) "10.32.44.77:51662"
    6) "ks8p-dshbz-ap02"

3)  1) "6989"
    2) "1643051266"
    3) "21587"
    4) 1) "GET"
       2) "Baize:WorkFlowCenter:WFRouteProcessHold:253102712697270272__246585619990589440"

    5) "10.32.44.76:41342"
    6) "ks8p-dshbz-ap01"
```

**Comment by NickCraver** [comment]
Hmm, a simple GET or SET command taking 10ms+ is odd - can you view CPU/network traffic on the Redis side for when your client was timing out?

**Comment by zqlovejyc** [comment]
> Hmm, a simple GET or SET command taking 10ms+ is odd - can you view CPU/network traffic on the Redis side for when your client was timing out?

The monitoring software we use is `ZABBIX`

redis server:

![企业微信截图_16430737824942](https://user-images.githubusercontent.com/19462884/150893704-e8022d5c-b288-4b66-8081-d862b4dbf094.png)
![企业微信截图_16430738169954](https://user-images.githubusercontent.com/19462884/150893718-f4292493-2ffc-4a71-a8f0-ad80bdcd75f4.png)
![企业微信截图_16430738394212](https://user-images.githubusercontent.com/19462884/150893726-3d407f53-df90-427a-997b-bb44a7b51f33.png)

redis client:
![企业微信截图_164307392234](https://user-images.githubusercontent.com/19462884/150893758-a2616314-71ed-470f-b554-821e624f9fdb.png)
![企业微信截图_16430739382520](https://user-images.githubusercontent.com/19462884/150893773-238e1be0-ea02-48b5-9008-570d4826a4c1.png)
![企业微信截图_16430739861919](https://user-images.githubusercontent.com/19462884/150893788-0424dcc1-eaa7-4e8c-adc3-6e63d6962efc.png)

**Comment by zqlovejyc** [comment]
Through the comparison test between the local machine and the server redis, it is found that the timeout reason is basically locked in the network
