### ISSUE TITLE
Running a command on an already executed batch causes a deadlock

### ISSUE THREAD

**Issue by OronDF343** [StackExchange/StackExchange.Redis#1965]
Hi,

I have encountered a deadlock that occurs when running a command on an already completed batch. I know that this scenario is caused by bad code, but it is difficult to debug due to the deadlock.

I suggest that an `InvalidOperationException` be thrown in this scenario instead of a silent deadlock.

Example of how this can happen accidentally:
```
        [Fact]
        public async Task Batch_Deadlock()
        {
            var connection = await ConnectionMultiplexer.ConnectAsync("localhost");
            var db = connection.GetDatabase();
            var batch = db.CreateBatch();

            // Init our batched commands
            var task1 = FastCommand(batch);
            var task2 = SlowCommand(batch);

            batch.Execute();

            await Task.WhenAll(task1, task2); // <-- Deadlock here
        }

        private async Task FastCommand(IBatch batch)
        {
            await batch.StringSetAsync("test:key1", "foo");
        }

        private async Task SlowCommand(IBatch batch)
        {
            // This method does some other work before running the command. Oops!
            await Task.Delay(1000);
            // The following line executes after the batch is executed, so the await never completes!
            await batch.StringSetAsync("test:key2", "bar");
        }
```

Simplest repro code:
```
        [Fact]
        public async Task Batch_Deadlock()
        {
            var connection = await ConnectionMultiplexer.ConnectAsync("localhost");
            var db = connection.GetDatabase();
            var batch = db.CreateBatch();
            var task1 = batch.StringSetAsync("test:key1", "foo");
            batch.Execute();
            var task2 = batch.StringSetAsync("test:key2", "bar");
            await Task.WhenAll(task1, task2); // <-- Deadlock here
        }
```

**Comment by NickCraver** [comment]
This isn't a deadlock per se, it's only awaiting a task that'll never complete. It's waiting _on you_ to call `.Execute()`. The awaiting of it is valid, the awaiting of it before ever starting it is not an awesome idea and will never complete. This is the same as waiting on an HTTP request that never got a response, forever. It's not blocked _because of something else contending for resources_ (a deadlock), it's a solo lock of a non-started thing.

The example I typically use to illustrate this is it's like listening for a laundry load to finish when you never hit start - the same is happening here. Another thread could call `batch.Execute()` and that task would return, just as another person could hit start the laundry and you'd still get the intended result down the line.

**Comment by OronDF343** [comment]
@NickCraver 
In this case, I have already called `Execute()`. I would normally expect that a batch that was already executed would no longer be valid, just like a `Task` that was already started before and completed cannot be started again (and will throw an exception if I attempt to do so).

**Comment by NickCraver** [comment]
@OronDF343 the batch has executed and those commands have been sent, yes. But it is reusable and that's a supported use case. For example this is 100% valid use:

```
[Fact]
public async Task TestBatchReuse()
{
    using (var muxer = Create())
    {
        var conn = muxer.GetDatabase();
        var key = Me();
        _ = conn.KeyDeleteAsync(key);

        var batch = conn.CreateBatch();                
        _ = batch.StringIncrementAsync(key); // 1
        var countTask = batch.StringIncrementAsync(key); // 2
        batch.Execute();

        var count = await countTask;
        Assert.Equal(2, count);

        // Starting at 2 from above - the queue has cleared and we're only sending the below 2 commands in the next batch
        _ = batch.StringIncrementAsync(key); // 3
        var count2Task = batch.StringIncrementAsync(key); // 4
        batch.Execute();

        var count2 = await count2Task;
        Assert.Equal(4, count2);
    }
}
```

**Comment by OronDF343** [comment]
@NickCraver Ok I got it, thanks.
