### ISSUE TITLE
A connection attempt failed because the connected party did not properly respond after a period of time

### ISSUE THREAD

**Issue by congruihuang** [StackExchange/StackExchange.Redis#197]
Hi,
I use the library in our service and we got the bellowing exception and i haven't found any related possible reasons about raising such exception

```
Unhandled Exception: StackExchange.Redis.RedisConnectionException: SocketFailure on GET ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at StackExchange.Redis.PhysicalConnection.EndReading(IAsyncResult result) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 707
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1766
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1431 
```

**Comment by mgravell** [comment]
That's:  a socket timeout; IIRC the default socket timeout (we don't
specify `ReceiveTimeout` in the code, so the default it all that applies)
is 10 minutes (source:
https://msdn.microsoft.com/en-us/library/system.servicemodel.channels.binding.receivetimeout%28v=vs.110%29.aspx).
Normally, I would expect the system to setup a keep-alive much lower than
this, however: you could try specifying `KeepAlive` explicitly in  the
configuration; the time is in seconds. I would suggest 30 seconds as  a
first attempt. Normally, it negotiates the keep-alive internally by talking
to the server, but this is not always available - especially if the
`CONFIG` command is not available. Let me know if adding a keep-alive helps.

On 23 April 2015 at 09:26, congruihuang <notifications@github.com> wrote:

> Hi,
> I use the library in our service and we got the bellowing exception and i
> haven't found any related possible reasons about raising such exception
>
> Unhandled Exception: StackExchange.Redis.RedisConnectionException:
> SocketFailure on GET ---> System.IO.IOException: Unable to read data from
> the transport connection: A connection attempt failed because the connected
> party did not properly respond after a period of time, or established
> connection failed because connected host has failed to respond. --->
> System.Net.Sockets.SocketException: A connection attempt failed because the
> connected party did not properly respond after a period of time, or
> established connection failed because connected host has failed to respond
> at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
> --- End of inner exception stack trace ---
> at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
> at StackExchange.Redis.PhysicalConnection.EndReading(IAsyncResult result)
> in
> c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line
> 707
> --- End of inner exception stack trace ---
> at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImplT in
> c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line
> 1766
> at StackExchange.Redis.RedisBase.ExecuteSyncT in
> c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line
> 81
> at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags
> flags) in
> c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line
> 1431
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/197>.
>



-- 
Regards,

Marc

**Comment by congruihuang** [comment]
Thanks for your replying, the explanation is pretty clear, yesterday i reviewed my logic and found there was possibly too much useless connection to the cache. I just changed the logic to see if it works

**Comment by NickCraver** [comment]
@congruihuang are you working now, or any info to add here?

**Comment by amritdorka** [comment]
did this work ??

**Comment by javaHelper** [comment]
Could you please guide me here: https://stackoverflow.com/questions/62512541/a-connection-attempt-failed-because-the-connected-party-did-not-properly-respond ?
