### ISSUE TITLE
StringSetAsync does not support setting multiple values to RedisValue.Null

### ISSUE THREAD

**Issue by Bertie2011** [StackExchange/StackExchange.Redis#1980]
We want to supply multiple keys with `null` values, using StringSetAsync. This gives an exception that "null values are not supported in this context". However, with only 1 null value it does work. The null check is inside an `AssertNotNull()` method, so I think it is called very intentionally.

I was wondering, why? And is setting the keys one by one our only option or are we missing something?

---

### Answer
Redis doesn't support `null`. I made the wrong assumption that RedisValue.Null was a redis compatible value that represented `null` in the data store. What actually happens is that a SetString with a single RedisValue.Null results in a _key delete_ and a GetString on a non-existent key also returns RedisValue.Null. It's not possible to provide RedisValue.Null if there are multiple key/value pairs provided, because there is _no Redis command_ that supports setting some keys and deleting other keys at the same time.

**Comment by NickCraver** [comment]
The null check in there is for passing no pairs of key/values (unless I'm misunderstanding the overload). Can you please provide a code sample of what you're trying to call?

**Comment by Bertie2011** [comment]
We created an interfacing client with the following code:
```CS
public Task SetValuesAsync(IEnumerable<(string key, object value)> pairs)
{
  List<KeyValuePair<RedisKey, RedisValue>> keyValuePairs = new();
  foreach ((string key, object value) in pairs)
  {
    keyValuePairs.Add(new KeyValuePair<RedisKey, RedisValue>(new RedisKey(key), ToRedisValue(value)));
  }

  return Database.StringSetAsync(keyValuePairs.ToArray());
}
```

Then ToRedisValue, returns RedisValue.Null if `null` is provided.

Then, through StringSetAsync, we end up at [GetStringSetMessage](https://github.com/StackExchange/StackExchange.Redis/blob/15c752e1d2e1cc437359c1c203eafc2970db8a16/src/StackExchange.Redis/RedisDatabase.cs#L3471). It calls different methods based on the amount of provided values. If there is more than 1 value, then the Message.CreateInSlot method calls a constructor that asserts Not Null.

Which feels strange at first sight, because the execution path for 1 value only it does work.

**Comment by NickCraver** [comment]
Ah okay - thanks for the clarification! Now I get where you're hitting. I'm not sure what _should_ happen here but changing the base would allow other cases through to fail.

Follow-up question: what do you _want_ to happen here? Setting the key to null, or is removing them more appropriate for your use case?

**Comment by Bertie2011** [comment]
I think we want to set it to null and not remove it. I'll check tomorrow to confirm this, I'm not at work atm.

**Comment by mgravell** [comment]
> I think we want to set it to null and not remove it.

Null is not a value that can exist as a string in redis 🤷

**Comment by Bertie2011** [comment]
But the library uses a constant to symbolise null: RedisValue.Null. Using multiple of these values with StringSetAsync throws the exception.

**Comment by Bertie2011** [comment]
Yeah I'm not all that familiar with redis. It seemed like we were able to use RedisValue.Null when we only set 1 value. Why is that? 

I'm starting to think we didn't see what we thought we saw, but I can't double check anything right now.

**Comment by mgravell** [comment]
> I'm starting to think we didn't see what we thought we saw

I wouldn't assume anything at this point; I will try to have a look tomorrow, but it could (hypothetically) be that we're electing to interpret null as delete in the single case, *because we can*, meaning: there is a single atomic operation we can use which achieves that intent. There is not, however, a single atomic operation that achieves "set some strings and delete some others".

**Comment by mgravell** [comment]
Yup, you didn't imagine that: https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/RedisDatabase.cs#L3496

```
private Message GetStringSetMessage(RedisKey key, RedisValue value, TimeSpan? expiry = null, When when = When.Always, CommandFlags flags = CommandFlags.None)
        {
            WhenAlwaysOrExistsOrNotExists(when);
            if (value.IsNull) return Message.Create(Database, flags, RedisCommand.DEL, key);
```

**Comment by Bertie2011** [comment]
> we're electing to interpret null as delete in the single case

> there is a single atomic operation we can use which achieves that intent. There is not, however, a single atomic operation that achieves "set some strings and delete some others"

Ooooh, what I think happened was that setting the null value and then getting the same key returning this null value made us believe it stored something representing null in the database, while in fact it was deleted.

I will discuss this with the other guy who was working on this, but I'm pretty sure this was the source of the mystery. Thanks for your time!
