### ISSUE TITLE
SELECT after every EXEC / non-standard command

### ISSUE THREAD

**Issue by slorello89** [StackExchange/StackExchange.Redis#1988]
👋 I was debugging an issue today, a customer saw an abnormal number of SELECTS being sent to their Redis instance, which was pretty odd given they weren't passing any arguments into `GetDatabase`. After a bit of digging, I found [this](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/PhysicalBridge.cs#L1419) bit of code from the libraries earliest days, which pointed me to the fact that whenever they execute a transaction, a `SELECT` is called immediately afterward.

I then noticed that above that bit, the `UNKNOWN` command also falls through to the same condition. This means that if you execute any Redis Command via the `Execute`/`ExecuteAsync` API (which is the pattern in NRediSearch, Redis.OM, NReJSON, etc. . .) that the multiplexer will immediately call `SELECT` afterward.

I suppose my question is in 2 parts

1: What was the origination of this behavior for `EXEC`? My guess would be that it's because if you call a `SELECT` in the middle of a transaction that it will change the client's selected database. But I don't think there's a way in which you can call an arbitrary command on a transaction is there? My other guess would be that since you are loaning a copy of the database to the transaction you need to be double sure that you set the selected database is correct afterward, but for some reason that doesn't ring correctly to me.

2: Would it be possible to provide either a way to extend the `RedisCommand` enum to allow expanded command sets, or alternatively perhaps provide a configuration item to prevent `UNKNOWN` commands from encountering this? 

I'd of course be happy to open any PRs required myself.

Thanks!

**Comment by mgravell** [comment]
The motivation here is about correctness, and our confidence/knowledge of what a particular command has done, and in particular: could they have changed database?

I *thought* the transaction logic only applied in the case of failure, but I'm happy to be corrected. When using Lua, the caller can certainly change the connection database, so we need to treat that defensively. I "presume* the same is true of an ad-hoc command, whether inbuilt redis or a custom module.

Things we could consider here:

- if we know (from `info`, or config) that there is only one DB, we could ignore this (like we do for cluster)
- we could consider a new `CommandFlags` option which means "trust me, I don't change database"

Thoughts?

Note: the impact of this command is usually negligible, since we don't await it - it just becomes part of the same packet as the command, and the server processes it trivially. If you are seeing mearusable impact, I'm not against looking more, though.

**Comment by slorello89** [comment]
Hi @mgravell thanks for getting back so quick

> I thought the transaction logic only applied in the case of failure

I can confirm it's definitely happening after a successful transaction:

```csharp
var db = muxer.GetDatabase();
for (var i = 0; i < 3; i++)
{
    var transaction = db.CreateTransaction();
    var t1 = transaction.StringSetAsync("foo", "bar");
    var t2 = transaction.StringGetAsync("foo");
    await Task.WhenAll(transaction.ExecuteAsync(), t1, t2);
    Console.WriteLine(t2.Result);
}
```

The above trivial example corresponds to the following in Redis:

```text
1644588492.645289 [0 172.17.0.1:36414] "MULTI"
1644588492.645645 [0 172.17.0.1:36414] "SET" "foo" "bar"
1644588492.645673 [0 172.17.0.1:36414] "GET" "foo"
1644588492.645674 [0 172.17.0.1:36414] "EXEC"
1644588492.650322 [0 172.17.0.1:36414] "SELECT" "0"
1644588492.650345 [0 172.17.0.1:36414] "MULTI"
1644588492.650351 [0 172.17.0.1:36414] "SET" "foo" "bar"
1644588492.650353 [0 172.17.0.1:36414] "GET" "foo"
1644588492.650354 [0 172.17.0.1:36414] "EXEC"
1644588492.651078 [0 172.17.0.1:36414] "SELECT" "0"
1644588492.651082 [0 172.17.0.1:36414] "MULTI"
1644588492.651086 [0 172.17.0.1:36414] "SET" "foo" "bar"
1644588492.651087 [0 172.17.0.1:36414] "GET" "foo"
1644588492.651092 [0 172.17.0.1:36414] "EXEC"
```

You'll notice the SELECTs called after each EXEC (I think it's probably more accurate to say it's called BEFORE each successive MULTI). Again, I'm not certain that there's a valid reason to set the database to unknown after an EXEC, since as far as I can tell there's no API to call SELECT from within a transaction? Please correct me if I'm missing something?

> When using Lua, the caller can certainly change the connection database, so we need to treat that defensively

This was definitely true at one point, but as you can see in that [switch statement](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/PhysicalBridge.cs#L1412), it appears that there was a change in Redis that prompted you (or one of the library's other contributors - I can't readily tell from the blame) to circle around this for scripts, as apparently SELECT is no longer applied to the calling client within a script here's the pertinent section of the [release notes](https://github.com/redis/redis/blob/2.8/00-RELEASENOTES#L322).

To your point, I can definitely see the need to be defensive with arbitrary commands.

I'm not sure about trying to divine the presence of other databases from the info, since this can change on the fly. I suppose if something were added to the configuration of the multiplexer that told it there was only a single database that could work. But then I guess my next question is: Does it toss an exception if you try to select the non-default database?

Having a command flag "hey, pinky-swear I'm not changing the database" seems the most correct way to handle this with minimal disruption.

If that's acceptable to you, I'll open a PR to add it.

Circling back to the EXEC, given what I mentioned above, can I correct that behavior in the same shot?

thanks again!

**Comment by mgravell** [comment]
Ah yes, you've reminded me about that change to Lua, thanks; I'll try to
think about EXEC over the weekend - I *think* it should be OK in any
success case, but I believe the problem is that due to the multiplexed
nature of the connection, we don't usually wait for the result before
issuing the next command - which means *if* the user issued a select inside
the transaction, there's both possibilities: the select runs, and the
select doesn't run. Because of that, we need to be cautious. However! I
suspect we should be able to do something like tracking whether we've
issued a DB-impacting command during the transaction (which could be any of
SELECT, EVAL/EVALSHA on down-level servers, or unknown commands) - and then
we could only mark the DB as unreliable if any of those apply. That
probably means that we'd avoid the SELECT in almost all cases, without the
caller having to do anything special. Sound reasonable?

**Comment by mgravell** [comment]
(and yes, I think you're right in that the API won't give rise to direct
SELECT usage mid-transaction, so that just leaves Lua on down-level
servers, and unknown ad-hoc commands)

**Comment by slorello89** [comment]
Cool, so given all this how does the following sound:

* Preserve current feature-checking logic for EVAL/EVALSHA
* Remove `DISCARD`/`EXEC` from the switch statement (since as we've discussed it's not possible to call `SELECT` in a case where `DISCARD`/`EXEC` are the `cmd`'s value)
* Add a flag in Command flags (presumably ordinal value 2048) to tell the `PhysicalBridge` to not reset the database number in case of an ad-hoc command, call it something like: `NonDatabaseChanging` or something to that effect.
* Add a short blurb in the summary docs above `Execute`/`ExecuteAsync` explaining the reasoning?

LMK what you think, if this all sounds good I'll open a PR for it.

**Comment by mgravell** [comment]
The discard/exec is a bit more complex than that; we need to know whether any command *in the transaction* might have changed db - essentially just an accumulator of the day usual same logic, on a command-by-command basis, but: yes

**Comment by mgravell** [comment]
> Question: what's stopping someone from doing an .ExecuteAsync(<customCommand>) in the transaction itself? 

That would be the "we need to know whether any command *in the transaction* might have changed db" part

**Comment by NickCraver** [comment]
@mgravell k, same page there - I'm wondering if that's worth doing and adding complexity for, back to...what problem are we solving? @slorello89 Could you elaborate on if this is causing an issue today or just looks odd?

**Comment by slorello89** [comment]
@mgravell @NickCraver , so, this is actually surprisingly a bit of an issue on Redis Enterprise. The proxy routes all the incoming SELECTS to slot-0 by default (I'm not entirely sure why this is the case, I'm guessing this is because SELECT isn't supported), so the impact on the first shard can be significant if you are sending lots of transactions/ad-hoc commands (as it's getting hit by everything in the cluster). We can work around this by disabling SELECTs at the proxy level, but since these commands aren't doing anything to alter the selected database the SELECT probably shouldn't be sent in the first place.

**Comment by NickCraver** [comment]
Is Redis Enterprise cluster in this case? (Sorry I'm not familiar with all the hosting models going on) 

If the issue is sending the command at all in a cluster, that's a _much_ simpler change and totally agree we should tweak that (which also has no consequences to reason about). I even have a new helper method for this as a result of the Envoy work :)

**Comment by NickCraver** [comment]
Looked at where this happens - ultimately if `SELECT` isn't supported, then we should not be generating the `SELECT` commands to issue at all, that happens here: https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/PhysicalConnection.cs#L576 - so the higher level question I have is: what's the setup here, and why do we think it supports SELECT in the first place? I'm not sure what the connection setup is to Redis Enterprise so some more info there would help!

**Comment by mgravell** [comment]
if we can *detect* this scenario: no problem automatically disabling it; as a temporary workaround, I suspect if the user adds `,$SELECT=` to their connection string, it should end up disabled anyway

**Comment by NickCraver** [comment]
+1 - wondering if we can detect it and help out, with more details I can poke there (been in the area) - it looks like we _think_ it's Standalone atm (`.HasDatabases` is `true`), so I'm super curious what the combination of hosting is here, is it cluster with a single endpoint like Envoy? I'm curious!

**Comment by slorello89** [comment]
Aye, Clusters in Redis Enterprise have a proxy that accepts the incoming commands, so it looks sort of like a stand alone to the client. That's probably why the multiplexer thinks it can have multiple databases.

**Comment by mgravell** [comment]
I don't have redis enterprise to test against; any chance `info` gives us anything useful we could detect here?

**Comment by NickCraver** [comment]
I was looking at this but in a long session this week and didn't writeup: indeed there's no check here, but if we add one it needs to be as efficient as possible since it's inside the write lock. Most of the throughput performance that we're looking at is "how long is the lock taken?" and any extension of that is a net drain on throughput. I'll look at making `$SELECT=` work as part of making the lock slimmer in general - I think we can memoize some of the checks that don't change here to slim it a bit and I want to benchmark there. I'm only recently setup to do so, likely an end-of-week or next item.

**Comment by slorello89** [comment]
@NickCraver, if a config-level change ends up being the answer. Perhaps making `ServerEndpoint.HasDatabases` honor something in the configuration would be an appropriate route? Since every clock cycle is precious inside the write lock, you could even replace the computed property.

```csharp
public bool HasDatabases => serverType == ServerType.Standalone;
```

With a simple property:

```csharp
public bool HasDatabases { get; }
```

Then when the ServerEndpoint is initialized, interrogate the config for either a disabled SELECT command or perhaps a config setting `HasDatabases` which defaults to true, and set `HasDatabases` as such:

```csharp
HasDatabases = config.CommandMap.IsAvailable(RedisCommand.SELECT) && config.HasDatabases;
```

Then in the ServerType property's setter, (this is what gets called after a successful call to `CLUSTER NODES`), set `HasDatabses`  

```csharp
HasDatabase = HasDatabases && value == ServerType.Standalone
```

Unless there are some other externalities I'm missing?

**Comment by NickCraver** [comment]
@slorello89 This week is crazier than most so very slow here, likely won't dig in until next week and recharged but yes we can probably memoize it in some way, though I'm not sure if a) that's the correct location (it's not per-server that it's disabled, for example), and b) how that'll interact with config changes at runtime. Something in play here is we intend to add a method soon to allow config changes at runtime for example to change authentication passwords for next reconnect in rolling environments and such. How that plans with memoized things based on config downstream is a factor.

Is there any chance you could post a full `INFO` (sans anything sensitive of course) that we could peruse to see if anything else stands out on the "auto-detect it" front?

**Comment by slorello89** [comment]
Hi @NickCraver, figured I'd wait a few days to get back to you as you seemed a bit swamped. What follows is the info from a RedisEnterprise instance with a similar configuration to the one we are talking about. Unfortunately, there's not much to go off of from the info.

```
# Server
redis_version:6.0.13
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:0000000000000000000000000000000000000000
redis_mode:standalone
os:Linux 4.15.0-1098-gcp x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:5.4.0 20160609
process_id:3
run_id:0640e63f679f0ec0c2c3bb7d694de9eef3ed92df
tcp_port:12000
server_time_usec:1645108605000000
uptime_in_seconds:91
uptime_in_days:0
hz:10
lru_clock:0
config_file:

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
maxclients:0
cluster_connections:0

# Memory
used_memory:56383632
used_memory_human:53.77M
used_memory_rss:56383632
used_memory_peak:101404864
used_memory_peak_human:96.70M
used_memory_lua:227328
mem_fragmentation_ratio:1
mem_allocator:jemalloc-5.1.0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1645108513
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:1
total_commands_processed:1
instantaneous_ops_per_sec:26
total_net_input_bytes:235674
total_net_output_bytes:479458
instantaneous_input_kbps:1.18
instantaneous_output_kbps:3.09
rejected_connections:0
sync_full:1
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
total_forks:0
total_error_replies:0

# Replication
role:master
connected_slaves:1
slave0:ip=0.0.0.0,port=0,state=online,offset=0,lag=0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.00
used_cpu_user:0.00
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
used_cpu_sys_main_thread:0.00
used_cpu_user_main_thread:0.00

# Cluster
cluster_enabled:0

# Keyspace
```

**Comment by NickCraver** [comment]
@slorello89 Thanks for that - agree we can't do much here. I have some bigger fish in progress about 2.5 but haven't forgotten about this - we'll make the `$SELECT` work here.

**Comment by slorello89** [comment]
Fix works, thanks @NickCraver & @mgravell :)
