### ISSUE TITLE
Leaking sockets for ConnectionMultiplexer#GetDatabase()

### ISSUE THREAD

**Issue by dxynnez** [StackExchange/StackExchange.Redis#1995]
Hi team,

I originally added my question under https://github.com/StackExchange/StackExchange.Redis/issues/1084 but no one seems to be actively monitoring it so I am just opening a new issue instead.

Long story short, with the following code:
```
            var multiplexer = ConnectionMultiplexer.Connect("#A VALID REDIS HOST#:6380,password=#ANY INVALID PASSWORD#,ssl=True,abortConnect=False");
            for (int i = 0; i < 1000; i++)
            {
                try
                {
                    multiplexer.GetDatabase();
                }
                catch (Exception ex)
                {
                    Console.Out.WriteLine(ex.Message);
                }
            }
```

Seems like the GetDatabase call would try to establish the connection everytime since we set 'abortConnect=False' when connect. I guess this is somewhat expected as none of the connections could be established (invalid password) and it just keep opening new ones which sooner ends in TIME_WAIT? 

I know in the reality the password should be valid, but we are more concerned for the cases that when the azure redis service is down - in that case, would it result in the same socket leak as no connection could be established?

Also, do you happen to know why the abortConnect is default to false on Azure? I am wondering if I should just set it to true and enable retry when trying to connect.

**Comment by NickCraver** [comment]
I'm trying to follow the issue here - what is _not_ happening that should be happening? Or what _is_ happening that should not be happening?

Summary of things I'm thinking about in case it helps:
1. Repeated attempts to retry indefinitely are expected (but they're throttled).
2. abortConnect is so your app can continue starting if it can't initially connect to the endpoint (e.g. your app starts faster than Redis is available), and it'll connect as soon as it can.
3. There's by default an exponential backoff in our connect retries, so you should be a long, long way from sockets exhausting at the rate we continue connecting. (are you saying that's not working and it's slamming the server as hard as possible here?)

Does the above make sense? I'm not sure what _actual problem_ is being described - I realize "it won't connect without the right password" is the root (and expected) but what downstream problem is this causing?

**Comment by dxynnez** [comment]
Hi, @NickCraver 

Regarding:

>There's by default an exponential backoff in our connect retries, so you should be a long, long way from sockets exhausting at the rate we continue connecting

First thanks for pointing out it's possible to setup retry policy for reconnect, we will definitely looking into implementing a backoff retry with circuit breaker in place.

Currently the default reconnect retry seems more to be a linear retry, though. It just keeps opening new sockets at a steady rate (level of seconds) and eventually eat up all the available ports - we are on azure app service where outbound port is very limited (level of hundreds).

Also I would like to know what would happen if I call ConnectionMultiplexer#GetDatabase when it didn't actually connect to the redis server? Would it just throw immediately, or it's a blocking call until the next connect retry can take place? I am just trying to make sure increasing the retry backoff won't increase of the chance of running into thread starvation...

**Comment by NickCraver** [comment]
@dxynnez Which version of the library are you on? Exponential is the default in the current release for example.

GetDatabase _doesn't do anything_. It's a client-side construct. It won't cause any connection behavior or wait whatsoever. In the 2.5.x release (currently in prerelease on NuGet), we'll backlog commands issued against anything, up until the timeout, and retry when connected or reconnected, if that's appealing.

**Comment by dxynnez** [comment]
@NickCraver 

We are at 2.0.593 and I changed the code a little bit to sleep for 5 mins and the it seems to open up 2 sockets / s.

But even with the latest (2.2.88), it still behave the same. I also tried setting the ReconnectRetryPolicy to ExponentialRetry with following code but it's still the same:
```
            var multiplexer = ConnectionMultiplexer.Connect(
                "blahblah.redis.cache.windows.net:6380,password=,ssl=True,abortConnect=False",
                options =>
                {
                    options.ReconnectRetryPolicy = new ExponentialRetry(5000, 1000 * 60);
                });
            multiplexer.GetDatabase();

            Thread.Sleep(1000 * 60 * 5);
```

Regarding
>In the 2.5.x release (currently in prerelease on NuGet), we'll backlog commands issued against anything, up until the timeout, and retry when connected or reconnected, if that's appealing.
If I understand you correctly, currently desperately issuing commands (retry by our own logic) while the mux isn't connected wouldn't result in extra sockets getting opened - honestly that's the most important thing I am trying to prevent at the moment as again we have very limited number of available sockets.

**Comment by dxynnez** [comment]
@NickCraver oh yeah I got that, the GetDatabase call was just to make sure the multiplexer won't be optimized away by the compiler / IL.

I just realized my concern for the same socket leak while redis is down, is completely absurd as in that case the connection wouldn't even be established in the first place and hence no socket consumption.


>It's possible we could detect repeated auth failures specifically and institute the backoff policy in that case
This would be great, and it's probably even better if it can throw exception to signal the failure, or, provide a callback to rotate the key. Otherwise it's a bit hard to programmatically rotate the key without causing any downtime to the system,

**Comment by NickCraver** [comment]
Ah, the root of the issue - please lead with the problem next time! So, key rotation :)

We have an idea for this to _proactively_ rotate keys, but more generally: have something like a .UpdateConfig() on a multiplexer that allows updating running configuration for the next reconnect. Precisely for things like key rotation - this may land in 2.5, discussing it a bit offline now with some provider teams. Any thoughts you have on use case would help inform design there!

**Comment by dxynnez** [comment]
Absolutely. For this one, we didn't actually rotate the key (at least not on purpose) - it was our buggy deployment script somehow set the redis key to empty and we didn't find out until the machine was running out of ports.

The UpdateConfig would definitely help, but that would require us to try catch all the outbound call on the mux and only update the config if the exception is related to auth (which is pretty nasty as the exceptions are all RedisConnectionException). It would be great if a different exception could be thrown for auth issue. I know I am probably asking for too much, but it would be even better if we just need to provide a callback to fetch the latest key and the mux would automatically invoke it to do the rotation when auth fails.

**Comment by NickCraver** [comment]
@dxynnez Was trying to follow-up here. Yes the type is `RedisConnectionException`, but it has a `FailureType` property for disambiguating what's what. In this case, you're looking for `ConnectionFailureType.AuthenticationFailure`. This could be used in an exception filter, etc.

For the configuration part, in the next release the `ConfigurationOptions` passed in _will_ be respected after the initial connection (where it was a cloned copy before). This means updating `User` and `Password` at any point will be observed when reconnecting :)

**Comment by NickCraver** [comment]
The above bits are release and ready for use! You can proactively update the auto info for reconnect as it changes for exactly this situation. I'm going to close out to tidy up but happy to re-open if there's more follow-up here :)

**Comment by dxynnez** [comment]
Thanks for the update @NickCraver ! I  will play around with it!
