### ISSUE TITLE
Not able to connect to any endpoints returned by cluster-mode enabled Elasticache Redis instance

### ISSUE THREAD

**Issue by rpatel372** [StackExchange/StackExchange.Redis#1997]
I'm trying to flush my database. I am getting passing in my Elasticache Redis instance's configuration endpoint. Then I find the first server that is not a replica and attempt to flush it. However, this is failing because each of the endpoint's IsConnected property is set to false. I'm getting an exception: `StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: FLUSHALL; It was not possible to connect to the redis server(s).` How can I connect to my cluster-mode enabled Redis instance?

```
var options = new ConfigurationOptions()
{
    EndPoints = {  ElasticacheRedisConfigurationUrl },
    AllowAdmin = true,
            
};
        
using (ConnectionMultiplexer conn = ConnectionMultiplexer.Connect(options))
{
     var endpoints = conn.GetEndPoints();
     var server = endpoints.Select(x => conn.GetServer(x)).First(x => !x.IsReplica);
     server.FlushAllDatabases();
} 
```

I also attempted to directly connect via the configuration endpoint, and sometimes this works but most of the time I'm getting a "cannot flush on a replica node" error:

```
IServer server = conn.GetServer(ElasticacheRedisConfigurationUrl );
server.FlushAllDatabases();
```

**Comment by mgravell** [comment]
The code you have looks like it should work; I'm surprised and confused that it isn't, after what looks like a successful connect.

**Comment by NickCraver** [comment]
I don't believe we allow a `FLUSHALL` if the server doesn't have databases (I see cluster in the title here), instead you'll want to call `.FlushDatabase()` (or async) on the server for the cluster case - it only has 1 database total (database 0) since they aren't present in the cluster implementation.

**Comment by NickCraver** [comment]
Closing this out to tidy up!
