### ISSUE TITLE
Transaction/batch not working after unsuccessful connection to redis

### ISSUE THREAD

**Issue by fan1x** [StackExchange/StackExchange.Redis#200]
Hi,
I have problem when I start application and after few unsuccessful connection I finally start redis. After that I create transaction/batch and execute it. Than if I wait on tasks to finish it gets stuck. 
Here is my question on SO also with code to reproduce it:
http://stackoverflow.com/questions/29851293/transaction-not-working-after-unsuccessful-connection-to-redis-using-stackexchan

**Comment by NickCraver** [comment]
@fan1x are you still seeing this in a current build? Task completions changed a bit and one of those fixes may have been for the issue you're hitting.

**Comment by fan1x** [comment]
I tested it and looks fine. Thanks guys!
