### ISSUE TITLE
SE version 2.1.3 Timeouts

### ISSUE THREAD

**Issue by ShrikantAdp** [StackExchange/StackExchange.Redis#2007]
Hi,

We are using SE 2.1.3 with .Net4.7 Framework with Redis server running on RHEL and windows servers farm as clients. Currently we are facing frequent timeouts in a day. 

ConnectString:
redis.xyz.com:nnnn,allowAdmin=false,password=****,configChannel=,tiebreaker=,syncTimeout=500,configCheckSeconds=0,responseTimeout=1000

Exception:
_Timeout performing GET IDC:20179999, inst: 1, mgr: ExecuteSelect, err: never, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: myServer01, serverEndpoint: Unspecified/redis-nnnn.redis.xyz.com:nnnn, keyHashSlot: 4899, IOCP: (Busy=0,Free=1000,Min=600,Max=1000), WORKER: (Busy=2,Free=8189,Min=600,Max=8191) (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts); at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) at Xyz.RedisDriver.TryGet[T](String key, T& value)_

_ERROR Xyz.Cache.Client [IIS APPPOOL\API-Sys] - Data=The Redis connection was broken. ConnectionType: Interactive, FailureType: SocketFailure, Exception = StackExchange.Redis.RedisConnectionException: SocketFailure on redis-nnnn.redis.xyz.com:nnnn/Interactive, origin: CheckForStaleConnection, input-buffer: 0, outstanding: 2, last-read: 2s ago, last-write: 0s ago, unanswered-write:*REMOVED*, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 12, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: RecordConnectionFailed_ReportFailure, err: never_

Based on the above error  looking at the trace below "2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 0, ar: 0" implies that the client is waiting on 2 jobs(qs) to be completed on Redis side and nothing is pending on the client side(in). Looking into Redis server there are no slow running queries, CPU or memory issue. 

How to find out whats holding up the Redis connection? Is there log or setting in SE? Is the new version of SE 2.2.88 compatible with .Net4.7 and will the upgrade help?

**Comment by NickCraver** [comment]
Yes, the latest is compatible with .NET 4.7, and has more timeout information in errors to inform what's happening so you'll want to upgrade there. Overall though, the timeout is very low at 500ms - that's _in the worst case scenario_, it can never go over 500ms. Stuff happens on networks, etc. even if client/server isn't bogged down (your client doesn't _appear_ to be overloaded here - we'd never recommend a 500ms timeout in general (and only enforce it in 1000ms fidelity intervals anyhow).

**Comment by ShrikantAdp** [comment]
Thanks Nick!!  We are in process of updating the SE Redis version to 2.2.88, we are hitting an issue with having older version of System.Runtime.CompilerServices.Unsafe.dll version 4.0.x used by our application which we are resolving through bindingRedirect settings in App.config file. Let me know if there is another way.

As for syncTimeout being low, we started with 1000ms at first and were getting timeouts but the connections were getting restored very quickly so it was a fleeting interruption but we clear the cache to maintain the data integrity across 250-300 server web farm connected to Redis which is very disruptive.

As the Redis interactions are one part of a bigger transaction we didn't want to hold the transaction more than 1000ms so decided to try fail fast approach i.e. reduce syncTimeout to 500ms and retry one more time before throwing timeout exception as typical Redis operation time in our application is < 10ms and we reduced the timeouts by 40-50%. Is there inbuilt retry logic which we can leverage once we complete the upgrade?

**Comment by NickCraver** [comment]
@ShrikantAdp There is in-built queue logic (e.g. if the connection is down we'll hold and complete it) coming in v2.5 which I plan to release Monday (week got away from me here). I believe for retries there's a lot you don't want to retry automatically and some you do, so we leave that to a higher level like Parrot for users to determine what they want to retry.

**Comment by NickCraver** [comment]
@ShrikantAdp FYI that new release is now on NuGet, enjoy!
