### ISSUE TITLE
ERR Protocol error: invalid multibulk length

### ISSUE THREAD

**Issue by zhdaniel** [StackExchange/StackExchange.Redis#201]
Hi, mgravell. I got this error when I use the multi set keys to insert about 1 million records to redis at one time, i.e. the API in the StackExchange.Redis

`bool StringSet(KeyValuePair<RedisKey, RedisValue>[] values, When when = When.Always, CommandFlags flags = CommandFlags.None);`

and I searched the redis source code for `ERR Protocol error: invalid multibulk length`, but I'm sure my each value size is not bigger than 512MB, I can't figure out why, could you give me your help?

```
StackExchange.Redis.RedisServerException: ERR Protocol error: invalid multibulk length
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
```

**Comment by zhdaniel** [comment]
and I used like this
``` 
var temp = shareTerms
                  .AsParallel()
                  .Select(t => new KeyValuePair<string, string>(string.Format(keyTmpl, srcLang, tarLang, t.Tid), JsonConvert.SerializeObject(t)))
                  .ToArray();
if (Redis.Set(temp))
{
    ...
}
```

**Comment by zhdaniel** [comment]
finally, I figured it out.
the length of `args` of the API command `MSET` can't be bigger than 1024 * 1024, so the length of the array `KeyValuePair<RedisKey, RedisValue>[] values` cant be bigger than 524288, so I limit it to 524287, then it works.
I hope this would be helpful others.

**Comment by mgravell** [comment]
Wow; I wonder if that is documented anywhere. Good find! Please could you
reopen? I would like to change the code to work more appropriately: either
throw before sending, or split the work into multiple commands.

**Comment by zhdaniel** [comment]
with pleasure ;)

**Comment by zhdaniel** [comment]
I searched this error message at:  https://github.com/antirez/redis/blob/6c60526db91e23fb2d666fc52facc9a11780a2a3/src/networking.c#L1024
I think this should be the limitation of the `MSET` args length

**Comment by 631320085** [comment]
i still got this exception today. is this fixed ?

**Comment by zhdaniel** [comment]
@631320085 not yet

**Comment by 631320085** [comment]
Sorry for last comment, i was got this exception from ServiceStack.Redis yesterday. But today i use StackExchange.Redis SetAdd 1million values got a timeout exception, then i changed option's ConnectTimeout and SyncTimeout , it's worked. well done. @zhdaniel

**Comment by dtraykov** [comment]
+1

**Comment by vpagliari** [comment]
+1

**Comment by aspnerd** [comment]
When is this going to be fixed? I hit this error today once we loaded our data. Not good.

**Comment by mgravell** [comment]
k, I'll take responsibility for this and get it fixed next deploy. sorry -
it slipped through the cracks because it got closed

**Comment by zhdaniel** [comment]
very glad to hear that.

**Comment by circlechu** [comment]
it's in Redis source code 


/* We know for sure there is a whole line since newline != NULL,
         * so go ahead and find out the multi bulk length. */
        redisAssertWithInfo(c,NULL,c->querybuf[0] == '*');
        ok = string2ll(c->querybuf+1,newline-(c->querybuf+1),&ll);
        if (!ok || ll > 1024*1024) {
            addReplyError(c,"Protocol error: invalid multibulk length");
            setProtocolError(c,pos);
            return REDIS_ERR;
        }

**Comment by rtatton** [comment]
The error message on this should be more specific to avoid having to search and find this GitHub issue.
