### ISSUE TITLE
Core 5

### ISSUE THREAD

**Issue by billpratt** [StackExchange/StackExchange.Redis#202]
Will you be implementing a Core 5 build for this library? I'd like to use it in a Core 5 project I'm working on.

Thanks!

**Comment by mgravell** [comment]
Dnx? Yes, certainly. I'm working through projects: dapper is done,
protobuf-net is "kinda working ish"; SE.Redis is next on my list, but I'll
need to think about which socket polling methods to use - the regular .net
library does some things that won't be available in CoreCLR

**Comment by mgravell** [comment]
Timescales: hopefully before Monday - possibly sooner.

**Comment by billpratt** [comment]
![b4dfjkyciaaifz_](https://cloud.githubusercontent.com/assets/2847527/7520700/922790ce-f4b6-11e4-947f-e5c44323d598.jpg)

**Comment by mgravell** [comment]
Merry Christmas! Shitter was full!

**Comment by niemyjski** [comment]
+1

**Comment by TPoise** [comment]
Any update on a CoreCLR build?  Looking forward as well to using this...

**Comment by stebet** [comment]
Looking forward to this as well :) I'd love to help if possible.

**Comment by jmlothian** [comment]
I would absolutely love to have this as well.  Unfortunately, I'm not sure the CoreCLR is ready for it.  I put together a project myself just to get a general idea of the changes and for the features StackExchange.Redis uses, Core 5 is about 95% there. (And if anyone has looked closer, please correct me.  This was just a cursory scan of the compile results and the CoreFX github.)

A bit of the remaining stuff are easy fixes for things like some missing interfaces and array methods, and some things more complex with sockets like @mgravell mentioned.  

But the final 2% are things like... System.Threading.Thread missing a large number of functions or working in different ways (there's no Thread.Priority!?).  

For now, it looks like Thread and Threadpool are both somewhat incomplete and the CoreFX repo doesn't have a good public roadmap (that I've found anyhow), so its difficult to say when/if these features will be added.  I wouldn't want to go tinkering with the threading optimizations just to have to change things back later when features get added though.  

Unless someone has some insider information or is already planning a different approach anyhow.

**Comment by niemyjski** [comment]
We'd use this and are working towards getting our library to use core 5 as
well. We have a sole dependency on this library and would love if there was
support for it.

Thanks
-Blake Niemyjski

**Comment by ArieJones** [comment]
Would love to use this as well, I have a fairly large project that we have ported over to core 5 and the one dependency that is still out there is this one. We've managed a work around for now but would love to plug this back in. Does anyone have a timeline on when this might be available? 

Thanks,
AJ

**Comment by mgravell** [comment]
I did a spike but it lost momentum, mainly relating to work converting the
test suite. I'll re-evaluate the current state of core 5.

**Comment by niemyjski** [comment]
Thanks for your efforts, if you hit a road block please let us know and we all can chip in.

**Comment by Tazer** [comment]
This would be awesome! :+1:

**Comment by NickCraver** [comment]
@mgravell I'll have need for this soon too (blocker style) - I'm happy to continue the port, any chance you can throw what you currently have onto a branch?

**Comment by rustd** [comment]
@NickCraver @mgravell  @deepakverma has a fork which has the port (including unit tests)https://github.com/deepakverma/StackExchange.Redis/tree/client_for_k
Let us know if we can help update the client.

**Comment by TPoise** [comment]
And here I thought Pranav (@rustd) has forgotten all about me... :+1:

**Comment by mgravell** [comment]
Dare I ask: how big is the fork? How hard would it be to merge back in?
Happy to let other people take the heavy lifting here...

**Comment by deepakverma** [comment]
We @jeremymeng @rustd and Roger Best are actively working to make it work on coreclr 
@marc @TPoise @NickCraver can you please share what are you guys doing to make socket polling code work on coreclr?

**Comment by mgravell** [comment]
I mentioned this in a direct email too, but my original CoreCLR momentum
died with the pain of xunit => xunit. Beyond that, my plan was "make it
work". My initial hunch is that this will mean switching to the API that
the mono code uses.

**Comment by jeremymeng** [comment]
As easy as https://github.com/jeremymeng/StackExchange.Redis/commit/39cc2a79e080b803c36a2c3646c82e34e5c69a78? :)

**Comment by ForkBug** [comment]
+1

**Comment by louthy** [comment]
@mgravell - Hi Mark, first of all, thanks for all the hard work with this library, it's been solid as a rock for me on my [Language-Ext](https://github.com/louthy/language-ext) Redis-based actor library.

I'm just going through the process of migrating the project to DNX and wondered what the progress/expected likely delivery of DNX support will be?  I saw your blog posts on this subject, and yeah, I now feel your pain!

**Comment by mgravell** [comment]
There is an open PR from the MS folks that needs some final working
through. In theory we should be good for an alpha/beta pretty much any time.

On 9 December 2015 at 02:59, Paul Louth <notifications@github.com> wrote:

> @mgravell <https://github.com/mgravell> - Hi Mark, first of all, thanks
> for all the hard work with this library, it's been solid as a rock for me
> on my Language-Ext <https://github.com/louthy/language-ext> Redis-based
> actor library.
>
> I'm just going through the process of migrating the project to DNX and
> wondered what the progress/expected likely delivery of DNX support will be?
> I saw your blog posts on this subject, and yeah, I now feel your pain!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/202#issuecomment-163090506>
> .
>



-- 
Regards,

Marc

**Comment by louthy** [comment]
@mgravell - Thanks for the heads up.

**Comment by NickCraver** [comment]
This is now available in 1.1.533-alpha. Closing this out since we're up and running on it, but watch #328 for pending work for coreclr and of course please open issues for any trouble you see!
