### ISSUE TITLE
Redis Connection Timeouts under load

### ISSUE THREAD

**Issue by azharmahmood** [StackExchange/StackExchange.Redis#2028]
We run Redis sentinel with 3 nodes, it works fine when there are up to 175 users but starts throwing timeout errors when users exceed 200. At that point webservers CPUs are completely pegged.

Here is the configuration string we are using .
server1.stg:26379,server2.stg:26379,server3.stg:26379,serviceName=redisdb,allowAdmin=true
--
This is the exception:
Message:Timeout performing GET (5000ms), next: GET AcProductsOvernightZoneRate, inst: 6, qu: 0, qs: 48, aw: False, rs: ReadAsync, ws: Idle, in: 65536, in-pipe: 8192, out-pipe: 98, serverEndpoint: 10.91.132.24:6379, mc: 1/1/0, mgr: 7 of 10 available, clientName: server2.stg, IOCP: (Busy=2,Free=998,Min=4,Max=1000), WORKER: (Busy=46,Free=8145,Min=4,Max=8191), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) Logger: RedisCacheProvider , Method: GetFromCache<T> Exception: StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), next: GET AcProductsOvernightZoneRate, inst: 6, qu: 0, qs: 48, aw: False, rs: ReadAsync, ws: Idle, in: 65536, in-pipe: 8192, out-pipe: 98, serverEndpoint: 10.91.132.24:6379, mc: 1/1/0, mgr: 7 of 10 available, clientName: server1.stg, IOCP: (Busy=2,Free=998,Min=4,Max=1000), WORKER: (Busy=46,Free=8145,Min=4,Max=8191), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) at Teleflora.FlowerBuyer.Library.Providers.RedisCacheProvider.GetFromCache[T](CacheKeys cacheKey) in 

We tried connecting multiplexers pool without any luck. Any help will be much appreciated

**Comment by NickCraver** [comment]
There are a few things here:
1. `WORKER: (Busy=46,Free=8145,Min=4,Max=8191)` tells us that you have a lot of threads busy, and are likely hitting thread starvation.
2. `ExecuteSyncImpl` tells us you're using synchronous APIs (e.g. `.StringGet()`) rather than async APIs (e.g. `.StringGetAsync()`)
3. You're on an older lib version (lots of perf wins in newer versions, especially 2.5.x)

The second is likely a contributor or main cause of the first. Overall: you'll want to go async here.
