### ISSUE TITLE
support SPOP count parameter

### ISSUE THREAD

**Issue by doodoori2** [StackExchange/StackExchange.Redis#203]
SPOP key [count] http://redis.io/commands/spop
Redis command SPOP can use with default parameter 'count' .

But currently there is no parameter for count option.
RedisValue SetPop(RedisKey key, CommandFlags flags = CommandFlags.None);

I think need to implement below method. 
RedisValue SetPop(RedisKey key, long count = 0, CommandFlags flags = CommandFlags.None);

Thanks

**Comment by NickCraver** [comment]
Added to #528 for tracking.

**Comment by NickCraver** [comment]
PR open for this in #874

**Comment by NickCraver** [comment]
Merged into `pipelines`, closing this out as complete for v2 :)
