### ISSUE TITLE
Deadlock happened on ConnectionMultiplexer.OnHeartBeat

### ISSUE THREAD

**Issue by SamGuoMsft** [StackExchange/StackExchange.Redis#2035]
Hi folks,
We recently faced CPU wait issue in our service. When we looked at the dump, we found there is a deadlock on ConnectionMultiplexer.OnHeartBeat. Our NuGet package version is [2.0.519](https://www.nuget.org/packages/StackExchange.Redis/2.0.519), which is very old. We would like to know whether this is a known issue and had been fixed in the recent releases.

Following is the detail snapshot which showed the deadlock.
![image](https://user-images.githubusercontent.com/40610249/157986265-225ef79a-0d66-4d32-9b26-17956d8f8b77.png)

**Comment by NickCraver** [comment]
Update here: we discussed a better course of action than heavily debugging the root of this one is an upgrade to 2.5+ to avoid they interruptions in the first place or backlog when they do. Happy to help if y'all continue to see this  post-upgrade (which will have better debug info too).

Should we close this one out and reopen if you see it again with the update and more info we can hunt down?
