### ISSUE TITLE
Random timeout on read operations from Azure 

### ISSUE THREAD

**Issue by tinix0** [StackExchange/StackExchange.Redis#2044]
For the last few weeks, we have been chasing down an issue on our production that manifests in the following exception:
```
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=72KiB, 10368ms elapsed, timeout is 10000ms), command=MGET, next: MGET,
 inst: 0, qu: 0, qs: 0, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: xxx.redis.cache.windows.net:6380, 
mc: 1/1/0, mgr: 10 of 10 available, clientName: xxx(SE.Redis-v2.5.43.42402), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), 
WORKER: (Busy=8,Free=32759,Min=2,Max=32767), POOL: (Threads=12,QueuedItems=0,CompletedItems=39627833), v: 2.5.43.42402
```
It usually occurs ~once a day, the client is able to recover itself nearly immediately and the are no reconnects that happen as far as we can tell. When it occurs, it always results in large amount (single digit thousands) of request failures at once. The service that this occurs on is hosted in AKS, the cache is Azure Redis premium. 
What we tried/know:

- Update the library (it occurs on multiple versions)
- The cache is not under any abnormal load when this occurs and non-C# services have no issues from the same AKS cluster
- Increase the timeout to 10s from 5s, no change
- The clients do not spike in CPU usage at the time
- We've tried to use multiple connection multiplexers, no change
- It can occur across multiple cluster nodes
- IOCP busy, qu, qs is always at 0
- Highest WORKER busy I have seen was around 12
- The connection uses TLS
- Network load on the machines is well under 1Gbps
- The objects being processed on this client are small (64bit numbers and booleans)

We are also using a Redis LUA script to make some writes not fire in some conditions. 
We are at out wits end with this and we would be grateful if you could help us.

**Comment by NickCraver** [comment]
A few questions to help:
- Is it happening around the same time of the day? (e.g. scheduled job spike)
- Is SLOWLOG showing anything on the Redis server?

I see a large 72KiB inbound which would be a lot of tiny things you mentioned or something larger in play - I see it's an MGET, any idea how many are fetched at once, and what kind of volume/throughput you're seeing with these MGETs?

If you're able to see commands/sec, CPU, and bandwidth of the client or Redis server during this, all would help diagnose. Any chance you have some monitoring available?

**Comment by tinix0** [comment]
Its not happening around the same time. We have seen this at 2am, 12pm, 5pm, etc.
I've checked Slowlog, there were some queries however everything was under 1sec.
It should be 4 small keys. Two 64bit intereger a bool and an id serialized to string per request. Now that you mention it 72KB per MGET is way more than it should be. Are the inbounds per command or is it just current incoming buffer size and there could be other things at play?

I did check monitoring in azure, however there are no discernable anomalies, neither on the server or on the client. The cpu is stable around 50% on the redis server and bandwith was less than 10MB/s in both directions.

**Comment by NickCraver** [comment]
So it's for the total, but the qs: 0 in this case tells us it's for the 1 command. My best guess here is a much larger payload than we think is in play…is in play, on this connection. I'm not saying it's for sure the cause but it doesn't line up and warrants a check, certainly could be the issue.

Note though: SLOWLOG being near a second is an eternity, the threshold on it defaults to 10ms. I'm super curious what kind of command is taking nearly a second there. To set expectations: that'd tie for the highest stall I've ever seen on the Redis sever side.

**Comment by tinix0** [comment]
Regarding the slow log, I have misremembered, the worst that I saw is 20ms, however it is not from the timeframe of the timeouts on client side.

What is weird, is that I have checked the keys for the given command, and the keys that are being MGET are in total 79 Bytes, and there is no other place in the code that uses MGET. I also do not understand how can qs:0 since there are hundreds or requests timing out in a quick succession (under 1s). If we ignore this, the total buffer size the 72KB would be plausible since there are a lot of parallel requests that fetch different keys here.

**Comment by NickCraver** [comment]
Do you have other error messages along the way with different numbers, potentially trending up or down for the queue numbers we have here?

**Comment by tinix0** [comment]
Not really, only error messages from the given second when then requests fail and in those qs is always 0.

**Comment by NickCraver** [comment]
Sanity check: how are these multiplexers created? Do you have 1, or many?

**Comment by NickCraver** [comment]
@tinix0 Ah, so this error is for one of them - do you have errors from others? We're only seeing 1/10th of the contention picture here.

**Comment by tinix0** [comment]
I do, but they are not properly labeled so I cannot be 100% sure which is which, but since its round robin and there are hundreds of errors I am pretty sure it occurs on all of them. All the errors are mostly mostly the same 60-75KiB inbound, MGETs, qs=0. I saw a few with aw=true, bw Writing message and a few with next command= SELECT, but thats about it.

**Comment by NickCraver** [comment]
@tinix0 Are you using Envoy as a proxy type? It was added recently in the 2.5.43 release. I don't think it'd make a difference here necessarily, the main thing is: what's in that rather large payload? Is it doing a huge MGET?

**Comment by tinix0** [comment]
We are not. I will try it out on monday. I have checked the code and the keys in the cache and there is no reason it should be doing such a big MGET, unless there were multiple requests pipelined. Only MGET that the application is doing is the 4 small keys I have mentioned. There are many of them, but all are fixed size.

**Comment by tinix0** [comment]
I just wanted to update you, that it seems like the issues went away when we increased the number of executor from 5 (I was mistaken when I told you we had 10) to 10 so I will close this.
