### ISSUE TITLE
KeyExists for existing key returned false during high utilization

### ISSUE THREAD

**Issue by nmehlei** [StackExchange/StackExchange.Redis#205]
It seems to be possible (albeit rarely) that KeyExists returns an incorrect value either during connection problems or high utilization. 

In our case that occured yesterday, utilization was pretty high, which resulted in connection interruptions and KeyExists failed a few times with "No connection is available to service this operation" and when it finally succeeded it returned false which lead to heavy problems inside our application. 

Redis logs showed no problems (except client connects and disconnects etc.), especially no data loss, and our application has no way to remove this key (only change it), so I can pretty much rule out our side. Additionally, there are other open issues related to "No connection is available to service this operation", which makes it even more plausible.

**Comment by nmehlei** [comment]
The same situation happened again last night. Two attempts for KeyExists invocation resulted in

StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: EXISTS my:key:name

The third attempt returned with "false" although the Key does exist. Like last time, this happened during relatively high utilization which seems to be prerequisite for this issue to occur. There are no write operations for this key anywhere in the application, no way for Redis to delete it itself and Redis did not restart during this time, so I can guarantee that the key did have the correct value during this time.

**Comment by NickCraver** [comment]
Fixed in #279 :)
