### ISSUE TITLE
Seeking diagnosis for RedisTimeoutExceptions

### ISSUE THREAD

**Issue by BobbyMorris** [StackExchange/StackExchange.Redis#2053]
Any diagnosis to be gleaned from the following? Are we not using the multiplexer correctly (singleton `ConnectionMultiplexer`, transient `IDatabase`s)? When API requests start to fail in PROD around the cache it's in batches it seems - these will be grouped together in the same short timespans. ASP.NET 4.6.2. 

Timeout awaiting response (outbound=91808KiB, inbound=9KiB, 5157ms elapsed, timeout is 5000ms), command=GET, next: GET Order:101, inst: 0, qu: 21, qs: 0, aw: True, bw: Starting, rs: DequeueResult, ws: Writing, in: 65536, serverEndpoint: x-use-prod.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 9 of 10 available, clientName: wn0ldwk0000K0, IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=113,Free=8078,Min=200,Max=8191), v: 2.2.88.56325 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) 

Timeout awaiting response (outbound=28096KiB, inbound=10KiB, 5969ms elapsed, timeout is 5000ms), command=GET, next: GET orderList/201, inst: 0, qu: 2, qs: 0, aw: True, bw: Starting, rs: ReadAsync, ws: Writing, in: 65536, serverEndpoint: x-use-prod.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: wn0ldwk0000L0, IOCP: (Busy=1,Free=999,Min=50,Max=1000), WORKER: (Busy=220,Free=7971,Min=200,Max=8191), v: 2.2.88.56325 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) 

Timeout awaiting response (outbound=704KiB, inbound=6KiB, 7688ms elapsed, timeout is 5000ms), command=GET, next: MGET, inst: 0, qu: 0, qs: 0, aw: False, rs: ReadAsync, ws: Idle, in: 65536, serverEndpoint: x-use-prod.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: wn1ldwk0000K9, IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=192,Free=7999,Min=200,Max=8191), v: 2.2.88.56325 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) 

Timeout awaiting response (outbound=26950KiB, inbound=3KiB, 5734ms elapsed, timeout is 5000ms), command=GET, next: GET inventory/getAll, inst: 0, qu: 24, qs: 0, aw: True, bw: Starting, rs: ReadAsync, ws: Writing, in: 65536, serverEndpoint: x-use-prod.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: wn0ldwk0000K0, IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=161,Free=8030,Min=200,Max=8191), v: 2.2.88.56325 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) 

More info:

1. We have a particularly large string at a key with an expiry of an hour.
2. We have a wrapper over `StackExchange.Redis.IDatabase` called `ICache`. On that interface we have an `ICache.Get()` overload with a fallback where the implementation combines an `IDatabase.StringGet()`, executing some code if nothing at the key, and an `IDatabase.StringSet()`.
3. We have web requests from clients which fetch that particular key on their first launch and every 24 hours thereafter.

What happens with multiple requests that find that key is expired?
Our fallback our `ICache.Get()` overload uses, that action for that particular key takes a while. I would think it's quite possible multiple requests work on building up the value for that key simultaneously.
Would `IDatabase` prevent queueing up subsequent SETs again?
Does the write of that key need to finish or do subsequent calls for that key return the value in memory (locally not in the Redis instance) somewhere behind that `IDatabase` interface?
Do we need to break up that key given the timeouts and how we're using Redis?

**Comment by NickCraver** [comment]
> We have a particularly large string at a key with an expiry of an hour.

Can I get a more concrete idea of how large we're talking here? The queues I see are quite large (up to~ 30MB for only 2-24 commands). That seems like a very, very big value as I'm reading it currently.

There's a few suggestions I have here based on current info:
1. If there's a _huge_ key, use another connection for that, it's clogging your pipe pretty hadnily.
2. If there's a "cache cliff" on expirations, consider changing strategies here. What I've done many times is cache a value which itself has an expiration, and once it's past expiration and stale, _exactly 1_ thread goes to refresh the value. Picture a value with an expiration of 5 minutes (prop), stored in cache for say 10 minutes. If someone hits the value after 5 minutes, you _try_ to take a lock (we have methods for that) and if you get the lock, you kickoff a background thread to go refresh the value while everyone else gets the "stale" value for a few more seconds. This is extremely effective in stemming cache stampedes.
3. You an breakup the key, or change to a dedicated connection. If it's an immense 30MB I'd at the least offload to that new connection with a higher timeout, and with the cache stampede changes in point 2, it would be out of the line of fire.

Hope that helps, happy to clarify anything here or adjust advice if I've totally misunderstood. Either way: good luck!

**Comment by BobbyMorris** [comment]
Got a chance to look at this, so something like this for suggestion 2 @NickCraver ?

```
        private readonly IDatabase _cache;
        private readonly static ConcurrentDictionary<string, object> _lockDictionary
            = new ConcurrentDictionary<string, object>();
        public async Task<T> SynchronizedGetAsync<T>(string key, Func<Task<T>> fallbackAction, TimeSpan? timeout = null) where T : class
        {
            if (timeout == null || timeout <= TimeSpan.FromMinutes(-5))
            {
                return await GetAsync(key, fallbackAction, timeout).ConfigureAwait(false);
            }

            var preExpire = await _cache.StringGetAsync(key + "PreExpireKey").ConfigureAwait(false);
            if (!preExpire.IsNull)
            {
                return await GetAsync<T>(key).ConfigureAwait(false);
            }
            else
            {
                var lockObject = _lockDictionary.GetOrAdd(key, new object());
                bool acquiredLock = false;
                try
                {
                    Monitor.TryEnter(lockObject, ref acquiredLock);
                    if (acquiredLock)
                    {
                        await _cache.StringSetAsync(
                            key + "PreExpireKey", "notPreExpired", timeout.Value.Add(TimeSpan.FromMinutes(-5)))
                            .ConfigureAwait(false);
                        // actually could kick off a background thread to do this work, then
                        // just return the currently cached value
                        return await GetAsync(key, fallbackAction, timeout).ConfigureAwait(false);
                    }
                    else
                    {
                        return await GetAsync<T>(key).ConfigureAwait(false);
                    }
                }
                finally
                {
                    if (acquiredLock)
                    {
                        Monitor.Exit(lockObject);
                    }
                }
            }
        }
```

Still need to go lookup firing off background threads for the request that currently has to do the work above, but that should eliminate any possibility of multiple requests doing a redundant value store.

**Comment by NickCraver** [comment]
@BobbyMorris instead of 2 keys, the way we did this was like a `CacheWrapper<T>` inside your get methods, and that class was basically:
```cs
private class CacheWrapper<T>
{
    public DateTime ExpiresAt { get; set; }
    public T Value { get; set; }
}
```
Which simplifies your operations quite a bit - always get that single object, decide whether to kick off the background refresh thread based on that `ExpiresAt`. Much cheaper overall :)

**Comment by BobbyMorris** [comment]
@NickCraver Updated our hotfix for that, thanks. Guess I should close this issue.

**Comment by NickCraver** [comment]
@BobbyMorris glad you got it running!
