### ISSUE TITLE
StreamAddAsync Multi-key operations must involve a single slot; keys can use 'hash tags' 

### ISSUE THREAD

**Issue by Stan92** [StackExchange/StackExchange.Redis#2057]
Hi,
I have some troubles using transaction and streamAddAsync commands with a Redis Cluster

Currently I enqueue my commands like this.
```
 ITransaction transaction = RedisConnectionFactory.Database.CreateTransaction();
 foo = transaction.StreamAddAsync("stream{/term/1}/position",  "12345", r,1 flags: _flagWrite);
 foo = transaction.StreamAddAsync("stream{/term/1}/position",  "12345", r2, flags: _flagWrite);
 foo = transaction.StreamAddAsync("stream{/term/2}/position"  "12346", r3, flags: _flagWrite);
 bool isTransactionsOk = await transaction.ExecuteAsync();

```
And I get errors like this
StreamAddAsync Multi-key operations must involve a single slot; keys can use 'hash tags' 

I probably missed something about the hash keys notion and/or transactions.
Any help?

**Comment by slorello89** [comment]
Hi @Stan92, so it looks like you're trying to do the right thing in that you are using hashtags to ensure that your keys are on the same shard `stream{/term/1}/position`. 

However, your hashtags don't match, the first two:

```csharp
 foo = transaction.StreamAddAsync("stream{/term/1}/position",  "12345", r,1 flags: _flagWrite);
 foo = transaction.StreamAddAsync("stream{/term/1}/position",  "12345", r2, flags: _flagWrite);
```

are guaranteed to be on the same shard, therefore safe.

However:

```csharp
 foo = transaction.StreamAddAsync("stream{/term/2}/position"  "12346", r3, flags: _flagWrite);
```

carriers no such assurance, since `/term/2` != `/term/1`, if that third line was pointing to `/term/1`, the transaction should work.

**Comment by Stan92** [comment]
@slorello89 I thank you.. I got it.. :) after reading twice the error message.. 
OT : Is it bad to have several transaction instances at the same time?
I mean 
 ITransaction transaction0 = RedisConnectionFactory.Database.CreateTransaction();
 ITransaction transaction1 = RedisConnectionFactory.Database.CreateTransaction();
Even a  List or dictionary<string,ITransaction>
And execute them after ?
knowing my hash keys go from {term/0} to (term/9}

**Comment by Stan92** [comment]
Thanks to both of you
