### ISSUE TITLE
Pub/Sub OnMessage performance characteristics

### ISSUE THREAD

**Issue by JayJamieson** [StackExchange/StackExchange.Redis#2063]
Hi Team, 

Ive looked through past issues on `OnMessage` and `Subcribe("som_channel",  (channel, message) => {//...}` and the request for an signature.

The available `OnMessage(async (message) => {//...})` is suggested to be avoided for performance reasons. I want to know what kind of performance impact there is using this method and if there is an alternative that can be used?

Basically I want to forward messages from a sub to a WebSocket connect for live location tracking and notifications

```c#
multiplexer.GetSubscriber().Subscribe("<userid>.locations_events", (channel, message) => {
    await webSocket.SendAsync(
            new ArraySegment<byte>(buffer, 0, receiveResult.Count),
            receiveResult.MessageType,
            receiveResult.EndOfMessage,
            CancellationToken.None);
});
```

Alternatively I've thought about just creating an unbuffered Threading.Channel that my websocket work can try read messages from and have the subscription handler push messages onto that.

```c#
multiplexer.GetSubscriber().Subscribe("<userid>.locations_events", (channel, message) => {
     socketWork.channel.TryWrite(message);
});
```

Any suggestions about a better design or how StackOverflow uses websockets and `multiplexer.GetSubscriber().Subscribe`

**Comment by mgravell** [comment]
A ChannelMessageQueue (the thing with OnMessage) *is* an unbuffered
single-writer multi-reader channel (or a wrapper around one). One of the
main points here is that the legacy API was sync-only, where-as
ChannelMessageQueue allows proper async handlers. The ReadAsync / TryRead
on the API function just like the same in a channel. So: don't *add* an
extra channel: you already have one.

**Comment by JayJamieson** [comment]
> A ChannelMessageQueue (the thing with OnMessage) *is* an unbuffered single-writer multi-reader channel (or a wrapper around one). One of the main points here is that the legacy API was sync-only, where-as ChannelMessageQueue allows proper async handlers. The ReadAsync / TryRead on the API function just like the same in a channel. So: don't *add* an extra channel: you already have one.

Not sure I follow, are you suggesting that instead of adding a handler, just write a tight loop around `ReadAsync()/TryRead()`? in the websocket worker after calling `multiplexer.GetSubscriber().Subscribe("<userid>.locations_events")`?

If thats the case I still want to know the performance hits of `OnMessage()` as that wasn't as clear.

Cheers for the reply.

**Comment by mgravell** [comment]
Nit: if you're using `ReadAsync` (at least when `TryRead` fails), then: it isn't a tight loop. Performance impact is hugely contextual and scenario specific; the key point I was trying to emphasize: anything that demands `Action<....>` rather than `Func<..., [Value]Task>` is not going to be async friendly, and your webocket example used, IIRC, async.

**Comment by Lilk** [comment]
@mgravell will this enable concurrent processing messages if '_multiplexer.PreserveAsyncOrder = false' ?
Or will it process the message sequentially? What would be the best way to concurrency process messages with an async callback Func<..., [Value]Task> ? 

Thank you. very much in advance!
