### ISSUE TITLE
hash tag

### ISSUE THREAD

**Issue by jiangshangyizai** [StackExchange/StackExchange.Redis#2067]
How to solve the following exceptions:
![image](https://user-images.githubusercontent.com/103100959/161920210-8aa20f6f-7f3e-4320-8d15-6471e78d2b84.png)

I had a cluster，and now I had to use '{}' to process my key.

**Comment by NickCraver** [comment]
When operating on keys, they have to all be on the same server, for details see: https://redis.io/docs/reference/cluster-spec/#hash-tags
