### ISSUE TITLE
Azure Redis Performance Issues on Read/Write Operations in ASP.Net MVC

### ISSUE THREAD

**Issue by tsdev1** [StackExchange/StackExchange.Redis#2068]
Hi ,
I am using Azure Redis Cache Premium P2 Tier.
I have a requirement to store 10 lacs records (DataTable with 10 lacs rows and each row contains around 100 columns) into Redis Cache and I will have to retrieve those records as per need.
I am dividing this table into 20 rows and serializing 20 rows and saving that into one key which is around 8KB in size. This way I am generating around 50,000 Keys.

I need to read around 20,000 keys (~4lac rows) every time when I need to show the data into grid view.
I am managing the list of all the 50,000 keys into mem cache so I know which 20,000 keys I need to read when needed.
I am trying to read 20,000 Keys to collect all these data and it is taking around 2 minutes to complete read operations for 20,000 keys and that's too much. I am using StackExchange.Redis and also used Batch functionality. 

On #AzureRedis, It's showing P2 Tier can handle 350000 GET request per second for 1 KB.
Below is the code:

                public static void GetBatch(IDatabase cache, List<string> keys, ref DataSet ds)
                {
                    List<Task<RedisValue>> list = new List<Task<RedisValue>>(keys.Count);
                    var batch = cache.CreateBatch();
                    foreach (var key in keys)
                    {
                        var value = batch.StringGetAsync(key);
                        list.Add(value);
                    }
                    batch.Execute();

                    foreach (var item in list)
                    {
                        var result = item.Result;
                        if (result.HasValue)
                        {
                            var decompressedJsonData = GZipHelper.DecompressString(result);
                            var dtResult = JsonConvert.DeserializeObject<DataTable>(decompressedJsonData);
                            ds.Tables[0].Merge(dtResult);
                        }
                    }
                }

I am calling GetBatch method for each 1000 keys and my DataSet is getting prepared with 4lac records.

While setting the values into Cache Key, I am using below code which is taking around 10 minutes.

                    public static void SetBatch(IDatabase cache, Dictionary<string, DataTable> dict)
                    {
                            //set cache time
                            var expiresIn = TimeSpan.FromMinutes(KeyExpireTimeInMinutes);

                            IBatch batch = cache.CreateBatch();
                            List<Task<bool>> listTasksInBatch = new List<Task<bool>>();

                            foreach (var item in dict)
                            {
                                string key = item.Key;
                                DataTable dtProcess = item.Value;
                                //serialize item
                                var serializedItem = JsonConvert.SerializeObject(dtProcess);
                                // GZip serialized item
                                var compressedJsonData = GZipHelper.Zip(serializedItem);

                                var task = batch.StringSetAsync(key, compressedJsonData, expiresIn, flags: CommandFlags.FireAndForget);
                                listTasksInBatch.Add(task);
                            }
                            batch.Execute();
                            Task.WhenAll(listTasksInBatch.ToArray());
                    }

Suggest me a better approach for doing this.
Thanks

**Comment by NickCraver** [comment]
For this use case, I'm not kidding when I say "consider not caching it at all - go to the source". It seems like cache here is drastically over-complicating and over-costing you when a query against the original store is probably both faster and cheaper. On your caching (write) side you're calling a JSON serializer tens of thousands of times allocating those strings, that's going to be most of your time/CPU expensive. In reading you don't need to batch and can pipeline but...those are details. Overall, this isn't a good place to use Redis and you're probably better off directly against the original store.

**Comment by NickCraver** [comment]
Closing out to tidy up!
