### ISSUE TITLE
Unity3d reports error when accessing Redis database？

### ISSUE THREAD

**Issue by pystudy123** [StackExchange/StackExchange.Redis#2091]
Unity3d version: 2021.3.0f1c1  .net Standard 2.1

VS version: VS2022

Install StackExchange.Redis using NuGetForUnity

StackExchange.Redis version: 2.5.61

Code:
` private IDatabase db;
    void Start()
    {
        Debug.Log("Prepare to connect to redis");
        ConnectionMultiplexer _conn = ConnectionMultiplexer.Connect("127.0.0.1:6379,allowadmin=true,password=password01!");
        var database = _conn.GetDatabase(1);
        string str = database.StringGet("name");
        Debug.Log(str);
        
}`
Error message
> InvalidOperationException: The assembly for System.Runtime.CompilerServices.Unsafe could not be loaded; this usually means a missing assembly binding redirect - try checking this, and adding any that are missing; note that it is not always possible to add this redirects - for example 'azure functions v1'; it looks like you may need to use 'azure functions v2' for that - sorry, but that's out of our control
Pipelines.Sockets.Unofficial.Internal.Throw.InvalidOperation (System.String message) (at /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:16)
Pipelines.Sockets.Unofficial.Helpers.AssertDependencies () (at /_/src/Pipelines.Sockets.Unofficial/Helpers.cs:177)
Pipelines.Sockets.Unofficial.SocketConnection.AssertDependencies () (at /_/src/Pipelines.Sockets.Unofficial/SocketConnection.cs:121)
StackExchange.Redis.ConnectionMultiplexer.Connect (StackExchange.Redis.ConfigurationOptions configuration, System.IO.TextWriter log) (at /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:673)
StackExchange.Redis.ConnectionMultiplexer.Connect (System.String configuration, System.IO.TextWriter log) (at /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:654)
NewBehaviourScript.Start () (at Assets/Scenes/NewBehaviourScript.cs:13)

**Comment by NickCraver** [comment]
@pystudy123 As the error message indicates, this is usually a binding redirect issue with your application.

**Comment by NickCraver** [comment]
For anyone hitting this, written up a bit more here: https://nickcraver.com/blog/2020/02/11/binding-redirects/ - closing this out to tidy up!
