### ISSUE TITLE
RedisResult - method to get the Type

### ISSUE THREAD

**Issue by kilroytrout** [StackExchange/StackExchange.Redis#21]
Mark I've converted a BookSleeve project to SE.redis - so far so good. I use Lua scripts. One minor thing I ran into was a couple of my scripts return different types depending on inputs - e.g., a script that might return an int, null or byte[]. With BookSleeve's Eval, you could use is semantics - e.g., if (ret is Int64). With RedisResult, you wrap the returned object within the internals of the class with cast operators. So the only way I can distinguish is to cast and deal with InvalidCastException (although you do have an IsNull property). Would you consider adding some sort of Is(Type) function of something along those lines?

**Comment by NickCraver** [comment]
Added to the 2.x backlog

**Comment by mgravell** [comment]
Implemented in 2.0
