### ISSUE TITLE
Getting StackExchange.Redis.RedisTimeoutException frequently how to solve it?

### ISSUE THREAD

**Issue by jaya-rama** [StackExchange/StackExchange.Redis#2114]
Hi, 

I'm using Elastic cache  redis that aws provides and when I perform the below operation I'm getting TimeoutException after sometime can someone please help me to solve this attaching exception for reference 

_redis.KeyExists("cusID"+customerID) -> operation performed 

Exception has occurred: CLR/StackExchange.Redis.RedisTimeoutException
Exception thrown: 'StackExchange.Redis.RedisTimeoutException' in StackExchange.Redis.dll: 'Timeout performing EXISTS (5000ms), next: EXISTS cusID1, inst: 0, qu: 0, qs: 0, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: master.test-stage-test-new-jayaram3.mvg9d6.aps1.cache.amazonaws.com:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: JAYA-397(SE.Redis-v2.5.61.22961), IOCP: (Busy=0,Free=10000,Min=10000,Max=10000), WORKER: (Busy=2,Free=32765,Min=10000,Max=32767), POOL: (Threads=13,QueuedItems=0,CompletedItems=790), v: 2.5.61.22961 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)'
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1857
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 53
   at StackExchange.Redis.RedisDatabase.KeyExists(RedisKey key, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 667

**Comment by NickCraver** [comment]
It doesn't look like the client is busy here - recommend seeing what `SLOWLOG` yields if anything on the server end to see if something's happened here or possibly a failover has happened (for patching) on the AWS side.

**Comment by NickCraver** [comment]
If there's more info, happy to reopen here, closing to tidy up for now.
