### ISSUE TITLE
IIS RedisTimeoutException - huge load of GET commands

### ISSUE THREAD

**Issue by strejcradis** [StackExchange/StackExchange.Redis#2119]
Hi guys,

we are facing issues with using Redis Cluster. When huge amount of requests (around 200-300 HTTP requests per second on endpoint, it means around 200 - 300 GET commands to Redis). We have made a load test around 130k requests, for first XX thousands the Redis server responds normally, but after that it stops responding and timeouting. Server is hosted on our own, 3 nodes cluster.

We have tried to create testing Redis in Azure, but it also fails with same exception after some time.

The exception:
`StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), inst: 10, qu: 1, qs: 0, aw: False, bw: SpinningDown, serverEndpoint: XXXXXX.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: IIS001(SE.Redis-v2.5.61.22961), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=2,Free=32765,Min=2,Max=32767), POOL: (Threads=10,QueuedItems=0,CompletedItems=650), v: 2.5.61.22961`

Using .NET 5, using ConnectionMultiplexer initialized in singleton service, wrapped by the initialized Lazy instance for initialization.

Any tips what can cause the timeouts? Let me know if you need to know some addon informations, i will reply immediatelly.

Thanks!

**Comment by NickCraver** [comment]
Going by your counts and symptoms here, I'd guess that the multiplexer isn't being re-used and you're hitting socket exhaustion. You can see this by running `netstat` on the box in realtime. Overall: you want to be really sure it is indeed a singleton. The amount of item counts displayed in the error (650 complete) show that many multiplexers have likely been created exhausting your available ephemeral socket range.

But, what's really odd given your description is the `POOL: (Threads=10,QueuedItems=0,CompletedItems=650)`. This says only 650 things _total for the application_ completed, as in 650 `Task`-like operations. That's insanely low - I'd guess your entire app may be restarting more often than you're intending here - worth a look at system logs (e.g. Event Viewer) to see if IIS is restarting it for you after another issue.

**Comment by mgravell** [comment]
@NickCraver hey, random idea; should we track the number of muxer creations and add it to the exception info if it is over, say, 10?

**Comment by NickCraver** [comment]
@mgravell I was thinking about that, then dismissed it thinking "if the app is restarting, that's not going to tell us much" but I think you're right if we add one more data point: how long ago _this_ multiplexer was created - both could tell us a lot about scenarios - thoughts?

**Comment by mgravell** [comment]
yeah, I like that; how recent the multiplexer is can tell us a number of things; I can take that

**Comment by strejcradis** [comment]
Would be nice guys, thank you so much... 

We still have issues working with Redis in huge load, but now its not from IIS Windows App, but from some background worker.

Im not able to exactly determine the issue even if I went through some documentations, timeouts helper page and tried to determine the issue using your answers. Are you able to tell us what is still wrong? We are nearly sure that the connection is being reused now:

`Exception: Timeout awaiting response 
(outbound=56KiB, inbound=0KiB,7368ms elapsed, timeout is 5000ms), 
command=LPUSH, next: LPUSH mykey:mykey:mykey:success,
 inst: 0, qu: 0, qs: 93, aw: False, rs: ReadAsync, ws: Idle, in: 2650, in-pipe: 0, out-pipe: 0, serverEndpoint: xxx.xxx.xxx.xxx: 7000, mc: 1/1/0, 
 mgr: 10 of 10 available, clientName: some-kubernetes-service-574b8f5459-bk2ks, PerfCounterHelperkeyHashSlot: 11280, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=48,Free=32719,Min=4,Max=32767), 
 v: 2.2.50.36290 
(Please take a look at this article for some common client-side issues that can cause timeouts: https: //stackexchange.github.io/StackExchange.Redis/Timeouts)`


Thanks for your tips guys..

**Comment by NickCraver** [comment]
The `WORKER: (Busy=48,Free=32719,Min=4,Max=32767)` part of the message tells me that server is quite busy with workers likely hitting threadpool exhaustion. I'd recommend getting a memory dump when this happens to see what's eating all your threads and preventing other work from being taken care of.

**Comment by chengang-hub** [comment]
I am also getting TimeoutException:

StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), next: GET Identity:Session:1j8fP7Ai2ESGgEWcKOMN+pkk, inst: 3, qu: 0, qs: 10, aw: False, rs: ReadAsync, ws: Idle, in: 8384, in-pipe: 0, out-pipe: 0, serverEndpoint: , mgr: 9 of 10 available, clientName: yingkehuiyuan-5db544c847-t9vll, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=2963,Free=29804,Min=12402,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) | 
-- | --|
StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), next: GET Identity:Session:1j8fP7Ai2ESGgEWcKOMN+pkk, inst: 3, qu: 0, qs: 10, aw: False, rs: ReadAsync, ws: Idle, in: 8384, in-pipe: 0, out-pipe: 0, serverEndpoint: \, mgr: 9 of 10 available, clientName: yingkehuiyuan-5db544c847-t9vll, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=2980,Free=29787,Min=12402,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)  

StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), next: GET Identity:Session:1j8fP7Ai2ESGgEWcKOMN+pkk, inst: 3, qu: 0, qs: 10, aw: False, rs: ReadAsync, ws: Idle, in: 8384, in-pipe: 0, out-pipe: 0, serverEndpoint:  mgr: 9 of 10 available, clientName: yingkehuiyuan-5db544c847-t9vll, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3017,Free=29750,Min=12402,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) 

StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), next: GET Identity:Session:1j8fP7Ai2ESGgEWcKOMN+pkk, inst: 3, qu: 0, qs: 10, aw: False, rs: ReadAsync, ws: Idle, in: 8384, in-pipe: 0, out-pipe: 0, serverEndpoint: , mgr: 9 of 10 available, clientName: yingkehuiyuan-5db544c847-t9vll, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=2963,Free=29804,Min=12402,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

 StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), active: GET Identity:Session:5/+Moz+Oz0uXO3T19EYe6cxq, next: GET Identity:Session:9PnUYOgWoUCasxxR5e8Jtkt3, inst: 4, qu: 0, qs: 2, aw: False, rs: CompletePendingMessage, ws: Idle, in: 0, in-pipe: 4086, out-pipe: 0, serverEndpoint: , mgr: 7 of 10 available, clientName: yingkehuiyuan-5db544c847-t9vll, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1482,Free=31285,Min=12402,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
