### ISSUE TITLE
Redis 7 support 

### ISSUE THREAD

**Issue by baytekink** [StackExchange/StackExchange.Redis#2121]
Hi,
When do you think to support Redis 7.0 commands like EXPIRE key seconds [ NX | XX | GT | LT] ?

Thanks

**Comment by NickCraver** [comment]
You can see this progress in #2055 - [many of them are already added for the upcoming v2.6 release](https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes#unreleased) (at least 1-2 weeks out, I'd prefer not to release while traveling so we can quickly address any issues that arise).

**Comment by slorello89** [comment]
Specifically, this has already been done in #2083

**Comment by baytekink** [comment]
Where is the NX or XX parameters that we can pass to EXPIRE? I can not see it?

**Comment by NickCraver** [comment]
Thanks @slorello89 - closing out to tidy up!
