### ISSUE TITLE
Timeouts with backlog writer in 'Activating' state and steadily rising Queue-Awaiting-Write

### ISSUE THREAD

**Issue by polycirrus** [StackExchange/StackExchange.Redis#2126]
Hello, 

We have had several incidents of our application becoming unresponsive for long periods of time. During one of these incidents we've noticed the following pattern in timeout exceptions: 

| timestamp           | command | qu | qs | aw    | bw         | rs        | ws   | in | inPipe | outPipe | mc       | mgr              | iocpThreads                       | workerThreads                      |
|---------------------------|---------|----|----|-------|------------|-----------|------|-----|--------|---------|----------|------------------|-----------------------------------|------------------------------------|
| 4/18/2022, 4:37:04.404 PM | EXISTS  | 2  | 0  | FALSE | Activating | ReadAsync | Idle | 0   | 0      | 0       | 1/1/0 | 5 of 5 available | Busy=0,Free=1000,Min=500,Max=1000 | Busy=41,Free=8150,Min=500,Max=8191 |
| 4/18/2022, 4:38:31.721 PM | EXISTS  | 3  | 0  | FALSE | Activating | ReadAsync | Idle | 0   | 0      | 0       | 1/1/0 | 5 of 5 available | Busy=0,Free=1000,Min=500,Max=1000 | Busy=45,Free=8146,Min=500,Max=8191 |
| 4/18/2022, 4:39:32.574 PM | EXISTS  | 4  | 0  | FALSE | Activating | ReadAsync | Idle | 0   | 0      | 0       | 1/1/0 | 5 of 5 available | Busy=0,Free=1000,Min=500,Max=1000 | Busy=33,Free=8158,Min=500,Max=8191 |
| 4/18/2022, 4:39:50.346 PM | EXISTS  | 5  | 0  | FALSE | Activating | ReadAsync | Idle | 0   | 0      | 0       | 1/1/0 | 5 of 5 available | Busy=0,Free=1000,Min=500,Max=1000 | Busy=36,Free=8155,Min=500,Max=8191 |
| 4/18/2022, 4:41:12.212 PM | EXISTS  | 6  | 0  | FALSE | Activating | ReadAsync | Idle | 0   | 0      | 0       | 1/1/0 | 5 of 5 available | Busy=0,Free=1000,Min=500,Max=1000 | Busy=51,Free=8140,Min=500,Max=8191 |
| 4/18/2022, 4:41:40.747 PM | EXISTS  | 7  | 0  | FALSE | Activating | ReadAsync | Idle | 0   | 0      | 0       | 1/1/0 | 5 of 5 available | Busy=0,Free=1000,Min=500,Max=1000 | Busy=36,Free=8155,Min=500,Max=8191 |
| 4/18/2022, 4:41:59.857 PM | EXISTS  | 8  | 0  | FALSE | Activating | ReadAsync | Idle | 0   | 0      | 0       | 1/1/0 | 5 of 5 available | Busy=0,Free=1000,Min=500,Max=1000 | Busy=35,Free=8156,Min=500,Max=8191 |
| 4/18/2022, 4:42:31.681 PM | EXISTS  | 9  | 0  | FALSE | Activating | ReadAsync | Idle | 0   | 0      | 0       | 1/1/0 | 5 of 5 available | Busy=0,Free=1000,Min=500,Max=1000 | Busy=29,Free=8162,Min=500,Max=8191 |
| 4/18/2022, 4:43:55.162 PM | EXISTS  | 10 | 0  | FALSE | Activating | ReadAsync | Idle | 0   | 0      | 0       | 1/1/0 | 5 of 5 available | Busy=0,Free=1000,Min=500,Max=1000 | Busy=61,Free=8130,Min=500,Max=8191 |
| 4/18/2022, 4:47:11.469 PM | EXISTS  | 11 | 0  | FALSE | Activating | ReadAsync | Idle | 0   | 0      | 0       | 1/1/0 | 5 of 5 available | Busy=0,Free=1000,Min=500,Max=1000 | Busy=69,Free=8122,Min=500,Max=8191 |

And it goes on like that for over 100 more exceptions.

Although we weren't able to get a memory dump during this period, in a dump collected a few minutes after the application has seemingly recovered there are several backlog writer threads (probably one per multiplexer) all in 'SpinningDown' state waiting on the _backlogAutoReset event.

We are running version 2.5.43.42402 on .NET Framework 4.8. Server is Azure Cache for Redis C3 version 4.

I'm hoping you might suggest what could be causing this or how we could troubleshoot this further. Please let me know if there's any more information I can provide that would be helpful. Thanks.

**Comment by NickCraver** [comment]
It looks like consistently your app is overloaded with work on the thread pool given the last column there. Are you able to take a memory dump and see what's eating all available thread pool there when this happens?

**Comment by NickCraver** [comment]
Notes on what's happening above - closing this out to tidy up.
