### ISSUE TITLE
HttpClient from HttpClientFactory is faulty after call to offline Redis cache

### ISSUE THREAD

**Issue by pbfrederiksen** [StackExchange/StackExchange.Redis#2128]
I am using the Redis cache with the nuget package Microsoft.Extensions.Caching.StackExchangeRedis.
I made my cahce service so it would return null if the Redis cache database is offline.
But I experience some weird behavior: After a call to the offline Redis cache, my other service calls will fail with  this error:
`StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: HMGET IdentityModel.AspNetCore.AccessTokenManagement::TestClient::; UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.2.4.27433, mc: 1/1/0, mgr: 10 of 10 available, clientName: WSPEBOFR, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=2,Free=32765,Min=8,Max=32767), v: 2.2.4.27433`
and
`UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.2.4.27433`
This only happens if I use IHttpClientFactory to create a HttpClient - if I create a new HttpClient I have no problem of calling my services.
Here is a minimal example that has the problem:
Program.cs
`using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using TestRedisConnectionFault;

using IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices((_, services) =>
        services.AddLogging()
        .AddStackExchangeRedisCache(options =>
            {
                options.Configuration = "localhost:6379,password=Passw0rd,abortConnect=false";
            })
            .AddHttpClientsForExternalServices()
            .AddScoped<Cache.ICacheService, Cache.CacheService>())
    .Build();

using var serviceScope = host.Services.CreateScope();
var provider = serviceScope.ServiceProvider;

var cacheService = provider.GetService<Cache.ICacheService>();
var value = await cacheService.Get<string>("Dummy");

var httpClientFactory = provider.GetService<IHttpClientFactory>();

var httpClient = httpClientFactory.CreateClient("TestClient");
//httpClient = new HttpClient();
//httpClient.BaseAddress = new Uri("https://localhost:44333/");

try
{
    var response = await httpClient.SendAsync(new HttpRequestMessage(HttpMethod.Get, "api/v1/InternationalAppService/GetCarWashLocations"));
}
catch (Exception e)
{
    Console.WriteLine(e);
    throw;
}
`
HttpClientsExtension.cs:
`using IdentityModel.Client;
using Microsoft.Extensions.DependencyInjection;

namespace TestRedisConnectionFault;

public static class HttpClientsExtension
{
    public static IServiceCollection AddHttpClientsForExternalServices(this IServiceCollection services)
    {
        services.AddAccessTokenManagement((sp, options) =>
        {

            options.Client.Clients.Add("TestClient", new ClientCredentialsTokenRequest
            {
                Address = "https://localhost:8080/oauth2/v2.0/token",
                ClientId = "SECRET",
                ClientSecret = "SECRET",
                Scope = "SCOPE"
            });
        });

        services.AddHttpClient("TestClient", (sp, client) =>
        {
            client.BaseAddress = new Uri("https://localhost:44333/");
        }).AddClientAccessTokenHandler("TestClient");

        return services;
    }
}`

Cache.cs:
`using Microsoft.Extensions.Caching.Distributed;
using Newtonsoft.Json;

namespace TestRedisConnectionFault;

public class Cache
{
    public interface ICacheService
    {
        Task<T?> Get<T>(string key);
    }

    public class CacheService : ICacheService
    {
        private readonly IDistributedCache _cache;

        public CacheService(IDistributedCache cache)
        {
            _cache = cache;
        }

        public async Task<T?> Get<T>(string key)
        {
            try
            {
                var value = await _cache.GetStringAsync(key);
                return value != null ? JsonConvert.DeserializeObject<T>(value) : default;
            }
            catch (Exception e)
            {
                //We ignore the error because the service should not fail because of a faulty cache.
                return default;
            }
        }
    }
}`

Any idea of how to fix this?

Kind regards
Peter Bøtker Frederiksen

**Comment by mgravell** [comment]
SE.Redis has absolutely no interaction with HTTP, so this is odd; however, I notice the Initializing/NotStarted etc - how often / where are you connecting the multiplexer? if it is too often, then: bad things

**Comment by pbfrederiksen** [comment]
> 

The entire code is posted above.
I make 1 call to the Redis cache: await _cache.GetStringAsync(key);
This fails because I have turned of the Redis 6.2 alpine docker container in order to test that my code still functions without a cache. So I catch the exception and continue.
Then I get a HttpClient from httpClientFactory.CreateClient("TestClient");
I make 1 call: httpClient.SendAsync - which fails with the described error.
If I instead create a new HttpClient:
httpClient = new HttpClient();
httpClient.BaseAddress = new Uri("https://localhost:44333/");
I get no error.

So I don't have anything in my code where I do something with a multiplexer.

**Comment by pbfrederiksen** [comment]
I cannot reproduce the error any more. My computer has been restarted since - so maybe this weird behavior was resolved by restarting the computer.

**Comment by pbfrederiksen** [comment]
Sorry for the confusion - the weird behavior is still there.
When AccessTokenManagement is configured for the HttpClientFactory is configured, then the error happens - at one point I had removed the AccessTokenManagement configuration and then the error was gone - I thought it was because of a Windows restart - but that was not the case.

So the AddAccessTokenManagement and AddClientAccessTokenHandler configuration seems to enable the weird behavior:
`   

    public static IServiceCollection AddHttpClientsForExternalServices(this IServiceCollection services)
    {
        services.AddAccessTokenManagement((sp, options) =>
        {
            options.Client.Clients.Add("TestClient", new ClientCredentialsTokenRequest
            {
                Address = "localhost:8080",
                ClientId = "SECRET",
                ClientSecret = "SECRET",
                Scope = "SECRET"
            });
        });

        services.AddHttpClient("TestClient", (sp, client) =>
        {
            client.BaseAddress = new Uri("https://localhost:44333/");
        }).AddClientAccessTokenHandler("TestClient");

        return services;
    }
`

**Comment by pbfrederiksen** [comment]
I made a post in aspnetcore, where I found the reason and a workaround:
[Issue 41553](https://github.com/dotnet/aspnetcore/issues/41553)
