### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException

### ISSUE THREAD

**Issue by bentegtmeyer** [StackExchange/StackExchange.Redis#2130]
Using StackExchange.Redis version 2.5.61 with a .NET Framework 4.8 Web Project and Azure Cache for Redis I continually get the following error: 
`Timeout performing SET (10000ms), inst: 0, qu: 1, qs: 0, aw: False, bw: SpinningDown, rs: NotStarted, ws: Idle, in: 0, serverEndpoint: XXXX.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: XXXX(SE.Redis-v2.5.61.22961), IOCP: (Busy=2,Free=998,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=1,Max=32767), v: 2.5.61.22961 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

I have the following class setup as a singleton service to connect to redis and take/release locks:  

```
public class RedisClientService : IRedisClientService
    {
        private static Lazy<ConnectionMultiplexer> _redisConnection;

        public RedisClientService()
        {
            var redisConnectionString = ConfigurationManager.AppSettings["CacheConnection"];
            _redisConnection = new Lazy<ConnectionMultiplexer>(() => { return ConnectionMultiplexer.Connect(redisConnectionString); });
        }

        private static IDatabase RedisDatabase { get { return _redisConnection.Value.GetDatabase(); } }

        public bool LockTake(string value, TimeSpan timeout)
        {
            return RedisDatabase.LockTake(value, Environment.MachineName, timeout);
        }

        public bool LockRelease(string value)
        {
            return RedisDatabase.LockRelease(value, Environment.MachineName);
        }
    }
```
Use: 

```
if (_redisClientService.LockTake(lockKey, TimeSpan.FromMinutes(5)))
{
    //Some processing
    
    _redisClientService.LockRelease(lockKey);
}
```

I've tested locally and been able to successfully call the service to take and release a lock with no issue, however I get the exception above after deploying the code to a Basic SKU Azure App Service.  I've flushed the cache from the console in Azure to be sure nothing was set locally that may be effecting the code that has been deployed. I've tried increasing the timeout in the connection string by adding `syncTimeout=10000` to increase the timeout to 10000ms instead of the default 5000ms. I've also tried adding 
`<add key="aspnet:UseTaskFriendlySynchronizationContext" value="false" />` to my web.config that was suggested in another issue.  Any ideas on why this timeout may be occurring, but isn't reproducible locally?

**Comment by NickCraver** [comment]
The statuses in your error seem to indicate you're not successfully connecting to the Redis server at all - does that match your symptoms? You'll want to set `abortConnect=true` in your config to actually get an error when connecting rather than silent background retries (intended for when your service starts up before Azure Redis does in a deployment). I bet you'll see an issue connecting with that disabled - more config details here: https://stackexchange.github.io/StackExchange.Redis/Configuration

**Comment by bentegtmeyer** [comment]
@NickCraver Looks like it is a connection issue.  I'm not sure exactly where this is going wrong, as I can connect when testing locally, but in addition to the code provided above I have a key named `CacheConnection `added to the appSettings portion of my Web.config containing the Primary connection string as displayed under Access Keys in Azure Cache for Redis.  The only portion I've replaced from the auto-generated string is switching `abortConnect=true`, yet still getting an error:  
`It was not possible to connect to the redis server(s). There was an authentication failure; check that passwords (or client certificates) are configured correctly.`
