### ISSUE TITLE
Upgrade to .Net 6.0

### ISSUE THREAD

**Issue by charthick** [StackExchange/StackExchange.Redis#2132]
Looks like .Net 5.0 is ending its support by May 10. https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core 

Are there any efforts to move the [target](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/StackExchange.Redis.csproj#L6) to net6.0?

**Comment by NickCraver** [comment]
There are no plans to move the target, since that would break any downstream consumers and libs targeting net5.0 as well. Is there something specific you're looking for?

**Comment by NickCraver** [comment]
Closing this out to cleanup.
