### ISSUE TITLE
Creating 100K messages takes long time

### ISSUE THREAD

**Issue by wawaforya** [StackExchange/StackExchange.Redis#2134]
Profiling shows that the lib takes many time for creating large number of messages (like 100K with 25 chars per key in the sample code).  Does it expected?  Please let me know if there's any problem with my codes and if I misunderstood the meaning of fields in `ProfilingSession`.

Sample codes:
```csharp
static async Task Main(string[] args)
{
    var keys = Enumerable.Range(1, 100_000).Select(i => $"KEYS:{i,20}").ToList();
    var connection = await ConnectionMultiplexer.ConnectAsync("localhost");
    await connection.GetDatabase().PingAsync();

    foreach (int _ in Enumerable.Range(1, 10))
    {
        var profiler = new ProfilingSession();
        connection.RegisterProfiler(() => profiler);

        var sw = Stopwatch.StartNew();
        var database = connection.GetDatabase();
        var tasks = keys.Select(key => database.StringGetAsync(key));
        var results = await Task.WhenAll(tasks);
        sw.Stop();
        long elapsed = sw.ElapsedMilliseconds;

        var commands = profiler.FinishProfiling().ToList();
        var firstCreate = commands.Min(c => c.CommandCreated);
        var lastCreate = commands.Max(c => c.CommandCreated);
        var create = (lastCreate - firstCreate).TotalMilliseconds;
        var shortest = commands.Min(c => c.ElapsedTime).TotalMilliseconds;
        var longest = commands.Max(c => c.ElapsedTime).TotalMilliseconds;
        Console.WriteLine($"elapsed: {elapsed}, create: {create:F2}, min: {shortest:F2}, max: {longest:F2}");
    }

    Console.ReadKey(true);
}
```

Result on Intel Core i7-10850H CPU
```plaintext
elapsed: 296, create: 288.00, min: 0.10, max: 25.10
elapsed: 275, create: 268.78, min: 0.13, max: 20.70
elapsed: 284, create: 276.97, min: 0.11, max: 19.82
elapsed: 272, create: 266.96, min: 0.10, max: 17.86
elapsed: 268, create: 262.00, min: 0.10, max: 20.22
elapsed: 323, create: 317.97, min: 0.13, max: 23.39
elapsed: 258, create: 250.00, min: 0.10, max: 14.23
elapsed: 273, create: 267.80, min: 0.12, max: 25.29
elapsed: 314, create: 307.96, min: 0.14, max: 20.57
elapsed: 286, create: 279.00, min: 0.12, max: 19.59
```

Results on Intel Xeon Platinum 8259CL CPU, with lower frequency
```plaintext
elapsed: 2138, create: 2085.94, min: 30.16, max: 1167.28
elapsed: 894, create: 822.27, min: 29.00, max: 124.31
elapsed: 804, create: 717.78, min: 29.99, max: 213.75
elapsed: 1047, create: 971.69, min: 29.01, max: 394.96
elapsed: 1062, create: 932.61, min: 28.98, max: 222.75
elapsed: 887, create: 814.47, min: 30.58, max: 369.81
elapsed: 899, create: 749.02, min: 29.44, max: 248.60
elapsed: 1268, create: 1193.36, min: 28.83, max: 245.77
elapsed: 1122, create: 1043.95, min: 28.97, max: 594.75
elapsed: 1134, create: 1095.72, min: 28.95, max: 199.08
```

**Comment by mgravell** [comment]
Define "a long time" here; what would be "fast enough"?

Note that profiling will itself always add a little overhead; locally, with/without profiling I get (increasing the loop count a little):

``` txt
elapsed: 295, create: 287.89, min: 0.04, max: 11.07
elapsed: 325, create: 319.09, min: 0.04, max: 17.29
elapsed: 195, create: 190.83, min: 0.04, max: 25.31
elapsed: 195, create: 190.27, min: 0.05, max: 25.22
elapsed: 199, create: 195.60, min: 0.04, max: 29.55
elapsed: 192, create: 186.64, min: 0.05, max: 29.49
elapsed: 194, create: 189.95, min: 0.05, max: 46.14
elapsed: 165, create: 148.22, min: 0.04, max: 17.16
elapsed: 220, create: 216.40, min: 0.04, max: 22.27
elapsed: 178, create: 173.19, min: 0.04, max: 27.93
elapsed: 169, create: 164.37, min: 0.04, max: 13.87
elapsed: 211, create: 207.11, min: 0.04, max: 25.78
elapsed: 150, create: 146.60, min: 0.04, max: 15.00
elapsed: 183, create: 178.99, min: 0.05, max: 32.67
elapsed: 194, create: 189.96, min: 0.04, max: 26.19
elapsed: 202, create: 197.47, min: 0.06, max: 34.21
elapsed: 198, create: 192.57, min: 0.04, max: 30.56
elapsed: 186, create: 181.65, min: 0.05, max: 24.13
elapsed: 186, create: 181.50, min: 0.05, max: 25.05
elapsed: 230, create: 226.55, min: 0.03, max: 26.15
```

and 

``` txt
elapsed: 274
elapsed: 293
elapsed: 154
elapsed: 123
elapsed: 132
elapsed: 150
elapsed: 129
elapsed: 135
elapsed: 121
elapsed: 138
elapsed: 122
elapsed: 146
elapsed: 153
elapsed: 179
elapsed: 159
elapsed: 218
elapsed: 194
elapsed: 209
elapsed: 175
elapsed: 174
```

---

So; without profiling, that's frequently well over 600k ops/s. Keeping in mind that this is using a single connection, without any explicit batching: I'm not sure that's terrible. So: what performance number are you looking for here? And is your scenario amenable to any form of batching?

**Comment by wawaforya** [comment]
@mgravell, 600k ops/s is pretty awesome, while it's the benchmark on our dev machines, which could have 4.5GHz+ boost frequency normally.
The more normal cases on production would be 2.5GHz CPU, and per my tests, 100K keys would be 600ms+, which is less than 200k ops/s.
It's normal in our services that 100K+ GET commands to Redis in a single request, plus there are many timeout exception even with 10 connections in a ["least loaded pool"](https://github.com/StackExchange/StackExchange.Redis/issues/512).  Could you give some advice on our use case?  Thank you very much ;)

**Comment by NickCraver** [comment]
> It's normal in our services that 100K+ GET commands to Redis in a single request

This is an interesting comment because it seems like you'd be much better suited for fewer commands in an `MGET` - that's Marc's batching question above. On the surface, it seems like you'd want to take advantage of batching for your use case.

**Comment by mgravell** [comment]
Also: if your required throughput exceeds your available CPU and/or network capabilities: I'm not sure that's an library problem - that's more of a "don't under-provision your server" issue. `MGET` definitely seems the way to go here, though!

**Comment by NickCraver** [comment]
Going to close this out to tidy up but happy to expand if curious. Highly suggest `MGET` for your scenario, that's designed to remove a ton of meta work/cost from any Redis client/server interaction like this.
