### ISSUE TITLE
StringGetAsync returns RedisValue[] without Keys

### ISSUE THREAD

**Issue by murugappanm** [StackExchange/StackExchange.Redis#2139]
I was trying to get a batch of cached value from Redis and was able to do that by calling the StringGetAsync(RedisKey[] keys), but this returns RedisValue[]. Is there a way to get the Keys along with the response (like a KeyValuePair<TKey, TValue>[]). 

I assume we can do a work around by saving the key as part of the value and use that. But, was wondering if there are other standard ways to do this without adding extra payload.

Thanks.

**Comment by mgravell** [comment]
Basically: no, not currently. The MGET command doesn't return keys, and we
stay relatively close to the redis API. The results retain the order from
the request, so: whatever processing you need it should be trivial to do in
the calling code, where you already know the keys.

**Comment by murugappanm** [comment]
Thanks for such a quick response. One follow up question on that. But what if some of the values are missing in Redis. Do we get a null value at the corresponding indices in the array?

**Comment by NickCraver** [comment]
@murugappanm correct, the value will be `.IsNull == true`

**Comment by murugappanm** [comment]
Thank you @NickCraver and @mgravell .
