### ISSUE TITLE
Expiration value on StringSetAsync with KeyValuePair<RedisKey, RedisValue>[]

### ISSUE THREAD

**Issue by murugappanm** [StackExchange/StackExchange.Redis#2140]
Is there a way to provide the expiration time when we use the StringSetAsync with KeyValuePair<RedisKey, RedisValue>[] option to set multiple keys and values in the SE.Redis? 
I could see the option to set the expiration time on the StringSetAsync with just a single key and value.

**Comment by NickCraver** [comment]
There's no way to do this in a single command because MSET itself doesn't support it on the Redis side: https://redis.io/commands/mset/ At the moment, you're probably best off sending a lot of singular commands pipelined (e.g. only awaiting the last one).

**Comment by NickCraver** [comment]
Closing this out to tidy up!
