### ISSUE TITLE
Is it a bug in RedisValue?

### ISSUE THREAD

**Issue by Mutuduxf** [StackExchange/StackExchange.Redis#2144]
Hi guys, while reading the code I found in the class RedisValue.cs (https://github.com/StackExchange/StackExchange.Redis/blob/e74076de93/src/StackExchange.Redis/RedisValue.cs), there are two identical judgments "if (xType == StorageType.Null)" on lines 175 and 176, and the second judgment is never executed. Is the second judgment redundant? Or should it be "if (yType == StorageType.Null)" to match the original design?

**Comment by mgravell** [comment]
you weren't imagining things; thanks (fixed)
