### ISSUE TITLE
Is this command implemented?

### ISSUE THREAD

**Issue by wj8400684** [StackExchange/StackExchange.Redis#2147]
XREADGROUP GROUP group consumer [COUNT count] [BLOCK milliseconds] [NOACK] STREAMS key [key ...] id [id ...]

**Comment by slorello89** [comment]
@wj8400684 - XREAD groups is implemented by `StreamReadGroup`/`StreamReadGroupAsync`, however, the blocking aspect of this command is not possible at the moment given the architectural constraints of this library. 

I wrote an [article about stream basics](https://developer.redis.com/develop/dotnet/streams/stream-basics) for .NET devs. I also added tutorials for those who absolutely need blocking stream reads using ServiceStack.Redis (written by an old colleague of the authors of this library) and CSRedis, which is a resurrected .NET Redis library - both of which do support the blocking reads.

**Comment by wj8400684** [comment]
I looked at the source code of your framework. There is a request timeout mechanism. Is it because this can't be done?

**Comment by NickCraver** [comment]
The timeout version is blocking which currently isn't supported, but you could call it explicitly via `IDatabase.Exec()` (this isn't a simple operation). We're aiming to support blocking commands in the future (see #2055and #1961), but it's not a trivial thing and will take some time.

**Comment by wj8400684** [comment]
OK, thanks

**Comment by wj8400684** [comment]
Is it supported now?
