### ISSUE TITLE
Azure Redis Cache v6 response and client-side caching

### ISSUE THREAD

**Issue by ms92ita** [StackExchange/StackExchange.Redis#2148]
Hi,

from the v6 Redis feature I have noticed two considerable things:

1) Multi-threading
2) Client side caching

Since that sometimes I have timeouts regarding Azure Redis Cache response, I want to ask how new features in v6 speed up responses, since that multiple instances access the same Redis instance.

Also, for client-side caching, how does it work? In my application (asp.net), I am already using a similar approach with MemoryCache in front of Redis layer in order to overload as less as possible Redis. When I clean MemoryCache instance, application gets Redis value and save it in memory. These are basically data that would not change so much.
Also, I am using multiple databases (db0, db1 etc ...) and I am caching only some of them.

Now, I want to add in Redis other data what could change a lot more in the time and I must maintain multiple instances access. So, is client-side caching an automatic process that cleans local values when Redis value is updated or I must do clean / retrieve logic on my own?

**Comment by NickCraver** [comment]
Collapsing into #1461 for tracking - we've got the RESP3 bits in for the next release, next @mgravell is looking at some of the caching bits.
