### ISSUE TITLE
Key not expiring

### ISSUE THREAD

**Issue by Valdeminas** [StackExchange/StackExchange.Redis#2149]
Hi.

We are using Azure redis to rate limit requests.
This is done as follows:

On every request:
1. If key does not exist, it is created with expiry=rate limit rule period.
2. Key is incremented by one.

Above steps are all done in a transaction.

However, sometimes we notice issues, where a key is incremented well beyond it's intended expiry time (although it seems that it is not without expiration, since it also eventually expires).

I've read this: https://redis.io/docs/manual/keyspace-notifications/#timing-of-expired-events and since the key is incremented, but not expired after it's timeout, I'm thinking that maybe our incrementing transaction does not trigger Active expiration for the key?

So all of my other keys (which seem to work as intended) are expired passively?

Anyway, I'm attaching our transaction code, and maybe someone will help.

```
 public RedisCacheService(
            IConnectionMultiplexer cacheConnection)
        {
            _cacheConnection = cacheConnection;
            _cache = cacheConnection.GetDatabase();
        }

public async Task<long> IncrementAsync(string key, TimeSpan expiration)
        {
            var redisKey = new RedisKey(key);
            var tran = _cache.CreateTransaction();
            _ = tran.StringSetAsync(redisKey, 0, expiration, When.NotExists);
            var counterTask = tran.StringIncrementAsync(redisKey, 1);
            if (await tran.ExecuteAsync())
            {
                return await counterTask;
            }
            throw new InvalidOperationException($"Redis transaction failed.");
        }
```

**Comment by mgravell** [comment]
Curious; incr/decr/incrby do not change expiration (at least in vanilla redis, where I've just validated that) - and I agree you're setting expiration if

**Comment by Valdeminas** [comment]
Thanks for the response.

When you say: “server related” could you give an example of what you mean?

i.e. What sort of server processes could cause this?

Regarding Lua - thanks for the idea. Might try that.

One ither idea I had, is to “get key with expiry. If exists and expired, then delete” before running my increment transaction.

However, not knowing the reason behind this behaviour, it’s hard to say whether this would work. 🤔


I think I might just try logging the output of “get with expiry” and see what it shows for keys that display this non-expiring behaviour.

**Comment by mgravell** [comment]
All I mean is: it isn't the library that actually causes keys to become expired, it is the server. The commands you show *should* result in a key that expires. So: either some other command got executed that we can't see (perhaps a manual "set"), or the server failed to expire it. I can't say which.

Note: "if exists and expired" is an oxymoron. You shouldn't be able to detect a key as expired yet existing, unless the server is faulty, since expiry is checked when fetching values  - so even if the server hasn't spotted the expiration in the background, it will notice it *because you looked*, and will pretend it didn't find it.

**Comment by Valdeminas** [comment]
Gotcha.

Will try to investigate from the server side.

Thanks.

**Comment by Valdeminas** [comment]
@mgravell 

Just a quick update.

Rewrote our code to evaluate the following script

```
                                                    @"local current
                                                    current = redis.call('incr',@key)
                                                    if current == 1 then
                                                        redis.call('pexpire', @key, @timeout)
                                                    end
                                                    return current";
```

And the issue now seems to be fixed.
