### ISSUE TITLE
Not able to install 1.0.450

### ISSUE THREAD

**Issue by bencican** [StackExchange/StackExchange.Redis#215]
Visual Studio does not show the latest version and nuget console (version 2.8.50120.395) does not recognize it either. Same for both stock and StrongName variants.

![image](https://cloud.githubusercontent.com/assets/12614802/7819425/8e82817e-0396-11e5-9daa-09e1a2808032.png)

![image](https://cloud.githubusercontent.com/assets/12614802/7819819/270d9b98-0399-11e5-97d3-42394cced11b.png)

![image](https://cloud.githubusercontent.com/assets/12614802/7819389/515e361c-0396-11e5-9d47-555451f2c643.png)

**Comment by bencican** [comment]
Issue seems to be resolved now and the package can be installed with command line tools as well as the newest version appears when browsing from within Visual Studio.

**Comment by mgravell** [comment]
I think this was just nuget general fail - nothing package specific
