### ISSUE TITLE
我把程序部署在ubuntu上出现未指定端点

### ISSUE THREAD

**Issue by shuaidaipeng** [StackExchange/StackExchange.Redis#2151]
连接字符串192.168.1.9:6379;Unhandled exception. System.ArgumentException: No endpoints specified (Parameter 'configuration')
   at StackExchange.Redis.ConnectionMultiplexer.PrepareConfig(Object configuration, Boolean sentinel) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 939
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1061
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1036

**Comment by shuaidaipeng** [comment]
在windows上是正常的，在ubuntu上缺出现上面的错误
![Uploading Snipaste_2022-06-07_14-18-22.jpg…]()

**Comment by mgravell** [comment]
Can we see either the connection-string or the code you're using to create a `ConfigurationOptions` setup? Basically: *are there any endpoints?*

**Comment by shuaidaipeng** [comment]
> 我们可以看到连接字符串或您用于创建`ConfigurationOptions`设置的代码吗？基本上：_有端点吗？_

![image](https://user-images.githubusercontent.com/45552232/172313903-0dfbc48a-e005-4762-8794-befe0f5b8962.png)


public  RedisHelper(string connectionString, string instanceName, int defaultDB = 0)
        {
            //_connectionString = connectionString;
            //_instanceName = instanceName;
            _defaultDB = defaultDB;
            _connections = new ConcurrentDictionary<string, ConnectionMultiplexer>();
            Console.Write("开始连接");
            redis = ConnectionMultiplexer.Connect(connectionString);
            //redis = ConnectionMultiplexer.Connect("localhost");
            Console.Write("连接对象1111" + redis);
        }


appsettings.json 文件
  "Redis": {
    "Default": {
      "Connection": "192.168.1.9:6379",
      "InstanceName": "local",
      "DefaultDB": 0
    }
  },

startup 文件

//redis缓存
            var section = Configuration.GetSection("Redis:Default");
            //连接字符串
            string _connectionString = section.GetSection("Connection").Value;
            //实例名称
            string _instanceName = section.GetSection("InstanceName").Value;
            int _defaultDB = int.Parse(section.GetSection("DefaultDB").Value ?? "0");
            services.AddSingleton(new RedisHelper(_connectionString, _instanceName, _defaultDB));

![image](https://user-images.githubusercontent.com/45552232/172314252-6396ba7d-378e-4bc4-ab90-51e9d73812ef.png)

**Comment by shuaidaipeng** [comment]
我刚刚把传递的变量改成连接的字符串为localhost， 连接成功了。

**Comment by mgravell** [comment]
So what is the *actual value* of the `connectionString` variable, at runtime? Does it evaluate as `"192.168.1.9:6379"`?

**Comment by shuaidaipeng** [comment]
> 
对的，后面我好像也尝试的改成localhost:6379 、 192.168.1.9  好像都是失败的。
