### ISSUE TITLE
Unable to debug azure redis cache locally from azure function app - Timeout performing SETEX

### ISSUE THREAD

**Issue by mishmala** [StackExchange/StackExchange.Redis#2155]
I have created an azure function app locally and created azure redis cache under premium plan in azure portal. I am trying to get/set cache by debugging the function app locally. I have used StackExchange.Redis 2.5.61 version. When I am trying to access the cache, its failing with below error -

  {"Timeout performing SETEX (5000ms), inst: 0, qu: 1, qs: 0, aw: False, bw: SpinningDown, rs: NotStarted, ws: Idle, in: 0, 
serverEndpoint: test.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 
available, clientName:, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), 
WORKER: (Busy=1,Free=32766,Min=8,Max=32767), POOL: 
(Threads=16,QueuedItems=0,CompletedItems=803), v: 2.5.61.22961 (Please 
take a look at this article for some common client-side issues that can cause timeouts: 
https://stackexchange.github.io/StackExchange.Redis/Timeouts)"}

**Comment by NickCraver** [comment]
The error message indicates the reader never started, meaning we didn't finish connecting to the endpoint. Is your connection string ignoring connection errors? e.g. `abortConnect=false`? If so, remove that to get a better idea of what's erroring. Could be password, TLS protocols, or some other configuration mismatch in play as the most likely candidates.

**Comment by mm77777** [comment]
I have tried everything, even deploying the app in same region as cache,, but still same error. I am using premium redis cache. Please let me know if you have any other idea

**Comment by philon-msft** [comment]
That error message indicates that you're using a fairly old v2.0.601.3402 of the library - I'd highly recommend upgrading to 2.6.45+. 

Are you including `ssl=true` your connection string, and connecting from a client that supports TLS 1.2? See: 
https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-remove-tls-10-11
https://techcommunity.microsoft.com/t5/azure-paas-blog/azure-cache-for-redis-tls-versions/ba-p/1549630

**Comment by mm77777** [comment]
I started with the latest version and tried almost all versions.. I read downgrading from some other link so tried that..
With the latest version, I see just timeout.. like I said in my first comment..
 And,I did include ssl = true and sslprotocols = tls12, increased timeouts.. And, verified that function app is using tls 1.2. Nothing helped to fix that.. my function app and redis cache both are in same region.

**Comment by philon-msft** [comment]
It looks like public network access is disabled on your cache. You'll need to enable it with these instructions: https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-private-link#how-can-i-change-my-private-endpoint-to-be-disabled-or-enabled-from-public-network-access

**Comment by mm77777** [comment]
I did enable it here - it just gives message for a second - the update is in progress.. doesnt say if its actually enabled..
![Capture](https://user-images.githubusercontent.com/62717827/174691606-cf2ffeca-f528-4548-b551-b2c1a677c735.PNG)

**Comment by philon-msft** [comment]
I don't see the request to enable Public Network Access coming through for this cache, so you may be encountering a bug. I'll investigate more from the Azure side. 
Meanwhile, you have a couple options for getting unblocked: 
- Create a new cache with Public Network Access enabled from the start. You can always switch later to disable public access and connect via a Private Link instead. 
- Add a Private Link and connect through that

**Comment by mm77777** [comment]
I tried creating cache with public endpoint enabled from start or using the private link - I still get same error... 
![image](https://user-images.githubusercontent.com/62717827/174908838-95fafc38-5614-450a-b61f-898ec3f0a808.png)
Timeout performing SETEX (5000ms), inst: 0, qu: 1, qs: 0, aw: False, bw: SpinningDown, rs: NotStarted, ws: Initializing, in: 0, serverEndpoint: .redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: wn1mdwk0001KP(SE.Redis-v2.6.45.45955), IOCP: (Busy=0,Free=1000,Min=24,Max=1000), WORKER: (Busy=1,Free=32766,Min=24,Max=32767), POOL: (Threads=13,QueuedItems=0,CompletedItems=477), v: 2.6.45.45955 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)",
  "ExceptionType": "StackExchange.Redis.RedisTimeoutException",

**Comment by NickCraver** [comment]
There are a few more initial connection speed optimizations release in latest (2.6.70) but my read above is you can't connect _at all_ which still appears to be a network or configuration issue. Still, I wanted to pass along the library update piece because once your other blocker is resolved, this will connect much faster.

**Comment by NickCraver** [comment]
We've added more info to the exception here for relevant cases like this, but inability to connect in this one is a config issue, hope you were able to figure out network/hosting config here!
