### ISSUE TITLE
For the latest version 2.6.45, Redis in westus and eastus got timeout errors. 

### ISSUE THREAD

**Issue by zoeylan** [StackExchange/StackExchange.Redis#2157]
For the latest version 2.6.45, Redis in westus and eastus got timeout errors (from Azure web app to Azure Redis). All other redis in other regions are working fine. 
If we rolled back to the old version, the timeout issue was gone. Everything is working just fine.

If there are any updates for the library that could be related to the region issue? Thank you.

**Comment by NickCraver** [comment]
Do you have some example errors from what you were hitting? The error messages are meant to help us debug :)

**Comment by NickCraver** [comment]
Without more info, can't assist here - closing out to tidy up.
