### ISSUE TITLE
Simplest pub/sub example in the world is failing

### ISSUE THREAD

**Issue by LarryCalypso** [StackExchange/StackExchange.Redis#2159]
I am completely new to Redis and obviously Redis pub/sub.  I implemented an example.  I have redis instance running in a docker image in WLS2 so it's verified available at localhost:6379.  In VS2022 I created a simple console app.
I copied and slightly the example at:
https://www.thecodebuzz.com/redis-publish-subscribe-messages-redis-net-core-csharp/
I then run the console app in VS2022.  
The problem is that it executes the command "subScriber.Subscribe...", and doesn't wait for anything.  It just goes to the Console.WriteLine("Completed..." 
and the console app completes.
My newby-uninformed expectation would be that it would block (e.g., wait, await, pause, stay, stick, until a message is received in the "somechannel" channel).  That's the purpose of a subscription; sit and wait for something to arrive.  In this case, there isn't even a channel named "somechannel", so it should just sit and wait for some publisher to publish something onto "subchannel".
Instead, it just goes to the end and writes the "completed" message.  This expectation is so basic, I don't even know where to begin trying to figure out why it is "mis"-behaving this way.

using StackExchange.Redis;
using ConnectionMultiplexer redis =
ConnectionMultiplexer.Connect("localhost:6379");
ISubscriber subScriber = redis.GetSubscriber();

Console.WriteLine("started...");
subScriber.Subscribe("somechannel", (channel, message) =>
{
    //Output received message
    Console.WriteLine($"[{DateTime.Now:HH:mm:ss}]: {$"Message {message} received successfully"}");
});
Console.WriteLine("Completed...");

I will appreciate any guidance.  The solution has to be something really obvious, otherwise redis is broken, which I highly doubt.

**Comment by NickCraver** [comment]
Hey Larry! In short: that's not quite how subscriptions work for Redis - it's an event handler for all events coming in, observed for the lifetime of the multiplexer (same as your app, in this case). It's not waiting for a single thing, it's purely listening for all things on that channel/pattern. If you wanted to await something that completed in the subscription you could do that to observe one message and exit, you can do that, but that's a more narrow use of the mechanism. If you want to have things you _for sure_ observe, also consider looking at streams (https://redis.io/docs/manual/data-types/streams/) which we support, but not the blocking operations.

Here's an example script to illustrate waiting on a thing to fire:
```cs
async Task Main(string[] args)
{
    using ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost:6379");
    ISubscriber subScriber = redis.GetSubscriber();

    Console.WriteLine("Started...");
    var tcs = new TaskCompletionSource();
    subScriber.Subscribe("somechannel", (channel, message) =>
    {
        Console.WriteLine($"Message {message} received successfully");
        tcs.SetResult();
    });
    Console.WriteLine("Starting timer to fire in 5 seconds...");
    var t = new Timer((_) => subScriber.Publish("somechannel", "Heyyyyyy"), null, TimeSpan.FromSeconds(5), TimeSpan.Zero);
    await tcs.Task;
    Console.WriteLine("Exiting...");
}
```

**Comment by LarryCalypso** [comment]
Hi Nick, thank you for the push ahead.
I implemented your example and it works as long as you add the "using StackExchange.Redis;" to the top, make sure you have the NuGet package for StackExchange.Redis, and have a Redis service available at localost:6379 (which I did via a Docker container in WSL2).

After reviewing your code, I reworked my example into two different console projects within a VS solution, and set both of them as solution Startup Projects, so they both get started when I start the debugger.

One project is the publisher, one of the subscriber.

Project 1:  Subscriber:  (program.cs)
using StackExchange.Redis;
using ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost:6379");
ISubscriber subScriber = redis.GetSubscriber();
Console.WriteLine("Subscriber Started...");
subScriber.Subscribe("somechannel", (channel, message) =>
{
    Console.WriteLine($"Message {message} received successfully");
});
Console.ReadLine();

Project 2:  Publisher: (program.cs)
using StackExchange.Redis;
using ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost:6379");
ISubscriber subScriber = redis.GetSubscriber();
Console.WriteLine("Publisher Started...");
while (0==0)
{
    Console.WriteLine("Type a string to publish, and then press Enter");
    string sUserEnteredText = Console.ReadLine() ?? "";
    if (sUserEnteredText.Trim().Length > 0)
    {
        subScriber.Publish("somechannel", sUserEnteredText);
    }
}

When the solution is run, both console windows open; in the Publisher window, one you can type something, and it will appear in the other (Subscriber). I can take my work to the next step, however I do have these two observations, just in case you are able to offer clarification:

1.  What is purpose of TaskCompletionSource in your example?

2. Why am I using a class that has the name "Subscriber", as in:
ISubscriber subScriber = redis.GetSubscriber();
In order to perform a "Publish", as in:
subScriber.Publish("somechannel", sUserEnteredText); //seems unintuitive to have subScriber do a "Publish"
I was expecting some type of interface or class that would be called "GetPublisher", or "IPublisher".
I'll probably rename my class to indicate it is doing both, as in "ISubscriber redPubSub = redis.GetSubscriber();"
...or am I missing some other concept?
Thanks again.

**Comment by NickCraver** [comment]
Glad you got it going! For questions: 

1. It's a built-in .NET type that's just good for this example: something you can create, complete, and await.
2. Naming is hard - you can call it what you want :) Looks like you understand how it works, that's the important part!
