### ISSUE TITLE
IOCP、WORKER

### ISSUE THREAD

**Issue by ming2882** [StackExchange/StackExchange.Redis#2162]
If querying the current IOCP: (Busy=6,Free=994,Min=4,Max=1000),
WORKER: (Busy=3,Free=997,Min=4,Max=1000)

**Comment by mgravell** [comment]
I'm not sure how to interpret this. Context?

**Comment by ming2882** [comment]
Thanks for finding it, GetThreadPoolStats() in PerfCounterHelper.cs. My original intention is to know the working status of ConnectionMultiplexer and whether there is any abnormality. If ThreadPool.SetMinThreads() is not setting, there will be frequent timeout. After ThreadPool Status, we can know the current situation.
