### ISSUE TITLE
First chance exceptions being thrown 

### ISSUE THREAD

**Issue by Velpotta** [StackExchange/StackExchange.Redis#2163]
I'm using .NET 6 and Microsoft.Extensions.Caching.StackExchangeRedis 6.0.5 to connect with Redis (6.2.7) in K8s (1.22). Everything seems to be working just fine, however, upon taking a closer look I've noticed that a lot of first chance exceptions are being thrown:

System.Net.Sockets.SocketException (113): No route to host, at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59  

Configuration = "redis-cluster-0.x,redis-cluster-1.x,redis-cluster-2.x,redis-cluster-3.x,redis-cluster-4.x,redis-cluster-5.x,abortConnect=false,asyncTimeout=3000,password=*"

This seems to be related to Redis deployment. If deployed at same time as my code this happens, otherwise not.

Any help understanding what might be causing this and what I can do about it would be greatly appreciated!

**Comment by NickCraver** [comment]
This looks a network configuration error, the OS is telling us we can't reach at least one of those endpoints. I'd recommend pinging each from the box the client is running on and seeing what happens!

**Comment by Velpotta** [comment]
All the end points can be reached using Echo from the clients. I don't know if it's relevant but another thing that I noticed is that the exception rate is about the same regardless of load.

**Comment by Velpotta** [comment]
All (6) dns end points configured above can be reached using Echo from the client, however there are a couple of additional (6+3) IP-address end points known to the client which are not part of the active Redis cluster. Could they be the culprit I'm looking for? End point dump below:

Unspecified/redis-cluster-0.x:6379
Unspecified/redis-cluster-1.x:6379
Unspecified/redis-cluster-2.x:6379
Unspecified/redis-cluster-3.x:6379
Unspecified/redis-cluster-4.x:6379
Unspecified/redis-cluster-5.x:6379
10.208.4.14:6379
10.208.4.2:6379
10.208.4.7:6379
10.208.4.13:6379
10.208.4.4:6379
10.208.4.5:6379
10.208.4.16:6379
10.208.4.11:6379
10.208.4.15:6379

**Comment by NickCraver** [comment]
@Velpotta That'd be my guess, yes - looks like Redis is returning those to us when we check with `CLUSTER NODES` - you can query the same thing manually, details here: https://redis.io/commands/cluster-nodes/ If we're unable to reach them, we'd be seeing what you're seeing. If that is all happening the question is: what are those nodes?

**Comment by NickCraver** [comment]
Happy to reopen for follow-ups - closing out since there's nothing more to debug here for now.
