### ISSUE TITLE
Streams Transaction Issue

### ISSUE THREAD

**Issue by askoutaris** [StackExchange/StackExchange.Redis#2167]
All methods inside RedisDatabase.cs which call ExecuteAsync<T> with parameter 'T defaultValue' (eg StreamReadGroupAsync) does not work with transactions since there is no override ExecuteAsync<T> with parameter 'T defaultValue' in RedisTransaction.cs and as a result ExecuteAsync<T> of RedisBase.cs is used instead of  RedisTransaction.cs

FYI: I downloaded the code and managed it to work by adding the overriden methods shown in the attached screenshot.

![2022-06-21 17_49_48-RedisStreams - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/13051434/174829740-9db4227d-6754-4750-93c3-c903fa215720.png)

**Comment by mgravell** [comment]
agreed, this looks like a problem; do you have any concrete examples of failure cases here? honestly, the best thing is probably to submit this as a PR including tests

**Comment by askoutaris** [comment]
Thank you for your feedback!
I'll try to find some time in the next days to study and follow all Github's procedures about branching and PR policies in order to help you with that.
