### ISSUE TITLE
FIPS compliant 

### ISSUE THREAD

**Issue by icarmel** [StackExchange/StackExchange.Redis#2169]
Hi, 
I'd like to understand whether this library is FIPS complaint and how these requirements were verified. 
Appreciate any links on this. thanks 
https://csrc.nist.gov/publications/detail/fips/140/3/final

**Comment by mgravell** [comment]
I'm not sure this is something that anyone has, or indeed should, look into. We're not a cryptography provider, and until recently: redis itself didn't include any TLS commentary. We certainly *consume* cryptography providers when required, but we simply defer to `SslStream`, i.e. the platform intrinsic, which has [these remarks](https://docs.microsoft.com/en-us/dotnet/standard/security/fips-compliance) re FIPS compliance.

**Comment by NickCraver** [comment]
Closing this out to tidy up.
