### ISSUE TITLE
Difference between GetCounters().TotalOutstanding vs GetCounters().Interactive.TotalOutstanding in a Pool of IConnectionMultiplexer

### ISSUE THREAD

**Issue by danielpalacian** [StackExchange/StackExchange.Redis#2171]
I have in an MVC a piece of logic that tries to get the "least loaded" connection from a pool of Connections. 
And i was trying to figure out what is the best way to "measure" them. 

So can someone explain pls what is the difference between :

IConnectionMultiplexer.GetCounters().TotalOutstanding   ( Indicates the total number of outstanding items against this server)    vs  
IConnectionMultiplexer.GetCounters().Interactive.TotalOutstanding ( Indicates the total number of outstanding items against this connection) ? 

If i understand well first one .. is about the "server" and second one (Interactive) is about the "connection".

So the bellow example that i have found on other posts would be wrong, because it "measures" the server and not the individual connections. So it would offer the same value for all connections. Am i wrong? 

   private static IConnectionMultiplexer GetLeastLoadedConnection()
        {
            Lazy<IConnectionMultiplexer> lazyContext;

            var loadedLazys = lazyConnection.Where((lazy) => lazy.IsValueCreated);
            if (loadedLazys.Count() == lazyConnection.Count())
            {
                lazyContext = loadedLazys.OrderBy((lazy) => lazy.Value.GetCounters().TotalOutstanding).FirstOrDefault();
            }
            else
            {
                lazyContext = lazyConnection[loadedLazys.Count()];
            }

            return lazyContext.Value;
        }
Thx

**Comment by mgravell** [comment]
`TotalOutstanding` is defined as:

``` c#
public long TotalOutstanding => Interactive.TotalOutstanding + Subscription.TotalOutstanding + Other.TotalOutstanding;
```

If you're talking about regular operations such as `GET`, `SET`, etc - then the most relevant number for you is `Interactive.TotalOutstanding`

**Comment by NickCraver** [comment]
Closing this out to tidy since answered :)
