### ISSUE TITLE
Connecting to AWS Elastic Cache with Encryption enabled

### ISSUE THREAD

**Issue by Markjcp** [StackExchange/StackExchange.Redis#2172]
I am trying to connect to a AWS Redis with Encryption in transit and Encryption at rest (both enabled) and I can't get the right configurations.
I am trying this (this is a snippet to try to replicate):

```
#r "nuget: StackExchange.Redis, 2.6.45"

using StackExchange.Redis;

var options = ConfigurationOptions.Parse("gatewayhost:6379,ssl=True,sslprotocols=tls12);

options.User = "redis";

options.Password = "xxx";

options.AbortOnConnectFail = true;

var multiplexer = ConnectionMultiplexer.Connect(options);

Console.WriteLine(multiplexer.IsConnected)
```

I am getting errors, in the real code the error is:

`Error connecting the Redis database. Reason: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.`

**Comment by NickCraver** [comment]
In your .Connect() call, use the second argument to pass in a logger to get more detail about what's going on :)

**Comment by Markjcp** [comment]
I will close the issue because the problem was that we were using the wrong URL first and then we were using a username "redis" and AWS was expecting no username
