### ISSUE TITLE
Setting AbortConnectOnFail doesn't work for Redis Sentinel setups

### ISSUE THREAD

**Issue by pietervdheijden** [StackExchange/StackExchange.Redis#2173]
**Issue**
Setting AbortConnectOnFail doesn't work for Redis Sentinel setups.

**Details**
Setting `AbortConnectOnFail=false` works perfectly in Redis Master Slave setups. For example, this code:

```
// Startup.cs
var redisOptions = ConfigurationOptions.Parse("127.0.0.1:6379");
redisOptions.Password = "dev";
redisOptions.AbortOnConnectFail = false;
var redisConnection = ConnectionMultiplexer.Connect(redisOptions);
```

does not throw an exception when Redis is unavailable.

However, the setting does not work in Redis Sentinel setups. For example, this code:

```
// Startup.cs
var redisOptions = ConfigurationOptions.Parse("127.0.0.1:26379,serviceName=mymaster");
redisOptions.Password = "dev";
redisOptions.AbortOnConnectFail = false;
var redisConnection = ConnectionMultiplexer.Connect(redisOptions);
```

throws the following exception when Redis Sentinel is unavailable:

> Unhandled exception. StackExchange.Redis.RedisConnectionException: Sentinel: The ConnectionMultiplexer is not a Sentinel connection. Detected as: Standalone
   at StackExchange.Redis.ConnectionMultiplexer.GetSentinelMasterConnection(ConfigurationOptions config, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs:line 163
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 675

**Context**
I'm trying to set up the Redis configuration in Startup.cs to register Singleton IConnectionMultiplexer and to configure .NET's data protection library to persist keys in Redis:

```
services.AddSingleton<IConnectionMultiplexer>(_ => ConnectionMultiplexer.Connect(redisOptions));
services.AddDataProtection()
    .PersistKeysToStackExchangeRedis(ConnectionMultiplexer.Connect(redisOptions), "DataProtection-Keys");
```

When method `ConnectionMultiplexer.Connect(redisOptions)` throws an exception in the Startup.cs, the .NET application will abort. As a result, it's not possible to properly implement liveness and readiness (i.e. live = app is running, ready = app is running and all dependencies are available).

**Analysis**
I've tried to resolve this error myself, but unfortunately I didn't succeed... I think that the fix should be to move method `GetSentinelMasterConnection()` (see: [ConnectionMultiplexer.Sentinel.cs#L133-L135)](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs#L133-L135) into method `ReconfigureAsync()` (see: [ConnectionMultiplexer.cs#L1178-L1506](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/ConnectionMultiplexer.cs#L1178-L1506)). So, if the master node and/or the sentinel node are not available during startup, the connections will be regenerated during reconfiguration. Please let me know if I can assist in solving the issue!

**Comment by NickCraver** [comment]
I understand the issue here...but it's also not easy to fix. Since Redis is moving away from Sentinel and we always expect the control nodes to be responding, I think it's fair to say we're unlikely to support this scenario given the double-layer complexity it'd involve in making it work. Sentinel was always a but of a hack to make work in the first place so expanding on it isn't likely to happen given what I'm hearing about the future. You could _yourself_ wrap the ConnectionMultiplexer and keep trying the overall connection in a try/catch/loop fashion as a workaround would be my suggestion but in the core library this would be very complex (because it synchronously happens in flow, and handles downstream node changes on top of that).

Sorry that answer sucks, but trying to unblock at least!

**Comment by pietervdheijden** [comment]
@NickCraver Thanks for your reply!

Given that Redis is moving away from Sentinel, I guess I'd be better off spending my time to migrate to Redis Cluster (i.o. trying to make Sentinel work). Thanks for the heads-up and direction!

**Comment by NickCraver** [comment]
Going to tidy this one up - happy to re-open if there's a followup!
