### ISSUE TITLE
Message Access Modifier

### ISSUE THREAD

**Issue by shacharPash** [StackExchange/StackExchange.Redis#2179]
I'm writing a project and using StackExchange.Redis,
In my project I want to add support for commands that StackExchange.Redis does not currently support.
I tried to use the Message class to build my message to Redis, but Message Access Modifier is internal:
`internal abstract class Message : ICompletable`
 which means I can't use it.
I was thinking of changing the Access Modifier to public, to allow using the existing StackExchange.Redis commands and also add externally supported commands.
I'm happy to contribute a PR if you're interested in accepting this change.

**Comment by NickCraver** [comment]
The `Message` class is _very_ internal with many implementation details we do not want to expose or be bound to in a public API that we then can't break. It's not a modifier we'd want to change.

Which commands are you trying to support? Let's back up to the problem here and try to address that.

**Comment by mgravell** [comment]
In particular, note that there is the Execute API for ad-hoc unknown
commands, in particular custom "modules". This isn't quite as efficient as
a custom Message, but like Nick says: we'd want to understand the problem
before changing anything. If, for example, there's a genuine need for a
higher performance Execute (or similar): let's discuss *that*, but: it
probably won't be the Message type.

**Comment by NickCraver** [comment]
Closing this out to tidy up.
