### ISSUE TITLE
Cyclic performance degradation

### ISSUE THREAD

**Issue by pianoman4873** [StackExchange/StackExchange.Redis#2180]
Hello,
We're encountering a peculiar performance issue with the client that hopefully you could help with - 
It seems that once our apps hosting the Redis client  ( IIS running on .NET 5 ) are started,   the latency of the operations and performance is very good ( avg. latency less than 1 millisecond ), but slowly and steadily the latency of the commands ( seems to affect all of them ) increases till latency is unbearable ( tens of milliseconds ) and we restart the apps. After restart, everything performs great again and the cycle repeats approx. every 1.5 days.

We couldn't correlate this to anything concrete yet.
The client version used is  2.5.61 client version.

Any idea about what could be the reason ?
Any guidance and help for tracking this down would be appreciated.

Thanks

**Comment by NickCraver** [comment]
Have you run performance profiling or analyzed memory dumps when you're in the slow state? It sounds like _something_ is piling up and looking at a memory dump is likely one of your best paths to see what's stacked up.

**Comment by pianoman4873** [comment]
Hi , 
Yes - we've taken dumps and analyzed both memory and threads etc. but couldn't find any conspicuous culprit.
I have to note that the latency measurements are done with a DataDog agent which adds some overhead ( We saw its allocations in the memory dump ) but nothing meaningful that could explain this strange deterioration in performance.

The only interesting thing we could glean from the Datadog analysis was that there seems to be an increase in "contention time" ( which is defined as "The cumulated time spent by threads waiting on a lock" ) that correlates to the degraded performance. 
Any idea if this could somehow be related to the client or something else that indirectly affects the client's performance ?

**Comment by NickCraver** [comment]
If you have a memory dump of when it's happening, you can look at locks e.g. in windbg (e.g. `!locks`). I can't advise much beyond that here...really need to look at a dump and see what's locked. Dropping the dump in Visual Studio and looking at all threads or the Parallel Threads view may be super informative too, see where many are stuck.

**Comment by pianoman4873** [comment]
We found out that the culprit is actually DataDog :)
So closing this one. 
Thanks for the help.
