### ISSUE TITLE
Redis Timeout

### ISSUE THREAD

**Issue by chankly** [StackExchange/StackExchange.Redis#2185]
Hi,

I'm using StackExchangeRedis, Version=2.2.4 on my aspnet core app and I get many errors like the following:

![image](https://user-images.githubusercontent.com/42278768/178293914-a9b39419-aabd-4534-b4e8-0c184c5b2a70.png)

I don't understand what could be the problem. I see that there is no overload in the worker, 10 of 10 available.

In my program.cs I have put: ThreadPool.SetMinThreads(15, 15); desperately, but no luck.

**Comment by NickCraver** [comment]
I don't see anything wrong based on your error that stands out, but that's also a lot of code that's not our library...it is possible this is a fork of some sort?

**Comment by deleteLater** [comment]
Same problem here. My scenario: I am doing websocket load-testing using k6, and when I try to make 200,000 ws connections in 30s (qps = 200,000 / 30 = 6667) to the server(we need query some data in redis for every connection), timeout will happen because **worker threads are too busy**.

> StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5000ms elapsed, timeout is 5000ms), command=ZRANGEBYSCORE, next: ZRANGEBYSCORE inst: 0, qu: 60, qs: 0, aw: True, bw: WritingMessage, rs: ReadAsync, ws: Writing, in: 7004, serverEndpoint: you-can-guess, mc: 1/1/0, mgr: 10 of 10 available, clientName: ip-172-31-29-98(SE.Redis-v2.6.48.48654), PerfCounterHelperkeyHashSlot: 7276, IOCP: (Busy=0,Free=1000,Min=32,Max=1000), WORKER: **(Busy=53,Free=32714,Min=32,Max=32767)**, POOL: (Threads=53,QueuedItems=43545,CompletedItems=1421146), v: 2.6.48.48654 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by deleteLater** [comment]
I am also curious about **How StackOverflow Use StackExchange.Redis** , this timeout problem has been there many years. This didn't happen to StackOverflow ever? How StackOverflow avoid this problem? How you think about this problem? I think this can be written a good article. @NickCraver @mgravell

**Comment by chankly** [comment]
> I don't see anything wrong based on your error that stands out, but that's also a lot of code that's not our library...it is possible this is a fork of some sort?

We use the library as is, only through our own class. The normal...

I'm not an expert, I was hoping that someone with more experience seeing that error message would know what could be causing it...

**Comment by NickCraver** [comment]
@deleteLater We didn't have timeouts like you're seeing at Stack, not that we had zero but almost all of the timeout cases here are specific to a user's environment: keys being too large, threads being exhausted, CPU maxed out, server stalled, etc. A timeout means something _in the grand scheme of everything_ took too long - that could be _anywhere_.

For your case I'd recommend checking `SLOWLOG` and overall thread pool health on the client side. My top guesses would be your client is maxed out on CPU/thread pool locally, or you have a server-side stall. Given that the backlog writer is active here, it looks like you're doing more work than the CPU can handle.

**Comment by NickCraver** [comment]
Closing this out to tidy up - if there's still confusion happy to re-open :)
