### ISSUE TITLE
Internal thread pool on .NET 6

### ISSUE THREAD

**Issue by epeshk** [StackExchange/StackExchange.Redis#2187]
Looks like that internal thread pool for SocketManager was disabled in https://github.com/StackExchange/StackExchange.Redis/commit/239e34591df21af2b329bef902592fb6e9608945, but there is no assembly for .NET 6 target in NuGet package.

0. Is it my mistake and this change is already in the release?
1. Is this an experimental change that is not intentionally shipped or is it just a NuGet packaging bug?
2. Would `Environment.Version` check at runtime be better than conditional compilation for this case? At the time this change goes into production, of course.

**Comment by NickCraver** [comment]
The net6.0 target was indeed intentionally removed, but left in code to help the .NET team repro our results and make suggestions - see #1992 for context :)

**Comment by epeshk** [comment]
@NickCraver, thanks for the clarification!
