### ISSUE TITLE
Redis Cluster ConnectTimeout issue

### ISSUE THREAD

**Issue by sirbadger** [StackExchange/StackExchange.Redis#219]
We're running a 12 instance cluster across 2 machines and passing in 3 of the endpoints on each machine into ConfigurationOptions.EndPoints.  When one of the machines is down ConnectionMuliplexer.Connect takes over 4 minutes even though all the masters have been moved to the 1 remaining hosts... is this expected behaviour?

**Comment by NickCraver** [comment]
Are you still seeing this in a current build? If so we'll need to dig deeper - hopefully one of the many connection fixes between this issue and now resolved it though.

**Comment by sirbadger** [comment]
Will setup an environment to test with the latest nuget version.

On a related note, should we receive MOVED exceptions once it has reconnected?

**Comment by NickCraver** [comment]
@sirbadger this was a separate issue, which should be resolved in current code - we'll get a build out in the next week or so with a few fixes.
