### ISSUE TITLE
Subscription always fails to receive messages

### ISSUE THREAD

**Issue by rzong** [StackExchange/StackExchange.Redis#2192]
Jedis release using java under Linux, redis version 4.0.8, and stackexchange in windows Redis subscribes, but never receives messages, but publishes them by itself, and you can receive them by subscribing by yourself

**Comment by mgravell** [comment]
Any example code? Is this cluster or standalone? Any relevant config info (like remapped/disabled commands)?

**Comment by mgravell** [comment]
(I ask because subscriptions generally work, so I'm guessing there's something context-specific in play here)

**Comment by NickCraver** [comment]
If there's more info here, happy to re-open, but we can't do anything with more info :)
