### ISSUE TITLE
Sentinel support

### ISSUE THREAD

**Issue by mcolussi** [StackExchange/StackExchange.Redis#22]
Just a reminder to port the Sentinel code from Booksleeve to StackExchange.Redis.  

ConfigurationOptions allows you to specify the Sentinel ServiceName, but connecting to a Sentinel doesn't work:

```
SENTINEL_IP:26379,serviceName=mymaster,keepAlive=5,syncTimeout=1000,allowAdmin=True,connectTimeout=5000,abortConnect=False
1 unique nodes specified
Requesting tie-break from SENTINEL_IP:26379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
SENTINEL_IP:26379 faulted: ProtocolFailure on PING
SENTINEL_IP:26379 failed to nominate (Faulted)
> UnableToResolvePhysicalConnection on GET
No masters detected
SENTINEL_IP:26379: Sentinel v2.8.4, master; keep-alive: 00:00:05; int: Disconnected; sub: Connecting; not in use: DidNotRespond
SENTINEL_IP:26379: int ops=5, qu=0, qs=0, qc=0, wr=0, sync=5, socks=1; sub ops=2, qu=0, qs=0, qc=0, wr=0, sync=2, socks=2
Circular op-count snapshot; int: 0+5=5 (0.50 ops/s; spans 10s); sub: 0+2=2 (0.20 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Starting heartbeat...
ConfigurationChanged endpoint: SENTINEL_IP:26379
ConnectionFailed endpoint: SENTINEL_IP:26379, exception: ProtocolFailure on SENTINEL_IP:26379/Interactive, input-buffer: 663, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 5
s, pending: 0, state: ConnectedEstablishing, last-heartbeat: never, last-mbeat: 0s ago, global: 0s ago
```

**Comment by Buckers81** [comment]
mgravell - if you don't use sentinel, what is your strategy for handling redis failures?

**Comment by mgravell** [comment]
We have master/slave/slave/slave for limited recovery. At the moment actual
failover is largely manual and human. We're looking to make this smarter
when "cluster" is viable for us.

Does that help?

**Comment by Buckers81** [comment]
Interesting. We've found sentinel and automatic recovery a right PITA. Also looking forward to cluster if it helps with this.

**Comment by CamW** [comment]
Had a stab at this since we needed it and submitted a PR here https://github.com/StackExchange/StackExchange.Redis/pull/121 if you already have a plan for an implementation from booksleeve this probably won't be in line with that but let me know what you think or if I can help.

**Comment by sdebnath** [comment]
@mgravell bump

**Comment by cjb5790** [comment]
@mgravell Any update on this?

**Comment by mylesjj** [comment]
@mgravell Any news on this?

**Comment by sreefubs** [comment]
@mgravell Is Sentinel support there in StackExchange.Redis now ?

**Comment by chester89** [comment]
@sreefubs I believe there's a comment on some issue saying "it works in
most cases" or something like that

2016-01-08 10:28 GMT+03:00 sreefubs <notifications@github.com>:

> @mgravell <https://github.com/mgravell> Is Sentinel support there in
> StackExchange.Redis now ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/22#issuecomment-169917459>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by sreefubs** [comment]
@chester89 I’m new to Redis and we’re analyzing the tool for a specific requirement which needs High-Availability & Consistency.

Environment Details: 
Redis Server(Windows OS) : v2.8.2104 https://github.com/MSOpenTech/redis
.Net SDK                              : https://github.com/StackExchange/StackExchange.Redis
Cluster Setup                       : 1 Master & 3 Slaves & 3 Sentinels.

Test Scenario :
While iterating Redis SET command from .Net client thro StackExchange.Redis SDK, I'm crashing redis-master node.

Once Redis Sentinel elects new master (one of the slaves), now how will my application get updated about the new redis master IP?

**Comment by chester89** [comment]
If I'm not mistaken, there's a PR that addresses your problem:
https://github.com/StackExchange/StackExchange.Redis/pull/121
It's out of date, I believe, but the code does just that - it sets up a
cluster, shuts down current master and waits to see if the switch occurs

2016-01-08 15:16 GMT+03:00 sreefubs <notifications@github.com>:

> @chester89 <https://github.com/chester89> I’m new to Redis and we’re
> analyzing the tool for a specific requirement which needs High-Availability
> & Consistency.
>
> Environment Details:
> Redis Server(Windows OS) : v2.8.2104 https://github.com/MSOpenTech/redis
> .Net SDK : https://github.com/StackExchange/StackExchange.Redis
> Cluster Setup : 1 Master & 3 Slaves & 3 Sentinels.
>
> Test Scenario :
> While iterating Redis SET command from .Net client thro
> StackExchange.Redis SDK, I'm crashing redis-master node.
>
> Once Redis Sentinel elects new master (one of the slaves), now how will my
> application get updated about the new redis master IP?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/22#issuecomment-169983278>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by aishelm** [comment]
Marc, I have a question related to this topic: should the sentinels be registered as hosts along with the redis servers in the configuration?
If the answer is NO, would it be different in the future when we improve coverage for sentinel beyond what currently exists?

**Comment by aaronmell** [comment]
@mgravell @NickCraver  So the company I work for is paying me to implement sentinel support. Its a feature we really want, we don't want to switch clients to get it, and we can't wait for the feature to be added by someone else. I can follow the thread here and the current thoughts on implementation. Any other guidance or information you could provide that could help make this successful would be appreciated as I would prefer not to maintain a fork of the project long term.

**Comment by ajwharton** [comment]
@aaronmell IIRC sentinel support is in the Java SDK. If so, starting there and doing a port would be a thing.

**Comment by mgravell** [comment]
Since I don't use sentinel routinely, I simply don't know enough about it
*as it currently exists* to define what it needs to do. My naive assumption
is that *simple* usage should just list a sentinel node or nodes in the
config string, and a service name, and the connect API should just figure
everything out. For *that* it should just need some hacks (big or small) to
the connect code - and as long as the different connections are correctly
marked, it *should* all work.

As for what *additional* APIs should be used: don't know!

Any use?

Marc

On 29 March 2016 at 16:18, Aaron Mell <notifications@github.com> wrote:

> @mgravell <https://github.com/mgravell> @NickCraver
> <https://github.com/NickCraver> So the company I work for is paying me to
> implement sentinel support. Its a feature we really want, we don't want to
> switch clients to get it, and we can't wait for the feature to be added by
> someone else. I can follow the thread here and the current thoughts on
> implementation. Any other guidance or information you could provide that
> could help make this successful would be appreciated as I would prefer not
> to maintain a fork of the project long term.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/22#issuecomment-202949046>
>



-- 
Regards,

Marc

**Comment by aaronmell** [comment]
@mgravell  That helps. I dug into the code in the connection multiplexer and I think I have an idea about how to approach it.

**Comment by Areson** [comment]
Any movement on this? I'm also in need of a Sentinel implementation. I've rolled my own changes for it into the ConnectionMultiplexer, but I wanted to hold on pushing it out if folks already had something that was forthcoming.

**Comment by aaronmell** [comment]
Sorry, i ended up going the same route

**Comment by Areson** [comment]
Quick design question since I'm on the subject at the moment: Is there an overwhelming preference on how should be handled? I noticed that PR #121 handled it by having two ConnectionMultiplexers, one for the Sentinel connection, which was passed off to a second ConnectionMultiplexer as a configuration option. I riffed on that a bit but preferred not to directly handle two connections, instead having the ConnectionMultiplexer recognize that it was connecting to Sentinel(s) and internally create a second, managed, ConnectionMultiplexer that could be accessed via a property, ala:

```C#
ConfigurationOptions sentinelConfig = new ConfigurationOptions();
sentinelConfig.ServiceName = "MyServiceName";
sentinelConfig.EndPoints.Add("127.0.0.1", 26379);
sentinelConfig.EndPoints.Add("127.0.0.2", 26379);
sentinelConfig.TieBreaker = "";
sentinelConfig.CommandMap = CommandMap.Sentinel;

// Need Version 3.0 for the INFO command?
sentinelConfig.DefaultVersion = new Version(3, 0);

// Create config options for connection to the master
ConfigurationOptions masterConfig = new ConfigurationOptions();

sentinelConfig.SentinelMasterConfigurationOptions = masterConfig

// Connect!
ConnectionMultiplexer sentinelConnection = ConnectionMultiplexer.Connect(sentinelConfig);
ConnectionMultiplexer masterConnection = sentinelConnection.SentinelMasterConnection;
```

Another route would be to recognize that we are connecting to Sentinel(s) and internally create the connection to the master and pass that back instead, sidestepping having two ConnectionMultiplexer objects exposed to the end user:

```C#
// Same setup as before goes here

// Connect!
// We directly get back the ConnectionMultiplexer for the masters and the Sentinel connection
// is internally managed for us
ConnectionMultiplexer masterConnection = ConnectionMultiplexer.Connect(sentinelConfig);
```

Thoughts and/or preferences?

**Comment by Areson** [comment]
Also, see PR #406 for more details.

**Comment by CamW** [comment]
@Areson I may be wrong but it looks like you're considering it a foregone conclusion that someone using the client to connect to a sentinel also wants to connect to the dictionary server with that sentinel's advice, this isn't necessarily the case. One may just want to interact with the sentinel alone. Perhaps consider a method or config option to indicate that the master server advised by the sentinel server should be connected to.

**Comment by Areson** [comment]
@CamW I'd say that's a fair assessment. I'm a fairly recent user of Redis, so I have a pretty narrow use case that I am working with. It would be easy enough to have it forgo connecting to the master. What about something like this:

```C#
ConfigurationOptions sentinelConfig = new ConfigurationOptions();
// Don't specify a ServiceName when connecting to the Sentinel, as it can have
// several masters that it monitors
//sentinelConfig.ServiceName = "MyServiceName";
sentinelConfig.EndPoints.Add("127.0.0.1", 26379);
sentinelConfig.EndPoints.Add("127.0.0.2", 26379);
sentinelConfig.TieBreaker = "";
sentinelConfig.CommandMap = CommandMap.Sentinel;

ConnectionMultiplexer sentinelConnection = ConnectionMultiplexer.Connect(sentinelConfig);

// Get a managed connection to a master when I want it
ConnectionOptions masterConfig = new ConfigurationOptions();
// Specify the service name of the master I want to connect to
masterConfig.ServiceName = "MyServiceName";
ConnectionMultiplexer masterConnection = ConnectionMultiplexer.Connect(masterConfig, sentinelConnection);
```

Though I suppose at this point it could simply take the same approach your PR did and pass the Sentinel connection as a config option. I did nab a few bits of code from your PR (thanks!) so switching it back to that approach would be pretty straightforward.

On the other note, @mgravell has been committing PRs very recently, so I don't think that we are dead in the water. It may simply be that he felt like the effort had stalled and wasn't contributing any attention to it. We'll have to see if and what he says. I know my perception based on this thread and #121 was that things hadn't quite gotten resolved and then died out.

**Comment by aaronmell** [comment]
The approach I took in my code, was to treat them separately. I go to sentinel and get the configuration for redis. Then I hook up to the events that a slave has failed over to a master. When that happens, I reset my Multiplexer

**Comment by Areson** [comment]
That's certainly an option. I wanted more of the leg work to be done behind of the scenes so that if I asked for a master from a Sentinel connection that what I got would be governed automatically without needing me to setup any special event handling myself. Though perhaps I'm misinterpreting the approach you mentioned?

**Comment by moxplod** [comment]
Any ideas on when this is likely to be merged?

**Comment by moxplod** [comment]
Next best thing - Does anyone has a fork of this that has sentinel support  :)

**Comment by Areson** [comment]
@moxplod Yes. See #406 for the pull request from my fork.

**Comment by lexxdark** [comment]
Hey, I have just created a pull request updating the sentinel support, for your consideration. Pull request #692

**Comment by NickCraver** [comment]
Tracking this in #692 now - we were really hoping the community who's more familiar with Sentinel behavior could help us out there, but no luck thus far. It's really all we're lacking to merge Sentinel support in. Regardless - collapsing into #692 so all discussion happens on the PR.
