### ISSUE TITLE
Better handling for cases when Redis is "there" but Loading dataset into memory

### ISSUE THREAD

**Issue by nmehlei** [StackExchange/StackExchange.Redis#220]
Our application just threw massive amounts of exceptions for "No connection is available to service this operation" and "InvalidOperationException: Queue empty.

```
RedisConnection InternalError: System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.Dequeue()
   at StackExchange.Redis.PhysicalConnection.MatchResult(RawResult result) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 810
   at StackExchange.Redis.PhysicalConnection.ProcessBuffer(Byte[] underlying, Int32& offset, Int32& count) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 853
   at StackExchange.Redis.PhysicalConnection.ProcessReadBytes(Int32 bytesRead) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 877
   at StackExchange.Redis.PhysicalConnection.StackExchange.Redis.ISocketCallback.Read() in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 903
```

After taking a look at redis, it seems to have just restarted, so it was busy loading its dataset into memory (big dataset, so takes a while to load). While "No connection is available to service this operation" does in a way make sense here, Queue empty is very unhelpful. 
This should be optimized. As loading the dataset is expected behavior, one might even argue that a hint to that might be useful in the exception message.

**Comment by mgravell** [comment]
Valid complaint, yes; will need to investigate options - in particular,  there's a lot of handshaking that happens at the start of a connection, and I'll need to think about ways of ensuring the connection is in a viable state before putting it into use, etc

**Comment by mgravell** [comment]
as a complication, from experience there are two different scenarios that can happen here, depending on which part of the load process the server is in; sometimes you get the "err db loading into memory", sometimes you get *nothing* on the socket - it is obviously much more viable to detect the first scenario than the second

**Comment by mgravell** [comment]
if I had to speculate, "queue empty" probably happens when the library has already given up on a socket (and burned the pending queue) and *then* receives a reply from the server; you shouldn't be exposed to that - agree that is a bug

**Comment by nmehlei** [comment]
Sounds good.

Just wildly guessing here, but could this in some way be related to #205 ? For example, that SE.Redis somehow misinterprets the mentioned "nothing" on the socket as the value "false" ? As those are both "my" tickets and occured on the same server in roughly the same usage scenarios, it could be possible, right?

**Comment by mgravell** [comment]
No, it isn't possible that it can misunderstand the lack of data as a "no"
response; if there is some other glitch in there to do with timing and
connect, I will have to give it some love. It isn't something I've seen,
which makes it hard to investigate - although I don't have any reason to
doubt the report.

On 2 June 2015 at 12:48, nmehlei <notifications@github.com> wrote:

> Sounds good.
>
> Just wildly guessing here, but could this in some way be related to #205
> <https://github.com/StackExchange/StackExchange.Redis/issues/205> ? For
> example, that SE.Redis somehow misinterprets the mentioned "nothing" on the
> socket as the value "false" ? As those are both "my" tickets and occured on
> the same server in roughly the same usage scenarios, it could be possible,
> right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/220#issuecomment-107926355>
> .
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment]
Updated info here:
This was a redis server issue for a very long time but fixed in later 4.x releases after I poked the redis team. Now the server will respond, but it make take a very long time to do so. I'm not sure it's reasonable to handle this in a ping, unless we change how the ping queue works. e.g. leaving `n` pings outstanding but treating one past due as failures.

**Comment by mgravell** [comment]
Beyond what nick adds above, I don't think there's much more we can do from a client lib perspective; I think we've exhausted options here
