### ISSUE TITLE
Provision to log operation duration

### ISSUE THREAD

**Issue by mtamrakar** [StackExchange/StackExchange.Redis#2202]
Hello, I'm using [Redis Session State Provider](https://github.com/Azure/aspnet-redis-providers/blob/main/README.md). The specific library uses StackExchange.Redis under the hood.

Now, I need to log the duration for Redis operations in Application Insights but I can't seem to find a way to do so. I understand it would be the client's responsibility to wrap up their own telemetry logging (in this case aspnet-redis-providers) but I was curious if there was any abstract logger object I could override, or add an interceptor registration, to add custom logging at the core StackExchange.Redis implementation for each operation that would be performed.

**Comment by slorello89** [comment]
Pretty sure for the SessionStateProvider you'd need to use the `loggingClassName` and `loggingMethodName` from the [configuration](https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-aspnet-session-state-provider#store-aspnet-session-state-in-the-cache):

```
loggingClassName = "<Assembly qualified class name that contains logging method specified below>" [String]
loggingMethodName = "<Logging method should be defined in loggingClass. It should be public, static, does not take any parameters and should have a return type of System.IO.TextWriter.>" [String]
```

This would be the equivalent of passing int your own `TextWriter` to the multiplexer when you initialize it, and will dump the output from the multiplexer out to wherever is specified.

**Comment by mtamrakar** [comment]
@slorello89, it does allow that but it's quite limited. I can't wrap any logic around the redis operation itself and we'd need that to get a start/end time and calculate an operation duration.

**Comment by NickCraver** [comment]
We provider a profiling implementation here: https://stackexchange.github.io/StackExchange.Redis/Profiling_v2.html - if you want to capture that's a way to do it. We can't speak for the wrapper though, if the wrapper doesn't provide the access you need that's an upstream issue that'll have to be solved there.

**Comment by NickCraver** [comment]
Closing out to tidy up!
