### ISSUE TITLE
keepAlive default value

### ISSUE THREAD

**Issue by zhiweiv** [StackExchange/StackExchange.Redis#2204]
In https://stackexchange.github.io/StackExchange.Redis/Configuration.html
keepAlive={int} | KeepAlive | -1 | Time (seconds) at which to send a message to help keep sockets alive (60 sec default)
-- | -- | -- | --

Third column says default is-1, but the forth column says default is 60.

I am wondering which one is correct?

**Comment by NickCraver** [comment]
The default value is -1 indeed, but in code that translates to 60 later on, so both are true but the default column is literally the default value so we left that differentiation in docs :)
