### ISSUE TITLE
Transaction Execute yields wrong results

### ISSUE THREAD

**Issue by MichaCo** [StackExchange/StackExchange.Redis#221]
Hi Marc, hope you don't mind me reporting another strange issue ;)

I'm using version `1.0.450` of StackExchange.Redis and the Redis Nuget `Redis-64.2.8.19`.
The following issue only occurs if the Redis server is **not** running the moment I start the test program.
The multiplexer tries to connect though, and if I launch the Redis server a few seconds later, it does established the connection. 
But the state of the multiplexer seems to be broken and it runs into all kinds of strange issues.

If Redis is running the moment I start my app, and I shut down and restart Redis in between tests, everything seems to work fine (throws valid exceptions that there is no connection etc...). 
So, to reproduce the test below, shutdown the Redis server, run the console app, wait a few seconds and then start the Redis server. It will take a few seconds to recover and you should see some weird issues.

The test to reproduce uses a simple transaction to change a string value.
The cache key has an initial value, and I'm trying to change the value within the transaction.

Expected results: 
- If `transaction.Excecute` returns `true`, the value has been changed
- If `transaction.Excecute` returns `false`, the value has **not** been changed
- In both cases all tasks, created for the transaction, should be completed

Test Results:
- `transaction.Excecute` returns false, but the value was actually changed!!
- sometimes `transaction.Excecute` returns `true` although it didn't change the value!!
- In those cases, the `Task<bool>` of the `StringSet` operation is never in completed state, although `transaction.Excectute` should actually run those tasks(right ?)

If you hit enter, the test runs again. Try to shutdown the server and start it again, it might produce even more fancy results, sometimes it also recovers and from then on works fine.

So, here is the console program to reproduce it (again, first run this program, then start the Redis server a few seconds later).

``` C#
class Program
{
    static ConnectionMultiplexer _connection;

    static ConnectionMultiplexer Connection
    {
        get
        {
            if (_connection == null)
            {
                _connection = ConnectionMultiplexer.Connect("localhost:6379,abortConnect=false,connectRetry=100");
            }

            return _connection;
        }
    }

    static IDatabase Database
    {
        get
        {
            return Connection.GetDatabase(0);
        }
    }

    static void Main(string[] args)
    {
        var transactionResult = false;
        var value = "initial value";
        var key = "key";

        do
        {
            do
            {
                try
                {
                    Console.ForegroundColor = ConsoleColor.Gray;

                    Database.StringSet(key, value);
                    var initialValue = Database.StringGet(key);

                    var transaction = Database.CreateTransaction();
                    transaction.AddCondition(Condition.StringEqual(key, value));

                    var setResult = transaction.StringSetAsync(key, "value changed");

                    transactionResult = transaction.Execute();

                    var changedValue = Database.StringGet(key);
                    Console.WriteLine("Before: {0}, After: {1}", initialValue, changedValue);
                    Console.WriteLine("Set task completed: {0} - Transaction Result: {1}", setResult.IsCompleted, transactionResult);
                    if (!transactionResult && changedValue != value)
                    {
                        Console.ForegroundColor = ConsoleColor.Red;
                        Console.WriteLine("Value has been changed although transaction result was false (not commited)!");
                        Console.ForegroundColor = ConsoleColor.Gray;
                    }
                    if (transactionResult && changedValue == value)
                    {
                        Console.ForegroundColor = ConsoleColor.Red;
                        Console.WriteLine("Value has NOT been changed although transaction result was true (commited)!");
                        Console.ForegroundColor = ConsoleColor.Gray;
                    }
                }
                catch (TimeoutException)
                {
                    Console.WriteLine("Timeout");
                }
                catch (RedisConnectionException ex)
                {
                    Console.WriteLine(ex.Message);
                }
            } while (!transactionResult);

            Console.WriteLine("Done...");
        } while (Console.ReadKey() != null);
    }
}
```

Unfortunately it is pretty hard to write a Unit Test for this because we would have to shutdown and start the redis server instance...

Please let me know if it is not advisable to use `abortConnect=false,connectRetry=100` parameters.
Maybe it is better to react on connection errors and try to create the connection in a loop and throw away (dispose) multiplexer instances which are in some kind of corrupted state?

Thanks
M

**Comment by nmehlei** [comment]
It might be a long shot, but it's possible that this issue is related to https://github.com/StackExchange/StackExchange.Redis/issues/205
Though there is no transaction directly involved in #205, it also returns wrong values during problematic connection times.

**Comment by mgravell** [comment]
Closing; please see #871
