### ISSUE TITLE
What does threads and queuedItems values in exception log signify?

### ISSUE THREAD

**Issue by abrahma** [StackExchange/StackExchange.Redis#2211]
Hi,
We are getting the following exception when working with azure redis>

Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5452ms elapsed, timeout is 5000ms), command=GET, next: GET 654876542, inst: 0, qu: 0, qs: 0, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: ****, mc: 1/1/0, mgr: 10 of 10 available, clientName: **(SE.Redis-v2.6.48.48654), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=2,Free=32765,Min=200,Max=32767), POOL: (Threads=6,QueuedItems=2,CompletedItems=4994697), v: 2.6.48.48654

What does this queuedItems signify when qu and qs are 0? 
Also, what does threads signify as IOCP is 0 and worker has only 2 busy threads?

**Comment by NickCraver** [comment]
`QueuedItems` is referring to your thread pool (not the library), e.g. there are 2 Tasks (or Task-like things) queued up. Threads also refer to the .NET thread pool overall, not library specific they just help us debug overall state.

For your timeout investigation, I'd recommend seeing: a) if this is a large payload, and b) if there's a server-side stall via `SLOWLOG`. I don't see anything worrying on the client side here.
