### ISSUE TITLE
TimeOut and Concurrent reads or writes Error 

### ISSUE THREAD

**Issue by DilipVxceed** [StackExchange/StackExchange.Redis#2215]
Hi 
Server -  AWS Elastic Cache  Cluster mode with 2 nodes
Engine - 6.2.5
Client - StackExchange.Redis  2.1.58

We getting Timeout error  only in Server where we deploying our APIs
we get 1 time timeout error with below error message 

```
The timeout was reached before the message could be written to the output buffer, and it was not sent,
 command=GET, timeout: 120000, outbound: 0KiB, inbound: 0KiB, 
next: GET ULPRD:WS:PromotionPlan:VN:AD70386573DH11-002-2-20:1006902667,
 inst: 0, qu: 2, qs: 13057, aw: True, bw: Flushing, rs: ReadAsync, ws: Flushing, in: 0, 
serverEndpoint: [abc:6379 ](abc6379),
 mc: 1/1/0, mgr: 0 of 10 available, clientName: UL-WS-WEB1A, PerfCounterHelperkeyHashSlot: 10143,
 IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767), v: 2.1.58.34321 
(Please take a look at this article
 for some common client-side issues that can cause timeouts: [https://stackexchange.github.io/StackExchange.Redis/Timeouts ](https://stackexchange.github.io/StackExchange.Redis/Timeouts))
```

after that every call we getting concurrent read write error
`
Failed to write Concurrent reads or writes are not supported.`

**this errors continue to every apis call, and get solve after we reset IIS .** 

We not able to simulate this problem in our test and development server . but this error comes almost every day and required IIS reset . 
can anyone suggest any steps to solve this issue . 
let me know if i need provide any more information .
Thanks
Dilip

**Comment by NickCraver** [comment]
First thing I'd suggest is definitely upgrading to the latest version which has more diagnostics and more disconnect handling. But that's a huge timeout so something fundamentally breaks and the backlog seems to be trying to flush with a lot in queue - this is restructured in 2.5.x+ so it may help directly. At the least, you'll get better error messages to help further.

I can't speak to the "Failed to write Concurrent reads or writes are not supported", that's a downstream error about request handling that seems to be a consequence you'd need to investigate where that's called in your application or dependencies.

**Comment by NickCraver** [comment]
Happy to reopen if there's a follow-up here, closing out to tidy up for now :)
