### ISSUE TITLE
Timeout awaiting response error while fetching data from cache - concurrent read

### ISSUE THREAD

**Issue by Sangeetha-Murugesan** [StackExchange/StackExchange.Redis#2216]
Redis version : 6.2.6
StachExchange.Redis version : 2.6.48
Pool Size : 8

I am storing a data with size 17 KB in Redis cache. Data fetch will be in async manner as concurrent users may hit the redis and fetch data. Approximately 24 times, data will be fetched from cache at the same time.
In this case, below error occur :

_ Timeout awaiting response (outbound=0KiB, inbound=1994KiB, 10203ms elapsed, timeout is 10000ms), command=UNKNOWN, next: FT.SEARCH, inst: 0, qu: 0, qs: 92, aw: False, **bw: SpinningDown, rs: TryParseResult**, ws: Idle, in: 6615, in-pipe: 37095, out-pipe: 0, serverEndpoint: xxxxx:6379, mc: 1/1/0, mgr: 9 of 10 available, clientName: xxxx(SE.Redis-v2.6.48.48654), IOCP: (Busy=2,Free=998,Min=4,Max=1000), WORKER: (Busy=7,Free=32760,Min=24,Max=32767), POOL: (Threads=13,QueuedItems=7,CompletedItems=4678), Local-CPU: 100%, v: 2.6.48.48654 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)_

Sometimes rs-ReadState is TryParseResult, sometime DequeueResult.  and what does bw: SpinningDown mean?

How to overcome this issue?

Note : This error occur only if application and Rediserver hosted servers are different. If both are in same server, data fetching is fast.

**Comment by NickCraver** [comment]
There's another issue on this I can't find at the moment but I believe there was a bug in the search module for Redis causing a long stall, and you'll want to upgrade that module to latest. However, your error message indicates that the local CPU was maxed out at 100% CPU - indicating an overload in what you're able to process. I'd recommend a memory dump around when this is happening or attach a debugger to see what's eating all your CPU.

**Comment by NickCraver** [comment]
Closing out to tidy up!
