### ISSUE TITLE
HELP: Timeout

### ISSUE THREAD

**Issue by bebestmaple** [StackExchange/StackExchange.Redis#2218]
`StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5778ms elapsed, timeout is 5000ms), command=GET, next: GET GetToken, inst: 0, qu: 0, qs: 3, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: 192.168.1.101:6391, mc: 1/1/0, mgr: 10 of 10 available, clientName: 57c56c994f-j5zdb, IOCP: (Busy=0,Free=2000,Min=1500,Max=2000), WORKER: (Busy=3,Free=32764,Min=1500,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

I've set the minthread and IOCP cout to 1500,but why does this exception still occur?and what is the cause of this exception? plz.

**Comment by NickCraver** [comment]
If you upgrade to a newer version we have a bit better error message to _possibly_ help further here, but there's nothing odd I see in your message. Given you have 0 threads busy, I'd say the 1500 is very much overkill - I'd recommend looking at server-side stalls via `SLOWLOG` to see possible stalls are there.

**Comment by bebestmaple** [comment]
I have checked `SLOWLOG`,but did not find anything special...

**Comment by NickCraver** [comment]
@bebestmaple What do you mean by anything special there? If _anything_ is stalling the server, that's it: timeouts downstream if they take too long. Note: there are also newer versions of the client that add a bit more info, but I don't expect them to change your timeouts here.

**Comment by bebestmaple** [comment]
sorry,`SLOWLOG` is nothin special.I modify the `asnycTimeout` and now The Timeout Exception are less frequent.

**Comment by NickCraver** [comment]
@bebestmaple gotcha - without more detail there we can't help more but sounds like you figured this out so closing out to tidy up.
