### ISSUE TITLE
TLS cipher issues on linux servers in .NET 5+

### ISSUE THREAD

**Issue by slorello89** [StackExchange/StackExchange.Redis#2219]
Hey 👋  @NickCraver @mgravell - this is something of a follow on to #1998,

We've had some customers who run Redis Enterprise on some older OS's (e.g. RHEL 7) which support older tls ciphers run into some meaningful difficulties when trying to connect to Redis when upgrading to .NET 5+, the particular customer in question I'm working with is trying to upgrade to .net 6 but this is backwards to .NET 5 as that's where the [BC](https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux) was introduced.

The issue only occurs on linux servers, and of course is due to OpenSSL's configuraiton. But some folks have pre-existing images they need use in their entirety, and making even minor configuration changes is extremely difficult. Thus I wanted to see if we could perhaps add a mechanism to remediate this in the client via some means of configuration.

## Reproduction

I wrote a minimal reproduction and put it [here](https://github.com/slorello89/rhel7-issue-minimal-repro) - if you want to see the issue, follow the steps laid out in the README, basically, all it's doing is creating an instance of Redis-enterprise with a very narrow set of ciphers (AES128-SHA256:AES256-SHA256), and then running your .NET app in a separate ubuntu container who's OpenSSL config is not set to handle these ciphers.

## The Rub

The real rub with whatever form this fix would take is that the class & enum used to configure SslStream's configuration settings [SslClientAuthenticationOptions](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions?view=net-6.0) and [TlsCipherSuite](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.tlsciphersuite?view=net-6.0) are simply not available in the .NET standard, so any leverage of them would have to be guarded from the compiler by pre-processor directives.

Now, I have to imagine adding non-.NET standard data structures to the configuration is just not going to fly but I had a couple of ideas as to how we could remediate this

1. Follow the pattern laid out for handling certs (see the `SERedis_ClientCertPfxPath`), I actually wrote a fix that does remediate this issue using an environment variable to pull out the list of acceptable ciphers `SERedis_EnabledCiphers` but this seemed pretty hacky so I don't really want to open a PR
2. Add it as a string / array of strings in the configuration and parse out the ciphers if needed, but this would be a no-op on instances of .NET where the cipher-suites have no meaning, so idk if that's really appropriate for the public API

Would you entertain adding a fix like this? Do either of these routes sound more appealing than the other?

**Comment by NickCraver** [comment]
Thanks for the writeup! I think I understand the issue now, but I would say the scope is odd. The delta in behavior is _at the platform level_, so us fixing is in a single of potentially many libraries in use seems like the wrong place/level to solve the issue. I guess put another way: why doesn't this happen to _other_ TLS connections the app is making? And if it is, how is that being solved? Each library solving it per-platform doesn't seem like a good avenue to take but maybe I'm confused here - could use some more insight on scope.

**Comment by slorello89** [comment]
@NickCraver:

1. I agree, imo the correct way to 'work around' the problem, is to not work around it at all and just fix the configuration, as I mentioned though a big part of their issue is that they have a pretty locked down configuration and making any changes to that configuration is a significantly heavier lift than making a code change (or an env-var).
2. Why doesn't this happen in their other TLS connections? - I don't have a much visibility into their application than their connection between their linux instance and their redis instance, probably this is only an issue here because that's the only place they are connecting to that particular os/server from within .NET.

TLS config, in general, should be handled at the OS level, but StackExchange.Redis already makes carve-outs for certs (which you should be able to load out of your OS's cert store), so I don't think the notion that there would be further TLS configuration within the library is entirely uncalled for. As I mentioned though I think the weirdness around any potential solution is more problematic, just because of how the fix lives within the ecosystem.

**Comment by btchoum** [comment]
@NickCraver

Adding my 2 cents to this question: *Why doesn't this happen to other TLS connections the app is making? And if it is, how is that being solved?*

I've seen this TLS CipherSuite issue manifest in multiple ways in a few applications. 
1. The app makes TLS connections using System.Net.Http.HttpClient
2. The app uses a client library which uses System.Net.Http.HttpClient under the hood.
3. The app uses a library with uses lower level API (e.g. SslStream) to make TLS connections.

In the first 2 cases, the HttpClient can be configured to use specific cipher suites (see code snippet below). 
``` csharp
// This configures a HttpClient with a restricted list of allowed ciphers 
using System.Net.Security;

var allowedCiphers = new[] 
{ 
    TlsCipherSuite.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,
    // add more allowed ciphers here ...
};
var socketHandler = new SocketsHttpHandler
{
    SslOptions = new SslClientAuthenticationOptions
    {
        // unfortunately this throws PlatformNotSupportedException on Windows 
        CipherSuitesPolicy = new CipherSuitesPolicy(allowedCiphers)
    }
};
var httpClient = new HttpClient(socketHandler);

// if SomeLibraryClient allows the configuration of its inner HttpClient 
var someLibraryClient = new SomeLibraryClient 
{
    InnerHttpClient = httpClient
}
```

Of course this is only possible if the library exposes the underlying HttpClient (or SslStream), or allows the option to configure it somehow. 
That's why I believe a good solution for Redis users should involve adding a configuration option for specifying CipherSuites in the StackExchange.Redis client. 

Like @slorello89 I got a hacky solution working by adding "AllowedCipherSuites" to the StackExchange.Redis.ConfigurationOptions and passing those to the SslStream. As @slorello89 stated, such a solution would not compile in .NET Standard. 

I also found out that even on .NET 6.0 the [CipherSuitesPolicy constructor](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.ciphersuitespolicy.-ctor?view=net-6.0) only works on Linux system with OpenSSL 1.1.1 or higher or MacOS. It fails on Windows with a PlatformNotSupportedException. So this would also need to be guarded somehow.

Despite these caveats, I still believe it would be best to solve this issue in the StackExchange.Redis library, given how widely it is used across the .NET world.

**Comment by NickCraver** [comment]
Thanks for the additional info! I remain opposed to solving this global issue specifically in the library as it's super niche and creates a matrix of options support for a very narrow use case that goes boom everywhere else. But: what if we allowed something more general?

I added a proposal here: #2224 which is basically a `Func<string, SslClientAuthenticationOptions>` on configuration options that gets the host we're connecting to (or SslHost if set), and you can return a `SslClientAuthenticationOptions` object with as much configuration as your heart desires for whatever use case. I think that provides the functionality needed without supporting something super specific and frankly hard to support well.

If the above looks good, it still needs some @mgravell eyes for thoughts and test cases and such but...that's my idea for solving this while not locking us into very narrow specifics. Thoughts?

**Comment by slorello89** [comment]
@NickCraver - I've confirmed this fix works for my purposes :) - one thing I will note that may or may not be worth addressing. The way the tls authentication works now, it actually swallows the authentication failures in tls.

When I was initially testing this I was trying to run something like:

```cs
var options = new ConfigurationOptions();
options.EndPoints.Add($"{host}:12000");
options.Ssl = true;
options.SslClientAuthenticationOptions = delegate(string s)
{
    var opts = new SslClientAuthenticationOptions();
    opts.TargetHost = host;
    opts.EnabledSslProtocols = SslProtocols.Tls12;
   
    opts.CipherSuitesPolicy = new CipherSuitesPolicy(new TlsCipherSuite[]
    {
        TlsCipherSuite.TLS_RSA_WITH_AES_128_CBC_SHA256,
        TlsCipherSuite.TLS_RSA_WITH_AES_256_CBC_SHA256
    });
    
    opts.RemoteCertificateValidationCallback += (sender, certificate, chain, errors) =>
    {
        Console.WriteLine(errors);
        return true;
    };
    return opts;
};

options.SslProtocols = SslProtocols.Tls12;
options.CertificateValidation += (sender, certificate, chain, errors) => true;
```

This is erroneous because `options.CertificateValidation` and `opts.RemoteCertificateValidationCheck` both assign the delegate, but the only error I was getting was:

```
It was not possible to connect to the redis server(s). There was an authentication failure; check that passwords (or client certificates) are configured correctly.
```

If you really dig though, you see that you get:

```
The 'RemoteCertificateValidationCallback' option was already set in the SslStream constructor.
```

Now if I dropped a text-writer into the constructor of the multiplexer, this of course lights up the issue, and maybe this is a broader discussion, but some of these failures - might it be worth adding them as inner-exceptions to the exceptions the muxer is already throwing?

**Comment by Coder3333** [comment]
Could someone provide an example of how to modify the OS's configuration to get around this issue?  We upgraded our Redis server, but are still getting the same error.  Also, has the updated StackExchange.Redis been published to NuGet, yet, with the new config option?  Thank you.

**Comment by slorello89** [comment]
@Coder3333 - the latest version of the library 2.6.66 I believe has it (correct me if I'm wrong Nick). NOTE, the fix will only appear if you are running in .NET core 3.1+. If you are seeing a cipher/tls issue in pre .NET core 3.1, it's not this issue. WRT how to fix it on your servers end, this is not an issue to fix by upgrading your redis version. On the linux server running your .NET app, you'll need to adjust the cipher suite settings in your openssl.cnf file to match whatever cipher suites allowed by the linux server running Redis. See the recommended changes from Microsoft: https://learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux#recommended-action
