### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by mrbillo** [StackExchange/StackExchange.Redis#2220]
I have tried all of the solutions proposed. Random timeout under very light load.
Timeout performing EVAL (2000ms), next: EVAL, inst: 0, qu: 0, qs: 4, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 65536, in-pipe: 8050, out-pipe: 0, serverEndpoint: <hidden>, mc: 1/1/0, mgr: 8 of 10 available, clientName: BILL2022(SE.Redis-v2.6.48.48654), IOCP: (Busy=1,Free=999,Min=50,Max=1000), WORKER: (Busy=6,Free=32761,Min=50,Max=32767), v: 2.6.48.48654 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by NickCraver** [comment]
Looking at your values, I'd check 2 things:
1. This is from an EVAL, did it take a long time to run on the server? Check this via SLOWLOG on the server side.
2. Is the result of whatever this command is very large? The maxed out inbound buffer (`in: 65536`) may indicate a very large single payload coming back.

**Comment by NickCraver** [comment]
Advice given above - if more info happy to reopen but closing out to tidy up for now.
