### ISSUE TITLE
Unable to connect RediSearch running in docker container from .NET 6 console app using NRediSearch

### ISSUE THREAD

**Issue by sarath-kumar-harikrishnan** [StackExchange/StackExchange.Redis#2226]
I'm loading RediSearch module by using the official docker image. Below command is used in loading the module,

`docker run --name redisearch -p 6379:6379 redislabs/redisearch:latest`

On the other hand I've a .NET 6 console application locally, using NRediSearch (2.2.79) I'm trying to connect RediSearch running in docker container,

```
var connection = ConnectionMultiplexer.Connect("127.0.0.1:6379,ssl=False,abortConnect=False,connectTimeout=30000");
IDatabase db = connection.GetDatabase();
var client = new Client("idx:strings", db);
var schema = new Schema().AddTextField("englishtext", 1).AddNumericField("tid");
var index = client.CreateIndex(schema, new Client.ConfiguredIndexOptions());
```

Getting below error while trying to create index,

```
StackExchange.Redis.RedisConnectionException
  HResult=0x80131500
  Message=No connection is active/available to service this operation: FT.CREATE; UnableToConnect on redisearch:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 3s ago, v: 2.2.79.4591, mc: 1/1/0, mgr: 10 of 10 available, clientName: DESKTOP-11C6A3B, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=0,Free=32767,Min=8,Max=32767), v: 2.2.79.4591
  Source=StackExchange.Redis
  StackTrace:
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2859
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at NRediSearch.Client.CreateIndex(Schema schema, ConfiguredIndexOptions options) in /_/src/NRediSearch/Client.cs:line 330

```
Please note apart from 127.0.0.1:6379 in connectionstring, I've also tried localhost:6379 and redisearch:6370, but nothing works

Could someone help me on this

Thanks.

**Comment by slorello89** [comment]
@sarath-kumar-harikrishnan - this sounds an awful lot like redis is really not running - can you reach redis from the redis-cli? With your configuration you should just be able to run `redis-cli` with no arguments and connect.

**Comment by sarath-kumar-harikrishnan** [comment]
@slorello89 I could attach redis-cli to the container and execute commands successfully

`docker exec -it <container id> redis-cli`

I'm facing above issue only while trying to connect it from NRediSearch library

**Comment by NickCraver** [comment]
@sarath-kumar-harikrishnan In your connection string, remove `abortConnect=false` so the connection fails and you can see why :)

**Comment by sarath-kumar-harikrishnan** [comment]
@NickCraver after removing `abortConnect=false` from connection string, getting below error,

```
StackExchange.Redis.RedisConnectionException
  HResult=0x80131500
  Message=It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
  Source=StackExchange.Redis
  StackTrace:
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1179
```

**Comment by NickCraver** [comment]
@sarath-kumar-harikrishnan okay that's not giving us much, so next step is to your connect call, pass a text writer, and the content of that will give detailed info about each step of the connection.

**Comment by slorello89** [comment]
@sarath-kumar-harikrishnan - The extra logging would be really helpful here. But I can't help but thinking that this really sounds an awful lot like redis just isn't alive when you are trying to talk to it. I noticed the example error you shared with us you were talking to redisearch:6379 - this would not be valid if you are trying to run your app locally, it would only be correct if you were running it within docker on the same network as the RediSearch image (so if you are running your .NET app in a container, you may want to valide that the .NET container and reids container are on the same network). When you are running locally against 127.0.0.1, the docker command you provided SHOULD expose it to 6379 - which would work with 127.0.0.1:6379 or localhost:6379 - unless you've done something really weird with your docker network configuration - I know you said that you had tried both of those. 

At the risk of asking a very dumb question, I noticed that you're not daemonizing the `docker run` command, are you maybe accidentally stopping your redis instance (ctrl-C'ing out of docker will shut down redis) - maybe try running `docker run --name redisearch -d -p 6379:6379 redislabs/redisearch:latest` instead - that will put it off to the background and you wouldn't have to worry about accidentally shutting it off.

**Comment by sarath-kumar-harikrishnan** [comment]
@slorello89 @NickCraver communication from app running locally to docker container is established successfully after exposing the port like `--expose 6379`. Using below docker command to up the container,

`docker run --name search --expose 6379 -p 127.0.0.1:6380:6379 redislabs/redisearch:latest`

**Comment by NickCraver** [comment]
Glad you got this sorted - closing out to cleanup!
