### ISSUE TITLE
ExpireWhen only allows one argument at a time

### ISSUE THREAD

**Issue by HugKitten** [StackExchange/StackExchange.Redis#2228]
You should add [Flags] in front of the ExpireWhen enum to allow for combinations of "HasNoExpiry" with "GreaterThanCurrentExpiry" and "LessThanCurrentExpiry". I'm too lazy to test if my example works, but it can be fixed by updating the ToLiteral method in the ExpiryOptionExtentions static class. It would look something like this:

```
internal static class ExpiryOptionExtensions
{
    private static KeyValuePair<ExpireWhen, RedisValue>[] Map = new
    {
        KeyValuePair.Create(ExpireWhen.HasNoExpiry, RedisLiterals.NX),
        KeyValuePair.Create(ExpireWhen.HasExpiry, RedisLiterals.XX),
        KeyValuePair.Create(ExpireWhen.GreaterThanCurrentExpiry, RedisLiterals.GT),
        KeyValuePair.Create(ExpireWhen.LessThanCurrentExpiry, RedisLiterals.LT),
    };

    internal static RedisValue[] ToLiteral(this ExpireWhen op) =>
        Map
            .Where(p => op.HasFlag(p))
            .Select(kv => kv.Value)
            .ToArray();
}
```

**Comment by NickCraver** [comment]
This combination isn't supported by Redis, so it's not allowed in the client. You can see this in the documentation, e.g. https://redis.io/commands/pexpire/

> The GT, LT and NX options are mutually exclusive.

**Comment by mgravell** [comment]
also; adding `[Flags]` isn't a magic "make it work" wand - we'd also need to change the values of the enum elements, and changing the value of enum elements is a breaking change - meaning: any code that isn't recompiled against the newer library will be using the wrong constant values (this is very definitely a problem, since many libraries build upon SE.Redis, and would need to be updated)

**Comment by mgravell** [comment]
I'm going to close this out; if we've missed a genuine use-case, i.e. "here's the valid redis command scenario that I can't currently achieve", please let us know - happy to reopen if there's a scenario to discuss.

**Comment by HugKitten** [comment]
> This combination isn't supported by Redis, so it's not allowed in the client. You can see this in the documentation, e.g. [redis.io/commands/pexpire](https://redis.io/commands/pexpire/)
> 
> > The GT, LT and NX options are mutually exclusive.

It doesn't say the XX is mutually exclusive, it was why I was pointing this out.

**Comment by HugKitten** [comment]
> also; adding `[Flags]` isn't a magic "make it work" wand - we'd also need to change the values of the enum elements, and changing the value of enum elements is a breaking change - meaning: any code that isn't recompiled against the newer library will be using the wrong constant values (this is very definitely a problem, since many libraries build upon SE.Redis, and would need to be updated)

I'm aware of this, it's part of why I didn't try to do the changes myself. I just figured I'd point out an issue I found with the library.

**Comment by NickCraver** [comment]
If we try this in the repro, you'll see it fails even on the `XX` case:
> redis> EXPIRE mykey 10 XX NX
(error) NX and XX, GT or LT options at the same time are not compatible

@slorello89 perhaps the doc for e.g. `EXPIRE key seconds [NX | XX | GT | LT]` should note that they're _all_ mutually exclusive? I do agree that it stating only the 3 are is a bit confusing.
