### ISSUE TITLE
server.Keys(pattern: $"*{pattern}*") with Error?

### ISSUE THREAD

**Issue by kuan62** [StackExchange/StackExchange.Redis#2231]
**Stackexchange.Redis(2.6.48)** 
Always get error as below after call server.Keys(pattern: $"*{pattern}*").....

Remove Error: Timeout performing SCAN (2000ms), next: SCAN, inst: 3, qu: 0, qs: 1, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: redis.sit.kkday.com:50000, mc: 1/1/0, mgr: 10 of 10 available, clientName: Eric-Hu-de-MacBook-Pro(SE.Redis-v2.6.48.48654), IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=0,Free=32767,Min=100,Max=32767), POOL: (Threads=6,QueuedItems=0,CompletedItems=123), v: 2.6.48.48654 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts), stacktrace=   at StackExchange.Redis.CursorEnumerable`1.Enumerator.ThrowTimeout(Message message) in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 247
   at StackExchange.Redis.CursorEnumerable`1.Enumerator.Wait[TResult](Task`1 pending, Message message) in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 201
   at StackExchange.Redis.CursorEnumerable`1.Enumerator.SlowNextSync() in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 195
   at StackExchange.Redis.CursorEnumerable`1.Enumerator.MoveNext() in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 189

**Comment by mgravell** [comment]
Well... is it right? Keys / scan are (relatively) expensive operations. If
they are performing catastrophically it'll show in "slowlog" - does
anything show? Note: keys / scan are not intended for routine use.

**Comment by kuan62** [comment]
@mgravell  I knew use Keys/Scan are expensive operations, but still lack a effective way to reach it. Anyway I think in programming principle this exception should not be happen, Right?

**Comment by NickCraver** [comment]
@kuan62 The exception is saying "it took longer than 2 seconds to get an answer back" - if it's actually taking > 2 seconds, the exception should and will happen :) Checking SLOWLOG on the server as Marc said will help here, but overall: you're likely doing something that takes a long time and giving it a small window to do so. Those parameters are in conflict and one of 'em will need to change.

**Comment by NickCraver** [comment]
Advice posted above on this one - closing out to cleanup!
