### ISSUE TITLE
Connect to Redis cache using service principal

### ISSUE THREAD

**Issue by cakong10** [StackExchange/StackExchange.Redis#2232]
Is it possible to connect to an Azure Redis cache using service principal authentication? For example, if we give our service principal access to the Azure Redis cache resource, then can we do `ConnectionMultiplexer.Connect(string connectionString) `with just the host name and not a password?

**Comment by NickCraver** [comment]
I know this is requested on the Azure side but would not be part of this library (though we've added some configuration options functionality to enable it) - only user/password is supported. Putting on @philon-msft's radar for a possible update here later if anything changes service-side.

**Comment by NickCraver** [comment]
For anyone looking for this, we've enable the bits needed to implement it, but what you'll want to use is the wrapping https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/ library for various token supports like SP and MSI :)
