### ISSUE TITLE
(RedisJson) How do I atomically add an object to a nested array if the object doesn't already exist?

### ISSUE THREAD

**Issue by dgunderson** [StackExchange/StackExchange.Redis#2235]
Hi all, I'm hoping to get some guidance. Using `StackExchange.Redis` and `redis-json`, I'm trying to atomically add an object to a property array but only if the object being added doesn't already exist:

Example JSON document that is stored with the redis key `list:4`:

```
{
   listId: 4,
   answers: [
       {
           taskId: 4,
           answer: "Hello",
       },
       {
           taskId: 5,
           answer: "World"
       }
   ]
}
```

I want to add the following object to the `answers` property array but *only if* there isn't an object already in the collection with the same `taskId`:

```
{
    taskId: 7,
    answer: "foo"
}
```

How do I go about doing this in a thread-safe manner? I'm aware of how to use transactions within redis and adding conditions to the transaction, but the part I'm not grasping is specifically adding a condition where it looks at the object properties within the array.

Thanks in advance.

**Comment by dgunderson** [comment]
Great! Thank you for the response and the example. We're still new to this so we weren't aware a custom script was an option, and we were especially not aware that all intermediary results within the script are still within the same atomic action. That is excellent to know!

Regarding your example and searching the array, how performant is it if/when the array becomes very long? 

Another design thought we have is to do the following (and perhaps it would be more performant than searching a long list?):

1. store all list documents with the key `list:{listId}`
2. separately store `listId->taskId` answers as a separate hash
3. Atomically attempt to add the new `listId->taskId` combo to the hash in the 2nd step above
4. If the result of the third step above is true, we are safe to add the new task answer to the original list's document store collection. If it is false, we do not add it.
_Note: this approach means anytime a list object is loaded into redis, we also must populate that hash in step 2 above with its corresponding `listId-taskId` answers_

What's the "redis best practice" here?

**Comment by slorello89** [comment]
I don't think the JSON arrays are internally indexed within the data structure at all. You might want to think about adding a secondary index on top of the array:

```
FT.CREATE testidx ON JSON prefix 1 test: SCHEMA $.listId as listId TAG $.answers[*].taskId as taskIds TAG
JSON.SET test:1 $ '{"listId":"4", "answers":[{"taskId":"4","answer": "Hello"}]}' 
FT.SEARCH testidx "@taskIds:{4} @listId:{4}" 
```

I'm pretty sure that will be quicker if for no other reason than Redis will build an index on top of the documents, might have to experiment to see which is faster. You can shove this into a script as well. I'd be remiss if I didn't point out that [Redis OM .NET](https://github.com/redis/redis-om-dotnet) removes a bunch of the headaches for you (granted doing the query/update atomically isn't going to be doable here since RediSearch+JSON doesn't really support this outside of a script).

**Comment by dgunderson** [comment]
Awesome, thank you so much for the knowledge share! I really appreciate it.

**Comment by NickCraver** [comment]
Closing out to tidy up :)
