### ISSUE TITLE
[Question] Need help understanding TimeoutException

### ISSUE THREAD

**Issue by macchmie3** [StackExchange/StackExchange.Redis#2236]
Hi, we are using StackExchange.Redis through [this nuget ](https://github.com/MichaCo/CacheManager). We are hosting app service in Azure, and using _Azure Cache for Redis_ as Redis server. As a foreword - I think that it's better to create this question issue here than in the link github since people here will probably have a much better understanding of what happens underneath in StackExchange.Redis.

Each app instance that we use has in-memory cache, which is synchronized via Redis working as a backplane, utilizing pub/sub feature of Redis. When the traffic is high we see from time to time that one instance can "spiral out of control" CPU-wise, which causes a lot of timeouts on that instance. We wonder what might cause it.

Here are some exceptions (in chronological order, mind rising _qs_ parameter)

1. `StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL (1000ms), next: EVAL, inst: 62, qu: 0, qs: 2720, aw: False, rs: ReadAsync, ws: Idle, in: 65536, serverEndpoint: adress.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: RD0003FF541C54, IOCP: (Busy=7,Free=993,Min=256,Max=1000), WORKER: (Busy=282,Free=32485,Min=1024,Max=32767), v: 2.2.50.36290`
2. `StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL (1000ms), next: EVAL, inst: 63, qu: 0, qs: 2721, aw: False, rs: ReadAsync, ws: Idle, in: 65536, serverEndpoint: adress.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: RD0003FF541C54, IOCP: (Busy=6,Free=994,Min=256,Max=1000), WORKER: (Busy=285,Free=32482,Min=1024,Max=32767), v: 2.2.50.36290 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`
3. `StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL (1000ms), next: EVAL, inst: 9, qu: 0, qs: 2736, aw: False, rs: ReadAsync, ws: Idle, in: 65536, serverEndpoint: adress.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: RD0003FF541C54, IOCP: (Busy=12,Free=988,Min=256,Max=1000), WORKER: (Busy=284,Free=32483,Min=1024,Max=32767), v: 2.2.50.36290 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

Stack trace for full single exception:

```
StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL (1000ms), next: EVAL, inst: 9, qu: 0, qs: 2736, aw: False, rs: ReadAsync, ws: Idle, in: 65536, serverEndpoint: adress.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: RD0003FF541C54, IOCP: (Busy=12,Free=988,Min=256,Max=1000), WORKER: (Busy=284,Free=32483,Min=1024,Max=32767), v: 2.2.50.36290 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2856
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at CacheManager.Redis.RedisCacheHandle`1.Eval(ScriptType scriptType, RedisKey redisKey, RedisValue[] values, CommandFlags flags)
   at CacheManager.Redis.RedisCacheHandle`1.<>c__DisplayClass48_0.<GetCacheItemAndVersion>b__0()
   at CacheManager.Redis.RetryHelper.Retry[T](Func`1 retryme, Int32 timeOut, Int32 retries, ILogger logger)
   at CacheManager.Redis.RedisCacheHandle`1.Retry[T](Func`1 retryme)
   at CacheManager.Redis.RedisCacheHandle`1.GetCacheItemAndVersion(String key, String region, Int32& version)
   at CacheManager.Redis.RedisCacheHandle`1.GetCacheItemInternal(String key, String region)
   at CacheManager.Core.BaseCacheManager`1.GetCacheItemInternal(String key, String region)
   at CacheManager.Core.Internal.BaseCache`1.Get(String key, String region)
   at CacheManager.Core.Internal.BaseCache`1.Get[TOut](String key, String region)
   at <out namespace>(ICacheManager`1 cache, String key, String region)
```

Here is the connection string parameters we pass: 
<adress>,password=<key>,ssl=true,sslprotocols=tls12,abortConnect=False,allowAdmin=True,syncTimeout=3000

Do you have any tips for us what we should try to fix the issue? We are not sure if that means that the issue is with the app services that connect to the redis server, or the redis server itself. We are also not quite sure if this is related to network issues or other stuff. It seems that when we run our app without the in-memory cache handle (thus skipping pub/sub mechanism) and always go to the redis server for the data then the load is a bit higher, but things seem not to fall apart. 

Edit: I added the average CPU graph that shows that things can go sideways in moments, and I can confirm that the traffic to the application is quite stable over time. meaning there is constant high traffic, **without** and spikes here and there. 
![Capture](https://user-images.githubusercontent.com/12615493/187676888-b055228f-ce43-4982-a8cf-9ee2f673d723.PNG)

**Comment by macchmie3** [comment]
Some more insight - I checked that some values we store in redis might be considered big. I'm not sure if there is any "best-practice", but values can commonly have 10-300 kB, sometime getting to 1-2 MB. Could that be a huge issue?

**Comment by NickCraver** [comment]
The `WORKER: (Busy=284,Free=32483,Min=1024,Max=32767)` indicates you have many threads blocked and are likely encountering thread/pool exhaustion here. I'd be looking for sync over async or general synchronous calls that should be async, but also: payloads of that size are also likely to cause issues as seen in `in: 65536`. If your timeout is only 1 second _for the worst case_ and you're dealing in large payloads: you're likely to hit timeouts. I'd recommend offloading any large payloads to another connection with a higher timeout if they're on the rare side...or splitting them up if on the non-rare side.

**Comment by macchmie3** [comment]
About thread pool - we do not use async calls to redis, is this number the amount of threads used by StackExchange.Redis only or in general on the machine? Is high "qs" parameter indicating anything?

**Comment by macchmie3** [comment]
Some more information - we turned off the pub/sub mechanism and always read the data directly from redis server, and I still notice some timeout exceptions, even on "delete" operations, which do not carry huge payload I would assume.I think we could manage to rewrite the cache mechanism that would end up in storing entities no larger than ~100B, but I am not sure if that would definitely help.
`Exception:StackExchange.Redis.RedisTimeoutException: Timeout performing UNLINK (1000ms), next: EVAL, inst: 39, qu: 0, qs: 488, aw: False, rs: ReadAsync, ws: Idle, in: 65536, serverEndpoint: adress.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: RD0003FF54402D, IOCP: (Busy=12,Free=988,Min=256,Max=1000), WORKER: (Busy=283,Free=32484,Min=1024,Max=32767), v: 2.2.50.36290 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

**Comment by Mhirji** [comment]
Hi,

Having a similar issue.  Ironically I am also suffering from 'it works on my local machine but not when I deploy it'.  I have increased the minimum number of threads, but still getting the same timeout.  The stacktrace is:

StackExchange.Redis.RedisTimeoutException: The timeout was reached before the message could be written to the output buffer, and it was not sent, command=EXISTS, timeout: 5000, inst: 0, qu: 0, qs: 0, aw: False, bw: CheckingForTimeout, rs: NotStarted, ws: Initializing, in: 0, serverEndpoint: adress.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: CLIENTNAME(SE.Redis-v2.5.43.42402), IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=2,Free=32765,Min=8,Max=32767), POOL: (Threads=11,QueuedItems=0,CompletedItems=167), v: 2.5.43.42402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at API.Infrastructure.Storage.RedisCache.CacheService.ExistsAsync(String key, CancellationToken cancellationToken) in C:\Workspace\src\API\dev\src\API.Infrastructure.Storage.RedisCache\CacheService.cs:line 114
   at API.Web.OData.Middleware.DistributedResponseCacheMiddleware.Invoke(HttpContext context) in C:\Workspace\src\API\dev\src\API.Web.OData\Middleware\DistributedResponseCacheMiddleware.cs:line 32
   at API.Web.OData.Middleware.HostStringRewriteMiddleware.Invoke(HttpContext context) in C:\Workspace\src\API\dev\src\API.Web.OData\Middleware\HostStringRewriteMiddleware.cs:line 23
   at Microsoft.AspNetCore.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.OData.Query.ODataQueryRequestMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

Any advice would be greatly appreciated to understand this message and how to get around it.

**Comment by NickCraver** [comment]
@macchmie3 If you want to fix your issues, I recommend moving to async calls. Sync calls, by nature, use a thread doing nothing while they wait on a result. The real fix here may not be easy: go async, because you're doing async work. Anything short of that will result in blocking which is what you're observing.

@Mhirji your exception looks different, as if it didn't connect at all. I recommend changing your connection config to _remove_ `abortConnect=false` so you can see the reason it's failing.

**Comment by NickCraver** [comment]
Closing this out to tidy up - advice above!
