### ISSUE TITLE
Unobserved task exception

### ISSUE THREAD

**Issue by stedmanm** [StackExchange/StackExchange.Redis#2239]
Using version 2.6.48 of lib, and an Azure Redis instance with 2 nodes (with 2 replicas per node). When I reboot a master node, sometimes SE.Redis lib throws the unobserved exception posted below.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (InternalFailure on [0]:PEXPIRE MCP:{8YG}:FixtureStream:1558065055 (BooleanProcessor))
 ---> StackExchange.Redis.RedisConnectionException: InternalFailure on [0]:PEXPIRE MCP:{8YG}:FixtureStream:1558065055 (BooleanProcessor)
 ---> StackExchange.Redis.RedisCommandException: Command cannot be issued to a replica: PEXPIRE MCP:{8YG}:FixtureStream:1558065055
   at StackExchange.Redis.PhysicalBridge.WriteMessageToServerInsideWriteLock(PhysicalConnection connection, Message message) in /_/src/StackExchange.Redis/PhysicalBridge.cs:line 1483
   --- End of inner exception stack trace ---
   at Trading.Backend.Redis.RedisCache.ExecuteRedisOperation[TResult](Func`1 action, Operation operation, RedisKey key, String additionalInfo, Boolean logResult, Action`1 logQueryAction)
   --- End of inner exception stack trace ---

**Comment by NickCraver** [comment]
This would happen if you have a task somewhere that's not awaited (so it's thrown in the background). I'd check if you have a call somewhere that's a task left orphaned.

**Comment by stedmanm** [comment]
@NickCraver  Thx sorry to bother, thought it might be something in lib. I think I see where my mistake it now.

**Comment by NickCraver** [comment]
Closing out to tidy up - glad you got sorted here!
