### ISSUE TITLE
In an MVC app for how log should a ConnectionMultiplexer live?

### ISSUE THREAD

**Issue by ricardopolo** [StackExchange/StackExchange.Redis#224]
I now a ConnectionMultiplexer  is long lived. You said store it and re use.

So... in  a website, for how long?
Use a Static for the Whole App? 
A new one for each request (using an IOC)?

**Comment by mgravell** [comment]
Definitely not one per request. We use "one as long as it stays alive" -
usually many hours or days, but if there is a particularly nasty network
hiccough a new one can be more stable.

**Comment by ricardopolo** [comment]
@mgravell any recomendation about an specific implementation.

I an currently using it as an static property.

````cs
private static readonly ConnectionMultiplexer _redis = ConnectionMultiplexer.Connect("connectionString");
````

So it only gets initialized the first time.

The issue I encounter here is that when the redis server is gone the app never start to work again. I would like to have something like be static until it fails. Then a new one until it works.

Any idea?

**Comment by ricardopolo** [comment]
@mgravell any idea? thank you

**Comment by NickCraver** [comment]
@ricardopolo The `ConnectionMultiplexer` should handle connection interrupts and reconnects (it also has events for this). Are you having issues with it doing such with a current build?
