### ISSUE TITLE
Unable to connect to an IPv6-only redis server by hostname

### ISSUE THREAD

**Issue by nazar554** [StackExchange/StackExchange.Redis#2240]
I'm unable to connect to a Redis server when hostname only has AAAA record.

![image](https://user-images.githubusercontent.com/12029825/188271188-cb10e566-bbb0-490f-973d-d4ec290ebfdc.png)

Probably the issue is around here, since when debugging the `Socket` gets created as `AddressFamily.Internetwork`, 

https://github.com/StackExchange/StackExchange.Redis/blob/d2d13bc4cf972beea8fe528be38db2eccbc72d9a/src/StackExchange.Redis/SocketManager.cs#L217

It's then crashes inside `PhysicalConnection.BeginConnectAsync` with

```
Exception thrown: 'System.Net.Sockets.SocketException' in Pipelines.Sockets.Unofficial.dll
The requested name is valid, but no data of the requested type was found.
```

There is a workaround, seems that setting `ConfigurationOptions.ResolveDns = true` forces to use the IPv6 address directly, but this breaks DNS updates.

Environment: .NET 6.0.8 (x64) on both Windows and Linux
StackExchange.Redis 2.6.48

**Comment by NickCraver** [comment]
@nazar554 Is there any chance you are in a position to give #2241 a try?

**Comment by nazar554** [comment]
> @nazar554 Is there any chance you are in a position to give #2241 a try? 

Is there a nightly NuGet I could use or I have to clone the branch and build it manually?

**Comment by NickCraver** [comment]
@nazar554 I'm pretty sure this change is safe - let me get some co-conspirator eyes on it and will ping when merged, that'll land on the MyGet feed shortly after. Feed links: https://github.com/StackExchange/StackExchange.Redis

**Comment by NickCraver** [comment]
@nazar554 There should be a build landing on MyGet shortly - have to run here but will check in later and make sure that went up :)

**Comment by NickCraver** [comment]
Alrighty, version 2.6.62 is available on MyGet 0 if you could confirm this works that'd be awesome :)

**Comment by nazar554** [comment]
> Alrighty, version 2.6.62 is available on MyGet 0 if you could confirm this works that'd be awesome :)

Just tested it, seems to work both on Linux and Windows.

**Comment by NickCraver** [comment]
Awesome, thanks for the update! This will be in the next release, probably not too far out.
