### ISSUE TITLE
(RedisJson) How do I find the index of a json object in an array based off of a value of its properties

### ISSUE THREAD

**Issue by Holmslice86** [StackExchange/StackExchange.Redis#2244]
I am fairly new to Redis and RedisJson and I have been through all of the documentation I can get my hands on but I still cant seem to figure this one out. I am hoping someone could shed some light on this situation to help me understand. My end goal is to be able to remove the json object from the responses array using JSON.ARRPOP. I need to get the index of the object first and I cant seem to do that.
Here is my object structure:
```
JSON.SET test:1 $ '{ "responses":[{"responseId":"29aab59c-10b0-48c0-ab91-8873fb6e2238"},{"responseId":"ab79f09b-8e31-41f4-9191-ef89a34964d3"}]}'
```

Check the path: 
```
JSON.GET test:1 $.responses[*].responseId
"[\"29aab59c-10b0-48c0-ab91-8873fb6e2238\",\"ab79f09b-8e31-41f4-9191-ef89a34964d3\"]"
```

Ok looks good I have an array of two strings  lets get that index of 29aab59c-10b0-48c0-ab91-8873fb6e2238.
```
JSON.ARRINDEX test:1 $.responses[*].responseId '"29aab59c-10b0-48c0-ab91-8873fb6e2238"'
1) (nil)
2) (nil)
```
It appears to have searched but found nothing?
At first I thought it was an escape character issue but I get the same results with responeIds 1 and 2.
Any help here would be greatly appreciated. Thanks!

**Comment by NickCraver** [comment]
This repo is for the StackExchange.Redis client - I think where you'll want to ask is over in https://github.com/RedisJSON/RedisJSON for that expertise :)

**Comment by Holmslice86** [comment]
Will do thanks

**Comment by NickCraver** [comment]
Welcome! Closing out to tidy up here :)

**Comment by slorello89** [comment]
@Holmslice86 - this sounds like a bug, so the repo that Nick pointed to would be a good place to open an issue. Also if you have any general Redis questions probably the best place to ask questions of the Redis community is on our [Discord server](https://discord.com/invite/redis) - RedisJSON even has it's own channel there. (Of course the service this library is named for isn't a bad place to look either :) )
