### ISSUE TITLE
Redis Get calls Fail with Authentication

### ISSUE THREAD

**Issue by azharmahmood** [StackExchange/StackExchange.Redis#2248]
We have been using StackExchange.Redis client with sentinel/redis setup without authentication.

I am trying to configure authentication but running into some issues. When I setup a password on sentinel/redis and supply the password in the config string (as below). ConnectionMultiplexer.Connect() method does not complain, the Add calls seem to work fine but Get calls fail with an error below.

Config String: acd-fbsent201:26379,acd-fbsent203:26379,serviceName=Redisdb,allowAdmin=true,password=test

Error:
No connection is active/available to service this operation: GET BouquetProducts, mc: 1/1/0, mgr: 10 of 10 available, clientName: ACD-FBWEB202(SE.Redis-v2.5.43.42402), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=2,Free=8189,Min=2,Max=8191), v: 2.5.43.42402 at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)

If I supply an incorrect password, ConnectionMultiplexer.Connect() method throws the following error, which makes sense since an incorrect password is supplied by the client.

Error:
It was not possible to connect to the redis server(s). There was an authentication failure; check that passwords (or client certificates) are configured correctly. at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) at StackExchange.Redis.ConnectionMultiplexer.SentinelConnect(ConfigurationOptions configuration, TextWriter log) at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) ....

Any help or pointers will be much appreciated.

**Comment by azharmahmood** [comment]
Update:
I found the culprit i.e. all my Get() calls are using "CommandFlags.DemandReplica", when I changed it to None, it started working.

Can you please help me understand why does "CommandFlags.DemandReplica"  not work with authentication?

**Comment by NickCraver** [comment]
Do you have a small code example? It's unclear if you're connecting only to Sentinel, Sentinel then getting a primary, etc. but overall my question is: are we actually connected to any replicas? It seems now, so what are we connected to? You can get servers from the multiplexer and list out what's there and see if it's connected.

**Comment by azharmahmood** [comment]
@NickCraver 
Please see below
`{04:56:56.6603: Connecting (sync) on .NET Framework 4.8.4510.0 (StackExchange.Redis: v2.5.43.42402)
04:56:56.8248: acd-fbsent201.teleflora.org:26379,acd-fbsent203.teleflora.org:26379,serviceName=flowerbuyerdb,allowAdmin=True,password=*****,$NONE=,$APPEND=,$ASKING=,$BGREWRITEAOF=,$BGSAVE=,$BITCOUNT=,$BITOP=,$BITPOS=,$BLPOP=,$BRPOP=,$BRPOPLPUSH=,$CLIENT=,$CLUSTER=,$CONFIG=,$DBSIZE=,$DEBUG=,$DECR=,$DECRBY=,$DEL=,$DISCARD=,$DUMP=,$ECHO=,$EVAL=,$EVALSHA=,$EXEC=,$EXISTS=,$EXPIRE=,$EXPIREAT=,$FLUSHALL=,$FLUSHDB=,$GEOADD=,$GEODIST=,$GEOHASH=,$GEOPOS=,$GEORADIUS=,$GEORADIUSBYMEMBER=,$GET=,$GETBIT=,$GETDEL=,$GETRANGE=,$GETSET=,$HDEL=,$HEXISTS=,$HGET=,$HGETALL=,$HINCRBY=,$HINCRBYFLOAT=,$HKEYS=,$HLEN=,$HMGET=,$HMSET=,$HSCAN=,$HSET=,$HSETNX=,$HSTRLEN=,$HVALS=,$INCR=,$INCRBY=,$INCRBYFLOAT=,$KEYS=,$LASTSAVE=,$LATENCY=,$LINDEX=,$LINSERT=,$LLEN=,$LPOP=,$LPUSH=,$LPUSHX=,$LRANGE=,$LREM=,$LSET=,$LTRIM=,$MEMORY=,$MGET=,$MIGRATE=,$MONITOR=,$MOVE=,$MSET=,$MSETNX=,$MULTI=,$OBJECT=,$PERSIST=,$PEXPIRE=,$PEXPIREAT=,$PFADD=,$PFCOUNT=,$PFMERGE=,$PSETEX=,$PTTL=,$PUBLISH=,$PUBSUB=,$QUIT=,$RANDOMKEY=,$READONLY=,$READWRITE=,$RENAME=,$RENAME
NX=,$REPLICAOF=,$RESTORE=,$RPOP=,$RPOPLPUSH=,$RPUSH=,$RPUSHX=,$SADD=,$SAVE=,$SCAN=,$SCARD=,$SCRIPT=,$SDIFF=,$SDIFFSTORE=,$SELECT=,$SET=,$SETBIT=,$SETEX=,$SETNX=,$SETRANGE=,$SINTER=,$SINTERSTORE=,$SISMEMBER=,$SLAVEOF=,$SLOWLOG=,$SMEMBERS=,$SMOVE=,$SORT=,$SPOP=,$SRANDMEMBER=,$SREM=,$STRLEN=,$SUNION=,$SUNIONSTORE=,$SSCAN=,$SWAPDB=,$SYNC=,$TIME=,$TOUCH=,$TTL=,$TYPE=,$UNLINK=,$UNWATCH=,$WATCH=,$XACK=,$XADD=,$XCLAIM=,$XDEL=,$XGROUP=,$XINFO=,$XLEN=,$XPENDING=,$XRANGE=,$XREAD=,$XREADGROUP=,$XREVRANGE=,$XTRIM=,$ZADD=,$ZCARD=,$ZCOUNT=,$ZINCRBY=,$ZINTERSTORE=,$ZLEXCOUNT=,$ZPOPMAX=,$ZPOPMIN=,$ZRANGE=,$ZRANGEBYLEX=,$ZRANGEBYSCORE=,$ZRANK=,$ZREM=,$ZREMRANGEBYLEX=,$ZREMRANGEBYRANK=,$ZREMRANGEBYSCORE=,$ZREVRANGE=,$ZREVRANGEBYLEX=,$ZREVRANGEBYSCORE=,$ZREVRANK=,$ZSCAN=,$ZSCORE=,$ZUNIONSTORE=,$UNKNOWN=

04:56:56.8383: acd-fbsent201.teleflora.org:26379/Interactive: Connecting...
04:56:56.8901: acd-fbsent201.teleflora.org:26379: BeginConnectAsync
04:56:56.9032: acd-fbsent203.teleflora.org:26379/Interactive: Connecting...
04:56:56.9032: acd-fbsent203.teleflora.org:26379: BeginConnectAsync
04:56:56.9041: 2 unique nodes specified (without tiebreaker)
04:56:56.9071: acd-fbsent201.teleflora.org:26379: OnConnectedAsync init (State=Connecting)
04:56:56.9071: acd-fbsent203.teleflora.org:26379: OnConnectedAsync init (State=Connecting)
04:56:56.9071: Allowing 2 endpoint(s) 00:00:05 to respond...
04:56:56.9141: Awaiting 2 available task completion(s) for 5000ms, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=5,Free=32762,Min=12,Max=32767)
04:56:56.9983: acd-fbsent203.teleflora.org:26379/Interactive: Connected 
04:56:57.0012: acd-fbsent201.teleflora.org:26379/Interactive: Connected 
04:56:57.0152: acd-fbsent203.teleflora.org:26379: Server handshake
04:56:57.0152: acd-fbsent203.teleflora.org:26379: Authenticating (password)
04:56:57.0152: acd-fbsent201.teleflora.org:26379: Server handshake
04:56:57.0152: acd-fbsent201.teleflora.org:26379: Authenticating (password)
04:56:57.1533: acd-fbsent203.teleflora.org:26379: Auto-configuring...
04:56:57.1640: acd-fbsent201.teleflora.org:26379: Auto-configuring...
04:56:57.1640: acd-fbsent203.teleflora.org:26379: Sending critical tracer (handshake): PING
04:56:57.1640: acd-fbsent201.teleflora.org:26379: Sending critical tracer (handshake): PING
04:56:57.1649: acd-fbsent203.teleflora.org:26379/Interactive: Writing: PING
04:56:57.1649: acd-fbsent203.teleflora.org:26379: Flushing outbound buffer
04:56:57.1729: acd-fbsent201.teleflora.org:26379/Interactive: Writing: PING
04:56:57.1729: acd-fbsent201.teleflora.org:26379: Flushing outbound buffer
04:56:57.1729: acd-fbsent203.teleflora.org:26379: OnEstablishingAsync complete
04:56:57.1739: acd-fbsent201.teleflora.org:26379: OnEstablishingAsync complete
04:56:57.1749: acd-fbsent203.teleflora.org:26379: Starting read
04:56:57.1849: acd-fbsent201.teleflora.org:26379: Starting read
04:56:57.2977: acd-fbsent201.teleflora.org:26379: Auto-configured (SENTINEL) server-type: sentinel
04:56:57.2977: acd-fbsent203.teleflora.org:26379: Auto-configured (SENTINEL) server-type: sentinel
04:56:57.3197: acd-fbsent201.teleflora.org:26379: Auto-configured (INFO) version: 5.0.3
04:56:57.3197: acd-fbsent201.teleflora.org:26379: Auto-configured (INFO) server-type: sentinel
04:56:57.3217: acd-fbsent203.teleflora.org:26379: Auto-configured (INFO) version: 5.0.3
04:56:57.3217: acd-fbsent203.teleflora.org:26379: Auto-configured (INFO) server-type: sentinel
04:56:57.3241: Response from acd-fbsent201.teleflora.org:26379/Interactive / PING: SimpleString: PONG
04:56:57.3277: Response from acd-fbsent203.teleflora.org:26379/Interactive / PING: SimpleString: PONG
04:56:58.0089: All 2 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=4,Free=32763,Min=12,Max=32767)
04:56:58.0089: Endpoint summary:
04:56:58.0089:   acd-fbsent201.teleflora.org:26379: Endpoint is ConnectedEstablished
04:56:58.0089:   acd-fbsent203.teleflora.org:26379: Endpoint is ConnectedEstablished
04:56:58.0089:   acd-fbsent201.teleflora.org:26379: Returned with success as Sentinel primary (Source: From command: PING)
04:56:58.0089:   acd-fbsent203.teleflora.org:26379: Returned with success as Sentinel primary (Source: From command: PING)
04:56:58.0099: acd-fbsent201.teleflora.org:26379: OnConnectedAsync completed (From command: PING)
04:56:58.0099: acd-fbsent203.teleflora.org:26379: OnConnectedAsync completed (From command: PING)
04:56:58.0159: Election summary:
04:56:58.0159:   Election: Multiple masters detected...
04:56:58.0159:   Election: Choosing master arbitrarily: acd-fbsent201.teleflora.org:26379
04:56:58.0159: acd-fbsent201.teleflora.org:26379: Clearing as RedundantMaster
04:56:58.0159: acd-fbsent203.teleflora.org:26379: Setting as RedundantMaster
04:56:58.0179: Endpoint Summary:
04:56:58.0209:   acd-fbsent201.teleflora.org:26379: Sentinel v5.0.3, master; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
04:56:58.0240:   acd-fbsent201.teleflora.org:26379: int ops=6, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
04:56:58.0259:   acd-fbsent201.teleflora.org:26379: Circular op-count snapshot; int: 0+6=6 (0.60 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
04:56:58.0259:   acd-fbsent203.teleflora.org:26379: Sentinel v5.0.3, master; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active; not in use: RedundantMaster
04:56:58.0259:   acd-fbsent203.teleflora.org:26379: int ops=6, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
04:56:58.0259:   acd-fbsent203.teleflora.org:26379: Circular op-count snapshot; int: 0+6=6 (0.60 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
04:56:58.0269: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
04:56:58.0269: Starting heartbeat...
04:56:58.0540: Total connect time: 1,424 ms
04:56:58.2056: Connecting (sync) on .NET Framework 4.8.4510.0 (StackExchange.Redis: v2.5.43.42402)
04:56:58.2056: 10.88.165.179:6379,serviceName=flowerbuyerdb,allowAdmin=True,password=*****

04:56:58.2065: 10.88.165.179:6379/Interactive: Connecting...
04:56:58.2066: 10.88.165.179:6379: BeginConnectAsync
04:56:58.2076: 1 unique nodes specified (with tiebreaker)
04:56:58.2076: 10.88.165.179:6379: OnConnectedAsync init (State=Connecting)
04:56:58.2076: Allowing 1 endpoint(s) 00:00:05 to respond...
04:56:58.2076: Awaiting 1 available task completion(s) for 5000ms, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=1,Free=32766,Min=12,Max=32767)
04:56:58.2226: 10.88.165.179:6379/Interactive: Connected 
04:56:58.2226: 10.88.165.179:6379: Server handshake
04:56:58.2226: 10.88.165.179:6379: Authenticating (password)
04:56:58.2276: 10.88.165.179:6379: Setting client name: OKC-L-4YMSQ13(SE.Redis-v2.5.43.42402)
04:56:58.2276: 10.88.165.179:6379: Auto-configuring...
04:56:58.2326: 10.88.165.179:6379: Requesting tie-break (Key="__Booksleeve_TieBreak")...
04:56:58.2336: 10.88.165.179:6379/Interactive: Writing: GET __Booksleeve_TieBreak
04:56:58.2336: 10.88.165.179:6379: Sending critical tracer (handshake): ECHO
04:56:58.2336: 10.88.165.179:6379/Interactive: Writing: ECHO
04:56:58.2336: 10.88.165.179:6379: Flushing outbound buffer
04:56:58.2336: 10.88.165.179:6379: OnEstablishingAsync complete
04:56:58.2336: 10.88.165.179:6379: Starting read
04:56:58.2535: 10.88.165.179:6379: Auto-configured (CONFIG) read-only replica: true
04:56:58.2555: 10.88.165.179:6379: Auto-configured (CONFIG) databases: 1
04:56:58.2595: 10.88.165.179:6379: Auto-configured (INFO) role: master
04:56:58.2615: 10.88.165.179:6379: Auto-configured (INFO) version: 5.0.3
04:56:58.2615: 10.88.165.179:6379: Auto-configured (INFO) server-type: standalone
04:56:58.2625: Response from 10.88.165.179:6379/Interactive / GET __Booksleeve_TieBreak: (null)
04:56:58.2635: Response from 10.88.165.179:6379/Interactive / ECHO: BulkString: 16 bytes
04:56:58.2736: 10.88.165.179:6379: OnConnectedAsync completed (From command: ECHO)
04:56:58.2736: All 1 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=2,Free=32765,Min=12,Max=32767)
04:56:58.2745: Endpoint summary:
04:56:58.2745:   10.88.165.179:6379: Endpoint is ConnectedEstablished
04:56:58.2745:   10.88.165.179:6379: Returned with success as Standalone primary (Source: From command: ECHO)
04:56:58.2745: Election summary:
04:56:58.2745:   Election: 10.88.165.179:6379 had no tiebreaker set
04:56:58.2745:   Election: Single master detected: 10.88.165.179:6379
04:56:58.2745: 10.88.165.179:6379: Clearing as RedundantMaster
04:56:58.2745: Endpoint Summary:
04:56:58.2745:   10.88.165.179:6379: Standalone v5.0.3, master; 1 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
04:56:58.2745:   10.88.165.179:6379: int ops=11, qu=0, qs=1, qc=0, wr=0, socks=1; sub ops=4, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
04:56:58.2745:   10.88.165.179:6379: Circular op-count snapshot; int: 0+11=11 (1.10 ops/s; spans 10s); sub: 0+4=4 (0.40 ops/s; spans 10s)
04:56:58.2745: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
04:56:58.2745: Starting heartbeat...
04:56:58.2745: Total connect time: 68 ms
}
    CoreNewLine: {char[2]}
    Encoding: {System.Text.UnicodeEncoding}
    FormatProvider: {en-US}
    NewLin`

**Comment by azharmahmood** [comment]
@NickCraver 
You were right, there were no replicas setup in this test environment, both nodes were masters. It works fine with primary/replica setup.
Question: is it a good idea to DemandReplica for cache get calls or not? I was thinking that since there are multiple replicas, it might offload some burden from the primary node.

**Comment by NickCraver** [comment]
That's up to your setup - there's no right or wrong here. You can PreferReplica without forcing it, though.

**Comment by azharmahmood** [comment]
Thank you sir, much appreciated.
