### ISSUE TITLE
Await on ITransaction async method will get blocked.

### ISSUE THREAD

**Issue by FantasticGithubUser** [StackExchange/StackExchange.Redis#2252]
`[TestMethod]`
		`public async Task ConnectionTest()`
		`{`
			`ConnectionMultiplexer multiplexer = await ConnectionMultiplexer.ConnectAsync(connectionString);`
			`var database = multiplexer.GetDatabase();`
			`var result = await database.ExecuteAsync("scan", 0);`
			`var trans = database.CreateTransaction();`
			`var lockResult = await trans.LockTakeAsync("test", "test", TimeSpan.FromSeconds(10));`
			`var transResult = await trans.ExecuteAsync();`
			`Trace.WriteLine(result);`
		`}`

The LockTakeAsync method here can never complete the async task.

I wonder if the await operation is not supported here.
Because the code

`var json = JsonConvert.SerializeObject(people);`
					`trans.HashSetAsync("People", people.Id.ToString(), json);`
					`var updated = JsonConvert.SerializeObject(people with { Age = 20 });`
					`trans.HashSetAsync("People", people.Id.ToString(), updated);`
					`await trans.ExecuteAsync();`

works fine.

**Comment by mgravell** [comment]
You need to defer your await in this case. Nothing is sent until the
ExecuteAsync. You can, however, store the result in a task, and await it
*after the execute*, to see the result:

var pending = trans.LockTakeAsync(...);
...
var tranResult = await trans.ExecuteAsync();
var lockResult = await pending;

---

Note, however, that the lock operation itself is atomic, and adding a
transaction won't make it any more atomic. Quite honestly, it is *very
hard* to work with redis transactions correctly, and these days people
usually use Lua instead (the ScriptEvaluate API)

**Comment by FantasticGithubUser** [comment]
Thanks a lot! That's tricky though reasonable.
