### ISSUE TITLE
Bulk delete keys inside transaction - Blocks Multiplexer?

### ISSUE THREAD

**Issue by SenthilKGandhi** [StackExchange/StackExchange.Redis#2256]
Would the below code block the multiplexer on ExecuteAsync ?

ITransaction trans = db.CreateTransaction();
foreach (var childKey in childKeys)
{
	trans.KeyDeleteAsync(childKey); // key value delete
}

trans.KeyDeleteAsync(parentKey); // set delete (set keeps list of childKeys)
return trans.ExecuteAsync();

**Comment by mgravell** [comment]
It shouldn't do, no - however, some thoughts:

1. it may be simpler to just use the multi-key version of KeyDeleteAsync
2. if the values are string-ish, it *may* (usage dependent) be possible to
use a hash (keyed against the parent, with the child values in the hash
name token) in such a way as that you only need to do a single delete to
nuke everything

**Comment by SenthilKGandhi** [comment]
1. Thanks for pointing out to multi-key version of KeyDeleteAsync. I replaced trans with multi-key delete. Would you see any issues (particularly blocking other requests in Multiplexer) if I delete, for example, more than 1000 keys?
** hope UNLINK comes to the rescue
2. Though all the keys are strings, and using Redis HashSet *may* seem appropriate, we wanted to provide the functionality to have a dedicated expiration at the hash set field level, which is currently not supported. So we are going with Redis Set (has a list of related keys) and Individual key-value pairs with their expiration, and betting on the transactions on the write-side to achieve consistency. 

When adding a child key

> ITransaction trans = db.CreateTransaction();
> trans.StringSetAsync(childKey, childValue expiry: childKeyExpiry);
> trans.SetAddAsync(groupKey, childKey);
> return trans.ExecuteAsync();

When removing a child key
 
> ITransaction trans = db.CreateTransaction();
>     trans.KeyDeleteAsync(childKey);
>     trans.SetRemoveAsync(parentKey, childKey);
>     return trans.ExecuteAsync();


When removing a parent along with child keys

> var childKeys = await db.SetMembersAsync(parentKey);
> ... // convert to RedisKey[] ...
> await db.KeyDeleteAsync(... parentKey + childKeys ..)


** If a child key expires, we cannot update the parent Set, and we can live with this constraint

**Comment by mgravell** [comment]
I can't guage the impact of deleting a large number of keys; it isn't fixed
- it depends on:

- key size
- payload size
- server hardware specification
- concurrent / ambient load on the server
- replication / cluster configuration
- persistence configuration
- random fluctuations in the moon's orbit

OK, probably not the last one, but you get the point

The beat thing to suggest is: try it locally with your setup, and see what
the impact is!

Marc

**Comment by SenthilKGandhi** [comment]
We tested the our use cases with a few hundred key deletes and it is performing well. Thanks @mgravell 

does multiple-key-deletes, using KeyDeleteAsync overload, provide consistency(all keys are deleted OR nothing gets deleted)?

**Comment by mgravell** [comment]
Yes (at least, within the atomicity level of redis itself)
