### ISSUE TITLE
Configure SSL connection to a Redis server

### ISSUE THREAD

**Issue by claudiorafaels** [StackExchange/StackExchange.Redis#2258]
How to configure SSL connection to a Redis server with Private Key, Public Key, Authority and Password? I can successfully connect to "Another Redis Desktop" but not to StackExchange.Redis 2.6.66

**Comment by claudiorafaels** [comment]
![image](https://user-images.githubusercontent.com/1093885/192177525-cc571469-bf72-404b-b0f1-fb20c618a222.png)

**Comment by RogerSep** [comment]
See if this works for you
https://docs.redis.com/latest/rs/references/client_references/client_csharp/#tls

**Comment by NickCraver** [comment]
Advice is above on this (thanks @RogerSep!) - closing out to tidy up :)
