### ISSUE TITLE
Azure server maintenance subscriptions not working

### ISSUE THREAD

**Issue by mirekkukla** [StackExchange/StackExchange.Redis#2263]
Despite a fairly straightforward redis setup, we never receive any Azure server maintenance events in our fully-Azure-hosted setup. Our redis configuration is rather straightforward, and with subscription configured as detailed [in the docs](https://github.com/StackExchange/StackExchange.Redis/blob/main/docs/ServerMaintenanceEvent.md). Relevant configuration excerpt:

```
logger.LogInformation("Redis connection multiplexer starting up"); // to confirm logging is working

var options = ConfigurationOptions.Parse("our_cache.redis.cache.windows.net:6380,password=our_password,ssl=True,abortConnect=False");
options.AllowAdmin = true;
options.AbortOnConnectFail = false;
connectionMultiplexer = ConnectionMultiplexer.Connect(options);

connectionMultiplexer.ServerMaintenanceEvent += (_, e) =>
{
    // never observed in the logs
    logger.LogInformation("{Msg}", e is AzureMaintenanceEvent azureEvent
        ? $"Azure maintenance event: {azureEvent.ToJson()}"
        : $"Unknown redis maintenance event {e.GetType()}: {e.ToJson()}");
};
```

We use a single long-lived multiplexer (held in an injected singleton service). Further configuration details:
* Our server is hosted as an asp.net core Azure app service running on .net6 using `StackExchange.Redis` version 2.6.66
* Our redis cache is an Azure managed redis cache running redis 6 ("basic" tier in staging and "standard" in production)
* Our Azure network configuration is "out of the box" (no virtual networks, firewalls, ip whitelisting, etc)
* We use application insights as our logging solution (confirmed to work per first line in the code snippet above)
* We've had no other issues related to our redis configuration (we've been using redis for years)

Some findings during debugging:
* When running the server locally and connecting to the Azure cache, I've confirmed the `AzureOptionsProvider` is correctly being loaded during configuration.
* The Azure redis console suggests that there is a registered subscription:
```
>pubsub channels
1) "AzureRedisEvents"
2) "__Booksleeve_MasterChanged"
>pubsub numsub AzureRedisEvents
1) "AzureRedisEvents"
2) (integer) 1
```

Finally, the code above has been live for months, during which time we've had numerous instances in which Azure clearly states a server maintenance event _has_ occurred (the most recent being this morning). The following image comes from Azure's "network connection" diagnostics page for our cache:
<img width="908" alt="image" src="https://user-images.githubusercontent.com/903370/192911162-72e48fc2-6577-45f5-9486-a3b68f957b32.png">

Since we can't trigger the issuance of Azure maintenance ourselves, we're at a bit of a loss as to how further debug, and are beginning to wonder if this isn't a bug.

Any further guidance would be much appreciated, and thanks in advance!

**Comment by NickCraver** [comment]
If you can give version 2.6.70 a try (currently on NuGet) it's possible that the lazy subscription connection issue under some circumstances could race. What we want to do here though is also add a "last relevant maintenance event" to exception logs and we talked about that this week - hope to add it in pretty soon which may help diagnose here.

**Comment by NickCraver** [comment]
cc @philon-msft

**Comment by philon-msft** [comment]
Actually you can simulate a maintenance event by rebooting a cache node (see https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-administration#reboot). If everything is working properly, your client application will receive ServerMaintenanceEvents corresponding to the reboot.
