### ISSUE TITLE
Could large times observed on  `SentToResponse` profile-metric be affected by connection pool issues on client side?

### ISSUE THREAD

**Issue by plachor** [StackExchange/StackExchange.Redis#2266]
Hi we connect to AWS Redis instance (ElasticCache for Redis v6.0.5) within same network form same availability zone. From time to time we observe timeouts on HMGET,  commands to Redis.

`StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 624ms elapsed, timeout is 500ms), command=HMGET, next: HMGET REDACTED_KEY, inst: 0, qu: 0, qs: 2, aw: False, rs: ReadAsync, ws: Idle, in: 10386, serverEndpoint: REDACTED_ENDPOINT, mc: 1/1/0, mgr: 10 of 10 available, clientName: REDACTED_CLIENT, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=6,Free=32761,Min=1,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

1) We are using version `2.2.4` of `StackExchange.Redis`. According to docs (if I understand it correctly) since we do not alter `SocketManager` default should not be affected by this thread pool starvation issue reported for previous `v1.x` version of `StackExchange.Redis` ?

2) We enabled command profiling and observe that  most of time is spend on `SentToResponse`  statistic which would correlate with this `qs > 0` in log above. So second question is: can we exclude any thread-starvation issues when all latency is observed on `SentToResponse` metric ?

We are searching for explanation as AWS Redis instance is not reporting any slow-log entries that would match observed times on `SentToResponse` metric. Also we tried to bump Redis instance to higher tier but also without any success. Those timeouts do not occur for each request but rather rarely. For 76K requests only 300 are above 100ms. The object that we request is small bellow 1KB.

**Comment by NickCraver** [comment]
Can you give me an idea of payload here? You said it's small below 1KB but is that _per key_ or total? What's a total batch look like, in the worst case - that's what we're hitting on a timeout here.

The time you're observing would include _bytes across the wire_ coming back, so if we get a large payload or _we're behind another large payload_, you'd see these kind of timings. It can help to look at the command immediately before as an example.

I would recommend upgrading to the latest client library which has additional goodies - right now your timeout of 500ms isn't actually consistent, it only triggers every 1000ms so you may be +/- 1000ms fidelity on the timeout evaluation and actually be exceeding 500ms far more often than we alert on now. There are a few new options in the latest client to control this if you really want lower timeouts (e.g. evaluated more often) - this can help narrow the issue too.

**Comment by plachor** [comment]
Hi @NickCraver, this 1KB was per object under key. Key itself is like 3-guid-s long. Most of the time this is like one or two Redis requests per http-request however many http-requests are occurring in parallel.

I've updated my dependency on `StackExchange.Redis` to `2.6.66`. I also let it work for some time so I can gather new results.
I still observe those timeouts - library upgrade has not introduced any noticeable change in observed statistics.

For past 24h I observed:
* 426 414 calls that were executed under 1.32ms (95% of requests bellow that time)
* 1 821 calls that took over 100ms to execute (of which 95% of requests were bellow 200ms)

Sample exception for latest version:
>Timeout awaiting response (outbound=62KiB, inbound=0KiB, 736ms elapsed, timeout is 500ms), command=HMGET, next: HMGET REDACTED_KEY, inst: 0, qu: 0, qs: 0, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 21649, serverEndpoint: REDACTED_SERVER, mc: 1/1/0, mgr: 10 of 10 available, clientName: REDACTED_CLIENT(SE.Redis-v2.6.66.47313), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=3,Free=32764,Min=1,Max=32767), POOL: (Threads=7,QueuedItems=7,CompletedItems=1649660), Local-CPU: unavailable, v: 2.6.66.47313 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Before I introduce more debug info I would like to understand if I can exclude issue described in my initial question. So let me  ask my questions again:**
1) We observe that for all requests significant amount of time is reported on `SentToResponse` statistic (like 99.9% of time is there). So question is can this metric misreport such times due to the issue that relates to `ThreadPool` or can we safely assume this must be a network issue (on the other end AWS Redis slow logs do not report any slow requests)?
2) According to docs (if I understand it correctly) since we do not alter SocketManager - than default setting should not be affected by this thread pool starvation issue reported for previous v1.x version of StackExchange.Redis ([link to docs](https://stackexchange.github.io/StackExchange.Redis/Timeouts#are-you-seeing-a-high-number-of-busyio-or-busyworker-threads-in-the-timeout-exception)) ?

Additionally I've observed strange times reported for `EnqueuedToSending` and `SentToResponse` in microservice that is hosting SignalR server. On initial start of microservice random instance is reporting strange times there:
```json
       "ProfiledCommand": {
          "ElapsedTime": "00:00:00.9839256",
          "RetransmissionOf": false, // null
          "Flags": "2048",
          "CommandCreated": "2022-10-18T13:46:35.8338460Z",
          "EnqueuedToSending": "-12.23:08:39.2607852",
          "SentToResponse": "12.23:08:40.2388732",
          "ResponseToCompletion": "00:00:00",
          "Db": -1,
          "Command": "SUBSCRIBE",
          "CreationToEnqueued": "00:00:00.0058376",
          "RetransmissionReason": null
        },
```
Could there be some issue with marking [ `RequestSentTimeStamp`](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/Profiling/ProfiledCommand.cs#L26-L28) for case of initial `SUBSCRIBE` command issued just after bootstrap. Just two metrics are invalid so this would indicate issue with `RequestSentTimeStamp`. For other commands I have not observed this issue. It seems to be occurring just after restart.

**Comment by NickCraver** [comment]
1. Given your payload sizes in the buffer, my assumption would be "actual time on the network, while bursting".
2. Correct it's not related _for that reason_. That doesn't rule out general thread pool exhaustion inside the application resulting in stalls though. That can happen to any .NET app when we exceed what the pool or CPU it self can handle. I'm just being thorough though - I'm reasonably confident that's _not_ happening here based on `IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=3,Free=32764,Min=1,Max=32767), POOL: (Threads=7,QueuedItems=7,CompletedItems=1649660)`.

If a subscribe can't connect immediately after startup, it'll queue subscription messages to be be sent as soon as it can connect and subscribe and send them. It's possible there's something in that case there the timing isn't set, will try and see.

**Comment by plachor** [comment]
As to the topic:
> If a subscribe can't connect immediately after startup, it'll queue subscription messages to be be sent as soon as it can connect and subscribe and send them. It's possible there's something in that case there the timing isn't set, will try

I've changed timeouts from 500ms to 2s for connection multiplexer used by SignalR Server and now when instance is recreated I do not observe those strange times. So to reproduce you could try to set some rigorous timeout in conjunction with SingalR.

**Comment by plachor** [comment]
Hi, it turned out that it was caused by CPU throthling. It was not visible on CPU limit and request usage graphs due to metric resolution  in our k8s env 😞. Without limit on CPU Im not observing those anymore. Thx for your input.
