### ISSUE TITLE
Improve performance, by directly exposing ReadOnlySpan<Byte> from RedisValue

### ISSUE THREAD

**Issue by andhesky** [StackExchange/StackExchange.Redis#2271]
Scenario:
We use Redis as a lookaside cache for complex C# objects. We have a local cache on each frontend VM for a webservice which queries Redis on a local cache miss. If Redis is also a cache miss, we query a backend service to get the object, serialize it to JSON then write back to Redis. We have about a 60% hit rate on the cache which means about 40% of our requests are going through all steps of this flow.

Issue:
While profiling, we find a lot of time is spent in System.Text.Encoding.GetString(byte*,int) which is called via Format.GetString() via RedisValue's implicit string converter.

Potential solution:
[JsonSerilizer.Deserialize](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserialize) can operate directly on a readonlyspan<byte>, if RedisValue exposed this buffer directly, we could bypass the conversion from the UTF-8 Buffer to the UTF-16 C# String.

Applying to write APIs:
If this works, we can extend the write APIs to work the same way by writing directly to a UTF-8 buffer using the [SerializeToUtf8Bytes](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.serializetoutf8bytes) method. I have not look as deeply at the code to see what is required there, but could investigate more if the overall approach seems plausible.

Please let me know if this seems reasonable. It is useful enough to my service that I can send a PR, I just want to make sure it is aligned with the goals of the project before diving too deep.

Thanks.

**Comment by andhesky** [comment]
Sorry, I guess there is an implicit conversion to ReadOnlyMemory which should work to generate a ReadOnlySpan. I'll take a look and see if there is anything else needed.

**Comment by mgravell** [comment]
Note: if you're doing things with `StringGet`, you may also want to look at `StringGetLease`, which is far more "raw", and exposes values more directly as byte chunks *and* supports buffer pooling more naturally

beyond that; yes there is a memory-conversion, which should be fine for most scenarios, although there is a bit of a weird hybrid thing that goes on the data can be represented by a simple integer etc
