### ISSUE TITLE
Redis timing out

### ISSUE THREAD

**Issue by vraghuvaran** [StackExchange/StackExchange.Redis#2272]
I am getting redis timeout exception as below

Exception occurred in RedisService CheckAlivenessRedis StackExchange.Redis.RedisTimeoutException: The timeout was reached before the message could be written to the output buffer, and it was not sent, command=SET, timeout: 5000, inst: 0, qu: 0, qs: 0, aw: False, bw: CheckingForTimeout, rs: NotStarted, ws: Idle, in: 0, serverEndpoint: 0.9.22.226:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: InferenceService-0(SE.Redis-v2.6.66.47313), IOCP: (Busy=0,Free=1000,Min=80,Max=1000), WORKER: (Busy=0,Free=32767,Min=80,Max=32767), POOL: (Threads=21,QueuedItems=0,CompletedItems=4050), v: 2.6.66.47313 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

Below is my code:

ConnectionMultiplexer conn = await ConnectionMultiplexer.ConnectAsync(new ConfigurationOptions
                {
                    EndPoints = { _redisConfiguration.RedisHost, _redisConfiguration.RedisPort] },
                    Password = _redisConfiguration.RedisKey,
                    Ssl = _redisConfiguration.sslEnabled,
                    ConnectRetry = 8,
                    ConnectTimeout = 10000,
                    AbortOnConnectFail = false
                });
database = conn.GetDatabase();
var stringSetResult = await database.StringSetAsync(key, value);
var stringGetResult = await database.StringGetAsync(key);

By looking at the stacktrace, i see that error occurred at stringset. But i am not sure why its happened. Other thing i observed is i set ConnectTimeout to 10000 but in the exception message its showing as 5000 and port is also shown wrong.

**Comment by NickCraver** [comment]
To see the error, set `AbortOnConnectFail=true` instead, so we see why it's not connecting :) That'll throw a better error, and you can pass a logger into the ConnectAsync method to get full details. With those, we can help advise.

**Comment by vraghuvaran** [comment]
This is the error message after setting AbortOnConnectFaile=true.

 Exception occurred in RedisService CheckAlivenessRedis StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.

Did some debug, looks like it was trying to connect to 6379 which is not enabled and i set 6380 in configuration options. I am not sure why its showing error.

**Comment by NickCraver** [comment]
Can you double check your endpoint config? The issue has `EndPoints = { _redisConfiguration.RedisHost, _redisConfiguration.RedisPort] },` which isn't valid code, so I'm wondering if you're accidentally passing the port _as a second endpoint_, rather than the port of the host.

**Comment by vraghuvaran** [comment]
No i checked my logs and the config i passed is correct. Infact i am able to run in my local with the same config
