### ISSUE TITLE
Transactions hit timeout checking preconditions even after the connection multiplexer is in 'ConnectedEstablished' state

### ISSUE THREAD

**Issue by sumeetbedi** [StackExchange/StackExchange.Redis#228]
I'm hitting what seems to be an issue with transactions after a connection multiplexer recovers from connectivity issues with the redis server.
From the logs, the failure seems to be in executing transactions -- **due to timeout checking preconditions** -- when the connection multiplexer transitions from Disconnected -> Connecting -> ConnectedEstablishing-> ConnectedEstablished. 

In order to reproduce the issue, I wrote a simple application to do transaction based writes periodically (every 2secs).
One way to reproduce this is to run  before starting the Redis server allowing initial operations to fail with the  ---> StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: ... Then, start the redis-server and observe the connection goes into a connected state but transactions continue to fail with this error. 

You can also stop and restart the redis-server after a few seconds while the application is running to get into this state.

Sometimes the connection multiplexer recovers out of this erroneous state within 5-6 seconds and transactions writes start working but sometime it seems to get in this state for a period of a few minutes (maybe longer).

**I'm using 2.8.17 x64 redis-server and version 1.0.450 of StackExchange.Redis 
and am running with AbortOnConnectFail =  false.**

**LOGS**
**SE Logs showing Connection multiplexer recovery**

3255 70310ms on 7 ~ Subscription/localhost:6379: OnHeartbeat: Connecting
3266 71090ms on 1 ~ TryPushMessageToBridge: No server or server unavailable - aborting: [0]:HGETALL sample:35 (HashEntryArrayProcessor)
3267 71324ms on 4 ~ OnHeartbeat: heartbeat
3268 71324ms on 4 ~ Interactive/localhost:6379: OnHeartbeat: Disconnected
3269 71324ms on 4 ~ OnHeartbeat: Resurrecting Interactive/localhost:6379
3273 71324ms on 4 ~ Subscription/localhost:6379: OnHeartbeat: Disconnected
3274 71324ms on 4 ~ OnHeartbeat: Resurrecting Subscription/localhost:6379
3288 72338ms on 5 ~ OnHeartbeat: heartbeat
3289 72338ms on 5 ~ Interactive/localhost:6379: OnHeartbeat: Disconnected
3290 72338ms on 5 ~ OnHeartbeat: Resurrecting Interactive/localhost:6379
3294 72338ms on 5 ~ Subscription/localhost:6379: OnHeartbeat: Disconnected
3295 72338ms on 5 ~ OnHeartbeat: Resurrecting Subscription/localhost:6379
3300 72837ms on 16 ~ ChangeState: Interactive state changed from Connecting to ConnectedEstablishing
3308 72837ms on 17 ~ ChangeState: Subscription state changed from Connecting to ConnectedEstablishing
3345 72837ms on 13 ~ ChangeState: Subscription state changed from ConnectedEstablishing to ConnectedEstablished
**3422 72853ms on 13 ~ ChangeState: Interactive state changed from ConnectedEstablishing to ConnectedEstablished**

**SE logs showing Transaction failure even after connection recovery**
3473 73102ms on 1 ~ TryPushMessageToBridge: Queueing on server: [0]:HGETALL sample:36 (HashEntryArrayProcessor)
3474 73102ms on 1 ~ Interactive/localhost:6379: Now pending: 1
3475 73102ms on 1 ~ RequestWrite: Requesting write: localhost:6379/Interactive
3476 73102ms on 3 ~ Interactive/localhost:6379: Writing queue from bridge
3477 73102ms on 3 ~ Interactive/localhost:6379: Now pending: 0
3478 73102ms on 3 ~ Interactive/localhost:6379: Writing: [0]:HGETALL sample:36 (HashEntryArrayProcessor)
3479 73102ms on 3 ~ Interactive/localhost:6379: Nothing to write; exiting
3480 73102ms on 3 ~ Interactive/localhost:6379: Exiting writer
3481 73102ms on 3 ~ Interactive/localhost:6379: Writing queue from bridge
3482 73102ms on 3 ~ Interactive/localhost:6379: Nothing to write; exiting
3483 73102ms on 3 ~ Interactive/localhost:6379: Exiting writer
3484 13 ~ ReadImpl: Read sockets: 1
3485 73102ms on 13 ~ Interactive#57@localhost:6379: More bytes available: 4 (4)
3486 73102ms on 13 ~ Interactive#57@localhost:6379: MultiBulk: 0 items
3487 73102ms on 13 ~ Interactive#57@localhost:6379: Matching result...
3488 73102ms on 13 ~ Interactive#57@localhost:6379: Response to: [0]:HGETALL sample:36 (HashEntryArrayProcessor)
3489 73102ms on 13 ~ StackExchange.Redis.ResultProcessor+HashEntryArrayProcessor: Completed with success: MultiBulk: 0 items (HashEntryArrayProcessor)
3490 73102ms on 13 ~ localhost:6379/Interactive: Queueing for asynchronous completion
3491 73102ms on 13 ~ localhost:6379/Interactive: Starting new async completion worker
3492 73102ms on 13 ~ Interactive#57@localhost:6379: Processed: 1
3493 73102ms on 13 ~ Interactive#57@localhost:6379: Buffer exhausted
3494 73102ms on 11 ~ localhost:6379/Interactive: Completing async (ordered): [0]:HGETALL sample:36 (HashEntryArrayProcessor)
3495 73102ms on 11 ~ Transaction: Wrapping HDEL
3496 73102ms on 11 ~ Transaction: Wrapping HMSET
3497 73102ms on 11 ~ Transaction: Wrapping EXPIRE
3498 73102ms on 11 ~ TryPushMessageToBridge: Queueing on server: [0]:EXEC (TransactionProcessor)
3499 73102ms on 11 ~ Interactive/localhost:6379: Now pending: 1
3500 73102ms on 11 ~ RequestWrite: Requesting write: localhost:6379/Interactive
3501 73102ms on 11 ~ localhost:6379/Interactive: Async completion worker processed 1 operations
3502 73102ms on 3 ~ Interactive/localhost:6379: Writing queue from bridge
3503 73102ms on 3 ~ Interactive/localhost:6379: Now pending: 0
3504 73102ms on 3 ~ Interactive/localhost:6379: Writing: [0]:EXEC (TransactionProcessor)
3505 73102ms on 3 ~ GetMessages: Flushing and waiting for precondition responses
3506 13 ~ ReadImpl: Read sockets: 1
3507 73102ms on 13 ~ Interactive#57@localhost:6379: More bytes available: 9 (9)
3508 73102ms on 13 ~ Interactive#57@localhost:6379: SimpleString: OK
3509 73102ms on 13 ~ Interactive#57@localhost:6379: Matching result...
3510 73102ms on 13 ~ Interactive#57@localhost:6379: Response to: [0]:WATCH sample:36 ((n/a))
3511 13 ~ Message: No result-box to complete for WATCH
3512 73102ms on 13 ~ localhost:6379/Interactive: Completed synchronously: [0]:WATCH sample:36 ((n/a))
3513 73102ms on 13 ~ Interactive#57@localhost:6379: Integer: 0
3514 73102ms on 13 ~ Interactive#57@localhost:6379: Matching result...
3515 73102ms on 13 ~ Interactive#57@localhost:6379: Response to: [0]:HEXISTS sample:36 (ConditionProcessor)
3516 13 ~ TryValidate: exists: False; expected: False; voting: True
3517 73102ms on 13 ~ StackExchange.Redis.Condition+ConditionProcessor: Completed with success: Integer: 0 (ConditionProcessor)
3518 73102ms on 13 ~ localhost:6379/Interactive: Completed synchronously: [0]:HEXISTS sample:36 (ConditionProcessor)
3519 73102ms on 13 ~ Interactive#57@localhost:6379: Processed: 2
3520 73102ms on 13 ~ Interactive#57@localhost:6379: Buffer exhausted
3521 73352ms on 12 ~ OnHeartbeat: heartbeat
3522 73352ms on 12 ~ Interactive/localhost:6379: OnHeartbeat: ConnectedEstablished
3523 73352ms on 12 ~ Subscription/localhost:6379: OnHeartbeat: ConnectedEstablished
3524 74366ms on 7 ~ OnHeartbeat: heartbeat
3525 74366ms on 7 ~ Interactive/localhost:6379: OnHeartbeat: ConnectedEstablished
3526 74366ms on 7 ~ Subscription/localhost:6379: OnHeartbeat: ConnectedEstablished
**3527 75099ms on 3 ~ GetMessages: Timeout checking preconditions**
**3528 75099ms on 3 ~ GetMessages: Aborting: canceling wrapped messages**
3529 75099ms on 3 ~ localhost:6379/Interactive: Completed synchronously: [0]:HDEL sample:36 (BooleanProcessor)
3530 75099ms on 3 ~ localhost:6379/Interactive: Completed synchronously: [0]:HMSET sample:36 (ExpectBasicStringProcessor)
3531 75099ms on 3 ~ localhost:6379/Interactive: Queueing for asynchronous completion
3532 75099ms on 3 ~ localhost:6379/Interactive: Starting new async completion worker
**3533 75099ms on 3 ~ GetMessages: End ot transaction: UNWATCH**
3534 75099ms on 6 ~ localhost:6379/Interactive: Completing async (ordered): [0]:EXPIRE sample:36 (BooleanProcessor)
3535 75099ms on 6 ~ localhost:6379/Interactive: Async completion worker processed 1 operations
3536 75099ms on 3 ~ Interactive/localhost:6379: Nothing to write; exiting
3537 75099ms on 3 ~ Interactive/localhost:6379: Exiting writer
3538 75099ms on 3 ~ Interactive/localhost:6379: Writing queue from bridge
3539 75099ms on 3 ~ Interactive/localhost:6379: Nothing to write; exiting
3540 75099ms on 3 ~ Interactive/localhost:6379: Exiting writer
3541 13 ~ ReadImpl: Read sockets: 1
3542 75099ms on 13 ~ Interactive#57@localhost:6379: More bytes available: 5 (5)
3543 75099ms on 13 ~ Interactive#57@localhost:6379: SimpleString: OK
3544 75099ms on 13 ~ Interactive#57@localhost:6379: Matching result...
3545 75099ms on 13 ~ Interactive#57@localhost:6379: Response to: [0]:UNWATCH (TransactionProcessor)
3546 75099ms on 13 ~ SetResultCore: Acknowledging UNWATCH (aborted electively)
3547 75099ms on 13 ~ StackExchange.Redis.RedisTransaction+TransactionProcessor: Completed with success: SimpleString: OK (TransactionProcessor)
3548 75099ms on 13 ~ localhost:6379/Interactive: Queueing for asynchronous completion
3549 75099ms on 13 ~ localhost:6379/Interactive: Starting new async completion worker
3550 75099ms on 13 ~ Interactive#57@localhost:6379: Processed: 1
3551 75099ms on 13 ~ Interactive#57@localhost:6379: Buffer exhausted
3552 75099ms on 4 ~ localhost:6379/Interactive: Completing async (ordered): [0]:UNWATCH (TransactionProcessor)
3553 75099ms on 4 ~ localhost:6379/Interactive: Async completion worker processed 1 operations

I have turned on tracing for stackexchange redis so I can provide more logs as needed.

**Comment by mgravell** [comment]
Closing; please see #871
