### ISSUE TITLE
Timeout connecting to azure redis cache 

### ISSUE THREAD

**Issue by destasys** [StackExchange/StackExchange.Redis#2281]
Any idea what could be causing this? 

StackExchange.Redis.RedisTimeoutException: The timeout was reached before the message could be written to the output buffer, and it was not sent, command=EVAL, timeout: 
    5000, inst: 0, qu: 0, qs: 10, aw: False, bw: CheckingForTimeout, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, 
    serverEndpoint: my-app-redis-cache.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: 
    api-rtw(SE.Redis-v2.6.70.49541), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=0,Free=32767,Min=1,Max=32767), POOL: (Threads=3,QueuedItems=0,CompletedItems=34150), 
    v: 2.6.70.49541 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)   
    at StackExchange.Redis.RedisDatabase.ScriptEvaluateAsync(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) 
    in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1550   
    at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.

**Comment by NickCraver** [comment]
I'd take a look at SLOWLOG on the Redis server-side here and see what's in the log. There's nothing standing out in your numbers - everything indicates we're waiting for a response from a script EVAL and it's likely that's taking a long time server-side.

**Comment by destasys** [comment]
Thanks @NickCraver. I did check the `SLOWLOG` nothing stands out. The screen shot is below (it is a remote azure redis cache service - via stunnel).   

![image](https://user-images.githubusercontent.com/49215025/197843955-4880aece-a21f-498c-9002-97cfccba876a.png)

**Comment by Dougxian** [comment]
i found a article about the error
https://stackexchange.github.io/StackExchange.Redis/ThreadTheft.html

**Comment by NickCraver** [comment]
@destasys Apologies I misread the initial message - this is entirely different. Do you know what the call looks like leading into this? Looks like we couldn't get a write lock on the outbound socket so I'm curious when and how often this error happens - can you reproduce it, or totally random?

**Comment by destasys** [comment]
np @NickCraver. We are working with MSFT engineer, and he is investigating a TLS issue.  Since it is not related to this package, I am closing the issue. Thank you.
