### ISSUE TITLE
should RedisValue.HasValue check for valueBlob != IntegerSentinel?

### ISSUE THREAD

**Issue by jamesmanning** [StackExchange/StackExchange.Redis#229]
Currently a RedisValue created from an int or long will have valueBlob == IntegerSentinel, and since IntegerSentinel is an empty array, HasValue will be false.

https://github.com/StackExchange/StackExchange.Redis/blob/12e611401d86a63388758c3470840801cb4ee79a/StackExchange.Redis/StackExchange/Redis/RedisValue.cs#L52-L72

This might be ByDesign, but it seemed strange since it appears RedisValue instances holding an int or long still have a 'value', just stored in the valueInt64 field instead of the valueBlob one.

**Comment by NickCraver** [comment]
@mgravell did we ever revisit this? Appears to still be an issue in current code:

```c#
public bool IsNullOrEmpty => valueBlob == null || (valueBlob.Length == 0 && !(valueBlob == IntegerSentinel));
public bool HasValue => valueBlob?.Length > 0;
```
A simple test locally:
```c#
RedisValue val = 4;
Console.WriteLine(val.IsNullOrEmpty); // false - correct
Console.WriteLine(val.HasValue);      // false - incorrect
```

IMO, the best fix here is to simply make `HasValue`:
```c#
public bool HasValue => !IsNullOrEmpty;
```

I've opened up a PR (#840) to resolve this.
