### ISSUE TITLE
SER 2.5.61 version: Getting stale read even after almost 6 seconds after write

### ISSUE THREAD

**Issue by ShrikantAdp** [StackExchange/StackExchange.Redis#2290]
Using Redis 6.2.10 with SER 2.5.61 with connect string

'nn.nn.nn.nnn:12001,allowAdmin=false,password=xyz,configChannel=,tiebreaker=,syncTimeout=500,configCheckSeconds=0,responseTimeout=1000'

**Issue:** Not getting the latest key value after almost 6 seconds. Below are the timings of the operation showing timelines

_--Event detects value to be added_
1. 2022-10-29 11:01:41,244 DEBUG - component=ASLSDC=Provisioning.EventHandler;IID=20095203;UID=myUid;Ctx=FStateChangeProvisioningEventHandler;: SetupAimMca enabled. ADD TO IGM >>>>True for IID=20095203

_--Updated value save to db_
2. 2022-10-29 11:01:41,335 DEBUG - component=ASLSDC=Core;IID=20095203;UID=myUid;Ctx=<no context>;: IGDataAccess AddInstallationGroupMember for >>>>Aim.Mca iid 20095203

--_SER driver call made includes new value **Aim.Mca**_
3. 2022-10-29 11:01:41,608 DEBUG - Data=RedisDriver.SetAdd - key: InstGroupsForIID:20095203, values: [BranchCode.A2,RunAccountantPortal,**Aim.Mca**]

_--Looking up the new value, expected to see latest value but gets stale data??_
4. 2022-10-29 11:01:47,532 ERROR -  Incorrect group membership data for IID 20095203, according to property Aim.Mca.Enabled.RunMca

Are there any known latency issues? There are 0 exceptions or errors during the above test window, any ideas?

**Comment by ShrikantAdp** [comment]
Correction, Step#3 is after the Aim.Mca has been add to Redis and returned without exceptions or error i.e. after execution of the following command

database.SortedSetAdd(key, sortedList.ToArray());

In Step#4 the look up should have succeeded but it's not!!

**Comment by NickCraver** [comment]
There's not really anything here we can advise on - there are no known latency issues, it's atomic on the Redis server side, if you are indeed connecting to the same server. But all I can see is logs, no code, infrastructure, setup, topology, etc. - but there's so much involved here in the "end-to-end doesn't work with 100 factors" that it's also unlikely we can advise in an issue here much unless you have a much more specific or smaller repro.

**Comment by NickCraver** [comment]
Since we can't advise further without more info, closing out to tidy up.
