### ISSUE TITLE
Redis Timeout Exception and 100% CPU

### ISSUE THREAD

**Issue by erman-afacan-deltatre** [StackExchange/StackExchange.Redis#2291]
Hi all, 

I know this topic is quite common following a few years back. However, I know the fact that this can happen for a variety of reasons.  So I decided to share our unfortunate experience in the hope of finding at least an explanation, even better, a solution.

We experienced a significant meltdown on production yesterday all the logs pointed to the Redis as we were getting timeouts all over the place.  

Our stack is .Net 4.6.1, our MinWorkerThreads setting is 480, and MaxWorkerThread is 500 
we were using Azure Cache For Redis during the incident Redis scaling was P2 Premium 13GB cache

The change was the Redis version upgrade, the previous version was as follows
``` xml
<PackageReference Include="StackExchange.Redis" Version="2.1.58" />
<PackageReference Include="StackExchange.Redis.Extensions.Core" Version="5.0.3" />
<PackageReference Include="StackExchange.Redis.Extensions.Newtonsoft" Version="5.0.3" />
```

and we upgraded the package versions to the
```xml
<PackageReference Include="StackExchange.Redis.Extensions.Core" Version="8.0.5" />
<PackageReference Include="StackExchange.Redis.Extensions.Newtonsoft" Version="8.0.5" />
```

If you look at the Redis performance metric down below, there is 14k connected clients at the moment of the incident
![image](https://user-images.githubusercontent.com/99476298/198973610-00ea076c-98e5-4bc8-96fb-646776772575.png)

![image](https://user-images.githubusercontent.com/99476298/198974168-92d5ed09-4c3b-43fc-9736-3b1282b86aae.png)

![image](https://user-images.githubusercontent.com/99476298/198974278-b7cf95fd-224d-4086-b544-bcd24f06a031.png)

We had to roll back the latest Redis version to 2.1.58 again. After that, all the problems disappeared. We also restarted the servers it didn't help at all. Because I know that these connection errors solve the connectivity error as it gets a fresh start. 

Some of the connection timeout errors as blow; (I removed sensitive information like server address etc.)
```
The timeout was reached before the message could be written to the output buffer, and it was not sent, command=GET, timeout: 20000, inst: 0, qu: 4003, qs: 0, aw: False, bw: CheckingForTimeout, rs: NotStarted, ws: Idle, in: 0, mc: 1/1/0, mgr: 10 of 10 available, clientName: client1(SE.Redis-v2.6.66.47313), IOCP: (Busy=29,Free=771,Min=20,Max=800), WORKER: (Busy=500,Free=0,Min=480,Max=500), v: 2.6.66.47313 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
```

```
The timeout was reached before the message could be written to the output buffer, and it was not sent, command=GET, timeout: 20000, inst: 0, qu: 47, qs: 0, aw: False, bw: CheckingForTimeout, rs: NotStarted, ws: Initializing, in: 0,  mc: 1/1/0, mgr: 0 of 10 available, clientName: client1(SE.Redis-v2.6.66.47313), IOCP: (Busy=215,Free=585,Min=20,Max=800), WORKER: (Busy=311,Free=189,Min=480,Max=500), v: 2.6.66.47313 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
```

```
The timeout was reached before the message could be written to the output buffer, and it was not sent, command=GET, timeout: 20000, inst: 0, qu: 117, qs: 0, aw: False, bw: CheckingForTimeout, rs: NotStarted, ws: Idle, in: 0, mc: 1/1/0, mgr: 10 of 10 available, clientName: client1(SE.Redis-v2.6.66.47313), IOCP: (Busy=18,Free=782,Min=20,Max=800), WORKER: (Busy=36,Free=464,Min=480,Max=500), v: 2.6.66.47313 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
```

```
The timeout was reached before the message could be written to the output buffer, and it was not sent, command=GET, timeout: 20000, inst: 0, qu: 834, qs: 0, aw: False, bw: CheckingForTimeout, rs: NotStarted, ws: Initializing, in: 0, mc: 1/1/0, mgr: 10 of 10 available, clientName: client1(SE.Redis-v2.6.66.47313), IOCP: (Busy=0,Free=800,Min=20,Max=800), WORKER: (Busy=500,Free=0,Min=480,Max=500), v: 2.6.66.47313 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
```

Any help is appreciated. 
Thank you

**Comment by NickCraver** [comment]
Do you have a memory dump showing where all the threads were? It's definitely thread pool exhaustion, but I can't speak for those other packages and threads are a global shared resource. You could for example try bumping only StackExchange.Redis to latest to see what happens but we don't expect any regressions here as there haven't been any large behavior changes on this front.

A memory dump when it happens is your best bet, but the long-term play should be going async rather than relying on the thread pool to be unbounded or very high capacity, you're going to get a lot more throughput on a lot fewer resources with proper async flows here.

**Comment by NickCraver** [comment]
Closing this out pending more info - happy to re-open if there's more to advise on.
