### ISSUE TITLE
Rout53 Redis

### ISSUE THREAD

**Issue by akshatchhangani** [StackExchange/StackExchange.Redis#2292]
Hey! I am using StackExchange.Redis.Extensions.Core package and using route53 URL to connect to Redis in my .NET code, and I am not able to connect to it and I get connection timeout error. But if I use direct configuration endpoint to connect, I am able to connect to Redis.
Below are my redis settings :

"East1Redis": {
    "Password": "",
    "AllowAdmin": true,
    "Ssl": true,
    "KeepAlive": 180,
    "ConnectTimeout": 5000,
    "ConnectRetry": 2,
    "PoolSize": 1,
    "SyncTimeout": 5000,
    "AsyncTimeout": 5000,
    "Database": 0,
    "isDefault": false,
    "Hosts": [
      {
        "Host": "clustercfge.cfge-pymnt-dev-us-east-1-redis.lj9hun.use1.cache.amazonaws.com",
        "Port": "6379"
      }
    ]
  },

**Comment by mgravell** [comment]
StackExchange.Redis.Extensions.Core isn't us; they simply got in with that name before we managed to lock it down as a reserved prefix; you'll need to ask whoever wrote that

**Comment by akshatchhangani** [comment]
@mgravell and team. Even if i use StackExchange.Redis package. I am not able to connect using route53 url.

**Comment by mgravell** [comment]
xref #2293
