### ISSUE TITLE
Route53 StackExchange.Redis

### ISSUE THREAD

**Issue by akshatchhangani** [StackExchange/StackExchange.Redis#2293]
I have just started using StackExchange and just tried connecting to redis using route53 url and i am not able to connect. But with configuration endpoint, i am able to connect.

**Comment by mgravell** [comment]
Very hard to comment without context. What does that look like in terms of code / configuration string (omitting anything private; we don't want/need your actual servers!)

**Comment by akshatchhangani** [comment]
We have a redis global datastore setup with two redis clusters in east1 and east2 regions  with passwords in aws. The encryption in transit is true and cluster mode is enabled in aws. Now, we have created a route53 and we are redirecting the rout53 url to redis configuration endpoints. Now if we use route53 endpoint url to connect to redis in RedisInsight tool, we are able to connect. But from code side we are not able to connect if we use route53 url, but able to connect if we use direct configuration endpoint.

**Comment by akshatchhangani** [comment]
It behaves as if redis doesn't support Rout53 urls directly. Looks like we have to first resolve the route53 url in code and then connect to it

**Comment by mgravell** [comment]
The library doesn't expect or support URLs. If you remove / scramble the server name: what does the URL look like? There is a redis:// url-thing that some clients support; we don't currently implement that (for reasons), but: the same thing can be expressed in terms we do support.

**Comment by akshatchhangani** [comment]
"The same thing can be expressed in terms you do support" . Could be please elaborare a little ? or just give an example ?

**Comment by mgravell** [comment]
https://stackexchange.github.io/StackExchange.Redis/Configuration.html
