### ISSUE TITLE
Yet another Redis Timeout Exception

### ISSUE THREAD

**Issue by BloxcrossIT** [StackExchange/StackExchange.Redis#2295]
I have a computer on a bus, it is powered by 2 sources (master and battery), when the source changes to battery (2 x12 volts) redis fails, this only happens on some buses.

I assume the timeout error must be related to the battery charge, but I don't understand why it only affects redis.

Specs:

- SE.Redis-v2.6.66.47313
- Net core 6.0
- Ubuntu 18.04
- Redis 7.0.5
- ConnectionMultiplexer is a lazy singleton

Error:

Timeout awaiting response (outbound=1KiB, inbound=0KiB, 5003ms elapsed, timeout is 5000ms), 
command=LPUSH, 
next: INFO, 
inst: 0, 
qu: 0, 
qs: 279, 
aw: False, 
bw: SpinningDown, 
rs: ReadAsync, 
ws: Idle, 
in: 0, 
in-pipe: 0, 
out-pipe: 0, 
serverEndpoint: 127.0.0.1:6379, 
mc: 1/1/0, 
mgr: 10 of 10 available, 
clientName: iot1405(SE.Redis-v2.6.66.47313), 
IOCP: (Busy=0,Free=1000,Min=1,Max=1000), 
WORKER: (Busy=1,Free=32766,Min=1,Max=32767), 
POOL: (Threads=3,QueuedItems=0,CompletedItems=33740), 
v: 2.6.66.47313

**Comment by NickCraver** [comment]
What is your connection timeout? A few thoughts:
- If you're connecting to cluster, you'll want to grab a new release that'll connect faster
- If your connection timeout is 5 sec, it may be taking the full duration until you update, effectively cancelling out the retry here
- The retry won't help _commands already in flight_ so for example does the network blip here? I have no insight into your connectivity portion
- 5 seconds is pretty low _as a maximum_ for such a scenario, I'd usually think of using higher.

**Comment by NickCraver** [comment]
What is your connection timeout? A few thoughts:
- If you're connecting to cluster, you'll want to grab a new release that'll connect faster
- If your connection timeout is 5 sec, it may be taking the full duration until you update, effectively cancelling out the retry here
- The retry won't help _commands already in flight_ so for example does the network blip here? I have no insight into your connectivity portion
- 5 seconds is pretty low _as a maximum_ for such a scenario, I'd usually think of using higher.

**Comment by NickCraver** [comment]
Closing this out without any more to go on.
