### ISSUE TITLE
Frequent timeouts when using StringGet in a multi-threaded manner

### ISSUE THREAD

**Issue by jkrmo** [StackExchange/StackExchange.Redis#2296]
This was tough to track down, but it is easily reproducable. To cut to the chase, the code that can produce the problem is as follows:

```csharp
public async Task StringGetTimeouts()
{
    int hitCount = 10;
    List<Task> testingTasks = new List<System.Threading.Tasks.Task>();
    for (int i = 0; i < hitCount; i++)
    {
        // _database is an instance of StackExchange.Redis.IDatabase
        testingTasks.Add(Task.Run(() => _database.StringGet("SOME_KEY_HERE")));
    }

    await Task.WhenAll(testingTasks);
}
```

What happens is that, when executing this code, _sometimes_ we observe timeout errors. I've gone into the code that handles `StringGet` and I can't quite make heads or tails of what's going on in regards to how the synchronization during multi-threading is being managed, but it looks like the call to [`Monitor.Wait` in the `ConnectionMultiplexer`](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/ConnectionMultiplexer.cs#L1879) ends up causing the timeout, and we receive the "Timeout performing...." error message when that happens.

I've reproduced this error in an environment where we are executing C# Lambda's written in .NET Core 3.1, deployed as a deployment package (vs. a docker image) in AWS, but we have also seem very similar errors in apps deployed to ECS with .NET Core 3.1, as well as apps deployed on internal servers using .NET Framework 4.6.2. 

Just some other random facts about our setup in case they are needed or are helpful
- Our timeouts are set at 5000ms
- We are using a redis cluster deployed to AWS using engine version 6.2.6
   - 2 nodes, 1 shard, cluster mode is off, encryption at rest enabled
- I have tried modifying thread-theft settings by adding `ConnectionMultiplexer.SetFeatureFlag("preventthreadtheft", true);` with no success

The error messages we end up seeing when this happens are similar to this:
<details>
  <summary>View error</summary>
  <pre>
Type: StackExchange.Redis.RedisTimeoutException
Message: Timeout performing GET (5000ms), next: INFO, inst: 0, qu: 0, qs: 8, aw: False, rs: ReadAsync, ws: Idle, in: 5702, serverEndpoint: &lt;REDACTED_SERVER&gt;, mc: 1/1/0, mgr: 10 of 10 available, clientName: 169, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=7,Free=32760,Min=2,Max=32767), v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
Properties:
   Commandstatus: Sent
   HelpLink: https://stackexchange.github.io/StackExchange.Redis/Timeouts
   HResult: 0x80131505
Source: StackExchange.Redis
Exception Data:
   Redis-Message - GET &lt;REDACTED_KEY&gt;
   Redis-Message-Next - INFO
   Redis-OpsSinceLastHeartbeat - 0
   Redis-Queue-Awaiting-Write - 0
   Redis-Queue-Awaiting-Response - 8
   Redis-Active-Writer - False
   Redis-Read-State - ReadAsync
   Redis-Write-State - Idle
   Redis-Inbound-Bytes - 5702
   Redis-Server-Endpoint - &lt;REDACTED_SERVER&gt;
   Redis-Multiplexer-Connects - 1/1/0
   Redis-Manager - 10 of 10 available
   Redis-Client-Name - 169
   Redis-ThreadPool-IO-Completion - (Busy=0,Free=1000,Min=2,Max=1000)
   Redis-ThreadPool-Workers - (Busy=7,Free=32760,Min=2,Max=32767)
   Redis-Busy-Workers - 7
   Redis-Version - 2.1.58.34321
   redis-command - GET &lt;REDACTED_KEY&gt;
   request-sent-status - Sent
   redis-server - &lt;REDACTED_SERVER&gt;
Stack Trace:
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2818
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2374
   at &lt;REDACTED_CODE&gt;
   at &lt;REDACTED_CODE&gt;
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at &lt;REDACTED_CODE&gt;
  </pre>
</details>

You can see that that's a GET operation.. but we also see timeout errors on other operations when this happens such as:
<details>
  <summary>View error</summary>
  <pre>
Type: StackExchange.Redis.RedisTimeoutException
Message: Timeout performing HINCRBYFLOAT (5000ms), next: PING, inst: 1, qu: 0, qs: 6, aw: False, rs: ReadAsync, ws: Idle, in: 216, serverEndpoint: &lt;REDACTED_SERVER&gt;, mc: 1/1/0, mgr: 10 of 10 available, clientName: 169, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=8,Free=32759,Min=2,Max=32767), v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
Properties:
   Commandstatus: Sent
   HelpLink: https://stackexchange.github.io/StackExchange.Redis/Timeouts
   HResult: 0x80131505
Source: StackExchange.Redis
Exception Data:
   Redis-Message - HINCRBYFLOAT &lt;REDACTED_KEY&gt;
   Redis-Message-Next - PING
   Redis-OpsSinceLastHeartbeat - 1
   Redis-Queue-Awaiting-Write - 0
   Redis-Queue-Awaiting-Response - 6
   Redis-Active-Writer - False
   Redis-Read-State - ReadAsync
   Redis-Write-State - Idle
   Redis-Inbound-Bytes - 216
   Redis-Server-Endpoint - &lt;REDACTED_SERVER&gt;
   Redis-Multiplexer-Connects - 1/1/0
   Redis-Manager - 10 of 10 available
   Redis-Client-Name - 169
   Redis-ThreadPool-IO-Completion - (Busy=0,Free=1000,Min=2,Max=1000)
   Redis-ThreadPool-Workers - (Busy=8,Free=32759,Min=2,Max=32767)
   Redis-Busy-Workers - 8
   Redis-Version - 2.1.58.34321
   redis-command - HINCRBYFLOAT &lt;REDACTED_KEY&gt;
   request-sent-status - Sent
   redis-server - &lt;REDACTED_SERVER&gt;
Stack Trace:
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2818
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.HashIncrement(RedisKey key, RedisValue hashField, Double value, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 370
   at Splitio.Redis.Services.Cache.Classes.RedisAdapter.HashIncrement(String key, String hashField, Double value)
  </pre>
</details>

I was originally seeing this version happen on `StackExchange.Redis 2.1.58`. I increased our version to `StackExchange.Redis 2.6.70` and observed the issue continued to happen. After upgrading from `StackExchange.Redis` from `2.1.58` to `2.6.70`, the error message looks pretty much the same:

<details>
  <summary>View error</summary>
  <pre>
Type: StackExchange.Redis.RedisTimeoutException
Message: Timeout performing GET (5000ms), next: GET &lt;REDACTED_KEY&gt;, inst: 2, qu: 0, qs: 0, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 8332, serverEndpoint: &lt;REDACTED_SERVER&gt;, mc: 1/1/0, mgr: 10 of 10 available, clientName: 169(SE.Redis-v2.6.70.49541), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=8,Free=32759,Min=2,Max=32767), POOL: (Threads=8,QueuedItems=13,CompletedItems=96), v: 2.6.70.49541 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
Properties:
   Commandstatus: Sent
   HelpLink: https://stackexchange.github.io/StackExchange.Redis/Timeouts
   HResult: 0x80131505
Source: StackExchange.Redis
Exception Data:
   Redis-Message - GET &lt;REDACTED_KEY&gt;
   Redis-Message-Next - GET &lt;REDACTED_KEY&gt;
   Redis-OpsSinceLastHeartbeat - 2
   Redis-Queue-Awaiting-Write - 0
   Redis-Queue-Awaiting-Response - 0
   Redis-Active-Writer - False
   Redis-Backlog-Writer - Inactive
   Redis-Read-State - ReadAsync
   Redis-Write-State - Idle
   Redis-Inbound-Bytes - 8332
   Redis-Server-Endpoint - &lt;REDACTED_SERVER&gt;
   Redis-Multiplexer-Connects - 1/1/0
   Redis-Manager - 10 of 10 available
   Redis-Client-Name - 169(SE.Redis-v2.6.70.49541)
   Redis-ThreadPool-IO-Completion - (Busy=0,Free=1000,Min=2,Max=1000)
   Redis-ThreadPool-Workers - (Busy=8,Free=32759,Min=2,Max=32767)
   Redis-ThreadPool-Items - (Threads=8,QueuedItems=13,CompletedItems=96)
   Redis-Busy-Workers - 8
   Redis-Version - 2.6.70.49541
   redis-command - GET &lt;REDACTED_KEY&gt;
   request-sent-status - Sent
   redis-server - &lt;REDACTED_SERVER&gt;
Stack Trace:
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1887
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/RedisBase.cs:line 62
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2960
   at &lt;REDACTED_CODE&gt;
   at &lt;REDACTED_CODE&gt;
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at &lt;REDACTED_CODE&gt;
  </pre>
</details>

I also tested using the matching `StringGetAsync` method, and found that this same issue does _NOT_ occur when consuming this library asynchronously. While I would love to just convert everything over to the async operations, the problem is that we are using another third-party library that then consumes `StackExchange.Redis`, and that library does not provide a way to use the asynchronous operations provided at this time.

Looking for ideas as to why this is happening. I had found #1196 from a while ago that was marked as closed, but unfortunately no solution was provided. Because of how simple the use-case is that can cause this to happen, i'm wondering if this is a bug.

**Comment by NickCraver** [comment]
The core problem here is that `.StringGet()` call. For the duration of the call, you're using a thread from the thread pool. This will cause exhaustion and timeouts result from waiting on another thread to do the work or complete a call (e.g. to handoff from the library back to the app). The bandaid some people are using is ThreadPool.SetMinThreads as an example of the issue, but be very clear: this is a bandaid and not solving the root issue of occupying threads while waiting on I/O. To really fix this, you want to go async...this is _the_ reason `async` was added to the platform/framework/languages.

**Comment by NickCraver** [comment]
Closing out to tidy up.
