### ISSUE TITLE
Configuring .net core 6 app to proparly connect to a redis running with sentinel configuration 

### ISSUE THREAD

**Issue by remus-corneliu** [StackExchange/StackExchange.Redis#2297]
I'm trying to connect a my .net core 6 app to a configuration of 3 nods (1 master + 2 slaves) + 3 sentinels. 

Attaching the config files 

master.conf :
```

bind 0.0.0.0
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
rdb-del-sync-files no
dir ./
masterauth pass
replica-serve-stale-data yes
replica-read-only yes
repl-diskless-sync no
repl-diskless-sync-delay 5
repl-diskless-load disabled
repl-disable-tcp-nodelay no
replica-priority 100
requirepass pass
lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
replica-lazy-flush no
lazyfree-lazy-user-del no
oom-score-adj no
oom-score-adj-values 0 200 800
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
aof-use-rdb-preamble yes
lua-time-limit 5000
slowlog-max-len 128
latency-monitor-threshold 0
notify-keyspace-events ""
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
stream-node-max-bytes 4096
stream-node-max-entries 100
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
dynamic-hz yes
aof-rewrite-incremental-fsync yes
rdb-save-incremental-fsync yes
jemalloc-bg-thread yes
```

sentinel.conf file
```

port 6380
daemonize no
pidfile /var/run/redis-sentinel.pid
logfile ""
dir /tmp
sentinel monitor redismaster redis-node-1 6379 2
sentinel auth-pass redismaster pass
sentinel down-after-milliseconds redismaster 30000
sentinel parallel-syncs redismaster 3
sentinel failover-timeout redismaster 30000
sentinel deny-scripts-reconfig yes
```

slave.conf
```

bind 0.0.0.0
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
pidfile /var/run/redis_6379.pid
loglevel notice
logfile ""
databases 16
always-show-logo yes
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
rdb-del-sync-files no
dir ./
replicaof redis-node-1 6379
masterauth pass
replica-serve-stale-data yes
replica-read-only yes
repl-diskless-sync no
repl-diskless-sync-delay 5
repl-diskless-load disabled
repl-disable-tcp-nodelay no
replica-priority 100
acllog-max-len 128
requirepass pass
lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
replica-lazy-flush no
lazyfree-lazy-user-del no
oom-score-adj no
oom-score-adj-values 0 200 800
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-use-rdb-preamble yes
lua-time-limit 5000
slowlog-log-slower-than 10000
slowlog-max-len 128
latency-monitor-threshold 0
notify-keyspace-events ""
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
stream-node-max-bytes 4096
stream-node-max-entries 100
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
dynamic-hz yes
aof-rewrite-incremental-fsync yes
rdb-save-incremental-fsync yes
jemalloc-bg-thread yes

```

Based on this conf files I'm creating 3 docker images, and I'm using them in my docker-compose.yml file. I'm not doing anything special except for exposing the ports and  running on each container this command

```
    command: "redis-server /config/redis.conf"
```

When running docker-compose up all is good. I can see my nodes up and running my sentinels as well. I'm ssh-ing into master and create a key and add a value. I'm ssh-ing into the other slaves an I can see the data replication is done. I'm stoping the container in which master runs, and I can see that the sentinles are doing their job and pick up antoher master. I bring back the ex-master and I can see it now that it joined as a slave. 

I'n my net core app I've tested using only master node, and everything works well. 
I'm adding the rest of the nodes 

```


  "Redis": {
    "Connection": {
      //"Host": "localhost",
      //"Port": 6370,
      "Password": "pass",
      "ConnectTimeout": 5000,
      "ConnectRetry": 10,
      "ReconnectRetry": 3000,
      "KeepAlive": 3000,
      "SyncTimeout": 500,
      "AsyncTimeout": 500,
      "AllowAdminCommands": false,
      "HeartbeatInterval": 1000,
      "InstanceIdentifier": "redis-instance::",
      "IncludePerformanceCountersInExceptions": false,
      "IncludeDetailInExceptions": false,
      "Endpoints": [
        {
          "Host": "localhost",
          "Port": 6370",
          "Type": "Master"
        },
        {

          "Type": "Slave",
          "Host": "localhost",
          "Port": 6371
        },
        {
          "Type": "Slave",
          "Host": "localhost",
          "Port": 6372
        }
        //{
        //  "Host": "localhost",
        //  "Port": 6380,
        //  "Type": "Sentinel"
        //},
        //{
        //  "Host": "localhost",
        //  "Port": 6381,
        //  "Type": "Sentinel"
        //},
        //{
        //  "Host": "localhost",
        //  "Port": 6382,
        //  "Type": "Sentinel"
        //}
      ],
      "MasterName": "redismaster" /// see redis.sentinel.conf line 85 > it is called redismaster
    }
```

I'm creating my IConnectionMultiplexer using this configuraiton

```
await ConnectionMultiplexer.ConnectAsync(_options.ConfigurationOptions)
```

I'm getting

```
StackExchange.Redis.RedisConnectionException: 'Sentinel: The ConnectionMultiplexer is not a Sentinel connection. Detected as: Standalone'
```

My connection looks like this 

```
localhost:6370,localhost:6371,localhost:6372,name=Api.Reporting,serviceName=redismaster,keepAlive=3,syncTimeout=500,asyncTimeout=500,allowAdmin=False,connectTimeout=5000,password=pass,connectRetry=10
```

Is it something I'm missing ?  

I can see that there is a SentinelConnectAsync method, not sure what exactly it does but using this does not fail. However when trying to write something, it still does not fail, but when I inspect if anything has been written to the master no key is present on master nor slaves. So I'm not sure what SentinelConnectAsync  does.

My question is , is there a way using stackexchange.redis cliant to connect to a running ha redis cluster ? how ? 

What else I've tried is using the SentinelConnectAsync() get the servers, see the master and get the database but I don't see anyway of getting the database from a server, but most importantly I don't think I'm on the right path with this..

Thank you!

I've tried using single sntinel node + master name in configuration 

According to this https://stackexchange.github.io/StackExchange.Redis/Configuration.html 

If you specify a serviceName in the connection string, it will trigger sentinel mode. This example will connect to a sentinel server on the local machine using the default sentinel port (26379), discover the current primary server for the myprimary service and return a managed connection pointing to that primary server that will automatically be updated if the primary changes:
```
var conn = ConnectionMultiplexer.Connect("localhost,serviceName=myprimary");
```
If I understand it right  conn should actually point to master?  so  conn  should be with master ?

If I do 
```
var database - conn.GetDatabase();
database.StringSet("key", "val") 
```

I dont have any keys on master.

**Comment by NickCraver** [comment]
I'm not sure how your configuration works, but looking at this my guess would be:
```diff
- "MasterName": "redismaster" /// see redis.sentinel.conf line 85 > it is called redismaster
+ "ServiceName": "redismaster" /// see redis.sentinel.conf line 85 > it is called redismaster
```

**Comment by remus-corneliu** [comment]
> I'm not sure how your configuration works, but looking at this my guess would be:
> 
> ```diff
> - "MasterName": "redismaster" /// see redis.sentinel.conf line 85 > it is called redismaster
> + "ServiceName": "redismaster" /// see redis.sentinel.conf line 85 > it is called redismaster
> ```

Ah yes, actully I'm mapping the appsettings.json redis config to some class (wrapper), and that class than is used to create the ConfigurationOptions, 

The logic is something like this 


public static IDistributedCacheBuilder AddStackExchangeRedis(this IServiceCollection services, Func<IServiceProvider, TcpEndpointOptions> connectionSetup)
        {
            if (connectionSetup is null) throw new ArgumentNullException(nameof(connectionSetup));

            services.AddSingleton<IDistributedCache, RedisDistributedCache>()
                .AddSingleton<IDistributedStringTypeCache, RedisStringTypeCache>()
                .AddSingleton<IDistributedSetTypeCache, RedisSetTypeCache>()
                .AddSingleton<IDistributedHashTypeCache, RedisHashTypeCache>()
                .AddSingleton<IDistributedCacheBuilder>(
                    serviceProvider =>
                    {
                        IDistributedCacheBuilder cacheBuilder = new DistributedCacheBuilder(services);

                        return cacheBuilder
                            .AddBasicCacheOptions(() =>
                            {
                                TcpEndpointOptions cluster = connectionSetup(serviceProvider);
                                ConfigurationOptions configurationOptions = new ConfigurationOptions();

                                foreach (TcpEndpoint endpoint in cluster.Endpoints)
                                {
                                    configurationOptions.EndPoints.Add(endpoint.Host, endpoint.Port);
                                }

                                configurationOptions.Password = cluster.Password;

                                configurationOptions.ConnectTimeout = cluster.ConnectTimeout;
                                configurationOptions.ConnectRetry = cluster.ConnectRetry;
                                configurationOptions.ReconnectRetryPolicy = new ExponentialRetry(cluster.ReconnectRetry);

                                configurationOptions.KeepAlive = cluster.KeepAlive / 1_000;
                                configurationOptions.HeartbeatInterval = TimeSpan.FromMilliseconds(cluster.HeartbeatInterval);

                                configurationOptions.IncludeDetailInExceptions = cluster.IncludeDetailInExceptions;
                                configurationOptions.IncludePerformanceCountersInExceptions = cluster.IncludePerformanceCountersInExceptions;

                                configurationOptions.ClientName = cluster.ClientName;

                                configurationOptions.AllowAdmin = cluster.AllowAdminCommands;
                                configurationOptions.AsyncTimeout = cluster.AsyncTimeout;
                                configurationOptions.SyncTimeout = cluster.SyncTimeout;

                                configurationOptions.ServiceName = cluster.MasterName;

                                cluster.ConfigurationOptions = configurationOptions;
                                cluster.Sentinel = true;

                                return cluster;
                            })
                            .AddStackExchangeRedisSerializer(() => new ProtobufSerializer());
                    });

            return new DistributedCacheBuilder(services);
        }

But I don't want to waste anyones time on this. I'm not sure in regards if StackExchange.Redis provides out of the box  failover management, like if my initial master goes doe somehow behid the scen will redirect to the new master. And if it does not do this, what is the actual approch would one propse ? I've read something in regards with subscribing to sentinel events ? So my guess is to create the connection using SentinelConnection and then subscribe somehow to this events and create another multiplexerConnection and keeping this one up to date according to the cluster state ?

**Comment by NickCraver** [comment]
All of this is in-box, but it depends on ServiceName being set - that's the critical component of how Sentinel operates :) If you connect to a sentinel endpoint with a service name, we'll connect to the downstream servers and handle changes as well.

**Comment by remus-corneliu** [comment]
Ok, so management of how traffic is downstremed should be handled by the library. 

Then, having this configuraiton 

```
localhost:6370,localhost:6371,localhost:6372,name=Api.Reporting,serviceName=redismaster,keepAlive=3,syncTimeout=500,asyncTimeout=500,allowAdmin=False,connectTimeout=5000,password=pass,connectRetry=10
```

where the 3 hosts are master + 2 slaves, should be replaced with a single sentinel node? and the connection should be somthing like 

```
<sentinel>:<sentinelPort>, name=Api.Reporting,serviceName=redismaster,keepAlive=3,syncTimeout=500,asyncTimeout=500,allowAdmin=False,connectTimeout=5000,password=pass,connectRetry=10
```

And when creating the connection I sould be using SentinelConnect or Connect ?

**Comment by NickCraver** [comment]
Just .Connect (or ConnectAsync) - SentinelConnect is when you _explicitly_ don't want to go down to the nodes it manages, and interface with the Sentinel servers themselves for some reason.

**Comment by remus-corneliu** [comment]
> All of this is in-box, but it depends on ServiceName being set - that's the critical component of how Sentinel operates :) 

What exactly is the service name ? I understand is the master, but how do I determine the service name? In my sentinel.conf file I've  specified 

```
sentinel monitor redismaster redis-node-1 6379 2

```

So I was living under the impression that ```redismaster```  should be it.

**Comment by NickCraver** [comment]
redismaster is it - exactly as in my first reply :)

You're using terms like "does nothing" - does _what_? How are you checking it? What error? There's little to no information to go on here.

**Comment by remus-corneliu** [comment]
This is the connection string which points to a sentinel. 

{localhost:6380,name=Api.Reporting,serviceName=redismaster,keepAlive=3,syncTimeout=500,asyncTimeout=500,allowAdmin=False,connectTimeout=5000,password=pass,abortConnect=False,connectRetry=10}

And the actual call to connect is this 

 ```
      private async ValueTask ConnectAsync(CancellationToken token)
        {
            if (_connectionStatus == ConnectionStatus.Connected) return;

            await _connectionMultiplexerLock.WaitAsync(token);

            try
            {
                _connectionMultiplexer = await ConnectionMultiplexer.ConnectAsync(_options.ConfigurationOptions);

                _database = _connectionMultiplexer.GetDatabase();

                _connectionStatus = ConnectionStatus.Connected;
            }
            catch (Exception ex)
            {
                throw;
            }
            finally
            {
                _connectionMultiplexerLock.Release();
            }
        }
```

when trying to connect this is what I'm getting

StackExchange.Redis.RedisTimeoutException: 'Timeout performing ROLE (500ms), inst: 0, qu: 1, qs: 0, aw: False, bw: Inactive, serverEndpoint: 172.128.0.2:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: Api.Reporting, IOCP: (Busy=0,Free=1000,Min=36,Max=1000), WORKER: (Busy=1,Free=32766,Min=36,Max=32767), POOL: (Threads=30,QueuedItems=0,CompletedItems=425), v: 2.6.70.49541 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)'

Docker :
```
11947118c3ee   redis:master       "docker-entrypoint.s…"   20 hours ago   Up 15 hours    0.0.0.0:6370->6379/tcp                                                                                        redis-node-1
```

Looking at  the suggested link  https://stackexchange.github.io/StackExchange.Redis/Timeouts and checking the exception I can see qu:1 , not sure if this is the reason.

If I use the same exact connection, but instead of point to sentinel I'm pointing to master, and I remove the serviceName, the connection to redis gets created.

![Capture](https://user-images.githubusercontent.com/41466855/201141011-7892e561-1cf4-47a6-b0ff-5ecc4124a7e5.PNG)

**Comment by NickCraver** [comment]
Remove `abortConnect=False` when trying to troubleshoot connection issues - and you can pass a logger into the connect method to get a full view of what's happening. Right now, it doesn't appear you're connecting at all, which could be a network/port issue. For example, try connecting from redis-cli on the same client machine.

**Comment by remus-corneliu** [comment]
Got the log file, will investigate on this.

**Comment by remus-corneliu** [comment]
Ok, I've investigate the log files, but without any success. It seems as if the container in which the sentinel runs is not reachable or something, and I have no idea if it's some limitation of docker or redis or a combination of both or something inside the stackexchange.redis library. 

Expalin once again what how I'm running this and my hosting env. 

master config
```
protected-mode no 
bind 0.0.0.0 
port 6379 

masterauth pass 
requirepass pass
```

slave config
```
protected-mode no
bind 0.0.0.0
port 6379
replicaof 172.128.3.10 6379

masterauth pass
requirepass pass
```

sentinel1
```
port 6379
protected-mode no

sentinel announce-ip 172.128.3.13

sentinel myid 5bdaf984e15ec43bfde835d04d485848acbab78c
sentinel known-sentinel redismaster 172.128.3.14 6379 d8de0f4bcb59725cea695791379094ea12bfbde5
sentinel known-sentinel redismaster 172.128.3.15 6379 326f98bb6afca0ff9db88513ebcc0050033706f4

sentinel deny-scripts-reconfig yes
sentinel monitor redismaster 172.128.3.10 6379 2
sentinel auth-pass redismaster pass
sentinel down-after-milliseconds redismaster 5000
sentinel failover-timeout redismaster 60000

dir "/data"

sentinel known-replica redismaster 172.128.3.11 6379
sentinel known-replica redismaster 172.128.3.12 6379

sentinel resolve-hostnames no
sentinel announce-hostnames no
```

sentinel2

```
port 6379
protected-mode no

sentinel announce-ip 172.128.3.14

sentinel myid 5bdaf984e15ec43bfde835d04d485848acbab78c
sentinel known-sentinel redismaster 172.128.3.13 6379 d8de0f4bcb59725cea695791379094ea12bfbde5
sentinel known-sentinel redismaster 172.128.3.15 6379 326f98bb6afca0ff9db88513ebcc0050033706f4

sentinel deny-scripts-reconfig yes
sentinel monitor redismaster 172.128.3.10 6379 2
sentinel auth-pass redismaster pass
sentinel down-after-milliseconds redismaster 5000
sentinel failover-timeout redismaster 60000

dir "/data"

sentinel known-replica redismaster 172.128.3.11 6379
sentinel known-replica redismaster 172.128.3.12 6379

sentinel resolve-hostnames no
sentinel announce-hostnames no
```

sentinel3
```
port 6379
protected-mode no

sentinel announce-ip 172.128.3.15

sentinel myid 5bdaf984e15ec43bfde835d04d485848acbab78c
sentinel known-sentinel redismaster 172.128.3.13 6379 d8de0f4bcb59725cea695791379094ea12bfbde5
sentinel known-sentinel redismaster 172.128.3.14 6379 326f98bb6afca0ff9db88513ebcc0050033706f4

sentinel deny-scripts-reconfig yes
sentinel monitor redismaster 172.128.3.10 6379 2
sentinel auth-pass redismaster pass
sentinel down-after-milliseconds redismaster 5000
sentinel failover-timeout redismaster 60000

dir "/data"

sentinel known-replica redismaster 172.128.3.11 6379
sentinel known-replica redismaster 172.128.3.12 6379

sentinel resolve-hostnames no
sentinel announce-hostnames no
```

dockerfile for slaves, master, sentinels is the same, I'm building on top of redis 7 copy and copy the .conf files and replace.

```
FROM redis:7.0-alpine
COPY redis.conf /config/redis.conf
```


```
redis-node-1:
    build:
      context: ./governance.infraLayer/redis-ha/redis-0
      dockerfile: ./master.dockerfile
    image: redis:master
    container_name: redis-node-1
    networks:
      governance-local:
        ipv4_address: 172.128.3.10
    ports:
      - 6370:6379
    volumes:
      - /redis-node-1-volume:/data
    restart: unless-stopped
    command: "redis-server /config/redis.conf"

  redis-node-2:
    build:
      context: ./governance.infraLayer/redis-ha/redis-1
      dockerfile: ./slave.dockerfile
    image: redis:slave
    container_name: redis-node-2
    networks:
      governance-local:
        ipv4_address: 172.128.3.11
    ports:
      - 6371:6379
    depends_on:
      - redis-node-1
    volumes:
      - /redis-slave1-volume:/data
    restart: unless-stopped
    command: "redis-server /config/redis.conf"

  redis-node-3:
    build:
      context: ./governance.infraLayer/redis-ha/redis-2
      dockerfile: ./slave.dockerfile
    image: redis:slave
    container_name: redis-node-3
    networks:
      governance-local:
        ipv4_address: 172.128.3.12
    ports:
      - 6372:6379
    depends_on:
      - redis-node-1
    volumes:
      - /redis-slave2-volume:/data
    restart: unless-stopped
    command: "redis-server /config/redis.conf"

  redis-sentinel-1:
    build:
      context: ./governance.infraLayer/redis-ha/sentinel-0
      dockerfile: ./sentinel.dockerfile
    image: redis:sentinel
    container_name: redis-sentinel-1
    networks:
      governance-local:
        ipv4_address: 172.128.3.13
    ports:
      - 6380:6379
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    volumes:
      - /redis-sentinel1-volume:/data
    restart: unless-stopped
    command: "redis-sentinel /config/redis.conf"

  redis-sentinel-2:
    build:
      context: ./governance.infraLayer/redis-ha/sentinel-1
      dockerfile: ./sentinel.dockerfile
    image: redis:sentinel
    container_name: redis-sentinel-2
    networks:
      governance-local:
        ipv4_address: 172.128.3.14
    ports:
      - 6381:6379
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    volumes:
      - /redis-sentinel2-volume:/data
    restart: unless-stopped
    command: "redis-sentinel /config/redis.conf"

  redis-sentinel-3:
    build:
      context: ./governance.infraLayer/redis-ha/sentinel-2
      dockerfile: ./sentinel.dockerfile
    image: redis:sentinel
    container_name: redis-sentinel-3
    networks:
      governance-local:
        ipv4_address: 172.128.3.15
    ports:
      - 6382:6379
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    volumes:
      - /redis-sentinel3-volume:/data
    restart: unless-stopped
    command: "redis-sentinel /config/redis.conf"
```

I'm running 
Windows10 22H2 (19045.2251)
Docker Desktop 4.13.1 (90346) with wsl2 integration (my wsl distro is Ubuntu-22.04).

My infrastructure runs inside docker containers. 
I'm not running my .net 6 app inside docker container  (so it is not deployed as a container yet) - I don't know maybe this is a limitation ??? 

What is strange and I don't understand is  the following scenarios.

1. If I run a single redis node (standalone configuration) with
```
var connectionMultiplexer = await ConnectionMultiplexer.ConnectAsync(_options.ConfigurationOptions, logger);
```
I am able to connect to it and run operation against the configured redis node from my .net 6 app


2. If I run 3 redis nodes + 3 sentinels with 
```
var connectionMultiplexer = await ConnectionMultiplexer.SentinelConnectAsync(_options.ConfigurationOptions, logger);
```
I am able to connect to it 



3. But If I run 3 redis nodes + 3 sentinels 
```
var connectionMultiplexer = await ConnectionMultiplexer.ConnectAsync(_options.ConfigurationOptions, logger);
```
I'm getting 


```
12:09:55.9612: 172.128.3.11:6379/Interactive: Connecting...
12:09:55.9615: 172.128.3.11:6379: BeginConnectAsync
12:09:55.9635: 172.128.3.12:6379/Interactive: Connecting...
12:09:55.9639: 172.128.3.12:6379: BeginConnectAsync
12:09:55.9649: 172.128.3.10:6379/Interactive: Connecting...
12:09:55.9650: 172.128.3.10:6379: BeginConnectAsync
12:09:55.9657: 3 unique nodes specified (without tiebreaker)
12:09:55.9657: 172.128.3.11:6379: OnConnectedAsync init (State=Connecting)
12:09:55.9657: 172.128.3.12:6379: OnConnectedAsync init (State=Connecting)
12:09:55.9657: 172.128.3.10:6379: OnConnectedAsync init (State=Connecting)
12:09:55.9657: Allowing 3 endpoint(s) 00:00:05 to respond...
12:09:55.9658: Awaiting 3 available task completion(s) for 5000ms, IOCP: (Busy=0,Free=1000,Min=36,Max=1000), WORKER: (Busy=1,Free=32766,Min=36,Max=32767), POOL: (Threads=29,QueuedItems=0,CompletedItems=96)
12:10:00.9774: Not all available tasks completed cleanly (from ReconfigureAsync#1292, timeout 5000ms), IOCP: (Busy=0,Free=1000,Min=36,Max=1000), WORKER: (Busy=8,Free=32759,Min=36,Max=32767), POOL: (Threads=29,QueuedItems=0,CompletedItems=110)
12:10:00.9831:   Server[0] (172.128.3.11:6379) Status: WaitingForActivation (inst: 0, qs: 0, in: 0, qu: 0, aw: False, in-pipe: -1, out-pipe: -1, bw: Inactive, rs: NotStarted. ws: Initializing)
12:10:00.9832:   Server[1] (172.128.3.12:6379) Status: WaitingForActivation (inst: 0, qs: 0, in: 0, qu: 0, aw: False, in-pipe: -1, out-pipe: -1, bw: Inactive, rs: NotStarted. ws: Initializing)
12:10:00.9832:   Server[2] (172.128.3.10:6379) Status: WaitingForActivation (inst: 0, qs: 0, in: 0, qu: 0, aw: False, in-pipe: -1, out-pipe: -1, bw: Inactive, rs: NotStarted. ws: Initializing)
12:10:00.9832: Endpoint summary:
12:10:00.9832:   172.128.3.11:6379: Endpoint is (Interactive: Connecting, Subscription: Connecting)
12:10:00.9836:   172.128.3.12:6379: Endpoint is (Interactive: Connecting, Subscription: Connecting)
12:10:00.9836:   172.128.3.10:6379: Endpoint is (Interactive: Connecting, Subscription: Connecting)
12:10:00.9836: Task summary:
12:10:00.9836:   172.128.3.11:6379: Did not respond (Task.Status: WaitingForActivation)
12:10:00.9836:   172.128.3.12:6379: Did not respond (Task.Status: WaitingForActivation)
12:10:00.9836:   172.128.3.10:6379: Did not respond (Task.Status: WaitingForActivation)
12:10:00.9836: Election summary:
12:10:00.9836:   Election: No primaries detected
12:10:00.9836: Endpoint Summary:
12:10:00.9837:   172.128.3.11:6379: Standalone v3.0.0, primary; keep-alive: 00:00:03; int: Connecting; sub: Connecting; not in use: DidNotRespond
12:10:00.9837:   172.128.3.11:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=1
12:10:00.9837:   172.128.3.11:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
12:10:00.9837:   172.128.3.12:6379: Standalone v3.0.0, primary; keep-alive: 00:00:03; int: Connecting; sub: Connecting; not in use: DidNotRespond
12:10:00.9837:   172.128.3.12:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=1
12:10:00.9837:   172.128.3.12:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
12:10:00.9837:   172.128.3.10:6379: Standalone v3.0.0, primary; keep-alive: 00:00:03; int: Connecting; sub: Connecting; not in use: DidNotRespond
12:10:00.9837:   172.128.3.10:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=1
12:10:00.9837:   172.128.3.10:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
12:10:00.9838: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
12:10:00.9838: Resetting failing connections to retry...
12:10:00.9968: 172.128.3.11:6379: OnConnectedAsync completed (Disconnected)
12:10:00.9969: 172.128.3.10:6379: OnConnectedAsync completed (Disconnected)
12:10:00.9969: 172.128.3.12:6379: OnConnectedAsync completed (Disconnected)
12:10:01.0201:   Retrying - attempts left: 9...
12:10:01.0202: 3 unique nodes specified (without tiebreaker)
```

**Comment by NickCraver** [comment]
All we can see here is: we can't connect. We can't reach those endpoints, it's likely a network configuration issue with your environment. As I said before, try connecting to those endpoints _from the same place_ with `redis-cli` to verify basic connectivity - the library can't really do anything about things we can't open a connection to.

**Comment by remus-corneliu** [comment]
![image](https://user-images.githubusercontent.com/41466855/201524980-15ca76a6-d134-4bc5-a37a-8b7d037e814d.png)

I've installed redis inside my wsl distro ubuntu 22.04 And It seems that I can reach the nodes ?

**Comment by NickCraver** [comment]
I don't see it connecting to the 3 172. nodes, same as the client can't connect, notice how you aren't getting a prompt? You have a networking issue here to figure out, before any library has a chance of working.

**Comment by remus-corneliu** [comment]
Ok, I think I've made some progress. I've reconfigured my docker-compose to target the host network using 

```
    network_mode: host
```

127.0.0.1:6380,name=Api.Reporting,serviceName=redismaster,keepAlive=3,syncTimeout=2500,asyncTimeout=2500,allowAdmin=False,connectTimeout=5000,password=pass,abortConnect=False,connectRetry=10

But now I'm getting an exception that states 

StackExchange.Redis.RedisConnectionException
  HResult=0x80131500
  Message=Sentinel: The ConnectionMultiplexer is not a Sentinel connection. Detected as: Standalone
  Source=StackExchange.Redis
  StackTrace:
   at StackExchange.Redis.ConnectionMultiplexer.GetSentinelMasterConnection(ConfigurationOptions config, TextWriter log)
   at StackExchange.Redis.ConnectionMultiplexer.<SentinelPrimaryConnectAsync>d__230.MoveNext()
   at lib.Redis.Internals.RedisDistributedCache.<ConnectAsync>d__43.MoveNext() in D:\project-governance\Governance.Api\lib.Redis\Internals\RedisDistributedCache.cs:line 273
   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
   at lib.Redis.Internals.RedisDistributedCache.<lib-Redis-IDistributedCache-ConnectAsync>d__41.MoveNext() in D:\project-governance\Governance.Api\lib.Redis\Internals\RedisDistributedCache.cs:line 258
   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
   at lib.Redis.MicrosoftExtensions.IHostExtensions.<ConnectRedisOnStartupAsync>d__0.MoveNext() in D:\project-governance\Governance.Api\lib.Redis\MicrosoftExtensions\IHostExtensions.cs:line 10
   at Api.Reporting.Program.<Main>d__0.MoveNext() in D:\project-governance\Governance.Api\Api.Reporting\Program.cs:line 15

port 6780 is exposed a sentinel.

**Comment by slorello89** [comment]
Fundamentally your issue is that the sentinels only know about the IPs of the docker network, that networks ips are not reachable from your local interface. So while you CAN connect to the sentinel to get the topography, when it replies with the topography and the multiplexer tries to connect to the whole sentinel instance, it only sees a bunch of IPs that it can't reach. 

Try deploying your application with your docker-compose. That way it can see the network.

**Comment by remus-corneliu** [comment]
So to close this. Is my statment correct when I say  that in order to use sentinel mode, the app should run inside docker along with the redis configuration , and I cannot run during local development this mode ? 

Thank you!

**Comment by remus-corneliu** [comment]
I understand. 

Thank you @NickCraver and @slorello89  for the time and effort.
