### ISSUE TITLE
Is ServerMaintenanceEvent handler implemented?

### ISSUE THREAD

**Issue by sudheergn** [StackExchange/StackExchange.Redis#2301]
Hi,
https://github.com/StackExchange/StackExchange.Redis/blob/main/docs/ServerMaintenanceEvent.md suggests that ConnectionMultiplexer has ServerMaintenanceEvent event handler. (to get notifications when Azure Redis cache does failover)
But I am not seeing that with version 2.6.70 of StackExchange.Redis nuget package.

I dont see it in https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/Interfaces/IConnectionMultiplexer.cs
too

Did the feature get reverted for some reason? Or am I missing something?

Thanks
Sudheer

**Comment by mgravell** [comment]
Definitely exists:  https://github.com/StackExchange/StackExchange.Redis/blob/9af4b75c7609f36426e26e820dc63b1254484de9/src/StackExchange.Redis/ConnectionMultiplexer.Events.cs#L90

I can easily imagine we failed to add it to the interface, though :( we can fix that

**Comment by NickCraver** [comment]
This is added to `IConnectionMultiplexer` as well for the next release, so closing this out :)
