### ISSUE TITLE
Redis timeouts and memory dump shows... deadlock?

### ISSUE THREAD

**Issue by razzemans** [StackExchange/StackExchange.Redis#2304]
We were running a load test on our Azure App Service and I see some confusing results. Actually the applications crashed, mostly an OutOfMemoryException, but the dump files and logs show some data that I would like to fully comprehend. First of all, most of the logs show something like:

```
Timeout awaiting response

(outbound=5490KiB, inbound=13804KiB, 8890ms elapsed, timeout is 5000ms), 
command=GET, 
active: GET XXX, 
next: GET XXX, 
inst: 0, 
qu: 175, 
qs: 0, 
aw: True, 
bw: WritingMessage, 
rs: ComputeResult, 
ws: Writing, 
in: 65536, 
serverEndpoint: xxx,
mc: 1/1/0, 
mgr: 8 of 10 available, 
clientName: XXX(SE.Redis-v2.5.43.42402), 
IOCP: (Busy=5,Free=995,Min=200,Max=1000), 
WORKER: (Busy=13,Free=1010,Min=200,Max=1023), 
POOL: (Threads=138,QueuedItems=25,CompletedItems=9768), 
v: 2.5.43.42402
```

The dump files shows there are 172 tasks waiting on another thread:

![image](https://user-images.githubusercontent.com/1167518/202453610-8bc11e0a-92ec-4686-8040-0226ed9ec262.png)

Which is actually this code:

![image](https://user-images.githubusercontent.com/1167518/202463641-9a58c3be-90e8-45b8-a089-e50539001d0c.png)

Then if I drill down on the "lock owned by thread 33216" it points me to this line of code:

![image](https://user-images.githubusercontent.com/1167518/202453798-05ef4a4e-87c7-472e-be24-37792cf1f9a1.png)

Questions:

1. Is this an actual deadlock?
2. Do these 172 threads more or less correlate with the `qu` number in the log message (which is the number of items queued to be written if I am correct)
3. What is the difference between `inbound` and `in`?
4. Any other troubling observations from the log?

I have a feeling we were just CPU bound on our App Service (even though we weren't hitting 100% CPU) and what I am seeing is the consequence of that, but I just want to be sure.

**Comment by razzemans** [comment]
Ok will definitely update to the latest packages.

**Comment by NickCraver** [comment]
Given this is almost certainly the resolved issue, going to close this out - @razzemans if the problem remains, please ping here and we'll reopen!
