### ISSUE TITLE
The StackExchange.Redis doesn't support net7.0 target framework

### ISSUE THREAD

**Issue by ykirichenko** [StackExchange/StackExchange.Redis#2308]
When new ConnectionMultiplexer instance creates and try to connect

ConnectionMultiplexer.Connect(connectionString)

the following error occurred:

"It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code."

**Comment by NickCraver** [comment]
net7.0 is supported - you don't an update every time a new version is released unless compatibility has broken.

Pass a logger into your Connect method to see what's happening in your connection, this is much more likely about your config or environment.

**Comment by ykirichenko** [comment]
Few investigation results. Yes, in fact the issue is not related to net7.0. It appears after upgrade 2.6.48->2.6.66 (I think the problem is in the three sixes :) ) and reproduces with net6.0 framework. To fix this I've added the "abortConnect=false" configuration option and it works in 2.6.66 and with net7.0 + 2.6.70 of lib.

My code is here:
<code>var connectionString = "localhost:6379,allowAdmin=true,connectTimeout=1000,syncTimeout=1000,abortConnect=false,ssl=false";
 var client = ConnectionMultiplexer.Connect(connectionString, log);
</code>

**And log for 2.6.48:**
Connecting (sync) on .NET 6.0.11 (StackExchange.Redis: v2.6.48.48654)
localhost:6379,syncTimeout=1000,allowAdmin=True,connectTimeout=1000,ssl=False

localhost:6379/Interactive: Connecting...
localhost:6379: BeginConnectAsync
1 unique nodes specified (with tiebreaker)
localhost:6379: OnConnectedAsync init (State=Connecting)
Allowing 1 endpoint(s) 00:00:00.9950000 to respond...
Awaiting 1 available task completion(s) for 995ms, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=2,Free=32765,Min=12,Max=32767), POOL: (Threads=9,QueuedItems=0,CompletedItems=13)
localhost:6379/Interactive: Connected 
localhost:6379: Server handshake
localhost:6379: Setting client name: DESKTOP-VA4O8LM(SE.Redis-v2.6.48.48654)
localhost:6379: Auto-configuring...
localhost:6379: Requesting tie-break (Key="__Booksleeve_TieBreak")...
localhost:6379/Interactive: Writing: GET __Booksleeve_TieBreak
localhost:6379: Sending critical tracer (handshake): ECHO
localhost:6379/Interactive: Writing: ECHO
localhost:6379: Flushing outbound buffer
localhost:6379: OnEstablishingAsync complete
localhost:6379: Starting read
localhost:6379: Auto-configured (CONFIG) read-only replica: true
localhost:6379: Auto-configured (CONFIG) databases: 16
localhost:6379: Auto-configured (INFO) role: primary
localhost:6379: Auto-configured (INFO) version: 3.2.100
localhost:6379: Auto-configured (INFO) server-type: standalone
Response from localhost:6379/Interactive / GET __Booksleeve_TieBreak: (null)
Response from localhost:6379/Interactive / ECHO: BulkString: 16 bytes
localhost:6379: OnConnectedAsync completed (From command: ECHO)
All 1 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=2,Free=32765,Min=12,Max=32767), POOL: (Threads=9,QueuedItems=0,CompletedItems=26)
Endpoint summary:
  localhost:6379: Endpoint is ConnectedEstablished
  localhost:6379: Returned with success as Standalone primary (Source: From command: ECHO)
Election summary:
  Election: localhost:6379 had no tiebreaker set
  Election: Single primary detected: localhost:6379
localhost:6379: Clearing as RedundantPrimary
Endpoint Summary:
  localhost:6379: Standalone v3.2.100, primary; 16 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
  localhost:6379: int ops=10, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
  localhost:6379: Circular op-count snapshot; int: 0+10=10 (1.00 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Starting heartbeat...
Total connect time: 456 ms

**And log for 2.6.66:**
Connecting (sync) on .NET 6.0.11 (StackExchange.Redis: v2.6.66.47313)
localhost:6379,syncTimeout=1000,allowAdmin=True,connectTimeout=1000,ssl=False

localhost:6379/Interactive: Connecting...
localhost:6379: BeginConnectAsync
1 unique nodes specified (with tiebreaker)
localhost:6379: OnConnectedAsync init (State=Connecting)
Allowing 1 endpoint(s) 00:00:01 to respond...
Awaiting 1 available task completion(s) for 1000ms, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=0,Free=32767,Min=12,Max=32767), POOL: (Threads=5,QueuedItems=0,CompletedItems=12)
Not all available tasks completed cleanly (from ReconfigureAsync#1284, timeout 1000ms), IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=3,Free=32764,Min=12,Max=32767), POOL: (Threads=8,QueuedItems=0,CompletedItems=14)
  Server[0] (localhost:6379) Status: WaitingForActivation (inst: 0, qs: 0, in: 0, qu: 0, aw: False, in-pipe: -1, out-pipe: -1, bw: Inactive, rs: NotStarted. ws: Initializing)
Endpoint summary:
  localhost:6379: Endpoint is Connecting
  localhost:6379: Did not respond
Election summary:
  Election: localhost:6379 had no tiebreaker set
  Election: No primaries detected
Endpoint Summary:
  localhost:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
localhost:6379: OnConnectedAsync completed (Disconnected)
  localhost:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=1
  localhost:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Resetting failing connections to retry...
  Retrying - attempts left: 2...
1 unique nodes specified (with tiebreaker)
localhost:6379: OnConnectedAsync init (State=Connecting)
Allowing 1 endpoint(s) 00:00:01 to respond...
Awaiting 1 available task completion(s) for 1000ms, IOCP: (Busy=4,Free=996,Min=12,Max=1000), WORKER: (Busy=3,Free=32764,Min=12,Max=32767), POOL: (Threads=11,QueuedItems=0,CompletedItems=20)
localhost:6379: OnConnectedAsync completed (Disconnected)
All 1 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=3,Free=32764,Min=12,Max=32767), POOL: (Threads=12,QueuedItems=0,CompletedItems=26)
Endpoint summary:
  localhost:6379: Endpoint is Disconnected
  localhost:6379: Returned, but incorrectly
Election summary:
  Election: localhost:6379 had no tiebreaker set
  Election: No primaries detected
Endpoint Summary:
  localhost:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
  localhost:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=2
  localhost:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Resetting failing connections to retry...
  Retrying - attempts left: 1...
1 unique nodes specified (with tiebreaker)
localhost:6379: OnConnectedAsync init (State=Connecting)
Allowing 1 endpoint(s) 00:00:01 to respond...
Awaiting 1 available task completion(s) for 1000ms, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=3,Free=32764,Min=12,Max=32767), POOL: (Threads=12,Queued

**Comment by NickCraver** [comment]
@ykirichenko checking in: did you figure this out locally? (see Marc's advice above as well)

**Comment by NickCraver** [comment]
Closing this unless there's more to go on - happy to reopen if still having issues :) Hopefully the above advice helped!
