### ISSUE TITLE
how to do bulk insertion of hashsets in Redis?

### ISSUE THREAD

**Issue by Hela-Masri-shift** [StackExchange/StackExchange.Redis#2310]
Hello,
I need to insert millions of hashsets into a redis database. 
What is the fastest way to do it? The time really counts in this application context.
I know that with Redis commands, there is the --pipe mode, is there any equivalent
implementation in StackExchange.Redis?

Thanks

**Comment by slorello89** [comment]
StackExchange.Redis will automagically pipeline everything for you under the hood. What I've always done is dispatch tasks using the async api, and await them in batches or in aggregate at the end. @mgravell or @NickCraver probably have a more informed opinion than I do, but my pipelining ops follow a pattern along the lines of this toy example:

```cs
var insertTasks = new List<Task>();
var stopwatch = Stopwatch.StartNew();
for (var i = 0; i < 100_000; i++)
{
    insertTasks.Add(db.HashSetAsync(Guid.NewGuid().ToString(), "toy", "example"));
}

await Task.WhenAll(insertTasks);
stopwatch.Stop();
Console.WriteLine($"Insertions took: {stopwatch.Elapsed}");
```

You can also use the Batching API, if you really want to control what's being pipelined to Redis, but I've found just the async API sufficient for my purposes in the past

**Comment by Hela-Masri-shift** [comment]
Thank you for the answer, I will give a try and let you know.
Otherwise, what do you mean by the  the Batching API?

**Comment by slorello89** [comment]
You can create an IBatch by using `db.CreateBatch()`. IBatch exposes all db commands as async commands. you can queue up as many commands as you want, and when you call `Execute` on the batch it will send them all over to Redis. It's basically explicit pipelining whereas the async pattern above is implicit. But it will guarantee that the client does not interleave other commands with the commands that you've batched.

**Comment by mgravell** [comment]
SE.Redis pipelines by default; to do this aggressively from a single caller:

1. Use CommandFlags.FireAndForget (noting that this means you won't observe
failures), or
2. Use a pipeline of overlapped async operations - perhaps via a
`Queue<Task>` - loop and add; when it becomes "full" to some number N, pop
and await the last - then you should have N in-flight operations, while
observing errors

**Comment by NickCraver** [comment]
Closing out to tidy up :)
