### ISSUE TITLE
Yet another timeout issue

### ISSUE THREAD

**Issue by soenneker** [StackExchange/StackExchange.Redis#2319]
Hi guys,

Wondering if you can take a look at this timeout exception. This app is using .NET7, deployed on a Web App (Windows Service Plan) using Azure Redis (production tier)

`StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=68KiB, inbound=1215KiB, 5922ms elapsed, timeout is 5000ms), command=GET, next: GET <redacted>, inst: 0, qu: 0, qs: 0, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 0, last-in: 2, cur-in: 69640, serverEndpoint: <redacted>, mc: 1/1/0, mgr: 9 of 10 available, clientName: WN0SDWK0000GP(SE.Redis-v2.6.80.25426), IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=3,Free=32764,Min=100,Max=32767), POOL: (Threads=5,QueuedItems=0,CompletedItems=13784123), v: 2.6.80.25426 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

I've increased the number in the pool, prior to this exception:
```ThreadPool.SetMinThreads(100, 100);```

It seems to occur randomly; and a lot of my requests will timeout at once. This isn't a new issue, it's been happening for several months.

Anything stand out?

Thanks

**Comment by NickCraver** [comment]
This looks like a bandwidth/payload issue rather than threads given the counters. What are your payload sizes here?

**Comment by soenneker** [comment]
> This looks like a bandwidth/payload issue rather than threads given the counters. What are your payload sizes here?

The size of the key can be anywhere between 10-100k. I haven't seen any correlation between the larger keys and this error occurring, but it could be.

What's the best way I can validate if I'm running into bandwidth/payload issues?

**Comment by NickCraver** [comment]
@soenneker apologies, missed reply here - the best way would be any external monitoring but on the timeout exceptions you can see the `cur-in` counter and how much is on the wire coming in to be read, I'd see if that's fairly consistently high.

**Comment by NickCraver** [comment]
Closing out to cleanup, but happy to reopen if there's further info here.
