### ISSUE TITLE
MOVED and CommandFlags.NoRedirect

### ISSUE THREAD

**Issue by pianoman4873** [StackExchange/StackExchange.Redis#2324]
Hi , 
We're running the StackExchange Redis client against an AWS cluster of 8 nodes ( 8 masters with a single replica for each )

We got this exception yesterday from the client - 
Partially successfully processed keys count = 0 , first 10 keys are ---> StackExchange.Redis.RedisServerException: Key has MOVED to Endpoint 10.71.88.95:6379 and hashslot 3830 but CommandFlags.NoRedirect was specified - redirect not followed for GET U.0:U_6831. at  

Any idea what could be the reason for the MOVED reply from the server ( as the topology hasn't changed as far as we know ), and why isn't the MOVED followed by the client ?
In the CommandFlags we **never** use the NoRedirect flag.

After restarting the faulting clients the issue was resolved.

Thanks !

**Comment by mgravell** [comment]
I'd need to check the code, but I *think* (from memory) we add this flag
when already following a redirect, to avoid infinite/lengthy bounces. IMO
the most likely things here is that AWS re-balanced the shards, and
something got confused. If you want to be sure nothing has been moved,
you'd need to take a snapshot of the shard layout for comparison - however,
such a move could be temporary, to move data off one shard for maintenance,
so: it could be back to normal by the time you investigate.

**Comment by pianoman4873** [comment]
Thanks Marc - we didn't invoke any rebalancing manually - could be some temporary maintenance as you mentioned :(
Would you suggest anything else to mitigate this situations ?

**Comment by mgravell** [comment]
It is hard to mitigate the data for a slot being unavailable, which *from the client's perspective* is what happened here; there may be admin tools in AWS to at least allow you to investigate this. Note that the Azure redis folks have been proposing a pattern of system-integrated announcement of admin operations, which Azure now implements, which allows tools better chance to prepare for and respond to maintenance events - they (Azure redis) have been trying to get other providers on board.

**Comment by NickCraver** [comment]
This happens to coincide with the latest release - if you grab 2.6.86 or later, it has additional handling to adapt to cluster changes (resulting in MOVED responses) more rapidly.

**Comment by NickCraver** [comment]
Advice here is to upgrade to latest library version which handles this case a bit better - closing out to tidy up here!
