### ISSUE TITLE
Managed Debugging Assistant 'FatalExecutionEngineError'

### ISSUE THREAD

**Issue by dpuza-formativ** [StackExchange/StackExchange.Redis#2327]
Repeatedly get this fatal exception in some of our dev environments when trying to start our web app that uses StackExchange.Redis.  Using IIS Express / Visual Studio.  It kills the process, resulting in being unable to start our web app in these environments while this issue persists.

Restarting Windows does not resolve the error.  But... sometimes, it does.  Then it will work more or less fine until about the next morning when this fatal exception tends to appear in the environment again.

StackExchange.Redis v2.6.80 and previous (2.6.66)
Server redis_version: 3.2.100

```
Managed Debugging Assistant 'FatalExecutionEngineError' 
  Message=Managed Debugging Assistant 'FatalExecutionEngineError' : 'The runtime has encountered a fatal error. The address of the error was at 0x3c858f69, on thread 0x254c. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'

```

```
Call Stack
>	[External Code]
>	StackExchange.Redis.dll!StackExchange.Redis.RedisSubscriber.Publish(StackExchange.Redis.RedisChannel channel, StackExchange.Redis.RedisValue message, StackExchange.Redis.CommandFlags flags) Line 342	C#
>	[External Code]
```

**Comment by NickCraver** [comment]
This is super interesting, would not expect this at all. A few questions:
1. Is it consistent? Same call stack every time? (Can you share more from the stack?)
2. Same machine or on multiple?
3. Which version of .NET are you running on?
4. 32 or 64-bit?
5. Is the profiler or debugger attached?
6. Does it happen in both Release and Debug?

This may be a runtime problem somehow, or with some other library interaction, but trying to think of how to advise better here. The stack location you're at is all managed code so...it's quite strange to see something like this.

**Comment by dpuza-formativ** [comment]
> Is it consistent?

It's consistent.  Today, it's happened every time I attempted it, probably about 20 times in a row, through multiple Windows and Redis service restarts, FLUSHALLs.  I ended up completely disabling Redis in my project otherwise I wouldn't be able to continue with my work.

> Same call stack every time? (Can you share more from the stack?)

Yes, same call stack every time, and that is the entire stack:  "External code" > Publish, Line 342 > "External code"

> Same machine or on multiple?

Same machine.  Not certain about others.  Have run into intermittent issues but not sure if it's identical. 

> Which version of .NET are you running on?

.NET Framework 4.6.1.  Building "Any CPU", but on a 64-bit system.

> Is the profiler or debugger attached?  Does it happen in both Release and Debug?

So far I've been trying in Debug with the debugger attached.  I can attempt the other and let you know.

**Comment by dpuza-formativ** [comment]
> 6. Does it happen in both Release and Debug?

Happens in Release mode too.  The IISEXPRESS process just disappears, and from there of course I can no longer make any requests to the site.

**Comment by NickCraver** [comment]
The most interesting thing would be if you can reproduce this on another machine. Given what's wrong it really seems like a corrupted .NET Framework install is well within a reasonable possibility.

Which version of .NET does the machine have? Target usually isn't relevant here, only what you're running on (can only be 1 version on the machine here, 4.6.1 or higher).

**Comment by dpuza-formativ** [comment]
> Which version of .NET does the machine have? Target usually isn't relevant here, only what you're running on (can only be 1 version on the machine here, 4.6.1 or higher).

RuntimeInformation.FrameworkDescription returns ".NET Framework 4.8.4515.0"

**Comment by NickCraver** [comment]
I'd give this a go: https://support.microsoft.com/en-us/topic/microsoft-net-framework-repair-tool-is-available-942a01e3-5b8b-7abb-c166-c34a2f4b612a

What you're hitting is very, very unlikely to be a problem with the library just trying to help fix the core issue we're tripping on here.

If that doesn't work: try running with antivirus disabled for one go for a sanity check, and last do a disk check with sfc /scannow.

**Comment by dpuza-formativ** [comment]
Thanks, FWIW here is a sequence of events which followed:

I ran the repair tool.  It reported that it was "unable to resolve" the issue:

![2022-12-21 16_50_25-Mail](https://user-images.githubusercontent.com/32490645/209194785-b67690aa-0424-41bc-96c2-3618ee0690da.png)

Afterward, I was still getting the fatal Redis exception.

After rebooting, I happened to no longer be able to connect to our VPN.  I contacted our tech support.  They ended up uninstalling and reinstalling Cisco, and I was able to connect to the VPN again.

At this point, I made another attempt running our web app.  This time, the web app is running successfully.  I did not get the Redis exception.

FWIW the Cisco error message was "AnyConnect was not able to establish a connection to the specified secure gateway.  Please try connecting again.".  I also rebooted my cable modem and router during that troubleshooting and restarted my computer again.

The Redis instance I've been connecting to is the same machine: 127.0.0.1:6379.

**Comment by NickCraver** [comment]
I'm not sure what to make of that combo honestly, but it does seem like something specific to that machine and corruption is inherently hard to reason about. I'd say if it repeats poke here but I believe you're hitting something external to the library and just by chance, it's happening at this point. Hope you're all sorted after the current changes!

**Comment by NickCraver** [comment]
Since this was very specific machine corruption, not sure there's any other advice we can offer - going to tidy up here :)
