### ISSUE TITLE
RedisCache initialization exception: System.Threading.ThreadAbortException: Thread was being aborted. xx:xx:xx.xxxx: Encountered error while updating cluster config: Cannot access a disposed object. Object name: 'xxxxxxxxxxxxx(SE.Redis-v2.5.61.22961)'.

### ISSUE THREAD

**Issue by ribarua** [StackExchange/StackExchange.Redis#2329]
Hi Redis folks,
We keep getting ThreadAbort exceptions occasionally, when trying to connect to Redis endpoints. Can you please help us understand if this is a bug or something we need to fix in the client upstream.

System.Threading.ThreadAbortException: Thread was being aborted...............................
.........................................................................................................
10:53:19.1286: Endpoint summary:
10:53:19.1286:   xxxxxxxxxx.redis.cache.windows.net:6380: Endpoint is ConnectedEstablished
10:53:19.1286:   xxxxxxxxxx.redis.cache.windows.net:6380: Returned with success as Cluster primary (Source: From command: ECHO)
10:53:19.1286: Encountered error while updating cluster config: Cannot access a disposed object.
Object name: 'xxxxxxxxxxxxxxxxxx(SE.Redis-v2.5.61.22961)'.
10:53:19.1286: Cluster: 16384 of 16384 slots covered
10:53:19.1286: Endpoint Summary:
10:53:19.1286:   xxxxxxxxxx.redis.cache.windows.net:6380: Cluster v4.0.14, primary; keep-alive: 00:01:00; int: ConnectedEstablished; sub: n/a
10:53:19.1286:  xxxxxxxxxx.redis.cache.windows.net:6380: int ops=13, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=0, qu=0, qs=0, qc=0, wr=0
10:53:19.1286:   xxxxxxxxxx.redis.cache.windows.net:6380: Circular op-count snapshot; int: 0+13=13 (1.30 ops/s; spans 10s); sub:
10:53:19.1286:   20.112.10.32:15012: Standalone v4.0.0, primary; keep-alive: 00:01:00; int: Connecting; sub: n/a
10:53:19.1286:   20.112.10.32:15012: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=0, qu=0, qs=0, qc=0, wr=0
10:53:19.1286:   20.112.10.32:15012: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub:
10:53:19.1286:   20.112.10.32:15014: Standalone v4.0.0, primary; keep-alive: 00:01:00; int: Connecting; sub: n/a

**Comment by ribarua** [comment]
Messaged you on teams with the stacktrace.

**Comment by NickCraver** [comment]
Closing out here since we move the discussion elsewhere. For anyone finding this later: Thread.Abort() does very bad things, including hosing this library under a lot of circumstances, so avoid that at all costs :)
