### ISSUE TITLE
Failing to connect on MacOSX Mono 

### ISSUE THREAD

**Issue by barambani** [StackExchange/StackExchange.Redis#233]
Hi,
I'm trying to connect the Redis client to a local instance of Redis Server on Mac OSX using Mono (Mono .NET 4.5).
If I use the NuGet Package (ver 1.0.450) it fails but if I download the code, build it with monobuild.bash and I reference the dll created it works fine.

I use the following code to test the connection

```
public static void Main(string[] args)
{
    var sw = new StringWriter();

    try
    {
        var configOptions = new ConfigurationOptions() 
            {
                EndPoints =
                    {
                        { "localhost", 6379 },
                    },
                ResolveDns = true,
                KeepAlive = 180
            };

        ConnectionMultiplexer.Connect(configOptions, sw);
    }
    catch (System.Exception ex)
    {
        Console.Out.WriteLine(sw);
    }
    finally
    {
        sw.Close();
    }
}
```

And I get the following logs

```
localhost:6379,keepAlive=180,resolveDns=True

Using DNS to resolve 'localhost'...
'localhost' => 127.0.0.1
Connecting 127.0.0.1:6379/Interactive...
BeginConnect: 127.0.0.1:6379
1 unique nodes specified
Requesting tie-break from 127.0.0.1:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=2,Free=398,Min=4,Max=400)
EndConnect: 127.0.0.1:6379
Connect complete: 127.0.0.1:6379
All tasks completed cleanly, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=2,Free=398,Min=4,Max=400)
127.0.0.1:6379 faulted: UnableToResolvePhysicalConnection on PING
All tasks are already complete
127.0.0.1:6379 failed to nominate (Faulted)
> UnableToResolvePhysicalConnection on GET
No masters detected
127.0.0.1:6379: Standalone v2.0.0, master; keep-alive: 00:03:00; int: Connecting; sub: Connecting; not in use: DidNotRespond
127.0.0.1:6379: int ops=0, qu=0, qs=0, qc=1, wr=0, sync=1, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=1
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 2...
1 unique nodes specified
Requesting tie-break from 127.0.0.1:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=2,Free=398,Min=4,Max=400)
All tasks completed cleanly, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=2,Free=398,Min=4,Max=400)
127.0.0.1:6379 returned, but incorrectly
Awaiting task completion, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=2,Free=398,Min=4,Max=400)
All tasks completed cleanly, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=2,Free=398,Min=4,Max=400)
127.0.0.1:6379 failed to nominate (Faulted)
> UnableToResolvePhysicalConnection on GET
No masters detected
127.0.0.1:6379: Standalone v2.0.0, master; keep-alive: 00:03:00; int: Disconnected; sub: Connecting; not in use: DidNotRespond
127.0.0.1:6379: int ops=0, qu=0, qs=0, qc=1, wr=0, sync=1, async=4, socks=3; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=2
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 1...
1 unique nodes specified
Requesting tie-break from 127.0.0.1:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=2,Free=398,Min=4,Max=400)
All tasks completed cleanly, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=2,Free=398,Min=4,Max=400)
127.0.0.1:6379 returned, but incorrectly
Awaiting task completion, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=2,Free=398,Min=4,Max=400)
All tasks completed cleanly, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=2,Free=398,Min=4,Max=400)
127.0.0.1:6379 failed to nominate (Faulted)
> UnableToResolvePhysicalConnection on GET
No masters detected
127.0.0.1:6379: Standalone v2.0.0, master; keep-alive: 00:03:00; int: Disconnected; sub: Connecting; not in use: DidNotRespond
127.0.0.1:6379: int ops=0, qu=0, qs=0, qc=1, wr=0, sync=1, async=7, socks=4; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=3
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
```

Is this an expected behaviour ? Is Mono supported by the NuGet package of the Redis client ?
Thanks a lot for the help.

**Comment by kevfromireland** [comment]
Mono doesn't seem to be supported by the NuGet package, but if I build using `monobuild.bash` then everything works fine.

Should we just start publishing a nuget package that has been built with `monobuild.bash` and call it `StackExchange.Redis.Mono` ?

**Comment by MichaCo** [comment]
@kevfromireland yup currently you have to build the mono version.
Hopefully, this library gets build with the new .NET CORE at some point and this goes away ;)

**Comment by mgravell** [comment]
does it work if you use an IP address rather than a name?

I spent a pile of days trying to get the .net core version working happily, but it took longer than the time I had...

**Comment by mgravell** [comment]
if anyone knows if there is a magic string for nuget for mono-specific builds, we can probably fix the build

**Comment by kevfromireland** [comment]
Tried with IP address but no joy (might be subtly different connection issue to OP, but same fix :) ) .

If you don't want to do a separate package, then would it be possible to change the bits that are currently `#if __MONOCS__` to instead check for `Environment.OSVersion.Platform == Unix` ?

**Comment by mgravell** [comment]
@kevfromireland no, because some of those bits use APIs that don't exist... it won't make it past JIT

**Comment by barambani** [comment]
I confirm, no luck with the IP address.

**Comment by thecopy** [comment]
I have the same problem for Core CLR, for both IP and hostname.

**Comment by IonoclastBrigham** [comment]
I spent all day banging my head against a wall, on this one. If you catch the exception and try connecting again (as some threads suggest) it definitely starts accumulating tasks that will never complete. There's some kind of deadlock or uncaught error causing thread starvation in there.

As soon as I built with monobuild.bash, it just magically starts working. I was going to do that originally, but was seduced by the siren call of NuGet... :(

**Comment by zach-yu** [comment]
I confirm this problem on mono/osx. keep get errors as following:
localhost:6379,abortConnect=False,connectRetry=1

> Connecting localhost:6379/Interactive...
BeginConnect: localhost:6379
1 unique nodes specified
Requesting tie-break from localhost:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=1,Free=399,Min=4,Max=400)
EndConnect: localhost:6379
Connect complete: localhost:6379
All tasks completed cleanly, IOCP: (Busy=0,Free=16,Min=8,Max=16), WORKER: (Busy=2,Free=398,Min=4,Max=400)
localhost:6379 faulted: UnableToResolvePhysicalConnection on PING
All tasks are already complete
localhost:6379 failed to nominate (Faulted)
UnableToResolvePhysicalConnection on GET
No masters detected
localhost:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Connecting; sub: Connecting; not in use: DidNotRespond
localhost:6379: int ops=0, qu=0, qs=0, qc=1, wr=0, sync=1, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=1
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s);

**Comment by barambani** [comment]
@zach-yu have you tried running monobuild.bash in terminal ? after that you have to reference the dll created inside the bin/mono folder by the script.
I haven't tried it in a while but was working for me.

**Comment by zach-yu** [comment]
yes I did have tried that. the version for mono was 1.0.0. and I have changed my project to refer to the new dll.

**Comment by barambani** [comment]
I see, then it looks a different issue from this one.
The one I opened is about the NuGet packed version of the client not working on Mac/Mono. If built from the code using the script, the client works fine for the sample code above (I checked again right now).

**Comment by NickCraver** [comment]
Closing this out consolidate tracking of the same-assembly Mono build effort in #314
