### ISSUE TITLE
Thread Safety Violation warnings found by InferSharp

### ISSUE THREAD

**Issue by udlose** [StackExchange/StackExchange.Redis#2331]
I am using StackExchange.Redis v2.6.86 in my .NET 7 API. I am using the new Microsoft Static Analysis Tool ([InferSharp](https://github.com/microsoft/infersharp)) to analyze my code as well as dependent packages and I found a few Thread Safety Violation warnings:
```
/_/src/StackExchange.Redis/LogProxy.cs:14: warning: Thread Safety Violation
  Read/Write race. Non-private method `LogProxy.ToString()` reads without synchronization from `this.StackExchange.Redis.LogProxy._log`. Potentially races with write in method `LogProxy.Dispose()`.
 Reporting because this access may occur on a background thread.

/_/src/StackExchange.Redis/LogProxy.cs:30: warning: Thread Safety Violation
  Read/Write race. Non-private method `LogProxy.WriteLine()` reads without synchronization from `this.StackExchange.Redis.LogProxy._log`. Potentially races with write in method `LogProxy.Dispose()`.
 Reporting because this access may occur on a background thread.

/_/src/StackExchange.Redis/LogProxy.cs:40: warning: Thread Safety Violation
  Read/Write race. Non-private method `LogProxy.WriteLine(...)` reads without synchronization from `this.StackExchange.Redis.LogProxy._log`. Potentially races with write in method `LogProxy.Dispose()`.
 Reporting because this access may occur on a background thread.

/_/src/StackExchange.Redis/LogProxy.cs:50: warning: Thread Safety Violation
  Read/Write race. Non-private method `LogProxy.WriteLine(...)` reads without synchronization from `this.StackExchange.Redis.LogProxy._log`. Potentially races with write in method `LogProxy.Dispose()`.
 Reporting because this access may occur on a background thread.

/_/src/StackExchange.Redis/LogProxy.cs:60: warning: Thread Safety Violation
  Read/Write race. Non-private method `LogProxy.Dispose()` reads without synchronization from `this.StackExchange.Redis.LogProxy._log`. Potentially races with write in method `LogProxy.Dispose()`.
 Reporting because this access may occur on a background thread.
```

**Comment by NickCraver** [comment]
Not sure what to say on this: yes, [it is safe and locked](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/LogProxy.cs). This sounds like a bug report for the analysis tool to improve on. I'm not against changing the code slightly to make things happy, but this isn't an actual issue and since `_log` may be null, most other approaches are going to be messier.

Given the problem is with a false flag, I'd rather leave this as is and suggest filing an issue on the InferSharp repo :)

**Comment by udlose** [comment]
@NickCraver I appreciate your fast reply! I just wanted to alert you if there were issues. I can open a bug report with the InferSharp repo if you feel that is the case.

**Comment by NickCraver** [comment]
Yeah I'd ask that crew - basically this is synchronized via another object (which is necessary, since `_log` may be null) and the analyzer doesn't seem to handle it.

**Comment by udlose** [comment]
Appreciate your input. I'll open an issue in their repo.

**Comment by udlose** [comment]
@NickCraver  Looking at the code you referenced, I just noticed that the `SyncLock` is on the `this` pointer - https://github.com/StackExchange/StackExchange.Redis/blob/e596322aefbe22a13accbdd0e4a76022c1ccbda9/src/StackExchange.Redis/LogProxy.cs#L26

IIRC, this is a red flag and leaves the code open for deadlocks/lock contention since the internal class can be locked by another since both the `LogProxy` class and its `SyncLock` member are visible to other classes.

- https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/lock#guidelines
- https://app.pluralsight.com/guides/lock-statement-best-practices

I also see that there is no call to either `GC.SuppressFinalize()` in `Dispose` nor a call to `_log.Dispose()`.  Should I open a PR for these 3 things?

**Comment by mgravell** [comment]
It is not necessary to call `GC.SuppressFinalize` in the general case; that is *only* useful if a type either has a finalizer or we should reasonable *anticipate* a finalizer due to inheritance; `LogProxy` is `internal` and `sealed` - it cannot be subclassed, so will never have a finalizer.

Likewise, since `LogProxy` is internal and not publicly exposed via an interface or similar, it *cannot* be `lock`-ed by external code, and our internal code *does not* `lock` it.

These guidances can be over-applied. They have value, but it is necessary to understand what each means, and how that applies in a specific context.

**Comment by udlose** [comment]
> Likewise, since LogProxy is internal and not publicly exposed via an interface or similar, it cannot be lock-ed by external code, and our other internal code does not lock it.

I'd consider "external code" to be any class outside of `LogProxy` itself - wither within or external to your assembly.  You can't stop someone from locking on the code within your library (other than a code review on a PR) again leaving it susceptible to human error to be missed.

> These guidances can be over-applied. They have value, but it is necessary to understand what each means, and how that applies in a specific context.

Respectfully, I don't agree that a best-practice can be over-applied but I respect that you have a different opinion.  I'm used to working on SDK's and API's that have many developers/contributors. So I do not always have fine-grained control (outside of a PR which things can be (and sometimes are) missed. Other developers learn from (and tend to repeat) patterns of code that they see. If there is a place where technically the "best-practice" has no effect on the runtime behavior (arguably the case here), then they may think it should always be done this way.

WRT, not calling `Dispose` on the `TextWriter`, it leaves it up for the GC and the Finalizer to clean up.  This means its lifetime is promoted from Gen0 to Gen1.  My guess is that you'd argue that `TextWriter` does not have a Finalizer and thus would not cause GC promotion.  I'd say it is not a good practice to rely on the internal implementation of an API of which you have no control.

**Comment by mgravell** [comment]
> (other than a code review on a PR)

Good job we do code reviews, then! Given the choice of "allocate extra objects" vs "don't screw up", I'd argue that we're *always* at risk of screwing up, so we need to embrace that and work in a way that minimizes it. Adding a comment on the field of the form `// note: synchronized internally against self; do not use as a lock externally, or expose` - could be legit.

> I don't agree that a best-practice can be over-applied

Tools will *always* produce false positives; smashing your code out of shape to satisfy the current implementation of a single tool is not a good solution; sometimes the correct solution is a reasoned and documented suppression. I would *absolutely* accept a PR that added some suppression attributes, for example.

> WRT, not calling `Dispose` on the `TextWriter`

I didn't discuss that; I *only* discussed calling `GC.SuppressFinalize` on the `LogProxy`. Whether or not to call `Dispose` on the `TextWriter` is a very valid topic that hinges on the intended lifetimes and ownership. It simply isn't related to what I discussed.

**Comment by NickCraver** [comment]
LogProxy does not create the TextWriter, so calling Dispose on something it doesn't own is just wrong. Please don't do that anywhere. You'll cause bugs.

**Comment by udlose** [comment]
> > (other than a code review on a PR)
> Good job we do code reviews, then!

Yes, of course!  My point was that you are leaving it to an individual or group of individuals to catch it; thus, shouldn't be considered a fail-safe. Rather, it's another potential point of failure in SDLC. I know how PR's are done is a debate that could be endless and of many different opinions. However, my experience in 29 yrs. is that you might get 25% participation of your dev team (50% is rare). People avoid them for many reasons: too shy to participate, don't have the confidence to give another dev feedback (especially if they consider that dev "senior" to them), don't want to offend someone, team so big that everyone assumes someone else will do it, or mostly just too busy with their own work and view it as a distraction. BTW, I don't share this opinion and see it as a necessary part of SDLC.

> > I don't agree that a best-practice can be over-applied
> 
> Tools will _always_ produce false positives; smashing your code out of shape to satisfy the current implementation of a single tool is not a good solution; sometimes the correct solution is a reasoned and documented suppression. I would _absolutely_ accept a PR that added some suppression attributes, for example.

I should qualify my comment about "best-practices can't be over-applied"...I totally agree that static analysis tools inherently give false positives and there are times to suppress warnings.  I have done so _as needed_ in my coding lifetime.  The _as needed_ qualification though is a subjective one. I guess my comment was more specific to the 3 items I'd mentioned (best-practices _in this case_) and will remember to choose my words more carefully next time :)

**Comment by udlose** [comment]
@NickCraver that's what I get for doing a quick perusal of the `LogProxy` class. Yes, definitely don't dispose of something you own! But you do null it out in the `Dispose` method...https://github.com/StackExchange/StackExchange.Redis/blob/e596322aefbe22a13accbdd0e4a76022c1ccbda9/src/StackExchange.Redis/LogProxy.cs#L62

**Comment by udlose** [comment]
@NickCraver that's what I get for doing a quick perusal of the `LogProxy` class. Yes, definitely don't dispose of something you own! You do null it out in the `Dispose` method...https://github.com/StackExchange/StackExchange.Redis/blob/e596322aefbe22a13accbdd0e4a76022c1ccbda9/src/StackExchange.Redis/LogProxy.cs#L62 but that is just the copy of your rooted reference to the `TextWriter`
