### ISSUE TITLE
Troubleshooting eval timeouts

### ISSUE THREAD

**Issue by mrbillo** [StackExchange/StackExchange.Redis#2339]
We are having timeout errors under load. We're are at a loss on how to use the exceptions to know what the issue is. Asp.Net application with the Redis server on the same network. We are willing to hire a consultant to help solve this issue. Attached is an example error. Thanks
[rediserror.txt](https://github.com/StackExchange/StackExchange.Redis/files/10340830/rediserror.txt)

**Comment by NickCraver** [comment]
Overall this looks like an overload on the thread pool, complete message:
> Timeout performing EVAL (10000ms), next: EVAL, inst: 2, qu: 0, qs: 30, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, last-in: 0, cur-in: 2227321, sync-ops: 128019, async-ops: 0, serverEndpoint: redacted:6379, conn-sec: 326890.73, mc: 1/1/0, mgr: 9 of 10 available, clientName: WA3(SE.Redis-v2.6.86.49666), IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=31,Free=32736,Min=50,Max=32767), v: 2.6.86.49666 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

Notably: `WORKER: (Busy=31,Free=32736,Min=50,Max=32767)` indicates high thread utilization and `sync-ops: 128019, async-ops: 0` tells us it's all sync calls and not async calls. When the thread pool is exhausted, the application won't be able to handle results fast enough, which the inbound 2.2MB of payload confirms here. Overall: you want to go async whenever possible to alleviate thread pool pressure, otherwise those threads are in use, but wasted waiting and blocking other things from getting a thread and completing.

**Comment by mrbillo** [comment]
I have sync methods like context.Session[key]=object. Will making these async help this issue ? Also I'm not sure how to make sessionstate async. Thanks for your help, really in trouble here.

**Comment by mgravell** [comment]
What sessionstate implementation is this? Also, what framework?

**Comment by mrbillo** [comment]
.NET Framework 4.7.2  <sessionState cookieless="false" regenerateExpiredSessionId="true" mode="Custom" customProvider="RedisSessionStateStoreProvider" timeout="180"> ... <add name="RedisSessionStateStoreProvider" type="Microsoft.Web.Redis.RedisSessionStateProvider" accessKey="redacted" ssl="false" host="1redacted"
          port="6379" password="redacted" throwOnError="true" retryTimeoutInMilliseconds="4000" connectionTimeoutInMilliseconds="10000"
          operationTimeoutInMilliseconds="10000" AbortOnConnectFail="false" connectRetry="10" syncTimeout="10000" asyncTimeout="10000"
          IncludeDetailInExceptions="True"/>

**Comment by mrbillo** [comment]
server info:
# Server
redis_version:5.0.3
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:d0e2dcdeba8c0cee
redis_mode:standalone
os:Linux 4.18.0-372.9.1.el8.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.4.1
process_id:853518
run_id:6e02f1b556029c2dbbb1661a3ef95d4d83d5c3d8
tcp_port:6379
uptime_in_seconds:5991412
uptime_in_days:69
hz:10
configured_hz:10
lru_clock:11891386
executable:/usr/bin/redis-server
config_file:/etc/redis.conf

# Clients
connected_clients:7
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:0

# Memory
used_memory:83444552
used_memory_human:79.58M
used_memory_rss:282415104
used_memory_rss_human:269.33M
used_memory_peak:27423274264
used_memory_peak_human:25.54G
used_memory_peak_perc:0.30%
used_memory_overhead:955738
used_memory_startup:792056
used_memory_dataset:82488814
used_memory_dataset_perc:99.80%
allocator_allocated:84348648
allocator_active:95105024
allocator_resident:199114752
total_system_memory:33680732160
total_system_memory_human:31.37G
used_memory_lua:648192
used_memory_lua_human:633.00K
used_memory_scripts:3752
used_memory_scripts_human:3.66K
number_of_cached_scripts:5
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.13
allocator_frag_bytes:10756376
allocator_rss_ratio:2.09
allocator_rss_bytes:104009728
rss_overhead_ratio:1.42
rss_overhead_bytes:83300352
mem_fragmentation_ratio:3.39
mem_fragmentation_bytes:199012552
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:151226
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:336
rdb_bgsave_in_progress:0
rdb_last_save_time:1672835604
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:1814528
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:3186
total_commands_processed:702021706
instantaneous_ops_per_sec:8
total_net_input_bytes:1112117112990
total_net_output_bytes:100938906921653
instantaneous_input_kbps:0.29
instantaneous_output_kbps:581.85
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:97615
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:122566587
keyspace_misses:59949609
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:69454
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:c9424881c9ff23ac4586f355b367d49c070be936
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:53476.518549
used_cpu_user:100095.338278
used_cpu_sys_children:11038.822474
used_cpu_user_children:102664.040013

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=72,expires=72,avg_ttl=9993503

**Comment by philon-msft** [comment]
If this is the Microsoft.Web.RedisSessionStateProvider package, we're working on changes to make it async internally. 

Meanwhile, reducing the size of the session state payloads from 2.2MB will help prevent thread exhaustion.

**Comment by mrbillo** [comment]
Ok thanks!

**Comment by NickCraver** [comment]
Closing out to tidy up!
