### ISSUE TITLE
Correct way to delete keys by pattern via KeysAsync

### ISSUE THREAD

**Issue by w7rus** [StackExchange/StackExchange.Redis#2341]
KeysAsync function contains parameters such as ``cursor`` and ``pageOffset``, but i found no usages on them (or proper documentation)...

My current implementation to delete all matched keys is:
```
    public async Task DeleteItems(RedisValue pattern, int database = -1)
    {
        var endpoints = _connectionMultiplexer.GetEndPoints();
        var db = GetDatabase(database);

        foreach (var endpoint in endpoints)
        {
            var server = _connectionMultiplexer.GetServer(endpoint);

            if (!server.IsConnected || server.IsReplica) continue;

            bool hasMore;

            do
            {
                hasMore = false;
                
                await foreach (var key in server.KeysAsync(db.Database, pattern, 1024))
                {
                    await db.KeyDeleteAsync(key);
                    hasMore = true; //If at least one key been deleted, attempt to retrieve another page later
                }
            } while (hasMore); //hasMore remains false if nothing was iterated
        }
    }
```

Should i use cursor / pageOffset instead? If so, how then? If using cursor, what is the stopping condition should be?

**Comment by mgravell** [comment]
Those parameters are for *very* niche scenarios involving custom iteration
and resuming walks. You almost certainly don't need them. The library
already iterates the entire keyspace for you. You don't need to loop inside
an individual server - one `await foreach` per server is fine.
