### ISSUE TITLE
TwemProxy can not use Multi-key Operation

### ISSUE THREAD

**Issue by virtualcca** [StackExchange/StackExchange.Redis#2345]
in this code
https://github.com/StackExchange/StackExchange.Redis/blob/e74076de9333d462ba2c11d4fe323cd5574a956c/src/StackExchange.Redis/ServerSelectionStrategy.cs#L145

Why do you still need to determine that Multi-key operations cannot be used under TwemProxy 
when the servertype is TwemProxy

it will throw "Multi-key operations must involve a single slot" exception

I see there have been such problems before #296 but I still get errors

stackexchange.redis version is 2.6.90

**Comment by mgravell** [comment]
because unless something has changed: those things aren't valid things to do under twemproxy, and as a general principle, we *try* to ensure that things are valid *before* issuing them to the server

has something changed? either in the general case, or in some specific case? happy to reconsider if there are reasons to, but ultimately we're just trying to reflect the server semantics

**Comment by virtualcca** [comment]
Although I don't know if it is a general situation, at least we confirm that this is supported in Tencent Cloud

That is, it can support Multi-key operations through the TwemProxy solution (no hashtag required)


Recently, we encountered redis performance problems, which were confirmed to be caused by hashtags. We also confirmed that the cloud provider (Tencent Cloud) we use supports Multi-key operations without hashtags (their redis is processed at the proxy layer)
Then we canceled the hashtag designation and found that the test was always unsuccessful, throw "Multi-key operations must involve a single slot" exception
Finally, we confirmed that it was due to the interception of SE.Redis itself (that is, when the case is TwemProxy in the code, MultipleSlots was also executed. Finally, it was confirmed that it was not the same Slots and then an exception was thrown.


Our current temporary solution is to remove the case TwemProxy in the code I posted above and package a version of SE.Redis of our own. It is currently working normally.

**Comment by mgravell** [comment]
Presumably (please say otherwise) you're currently telling it to use
proxy=twemproxy in the configuration string (or similar via the
configuration options API). Have you tried just not including that?
Meaning: if this proxy doesn't have the classic twemproxy limits: let's not
use twemproxy mode?

That might be a very quick/easy workaround. I will try to find out whether
this is a general change in twemproxy over time, i.e. whether our code is
still applying to correct limits. I will also try to find out about this
hosted solution to see whether they have any unique rules that we should
care about.

**Comment by virtualcca** [comment]
If I don't set proxy=twemproxy, the obtained SE.Redis will initialize the ServerType to cluster, and there will still be the same restrictions

**Comment by mgravell** [comment]
So that suggests that we're detecting an underlying cluster topology. Which
normally *does* imply certain slot semantics. For us to route correctly for
an environment, we need to understand the layout; do you have a link to
whatever product/service is offering this setup?

**Comment by virtualcca** [comment]
We use is Tencent Cloud Redis, and here is a list of its related command compatibility (not all supported) 
https://www.tencentcloud.com/document/product/239/48367
Common commands like mget, mset, etc. support multikey commands

**Comment by mgravell** [comment]
Right; so it sounds like this is a candidate for a separate proxy entry, that isn't twemproxy but is something similar; in particular, it looks like we need:

- command map eyeball (I do *not* propose to handle every variant of server; things with a tick at all)
- SupportsDatabases -> true (with default 256?)
- SupportsPubSub -> true
- SupportsServerApi -> true (ish)
- SupportsAutoConfigure -> maybe, but needs validation in case it flips to cluster mode?
- tweak to ServerSelectionStrategy.Select to allow `MGET`, `MSET` and `DEL` (only) as cross-slot
- validation

It is that last step that gets tricky without an endpoint to test against, and I'm not volunteering to setup an account with yet another redis provider.

I wonder; as a temporary workaround, could you try using a configuration string that *does not* specify a proxy, and add `,$CONFIG=,$INFO=,version=6.0` onto your configuration string? the `$CONFIG=` and `$INFO=` just disable the `CONFIG` and `INFO` commands to try to *prevent* auto-configuration and thus prevent it trying to be "clever"; the `version=6.0` just specifies an assumed server API version (feel free to use a different version here if you know the actual server API level of your system). With this setup if you try to do a cross-slot operation that isn't allowed (i.e. not `MGET` etc) the library won't stop you, but the proxy presumably still will - either way, it was doomed so... meh.

let me know how that works!

**Comment by mgravell** [comment]
well that's very odd; the detection of cluster mode comes from the `INFO` auto-configuration, which should be disabled here; you could *try* adding `$CLUSTER=`, but that shouldn't even be used if we haven't detected a cluster-mode node, which we can't if we've disabled auto-config

Things that might help:

- passing a `StringWriter` or similar to the optional `log` parameter in `Connect[Async]`, so we can see how it has made this determination, or
- using the `ExportConfiguration` API on the multiplexer and giving it a `FileStream` - this writes a zip archive with a per-server breakdown of the info/config/etc setup

examples:

```
var sw = new StringWriter();
var muxer = ConnectionMultiplexer.Connect(config, log: sw);
Console.WriteLine(sw); // this is what is interesting
```

or

```
using (var output = File.Create("somepath\config.zip"))
{
    muxer.ExportConfiguration(output);
}
```

Note that both of these contain quite a lot of info - probably more than you want to blindly dump onto github, so either approach probably needs some level of redaction (it does not include passwords or similar); or if you are happy to share data but not on github, I'm available via marc.gravell (at) gmail.com

**Comment by virtualcca** [comment]
I found that after adding $CLUSTER=, ServerType became Standalone, and now works (no MultiSlot exception will be thrown)

At the same time, I also tried to only add $CLUSTER without adding $CONFIG=, $INFO=, version=6.0, and found that it was not possible, and it was possible to add it at the same time

I got log added $CLUSTER and not,the log is attached

[Add $CLUSTER=.txt](https://github.com/StackExchange/StackExchange.Redis/files/10441054/Add.CLUSTER.txt)
[no $CLUSTER.txt](https://github.com/StackExchange/StackExchange.Redis/files/10441055/no.CLUSTER.txt)

**Comment by NickCraver** [comment]
Ah okay, this makes sense. @mgravell we issue INFO and the CLUSTER NODES conditional on the map but not on the server type from INFO (to pipeline the handshake faster), so in retrospect it makes sense both would need to be disable to feign detectability here. @virtualcca thanks for helping debug this!

**Comment by NickCraver** [comment]
Given we have a fix here, closing out to tidy up.
