### ISSUE TITLE
Timeout when using Clustering

### ISSUE THREAD

**Issue by scmsdev** [StackExchange/StackExchange.Redis#2348]
I am getting a timeout when using a cluster configuration on Redis (REL8). What is odd is that I have two test projects both .NET but one is a windows application and the other is a Web Application. In Windows I am setting up the server as follows

            private static ConnectionMultiplexer _cnn;
            private string _redisKey;
            public RedisDictionary(string redisKey)
            {
                _redisKey = redisKey;
                var options = ConfigurationOptions.Parse("Server IP:Port"); // host1:port1, host2:port2, ...
                options.DefaultDatabase = 1;
                //options.Ssl = false;
                options.Password = "My Password";
                
                options.SyncTimeout = 25000;
                _cnn = ConnectionMultiplexer.Connect(options);
            }

Looking at my Redis Monitor I see this connect but when I try to the the following and send it data it pulls an error.

            public void Add(TKey key, TValue value)
            {
                GetRedisDb().HashSet(_redisKey, Serialize(key), Serialize(value));
            }

I get the following timeout error

StackExchange.Redis.RedisTimeoutException: 'Timeout performing HSET (25000ms), inst: 0, qu: 0, qs: 0, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, last-in: 314, cur-in: 0, sync-ops: 1, async-ops: 1, serverEndpoint: My Server and Port, conn-sec: 35.72, mc: 1/1/0, mgr: 10 of 10 available, clientName: LAPTOP-I213598Q(SE.Redis-v2.6.90.64945), PerfCounterHelperkeyHashSlot: 915, IOCP: (Busy=0,Free=1000,Min=20,Max=1000), WORKER: (Busy=1,Free=2046,Min=20,Max=2047), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)'

Now, when I do the same thing in a Non Clustered Redis Server it works fine.

the Web App seems to work using this in the webconfig and sending Session Data to it.

        <add name="MySessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="My Host" port="My Port" password="My Password" accessKey="My Password" ssl="false" throwOnError="true" retryTimeoutInMilliseconds="2000" connectionTimeoutInMilliseconds="10000" operationTimeoutInMilliseconds="20000" />

Any Help would be great!!!

Thanks

**Comment by NickCraver** [comment]
The default database in Redis is 0, Cluster doesn't support databases at all, so setting it to 1 will...I guess do this, honestly never explicitly tried it. Try removing your `options.DefaultDatabase = 1;` and see if cluster behaves as you expect there :)

**Comment by NickCraver** [comment]
Closing out to tidy up.
