### ISSUE TITLE
Timeouts after upgrading to .NET 6

### ISSUE THREAD

**Issue by wz818wz** [StackExchange/StackExchange.Redis#2349]
My project has upgrade to .Net6, but it was not work well when using StackExchange.Redis.Timeouts often occur.Is there a plan to upgrade to 6.0? After all, it is a long-term supported version.
I saw a 3.x millstone,Does it stopped?

**Comment by mgravell** [comment]
Short answer: "yes it works on .net 6, no we haven't stopped anything"

It is hard to talk about timeouts without knowing an awful lot about your scenario; that could be any number of causes, including simply overloading the server or client node. Or using sync-over-async. It could also be that you're migrating from an old version of the library that failed to report timeouts, even though things were running over-long.

**Comment by wz818wz** [comment]
Here is a timeout message,It is difficult to find the reason.
Work normally in .NetCore3.1 and StackExchange.Redis 2.2.4,when I upgrade to .Net6 and StackExchange.Redis 2.6.91 the problem arises.
A request can read and write thousands of times at most, but not every request will appear.
StackExchange.Redis.RedisTimeoutException: Timeout performing GET 15-68-9c265aaf-78b8-4989-ba0c-dde40d3783c2 (5000ms), active: GET 15-68-9c265aaf-78b8-4989-ba0c-dde40d3783c2, inst: 0, qu: 0, qs: 0, aw: False, bw: Inactive, in: 0, in-pipe: 0, out-pipe: 0, last-in: 0, cur-in: 0, sync-ops: 10521, async-ops: 0, serverEndpoint: 10.147.163.54:6380, conn-sec: n/a, mc: 1/1/0, clientName: SERVER001(SE.Redis-v2.6), IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=7,Free=993,Min=200,Max=1000), POOL: (Threads=12,QueuedItems=0,CompletedItems=79010), v: 2.6 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)     at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T]...

**Comment by mgravell** [comment]
That client looks (at an initial glance) to be pretty unstressed - maybe
doing lots of individual sync things sequentially (not concurrently).
There's no backlog that I can see. On this occasion, I'm tempted to think
"server". Have you looked at the SLOWLOG on the server? Was there any
long-running operation happening around this time?

**Comment by wz818wz** [comment]
There is no log an monitor on server.I have two repos for .NetCore3.1 and .Net6. Exceptions only occur after I publish the. Net6 repository.So I don't think it is server problem.
I tried Thread theft, it works well, And looks like some performance loss.

**Comment by NickCraver** [comment]
@wz818wz Have you tried the 2.6.90 client on .NET Core 3.1 to sanity check that combination? That should be a drop-in replacement so you're testing the library change independently of the entire runtime being swapped out :)

**Comment by wz818wz** [comment]
Yes,I tried the 2.6.90 client on .Net Core 3.1, It's almost the same with 2.2.4 client.

**Comment by SH2015** [comment]
I am getting this error two , the server is not busy at all and it is fully in controlled environment, please fix it or suggest how to proceed, I also tried  with other clients and  CLI all working fine.

**Comment by NickCraver** [comment]
@wz818wz  I'm trying to follow your message - so the latest client works fine? It's the .NET 3.1 -> .NET 6 change that breaks you, all other things being equal?

**Comment by telb99** [comment]
Right now, a .NET 6 or 7 app gets the .NETStandard 2.0 version of StackExchange.Redis which brings in additional dependencies not needed in .NET 6 or 7?

From package lock file on an app targetting .NET 7

      "StackExchange.Redis": {
        "type": "Direct",
        "requested": "[2.6.90, )",
        "resolved": "2.6.90",
        "contentHash": "OVmlUSvuCI4rMcSU1dI1h+U/6t2k8AL7TVD1kIrZ0eSDDrgNlKcsTlQhZU8u9ViU6F8AVOvFZnxDP69NyU/oUQ==",
        "dependencies": {
          "Microsoft.Bcl.AsyncInterfaces": "5.0.0",
          "Pipelines.Sockets.Unofficial": "2.2.2",
          "System.Threading.Channels": "5.0.0"
        }
      },


Could this be contributing to timeout issues?

**Comment by NickCraver** [comment]
@telb99 You're seeing the netstandard2.0 version resolve? I would have thought it'd grab net5.0, need to double check my assumptions there if it's not doing that...

**Comment by telb99** [comment]
Wow Nick, that was quick! 
I was just coming back to delete my comment!

I realized that our app is multi targetting, and that section of the lock file is for NETStandard 2.0

The 7.0 section has this
      "StackExchange.Redis": {
        "type": "Direct",
        "requested": "[2.6.90, )",
        "resolved": "2.6.90",
        "contentHash": "OVmlUSvuCI4rMcSU1dI1h+U/6t2k8AL7TVD1kIrZ0eSDDrgNlKcsTlQhZU8u9ViU6F8AVOvFZnxDP69NyU/oUQ==",
        "dependencies": {
          "Pipelines.Sockets.Unofficial": "2.2.2"
        }
      },

Sorry for the confusion :(

**Comment by NickCraver** [comment]
All good! I'd much rather that than your first post be right and break a _lot_ of debugging assumptions I've had <3

**Comment by pedrohma** [comment]
I've been getting this error since we've upgraded to .net 6:

Timeout performing GET (5000ms), next: GET LOCAL-634232221 inst: 4, qu: 0, qs: 0, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: rc-sharedservices-dev01.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: SRM-LT-X2307(SE.Redis-v2.6.48.48654), IOCP: (Busy=2,Free=998,Min=16,Max=1000), WORKER: (Busy=9,Free=32758,Min=16,Max=32767), POOL: (Threads=46,QueuedItems=3,CompletedItems=31673), v: 2.6.48.48654 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

Any ideas?

**Comment by NickCraver** [comment]
@pedrohma It looks like you have a decent amount of thread usage going on, maybe a lot of sync (rather than async) calls eating threads? A newer versions of the client would show this in exception messages as a counter but I can't see here. Going by `POOL: (Threads=46,QueuedItems=3,CompletedItems=31673)` - I'd try and get a memory dump to see what's happening.

Note: most people tend to think "it's hard to get a dump when it happens" but this is likely very often happening under load, just not hitting the redline of a 5 second timeout...if you capture under load, hopefully you can see what those threads are doing.

**Comment by NickCraver** [comment]
Closing this out to cleanup, handling #2373 separately :)

**Comment by smalgin-esri** [comment]
Noted, thanks.
