### ISSUE TITLE
ParameterExtractor of cultureInfo issue

### ISSUE THREAD

**Issue by samiozer** [StackExchange/StackExchange.Redis#2350]
There is a CultureInfo problem in the process of finding the "@blabla" parameters defined in the script text with regex. 
For example
A parameter named "@testIId" cannot be found in script text when CulturerInfo is "tr-TR". The character "I" has always been a problem for this Culture :)  RegexOptions.CultureInvariant can be added as a solution.

Old

```csharp 
private static readonly Regex ParameterExtractor = new Regex(@"@(?<paramName> ([a-z]|_) ([a-z]|_|\d)*)", RegexOptions.Compiled | RegexOptions.IgnoreCase | RegexOptions.IgnorePatternWhitespace);
```

New 

```csharp 
private static readonly Regex ParameterExtractor = new Regex(@"@(?<paramName> ([a-z]|_) ([a-z]|_|\d)*)", RegexOptions.Compiled | RegexOptions.IgnoreCase | RegexOptions.IgnorePatternWhitespace | RegexOptions.CultureInvariant);
```

**Comment by mgravell** [comment]
Yep, totally understood, and you're absolutely right - this should be invariant. Thanks for reporting. Will happily take a PR, or I will commit to taking this at the start of the week.

**Comment by NickCraver** [comment]
This gave me an idea on testing I wanted to poke on (culture via attribute for test-scoping), turns out there is some prior art and it works pretty well I think, made a PR here: #2351

**Comment by samiozer** [comment]
I couldn't create PR because I had urgent work at the weekend. thanks, @NickCraver.
