### ISSUE TITLE
Exception during ConnectionMultiplexer Connect

### ISSUE THREAD

**Issue by james-vaughn** [StackExchange/StackExchange.Redis#2352]
This is happening on 
* .NET Framework 4.8.4515.0
* StackExchange.Redis version 2.6.90.64845
* Windows 11 version 10.0.22000 Build 22000. 

The issue comes up intermittently. It seems to occur and go away randomly. We are also not experiencing this issue running in docker on Linux, only on Windows.

We are getting the follow exception when using ConnectionMultiplexer to connect to our redis server.

```        
        private static IConnectionMultiplexer getRedisConnection()
        {
            var sessionStateSettings = ConfigurationSettings.SessionState;
            var provider = sessionStateSettings.Providers[Constants.Constants.SessionProviders.MySessionStateStore];

            //throws exception
            return ConnectionMultiplexer.Connect(provider.Parameters["connectionString"]);
        }
```

```
System.ArgumentException: Cannot use type 'StackExchange.Redis.RawResult'. Only value types without pointers or references are supported.
   at System.ThrowHelper.ThrowArgumentException_InvalidTypeWithPointersNotSupported(Type type)
   at System.Span`1..ctor(Void* pointer, Int32 length)
   at Pipelines.Sockets.Unofficial.Arenas.PerTypeHelpers`1.IsReferenceOrContainsReferences()
```

**Comment by james-vaughn** [comment]
@NickCraver We have Pipelines.Sockets.Unofficial version 2.2.2 installed via NuGet, which seems like the right version, if Im understanding you right.

**Comment by NickCraver** [comment]
@james-vaughn That's the package version. Inside there are builds for multiple platforms, you're somehow using a .NET Core or .NET Standard 2.1 build rather than the proper `net472` build, which is what's causing your runtime explosion...none of that path is supported on older .NET Framework.

You can see what I mean here: https://nuget.info/packages/Pipelines.Sockets.Unofficial/2.2.2
<img width="822" alt="image" src="https://user-images.githubusercontent.com/454813/214895868-a7613606-f038-455c-9416-02439033e021.png">

**Comment by james-vaughn** [comment]
Looking at the built assemblies, I'm seeing Pipelines.Sockets.Unofficial version 1.0.0.0 MSIL, file version 2.2.2.34088, target framework .NETFramework,Version=v4.7.2

**Comment by NickCraver** [comment]
@mgravell have you seen any other permutations of this?

**Comment by NickCraver** [comment]
@james-vaughn Did you ever figure this out? We couldn't reason about what the heck you were hitting here, some combination that shouldn't happen if package manager and runtime is behaving as expected :-/

**Comment by alexeyzimarev** [comment]
I have the same issue running on .NET Framework 4.8. The caching library targets both .NET 7 and .NET Framework 4.8. The application targets .NET Framework 4.8. Aforementioned assembly is .NET Framework 4.7.2:

![image](https://github.com/StackExchange/StackExchange.Redis/assets/2821205/94b96238-6e59-4b4d-bee3-69b9c15f2f2c)

Exception:
> System.ArgumentException: Cannot use type 'StackExchange.Redis.RawResult'. Only value types without pointers or references are supported.
   at System.ThrowHelper.ThrowArgumentException_InvalidTypeWithPointersNotSupported(Type type)
   at System.Span`1..ctor(Void* pointer, Int32 length)
   at Pipelines.Sockets.Unofficial.Arenas.PerTypeHelpers`1.IsReferenceOrContainsReferences() in /_/src/Pipelines.Sockets.Unofficial/Arenas/PerTypeHelpers.cs:line 153

**Comment by NickCraver** [comment]
@alexeyzimarev We pin the assembly versions at x.0.0.0 to minimize binding redirect pain for users, so I can't tell the difference there - can you please show the file versions? There is something very telling there though: how in the world do you have Debug DLLs? We never ship debug in the packages. Is there some build process replacing your libraries?

**Comment by alexeyzimarev** [comment]
Sorry my bad. The exception is, I believe, intentional as it's wrapped in try-catch upstream in `Area<RawResult>`.

**Comment by NickCraver** [comment]
I think there's nothing to do here, just a chance of first chance exceptions behavior and confusion there, but happy to reopen if that's not the case.
