### ISSUE TITLE
Pass null expiry to LockTakeAsync

### ISSUE THREAD

**Issue by ArminShoeibi** [StackExchange/StackExchange.Redis#2355]
Hello there folks,

As you know StringSetAsync
https://github.com/StackExchange/StackExchange.Redis/blob/b1fddf3d1e449326e044e2ae91d934af33cad8a3/src/StackExchange.Redis/RedisDatabase.cs#L3174
accepts `Nullable<TimeSpan>`, I want to create a lock without TTL and after that I want to release it manually.

https://github.com/StackExchange/StackExchange.Redis/blob/b1fddf3d1e449326e044e2ae91d934af33cad8a3/src/StackExchange.Redis/RedisDatabase.cs#L1440

for example with this code I want to release the lock manually.
```csharp
   [HttpPut]
    public async Task<IActionResult> WithdrawMoney()
    {
        IDatabase database = _connectionMultiplexer.GetDatabase();
        bool isAcquired = await database.LockTakeAsync("USERNAME-WithdrawMoney", 1, expiry: null);
        if (isAcquired)
        {
            // some code
           await database.LockReleaseAsync("USERNAME-WithdrawMoney", 1);
           return Ok();
        }
        else
        {
            return BadRequest();
        }
    }
```

Can we have a new overload of _LockTakeAsync_ with `Nullable<Timespan>` expiry in upcoming versions?

Right now I have added it as an extra method.

**Comment by ArminShoeibi** [comment]
> In a locking mechanism, I would consider that actively harmful. Locks _at least in the typical sense_ need to expire at some point to avoid leaving the system in a state where it needs manual intervention to recover from a stall (any exception in the "some code", or a hard process exit, server reboot, network disconnect, etc). Also, without the time component a lock is mostly just a "stringset with when notexists", and maybe a one-liner of Lua to release after validating the current value. I'm very reluctant to add this, to be honest. Maybe just use a suitably large timeout instead?

Thanks for your quick response.

Yeah, I agree with a large timeout, I should go with this approach.

In fact, If we want to go by _standards_ It's good to use a short timeout and Extend it via `LockExtend/LockExtendAsync` but I think it is really hard 😄 

I have also read the [RedLock.NET](https://github.com/samcook/RedLock.net) It starts a timer https://github.com/samcook/RedLock.net/blob/dcfe373b3e288caac4f45b78c88b5943f8b47e42/RedLockNet.SERedis/RedLock.cs#L301
for  all locks with acquired status 
https://github.com/samcook/RedLock.net/blob/dcfe373b3e288caac4f45b78c88b5943f8b47e42/RedLockNet.SERedis/RedLock.cs#L403

If you have time can you explain a good way to use `LockExtend/LockExtendAsync` ?

**Comment by mgravell** [comment]
"call them every so often" - so if you're processing a large volume of data while you hold the lock, perhaps every (some number, not usually 1) cycles:

```
if ((++i % EXTEND_EVERY) == 0) /* extend here */
