### ISSUE TITLE
Redis Server Supported Versions

### ISSUE THREAD

**Issue by ghost1face** [StackExchange/StackExchange.Redis#2356]
Hey all,

Quick question for you all, are there any specific minimum or maximum supported versions of Redis Server with this client?

I read through the docs but couldn't find anything specific.

**Comment by NickCraver** [comment]
We don't really test < v2 in years, but it should work with all versions out there. Commands are only available if the server supports them of course.

**Comment by ghost1face** [comment]
Thanks @NickCraver , I appreciate the fast response!
