### ISSUE TITLE
Get available ACL from server?

### ISSUE THREAD

**Issue by dominikjeske** [StackExchange/StackExchange.Redis#2360]
Our instance of Redis has custom ACL's with some commands blocked. Currently we are using CommandMap to exclude commands but I wonder is it possible to use StackExchange.Redis to get available ACL's for user and configure CommandMap having server configuration? If I get it right ACL commands are missing for now https://github.com/StackExchange/StackExchange.Redis/issues/2055 but I wonder if scenario described above will be available in the future?

**Comment by mgravell** [comment]
I haven't checked, but does redis even offer the ability to query this? does it filter `COMMAND LIST`, for example? there's `ACL DRYRUN`, but that needs a full set of args, and needs to be per-command; there's also the issue of the key pattern (`~`, `%R` and `%W`) which we'd need to run.

UItimately, though: what would the benefit here be? we'll get a suitable error either way; this would just get the error without bothering the server. That's useful if we can do it for free, but given the amount of complexity that we'd need to duplicate at the client, I'm not sure it warrants it.

**Comment by dominikjeske** [comment]
thanks for info.
