### ISSUE TITLE
Getting time out error even though neither client or servers are busy. 

### ISSUE THREAD

**Issue by SH2015** [StackExchange/StackExchange.Redis#2361]
`database.HashGet(new RedisKey("sin"), RedisValue.EmptyString)`
I get : 

'database.HashGet(new RedisKey("sin"), RedisValue.EmptyString)' threw an exception of type 'StackExchange.Redis.RedisTimeoutException'
    Commandstatus: WaitingToBeSent
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233083
    HelpLink: "https://stackexchange.github.io/StackExchange.Redis/Timeouts"
    InnerException: null
    Message: "Timeout performing HGET (5000ms), inst: 0, qu: 1, qs: 0, aw: False, bw: Inactive, rs: NotStarted, ws: Initializing, last-in: 0, cur-in: 0, sync-ops: 1, async-ops: 0, serverEndpoint: redis://127.0.0.1:6379:6379, conn-sec: n/a, mc: 1/1/0, mgr: 10 of 10 available, clientName: DESKTOP-7V6BSTG(SE.Redis-v2.6.90.64945), IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=32766,Min=80,Max=32767), POOL: (Threads=10,QueuedItems=0,CompletedItems=34), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)"
    Source: "StackExchange.Redis"
    StackTrace: "   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue)\r\n   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue)\r\n   at StackExchange.Redis.RedisDatabase.HashGet(RedisKey key, RedisValue hashField, CommandFlags flags)"
    TargetSite: {T ExecuteSyncImpl[T](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor`1[T], StackExchange.Redis.ServerEndPoint, T)}

**Comment by mgravell** [comment]
That looks like it hasn't connected, perhaps due to connecting with the "abort on connect fail" flag disabled. If you pass a log (typically a StringWriter or Console.Out) to the "log" parameter of connect, does it say it has connected? It not, does it say why not?

**Comment by SH2015** [comment]
@mgravell  , it is unable to connect but same connection string is able to connect using other clients , what I noticed is the port is internally duplicated, check this log stream , is that normal ? although this is my connection string : 
`    "connectionstring": "redis://localhost:6379,abortConnect=false,syncTimeout=10000"`
Log Stream : 
02:23:16.9060: Connecting (sync) on .NET 6.0.11 (StackExchange.Redis: v2.6.90.64945)
02:23:17.0123: redis://localhost:6379,syncTimeout=10000,connectTimeout=10000,abortConnect=False,connectRetry=5

02:23:17.0331: redis://localhost:6379:6379/Interactive: Connecting...
02:23:17.1339: redis://localhost:6379:6379: BeginConnectAsync
02:23:17.2112: 1 unique nodes specified (with tiebreaker)
02:23:17.2269: redis://localhost:6379:6379: OnConnectedAsync init (State=Connecting)
02:23:17.2285: Allowing 1 endpoint(s) 00:00:10 to respond...
02:23:17.2643: Awaiting 1 available task completion(s) for 10000ms, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=0,Free=32767,Min=80,Max=32767), POOL: (Threads=6,QueuedItems=0,CompletedItems=9)
02:23:17.3328: redis://localhost:6379:6379: OnConnectedAsync completed (Disconnected)
02:23:17.3617: All 1 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=5,Free=32762,Min=80,Max=32767), POOL: (Threads=12,QueuedItems=0,CompletedItems=10)
02:23:17.3852: Endpoint summary:
02:23:17.3855:   redis://localhost:6379:6379: Endpoint is (Interactive: Disconnected, Subscription: Disconnected)
02:23:17.3858: Task summary:
02:23:17.3861:   redis://localhost:6379:6379: Returned, but incorrectly
02:23:17.3960: Election summary:
02:23:17.3963:   Election: redis://localhost:6379:6379 had no tiebreaker set
02:23:17.3965:   Election: No primaries detected
02:23:17.3979: Connection failed: redis://localhost:6379:6379 (Subscription, UnableToConnect): UnableToConnect on redis://localhost:6379:6379/Subscription, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.90.64945
02:23:17.3993: Connection failed: redis://localhost:6379:6379 (Interactive, UnableToConnect): UnableToConnect on redis://localhost:6379:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.90.64945
02:23:17.3999: Endpoint Summary:
02:23:17.4049:   redis://localhost:6379:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
02:23:17.4289:   redis://localhost:6379:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=2
02:23:17.4448:   redis://localhost:6379:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
02:23:17.4455: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
02:23:17.4470: Resetting failing connections to retry...
02:23:17.4521:   Retrying - attempts left: 4...
02:23:17.4528: 1 unique nodes specified (with tiebreaker)
02:23:17.4545: redis://localhost:6379:6379: OnConnectedAsync init (State=Connecting)
02:23:17.4590: Allowing 1 endpoint(s) 00:00:10 to respond...
02:23:17.4595: All tasks are already complete
02:23:17.4605: redis://localhost:6379:6379: OnConnectedAsync completed (Disconnected)
02:23:17.4613: Endpoint summary:
02:23:17.4627:   redis://localhost:6379:6379: Endpoint is (Interactive: Disconnected, Subscription: Disconnected)
02:23:17.4656: Task summary:
02:23:17.4675:   redis://localhost:6379:6379: Returned, but incorrectly
02:23:17.4684: Election summary:
02:23:17.4692:   Election: redis://localhost:6379:6379 had no tiebreaker set
02:23:17.4700:   Election: No primaries detected
02:23:17.4728: Endpoint Summary:
02:23:17.4742:   redis://localhost:6379:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
02:23:17.4751:   redis://localhost:6379:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=3; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=3
02:23:17.4760:   redis://localhost:6379:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
02:23:17.4783: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
02:23:17.4792: Resetting failing connections to retry...
02:23:17.4812:   Retrying - attempts left: 3...
02:23:17.4852: 1 unique nodes specified (with tiebreaker)
02:23:17.4871: redis://localhost:6379:6379: OnConnectedAsync init (State=Disconnected)
02:23:17.4881: Allowing 1 endpoint(s) 00:00:10 to respond...
02:23:17.4888: Awaiting 1 available task completion(s) for 10000ms, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=32766,Min=80,Max=32767), POOL: (Threads=12,QueuedItems=0,CompletedItems=21)
02:23:27.4938: Not all available tasks completed cleanly (from ReconfigureAsync#1386, timeout 10000ms), IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=32766,Min=80,Max=32767), POOL: (Threads=11,QueuedItems=0,CompletedItems=40)
02:23:27.4965:   Server[0] (redis://localhost:6379:6379) Status: WaitingForActivation (inst: 0, qs: 0, in: -1, qu: 0, aw: False, in-pipe: -1, out-pipe: -1, bw: Inactive, rs: NA. ws: NA)
02:23:27.4968: Endpoint summary:
02:23:27.4970:   redis://localhost:6379:6379: Endpoint is (Interactive: Disconnected, Subscription: Disconnected)
02:23:27.4973: Task summary:
02:23:27.4974:   redis://localhost:6379:6379: Did not respond (Task.Status: WaitingForActivation)
02:23:27.4976: Election summary:
02:23:27.4979:   Election: redis://localhost:6379:6379 had no tiebreaker set
02:23:27.4989:   Election: No primaries detected
02:23:27.4996: Endpoint Summary:
02:23:27.5005:   redis://localhost:6379:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
02:23:27.5016:   redis://localhost:6379:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=4; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=4
02:23:27.5026:   redis://localhost:6379:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
02:23:27.5037: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
02:23:27.5044: Resetting failing connections to retry...
02:23:27.5065:   Retrying - attempts left: 2...
02:23:27.5069: 1 unique nodes specified (with tiebreaker)
02:23:27.5077: redis://localhost:6379:6379: OnConnectedAsync completed (Disconnected)
02:23:27.5085: redis://localhost:6379:6379: OnConnectedAsync init (State=Disconnected)
02:23:27.5093: Allowing 1 endpoint(s) 00:00:10 to respond...
02:23:27.5161: Awaiting 1 available task completion(s) for 10000ms, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=32766,Min=80,Max=32767), POOL: (Threads=11,QueuedItems=0,CompletedItems=44)
02:23:37.5163: Not all available tasks completed cleanly (from ReconfigureAsync#1386, timeout 10000ms), IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=4,Free=32763,Min=80,Max=32767), POOL: (Threads=11,QueuedItems=0,CompletedItems=45)
02:23:37.5181:   Server[0] (redis://localhost:6379:6379) Status: WaitingForActivation (inst: 0, qs: 0, in: -1, qu: 0, aw: False, in-pipe: -1, out-pipe: -1, bw: Inactive, rs: NA. ws: NA)
02:23:37.5194: Endpoint summary:
02:23:37.5196:   redis://localhost:6379:6379: Endpoint is (Interactive: Disconnected, Subscription: Disconnected)
02:23:37.5200: Task summary:
02:23:37.5202:   redis://localhost:6379:6379: Did not respond (Task.Status: WaitingForActivation)
02:23:37.5205: Election summary:
02:23:37.5213:   Election: redis://localhost:6379:6379 had no tiebreaker set
02:23:37.5219:   Election: No primaries detected
02:23:37.5242: Endpoint Summary:
02:23:37.5252:   redis://localhost:6379:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
02:23:37.5267:   redis://localhost:6379:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=5; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=5
02:23:37.5286:   redis://localhost:6379:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
02:23:37.5303: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
02:23:37.5317: Resetting failing connections to retry...
02:23:37.5372:   Retrying - attempts left: 1...
02:23:37.5380: 1 unique nodes specified (with tiebreaker)
02:23:37.5425: redis://localhost:6379:6379: OnConnectedAsync init (State=Connecting)
02:23:37.5431: Allowing 1 endpoint(s) 00:00:10 to respond...
02:23:37.5447: All tasks are already complete
02:23:37.5458: Endpoint summary:
02:23:37.5473: redis://localhost:6379:6379: OnConnectedAsync completed (Disconnected)
02:23:37.5559: redis://localhost:6379:6379: OnConnectedAsync completed (Disconnected)
02:23:37.5593:   redis://localhost:6379:6379: Endpoint is (Interactive: Disconnected, Subscription: Disconnected)
02:23:37.5621: Task summary:
02:23:37.5636:   redis://localhost:6379:6379: Returned, but incorrectly
02:23:37.5652: Election summary:
02:23:37.5660:   Election: redis://localhost:6379:6379 had no tiebreaker set
02:23:37.5668:   Election: No primaries detected
02:23:37.5676: Endpoint Summary:
02:23:37.5683:   redis://localhost:6379:6379: Standalone v3.0.0, primary; keep-alive: 00:01:00; int: Disconnected; sub: Disconnected; not in use: DidNotRespond
02:23:37.5693:   redis://localhost:6379:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=6; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=6
02:23:37.5702:   redis://localhost:6379:6379: Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
02:23:37.5711: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
02:23:37.5723: Starting heartbeat...
02:23:37.5747: Total connect time: 20,672 ms

**Comment by NickCraver** [comment]
I can write more in the morning, but short version is: remove the `redis://` prefix, that isn't a supported endpoint/connection string format, so it won't be parsed correctly.

**Comment by SH2015** [comment]
> I can write more in the morning, but short version is: remove the `redis://` prefix, that isn't a supported endpoint/connection string format, so it won't be parsed correctly.

Worked, thank you , I was almost going to abandon REDIS server because of this error
