### ISSUE TITLE
Seems like FailureType is not correctly indicating authentication error

### ISSUE THREAD

**Issue by tavisca-manpreet** [StackExchange/StackExchange.Redis#2362]

**Comment by tavisca-manpreet** [comment]
In case of incorrect credentials, I am getting StackExchange.Redis.RedisConnectionException exception. To differentiate Authentication errors, the code seems to have an enum of failure type. But in case of authentication error also, I am getting FailureType as "UnableToConnect". 

![image](https://user-images.githubusercontent.com/82931644/216973377-cf1c2548-284b-4fc0-bd1b-2145c343a3c2.png)

**Comment by NickCraver** [comment]
Which version of the library are you using?

**Comment by tavisca-manpreet** [comment]
I am using 2.6.90 version and the the screenshot is of the same code. ExceptionFactory seems to be setting same failure type in case of all UnableToConnect errors.

**Comment by NickCraver** [comment]
Can you post the actual error message and type you're seeing? Look at this from my view: all I have is a screenshot of code, I'm not sure what error you're seeing and what you're expecting to see. e.g. "is it including the test about it being an authentication failure?" - give us something to go on here...

**Comment by tavisca-manpreet** [comment]
Exception message: **It was not possible to connect to the redis server(s). There was an authentication failure; check that passwords (or client certificates) are configured correctly: (RedisServerException) Error: WRONGPASS invalid username-password pair or user is disabled.**
Type: StackExchange.Redis.RedisConnectionException
![image](https://user-images.githubusercontent.com/82931644/216994491-744566c5-b6c3-4370-b78b-4dc9f442f7b4.png)

**Comment by tavisca-manpreet** [comment]
I am trying to handle authentication failures in my code. To test this scenario, when I pass incorrect credentials , I am getting exception with the correct message but the "FailureType" in the exception seems to be not correct as the enum has a better alternative to represent authentication failure. I need a differentiator in case of authentication errors apart from the exception message. FailureType seems to be the correct field for it. But the value getting returned in this case in FailureType is "UnableToConnect" I felt was incorrect.

**Comment by tavisca-vshah** [comment]
I agree with the @tavisca-manpreet point, enum StackExchange.Redis.ConnectionFailureType already have `AuthenticationFailure` Field. Expected behaviour should be to set FailureType to ConnectionFailureType.AuthenticationFailure when there is authetication failure.
![image](https://user-images.githubusercontent.com/51902571/217482459-3f15d39e-1ac0-415e-a8b1-743f26759359.png)

**Comment by NickCraver** [comment]
Hey y'all - I'm just slammed with actual work stuff this week (this isn't the thing we're paid for :)) but wanted to say yes: completely agree. I haven't gotten a chance to look at this (hopefully later this week but we'll see how it goes), but I appreciate the clarification and additional detail. The request absolutely seems reasonable. Adding to the message it was because of auth and not a generic connection failure was something I only recently did a few months ago, and likely missed this aspect - will take a peek and report back.

**Comment by NickCraver** [comment]
Had to wait on some builds this morning so poked at how big this is - super minor to adjust/test, fix is up here: #2367

**Comment by tavisca-manpreet** [comment]
Thanks @NickCraver for the quick fix.

**Comment by NickCraver** [comment]
@tavisca-manpreet one note here: you could check the type on InnerException if you wanted until this is available on NuGet, in case that unblocks :)

**Comment by deychandan** [comment]
Hi @NickCraver,
I'm getting following error while try to run my .Net Core WebAPI. But with the same configuration it's working in another project.
![image](https://user-images.githubusercontent.com/6151558/232852463-0112f8eb-89d6-4017-b5b3-94db40683a85.png)
Redis version: StackExchange.Redis v2.0.601(tried with latest version but no luck)
Redis Config:
"RedisSettings": {
    "Endpoint": "xxxxxxxxx:6379",
    "Password": "xxxxxxxxxx",
    "Ssl": false,
    "AbortOnConnectFail": true,
    "KeepAlive": 30,
    "SyncTimeout": 3000,
    "ConnectTimeout": 4000,
    "ConnectRetry": 3,
    "sslprotocols": "tls12"
  }

Thanks
Chandan

**Comment by NickCraver** [comment]
I'm not sure how your connection is being created, but sslprotocols being specified while also turning SSL off is curious - any idea what's going on there?

**Comment by deychandan** [comment]
Hi @NickCraver
Sorry my bad wrongly added "sslprotocols". Following the config which is working in one project but not working in other project
"RedisSettings": {
    "Endpoint": "sis-redis.development.us.markerspro.net:6379",
    "Password": "bHoK4c2kHUuNj0WfnxmkWeVVo3DMVbnJ",
    "Ssl": false,
    "AbortOnConnectFail": true,
    "KeepAlive": 30,
    "SyncTimeout": 3000,
    "ConnectTimeout": 4000,
    "ConnectRetry": 3
  }
