### ISSUE TITLE
How can the cluster slots update be triggered?

### ISSUE THREAD

**Issue by stulzq** [StackExchange/StackExchange.Redis#2363]
when exception or timed refresh?

**Comment by mgravell** [comment]
Any time you fetch `ClusterNodes[Async]` via `IServer` (for any chosen endpoint), it will update the multiplexer's understanding of the shard topology. More generally, if you call `Reconfigure[Async]` on the multiplexer, it will refresh a lot more *including* the shard topology. The library will also try to respond to a few scenarios (such as `MOVED`) by updating the shard topology.

**Comment by stulzq** [comment]
Thanks
