### ISSUE TITLE
High timeout when redis connection fails on new redis library compared to stackechange.redis.strongname

### ISSUE THREAD

**Issue by goyalpallavi11** [StackExchange/StackExchange.Redis#2364]
We are upgrading the redis library of "Stackexchange.Redis.Strongname(1.2.6)" to "Stackexchange.Redis" (2.6.86) since the former version has been deprecated.
A latency of 15ms is observed when new library is used in the case where redis connection fails due to any reason (eg. incorrect connection string) whereas with older library it comes out to be 0ms. Not sure why the new library is not failing fast and is taking 15ms to throw exception
The exception is 
_`StackExchange.Redis.RedisTimeoutException: Timeout performing GET (1ms), inst: 0, qu: 6, qs: 0, aw: False, bw: SpinningDown, last-in: 0, cur-in: 0, sync-ops: 625, async-ops: 1, serverEndpoint: sfd-staging1.redis.cache.windows.net:6380, conn-sec: n/a, mc: 1/1/0, mgr: 10 of 10 available, clientName: Legacy000001(SE.Redis-v2.6.86.49666), IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=4,Free=32763,Min=200,Max=32767), v: 2.6.86.49666 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)..   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue)..   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue)..   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)..   at ......`_

Please provide guidance on how to reduce this timeout.
I tried setting the `synctimeout` and `connecttimeout` as 1ms in the redis connection string but no change in latency.

**Comment by NickCraver** [comment]
How are you measuring this? The default timer resolution in .NET is 16ms, for example. I'm also not sure what your expectations are - you want to evaluate timeouts every 1ms? Timers don't fire that often in .NET so we don't support anything that low as a baseline. Consider that 1.2.6 _wasn't accurately reporting timeouts_ and that's one of the major refactors to the entire pipe.

If this is specific to the connection, and you want to fail fast, then I'd advise not setting abortConnect=false so it doesn't retry. If you're getting all the way to a GET timeout, then I'm guessing that's set, which is explicitly "don't abort, try some more and in the background too" - then we evaluate command timeouts on the heartbeat after that.

Happy to help with suggestions, but I don't yet understand your expectations, hoping the abortConnect info helps.

**Comment by goyalpallavi11** [comment]
The timeout is measured by adding a stopwatch around `StringGet` method of the redis library.
When the connection fails the new library takes 15ms to fail and throw an exception and the old one takes 0ms.
I want to understand the reason of this difference.

**Comment by NickCraver** [comment]
Can you provide more information? You're seeing a timeout, rather than a connection failure overall. "When the connection fails" - what does this mean? You have an exception? The socket failed? You yanked the network cable? This can mean a ton of different things and all have different response times.

If you're talking about a broken _outbound_ socket, the new library will by queue and retry for when the connection is up, rather than instantly failing. This is called the BacklogPolicy and you can change it in configuration: https://stackexchange.github.io/StackExchange.Redis/Configuration

**Comment by NickCraver** [comment]
@goyalpallavi11 ^ Any chance you have that info? Happy to help further, but lacking enough detail atm.

**Comment by NickCraver** [comment]
Closing out, not enough info to advise further.
