### ISSUE TITLE
High latency ( 1 second) while calling sync methods with 1 vCPU 

### ISSUE THREAD

**Issue by chapinmark** [StackExchange/StackExchange.Redis#2365]
I've been investigating 1 second stalls in my docker app running in AWS ECS.  I will see delays from 500 ms to 1000 ms when using sync StringSet with no CommandFlags set.  I first noticed this when running on a t3a.small instance (2 vCPUs, 2 GB memory).  I run a few different services on the instance.  This instance sees extremely light traffic. After a few tests, I narrowed it down to the number of vCPUs.  As I reduce the number of vCPUs to 1, it rears its head.  If I'm running on 2 vCPUs and running some other service like MassTransit (rabbitmq), I will start to see the delays.  If I turn off MassTransit on 2 vCPUS, I don't see it.

Below is an example of the simplest version possible, just a console app that keeps calling StringSet every second and measures the latency/delay.  It is not necessary to run in Docker, I'm testing in an Amazon Linux 2 instance.  On a t2.small instance (1 vCPU), I see long running (>50ms) StringSet calls happening 1-2 per minute (1 out of every 30 calls to StringSet).  I should note that most (> 80%) of the measured long latency calls are just shy of 1 second (around 950 ms).

Simultaneously, I collected TCP traffic on the instance with tcpdump.  I can see that the set command goes out to the network immediately and is responded to by the server in around 1ms.  The test app just sits there for 500 to 1000 ms before coming back from StringSet.  The redis server is an AWS elsticache instance, 1 master and 1 backup I believe.

I also built StackExchange.Redis and Pipelines.Sockets.Unofficial and put logging in to figure out where the delay was happening.  All I could discern from those tests was that it lies within the SocketAwaitableEventArgs.  The OnCompleted method is not called immediately after I see the response come back from redis via tcpdump.  It seems that it is within SocketAsyncEventArgs (System.Net.Sockets) where this delay occurs.

I tried building System.Net.Sockets to debug further, but could not get it to build.

Although most of the time sitting around seems to be after the redis server returns a response, I have seen a delay in the command making it to the network.  However, I haven't come across this in the simple example below.  I have only noticed the delay before reaching the network in my productions app a few time.  The production app does have a few more things going on (like MassTransit).

I am forced to use the sync methods in one part of my app due to 3rd party api not being async.  

Any ideas why this delay occurs when I use one vCPU and only when sync methods (StringSet) are called?  

I have added vCPUs to production but at an expense.  Going from 2 vCPUs to 4 vCPUs is an 8x increase in price.

`
using StackExchange.Redis;
using System.Diagnostics;

namespace App5
{
    internal class Program
    {
        private static int _ii = 0;
        
	static async Task Main(string[] args)
	{

	    var redisConfiguration = ConfigurationOptions.Parse("redis.v9qasj.ng.0001.use1.cache.amazonaws.com:6379", true);
            redisConfiguration.ResolveDns = true;
            
	    var connection = ConnectionMultiplexer.Connect(redisConfiguration);
            var database = connection.GetDatabase();

	    while(true)
	    {
		await Task.Delay(1000);
	       _ii++;

               var sw = new Stopwatch();

               sw.Start();
               var dtStart = DateTime.Now;
               var dtoStart = DateTimeOffset.Now;
               database.StringSet("test",_ii);

               if (sw.ElapsedMilliseconds > 50)
               {
                   Console.WriteLine("Start: {0} {1}, End {2} {3} TestImplicitFlags took {4} {5}ms {6} {7} {8} {9}", dtStart.ToString("HH:mm:ss.FFF"), (double)dtoStart.ToUnixTimeMilliseconds()/1000, DateTime.Now.ToString("HH:mm:ss.FFF"), (double)DateTimeOffset.Now.ToUnixTimeMilliseconds()/1000, _ii, sw.ElapsedMilliseconds);
               }

               sw.Stop();
	    }
        }
    }
}
`

**Comment by chapinmark** [comment]
Finding inspiration from issues [2364](https://github.com/StackExchange/StackExchange.Redis/issues/2364) and [2366](https://github.com/StackExchange/StackExchange.Redis/issues/2366), I decided to increase the the worker minimum thread pool size from 1 to 2.  This resolved my issues.

`ThreadPool.SetMinThreads(2, 1);`

**Comment by chapinmark** [comment]
So far, the only way I can keep this delay from happening is to set ThreadPool.SetMinThreads(2,1) on a single vCPU machine.  The default is (1,1).  I'm happy to set a minimum but I think there is more going on here.

All output from tests below are run without setting minimum threads.  There are two set of results below, running Test App built with net5 and Test App built with net6.  Both are using nuget package SE.Redis 2.6.90.  SyncTimeout is set to 500ms so that exception data is captured.  Typically, the delay ranges from 500-1000ms without the low SyncTimeout set low.  Note the profiling shows that the delay occurs in the SendingToResponse stage.  This agrees with the tcpdump I mentioned in the original post.

Things to note:

net5 always show 1 thread in the pool when a Timeout exception occurs.  net6 shows many threads. I guess I can understand why net5 would have high latency with only one thread available and it being blocked by a sync call.  net6 shows around 4 threads but still delays.

Any suggestions on why setting the minimum to 2 on net6 fixes the delay?  The delay occurs even when the thread count is much greater than 2.

### **net5 build**
**NOTE: thread count is always 1 after delay**
Initial values: minWorker 1, minIOC 1

1 15:51:41.311 Total Time: 8, CreatToEnqueu: 6, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 2
...
5 15:51:45.322 Total Time: 1, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 2

Timeout performing SET (500ms), next: SET test, inst: 1, qu: 0, qs: 1, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 5, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 0, sync-ops: 6, async-ops: 0, serverEndpoint: 172.31.28.146:6379, conn-sec: 6.65, mc: 1/1/0, mgr: 10 of 10 available, clientName: ip-172-31-51-139(SE.Redis-v2.6.90.64945), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=1,Max=32767), POOL: (Threads=1,QueuedItems=3,CompletedItems=45), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
Note: profiler doesn't give results after exception - those results will be printed on next iteration
6 Test took 513 ms, ThreadCount 1 - **NOTE: thread count is always 1 after delay**

7 15:51:46.325 Total Time: 515, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 515, ResponseToComplete: 0, ThreadCount: 3
7 15:51:47.837 Total Time: 1, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 3

8 15:51:48.838 Total Time: 2, CreatToEnqueu: 0, EnqueuToSending: 1, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 4
...
12 15:51:52.854 Total Time: 1, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 4

Timeout performing SET (500ms), next: SET test, inst: 1, qu: 0, qs: 1, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 5, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 0, sync-ops: 13, async-ops: 0, serverEndpoint: 172.31.28.146:6379, conn-sec: 14.17, mc: 1/1/0, mgr: 10 of 10 available, clientName: ip-172-31-51-139(SE.Redis-v2.6.90.64945), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=1,Max=32767), POOL: (Threads=1,QueuedItems=3,CompletedItems=100), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
Note: profiler doesn't give results after exception - those results will be printed on next iteration
13 Test took 500 ms, ThreadCount 1 - **NOTE: thread count is always 1 after delay**

14 15:51:53.859 Total Time: 501, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 501, ResponseToComplete: 0, ThreadCount: 4
14 15:51:55.361 Total Time: 1, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 4

15 15:51:56.362 Total Time: 1, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 4


### **net6 build**
**NOTE: thread count is always > 1 after delay**
Initial values: minWorker 1, minIOC 1

1 16:02:41.319 Total Time: 6, CreatToEnqueu: 4, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 2
...
19 16:02:59.353 Total Time: 1, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 4

Timeout performing SET (500ms), next: SET test, inst: 1, qu: 0, qs: 1, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 5, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 0, sync-ops: 20, async-ops: 0, serverEndpoint: 172.31.28.146:6379, conn-sec: 20.7, mc: 1/1/0, mgr: 10 of 10 available, clientName: ip-172-31-51-139(SE.Redis-v2.6.90.64945), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=1,Max=32767), POOL: (Threads=4,QueuedItems=2,CompletedItems=125), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
Note: profiler doesn't give results after exception - those results will be printed on next iteration
20 Test took 508 ms, ThreadCount 4 - **NOTE: thread count is always > 1 after delay**

21 16:03:00.356 Total Time: 509, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 509, ResponseToComplete: 0, ThreadCount: 4
21 16:03:01.866 Total Time: 1, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 4

22 16:03:02.867 Total Time: 1, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 4
...
40 16:03:20.878 Total Time: 1, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 4

Timeout performing SET (500ms), next: SET test, inst: 1, qu: 0, qs: 1, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 5, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 0, sync-ops: 41, async-ops: 0, serverEndpoint: 172.31.28.146:6379, conn-sec: 42.22, mc: 1/1/0, mgr: 10 of 10 available, clientName: ip-172-31-51-139(SE.Redis-v2.6.90.64945), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=1,Max=32767), POOL: (Threads=4,QueuedItems=2,CompletedItems=210), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
Note: profiler doesn't give results after exception - those results will be printed on next iteration
41 Test took 500 ms, ThreadCount 4 - **NOTE: thread count is always > 1 after delay**

42 16:03:21.876 Total Time: 500, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 500, ResponseToComplete: 0, ThreadCount: 4
42 16:03:23.379 Total Time: 1, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 4

43 16:03:24.38 Total Time: 1, CreatToEnqueu: 0, EnqueuToSending: 0, SendingToResponse: 1, ResponseToComplete: 0, ThreadCount: 4

`      static async Task Main(string[] args)
	{
	    int ii = 0, minWorker, minIOC, setMinWorker = 1;
            ThreadPool.GetMinThreads(out minWorker, out minIOC);
	    Console.WriteLine("Initial values: minWorker {0}, minIOC {1}", minWorker, minIOC);
            if (ThreadPool.SetMinThreads(setMinWorker, minIOC))
            {
                Console.WriteLine($"set to {setMinWorker}");
            }
            else
            {
                Console.WriteLine("Not set");
            }
	    
	    Console.WriteLine($"ThreadCount: {ThreadPool.ThreadCount}");
	    var redisConfiguration = 
            ConfigurationOptions.Parse("redis.v9qasj.ng.0001.use1.cache.amazonaws.com:6379,syncTimeout=500", true);
            redisConfiguration.ResolveDns = true;
            
	    var connection = ConnectionMultiplexer.Connect(redisConfiguration, Console.Out);
            var profiler = new AsyncLocalProfiler();
            connection.RegisterProfiler(profiler.GetSession);

	    var database = connection.GetDatabase();

	    while(true)
	    {
		await Task.Delay(1000);
	        Console.WriteLine("");
		ii++;

               var sw = Stopwatch.StartNew();
               try{
	          database.StringSet("test",ii);
               } catch (Exception ex) {
                  Console.WriteLine(ex.Message);
		  Console.WriteLine("Note: profiler doesn't give results after exception - those results will be printed on next iteration");
	       }

	       var commands = profiler.GetSession().FinishProfiling().ToList();
               commands.ForEach(x => Console.WriteLine("{7} {0} Total Time: {1}, CreatToEnqueu: {2}, EnqueuToSending: {3}, SendingToResponse: {4}, ResponseToComplete: {5}, ThreadCount: {6}",
                   x.CommandCreated.ToString("HH:mm:ss.FFF"), x.ElapsedTime.Milliseconds, x.CreationToEnqueued.Milliseconds,
                   x.EnqueuedToSending.Milliseconds, x.SentToResponse.Milliseconds, x.ResponseToCompletion.Milliseconds, ThreadPool.ThreadCount, ii));

	       if (sw.ElapsedMilliseconds > 50)
               {
                   Console.WriteLine("{0} Test took {1} ms, ThreadCount {2}", ii, sw.ElapsedMilliseconds, ThreadPool.ThreadCount);
               }

               sw.Stop();
	    }
        }
    }
 
    public class AsyncLocalProfiler
    {
        private readonly AsyncLocal<ProfilingSession> perThreadSession = new AsyncLocal<ProfilingSession>();

        public ProfilingSession GetSession()
        {
            var val = perThreadSession.Value;
            if (val == null)
            {
                perThreadSession.Value = val = new ProfilingSession();
            }
            return val;
        }
    }`

**Comment by NickCraver** [comment]
I'd honestly need a memory dump when this is happening to see why we can't get a thread (e.g. what are they doing?), or why the completion isn't happening (could be down at the socket send or receive side). I wonder if @stephentoub could point us in the right direction here at thread counts so low. I'm curious about this one because my day job involves a lot of people on single-vCPU boxes and understanding what's happening here would be great.

**Comment by chapinmark** [comment]
I'm not really sure how to trigger a memory dump (or even do a memory dump).  Any suggestions? 

I set the following in my runtimeconfig.json, it did not help.  Only setting MinThreads helped.

I don't know how to verify that these settings are actually being use when built with net6.  ThreadCounts did not change noticeably compared to nothing set. 

System.Threading.ThreadPool.Blocking.ThreadsToAddWithoutDelay_ProcCountFactor: 2 and 4 
System.Threading.ThreadPool.Blocking.ThreadsPerDelayStep_ProcCountFactor: 2
System.Threading.ThreadPool.Blocking.DelayStepMs: 100
System.Threading.ThreadPool.Blocking.MaxDelayMs: 500

**Comment by chapinmark** [comment]
I was able to capture a full memory dump with dotnet-dump.  I believe I issued the command while the delay was occurring.  I have no idea how to analyze this dump though.  Any suggestions?

**Comment by NickCraver** [comment]
@chapinmark Do you have Visual Studio? You can open it directly that way, and use the Threads and Task views under Debug to browse around and see what's active..

**Comment by chapinmark** [comment]
@NickCraver I looked at the dump file in VS 2022.  Unfortunately, I was not able to gain much insight from it.  That would be the first dump file I looked at.  There might be something there but I'm not seeing it.

I'm going to print the call stack within SocketsAwaitableEventArgs (Pipeline.Unofficial..) and see where that points me.  I'm also trying to locally build dotnet/runtime to debug further.  I'll let you know if I find anything.

**Comment by chapinmark** [comment]
@NickCraver the delay occurs on a 4 vCPU instance if I set MinThreads to 1.  Similar frequency, about 1 in 60 calls to StringSet.  Not surprisingly, it also occurs with StringGet.

**Comment by chapinmark** [comment]
@NickCraver I was able to find where NumThreadsGoal is reduced to 1 in System.Threading.PortableThreadPool.  I can see that NumThreadsGoal goes from 2  or 3 to 1 in one evaluation of ThreadPoolHillClimber.Update.  I did not try to figure out why ThreadPoolHillClimber.Update reduced the goal to 1, it's too complex.

If _separated.counts.NumThreadsGoal is reduced to 1, there are no threads to perform the work in the queue (processing the socket response) since I am blocking the only thread available.  After a wait of between 500 and 1000ms, the GateThread takes over and realizes there is work to do.  This is why it eventually processes the response.

Do you consider this a bug?  If so, I can report it in dotnet/runtime.

PS:  I couldn't figure out how to properly reference the lines of code in System.Threading.PortableThreadPool, below is my best attempt...
 
(newNumThreadsGoal, _threadAdjustmentIntervalMs) =
                        HillClimbing.ThreadPoolHillClimber.Update(oldNumThreadsGoal, elapsedSeconds, numCompletions);

https://github.com/dotnet/runtime/blob/bcd44bfc3d435ffe5af372491818a9cfcd0a959b/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.cs#L370

**Comment by NickCraver** [comment]
You can file an issue to see what the team thinks - I honestly have no idea. It's a set of growth algorithms designed to fit _most_ scenarios by default and the answer you may get is used the overrides for minimums if it doesn't suit your needs. But to get any better answer, dotnet/runtime is where to ask the experts :)

**Comment by NickCraver** [comment]
@chapinmark Did you have any more questions here? Didn't want to close it out if so, but not sure what else there is on the library side here for anything to do or change...asking though!
