### ISSUE TITLE
Experiencing timeouts on Linux but not on Windows

### ISSUE THREAD

**Issue by Karanveer-Mul** [StackExchange/StackExchange.Redis#2366]
We recently migrated from .Net Framework 4.5 to .Net 6 and decided to change over to StackExchange as the new RedisClient library.
I'm running load tests in dev environment to simulate Production traffic. However I'm noticing timeout exceptions when running higher loads. From what I could see in the documentation it seems like my machine is not able to start new threads in time to process requests. I verified this by increasing the minimum thread pool and it seemed to fix the issue but this solution is not scalable.

I'm running my Core API on AWS Linux 2 instance (t2.micro) and a similar configuration hosted on Windows IIS. What I find strange is that same code seems to work fine on windows and connecting to the same redis server without messing around with minimum threadpool count.

We are running synchronous code due to existing application running in synchronous flow so changing to async flow is not the ideal solution.

Would appreciate any insights on figuring this issue out.

StackExchange.Redis.RedisTimeoutException: Timeout performing SETEX (5000ms), 
next: GET RedisKey, 
inst: 11,
qu: 0, 
qs: 144, 
aw: False, 
bw: SpinningDown, 
rs: ReadAsync, 
ws: Idle, 
in: 15890, 
in-pipe: 0, 
out-pipe: 0, 
last-in: 2, 
cur-in: 0, 
sync-ops: 585, 
async-ops: 0, 
serverEndpoint: ****, 
conn-sec: 137.41, 
mc: 1/1/0, 
mgr: 10 of 10 available, 
clientName: ****, 
IOCP: (Busy=0,Free=1000,Min=1,Max=1000), 
WORKER: (Busy=67,Free=32700,Min=1,Max=32767), 
POOL: (Threads=67,QueuedItems=3,CompletedItems=485), 
v: 2.6.86.49666 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1911
   at StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable`1 expiry, Boolean keepTtl, When when, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 3128

**Comment by NickCraver** [comment]
I think you have figured the main issue out exactly - thread pool growth semantics is exactly what you're hitting. I'm interpreting the remaining question as "Why is it different?" I'm not sure there but I'd advise to first be sure you're testing equivalent things.

For example, if the Linux server is further away (even by microseconds), that's going to have different thresholds for falling over, because it directly affects how fast threads are returned and how much pile-up is happening. My cloud-based guess is it's almost certain those 2 machines aren't on the same host and may have different network topologies...or hypervisors/firewalls/etc. to go through, all affecting round-trip time. Do you actually have the same number of cores/hardware as well? (note: these still aren't 1:1, .NET will differ across platforms because system calls underneath also vary)

You could for example use [the profiling API](https://stackexchange.github.io/StackExchange.Redis/Profiling_v2.html) to get some timings and numbers to compare there. I'm curious what you find!

**Comment by lobodava** [comment]
We have the same set of starting conditions:
— .Net 7, ASP.NET Core
— StackExchange.Redis (the last update June 08, 2023)
— Redis (7.0)

With 20,000–50,000 requests per minute, the ASP.NET application worked without any errors. On Windows!
However, on Linux (Ubuntu and AlmaLinux were checked), the logs showed a lot of StackExchange.Redis.RedisTimeoutException
exception within several seconds, and then the application completely refused to respond.

The following ThreadPool setup in `Program.cs` file helped to keep the application running on Linux:
```
public class Program
{
	public static void Main(string[] args)
	{
		ThreadPool.GetMinThreads(out int minWorker, out int minIOC);
		ThreadPool.GetMaxThreads(out int maxWorker , out int maxIOC);

		if (maxWorker < 32767)
			ThreadPool.SetMaxThreads(32767, maxIOC);

		if (minWorker < 1000)
			ThreadPool.SetMinThreads(1000, minIOC);

		CreateHostBuilder(args).Build().Run();
	}
}
```
Here is the doc: https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadpool.setminthreads?view=net-7.0

Originally the `minWorker` value on our machine was 16. 
According to the documentation "By default, the minimum number of threads is set to the processor count.".

**Comment by NickCraver** [comment]
@lobodava That's going to do very bad things too at scale :) If you have some exception examples, that'd help, but you should see what those threads are doing on Linux. It's possible you're just over a threshold, or that you're _way_ over - an exception message would help there seeing just a bit of what's happening. Even a mini dump using https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump#dotnet-dump-collect (type: Mini) would give you thread information and insight of where things are with minimal disruption.

**Comment by NickCraver** [comment]
Need more info to go on here - so closing out without that, but basically: thread exhaustion, external to the library is happening and that's the core issue here.
