### ISSUE TITLE
SortedSetAddAsync(RedisKey key, SortedSetEntry[] values) produces wrong value in DB?

### ISSUE THREAD

**Issue by larryons** [StackExchange/StackExchange.Redis#2369]
Version 2.6.90
.net 7
Example code:

```
public Task AddPublicationsToUserFeedAsync(Guid userId, SortedSetEntry[] items)
{
        var userFeedKey = RedisKeyStorage.GetUserFeedKey(userId);
        var trimTime = DateTimeOffset.UtcNow.AddDays(-Consts.DaysToGetPublications).ToUnixTimeSeconds();
        var transaction = _redisDatabase.CreateTransaction();
        _ = transaction.SortedSetAddAsync(userFeedKey, items);
        _ = transaction.SortedSetRemoveRangeByScoreAsync(userFeedKey, 0, trimTime);
        return transaction.ExecuteAsync();
}
```

this code produces:
![image](https://user-images.githubusercontent.com/108321237/217831056-dfea2135-90d8-4bcf-b30a-dc338670a05e.png)
but my expectations were about
![image](https://user-images.githubusercontent.com/108321237/217831355-74e35ec4-228f-424b-a687-6faf86a8b659.png)

Is this behaviour correct?

**Comment by NickCraver** [comment]
I'm trying to determine what's being asked here. What mismatches your expectations? (what's in the screenshots here is just entirely different sets of data) And what are you passing in as items? I can see from the value there's a mismatch in seconds vs. milliseconds but beyond that, I'm not sure what you're passing and expect to have happen.

**Comment by larryons** [comment]
I mean, why array of SortedSetEntries added to DB like `{ id = 127bc463-ce5e-428a-ba57-13aed8f756cf, timestamp = 02/08/2023 12:12:00 +00:00 }` but not just score and value like on second screenshot? Is it normal?

**Comment by NickCraver** [comment]
@larryons Again: _what are you passing in?_ You're passing in an array of `items` and we can't see what their value is.

**Comment by NickCraver** [comment]
@larryons A SortedSetEntry's element type is RedisValue, this can be _anything_. It can be a 40 MB PDF file. I'm asking what it is in your case, because _that's what we're sending out the other end_. It's very likely your problem is in converting to the entry, and nothing at all included in the post, that's why we're asking.

I'm trying to help, please don't make us continually pry for information, we're not paid to do this.

**Comment by larryons** [comment]
@NickCraver Sorry for my inattention. It's my first time here. In my case element is always Guid in string representation. For example: 
```
var items = userPublications
            .Select(x => new SortedSetEntry(x.Id.ToString(), x.Date.ToUnixTimeSeconds()))
            .ToArray();
```

Thank you for trying to help.

**Comment by NickCraver** [comment]
What is the type of `Id` there, a literal `System.Guid`? Or a custom type? A key indicator here is "timestamp" isn't a thing we have, that has to be coming from a type upstream.

**Comment by larryons** [comment]
Found a problem. It was in our external lib with models. Sorry to take up your time.
