### ISSUE TITLE
String serialization difference when using batched command

### ISSUE THREAD

**Issue by muj-beg** [StackExchange/StackExchange.Redis#2372]
Hi.  I created a simple NET  7 WebAPI test project, and then added the following two packages to it:

```
<PackageReference Include="StackExchange.Redis.Extensions.AspNetCore" Version="8.0.5" />
<PackageReference Include="StackExchange.Redis.Extensions.Newtonsoft" Version="8.0.5" />
```

In `Program.cs` I have this:
```csharp
builder.Services.AddStackExchangeRedisExtensions<NewtonsoftSerializer>(...);
```

The controller code is quite bare bones:
```csharp
[ApiController]
[Route("")]
public class HomeController : ControllerBase
{
    private readonly IRedisDatabase _redis;

    public HomeController(IRedisDatabase redis)
    {
        _redis = redis;
    }

    [HttpGet]
    public async Task<IActionResult> Get()
    {
        const string key = "test";

       // ---->  Write key/value without batching
        await _redis.HashSetAsync(key, "key-1", "value-1");

       // ---->  Write key/value with batching
        var batch = _redis.Database.CreateBatch();
        var t1 = batch.HashSetAsync(key, "key-2", "value-2");
        batch.Execute();
        await t1;

        return Ok("test");
    }
}
```

When I check the Redis DB after this executes, I see this:
![image](https://user-images.githubusercontent.com/19629343/218205454-19e5ed7e-88ae-48e9-9a2d-93ad37e9dd3c.png)

Note that `value-1` is quoted, but not `value-2` -- which seems rather strange.  In fact trying to read back `value-2` using `HashGetAsync<string>()`  throws a serialization  exception from NewtonsoftJson.

**Comment by mgravell** [comment]
This seems ... critical and unlikely in equal measure! I will investigate as soon as I get chance, but: I also want to be very clear about the code shown (since this matters) - `_redis.Database` on `IDatabase`? I'm not sure that compiles - are you sure that is the real code? Sorry to be a pain, but getting the details right here could be hugely important

**Comment by NickCraver** [comment]
I'm not sure what these libraries do...but they're not us :) Their extension repo is here: https://github.com/imperugo/StackExchange.Redis.Extensions - they are doing some other things to the values.

**Comment by mgravell** [comment]
Oh, yeah, if you're using a third party add on: ask the third party

**Comment by muj-beg** [comment]
My apology;  I really though this was part of the StackExcahnges team's pachage :( . Given the package name and the fact that interface looks similar enough to the official package, I might have gone down the wrong path:
![image](https://user-images.githubusercontent.com/19629343/218221342-f03ed898-c6b9-4348-8b99-a1098d13251a.png)


I'll close the ticket.

**Comment by muj-beg** [comment]
I do want to note one thing however.  The interface returned by _redis.Database is a `StackExchange.Redis.IDatabase` instance -- so while this is partly 3rd party  -- it ultimately seems to call into the StackExchange IDatabase interface.  I'll try the same code without using the 3rd party package and post here if the anomaly is still there.  Thanks for looking intopla.

**Comment by mgravell** [comment]
Our API is IDatabase; IRedisDatabase is the external wrapper, with IRedisDatabase.Database giving back our API.  So: we're using naked values, and they (the wrapper) are adding quotes - I have no idea why, but that's one for them. I suspect if you use IRedisDatabase.Database for both operations you'll get the same result, but: then it might not work with this wrapper library.
