### ISSUE TITLE
Client not responsive since upgrading from 2.6.86 to 2.6.90

### ISSUE THREAD

**Issue by gdoron** [StackExchange/StackExchange.Redis#2374]
Hi guys, 

Since upgrading from 2.6.86 to 2.6.90, on average every 2 days we have a pod starting with

> StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 10948ms elapsed, timeout is 5000ms), command=SUBSCRIBE, next: SUBSCRIBE cache-messages, inst: 0, qu: 0, qs: 1, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 15970, in-pipe: 0, out-pipe: 0, last-in: 0, cur-in: 0, sync-ops: 0, async-ops: 1, serverEndpoint: our-domain.com:12333, conn-sec: 15.72, mc: 1/1/0, mgr: 10 of 10 available, clientName: our-company-id(SE.Redis-v2.6.90.64945), IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=21,Free=32746,Min=4,Max=32767), POOL: (Threads=21,QueuedItems=100,CompletedItems=685), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
at StackExchange.Redis.RedisSubscriber.SubscribeAsync(RedisChannel channel, CommandFlags flags) in /_/src/StackExchange.Redis/RedisSubscriber.cs:line 390
at Foundatio.Messaging.RedisMessageBus.EnsureTopicSubscriptionAsync(CancellationToken cancellationToken) in /_/src/Foundatio.Redis/Messaging/RedisMessageBus.cs:line 33
at Foundatio.Messaging.MessageBusBase`1.SubscribeAsync[T](Func`3 handler, CancellationToken cancellationToken) in /_/src/Foundatio/Messaging/MessageBusBase.cs:line 132
at Foundatio.Caching.HybridCacheClient..ctor(ICacheClient distributedCacheClient, IMessageBus messageBus, InMemoryCacheClientOptions localCacheOptions, ILoggerFactory loggerFactory) in /_/src/Foundatio/Caching/HybridCacheClient.cs:line 27
at ZA.Common.Providers.Cache.Redis.RedisHybridCacheClientContainer.InitClient(RedisHybridCacheConfiguration configuration, RedisConnectionMultiplexerContainer

There are thousands of errors like this (always the same metrics in the exception) in a very short amount of time until the pod crashes.

We are also using `Foundatio.Redis` version `10.6.0` for hybrid redis\in-memory cache.

We are wondering if it can be related somehow to:
https://github.com/StackExchange/StackExchange.Redis/issues/1458

Best,
Doron

**Comment by gdoron** [comment]
We rolledback to the previous version and it did not solve it.
Seems like we got hit by the issue described here:
https://gist.github.com/JonCole/925630df72be1351b21440625ff2671f#reconnecting-with-lazyt-pattern

Though interestingly it correlated perfectly with StackExchange.Redis update, it was not the root cause.
@mgravell feel free to close or alter the title, since anyway there is an issue somewhere.

**Comment by Amir-Chehri** [comment]
WORKER: (Busy=21,Free=32746,Min=4,Max=32767)

**Comment by Amir-Chehri** [comment]
Based on the provided exception, you're experiencing thread pool throttling.

> WORKER: (Busy=21,Free=32746,Min=4,Max=32767)

It means that you have 21 busy threads while you're min thread pool size is 4.

**Comment by mgravell** [comment]
> Based on the provided exception, you're experiencing thread pool throttling.

I'm not sure I could make that conclusion. What I *can* see is a lot of backlog on what appears to be the pub/sub connection; is this under particularly high pub/sub throughout? If so, what does your subscription code look like? Maybe there's some answers there.

**Comment by gdoron** [comment]
@mgravell see my comments on `ResetContainer` below.
Also, we believe it actually related to the behavior the azure redis team describes here: 
https://gist.github.com/JonCole/925630df72be1351b21440625ff2671f#reconnecting-with-lazyt-pattern
(Though we run on AWS, shouldn't matter)

About the throughput, a couple of 10K requests an hour per pod.
When the client manages to init at startup, it manages to handle the load just fine, when it doesn't - it logs these errors from the get go.

```csharp
using System;
using System.Threading.Tasks;
using Foundatio.Caching;
using Foundatio.Serializer;
using NewRelic.Api.Agent;

namespace CompanyFoo

public class RedisHybridCacheClientContainer : IRedisHybridCacheClientContainer, IDisposable {
    private readonly RedisConnectionMultiplexerContainer _multiplexerContainer;
    private readonly Lazy<RedisHybridCacheClient> _client;

    public RedisHybridCacheClientContainer(RedisHybridCacheConfiguration configuration,
        RedisConnectionMultiplexerContainer multiplexerContainer,
        ISerializer serializer) {
        _multiplexerContainer = multiplexerContainer;
        _client = new Lazy<RedisHybridCacheClient>(
            () => InitClient(configuration, multiplexerContainer, serializer));
    }

    public IHybridCacheClient RedisHybridCacheClient => _client.Value;

    /// <summary>
    /// This we added after seeing the above, where if for some reason InitClient fails
    /// it would forever fail and not recover. So now on startup, we explicitly call the client to make sure it works, and if it does not
    // We call ResetContainer.
    /// </summary>
    public async Task ResetContainer() {
        await _multiplexerContainer.ResetMultiplexer();
    }
    public void Dispose() {
        if (_client.IsValueCreated)
            _client.Value.Dispose();
    }

    [Trace]
    private static RedisHybridCacheClient InitClient(RedisHybridCacheConfiguration configuration,
        RedisConnectionMultiplexerContainer multiplexerContainer,
        ISerializer serializer) {
        var redisOptions = new RedisHybridCacheClientOptions {
            Serializer = serializer,
            ShouldThrowOnSerializationError = true,
            ConnectionMultiplexer = multiplexerContainer.RedisConnectionMultiplexer
        };

        var inMemoryOptions = new InMemoryCacheClientOptions {
            Serializer = serializer,
            ShouldThrowOnSerializationError = true,
            CloneValues = true,
            MaxItems = configuration.MaxItems
        };

        return new RedisHybridCacheClient(redisOptions, inMemoryOptions);
    }
}
```

**Comment by NickCraver** [comment]
That's all another library so I'm not sure what all it's doing under the covers, but overall: we don't recommend a reconnect pattern as all the reasons for it we're aware of are not handled internally. Tearing down the multiplexer while it's doing down or trying to reconnect is likely to cause _more_ errors (e.g. tossing pending backlogs) than to help at this point. If you're getting any kid of lockups _without_ the reconnect pattern - I'm super curious and we'd want to solve those ASAP.

**Comment by NickCraver** [comment]
Closing out to tidy up here - happy to reopen if questions persist.
