### ISSUE TITLE
Battling with TimeoutException

### ISSUE THREAD

**Issue by caoyang1024** [StackExchange/StackExchange.Redis#2379]
We are using Redis for PUB/SUB (>90%) and Cache(<=10%), but occasionally we still have timeout issue which we don't have idea why and how can we fix it. Can anyone guide please?

2023-02-18 08:00:10	
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=6KiB, inbound=0KiB, 5708ms elapsed, timeout is 5000ms), command=SETEX, next: SETEX ********************, inst: 0, qu: 0, qs: 55, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 254, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 0, sync-ops: 1, async-ops: 221132, serverEndpoint: xxx.xxx.xxx.xxx:xxxxx, conn-sec: 6364.8, mc: 1/1/0, mgr: 10 of 10 available, clientName: [NAME](SE.Redis-v2.6.90.64945), PerfCounterHelperkeyHashSlot: 1171, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=93,Free=32674,Min=8,Max=32767), POOL: (Threads=93,QueuedItems=1373,CompletedItems=12918282), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
2023-02-18 08:00:10	
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=6KiB, inbound=0KiB, 5708ms elapsed, timeout is 5000ms), command=ZREMRANGEBYSCORE, next: SETEX ********************, inst: 0, qu: 0, qs: 55, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 254, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 0, sync-ops: 1, async-ops: 221132, serverEndpoint: xxx.xxx.xxx.xxx:xxxxx, conn-sec: 6364.8, mc: 1/1/0, mgr: 10 of 10 available, clientName: [NAME](SE.Redis-v2.6.90.64945), PerfCounterHelperkeyHashSlot: 1171, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=93,Free=32674,Min=8,Max=32767), POOL: (Threads=93,QueuedItems=1374,CompletedItems=12918282), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)Show context
2023-02-18 08:00:10	
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=5KiB, inbound=0KiB, 5708ms elapsed, timeout is 5000ms), command=SETEX, next: SETEX ********************, inst: 0, qu: 0, qs: 55, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 254, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 0, sync-ops: 1, async-ops: 221132, serverEndpoint: xxx.xxx.xxx.xxx:xxxxx, conn-sec: 6364.8, mc: 1/1/0, mgr: 10 of 10 available, clientName: [NAME](SE.Redis-v2.6.90.64945), PerfCounterHelperkeyHashSlot: 1171, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=93,Free=32674,Min=8,Max=32767), POOL: (Threads=93,QueuedItems=1375,CompletedItems=12918282), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
2023-02-18 08:00:10	
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=5KiB, inbound=0KiB, 5184ms elapsed, timeout is 5000ms), command=SETEX, next: SETEX ********************, inst: 0, qu: 0, qs: 55, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 254, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 0, sync-ops: 1, async-ops: 221132, serverEndpoint: xxx.xxx.xxx.xxx:xxxxx, conn-sec: 6364.8, mc: 1/1/0, mgr: 10 of 10 available, clientName: [NAME](SE.Redis-v2.6.90.64945), PerfCounterHelperkeyHashSlot: 2120, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=93,Free=32674,Min=8,Max=32767), POOL: (Threads=93,QueuedItems=1376,CompletedItems=12918282), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
2023-02-18 08:00:10	
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=5KiB, inbound=0KiB, 5184ms elapsed, timeout is 5000ms), command=ZREMRANGEBYSCORE, next: SETEX ********************, inst: 0, qu: 0, qs: 55, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 254, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 0, sync-ops: 1, async-ops: 221132, serverEndpoint: xxx.xxx.xxx.xxx:xxxxx, conn-sec: 6364.8, mc: 1/1/0, mgr: 10 of 10 available, clientName: [NAME](SE.Redis-v2.6.90.64945), PerfCounterHelperkeyHashSlot: 2120, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=93,Free=32674,Min=8,Max=32767), POOL: (Threads=93,QueuedItems=1377,CompletedItems=12918282), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
2023-02-18 08:00:10	
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=5KiB, inbound=0KiB, 5184ms elapsed, timeout is 5000ms), command=SETEX, next: SETEX ********************, inst: 0, qu: 0, qs: 55, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 254, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 0, sync-ops: 1, async-ops: 221132, serverEndpoint: xxx.xxx.xxx.xxx:xxxxx, conn-sec: 6364.8, mc: 1/1/0, mgr: 10 of 10 available, clientName: [NAME](SE.Redis-v2.6.90.64945), PerfCounterHelperkeyHashSlot: 2120, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=93,Free=32674,Min=8,Max=32767), POOL: (Threads=93,QueuedItems=1378,CompletedItems=12918282), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

more log at different time:

2023-02-18 08:00:10	
00:00:10.2843: Sync timeouts: 0; async timeouts: 96; fire and forget: 0; last heartbeat: 0s ago
2023-02-18 08:00:10	
00:00:10.2843:   [address_1]:6379: Circular op-count snapshot; int: 118 (0.00 ops/s; spans 10s); sub: 5 (0.00 ops/s; spans 10s)
2023-02-18 08:00:10	
00:00:10.2843:   [address_1]:6379: int ops=118, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=5, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
2023-02-18 08:00:10	
00:00:10.2843:   [address_1]:6379: Cluster v7.0.8, replica; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
2023-02-18 08:00:10	
00:00:10.2843:   [address_2]:6379: Circular op-count snapshot; int: 118 (0.00 ops/s; spans 10s); sub: 5 (0.00 ops/s; spans 10s)
2023-02-18 08:00:10	
00:00:10.2843:   [address_2]:6379: int ops=118, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=5, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
2023-02-18 08:00:10	
00:00:10.2843:   [address_2]:6379: Cluster v7.0.8, replica; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
2023-02-18 08:00:10	
00:00:10.2843:   [address_3]:6379: Circular op-count snapshot; int: 118 (0.00 ops/s; spans 10s); sub: 5 (0.00 ops/s; spans 10s)
2023-02-18 08:00:10	
00:00:10.2843:   [address_3]:6379: int ops=118, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=5, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
2023-02-18 08:00:10	
00:00:10.2843:   [address_3]:6379: Cluster v7.0.8, replica; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
2023-02-18 08:00:10	
00:00:10.2843:   [address_4]:6379: Circular op-count snapshot; int: 89215+14+9+8+10+13+69+9+21+19+1=89388 (17.30 ops/s; spans 10s); sub: 188 (0.00 ops/s; spans 10s)
2023-02-18 08:00:10	
00:00:10.2843:   [address_4]:6379: int ops=89388, qu=0, qs=56, qc=0, wr=0, socks=1; sub ops=188, qu=0, qs=0, qc=0, wr=0, subs=185, socks=1
2023-02-18 08:00:10	
00:00:10.2843:   [address_4]:6379: Cluster v7.0.8, primary; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 185 active
2023-02-18 08:00:10	
00:00:10.2843:   [address_5]:6379: Circular op-count snapshot; int: 64973+3+9+6+6+8+55+21+6+27=65114 (14.10 ops/s; spans 10s); sub: 176 (0.00 ops/s; spans 10s)
2023-02-18 08:00:10	
00:00:10.2843:   [address_5]:6379: int ops=65114, qu=0, qs=63, qc=0, wr=0, socks=1; sub ops=176, qu=0, qs=0, qc=0, wr=0, subs=173, socks=1
2023-02-18 08:00:10	
00:00:10.2841:   [address_5]:6379: Cluster v7.0.8, primary; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 173 active
2023-02-18 08:00:10	
00:00:10.2841:   [address_6]:6379: Circular op-count snapshot; int: 66279+5+9+6+12+12+78+18+21+14=66454 (17.50 ops/s; spans 10s); sub: 176 (0.00 ops/s; spans 10s)
2023-02-18 08:00:10	
00:00:10.2840:   [address_6]:6379: int ops=66454, qu=0, qs=56, qc=0, wr=0, socks=1; sub ops=176, qu=0, qs=0, qc=0, wr=0, subs=173, socks=1
2023-02-18 08:00:10	
00:00:10.2840:   [address_6]:6379: Cluster v7.0.8, primary; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 173 active
2023-02-18 08:00:10	
00:00:10.2840:   [address_7]:6379: Circular op-count snapshot; int: 118 (0.00 ops/s; spans 10s); sub: 4 (0.00 ops/s; spans 10s)
2023-02-18 08:00:10	
00:00:10.2840:   [address_7]:6379: int ops=118, qu=0, qs=0, qc=0, wr=0, socks=1, non-pref=1; sub ops=4, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
2023-02-18 08:00:10	
00:00:10.2840:   [address_7]:6379: Cluster v7.0.8, replica; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
2023-02-18 08:00:10	
2023-02-18 00:00:10.284395 +00:00 [Error] [Machine] [P=1] [T=116] [[XXX]] 00:00:10.2840: Endpoint Summary:
2023-02-18 08:00:10	
   at [XXX].SetAsync[TValue](String key, TValue value, Nullable`1 expiry) in xxxxxxxxxxxxxx.cs:line 66
2023-02-18 08:00:10	
StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=5KiB, inbound=0KiB, 5184ms elapsed, timeout is 5000ms), command=SETEX, next: SETEX xxxxxxxxxxx, inst: 0, qu: 0, qs: 55, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 254, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 0, sync-ops: 1, async-ops: 221132, serverEndpoint: [address_4]:6379, conn-sec: 6364.8, mc: 1/1/0, mgr: 10 of 10 available, clientName: client(SE.Redis-v2.6.90.64945), PerfCounterHelperkeyHashSlot: 2120, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=93,Free=32674,Min=8,Max=32767), POOL: (Threads=93,QueuedItems=1378,CompletedItems=12918282), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
2023-02-18 08:00:10	
2023-02-18 00:00:10.283853 +00:00 [Error] [Machine] [P=1] [T=116] [[XXX]] SetAsync : k:xxxxx v:xxxxx s:"00:00:10.2836: Endpoint Summary:\n00:00:10.2836:   [address_7]:6379: Cluster v7.0.8, replica; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active\n00:00:10.2837:   [address_7]:6379: int ops=118, qu=0, qs=0, qc=0, wr=0, socks=1, non-pref=1; sub ops=4, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1\n00:00:10.2837:   [address_7]:6379: Circular op-count snapshot; int: 118 (0.00 ops/s; spans 10s); sub: 4 (0.00 ops/s; spans 10s)\n00:00:10.2837:   [address_6]:6379: Cluster v7.0.8, primary; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 173 active\n00:00:10.2837:   [address_6]:6379: int ops=66454, qu=0, qs=56, qc=0, wr=0, socks=1; sub ops=176, qu=0, qs=0, qc=0, wr=0, subs=173, socks=1\n00:00:10.2837:   [address_6]:6379: Circular op-count snapshot; int: 66279+5+9+6+12+12+78+18+21+14=66454 (17.50 ops/s; spans 10s); sub: 176 (0.00 ops/s; spans 10s)\n00:00:10.2837:   [address_5]:6379: Cluster v7.0.8, primary; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 173 active\n00:00:10.2837:   [address_5]:6379: int ops=65114, qu=0, qs=63, qc=0, wr=0, socks=1; sub ops=176, qu=0, qs=0, qc=0, wr=0, subs=173, socks=1\n00:00:10.2838:   [address_5]:6379: Circular op-count snapshot; int: 64973+3+9+6+6+8+55+21+6+27=65114 (14.10 ops/s; spans 10s); sub: 176 (0.00 ops/s; spans 10s)\n00:00:10.2838:   [address_4]:6379: Cluster v7.0.8, primary; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 185 active\n00:00:10.2838:   [address_4]:6379: int ops=89387, qu=0, qs=55, qc=0, wr=0, socks=1; sub ops=188, qu=0, qs=0, qc=0, wr=0, subs=185, socks=1\n00:00:10.2838:   [address_4]:6379: Circular op-count snapshot; int: 89215+14+9+8+10+13+69+9+21+19=89387 (17.20 ops/s; spans 10s); sub: 188 (0.00 ops/s; spans 10s)\n00:00:10.2838:   [address_3]:6379: Cluster v7.0.8, replica; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active\n00:00:10.2838:   [address_3]:6379: int ops=118, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=5, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1\n00:00:10.2838:   [address_3]:6379: Circular op-count snapshot; int: 118 (0.00 ops/s; spans 10s); sub: 5 (0.00 ops/s; spans 10s)\n00:00:10.2838:   [address_2]:6379: Cluster v7.0.8, replica; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active\n00:00:10.2838:   [address_2]:6379: int ops=118, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=5, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1\n00:00:10.2838:   [address_2]:6379: Circular op-count snapshot; int: 118 (0.00 ops/s; spans 10s); sub: 5 (0.00 ops/s; spans 10s)\n00:00:10.2838:   [address_1]:6379: Cluster v7.0.8, replica; 16 databases; keep-alive: 7.00:00:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active\n00:00:10.2838:   [address_1]:6379: int ops=118, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=5, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1\n00:00:10.2838:   [address_1]:6379: Circular op-count snapshot; int: 118 (0.00 ops/s; spans 10s); sub: 5 (0.00 ops/s; spans 10s)\n00:00:10.2838: Sync timeouts: 0; async timeouts: 96; fire and forget: 0; last heartbeat: 0s ago\n"

**Comment by NickCraver** [comment]
It looks like you're likely exhausting the thread pool, given by `WORKER: (Busy=93,Free=32674,Min=8,Max=32767)`. Your usage of StackExchange.Redis is great with all async usage (`sync-ops: 1, async-ops: 221132`), but it looks like some other part of your application needs similar love to not exhaust available threads in the pool. The quickest way to diagnose this is take a memory dump while it's happening and see what all the threads are doing - so very often you'll see they're all in a similar spot and the effect is multiplying. I hope that's your case - quicker to make better!

If it helps, whenever I've seen this _it's almost always happening_, just not enough _to reach the limit_, so while most people thing you need to catch it in the act when a timeout happens, generally any memory dump under load works to find the culrpits. Occasionally that's wrong (e.g. it's a specific nightly job or something), but just throwing that out there in case it helps :)

**Comment by KarthikHebbarMN** [comment]
Not sure if its fall under the same basket. But we too are experiencing Time Out errors. 
I just did a test run with a simple SET ADD operation. With key being "fbf9f4" and value being "1".

Here is the code for Adding the set 
```
public async void AppendProductIdToColorBand(ColorProductMap prodColorMap) {
            await db.SetAddAsync("fbf9f4", 1);

        }
```

Based on some suggestion tried out with Lazy initializer for getting the database, not sure how it would even help, but at desperate times you try everything 
```
private static Lazy<ConnectionMultiplexer> lazyConnection = new Lazy<ConnectionMultiplexer>(() => { return ConnectionMultiplexer.Connect("0.0.0.0:6739,ssl=false,abortConnect=false"); });

        public static ConnectionMultiplexer Connection { get { return lazyConnection.Value; } }
```

And here is the error 

> Exception has occurred: CLR/StackExchange.Redis.RedisTimeoutException
An exception of type 'StackExchange.Redis.RedisTimeoutException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'The timeout was reached before the message could be written to the output buffer, and it was not sent, command=SADD, timeout: 5000, inst: 0, qu: 0, qs: 0, aw: False, bw: CheckingForTimeout, last-in: 0, cur-in: 0, sync-ops: 0, async-ops: 1, serverEndpoint: 0.0.0.0:6739, conn-sec: n/a, mc: 1/1/0, mgr: 10 of 10 available, clientName: DESKTOP-R5IPF7I(SE.Redis-v2.6.90.64945), IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=2,Free=32765,Min=12,Max=32767), POOL: (Threads=17,QueuedItems=0,CompletedItems=281), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)'

**Environment**
 Windows : 10 
 Dotnet Version: dotnet6.0
 StackExchange version: 2.6.90

Redis server running in docker 

Tried with Sync as well

**Comment by NickCraver** [comment]
For your case, 0.0.0.0 is not a valid endpoint to connect to, you'll need to use the actual IP of the instance. Sometimes you'll see 0.0.0.0 on the listening side which usually means "listen on all IPs this machine has", but doesn't work the other direction.

**Comment by KarthikHebbarMN** [comment]
Hey tried with localhost 
and Ip address listed for redis in docker inspect for that redis container. Both results in same error 

> An exception of type 'StackExchange.Redis.RedisTimeoutException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'The timeout was reached before the message could be written to the output buffer, and it was not sent, command=SADD, timeout: 5000, inst: 0, qu: 0, qs: 0, aw: False, bw: CheckingForTimeout, rs: NotStarted, ws: Idle, in: 0, last-in: 0, cur-in: 0, sync-ops: 0, async-ops: 1, serverEndpoint: 172.17.0.2:6739, conn-sec: n/a, mc: 1/1/0, mgr: 10 of 10 available, clientName: DESKTOP-R5IPF7I(SE.Redis-v2.6.90.64945), IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=2,Free=32765,Min=12,Max=32767), POOL: (Threads=15,QueuedItems=0,CompletedItems=163), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)'

**Comment by NickCraver** [comment]
@KarthikHebbarMN see the `conn-sec: n/a`? That means you haven't ever successfully connected to the server. Be sure you're _not_ setting `abortConnect=false` so that you can see the reason it's failing.

**Comment by KarthikHebbarMN** [comment]
He @NickCraver Thanks for getting back so quick. Did set the abortConnection to false, you were right connection failed. But the exception is not very helpful. Any idea how to get more information 

> An exception of type 'StackExchange.Redis.RedisConnectionException' occurred in StackExchange.Redis.dll but was not handled in user code: 'It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.'

The redis server is spun up in port forward network mode

**Comment by NickCraver** [comment]
@KarthikHebbarMN check the .Connect(Async) method, the second argument is a logger which will tell you far more - if you can share that log it'll be very helpful in advising.

**Comment by KarthikHebbarMN** [comment]
>
[redis-logs.txt](https://github.com/StackExchange/StackExchange.Redis/files/10843072/redis-logs.txt)
[redis-logs2.txt](https://github.com/StackExchange/StackExchange.Redis/files/10843073/redis-logs2.txt)

Thanks again for the help. I have attached two logs, one with localhost and other with Docker assigned IP

**Comment by KarthikHebbarMN** [comment]
Hey @NickCraver, a gentle reminder on the logs I shared. Please do let me know if anything else is required from my end.

**Comment by NickCraver** [comment]
@KarthikHebbarMN It looks like those endpoints aren't there, I did notice though your port is `:6739`, whereas the default Redis port is `:6379`, perhaps some number got swapped in your config?

**Comment by KarthikHebbarMN** [comment]
> @KarthikHebbarMN It looks like those endpoints aren't there, I did notice though your port is `:6739`, whereas the default Redis port is `:6379`, perhaps some number got swapped in your config?

Hey @NickCraver , thanks for getting back with such patience. Haha looks like such a trivial issue. Damn I had remembered mapping correctly, guess I made a mistake. 
I got it working by spinning up a new container.
Seriously such a trivial error (face palm) 
Thank you for your support and patience.

**Comment by NickCraver** [comment]
Glad you're up and running - closing out!
