### ISSUE TITLE
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. Timeout

### ISSUE THREAD

**Issue by apixu** [StackExchange/StackExchange.Redis#238]
My .Net app is hosted on AWS and uses ElasticCache and has been working fine for weeks now. But today it has started giving error:

StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. Timeout

Please help.

**Comment by aliostad** [comment]
Same here. Happened twice.

**Comment by NickCraver** [comment]
This was resolved back in the 1.2.x changes - closing out to cleanup.
