### ISSUE TITLE
Redis timeout much longer than configured

### ISSUE THREAD

**Issue by shayfroid** [StackExchange/StackExchange.Redis#2388]
I'm using Redis for  Login rate limit on some critical path. 
The requirement is for a strongly enforced timeout.
Running with configuration of 250ms for both sync and async operations, I end up getting the timeout exception 3-4X times the configured timeout. 

For example (with 100ms configured timeout): 
**Timeout awaiting response (outbound=0KiB, inbound=0KiB, 1016ms elapsed, timeout is 100ms)**
The elapsed 1016 ms corresponds with my external measurements. 

Is that an expected behavior? 
If so, Is there a way to enforce timeout on the client side? (I know how to do it myself with Cancellation token + timeout, asking if there is an already supported way in the library).

**Comment by NickCraver** [comment]
By default we evaluate client timeouts once per second, during the heartbeat. If you want that to happen more often (in exchange for _some_ CPU, since it's executing more things per unit of time), you're looking for `ConfigurationOptions.HeartbeatInterval`, available in 2.6.66+.

**Comment by NickCraver** [comment]
Closing this out to tidy up since answered above :)
