### ISSUE TITLE
Exception thrown when using RedisDatabase.KeyExpireTime() method

### ISSUE THREAD

**Issue by srichmond3000** [StackExchange/StackExchange.Redis#2389]
I'm trying to use the RedisDatabase.KeyExpireTime method but get this error:
`StackExchange.Redis.RedisServerException: ERR unknown command `PEXPIRETIME`, with args beginning with: `selina-access-token``

The code I'm using is this:
```
public DateTime? GetKeyExpireTime(string key)
 {
       return Cache.KeyExpireTime(key, CommandFlags.None);
 }
```

and I'm calling it with the 'selina-access-token' arg.
Setting the key with a value via the StringSet method works fine.

Do you know what might be happening?

**Comment by slorello89** [comment]
@srichmond3000 - the `EXPIRETIME` command was introduced in Redis 7, so if you are not on Redis 7+, this will not work (seems to be what this indicates). If you cannot upgrade Redis versiosn, you're better off using `KeyTimeToLive` instead.

**Comment by srichmond3000** [comment]
I’ve realised we’re using AWS ElastiCache and our Redis version is 6.2.6.
So we need to upgrade it. Thanks for the rapid response.

**Comment by NickCraver** [comment]
Closing out to tidy up - thanks @slorello89!
