### ISSUE TITLE
Small Object Heap: code that allocates a lot of memory in SOH

### ISSUE THREAD

**Issue by ht-s-fog** [StackExchange/StackExchange.Redis#2391]
Translation: "As StreamReadGroup does not support blocking data reading, I have to use while(true) {} to read data, which will result in the following problems."

![WX20230302-232406@2x](https://user-images.githubusercontent.com/90367039/222472542-6faf8406-ba8c-41fe-85b3-e3febb69c39b.png)

“Small Object Heap: code that allocates a lot of memory in SOH”  is an unstable factor, how can I solve this problem?

**Comment by mgravell** [comment]
Are you in a tight loop without any delays? Because, sure that will allocate - maybe add a pause?

**Comment by ht-s-fog** [comment]
My requirement is that messages are processed promptly, so adding delays arbitrarily is not acceptable as it may lead to unexpected issues.

**Comment by NickCraver** [comment]
@ht-s-fog This isn't a scenario we support today, you can keep an eye on #1961, but we have no planed work/ETA there.

**Comment by NickCraver** [comment]
Closing out since #1961 is tracking blocking
