### ISSUE TITLE
Redis subscriber being called twice or more when publishing messages

### ISSUE THREAD

**Issue by YagoBiermann** [StackExchange/StackExchange.Redis#2394]
Hello there! I'm facing an odd behavior with the pub/sub, when I'm using the subscriber inside a worker it's always being called multiple times, one thing I noticed is that everytime I start the server, two clients are connected, but I couldn't figure out why this is happening.

That's the minimal reproducible code I've made
```
// Program.cs
using redisTest;
using StackExchange.Redis;

IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
        services.AddSingleton<IConnectionMultiplexer>(sp =>
        ConnectionMultiplexer.Connect("localhost:6379,abortConnect=False"));
        services.AddHostedService<Worker>();
    })
    .Build();

host.Run();

```

```
// Worker
using StackExchange.Redis;

namespace redisTest;

public class Worker : BackgroundService
{
    private readonly ILogger<Worker> _logger;
    private readonly IConnectionMultiplexer _services;

    public Worker(ILogger<Worker> logger, IConnectionMultiplexer services)
    {
        _logger = logger;
        _services = services;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
        while (!stoppingToken.IsCancellationRequested)
        {
            _services.GetSubscriber().Subscribe("Channel1").OnMessage(channelMessage =>
            {
                Console.WriteLine((string)channelMessage.Message);
            });

            await Task.Delay(5000);
        }
    }
}
```
### 

**The two clients highlighted in red are those that were created when the server was started.**

![CLI redis stack](https://user-images.githubusercontent.com/55931376/222854206-bb60d0c0-54b9-4ed7-a5a7-24624091fc88.png)

### 
**Something I noticed is that the longer the delay between each published message, the more times the subscriber runs.**

![messages](https://user-images.githubusercontent.com/55931376/222854741-ed2b1859-1703-4aa5-a998-6b6dab99854e.png)

I'll leave here the zip with the example in case you need to run in your machine.

[example.zip](https://github.com/StackExchange/StackExchange.Redis/files/10886955/example.zip)

I'm using the redis-stack container for development, so just run the command: `docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest`

Thanks for your time, in advance!

**Comment by NickCraver** [comment]
I'm trying to understand your example - the code is calling subscription and adding a new handler, in a loop, so yes we would expect it to add an _additional_ writeline per run, e.g. 1 for messages received in the first 5 seconds, 2 in the next 5, 3 in the next 5, etc. But it's unclear without timestamps what you're seeing vs. expected.

The 2 clients being connected is 2 connections from StackExchange.Redis, 1 for pretty much everything but subscriptions, and 1 for subscriptions.

**Comment by YagoBiermann** [comment]
Ok, now I got it... In the [worker docs](https://learn.microsoft.com/en-us/dotnet/core/extensions/workers), they include this loop per default, even when creating a new project, so I thought it was needed to keep the worker running, but I was wrong, my bad.
