### ISSUE TITLE
ConnectionRestored doesn't work when ConnectionMultiplexer.Connect

### ISSUE THREAD

**Issue by redondance** [StackExchange/StackExchange.Redis#24]
Normally, the muxer.ConnectionRestored is null when connection established.

ex:
var muxer =  ConnectionMultiplexer.Connect(...);
// has connected, but now muxer.ConnectionRestored doesn't be set
// then
muxer.ConnectionRestored += myConnectedFunc;

**Comment by NickCraver** [comment]
Closing this out...because we've no clue what "this" is.
