### ISSUE TITLE
error CS1545: Property, indexer, or event 'ConfigurationOptions.EndPoints' is not supported by the language; try directly calling accessor methods 'ConfigurationOptions.get_EndPoints()' or 'ConfigurationOptions.set_EndPoints(?)'

### ISSUE THREAD

**Issue by PandurangShinde2018** [StackExchange/StackExchange.Redis#2401]
error CS1545: Property, indexer, or event 'ConfigurationOptions.EndPoints' is not supported by the language; try directly calling accessor methods 'ConfigurationOptions.get_EndPoints()' or 'ConfigurationOptions.set_EndPoints(?)' 

 EndPoint endPoint = ConfigurationOptions.EndPoints[0];

**Comment by PandurangShinde2018** [comment]
After updating StackExchange.Redis we are geeting above issue

**Comment by mgravell** [comment]
The issue here is that at some point we added an `init` setter on `ConfigurationOptions.EndPoints`; unfortunately, this has a "modreq" that is only understood by C# 9 compilers (and above), so: something from Nov 2020 onwards.

The "fix" here is to update your build tools.

**Comment by bevanshaw** [comment]
@mgravell can you explain the fix further and will this work if running an ASP.NET solution on Visual Studio 2017? I hit this same issue migrating a .NET Framework solution from 4.5.2 to 4.8.1

**Comment by mgravell** [comment]
this is a *compiler version* thing; it *might* be enough to just add `<LangVersion>9.0</LangVersion>` in the csproj, if you're using a new-style (SDK) project file. IIRC the IDE tends to insist that the language version is tied to the framework version (which simply isn't true, although it is a pragmatic and simple approach, and I understand why they do it) - but you can *usually* bypass the IDE's ideas

**Comment by bevanshaw** [comment]
I am now running on Visual Studio 2022 which resolved this for me.

**Comment by NickCraver** [comment]
Closing out to tidy up - glad you're up and running!
