### ISSUE TITLE
move to .NET 7 -> more timeouts

### ISSUE THREAD

**Issue by pianoman4873** [StackExchange/StackExchange.Redis#2403]
Hello, 
After moving from .NET 5 to .NET 7 we are encountering more timeouts on the Redis client.
We're using version 2.6.90.
Since there have been some code changes along the switch , I'm not sure the culprit is Redis, but based on your knowledge of the changes made in .NET 7 ( maybe particularly in the threading department) - are there any recommendations for tweaking any of the configurations of the client to suit more the .NET 7 platform?

Thanks !

**Comment by NickCraver** [comment]
There isn't anything inherent here to a move (no behavior change for us), but if you posted some of the timeout exceptions we may be able to provide some suggestions :)

**Comment by NickCraver** [comment]
Absent any more information here - nothing to advise on, closing out to tidy up. Happy to re-open if there's a specific error/question though!
