### ISSUE TITLE
Are RedisTimeoutException error codes documented somewhere ?

### ISSUE THREAD

**Issue by Veverke** [StackExchange/StackExchange.Redis#2404]
I have been searching in the docs and online in general but could not find a place where the meaning of error codes of flags in RedisTimeoutException error messages are explained in detail.

When I talk about error codes/flags, I mean these abbreviated words singled out in bold, in timeout exceptions such as:

Timeout performing XCLAIM (5000ms), next: XCLAIM, **inst**: 0, **qu**: 0, **qs**: 3, **aw**: False, **bw**: SpinningDown, **rs**: TryParseResult, **ws**: Idle, **in**: 5919075, **in-pipe**: 19144704, **out-pipe**: 0, serverEndpoint: redis:6379, **mc**: 1/1/0, **mgr**: 8 of 10 available, clientName: 7ad494236e3a(SE.Redis-v2.5.61.22961), **IOCP**: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767), POOL: (Threads=9,QueuedItems=0,CompletedItems=27880), v: 2.5.61.22961

The closest I could find was:
1. [MGET error message codes](https://azure.microsoft.com/en-us/blog/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/). I understand each different command may have different codes/flags reported, so I am missing some for my XCLAIM
2. [General Redis client troubleshooting](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-troubleshoot-client) 
3. [Timeout troubleshooting](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-troubleshoot-timeouts)
4. Stackoverflow answers such as [this](https://stackoverflow.com/a/47568523/1219280)

I have been browsing through the source code, places such as `RedisDatabase.GetStreamClaimMessage` and `ConnectionMultiplexer.ExecuteSyncImpl`, but could not reach answers yet

Can I find these codes/flags documented somewhere?

**Comment by NickCraver** [comment]
Yes, the end of that error message should literally contain the link to https://stackexchange.github.io/StackExchange.Redis/Timeouts - if you're getting cut off at that point, it's possible your text for errors is getting truncated overall.

**Comment by Veverke** [comment]
@NickCraver , no I get the full error message including the link you mentioned (which I should obviously have mentioned as part of the relevant links), I just cropped the message for brevity/clarity.
I could not find there, either, a detailed explanation on those codes/flags as well.

**Comment by NickCraver** [comment]
@Veverke There's a table of them in the page... https://stackexchange.github.io/StackExchange.Redis/Timeouts#explanation-for-abbreviations-appearing-in-exception-messages - am I totally misunderstanding your question here?

**Comment by Veverke** [comment]
Nope, you totally got it right, and I somehow missed this (although seeing it now feels the table is familiar. I must somehow have dismissed this document as "I already read this and did not help" - wrongly.

Thank you. Closing
