### ISSUE TITLE
ServerMaintenanceEvent not properly fired

### ISSUE THREAD

**Issue by DarthSonic** [StackExchange/StackExchange.Redis#2405]
We received NodeMaintenanceEnded event for an "IsReplica" server today. Problems are that we a) did not get any NodeMaintenanceScheduled, NodeMaintenanceStarting and/or NodeMaintenanceStart event and b) we do not have any replica server set up, only primary server. 

And if there was a replica started, due to primary server going down for maintenance, where is the NodeMaintenanceFailoverComplete event when (new) replica (that we do not have at all) switches to primary?

This feature is practically useless if we do not get all the events in the maintenance pipeline. All we can do is log those events for information if we cannot rely on them.

Is there something more we need to do on Azure side to get all that events?

**Comment by mgravell** [comment]
@philon-msft maybe?

**Comment by DarthSonic** [comment]
Well, in your defense, I have to say that Azure had a problem with the Azure Redis Cache yesterday. Perhaps that's why Azure did not fully run the processes.

Nevertheless, after fixing the problem, "NodeMaintenanceScheduled" events were fired several times, but without any maintenance being started at the time mentioned. But I cannot blame you for that either.

I am watching the issue and will let you know if any irregularities occur during "regular operation".

Nevertheless, it would be good to know if there are still things to be adjusted on the part of the developer to receive the proper events. Or at least to get confirmation that this is not necessary ;-)

**Comment by philon-msft** [comment]
Yes it sounds like you were impacted by the issue with the Azure Cache for Redis service last week. One of the side effects of the issue would be unusual behavior in the maintenance notifications. No changes are needed on your end - notifications should return to normal now. 

Out of curiosity, could you tell us more about the actions you take in response to the maintenance notifications received?

**Comment by DarthSonic** [comment]
If there is a maintenance about to start, we set this as an internal status of our app and bypass Redis Cache until the maintenance ends. This is to prevent exceptions caused by force close of connection and to prevent timeouts. Users do not have to wait some seconds before using fallback if Redis is not available. We can serve the fallback at once without waiting for Redis timeout or without looking if Redis is available.

Also, if we would start to use a replica, we could bypass storing data to Redis (or maybe delay those writes), but still read data from Redis.

**Comment by DarthSonic** [comment]
Here are the events of this weekend's regular maintenance window:

Sat, 18 Mar 2023 02:02:42 GMT => NodeMaintenanceStarting (**IsReplica = true**)
Sat, 18 Mar 2023 02:03:02 GMT => NodeMaintenanceStart (**IsReplica = true**)
Sat, 18 Mar 2023 02:17:48 GMT => NodeMaintenanceEnded (**IsReplica = true**)
Sat, 18 Mar 2023 02:20:06 GMT => NodeMaintenanceStarting (IsReplica = false)
Sat, 18 Mar 2023 02:20:26 GMT => NodeMaintenanceStart (IsReplica = false)
Sat, 18 Mar 2023 02:37:32 GMT => NodeMaintenanceEnded (**IsReplica = true**)

- I still do not know why those events with IsReplica are fired. We still do not have any replica set up, as we are running on "Standard" tier, where clustering or replication is not available.
- The last event should have been NodeMaintenanceEnded with IsReplica = false cause at this point primary must have come up again. Otherwise there must have been some NodeMaintenanceFailoverComplete event.

**Comment by philon-msft** [comment]
Thanks for the detail - it's great to hear about such a robust integration with maintenance events. 

Your Standard tier cache actually does include a replica (and a primary) node internally to maintain availability and preserve cache data during planned maintenance events. You can find a description of the system [here](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-high-availability#standard-replication-for-high-availability). 

NodeMaintenanceEnded events reporting IsReplica=true is expected, because by the time maintenance on a node is complete it's expected that the impacted node has been demoted to the replica role (if it wasn't already operating as the replica). The non-impacted node will be running as primary to maintain cache availability during the maintenance.

**Comment by DarthSonic** [comment]
Thanks for these explanations!
