### ISSUE TITLE
Deadlock while awaiting Task from Database using disposed/closed ConnectionMultiplexer

### ISSUE THREAD

**Issue by tinix0** [StackExchange/StackExchange.Redis#2412]
Hi, I ran into the following situation. When having connection issues, closing or disposing the ConnectionMutex can cause some in flight requests to not cancel or timeout. 

We've discovered this, because we have some convoluted connection restoration logic in our microservices that tries to throw away the multiplexer if there are too many failed requests and sometimes this logic causes the service to become stuck, because redis calls do not return.

I have reduced the issue to this minimal example: 
```cs
ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost");
var db = redis.GetDatabase();
var result = db.StringSetAndGetAsync("a", "b", null, When.Always, CommandFlags.None); // Breakpoint here and stop the redis server, then resume  the program
redis.Close();
Console.WriteLine(await result.ToString()); // Hangs forever
```

I would expect the await to throw in this situation, not to hang.

**Comment by NickCraver** [comment]
A fix for this is now available in https://www.nuget.org/packages/StackExchange.Redis/2.6.104 (currently unlisted) if anyone wants to grab it early
