### ISSUE TITLE
Azure Cache is forcing everyone to Redis 6

### ISSUE THREAD

**Issue by ShaneCourtrille** [StackExchange/StackExchange.Redis#2421]
I noticed this change was done in the past "Change: Update assumed redis versions to v2.8 or v4.0 in the Azure case ([#1929 by NickCraver](https://github.com/StackExchange/StackExchange.Redis/pull/1929))" and wanted to point out that MS is moving all Azure Cache instances to [Redis 6 on June 30th ](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-whats-new#upgrade-your-azure-cache-for-redis-instances-to-use-redis-version-6-by-june-30-2023) in case there was any value in a similar change based off that once the move is completed.

**Comment by mgravell** [comment]
Yup; we work very closely with @philon-msft, and I'm confident that we'll get this applied promptly when it is appropriate to do so

**Comment by NickCraver** [comment]
Closing this out to tidy up - when Azure is 100%+, we will change the default here :)
