### ISSUE TITLE
wont work on .NET 4.6.1 web api

### ISSUE THREAD

**Issue by gjhdigital** [StackExchange/StackExchange.Redis#2422]
Hello, after installing v2.6.104 (I tried all the way back to v2.2.4 too. )on my .NET 4.6.1 web api im getting this error. Any help would be greatly appreciated.

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'System.Web.Http.GlobalConfiguration' threw an exception.

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by NickCraver** [comment]
Hey there - we don't do anything related to this library at all, but based on past experience I'd be looking at your binding redirects and see if you're _over_ redirecting (a lot of this is solved targeting 4.7.2+ if that helps). I wrote up a bit about why this happens here: https://nickcraver.com/blog/2020/02/11/binding-redirects/

**Comment by gjhdigital** [comment]
Thank you for your fast reply. Im actually moving this project to .net 6.0 since its so small.

**Comment by NickCraver** [comment]
That's an awesome call - the entire category of problem goes away there :)

**Comment by NickCraver** [comment]
Closing out to tidy up!
