### ISSUE TITLE
Redis server get stuck when client throw exception 

### ISSUE THREAD

**Issue by engmustafak26** [StackExchange/StackExchange.Redis#2436]
When send a heavy "GetStringAsync" to retreive  (large base64 string) concurrent requests to redis server and timeout exception occurs, then the client and server demonstrate degrade in performance. 

While, if I increase SynTimeout to overcome timeout exception, things go well

**Comment by engmustafak26** [comment]
I faced this exception:

StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=2723KiB, 5500ms elapsed, timeout is 5000ms), command=HMGET, next: HMGET NWCApi_ProfilePicture-192022, inst: 0, qu: 0, qs: 7, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: 10.68.140.75:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: SERVER, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=4,Free=32763,Min=8,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

note: the issue is resolved when increase SyncTimeout

**Comment by mgravell** [comment]
Again, how big is the data? This seems to be timing out after 2.7MiB which isn't huge, but: how big is the image? What other load is there? We can't tell what this means without context, other than saying *something* didn't happen fast enough.

**Comment by engmustafak26** [comment]
Actually images size range from 217kb to 450kb.

The execution context as follow:
1. Set one image as base64 string
2. Set 5 keys with body load 12kb json array for each
3. Read one image

This are the whole concurrent requests happens when frontend user access his profile page,

Note: if I set some delays between concurrent requests to make it sequential, requests success and never throw timeout exception which hanging client also the redis server too. 

Or I increase SynTimeout, problem is solved

I test redis server hanging problem by redis-insight v2 (e.g. another redis client)  when nuget throw exception

**Comment by NickCraver** [comment]
I'm looking at the timeout here and it's an HMGET, are you fetching multiple images at once?

In any case, you'll want to upgrade to a much newer version (latest preferably) which has greatly improved logging giving a better idea of where things are stuck at especially for timeouts.

**Comment by engmustafak26** [comment]
Thanks for your support, Nick
The problem was in Total memory assigned to Redis instance, I increased it and every thing goes well
