### ISSUE TITLE
Two Redis Services are not working in MS Azure Portal

### ISSUE THREAD

**Issue by adviknjadhav** [StackExchange/StackExchange.Redis#2446]
We have two Redis cache instances for webapi on same MS azure resource group and it uses same code for two instances like QA1 environment and QA2 environment(webapi). So we created two instances of redis in same resource group like redis 1 fo QA 1 and redis 2 for QA2. 
Now issue is it's generating keys only for QA1 redis and not generating for QA2. As I mentioned both are using same code base and different redis connection string but still it is not working. 

Can someone help on this?

**Comment by mgravell** [comment]
@philon-msft ^^^ ?

**Comment by NickCraver** [comment]
Closing out since this is a platform issue rather than a client one.
