### ISSUE TITLE
 Timeout performing GET (5000ms) Redis-v2.6.90.64945

### ISSUE THREAD

**Issue by SimonS1988** [StackExchange/StackExchange.Redis#2455]
Hi, we use this version for a while, and in the last few weeks we are getting a lot of errors like this:

Exception:StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL (5000ms), next: EVAL, inst: 1, qu: 0, qs: 190, aw: False, bw: SpinningDown, rs: TryParseResult, ws: Idle, in: 65536, in-pipe: 1126630, out-pipe: 0, last-in: 0, cur-in: 24039961, sync-ops: 4370147, async-ops: 0, serverEndpoint: ***:6379, conn-sec: 514839.62, mc: 1/1/0, mgr: 4 of 10 available, clientName: ***(SE.Redis-v2.6.90.64945), IOCP: (Busy=2,Free=798,Min=400,Max=800), WORKER: (Busy=58,Free=742,Min=400,Max=800), v: 2.6.90.64945 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

We had no code change, but our usage increased slightly. The server almost falls asleep (5% of CPU).

Does anyone have any idea?

**Comment by SimonS1988** [comment]
Thank you Nick!
We assume that most of our usage is done by the "Microsoft.Web.RedisSessionStateProvider"(4.0.1) package, is there a way to force the package to work asynchronously?
Thank you!

**Comment by philon-msft** [comment]
@SimonS1988 currently the Microsoft.Web.RedisSessionStateProvider uses only synchronous code paths, but we're working on improvements to enable async. Feel free to create an issue in that repo to track: https://github.com/Azure/aspnet-redis-providers

**Comment by NickCraver** [comment]
Closing out since this is an upstream issue - nothing for the client to do in this case.
