### ISSUE TITLE
Subscriber events never get raised on Mono

### ISSUE THREAD

**Issue by ghost** [StackExchange/StackExchange.Redis#246]
ISubscriber.Subscribe() does not appear to raise events when running under Mono. 

Very basic program to demonstrate: 

``` C#
var connection = ConnectionMultiplexer.Connect("redis-host");
var subscriber = connection.GetSubscriber();
subscriber.Subscribe("helloworld",
    (channel, value) => Console.WriteLine("Channel: {0}, Value: {1}", channel, value));

Console.WriteLine("Listening");
Console.ReadKey(); 
```

When compiled and run on Windows using VS2013, we get events for messages published to "helloworld".  
Take that compiled assembly and run it on Mono, using a Mono-compiled StackExchange.Redis lib - no events. 
Compiling the application on Mono doesn't change things either. 

In all cases, we can see the client running Subscribe for "helloworld", but it's only mono that doesn't display any events. 

Any suggestions or advice? 

Mono version: 4.0.2.5 (Centos7 packages)  
StackExchange.Redis version: Current master as of this ticket's date.

**Comment by NickCraver** [comment]
Tagging for #314 - we want to run the full test suite under Mono and find all the issues like this that exist.

**Comment by NickCraver** [comment]
Latest master branch now works in Mono, including this :) Note there are bugs in 5.12, but works fine on 5.10.1.47.

No special build is needed anymore, the `net46` DLLs *just work* here, and will in the next NuGet release.
