### ISSUE TITLE
GEOPOS of missing key is returning (0,0) instead of marking hasValue flag to false

### ISSUE THREAD

**Issue by incloudss** [StackExchange/StackExchange.Redis#2460]
Is this intended behaviour? Because it's quite counter-intuitive. I expected the hasValue getter to return false if there is not position stored for given key, but to my suprise, it returned 0 lat 0 long.

**Comment by NickCraver** [comment]
Do you have a repro example of this? We have tests around this behavior and I just verified even simplified they do as expected:
```cs
    [Fact]
    public void GeoGetPositionMissing()
    {
        using var conn = Create(require: RedisFeatures.v3_2_0);

        var db = conn.GetDatabase();
        RedisKey key = Me();
        db.KeyDelete(key, CommandFlags.FireAndForget);

        var pos = db.GeoPosition(key, "Nowhere");
        Assert.False(pos.HasValue);
    }
```

**Comment by NickCraver** [comment]
Need more info to assist further here - closing out to tidy up.
