### ISSUE TITLE
SentinelConnect does not fall back to 'INFO replication' if 'ROLE' is not supported by server

### ISSUE THREAD

**Issue by Kilowhisky** [StackExchange/StackExchange.Redis#2461]
HI,

I have a situation where i'm attempting to use `StackExchange.Redis` library with a Redis based server that does not support the `ROLE` command but does support `INFO replication`. 

According to the Sentinel spec, clients are supposed to drop to `INFO replication` if the `ROLE` command is not present.
 
https://redis.io/docs/reference/sentinel-clients/
>If the [ROLE](https://redis.io/commands/role) commands is not available (it was introduced in Redis 2.8.12), a client may resort to the INFO replication command parsing the role: field of the output.

The issue is this line here: 
https://github.com/StackExchange/StackExchange.Redis/blob/ae6419a164600b4b54dd7ce8a699efe8e98d8f1c/src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs#L236

It should be a try catch with the fallback to `INFO replication`.

**Comment by NickCraver** [comment]
Are you trying to connect to a Redis server that predates 2.8.12 or...? Figuring out what role an instance is happens way early, it's very non-trivial to change how handshake works so just to set expectations: is probably unlikely we'll fix this scenario, but let's figure out _why_ you're hitting this first. Why isn't ROLE available for your case?

**Comment by Kilowhisky** [comment]
In this situation, i'm not technically using a Redis server but a [Tile38](https://tile38.com/) server which supports a subset of Redis commands. 

https://tile38.com/topics/client-libraries#:~:text=C%23%3A%20StackExchange.Redis

I guess i need to create an issue on their side to get that command supported.

**Comment by NickCraver** [comment]
@Kilowhisky Okay I got a look at this local, it's far more isolated than other handshake code that's much harder to change. What happens when you run this against a server? I don't have a test case here so...need more info. Does it error? Have an example?

**Comment by Kilowhisky** [comment]
It errors out, and in my case crashes the app. 

I was starting to work on a fork but ran out of time today. Very rough fix would look something like this. 
```
// verify role is primary according to:
            // https://redis.io/topics/sentinel-clients
            try
            {
                if (connection.GetServer(newPrimaryEndPoint)?.Role()?.Value == RedisLiterals.master)
                {
                    success = true;
                    break;
                }
            } catch (RedisServerException e) when (e.Message == "ERR unknown command 'ROLE'") {
                if (connection.GetServer(newPrimaryEndPoint)?.Info("replication")
                    ?.FirstOrDefault(x => x.Key == "replication")
                    ?.FirstOrDefault(x => x.Key == "role").Value == RedisLiterals.master)
                {
                    success = true;
                    break;
                }
            }
```

There are two places that `Role()` is used to check if its master or not. Both could be replaced with a call like this.

**Comment by NickCraver** [comment]
@Kilowhisky if you have the client running and a test server, let's try a much simpler change please:
```diff
- if (connection.GetServer(newPrimaryEndPoint)?.Role()?.Value == RedisLiterals.master) 
+ if (connection.GetServer(newPrimaryEndPoint)?.IsReplica == false)
```

We're _already_ parsing INFO as part of our handshake earlier, so let's just take advantage and remove a roundtrip at the same time. This works in all tests here, but I'd appreciate confirmation against your crazy server :)

**Comment by Kilowhisky** [comment]
I can confirm that making this change works against my Tile38 server. 

 If you really want to match the spec though, you probably have to do the whole `try {} catch {}` bit.

**Comment by NickCraver** [comment]
We don't need to match the spec here - it's the same information. The instructions are really about "make sure this is a primary"...and we're doing that, in the most compatible way possible. They recommend ROLE because that's easier to implement, but we're already parsing for other reasons so that's not a win :)

I'd love to give credit for this, any chance you want to do a PR with that line change to make that happen? If not happy to PR and reference the issue, just let me know :)

**Comment by Kilowhisky** [comment]
Well good news, the maintainer of Tile38 has said they will integrate the ROLE command. 

I feel like this is a better closure of the issue than modifying this library.  

If something changes in the future i will create a PR for it.
