### ISSUE TITLE
Timeout Exception in stackexchange version 5.0.1

### ISSUE THREAD

**Issue by shanqq** [StackExchange/StackExchange.Redis#2468]
No connection is available to service this operation: HMGET somevalue It was not possible to connect to the redis server(s). To create a disconnected multiplexer, disable AbortOnConnectFail. ConnectTimeout; IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=2,Free=1021,Min=1,Max=1023), Local-CPU: n/a It was not possible to connect to the redis server(s). To create a disconnected multiplexer, disable AbortOnConnectFail. ConnectTimeout

**Comment by NickCraver** [comment]
So...we're at version 2.6.111, and that's the latest. I'm not sure which version of what 5.0.1 library you're using, but given the exception message I can at least tell it's using a very, very old version of StackExchange.Redis underneath. I'd suggest upgrading to our latest and seeing if you still have issues.

**Comment by shanqq** [comment]
I upgraded but still i am facing this issues .No connection is active/available to service this operation: HMGET somevalue* ; It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to
 connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code. ConnectTimeout, mc: 1/1/0, mgr: 10 of 10 available, clientName: dw1sdwk0012JW, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=2,Free=1021,Min=1,Max=1023),
 v: 2.2.4.27433

**Comment by shanqq** [comment]
I dont know but the exception comes in the health endpoint

**Comment by NickCraver** [comment]
@shanqq I don't have any more information available to answer your question. You have a configuration problem somewhere and sans any more info, I can't even guess where that is. It's like asking why you can't connect to some internal website...we'd have no idea. Could be firewall. Could be auth. Could be SSL config. Could be you have the address wrong. Could be _anything_ about 2 machines talking to each other.

**Comment by NickCraver** [comment]
Can't advise more here without more info - closing out.
