### ISSUE TITLE
Can StackExchange.Redis insert Null redisvalue to Hash? 

### ISSUE THREAD

**Issue by julyice** [StackExchange/StackExchange.Redis#2469]
when I write Hash key and value(null) to redis, it always report Null Error. 

```
            RedisValue rv = RedisValue.Null;
            List<HashEntry> arr = new List<HashEntry>();
            arr.Add(new HashEntry("Key1", rv));
            redis.HashSet("Test",arr.ToArray());
```

Exception message:
{"A null value is not valid in this context"}

if I write HashEntry with non-null RedisValue to redis, no exception is reported. 
if I use `redis.HashSet("Test", "key2", RedisValue.Null);` ,  no exception is reported, but keys is not inserted to redis. 

Thanks.

**Comment by mgravell** [comment]
That's not a thing redis can store. Now, you could argue that we should
interpret null as HDEL, but: that would be inconsistent with most redis
usage (and there would be no way of supporting it in HMSET usage), so: we
don't do that. A hash value must either not exist, or have a non-null value.

**Comment by julyice** [comment]
thanks mgravell's clarification.
