### ISSUE TITLE
custom condition within transaction

### ISSUE THREAD

**Issue by leslietoo** [StackExchange/StackExchange.Redis#247]
I want to add some conditions within a transaction like when a Set/OrderedSet/List contains some value, or when Set/OrderedSet/List/HashSet's length is 0(or 1,2, whatever). But there were only few predefined Condition like HashEqual, HashNotEqual, HashExists, HashNotExists, KeyExists, KeyNotExists, StringEqual, StringNotEqual.  So what can I do? Can I realized a custom condition?

**Comment by mgravell** [comment]
At the moment, you would need to change the source to do this. I haven't
figured out a way of making this API more general without introducing the
risk of allowing external code to accidentally stall the dedicated worker
thread that is fielding this. I'm sure a few more would be plenty welcome
as a PR; but I might also ask: could it be done more conveniently in a Lua
script?

On 27 July 2015 at 08:01, leslietoo <notifications@github.com> wrote:

> I want to add some conditions within a transaction like when a
> Set/OrderedSet/List contains some value, or when
> Set/OrderedSet/List/HashSet's length is 0(or 1,2, whatever). But there were
> only few predefined Condition like HashEqual, HashNotEqual, HashExists,
> HashNotExists, KeyExists, KeyNotExists, StringEqual, StringNotEqual. So
> what can I do? Can I realized a custom condition?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/247>.
>



-- 
Regards,

Marc

**Comment by leslietoo** [comment]
I don't know anything about Lua, and I prefer to add these support in C#.
Would you please point out which source code I should keep my eyes on if I
want to add them by myself?

2015-07-27 23:16 GMT+08:00 Marc Gravell <notifications@github.com>:

> At the moment, you would need to change the source to do this. I haven't
> figured out a way of making this API more general without introducing the
> risk of allowing external code to accidentally stall the dedicated worker
> thread that is fielding this. I'm sure a few more would be plenty welcome
> as a PR; but I might also ask: could it be done more conveniently in a Lua
> script?
>

**Comment by leslietoo** [comment]
So, dear Marc, is it possible for me to add some classes to the source code so as to achieve my goal?

**Comment by NickCraver** [comment]
@leslietoo Following up on issues we didn't see replies to :( Is this still something you want to do? We often get one-time requests, to judging where to add them to the API or not is difficult until a similar request comes along, given that it never happened in this case, I'm not sure we'd put something like this in the library, now that lua exists in redis.

If you're still wanting to modify source, you'll want to look around in https://github.com/StackExchange/StackExchange.Redis/blob/ddabd9d5ac346bac8393de42d747021b5ad4a1bf/StackExchange.Redis/StackExchange/Redis/RedisTransaction.cs where transactions are today. Note they'd need to be added to the `IDatabase` (or `IDatabaseAsync`) interfaces for exposing.

**Comment by mgravell** [comment]
In principle: yes, conditions can be added. There is a reason they aren't exposed via a runtime pluggable API - specifically, the point when they would be to be called is in a critical region when we absolutely *do not* want to call into user code, as it could jam the pipe. If you have very specific scenarios, happy to consider them - #778 would be a great example of this. However, my recommendation for most day-to-day scenarios would be: use Lua instead.

Happy to consider specific condition scenarios to add to the code - as new issues, but for a general purpose caller-consumable API: I think the answer is a simple "no" (for the reasons above).
