### ISSUE TITLE
IndexOutOfRangeException for RedisResult.ToDictionary

### ISSUE THREAD

**Issue by giuliohome** [StackExchange/StackExchange.Redis#2472]
I'm trying a command `info = db.Execute("KEYS","*")` but getting` RedisResult.ToDictionary` throws the `IndexOutOfRangeException`

It should be an array of strings.

```csharp
using StackExchange.Redis;

var r = ConnectionMultiplexer.Connect("localhost:6379");

var db = r.GetDatabase();

var info = db.Execute("KEYS", new string[] { "*"});

var dict = info.ToDictionary();
```

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Messaggio=Index was outside the bounds of the array.
  Origine=StackExchange.Redis
  Analisi dello stack:
   in StackExchange.Redis.RedisResult.ToDictionary(IEqualityComparer`1 comparer)
```

However, the explicit operator is working fine

```
var dict = ((string?[]?)info);

foreach (var item in dict ?? Array.Empty<string>())
{
    Console.WriteLine("key  " + item);
}
```

**Comment by giuliohome** [comment]
fair enough,
fyi F# version would be

```fsharp
let getAll () : (string * RedisEmbedding) seq = 
   let db = getDB ()
   let info = db.Execute("KEYS","*") 
   let info_dict : string array = RedisResult.op_Explicit(info) 
```

**Comment by mgravell** [comment]
You should almost never issue `KEYS *`, and even if you used `SCAN`, this is a per-server operation not a global operation (this matters for "cluster"). There is an API on `IServer` to do what you want, more efficiently. Finally note that the result of `KEYS` *is not a dictionary* - it is a list/array of key names. It doesn't make sense to convert it to a dictionary, as a dictionary is a key/value pair mapping, and `KEYS` *does not return values*.

**Comment by giuliohome** [comment]
What do I want to do? I need to rebuild the keys of an index (it is coming from openai embeddings but that's irrelevant here). I've already done tbh, but I see it takes a few minutes, fwiw, I'm wondering why. It's running on a kubetnetes cluster.
Which api calls exactly would you suggest me to use? Btw the python version is really straightforward, but I'm struggling to bring .net F# to my team. All those op explicit converters didn't help much, but eventually it all worked... If there are simpler apis for index re-building, I would be more than happy to use them.

Thanks for your kind and helpful reply

**Comment by mgravell** [comment]
What *exactly* are you trying to do? "rebuild the keys and the values of an index" is incredibly vague. You mention hashes (`hgetall`, `hget`), but: `keys` has nothing whatsoever to do with hashes. Are you trying to get all the keys and values of a single hash, by key? If so: there are method for that - maybe `.HashGetAll(key).ToStringDictionary()` or similar?

**Comment by giuliohome** [comment]
This is what i see and i am doing, less vague than possible.

I have 500 embeddings vectors (with metadata) in my redis db.
If a issue one keys cmd is returns 500 strings.
For each of those 500 keys I can run a hgetall and it will return the metadata and the embeddings of that specific vector. That is triggered by a chatgpt api from azure from a user question but we don't care, this part can remain vague.
The fact is there there will be a knn query for similarity search.

Now I need to rebuild the whole index, because maybe I will have to insert 700 different vectors and metadata for next search.

But my point is that the "keys" call returns the list of the keys for which I can read metadata through hgetall or I can write metadata (and embedding 1536 float32/byte vector) through hset.

I'm not sure if there is something else I should call instead of "keys" but that is working at least as I have tried to describe above

**Comment by giuliohome** [comment]
This is what i see and i am doing, less vague than possible.

I have 500 embeddings vectors (with metadata) in my redis db.
If a issue one keys cmd is returns 500 strings.
For each of those 500 keys I can run a hgetall and it will return the metadata and the embeddings of that specific vector. That is triggered by a chatgpt api from azure from a user question but we don't care, this part can remain vague.
The fact is there there will be a knn query for similarity search.

Now I need to rebuild the whole index, because maybe I will have to insert 700 different vectors and metadata for next use searches.

But my point is that the "keys" call returns the list of the keys for which I can read metadata through hgetall or I can write metadata (and embedding 1536 float32/byte vector) through hset.

I'm not sure if there is something else I should call instead of "keys" but that is working at least as I have tried to describe above

**Comment by slorello89** [comment]
@giuliohome - if you are using redis as a vector database I'm assuming you are using RediSearch - you should just query the index with * as the query string- that will bring everything back for you.

**Comment by slorello89** [comment]
https://redis.io/docs/stack/search/reference/vectors/

Assuming you're using this?

**Comment by giuliohome** [comment]
Yes sure Research of course.
Will try the query *
Thanks but what about the building part?
Should I still do many hset - this is the slow part - and finally a FT.Create (this seems fast instead) ? No other high level .net wrappers here? Thanks again

**Comment by slorello89** [comment]
I'm pretty sure if you run the FT.CREATE - first the documents will be indexed synchronously as they are inserted - that's how it works with everything else in Search - but I'm not 100% sure on vectors. NRedisStack has some support for vectors - and I will probably add vectors to Redis OM when I get some bandwidth (we've piloted it in Redis OM Spring)

**Comment by giuliohome** [comment]
[Here in their docs](https://github.com/RediSearch/redisearch-getting-started/blob/master/docs/003-create-index.md#create-index)

 they write

> **Before** creating the index let's describe the dataset and **insert entries**.

and from my experience I remember my queries get the correct responses when the index is built after the vectors are inserted.

**Comment by Aeriewindows-services7** [comment]
@slorello89 https://pythondev.space/questions/can-a-string-be-generated-from-a-dictionarys-key-value-pair-in-python
