### ISSUE TITLE
Support for Microsoft.Extensions.Logging.ILogger in ConnectionMultiplexer

### ISSUE THREAD

**Issue by AmrutaMoghe** [StackExchange/StackExchange.Redis#2473]
Currently all the implementations of ConnectionMultiplexer accepts TextWriter as an optional input to print the logs while creating the multiplexer.
This is not compatible with .NetCore services using ILogger 
 Reference File - https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/ConnectionMultiplexer.cs#L650

Can ConnectionMultiplexer support ILogger with current implementation or enhanced to add the support?

**Comment by mgravell** [comment]
@NickCraver status/thoughts on https://github.com/StackExchange/StackExchange.Redis/pull/2051?

**Comment by NickCraver** [comment]
@AmrutaMoghe Would you mind taking a look at #2051, and seeing if that design covers what you need? Basically allows setting an ILogger on ConnectionOptions. I need to take a day and finish getting that in, but still cautious on if that's the right API design (should probably look at other similar libraries and confirm what they're doing...that's what I needed to spend some time digging on before we're locked in).

**Comment by AmrutaMoghe** [comment]
Yes would work, you can take a look at https://www.npgsql.org/doc/diagnostics/logging.html?tabs=console

**Comment by NickCraver** [comment]
Closing this out as completed in #2051 :)
