### ISSUE TITLE
Use Activity for profiling

### ISSUE THREAD

**Issue by WeihanLi** [StackExchange/StackExchange.Redis#2474]
Maybe we could consider using `Activity` for profiling so that it would be much easier to integrate tracing events.

Currently, if we want to use the OpenTelemetry to analyze the Redis profiling data, we had to reference another package to convert current profiler events to activities

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisConnectionInstrumentation.cs

And also `Activity` is recommended to support distributed tracing

- https://github.com/dotnet/designs/blob/main/accepted/2020/diagnostics/activity-improvements.md
- https://github.com/dotnet/designs/blob/main/accepted/2020/diagnostics/activity-improvements-2.md

**Comment by NickCraver** [comment]
We've discussed this quite a bit in #833 - you can see there why it's not supported in-box. If in the future this gets far cheaper we may revisit it, but it's unlikely to be the case for the foreseeable future.

**Comment by DavidParks8** [comment]
The Activity Api has received an upgrade after 2018 to more closely conform to the opentelemetry schema. If you don't want to use the DiagnosticSource apis, why not take a look at using the OpenTelemetry sdk directly? It is effectively just a wrapper on Activity that gives more structure and standardization in ways that may ease some of your concerns @NickCraver

**Comment by WeihanLi** [comment]
> That would require StackExchange.Redis to depend on OpenTelemetry

Actually not, we could depend on `Activity` only

**Comment by WeihanLi** [comment]
Sorry that I misunderstood that

**Comment by cijothomas** [comment]
> @DavidParks8 That would require StackExchange.Redis to depend on OpenTelemetry (which isn't a small dependency tree addition), and still take the weight of Activity (which isn't cheap) too. I agree it helps in one area, but hurts overall, especially for the vast majority of users getting no benefits and all the pain.

There is some misunderstanding here. To instrument for Tracing (Or metrics), the *only* dependency is on `System.Diagnostics.DiagnosticSource` only. (OTel .NET is somewhat special - it decided not to provide any tracing/metrics API, but instead recommends using DiagnosticSource directly).
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#introduction-to-opentelemetry-net-tracing-api
