### ISSUE TITLE
Redis client breaks on redis server error code=0x00000005 Problem creating slave process: permission denied. This causes the .NET app to crash

### ISSUE THREAD

**Issue by ankurmalhotra89** [StackExchange/StackExchange.Redis#2478]
We have a .NET Console application written in C# which is using StackExchange.Redis client library to make connections to a locally (on same server) hosted Redis. Below are the versions that I am using

Redis C# client : https://github.com/StackExchange/StackExchange.Redis
StackExchange.Redis.StrongName version 1.1.603

On premise hosted redis server (windows) : https://github.com/MicrosoftArchive/redis/releases -version 3.2.100

On few servers we are using the above setup, and it runs quite heavy loads but the RAM and CPU never chokes (so no resource crunch). Intermittently, we get the below error on the redis server logs

![image](https://github.com/StackExchange/StackExchange.Redis/assets/6507285/1cd00d67-3fd5-42d6-b695-e644db35b6f6)

This causes few of our services and running console applications to break with unhandled exception. So I have to restart the services and re run the jobs manually . Below is the snapshot of my configuration option

![image](https://github.com/StackExchange/StackExchange.Redis/assets/6507285/dcfc06b5-4634-478a-93f7-bb92a1222f94)

Are there any changes that I need to do within my application code or in the settings of the redis.windowsservice.conf file

**Comment by NickCraver** [comment]
This is a server-side error - we can't speak to that much and the thing you're using is definitely not maintained.

On the client side: please be aware you're using a client from over 5 years ago marked deprecated long ago. StackExchange.Redis (note: not .StrongName anymore - the base one is strong named) has gotten many, many improvements.
