### ISSUE TITLE
Some keys not being deleted

### ISSUE THREAD

**Issue by SilvandroOliveira** [StackExchange/StackExchange.Redis#2485]
We noticed that some keys that we defined the expiration time are not being deleted, and this situation occurs randomly and we still cannot identify the source of the problem, basically we define the key and the expiration time as follows:

```
await redis.StringSetAsync(index, listJson);
await redis.KeyExpireAsync(index, DateTime.UtcNow.AddMinutes(5));
```

Does anyone have any ideas what it could be and what we can do?

**Comment by mgravell** [comment]
If you send two discreet operations without any kind of batch, there's always a chance of a broken connection / process termination / whatever between the two, even if pipelined (which these aren't).

Fortunately, an atomic operation exists to do this in one go:

``` c#
await redis.StringSetAsync(index, listJson, TimeSpan.FromMinutes(5));
```

**Comment by NickCraver** [comment]
Answered above - closing out to tidy up.
