### ISSUE TITLE
Are new threads created in a sync way or async way?

### ISSUE THREAD

**Issue by ness001** [StackExchange/StackExchange.Redis#2491]
Context:
When the value of BUSY is much bigger than MIN and no threads free in 500ms
Question:
If I have a huge gap between BUSY and MIN,  will the client create threads concurrently by leveraging the multi-thread feature or we create threads one by one

**Comment by NickCraver** [comment]
Overall: we don't create any threads outside the SocketManager (default 10) at once and 1 for the backlog queue when that happens. The number you're referring to are the .NET thread pool used by everything, we only report on it because thread exhaustion is a _very_ common cause of timeouts of users and it helps us advise on that when issues are posted.

By default, the thread pool grows up to the min unconditionally, and then at ~500ms per new thread after the min is reached.

If you're seeing a ton of busy threads, it's likely some things that should be async are synchronous, using threads when there's no work to do (e.g. waiting on IO), or, more rarely: there is a ton of work overwhelming available CPU in which case nothing will help outside lowering the load or running it on beefier hardware. I'd say ~95% of the cases we see are the former: some things should be async.

Taking a memory dump when this happens can let you know what all those threads are doing/waiting on...and it may be extremely enlightening at some paths that, if async, can make things much better.

**Comment by ness001** [comment]
> Overall: we don't create any threads outside the SocketManager (default 10) at once and 1 for the backlog queue when that happens. The number you're referring to are the .NET thread pool used by everything, we only report on it because thread exhaustion is a _very_ common cause of timeouts of users and it helps us advise on that when issues are posted.
> 
> By default, the thread pool grows up to the min unconditionally, and then at ~500ms per new thread after the min is reached.
> 
> If you're seeing a ton of busy threads, it's likely some things that should be async are synchronous, using threads when there's no work to do (e.g. waiting on IO), or, more rarely: there is a ton of work overwhelming available CPU in which case nothing will help outside lowering the load or running it on beefier hardware. I'd say ~95% of the cases we see are the former: some things should be async.
> 
> Taking a memory dump when this happens can let you know what all those threads are doing/waiting on...and it may be extremely enlightening at some paths that, if async, can make things much better.

Thank you for the reply. Per the document, it said the implementation for 3.0 is we have a dedicated thread pool by default. Now my application is using that pool by default and the min is 24.
My question is:
1. Where does the number 24 come from?
2. When using dedicated pool, if busy is bigger than min, will the dedicated pool create new threads for the workload? If it will create new threads, then whether the threads are created one by one or by batch concurrently?

**Comment by ness001** [comment]
> Per which document, and what thing is 3.0? As Nick says: the only dedicated pool the library accesses is for IO work, and that _doesn't impact your code directly_ (and it never creates additional threads).
> 
> If you're hitting limits on the regular .net thread pool, then that strongly suggests you're doing unwise things like "sync over async", or excessive use of concurrent sync calls - considering using pure async may be useful. The .net thread-pool growth rate is outside of our control.
Thank you. Sorry, I mean 2.* version of this client. We are using the async interfaces all the time. 
<img width="937" alt="image" src="https://github.com/StackExchange/StackExchange.Redis/assets/5109598/594d8687-8218-467a-8f96-5e7dd6b5d917">


_the only dedicated pool the library accesses is for IO work, and that doesn't impact your code directly (and it never creates additional threads)._
I think I already get the answer. The dedicated pool will not create new threads even if the workload is too heavy for it. Then my question is
1. What's the default Min of the dedicated pool
2. If using dedicated pool and we can see BUSY is much larger than MIN, the best practice is to turn to .NET global Thread Pool and set our own Min?

**Comment by NickCraver** [comment]
@ness001 I'd propose you back up a bit here and start with a concrete problem like an exception message. The BUSY and MIN have nothing to do with the dedicated thread pool, that's reported as `mgr: 10 of 10 available`. The labels you're asking about are only for the .NET (**not us** thread pool).

If you have a timeout message, we can advise, that's what all the numbers are there for, so we can do just that. The current conversation is misinterpreting what most of these things are and likely not helping solve whatever the actual issue you're hitting is. Let's start with a concrete thing, it'll be far more productive to talk through that.

**Comment by ness001** [comment]
@NickCraver Sorry, I have already found a solution to my problem and I'm testing its stability. I'm asking here because I want to clarify some detailed mechanism that is not shown in the [documentation](https://stackexchange.github.io/StackExchange.Redis/Timeouts.html) and check whether my solution has some problems from the client developers' perspective.


First things first, I'm using version 2.6.66.
I don't specify the `SocketManager.Shared` in the Redis options so I suppose it's using the dedicated Redis pool.
I could spot hundreds of Redis timeout exception messages every day. I have done some math and found that in most of the cases we have Busy > Min in the IOCP pool. Mostly mgr is 9 out of 10. Per the document, it says `Redis Internal Dedicated Thread Pool State`.

Question:
1. What does 9 out of 10 mean? Does it mean the dedicated thread pool is not occupied?
2. I have Busy > Min, does it mean the application is also using the .NET thread pool for Redis tasks?
3. My solution now is to set the Min to 200 for IO thread pool and worker thread pool and set `SocketManager.Shared`. The problem is solved with a little decrease on performance. Is it a recommended solution to solve this case?

**Comment by mgravell** [comment]
`SocketManager.Shared` is the default if one is not specified, so: that isn't going to make any difference; the "9 out of 10" tells us that the socket manager pool isn't saturated and that isn't a problem, so: we can mostly forget that `SocketManager` exists

Busy > Min just means your system is doing something more than just idling, and needed some extra thread-pool threads; not necessarily a problem, although knowing what these numbers *are* might be helpful (there's a difference between "45 > 20" and "6123 > 20" (or whatever); you say that you "have a huge gap between BUSY and MIN" - to me, that suggests that your code is doing a lot of sync IO and/or sync-over-async, which are classic causes of increases in thread-pool size.

In reality, there's usually four things that are more interesting than everything else here:

1. how often are you *connecting to redis*? your connection (`ConnectionMultiplexer`) should be long-lived and heavily shared between concurrent callers; if you're connecting to redis over and over and over: expect bad performance
2. what do your calls to redis look like? are they sync? true async? sync-over-async? something else? can we see some example code?
3. what do your payloads look like? if you're constantly sending huge blobs, then sure: things might get blocked occasionally - that's just bandwidth limits
4. where is your redis server? "local private LAN" vs "hosted cloud server 200 miles away through 5 VPNs/gateways" makes a huge difference re latency (and, to some degree, bandwidth)

**Comment by ness001** [comment]
@mgravell Thanks for replying. My problem is already solved with the solution I mentioned above. The answers are
1) They are shared.
2) All the interfaces I use from stack exchange redis are async, as well as my wrapper. I couldn't share the code in case of potential leaking.
3) no huge blobs. Just small size strings.
4) Azure Redis
