### ISSUE TITLE
Need for multiple Redis ConnectionMultiplexer for each pub/sub subscription?

### ISSUE THREAD

**Issue by superastu** [StackExchange/StackExchange.Redis#2492]
Hi, 

I have a problem where I have to set up numerous connections to redis for each thread in order to subscribe to a specific channel. If I just use one, Unsubscribe frequently deletes every subscription from every thread. 

Is this behaviour normal, or am I overlooking something? 

What is the best way to manage many ConnectionMultiplexers in a solution if I need to construct them?

**Comment by NickCraver** [comment]
Without any code, I'm not sure we can help here. You can subscribe to many channels on a single multiplexer, with a handler for each - this is a common and intended use case. Unless you have a bandwidth starvation issue, I wouldn't recommend multiple multiplexers :)

**Comment by NickCraver** [comment]
@superastu You're using the `.UnsubscribeAsync(channel)` overload, without telling it _which thing_, so yes that unsubscribes _everything_. You need to pass in your action (the same passed to `.SubscribeAsync()` as the second argument to unsubscribe that specific action/handler only.

The full signature looks like this:
```cs
Task UnsubscribeAsync(RedisChannel channel, Action<RedisChannel, RedisValue>? handler = null, CommandFlags flags = CommandFlags.None)
```

**Comment by NickCraver** [comment]
Answered above - closing out to tidy up!
