### ISSUE TITLE
Redis Cache time out

### ISSUE THREAD

**Issue by sasankjonna** [StackExchange/StackExchange.Redis#2493]
We are implementing Redis Cache to out .net 4.6.1 project and are getting below error

StackExchange.Redis.RedisTimeoutException
  HResult=0x80131505
  Message=Timeout performing HMSET (10000ms), next: HMSET LOCATIONen-US, inst: 0, qu: 1, qs: 2, aw: True, bw: Flushing, rs: ReadAsync, ws: Flushing, in: 0, in-pipe: 0, out-pipe: 31992055, last-in: 2, cur-in: 0, sync-ops: 24, async-ops: 1, serverEndpoint: 10.29.160.12:6379, conn-sec: 39.99, aoc: 0, mc: 1/1/0, mgr: 10 of 10 available, clientName: 5CG0251G81(SE.Redis-v2.6.116.40240), PerfCounterHelperkeyHashSlot: 10011, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=5,Free=32762,Min=8,Max=32767), v: 2.6.116.40240 

Any pointers where to start trouble shooting this?

**Comment by NickCraver** [comment]
Is it possible your connection took a while to spin up? I see a few things here:
1. Your connection has only been connected 39 seconds, and the timeout is at 10 seconds
2. `AbortOnConnect` is set to false, allowing sending commands before it's up
3. The backlog writing is flushing indicating this is the case, and items were backlogged

**Comment by sasankjonna** [comment]
I am sorry I am new and trying to get around this. Do you suggest any changes to the way I am connecting?

   Private Shared Function CreateMultiplexer() As Lazy(Of ConnectionMultiplexer)
        Return New Lazy(Of ConnectionMultiplexer)(Function() ConnectionMultiplexer.Connect(ConfigurationHelper.ConnectionStrings.Redis))
    End Function


Config : 
<add key="RedisConnectionStrings" value="10.29.160.11:6379,10.29.160.12:6379,10.29.160.13:6379,ssl=False,allowAdmin=True,abortConnect=False,defaultDatabase=0,syncTimeout=10000" />

**Comment by NickCraver** [comment]
(Note: I edited your comment purely for code formatting, so the XML was visible)

I'd recommend passing a logger into `.Connect()` (second argument) to see what's happening. Given your symptoms potentially 1-2 of the 3 nodes aren't connecting quickly..

**Comment by NickCraver** [comment]
Closing this out pending more info, but happy to re-open if there's more to go on.
