### ISSUE TITLE
After synchonous Subscribe function the subscription is not always ensured

### ISSUE THREAD

**Issue by albertjan** [StackExchange/StackExchange.Redis#250]
so I have a 

``` f#
do sub.Subscribe(
             newJobChannel,
             (fun c v ->
                 async {
                     let jobId = v |> int64
                     return! this.emitNewJobEvent(jobId)
                 } |> Async.RunSynchronously))
```

after this function when I do a publish directly it returns `0` 

I have to do this to ensure the subscription:

``` f#
let rec ensureSubscription () =
    async {
        let! res = sub.PublishAsync (newJobChannel, -1L |> toValueI64)  |> Async.AwaitTask
        if res >= 1L then 
            ()
        else 
            return! ensureSubscription ()
        do! Async.Sleep 10
    }

do ensureSubscription () |> Async.RunSynchronously
```

Is this by design or a bug?

**Comment by NickCraver** [comment]
Are you still having issues with current versions of the library? I think no one looked at this due to the very few F# developers in general, but of course it's not a language issue.

We have made several tweaks and fixes on this front in the very long time this this was opened (sorry!), hopefully you can't repro in the current version. If you can, I'm very curious about your setup.

**Comment by albertjan** [comment]
Haven't looked at it in a while, but I have to soon, so I'll keep you posted. 

It's probably less easy to produce in c# because there's gonna be a few people out there rely on pub/sub being (close to) water tight because they can't use the blocking calls.

**Comment by NickCraver** [comment]
@albertjan Did you ever get a chance to see if this works? Don't want to close it out if there's still an issue on it - so far this is the only report I've gotten. Cleaning up old issues and checking in :)

**Comment by albertjan** [comment]
@NickCraver nah switched jobs 😄as you do. I will try and run the tests for the thing tomorrow. They should prove if it's still a bug.

**Comment by albertjan** [comment]
@NickCraver just ran the tests without the `ensureSubscription` and I don't see this anymore. 👍

**Comment by NickCraver** [comment]
Thanks for the follow up! Much appreciated :)
