### ISSUE TITLE
Timeout while trying to use self-configured Tls port

### ISSUE THREAD

**Issue by jimmycham** [StackExchange/StackExchange.Redis#2501]
Hi, 
I have setup an endpoint with tls port 16380, but it is getting timeout error in version 2.5.43 and authentication failure in version 2.6.116.
I have tested the endpoint and the port by using Redis Insight and redis-cli, everything working fine.
I have another endpoint which tls port was configured to 6380, it can be used without any issues as well.

Is there any limitations on the port in this library? Thanks.

var options = new ConfigurationOptions();
options.EndPoints.Add(settings.Host);
options.ConnectRetry = settings.MaxConnectionRetryAttempts;
options.ConnectTimeout = settings.ConnectionTimeoutMilliseconds;
options.AllowAdmin = settings.AllowAdmin;
options.AbortOnConnectFail = settings.AbortOnConnectFail;
options.SyncTimeout = settings.SyncTimeoutMilliseconds;
options.Password = settings.Password;
options.Ssl = true;
options.SslHost = settings.Host.Split(':')[0];
options.SslProtocols = SslProtocols.Tls12;

**Comment by jimmycham** [comment]
Most likely will be the Ssl's RemoteCertificateNameMismatch issue, will close this once I have confirmed the fix in my code.

**Comment by NickCraver** [comment]
@jimmycham Checking in - did you get this sorted?

**Comment by jimmycham** [comment]
yes, I have added a function to validate the cert and confirmed that it was due to cert name issue. Thanks.
