### ISSUE TITLE
Supporting Write Through and Read Through caching strategy

### ISSUE THREAD

**Issue by mehdihadeli** [StackExchange/StackExchange.Redis#2504]
Hi,
Is there any plan for handling Write Through and Read Through caching strategy in this library, like something exists in [redisson/redisson](https://github.com/redisson/redisson/wiki/7.-distributed-collections#712-map-persistence) java library?

**Comment by NickCraver** [comment]
Not in this library most likely, this is purely a client with some handling almost 1:1 with what Redis allows. But this is being discussed, and we may end up adding some extensibility points to support that (especially around efficiency in later .NET versions taking advantage of goodies.

"How do I (de)serialize my object?" is a surprisingly deep question to get right, and varies a lot across languages/platforms. We want to solve it well for .NET when doing this.

cc @mgravell

**Comment by mgravell** [comment]
Indeed; this is a focus of mine for .NET 9 in the context of asp.net - see https://devblogs.microsoft.com/dotnet/caching-abstraction-improvements-in-aspnetcore/ for some preview discussion on that topic. As Nick notes, serialization is a significant hurdle re configuration, but: I have ideas. And as discussed in #2507, we'd also be looking to implement things like server-assisted evictions at the same time.

**Comment by mehdihadeli** [comment]
Thanks for your information,
Does it make sense to create this type of caching strategy (Write Through or Read Through) in a building block project or an azure function, and our application just use it without handling updating primary database manually?

**Comment by mgravell** [comment]
Whether it makes sense or not is hugely contextual. "Maybe"

**Comment by mehdihadeli** [comment]
Yes, Thanks

**Comment by NickCraver** [comment]
Since we'll have many issues on this - closing out as the question here's answered.
