### ISSUE TITLE
Implement Client side caching 

### ISSUE THREAD

**Issue by punitsinghi** [StackExchange/StackExchange.Redis#2505]
Is there a plan to bring Client side caching like NCache does. We currently use Stackexchange.redis -c# and connect o Azure redis. We would like to cache values on Client side to avoid delay / reduce network calls. We currently use NCache which supports client side caching. I thought we can subscribe to events like Cache Eviction or Expired ( __keyevent@0__:expired) and have a mem cache on client side which can refresh the value when redis cache is updated but looks like Azure redis doesn't supports this. 

so wondering if there is any other way to have client side cachning so we dont have to get data from redis server everytime.

**Comment by mgravell** [comment]
Right now: no; we've discussed it many many times, but the code we had (back at Stack): wasn't suitable for sharing.

I *am* hoping to address this in the .net 9 timeframe as part of an asp.net distributed caching overhaul, but: no guarantees.

**Comment by punitsinghi** [comment]
Thanks for the update.
