### ISSUE TITLE
SortedSetCombineAndStore with SetOperation.Difference not working for me

### ISSUE THREAD

**Issue by liormn** [StackExchange/StackExchange.Redis#251]
Hi,

I've started to work with redis and after setting 2 sortedsets i've tried
SetOperation.Intersect, SetOperation.Union and SetOperation.Difference.

Intersect and Union works just fine but when i trying to use Difference i'm getting an error:
"Specified argument was out of the range of valid values.
Parameter name: operation"

The call for all the 3 is the same beside the SetOperation option
SortedSetCombineAndStore(SetOperation.Intersect, sortedSetDestination, firstSortedSet, secondSortedSet, Aggregate.Min, CommandFlags.None);

Any ideas?

10x,
Lior

**Comment by NickCraver** [comment]
Ok so why this doesn't work: there's simply no redis mapping for such an operation. The following mappings *do* exist:
`SetOperation.Intersect` => `ZINTERSTORE`
`SetOperation.Union` => `ZUNIONSTORE`

While something like a "ZDIFFERENCE" has been requested - it's never been added to Redis. If you get Redis to add such an operation, we'll support it!
