### ISSUE TITLE
Supporting async operation inner Subscribe callbacks

### ISSUE THREAD

**Issue by mehdihadeli** [StackExchange/StackExchange.Redis#2511]
Hi,
Is it possible to add an overload to `SubscribeAsync` like `Func<RedisChannel,RedisValue,Task>` for supporting `await` keyword inner SubscribeAsync callback?

``` csharp
 await database.Multiplexer
            .GetSubscriber()
            .SubscribeAsync(
                channelName,
               // this parameter is a `Action<RedisChannel,RedisValue>` so we can do await on async operation inner this delegate
                (chan, val) =>
                {
                   // await keyword is not possible because we don't have an overload with return type Task
                }
            );
```

**Comment by mgravell** [comment]
The `Subscribe` method *without* a delegate returns a `ChannelMessageQueue`; from there, you can write your own loop that asynchronously dequeues events and performs synchronous or asynchronous operations. That's probably the way I would go here. It does raise the question of whether we should provide a pre-rolled implementation via an extension method that takes an async delegate.

**Comment by mehdihadeli** [comment]
Thanks for your suggestion, It works with something like this:
``` csharp
var channelMessageQueue = await database.Multiplexer
    .GetSubscriber()
    .SubscribeAsync(channelName);

var channelMessage = await channelMessageQueue.ReadAsync();
var message = channelMessage.Message;
```
But maybe adding a new `Func<RedisChannel,RedisValue,Task>` overload for handling this is more compact and easy to use.
