### ISSUE TITLE
ACL NOPERM this user has no permissions to access to the publish command

### ISSUE THREAD

**Issue by ilya-indigo** [StackExchange/StackExchange.Redis#2512]
openSUSE Tumbleweed Redis 7.0.12

In the config, I disable the default user and define my own user
```
user default off
user MY_USER on +@all ~* >MY_PASSWORD
````
I connect by socket via `redis-cli` and can execute `keys *` without any problems
But I don't have access to the publish command.
```
PUBLISH time 1689623995
(error) NOPERM this user has no permissions to access one of the channels used as arguments
```
It used to work fine, but now, for some reason, it's not working. :-(

**Comment by mgravell** [comment]
It sounds like you're saying `PUBLISH` doesn't work even via redis-cli, in which case that's a server config issue - which is "not us" - we're just a specific client library implementation, which you aren't using if you're using redis-cli.

However, please see the server docs [here](https://redis.io/docs/management/security/acl/) and search for "Allow and disallow Pub/Sub channels"

**Comment by ilya-indigo** [comment]
I'm sorry I took you for an upstream.
https://github.com/redis/redis/issues/12418
