### ISSUE TITLE
LockTake failing

### ISSUE THREAD

**Issue by pianoman4873** [StackExchange/StackExchange.Redis#2518]
Hello, 
I am encountering a peculiar exception from a particular windows services accessing our Redis cluster and not from others - although they share the same Redis cluster configuration ( amongst additional IIS servers from other machines all sharing the same Redis cluster config ) - 

StackExchange.Redis.RedisServerException: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.\r\n   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1986\r\n   at StackExchange.Redis.RedisDatabase.LockTake(RedisKey key, RedisValue value, TimeSpan expiry, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1437\r\n   at 

As mentioned, there's no such exception from any other service , although many of them execute write commands in general and the LockTake in particular abundantly.

Any idea what could be the reason for that ?

Thanks  a lot !

PS This happened hundreds of times in the last week.

**Comment by NickCraver** [comment]
@pianoman4873 It sounds like maybe you have _some_ nodes of a cluster out? This is a server-side error, it could be lack of disk access or disks running out of space or similar.

**Comment by mgravell** [comment]
I'm intrigued, but ultimately as Nick says: this error is coming from the server itself - there's literally nothing we can do to either cause or remedy this message. I would advise checking all the server nodes individually. Closing this out.

**Comment by pianoman4873** [comment]
Thanks Nick and Marc.
