### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by MosheL** [StackExchange/StackExchange.Redis#252]
Hi!

I am using  Redis client (and in the past, BookSleeve) in production.  The connector works and useful in IPV4 but could not connect to IPV6 Redis.

Redis itself responding to V6 (tested via `telnet`).

Will be change?

thanks

**Comment by NickCraver** [comment]
What error are you getting with IPv6? We're not using it internally for other reasons, so need a starting point here.

**Comment by MosheL** [comment]
when I am using a direct IPv6 Address:

````
[ArgumentException: הערך אינו נמצא בטווח הנדרש.]
   StackExchange.Redis.EndPointCollection.Add(String hostAndPort) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\EndPointCollection.cs:33
 ````

When I am using DNS with only a AAAA (v6) record:

````
No connection is available to service this operation: EVAL
````

**Comment by NickCraver** [comment]
Translation:
> The value is not within range required

Okay got it - should be able to test this soon and see where we're breaking down.

**Comment by MosheL** [comment]
something new ?
the same system works with IPv4 NAT.

**Comment by TheHydGuy** [comment]
Does this supports IPV6?

**Comment by MosheL** [comment]
Still not.  I was found my self using IPv4 NAT to bypass this problem.

**Comment by TheHydGuy** [comment]
Can you point me the document for using IPv4 NAT

**Comment by MosheL** [comment]
what is your system topology?  LAN?  VPN for something?

**Comment by TheHydGuy** [comment]
LAN

**Comment by MosheL** [comment]
So just use IPv4 on local subnet and ignore whole IPv6 problem.

**Comment by laskoviymishka** [comment]
Any progress on this? 
Do we have any way to connect redis which DNS resolved to ipv6 only?

**Comment by goncalo-oliveira** [comment]
Hi. Is there any progress on this?

It seems that using the IP address directly (IPv6) the connection succeeds, but using a DNS name that only resolves to IPv6 doesn't...
