### ISSUE TITLE
Is it okay to use StackExchange.Redis v1.2.6?

### ISSUE THREAD

**Issue by sea0920** [StackExchange/StackExchange.Redis#2524]
I am getting the impression that StackExchange.Redis v2 has some architectural issues.
My company has been using StackExchange.Redis v1.2.6 for so many years without worrying about Redis Timeout exceptions.
Somehow after switching to v2, we are getting a lot of exceptions.

The fishiest part is _singleWriterMutex in PhysicalBridge.cs. This looks like the bottleneck when a lot of Redis requests are sent.
MutexSlim doesn't look reliable. Even if I switch it to SemaphoreSlim and use Async method(I am currently using Sync method in .Net Framework 4.8.), I don't think Redis Timeout exceptions will disappear.

Would it be okay to keep using StackExchange.Redis v1.2.6?

**Comment by mgravell** [comment]
Can you use it? Sure, we aren't going to turn up and delete it from your machine. But you're on your own with it too - we can't offer advice or fixes on the long out-of-date bits. Of course, we don't have an SLA either way, so: maybe that isn't a concern.
