### ISSUE TITLE
'StackExchange.Redis

### ISSUE THREAD

**Issue by ShivaniY4W** [StackExchange/StackExchange.Redis#2532]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'ConnectionMultiplexer' exists in both 'StackExchange.Redis.StrongName, Version=1.2.6.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46'	y4w	C:\Users\DELL\Desktop\y4w Packages\git\Y4Wmain\Concrete\YUtitlity.cs	62	N/A

**Comment by mgravell** [comment]
The message says it all: you're referencing (either directly or transitively) two different packages with the SE.Redis core. The preferred option is to unify that down to just StackExchange.Redis (which has been strong named for "quite some time") and discard StackExchange.Redis.StrongName (which is no longer maintained). Worst case, you can use "extern alias" to keep both and tell the compiler which you mean at any point. But that is not the recommended option.

**Comment by NickCraver** [comment]
What Marc said :) Closing out to tidy up!
