### ISSUE TITLE
[Question] byte array or Memory<byte> and FireAndForget message

### ISSUE THREAD

**Issue by rayao** [StackExchange/StackExchange.Redis#2536]
When RedisValue payload is byte[] (or Memory<byte>), and CommandFlags.FireAndForget is set, is there any way to know when it's safe to touch the byte[] content?
For example, if the byte array is rented from ArrayPool, how do I know when to return it back to the pool? Or maybe in this case it's not recommended to use FireAndForget?

**Comment by mgravell** [comment]
Don't use fire and forget in this scenario.

**Comment by rayao** [comment]
Thank you @mgravell
