### ISSUE TITLE
Guidance for using ConnectionMultiplexer with dependency injection and health checks

### ISSUE THREAD

**Issue by adamsitnik** [StackExchange/StackExchange.Redis#2537]
I would like to do the following:
- register a `ConnectionMultiplexer` factory in the DI container
- register an ASP.NET health check for given `ConnectionMultiplexer` 
- have optimal perf and resiliency

Based on the available [docs](https://github.com/StackExchange/StackExchange.Redis/blob/main/docs/Basics.md#basic-usage) I've assumed that I should register a singleton so the instance can be reused (perf):

```cs
builder.Services.AddSingleton<IConnectionMultiplexer>(sp => ConnectionMultiplexer.Connect(settings.ConfigurationOptions));
```

Then I read the implementation of popular [health check](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/c000704e1e256c932539fcd5d4c8df781e8ec1a7/src/HealthChecks.Redis/RedisHealthCheck.cs#L84-L90) for `ConnectionMultiplexer`, which **disposes** the `ConnectionMultiplexer` on exception.

What happens when I successfully connect via `ConnectionMultiplexer.Connect`, but later the connection fails? Is `ConnectionMultiplexer` able to reconnect on it's own and I should keep using a singleton? I saw the `ConnectionFailed` and `ConnectionRestored` events, so I would assume that to be true?

cc @mgravell @NickCraver @damianedwards @eerhardt

**Comment by NickCraver** [comment]
Correct: safe to use a singleton that doesn't change - we reconnect internally, and you can observe via events what's going on (as well as ILogger bits next release). 

Only if your configuration is changing to different endpoints (e.g. moving clusters, part of some migration for example) would you want to swap that singleton out. Most other things like passwords and such are observed live, so we'll respect the options passed in and get live values from it (to support things like MI).

**Comment by adamsitnik** [comment]
@NickCraver thank you very much!

**Comment by eerhardt** [comment]
What about https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-best-practices-connection#using-forcereconnect-with-stackexchangeredis? And [this functionality in ASP.NET](https://github.com/dotnet/aspnetcore/blob/045afcd68e6cab65502fa307e306d967a4d28df6/src/Caching/StackExchangeRedis/src/RedisCacheOptions.cs#L51-L57)?

**Comment by NickCraver** [comment]
@eerhardt I wouldn't advise using the force reconnect pattern at all - it was a pattern from before we knew about a lot of the various problems hitting many cloud teams (which we rapidly improved once seeing them - joining MS), these days it only causes more drops and problems. The multiplexer handling this internally results in fewer errors (e.g. things not dropped on the floor, but buffered and tried when connected internally, etc.).
