### ISSUE TITLE
Sentinel mode selecting master

### ISSUE THREAD

**Issue by joesun99** [StackExchange/StackExchange.Redis#2542]
Hi everyone, hope u r all doing fine.  I am having problem connecting to my test docker redis-sentinel setup. I have three redis instances on ports 6381, 6382, 6383 and three sentinel instances running on ports 5000, 5001 and 5002.

Am I able to connect through custom ports?

Kind regrads

**Comment by mgravell** [comment]
Ports can be specified in either a configuration string ("server:port") or via the endpoints API. Do you have an example of how you're trying to connect currently?

**Comment by joesun99** [comment]
Sample connections:

1. "redis.local:6381, redis.local:6382, redis.local:6383, serviceName=mymaster"
UnableToConnect on redis.local:6381, redis.local:6382, redis.local:6383, serviceName=mymaster:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.122.38350


2. "redis.local:5000, redis.local:5001, redis.local:5002, serviceName=mymaster"
UnableToConnect on redis.local:5000, redis.local:5001, redis.local:5002, serviceName=mymaster:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.6.122.38350

3. redis.local:6381
If 6381 is master then is working

**Comment by joesun99** [comment]
Could be that redis and sentinel must be on same instance with default port 6379 and 26379?

**Comment by slorello89** [comment]
@joesun99 

Something really important to keep in mind when you are experimenting with Sentinel/cluster inside of docker is that the IP addresses / host-names that the sentinel/masters will respond with will not necessarily be accessible outside of your docker network, you might have to deploy your application into the network in order for it to see it.

**Comment by joesun99** [comment]
Hi, @slorello89 I have my public ip exposed for example i am using -slave-announce-ip xx.xx.xx.xx --slave-announce-port xxxx
I also tested and sentinels are electing master In different test cases. I think problem is with Stackexchange driver that is awaiting redis and sentinel running on same instance with default ports. Of Course the ip addr should be exposed. I think I have to debug the driver to confirm my assumption.

**Comment by NickCraver** [comment]
@joesun99 I looked over the obvious here: it's spaces in your connection string. That's being parsed as one giant endpoint :)

**Comment by joesun99** [comment]
Sorry I found where my bug was Sorry for bothering.  After using connectionString property not host everything works fine. Sample of connection
<add name="RedisStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" connectionString="xx.xx.xx.xx:6381, xx.xx.xx.xx:6382, xx.xx.xx.xx:6383" ssl="false"/>
