### ISSUE TITLE
Getting Compile Error CS1545: Property, indexer, or event 'ConfigurationOptions.EndPoints' is not supported by the language;

### ISSUE THREAD

**Issue by LoudThunderNET** [StackExchange/StackExchange.Redis#2544]
Condition:
- .Net Framework 4.6.2.
- Used language C# 7.3 (unable to use greater version)
- Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
- StackExchange.Redis version 2.6.80 (all version where used 'init' modificator for EndPoints property of the ConfigurationOtions class)
msBuild 2019
- source code that caused the error
```
var options = new ConfigurationOptions
{
    AbortOnConnectFail = true,
    ConnectTimeout = 10000,
    AllowAdmin = true
};
foreach (var host in Configuration.RedisHosts)
{
    options.EndPoints.Add(host, Configuration.RedisPort); // this line
}
```
Workarround:
use reflection as suggested in error message

**Comment by NickCraver** [comment]
You will need MSBuild 17+ to build our project - this is known and intended. We do not support anything lower.

**Comment by NickCraver** [comment]
Going to close this out to tidy up - not much to change here, use 17+ tooling :)

**Comment by mgravell** [comment]
With hindsight we might not have added an "init" property, it avoid making
the API twitchy. But we can't remove it now without causing worse, and I
don't think it warrants a secondary API.
