### ISSUE TITLE
Ignore self sent message in an auto scaled cloud environment

### ISSUE THREAD

**Issue by ap-81** [StackExchange/StackExchange.Redis#2549]
I have the application running on Azure cloud with auto scaling turned on.  How can I ignore the self message, given the number of servers can change dynamically? 

This issue (#859)  talks about a similar scenario but the number of servers are static, so the names could be pre-assigned in order to identify each server.

**Comment by mgravell** [comment]
With the exception of server-assisted client caching: that isn't a scenario supported by the server, and the library tries to stay "pure" (meaning: no opinionated convention things - users can add their own). I have a branch for the server-assisted caching: "in progress" - so if you're using server v6 or above, waiting on that is probably the best move.

**Comment by mgravell** [comment]
If that isn't an option, for a convention based approach: pick a guid at the start of your process, and prefix all messages with your own guid. Ignore any messages that start with your own guid.

**Comment by NickCraver** [comment]
Closing out to tidy up!
