### ISSUE TITLE
ThreadPriority.AboveNormal for SocketManager reader/writer threads should be optional

### ISSUE THREAD

**Issue by mckenzieg1** [StackExchange/StackExchange.Redis#255]
The 'reader' and 'writer' threads used by the `SocketManager` are created with `ThreadPriority.AboveNormal`. Depending on the client's threading model and the relative priority of Redis operations vs. other client code, this may not be desirable for all clients. A configuration option would allow clients to override this if they chose.

**Comment by NickCraver** [comment]
Fixed via #256
