### ISSUE TITLE
Connect standalone cluster (1 node, no sentinel, standalone) CLUSTER command passed

### ISSUE THREAD

**Issue by mscbpi** [StackExchange/StackExchange.Redis#2569]
Hi,

We are using Redis Bitnami `helm`chart to deploy a non-cluster, single-node, no sentinel, in k8s, `standalone` architecture. 
Clients are running in the same K8s cluster and accessing with an internal `ClusterIP` service.

We are using a standard, minimal connection string.
`<clusterIP URL>:6379,password=<password>,ssl=False,abortConnect=False,syncTimeout=7100`

`INFO Errorstats` is reporting lots of errors (`errorstat_ERR`, several 100Ks), and we struggle to identify what they are.

We have identified `CLUSTER NODES` command that triggers an ERR that is expected that is regularly passed to the server
`ERR This instance has cluster support disabled` 

which would be expected.

Is there something we miss to connect this ? Is excluding `CLUSTER` command the right way to avoid this counter to grow ?
Is there a way to identify the numerous ERR we have in the counters (there are certainly more) ?

Thanks

**Comment by mgravell** [comment]
(basically, we pipeline everything we might possibly need when connecting, to avoid having to pay N x {latency} overhead)

**Comment by mscbpi** [comment]
Investigating the code, we had indeed a wrongdoing in managing the connection. 

2 per Redis Client is what is expected, one of we exclude SUBSCRIBE if not used. 

The "store and reuse" ConnectionMultiplexer had not been respected.

I close the issue as `ERR` (and certainly other side effects) are related to `CLUSTER` commands that were triggered at each caching operation (`GET` or `SET`) because of `Connect()` that should have been avoided.

**Comment by mgravell** [comment]
@NickCraver  do we currently track how many multiplexers have been created? Maybe we should, and include in the error message if it is more than, say, 100: "hey, it looks like you're creating lots of multiplexers... that sounds wrong"

**Comment by mscbpi** [comment]
Great idea,

And is there a way to log/view the replies / errors from redis server to redis client ?

Thanks
