### ISSUE TITLE
Whats the logic for update the Web.config on Updates

### ISSUE THREAD

**Issue by ricardopolo** [StackExchange/StackExchange.Redis#257]
I have this in my web.config
````
    <sessionState mode="Custom" customProvider="SessionStateStore">
      <providers>
        <add port="" applicationName="SigntulSession" name="SessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="localhost" accessKey="" ssl="false" throwOnError="true" />
      </providers>
    </sessionState>
````

Always when update the NuGet I get the example   <sessionState mode="Custom" customProvider="MySessionStateStore"> in my web.config and the app stops working until I deleted

So whats the logic for that and how can avoid this?

Thank you

**Comment by NickCraver** [comment]
That looks to be the work of the RedisSessionStateProvider package, which just includes StackExchange.Redis but has other code doing this. You can report any issues [on their GitHub project here](https://github.com/Azure/aspnet-redis-providers). If curious [here's the offending transform that seems to be affecting you](https://github.com/Azure/aspnet-redis-providers/blob/master/src/RedisSessionStateProvider/web.config.transform).

It *seems* like you may not be using the session state provider package at all though, if removing it is a solution. If that is indeed the case, you want to remove that package and add the StackExchange.Redis package directly.

**Comment by ricardopolo** [comment]
You are right. This is not an issue of StackExchange.Redis, but an issue of the Redis Session State Provider

**Comment by ricardopolo** [comment]
I open an issue on that project https://github.com/Azure/aspnet-redis-providers/issues/9
