### ISSUE TITLE
KeyExpireTimeAsync Just works with master and not Replica

### ISSUE THREAD

**Issue by MattGhafouri** [StackExchange/StackExchange.Redis#2592]
KeyExpireTimeAsync  returns the DateTime? just in case a key has an ExpiryDate. I think It should be part of read-only operation, but found out It does not work with replica and returning this error :

> No connection (requires writable - not eligible for replica) is active/available to service this operation: PEXPIRETIME mc: 1/1/0, mgr: 9 of 10 available, OCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=11,Free=32756,Min=50,Max=32767), POOL: (Threads=28,QueuedItems=0,CompletedItems=2540), v: 2.6.96.30123

**Comment by mgravell** [comment]
Agreed - this seems to be miscategorized!
