### ISSUE TITLE
FLUSHDB performs slowly when persistence-available=no

### ISSUE THREAD

**Issue by davidwestern** [StackExchange/StackExchange.Redis#261]
Using StackExchange REDIS 2.8.19 on Windows 2008 R2, 32GB RAM, 12 cores, dual E5645 CPUs

We do not need persistent data in REDIS, just the in-memory cache. We flush the cache periodically using the FLUSHDB command. When we have persistence-available=no this FLUSHDB command takes 90 minutes. When persistence-available=yes the command yields almost immediately and the background flush appears to finish within a minute or so based on monitoring disk I/O in resource monitor.

I've written a .Net app that reproduces this problem. It appears to be related to large key values. When I test with 2 million keys of 512 bytes it finishes in a few seconds. When I try this with 150K keys of 512K  each it takes an inordinate amount of time (stopped at 10 minutes).

Our production environment has around 800K keys and uses 14GB of data (maxmemory 14GB). This consistently takes 90 minutes. the .conf file comments indicates using persistence-available=no would provide better performance.

"As an optimization, all persistence can be turned off in the Windows version of Redis." (from redis.windows.conf).

**Comment by chester89** [comment]
What about if you try the same thing using Redis console client?

**Comment by davidwestern** [comment]
In my testing the flushdb was issued from the redis-cli.exe after loading
cache data from a test app.

**Comment by chester89** [comment]
So I guess it looks more like a server concern then, not related to the
client

2015-08-14 15:28 GMT+03:00 davidwestern <notifications@github.com>:

> In my testing the flushdb was issued from the redis-cli.exe after loading
> cache data from a test app.
>
> On Fri, Aug 14, 2015 at 7:33 AM, Gleb Chermennov <notifications@github.com
> >
> wrote:
>
> > What about if you try the same thing using Redis console client?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/StackExchange/StackExchange.Redis/issues/261#issuecomment-131083178
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/261#issuecomment-131092864>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by davidwestern** [comment]
Moving this issue to the MSOpenTech redis project as it appears to be a server issue and not related to the StackExchange Redis client.

**Comment by mgravell** [comment]
This sounds like something that should be addressed to the redis-server
(whether the core antirez project, or the MS port, etc). I don't think this
is related to the client library, and I don't think there is anything the
client library can do differently here.
