### ISSUE TITLE
 An exception was thrown while invoking the constructor 'Void .ctor()' on type 'RedisCacheService'.

### ISSUE THREAD

**Issue by Mjalali1982** [StackExchange/StackExchange.Redis#2626]
0

I am going to change my server, but when I want to run my application on the new server, I get this error:

An exception was thrown while activating Walrus.AAA.Services.SharedServices.Core.TokenService -> Walrus.AAA.Services.EndUserServices.Core.UserService -> Walrus.AAA.Services.SharedServices.Core.CacheService.RedisCacheService. Inner: An exception was thrown while invoking the constructor 'Void .ctor()' on type 'RedisCacheService'.

This application still works correctly on the previous server, but it gives this error on the new server. Does anyone know what I should do?

I checked the connection between this server and Redis and it was correct. The config file related to this connection is also correct .

**Comment by mgravell** [comment]
Also received via email. Echoing my response,for visibility:

> Well, what is RedisCacheService? That isn't a SE.Redis type, so it is hard for me to comment. Also, try looking at the InnerException here - it may provide more context.

**Comment by mgravell** [comment]
If that doesn't help, but the error is definitely in a "connect" step: the `ConnectionMultiplexer.Connect[Async](...)` API accepts an optional "log" parameter; if you pass in a suitable writer, lots of additional context is emitted, which can help identify what is failing.

**Comment by Mjalali1982** [comment]
Thank you dear Mark for answering me.
I will try to find a solution to the problem with this guide and I will let
you know the result.
thank you
