### ISSUE TITLE
Tag Releases

### ISSUE THREAD

**Issue by Xhanti** [StackExchange/StackExchange.Redis#267]
Hi Marc,

It would be great if you could tag release versions of the source so they match up with nuget releases. At work, I have to justify an upgrade in any 3rd party library by pointing at the specific feature(s)  we need and why we need them. That's a bit hard when I don't know which nuget release has the features we need specifically.

Any assistance you could provide in this regard would be greatly appreciated.
Regards,
Xhanti

**Comment by spuder** [comment]
+1

**Comment by mgravell** [comment]
Fair point. Will do. I did the same for dapper a week or so ago, so fully
agree.

**Comment by Xhanti** [comment]
Thanks, closing this.
