### ISSUE TITLE
Invalid bulk string terminator

### ISSUE THREAD

**Issue by axelgenus** [StackExchange/StackExchange.Redis#2674]
I am facing this exception when trying to read from a remote Redis server:

```
StackExchange.Redis.RedisConnectionException: Invalid bulk string terminator
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2109
   at StackExchange.Redis.RedisDatabase.Execute(String command, ICollection`1 args, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1501
   at NRedisStack.JsonCommands.Get[T](RedisKey key, String path, JsonSerializerOptions serializerOptions)
```

I am using the official Debian Bullseye redis-stack package on the server, the latest version of StackExchange.Redis (2.7.33) and .NET 8. I have found no hints about what can cause the issue and with a local instance of Redis, the code seems to work just fine.

**Comment by mgravell** [comment]
What is the actual server here? Is it genuine redis?

If the problem is reproducible on demand, there is an API available that can capture your RESP traffic, allowing validation and investigation; please see https://stackexchange.github.io/StackExchange.Redis/RespLogging - are you able to see the issue with this enabled?

**Comment by mgravell** [comment]
TODO for self: switch to 100% isolated independent buffer inside the logging loop for the external read, to rule out any buffer reuse problem

**Comment by axelgenus** [comment]
What do you mean by "genuine Redis"? I am using the Debian package from the [official Redis repository](https://redis.io/docs/install/install-stack/linux/). The version is 7.2.0v9.

I am now checking with RESP logging enabled.

**Comment by mgravell** [comment]
That's a "yes" then - sometimes we've had problems with people using the library against other servers that implement the redis API, and we've seen *those servers* have glitches (especially with pipelined operations). Redis itself is usually pretty solid here!

**Comment by axelgenus** [comment]
I did not know there were custom re-implementations of the Redis API's; I just thought they were instances running in webfarms...

Anyways, I dug a bit into the issue:
- when running in the Debian VM it happens when I send a lot of data;
- when running in Docker (either locally or remotely), it does not reproduce.

I am going to keep investigating the logs.

**Comment by axelgenus** [comment]
I've just reproduced the issue. It seems the connection is severed by the server! I still do not know why but probably it's just a virtualization issue (virtio NIC), I guess it has nothing to do with the library. Sorry for wasting your time.
