### ISSUE TITLE
Bad profiler can bubble exception to the caller of redis commands

### ISSUE THREAD

**Issue by jdivy** [StackExchange/StackExchange.Redis#2684]
This might be a quick 'not our issue' ticket to close... but I recently discovered that by adding a profiler (thankfully not in production just yet) I was opening myself up to exceptions thrown by the profiler.  I don't have the exact stack trace in hand any more but it was in a call to `.Subscribe()` on the multiplexer, making its way down to the profiling session `.Invoke()` call (link below).

Thought it worth asking the question "should a naughty profiler have any bearing on an otherwise perfectly good Redis command".  I'm awaiting this fix in APM but I'm also now scared for future me when updating nuget...

https://github.com/elastic/apm-agent-dotnet/issues/2292
 
https://github.com/StackExchange/StackExchange.Redis/blob/2f69707d87488febb7376739ed4dc51ad9a422c6/src/StackExchange.Redis/ConnectionMultiplexer.cs#L1990

**Comment by NickCraver** [comment]
I'm trying to understand the question - are you saying the `.Invoke()` from a profiler is throwing internally? If so: yeah I'd say that's a profiler issue and not something we'd try/catch everywhere to prevent bad behavior on.

**Comment by jdivy** [comment]
Yep, that was basically the question - wasn't sure how extensive the use of the profiler `.Invoke()` was in the codebase so figured I'd ask to give you something to think about other than 'Timeout' tickets for a few minutes ;)
