### ISSUE TITLE
Assembly mismatch

### ISSUE THREAD

**Issue by abhishek9916** [StackExchange/StackExchange.Redis#2691]
I have upgraded redis to 2.7.33 version and also updated "[Microsoft.Extensions.Logging.Abstractions(>= 6.0.0)" but in project I am getting the old version so is this problem with current redis version or can someone tell me solution for this so I can solve this issue

{"Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' 
or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"
:"Microsoft.Extensions.Logging.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"}

**Comment by NickCraver** [comment]
You're hitting some mismatches upstream - see where I wrote up what's happening here :) https://nickcraver.com/blog/2020/02/11/binding-redirects/
