### ISSUE TITLE
RedisTimeoutException with high inbound

### ISSUE THREAD

**Issue by rlenoci-conga** [StackExchange/StackExchange.Redis#2709]
Seeing many of these and I am not sure what could be the cause. Only thing that stands out to me is high inbound of 40244KiB. Could this indicate other commands are requesting a lot of data causing commands like EXISTS to be delayed?

`Timeout awaiting response (outbound=7KiB, inbound=40244KiB, 5628ms elapsed, timeout is 5000ms), command=EXISTS, next: GET mykey, inst: 0, qu: 0, qs: 175, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, last-in: 335453, cur-in: 304708, sync-ops: 0, async-ops: 138291, serverEndpoint: localhost:6379, conn-sec: 7373.02, aoc: 1, mc: 1/1/0, mgr: 10 of 10 available, clientName: client(SE.Redis-v2.6.122.38350), PerfCounterHelperkeyHashSlot: 2666, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=8,Free=32759,Min=8,Max=32767), POOL: (Threads=9,QueuedItems=46,CompletedItems=6178363,Timers=10), v: 2.6.122.38350 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

**Comment by NickCraver** [comment]
Correct - this indicates quite a massive payload monopolizing the bandwidth from server to client delaying commands in the pipe behind it. Generally speaking, we don't recommend huge payloads for this reason, or separate those out to another connection with higher timeout thresholds and such if they have to be that large.
