### ISSUE TITLE
LockRelease always return false after updated the key's value

### ISSUE THREAD

**Issue by AnthonyCC** [StackExchange/StackExchange.Redis#271]
I am following the example from http://stackoverflow.com/questions/25127172/stackexchange-redis-locktake-lockrelease-usage,  with minor changes
```
RedisValue token = Environment.MachineName;

if(db.LockTake(key, token, duration)) {
    try {
        // you have the lock do work
       // try to update the value
      db.StringSet(key, "testNewValue");
    } finally {
        var isSuccess = db.LockRelease(key, token);
       //Problem, isSuccess always return false
    }
}
```
I am having problem with db.LockRelease(key, token), the method always return false after the update. If I don't do the update, it will return true as expected, but what's the point of using a lock if I can't do update after obtaining the lock?

**Comment by Pliner** [comment]
@AnthonyCC,

Actually, you use key incorrectly. If you choose some key to synchonize access between muptiple client, you must use choosen key only for lock.
For example, if you would like to syncronize access to key "resource", for the lock key you can use "resource_lock".

**Comment by AnthonyCC** [comment]
Gotcha. I thought the lock key should be the cache key. Thanks for clarifying.
