### ISSUE TITLE
Is there any way to match keys aligned reg pattern ^[0-9A-Za-z_-]{80}$?

### ISSUE THREAD

**Issue by maomaomqiu** [StackExchange/StackExchange.Redis#2719]
Hi,
I use below scripts to enumerate keys like - 
ZvNQasfj6U6joJUqFopU6xpzqUaoCfdHhvrqMm50lj5UQ0pMMUZFRE1IODNMRDlJNDhLTVNNUFI4My4u

```C#
string pattern = "^[0-9A-Za-z_-]{80}$";
await using var keys = server.KeysAsync(pattern: pattern).GetAsyncEnumerator();
```
Unluckily there find NO keys (Actually those kind of keys exist), I also try with pattern "[0-9A-Za-z_-]{80}", still no work,
Could anyone help suggest proper pattern?

**Comment by maomaomqiu** [comment]
I try workaround like ```"Z[0-9A-Za-z_-]{79}$"```, still no work

**Comment by mgravell** [comment]
redis pattern matching is not regex - it is glob; the only multiplicity support is `?` (any single) vs `*` (any multiple); untested, but if it needs to be exactly 80, maybe you could try `[0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-][0-9A-Za-z_-]` (etc, 80 of them)

alternatively, you could perhaps use a glob pattern to do a *broad* filter, and then apply a secondary regex in the C# code as a fine filter, i.e.

``` c#
await foreach (var key in server.KeysAsync(pattern: pattern))
{
    if (someRegex.IsMatch(key))
    {
         // more code
    }
}
```

**Comment by mgravell** [comment]
just to clarify: the server limitations are out of our hands - if you want to advocate for having regex support for keys/scan, that would be a topic for https://github.com/redis/redis

**Comment by maomaomqiu** [comment]
Another question, will ```???..``` be heavy cost to redis server? @mgravell

**Comment by maomaomqiu** [comment]
I try ```???```, it works

**Comment by mgravell** [comment]
> Another question, will ???.. be heavy cost to redis server?

You'd have to measure in your environment, but I wouldn't *expect* it to be particularly expensive

**Comment by maomaomqiu** [comment]
Thanks @mgravell , love you!
