### ISSUE TITLE
Can I pick specific shard of a redis server?

### ISSUE THREAD

**Issue by maomaomqiu** [StackExchange/StackExchange.Redis#2731]
Hi, I am working on a task to purge some keys in redis, I use below way to 
```C#
// initial config
ConfigurationOptions config;

ConnectionMultiplexer connection = await ConnectionMultiplexer.ConnectAsync(config)

// get servers
var rets = connection.GetServers();
var servers = new List<IServer>(rets.Length);

foreach (var ret in rets)
{
    servers.Add(ret);
}

// pick 1 server
await using var keys = server.KeysAsync(pattern: pattern).GetAsyncEnumerator();
bool isLastkey = !await keys.MoveNextAsync();
```

However, each time I run, it will randomly pick 1 shard in picked server (some server could have shard, while some server not)

So, I wonder could be possible to control hit which shard?

**Comment by mgravell** [comment]
At the moment: probably not. We could potentially add `GetServerByKey(string key, CommandFlags flags = default)` or `GetServerBySlot(int slot, CommandFlags flags = default)` if that would be useful, though? What is the scenario here?

**Comment by maomaomqiu** [comment]
Thanks for you reply @mgravell 

The scenario is - I am going to run a job to purge persistent keys in different region redis instance
(Those persistent keys are dirty data, generated by bug, and bug is now fixed)

# Before Purge
![image](https://github.com/StackExchange/StackExchange.Redis/assets/154726587/9d901a44-8fd5-4728-b06c-f0088a57f66d)


# After Purge
![image](https://github.com/StackExchange/StackExchange.Redis/assets/154726587/82190be9-32b6-44cf-964a-b05ea2fe0bba)

But in some region, there are > 1 shard, once purge 1 shard, persistent keys will be expired in 12 hours. I launch task again, then this task could hit same shard as I purged, and also could not, this need many human effort.

And I observed, in **some** region, every time I launch task, it will hit same shard.
e.g. for this region, I launch 6 times, every time it will hit shard 1. So I can not purge shard 0.
![image](https://github.com/StackExchange/StackExchange.Redis/assets/154726587/ce51704f-04af-4f89-bd54-436780eece13)

(This only happened in one region so far)

**Comment by mgravell** [comment]
OK, but how would you see this working in reality? I doubt you want to rotate through all 16384 slots, and it sounds like you don't have an individual key. For a purge, surely the appropriate thing is to iterate through the *servers*, limiting to the primaries (non-replicas), and use the existing key-scan API on `IServer`, which you can already do? But if not: again, how would you see your code using this?

**Comment by maomaomqiu** [comment]
Hi @mgravell 
1) OK, but how would you see this working in reality?
- If my understanding not wrong .. You mean suppose there exist some API that can select specific shard, I want it would be like ```server.KeysAsync(shardId: shardId, pattern: pattern)```
    - If I do not assign specific shardId, then I would expect it return keys from a random shard
    - If I do assign a specific valid shardId, then I would expect it return keys from choosen shard
    - If there is no shard, or a shardId is not valid, return nothing

2) Sounds like you don't have an individual key
- Yes, I only have pattern for keys

Correct me if any clarification wrong : )

Thank you!

**Comment by mgravell** [comment]
OK, but the shard-id is *not* something that you would casually know - you'd have to be using one of the `CLUSTER` APIs to get that, and at that point: you would also know the endpoint address, so: what scenario do you see where you would know a shard-id, but where the existing `GetServer()` API wouldn't work?

Understanding how you would actually use this API in reality is key to ensuring that any proposed API is suitable and useful; so: can you talk me though an actual use-case example, illustrating where you would know a shard id?

**Comment by maomaomqiu** [comment]
Thanks for following up @mgravell, for scene I faced, it is not common, or can say relatively niche.

In our service, we found there are great of persistent keys in redis cache, they are generated due to code bug, so we take 2 steps:
1) fix buggy code, add default TTL, so that persistent keys won't generate anymore
2) write a task to clear persistent keys

So in 2), I write a task, it works fine, but I found if there exist multiple shard, the task will randomly hit a shard, the signal for it start can query from log 
![image](https://github.com/StackExchange/StackExchange.Redis/assets/154726587/43b2bf60-5263-4666-9880-77ef30ef3dc7)

or metric peaks in dashboards
![image](https://github.com/StackExchange/StackExchange.Redis/assets/154726587/e300871d-e67d-46c3-b612-65ecc0d5204f)

But unluckily, the log our service onboard is not reliable, the end of purge task can not queried.

So I can only tell when task end from dashboard, I found when a shard task finished, it will not continue purge in another shard, so I have to trigger many times, especially for those have multiple shards.

**Comment by NickCraver** [comment]
I'm trying to understand the use case here - what's the problem with even purging end-to-end all the keys you want to purge, regardless of the shard? Which keys are stored were may even change during operation if a scale up, scale down, failover, etc. happens - the point of sharding generally is scaling you _don't_ have to care about. The intention is for you to care about a _key_ and let Redis/clustering handle the "where" aspect.

So let's back up: what's the problem with just iterating through your keys and purging, not caring about shards at all? Understanding that would help us advise better.

**Comment by maomaomqiu** [comment]
Thanks @NickCraver reply

 _what's the problem with even purging end-to-end all the keys you want to purge, regardless of the shard?_ - There is NO problem regardless of the shard.

And the issue can be mitigated by backward workaround, e.g., manually trigger my task repeat, until I hit ideal shard
![image](https://github.com/StackExchange/StackExchange.Redis/assets/154726587/1677cf04-9555-4e66-b738-2f31abba8824)

**Comment by maomaomqiu** [comment]
This issue can be closed
