### ISSUE TITLE
What's the possible reason leading difference peak in Server Load, Processor Time and CPU usage?

### ISSUE THREAD

**Issue by maomaomqiu** [StackExchange/StackExchange.Redis#2733]
Hi all, greatly thanks for many of previous answers, I am now working on a purge task to clear persistent redis region, and when I trigger task, I notice there exist difference in server load, processor time and CPU usage in different region.

# Region A
## Configuration
configuration Premium 26 GB (2 × 13 GB)

## Dashboards
- the peak indicates the trigger time
![image](https://github.com/StackExchange/StackExchange.Redis/assets/154726587/49b16711-ca1b-4a4f-aca5-72c962207709)
there is no obvious increase in Server Load, Processor Time and CPU usage at that period

- I trigger 3 times, every time dashboards are similar

## Volume
- Total keys ~8 million, purge task clear ~7 million keys

## Condition
- operation per second is 1.3-1.4 k before trigger
- get operation is slightly higher than set operation
![image](https://github.com/StackExchange/StackExchange.Redis/assets/154726587/aff89917-752f-4eea-9466-0d0e30268109)

## Configuration
configuration Premium 26 GB (2 × 13 GB)

## Dashboards
- the peak indicates the trigger time
![image](https://github.com/StackExchange/StackExchange.Redis/assets/154726587/796778e5-b561-48b0-8595-e8271587aee0)

## Volume
- Total keys ~6.5 million, purge task clear ~5.5 million keys
- Region A and Region B key distribution are similar

## Condition
- operation per second is 1.8-1.9 k before trigger
- get operation is double than set operation
![image](https://github.com/StackExchange/StackExchange.Redis/assets/154726587/67b82952-bdb8-4331-9556-e3651f648d9d)

# Purge Task Logic
```C#
// List of keys pattern that need get from redis
string[] patterns;

 using (ConnectionMultiplexer connection = await ConnectionMultiplexer.ConnectAsync(config))
 {
    // get server
    Iserver server = connection.GetServers().// filter server and check server logic, then get a serer
    List<Task> tasks = new List<Task>(patterns.Length);

    foreach (var pattern in patterns)
    {
        tasks.Add(RedisPersistentKeyPurgeAction(connection, server, pattern));
    }
    await Task.WhenAll(tasks).ConfigureAwait(false);
}

private async Task RedisPersistentKeyPurgeAction(ConnectionMultiplexer connection, IServer server, string pattern)
{ 
     // batchExpire keys from redis
    List<string> batchExpireBuffer = new List<string>(50);

    var db = connection.GetDatabase();
    await using var keys = server.KeysAsync(pattern: pattern).GetAsyncEnumerator();
    bool isLastkey = !await keys.MoveNextAsync();

    while (! isLastKey) 
    {
        // every proccessed 100 keys, there will be a sleep
        await Task.Delay(200);

        // every 50 keys or current has reached last key matched, then batch set default time to live to those persistent keys
        if (statisfy some condtion)
         {
             await BatchSetExpiry(batchExpireBuffer, expiry, db);
             batchExpireBuffer.Clear();
          }
         // if it length of batchExpireBuffer < 50 
         if (batchExpireBuffer.Count < 50)
         {
             batchExpireBuffer.Add(keys.Current.ToString());
         }
         // other logic of iterator
         ....
    }
}

 private Task BatchSetExpiry(List<string> setExpiryList, int expiry, IDatabase db)
 {
         IBatch batch = db.CreateBatch();

         foreach (var key in setExpiryList)
         {
            // expiry is default expire time, 12 hours
             batch.KeyExpireAsync(key, TimeSpan.FromSeconds(expiry));
         }

         batch.Execute();
       // omit other logic, e.g. exception handling
        return Task.CompletedTask;
 }
```

I wonder, do you have any ideas why cause difference?

**Comment by NickCraver** [comment]
It seems like this is a server-side question really, not a client one. Is the client doing anything incorrect here? I'm reading your question as "why _didn't_ the first server have the same impact?" - there are many reasons if that's the case from shard counts to SKU sizes, etc. - we can't really speak to server impact here because that's side widely variable depending on the hosting setup, replication, latency, concurrent load, etc.

If you can repro bad load patterns, it'd be best to engage the hosting team here to pose that question. If I'm missing a client-side question though: please clarify, happy to answer.

**Comment by maomaomqiu** [comment]
Thanks @NickCraver , I can repro.
**Bad load pattern** - it is tolerable, due to peak is only in 1 minutes.
I just wonder the possible root cause, so that if further similar operation needed, I can avoid peak

**Comment by maomaomqiu** [comment]
![image](https://github.com/StackExchange/StackExchange.Redis/assets/154726587/368c0d42-85c4-41f6-8dc7-58c6fcea59d4)

**Comment by maomaomqiu** [comment]
Hi @NickCraver , could you provide some ways to engage hosting team? Greatly thanks in advance!

**Comment by philon-msft** [comment]
@maomaomqiu Please engage support via 'Support + Troubleshoot' on the cache in the Portal

**Comment by maomaomqiu** [comment]
Thanks for reply, you mean azure portal? @philon-msft
