### ISSUE TITLE
How to optimize array allocate when `StringGet`？

### ISSUE THREAD

**Issue by dameng324** [StackExchange/StackExchange.Redis#2745]
My program fetches a lot of data from Redis during startup. Each value is a byte array, which is deserialized immediately and the byte array is never used again after deserialization. This results in a significant number of byte arrays being allocated, causing high GC pressure.

Can I configure an array pool to reduce this problem when using StringGet?

**Comment by mgravell** [comment]
`StringGetLease`; dispose the result when you're done with the payload.

**Comment by dameng324** [comment]
@mgravell Thanks a lot.I will try it.
