### ISSUE TITLE
SBOM Report for Infor( GRC product)

### ISSUE THREAD

**Issue by AdityaBhinge** [StackExchange/StackExchange.Redis#2759]
Hi,

Aditya here from the Infor GRC automation team. We have been using these packages for our product, GRC (Governance Risk and Compliance), for a while now. Infor GRC has been generating SBOM reports for vulnerability scanning. Recently, we have been asked to obtain SBOM reports from third-party resources we have been using. Therefore, I request you to provide me with the SBOM reports for the packages mentioned below, along with their versions. The reports are required for these versions only and in CycloneDX JSON format.

stackexchange.redis	   2.8.0
stackexchange.redis	   2.7.33
stackexchange.redis	   2.7.27
stackexchange.redis.strongname	1.2.6
stackexchange.redis.strongname	1.2.4

**Comment by NickCraver** [comment]
This is not something we provide. It is however open source, so you can generate an SBOM if you wish, it's by definition an open book.
