### ISSUE TITLE
AWS Elasticcache Redis Serverless with RBAC

### ISSUE THREAD

**Issue by alvaromongon** [StackExchange/StackExchange.Redis#2761]
Hello,

I am trying to connect to a serverless redis. It has some peculiarities like that SSL is always enabled and the only way to connect is by RBAC. We have other clusters not using SSL and using NO AUTH. So I don´t really need anything but the connection string to connect.

[Role-Based Access Control (RBAC)](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Clusters.RBAC.html)

Is StackExchange compatible with this configuration?

**Comment by mgravell** [comment]
TLS: no problem - see the Ssl property in the config options

RBAC - not explicitly tested, but from https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/auth-iam.html you should be able to use the token the same as a password when connecting, so it *should* work

**Comment by alvaromongon** [comment]
Hello Marc, thank you for your answer,

I was able to connect with user and password.

What I did was to create a user that had same user id and user name. This is important and required for it to work. I established authentication type password and set a password for the user. Then added the user to the user group assigned to elasticache redis serverless instance.

My ConfigurationOptions class looks like this:

```
new ConfigurationOptions()
                {
                    EndPoints = { new DnsEndPoint(redisConfiguration.ConnectionString, redisConfiguration.Port) },
                    //ResolveDns = true,
                    Ssl = true,
                    User = redisConfiguration.Username,
                    Password = redisConfiguration.Password,
                    SslProtocols = System.Security.Authentication.SslProtocols.Tls12,
                    AbortOnConnectFail = false
                };

```
