### ISSUE TITLE
High CPU use

### ISSUE THREAD

**Issue by Piotr-Fr** [StackExchange/StackExchange.Redis#2768]
High CPU, from 1%-2% as regular
after the update to the newest
goes to 58%.

Current version, before the update:
Redis server v=7.2.5 sha=00000000:0 malloc=jemalloc-5.3.0 bits=64 build=d284576ab9ca3cc5
Ubuntu 22.04.4 LTS.

Had to roll back.

**Comment by mgravell** [comment]
Which CPU? Client? Server?

**Comment by mgravell** [comment]
Once again: which CPU are we discussing here? The CPU of the redis server? Or the CPU of some client node *talking* to redis - for example, an asp.net/grpc web server?

**Comment by Piotr-Fr** [comment]
Sorry for that, I am pretty lame here.
It is the second, CPU of the client node.

**Comment by Piotr-Fr** [comment]
Paused update until today, did it, all is fine now.
No idea what worked.
