### ISSUE TITLE
poor performance of retrieving data from SortedSetScan result object

### ISSUE THREAD

**Issue by garytsoi** [StackExchange/StackExchange.Redis#278]
I try to retrieve the search the data using the SortedSetScan function. But i have find that retrieving the data from the result object is very slow. I would like to know any way can retrieve the data from result object faster? 

Here is my test result (2 record returned from SortedSetScan):

```C#
var records = db.SortedSetScan("keyword_0", "ACCIDENT*", 100);  // take 2 Milliseconds

// take 3.31 Seconds
var e = records.GetEnumerator();
while(e.MoveNext())
{
      var tmp = e.Current.Element;
}

var list = records.ToList(); // take 2.29 Seconds

var arr = records.ToArray(); // take 3.34 Seconds
```

**Comment by mgravell** [comment]
The important point here is that `SortedSetScan` doesn't fetch the data in one go; rather - it hands back an iterator that contains the first page of data and has the *cursor information* required to keep scanning. As you iterate over the data, it will issue *additional queries* to fetch more data. It does this pre-emptively as much as possible, but will never have more than 2 pages of data - the current page and the next page. It will automatically have a cost of [number of page fetches required] x [latency] (although in some scenarios, you might be consuming data slower than latency, so the buffered page will mean you never see that cost).

You can reduce the number of round trips (and thus reduce the overall cost) by increasing the page size, bu this is at the expense  of server utilization. You don't want to make the page size insanely big. You should also ensure you only consume the data once - if you need all the data and iterate it multiple times, consume it into a `List<T>` or `T[]` *first*, *then* consume it.

The following timing comparison  is largely irrelevant:

    var records = db.SortedSetScan("keyword_0", "ACCIDENT*", 100); // take 2 Milliseconds

I  can't remember without looking, but that could have done any of the following at this point:

- nothing (except validate the parameters)
- send the initial `SSCAN`, but not wait for the result
- send the initial `SSCAN` and buffered the first page

**Comment by NickCraver** [comment]
@garytsoi Does the above answer your question, or have a followup? (just revisiting older issues here)
