### ISSUE TITLE
SocketClosed error log on shutdown

### ISSUE THREAD

**Issue by RefaelP23** [StackExchange/StackExchange.Redis#2788]
I have a question about graceful shutdown of the Redis client.

We added the `ILoggerFactory` to the `ConfigurationOptions` and started seeing error level logs during shutdown of services:
```
StackExchange.Redis.RedisConnectionException: SocketClosed on redis-cache.com:6379/Interactive, Idle/MarkProcessed, last: QUIT, origin: ReadFromPipe, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, last-heartbeat: 0s ago, global: 0s ago, v: 2.7.27.49176
(StackExchange.Redis.ConnectionMultiplexer)
```

We have a wrapper to a Lazy initialized `ConnectionMultiplexer` that is registered via DI and implements `IAsyncDisposable`:
```
await _connection.CloseAsync(allowCommandsToComplete: true);
_connection.Dispose();
```

I'm trying to understand why this is an error log and not an info one.
At first, I thought that maybe it's due to an attempt to use the CM during shutdown, but I didn't get any `ObjectDisposedException` and I also tried shutting down while the service was idle and the log still appeared.
What am I missing here?

**Comment by bgrainger** [comment]
Duplicate of https://github.com/StackExchange/StackExchange.Redis/issues/2652?

**Comment by RefaelP23** [comment]
@bgrainger Thanks, seems so.
I tried searching for this scenario and error log but didn't find that open issue.
I'll close this one.
