### ISSUE TITLE
[Question] What's the minimum version of Redis Server to work with StackExchange.Redis?

### ISSUE THREAD

**Issue by mari3728** [StackExchange/StackExchange.Redis#2789]
What's the minimum version of Redis Server to work with StackExchange.Redis?

I'm asking this to check if Redis version 3.0.504 is expected to work with the library.

Thanks!

**Comment by mgravell** [comment]
Anything RESP2 or above - which includes  3.0.504 and quite a bit lower. Are you seeing any specific problems? By chance, Redis 3.0.5xx is actually particularly well-tested simply because Redis-64 is around there (I think that's 503).

**Comment by mgravell** [comment]
I looked it up; RESP aka RESP2 was released in Redis 1.2; so that is the earliest Redis version that I would expect to work. I have not explicitly tested Redis 1.2, and of course many features/commands will be missing at the server.

**Comment by mari3728** [comment]
Yes, I'm observing an issue when using Redis as a backplane for SignalR:

```
System.InvalidOperationException: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   bei Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   bei Microsoft.AspNet.SignalR.Transports.TransportConnectionExtensions.SendCommand(ITransportConnection connection, String connectionId, CommandType commandType)
   bei Microsoft.AspNet.SignalR.Transports.ForeverTransport.<>c__DisplayClass41_0.<ProcessReceiveRequest>b__0()
   bei Microsoft.AspNet.SignalR.Transports.ForeverTransport.<>c__DisplayClass41_0.<ProcessReceiveRequest>b__1()
   bei Microsoft.AspNet.SignalR.Transports.ForeverTransport.ProcessMessages(ITransportConnection connection, Func`1 initialize)
   .....
```

As expected, once it uses the connection for pub/sub, it does not handle other commands, but I'd expect the secondary connection would be used for the other commands and apparently it's trying to use the same connection.

We're currently using StackExchange.Redis version `2.7.33`.

**Comment by mgravell** [comment]
OK; let's gather some info, then.

We have your client version - 2.7.33 - and your server version, 3.0.504, thanks. Can I check some additional things:

- the redis server; the version number is suspiciously Redis-64; can I check: is this vanilla Redis, or is this Redis-64? or Memurai? or something else? and is this self-hosted? or a hosted service (and if so: which one)?
- the web server; which framework and SignalR version is this?
- if you are using Redis yourself at all (which might not be the case if you're just using it as a backplane), are you issuing any commands *manually*, i.e. via the `Execute[Async]` API?
- have you enabled RESP3? (you should not do this for this setup - I'm just thinking the symptom sounds suspiciously similar to #2783)
- finally: is there anything else relevant in play here? for example, are you routing your redis traffic through "envoy", "twemproxy", or any other TCP or Redis-specific proxy?

The library is indeed meant to take care of splitting commands between their correct connections; if that's not happening, something is wrong - let's see if we can figure out what!

(/cc @BrennanConroy just for SignalR visibility; *probably* nothing for SignalR to do here, though)

**Comment by mgravell** [comment]
RESP3 is great when it works; however, Redis 3 absolutely does *NOT* support RESP3. The bug mentioned above will hopefully be addressed quickly - it is not expected to fail in this way.

**Comment by mari3728** [comment]
I did notice, as we log this info after establishing the connection:

```
multiplexer.GetServers().FirstOrDefault().Protocol;
```

That the actual protocol used for the connection was `RESP2` after all, even when trying to set 

```
configuration.Protocol = RedisProtocol.Resp3
```

But perhaps the _attempt_ to use `RESP3` already suffices to cause the issue.

**Comment by mgravell** [comment]
Yes, it is believed that the problem here happens during the *attempt* - basically, we need to defer any subscription code until fully after the handshake has completed successfully and we can see what the discovered setup is.

**Comment by mari3728** [comment]
Hello! Just an update for this issue, indeed when we stop forcing `RESP3` protocol the issue stops happening. Thank you for the support and sorry for the late update! I'll close this as resolved.
