### ISSUE TITLE
ConfigurationOptions.ToString does not add brackets to IPv6 address

### ISSUE THREAD

**Issue by mari3728** [StackExchange/StackExchange.Redis#2811]
Hello!

I'm having an issue when calling `ConfigurationOptions.ToString` method, when my connection string has an IPv6 address.

Just for some context, I'm using Redis as a backplane for SignalR and I parse my original connection string to enhance it. Then, I convert it back to string to pass it to `RedisScaleoutConfiguration` (`Microsoft.AspNet.SignalR.StackExchangeRedis@2.4.3` - I'm using .Net Framework 4.8). 

That's why I need to use `ConfigurationOptions.ToString` method, and I'd expect my connection string IPv6 address to have brackets added to it.

The following example reproduces the behavior:

```csharp
 var connectionString = "[::1]:6379,password=mypass";
 var configuration = ConfigurationOptions.Parse(connectionString);
 configuration.AbortOnConnectFail = false;
 configuration.ClientName = "my-client-name";

 var converted = configuration.ToString();
 Console.WriteLine(converted); //expected [::1]:6379, actual: ::1:6379

 var endpoint = configuration.EndPoints.FirstOrDefault().ToString();
 Console.WriteLine(endpoint); //EndPoint.ToString method correctly adds the brackets
```

From my observation, the `ConfigurationOptions.ToString` method writes the endpoints using `Format` class, which [directly writes](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/Format.cs#L101) the IP address without checking if that's an IPv6 address.

**Comment by mgravell** [comment]
working on it ^^^

**Comment by mari3728** [comment]
Thanks for the swift fix! Is there an ETA for the next release of StackExchange.Redis package?

**Comment by mgravell** [comment]
Actually, [2.8.18](https://www.myget.org/feed/stackoverflow/package/nuget/StackExchange.Redis/2.8.18) is available right now on the myget preview feed (https://www.myget.org/gallery/stackoverflow) - it would be super useful if you're able to try against that build, and check whether it works as you expect (it is the exact same build, as produced by the build-server - just not yet published on NuGet)

**Comment by mari3728** [comment]
I have installed the version mentioned and it works as expected, thank you!
![image](https://github.com/user-attachments/assets/92905d4f-7cf0-49f7-992d-2e4bca91c040)

**Comment by mgravell** [comment]
Great! There's a few hoops to jump through for a "proper" release (tags, release notes, deploys, etc) - shouldn't be long, but you can happily keep using the myget one for now.
