### ISSUE TITLE
Question about keyspace_misses increase by 2 when call ConnectionMultiplexer.Connect

### ISSUE THREAD

**Issue by Huachao** [StackExchange/StackExchange.Redis#283]
I use StackExchange Redis client to connect Azure Redis Cache, I found that each time I call ConnectionMultiplexer.Connect(xxx), using Info stats command, I will see that the keyspace_misses will increase 2.

I don't know why the Connect operation needs to get the key?

**Comment by mgravell** [comment]
An `exists {some guid}` command is issued to confirm connectivity; I expect
this is what is causing the keyspace miss.

On 23 September 2015 at 07:17, Huachao Mao <notifications@github.com> wrote:

> I use StackExchange Redis client to connect Azure Redis Cache, I found
> that each time I call ConnectionMultiplexer.Connect(xxx), using Info stats
> command, I will see that the keyspace_misses will increase 2.
>
> I don't know why the Connect operation needs to get the key?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/283>.
>



-- 
Regards,

Marc

**Comment by Huachao** [comment]
Thanks mgravell, really helpful. I checked the code that since uses tie-breaks which will trigger get command, that's the reason.
