### ISSUE TITLE
Error getting value from 'SslHost' on 'StackExchange.Redis.ConfigurationOptions'. ---> System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by emilyclairelewis42** [StackExchange/StackExchange.Redis#284]
Hello, this may or may not be a proper bug, but when I upgrade to NuGet package 1.0.481 from 1.0.414 many of my unit tests break with the following exception:

> Error getting value from 'SslHost' on 'StackExchange.Redis.ConfigurationOptions'. ---> System.InvalidOperationException: Sequence contains no elements

The root cause appears to be because I have many tests that instantiate RedisCommandDescriptor like so:

```C#
ConfigurationOptions configurationOptionsExpected = new ConfigurationOptions();
```

... set a few sparse properties,and then do a cheap comparison for equality using Json.NET:

```C#
Assert.IsTrue(BsonSerializer.ToBson(configurationOptionsExpected).SequenceEqual(BsonSerializer.ToBson(configurationOptionsObserved)));
```

It would appear that in this version of 1.0.481 a default instance of ConfigurationOptions throws "InvalidOperationException" from SslHost because it's not initialized, so I am forced to set it to an empty string to suppress the test failure.

**Comment by NickCraver** [comment]
Thanks for the report! Fixed for the next release, see the commit above :)
