### ISSUE TITLE
Question List for StackExchange.Redis

### ISSUE THREAD

**Issue by glikoz** [StackExchange/StackExchange.Redis#29]
* Is there any alternative to ServiceStack's Pipeline concept. Or there is no need, because you are pipelining all commands silently?

* I have HashItem class. Is there any function in your library like LoadHashItemFromDb (HashItem[]) ? (the method fills value fields of hashItems)
```
 public class HashItem
    {
        public string HashId { get; private set; }
        public string Key { get; private set; }
        public object Value { get; private set; 
   }
```

* Do you have any benchmark between ServiceStack.Redis and yours?
* This code takes advantage of async performance and sync simplicity ?
```  
public long GetAid(string code)
        {
            var ret = db.StringIncrementAsync("aid:" + code, 1);
            ret.Wait();
            return ret.Result;
        } 
```
PS: As a result: I've started to replace ServiceStack.Redis with yours. 
  - Performance advantage (async api, multiplexer)
  - Continous development (ex:2.8.4 support (Tcp loopback))
  - Free of charge
 
Thanks.

**Comment by NickCraver** [comment]
@glikoz Going through and cleaning up - are you good to go? Can we close this out?
