### ISSUE TITLE
Timeout performing EXISTS

### ISSUE THREAD

**Issue by sgoky** [StackExchange/StackExchange.Redis#291]
Timeout performing EXISTS PARMx82006590796, inst: 0, mgr: ExecuteSelect, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=1,Free=32766,Min=16,Max=32767

How can I fix this?
Thank you.

**Comment by NickCraver** [comment]
Merging with #293 - @sgoky can you add the required timeout details and setup info there please?
