### ISSUE TITLE
Redis on SharePoint

### ISSUE THREAD

**Issue by mstrnaz** [StackExchange/StackExchange.Redis#294]
I am new to redis and have the task of running redis on SharePoint webparts. I was able to run redis from ASP.Net page without any issues.

 When I create a SharePoint project, include StackExchange.Redis.StrongName I get the following error after I compile the code and run it:
 Could not load file or assembly 'StackExchange.Redis.StrongName, Version=1.0.316.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' or one of its dependencies. The system cannot find the file specified.

I am not familiar with this at all. Any help is greatly appreciated.

Nasser Hamdan

**Comment by mgravell** [comment]
Is any inner-exception available with more detail? This is kinda hard to
debug without it. Alternatively, what would I need to do to repro?
(Context: I'm not a SharePoint developer)

**Comment by mstrnaz** [comment]
Marc,

 

After three days of looking, I found out what is going on.

 

I added StackExchange.Redis.StrongName from Nuget.  This installed correctly.  

 

One of the problem with SharePoint sometimes it needs to be told where the dll file is.  In the advanced options of Package.Package, I added the assembly reference to the dll file and it worked fine.

 

Lesson learned.

 

Thank you very much for your response…

 

Nasser Hamdan

**Comment by mgravell** [comment]
Awesome to hear it is sorted, and it would have been outside of my
non-existant SharePoint knowledge to debug that for you!

**Comment by mstrnaz** [comment]
Thanks for all your work.  I am loving it.

 

Nasser

**Comment by NickCraver** [comment]
Closing out to tidy up :)
