### ISSUE TITLE
TwemProxy MGET "Multi-key operations must involve a single slot" exceptions

### ISSUE THREAD

**Issue by Rodrigo-Andrade** [StackExchange/StackExchange.Redis#296]
When i comment:

https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis/StackExchange/Redis/ServerSelectionStrategy.cs#L94-L104

Everything seems to work fine, why isn't MGET with TwemProxy  allowed?

**Comment by mgravell** [comment]
Because until fairly recently, it wasn't supported in twemproxy - see this commit: https://github.com/twitter/twemproxy/commit/f6cc55bc8cd27bd4c47b8b60c048d65449f2fb6d#diff-97c9e5b674e7b2a4959e3a73ea9cdbe9

Now that this has changed, I would welcome a PR fixing it, or I can add it to my backlog - should just be a case of adding MGET to the allowed sub-set of commands.

**Comment by mgravell** [comment]
(ignore previous comment, I was confusing with MSET - still looking)

**Comment by mgravell** [comment]
Indeed, [redis.md](https://github.com/twitter/twemproxy/blob/master/notes/redis.md) indicates it is supported; if it works fine, I'd be happy to take a PR or I can add it to my backlog. There are some questions that should be investigated, though; in particular, does this always work? or does it work by coincidence on your test  keys. For example, if you loop over 10,000 pairs of guids:

    for(1-10000) {
        Guid a = {rand}, b = {rand};
        var got  = mget(a,b);
    }

does that work? If so, I would assume that the remark:

> only vectored commands 'MGET key [key ...]', 'MSET key value [key value ...]', 'DEL key [key ...]' needs to be fragmented

means that only `MGET`/`MSET` have internal "split the things" logic, in which case the `ServerType.Twemproxy` && ( `RedisCommand.GSET` || `RedisCommand.MSET` ) should be a special-case.

**Comment by mgravell** [comment]
[This discussion](https://groups.google.com/forum/#!topic/redis-db/bwuWatW5tiA) further supports that this is handled internally inside twemproxy, so; agree - the client should allow that to be deferred to twemproxy.

**Comment by Rodrigo-Andrade** [comment]
We currently use an older version of servicestack.redis, and it works fine with MGET, so i don't see a reason for it to fail here, since it looks like twemproxy handles it transparently.

**Comment by NickCraver** [comment]
Tagging for #528 tracking - since we're shifting bits in 2.0, we'll take a look at this one.

**Comment by NickCraver** [comment]
Commit above, now fixed for v2!
