### ISSUE TITLE
[Newbie] Fail to use StackExchange.Redis for NET4.0

### ISSUE THREAD

**Issue by Gavin-VTech** [StackExchange/StackExchange.Redis#297]
Hi All,

  I am new in using StackExchange.Redis (and Redis). And I have met difficulties in using the client.

  My development environment is VS2010(SP1) on Windows 7(32-bit), NET4.0 installed. Redis Server was running locally with default port. The Redis Server was the version 2.4.x for Windows (32-bit)

  I had tried to create a simple C# console application, installed the StackExchange.Redis with PackageManager. Everything went fine to this point.

  I had written simple code to connect to Redis Server, code as below:

``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using StackExchange.Redis;

namespace RedisTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var conn = ConnectionMultiplexer.Connect("localhost:6379");

            int i = 0;
        }
    }
}
```

> A exception was thrown when the code was reached the line of Connect(). The error told there was "No Source Available".

Did I miss any essential step in setting up the environment?

**Comment by nbarbettini** [comment]
If you open up your Command Prompt and run:
```
redis-cli ping
```
do you see `PONG`?

**Comment by news4vip** [comment]
I also it's similar
*Mac OS X 10.10.5
*Mono 4.2.1 
*Redis 3.0.4  64 bit (install from homebrew)


    $ redis-cli 
    127.0.0.1:6379> ping
    PONG

but

    using System;
    using System.Collections.Generic;
    using StackExchange.Redis;

    class MainClass
    {
        public static void Main(string[] args)
        {
            var cn = ConnectionMultiplexer.Connect("localhost");
        }
    }

StackExchange.Redis.RedisConnectionException
It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. UnableToResolvePhysicalConnection on PING

**Comment by mgravell** [comment]
Can you try instead: Connect("127.0.0.1")

?

On 30 November 2015 at 07:45, ニュース速報(VIP) <notifications@github.com> wrote:

> I also it's similar
> *Mac OS X 10.10.5
> *Mono 4.2.1
> *Redis 3.0.4 64 bit (install from homebrew)
>
> $ redis-cli 127.0.0.1:6379> ping
> PONG
>
> but
>
> using System;
> using System.Collections.Generic;
> using StackExchange.Redis;
>
> class MainClass
> {
>     public static void Main(string[] args)
>     {
>         var cn = ConnectionMultiplexer.Connect("localhost");
>     }
> }
>
> StackExchange.Redis.RedisConnectionException
> It was not possible to connect to the redis server(s); to create a
> disconnected multiplexer, disable AbortOnConnectFail.
> UnableToResolvePhysicalConnection on PING
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/297#issuecomment-160546205>
> .
>



-- 
Regards,

Marc

**Comment by news4vip** [comment]
A build was done from source code.
That was no problem.

NuGet edition may be a broken.

Build
  Xamarin Studio 5.10 (build 871)
  Mono 4.2.1
  
NuGet
  StackExchange.Redis 1.0.488

**Comment by mgravell** [comment]
Ah, I don't think the NuGet package currently contains the various monikers
for mono and xamarin; I will see if we can do something about that.

On 1 December 2015 at 01:27, ニュース速報(VIP) <notifications@github.com> wrote:

> A build was done from source code.
> That was no problem.
>
> NuGet edition may be a broken.
>
> Build
> Xamarin Studio 5.10 (build 871)
> Mono 4.2.1
>
> NuGet
> StackExchange.Redis 1.0.488
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/297#issuecomment-160817336>
> .
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment]
Tagging this coreclr because it's a good candidate for fixing with the new `project.json` layout.

**Comment by NickCraver** [comment]
Update on the above: .NET 4.0 support works correctly in the 1.1.608 release (and a few before) but was bugged for a while. We will be dropping .NET 4.0 support in the 2.x line though, for sanity sake. But you can continue to reference the 1.x line from NuGet for .NET 4.0 support.

Closing out just to cleanup - feel free to ask any followups.
