### ISSUE TITLE
ConnectionMultiplexer.GetDatabase is not retrocompatible anymore

### ISSUE THREAD

**Issue by mfelicio** [StackExchange/StackExchange.Redis#299]
Hi, 

The change on https://github.com/StackExchange/StackExchange.Redis/commit/0c7dd1468b9da5658fd8937dd308fd5589fe3755 broke retrocompatiblity for GetDatabase method, by changing a public constant value, thus breaking existing code that was compiled with the old constant value. In this case, the default db index argument.

If you use a lib that is compiled with a StackExchange.Redis version that uses db=-1 as default, but your application is running with an older version of StackExchange.Redis, then it will always throw an ArgumentOutOfRangeException.

It's generally a bad idea to have public constants and modify its values later, because you have to recompile all assemblies that use your lib in order to use the new const value. Default values for method arguments are public constants.

There should be a note somewhere recommending to upgrade package.

**Comment by mgravell** [comment]
If your application is running with an older version of the library to that
against which it was compiled, you're kinda already in a world of hurt...
just sayin'

We did put some thought into this, and I was content that the opposite
scenario - the supported one - is safe and reliable, specifically: running
against a *newer* version (at runtime) to the version against which you
compiled.

I'm not sure that "running with an older version that the one you compiled
for" is a scenario we need to try to support; ultimately you could also
instantly get missing type/method exceptions doing that.

**Comment by mfelicio** [comment]
Yes, of course. Once we spotted this we immediately updated the package and now we're running with the newer version. But we were already happy with our current StackExchange.Redis version so didn't feel the need to upgrade it, until we recently added a reference to a new library that was compiled against the newer version of StackExchange.Redis and it wasn't working.

This is a breaking change, and it's perfectly reasonable not to support this scenario in order to evolve the library to a desired state. However, others might run into this issue and it may not be immediately clear what the problem is. Calling a method that has a default value of -1 and it throws an IndexOutOfRangeException.. at first glance it would indicate it's a bug in the code.. especially when it happens inside an external library you don't control.

**Comment by mgravell** [comment]
It is perhaps a subtle scenario, but by compiling against version X, you are implicitly taking a dependency on running against version "X or above" - a very similar scenario would apply with many things - for example overload resolution. I accept that is perhaps a little more open to hard-to-detect errors than a few changes, and your point is noted. I'm in the process of building the next set of releases (for coreclr, etc) - I'll try to make sure we call this out in the release notes at the same time. Beyond that, in terms of the actual change: that ship has already sailed.  But hopefully release notes should be possible.

**Comment by mfelicio** [comment]
Yeah, I think that should do, thanks :)

I think the problem we had is because our external dependency that was compiled against the newer version of StackExchange.Redis was a nuget package that didn't specify that version as its dependency, and as such our pacakge manager didn't upgrade the StackExchange.Redis package to the expected version.

**Comment by mgravell** [comment]
Ah, yes. I can see how that would be unfortunate. However, I think the
ultimate failing here was the component not updating its dependency list.
There are a myriad other ways this could have exploded  - admittedly most
of them would be more immediate and obvious (missing method / type
exceptions, primarily)

**Comment by mgravell** [comment]
Additional thought - this is one thing I like in particular about the new
core-clr build system: there is no nuspec to have to maintain, and the
build tool always declares the correct dependencies. We will be moving
SE.Redis to the new build tools shortly, but to have helped here it would
need to be the component you are using that updated to the new tooling.

Might I ask what that tool was, so I can check their core-clr status? If it
is an internal component or you'd simply rather not say: that is fine too.

**Comment by mfelicio** [comment]
Yes, it's an internal component that is published to an internal nuget repository. So a developer updated its version (and the packages it uses) but forgot to update the nuspec file with the new versions for all dependencies. However, I can see this happening very easily on the public nuget repository.

The new build system sounds very promising. I think we can close this issue now.
