### ISSUE TITLE
Script execution on redis-cluster reports "Lua script attempted to access a non local key in a cluster node"

### ISSUE THREAD

**Issue by BojanSerbula** [StackExchange/StackExchange.Redis#305]
What do I need to add to the connection string or ConfigurationOptions to connect to Redis using cluster mode ( -c command parameter in redis cli console) ? 
On this page (https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Configuration.md) it is stated that it is possible to map commands into any other name enable or disable command, but not how to set the value in the command.

**Comment by spuder** [comment]
Here is my config for IIS inside the web.config
```xml
<sessionState customProvider="RedisSessionStateStoreProvider" mode="Custom" timeout="90">
    <providers>
        <add name="RedisSessionStateStoreProvider" type="RedisAspNetProviders.SessionStateStoreProvider,RedisAspNetProviders" connectionString="10.10.10.10:6379,10.10.10.11:6379,10.10.10.12:6379,10.10.10.13:6379,10.10.10.14:6379,10.10.10.15:6379,5000,abortConnect=false,ssl=false" />
    </providers>
</sessionState

```

**Comment by mgravell** [comment]
The -c is specifically for redis-cli, a command-line tool. SE.Redis does
not use redis-cli. What happens currently? The library *should* normally be
able to detect a cluster without prompting.

**Comment by BojanSerbula** [comment]
Redis is set to run in cluster mode and I am trying to execute the simplest command ever :
redis.call('SET','t1', 't2')

I get an error
ERR Error running script (call to f_2c860e0e74b0b8b2bfdcbfb81b2ca7d18639017b): @user_script:1: @user_script: 1: Lua script attempted to access a non local key in a cluster node.

When I connect to redis using redis-cli and cluster mode, everything works fine.

In my connection string I have tried setting only one or than one node. I have also tried with PublishReconfigure() after connecting, just in case.

**Comment by mgravell** [comment]
In cluster mode, **that is explicitly not valid**. The call to ScriptEvaluate has a parameter to tell it about keys; you *must* use this, so that it can choose the correct node to issue the call to. If you aren't specifying any keys, it chooses arbitrarily. For more context on this, please see the redis documentation:http://redis.io/commands/eval

The fix should be simple, though:

    db.ScriptEvaluate("redis.call('SET', KEYS[1], 't2')", new RedisKey[] { "t1" }, null);

This  is actually remarkably similar to the example in the redis documentation:

>     > eval "return redis.call('set','foo','bar')" 0
>
> The above script sets the key foo to the string bar. However it violates the EVAL command semantics as all the keys that the script uses should be passed using the KEYS array:
>
>     > eval "return redis.call('set',KEYS[1],'bar')" 1 foo

More typically, you would actually specify the value as an argument, too; that  is the second parameter to the method-call, and `ARGV` inside the script.

Note that there is also a secondary script API in SE.Redis that simplifies this, using anonymous types and named parameters - it works a lot like "Dapper", if you're familiar with that library.

**Comment by mgravell** [comment]
I should also note that if you use the simpler and more typical `db.StringSet("t1", "t2");` it should get this right for you automatically.

**Comment by mgravell** [comment]
Has this helped? Is your script now working? Can I close this?

**Comment by BojanSerbula** [comment]
Thank you for the information. Your answer did help. The other thing is that before running in cluster mode we had a lua script with a for loop which is not running now because of this error. We tried to solve this by making a long script with multiple redis.call("HINCRBYFLOAT", ...   ) calls with keys and values stated explicitly but that is not possible as you well explained.
We can make multiple scripts and run them separately, but in that case we need to implement some kind of manual rollback which is pretty coding. Is there a way we can still have transactions with all this in mind?

**Comment by mgravell** [comment]
@BojanSerbula  sorry, I missed your reply. I'm not sure I understand the question, but:

- whenever possible, parameterize all scripts and use KEYS[...] etc
- if keys are on different servers, you'll need to execute them separately
- redis cluster has no notion of a transaction that spans multiple nodes, so if you need something there: you'll need to implement it manually

**Comment by NickCraver** [comment]
@BojanSerbula are you all set the the info above? If so I'll close this out to tidy up.

**Comment by BojanSerbula** [comment]
Thank you very much for your help and for the info. It helped a lot. Besides the initial problem there was also problem in the redis setup. All fine now, you can close this one.
