### ISSUE TITLE
SortedSetRangeByScoreAsync not respecting limit/take?

### ISSUE THREAD

**Issue by mattmazzola** [StackExchange/StackExchange.Redis#307]
When I access data through the C# client such as:
`var value = (await cache.SortedSetRangeByScoreAsync("testkey", 0, double.PositiveInfinity, Exclude.None, 0, 10))`
I would still get back more then 10 results even though I specified a limit / take parameter of 10.
I'm essentially trying to get the first 10 items of the set.

If I execute the equivalent command directly through the redis command line:
`zrangebyscore "testkey" 0 Inf limit 0 10`
I get back only 10 results as expected.

This seems like a really fundamental thing for the client to do so I'm assuming I'm using the client wrong, but I don't see how else to set the limit as 10.

Is there something else I need to configure in one of the parameters to `SortedSetRangeByScoreAsync` ?

**Comment by mgravell** [comment]
That sounds like a bug; will check; I've given GetSortedSetRangeByScoreMessage
a quick eyeball, and I couldn't see anything too crazy - I'll have to spin
it up to see what is going on there.

On 20 November 2015 at 01:32, Matt Mazzola <notifications@github.com> wrote:

> When I access data through the C# client such as:
> var value = (await cache.SortedSetRangeByScoreAsync("testkey", 0,
> double.PositiveInfinity, Exclude.None, 0, 10))
> I would still get back more then 10 results even though I specified a
> limit / take parameter of 10.
>
> If I execute the equivalent command directly through the redis command
> line:
> zrangebyscore "testkey" 0 Inf limit 0 10
> I get back only 10 results as expected.
>
> This seems like a really fundamental thing for the client to do so I'm
> assuming I'm using the client wrong, but I don't see how else to configure
> the call so that the limit is 10.
>
> Is there something else I need to configure in one of the parameters to
> SortedSetRangeByScoreAsync ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/307>.
>



-- 
Regards,

Marc

**Comment by mattmazzola** [comment]
As expected, I found the error was with my code not the library. I skipped the `Order.Ascending` argument in the call, and 0 was accepted as a value so there was no compile error. Then 10 was unintentionally set as the offset and take defaulted to -1 which meant there is no limit hence why I was receiving more than 10 results.

Incorrect:
`cache.SortedSetRangeByScoreAsync("testkey", 0, double.PositiveInfinity, Exclude.None, 0, 10)`
Correct:
`cache.SortedSetRangeByScoreAsync("testkey", 0, double.PositiveInfinity, Exclude.None, Order.Ascending, 0, 10)`

**Comment by mgravell** [comment]
ah yes; the "0 is valid as any enum" feature of C#. A brutal trap for the
unwary!

On 23 November 2015 at 23:02, Matt Mazzola <notifications@github.com> wrote:

> As expected, I found the error was with my code not the library. I skipped
> the Order.Ascending argument in the call, and 0 was accepted as a value
> so there was no compile error. Then 10 was unintentionally set as the
> offset and take defaulted to -1 which meant there is no limit hence why I
> was receiving more than 10 results.
>
> Incorrect:
> cache.SortedSetRangeByScoreAsync("testkey", 0, double.PositiveInfinity,
> Exclude.None, 0, 10)
> Correct:
> cache.SortedSetRangeByScoreAsync("testkey", 0, double.PositiveInfinity,
> Exclude.None, Order.Ascending, 0, 10)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/307#issuecomment-159095497>
> .
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment]
That's such a bullshit feature - I maintain the framework is just plain stupid on that one.

**Comment by mgravell** [comment]
Technically that's a compiler / language issue, not the framework, but your
point is very valid. The usual `default(SomeEnumType)` should have been
fine, and would avoid such issues.
