### ISSUE TITLE
Is it possible to send an array to stored lua script in redis server?

### ISSUE THREAD

**Issue by kobynet** [StackExchange/StackExchange.Redis#308]

**Comment by mgravell** [comment]
Fair question. The protocol supports the concept of arrays as sub
parameters, although I don't think they are actively used anywhere in the
client->server direction (they are definitely uses in the server->client-
direction).

Short version: I don't know. I would have to investigate.

**Comment by kobynet** [comment]
Thanks @mgravell , i am wondering if this is not a common scenario for querying multiple keys, for example retrieving multiple results of PFCOUNT on multiple keys etc.

**Comment by mgravell** [comment]
The protocol doesn't currently allow this, basically. If RESP2 adds support, we can reconsider.
