### ISSUE TITLE
Synchronous events are delivered asynchronously

### ISSUE THREAD

**Issue by paveliak** [StackExchange/StackExchange.Redis#31]
ConnectionMultiplexer may deliver notifications about connection failure (and some other infrastructure errors). In some scenarios it might be important to process these notifications synchronously or client may blindly start working with the different Redis instance (e.g. if crashed server was automatically restarted).

Internally StackExchange tries to deliver "connection failed" synchronously by invoking ConnectionMultiplexer.TryCompleteHandler(,,,. false /\* isAsync*/). However it looks like isAsync is not handled correctly inside TryCompleteHandler(). In fact "isAsync == true"  does synchronous processing while isAsync == false just returns control to the caller hence triggering asynchronous event processing.

Should it be "if (NOT isAsync)" here?

```
        if (isAsync)
        {
            foreach (EventHandler<T> sub in handler.GetInvocationList())
            {
                try
                { sub.Invoke(sender, args); }
                catch
                { }
            }
            return true;
        }
        return false;
```

**Comment by NickCraver** [comment]
@paveliak I think I understand your scenario, so let's break it down. This all comes down to dependencies; at a basic level if you're restarting redis in the middle of transactions and you're losing your atomic locking mechanism and there's really no sanely handling that no matter how many safeguards we put in place.

If you were using transactions, in the transaction itself you can make sure you own the lock. That'd be the proper point here - as close to the atomicity as possible you want the most assurance of atomic behavior.
