### ISSUE TITLE
Throwing error on connection open

### ISSUE THREAD

**Issue by prathapreddy123** [StackExchange/StackExchange.Redis#323]
Hi,

I installed stackexchange through nuget package in a .Net 4.0 Console application. My redis server is running on my local host on default port 6379. When I try to connect using below code
 var conn = ConnectionMultiplexer.Connect("localhost");

 it throws an error: 
> Method System.Runtime.CompilerServices.AsyncTaskMethodBuilder1[System.Boolean].AwaitUnsafeOnCompleted:
type argument 'Microsoft.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter[StackExchange.Redis.ServerEndPoint]' violates the constraint of type parameter 'TAwaiter'.

can someone help me what is the issue?

Thanks,
prathap

**Comment by NickCraver** [comment]
Which version of the NuGet package are you on?

**Comment by prathapreddy123** [comment]
This issue is resolved and root cause is version mismatch, Thanks.
