### ISSUE TITLE
Timeout performing HGETALL 2.2:CallState:2DE78EC8AE7C4DF88917C0B2FE76E556, inst: 2, mgr: ProcessReadQueue, err: never, queue: 59, qu: 0, qs: 59, qc: 0, wr: 0, wq: 0, in: 65536, ar: 1, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=1020,Min=4,Max=1023), 

### ISSUE THREAD

**Issue by guntergunter** [StackExchange/StackExchange.Redis#326]
I know similar issues have been around but I can't seem to find a solution:
I am frequently getting such timeouts when running my VSTest unit tests. Everything is local on the same machine, no load at all, SLOWLOG shows nothing. 
StackExchange.Redis: 1.0.481
Windows Redis Server: 2.8.17
Code uses TPL, ConfigureAwait(false) and Connection.PreserveAsyncOrder = false;
based on other comments in: 65536 means that incoming messages are not getting processed and 59 requests are waiting in the queue.

What is going on? Your help is appreciated.

**Comment by mgravell** [comment]
That's super odd. Data on the socket, an active reader - looks stalled in ProcessReadQueue. 59 items waiting on replies... hard to grok, but will have a look at ProcessReadQueue.

**Comment by guntergunter** [comment]
Hi Marc,

Please let me know if there is anything else I can provide.

Here is another instance. This time I tried it against the latest Windows Redis 3.0.500.

Timeout performing HGETALL 2.2:CallState:99832CA4-85CD-4155-A538-B7AC12FCC859, inst: 1, mgr: ProcessReadQueue, err: never, queue: 15, qu: 0, qs: 15, qc: 0, wr: 0, wq: 0, in: 19663, ar: 1, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=0,Free=1023,Min=4,Max=1023), clientName: VENUS2

Regards,

Gunter

**Comment by NickCraver** [comment]
Related to #450 but this one's a local queue issue, so not merging in.

**Comment by NickCraver** [comment]
A ton or reader fixes since this was created on the inbound reader - closing out to cleanup.
