### ISSUE TITLE
Open work items in CoreClr port

### ISSUE THREAD

**Issue by jeremymeng** [StackExchange/StackExchange.Redis#328]
This is for #202.

Open issues
- [x] Performance issues
  - [x] Currently `BufferedStream` isn't available in .Net Core yet. @mgravell added an implementation of buffered write stream for now.
  - [ ] When running `MassiveBulkOpsSync(bool preserveOrder, int threads)`, increasing number of threads doesn't help much on the .Net Core port, not like the original code.
- [ ] Re-visit `Type.GetTypeCode(Type)` after moving to RC.
- [x] The dnx test project is a console-based project because it's the only supported way at this point.  NUnit will be adding a dnx console runner and VS integration.
  - [x] There's also an issue that causes the dnx process to crash when running tests (https://github.com/nunit/nunit/issues/1131)
- [x] `Moq` based tests are all passing using a private build of package that supports .Net Core, but currently disabled for dnx test project.  It can be re-enabled by defining `FEATURE_MOQ` in `project.json`.
- [x] We were not able to run the following tests as they require special setup.
  - SSDB
  - SSL
  - VPNTest

@mgravell 
CC @rustd @deepakverma @rogerbestmsft

**Comment by NickCraver** [comment]
TODO: Re-visit when RC2 lands, a few of these are in it.

**Comment by NickCraver** [comment]
Note: `GetTypeCode()` is landing: https://github.com/dotnet/corefx/issues/5381

**Comment by davunderscorei** [comment]
Hey, any update on this?

**Comment by gzpbx** [comment]
Any update ? We are waiting for this.

**Comment by NickCraver** [comment]
Closing this out since we're on `netstandard` now.
