### ISSUE TITLE
GetHashCode stability

### ISSUE THREAD

**Issue by johnnycardy** [StackExchange/StackExchange.Redis#333]
A hash code method is stable if it returns the same values reliably outside the current app domain. In particular, [.NET's GetHashCode is not stable](https://msdn.microsoft.com/en-us/library/system.string.gethashcode(v=vs.110).aspx).

`RedisValue` is unstable when it's an `int`:
 - when `valueBlob == IntegerSentinel`, `int.GetHashCode()` is returned which is unstable
 - otherwise a custom stable hash algorithm is used

`RedisKey` is unstable when it's a `string`:
 - `GetHashCode` combines two parts - the aforementioned custom stable hash algorithm of `RedisValue`, and when `RedisKey` is a `string`, `string.GetHashCode()` which is unstable.

My questions are:
- why is the implementation of RedisKey different from RedisValue?
- why is the custom RedisValue.GetHashCode(byte[] value) function not always used to provide stability all the time?
- are there backwards compatibility issues in changing the behaviour?

**Comment by mgravell** [comment]
It is not required that a hash-code be stable between app-domains. There is
no valid use of GetHashCode() that would require that. SE.Redis does not
intentionally aim to be unstable across app-domains, bit it also doesn't
explicitly attempt to be stable between them.

The byte[] method is not always used specifically because the data is not
always a byte[].

There is no expectation for GetHashCode() to remain equal between runs, so
no: there are no backwards compatibility issues with changing the
implementation. However, I would want to see an actual real-world
justification before attempting (or merging) any changes.

**Comment by mgravell** [comment]
Note: a far more compelling discussion for any changes would be the
equality rules for (as an example) a key of value that has been expressed
separately from an int, from a string, and from a byte[] of ASCII, all
representing the same numerical value.

**Comment by johnnycardy** [comment]
Thanks Marc for the detailed reply. I understand that there's no expectation for hash codes to ever be stable, but it would be a bonus to me if they were, and they very *nearly* are - all we'd need to do it get the byte[] for the data if it isn't already byte[]. Maybe that'd be too much of a performance impact but I doubt it.

My real-world scenario is this: I'm caching a set in-memory. When a value is removed from the set in Redis, I need to know when to remove it from my in-memory set. The `srem` keyspace notification doesn't say what value it is, so I'm publishing a custom event containing a hashcode of the value. I've published my solution here and feedback is more than welcome: https://github.com/johnnycardy/StackRedis.L1

With regard to equality - I'd imagine the hash code for a string should be the same as the byte[] of ascii, and int should be different...unless I misunderstand what you mean!

**Comment by mgravell** [comment]
I wonder if the answer in your case is a custom
`IEqualityComparer<Whatever>` that you pass to whichever container you are
using for state. This can then cast things out as `byte[]` or whatever you
need, and apply a stable hash/compare, without impacting the core library.

**Comment by johnnycardy** [comment]
That's pretty much what I've implemented and it's working nicely. Cheers.

**Comment by NickCraver** [comment]
@johnnycardy do you want to pursue this anymore? The `byte[]` changes when comparing very large lists can be a very significant overhead in allocations (and GC), so I'd also be very hesitant to add weight here for such a rare use case when there's another approach.

**Comment by johnnycardy** [comment]
I agree and don't think changing GetHashCode is of general benefit - it works as people would expect. Thanks.
