### ISSUE TITLE
Transaction deadlocks with multiple ConnectionMultiplexers

### ISSUE THREAD

**Issue by rossipedia** [StackExchange/StackExchange.Redis#336]
Setup: 2 instances of redis on localhost, one on port 6379, the other 6385

Trying to do a straight key copy from one instance to the other, using DUMP/RESTORE.

I first noticed this in an ASP.NET app, but was able to repro it with the following code in LINQPad:

``` csharp
using (var redis = ConnectionMultiplexer.Connect("localhost:6385"))
using (var otherRedis = ConnectionMultiplexer.Connect("localhost:6379"))
{
	var srcDb = redis.GetDatabase();
	var dstDb = otherRedis.GetDatabase();

	var serialized = await srcDb.KeyDumpAsync("Foo");
	
	var tran = dstDb.CreateTransaction();
	
	await tran.KeyDeleteAsync("Foo"); // <- deadlock here
	await tran.KeyRestoreAsync("Foo", serialized);
	
	await tran.ExecuteAsync();
}
```

I've tried adding `ConfigureAwait(false)`, as well as removing the `await` from the transaction operations (`KeyDeleteAsync` and `KeyRestoreAsync`).

**Comment by mgravell** [comment]
that's because you can't `await` something that hasn't been sent to the server yet. You *can* check afterwards, though, to see what happened. For example:

    var del = tran.KeyDeleteAsync("Foo"); // <- deadlock here
    var restore = tran.KeyRestoreAsync("Foo", serialized);

    await tran.ExecuteAsync();
    bool wasDeleted = await del;
    await restore; // to check for error messages

You **must** wait until after the `Execute[Async]` to check the replies of operations inside the transaction. Also, if you have *conditions* (which: you don't) - you should check the result of the `Execute[Async]` too: if that is `false`, it got aborted internally.

**Comment by mgravell** [comment]
See also: https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Transactions.md

**Comment by mgravell** [comment]
It would be nice if there was some way I could signal to the TPL "throw a fit if someone tries to call `GetAwaiter()`", but: I haven't yet found a way of doing that.

**Comment by rossipedia** [comment]
I swear I had tried that before, but this time it worked. PEBCAK

Thanks!
