### ISSUE TITLE
Timeout getting cluster info on DNX Core only

### ISSUE THREAD

**Issue by MichaCo** [StackExchange/StackExchange.Redis#337]
Hi,
I was just going to test the alpha builds running on DNX Core. Great job btw! 
While running a very simple text console app against a Redis CLUSTER, I encountered one issue during the initial connect.

According to the log, it cannot retrieve the cluster information:
`Encountered error while updating cluster config: Timeout performing CLUSTER`

After that, `StringSet` etc works perfectly fine though!
And running the same code on .Net Framework also works without timeouts!

Something to note though, the environment are 3 Ubuntu VMs running 4 instances of Redis each and I'm trying to run the code from Windows.

Will be trying to run the code on one of the Linux VMs, what could go wrong ;)
Let me know if you need more information or if I can help

**Comment by mgravell** [comment]
There are a number of recent changes that may be related to this. I have
deployed 553 to nuget, but this does not include the DNX build (mainly: I
haven't updated our build / deploy tools). I will do a manual alpha build
later today including the DNX bits. If you could retry with that, I'd be
grateful.

**Comment by MichaCo** [comment]
Surething.
Is the core running for you on linux? On mono or core clr?
For me, on mono it cannot connect to the endpoint. And on coreclr I'm getting:

	micha@Ubuntu-Node-A:~/Public/src/Console$ dnvm upgrade -u -r coreclr
	Determining latest version
	Latest version is 1.0.0-rc2-16357
	dnx-coreclr-linux-x64.1.0.0-rc2-16357 already installed in /home/micha/.dnx
	Adding /home/micha/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-rc2-16357/bin to process PATH
	Updating alias 'default' to 'dnx-coreclr-linux-x64.1.0.0-rc2-16357'
	micha@Ubuntu-Node-A:~/Public/src/Console$ dnx run
	192.168.178.32:7000

	Connecting 192.168.178.32:7000/Interactive...
	Connect 192.168.178.32:7000/Interactive failed: Operation is not supported on this platform.
	System.PlatformNotSupportedException: Operation is not supported on this platform.
	   at System.Net.Sockets.SocketPal.Ioctl(SafeCloseSocket handle, Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue, Int32& optionLength)
	   at System.Net.Sockets.Socket.IOControl(Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
	   at StackExchange.Redis.SocketManager.BeginConnect(EndPoint endpoint, ISocketCallback callback, ConnectionMultiplexer multiplexer, TextWriter log)
	   at StackExchange.Redis.PhysicalConnection.BeginConnect(TextWriter log)
	   at StackExchange.Redis.PhysicalBridge.GetConnection(TextWriter log)
	   at StackExchange.Redis.ServerEndPoint..ctor(ConnectionMultiplexer multiplexer, EndPoint endpoint, TextWriter log)
	   at StackExchange.Redis.ConnectionMultiplexer.<ReconfigureAsync>d__115.MoveNext()

**Comment by MichaCo** [comment]
@mgravell after manually building the main branch, the above error is fixed (see also https://github.com/StackExchange/StackExchange.Redis/pull/338)

Bad news is, on Linux and Windows running coreclr, the basic stuff works but I'm still getting that Cluster information timeout in `GetEndpointsFromClusterNodes` :crying_cat_face:.

**Comment by MichaCo** [comment]
@mgravell After some more testing I found something fishy with synchronized implementation (still with .net core only). 
Still not 100% sure what exactly, but when I change `EndPointCollection GetEndpointsFromClusterNodes` to be async and await `ExecuteAsyncImpl` instead of calling `ExecuteSyncImpl` it just works without timeout and it receives the cluster configuration just fine.
So my assumption is a deadlock somewhere

**Comment by mgravell** [comment]
Hmmm; k, thanks for reporting. Will have to add to my list.

On 19 January 2016 at 20:37, MichaC <notifications@github.com> wrote:

> @mgravell <https://github.com/mgravell> After some more testing I found
> something fishy with synchronized implementation (still with .net core
> only).
> Still not 100% sure what exactly, but when I change EndPointCollection
> GetEndpointsFromClusterNodes to be async and await ExecuteAsyncImpl
> instead of calling ExecuteSyncImpl it just works without timeout and it
> receives the cluster configuration just fine.
> So my assumption is a deadlock somewhere
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/337#issuecomment-172978550>
> .
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment]
@MichaCo thanks for the pointer here - fix is in `master`
