### ISSUE TITLE
 Timeout performing GET inst: 1, mgr: ProcessReadQueue, err: never, queue: 3, qu: 0, qs: 3, qc: 0, wr: 0, wq: 0, in: 7, ar: 1

### ISSUE THREAD

**Issue by tamnm** [StackExchange/StackExchange.Redis#341]
We using StackExchange.Redis v1.0.488 in Amazon Cloud server
and sometime it throw exception
Timeout performing GET {KEY}, inst: 1, mgr: ProcessReadQueue, err: never, queue: 3, qu: 0, qs: 3, qc: 0, wr: 0, wq: 0, in: 7, ar: 1, IOCP: (Busy=13,Free=987,Min=4,Max=1000), WORKER: (Busy=12,Free=2035,Min=4,Max=2047)

Is there any solution to resolve the issues?

**Comment by MichaCo** [comment]
I'm not sure if that's the best approach, but I'd just **retry*** the command. 
I receive timeouts from time to time, could be basically anything, the server, network load, what ever... Retry a few times usually always works (also if a fail-over happens for example)

**Comment by NickCraver** [comment]
What are your timeouts set to? Amazon's network is notoriously bad, so there may be little we can do here...but let's see.

**Comment by GoodMirek** [comment]
We experience the same issue. It seems similar to #351.
It is very often accompanied / followed by bunch of exceptions:
SocketFailure on GET

Have you found any root cause / solution / workaround or proof that the issue is caused by AWS network?

**Comment by NickCraver** [comment]
Merging into #450 so we can track these in one place.
