### ISSUE TITLE
Diagnosing Azure Redis Timeouts

### ISSUE THREAD

**Issue by benfoster** [StackExchange/StackExchange.Redis#345]
Hey guys,

We're trying to investigate timeouts with an Azure Redis C1 Instance from an Azure Web site hosted in the same data centre (North Europe).

I've already been in contact with the Azure Redis team who advised increasing the IOCP and Worker min thread settings, which we did but it did not appear to make any difference. [This log](https://gist.github.com/benfoster/6e2a76e9499964f33b79) from last night shows that we never have more busy threads than the min threads (currently set to 100). 

The load on the Redis server seems minimal, as does the Azure Web Site. I've attached the performance charts for Redis below, in case I'm missing anything obvious.

[This article](https://azure.microsoft.com/en-gb/blog/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/) suggests we may experience timeouts if we get network bound on the server/client, but 250kbps hardly seems like a lot of bandwidth.

![redis-stats](https://cloud.githubusercontent.com/assets/827305/12581975/08f4b02e-c432-11e5-8add-9e2156ebf5b8.png)

**Comment by NickCraver** [comment]
When the issue occurs, is there a corresponding entry in SLOWLOG on the redis side?

**Comment by benfoster** [comment]
We found that was caused by CPU spikes caused by another Azure Web App in the same App Service Plan. After moving this app onto a different server (service plan) we stopped receiving timeouts. So it seems, the timeouts were genuine caused by us thrashing the CPU,
