### ISSUE TITLE
Strange Issue with ResponseToCompletion, SentToResponseTime

### ISSUE THREAD

**Issue by aaronmell** [StackExchange/StackExchange.Redis#346]
I found what may be a bug in the profiler.

![image](https://cloud.githubusercontent.com/assets/490702/12650718/780a29bc-c5a9-11e5-9804-e21b30abd048.png)

Total Elapsed Time looks normal for these entries, but there is something strange going on with the RTC and STR time values.

**Comment by NickCraver** [comment]
Agree it looks like `SetResponseReceived()` isn't getting called in this scenario - resulting in a 0 for that field and throwing off the last 2 columns and `Ticks - 0` and `0 - Ticks` looking like crazy numbers. That's a bug, will fix.

**Comment by NickCraver** [comment]
This one is good go to since last update - and we have unit tests in place to confirm now (though they are currently broken on *another* front). These will be all set in v2.0, but are already good in 1.2.6.
