### ISSUE TITLE
Why does IConnectionMultiplexer not inherit from IDisposable?

### ISSUE THREAD

**Issue by TomFreeman** [StackExchange/StackExchange.Redis#347]
It has a Dispose method on it, is there a reason it's not IDisposable?

**Comment by NickCraver** [comment]
ConnectionMultiplexer is meant to have a very long lifespan and be reused - being `IDisposable` which also triggers tooling to suggest `using()` would be counter-intuitive to the way it should be used. The lack of IDisposable is indeed intentional there.

**Comment by TomFreeman** [comment]
Fair enough.
