### ISSUE TITLE
Method SentinelGetMasterAddressByName

### ISSUE THREAD

**Issue by sreefubs** [StackExchange/StackExchange.Redis#356]
Can someone please help me on, how to call "SentinelGetMasterAddressByName" method in RedisServer class with a sample code?!!

I'll provide master/slave IP address & return should be master IP address so that I can established a connection with master IP address.

**Comment by sreefubs** [comment]
can anyone please help me here ?

**Comment by NickCraver** [comment]
We don't currently support this, but with integration tests we can fold in #692. I'm not sure that such a method is needed though, if we can just connect to Sentinel and handle everything, but if there's value in exposing the state of things, I'm certainly not opposed to it.

**Comment by NickCraver** [comment]
Tagging for #528 tracking.

**Comment by NickCraver** [comment]
Here's how to do this in 2.0:
```c#
var server = multiplexer.GetServer(sentinelIp, sentinelPort);
var endpoint = Server.SentinelGetMasterAddressByName(myServiceName) as IPEndPoint;
Console.WriteLine("{0}:{1}", ipEndPoint.Address, ipEndPoint.Port);
```
I'll be looking at first-class sentinel support on connection after this 2.0 stable release so this won't be needed.
