### ISSUE TITLE
Bug: deadlock happens

### ISSUE THREAD

**Issue by melnikov77** [StackExchange/StackExchange.Redis#36]
Sometimes I have deadlocks related to async methods.
I think it happens because sometimes async methods finish in "reading" thread.
Here is example:

``` C#
var task1 = _db.SetAddAsync(key1, val1);
var task2 = _db.SetAddAsync(key2, val2);

await Task.WhenAll(new[]{task1, task2}).ConfigureAwait(false);

//if you check current thread name sometimes it has name "computername:Read".
Console.WriteLine(System.Threading.Thread.CurrentThread.Name);

//if this happens the next code will newer finish.
// actually it could be any async call
await _db.SetAddAsync(key2, val3).ConfigureAwait(false);
// if you replace it with sync method the timeout will happen
```

**Comment by NickCraver** [comment]
The continuation pattern has changed since this was posted - are you able to repro this on a current version? If so, are you on .Net 4.6+ or prior?

**Comment by melnikov77** [comment]
Hi Nick,

We do use patched version where we always execute continuations in
ThreadPool's thread i.e. newer execute in reader thread. I saw your fix but
it requires .net 4.6 which we cannot use right now.

Thanks,
Sergey

**Comment by NickCraver** [comment]
@melnikov77 can you point me to the patch? If this is an issue more are hitting, a config option may be in order.
