### ISSUE TITLE
ConnectionMultiplexer uses wrong servers when installed locally

### ISSUE THREAD

**Issue by aaronmell** [StackExchange/StackExchange.Redis#360]
So I have two instances of Redis, a local version (windows) on my box, and a test server for QA.

When the local version is running, and I try to connect to the QA box, my connections are being rerouted to the local instance. Below is a screenshot of the issue

![image](https://cloud.githubusercontent.com/assets/490702/13093237/d31cccd6-d4c9-11e5-9f24-55a97c96b354.png)

My configuration is clustered on both my local machine and the QA box, however when I look at the cluster nodes for each, they have the correct configuration with no cross talk.

**Comment by aaronmell** [comment]
The only endpoint I added, was the 10.0.8.21 endpoint. the 127.0.0.1 are being added for me.

**Comment by aaronmell** [comment]
If there is something I could do to help track down the issue, I would be happy to

**Comment by aaronmell** [comment]
So after doing some more digging, I found the root cause. My cluster was defined as 127.0.0.1 6379, 127.0.0.1 6380, 127.0.0.1 6381 When I connected to the cluster, it was adding those endpoints to my configuration. After switching the cluster to use 10.0.8.21 it seems to be working correctly. The redis documentation doesn't explicitly mention it, but it makes sense.

**Comment by mgravell** [comment]
Yeah, cluster *will let you* configure the cluster using 127.0.0.1 - unfortunately, that is the address that it will hand out to external callers. So: if you're going to use client and server on the same machine, you can just about get away with it - otherwise, you'll need to configure the cluster using non-loopback IP addresses.
