### ISSUE TITLE
Using 1.1.553-alpha but not compiling with asp.net core

### ISSUE THREAD

**Issue by kevin5464** [StackExchange/StackExchange.Redis#362]
When I add the Nuget package for 1.1.533-alpha, it only adds references for "net451". 

I can get VS to recognize the libraries and write the code, but when I try and build it fails on account of "dotnet5.4" not having a reference to it. 

In the dependency list for the package, it references 5.0 and 5.5.

Apologies for my remedial understanding of the framework, but hoping this is a quick fix on my side to get it up and running. 

Thanks!

**Comment by mgravell** [comment]
Yes, we currently target dotnet5.5 only, so I would expect this. Will keep this open to track what level we can downport to, but given the amount of socket etc work: probably not very far

**Comment by kevin5464** [comment]
Mark,

Thank you for the reply. We got this sorted out the other day and I forgot to update. We are now targeting dnxcore50, so all is well. 

Thanks!
Kevin
