### ISSUE TITLE
[Question] Async pattern for using SE.Redis

### ISSUE THREAD

**Issue by aensidhe** [StackExchange/StackExchange.Redis#374]
Hi.

I'm sorry if this is not the right place for this question.

I know that it's bad to mix `.Wait()` and `async`for various reasons, so I don't do that. But sometimes I don't care about order of calls and want to wait all of them, not one by one (yep, it is possible that it is premature optimization), so I have code like this:

``` csharp
private Task UpdateLogin(IDatabaseAsync db, ...)
{
    return Task.WhenAll(
        db.HashSetAsync(key1, name, value),
        db.HashSetAsync(key2, name, value),
        db.HashSetAsync(key3, name, value);
}

await UpdateLogin(db, ...);
```

Will this cause any problems in SE.Redis? Is it an antipattern? And we have problem like #194 , so I am wondering - maybe the problem is in my code.

**Comment by NickCraver** [comment]
What you have with a `Task.WhenAll` is perfectly appropriate (and what I would do); it's both correct and less confusing to anyone else reading your code down the road. You can do other tricks like awaiting only the last one, but should an exception be thrown from something not awaited that's not a good situation.

Also note: you can use the fire and forget variants without waiting at all, if you don't care about the result in the code that follows. Future gets and such will be in order (if reusing the same multiplexer, which you should), so you don't actually need to await the previous commands to redis in many situations. You can continue executing your other code while they're in queue and complete in the background. Does that make sense?

**Comment by aensidhe** [comment]
Thank you, it is very clean and correct answer. Yes, it does make sense and I got my answer.

Fire and forget is good but not in my case, because I need to be sure that all tasks finished.

We are reusing multiplexers, but not one per website, one per role: data, bus, queue, etc. They write to different subset of keys.

**Comment by NickCraver** [comment]
Closing this out to cleanup!
