### ISSUE TITLE
If a configuration contains both sentinel and non-sentinel endpoints, no sentinel messages show up on the subscriber

### ISSUE THREAD

**Issue by aaronmell** [StackExchange/StackExchange.Redis#382]
You can reproduce this by creating a connection with both a sentinel endpoint and a non-sentinel endpoint. 
1. Subscribe with the "*" wildcard. 
2. You will only recieve hello messages published by sentinel
3. Remove the non-sentinel endpoint
4. Subscribe with the "*" wildcard.
5. You will now receive the sentinel messages

Playing around with the commands in the cli, it looks like sentinel messages are not broadcast to non-sentinel machines and probably vice-versa. Sentinel does not support the pubsub channels command either. 

Would it make sense to add a new CommandFlag DemandSentinel?

**Comment by mgravell** [comment]
Personally, I don't see this as a valid scenario.

A set of Redis nodes in a master-slave configuration: is a valid combined
entity

A set of Cluster nodes: is a valid combined entity

I don't see that it makes sense to talk to Redis nodes and Sentinel nodes
*as the same thing*.

What I *can* get behind is only specifying sentinel nodes and a service
name in the configuration and using that for *resolution purposes*,
meaning: the sentinels tell me where the actual Redis servers are. But
then: that's it - the sentinel nodes are essentially cut out of the
conversation.

What you describe has merit, but I don't think it should be forced to
cohabit in the same multiplexer - that simply isn't the intent.

**Comment by aaronmell** [comment]
I want to write a tool that monitors the sentinal pubsub, and send notifications to our organization when certain messages are published by Sentinel.  If changes are made to the multiplexer that allow it to automatically resolve the nodes it is monitoring, then I would no longer be able to get notifications from sentinel due to the bug I've encountered. 

In the case above, my monitoring tool, only cares about the sentinel servers, and only wants to talk to them. In fact, it doesn't need to do any resolution of the masters. 

One way that it might continue to work, although I am not sure if this is the best way to handle it, is by not specifying any service name. In that case the multiplexer would not be able to look up the masters being monitored, and sentinel notifications would work correctly.

**Comment by NickCraver** [comment]
Closing this out for the reasons Marc pointed out - this just isn't a valid combo. If you want to connect to this combination, I'd advise using 2 different multiplexers to do it :)

Note that #692 is working on supporting sentinel where you connect to a sentinel address and then automatically get forwarded to the nodes. That should satisfy the intended monitoring pattern here, giving a good overview. If there are additional bits of state you'd like to see exposed, please comment on #692 :)
