### ISSUE TITLE
SDK Support : Connection Failure

### ISSUE THREAD

**Issue by jayakrishnabh** [StackExchange/StackExchange.Redis#391]
I’m new to Redis and we’re analyzing the tool for a specific requirement which needs High-Availability & Consistency.

Environment Details: 
Redis Server(Windows OS) : v3.0.501 https://github.com/MSOpenTech/redis
.Net SDK : https://github.com/StackExchange/StackExchange.Redis/releases/tag/1.1.553
Cluster Setup : 1 Master & 3 Slaves & 3 Sentinels.

Test Scenario :
Given only master details on application startup and while iterating Redis SET command from .Net client through StackExchange.Redis SDK, stopped the master redis instance..

Sentinel elected a new master (one of the slaves), but my application didn't SET to the new master. How will my application get updated about the new redis master IP?

**Comment by moxplod** [comment]
I have a similar issue - its not detecting the right master in the cluster.

**Comment by NickCraver** [comment]
Closing this out to cleanup - this is now handled in current versions of the library :)
