### ISSUE TITLE
Timeouts with LRANGE command 

### ISSUE THREAD

**Issue by miwagner2016** [StackExchange/StackExchange.Redis#393]
I need some help to interpret the following timeout exception,

Failed to resolve members of list ..._/history/ from Redis endpoint \* with a timeout of 3000 ms for Redis service \* due to exception: System.TimeoutException: Timeout performing LRANGE ..._/history/, inst: 4, mgr: ExecuteSelect, err: never, queue: 9, qu: 0, qs: 9, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, IOCP: (Busy=8,Free=992,Min=4,Max=1000), WORKER: (Busy=20,Free=32747,Min=4,Max=32767), clientName: \* 

The exception occurs when our application executes many "LRANGE /.../history/ 0 -1" commands (up to 29). Is there a known issue with LRANGE? Each corresponding history key stores 100 commands with 100 elements. 

In general a LRANGE command takes about 500ms, so we do not expect any timeouts even with this number of requests. So how can we interpret the log message - especially all these parameters "qs, qc ..."?

**Comment by miwagner2016** [comment]
UPDATE:

During load scenarios we face with hanging client requests. Our logs show following errors: 

Failed to handle received message 1075875 invalidate due to exception Failed to resolve 91 members of list /.../history/ from Redis endpoint ... with a timeout of 6000 ms for Redis service ... due to exception: System.TimeoutException: Timeout performing LRANGE /.../history/, inst: 1, mgr: CheckForStaleConnections, err: never, queue: 2, qu: 2, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=854,Free=31913,Min=4,Max=32767), clientName: * 

The value for busy worker threads seem to be very high? When we turn on the "AbortOnConnectFail" -Flag these problems do not occur. How can we explain that? Could we activate a "CheckForStaleConnections" somehow?

**Comment by NickCraver** [comment]
The higher worker thread could would be in your app, starving the library from completing the commands due to lack of pool resources. What these are doing (they could be synchronous waiting on the lib, etc. I can't say without seeing a dump). Can you take a dump of the application or attach a debugger and see where all those threads are? You're likely seeing many other performance issues downstream from this as well.

**Comment by NickCraver** [comment]
Closing this due to no updates, track #450 for progress on timeouts in general. There are many causes but some fundamental changes in the network layout should help sort quite a few of them out.
