### ISSUE TITLE
Timeout performing GET {KEY}, inst: 1, mgr: CheckForHeartbeat, err: never, queue: 36147, qu: 0, qs: 36147, qc: 0, wr: 0, wq: 0, in: 8192, ar: 0, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=51,Free=32716,Min=8,Max=32767)

### ISSUE THREAD

**Issue by mayamoon** [StackExchange/StackExchange.Redis#395]
Dear Sir,
First,sorry for my poor English.

Host IIS 7
Redis Server 2.8.17 with master slave
this issue ocusers many times,when it come out ,the only way to fix it is reset my iis.
I also add the connecttimeout and asynctimeout to 10 seconds  

Timeout performing GET {KEY}, inst: 1, mgr: CheckForHeartbeat, err: never, queue: 36147, qu: 0, qs: 36147, qc: 0, wr: 0, wq: 0, in: 8192, ar: 0, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=51,Free=32716,Min=8,Max=32767)

**Comment by NickCraver** [comment]
@mayamoon It looks like you're hitting a thread pool spike given the numbers. For more information, please see the timeout docs for recommendations on how to resolve :) https://stackexchange.github.io/StackExchange.Redis/Timeouts
