### ISSUE TITLE
Help identifying cause of Timeouts under high-load

### ISSUE THREAD

**Issue by sodastraww** [StackExchange/StackExchange.Redis#416]
We are using  StackExchange.Redis version="1.0.488" . We have the syncTimeout is set to 30 sec which seems too high.

During performance tests with 20 concurrent users, we start to receive timeouts like the one below. Documentation on this error indicates we need to add more memory to our Redis cluster, but the redis cluster shows little memory and cpu usage. Is there anything you can advise we can look at to explain the timeout exceptions? Thanks for your help!

Error Unable to set fields : Timeout performing HGETALL 400401~GLI_H_8ca4a949-cb88-4752-9d8e-a8dd7ff57659, inst: 418, queue: 19385, qu: 19284, qs: 101, qc: 0, wr: 1, wq: 1, in: 0, ar: 0, IOCP: (Busy=0,Free=400,Min=4,Max=400), WORKER: (Busy=4,Free=32763,Min=4,Max=32767), clientName: xxx

**Comment by nemaroller** [comment]
A syncTimeout of 30 is way too high. Having a queue of 19,000 is way too high. We pushed our syncTimeout to 5 seconds and that seems irresponsible. Here's a few thoughts to ponder in order of what I see as most probable:
If you have large objects being cached (500kb and over), you should seriously consider chopping those objects into smaller items - this is especially critical under heavy load.
If you can get away with it, don't delete items, set them with a TTL or update them as necessary.
If you have persistence on, you can accrue timeouts during moments when Redis save snapshots to disk. 
Set maxmemory to a level which allows room for buffering I/O operations to connected clients and host OS operations (i.e. 75-80% of max capacity).
If you can separate concerns, try moving some high input/output items to another instance (either on the same host or a different host).
Adding more memory can help in some regards, but may just be delaying a less optimal configuration from becoming a pest again.

**Comment by mgravell** [comment]
What is the profile of the data? Are they large blobs? Basically, there's
two problems here;

- the server isn't keeping up - 101 sent requests and nothing on the input
socket to read
- the output is backlogged - *lots* of unsent message

The easiest way I can think to cause this is for some messages to be huge,
stalling both the output and server.

**Comment by sodastraww** [comment]
The objects represent rows in a grid where each row (HASH with aprox 75 HashFields) is ~ 5 KB and in this test there were aprox 16 K of these hashes being modified at once. In most of the cases we saw the timeouts when the entire "grid" expired sending all of the individual hashes to be recreated and read. We have not seen these timeouts in our Production environment since we turned off persistence - which may have been adding to the issue. We have the syncTimeout down to 10 sec, but i agree that this is still way to high.

Also note that we have replication on with 2 slaves and 1 master.

My question why would we not see increased load on the redis cluster? It never went past 2 GB of usage. CPU didn't spike either. Thanks for your help. Much appreciated.

**Comment by NickCraver** [comment]
@sodastraww to add some context on latest questions:
1. That is a *ton* of data, if you're throwing it at redis all at once, that's 75 * 16,000 = 1.2 million ops...that's a lot to churn through (and write to disk). Persistence being disabled improving things would confirm: that's just a metric ton of ops (to do quickly).
2. Why not increased load on the cluster? I'm not sure I follow the question, but if you're saying cluster performs better than a single node: that'd be expected, you're sharding out the load across multiple nodes.

**Comment by mgravell** [comment]
Closing; please see #871
