### ISSUE TITLE
getting exception "MOVED 13313 127.0.0.1:7002" when i am using stackexchange.redis c# client for redis clustering

### ISSUE THREAD

**Issue by amanbhushan** [StackExchange/StackExchange.Redis#417]
Configuration code:

```c#
connectionMultiplexer = ConnectionMultiplexer.Connect("192.168.2.168:7000");
database = connectionMultiplexer.GetDatabase();
database.StringSet("test", "testval");
```

Please guide if I need to do any configuration changes.

**Comment by NickCraver** [comment]
This was fixed in later releases - the `MOVED` results are handled properly in the client. Apologies for not following up here earlier.

**Comment by dscaravaggi** [comment]
I'm not sure but..
I suspect that 5.0.3 is still suffering this problem when binding multiple interfaces like 0.0.0.0
