### ISSUE TITLE
[Question] 1.1.603 release notes, or at least tag for source code?

### ISSUE THREAD

**Issue by aensidhe** [StackExchange/StackExchange.Redis#418]
Hello.

Can we see release notes for 1.1.603 nuget package? Tag on source code will work for me, thanks.

Regards,
Anatoly.

**Comment by NickCraver** [comment]
I'm not sure if @mgravell has the exact commit that was built or not - we can try and go back and tag this though.

**Comment by programcsharp** [comment]
I see tags on releases, which is better than nothing, but is it possible to have an actual release notes?

**Comment by mgravell** [comment]
Totally my bad. I will review our options for improving this.

**Comment by mgravell** [comment]
I'm working through history here: http://stackexchange.github.io/StackExchange.Redis/ReleaseNotes - I need to decide how far back I go...
