### ISSUE TITLE
Timeout exception when using Azure Redis with 1.1.603 but not 1.0.488

### ISSUE THREAD

**Issue by bunceg** [StackExchange/StackExchange.Redis#419]
Hi,

Still trying to get any useful information but I upgraded to the latest StackExchange 1.1.603 and my site started to instantly fail with timeouts. Changed it back to 1.0.488 and everything works again and is back to normal. I've not had to make any application or connection string changes to invoke this behaviour.

I'm using an Azure Redis C0 cache - upgraded to C2, still the same issue.

e.g.

465334900.405324 [0 13.69.190.80:27496] "GET" "cu-ixfzad9twbw5fyv.socialnetworking.geteventsasync"
1465334900.407321 [0 13.69.190.80:27496] "GET" "cbc_cu-IXFzAd9twbw5FYv_events"
1465334901.028880 [0 13.69.190.80:27496] "PING"

Is there any major updates that means I need to change my connection string or something in 1.1.603?

Thanks

**Comment by NickCraver** [comment]
Are you seeing this in the latest library? We made some continuation changes to help events like this.
