### ISSUE TITLE
RedisConnectionException at each first Connect(), while redis-py and hiredis work fine

### ISSUE THREAD

**Issue by tw-bert** [StackExchange/StackExchange.Redis#42]
Hi Marc,

Version 1.0.289.0 (nuget, .net 4.0).

When I leave my workstation alone for five minutes, after calling Connect() I get a RedisConnectionException the first time. Immediately retrying does work with no delay at a 90% success rate. No info is written to the supplied TextWriter.

 

    var oCli = ConnectionMultiplexer.Connect("srv-flux-01:14144", log);

Complete exception message:

    An unhandled exception of type 'StackExchange.Redis.RedisConnectionException' occurred in StackExchange.Redis.dll
    Additional information: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail

I connect from Win7 Pro X64 to Redis 2.8.9 (x64) on a Debian machine on our LAN (same subnet). No hardware firewalls in between, only Windows firewall.
Redis connections from redis-py or RedisDesktopManager(which uses hiredis) never fail, and always connect within milliseconds.

I use a simple Windows Forms project, VS2013 Express, for testing.
I use (and need) the .NET Framework 4 Client Profile.

Any ideas?

Kind regards, TW

**Comment by ship2moon** [comment]
I dont know writing it here will solve our poblem. Please add a "+1" to the same error:
"It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. UnableToResolvePhysicalConnection on PING at StackExchange.Redis.ConnectionMultiplexer"

**Comment by kmacmcfarlane** [comment]
In my case, the call to Connect(...) fails if it is inside an async delegate. I found this by trying to connect from within Nito's AsyncContext.Run(async () => {}) method. Hope that helps someone else :-)

**Comment by turowicz** [comment]
I'm getting that error again. The interesting thing is that some of my peer devs are working on the exact same setup and they do not experience this.

Any ideas?

**Comment by venkatperi** [comment]
+1

Stackexchange.Redis: 1.0.316.0 (via nuget)
Mono 3.12.0 ((detached/a813491)

```
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. UnableToResolvePhysicalConnection on PING
at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl (System.Func`1<StackExchange.Redis.ConnectionMultiplexer>,System.IO.TextWriter) <IL 0x00096, 0x0031b>
at StackExchange.Redis.ConnectionMultiplexer.Connect (string,System.IO.TextWriter) <IL 0x0001a, 0x000e7>
```

**Comment by berkutx** [comment]
+1 I have a same error, venkatperi (only under latest mono in linux, under windows w/o mono - all is ok), log:
 faulted: UnableToResolvePhysicalConnection on PING

**Comment by kohner86** [comment]
I'm seeing the same issue intermittently while connecting to an Azure Redis instance.  From the Azure monitoring I only have ~40 connections open at any given time.

-Lee

**Comment by mralj** [comment]
This is happening to me too, I'm using StackExchange.Redis.StrongName ver. 1.0.394, oddly enough, I've noticed that if I use  StackExchange.Redis ver. 1.0.394 everything works fine. (but I need StrongName because of RedisSessionStateProvider)

**Comment by bhenze** [comment]
Has anyone found a definitive solution for the "No connection is available to service this operation: SETEX" issue? I am currently using RE.Redis 1.0.331 and am seeing the same thing in my WebAPI app running in IIS. I have yet to constantly reproduce this issue but when it does happen its always occurs after rebooting our server.

I have 5 servers talking to redis and redis is configured with 1 master and 3 slaves. When I get into this state, about 1 in 5 or so calls actually work and the rest give me the no connection error. Also, most of the time my servers have no issue spinning back up and calling redis. I see this after reboot only about 1 in 10 times. I am just starting to dive into solutions for this issue but wanted to verify if someone has tracked this to the route cause yet.

**Comment by sickboy** [comment]
If you are using Lazy<ConnectionMultiplexer> manually or through a third party library (e.g SimpleInjector DI container) then the exception on creation is cached, and therefore you need to restart the web app to fix the issue again.

I'm currently experimenting by calling the following (instead of using DI):
```
        void EnsureConnection() {
            if (_cacheClient != null)
                return;

            lock (_lock) {
                if (_cacheClient != null)
                    return;
                var connectionMultiplexer = ConnectionMultiplexer.Connect(Environments.RedisCacheConnectionString);
                Thread.MemoryBarrier();
                _cacheClient = connectionMultiplexer;
            }
        }
```

**Comment by andysinclair** [comment]
We were experiencing the same issue on one of our installations and to resolve it I replaced the IP address of the Redis server with the hostname (as mentioned earlier in this thread). No idea why this happened as we have the same configuration on lots of machines and have never seen this issue before.

**Comment by smiket** [comment]
I am seeing this issue too.  In my case, I have a unit test that spawns multiple threads.  Each thread gets a multiplexer (the first thread in will initialize it).  That first thread enters ConnectionMultiplexer.ConnectImpl().  In that method, there is this line of code:

var task = Factory.StartNew(() => { return muxer.ReconfigureAsync(true, false, log, null, "connect").Result; });

In normal scenarios, this always works.  However, in my multithreaded test, the Task.Factory never ends up calling the inline lambda in the above code.  So the task times out, and surfaces as the exception noted in the beginning of this issue.  I'm looking at it now, but thought I'd just post to maybe shed some additional info.

**Comment by smiket** [comment]
I changed my test to not launch threads via Task.Run ...
Instead, I am now creating threads manually, and starting them.
The issue goes away - I was depleting the thread pool (as noted earlier in this thread).

**Comment by BrandesEric** [comment]
+1 - I'm seeing what looks like the same thing with 1.0.414.  It happens only on app startup, and not every time.  We're deploying with MSDeploy.  I'm going to try adding a ConnectRetry value > 1 and using the Task.Run() method @smiket suggested.

**Comment by saixiaohui** [comment]
I encountered the same issue. I downloaded the Redis code and debugged from my side, I found the code that is causing issue for me. 

When the code tries to connect, it starts a new task and waits for either complete or timeout. 
var task = Task.Factory.StartNew(() => muxer.ReconfigureAsync(true, false, log, null, "connect").Result);

In order to limit the number of parallel tasks my code can use, I created a TaskFactory and set the TaskScheduler as a limited concurrency level task scheduler. Somehow this task used the same TaskFactory (haven't figured out why) and all the threads were busy on something else, so the task was never scheduled and executed during waiting. 

I am guessing most of the issues happened here is because the task was not executed or hasn't completed.

@mgravell , hope this helps.

**Comment by BrandesEric** [comment]
@saixiaohui thanks for the insight!  I think you're on to something.  We're using a limited concurrency scheduler as well - and the call to create the multiplexer the first time and do the Connect() is actually within a spun-off task.  

I ended up creating the multiplexer and doing the Connect() in the static ctor of the class that ultimately spawns off the threads using the LCS, and so far that seems to have solved it.  However, i'm not calling it a success yet, since the issue was semi-intermittent.

**Comment by bhavishaKacha** [comment]
Hello @tw-bert ,

I have same issue and I have searched for demo project for Stack Exchange Redis in .NetFramework 4.0 C# but I didn't find yet.

Project Need: I want to use this in caching for storing just key, value pair. I have used system.caching but it destroy cache after service restart. 

So I have used first Service Stack Redis but it have limitation of 6000 request per day and my project have almost 282984 requests per day.

So I switched to Stack Exchange Redis. I have made sample project and it works fine in my local machine. But when I deploy project on staging environment gives below error:

<pre lang="c#">It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. UnableToResolvePhysicalConnection on PING

StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. UnableToResolvePhysicalConnection on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log)
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log)
   at StackExchangeApplication.Source.Service.RedisService..ctor()
   at StackExchangeApplication.Source.Service.RedisService.get_GetInstance()
   at StackExchangeApplication.RedisHelper.GetStringValue(GetValueRequestMessage requestMessage)</pre>

Here is my code:

<pre>

public class RedisService
{

        public static ConnectionMultiplexer _connection;
        public static IDatabase _redisDatabase;

        static RedisService()
        {
            _connection = ConnectionMultiplexer.Connect("localhost");
            _redisDatabase = _connection.GetDatabase();
        }
     
       public void AddStringKeyValue(string key, string value, int expireInMinute)
        {
            bool result = _redisDatabase.StringSet(key, value, TimeSpan.FromMinutes(expireInMinute), When.Always,
                CommandFlags.None);

            if (!result)
            {
                throw new Exception("Failed To add key value in Redis server Key : " + key + ", Value : " + value);
            }
        }

        public string GetStringValue(string key)
        {
            string value = _redisDatabase.StringGet(key);
            return value;
        }

}
</pre>

Please help if anyone tried this I am finding out solution from last 3 days :( .

Thanks in advance!

**Comment by dengere** [comment]
1.0.481 version, i've got exactly same exception as started this thread subject.

"It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING"

did i missed something?

**Comment by dtxlink** [comment]
It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING

**Comment by kirill-kruchkov** [comment]
Hello. Just encountered almost the same error. Though sometimes (not always!) with the message "InternalFailure on PING".

**Comment by kohner86** [comment]
I was never able to come up with a real solution to this problem so I ended up creating a 'WatchDog' timer which performs a write operation every 30 seconds and re-initializes the ConnectionMultiplexer if the operation fails.  Seems to be working pretty well, haven't had a single outage caused by this since the timer was put in place.

**Comment by aliostad** [comment]
Just saw this in production twice.

**Comment by andysinclair** [comment]
First Line
Second Line

**Comment by andysinclair** [comment]
First line
Second Line
And more...

----------------------
Andrew Sinclair
SharpCloud Software
t:  +44 (0) 203 7648 515
m: +44 (0) 7740 932 132
lync: andrew@sharpcloud.com
skype: andysinclairuk

SharpCloud, a visual place for business.
SharpCloud named a Gartner Cool Vendor in Social Software and Collaboration<http://www.sharpcloud.com/blog/SharpCloud_Gartner_Cool_Vendor_Report>
www.sharpcloud.com<http://www.sharpcloud.com/>

**Comment by DntArtherDnt** [comment]
My team and I just noticed a correlation between our web servers having connection issues with Redis (No Connections Available / Timeouts) and Redis saving snapshots of itself.

After a little digging I stumbled on this gem on http://redis.io/topics/persistence

![image](https://cloud.githubusercontent.com/assets/8289721/10436904/7ea1b17a-70f7-11e5-86a1-a0785cd09c91.png)

For our application we don't need persistence so I'm just disabling it altogether, but might be worth looking into as a potential cause or if it's tied to the difficulty with reproducing the issue.

**Comment by DntArtherDnt** [comment]
Unfortunately I am still seeing the issue relatively frequently

**Comment by MarwaAhmed** [comment]
I've the same problem. I'm using Azure redis cache as a session provider:
  "Exception": {
    "ClassName": "StackExchange.Redis.RedisConnectionException",
    "Message": "No connection is available to service this operation: EXISTS xxxx,
    "Data": {
      "redis-command": "EXISTS xxxx"
    },

Where xxxx is an arbitrary key.

**Comment by swmech** [comment]
Checking on this issue, as we're seeing it in production as well (Azure Redis cache).  Has there been progress made on determining a fix?  Or is opening a dummy connection first still the accepted workaround?

**Comment by dengere** [comment]
Do you really have any workaround? We can't use on azure last two months.
We stop to use it.
30 Ara 2015 00:35 tarihinde "swmech" <notifications@github.com> yazdı:
>
> Checking on this issue, as we're seeing it in production as well (Azure
Redis cache). Has there been progress made on determining a fix? Or is
opening a dummy connection first still the accepted workaround?

**Comment by smiket** [comment]
Marc, I have a unit test for you that can reproduce the issue.
Attaching screenshot of error, and unit test below.
In the unit test, if you dial back the number of threads below 30 (on my host) there are no issues.
If you turn it up over 50, the errors begin.

Looks like line 771 in ConnectionMultiplexer (task.wait) is timing out.
Its not that the connection timeout occurs - rather, the task never starts (deadlock / depletion?).
The error materializes as a connection error, but its really the task not starting.
The breakpoint in the lamda on line 767 never gets hit / task never starts.

Hope this helps, and thanks,
Steve

![image](https://cloud.githubusercontent.com/assets/679925/12785098/b791339c-ca58-11e5-83c0-5c15b89f8d92.png)

        [Test]
        public void CanSetAndGetItemsAcrossThreads()
        {
            var opts = ConfigurationOptions.Parse("REDISHOST:6999");
            using (var writer = File.CreateText(@"C:\Logs\StackExchange.log"))
            using (var conn = ConnectionMultiplexer.Connect(opts, writer))
            {
                var redis = conn.GetDatabase(0);

                List<Task> tasks = new List<Task>();
                for (int i = 0; i < 80; i++)
                {
                    var task = Task.Run(() =>
                    {
                        string key = Guid.NewGuid().ToString();
                        string val = Guid.NewGuid().ToString();
                        redis.StringSet(key, val);
                        redis.StringSet(key, val);
                    });
                    tasks.Add(task);
                }

                Task.WaitAll(tasks.ToArray());
                Console.WriteLine("Test Completed");
            }
        }

**Comment by rjmooney** [comment]
So I ran into this issue as well. After reading through some of the comments and taking a look at the code, I noticed an unnecessary indirection in `ConnectionMultiPlexer.ConnectImpl` which appears to be causing a deadlock:

```
// note that task has timeouts internally, so it might take *just over* the regular timeout
// wrap into task to force async execution
var task = Factory.StartNew(() => muxer.ReconfigureAsync(true, false, log, null, "connect").Result);
```

What's happening here is the code is spawning an async task which waits _synchronously_ on an async task result. This is bad juju. What it appears is happening next is the code blocks the context thread waiting for the wrapper task created with `Factory.StartNew` to return:

```
if (!task.Wait(muxer.SyncConnectTimeout(true)))
```

When the continuation from `ReconfigureAsync` returns, it waits for the context thread to become available. Since the context thread is blocked waiting for the continuation, it results in deadlock. Stephen Cleary has an [excellent description](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) of the pattern on his blog.

The fix, I believe, is simple: spawn the `ReconfigureAsync` method directly:

```
// note that task has timeouts internally, so it might take *just over* the regular timeout
var task = muxer.ReconfigureAsync(true, false, log, null, "connect");

if (!task.Wait(muxer.SyncConnectTimeout(true)))
```

If I had to guess, I'd say `ReconfigureAsync` was once a synchronous method that was converted to async without updating the `ConnectImpl` implementation to remove the async wrapping. 

The above is conjecture at this point, however in limited testing it appears to solve the problem.

Submitted as pull request #353.

**Comment by jonranes** [comment]
I had the same issue, I implemented the rjmooney change and the problem is not happening anymore.

**Comment by aliostad** [comment]
:+1: @rjmooney Thanks!
@mgravell @NickCraver Guys this is bringing our site down once a day, can you please review and release the fix?

**Comment by smiket** [comment]
@aliostad please let us know if this resolves your issue after a few days?

**Comment by aliostad** [comment]
@smiket we are deploying next week, I will keep you posted.

**Comment by ronnyek** [comment]
Is this code in any nuget releases? I've cloned latest and included and still very much seeing this in dnx on linux. redis-cli works fine, but still cant connect via stackexchange.redis

**Comment by aliostad** [comment]
@smiket it looks like my problem had nothing to do with this. But still investigating.

**Comment by rjmooney** [comment]
@ronnyek @ronnyek https://www.nuget.org/packages/StackExchange.Redis/1.1.572-alpha. What issue are you each seeing exactly?

**Comment by smiket** [comment]
@aliostad @rjmooney we solved our problem - but it had nothing to do with the pull request associated with this issue.  Our connection errors were caused by what I outlined above (see my previous post).  We were seeing the errors every day - and now we have not seen it in two weeks.

If the threadpool is drained then SE redis will not be able to connect.  The reason is that it times out waiting for a thread to become available, as it tries to connect.  The error indicates a connection issue, but its really thread starvation in our case (not a deadlock).

We took a hard look at our code, and found we were running several simultaneous jobs to load our cache.  The jobs kick off at the same time, and each uses parallel loops etc.  Lots of simultaneous, parallel loops - drained the pool.

We lightened up on parallelism, decreased the number of jobs running at same time and such.  By putting less pressure on the thread pool, we solved the issue.  In our case (and I suspect same for a number of other folks here) we were causing the issue.  Its just unfortunate the error message is a bit misleading.

Hope it helps!
Steve

**Comment by ronnyek** [comment]
@rjmooney basically in vnext with I believe that alpha, I was getting this:
An unhandled exception of type 'StackExchange.Redis.RedisConnectionException' occurred in StackExchange.Redis.dll
Additional information: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail on launch

only running on linux.

**Comment by danielkornev** [comment]
Same thing, although we launch multiple separate instances for a desktop (yikes!)-based client app. 

```
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. UnableToResolvePhysicalConnection on PING
   at StackExchange.Redis.ConnectionMultiplexer.<ConnectAsync>d__20.MoveNext() in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 765
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ZU.Storage.Redis.RedisEnvironmentManagement.<>c__DisplayClass0_0.<<CreateRedisInstance>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ZU.Storage.Redis.RedisEnvironmentManagement.CreateRedisInstance(String currentFolder, Boolean showRedisInstanceCommandPrompt)
```

**Comment by hesi726** [comment]
Please see http://stackoverflow.com/questions/23871110/stackexchange-redis-failing-to-connect-with-mono-in-mac-os-x  , 

And I use the follows package, 
https://www.nuget.org/packages/StackExchange.Redis.Mono/

it solved my question.

**Comment by tianzhiyuan** [comment]
after disable AbortOnConnectFail, ConnectionMultiplexer.Connect()  will success but still takes too long time(nearly 1 minute). I have tried many ways and after calling "ThreadPool.SetMinThreads(100, 200)", bingo, connect succeed very fast. Still I don't know why, may be thread starvation? Can anyone explain?

**Comment by rjmooney** [comment]
First guess is that there are blocked worker/completion port threads and the defaults are causing contention. Setting the minimum threads shouldn't be necessary.

**Comment by afpro** [comment]
upgrade to 1.1.608 from 1.1.606, got this error.
