### ISSUE TITLE
Continuations blocking other async calls

### ISSUE THREAD

**Issue by dolly22** [StackExchange/StackExchange.Redis#420]
I'm experiencing some strange behavior when blocking on async continuations. It seems it's already handled in [TaskSource.cs](https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis/StackExchange/Redis/TaskSource.cs), but **CreateDenyExecSync** does not use this ([TaskSource.cs#L106](https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis/StackExchange/Redis/TaskSource.cs#L106))

I have first encountered this when using ASP.NET Core Redis cache provider (issue https://github.com/aspnet/Caching/issues/202), but it seems the underlying cause is in StackExchange Redis library. This is the simplest repro i came up with.

``` csharp
public async Task TestMultipleGets()
{
    Console.WriteLine("Starting test");
    await Task.WhenAll(
        CacheGetTest(),
        CacheGetTest(),
        CacheGetTest());
    Console.WriteLine("Done");
}

public async Task CacheGetTest()
{
    var started = DateTime.UtcNow;
    var sw = new Stopwatch();
    sw.Start();
    await redisDb.StringGetAsync("cache_Key");
    sw.Stop();
    var finished = DateTime.UtcNow;

    Thread.Sleep(5000);

    Console.WriteLine($"Started {started}, finished {finished}, cache time {sw.ElapsedMilliseconds} ms");
}
```

My results for NET461 ...

> Starting test
> Started 8. 6. 2016 6:14:07, finished 8. 6. 2016 6:14:07, cache time 85 ms
> Started 8. 6. 2016 6:14:07, finished 8. 6. 2016 6:14:12, cache time 5082 ms
> Started 8. 6. 2016 6:14:07, finished 8. 6. 2016 6:14:17, cache time 10084 ms
> Done

**Comment by alanprot** [comment]
+1

**Comment by NickCraver** [comment]
We change the behavior here in 1.1.605 after the various continuation issues we encountered, are you still seeing this behavior?

**Comment by dolly22** [comment]
@NickCraver I can no longer reproduce in 1.1.605. Original ASP.NET Core issue is now also fixed in Microsoft.Extensions.Caching.Redis 1.1.0.

**Comment by NickCraver** [comment]
@dolly22 Thanks for the update! Closing this out to cleanup :)
