### ISSUE TITLE
How many sockets does StackExchange requires?

### ISSUE THREAD

**Issue by ahan1874** [StackExchange/StackExchange.Redis#423]
What is minimal sockets that StackExchagne requires when calling ConnectionMultiplexer.Connect()? 
My process has a limitation of 64 sockets at most, and I got OutofMemoryException when calling ConnectionMultiplexer.Connect(), is this related the max number of sockets allowed by a process?

**Comment by NickCraver** [comment]
We are hooking up to 2 sockets per redis instance: one for commands and one for pub/sub.

So if you're connecting to 1 server: 2 ports, if 2 servers: 4 ports.
