### ISSUE TITLE
Unable to generate a unique key

### ISSUE THREAD

**Issue by mparthoens** [StackExchange/StackExchange.Redis#425]
Hi,

I try to use redis as a session state provider on Azure.
For this I need to create unique keys not only per user but also if user is logged several times with same credentials.
What would be your recommendation to manage this?

**Comment by mgravell** [comment]
A guid stored in a cookie?

**Comment by mparthoens** [comment]
OK Thanks Marc.
I have another question.

I am in a multi-users environment asp.net web forms
My implementation is as follow:

Gobal.asx:

    public class Global : HttpApplication
    {
        public static ConnectionMultiplexer CswRedisConnection;
        public static IDatabase CswRedisCacheDb;
        public static int inactivityTimeout;
        public static int inactivityClearRedisCache;

        public void Session_Start(object sender, EventArgs e)
        {
            var serializer = new NewtonsoftSerializer();
            if (CswRedisConnection == null || !CswRedisConnection.IsConnected)
            {
                CswRedisConnection = ConnectionMultiplexer.Connect("...");
            }
            CswRedisCacheDb = CswRedisConnection.GetDatabase();
        }

in My pages:

            var serializer = new NewtonsoftSerializer();
            var cacheClient = new StackExchangeRedisCacheClient(serializer);

            DBOperations dbo = new DBOperations();

                added = cacheClient.Add(redisKey + "CurrentAnimal", animal, TimeSpan.FromMinutes(Global.inactivityClearRedisCache));


When multiple users are connected sometimes I get the error:

UnableToConnect on cswredis.redis.cache.windows.net:6379/Interactive, origin: ResetNonConnected, input-buffer: 0, outstanding: 0, last-read: 5s ago, last-write: 5s ago, unanswered-write: 702755s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 0s ago, mgr: Inactive, err: never 

What am I doing wrong?

**Comment by mparthoens** [comment]
I am in a multi-users environment asp.net web forms
My implementation is as follow:

Gobal.asx:

public class Global : HttpApplication
{
    public static ConnectionMultiplexer CswRedisConnection;
    public static IDatabase CswRedisCacheDb;
    public static int inactivityTimeout;
    public static int inactivityClearRedisCache;

    public void Session_Start(object sender, EventArgs e)
    {
        var serializer = new NewtonsoftSerializer();
        if (CswRedisConnection == null || !CswRedisConnection.IsConnected)
        {
            CswRedisConnection = ConnectionMultiplexer.Connect("...");
        }
        CswRedisCacheDb = CswRedisConnection.GetDatabase();
    }
in My pages:

        var serializer = new NewtonsoftSerializer();
        var cacheClient = new StackExchangeRedisCacheClient(serializer);

        DBOperations dbo = new DBOperations();

            added = cacheClient.Add(redisKey + "CurrentAnimal", animal, TimeSpan.FromMinutes(Global.inactivityClearRedisCache));
When multiple users are connected sometimes I get the error:

When multiple users are connected sometimes I get the error below
What am I doing wrong?


Server Error in '/' Application.
________________________________________
UnableToConnect on cswredis.redis.cache.windows.net:6379/Interactive, origin: ResetNonConnected, input-buffer: 0, outstanding: 0, last-read: 5s ago, last-write: 5s ago, unanswered-write: 702755s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 0s ago, mgr: Inactive, err: never 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: StackExchange.Redis.RedisConnectionException: UnableToConnect on cswredis.redis.cache.windows.net:6379/Interactive, origin: ResetNonConnected, input-buffer: 0, outstanding: 0, last-read: 5s ago, last-write: 5s ago, unanswered-write: 702755s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 0s ago, mgr: Inactive, err: never

Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below. 

Stack Trace: 

[RedisConnectionException: UnableToConnect on cswredis.redis.cache.windows.net:6379/Interactive, origin: ResetNonConnected, input-buffer: 0, outstanding: 0, last-read: 5s ago, last-write: 5s ago, unanswered-write: 702755s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 0s ago, mgr: Inactive, err: never]

[RedisConnectionException: No connection is available to service this operation: GET 19a5cbf8-b05a-4569-a406-83873ca3a896CurrentAnimal]
   StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl(Message message, ResultProcessor`1 processor, ServerEndPoint server) +2591
   StackExchange.Redis.RedisBase.ExecuteSync(Message message, ResultProcessor`1 processor, ServerEndPoint server) +96
   StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) +194
   StackExchange.Redis.Extensions.Core.StackExchangeRedisCacheClient.Get(String key) +137
   Csw.OnLineRegistration.Web.R1.AnimalEditor.TextBoxPassportNumber_Validation(Object sender, ValidationEventArgs e) +218
   DevExpress.Web.ASPxEdit.OnValidation(ValidationEventArgs e) +110
   DevExpress.Web.ASPxEdit.Validate() +350
   DevExpress.Web.ASPxEdit.RaisePostDataChangedEvent() +431
   DevExpress.Web.ASPxWebControl.System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent() +177
   System.Web.UI.Page.RaiseChangedEvents() +156
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +5486

________________________________________
Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

**Comment by NickCraver** [comment]
A lot of Azure issues were fixed in later versions of the library (including a lot of the symptoms here). If you're still having issues on latest (1.2.6 right now), please ping here and I'll reopen.
