### ISSUE TITLE
Non-IP Destinations without resolveDNS can lead to MemoryAccessViolations

### ISSUE THREAD

**Issue by phillipwei** [StackExchange/StackExchange.Redis#43]
If I do not set resolveDns=true, then I will sometimes get a AccessViolationException (System.Net.Dns.ResolveCallback ... System.Net.Dns.TryGetAddrInfo).  This seems to be a thread-safety issue, since it doesn't always happen.

But if I do set resolveDns=true, then I don't get this exception.  

ConnectionMultiplexer line 1086 seems to be where the the initial decision is being made - if thread safety cannot be guaranteed, then I think if configuration.HasDnsEndPoints() and !configuration.ResolveDns an exception should be thrown.

**Comment by NickCraver** [comment]
@phillipwei are you still hitting this? 18 months later we don't have a repro...so this I agree this is almost certainly either be a BCL bug or very specific to your environment somehow.

**Comment by phillipwei** [comment]
@nickcraver not sure -- no longer work where I was encountering this issue. Sorry! I'll close this issue as no one else seems to have encountered it.
