### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by drake69** [StackExchange/StackExchange.Redis#430]
randomly i got this error

> Timeout performing SET NHibernate-Cache:Medium:ACompany.FMS.Data.Objects.OperationStock.OilStockOperationBalance#77110:lock, inst: 0, mgr: ProcessReadQueue, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 1, clientName: MIL-S-613, IOCP: (Busy=0,Free=1000,Min=24,Max=1000), WORKER: (Busy=0,Free=32767,Min=24,Max=32767), Local-CPU: 0% (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)

Reading the suggested article I didn't find what's happening, can somebody point me to the right direction to resolve o workaround this error, I'm using a Hibernate Second Level Cache which is based on the main library StackExchange.redis

many thanks

**Comment by NickCraver** [comment]
We're looking at these in aggregate - collapsing in #450 so we can track these in one place.
