### ISSUE TITLE
channelPrefix disables Keyspace Notifications

### ISSUE THREAD

**Issue by zivillian** [StackExchange/StackExchange.Redis#439]
Using a connectionString with a [channelPrefix](https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Configuration.md#configuration-options) options seems to disable all [Keyspace Notifications](http://redis.io/topics/notifications).

As far as I can tell, all Pub/Sub Messages are checked against the prefix - if any is configured  ([RawResult.cs#L80](https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis/StackExchange/Redis/RawResult.cs#L80)). Since the Keyspace and Keyevent messages have a prefix of `__keyspace@` and `__keyevent@`, they will always be discarded if any channelPrefix is used on the ConnectionMultiplexer.

**Comment by NickCraver** [comment]
This is being worked on in #813 :)
