### ISSUE TITLE
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s)

### ISSUE THREAD

**Issue by rohitimuraks** [StackExchange/StackExchange.Redis#442]
Hi,

I have installed the Redis server on Linux box with IP xxx.xxx.xxx.123 and the server is running on the port 6379 (Default). I am trying to Create connection using the below code 
var configOption = new ConfigurationOptions();
             configOption.EndPoints.Add("xxx.xxx.xxx.123:6379");
             configOption.AllowAdmin = true;
             //configOption.AbortOnConnectFail = false;
             var multiplier = ConnectionMultiplexer.Connect(configOption);

but on executing the  var multiplier = ConnectionMultiplexer.Connect(configOption); line i get the following exception 
StackExchange.Redis.RedisConnectionException: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketClosed on PING.
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs: line 876
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs: line 854.

Kindly help.

**Comment by mgravell** [comment]
Any chance this is a firewall or routing problem?

**Comment by rohitimuraks** [comment]
I have disabled the firewall

**Comment by rohitimuraks** [comment]
Issue has been fixed I was missing on the configuration changes for bind in Redis.conf

**Comment by mathewspv** [comment]
Hi, I am getting the same issue after several successful connections, can you please tell me how did you resolve this issue?

An exception of type 'StackExchange.Redis.RedisConnectionException' occurred in StackExchange.Redis.dll but was not handled in user code

Additional information: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketClosed on PING

**Comment by rohitimuraks** [comment]
Hi,

The issue with me was that I was trying to Remotely connect to Redis server. 
My Solution: There is a configuration in Redis.config which says Bind IP. By default it is local server IP on which Redis server is running. This is a security feature provided by Redis. So if you are trying to access the Redis server from a client which is on some other machine then you need to inform Redis that this client is a trusted client and hence allow access. To do this you have to add the Client's IP in the Bind section of Redis.Conf file available in Redis installation path.

**Comment by wjdavis5** [comment]
You can also try RedisDesktopManager or redis-cli to connect from wherever this code is being ran to determine if this is an issue with SE.Redis or your server

**Comment by alexeyzimarev** [comment]
I have this with Mono on Linux (Ubuntu), trying to connect to both `localhost` or `127.0.0.1:6379` fails with this exception but RedisDesktopManager works fine.

**Comment by wsun4ipipeline** [comment]
I have load redis Docker on Ubuntu, it can access from my pc  , but not the app in the save server .

**Comment by rostislav-nikitin** [comment]
Has a same problem @ mono. 
Solution:
1. Download and unpack StackExchange.Redis library from there: https://www.nuget.org/packages/StackExchange.Redis.Mono/
2. Replace appropriate assemblies

Or use nuget manager (if possible) to replace packages to mono related.

**Comment by nikolay-256** [comment]
@rostislav-nikitin, Thank you very much!
The problem was in mono!
