### ISSUE TITLE
AutoComplete with Redis working fast on Windows server while it works slow on linux server

### ISSUE THREAD

**Issue by praveenpnj94** [StackExchange/StackExchange.Redis#445]
Hi,

I have written an Autocomplete Console application using Redis in C#. The application adds "Names" as keys and "Code" as values from SQL Database. After that, it searches the matching pattern using SearchKeys and displays the Name matching with the pattern given by the user. It works fine on localhost and windows server but takes a very long time on Linux Server. What could be the possible solution for my problem?

**Comment by NickCraver** [comment]
Can you supply more information here? Example code? Is the application on Windows or Linux? I'm not sure if we're talking about a .NET Core application issue, or a Windows vs. Linux Redis server issue.
