### ISSUE TITLE
OBJECT IDLETIME command Supported?

### ISSUE THREAD

**Issue by vpatel-fintech** [StackExchange/StackExchange.Redis#449]
Hi,

We want to fetch idle time of the key from Redis is there any way for that?

**Comment by orck-adrouin** [comment]
It looks like SE.Redis does not expose the OBJECT command.  However you can create a small Lua script to achieve what you want.

**Comment by mgravell** [comment]
More generally, I need to set aside some time to do a "all new commands"
sweep.

**Comment by NickCraver** [comment]
Tagging for #528.

**Comment by mgravell** [comment]
This is now implemented in 2.0, thanks

**Comment by mgravell** [comment]
note: as a 1.* workaround: `Execute` can invoke *anything*
