### ISSUE TITLE
socketfailure error

### ISSUE THREAD

**Issue by doterme** [StackExchange/StackExchange.Redis#453]
when i use stringget,i got a exception,how can i solve this error?
![image](https://cloud.githubusercontent.com/assets/12495369/17088157/44a00e9c-524a-11e6-95a1-ed931369d016.png)

**Comment by NickCraver** [comment]
Is this readily reproducible every time, or an intermittent error?

**Comment by NickCraver** [comment]
Closing this out to cleanup as we have several duplicates already.
