### ISSUE TITLE
How to make "Subscribe" block? 

### ISSUE THREAD

**Issue by wangkewei111** [StackExchange/StackExchange.Redis#456]
sub.Subscribe("messages", (channel, message) =>
            {
                Console.WriteLine((string)message);
            });

  It does not block. I want it block until there is a“Publish”,just like TcpListener.AcceptTcpClient()

**Comment by wangkewei111** [comment]
I get it.  Thread.Sleep......

**Comment by NickCraver** [comment]
What you want here is likely to await the Task version, like this:
```C#
await sub.SubscribeAsync("messages", (channel, message) =>
{
  Console.WriteLine((string)message);
});
```

**Comment by NickCraver** [comment]
Closing out to cleanup.
