### ISSUE TITLE
Expiry for SetAdd

### ISSUE THREAD

**Issue by hsimah** [StackExchange/StackExchange.Redis#462]
I'd like the ability to set an expiry when caching a set. Currently I use SetAdd and use KeyExpire immediately afterwards.

**Comment by NickCraver** [comment]
How would this work? `SetAdd` adds *members* to the set. You can only set the TTL on *the set itself*, so we're talking about 2 different entity levels here. 

For example, let's say we have an existing set with 1,000 items. You're adding 2 via `SetAdd`. What would the TTL be set on? Individual members don't have a TTL, only the entire set does.

**Comment by hsimah** [comment]
Goodness me, you're totally correct. I am just starting to implement redis and I have been caching a List<MyObject> as a single item in a set, not as individual set members. I feel a bit sheepish now and will close this.
