### ISSUE TITLE
SortedSetRemoveRangeByValue not removing integer

### ISSUE THREAD

**Issue by johnnycardy** [StackExchange/StackExchange.Redis#464]
I may have lost my mind, but I cannot get SortedSetRemoveRangeByValue to work in this scenario.

I have a sorted set where the values are integers. I want to remove one integer, by value. For example, to remove the value 101:

```C#
db.SortedSetRemoveRangeByValue(key, 101, 101);
```

I know it is odd to remove integers given that the range is considered to be lexicographical order. But I'd expect it to still work.

**Comment by NickCraver** [comment]
What you are doing is correct, an example test (just tried locally):
```c#
var key = "test";
var redis = ConnectionMultiplexer.Connect("127.0.0.1");
var db = redis.GetDatabase();
db.SortedSetAdd(key, "100", 100, CommandFlags.DemandMaster);
db.SortedSetAdd(key, "101", 101, CommandFlags.DemandMaster);
db.SortedSetAdd(key, "102", 102, CommandFlags.DemandMaster);
db.SortedSetScan(key, "*", 10, CommandFlags.DemandMaster).Select(e => e.Score).Dump();
db.SortedSetRemoveRangeByValue(key, "101", 101);
db.SortedSetScan(key, "*", 10, CommandFlags.DemandMaster).Select(e => e.Score).Dump();
```
I get the expected: `100,101,102` and then `100,102`.

Perhaps the test you're dealing with isn't waiting for the result to finish before checking? Or it's getting re-added elsewhere?

**Comment by johnnycardy** [comment]
I just ran your test and can no longer reproduce it...who knows what was going on two years ago. Thanks.
