### ISSUE TITLE
stackexchange.redis, 1.1.603 timeout performing exists

### ISSUE THREAD

**Issue by gunashekhar** [StackExchange/StackExchange.Redis#466]
Using stackexchange.redis. 

Though all the objects are really small and redis is a premimum one, i still see the queue @ 138 and more (with a minimal load of just less than 200 qps). Is the only possibility to use a pooled connection multiplexer or any other problems going on? 

Timeout performing EXISTS ctrl-9nblggh5wl6s-1466_en-us, inst: 3, mgr: Inactive, err: never, queue: 138, qu: 0, qs: 138, qc: 0, wr: 0, wq: 0, in: 9933, ar: 0, clientName: ConfigurationService_IN_0, IOCP: (Busy=59,Free=941,Min=299,Max=1000), WORKER: (Busy=35,Free=32732,Min=4914,Max=32767), Local-CPU: 100% (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)

StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl, ConnectionMultiplexer.cs, 2044
StackExchange.Redis.RedisBase.ExecuteSync, RedisBase.cs, 81
StackExchange.Redis.RedisDatabase.KeyExists, RedisDatabase.cs 425

**Comment by arbarik** [comment]
I am also using a premium Redis subscription. Facing the same issue. My message size is under 1000 bytes.  Getting the below exception.

Exception=Timeout performing ZADD offlinedlp:events:spop-sjc:lubrizol-my.sharepoint.com, inst: 12, mgr: Inactive, err: never, queue: 58, qu: 0, qs: 58, qc: 0, wr: 0, wq: 0, in: 9109, ar: 0, clientName: RD00155DFE44F9, IOCP: (Busy=24,Free=976,Min=4,Max=1000), WORKER: (Busy=0,Free=8191,Min=4,Max=8191), Local-CPU: unavailable (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)",8de7f95c-98f5-40ae-ad60-ba4bffbc7c6f.

Is Azure redis production ready ?

And what that exception means. (queue: 58, qu: 0, qs: 58). Going through some article they are saying 58 operations are in progress. once timeout happens does all that 58 operation getting cancelled ?

**Comment by NickCraver** [comment]
Can you please give version 1.1.605 a try? It's unlisted on NuGet, so install the specific version. We believe this may be one of the odd corner cases people are hitting with platform safe continuations behavior that we made changes to for 1.1.605 in hopes of addressing.

**Comment by NickCraver** [comment]
Closing this out to cleanup.
