### ISSUE TITLE
Bad Gateway exception when calling SetAsync / GetAsync

### ISSUE THREAD

**Issue by Ro3A** [StackExchange/StackExchange.Redis#471]
Using dnx 4.5.1, Azure Redis implementation for IDistributedCache. 

I have a barebones MVC action returning a view. If I add a call to "_cache.SetAsync" or "_cache.GetAsync"  in the action and set a breakpoint on it, the call returns and the process moves on to "return View()"

At this point the loading icon continues to spin. After a while I receive a Bad Gateway error. Nothing of value shows in the logs as far as I can see. If I switch these calls to the synchronous version everything works as expected. 

https://github.com/aspnet/Caching/issues/202 provides a valid work around albeit for a slightly different example. Adding "await Task.Delay(1)" immediately after the call seems to work well. Following the references in that thread I've not seen any clear indication of a fix for this and just wanted to keep this on the radar if it has not yet been resolved.

**Comment by stevejgordon** [comment]
@NickCraver I'm seeing similar issues as this item in our code. Not sure if this is 100% related so perhaps should be a new issue, which I can raise.

We're using "Microsoft.Extensions.Caching.Redis.Core": "1.0.3" to cache against an AWS Redis Elasticache.

This seems to use StackExchange.Redis.StrongName(1.1.608) which looking at #420 is newer than the fixed version.

Calls to both SendAsync and GetAsync against our cache seem to deadlock / never return. Adding the await Task.Delay(1); after both of them seems to workaround the issue as above.

We're targeting LTS ASP.NET Core (still project.json) at the moment.

If you need any other info, please let me know. Not knowing about about the async world, is this workaround "safe"? Any better solutions.

**Comment by NickCraver** [comment]
Are you still seeing this on the latest version? If so, can you please provide a sample of code so we can advise?

**Comment by NickCraver** [comment]
No updates here, so assuming this is resolved in all the changes since.

**Comment by stevejgordon** [comment]
Apologies Nick. I missed the last comment. As far as I've seen we've not experienced this since picking up newer versions of the library and .NET core in general. Thanks!
