### ISSUE TITLE
Timeouts with "net46" package (1.1.603) that didn't happen with "net45".

### ISSUE THREAD

**Issue by j-albert** [StackExchange/StackExchange.Redis#472]
Our app servers have been at .NET 4.6 for awhile. Our project targeted .NET 4.5.1 so we had been consuming the "lib/net45" version of StackExchange.Redis 1.1.603. We had no problems with this combination (other than developers using Task<T>.Result, but that's our own fault!)

Recently we changed the project to target .NET 4.6. NuGet dutifully asked us to reinstall StackExchange.Redis, thus consuming the "lib/net46" version of 1.1.603. However after the next deploy we started getting intermittent timeout errors. The variable appears to be the difference between the "net45" and "net46" versions of the 1.1.603 DLLs. When we reverted to the "net45" version, the timeouts disappeared. Some of the relevant exception data entries for a sample System.TimeoutException are:

Redis-Queue-Length = 791
Redis-Queue-Awaiting-Response = 791
Redis-ThreadPool-IO-Completion = (Busy=0,Free=1000,Min=2,Max=1000)
Redis-ThreadPool-Workers = (Busy=1168,Free=31599,Min=2,Max=32767)
Redis-Busy-Workers = 1168
Redis-Local-CPU = 0.24%

At this point, even after reading https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md, I'm uncertain whether we needed to change another setting after switching from the "net45" version to the "net46", or whether there's a legitimate issue between the binaries. Perhaps this has something to do with the PLAT_SAFE_CONTINUATIONS constant that's present in the 46 csproj but not in 45?

**Comment by mgravell** [comment]
I agree that this must be some subtle side-effect of PLAT_SAFE_CONTINUATIONS
- which is a shame, as that is *so nice*; I am investigating - will
probably do a deploy without this flag while I track it down.

**Comment by NickCraver** [comment]
Please give 1.1.605 (on NuGet, just unlisted) a try, this changes the `PLAT_SAFE_CONTINUATIONS` that @mgravell is talking about back to the previous behavior.

**Comment by j-albert** [comment]
Will do. I'll reply with our findings within a day or so. Thank you!

**Comment by j-albert** [comment]
I've verified in our test environment that the timeouts described in the original report are no longer occurring with version 1.1.605 targeting net46. Thank you for the prompt attention! I hope you're able to fix whatever's amiss when that flag is enabled. I see how it makes the code cleaner.
