### ISSUE TITLE
Timeout exception when using async KeyDelete

### ISSUE THREAD

**Issue by agoretsky** [StackExchange/StackExchange.Redis#477]
Hello! 
I am getting this exception:
System.TimeoutException: Timeout performing SCAN, inst: 1, queue: 16, qu: 0, qs: 16, qc: 0, wr: 0, wq: 0, in: 149, ar: 0, clientName:  (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisServer.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.CursorEnumerable`1.CursorEnumerator.MoveNext()

When use this code:

```
public class RedisCacheStorage : ICacheStorage
{
    private readonly int defaultDatabaseNumber;

    private readonly ConnectionMultiplexer redis;

    public async Task DeleteKeyByPatternAsync(string pattern)
    {
        Console.WriteLine(pattern);
        foreach (var endPoint in this.redis.GetEndPoints())
        {
            var server = this.redis.GetServer(endPoint);
            var database = this.redis.GetDatabase();
            foreach (var key in server.Keys(this.defaultDatabaseNumber, pattern))
            {
                await database.KeyDeleteAsync(key);
            }
        }
    }
}
```

But if I change it to sync implementation everything is OK:

```
    public Task DeleteKeyByPatternAsync(string pattern)
    {
        Console.WriteLine(pattern);
        foreach (var endPoint in this.redis.GetEndPoints())
        {
            var server = this.redis.GetServer(endPoint);
            var database = this.redis.GetDatabase();
            foreach (var key in server.Keys(this.defaultDatabaseNumber, pattern))
            {
                database.KeyDelete(key); // we do not use async implementation because it causes timeouts..
            }
        }

        return Task.FromResult(0);
    }
```

I am using ASP.NET Core RTM on .NET Core, and StackExchange.Redis 1.1.604-alpha. 
Why I am getting timeouts?

**Comment by NickCraver** [comment]
Is this 100% of the time, or randomly? Can you please give version `1.1.605` a try? It's unlisted but avaialable in NuGet. We reverted the .Net 4.6 continuations behavior in that build.

**Comment by agoretsky** [comment]
Thank you for response, this is 100% of the time, I will try 1.1.605 at the monday and leave feedback here.
By the way using sync implementation under load of our app auto-tests I've got this reproducible problem too, but not so often how with async . Next I tried to cache keys:

```
foreach (var endPoint in this.redis.GetEndPoints())
            {
                var server = this.redis.GetServer(endPoint);
                var database = this.redis.GetDatabase();
                var keys = server.Keys(this.defaultDatabaseNumber, pattern).ToArray();

                database.KeyDelete(keys);
            }
```
And all auto tests pass(we are currently use this version and haven't got this problem yet). So I have decided to cache keys as above but use async version for deletion - it failed with described exceptions.

**Comment by agoretsky** [comment]
@NickCraver, 1.1.605 fixes this reproducible issue with async deletion. 
But under load I am still getting these exceptions randomly both in 1.1.604-alpha and 1.1.605, so will read this https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Timeouts.md and trying to understand how to fix it
Thank you

**Comment by NickCraver** [comment]
@agoretsky can you again try latest? We made a few more tweaks which may help here, but it will help as us as well knowing which situations still exist as we make another debug pass.
