### ISSUE TITLE
GET Timeouts

### ISSUE THREAD

**Issue by dj-curls** [StackExchange/StackExchange.Redis#481]
> System.TimeoutException: Timeout performing GET commdevice.logging-3671, inst: 2903, queue: 3063, qu: 0, qs: 3062, qc: 1, wr: 1, wq: 1, in: 40886, ar: 0, clientName: IP-AC80020E, IOCP: (Busy=748,Free=4252,Min=2,Max=5000), WORKER: (Busy=339,Free=4661,Min=2,Max=5000), Local-CPU: 0%

Seeing a lot of timeouts on start up of our application. This is from a production server.
Server is running on an adequate (as far as I can see) AWS Elasticache instance.
Was using version 1.1.603, have upgraded to 1.1.605 - doesn't seem to have made a difference. 

Connection strings are

> private static string serversRead = $"{ ConfigurationManager.AppSettings.Get("RedisServer") },syncTimeout=1000,abortConnect=false,allowAdmin=true";

and

> private static string serversWrite = $"{ ConfigurationManager.AppSettings.Get("RedisServer") },syncTimeout=5000,abortConnect=false,allowAdmin=true";

'commdevice.logging-3671' is a particularly small piece of data, however there are larger values in there, but nothing too big.

I have attached the 'info' command output from the redis server
[redis-info.txt](https://github.com/StackExchange/StackExchange.Redis/files/467568/redis-info.txt)

Where can I find out what 'inst', 'queue', 'qu', 'qs', 'qc', 'wr', 'wq', 'in' and 'ar' refer to?
What can I do to start troubleshooting this?
Where can I look for any other info?

**Comment by gzpbx** [comment]
I think the information is here but it doesn't work for asp.net core (we encounter the same issue )
https://github.com/StackExchange/StackExchange.Redis/blob/1.1.605/Docs/Timeouts.md

**Comment by NickCraver** [comment]
Can you please try the latest library? We've added more info to the exception and are getting back into this now.

**Comment by NickCraver** [comment]
Merging into #450 so we can track this in one place.
