### ISSUE TITLE
System.Threading.ThreadAbortException: Thread was being aborted. 

### ISSUE THREAD

**Issue by geogeqq** [StackExchange/StackExchange.Redis#488]
Azure web-role to access a linux-based redis, periodically throw
"System.Threading.ThreadAbortException: Thread was being aborted.   at StackExchange.Redis.SocketManager.ReadImpl()   at StackExchange.Redis.SocketManager.Read()"

make the webrole restart

**Comment by NickCraver** [comment]
Is this happening when the application crashes as a whole. If not, what's the scenario? This indicates something is tearing down all threads.

**Comment by itn3000** [comment]
I found the exception in executing unittesting with VS2015+nunit.(test success, logged in vs debugging window)
Here is my repro code.
[RedisAbortTest.zip](https://github.com/StackExchange/StackExchange.Redis/files/641218/RedisAbortTest.zip)

I think it may be occured in specific synchronizationcontext.

**Comment by itn3000** [comment]
sorry, I misounderstood. PreserveAsyncOrder was not affected. Regardless of whether PreserveAsyncOrder is true or false, ThreadAbortException was occurred.

**Comment by NickCraver** [comment]
@itn3000 Am I understanding correctly that NUnit is simply tearing down the connection? If the multiplexer isn't being disposed, yes, this could definitely happens when the application ends.

**Comment by xinghe3** [comment]
@NickCraver  I also found same problem, I called Dispose() at the end of test to avoid the exception. Is there any other solutions that multiplexer can be disposed by itself?

**Comment by itn3000** [comment]
@NickCraver 
After I appended "Dispose()" at the end of unit test, then the problem seemed to be not occured.
Thank you.

**Comment by NickCraver** [comment]
Excellent, thanks for the update! Closing out to cleanup :)

**Comment by FONG1234** [comment]
Currently, I also facing the same problem of "System.Threading.ThreadAbortException: Thread was being aborted.". After I opened the thread and run the process, sometimes this exception will happen when I run the process for 70 times, sometimes this exception will happen when I run the process for 100 times, it don't have an order. For your solution, you guys using Dispose, but I am not sure actually where you guys put the Dispose (). Grateful for who willing to help me.
