### ISSUE TITLE
Redis server exception if empty array passed to SetRemove

### ISSUE THREAD

**Issue by kilroytrout** [StackExchange/StackExchange.Redis#492]
An empty RedisValue array passed to SetRemove will result in a RedisServerException:

"wrong number of arguments for 'srem' command"

**Comment by NickCraver** [comment]
We should probably just short-circuit and pretend this worked, thoughts @mgravell?

**Comment by NickCraver** [comment]
Tagging for #528

**Comment by NickCraver** [comment]
This is now handled in the v2 branch - we'll throw early with null arguments early and handle zero-length arrays as "yeah sure that worked" returning `0` items removed...but never hitting redis. Thanks for the suggestion!
