### ISSUE TITLE
Support for redis GeoSpatial indexes

### ISSUE THREAD

**Issue by GoldenCrystal** [StackExchange/StackExchange.Redis#496]
Hello,

I wanted to do some experiments on the geospatial indexes added with Redis 3.2, but I realized they are not implemented in StackExchange.Redis.
After a bit of search, I found pull request #381 but it seems to be dead.
Do you still have plans to support this feature ?

Thanks

**Comment by ataylorm** [comment]
I second this request!

**Comment by neuecc** [comment]
Redis Geo is an important feature; please support.

**Comment by ralison** [comment]
Also agree!

**Comment by caseymarquis** [comment]
Looks like WJD made a commit last month, so it doesn't seem dead as much as not moving ahead terribly quickly.

**Comment by caseymarquis** [comment]
I think an issue with this right now is that the Geo features were added in redis 3.2, and the highest nuget package available for redis is 3.0. This means you can't just clone the repo, rebuild the solution, and run tests. Their latest stable binary is 3.2 however, so I'd think they should be close to getting this done.

**Comment by caseymarquis** [comment]
So I grabbed WJD's branch and forked it, updated it from the main repo, neatened it up, wrote some tests, and got all the geo functionality he'd put together working along with async versions, etc, etc. I did have to modify Message to allow an argument to be passed along inside of it. Seemed like a good idea at the time:

https://github.com/caseymarquis/StackExchange.Redis/commits/master

Not really sure how pull requests work as we don't use them internally at my 9 to 5, but if anyone's interested in integrating this, then let me know. Or just steal it. Preferably that.

I need this for a personal project, so I'm just going to start using it as is, but if there's an interest in getting this into the main project let me know and I'll do what I can to help if I've got some time. Seems like there were some issues with newlines or something at some point, which probably makes direct merging a PITA; so someone would probably have to play with things a bit. Not sure if that came from WJD, myself, or if the repo was in a weird state to begin with. Best.

**Comment by Renti** [comment]
Please, I implore you, put a high priority on the GEO-commands so that their functionality can be put to use. I'm working on a project where the GEOADD and GEORADIUS commands would be extremely useful to reduce the size of a query but I can't use them. I'll clone and try to use caseymarquis's fork from WJD, but if that doesn't work then I'm stuck with having to retrieve a bunch of data I don't need that will be filtered away server-side which is a complete waste. Please get the GEO-commands up and running ASAP!

**Comment by caseymarquis** [comment]
@Renti if you're looking to push this the extra mile to get it integrated, I'd guess the todo list would be to:

1. Move all the geo code into a single file.
2. Undo WJDs 127.0.0.1 => 192.168.x.x changes. (I actually created a loopback adapter as I thought this was from the original)
3. Try to correct any tab/space/newline modifications or pull the latest version and manually reinsert everything with something like beyond compare.
4. Get approval for how I modified Message.
5. Maybe more tests?

My fork worked in testing, so it shouldn't be too far from something you can use.

**Comment by mgravell** [comment]
I've scheduled some time on SE.Redis, and getting the geo API finished up
and deployed is top of the list.

**Comment by mgravell** [comment]
This is now available in https://www.nuget.org/packages/StackExchange.Redis/1.2.0-alpha1

Closing.
