### ISSUE TITLE
How to pass dynamic script parameters

### ISSUE THREAD

**Issue by gtarsia** [StackExchange/StackExchange.Redis#501]
I really like the way to pass named parameters to a script like this:  

```
EvaluateAsync(..., new { "name" = "Mike" })
```

But what if I want to send n parameters? We obviously can't add properties to the object, and probably wouldn't make sense if the script is already loaded (because you don't know the name of each).  
Is there a way to handle this? I tried passing a `List<dynamic>` as parameters but it didn't work.

**Comment by NickCraver** [comment]
> We obviously can't add properties to the object

Ah but you can! Create a dynamic that you pass in, and you can add whatever you want to that way, before passing it to the method. This allows you to programmatically add properties as you wish.

**Comment by erandros** [comment]
You mean using an ExpandoObject? Because I've read that you can't add properties to an anonymous type (as shown in my post). Is ExpandoObject recognized by this lib?  
But even in that case, you still have to name the args with *@name*. And if I'm passing variable amounts of ARGV to a loaded script, I don't know the names beforehand to write in the script.

**Comment by erandros** [comment]
Bump

**Comment by NickCraver** [comment]
@gtarsia I missed the update here - I'm not sure what you're after. If you're saying you know *nothing* about the args or the names, I'm not sure how you could write anything. If it's all position based or some such, then just use that as your convention in both, e.g. `param1`, `param2`, etc.

**Comment by mgravell** [comment]
The only way to do this with dynamic ranges of values is to use the raw `ScriptEvaluate` API; this takes two inputs - one an array of keys, one an array of values. Your script can then access this via `ARGV` and `KEYS` (via indexers in the Lua)
