### ISSUE TITLE
Connection Singleleton Instance

### ISSUE THREAD

**Issue by HaythemJ** [StackExchange/StackExchange.Redis#507]
Is it recommended having only one Open Connection? I am using Redis Cache in ASP.NET application and I am creating only one connection instance( Singleton) that I am storing into a Dependency Injection Container Unity.

Is this recommended? or should I get a new connection for each REST Request?

**Comment by tayl0r** [comment]
this is covered in the docs: https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Basics.md

**Comment by NickCraver** [comment]
Yes, you want to reuse the `ConnectionMultiplexer` for very long durations (e.g. life of the application), not create one per. 

Closing this out to cleanup, but happy to answer any more questions!
