### ISSUE TITLE
Socket Failure on PING, Redis 3.2.4

### ISSUE THREAD

**Issue by kstrasters** [StackExchange/StackExchange.Redis#511]
We recently setup a new box with Redis 3.2.4 and are trying to use StackExchange.Redis v1.1.603 to connect to a multiplexer. We have an existing instance of Redis 2.8.17 that we also use your tool for and it works great, but since setting up this new box with the new Redis version, whenever we try to setup a new connection we get a Socket Failure on PING. We have tried many things and were wondering if you had any insights, or if the new Redis version was incompatible or something?

**Comment by NickCraver** [comment]
@kstrasters Is this still an issue on current versions? I'd give 1.2.6 a try and see if this still causes any issues.
