### ISSUE TITLE
Advice on choosing the "Least Loaded" Multiplexer when pooling

### ISSUE THREAD

**Issue by dendle** [StackExchange/StackExchange.Redis#512]
Hello All,

We've been seeing some timeouts regarding redis, and followed the great advice from the docs.

This seems to have helped, and now we are looking to implement pooling for the ConnectionMultiplexer as per the documentation [here](https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Timeouts.md#was-there-a-big-request-preceding-several-small-requests-to-the-redis-that-timed-out).

However, the linked paragraph mentions choosing the "Least Loaded" connection to use from the pool - how do I choose the least loaded? I can see a property called OperationCount I suppose I could use this as a metric to choose - but is there any other mechanism I can use to estimate the load that the documentation is referring to?

Thanks in advance,
Matt

**Comment by ajeckmans** [comment]
We would like to know as well. Currently we're using a function in our products which loops over our pool and gets the least loaded by looking ad the TotalOurstanding counter for the connection, but I can't shake the feeling it is a bit awkward and that there is a better way to do it somewhere out there.

**Comment by NickCraver** [comment]
In general for this information, you're looking under `connectionMultiplexer.GetCounters()`, e.g. `connectionMultiplexer.GetCounters().TotalOutstanding`

**Comment by NickCraver** [comment]
Answered above, so going to close this out :)
