### ISSUE TITLE
Question: Flushing FireAndForget messages

### ISSUE THREAD

**Issue by stankovski** [StackExchange/StackExchange.Redis#519]
This is a question. I have a system where I read from EventHubs as fast as I can (tens of thousands of events per second) and write to Redis at the same frequency in a FireAndForget way (it's OK if a few events get lost). Every so often I need to checkpoint EventHubs and for that I need to make sure that all Redis writes have been flushed. Is there a way to do that? 

Also, I've noticed a significant memory usage with FireAndForget. Is there a way to limit how many messages can be in a pipeline at a given time?

**Comment by NickCraver** [comment]
Can you provide some more info on "significant"? What volume of messages in the pipe and memory usage are you seeing? Example code would help a ton here.

As for seeing if there's nothing in the pipe: we could expose this counter, but would that actually solve it, or are you looking for something awaitable from a certain snapshot point? e.g. "wait until all events before NOW are complete"?

**Comment by stankovski** [comment]
I found a way to get the "pipeline" size via `connectionMultiplexer.GetCounters().TotalOutstanding` and am now using that to limit the amount of requests in the pipeline. 

I didn't record the number of messages I had when I was seeing memory issues as I didn't know of TotalOutstanding option. Now I'm "self-throttling" writes to Redis by limiting the TotalOutstanding to 10K and I haven't seen any issues with memory consumption since.

It would be nice to have such a threshold in IConnectionMultiplexer and not return FireAndForget or Async operation right away in case the threshold is reached.

**Comment by NickCraver** [comment]
Thanks for the feedback! If this comes up again we'll keep it in mind, but as it stands I'm going to treat that more of an application concern. Reasoning: if we had such a limit and someone set it, they'd just be experiencing a large deadlock in a *different* spot. One they don't have great control to stop feeding all the way down their pipe, whereas if a user controls it they can control there the backpressure in the pipe lies.

Glad you're up and running - going to close this out to cleanup :)
