### ISSUE TITLE
LINQ ?

### ISSUE THREAD

**Issue by PivotalAnimal** [StackExchange/StackExchange.Redis#523]
I have been looking at ServiceStack and StackExchange both some. It looks like ServiceStack provides some convenience methods to allow for using LINQ queries. But their library seems to cost money. I could instead use this library to store items as collections, deserialize them and do the same thing I am guessing. Having only looked at theirs and yours code a little, I don't know what the internals do exactly as for space and efficiency. Does native Redis support any notion of querying data thus improving performance if using one implementation over the other? Of do both libraries ultimately serialize and deserialize large objects from the redis to the client and use the clients memory for these operations. I hope this makes sense. Thanks in advance!

**Comment by NickCraver** [comment]
Redis supports *some* semantics (none that we directly implement as a LINQ provider) for such things, but there are very few. For example taking a range of items from a larger set can be done (a slice), but not much beyond that. I'm guessing you're talking more about `.Where()` clauses and such which isn't supported.

Technically Redis could do some of this via `LUA` scripting, but that's not really the intended use case and not very efficient. If your aim is to filter data like this regularly, I would respectfully suggest that Redis may not be the best data store option available to you. It does a lot of things and it does them *very* well, but that may or may not match your list of what you *want* it to do.

If you could provide some examples, I could give a bit more specific info!

**Comment by PivotalAnimal** [comment]
I'm looking at your tests. Do you have an example of a slice?

**Comment by MichaCo** [comment]
@PivotalAnimal @NickCraver 
I guess Nick meant the [LRANGE](http://redis.io/commands/LRANGE) command which is available by this client via e.g: 

    ....ListRange("key", 10, 20);

==> returns you element at index 10 through 20 from the list at the 'key'

Regarding a Linq provider, as Nick mentioned, Redis is not meant to be a database you can run SQL like queries against. There are no indexes on columns etc... You can do SCANs over all keys and hashes though, but those are not optimized at all and therefore very inefficient and shouldn't be used to build app logic with.

**Comment by PivotalAnimal** [comment]
Understood. I think this will meet our needs. Thanks!
