### ISSUE TITLE
Redis Connections changes

### ISSUE THREAD

**Issue by flowdopip** [StackExchange/StackExchange.Redis#525]
Hi,

I have on Production Server Redis wtih 2.8.4 version and .NET solution with StackExchange.Redis 1.0.488.

The setup with master and slave on Linux VM over Azure

We are delaling with 1.37k commands /sec, 35 client connections and a average of 9GB of memory stored and several times our applications logs this info:

REDIS ConfigurationChanged Unspecified/
REDIS ConnectionRestoredUnspecified/
REDIS ConnectionFailed SocketFailure on

Same time we have a lot of System.Timeout when Gets to Redis. 

We only use HGetALL, HGET, HMSET, SET, GET, RPush, LRange, LIndex Commands.

Any ideia?

**Comment by NickCraver** [comment]
Can you please try on a current version of the library? We're up to 1.1.608 on NuGet now, which has quite a few fixes in there.

**Comment by flowdopip** [comment]
Yes, i did that, but now i have new error´s:

REDIS InternalErrorSystem.InvalidOperationException: Queue empty.
REDIS ErrorMessage READONLY You can't write against a read only slave.

when this appends a have 5.7k commands /sec

**Comment by flowdopip** [comment]
this is the settings on the server

root@RDS01:/home/XXadmin# cat /etc/redis/redis.conf
daemonize yes
pidfile "/var/run/redis/redis-server.pid"
port 6379
bind 0.0.0.0
timeout 60
tcp-keepalive 0
loglevel notice
logfile "/var/log/redis/redis-server.log"
databases 16
#save 900 1
#save 300 10
#save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression no
rdbchecksum yes
dbfilename "dump.rdb"
dir "/mnt/redisrdb"
masterauth "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
slave-serve-stale-data yes
slave-read-only yes
repl-disable-tcp-nodelay no
repl-timeout 1200
repl-backlog-size 1gb
slave-priority 100
requirepass "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
maxmemory 24gb
maxmemory-policy volatile-ttl
appendonly no
appendfilename "appendonly.aof"
#appendfsync everysec
appendfsync no
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
lua-time-limit 5000
slowlog-log-slower-than 100
slowlog-max-len 128
notify-keyspace-events ""
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-entries 512
list-max-ziplist-value 64
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
aof-rewrite-incremental-fsync yes
maxclients 3952

**Comment by flowdopip** [comment]
I´ve checked several post with this problem and timeouts. Several people has this problems on load enviroments! 

Any help?

**Comment by flowdopip** [comment]
changed to other cluster with different configuration

**Comment by kylixtan** [comment]
do you find-out the difference?
