### ISSUE TITLE
Redis ListRightPop extremly slow

### ISSUE THREAD

**Issue by eddadjei** [StackExchange/StackExchange.Redis#527]
All what am doing is _redisDatabase.ListRightPop(PendingQueueName); and its super slow against a linux instance.

**Comment by NickCraver** [comment]
Can you define "super slow"? Can you provide some repro code?

**Comment by eddadjei** [comment]
What I meant is, other operations examples (adding to list, sorted list, hashset) yeilds about 9,789 ops per second but when only doing ListRightPop(PendingQueueName) it yeilds 25 ops per second all with the same library against a linux redis instance out of the box configuration. Also, same code pointed to a windows redis instance works ok (yeilds about 900 ops per second for ListRightPop) but not for redis running on either Mac, or Linux. Here is a code sample.running again a list with 200K items.

This is my factory to get an IDatabase
`   public class RedisStore
    {
        private static Lazy<ConnectionMultiplexer> _lazyConnection;
        private static readonly object RedisObjectLock = new  object();

        public static void Initialize(params string[] endPoints)
        {
            lock (RedisObjectLock)
            {
                if (_lazyConnection != null)
                    return;

                var configurationOption = new ConfigurationOptions
                {
                    AllowAdmin = true,
                    AbortOnConnectFail = false
                };

                foreach (var endPoint in endPoints)
                    configurationOption.EndPoints.Add(endPoint);

                _lazyConnection = new Lazy<ConnectionMultiplexer>(() => ConnectionMultiplexer.Connect(configurationOption));
            }
        }

        public static ConnectionMultiplexer Connection
        {
            get
            {
                return _lazyConnection.Value;
            }
        }

        public static void Dispose()
        {
            _lazyConnection.Value.Dispose();
        }
    }
}`

This is the code for getting items from the queue.
` public string Dequeue()
  {
       var messageId = RedisStore.Connection.GetDatabase().ListRightPop(PendingQueueName);
       if (string.IsNullOrEmpty(messageId))
           return null;
       return messageId;
 }`

**Comment by eddadjei** [comment]
Any updates?

**Comment by mgravell** [comment]
In this scenario, what is the size of the keys and payloads in the
different operations? Are they comparable? If so, this doesn't sound like a
library issue, but: a server issue. The library doesn't do much different
between these operations.

**Comment by eddadjei** [comment]
this is the actual value of the key am passing in

private const string PendingQueueName = "strimeo:queue:pending";
RedisStore.Connection.GetDatabase().ListRightPop(PendingQueueName)

And the Redis Value it returns is a guid. eg: "cc4924a2-3ee1-4318-8d9f-2eb46ba64fae"

**Comment by mgravell** [comment]
That shouldn't trip it at all. I very much doubt that this is a library
issue- it sounds more like a server configuration problem, especially as it
depends on the server back-end.

**Comment by NickCraver** [comment]
Closing this out to cleaning barring any new info - definitely agree this appears to be entirely server-side.
