### ISSUE TITLE
“No connection is available” when running in NUnit

### ISSUE THREAD

**Issue by urig** [StackExchange/StackExchange.Redis#530]
Please consider the following code, running against an [Azure Redis Cache][1]:
```C#
    var url = "...";
    var password = "...";

    var connnection = ConnectionMultiplexer.Connect(
        $"{url}, abortConnect=false, ssl=true, password={password},
        connectTimeout=10000, syncTimeout=10000, name=RedisCache");

    var database = connnection.GetDatabase();

    database.StringSet("some_key", "some_value");
```

When I run the code in a console application it works fine. When I run it inside an NUnit test it fails with this exception:

```
 StackExchange.Redis.RedisConnectionException : No connection is available to service this operation: SET some_key  
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor'1 processor, ServerEndPoint server)  
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor'1 processor, ServerEndPoint server)  
   at StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable'1 expiry, When when, CommandFlags flags)  
```

Why does this happen in NUnit?

  [1]: https://azure.microsoft.com/en-us/services/cache/

**Comment by NickCraver** [comment]
Can you give us some more information here? Is this one test that fails? One of many? Which platform are you running on?

**Comment by stanisls** [comment]
I experience the same problem:  Running NUnit (v3.12.0) integration tests results in consistently failing Redis connections, while running exactly the same code with exactly the same connection string either from VS in debug mode or stand-alone works perfectly. Here is the output log from the failing connection attempt:

`
server:6379,connectTimeout=500,connectRetry=1,defaultDatabase=9

Connecting server:6379/Interactive...
BeginConnect: server:6379
1 unique nodes specified
Allowing endpoints 00:00:00.5000000 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=1020,Min=4,Max=1023)
Finished awaiting tasks, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=4,Free=1019,Min=4,Max=1023)
server:6379 faulted: UnableToConnect on server:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
No masters detected
server:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: ConnectedEstablishing; sub: ConnectedEstablished, 1 active; not in use: DidNotRespond
server:6379: int ops=7, qu=0, qs=5, qc=0, wr=0, socks=2; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
Circular op-count snapshot; int: 0+7=7 (0,70 ops/s; spans 10s); sub: 0+3=3 (0,30 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
connection failed: server:6379 (Interactive, UnableToConnect): UnableToConnect on server:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
`
The resulting exception reads:
`
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on server:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.601.3402
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Object configuration, TextWriter log)
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log)
`

Here is a successful connection when simply running the application from Visual Studio:

`
server:6379,connectTimeout=500,defaultDatabase=9


Connecting server:6379/Interactive...
BeginConnect: server:6379
1 unique nodes specified
Allowing endpoints 00:00:00.5000000 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=8188,Min=4,Max=8191)
Connected Interactive/server:6379
Server handshake
Setting client name: VAR-D-DEV13
Auto-configure...
Sending critical tracer: Interactive/server:6379
Writing to Interactive/server:6379: ECHO
Flushing outbound buffer
Starting read
Response from Interactive/server:6379 / ECHO: BulkString: 16 bytes
Writing to Interactive/server:6379: PING
Response from Interactive/server:6379 / PING: SimpleString: PONG
All tasks completed cleanly, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=4,Free=8187,Min=4,Max=8191)
server:6379 returned with success
Single master detected: server:6379
server:6379: Standalone v3.0.7, master; 16 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablishing
server:6379: int ops=10, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=2, qu=0, qs=3, qc=0, wr=0, socks=1
Circular op-count snapshot; int: 0+10=10 (1,00 ops/s; spans 10s); sub: 0+2=2 (0,20 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Starting heartbeat...
`
