### ISSUE TITLE
Support Execute (ad-hoc commands, like modules) on IServer?

### ISSUE THREAD

**Issue by ckatili** [StackExchange/StackExchange.Redis#535]
As the title says, does StackExchange.Redis allow a client calling a command in Redis Module (in Beta)?

If not, any plan and/or timeline to add support for it?

Thank you.

**Comment by NickCraver** [comment]
This isn't something that's supported *right now*. However, it's something Marc was pitching me ideas on last week though - it's on our mind for an upcoming release. 

@mgravell may know more about any gotchas or uncertainties hit after we talked.

**Comment by mgravell** [comment]
*right now*, the only way to do this is via ScriptEvaluate and Lua. I am
investigating appropriate ways to expose a rich extensible API that allows
external callers to describe both simple and complex call semantics without
it being an unholy mess of crazy.

**Comment by dvirsky** [comment]
@mgravell is there any way to just allow users to execute unknown commands, like most clients do?

**Comment by NickCraver** [comment]
@dvirsky There is `IDatabase.Execute()` and `IDatabase.ExecuteAsync()` for this :)

**Comment by wasabii** [comment]
@NickCraver  Do any such equivalent commands exist on IServer?

**Comment by wasabii** [comment]
For Cluster management. CLUSTER FAILOVER, etc. Hard to make sure those run against a specific node.

**Comment by mgravell** [comment]
We could replicate this API on IServer, preselecting the node. Wouldn't be
massive work.

**Comment by NickCraver** [comment]
@wasabii thanks, that helps indeed. We'll take a look in the API pass of v2, agree this should be added.

**Comment by mgravell** [comment]
re-titling to clarify the outstanding work

**Comment by mgravell** [comment]
Implemented for 2.0
