### ISSUE TITLE
how to connect clusters with only one node

### ISSUE THREAD

**Issue by anytime-hxy** [StackExchange/StackExchange.Redis#538]
if the node is down ,the client throw a no-connection exception.how to connect clusters with only one node，but the one is down ,the other can connect.Thanks

**Comment by NickCraver** [comment]
I'm trying to parse the question here, not sure I'm understanding. In a cluster situation, for maximum redundancy you want to list all the endpoints. While we'll discovery and add, if you're only listing say `1` of `n`, it really depends on the 1 being up. If you list them all as endpoints, we're resilient to initial nodes being offline.

Hope this helps :)
