### ISSUE TITLE
asp.net core concurrency issues

### ISSUE THREAD

**Issue by mycsj** [StackExchange/StackExchange.Redis#539]
environment 

windows 7
.net core sdk 1.0.0
vs code 1.8.1
StackExchange.Redis  1.1.608
redis 3.2

project.json
```json
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "StackExchange.Redis": "1.1.608"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "debugType": "portable"
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },

  "tooling": {
    "defaultNamespace": "Test"
  }
}
```

Startup.cs

```csharp
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddSingleton(ConnectionMultiplexer.Connect("127.0.0.1:6379") as IConnectionMultiplexer);
            services.AddMvc();
        }       
```

TestController

```cshapr
        public readonly IConnectionMultiplexer _connect ;

        public ValuesController(IConnectionMultiplexer connect){
            _connect = connect;        
        }

        [HttpGet]
        [RouteAttribute("/")]
        public string Get()
        {
            return _connect.GetDatabase().HashGet("session:abcdefg","session").ToString();
        }
```

use ab test
ab -c 100 -n 100 http://127.0.0.1:5000/

exception message

"Timeout performing HGET session:abcdefg, inst: 6, queue: 6, qu: 0, qs: 6, qc: 0, wr: 0, wq: 0, in: 115, ar: 0, clientName: xxxx (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)"

but in vs 2015. Net 4.5 environment there is no such problem

**Comment by mycsj** [comment]
No one to answer the question?

**Comment by mycsj** [comment]
do it yourself and you will get food and clothing you need
ample food and clothing through self reliance

**Comment by NickCraver** [comment]
This is a reason to add #505 in, @mgravell let me know when you're at a calm point on Geo and I'll merge that in. It should be good to go as-is, but should definitely be in the next release.

**Comment by cleverguy25** [comment]
@NickCraver [#505 ](https://github.com/StackExchange/StackExchange.Redis/pull/505) certainly helps when not running core, but that code specifically is commented out in core.  [#599](https://github.com/StackExchange/StackExchange.Redis/issues/599) sounds very similar to this issue, although at higher gs and in variables.

**Comment by NickCraver** [comment]
This debug info is not in `netstandard2.0` as well, which enables it on Core. There has also been a *ton* of work on the .NET Core side that drastically impacts things here. The landscape has changed so much (including more information in the message), I'm going to close this specific issue out. If anyone is still hitting a distinct timeout issue though, please (using 1.2.6 or later) open an issue with the error message...it'll help is greatly in debugging.

**Comment by philiahe** [comment]
1.2.6 still have this problem

**Comment by NickCraver** [comment]
@philiahe We suggest upgrading to the 2.x release - 1.x needed sweeping architectural changes to address a lot of the connectivity issues and some breaking changes, so that's why it's a major version bump. 1.x will receive no further updates.

**Comment by philiahe** [comment]
> @philiahe We suggest upgrading to the 2.x release - 1.x needed sweeping architectural changes to address a lot of the connectivity issues and some breaking changes, so that's why it's a major version bump. 1.x will receive no further updates.

thx a lot , ok now ~
