### ISSUE TITLE
有大牛在吗

### ISSUE THREAD

**Issue by anytime-hxy** [StackExchange/StackExchange.Redis#540]

**Comment by mgravell** [comment]
google translate says "is there a big cow". Assuming this is spam?

**Comment by anytime-hxy** [comment]
can i use one node to connect redis cluster,when it down,but it has slave enable，the stackexchange.redis throw connection error

**Comment by mgravell** [comment]
what *exactly* is the error message? if the cluster hasn't successfully
swapped in the slave, you'll get "cluster down" - the library can't help
with that, as that is a server issue. If the error is related to other
logistics issues, it might be able to help. so what is the error message?

**Comment by mycsj** [comment]
就是一个坑
