### ISSUE TITLE
I want to get the hash list via script

### ISSUE THREAD

**Issue by vvvsrx** [StackExchange/StackExchange.Redis#542]
I want to get the hash list via script,but can not get list in C #.
this is my lua script:
``` lua
local results = {};
local insert = table.insert;
local rcall = redis.call;

for i=1,table.getn(KEYS) do
	local value = rcall('HGETALL', KEYS[i])
	insert(results, value)

end;
return results;
```

my C# code:
``` csharp
using (var redis = ConnectionMultiplexer.Connect(/* init code */))
{ 
    var db = redis.GetDatabase();
    var keys = new RedisKey[]{ "{a}1","{a}2" };
    const string Script = "local results = {};local insert = table.insert;local rcall = redis.call;for i=1,table.getn(KEYS) do local value = rcall('HGETALL', KEYS[i]); insert(results, value) end;return results;";
    var data = db.ScriptEvaluate(Script, keys);
}
```

How can I convert data(RedisResult) to `List<T>`?

thx~

**Comment by mgravell** [comment]
I apologise for this one falling between some cracks. Genuinely: sorry.

You'll hate me, but the answer is actually very short - which I'm sure makes it more frustrating that I utterly failed to answer promptly (again, sorry):

`RedisResult` has explicit conversion operators to `RedisResult[]`, `RedisValue[]`, `int[]`, `long[]`, `byte[][]`, `double[]`, etc. So...  *just cast*:

    var arr = (int[])data;
