### ISSUE TITLE
DLL not strong signature

### ISSUE THREAD

**Issue by Wlitsoft** [StackExchange/StackExchange.Redis#545]
DLL not strong signature，After strong signature class library can not use StackExchange.Redis.
If possible Please correct.

Thanks

**Comment by NickCraver** [comment]
In 2.0 we'll strongly sign the main library and do away with the variant. But for 1.x, you can find a strongly named package here: https://www.nuget.org/packages/StackExchange.Redis.StrongName/

**Comment by mgravell** [comment]
For reference, the issue here is that changing between strong named / not fundamentally changes the formal identity of the library  so is a very very breaking change. Hence something we plan to roll into a 2.0
