### ISSUE TITLE
Read from Slave

### ISSUE THREAD

**Issue by derix** [StackExchange/StackExchange.Redis#547]
Hi 

We are working with Master and two slaves.
When system load I want the user to read data from the slaves and not from the master.
But I see that StackExchange driver always send the read commands to the master node.

Is there a way to manipulate or change the behaviour?

Best regards,

Oren

**Comment by NickCraver** [comment]
On most commands there is a `CommandFlags` optional parameter, you can pass `CommandFlags.PreferSlave` there :)

**Comment by wdqzdd** [comment]
when i use CommandFlags.PreferSlave ,can it achieve load balancing? @derix @NickCraver

**Comment by NickCraver** [comment]
@wdqzdd Yep, it will round-robin to the replicas :) Closing out to cleanup.
