### ISSUE TITLE
SortedSetRangeByValue min/max formatting

### ISSUE THREAD

**Issue by m-nagy** [StackExchange/StackExchange.Redis#548]
I am trying to execute the command `ZRANGEBYLEX mykey "[\xd9\x8a" "[\xd9\x8a\xff"` using `SortedSetRangeByValue("mykey",  min, min + @"\xff")`

But the redis output is `ZRANGEBYLEX mykey "[\xd9\x8a" "[\xd9\x8a\\xff" `, the extra backslash leads to incorrect search behavior.

**Comment by NickCraver** [comment]
Can you please provide the code here? I'm a little unsure where that's coming from.
