### ISSUE TITLE
Time out on Exists

### ISSUE THREAD

**Issue by nripendra** [StackExchange/StackExchange.Redis#550]
Getting following exception, in dotnet core application (asp.net mvc):

```
System.TimeoutException: Timeout performing EXISTS SFV2_AS_DO, 
inst: 5, 
queue: 16, 
qu: 0, 
qs: 16, 
qc: 0, 
wr: 0, 
wq: 0, 
in: 289, 
ar: 0, 
clientName: ...
```
I have tried increasing syncTimeout value to 5000(ms) seems to solve a bit, still gives a lot of timeout. What information can I gather from above exception message? And what configuration tweaks can I try?

**update**

Some more messages:

```
System.TimeoutException: Timeout performing EXISTS SFV2_AS_DO, 
inst: 6, 
queue: 17, 
qu: 0, 
qs: 17, 
qc: 0, 
wr: 0, 
wq: 0, 
in: 279, 
ar: 0, 
clientName: ... 
```
```
System.TimeoutException: Timeout performing EXISTS SFV2_AS_DO, 
inst: 6, 
queue: 16, 
qu: 0, 
qs: 16, 
qc: 0, 
wr: 0, 
wq: 0, 
in: 27, 
ar: 0, 
clientName: ...
```
```
System.TimeoutException: Timeout performing EXISTS SFV2_AS_DO, 
inst: 3, 
queue: 37, 
qu: 0, 
qs: 37,
qc: 0, 
wr: 0, 
wq: 0, 
in: 76, 
ar: 0, 
clientName: ...
```
**update2**
- Redis Client machine is a AWS virtual machine with 2 virtual processors, 64bit and 3.75 mb memory.
- Redis Server is AWS ElasticCache.

**Comment by mgravell** [comment]
hmm - no active reader, which is a problem. what library version is this?

**Comment by nripendra** [comment]
@mgravell 
It is `1.1.608` installed from nuget.

**Comment by nripendra** [comment]
@mgravell 
I'm using following code to create connection:

```cs
    public static class RedisHelper
    {
        public static string ConnectionString { get; set; }

        private static readonly Lazy<IConnectionMultiplexer> LazyConnection = new Lazy<IConnectionMultiplexer>(() => ConnectionMultiplexer.Connect(ConnectionString));

        public static IConnectionMultiplexer Connect()
        {
            return LazyConnection.Value;
        }
    }
```
This gives me the `IConnectionMultiplexer` which I'm using as follows, in class constuctor:
```cs
    public Cache(IConnectionMultiplexer redis, string nameSpace)
    {
        _redis = redis;
        _nameSpace = nameSpace;
        _db = _redis.GetDatabase();
    }
```
Then `_db` is used to check if Key exists, something like this:

```cs
    public bool ContainsKey(string key)
    {
       return _db.KeyExists(key);
    }
```

**Comment by NickCraver** [comment]
Closing this out to consolidate on issues with the current lib - this specific one (AWS cache) was drastically improved in 1.2.1+.
