### ISSUE TITLE
Timeout performing SETEX

### ISSUE THREAD

**Issue by francofs** [StackExchange/StackExchange.Redis#555]
Hi, I'm having a hard time to get around a situation, which I suspect I already know the cause.

Here is the scenario:

1 - The cache is for session and authorization management. A randomized token is used as the key, which is sent back to the client for keeping it's session alive.

2 - At every request from the server I fetch the contents using the token sent by the client, verify its access rights that are the value, then I save the contents again with the same key, back to Redis, so I can extend it's expiration (a sort of key with sliding expiration).

The problem is that sometimes there are concurrent requests that try to write to the same key. This happens because the SPA page renders several section asynchronously and the session renewal happens at every request, so assuming SETEX performs an exclusive lock on the key while writing it, I believe it's the cause of this error:

Timeout performing SETEX 3kfiIGdA1EhvHPScrWX4+7llsblH, inst: 10, mgr: Inactive, err: never, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 148, ar: 0, IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=5,Free=4090,Min=4,Max=4095), clientName: -

I am using StackExchange.Redis.IDatabase with .net and I couldn't find a method that would issue a SET instead of SETEX, if that's really the case.

I would really appreciate your help and suggestion with this scenario.

I used FireAndForget Command flag for now, but I am not sure this is the best solution.

Thanks and great job on this.

**Comment by deepakverma** [comment]
in: 148 means there are 148 bytes available to be read on the client, I have seen this when the client is not able to read fast enough, in this case most likely to worker thread growth. I would recommend looking at this document: https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Timeouts.md

**Comment by francofs** [comment]
Hi sorry for the delay. I think I may have not been clear. This is a write operation, not read.

Again I believe it's because of concurrent write operation, utilizing the SETEX on the same key. For now I resolved it with FireAndForget command flag, however I believe a more appropriate solution would be a SET operation. But I don't see how to call it via the REDIS API for .net 45.

I tried many things but always end up with a SETEX instead of SET, which I believe would solve the problem.

**Comment by NickCraver** [comment]
Reading through the above, yes the synchronous double write on the same key brings all the network and server latency into play. If you don't *need* to wait: don't...it interrupts the pipeline (evaluated timeouts) when not needed really.

In general, to call `SET` instead of `SETEX`, you'll want: `db.StringSet("key", "value")`. Then `When` optional parameter defaults to `When.Always`, which calls `SET` underneath when no expiration is present.
