### ISSUE TITLE
InvalidOperationException when profiling ScriptEvaluate

### ISSUE THREAD

**Issue by zaltar** [StackExchange/StackExchange.Redis#557]
When profiling ScriptEvaluate, StringGetWithExpiry, or CreateTransaction a InvalidOperationException is thrown.  This happens in the latest 1.2.0 version from Nuget and previous versions. This is the stack trace from the InternalError handler:
```
Operation is not valid due to the current state of the object.
   at StackExchange.Redis.ProfileStorage.SetRequestSent()
   at StackExchange.Redis.Message.SetRequestSent()
   at StackExchange.Redis.PhysicalBridge.WriteMessageDirect(PhysicalConnection tmp, Message next)
   at StackExchange.Redis.PhysicalBridge.WriteQueue(Int32 maxWork)
```

It seems like there is a duplicate call to `SetRequestSent` at `StackExchange.Redis.PhysicalBridge.WriteMessageDirect(PhysicalConnection tmp, Message next) in PhysicalBridge.cs:line 541`. From what I can tell, all three current `IMultiMessage` implementations, `ScriptEvalMessage`, `StringGetWithExpiryMessage`, and `TransactionMessage`, end up returning themselves, `yield return this;`, in `IEnumerable<Message> GetMessages(PhysicalConnection connection)`.  This causes `WriteMessageToServer` to call `SetRequestSent` on the message making the call at `PhysicalBridge.cs:line 541` redundant.

Here is an example program to reproduce the exception:
```C#
using StackExchange.Redis;
using System;

namespace ConsoleApp
{
	public class MyProfiler : IProfiler
	{
		object context = new object();
		public object GetContext()
		{
			return context;
		}
	}
	class Program
	{
		static void Main(string[] args)
		{
			var redis = ConnectionMultiplexer.Connect("127.0.0.1");
			redis.InternalError += (o, e) => 
				Console.WriteLine(e.Exception.Message + Environment.NewLine + e.Exception.StackTrace);

			var profiler = new MyProfiler();
			redis.RegisterProfiler(profiler);
			redis.BeginProfiling(profiler.GetContext());

			var db = redis.GetDatabase();
			db.ScriptEvaluate("return 0");

			foreach (var p in redis.FinishProfiling(profiler.GetContext()))
					Console.WriteLine(p);

			Console.WriteLine("Done");
			Console.ReadLine();
		}
	}
}
```

**Comment by NickCraver** [comment]
Apologies for taking so long to respond. I tested this with the latest lib and can no longer reproduce, so I'm going to close this out as working. If it's not and you're still having issues, please ping here and I'll reopen and we'll dig into it.
