### ISSUE TITLE
slow results from ubuntu redis while things work fast from a windows machine - same code.

### ISSUE THREAD

**Issue by katmai** [StackExchange/StackExchange.Redis#560]
hey guys, so i have this client that's using StackExchange.Redis with C#.  he is using a windows redis server and i created an ubuntu redis server for him.

the problem is that when he's querying the windows redis, with the same code he's getting the results pretty much instantly while it takes 10-20 seconds to get the results from the linux box. both boxes have identical hardware and i have the linux box performance optimized.

here's a couple screenshots with the relevant code and the queries:

https://www.screencast.com/t/D2puFlh3j
https://www.screencast.com/t/5WxAcqCZGt

if anyone would give me a few ideas on how to get the things working properly, i would appreciate it.

thank you.

**Comment by NickCraver** [comment]
There's really no difference in the client as to which server type your connected to, so let's start with a sanity check: have you tried [Redis Benchmark](https://redis.io/topics/benchmarks) from the same client to both servers?
