### ISSUE TITLE
StackExchange.Redis.RedisServerException: Endpoint 127.0.0.1:7200 serving hashslot 12448 is not reachable at this point of time. Please check connectTimeout value. If it is low, try increasing it to give the ConnectionMultiplexer a chance to recover from the network disconnect.  IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=9,Free=32758,Min=4,Max=32767), Local-CPU: 0%

### ISSUE THREAD

**Issue by yswenli** [StackExchange/StackExchange.Redis#567]
![image](https://cloud.githubusercontent.com/assets/6139455/22616870/c498cae0-eaf1-11e6-9d69-ba2298575d18.png)

![image](https://cloud.githubusercontent.com/assets/6139455/22616697/0192dde6-eaed-11e6-9ca9-0ba347bca24c.png)

Execute hexist command in cluster appear this error.

I set the connection time for 30 seconds,and this problem will still appear

StackExchange.Redis.dll v1.2.0

and i set the connection time for 180 seconds,and this problem will still appear

ERROR 2017-02-04 15:41:12,686 [logerror] |No IP Adress|main:|Params: |ErrDesc: Endpoint 10.205.204.174:7200 serving hashslot 12448 is not reachable at this point of time. Please check connectTimeout value. If it is low, try increasing it to give the ConnectionMultiplexer a chance to recover from the network disconnect.  IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=7,Free=32760,Min=4,Max=32767), Local-CPU: 0%   在 StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 StackExchange.Redis.RedisDatabase.HashExists(RedisKey key, RedisValue hashField, CommandFlags flags)
   在 MessageProxyTest.StackExchangeTest.ChannelMappingOperationTest.IsInChannel(String channelID, String imUserID)
   在 MessageProxyTest.Program.<>c.<Main>b__0_0(Int32 i)
StackExchange.Redis.RedisServerException: Endpoint 10.205.204.174:7200 serving hashslot 12448 is not reachable at this point of time. Please check connectTimeout value. If it is low, try increasing it to give the ConnectionMultiplexer a chance to recover from the network disconnect.  IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=7,Free=32760,Min=4,Max=32767), Local-CPU: 0%
   在 StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 StackExchange.Redis.RedisDatabase.HashExists(RedisKey key, RedisValue hashField, CommandFlags flags)
   在 MessageProxyTest.StackExchangeTest.ChannelMappingOperationTest.IsInChannel(String channelID, String imUserID)
   在 MessageProxyTest.Program.<>c.<Main>b__0_0(Int32 i)

ERROR 2017-02-04 15:41:12,701 [logerror] |No IP Adress|main:|Params: |ErrDesc: SocketClosed on HEXISTS   在 StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 StackExchange.Redis.RedisDatabase.HashExists(RedisKey key, RedisValue hashField, CommandFlags flags)
   在 MessageProxyTest.StackExchangeTest.ChannelMappingOperationTest.IsInChannel(String channelID, String imUserID)
   在 MessageProxyTest.Program.<>c.<Main>b__0_0(Int32 i)
StackExchange.Redis.RedisConnectionException: SocketClosed on HEXISTS
   在 StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 StackExchange.Redis.RedisDatabase.HashExists(RedisKey key, RedisValue hashField, CommandFlags flags)
   在 MessageProxyTest.StackExchangeTest.ChannelMappingOperationTest.IsInChannel(String channelID, String imUserID)
   在 MessageProxyTest.Program.<>c.<Main>b__0_0(Int32 i)

**Comment by billsquall** [comment]
show me your connectTimeout

**Comment by yswenli** [comment]
This is a redis cluster environment configuration problem that has been resolved

**Comment by dpenton** [comment]
Hi @yswenli I am curious what your cluster environment configuration issue was?

**Comment by ArvinHsieh** [comment]
Hi @yswenli 
I hava same problem of redis cluster.
Can you let me know how to fix this? 
Thanks.

**Comment by yswenli** [comment]
This is the node configuration problem, the specific reasons unknown; I was a re configured a cluster to solve this problem

**Comment by foreverhot1019** [comment]
config set no-appendfsync-on-rewrite no

i change the configration of no-appendfsync-on-rewrite  to solve this problem

**Comment by Mirzakan** [comment]
foreverhot1019 where do you need to set **no-appendfsync-on-rewrite** to no? 
i having similar problem - some keys get trough and some not.

**Comment by zeerehmat** [comment]
@Mirzakan can you please share workaround if you have sorted the issue, i am facing the same issue.
