### ISSUE TITLE
Windows 10 universal apps (edit: and remove IL Emit)

### ISSUE THREAD

**Issue by tsimbidis** [StackExchange/StackExchange.Redis#568]
Do you plan support for windows 10 uap ?

**Comment by NickCraver** [comment]
We simply don't build Windows 10 apps, so it's hard to intelligently answer the question. What doesn't work today?

**Comment by tsimbidis** [comment]
I'm developing a windows 10 app and I cannot find a redis client which is compatible. Any attempt for nuget install-package ==>
"Install-Package : Package StackExchange.Redis 1.2.0 is not compatible with uap10.0 (UAP,Version=v10.0). Package StackExchange.Redis 1.2.0 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - net46 (.NETFramework,Version=v4.6)
  - netstandard1.5 (.NETStandard,Version=v1.5)"

At this moment, the only way to work with windows 10 app & redis, is to expose to build a webapi ( .net 4.6) which has access to redis through stackexchange.redis  and use httpclient from windows 10 app. But this is a little stupid...

**Comment by NickCraver** [comment]
@tsimbidis I'll take a look at a UAP 10 build after we port the project system over (I want to do this after merging some PRs) and see what the gap is. I honestly don't have a clue what the gap from current to supporting UAP would be. It might be easy, it might be insanely difficult. Let me fire up a build and see where we stand after a port.

**Comment by NickCraver** [comment]
Going forward, the plan is to suppose `netstandard` which will in tern supports UWP platforms. Now that UWP supports `netstandard2.0` and `StackExchange.Redis` ships `netstandard2.0`, calling this done :)

**Comment by tsimbidis** [comment]
Perfect!! I have Redis at Windows 10 native apps!!
Thanks!!

**Comment by mgravell** [comment]
Note: I need to take a quick look at our IL Emit usage - literally about 5 lines in one place. I think we can probably nuke it. I'm going to reopen specifically to track that last piece.

**Comment by mgravell** [comment]
I was wrong; it is actually 2 places; one is the "can we complete tasks cheaply" code, which is removed in the (possibly nasty) https://github.com/StackExchange/StackExchange.Redis/pull/877

the other is scripting with parameter replacements; two options there:

1. tell UWP to use `ScriptEvaluate` rather than the helper
2. rewrite the parameter extraction using `Expression` trees

**Comment by mgravell** [comment]
I have implemented "2", and will test in a UWP package later.

**Comment by mgravell** [comment]
This is now verified in 2.0 (using basic ops) against FCU (16299) as the minimum version (required for netstandard 2.0).
