### ISSUE TITLE
ConnectionMultiplexer.Connect("localhost:6379") throws 'System.AggregateException' in System.Private.CoreLib.ni.dll occurred

### ISSUE THREAD

**Issue by uday31in** [StackExchange/StackExchange.Redis#569]
ConnectionMultiplexer.Connect("localhost:6379");

An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.ni.dll occurred

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.0"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.0" />
    <PackageReference Include="NETStandard.Library" Version="1.6.1" />
    <PackageReference Include="StackExchange.Redis" Version="1.2.0" />
  </ItemGroup>

```

Server is listening on localhost:

uday@DESKTOP:/mnt/c/Windows/System32$ redis-cli -h localhost
localhost:6379> keys *
1) "test"
localhost:6379>

**Comment by NickCraver** [comment]
This looks to bet a .NET Core 1.x app, which didn't properly support connecting to `localhost` (a DNS name). This has been resolved in .NET Core 2.0. If you *must* use `netstandard1.x` (please, please upgrade!), you'll need to connect via IP: `ConnectionMultiplexer.Connect("127.0.0.1:6379");`
