### ISSUE TITLE
KeyExpire when using Redis Cluster / CLUSTER FAILOVER

### ISSUE THREAD

**Issue by peter-myklebust** [StackExchange/StackExchange.Redis#57]
Hi, great package!

I am trying to use Redis 3.0 (on Linux)  in a cluster configuration, same setup (6 nodes) as you use in the Cluster.cs tests. The underlying requirement is to get one of the ASP.NET session providers working with a cluster configuration. They typically use "KeyExpire()" in some fashion. However, if I execute a "CLUSTER FAILOVER" command on one of the slaves, KeyExpire() (and maybe other methods) falls apart. Here is a test I added to "cluster.cs":

        [Test]
        public void KeyExpireWithClusterFailover()
        {
            using (var conn = Create())
            {
                var db = conn.GetDatabase();
                RedisKey key = "abcabc";
                db.StringSet(key, "myvalue");
                for (var i = 0; i < 1000; i++)
                {
                    db.KeyExpire(key, TimeSpan.FromHours(1));
                    Thread.Sleep(5000);
                }
            }
            Assert.IsTrue(true);
        }

While this code is running, execute a "CLUSTER FAILOVER" from port 7004. After a little while, the code fails with a 

`StackExchange.Redis.RedisServerException : MOVED 6207 <ip-address>:7004`

Sniffing around with the debugger, the code doesn't seem to pick up the new master/slave configuration after the failover.

Any help would be much appreciated! If this is resolved, we would have the perfect scale out / failover solution for ASP.NET session state.

Regards, Peter Myklebust

**Comment by debbiswal** [comment]
Hi @peter-myklebust  ,
Finally I got my program working. Thanks to @hrishi18pathak .
I have downloaded the code from https://github.com/hrishi18pathak/StackExchange.Redis/tree/SEClusteringBugFix branch with changes from 17-July-2015. The main changes are  in ConnectionMultiplexer and ConfigurartionOptions class.

********************************************************************************************
ConnectionMultiplexer.cs (modified UpdateClusterRange() method,added IsNodeCompatibleWithConfiguration() method) :
---------------------------------------------------------------------------------
 internal void UpdateClusterRange(ClusterConfiguration configuration)
        {
            if (configuration == null) return;
            foreach (var node in configuration.Nodes)
            {
                // do not update cluster range if the node configuration is incompatible with the multiplexer 
                // endpoints configuration. If a user has specified endpoints in the multiplexer configuration using
                // Dns endpoints, Stackexchange.redis returns the ConnectionMultiplexer object successfully 
                // after connecting to all the nodes in the connection string (using their host names). 
                // Also, before returning the multiplexer object it updates the mapping of nodes to their clusterslots 
                // and this mapping is of the format “DNS hostname:port” : “clusterSlotNumber”.
                // However at the same time, the client also issues “CLUSTER NODES” command to each of the nodes in the above list 
                // (to determine master and slave configuration) and re-updates the cluster mapping with the output of the clusternodes command 
                // which now is going to contain IP addresses (redis-server itself does not understand host names). 
                // So the cluster mapping is now updated to the format: “IP Address” : “clusterSlotNumber”
                // If the StackExchange.Redis has not been able to connect to all the nodes using their IP addresses by the time the first command (GET,SET) 
                // is issued to the cluster, it results in failure to connect to that particular node resulting in the “MOVED ERROR” 
                // (since it tries to hit a random node in the list subsequently)
                if (node.IsSlave || node.Slots.Count == 0 || !IsNodeCompatibleWithConfiguration(node)) continue;
                foreach (var slot in node.Slots)
                {
                    var server = GetServerEndPoint(node.EndPoint);
                    if (server != null) serverSelectionStrategy.UpdateClusterRange(slot.From, slot.To, server);
                }
            }
        }

 /// <summary>
        /// Checks if the specified node has the same format as that of
        /// the endpoints specified in the multiplexer configuration i.e.
        /// if all nodes are dns endpoints then the specified node has to be a dns endpoint
        /// to be compatible.
        /// </summary>
        /// <param name="node"></param>
        /// <returns>True if node is compatible with multiplexer configuration</returns>
        private bool IsNodeCompatibleWithConfiguration(ClusterNode node)
        {
            return (this.configuration.HasAllDnsEndPoints() && (node.EndPoint is DnsEndPoint)) ||
                (!this.configuration.HasDnsEndPoints() && !(node.EndPoint is DnsEndPoint));
        }
******************************************************************************************
ConfigurationOptions.cs(added method HasAllDnsEndPoints())
-----------------------------------------------------------------------------------
 internal bool HasAllDnsEndPoints()
        {
            return !endpoints.Any(ep => !(ep is DnsEndPoint));
        }

Still I need to verify for any implications with this fix.

**Comment by NickCraver** [comment]
This should be resolved by #312, but merging with #248 for tracking on cluster connections and `MOVED`.
