### ISSUE TITLE
RedisConnectionException timeout

### ISSUE THREAD

**Issue by hamish-tushar** [StackExchange/StackExchange.Redis#570]
HI,
I have an application using redis on top of SqlServer. We  had an issue recently wherein the connection to redis were a little flaky for few seconds. 

Error Messages:

It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. Timeout
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: SETEX 

The application recovered from this but I think I just want to dig deep and try to understand some connection options in particularly SyncTimeout. We are using the default timeout value for this which is 1 sec.

Should this be tampered with in case the redis servers had a temporary network issue and came back on ? What is the recommended values for this and how can the increase affect the overall performance.

**Comment by NickCraver** [comment]
What is your environment like? If it's not very close/local on-prem, you likely want over 1 second, yep. The default these days is 5 seconds, due to so much cloud usage of the lib.

**Comment by mgravell** [comment]
Closing; please see: https://github.com/StackExchange/StackExchange.Redis/issues/871
