### ISSUE TITLE
System.TimeoutException after over 1M seconds when executing ExecuteSyncImpl

### ISSUE THREAD

**Issue by jochenvw** [StackExchange/StackExchange.Redis#573]
I'm using the Redis cache session state provider in my ASP.NET app ( .NET 4.5.1 ) with a very basic config:

```
<sessionState timeout="60" mode="Custom" customProvider="ReddisCache">
  <providers>
    <add name="ReddisCache" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="**" accessKey="**" 
     ssl="true" port="6380" retryTimeoutInMilliseconds="5000" />
  </providers>
</sessionState>
```
The application has not been touched for months, but last week we had an outage because of a continuous CPU load of 100% . We observed that the Redis thread count was > 350 whereas this normally is normally less than 50. So scaling everything up resolved the issue, but we're trying to figure out *why* the required thread count is so much higher than normal.

So checking out Application Insights - I noticed the following:

![image](https://cloud.githubusercontent.com/assets/17111555/23069373/7cddc5da-f527-11e6-9406-d7266221cec6.png)

The TimeOutExceptions seems to occur from `ExecuteSyncImpl`. That may be because we overloaded Redis, but the duration for the request was over 1 M seconds ( according to AI ). Any idea what can cause this?

**Comment by NickCraver** [comment]
There were similar performance regressions around the cache provider/library version combo, but all resolved in 1.2.5 it seems. Going to close this out to cleanup but please do ping if you're still seeing this in 1.2.6 or later.
