### ISSUE TITLE
Missing release?

### ISSUE THREAD

**Issue by vladsaftoiu** [StackExchange/StackExchange.Redis#577]
Noob question: are we missing the latest release (1.2.1)? 

On [nuget](https://www.nuget.org/packages/StackExchange.Redis/1.2.1) I see the package for 1.2.1 but there is no such version in the release tab (last is 1.2.0).

Thanks, 
Vlad

**Comment by freerider7777** [comment]
Yep, just wanted to write the same...

**Comment by mgravell** [comment]
That has been fixed; I've also tried to start improving our tracking here: http://stackexchange.github.io/StackExchange.Redis/ReleaseNotes
