### ISSUE TITLE
[question] Server side master change notification

### ISSUE THREAD

**Issue by yhan** [StackExchange/StackExchange.Redis#581]
According to the reply of Marc Gravell, redis cluster does not broadcast master change:
http://stackoverflow.com/questions/29247616/how-does-stackexchange-redis-use-multiple-endpoints-and-connections

my server side version:3.2.3

in the latest release of redis, according to their release notes, it is still not managed
https://raw.githubusercontent.com/antirez/redis/3.2/00-RELEASENOTES

do you confirm?

**Comment by NickCraver** [comment]
This is correct, Redis still doesn't to this, though Sentinel (what many use as an external witness) will. See #692 for tracking that addition.
