### ISSUE TITLE
HashSetAsync code comments

### ISSUE THREAD

**Issue by jackbond** [StackExchange/StackExchange.Redis#583]
Please update the code comments for HashSetAsync to indicate that the return value indicates whether an existing value was overwritten.

For other methods like LockTakeAsync, the return value indicates success / failure, so it's easy to assume that is true for other methods.

**Comment by NickCraver** [comment]
The current comments reflect this, thanks!

**Comment by jackbond** [comment]
Ah, if you examine the metadata it does. The tooltip that pops up in Visual Studio only displays the summary. Sorry for the confusion.
