### ISSUE TITLE
Increment multiple keys in a single request

### ISSUE THREAD

**Issue by ttchongtc** [StackExchange/StackExchange.Redis#585]
I have a redis cache that store very basic key/pair value: kvp<string, int>. Every few milliseconds, I want to increment the value of multiple keys in 1 request. What is the best way to do that? I only see the options to perform on multiple keys for get and set but no increment.

**Comment by manigandham** [comment]
There is no native command in Redis to increment multiple keys in one operation. What is your scenario in doing this? You can just send multiple increment operations. If you need a transaction to process all the increments together than you can use the `MULTI` option to send them as a batch. 

https://redis.io/commands/multi

**Comment by NickCraver** [comment]
Closing this out for lack of information. If more questions remain, please comment here and we'll help out.

**Comment by jaydip-lnxct** [comment]
i want to increament with multiple value using numincrby

**Comment by mgravell** [comment]
@jaydip-lnxct assuming you mean `JSON.NUMINCRBY`, then note that NRedisStack adds these module-specific extensions.
