### ISSUE TITLE
How to lock a specified Key to prevent concurrency problem for multiple apps/clients

### ISSUE THREAD

**Issue by Xiaohongt** [StackExchange/StackExchange.Redis#59]
I’m trying to find how to use StackExchange.Redis to lock a specified Key to prevent concurrency problem for multiple apps/clients
e.g. what I need to do:
1. Get value for the a specified Key
2. Set increased value back to Redis

**Comment by NickCraver** [comment]
Answered by Marc above - closing this out due to inactivity.

**Comment by gdoron** [comment]
Might be worth mentioning that `INC` might be enough, depends on what you need.
(Since redis is single threaded)

Yeah I know it's old issue, but for future readers.
