### ISSUE TITLE
OnTopicMessage should be async

### ISSUE THREAD

**Issue by niemyjski** [StackExchange/StackExchange.Redis#590]
I've been wanting to log this for some time, recently I started seeing a ton of threads dead lock in OnTopicMessage handlers. I need to do async work in this handlers and I think this is part of the issue. It appears that the client isn't 100% async and how these handlers are being called (passed an argument of isAsync in some cases). Are there plans to drop sync support and be 100% async and have OnTopicMessage event handler return a Task...

**Comment by NickCraver** [comment]
Can you please point to the code you're seeing? `OnTopicMessage` isn't something in our codebase, so I'm a bit confused here.

**Comment by niemyjski** [comment]
Sorry, I should have been more clear (SubscribeAsync) the handler is sync but the usages call it with a parameter isAsync.. But it's very common for these message handlers to do async things...

**Comment by NickCraver** [comment]
Agree we want to visit this - consolidating into #639 where a bit more discussion is happening.
