### ISSUE TITLE
Why not provide us a event to catch all command exception?

### ISSUE THREAD

**Issue by coldicelion** [StackExchange/StackExchange.Redis#591]
hi, i have a problem with catch exception, if i use command like (StringGet、StringSet、HashGet、HashGetAll) in multiple thread,  StackExchange.Redis will throw a RedisConnectionException  when a server shutdown, i try to catch the exception in ConnectionFaild event to switch another redis server. but the exception still throw up. is there any idea to catch all command exception? thank a lot!

**Comment by NickCraver** [comment]
If the use case here is to switch to another server, I'm wondering what your setup is, are you not connecting to multiple servers with the same multiplexer already?
