### ISSUE TITLE
Bcl issue with VS2017's .NET Core build system

### ISSUE THREAD

**Issue by MichaCo** [StackExchange/StackExchange.Redis#595]
Hi @NickCraver,
I just ran into a strange issue migrating some projects which reference the StackExchange.Redis client and trarget .net40.
Installing the nuget works fine, building doesn't work because it seems to not finding the System.Threading.Tasks stuff

	1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3268: The primary reference "C:\Users\User\.nuget\packages\stackexchange.redis\1.2.1\lib\net40\StackExchange.Redis.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "C:\Users\User\.nuget\packages\stackexchange.redis\1.2.1\lib\net40\StackExchange.Redis.dll" or retarget your application to a framework version which contains "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
	1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3268: The primary reference "C:\Users\User\.nuget\packages\microsoft.bcl.async\1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "C:\Users\User\.nuget\packages\microsoft.bcl.async\1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.dll" or retarget your application to a framework version which contains "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
	1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3268: The primary reference "C:\Users\User\.nuget\packages\microsoft.bcl.async\1.0.168\lib\net40\Microsoft.Threading.Tasks.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "C:\Users\User\.nuget\packages\microsoft.bcl.async\1.0.168\lib\net40\Microsoft.Threading.Tasks.dll" or retarget your application to a framework version which contains "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
	1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3268: The primary reference "C:\Users\User\.nuget\packages\stackexchange.redis\1.2.1\lib\net40\StackExchange.Redis.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "C:\Users\User\.nuget\packages\stackexchange.redis\1.2.1\lib\net40\StackExchange.Redis.dll" or retarget your application to a framework version which contains "System.Runtime, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
	1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3268: The primary reference "C:\Users\User\.nuget\packages\microsoft.bcl.async\1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "C:\Users\User\.nuget\packages\microsoft.bcl.async\1.0.168\lib\net40\Microsoft.Threading.Tasks.Extensions.dll" or retarget your application to a framework version which contains "System.Runtime, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
	1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3268: The primary reference "C:\Users\User\.nuget\packages\microsoft.bcl.async\1.0.168\lib\net40\Microsoft.Threading.Tasks.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "C:\Users\User\.nuget\packages\microsoft.bcl.async\1.0.168\lib\net40\Microsoft.Threading.Tasks.dll" or retarget your application to a framework version which contains "System.Runtime, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
	1>Program.cs(2,7,2,20): error CS0246: The type or namespace name 'StackExchange' could not be found (are you missing a using directive or an assembly reference?)
	1>Done building project "ConsoleApp1.csproj" -- FAILED.

I'm just wondering if you already ran into that and maybe have a workaround or if I have to put an issue on the dotnet/cli repo.

To reproduce it:
* open VS 2017
* create a new .NET Core console application
* edit the project file
* change `<targetFramework>` to `net40`
* install StackExchange.Redis
* put some code... `var multi = ConnectionMultiplexer.Connect("localhost");`
* try to build

(I know you will drop .net40 support soon, I'm just trying to get my libs (which still support .net40, too) building in VS2017)

/update there is also an issue on the dotnet-cli repo: https://github.com/dotnet/cli/issues/5993

**Comment by jarenduan** [comment]
I have some of the same errors when I try to reference microsoft.bcl.async in a multi-target class library(target net40 and netstandard14).

**Comment by mgravell** [comment]
I've had some discussion with folks, and basically Bcl.Async is pretty screwed for use with dotnet build, and it isn't on the roadmap to fix it. To not delay the *ongoing* package while we keep fiddling, I have dropped net40 from the build targets in 1.2.2, but this is hopefully just while we find a workaround. I do not, however, know how big of a problem net40 is - every time I try to ask, the response is essentially (and I mean people in general, not specifically Microsoft) "wow, drop that stuff like a hot potato, net40 is horribly broken and unsupported and insecure and think of the puppies".

So that I can try to think of the routes forward: what are your reasons for using net40? I was kinda hoping that the new build tools would *reduce* work, not add work :(

**Comment by MichaCo** [comment]
@mgravell  Hey Marc,
I'm in the same situation as you are. I'm not using .net40 myself, the [CacheManager library](https://github.com/MichaCo/CacheManager) supports .net40. 

For Redis, I dropped support for .net40 (until fixable), in the latest version already a few months ago. Same reasons as you mention, so, I'm fine with your approach ;) 

And totally agree, the "upgrade" to the new project system wasn't really friendly..

**Comment by jarenduan** [comment]
Maybe [this](https://github.com/dotnet/corefx/issues/17026) would help?

**Comment by jarenduan** [comment]
Hi @mgravell, net40 supports WinXP, which is the last version of .Net Framework that does that. So if your class library don't want to lose user who using XP, you have to support net40 (or even lower). Maybe this is a reason for many library developers.

**Comment by NickCraver** [comment]
We have decided to drop `net40` in future builds (it's actually been unavailable in our builds for some time), so closing this out to cleanup.
