### ISSUE TITLE
MGET calls getting slower and slower under load

### ISSUE THREAD

**Issue by cleverguy25** [StackExchange/StackExchange.Redis#599]
Also posted to stackexchange - http://stackoverflow.com/questions/42847046/mget-calls-getting-slower-and-slower-under-load-using-stackexchange-redis

I have a ASP.Net Core Web API running in a linux container in AWS ECS. This API gets data out of Redis mostly, but will fallback to a database if it is not there (we have engineered where 99.99% of our data is in the Redis cache). I have a reasonably high load coming in at about 1-2K RPS (sure maybe medium to small to some of you ;-).
This API looks up several keys via MGET (anywhere from 20-60) for each request. Everything is async all the way, no sync code or Waits or other deadlock prone code. Things just get slower and slower the more the RPS goes up. I also tried PreserveAsyncOrder = false, but that seemed to be worse.
I do not think my Redis server (which is in Elasticache) is the issue, metrics show barely 1% CPU utilization. Also the more instances of my container I create, the more latency goes down, something I wouldn't expect to see if the server is the bottleneck.
I heard there was a potential thread hijacking issue with TPL and SE.Redis (not sure if it is fixed or not, or applicable to .Net Core), so I tried moving everything to sync instead of async (although my web api calls are still async, but my calls to SE.Redis are sync). This resulted in actual timeouts rather then just taking awhile:
Timeout performing MGET, inst: 5, queue: 199, qu: 0, qs: 199, qc: 0, wr: 0, wq: 0, in: 150304, ar: 0, clientName: , serverEndpoint: *.*.*.*6379, keyHashSlot: -2 
Being as this is .Net Core the timeout exception seems to give less info than full stack, I do not see the number of worker threads or IOCP threads to see if there is a bottleneck there.
As more and more timeouts occur, the queue/qs: number goes up as well as the in: number.
The in number leads me to believe I am getting a response just not processing it fast enough, could I be falling prey to the thread hijacking issue? Or maybe my client is network bound?
I also have tried creating a connection pool for redis connections, as indicated on the SE.Redis timeouts page. Very small improvement, but still facing the same issue.
Any help would be appreciated.

**Comment by manigandham** [comment]
Answer posted on stackoverflow. You're sending 60 GETs per request with 2k requests per second which is likely maxing out your Redis instance with 120k ops/second.

**Comment by niemyjski** [comment]
@manigandham where does it say the max redistribution opts is 120k ops/sec that's pretty low when people are doing much higher throughput.

**Comment by manigandham** [comment]
I'm sure they are since it's very CPU/RAM dependant but it seems like a probable issue (along with network saturation) unless there's a stress test to show that's not the limit.

**Comment by NickCraver** [comment]
There is! Meet redis-benchmark: https://redis.io/topics/benchmarks

**Comment by manigandham** [comment]
Yes. I meant test results from the submitter for their AWS Elasticache setup to make sure that's not the limit. Anyway will wait and see what they say.

**Comment by cleverguy25** [comment]
I am sure this is not the issue.  1.  In the original issue above I mentioned that the Redis server seems to be barely breaking a sweat.  And in fact if I connect from a different machine everything is still fast.  2.  You can see that there is a local queue that is unprocessed.  That is not related to the server.  3.  I have written my own library since this doesn't seem to be addressed and that does not suffer from this issue.

**Comment by NickCraver** [comment]
@cleverguy25 Can you please let us know if you're still seeing this on the latest version of the library? 1.2.6 is stable. A lot of fixes went in there, and your very high inbound queue (150KB) points to the exact set of symptoms I'd expect to see in the 1.2.1 through 1.2.5 releases under high load conditions.

**Comment by mgravell** [comment]
Closing; please see #871

**Comment by MasiumDev** [comment]
> There is! Meet Redis-benchmark: https://redis.io/topics/benchmarks

I have same issue, Redis benchmark is 20,000 per second on the network and network go up to 1 Gbps, but in redisExchange, I see my stopWatch logs that in 20.000 requests some of the requests get time up to 4000 ms.
why? this is not CPU or network issue, it's related to redisExchange
