### ISSUE TITLE
ConnectionRestored event always raised two times after Redis restart

### ISSUE THREAD

**Issue by Xiaohongt** [StackExchange/StackExchange.Redis#60]
We use StackExchange.Redis in SignalR Redis scale-out, I found that ConnectionRestored event always raised two times after Redis restart.

Here is simple repro app:

```csharp
       private static ConnectionMultiplexer _connection;
        static void Main(string[] args)
        {
           string connectionString = "......";
            _connection = ConnectionMultiplexer.Connect(connectionString);

            _connection.ConnectionRestored += OnConnectionRestored;

            Console.ReadLine();
        }

        private static void OnConnectionRestored(object sender, ConnectionFailedEventArgs args)
        {
            Console.WriteLine("_connection.IsConnected is " + _connection.IsConnected);
        }
```

Repro steps:
 1). Update connectionString for your Redis, build the app and run
 2). Stop and Restart the Redis

Expected result:
OnConnectionRestored rasie one time, in output should just display one line "_connection.IsConnected is ..."

Actual result:
OnConnectionRestored rasie two times, in output displays two lines "_connection.IsConnected is  ..."

**Comment by NickCraver** [comment]
Yep, the above comment is correct. Closing this out due to answered and age.
