### ISSUE TITLE
Lost connection when application idle

### ISSUE THREAD

**Issue by garytsoi** [StackExchange/StackExchange.Redis#600]
We are using StackExchange.Redis v1.1.0.0 in our application with C#. We have find that  "System.ObjectDisposedException: Cannot access a disposed object." error occur when our application idle for a while.  it seem to been lost the Redis connect but it doesn't reconnect automatically. we have try to add the "keepAlive" parameter in the Connection string. But the issue a still happen sometime. 

We would like to know is there any solution to fix it? Did we need to update the StackExchange.Redis library to latest version? What is the new feature between v1.1.0.0 and latest version?

**Comment by NickCraver** [comment]
Yep, an upgrade to latest should fix this. I recall seeing 2 issues about this, both resolved since. Please try the latest 1.2.6 and let us know if you're still hitting issues (with a full error message + stack please!). If you're having trouble, I'll re-open this :)
