### ISSUE TITLE
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: EVAL; IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=4094,Min=4,Max=4095), Local-CPU: 0%

### ISSUE THREAD

**Issue by huazhesky** [StackExchange/StackExchange.Redis#602]
I got an exception when I use .NET connect to redis cluster. The exception message is: "StackExchange.Redis.RedisConnectionException:StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: EVAL; IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=4094,Min=4,Max=4095), Local-CPU: 0%"
but at the same time,I can user Redis Desktop Manager connet to redis cluster.

OS:Centos:  v7.2
Redis: v3.2.8
StackExchange.Redis: v1.2.1

Can anybody help me?Your help is appreciated.

**Comment by flowdopip** [comment]
I´m with the same problem.

**Comment by hacbq** [comment]
I´m with the same problem. And wait too long :(

**Comment by avshetty** [comment]
Im having the same issue, huazhesky were you able to solve this?

**Comment by mgravell** [comment]
It is highly possible this relates to a nasty configuration (build) error that was fixed in 1.2.5 (very recently) - that was cause the reader to become unreliable under high load. Please try 1.2.5 and see if it fixes it.

**Comment by NickCraver** [comment]
Going to close this out given no updates - see Marc's note above. The latest stable release is 1.2.6, though 1.2.5 onwards fixes a nasty networking bug here.
