### ISSUE TITLE
exception on aspnetcore linux docker

### ISSUE THREAD

**Issue by grahamehorner** [StackExchange/StackExchange.Redis#607]
https://github.com/aspnet/Caching/issues/292#issuecomment-290840973

**Comment by NickCraver** [comment]
Can you please provide your connection string? There are currently (until `netstandard2.0`) major differences in sockets and what's allowed on the *nix platforms.

**Comment by grahamehorner** [comment]
tried both localhost and internal ip 10.0.1.150

**Comment by NickCraver** [comment]
Looks like this was closed out on the other end - cleaning up here.
