### ISSUE TITLE
replicas in redis-cluster are not applying round-robin

### ISSUE THREAD

**Issue by mgravell** [StackExchange/StackExchange.Redis#610]
(discovery via an off-list email chain)

See `ServerSelectionStrategy.Select`; in the non-cluster scenario (aka `NoSlot`), we use the local `Any` method which does an `Interlocked.Increment` of the base offset to apply a crude round-robin.

However, in the redis-cluster scenario, for replicas, we use `FindSlave` which iterates the replica nodes for a given `ServerEndPoint` (the master endpoint for that slot). We *do not* apply any round-robin, with the consequence that in a multi-replica scenario, all "prefer slave" / "demand slave" requests go to the first replica (unless it is unavailable).

For balancing, we should add some kind of base-offset integer to the parent `ServerEndPoint`, and used in the same way that the global `anyStartOffset` currently works. We *could* also possibly just use `anyStartOffset`? it'll still rotate, which is all we really need...

**Comment by mgravell** [comment]
aside: no round-robin is required for the `FindMaster` scenario, as that is walking a replica chain upwards to find a master (usually: the same input element); it makes no sense to discuss round-robin on a master.

**Comment by CraigLager** [comment]
Is there an ETA for a fix on this?

**Comment by mgravell** [comment]
@CraigLager I have it on my desk right now; it is the single remaining thing I want to fix for 1.2.3.

**Comment by mgravell** [comment]
https://www.nuget.org/packages/StackExchange.Redis/1.2.3

**Comment by CraigLager** [comment]
thanks Marc, looks to be working 👍
