### ISSUE TITLE
Support for BITPOS in transaction conditions (CAS scenarios)

### ISSUE THREAD

**Issue by ltines** [StackExchange/StackExchange.Redis#612]
I am looking how to implement following scenario using StackExchange.Redis
```
WATCH key
BITPOS key 0 <-- save the offset
MULTI
BITFIELD key SET u1 <offset> 1
EXEC
UNWATCH key
```
The idea is to fail the transaction if somebody changed "key" bitfield after we checked it. 

The transaction conditions feature seems to be a good candidate. There are some issues:
* the ``BITPOS`` is not really a condition
* we need a way to propagate the returned value from the condition

**Comment by NickCraver** [comment]
@ltines I think the general approach (generically supporting this) is lua these days, is that an option for your use case?

**Comment by mgravell** [comment]
The key point of redis `MULTI`/`EXEC` is that you **cannot** access results (such as the `offset`) until **after** the `EXEC` - so the way you want to do it can't work. You *could* read the value once *before*, then do a transaction with a new `Condition` type that enforces it *during*, but that would end up being a double-read on the bitpos, which could be relatively expensive. Frankly, I think you should move this to Lua:

```
var pos = redis.call("bitpos", KEYS[1])
redis.call("bitfield", KEYS[1], "set", pos, 1)
```

(or something like that; untested)

then call that via `ScriptEvaluate`, passing `key` in the `keys` parameter (becomes `KEYS`), and an empty / null `args` (becomes `ARGV`).

I would strongly suggest that this is going to be your best option.
