### ISSUE TITLE
How can I get keys when use keys

### ISSUE THREAD

**Issue by mojinxun** [StackExchange/StackExchange.Redis#614]
1. Env:
    3 group(every group contain 1 master 1 slave)

2. Use:
    (1) Get a IServer
         ConnectionMuxer.GetEndPoints().Select(x => ConnectionMuxer.GetServer(x)).First(x => !x.IsSlave);
    (2) Server.Keys

I can't get the all keys from [Servers]

**Comment by mgravell** [comment]
what makes you think you are missing things?

**Comment by mojinxun** [comment]
you mean?

**Comment by mgravell** [comment]
I mean: you haven't told me what makes you think there is a problem.  Where are you stuck? What happens, vs what you expect to happen?

**Comment by mgravell** [comment]
Closing due to lack of reply
