### ISSUE TITLE
Timeout performing HSET

### ISSUE THREAD

**Issue by nbacheng** [StackExchange/StackExchange.Redis#615]
Timeout performing HSET car_point, inst: 1, mgr: ExecuteSelect, err: never, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: CARDGPS-DB-ALI, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=0,Free=1023,Min=8,Max=1023), Local-CPU: 33.05% (Please take a look at this article for some common client-side issues that can cause timeouts:

**Comment by flowdopip** [comment]
I´m having the same issue

**Comment by NickCraver** [comment]
Can you tell us more about your environment? What's your connection string look like? What's the client/server situation, distance, etc?
