### ISSUE TITLE
Fire and forget issue

### ISSUE THREAD

**Issue by oscarld** [StackExchange/StackExchange.Redis#616]
I am trying to set increment in a sorted list using `CommandFlags.FireAndForget`, when i run 10000 sets not all them are setted in redis.  

I am using this code:

```c#
for (int i = 0; i < 10000; i++)
{
	for (int i = 0; i < 24; i++)
	{
		string keyName = $"LR_moreviewed_{(i == 0 ? 23 : i - 1)}";
		db.SortedSetIncrement(keyName, value, 1, CommandFlags.FireAndForget);
	}
}
```
In the image, redis response.
![result](https://cloud.githubusercontent.com/assets/2354895/25286435/58e9729a-2683-11e7-9c9a-f0beea3b52bb.png)

Thanks for the help.

**Comment by oscarld** [comment]
This is a more accurated version of the code.
```javascript
Random r = new Random();
for (int i = 0; i < 10000; i++)
{
	value = r.Next(1, 10);
	for (int i = 0; i < 24; i++)
	{
		string keyName = $"moreviewed_{(i == 0 ? 23 : i - 1)}";
		db.SortedSetIncrement(keyName, value, 1, CommandFlags.FireAndForget);
	}
}
```

**Comment by mgravell** [comment]
I notice you're incrementing 24 times per key - is this just a stress test?
Or is this because you want to increment by 24? If the latter, you can
specify the increment count in the parameter.

**Comment by oscarld** [comment]
Marc, Thanks for the response,

No, I want to create 24 keys than will be expired periodically. The goal is to create a Most-viewed feature. I can share you the source code if you want.

**Comment by NickCraver** [comment]
Since these are fire and forget, are you letting the process finish sending before both exiting and checking the result? This would create a bit of a queue that may take a bit to drain depending on the horsepower involved.

**Comment by NickCraver** [comment]
Not enough info to go on here - closing out to cleanup.

**Comment by oscarld** [comment]
@NickCraver 

Quite so!, I was running a console application that exit when the principal thread is finished.

Thanks and sorry for the delay.
