### ISSUE TITLE
My Mouse Gets Stuck When i load up my game it will wok for a few sec and then stop and get stuck in the middle of screen

### ISSUE THREAD

**Issue by SnipesWildcat** [StackExchange/StackExchange.Redis#618]

**Comment by NickCraver** [comment]
Ah hell, let's give it a go. 
- What OS are you on? 
- Is it all games or a particular game? 
- Are you running in fullscreen or windowed mode?
- Is this a new problem?
- If Windows, have you run updates in a while?
- Is the cursor on your redis server or the client?

**Comment by mj1856** [comment]
It's normal for a mouse to only wok for a few seconds.  The don't like the heat.

![image](https://cloud.githubusercontent.com/assets/1396388/25413524/e460479a-29df-11e7-9910-0aecb94b821d.png)

**Comment by mgravell** [comment]
I have a similar problem with my trackball: if I install the vendor's driver / tool, then it is unusable inside any game. If I just use the OS driver, it is fine - but then  I can only use 2 of the 4 buttons. So if you have additional mouse software, try uninstalling it.

Fortunately, redis doesn't trigger this quirk, so in theory I can happily use `redis-cli` etc with all 4 mouse buttons. But sadly `redis-cli` only uses a keyboard :(

**Comment by itamarhaber** [comment]
I have Redis running almost all the time on my laptop and the trackpad + buttons + little red thing (Lenovo Thinkpad) work fine. Never connected a real mouse though so maybe this isn't a good way to reproduce this issue.

P.S. Running on Ubuntu 16.04

**Comment by itamarhaber** [comment]
BTW - we had an alleged cat messing with the Redis repo a few days ago, could be related. Ref: https://github.com/antirez/redis/issues/3909
