### ISSUE TITLE
Slow performance while writing data into Redis

### ISSUE THREAD

**Issue by SFareedi** [StackExchange/StackExchange.Redis#621]
I installed Redis using **Redis-x64-3.2.100.msi** on my machine, then I created my .Net project using VB.Net and done the following code

```vb
Dim Conn As ConnectionMultiplexer = ConnectionMultiplexer.Connect("localhost")
Dim redis As IDatabase = Conn.GetDatabase

Dim gStrConnectionString As String = ""
Dim lObjConnection As New SqlConnection(gStrConnectionString)
lObjConnection.Open()

Dim lStrQuery = "SELECT * FROM [dbo].[AggregarTest_2M]"

Dim SqlCommand As SqlCommand = New SqlCommand(lStrQuery, lObjConnection)
Dim lObjDataReader As SqlDataReader = SqlCommand.ExecuteReader()

If lObjDataReader IsNot Nothing Then

    For cnt As Integer = 0 To 2000000 - 1
        lObjDataReader.Read()

        'Loop throug each column (Total columns: 20) to create redis list against
        'each column and save its value
        For count = 1 To 20 - 1
            'Column name
            Dim colName = lObjDataReader.GetName(count)
            'Column Value
            Dim val = lObjDataReader(colName)

            'Save to redis cache
            redis.ListRightPush(colName.ToString, val.ToString)
        Next
    Next
End If
```

it is taking too much time. Do I something missing in my installation or in my code that make it fast

**Comment by manigandham** [comment]
What does "too much time" mean? You didn't include any info on how much time it takes. What are you expecting vs how long is it taking?

Redis on Windows is a port of the original code and will never be as fast as on Linux. Redis is also single-threaded and 100k ops/second is about the max for most CPUs. If you're doing 20 * 2M = 40 million ops then that'll take about 400 seconds at the fastest.

**Comment by NickCraver** [comment]
@manigandham I'd be careful on stats there, we have pretty standard server CPUs and pushing 250k ops/sec per core is something we do every day. Claiming that 100k is the max for "most" I'd consider incorrect.

**Comment by manigandham** [comment]
@NickCraver Sure, this doesn't seem like a server CPU based on the details but edited answer.

**Comment by SFareedi** [comment]
**@manigandham** In doing 20 * 2M = 40 Million ops, it is taking more than 20 mints. In memory point of view it is awesome but taking too much time, although in the above code I am not doing any extra operation. 

What I am expecting is if it comes on 3 to 4 mints for the above mentioned ops that will be fine for me and I am not running this on server CPU.

**Comment by SFareedi** [comment]
**@manigandham** It is fast on server CPU but taking 36 mints there too of doing 20 * 2M = 40 Million ops. Following is the CPU specs

Intel(R) Xeon(R) CPU E5-2609 v2 @ 2.50 GHz 2.50 GHz (2 Processors)

**Comment by manigandham** [comment]
The linux/server version is better to test against but 36 minutes is a long time. Is the SQL query slow? Are you using pipelining? Try sending 40M ops in a simple for-loop with fire/forget so you're not waiting on the latency for each request.

```
var redis = ConnectionMultiplexer.Connect("localhost");
var db = redis.GetDatabase();
for (int i = 0; i < 40 * 1000000; i++)
{
    db.ListRightPush("abc", i, flags: CommandFlags.FireAndForget);
}
```

This code in a console app takes a few seconds to send all the commands and under 3 minutes for Redis to fill the list. Remember to not quit the app until Redis receives all the commands.

**Comment by NickCraver** [comment]
Good to see this resolved, closing out to clean up!

**Comment by MasiumDev** [comment]
@SFareedi flags: CommandFlags.FireAndForget just means you queue tasks to do, performance not increased.
