### ISSUE TITLE
[Question]: RedisValue GetHashCode algorithm

### ISSUE THREAD

**Issue by RamanBut-Husaim** [StackExchange/StackExchange.Redis#626]
@mgravell , @NickCraver hello,

Could you please provide some information on the algorithm that is used for `GetHashCode` for [RedisValue](https://github.com/StackExchange/StackExchange.Redis/blob/c4c9c1fdb455070415e82d2f104fc89a90b057b5/StackExchange.Redis/StackExchange/Redis/RedisValue.cs) struct.

The name or just a link will be really helpful.

Thank you.

**Comment by NickCraver** [comment]
Hey @RamanBut-Husaim, here's a link with some details about the optimizations in there: http://stackoverflow.com/a/21981560/13249

**Comment by RamanBut-Husaim** [comment]
@NickCraver Thanks a lot. Seems that I understand why it is done in such manner.

All black magic is placed into these lines
```cs
int valHash = (((int)val) ^ ((int)(val >> 32)));
acc = (((acc << 5) + acc) ^ valHash);
```
with the initial accum value `int acc = 728271210`. 
I've read (another SO answer :) ) that prime numbers could be used for such stuff. But this is not the case there. 

Maybe you remember why this number was chosen? 

Google refers to the source code only. :)

**Comment by mgravell** [comment]
There is probably less voodoo here than you are imagining. If you want to propose a different seed, I'm fine with that.
