### ISSUE TITLE
[?Fixed?] Issue with perfomance

### ISSUE THREAD

**Issue by AlexanderKot** [StackExchange/StackExchange.Redis#628]
Hello

I have found interesting behavior ?bug? with StackExchange.Redis used in our app.
We are using ASP.NET MVC + latest  NHibernate + NHibernate.Caches.Redis + StackExchange.Redis [1.2.1] + many other libs. MSOpenTech Redis 3.2 installed on the same win server as IIS.

It was committed bug in our code, which cause many [~210] cached Nhib round-trip to DB.
After that we have faced problem: App become extremely slow on test environment when Redis cache is enabled, comparing to the same functionality without caching (but with many round-trips to DB).
Same behavior was not reproduced on dev environment.
Finally, after many experiments, updating StackExchange.Redis to 1.2.3 has solved problem on test environment.
But behavior of app with this problem was interesting.
Now I can reproduce situation simply by replacing StackExchange.Redis.dll (1.2.1 <-> 1.2.3) in IIS app dir.

Here it is possible to see what happens:
![capture13](https://cloud.githubusercontent.com/assets/1678749/25950009/29c79d9a-3662-11e7-971e-17864456fd6a.JPG)
During marked 10sec CPU activity application mainly processing Redis connection with big latency:
![capture11](https://cloud.githubusercontent.com/assets/1678749/25950391/7e151cf0-3663-11e7-8767-e249f2078102.JPG)
![capture11a](https://cloud.githubusercontent.com/assets/1678749/25950479/d0b660cc-3663-11e7-91af-f90245d1d451.JPG)
As i understand this:
1) Working IIS thread call Nhib for data (~210 times)
2) Nhib receive this data from 2d level cache 
3) During not optimal (_2 round-trips to redis per 1 query_ ) communication with cache,  StackExchange.Redis multiplex all Redis interaction to it's working R\W threads.
4) This interaction is slow on Sockets.NetworkStream.Read level
5) IIS working thread at that time consuming CPU by Monitor.Wait call...
![capture12](https://cloud.githubusercontent.com/assets/1678749/25951001/116b1814-3665-11e7-8065-0f1cd42fa57d.JPG)
 
This behavior disappear, if update StackExchange.Redis  to latest version.

So
1) Could anybody explain this behavior, and why it is fixed only by upgrading StackExchange.Redis?
2) Seems, that approach with multiplexing network interaction + latency + Monitor.Wait potentially dangerous. Is this true?

**Comment by NickCraver** [comment]
@mgravell would be best to comment - it looks like there's a perf fix from 1.2.1 to 1.2.3 and they're curious about what it was...any idea?

**Comment by abhit011** [comment]
#665 
Are they any way related ?

**Comment by mgravell** [comment]
IMPORTANT UPDATE: it turns out that the build config was broken during the csproj=>json=>csproj gymnastics; a very important flag wasn't ... flagged. This has been fixed in 1.2.5 which will be available on NuGet as soon as it indexed. We think this relates to this bug, and I'm hopeful that 1.2.5 will improve or completely fix this.

**Comment by AlexanderKot** [comment]
Hello
For my project it was fixed by 1.2.1 -> 1.2.3

**Comment by AlexanderKot** [comment]
Hello
I have done upgrade 1.2.4 -> 1.2.6 and now I have exactly same problem.
And can reproduce this on the same server.
Any idea what I can explore to understand why?

**Comment by AlexanderKot** [comment]
1.2.4 -> 1.2.5 is enough for reproduction

**Comment by NickCraver** [comment]
We've got a bifurcation of approaches that suit different use cases here. We accidentally reverted to the old style between 1.2.1 and 1.2.4 and fixed it in 1.2.5. Unfortunately, you're on the side adversely affected by this. We're anxiously awaiting a stable Pipelines release so that we can change the networking stack to work much simpler on top of this and *hopefully* solve far better for both groups.  Tagging this for that work.

**Comment by AlexanderKot** [comment]
Can I help something or explore to understand why this happens? Happens on my side - can happens on other sides.
I have only 1 test server where this behavior is reproducible. I cannot repeat this on any dev's environment.
One suspicious difference for this server is McAfee  antivirus. I have no control on it to disable and check it's influence to latency. I will try obtain this control.
What else i can check?

**Comment by NickCraver** [comment]
@AlexanderKot I'm not sure what advice to give here - if you're seeing it on one server then there's *something* about that environment, yes. Short of attaching a profiler directly and observing where the pauses are (any server stall could do this), I'm not sure what else to tell ya here.

**Comment by mgravell** [comment]
whatever changes have happened in 1.* point releases , 2.0 changes the shape completely - probably best to close and re-assess from there: https://github.com/StackExchange/StackExchange.Redis/issues/871
