### ISSUE TITLE
Exception from HRESULT: 0x8007007E

### ISSUE THREAD

**Issue by shanmine** [StackExchange/StackExchange.Redis#632]
Sorry, I got a exception is:
System.DllNotFoundException: Unable to load DLL 'combase.dll': 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)

How to handle it?
Thx!

**Comment by NickCraver** [comment]
Do you have a stack trace? What points to thinking this is a StackExchange.Redis issue?

**Comment by NickCraver** [comment]
Closing out to cleanup, we just don't have anything to go on here.
