### ISSUE TITLE
Problems writing to a redis cluster - connection endpoints contains also replicas with local IP

### ISSUE THREAD

**Issue by vladsaftoiu** [StackExchange/StackExchange.Redis#634]
I have a problem writing to a redis cluster. 

Having this as configuration: 
```
static readonly IEnumerable<EndPoint> Endpoints = new[]
{
    EndPointCollection.TryParse("10.5.2.146:7000"),
    EndPointCollection.TryParse("10.5.2.146:7001"),
    EndPointCollection.TryParse("10.5.2.146:7002"),
 };

public static ConnectionMultiplexer Build()
{
    var opt = new ConfigurationOptions { AllowAdmin = true };

    foreach (var endpoint in Endpoints)
        opt.EndPoints.Add(endpoint);

    Redis = ConnectionMultiplexer.Connect(opt);
    FlushAllDatabases();
    return Redis;
 }
```

and using it like this:
```
var redis = RedisConfig.Build();
redis.GetDatabase().StringSet("foo", "bar");
redis.GetDatabase().StringGet("foo");
```
returns this exception: 
```
StackExchange.Redis.RedisServerException: 'Endpoint 127.0.0.1:7002 serving hashslot 12182 is not reachable at this point of time. Please check connectTimeout value. If it is low, try increasing it to give the ConnectionMultiplexer a chance to recover from the network disconnect.  IOCP: (Busy=1,Free=999,Min=4,Max=1000), WORKER: (Busy=0,Free=2047,Min=4,Max=2047), Local-CPU: n/a'
```

the problem is that: `var endpoints = redis.GetEndPoints();` returns both configured endpoints with public IP and cluster-discovered endpoints (see image of inspected variable) with local IP, and then the node with private IP is used to retrieve the hashslot.

![image](https://cloud.githubusercontent.com/assets/1220347/26448212/748b935a-414c-11e7-81e4-fae8af2f0e06.png)

Is there anything else I should set up in the configuration or anything wrong using the client?

**Comment by vladsaftoiu** [comment]
Currently used configuration, each node has it's folder `.\700X` with it's own conf file and log:

    redis.conf  (for first node)
        port 7000
        cluster-enabled yes
        cluster-config-file nodes.conf
        cluster-node-timeout 5000
        appendonly yes
        logfile 7000.log
        protected-mode no
        bind 0.0.0.0

    nodes.conf
        0c213c727e90710bbd94d5094da2c6749872f74f 127.0.0.1:7001 master - 0 1494253090995 2 connected 5461-10922
        2e6d24ccec03d1ca674b936eac0e48dc6a97c405 127.0.0.1:7000 myself,master - 0 0 1 connected 0-5460
        7467c908c390bb6db202836fdff2966e4f100858 127.0.0.1:7007 slave bdd5c046e2a05b289ef0aba47a9987988defc799 0 1494253090889 8 connected
        bbb2d02845e57622b5e95574ab843d9cefd0b28a 127.0.0.1:7006 slave 0c213c727e90710bbd94d5094da2c6749872f74f 0 1494253090890 7 connected
        bdd5c046e2a05b289ef0aba47a9987988defc799 127.0.0.1:7002 master - 0 1494253092195 3 connected 10923-16383
        c39aa6ff1e9823a169b758fc5aed2f5e811a971a 127.0.0.1:7008 slave bdd5c046e2a05b289ef0aba47a9987988defc799 0 1494253091700 9 connected
        673d0af38625ae962f6ed7f527cc5162a08d7f21 127.0.0.1:7003 slave 2e6d24ccec03d1ca674b936eac0e48dc6a97c405 0 1494253091191 4 connected
        ed1e5ba7a0a569e2d4b8542bf8a8353d33e81384 127.0.0.1:7004 slave 2e6d24ccec03d1ca674b936eac0e48dc6a97c405 0 1494253090889 5 connected
        a4d29951bcf70593d14fbee5438608c88c971922 127.0.0.1:7005 slave 0c213c727e90710bbd94d5094da2c6749872f74f 0 1494253091722 6 connected
        vars currentEpoch 9 lastVoteEpoch 0

**Comment by mgravell** [comment]
Hmmm. Ultimately, the entire point of redis cluster is that *it* announces the IPs. If the cluster only knows and announces private IPs, then as I understand it: *it can't succeed*, unless I also introduce some additional configuration optional that maps public IPs to node ids.

I'm open to *adding* that, but frankly my understanding is the usual intended configuration is for the cluster to know *public* IPs. I'm going to ask on /r/redis to clarify this point before I proceed

**Comment by vladsaftoiu** [comment]
Asked on SO the same question [here](https://stackoverflow.com/questions/44182147/stackexchange-redis-writing-to-a-redis-cluster-points-to-local-ip-address) and it came out that `running:
```
    cluster meet 10.5.2.146 7000
    cluster meet 10.5.2.146 7001
    cluster meet 10.5.2.146 7002
```
solved the problem.
Reading [redis.io docs](https://redis.io/commands/cluster-meet) about `CLUSTER MEET

**Comment by mgravell** [comment]
So; it sounds like the solution is to configure the cluster with public IPs. Is there anything more the library can and should do to help here? or should I consider this closed?

**Comment by vladsaftoiu** [comment]
In my opinion the common cluster setup will be something like this: a set of reachable nodes with public IPs, all listed in the client configuration, and a set of replica nodes which can variate in number and should be of no interest to the client (thus with private IPs); the private nodes could be used for various tasks (bkps, monitoring etc.) and it is correct to make them not accessible to the client, unless required other way. 
Anyway, handling the list of public nodes is more a client task than a library task so for me this issue is closed.

Thank you

**Comment by mgravell** [comment]
I do not accept the statement that replica nodes should be of no interest to the client - it is absolutely useful to be able to run certain commands (read-only, obviously) against replicas when appropriate.

IMO what is needed is better partitioning of nodes into logical groups (which could be geographic groups, or operational groups), which would be reflected in the taxonomy APIs, and which should also impact election (you don't want a set of primaries that spans multiple different geos, if at all avoidable).

And since it isn*necessary"
