### ISSUE TITLE
Some important things is 

### ISSUE THREAD

**Issue by 564064202** [StackExchange/StackExchange.Redis#636]
As your words: ConnectionMultiplexer is thread-safe.So I think the instance which is  created by ConnectionMultiplexer  is also thread-safe like IDatabase 、IDatabase's method......

is that true???

The central object in StackExchange.Redis is the ConnectionMultiplexer class in the StackExchange.Redis namespace; this is the object that hides away the details of multiple servers. Because the ConnectionMultiplexer does a lot, it is designed to beshared and reused between callers. You should not create a ConnectionMultiplexer per operation. It is fully thread-safe and ready for this usage. In all the subsequent examples it will be assumed that you have a ConnectionMultiplexer instance stored away for re-use. But for now, let's create one. This is done using ConnectionMultiplexer.Connect orConnectionMultiplexer.ConnectAsync, passing in either a configuration string or a ConfigurationOptions object. The configuration string can take the form of a comma-delimited series of nodes, so let's just connect to an instance on the local machine on the default port (6379):

**Comment by 564064202** [comment]
@mgravell thank you very much,I see........

**Comment by 564064202** [comment]
@mgravell I just want to  know whether my inference is right or not. thanks sir.

**Comment by mgravell** [comment]
Note that "thread safety" is a complex topic; if you describe *precisely what you expect it to do*, I can be more specific. There are APIs designed for certain scenarios (batches, transactions, scripts, modules, etc). Which (if any) is appropriate: depends on context. You might not need any, and the regular "call methods, stuff happens" may be fine. 95% of the time, it is.

**Comment by 564064202** [comment]
@mgravell thank you for your help.

**Comment by mgravell** [comment]
(if I've closed incorrectly, just shout and we can re-open)
