### ISSUE TITLE
IRedisAsync exposes the ConnectionMultiplexer property instead of IConnectionMultiplexer

### ISSUE THREAD

**Issue by plushysmurf3** [StackExchange/StackExchange.Redis#638]
https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis/StackExchange/Redis/IRedisAsync.cs#L14

Since IConnectionMultiplexer was created, should IRedisAsync just return the interface instead?

**Comment by mgravell** [comment]
That would be a breaking change, so would need to be timed with a major rev.

I'm not hugely against it - it just isn't as simple as changing a type.

**Comment by plushysmurf3** [comment]
Understood. thanks!
