### ISSUE TITLE
Proper TimeoutException Handling

### ISSUE THREAD

**Issue by danielHalan** [StackExchange/StackExchange.Redis#64]
Hi, 

I'm running few threads with Redis Locking mechanism against an Azure Redis Cache Server, and once in a while I get a TimeoutException (even thou there has not been any Idle time during the past minute), not sure if this is by design and how would one avoid this?

My Current solution is to Close the Connection, and create a new one, and continue let the threads continue. (cMgr.Close; cMgr = ConnectionMultiplexer.Connect())

**Comment by NickCraver** [comment]
@danielHalan Are you still seeing issues today? Azure redis got off to a rocky start with latency but my understanding is the current situation is far better and more stable.
