### ISSUE TITLE
InConsistent Results with Fire&Forget Option while Saving to Redis DB.

### ISSUE THREAD

**Issue by nreddipalle** [StackExchange/StackExchange.Redis#644]
I am reading records from SQL DB to load into Redis. The data could be up to million records. I am getting consistent results when using **database.Execute("FT.ADD", args)** but not the case when I am using **database.Execute("FT.ADD", args, CommandFlags.FireAndForget)** 
Same for **database.SetAdd(this.indexSetKey, toAddToSet.Select(t => (RedisValue)t).ToArray(), CommandFlags.FireAndForget);**

As shown in the below snippet, I am reading all the data from SQL (around 1M records) and then trying to insert into Redis in chunk of 100. when using FireAndForget option, the results are inconsistent each time. 1 in 10th time, it might insert all the records as expected. 

![image](https://user-images.githubusercontent.com/28302399/26990777-daaf2f72-4d25-11e7-8366-23a4f1f56f5b.png)

Let me know if any more details are needed.

**Comment by mgravell** [comment]
I wonder if the "fix" here is for me to release the async throttled
overlapped pipe that we use internally (inspired by our dapper code). This
allows you to pipeline a ling sequence of operations without overloading
any absurd limits, essentially saying "run this koad sequentially but
overlapped with no more than [n] outstanding at any time".

**Comment by nreddipalle** [comment]
That could work I assume.

**Comment by nreddipalle** [comment]
Any update on this??

**Comment by NickCraver** [comment]
@nreddipalle Were you still hitting trouble with the latest version of the library? Some critical threading changes happened at various points. I'm sorry we missed this, but if you could let me know if this still happens on 1.2.6 or is no longer an issue I'd appreciate it. We've been underwater for a while, and I'm trying to catch up on any issues people are still experiencing.

**Comment by NickCraver** [comment]
Closing this one out, tons of changes since originally posted that would affect this.
