### ISSUE TITLE
Nuget Release 1.2.3 is built id debug mode and without optimizations

### ISSUE THREAD

**Issue by jrlost** [StackExchange/StackExchange.Redis#649]
While debugging a completely unrelated issue I noticed that with the release of 1.2.3, the assembly is now built in debug mode.  I walked through the last 3 prior releases and they were built with optimizations.

Would it be possible to get a fresh copy built and deployed to nuget.  Thanks.

**Comment by mgravell** [comment]
That would be a surpise to me; I will definitely investigate. If that is
the case it is certainly not intentional.

**Comment by mgravell** [comment]
1.2.4 pushed; this was unexpected fallout from the workaround code to the "dotnet build doesn't correctly add framework dependencies" issue; thanks for the report

**Comment by jrlost** [comment]
Thanks
