### ISSUE TITLE
StackExchange.Redis not able to detect automatic failover

### ISSUE THREAD

**Issue by hrishi18pathak** [StackExchange/StackExchange.Redis#65]
Hello
We have 2 node redis server setup where 1 node is master and the other is a slave. We have observed that  StackExchange.Redis can take anything from few seconds to several minutes to reconnect to the server if master/slave failover happens in the background. i.e. if we keep on using the same ConnectionMultiplexer object as the one created before the failover was triggered we get keep on getting a connection exception. The connectionMultiplexer object takes atleast 1 minute(sometimes more) to recover from this condition. Is this expected? If we create a new ConnectionMultiplexer object during this time its able to connect to the redis server successfully
Thanks

**Comment by NickCraver** [comment]
There have been many, *many* improvements on connections and retry since this was logged - I'm going to close this one out. If someone can repro on a current version we'll open it right back up.

**Comment by NickMRamirez** [comment]
I have three redis nodes, with Sentinel promoting another to master if one fails. I log into the Redis master and cause it to fail vis `debug sleep 30`. The following client code will receive a `System.TimeoutException` at when trying to write to the master that has failed:

```
public static void Main(string[] args)
        {
            ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("redis1-exp.aclens.local:6300,redis2-exp.aclens.local:6300,redis3-exp.aclens.local:6300");

            while (true)
            {
                var db = redis.GetDatabase();
                db.StringSet("mytime", DateTime.Now.ToLongTimeString()); // throws exception
                Console.WriteLine(db.StringGet("mytime"));
                Thread.Sleep(5000);
            }
        }
```
