### ISSUE TITLE
System.TimeoutException: Timeout performing 

### ISSUE THREAD

**Issue by rukhsarahmad-gep** [StackExchange/StackExchange.Redis#653]
System.TimeoutException: Timeout performing GET DownstreamBasicSettings_Order__0:XXX:0:en-US, inst: 0, mgr: Inactive, err: never, queue: 5, qu: 4, qs: 1, qc: 0, wr: 1, wq: 1, in: 0, ar: 0, IOCP: (Busy=3,Free=997,Min=150,Max=1000), WORKER: (Busy=2,Free=32765,Min=150,Max=32767), clientName: XXXXX

Possible reasons?

**Comment by NickCraver** [comment]
Apologies for the massive backlog here - trying to follow up on every issue. Are you still seeing this? If so:
- What is your timeout set to?
- What does your environment look like? On-prem? Cloud? What's the latency like?

Be sure you're on 1.2.6 or higher, which has several fixes around timeouts.

**Comment by mgravell** [comment]
Closing; please see #871
