### ISSUE TITLE
Cannot restore Nuget packages with vs2017

### ISSUE THREAD

**Issue by justinuliu** [StackExchange/StackExchange.Redis#656]
Hi everyone,

When I open solution with VS2017, I get this error. Did I miss something?

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for framework ".NETFramework,Version=v0.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	NRediSearch	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1111

**Comment by mgravell** [comment]
Well that's a new one! I will try to repro. What *exact* version of VS2017
are you using?

**Comment by justinuliu** [comment]
Microsoft Visual Studio Community 2017 
Version 15.2 (26430.14) Release
VisualStudio.15.Release/15.2.0+26430.14
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA232
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA232
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA232
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.30503.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Redgate SQL Search   2.3.10.1131
Search functionality for SQL Server databases, from within Visual Studio

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.2.2.0
TypeScript tools for Visual Studio

Visual Studio Tools for Apache Cordova   15.113.6201.1
Visual Studio Tools for Apache Cordova

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

Visual Studio Tools for Unity   3.1.0.0
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.26430.06
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

**Comment by mgravell** [comment]
So far, my attempts to repro have failed - it works fine here:

```
Attempting to gather dependency information for package 'StackExchange.Redis.1.2.4' with respect to project 'ConsoleApp12', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 655.65 ms
Attempting to resolve dependencies for package 'StackExchange.Redis.1.2.4' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'StackExchange.Redis.1.2.4'
Resolved actions to install package 'StackExchange.Redis.1.2.4'
Retrieving package 'StackExchange.Redis 1.2.4' from 'nuget.org'.
  GET https://api.nuget.org/packages/stackexchange.redis.1.2.4.nupkg
  OK https://api.nuget.org/packages/stackexchange.redis.1.2.4.nupkg 449ms
Installing StackExchange.Redis 1.2.4.
Adding package 'StackExchange.Redis.1.2.4' to folder 'C:\Users\marcg\OneDrive\Documents\Visual Studio 2017\Projects\ConsoleApp12\packages'
Added package 'StackExchange.Redis.1.2.4' to folder 'C:\Users\marcg\OneDrive\Documents\Visual Studio 2017\Projects\ConsoleApp12\packages'
Added package 'StackExchange.Redis.1.2.4' to 'packages.config'
Successfully installed 'StackExchange.Redis 1.2.4' to ConsoleApp12
Executing nuget actions took 2.45 sec
Time Elapsed: 00:00:03.4771831
========== Finished ==========
```

**Comment by justinuliu** [comment]
I will try to repro it on another system. Maybe my current system have some problem.

Thank you.

**Comment by justinuliu** [comment]
I'm so sorry I didn't make myself clear.  I use VS2017 to open "StackExchange.Redis.sln", and I get the error like this:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for framework ".NETFramework,Version=v0.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	StackExchange.Redis	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1111	

What I mean is I want to compile "StackExchange.Redis" library manually .  What should I do to build "StackExchange.Redis" library?  Could you please give me any reference ? 

Thank you.

**Comment by mgravell** [comment]
Oh, right. yeah, opening the sln should be enough. However, you can also
build at the command-line with "dotnet restore" and "dotnet build -c
Release"

**Comment by justinuliu** [comment]
Thank you.  I got my answer.
