### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException - on concurrent KeyExpire and StringSet

### ISSUE THREAD

**Issue by badalp** [StackExchange/StackExchange.Redis#657]
I am facing timeout exception in my aspnet core app. The exception details are as below
`StackExchange.Redis.RedisTimeoutException: Timeout performing GET search.key, inst: 56, queue: 56, qu: 0, qs: 56, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0, clientName: MGNWS1, serverEndpoint: 192.168.100.10:6379, keyHashSlot: 5494 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)
   at App.Service.Caching.RedisCacheManager.Get[T](String key, Boolean& hasValue)`

I have initialized the multiplexer using C# Lazy keyword in static class and i am executing around 15000 redis request (90% ar GET and 10% are SET) in a minute. Everything is working fine. But once i run the code to expire around 15-20 keys then Redis becomes unresponsive and throws above exception. It simply doesnt respond any command from app, i need to restart the website to make it work . I have set 30 seconds for both SyncTimeout and ConnectionTimeout. Above errors starts after 30 seconds once i expire the keys. Till that time no requests are being served

for setting the key, i am using the below code
`bool temp = db.StringSet(key, value, new TimeSpan(expireDate.Ticks));`

and for expire, i am executing loop to expire one key at a time
`db.KeyExpire(key, TimeSpan.FromTicks(0));`

As of now, i have put C# "lock" keyword on both StringSet and KeyExpire code, so it can be done thread safe. And now everything is working fine, even if i expire the keys while requests are executing. But i am looking for any better alternative than this. Is there any deadlock kind of issues? I know MONITOR functionality is there, but is there any better way to troubleshoot (MONITOR is messy with all this many requests)?

**Comment by mgravell** [comment]
IMPORTANT UPDATE: it turns out that the build config was broken during the csproj=>json=>csproj gymnastics; a very important flag wasn't ... flagged. This has been fixed in 1.2.5 which will be available on NuGet as soon as it indexed. We think this relates to this bug, and I'm hopeful that 1.2.5 will improve or completely fix this.

**Comment by NickCraver** [comment]
@badalp Can you please try the latest release and let us know if the problem persists?

**Comment by badalp** [comment]
We have used memory cache for the time being. This one is live site
However, we plan for beta release with redis again in 15 days. So i will let you know in that time.

**Comment by wags1999** [comment]
@badalp, do you have any updates on this?  

I also have a Production site using Microsoft.Web.RedisSessionStateProvider v2.2.2 and StackExchange.Redis v1.2.5, getting a very similar issue to what you posted:
`Message: Timeout performing EVAL, inst: 1, mgr: RecordConnectionFailed_FailOutstanding, err: never, queue: 17044, qu: 0, qs: 17044, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0,`

Based on [this link](https://azure.microsoft.com/en-us/blog/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/), **in** represents the bytes available on the NIC, and I'm guessing **ar** represents the number of active readers. I believe in both our cases this means there's data on the NIC waiting to be read, but for some reason, StackExchange.Redis has zero readers - and so all requests timeout until the App Pool is restarted.

@NickCraver, does that sound right?

**Comment by NickCraver** [comment]
@wags1999 Yep that's the exhaustion issue largely addressed by the 1.2.6+ build fixes.

Since there's no update on the original issue and we have a consolidated discussion in #716, I'm going to close this out to cleanup.
