### ISSUE TITLE
How can I use redis pipeline in async/await way.

### ISSUE THREAD

**Issue by standardcore** [StackExchange/StackExchange.Redis#662]
I have done read the chapter 'Pipelining'.It looks like when I use db.Wait then the application will use pipeline to execute the command.But I am not really understood it.
Here is my issue.I have to get many hash-values in my applciation , but the performance of `foreach` is unsatisfactory. I am thinking of use redis pipeline to improve it. But synchronize methods will cause deadlock, so I can't use db.Wait. 
Can I use redis pipeline in a more native way?

**Comment by NickCraver** [comment]
Are you getting *all* the values for a particular hash and iterating over them? If so you likely want `HashGetAll` (or `HashGetAllAsync`) and then iterate locally. This is one batch of IO which should have substantially better performance.
