### ISSUE TITLE
SetAdd and SetMembers behaviors

### ISSUE THREAD

**Issue by leslie019** [StackExchange/StackExchange.Redis#664]
I'm just wondering about the behavior of SetAdd and SetMembers. I have an array of RedisValue, during debugging mode, I could see the expected order of my array but when the SetAdd fires, it seems that the stored array has been shuffled and so as for the SetMembers,

Ex.
Expected order of members: 
21000-0000-000
21000-0001-000
21000-0002-000
21000-0003-000
21000-0004-000 and so on...

Saved set (**SetAdd**): 
21001-0007-007
21001-9000-000
21000-9000-006
21000-9000-007
99010-9021-011 and so on...

Retrieved members (**SetMembers**):
21001-9001-002
21001-9001-000
21000-0007-006
21000-9000-007
21001-0103-007 and so on...

I tried using the ListRightPush and I was able to save the array in correct order. However, I can't find an easy way to retrieve the list and I think there's no built-in function for it unless you specify the index.

Can you enlighten mo on this? 

Thanks in advance.

**Comment by mgravell** [comment]
A "set" (in the `sadd` sense) in redis. The order is explicitly undefined. I expect that if you use `monitor`, you'll see that SE.Redis is *adding* them in the order you defined, but what the server does with them is entirely up to it. This is explicitly called out in the redis docs: https://redis.io/topics/data-types-intro#redis-sets

>  Redis is free to return the elements in any order at every call, since there is no contract with the user about element ordering.

Essentially, redis sets are comparable to `Dictionary<string,string>` in .NET: there is no guarantee whatsoever about the insert order being respected.

**Comment by NickCraver** [comment]
@leslie019 Just going through an issue cleanup pass here, did this answer your question or have some follow-ups?
