### ISSUE TITLE
How to execute the 'TYPE' command?

### ISSUE THREAD

**Issue by gsh434541340** [StackExchange/StackExchange.Redis#667]
I want to use the key to get the data type.

**Comment by mgravell** [comment]
`IDatabase.KeyType(key)` (and similarly for async)

**Comment by gsh434541340** [comment]
Thanks ! It's right.
I use the following method:
            string script = "return redis.call('type', @key)";
            var prepared = LuaScript.Prepare(script);
            var keyType = redisDB.ScriptEvaluate(prepared, new { key = redisKey });

**Comment by mgravell** [comment]
but... but... why would you use lua when the method is exposed natively and
more efficiently?
