### ISSUE TITLE
Stack Exchange connecting to Redis Cluster gives connection failure

### ISSUE THREAD

**Issue by avshetty** [StackExchange/StackExchange.Redis#670]
I am trying to connect our asp.net application through Stack exchange client to Redis Cluster, but I am getting an connection error shown below :

No connection is available to service this operation:

I am using the connection string :

< add key="SearchCacheRedisConnectionString" value="IP:6379,IP:6379,connectTimeout=1000,abortConnect=false,ConnectRetry=3,syncTimeout=500,keepAlive=180" />

I have used the same connection string to connect to a standalone redis instance and everything works perfectly.

Its only when i try to connect to a cluster ( 3 master 3 slave ) architecture that i am getting a connection error.

Is there a different connection string i am supposed to use to connect to a Redis Cluster or is there any specific changes i am supposed to make in my code to connect to a Cluster.

Any help will be much appreciated. Thank you

**Comment by mgravell** [comment]
This should just work. Does this happen for all operations? Or some operations / keys? Or just intermittently? 

How is the cluster configured? Does the cluster advertise *available* IP addresses? One common error I've seen people make (perhaps due to vague documentation) is to configure the cluster using loopback / private IPs, which is problematic because "cluster nodes" etc will then announce these as the ones to use.

**Comment by avshetty** [comment]
Hi mgravell, thanks for your quick response.

This is happening for all operations/keys.  Im not sure whether the cluster is advertising available ip address, could you please guide me on configuring the cluster. We are using only private address for connections.

**Comment by avshetty** [comment]
Hi mgravell thanks for your response.

Im getting this error for all operations. The cluster is configured to use private IP and my application is in the same vnet as the redis cluster, so it should be able to connect without any issues. Apart from this is there any additional configurations that need to made in configuration file?

**Comment by avshetty** [comment]
Also we have set cluster-announce-ip **private_ip_address**   and cluster-accounce-port **6379**

**Comment by mgravell** [comment]
if this relates to redis 4.*, see #672 - this was due to an undocumented break in redis, and is fixed in the latest SE.Redis lib on nuget****

**Comment by avshetty** [comment]
@mgravell Thanks for your help marc, it seems to be working as expected after updating to SE.Redis 1.2.6.         Have a great day.

**Comment by NickCraver** [comment]
Closing out to cleanup!
