### ISSUE TITLE
Easy way for cross-platform

### ISSUE THREAD

**Issue by voidmonk** [StackExchange/StackExchange.Redis#671]
Hi, just wanted to know what's the best approach for cross-platform usage of this lib?

My dev environment is running .NET Framework 4.7 on Windows, but the deployment is required on Linux running Mono. The lib package is referenced via nuget, but it doesn't work on Mono (due to #314), so how can I automate the build process (msbuild via TeamCity on Windows) to seamlessly include, build & reference the Mono version, but still use the nuget package during development?

Any suggestions are appreciated. Thanks!

**Edit:** I suppose one way can be to edit the project file with conditional references (like the [example in this SO answer](https://stackoverflow.com/a/1836417/1157545)) to use the nuget package (dev only) or a locally compiled copy (using `monobuild.cmd` on the build server). Does this seem like a good, reliable way, or is there any other better alternative in the absence of a universal assembly or even platform-specific nuget packages?

**Comment by NickCraver** [comment]
What error actually happens on Mono? I know a lot has changed and we're behind on current data here (and generally unfamiliar with the Mono day-to-day happenings). Any info would be appreciated, and it'll help us figure out what to do with the builds, etc.

**Comment by NickCraver** [comment]
Folding this into #314 - we're digging into the Mono problem and working on getting setup to test it there.
