### ISSUE TITLE
Compilation error: Feature 'declaration expression' cannot be used

### ISSUE THREAD

**Issue by voidmonk** [StackExchange/StackExchange.Redis#674]
I downloaded the latest source (1.2.5) zip, and tried compiling it using `monobuild.cmd` under Windows Server with latest mono stable (5.0.1.1), but it throws an error during compilation:

> Building StackExchange.Redis.dll ...
> StackExchange.Redis\StackExchange\Redis\CommandMap.cs(179,49): error CS1644: Feature `declaration expression' cannot be used because it is not part of the C# 6.0 language specification
> Compilation failed: 1 error(s), 0 warnings

Any clues why this would occur, and how to resolve it?

**Edit:** Same error when compiling it using `monobuild.bash` under Ubuntu Server 16.04 with latest mono stable (5.0.1.1).

**Comment by rufusl** [comment]
You can compile using the new roslyn compiler: replace calls to `mcs` by `csc` in the script. I think the new compiler is included in Mono 5.x releases.
