### ISSUE TITLE
Timeout exceptions, Version :1.2.6.0

### ISSUE THREAD

**Issue by xiongwenyu** [StackExchange/StackExchange.Redis#675]
Timeout performing GET e9082a4913de4d70859f8b366603dc7c.StoreUser, inst: 5, mgr: ExecuteSelect, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: DESKTOP-P4NH1CV, serverEndpoint: 192.168.10.222:6379, keyHashSlot: 13994, IOCP: (Busy=0,Free=1000,Min=200,Max=1000), WORKER: (Busy=22,Free=4073,Min=200,Max=4095) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts

**Comment by wyaron** [comment]
I encounter a similar issue @ version 1.2.6 after upgrading from 1.1.6 (using only sync requests)

**Comment by NickCraver** [comment]
Closing this one out as a duplicate - as in the timeout documentation above: the `Busy=22` in the error message indicates a bit of load built up on that machine. You can either up the timeout in the configuration, or address the application load in other ways.
