### ISSUE TITLE
Connection failure when creating a multiplexer on Mono/Linux, works on Core and Windows CLR  

### ISSUE THREAD

**Issue by alexeyzimarev** [StackExchange/StackExchange.Redis#679]
I have made a repository to reproduce the issue https://github.com/alexeyzimarev/StackExchange.Redis.ConnectionIssue

Error message is 
> It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. 

Core project - works fine on Linux
4.6.1 project - works on Windows, crashes on Linux with Mono. Build with Mono 15

**Comment by NickCraver** [comment]
You can see progress in #314, but this now works. No Mono build required, `master` latest build just supports Mono in one DLL. This means the next NuGet release will as well. Use the `net46` DLLs as an example, we now have the full test suite runnable on Mono :)
