### ISSUE TITLE
StackExchange.Redis.RedisConnectionException: UnableToResolvePhysicalConnection on EXEC

### ISSUE THREAD

**Issue by axefrog** [StackExchange/StackExchange.Redis#68]
This is more of a question than an issue. My app is experiencing an exception periodically which I'm guessing may be brief network glitches with my hosting provider?

StackExchange.Redis.RedisConnectionException: UnableToResolvePhysicalConnection on EXEC

What are the conditions under which this exception is thrown, instead of waiting for a connection to become available? Is there a way I can make the library unconditionally tolerant of prolonged disconnected periods? I'm happy for it to hold up the entire application while waiting for reconnection, as it's a back end process and of course anything is preferable to a flat out crash.

**Comment by TPoise** [comment]
Is there not a way to auto-reconnect?  Checking IsConnected on every command can be cumbersome.
