### ISSUE TITLE
Unable to build solution in VS2017 community

### ISSUE THREAD

**Issue by LoudDJ** [StackExchange/StackExchange.Redis#688]
I've clone this repo to local machine and can't build it. Visual Studio show dozens of errors like CS0518 Predefined type 'System.Object' is not defined or imported. Could you help me please?

**Comment by OpenSourceAries** [comment]
Try build.cmd

**Comment by LoudDJ** [comment]
build.cmd works fine and generate dlls in output path, but visual studio still deny to work and error messages stay.

**Comment by NickCraver** [comment]
If you have the latest Visual Studio (2017 15.3) restore happens appropriately automatically. If you don't, you'll need to manually restore, either by right clicking the solution or `dotnet restore` at the command line. Doing a build from the command line with `build.cmd` or `build.ps1` first will also cause a restore to happen.
