### ISSUE TITLE
GeoPosition - Switching lat, lon error

### ISSUE THREAD

**Issue by brunohbrito** [StackExchange/StackExchange.Redis#690]
Hi guys,

After a few tests, I found something thats seems a bug at GeoPositon object, I don't know why, but sometimes it's changing the Latitude with Longitude.

Look at this:
![image](https://user-images.githubusercontent.com/7241156/29327119-744ca1f0-81c4-11e7-977f-c042bf7242fc.png)

But when we request for the Latitude property, it return the Longitude:
![image](https://user-images.githubusercontent.com/7241156/29327075-45b62064-81c4-11e7-95bb-9e19b63aea04.png)

**Comment by mgravell** [comment]
well that would be bad! will investigate

**Comment by brunohbrito** [comment]
Hi, 

I found the issue, on RawResult.cs in GetItemsAsGeoPosition() at return the parameters of GeoPosition is in format of Lat+Lon, but constructor expect a Lon + Lat.

The most commom cases about using Geoposition objects, use Lat first from Lon, but in this scenario I believe that there is a lot of projects that reference the GeoPosition object, so instead of change the constructor I've changed the RawResult. I'll make a pull Request.

**Comment by NickCraver** [comment]
The lack of stable Redis 3.2 on Windows is the issue in testing here. I need to get Docker/other testing up to enable these...but I don't have a CI story for that. Sorry for the delay, the fundamental issue of MSOpenTech shutting down Redis on Windows is causing a lot of pain for anything on versions newer than that :( Will merge PR soon as I can get time for additional testing options.

**Comment by NickCraver** [comment]
Fixed via #694, thanks @brunohbrito!
