### ISSUE TITLE
Timeout exceptions, Version :1.2.5.0

### ISSUE THREAD

**Issue by pruzam** [StackExchange/StackExchange.Redis#693]
Timeout performing EXISTS session_5968d77d-9531-4263-8bf4-d3260686ed12, inst: 1, queue: 118, qu: 0, qs: 118, qc: 0, wr: 0, wq: 0, in: 42801, ar: 0, IOCP: (Busy=0,Free=3200,Min=160,Max=3200), WORKER: (Busy=95,Free=3105,Min=160,Max=3200), clientName: docker-gmu-16913

above error occur from time to time, our config:

config.AbortOnConnectFail = false; 
config.ConnectTimeout = 15000;
config.SyncTimeout = 15000;
connection.PreserveAsyncOrder = false;

**Comment by NickCraver** [comment]
Can you please try 1.2.6? A major threading issue was resolve in this release. I see quite a few busy workers going on there so it appears the thread pool is being starved. 

Note: you have a *lot* of background work happening, I would also ensure that 95 workers running is intentional.

**Comment by pruzam** [comment]
alter update to 1.2.6 i don't see any errors. thanks :)
