### ISSUE TITLE
stackexchange redis unable to connect

### ISSUE THREAD

**Issue by 1amirjalai** [StackExchange/StackExchange.Redis#696]
I'm getting this error a lot.

Two Asp.net core 1.1 app make connection to redis using following code.

latest redis is intalled on a different machine on centos 7

> {Redis-FailureType: "UnableToConnect", Redis-EndPoint: "192.168.xxx.xxx:6379", Redis-Origin: "ResetNonConnected", Redis-Input-Buffer: "0", Redis-Outstanding-Responses: "0", Redis-Last-Read: "6s ago", Redis-Last-Write: "6s ago", Redis-Unanswered-Write: "737699s ago", Redis-Keep-Alive: "60s", Redis-Pending: "0", Redis-Previous-Physical-State: "Connecting", Redis-Last-Heartbeat: "never", Redis-Last-Multiplexer-Heartbeat: "-1s ago", Redis-Last-Global-Heartbeat: "2s ago"}

and my connection 

```c#
public  static class  RedisConnectionManager
{
    private static Lazy<ConfigurationOptions> configOptions = new Lazy<ConfigurationOptions>(() =>
    {
        var configOptions = new ConfigurationOptions();

        configOptions.EndPoints.Add("192.168.xxxx.xxx:6379");
        configOptions.SyncTimeout = 4000;
        configOptions.AbortOnConnectFail = false;
        return configOptions;
    });

    private static readonly Lazy<ConnectionMultiplexer> LazyConnection = new Lazy<ConnectionMultiplexer>(() =>
    {
        var connection = ConnectionMultiplexer.Connect(configOptions.Value);
        connection.PreserveAsyncOrder = false;
        return connection;
        
    });

    public static ConnectionMultiplexer SafeCoonect
    {
        get
        {
            return LazyConnection.Value;
        }
    }
}
```

**Comment by NickCraver** [comment]
There are some newer issues we need to address here (specifically for @1amirjalai), but I think it's safe to close out all the `netstandard1.x` issues at this time due to the sockets landscape being *very* different and lacking. Most of the base connection issues here were resolved on the .NET team side of the fence.
