### ISSUE TITLE
StackExchange.Redis.StrongName problem in AspNetCore 2.0

### ISSUE THREAD

**Issue by Rodrigo-Andrade** [StackExchange/StackExchange.Redis#697]
I am porting an app from the full framework to the new dotnetcore 2.0.

I added StackExchange.Redis as a nuget dependency, when i build the solution i get this:

Error	CS0433	The type 'IDatabase' exists in both 'StackExchange.Redis.StrongName, Version=1.2.4.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=1.2.6.0, Culture=neutral, PublicKeyToken=null'	

my csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.3.10.1" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.3.0.21" />
    <PackageReference Include="Dapper" Version="1.50.2" />
    <PackageReference Include="JetBrains.Annotations" Version="11.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="MySqlConnector" Version="0.25.1" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Polly" Version="5.3.1" />
    <PackageReference Include="StackExchange.Redis" Version="1.2.6" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>

</Project>
```

**Comment by NickCraver** [comment]
Ultimately we're included in the `Microsoft.AspNetCore.All` package, so you can simply remove this line:
```xml
<PackageReference Include="StackExchange.Redis" Version="1.2.6" />
```

**Comment by OpenSourceAries** [comment]
@NickCraver  My asp.net core program reference Common DLL(which reference StackExchange.Redis 1.2.6) and Microsoft.AspNetCore.All, this solution will not work very well.

**Comment by OpenSourceAries** [comment]
@NickCraver  I change the Common DLL reference to StackExchange.Redis.StrongName(1.2.6) then fix this issue, thank you.

**Comment by Rodrigo-Andrade** [comment]
i installed the newer version of the strong named package, but, is it intended to only allow strong named versions for dotnet core? it was quite confusing until i got what was going on.

**Comment by NickCraver** [comment]
@Rodrigo-Andrade There are just 2 packages (one strong, one not). We agree it's confusing since we've gotten so populate (dependency tree-wise). In V2 the main package will be strongly named and `.StrongName` will go away.

**Comment by losttrekker** [comment]
For others who have run into this issue where .Net Core is still referencing the StrongName package see this issue for the workaround: https://github.com/NuGet/Home/issues/4989

**Comment by mgravell** [comment]
We totally missed an opportunity to ship V2 of SE.Redis, Dapper, etc - with
all the breaking changes - on 1st April. Dammit.

**Comment by elestedt** [comment]
When is this going to be resolved? The workaround mentioned does make `dotnet build` run without errors or warnings - but IDE's, in my case specifically vscode, still shows alot of errors on this...
I'm running with the RC1-final of .NET Core 2.1.

**Comment by chris-brown** [comment]
If your using netcore 2.1 @elestedt you should be able to move to the new meta-package `Microsoft.AspNetCore.App` and reference `StackExchange.Redis` explicitly as it has been taken out of the `.all` meta-package. More details here: https://github.com/aspnet/Announcements/issues/287

**Comment by elestedt** [comment]
@chris-brown I am on the `Microsoft.AspNetCore.All` package - which is the default one. But I'll try swapping to `Microsoft.AspNetCore.App` and see if it makes a difference.

**Comment by erdogangulsoy** [comment]
Swapping to `Microsoft.AspNetCore.App` works! Thanks.

**Comment by ReneCode** [comment]
simply install only the nuget-package: 
    StackExchange.Redis.StrongName

**Comment by dewelloper** [comment]
> @Rodrigo-Andrade There are just 2 packages (one strong, one not). We agree it's confusing since we've gotten so populate (dependency tree-wise). In V2 the main package will be strongly named and `.StrongName` will go away.

how to go away?. i have tryed everything

**Comment by mcheung610** [comment]
Does anyone has a fix for this? I am trying to upgrade  `stackexchange.redis` in my netcoreapp and keep getting this error.

**Comment by uskorc** [comment]
@mcheung610 Please see this [issue 4989 on nuget home](https://github.com/NuGet/Home/issues/4989)

**Comment by mesutpiskin** [comment]
Does anyone has a fix for this

**Comment by akhileshmaithani** [comment]
Does anyone have a solution for this I am getting the same error in .NET Core 3.1?

**Comment by mgravell** [comment]
Without knowing your build dependencies, that's hard to comment on, but: from v2, the StrongName package is effectively redundant and obsolete

**Comment by akhileshmaithani** [comment]
> Without knowing your build dependencies, that's hard to comment on, but: from v2, the StrongName package is effectively redundant and obsolete

![image](https://user-images.githubusercontent.com/22465057/92716209-23c79c80-f37c-11ea-8c0c-2f8cec1ab6e8.png)
Please check the screenshot for build dependencies.

**Comment by NickCraver** [comment]
Ah I see - they changed the package name after 2.x, see https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis/3.1.8 instead of `Microsoft.Extensions.Caching.Redis`
