### ISSUE TITLE
Repository pattern with Redis

### ISSUE THREAD

**Issue by aberbegall** [StackExchange/StackExchange.Redis#703]
When using Redis as database,
Does anyone has experience implementing repository pattern with a Redis "context"? 
The idea is to abstract the underlying Redis data source.
The same question about generic repository and unit of work patterns.
Thanks in advance.

**Comment by NickCraver** [comment]
@aberbegall There are *some* generic caching things in play here, e.g. [Microsoft.Extensions.Caching.Redis](https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis), but nothing relational since a key/value style store is so very different.

**Comment by NickCraver** [comment]
Closing out to cleanup.
