### ISSUE TITLE
Intermittent failure in RedisSubscriber.Ping : No connection is available to service this operation: UNSUBSCRIBE

### ISSUE THREAD

**Issue by djagd** [StackExchange/StackExchange.Redis#704]
**Background**
We were intermittently missing messages published after `RedisSubscriber.Subscribe` call. We could also see that ConnectionRestored event was raised for `ConnectionType.Subscription` whenever this happened.

In order to determine what was going wrong `RedisSubscriber.Ping()` was placed before the subscription call and the reported exception manifested.

**Reproduction Code**
```C#
public void DoTest()
{
    for (int i = 0; i < 50; i++)
    {
        StringWriter stringWriter = new StringWriter();
        using (var conn = ConnectionMultiplexer.Connect("localhost", stringWriter))
        {
            var subscriber = conn.GetSubscriber();
            try
            {
                subscriber.Ping();
            }
            catch (Exception e)
            {
                stringWriter.Flush();
                Console.WriteLine(stringWriter.ToString());
                Console.WriteLine("{0} : {1}", i, e);
                throw;
            }

            subscriber.Subscribe("Testing" + i, delegate (RedisChannel channel, RedisValue value)
            {
                Console.WriteLine(value);
            });
        }
    }
}
```

**Stacktrace**
```
StackExchange.Redis.RedisConnectionException
No connection is available to service this operation: UNSUBSCRIBE; IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767), Local-CPU: n/a
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisSubscriber.Ping(CommandFlags flags)
   at Fusion.LmeFeedHandler.EndToEndTests.MessageBusTest.DoTest()
```
**Log Details**
```
localhost:6379,password=*****

Connecting localhost:6379/Interactive...
BeginConnect: localhost:6379
1 unique nodes specified
Requesting tie-break from localhost:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=32764,Min=4,Max=32767)
EndConnect: localhost:6379
Connected Interactive/localhost:6379
Server handshake
Setting client name: DESKTOP-36K2HOO
Auto-configure...
Sending critical tracer: Interactive/localhost:6379
Writing to Interactive/localhost:6379: ECHO
Flushing outbound buffer
Starting poll
Connect complete: localhost:6379
Response from Interactive/localhost:6379 / ECHO: BulkString: 16 bytes
Writing to Interactive/localhost:6379: GET __Booksleeve_TieBreak
Writing to Interactive/localhost:6379: PING
Response from Interactive/localhost:6379 / GET __Booksleeve_TieBreak: (null)
Response from Interactive/localhost:6379 / PING: SimpleString: PONG
All tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=4,Free=32763,Min=4,Max=32767)
localhost:6379 returned with success
All tasks are already complete
localhost:6379 had no tiebreaker set
Single master detected: localhost:6379
localhost:6379: Standalone v3.0.503, master; 16 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablishing
localhost:6379: int ops=12, qu=0, qs=0, qc=1, wr=0, sync=10, socks=1; sub ops=3, qu=0, qs=3, qc=0, wr=0, socks=1
Circular op-count snapshot; int: 0+12=12 (1.20 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Starting heartbeat...
```

**Comment by NickCraver** [comment]
@djagd I'm trying to puzzle what the issue was here - in the repro code it's creating and disposing connection multiplexers (which isn't the norm), but guessing you went to extremes to repro here. But! After upping the numbers I can re-create the issue. Taking a look now.

**Comment by mgravell** [comment]
Closing; please see: https://github.com/StackExchange/StackExchange.Redis/issues/871

**Comment by djagd** [comment]
@NickCraver sorry I just saw the message. Yes it is an extreme repo. The actual use case was very simple really - Connect to REDIS, subscribe on a topic, request another service to publish some data on that topic (request made via a different transport for unavoidable reasons).

**We have a couple of applications - I'll call them Client and RecoveryService**. The Client would request for some data to be streamed back from RecoveryService via a pre-configured topic.

1. Connect to redis via ConnectionMultiplexer
2. Make a subscription topic RedisSubscriber.Subscribe("RecoveryService/reply)" --> when this method returned we assumed that the subscription is completed.
3. Make a request using a different transport requesting for some data to be streamed back on "RecoveryService/reply" topic

**The observation was that we would intermittently miss some of the messages which we could workaround by putting a 100ms sleep between Connect and Subscribe**

Thanks for the fix.

**Comment by mgravell** [comment]
@djagd  for that use case, you might *also* want to look at the new "streams" feature in redis RC; we should be merging the PR for that very soon
