### ISSUE TITLE
Timeout performing EVAL - High QS

### ISSUE THREAD

**Issue by frg** [StackExchange/StackExchange.Redis#705]
Every few weeks or so during average traffic I've been getting a lot of timeouts with high qs. Usually the application would need a restart as it hangs on timeouts.

`Timeout performing EVAL, inst: 1, queue: 6760, qu: 0, qs: 6760, qc: 0, wr: 0, wq: 0, in: 0, ar: 0`

I've looking into similar issues, checked the docs but I haven't found any resource to help me identify what is causing this.

> The parameter “qs” in the error message tells you how many requests were sent from the client to the server, but have not yet processed a response.  This value keeps growing because StackExchange.Redis uses a single TCP connection and can only read one response at a time.  Even though the first operation timed out, it does not stop the data being sent to/from the server, and other requests are blocked until this is finished. Thereby, causing time outs. One solution is to minimize the chance of timeouts by ensuring that your cache is large enough for your workload and splitting large values into smaller chunks. Another possible solution is to use a pool of ConnectionMultiplexer objects in your client, and choose the "least loaded" ConnectionMultiplexer when sending a new request.  This should prevent a single timeout from causing other requests to also timeout.

This resource from the redis docs mentioned "One solution is to minimize the chance of timeouts by ensuring that your cache is large enough for your workload and splitting large values into smaller chunks". Which cache is this referring to?

I'm also trying to figure out what might cause the connection to totally hang on 1 response becoming unusable.

Also, I wasn't able to replicate this. Currently I've been only successful in replicating Timeouts with an ever increasing queue but not qs specifically. Does anyone know how I can go about replicating this behavior? 

Thanks for any help.

**Comment by NickCraver** [comment]
This was likely fixed in the 1.2.6 release (which also contains more debug information). I apologize for the backlog here, but are you still seeing this? If so, can you paste the exception from the latest version of the library? It'll contain more debug information.

**Comment by mgravell** [comment]
Closing; please see #871
