### ISSUE TITLE
Timeout performing GET Market:EPPlat

### ISSUE THREAD

**Issue by minminmsn** [StackExchange/StackExchange.Redis#709]
Hi,ALL

Server Environment:
Redis Cluser 3.2.9
StatckExchange.Redis1.2.0

Error Log:
Timeout performing GET Market:EPPlat:HomeInitDealerContractInfo:100026194, inst: 10, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: WIN-4SEUJG0RS2U, serverEndpoint: 172.17.6.74:7006, keyHashSlot: 12496, IOCP: (Busy=2,Free=798,Min=8,Max=800), WORKER: (Busy=13,Free=787,Min=8,Max=800) 

But Redis Cluster 3.0.7 is ok.  Is it not compatible?

**Comment by NickCraver** [comment]
@minminmsn There were a lot of fixes to cluster in subsequent releases, so I'm pretty sure this specific issue is done, but can you please poke here if still seeing this in latest (1.2.6+)? If you are, we'll re-open and look.
