### ISSUE TITLE
asp.net core stackexchange.redis timeout

### ISSUE THREAD

**Issue by 1amirjalai** [StackExchange/StackExchange.Redis#710]
i'm getting this error on  

stackexchange.redis1.2.6 and asp.net core 1.1.2 a lot
i'm using lazy connectionmultiplexer and have a dedicated machine for redis but still i see these errors and it would cause my web app to stop working 

any suggestion or help would be appreciated

`StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: EVAL; UnableToConnect on xxxxx:6379/Interactive, origin: ResetNonConnected, input-buffer: 0, outstanding: 7, last-read: 19s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablishing, last-heartbeat: never, last-mbeat: -1s ago, global: 0s ago ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on xxxxxx:6379/Interactive, origin: ResetNonConnected, input-buffer: 0, outstanding: 7, last-read: 19s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablishing, last-heartbeat: never, last-mbeat: -1s ago, global: 0s ago`

followed by this error

`StackExchange.Redis.RedisTimeoutException: performing HINCRBY view:count:ad, inst: 306, queue: 43, qu: 43, qs: 0, qc: 0, wr: 1, wq: 1, in: 0, ar: 0, clientName: WIN-xxxxxxx, serverEndpoint: xxxxxxxxx:6379, keyHashSlot: 2068`

**Comment by 1amirjalai** [comment]
**more detail**
it happens randomly for 2 or 3 minutes in a day twice or one time.

![capture](https://user-images.githubusercontent.com/2786675/30239445-20f7abbe-9572-11e7-9bb1-92ff8fd5b4de.PNG)

my connection

        private static Lazy<ConfigurationOptions> configOptions
           = new Lazy<ConfigurationOptions>(() =>
           {
                var configOptions = new ConfigurationOptions();
                configOptions.EndPoints.Add("xxxxxxx:6379");
                configOptions.SyncTimeout = 4000;
                configOptions.AbortOnConnectFail = false;
                return configOptions;
            });
        private static readonly Lazy<ConnectionMultiplexer> LazyConnection = new Lazy<ConnectionMultiplexer>(() =>
        {
            var connection = ConnectionMultiplexer.Connect(configOptions.Value);
            connection.PreserveAsyncOrder = false;
            return connection;
           
        });

        public static ConnectionMultiplexer SafeCoonect
        {
            get
            {
                return LazyConnection.Value;
            }
        }

**Comment by niemyjski** [comment]
@1amirjalai did you find the issue or a solution?

**Comment by MaharshiMCA** [comment]
As per the solution I have found, you should set property KeepAlive as per your application needs. I have resolved the same issue with we app by setting KeepAlive to 4.

**Comment by mgravell** [comment]
Please try the current pre-release alpha of .7

**Comment by middlewaysas** [comment]
@mgravell : I have the same issue while using the lib from an Azure function.
My function is reading data from an Azure redis cache and this function is called by an Azure Logic App. I can have multiple Azure Logic App instances running at a time and calling the function.
Sometimes I have this error "ResetNonConnected". I'm using the 1.2.6 version of the lib.
You are taling about the .7 alpha, where can I find it?

**Comment by MaharshiMCA** [comment]
I found that if we have lots of keys on the root directory on the redis database, then this issue occurs. I resolved this issue by storing keys in the namespace. Give it a try

**Comment by 1amirjalai** [comment]
@mgravell 

it's more than a week that we shipped our app with redis   version 1.2.7-alpha-00002. 
still i have frequent timeout error which causes our web app to crash  but i don't see this error in my error log any more.
I find these error in dump file 


> Timeout performing EVAL, inst: 2, queue: 1557, qu: 0, qs: 420, qc: 1137, wr: 0, wq: 0, in: 6398, ar: 0, clientName: WIN-1P43GE1NHA6, serverEndpoint
> --


 

>  StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[[System.__Canon, System.Private.CoreLib]](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor`1<System.__Canon>, StackExchange.Redis.ServerEndPoint)    StackExchange.Redis.RedisBase.ExecuteSync[[System.__Canon, System.Private.CoreLib]](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor`1<System.__Canon>, StackExchange.Redis.ServerEndPoint)    StackExchange.Redis.RedisDatabase.ScriptEvaluate(System.String, StackExchange.Redis.RedisKey[], StackExchange.Redis.RedisValue[], StackExchange.Redis.CommandFlags)    Microsoft.Extensions.Caching.Redis.RedisExtensions.HashMemberGet(StackExchange.Redis.IDatabase, System.String, System.String[])    Microsoft.Extensions.Caching.Redis.RedisCache.GetAndRefresh(System.String, Boolean)    Microsoft.Extensions.Caching.Redis.RedisCache.Get(System.String)    Microsoft.AspNetCore.Session.DistributedSession.Load()

**Comment by 1amirjalai** [comment]
@NickCraver now i have so many threads in server dump file :


> 0:029> !clrstack
> OS Thread Id: 0xa00 (29)
>         Child SP               IP Call Site
> 000000a664b3eec8 00007ffa2d956724 [HelperMethodFrame: 000000a664b3eec8] System.Threading.Thread.SleepInternal(Int32)
> 000000a664b3efd0 00007ffa0995419a System.Threading.Thread.Sleep(Int32)
> 000000a664b3f000 00007ff9ad1774be StackExchange.Redis.CompletionManager.ProcessAsyncCompletionQueueImpl()
> 000000a664b3f080 00007ffa0997b3ee System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
> 000000a664b3f0f0 00007ffa09a470e9 System.Threading.ThreadPoolWorkQueue.Dispatch()
> 000000a664b3f5f0 00007ffa0c6f35d3 [DebuggerU2MCatchHandlerFrame: 000000a664b3f5f0] 

![image](https://user-images.githubusercontent.com/2786675/37268309-6d7945b2-25da-11e8-87b3-d058130b9091.png)

**Comment by 1amirjalai** [comment]
@NickCraver  @mgravell  I went to 1.2.6 high memory usage issue get solved

**Comment by NickCraver** [comment]
@1amirjalai On this:
> now i have so many threads in server dump file

How many are we talking here? It's normal to see the completion threads in that state (waiting for data to process), but seeing a lot of them indicates another issue. Your timeout settings and server `SLOWLOG` would also be helpful. Given this is happening under specific ops and what appears to be decent load, this may be a server capacity/timeout issue overall.

**Comment by mgravell** [comment]
Closing; please see: https://github.com/StackExchange/StackExchange.Redis/issues/871
