### ISSUE TITLE
KeyExpireAsync executed before MULTI

### ISSUE THREAD

**Issue by ghost** [StackExchange/StackExchange.Redis#711]
Hi,

We use StackExchange.Redis 1.2.5 in a .NET 4.6 application running against Redis 3.2.100 on Windows

We issue the following commands:

```
CreateTransaction();
HashSetAsync(key, ...);
KeyExpireAsync(key, 3600);
Execute();
```

The KeyExpireAsync does not seem to work as expected

Using Redis DEBUG we see following trace:

```
EXPIRE
MULTI
HSET
EXEC
```

That happens at all of our installations

If we issue commands using cli, it works as expected

It seems to be a bug. Could anyone verify?

Thanks in advance

**Comment by NickCraver** [comment]
I'm trying to understand if this is abbreviated, are you calling the commands *on* the transaction? The transaction itself is not ambient, you'll need to call the methods on it directly. For example:
```c#
var db = conn.GetDatabase(0);
var t = db.CreateTransaction();
t.HashSetAsync(key, ...);
t.KeyExpireAsync(key, 3600);
t.Execute();
```

**Comment by mgravell** [comment]
Tested with @NickCraver's code;

```
        var db = conn.GetDatabase(0);
        var t = db.CreateTransaction();
        t.HashSetAsync(key, "foo", "bar");
        t.KeyExpireAsync(key, TimeSpan.FromSeconds(3600));
        t.Execute();
```

output is:

```
1530221943.821359 [0 127.0.0.1:58097] "MULTI"
1530221943.821398 [0 127.0.0.1:58097] "HSET" "abc" "foo" "bar"
1530221943.821426 [0 127.0.0.1:58097] "EXPIRE" "abc" "3600"
1530221943.821440 [0 127.0.0.1:58097] "EXEC"
```

I think you're calling `HashSetAsync` on the wrong object. If we're wrong, please : a repro would really help.

**Comment by DavidKlempfner** [comment]
> I'm trying to understand if this is abbreviated, are you calling the commands _on_ the transaction? The transaction itself is not ambient, you'll need to call the methods on it directly. For example:
> 
> ```cs
> var db = conn.GetDatabase(0);
> var t = db.CreateTransaction();
> t.HashSetAsync(key, ...);
> t.KeyExpireAsync(key, 3600);
> t.Execute();
> ```

Don't you need to `await` the call to `HashSetAsync()` etc?

**Comment by mgravell** [comment]
@DavidKlempfner not in this case; they are deferred until the Execute - although yes you could choose to await them *after* the execute to observe any results

**Comment by DavidKlempfner** [comment]
@mgravell We have this code inside a void Save method:
```
Task.Run(async () =>
{
    var transaction = cache.CreateTransaction();
    var _ = transaction.StringSetAsync(...);
    _ = transaction.SetAddAsync(...);
    _ = transaction.KeyExpireAsync(...);
    await transaction.ExecuteAsync();
}).Wait();
```

I was told the `SetAddAsync()` and `KeyExpireAsync()` don't need to be awaited, but I couldn't work out why, I thought there'd be  race condition, because those Tasks might still be running after await `transaction.ExecuteAsync()`

Is this the same situation as what you just mentioned? Ie. they also don't need to be `await`ed?

**Comment by mgravell** [comment]
The nature of MULTI/EXEC is that the queued commands are executed - and give their results - as part of the EXEC. Until `transaction.Execute` nothing has even been issued, and the results will all be set as part of processing the execute result.

The .Wait() here is bad, though - that's sync-over-async. If you want synchronous, that's fine - we have Execute() which is synchronous. No need to a task.run - Nick's example from May 2018 shows synchronous usage.

**Comment by DavidKlempfner** [comment]
@mgravell I'm trying to convince the devs that although it'll take a while to update all the method signatures, it's worth it to not block a thread, and could even save us money in Azure since it could prevent unnecessary scaling by having an extra thread available.

Is it bad to `await` `SetAddAsync()` and `KeyExpireAsync()`, or is it just that you don't need to do it?
