### ISSUE TITLE
RedisConnectionException exists in bot StrongName and Redis - core 2.0

### ISSUE THREAD

**Issue by petarvucetin** [StackExchange/StackExchange.Redis#713]
Hi,

Using .net core 2.0 web app I am getting ambiguous error when explicitly referencing the type:

1>ResourceAccess\Azure\AzureNavigationResourceAccess.cs(191,40,191,64): error CS0433: The type 'RedisConnectionException' exists in both 'StackExchange.Redis.StrongName, Version=1.2.4.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=1.2.6.0, Culture=neutral, PublicKeyToken=null'

            catch (StackExchange.Redis.RedisConnectionException e)
            {
                //Log
                
            }

What could be the solution to this problem?

**Comment by NickCraver** [comment]
Likely due to another library using StrongName (some of the Microsoft libraries do), you can simply remove the non-StrongName reference from your project. You only need 1 or the other, the code is identical.

**Comment by OpenSourceAries** [comment]
Refer to #697

**Comment by NickCraver** [comment]
Closing due to dupe and solution above.
