### ISSUE TITLE
Redis timeout

### ISSUE THREAD

**Issue by bipindas** [StackExchange/StackExchange.Redis#716]
Hello,

I keep getting timeouts on Redis. The message is below. in: 65536 and 120 items in the queue. Any ideas how to resolve this? The app is hosted on an Azure api app and calling a Azure Redis instance. Both are in the same region.

inst: 1, mgr: Inactive, err: never, queue: 120, qu: 0, qs: 120, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0, clientName: RD0004FFA37AA4, serverEndpoint: Unspecified/servername.redis.cache.windows.net:6380, keyHashSlot: 11524, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=21,Free=8170,Min=200,Max=8191).

**Comment by Skolzack** [comment]
I'm wih the same trouble.

StackExchange.Redis.RedisTimeoutException: Timeout performing GET USERORGANIZATIONS_D96510A4-A9A2-4DAA-84A9-BB77363DD3EA, inst: 9, mgr: ProcessReadQueue, err: never, queue: 24, qu: 0, qs: 24, qc: 0, wr: 1, wq: 1, in: 65536, ar: 1, clientName: RD00155D008B42, serverEndpoint: Unspecified/xxxxxxx.redis.cache.windows.net:xxxx, keyHashSlot: 9735, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=27,Free=32740,Min=200,Max=32767)

Any help?

**Comment by bipindas** [comment]
What I found was that Redis is not suitable for large objects/key. Each key can only store small objects. So I basically removed all my large objects & collections out of Redis.

**Comment by wags1999** [comment]
I also have a Production site using Microsoft.Web.RedisSessionStateProvider v2.2.2 and StackExchange.Redis v1.2.5, getting a very similar issue to what you posted:
Message: Timeout performing EVAL, inst: 1, mgr: RecordConnectionFailed_FailOutstanding, err: never, queue: 17044, qu: 0, qs: 17044, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0,

Based on this link, in represents the bytes available on the NIC, and I'm guessing ar represents the number of active readers. I believe in both our cases this means there's data on the NIC waiting to be read, but for some reason, StackExchange.Redis has zero readers - and so all requests timeout until the App Pool is restarted.

Might be the same as #657

**Comment by mootoools0123456789** [comment]
{"Timeout performing GET A10011093388, inst: 31, mgr: ProcessReadQueue,
 err: never, queue: 49, qu: 0, qs: 49, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0, clientName: SDWQ-PC, serverEndpoint: 192.168.47.131:6379, keyHashSlot: 7160, IOCP: (Busy=0,Free=400,Min=200,Max=400), 
 WORKER: (Busy=137,Free=263,Min=300,Max=400) (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)"}
I also have this problem,my value is 4kb, then I change the value 1kb, this problem become less.

**Comment by mootoools0123456789** [comment]
{"Timeout performing GET A10011093388, inst: 31, mgr: ProcessReadQueue,
 err: never, queue: 49, qu: 0, qs: 49, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0, clientName: SDWQ-PC, serverEndpoint: 192.168.47.131:6379, keyHashSlot: 7160, IOCP: (Busy=0,Free=400,Min=200,Max=400), 
 WORKER: (Busy=137,Free=263,Min=300,Max=400) (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)"}

I alse have this problem,My value is 4kb,then I change value to 1kb，the problem happen less!!

**Comment by kierenj** [comment]
If `in>0` and `ar=0`, it would seem to be the same as #650 ?

**Comment by mgravell** [comment]
Closing; please see #871

**Comment by PeyShine** [comment]
ConnMultiplexer_InternalError: System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: newSize
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Array.Resize[T](T[]& array, Int32 newSize)
   at StackExchange.Redis.PhysicalConnection.EnsureSpaceAndComputeBytesToRead() in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 874
   at StackExchange.Redis.PhysicalConnection.BeginReading() in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 717
   at StackExchange.Redis.PhysicalConnection.<>c__DisplayClass4_0.<EndReadFactory>b__0(Task`1 result) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 42
ConnMultiplexer_ConnectionFailed: StackExchange.Redis.RedisConnectionException: InternalFailure on cookiecache.nwajld.0001.use1.cache.amazonaws.com:6379/Interactive, origin: EndReadFactory, input-buffer: 1073741824, outstanding: 78, last-read: 0s ago, last-write: 0s ago, unanswered-write: 83524s ago, keep-alive: 600s, pending: 0, state: ConnectedEstablished, in: 5094067, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago ---> System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: newSize
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Array.Resize[T](T[]& array, Int32 newSize)
   at StackExchange.Redis.PhysicalConnection.EnsureSpaceAndComputeBytesToRead() in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 874
   at StackExchange.Redis.PhysicalConnection.BeginReading() in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 717
   at StackExchange.Redis.PhysicalConnection.<>c__DisplayClass4_0.<EndReadFactory>b__0(Task`1 result) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 42
   --- End of inner exception stack trace ---
ConnMultiplexer_ConnectionRestored:

**Comment by mgravell** [comment]
Another comment appeared and may have been deleted, but is in my inbox, talking about the array.resize in the back-buffer. That code literally doesn't exist in 2.0, so I'm automatically considering that additional comment (that doesn't show here): "already fixed"
