### ISSUE TITLE
Is 1.2.6 currently broken for .NET 4.5.2?

### ISSUE THREAD

**Issue by berniezhao** [StackExchange/StackExchange.Redis#717]
According the README 1.2.6 is currently not working with .NET 4.0
I'm wondering if it's fine to use it with 4.5.2?
I did a brief test and seems like it's writing values into my local test Redis server.
Any hint is appreciated, thx.

**Comment by NickCraver** [comment]
@berniezhao We still build for net452, so you're good there. The new tooling in VS 2017 for multi-targeting doesn't correctly support net40 and Microsoft hasn't supported it in some time...so we specifically dropped that build only. It's simply impractical to support it at this point.

**Comment by berniezhao** [comment]
Thanks @NickCraver for clarification!
