### ISSUE TITLE
How can i confirm if i was read from slave node and it's load balance automatically

### ISSUE THREAD

**Issue by hidavidpeng** [StackExchange/StackExchange.Redis#719]
[{"Nodes":[{"Master":"127.0.0.1:6371","Slave":"127.0.0.1:6372,127.0.0.1:6373","BeginSlot":"0","EndSlot":"10000"},{"Master":"127.0.0.1:6380","Slave":"127.0.0.1:6382,127.0.0.1:6383","BeginSlot":"0","EndSlot":"10000"}],"KeepAlive":"60","Patterns":["MessagePushQueue","BasicInfo","RedisLog"]}]

I had custom a redis Configuration by myself. and it's will find the key slot and select the right master for I have 2 master node, and 2 slave node per master node.  when i have a read command, How can i comfirm it's running on a slave node. 
Thank you for your help

**Comment by NickCraver** [comment]
You'd have to `MONITOR` ([docs](https://redis.io/commands/monitor)) that node to confirm directly, we don't expose that information outside the pipe at the moment due to complexities of retries, etc. the logging would not be simple or consistent.
