### ISSUE TITLE
key.Exists return true for expired key

### ISSUE THREAD

**Issue by elutsky** [StackExchange/StackExchange.Redis#72]
May be I missed something general, and I am sorry for that.
But in my tests, when I check expired key (hash) for exists, it returns true:

here "cache" is IDatabase instance

``` C#
// This will return true
var exists = cache.KeyExists(key);
// This will return null
var ttl = cache.KeyTimeToLive(key);
// This will return null
var fullWait = cache.HashGetAsync(key, "full", flags: CommandFlags.None);
```

Also, set with When.NotExists will work:

``` C#
cache.HashSetAsync(key, "full", value, When.NotExists, CommandFlags.PreferMaster);
```

**Comment by NickCraver** [comment]
It looks like you're dealing with a hash that has no expiration and setting a key *on the hash* that doesn't exist - is that right? Given you have a non-expiring hash without that key, the behavior would be correct. The expiration you're dealing with here is of the entire hash, not specific keys on the hash...so depending on the setup your code and results may be correct.

Can you provide a bit more info on the state of things?
