### ISSUE TITLE
Question: NRediSearch Dependency on StackExchange.Redis

### ISSUE THREAD

**Issue by nreddipalle** [StackExchange/StackExchange.Redis#720]
I created my own class to make it work with RediSearch. I do use StackExchange.Redis.StrongName till now. 
Planning to use NRediSearch but looks like it has dependency on StackExchange.Redis and I am getting exceptions like 
![image](https://user-images.githubusercontent.com/28302399/30920773-d14955ae-a372-11e7-9686-49747a0bc1f3.png)
I cannot remove dependency on StackExchange.Redis.StrongName which could need lot of changes in other classes. Please do suggest how to work around this... 

Thanks.

**Comment by NickCraver** [comment]
TL;DR: We need to remove the .StrongName library and strong name the base library in 2.0 to eliminate situations like this. We need to find the time for 2.0 ASAP, and I think pipelines will be the trigger to button down and do the work.

**Comment by mgravell** [comment]
Closing - see https://github.com/StackExchange/StackExchange.Redis/issues/871 - the changes in 2.0 change this landscape
