### ISSUE TITLE
Question: Use TLS + pre shared Key for authentication

### ISSUE THREAD

**Issue by desaiamogh** [StackExchange/StackExchange.Redis#722]
Is it possible to use This client with TLS and Pre-shared key based authentication ??  

We want to connect to Redis behind an Stunnel but want to avoid using a certifcate as the enironment is on AWS beanstalk and installing certificates on PaaS is complex.

Below is the web.config setup just for reference.

    <sessionState mode="Custom" customProvider="SessionStateStore">
      <providers>
        <add name="SessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="remotehost" applicationName="app" databaseId="0" accessKey="" ssl="false" />
      </providers>
    </sessionState>

**Comment by NickCraver** [comment]
As far as I know, this isn't possible with current infrastructure, you'd be bolting some other bits of pipe onto this. That being said, once we rewrite to use Pipelines coming to .NET soon, such extensibility would be far more practical to achieve.

**Comment by NickCraver** [comment]
Closing this out due to inactivity/no further questions.
