### ISSUE TITLE
ASP.NET Core Redis Session Delay for SetString

### ISSUE THREAD

**Issue by jaimebennett** [StackExchange/StackExchange.Redis#725]
I'm using Redis on Azure to store Session State and Data Protection Keys.

**Startup.cs includes:**
```c#
services.AddDistributedMemoryCache();
services.AddSession(options =>
{
   options.IdleTimeout = TimeSpan.FromMinutes(30);
   options.CookieName = ".appcookie";
});
var redis = ConnectionMultiplexer.Connect(Configuration.GetConnectionString("Redis"));
services.AddSingleton(options => redis.GetDatabase());
services.AddDataProtection().PersistKeysToRedis(redis, "DataProtection-Keys");
services.AddDistributedRedisCache(options =>
{
   options.Configuration = Configuration.GetConnectionString("Redis");
   options.InstanceName = "redis";
});
```
Controller contains:
```c#
private readonly IHttpContextAccessor _context;
private ISession _session => _context.HttpContext.Session;
```

I call two functions from controller immediately after one another.  
Function 1 contains:
```c#
_session.SetString("header_row", header_row);
var val = _session.GetString("header_row");
```

Function 2 contains:
```c#
var val2 = _session.GetString("header_row");
```

In this scenario, when header_row is set to "1", val has a value of "1", but val2 has a value of "".
If I run functions again setting header_row to "2", val has a value of "2", but val2 has a value of "1".

If I debug the code, and use redis console, I see that the keys are not updated right away (takes about 3 seconds to update).  So, how do I await the _session.SetString?

**Comment by NickCraver** [comment]
This seems to be an issue with the provider, where `SetString` is using a LUA script and setting asynchronously under the covers which isn't awaited (I guess it doesn't normally need to be?) and the next call doesn't know about it.

Regardless, I recommend filing this in the [aspnet/Caching](https://github.com/aspnet/Caching/) repo, as the behavior would need to be changed there, if warranted. I honestly don't know enough about the motivations to say what *should* happen there, but the issue you're hitting is one layer above our library, in that caching layer/behavior :)
