### ISSUE TITLE
NadekoBot.exe has stopped working?

### ISSUE THREAD

**Issue by Scipio674** [StackExchange/StackExchange.Redis#726]
So I had my Nadeko bot on ver 1.8.1-1.8.2 something in there. Then I tried to use it and nothing happened. All I got was this big error message saying 
![image](https://user-images.githubusercontent.com/32799170/31577323-011ddc2a-b0d2-11e7-98f6-3a068808062e.png)

What do I do?

**Comment by kierenj** [comment]
You'll want to talk to NadekoBot - https://github.com/Kwoth/NadekoBot .  The error just says it can't connect to Redis.

**Comment by Scipio674** [comment]
I got it by uninstalling then reinstalling, I realized the problem after was that I had updated and didn't have something that I could of gotten easily. Thank you though

**Comment by NickCraver** [comment]
Closing this out as it seems to be a one-off install error (likely redis not started?)
