### ISSUE TITLE
Timeout performing GET with barely any traffic

### ISSUE THREAD

**Issue by dexterdauz** [StackExchange/StackExchange.Redis#727]
We're on version 1.2.6 and I get the following exception once in a while with barely any traffic happening. Any ideas why this might be happening?

StackExchange.Redis.RedisTimeoutException: Timeout performing GET state:eDog_78e53cd29620b519ca79a5724af9b984_eb138edd-b05f-46f4-a914-da0d4c940035, inst: 1, mgr: Inactive, err: never, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: NotificationService_IN_1, serverEndpoint: Unspecified/test.redis.cache.windows.net:xxx, keyHashSlot: 14525, IOCP: (Busy=0,Free=400,Min=200,Max=400), WORKER: (Busy=1,Free=399,Min=200,Max=400)

BTW, my SyncTimeout and ConnectionTimeout are both set to 10 secs which should be more than sufficient.

**Comment by NickCraver** [comment]
Are you connecting to the endpoint `test.redis.cache.windows.net`, or is that a replacement?

**Comment by mgravell** [comment]
Closing; please see #871
