### ISSUE TITLE
StackExchange.Redis not sending uniform read traffic to all replicas

### ISSUE THREAD

**Issue by mohitkumarr** [StackExchange/StackExchange.Redis#728]
StackExchange.Redis not sending uniform read traffic to all replicas. We have 3 read replicas.We see around 67% of the traffic to one redis replica and 33% to the other two read replicas. 

![image](https://user-images.githubusercontent.com/32914233/31743831-701d1b9e-b411-11e7-9c80-e54d93bb1139.png)

**Comment by bryancusatis** [comment]
Are you in cluster mode? We are seeing the same issue where all of our read traffic hits one node in the cluster.

**Comment by mohitkumarr** [comment]
No, we are not on clustered mode.

**Comment by NickCraver** [comment]
The library, by default prefers the first slave (as it has the least latency), so this would be by-design. If you want to add a feature request for load sharding on the same-child-level replicas that sounds reasonable, but isn't necessarily a trivial addition.
