### ISSUE TITLE
PhysicalBridge in a weird state in high load which causes command never finish 

### ISSUE THREAD

**Issue by cppcraze** [StackExchange/StackExchange.Redis#730]
I am still using an old version of StackExchange.Redis library, see below snapshot:
![image](https://user-images.githubusercontent.com/5673860/31874278-3d5668e0-b77d-11e7-8356-cfba5ecc823b.png)

Recently I hit a hung issue under high load. So I sent too many SISMEMBER commands. The socket closed unexpectedly, might be because of the high load or server has some temporary issue. I found too many exception object in my dump file (error: no physical connection). But what is weird is PhysicalBridge (interactive one) is in below state (I saw in the dump)

failConnectCount is 1
physical is null
state is still 2 (ConnectionEstablished) 

because of state is still 2, PhysicalBridge.TryEnqueue will still push message to its message queue, but SocketManager's writeAllQueue thread waits for its writequeue (won't have any new bridge coming in) and its WriteOneQueue function also gone. So in this situation, if there is still new command coming in, it will just get inserted into PhysicalBridge's message queue but will never finish, hence the hung.

But after looking at latest code, I doubt the issue might still exist. Any idea why PhysicalBridge will enter above state?

**Comment by NickCraver** [comment]
We fixed a lot of issues here through 1.2.6, can you please ping me if still hitting this? I'm fairly sure this issue is resolved in latest, or at the very lease you'll get a much more informative error. Just closing these issues out to clean up - sorry we're behind on duplicates.
