### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException: Timeout performing HMSET

### ISSUE THREAD

**Issue by chenhuiguo** [StackExchange/StackExchange.Redis#732]
We're on version 1.2.6 and I get the following exception once in a while with barely any traffic happening. ConnectionMultiplexer use the default configuration and the data is written in redis successfully ,but why i get this exception? Any ideas,thanks a lot

tackExchange.Redis.RedisTimeoutException: Timeout performing HMSET test:Role:1018, inst: 1, mgr: ExecuteSelect, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: CHENHUIGUO, serverEndpoint: 192.168.2.31:6379, keyHashSlot: 8161, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767)

**Comment by richardlnnr** [comment]
I have the same problem.

**Comment by willhuo** [comment]
I also come across the same problem as flowing:

StackExchange.Redis.RedisTimeoutException: Timeout performing SET 0001000100001031, inst: 1, mgr: ExecuteSelect, err: never, queue: 2, qu: 2, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: iZso3wjl76eu61Z, serverEndpoint: 127.0.0.1:6379, keyHashSlot: 4725, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by mgravell** [comment]
Closing; please see #871
