### ISSUE TITLE
Can't restore packages in VS 2017

### ISSUE THREAD

**Issue by cmoncure** [StackExchange/StackExchange.Redis#734]
Trying to build StackExchange.Redis from git to follow up with my previous issue, but VS won't restore the NuGet packages, complaining as follows:

`Update-Package : Invalid restore input. Invalid target framework 'unsupported'. Input files: C:\Users\corey\Desktop\StackExchange.Redis\StackExchange.Redis.StrongName\StackExchange.Redis.StrongName.csproj.`

I tried changing <LibraryTargetFrameworks> in Directory.build.props to just net45;net46 but to no avail.  Also tried manually overriding in the csproj.

I'm giving up.

**Comment by NickCraver** [comment]
Which version of Visual Studio are you using?

**Comment by NickCraver** [comment]
No updated info here - if there's another question of example I'm happy to help, but can't give any further assistance based on current info.
