### ISSUE TITLE
How to split the Data in IEnumerable query[Linq]

### ISSUE THREAD

**Issue by Moinuddin147** [StackExchange/StackExchange.Redis#739]
Hi,
i am working in web application in that i am filling the gridview data from sqlserver but in that there is one column name "Column1" having data like "Name=abcd|Color=255,255,255,Align=Center"
can i split as below:
Gridview Column
column1     column2                column3
abcd             255,255,255           center
can is this possible?

**Comment by NickCraver** [comment]
This doesn't appear to be a redis question - what is being asked here? Are you just generally trying to split data based on multiple different delimiters? The comma here seems to be a delimiter *sometimes* and not in others, e.g. the first 2 commas aren't but the third one is. You'll find this to create a lot of brittleness and depend upon assumptions. I'd recommend changing your data format, and if redis related, not storing it as a string but instead protobuf or similar.
