### ISSUE TITLE
Unable to use StackExchange.Redis_Net40 library in project targeting framework 4.0

### ISSUE THREAD

**Issue by nandakishorvh** [StackExchange/StackExchange.Redis#74]
Hello everyone 

When i reference StackExchange.Redis_Net40 in a new project which is targeting to 4.0 framework i get these following errors

"The type or namespace name 'StackExchange' could not be found (are you missing a using directive or an assembly reference?)"   

and same error for ConnectionMultiplexer and IDatabase as well.

Please help

**Comment by Award4444** [comment]
I'm having the exact same problem - I used the install-package StackExchange.Redis command, got the exact output as described above, but I get a compile error on the "Using StackExchange,Redis" line. The references to StackExchange.Redis are there, as well as references to the Microsoft.Bcl dependencies. 

I'm in VS 2013 targeting .NET 4.0 framework. Intellisense recognizes StackExchange - ie: if I type in "StackExchange." it recognizes "Redis" and "Redis." recognizes the list under that, including ConnectionMultiplexer - but cannot compile "The type or namespace name 'StackExchange' could not be found (are you missing a using directive or an assembly reference?)"  Qualifying the complete object does not work either - "StackExchange.Redis.ConnectionMultiplexer"  - same error.

Help

**Comment by MichaCo** [comment]
Update the `Microsoft.Bcl` NuGet to version 1.1.10 manually should fix it.

**Comment by Award4444** [comment]
Thank You! That did the trick.

**Comment by NickCraver** [comment]
@nandakishorvh @Award4444 @slimjack Are you having this issue with current references, or all set on latest? Just following up on old issues here.
