### ISSUE TITLE
How to use "execute" properly

### ISSUE THREAD

**Issue by amphiware-alex** [StackExchange/StackExchange.Redis#740]
I set up the redis-stream on one of my testing machine, and i would like to use stackexchange.redis to issue xadd, xread and xrange command, but i couldn't make it work. ( always get wrong number of argument error )

the command that i would like to execute:
1) xadd otherstream * message "hi there" 
2) xrange otherstream 1510955900369-0 1510955900369-0

thanks,
Alex

**Comment by mgravell** [comment]
NRediSearch is a good example for this:
https://github.com/StackExchange/StackExchange.Redis/blob/master/NRediSearch/Client.cs

It should just be an array of the parameters, making sure to use RedisKey
where appropriate (for sharding)

Marc

**Comment by amphiware-alex** [comment]
Thanks ! got it to work
