### ISSUE TITLE
StackExcchange.Redis.dll dependency is incorrectly optimized

### ISSUE THREAD

**Issue by steavy29** [StackExchange/StackExchange.Redis#745]
Hi. I have two projects in my solution: `ProjectA` and `ProjectB`. 
`ProjectA` references `ProjectB`.
`ProjectB` references three packages:
StackExchange.Redis
StackExchange.Redis.Extensions.Core
StackExchange.Redis.Extensions.Newtonsoft

In code of `ProjectB` I use only types from `Extensions.Core` and `Extensions.Newtonsoft`. So `StackExchange.Redis` is not used directly. When I build my solution, msbuild optimizes references and doesn't include `StackExcchange.Redis.dll` in the output. But then I get errors in run-time saying that "namespace StackExcchange.Redis can not be found".
I suspect that extension libraries use "StackExcchange.Redis" namespace internally and that's why I get the error. Since I can't disable optimizations for my build, how do I reference packages correctly?

This problem reproduces for version 1.2.6 and I think this #649 might be related.

As a workaround I could add package `StackExcchange.Redis` to my main `ProjectA` but it doesn't seem to be the best solution since it doesn't need it directly and this would mean that I should do this for all projects that might reference `ProjectB`.

**Comment by NickCraver** [comment]
I'm honestly not sure what's happening here, but it appears to be a project system issue or an issue with those libs (though I don't see anything wrong when checking out their packages, at least on the current version).

Are you still seeing this? If so I really need to see the project to debug, or I recommend filing on the MSBuild side (or [the `StackExchange.Redis.Extensions` repo](https://github.com/imperugo/StackExchange.Redis.Extensions)). I did a bit of searching, but I can't find anyone else with this issue - I bet it's something messed up in your specific project file, but if you can share that I'm happy to take a peek.

**Comment by mgravell** [comment]
This sounds like a build tooling issue; I don't think we can do anything here. Note that recent build tools have greatly improved transitive reference support, so updating your build tools may be a good option. But: ... I don't think there's anything we can do to help here! It isn't us that is doing it...
