### ISSUE TITLE
db.StringIncrement(key)

### ISSUE THREAD

**Issue by kingreatwill** [StackExchange/StackExchange.Redis#750]
No connection is available to service this operation: INCR SEQ:OrderId:2017_3_29; 
SocketClosed on 172.19.4.59:6379/Interactive, origin: ProcessReadBytes, input-buffer: 0, outstanding: 1, last-read: 60s ago, last-write: 60s ago, 
unanswered-write: 0s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 1, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: ProcessReadQueue, 
err: never; IOCP: (Busy=1,Free=999,Min=8,Max=1000), 
WORKER: (Busy=0,Free=32767,Min=8,Max=32767), Local-CPU: unavailable

**Comment by kingreatwill** [comment]
The application pool is all recovered then it OK.

**Comment by kingreatwill** [comment]
![image](https://user-images.githubusercontent.com/13087689/33749646-d601dbdc-dc09-11e7-9366-a210fd64211d.png)

**Comment by NickCraver** [comment]
Are you seeing this in latest? Given the error message it looks like either a completely pegged CPU, or an `async` deadlock (e.g. via  a `.Result` or `.GetAwaiter().GetResult()` elsewhere) locking up the works. It's also possible with a 60s last read, your reader thread has just utterly died. That could happen between 1.2.1 and 1.2.5, but was resolved in all known cases are of 1.2.6. Are you still seeing this after upgrading to 1.2.6 or higher?

**Comment by mgravell** [comment]
Closing; please see: https://github.com/StackExchange/StackExchange.Redis/issues/871
