### ISSUE TITLE
Redis cluster  Timeout performing EVAL

### ISSUE THREAD

**Issue by szh222212** [StackExchange/StackExchange.Redis#756]
My problem is :
Timeout performing EVAL, inst: 185, mgr: ExecuteSelect, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: ***, serverEndpoint: ***, keyHashSlot: 5549, IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=148,Free=32619,Min=600,Max=32767), Local-CPU: unavailable (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)
The StackExchange.Redis  version is 1.2.6.0
I had set the ThreadPool in file global.asax.cs
ThreadPool.SetMinThreads(600, 50);
But  still has the problem.
Im troubled in this problem for a long time. 
Can anyone help me?  Thanks a lot!

**Comment by NickCraver** [comment]
It seems that you're saturating the threadpool in a spike with that many active. Are you using `.Result` or `.GetAwaiter().GetResult()` anywhere in your code? This deadlock-causing interaction will cause timeouts in the async layer in general.

**Comment by mgravell** [comment]
Closing; please see: https://github.com/StackExchange/StackExchange.Redis/issues/871
