### ISSUE TITLE
Implement Master Slave connection of redis in C#

### ISSUE THREAD

**Issue by Moinuddin147** [StackExchange/StackExchange.Redis#757]
How to implement master slave connection of redis is done in c#?
is there any solution for that?

**Comment by NickCraver** [comment]
@Moinuddin147 to issue a command to a replica/slave, connect to both in the multiplexer (or just the slave if that's all you need) and set the `CommandFlags`.

Here's an example :)
```c#
var conn = ConnectionMultiplexer.Connect("localhost:6379,localhost:6380");
var db = conn.GetDatabase(0);
var stringFromReplica = db.StringGet("xxx", CommandFlags.PreferSlave);
```
