### ISSUE TITLE
Parallel Timeout Program

### ISSUE THREAD

**Issue by shaddockblack** [StackExchange/StackExchange.Redis#758]
I Want to Know When Parallel Timeout Program will be Resolved
LIKE
static void Main(string[] args)
{
      Parallel.For(0, 100, (i) =>
      {
               Console.WriteLine($"{i}：{ConnectionMultiplexer.Connect("connectionString").GetDatabase(0).StringGet("xxx")}");
            });
            Console.ReadLine();
 }

this Code in NetCore will cause timeout 
but will not in NetFramework 
also can see in https://github.com/StackExchange/StackExchange.Redis/issues/678

so i want to know Is there a plan to repair this bug

**Comment by NickCraver** [comment]
@shaddockblack This usage pattern isn't correct, so it isn't a bug to solve. The connection multiplexer is meant to be long-lived and re-used. Connecting for every command is both very inefficient and exhausting (on ports).

Instead, your program should look something like this (though database 0 is the default and that part is extra):
```c#
var conn = ConnectionMultiplexer.Connect("localhost");
var db = conn.GetDatabase(0);
Parallel.For(0, 100, (i) =>
{
	Console.WriteLine($"{i}：{db.StringGet("xxx")}");
});
```

**Comment by Caskia** [comment]
@NickCraver  Did you tested the code which you pasted? It's still timeout.
