### ISSUE TITLE
getting stackexchange.redis working with mono

### ISSUE THREAD

**Issue by raistlinthewiz** [StackExchange/StackExchange.Redis#76]
Following #20.

my system is ubuntu 14.04 and i can use redis-cli to access it.

my mono version;
```
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

using nuget package: http://www.nuget.org/packages/StackExchange.Redis/
my debug log output when i try to connect 127.0.0.1:6379

```
Storage initialization failed: 127.0.0.1:6379 - 
 127.0.0.1:6379,allowAdmin=True,resolveDns=True

Using DNS to resolve '127.0.0.1'...
'127.0.0.1' => 127.0.0.1
1 unique nodes specified
Requesting tie-break from 127.0.0.1:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
127.0.0.1:6379 did not respond
127.0.0.1:6379 failed to nominate (WaitingForActivation)
No masters detected
127.0.0.1:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Connecting; sub: Connecting; not in use: DidNotRespond
127.0.0.1:6379: int ops=0, qu=2, qs=0, qc=0, wr=0, socks=1; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=1
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 2...
1 unique nodes specified
Requesting tie-break from 127.0.0.1:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
127.0.0.1:6379 did not respond
127.0.0.1:6379 failed to nominate (WaitingForActivation)
No masters detected
127.0.0.1:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Connecting; sub: Connecting; not in use: DidNotRespond
127.0.0.1:6379: int ops=0, qu=2, qs=0, qc=0, wr=0, async=3, socks=3; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=2
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 1...
1 unique nodes specified
Requesting tie-break from 127.0.0.1:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
127.0.0.1:6379 did not respond
127.0.0.1:6379 failed to nominate (WaitingForActivation)
No masters detected
127.0.0.1:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Connecting; sub: Connecting; not in use: DidNotRespond
127.0.0.1:6379: int ops=0, qu=2, qs=0, qc=0, wr=0, async=6, socks=4; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=3
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
```

**Comment by imuni4fun** [comment]
I have had the same experience as raistlinthewiz on CentOS 7, but without it ever succeeding at making the initial connection.  I ran MoMA (Mono Migration Analyzer) to check it StackExchange.Redis.dll against Mono version 2.8 (the newest MoMA target) and there are a few issues.

![image](https://cloud.githubusercontent.com/assets/10641399/5846248/4c465fb4-a190-11e4-96fa-db6fcae74dd6.png)

![image](https://cloud.githubusercontent.com/assets/10641399/5846258/59520794-a190-11e4-9edd-eb6f332e8724.png)

Anyone know if there is a plan to migrate this Redis library to be Mono-friendly??  For my application, it would be far less work to just not use Redis instead of spinning up on this client's implementation.

**Comment by raistlinthewiz** [comment]
give a try to; https://github.com/ctstone/csredis

I've submitted patches to it to make mono-compatible.

**Comment by imuni4fun** [comment]
I just caught my own fumble.

I was looking into this earlier this/last week among other things and I had been still referencing the non-mono DLL after building with the monobuild.bash option.  It’s looking good at the moment.  MoMA still raises (less severe) issues, but I can connect and interact with the Redis server now.  I will take a look at your suggestion if I run into any issues.

Best wishes,
Jason

![image](https://cloud.githubusercontent.com/assets/10641399/5847136/dd25740a-a197-11e4-8c1b-7af8b00941d1.png)

![image](https://cloud.githubusercontent.com/assets/10641399/5847138/e4bac616-a197-11e4-85bb-e11d36d9b307.png)

**Comment by mgravell** [comment]
That sounds better! I was indeed confused by the P/Invoke - was sure that
was in .net only via a #if

**Comment by NickCraver** [comment]
Hmmm, those IConvertible issues may be related to #152

**Comment by NickCraver** [comment]
Closing this out t consolidate. We're aiming for same-assembly Mono support via #314
