### ISSUE TITLE
RedisResult: make publicly available inner value

### ISSUE THREAD

**Issue by gzannerini** [StackExchange/StackExchange.Redis#764]
Hi, posted here: 
[https://stackoverflow.com/questions/48079957/redis-stackexchange-keys-vs-implementation-via-scan-usage-of-redisresult]()
a question regarding usage of Execute() method and RedisResult class. 
Problem is that inner result is non accessible. 
Is it possible to make it publicly available? How "risky" is to bypass StackExchange.Redis library and interact with Redis via explicit commands?

Thanks, 
Gabriele

**Comment by mgravell** [comment]
Just cast:

    RedisResult result = ...
    var lines = (RedisResult[])result;

**Comment by gzannerini** [comment]
Thanks for answer! Is not intuitive, but works.
Below code in bold font.

                RedisResult redisResult = cacheClient.Database.Execute("SCAN", new object[] { nextCursor.ToString(), "MATCH", "pdr:*", "COUNT", "1000" });
                **var innerResult = (RedisResult[])redisResult;
                nextCursor = int.Parse((string)innerResult[0]);
                List<string> resultLines = ((string[])innerResult[1]).ToList();**

Can close this issue.
Regards, Gabriele
