### ISSUE TITLE
Question: Get multiple hash keys

### ISSUE THREAD

**Issue by aberbegall** [StackExchange/StackExchange.Redis#765]
Having the following hash entries

```
myHash:1 
                  fieldA:valueA
                  fieldB:valueAA
myHash:2
                  fieldA:valueB
                  fieldB:valueBB
myHash:3
                  fieldA:valueC
                  fieldB:valueCC
```

What is the best/efficient way to retrieve all keys matching `myHash` and each fields and values?

Should I use `HashScan()` and then `HashGetAllAsync()` for each `HashEntry`?
If yes, what arguments should I pass to the `HashScan()` method?

Would it be better to keep each of `myHash:#` in a separated SET collection and get all its members to avoid `HashScan()` call?

**Comment by mgravell** [comment]
There is literally no good way to get all keys matching a pattern. The KEYS
and SCAN commands should not be used routinely - they are mainly intended
for tools like database analysis sets.

Usually, your best bet would be to put the *keys* of the hashes: in a set.
Then you can iterated that outer set. There is also a way to use the SORT
command to perform joins via key patterns, but I don't know whether this
supports hashes.

**Comment by aberbegall** [comment]
@mgravell I will go with the Set solution as you suggested.
Thanks for your quick reply
