### ISSUE TITLE
System.TimeoutException: Timeout performing EVAL

### ISSUE THREAD

**Issue by livesoftware** [StackExchange/StackExchange.Redis#77]
Using redis-2.8 for session state server in production.  First day running.  Ran into this exception.  Any way to alter the config to fix this?  Thanks
![error](https://cloud.githubusercontent.com/assets/6326647/3841717/dec9aca4-1e2f-11e4-899e-a59095c15dd4.PNG)

**Comment by NickCraver** [comment]
Did you have very low timeouts in a higher-latency environment perhaps? This looks like an actual timeout getting bytes to and from redis. I'll close this out due to being extremely old and the defaults in play have changed - but if you want to take another look I'll gladly reopen.
