### ISSUE TITLE
Overload with "When" parameter not available in HashSet, for multiple fields update

### ISSUE THREAD

**Issue by siva538** [StackExchange/StackExchange.Redis#779]
Hello Team.

Wanted to submit this request to enhance the HashSet Method, to include the "When" parameter, for StackExchange.Redis, to update multiple fields in one go based on the availability of the main key.

As-Is:
------
void HashSet(RedisKey key, HashEntry[] hashFields, CommandFlags flags = CommandFlags.None);

To-Be:
-------
void HashSet(RedisKey key, HashEntry[] hashFields, When when = When.Always, CommandFlags flags = CommandFlags.None);

Thanks in advance. 

Use-Case:

During the time of update, we wanted to update a set of fields in the Hash Key only when that already exists.

There is another overload available to update individual elements one by one. i.e. HashKey field and HashKey value. 

As on today, we are relying on the usage of Lua script to accomplish this as there is a set of fields that are required to be updated based on the availability of another key. 
We wanted to avoid the usage of Lua script and depend on the lighter version of the methods of StackExchange.Redis.

**Comment by mgravell** [comment]
Ultimately, StackExchange.Redis provides an API surface that mirrors the redis API. There are no flags on `HMSET` that would allow this. In redis terms, you're looking for a `XX` flag (`XX` means "only set if exists"), but: that isn't a feature that `HMSET` or `HSET` offer. So: we can't offer this option in the client, sorry.
