### ISSUE TITLE
Anyone implmented StackExchange.Redis as an Nhibernate Second Level Cache?

### ISSUE THREAD

**Issue by Tazer** [StackExchange/StackExchange.Redis#78]
Hello,

I have been looking for an implementation with StackExchange.Redis for Nhibernate Second Level Cache Provider. 

This would be awesome , cause at the moment there is only an ServiceStack.Redis implementation.
Anyone done this or planning todo? :hamster:

**Comment by jamesmanning** [comment]
Just FYI for anyone else running across this: that project switched from servicestack to stackexchange in its 2.0.0 version, so there's no stackexchange-redis branch anymore, you can just use master

https://github.com/TheCloudlessSky/NHibernate.Caches.Redis

    Switch the Redis library to StackExchange.Redis because of licensing changes with ServiceStack.Redis
