### ISSUE TITLE
op_Implicit RedisValue -> string is a pit of perf failure

### ISSUE THREAD

**Issue by TimLovellSmith** [StackExchange/StackExchange.Redis#780]
Today I saw a discussion around a performance bug in an app that was calling redis. The app was wasting a lot of CPU because it was doing this:

```
if (String.IsNullOrEmpty(rv)) { /*stuff */}
```

where rv is a RedisValue. This has the unfortunate effect of compiling in a call to op_Implicit to convert the redis value to a string, but then discarding the string value so created after verifying its not null.

Proposed approach:
Mark string implicit conversion as deprecated, and allow only for either explicit conversion, or using a method named AsString() to achieve that effect.

**Comment by mgravell** [comment]
Storing strings in redis is such a key scenario that I don't think this is
reasonable.

Things I would consider: custom string equality operator - it wouldn't help
in this exact scenario, though.

**Comment by NickCraver** [comment]
I'm going to close this one out - 100% agree this is a huge breaking change *most* people wouldn't want. But ignore the latter, it's still just a huge breaking change.

**Comment by TimLovellSmith** [comment]
Reopening - can you take it for 2.0?

**Comment by mgravell** [comment]
I think the absolute *most* I would consider here would be changing the `implicit` to an `explicit`, and even that is a huge breaking change that I think is very undesirable. I wonder if this is something better addressed through documentation? But it
