### ISSUE TITLE
Performance comparison Sync vs Async vs GetAwaiter 

### ISSUE THREAD

**Issue by mbpnet** [StackExchange/StackExchange.Redis#782]
Hi,

I am trying to capture performance matrix for Sync, Async and GetAwaiter with example of StringGet operation. Below is the code snippet and some results with different degreeofparallelism. 

- Does Sync call (StringGet operation) take care of connection failure/reconnect for multiplexer internally? 

- Does Sync call blocks other threads/connection call(s) to redis?

- Can anyone suggest which should NOT be used?

**Result** : 
        (With loop count - 3000, dop - 500)
        Hello Test! 
        Time For Sync 0.1524503.
        Time For Awaiter 0.6282039.
        Time For Async 0.6829395.
        Time For Sync 0.1524503 vs Awaiter 0.6282039 vs Async 0.6829395
       
(With loop count - 100, dop - 50)
        Hello Test!
        Time For Sync 0.0395311.
        Time For Awaiter 0.0918122.
        Time For Async 0.0394098.
        Time For Sync 0.0395311 vs Awaiter 0.0918122 vs Async 0.0394098

        using System;
        using System.Diagnostics;
        using System.Linq;
        using System.Threading.Tasks;
        using StackExchange.Redis;

        namespace RedisCacheConsole
        {
        	class Program
        	{
        		private static IDatabase _redis;
        		private static int loopCount = 3000;
        		private static int dop = 500;

		static Program()
		{
			_redis = ConnectionMultiplexer.Connect("localhost:6379").GetDatabase();
		}

		static void RunAwaiter()
		{
			Enumerable.Range(0, loopCount).ToList().AsParallel()
				.WithDegreeOfParallelism(dop)
				.ForAll(a =>
				{
					var watch = Stopwatch.StartNew();
					watch.Reset();
					var getResult = _redis.StringGetAsync("testkey").GetAwaiter().GetResult();
					if (watch.ElapsedMilliseconds > 0) { Console.WriteLine("RunAwaiter : " + a + " took " + watch.ElapsedMilliseconds); }
				});
		}

		static void Runsync()
		{
			Enumerable.Range(0, loopCount).ToList().AsParallel()
				.WithDegreeOfParallelism(dop)
				.ForAll(a =>
				{
					var watch = Stopwatch.StartNew();
					watch.Reset();
					var getResult = _redis.StringGet("testkey");
					if (watch.ElapsedMilliseconds > 0) { Console.WriteLine("Runsync : " + a + " took " + watch.ElapsedMilliseconds); }
				});
		}

		async static Task RunAsync()
		{
			Enumerable.Range(0, loopCount).ToList().AsParallel()
				.WithDegreeOfParallelism(dop)
				.ForAll(async a =>
				{
					var watch = Stopwatch.StartNew();
					watch.Reset();
					var getResult = await _redis.StringGetAsync("testkey");
					if (watch.ElapsedMilliseconds > 0) { Console.WriteLine("RunAsync : " + a + " took " + watch.ElapsedMilliseconds); }
				});
		}

		static void Main(string[] args)
		{
			Console.WriteLine("Hello Test!");

			_redis.StringSetAsync("testkey", "testvalue", TimeSpan.FromHours(3)).ConfigureAwait(false).GetAwaiter().GetResult();

			var watch = Stopwatch.StartNew();
			Runsync();
			var timeforsync = watch.Elapsed.TotalSeconds;
			Console.WriteLine($"Time For Sync {timeforsync}.");
			//Console.ReadLine();

			watch.Restart();
			RunAwaiter();
			var timeforawaiter = watch.Elapsed.TotalSeconds;
			Console.WriteLine($"Time For Awaiter {timeforawaiter}.");
			//Console.ReadLine();

			watch.Restart();
			RunAsync(); //.ConfigureAwait(false).GetAwaiter().GetResult();
			var timeforasync = watch.Elapsed.TotalSeconds;
			Console.WriteLine($"Time For Async {timeforasync}.");
			//Console.ReadLine();

			Console.WriteLine($"Time For Sync {timeforsync} vs Awaiter {timeforawaiter} vs Async {timeforasync}");
			Console.ReadLine();
		}
	}
        }

**Comment by mgravell** [comment]
-

   Does Sync call (StringGet operation) take care of connection
   failure/reconnect for multiplexer internally?

The multiplexer itself attempts to detect and reconnect. This is
independent of any particular operations and sync vs async does not matter.


   -

   Does Sync call blocks other threads/connection call(s) to redis?

Neither sync nor async monopolises the connection, with the exception of
multi/exec transactions, on which case sync and async still behave
similarly to each-other.

   -

   Can anyone suggest which should NOT be used?

GetAwaiter().GetResult() should not be used unless you know the task is
completed because either you checked the state, or you're in a completion
callback. The behaviour is technically undefined, and may depend on the
sync context.

**Comment by NickCraver** [comment]
Closing out to cleanup!
