### ISSUE TITLE
Not seeing thread pool statistics

### ISSUE THREAD

**Issue by MRhyne1931** [StackExchange/StackExchange.Redis#788]
Trying to debug a timeout issue and it looks like I should be seeing threadpool statistics based on the info in the Timeouts.md doc.  It says they should be shown as long as I am on netstandard 2.0 or greater.  This is an aspnetcore project and in the .csproj I have:
`<TargetFramework>netcoreapp2.0</TargetFramework>`

And am using the following version of the dependency:
`<PackageReference Include="StackExchange.Redis" Version="1.2.1" />`

However in my logs I only see the following:
`System.TimeoutException: Timeout performing HMSET inst: 0, queue: 153, qu: 153, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, keyHashSlot: 13090 (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)`

From what I've read I should also be seeing info on IOCP and WORKER

Am I missing something?

**Comment by NickCraver** [comment]
You are on a much older version without this, 1.2.6 is latest stable and include this info :) Just upgrade your library version to get the updated error message :)

**Comment by MRhyne1931** [comment]
@NickCraver thanks for the info!
