### ISSUE TITLE
Cluster pub/sub: keyspace notification issues

### ISSUE THREAD

**Issue by klords** [StackExchange/StackExchange.Redis#789]
Hoping this is just something I'm doing wrong, but I have a cluster with two master-slaves. I've found I'm unable to use a pattern subscription because it just subscribes to one master's notifications (and redis doesn't broadcast notifications across cluster by design). I tried subscribing with a few individual keys that I know are on different masters and only one subset of that group is coming back. I'm not sure if this is because of a slot miscalculation or what.

A way to remedy this would be to allow manual endpoint selection at subscription, but endpoint selection seems to be done automatically based on channel during subscription.

**Comment by klords** [comment]
I can't imagine I'm the first to want to use a pattern subscription to keyspace notifications in a cluster. Is there a workaround for this using this client?

**Comment by mgravell** [comment]
For *regular* pub/sub (done manually), the events propagate around all nodes in the cluster, so it is only necessary to subscribe to a single node. Becuase of this, SE.Redis essentially uses a hash of the channel name to choose a node arbitrarily, and it will get the message.

It sounds like keyspace notifications *do not* propagate, which is causing this confusion. I can see two possible fixes for this:

1. detect and special-case the keyspace notification keys, and subscribe to all primary nodes
2. implement a new API specifically to make keyspace notifications a first-class citizen in the API

(or, of course: both)

This doesn't exist today, but i certainly something that we could look at.

**Comment by NickCraver** [comment]
I'm going to close this out since a PR is open (and welcome!). Going through issues first, but #813 with some efficiency tweaks and tests added seems very appealing to me. Thanks for kicking this off @klords :)
