### ISSUE TITLE
Handle PreserveAsyncOrder flag in connection string

### ISSUE THREAD

**Issue by maxbrodin** [StackExchange/StackExchange.Redis#791]
Currenlty **ConnectionMultiplexer.PreserveAsyncOrder** can be changed by the property only.

Add **PreserveAsyncOrder** property  to **ConfigurationOptions** and make **ConfigurationOptions .Parse** method to parse it from connection string. It could look like this:

```
"contoso.redis.cache.windows.net,abortConnect=true, preserveAsyncOrder=true"
```

**Comment by NickCraver** [comment]
Added via #792, thanks!
