### ISSUE TITLE
Redis StackExchange ConnectionMultiplexer connection event fire twice

### ISSUE THREAD

**Issue by JackyLooProgrammer** [StackExchange/StackExchange.Redis#794]
I want to log the connection activity changes when the connection is disconnected/restored. But somehow the event is fire twice when is triggered which produces duplicated messages into my log.

Below is the code I implemented.

```
ConnectionMultiplexer connection = ConnectionMultiplexer.Connect(new ConfigurationOptions()
    {
        EndPoints = { "localhost" },
        AbortOnConnectFail = false
    });            

    connection.ConnectionFailed += (sender, args) =>
    {
        Console.WriteLine("Connection failed ");
    };

    connection.ConnectionRestored += (sender, args) =>
    {
        Console.WriteLine("Connection restored "); 
    };
```
My question is :-
1. Why is the ConnectionFailed & ConnectionRestored events fire twice when trigger?
2. How can I prevent the event being fire twice? (I am happy to hear any other solution)

Thanks & Regards
Jacky

**Comment by NickCraver** [comment]
Are you sure this code itself isn't run twice, attaching twice? What's the context of when this runs?

**Comment by JackyLooProgrammer** [comment]
Yes, I put the code in Constructor and log a message when initialize to ensure it's only being initialize once. It only log a single initialize message when run. But when I stop the Redis server service, it trigger the event and log "Connection failed " message twice. 
I use Topshelf to install this service for debugging.

**Comment by JackyLooProgrammer** [comment]
@NickCraver It does make sense now. Thank you so much for getting back to me regard to this question.
