### ISSUE TITLE
StackExchangeRedisCacheClient.Add() on existing key

### ISSUE THREAD

**Issue by Timovzl** [StackExchange/StackExchange.Redis#795]
Add(Async) returns a boolean, giving the impression that it returns false (doing nothing) if the key exists. However, Replace(Async) is implemented by a simple call to Add! This indicates that Add overwrites.

What is the expected and the actual behavior?

**Comment by mgravell** [comment]
Can you be very specific about what you're using here? `StackExchangeRedisCacheClient` doesn't sound familiar, and the method names in SE.Redis tend to be more specific than just `Add` etc. Are you sure you're not talking about another library?

**Comment by NickCraver** [comment]
@Timovzl you'll want to find help in the proper repo here :) https://github.com/imperugo/StackExchange.Redis.Extensions Closing this out to cleanup, but the author there should be able to answer on intended behavior.

**Comment by Timovzl** [comment]
Apologies! I will post this where it belongs.
