### ISSUE TITLE
 Redis storage initialization failed: 127.0.0.1:6379

### ISSUE THREAD

**Issue by dmshel** [StackExchange/StackExchange.Redis#804]
Hello.
I have a error
 Redis storage initialization failed: 127.0.0.1:6379
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail.
StackExchange.Redis.1.2.6
17223:M 20 Mar 15:51:31.335 # Server started, Redis version 3.0.6
17223:M 20 Mar 15:51:31.335 * DB loaded from disk: 0.000 seconds
17223:M 20 Mar 15:51:31.335 * The server is now ready to accept connections on port 6379

 redis-cli
127.0.0.1:6379> ping
PONG
127.0.0.1:6379>
How 2 fix this error
i am noob at radis:)
use mono

**Comment by dmshel** [comment]
Solved!

**Comment by eplowe** [comment]
What was the solution?

**Comment by dmshel** [comment]
Solved!
StackExchange.Redis 1.2.6 from neuget package not wont correctly work!
I copy to ~/CoiniumServ/build/bin/Release files StackExchange.Redis.dll and StackExchange.Redis.xml from 1.2.4 release and start CoiniumServ. works is fine all works!
