### ISSUE TITLE
Async calls won't respect timeout

### ISSUE THREAD

**Issue by rayao** [StackExchange/StackExchange.Redis#805]
Hi, it's a stupid question but it seems to me async version APIs won't respect timeoutMilliseconds, is that by design or maybe I missed something?
If it's by design what's the recommended way to timeout async calls?
Thanks.

**Comment by rayao** [comment]
Hi, could anyone give me some suggestion? Thanks in advance.

**Comment by zvolkov** [comment]
Same issue here - the Async equivalents of Database's methods do not take CancellationToken and seem to be ignoring the synch timeout setting in connection string? Any ideas?

**Comment by mgravell** [comment]
I have code to address this in a branch underneath 2.0; I'm going to review it (and the consequences) to see whether we can merge it into 2.0

**Comment by NickCraver** [comment]
@mgravell good to close as completed in 2.0 here?

**Comment by mgravell** [comment]
Yes; this is now in 2.0 - see https://github.com/StackExchange/StackExchange.Redis/issues/871 for more information

**Comment by zvolkov** [comment]
So, to confirm, the async versions of Database's Get/Put methods will now respect the same timeout setting as their sync originals? Will the time be measured inclusive of the callback (my code)? What exception will be thrown?

**Comment by mgravell** [comment]
"yes", "no, only the interval while waiting for a server response",
"TimeoutException"

that cover it?

**Comment by zvolkov** [comment]
Yes, I found a unit-test that defines it:

https://github.com/StackExchange/StackExchange.Redis/blob/3f7e5466c6bbff96a3ed1130b637a097d21f3fed/tests/StackExchange.Redis.Tests/AsyncTests.cs

it's RedisTimeoutException.

Thanks!
