### ISSUE TITLE
IPv6 is not worked by hostname

### ISSUE THREAD

**Issue by theanurin** [StackExchange/StackExchange.Redis#807]
1.  Symptom
    Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
       at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func1 multiplexerFactory, TextWriter log) in 
    C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 876
       at ipv6issue.EntryPoint.Main(String[] args) in 
    C:\Users\me\Work\StackExchange.Redis.IPv6Issue\TestApp.cs:line 21

1. Version: 1.2.7-alpha-00002

1. Condition to reproduce the issue:
    Hostname "redis-server" that has only one DNS record AAAA = 2xxx:xxxx:xxxx::1

1.  Source code to reproduce the issue
   var options = new ConfigurationOptions();
   options.EndPoints.Add("redis-server", 6379);
   //options.EndPoints.Add("2xxx:xxxx:xxxx::1", 6379); // with this row works fine
   var redis = ConnectionMultiplexer.Connect(options);
   var sub = redis.GetSubscriber();
   sub.Publish("messages", "hello");

**Comment by NickCraver** [comment]
Closing out to cleanup.

**Comment by alexvaut** [comment]
We are facing the exact same issue with StackExchange.Redis 2.2.4
