### ISSUE TITLE
IRedisAsync.Multiplexer should be IConnectionMultiplexer 

### ISSUE THREAD

**Issue by richardacre** [StackExchange/StackExchange.Redis#809]
To allow for mocking database.Multiplexer

https://github.com/StackExchange/StackExchange.Redis/blob/7c1563e57e77213cbb16729b2086a255143f021c/StackExchange.Redis/StackExchange/Redis/Interfaces/IRedisAsync.cs#L14

**Comment by mgravell** [comment]
Maybe, but that's a breaking change; it isn't something we can do trivially

**Comment by NickCraver** [comment]
I'll put this under a 2.x/3.x change (depending on how we reconcile strong naming), but Marc's right - has to be a major version. And we need to ensure everything needed is exposed on that interface, which I'm pretty sure it not the case today.

**Comment by mgravell** [comment]
@NickCraver  we should get our heads together to decide whether we want to do this "now" (i.e. for 2.0)

**Comment by NickCraver** [comment]
The impact feels small but *could* break upstream of course. But if we're going to break stuff, I think 2.0's the time.

I tested locally, this issue only affects: `IRedisAsync`, `RedisBase`, and `WrapperBase<T>` (all only changing the return type). None of our consuming code needed any changes, FWIW. Note: there's a related issue here: #855 around `IConnectionMultiplexer.GetCounters()` for the same reasons.

Thoughts?

**Comment by NickCraver** [comment]
This change has been made for 2.0 - thanks for the feedback! See 1d8e936345a834ba099771a1402d93dd4eee7d2b for changes :)

**Comment by richardacre** [comment]
Great stuff, thank you
