### ISSUE TITLE
Client stops working: RedisConnectionException

### ISSUE THREAD

**Issue by mjisaak** [StackExchange/StackExchange.Redis#81]
Hello,

I use StackExchange.Redis (1.0.322) in a WCF Backend Application running in IIS on Azure Cloud Service. I observed that the client runs well for some time (1 - 2 days) but then stops working until I restart the IIS. 
This is not a transient fault, I guess that the ConnectionMultiplexer runs in an invalid state. 

This is the exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation

Any suggestions?

**Comment by NickCraver** [comment]
I'm closing this out since it appears to be the same issue as #38, which I just reopened.
