### ISSUE TITLE
PubSub callback to expose subscription RedisChannel

### ISSUE THREAD

**Issue by Phil-ICAP** [StackExchange/StackExchange.Redis#814]
The public callback only exposes the transmitted channel name and payload. It would be handy if it also exposed the subscription as it would give more options to the user for ongoing message transformation and redirection.

**Comment by mgravell** [comment]
Can you be a bit more specific here; are you talking about wildcard
(psubscribe) messages where you would like to see the wildcard subscription
name in addition to the actual name?

**Comment by Phil-ICAP** [comment]
Yes, sorry I should have been clearer. It's exactly that, for wildcards I'd like to the original subscription specification as well as the channel.

**Comment by NickCraver** [comment]
@Phil-ICAP do you have some use cases in mind? This would change the signature of the delegate, breaking code or adding an odd overload, so a use case would help judge if this is worth the API complexity.

**Comment by Phil-ICAP** [comment]
@NickCraver we have a number of use cases when we need to know which subscription actually 'generated' the message. For us this is because we have a message library that has a definied signiture and a number of different transports (29West LBM, RabbitMQ, Solace etc).

Because of this we can't expose the native callback and have to hide what really happens. It's not terrible (for us) to just use the original subscription topic to lookup which lib callback to fire.

**Comment by mgravell** [comment]
The good news is: we have a new API in v2 that now exposes this

The "meh" news is - right now, this only applies to *ordered* subscriptions; so - are you using ordered? or unordered? subscriptions.

Basically, there's a new API:

    var queue = foo.Subscribe(channel);

which gives you a `ChannelMessageQueue`; this can be used in many ways, the simplest of which is just to call `OnMessage` (with either a sync or async handler), which sets up an ordered async message loop with your designated handler. The `ChannelMessageQueue` has a `Channel`, and the item in the `OnMessage` callback is a `ChannelMessage`, which has both the *actual* channel and the *subscription* channel. Does that solve things for you?

**Comment by mgravell** [comment]
in the absence of a response, I'm assuming that the 2.0 changes enable this; please let me know otherwise
