### ISSUE TITLE
Put Redis between Database and OutputCache in MVC 4/5

### ISSUE THREAD

**Issue by minhncud** [StackExchange/StackExchange.Redis#816]
- My purpose: 
I have a front-end web server (FE Server) to get data and an other server to change data (I use MVC4). I use Redis like temporary database. Because memory cache is fastest, so i want to put Redis before OutputCache. 
- Example:
First request from client, FE Server gets data from database and send a copy to Redis.
When data in Redis changes (from other server), Redis sends a notification and FE Server gets data from Redis, then put this data to Output Cache. Now, Output Cache works with Redis instead of the real Database 
(All TTL in Redis = -1, Output Cache only expires when disconnect)
![redis-map](https://user-images.githubusercontent.com/36953180/38488754-9d50cca2-3c0e-11e8-8f79-40aee8e18461.png)
Can i do this with StackExchange.Redis?

**Comment by NickCraver** [comment]
There's nothing built-into the library directly for this, though we can be part of a solution. What you'll want it something higher level that uses our library (or another) but it's not functionality we'd embed. I'd recommend checking out https://github.com/zzzprojects/EntityFramework-Plus/issues/93 :)
