### ISSUE TITLE
Is there any plan to support DiagnosticSource?

### ISSUE THREAD

**Issue by yuleyule66** [StackExchange/StackExchange.Redis#824]
Hello , Thanks for the great work.

I'm working on APM-related work. Using diagnostics allows users to get more runtime event data, which is helpful for distributed tracking systems.

Diagnositics doc :
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md

**Comment by NickCraver** [comment]
Sorry I missed this issue earlier - please see #833 for a lot of discussion around `DiagnosticSource` and current thoughts. Please chime in if you have additional thoughts, but let's get them together in one issue :)
