### ISSUE TITLE
Mocking exceptions in tests

### ISSUE THREAD

**Issue by q42jaap** [StackExchange/StackExchange.Redis#825]
We've created a wrapper service around an IDatabase and we want to test how our code behaves when the IDatabase methods throw exceptions.
We cannot create the exceptions, since their constructors are internal. Is there a way to make this possible?

The unittest code is as follows (we use Moq as mocking library):
```
mockDbService.Setup(
	m => m.GetAsync<string>(KEY_NOT_EXIST, null)
)
.Throws(new RedisConnectionException("mock exception"));

string result = await dbService.GetAsync<string>(KEY_NOT_EXIST);

Assert.Null(result);
```

Is there a way around the `internal`ness of the exception classes?

One way to do this is to have a separate assembly `[assembly:InternalsVisibleTo("Stackoverflow.Redis.TestHelper")]`. The helper should expose some methods to create the exceptions...

**Comment by mgravell** [comment]
I guess there's no real reason not to just expose them. Historically we
didn't, simply due to lack of obvious need, but if there's a genuine
use-case, I guess we can make whatever surface public as needed

**Comment by q42jaap** [comment]
That would help. I think the most straight forward way would be to make the constructors public. Or would it make more sense to expose the factory, since that provides more context as to what exception is used in what scenario?
I'd be happy to help with a PR.

**Comment by q42jaap** [comment]
@NickCraver I've created #839.

**Comment by NickCraver** [comment]
PR merged in, thanks @q42jaap :)
