### ISSUE TITLE
Not reading responses on heavy load with ASP.Net Core

### ISSUE THREAD

**Issue by MarcusWichelmann** [StackExchange/StackExchange.Redis#826]
Hi,
we are making use of this library in an **ASP.Net Core 2.0** web api and even though it runs just fine during occasional requests, the library stops processing redis-responses on heavy server loads.

This is our API-Method in the Controller:
```C#
namespace WebApplication2.Controllers
{
    [Route("api/[controller]")]
    public class TestController : Controller
    {
        private readonly ConnectionMultiplexer _client;

        public TestController(ConnectionMultiplexer client)
        {
            _client = client;
        }

        [HttpGet("many")]
        public async Task<IActionResult> Get()
        {
            var database = _client.GetDatabase();

            Console.WriteLine("-- StringSetAsync");
            await database.StringSetAsync($"testkey:{Guid.NewGuid()}", "test").ConfigureAwait(false);
            Console.WriteLine("-- -- Return");

            return Ok();
        }
    }
}
```

And we're connecting using:
```C#
var client = ConnectionMultiplexer.Connect(new ConfigurationOptions {
    EndPoints = { { "10.200.1.100", 6379 } },
    AbortOnConnectFail = false,
    ConnectTimeout = 15000
}, Console.Out);
```

Output during occasional requests (as expected):
```
-- StringSetAsync
-- -- Return
-- StringSetAsync
-- -- Return
-- StringSetAsync
-- StringSetAsync
-- -- Return
-- -- Return
...
```

Output on heavy load (`wrk -t8 -c400 -d60s --latency http://localhost/api/test/many`):
```
-- StringSetAsync
-- StringSetAsync
-- StringSetAsync
-- StringSetAsync
-- StringSetAsync
<<< Forever until we kill the request-spamming with wrk >>>
-- -- Return
-- -- Return
-- -- Return
-- -- Return
-- -- Return
````

We can see in Wireshark that Redis is responding to the SET commands instantaneously but it looks like that StackExchange.Redis doesn't read the incoming TCP responses and therefore the async `StringSetAsync` never completes.
Also the application starts consuming more and more memory because of thousands of Tasks waiting for their completion.

We tried some debugging and this line https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis/StackExchange/Redis/PhysicalConnection.cs#L716 is never reached during the request-spamming until we stop `wrk`. Then it is executed many times until all Redis-Responses have been processed.

This bug doesn't occur when executing many parallel Redis-Commands using a while/for loop manually, so we think that it is somehow related to the asynchronous ASP.Net Core Method execution.

Thanks in advance for any help!

**Comment by MarcusWichelmann** [comment]
Any thought's about this?
This is still a big issue for me and this usage is by no way a special case. So I think that anybody who uses this library with ASP.Net Core is affected.

The same bug even occurs with this completely synchronous API-Method:
```C#
[HttpGet("sync")]
public IActionResult Get()
{
    var database = _client.GetDatabase();

    Console.WriteLine("-- StringSet");
    database.StringSet($"testkey:{Guid.NewGuid()}", "test");
    Console.WriteLine("-- -- Return");

    return Ok();
}
```

**Comment by NickCraver** [comment]
This sounds like a starvation issue - can you post your setup/config, any any exceptions thrown as well? They have various counters we track to help diagnose these issues.

**Comment by MarcusWichelmann** [comment]
I've pushed the whole minimal Demo-Project together with the commandline-output and exceptions here now:
https://github.com/MarcusWichelmann/StackExchange.Redis-Issue-826-Demo

> can you post your setup/config

I'm not sure which config you mean?

Would be nice if you could try to reproduce it.
If you need anything else just let me know!

**Comment by mokezhuhy** [comment]
@MarcusWichelmann 
Yes, you are right. I have the same problem with you. My application go crashed when it is heavy loaded, even on windows iis or centos docker, bulit on net core 2.0.

**Comment by mgravell** [comment]
We have made significant network core changes that are relevant here; any followup here is probably best viewed in the context of the 2.0 work; please see https://github.com/StackExchange/StackExchange.Redis/issues/871
