### ISSUE TITLE
OOM command not allowed when used memory > 'maxmemory' but used_memory_human only 2.81M

### ISSUE THREAD

**Issue by foreverhot1019** [StackExchange/StackExchange.Redis#828]
RedisHelper - Redis命令<ListRightPush>b__c8失败：OOM command not allowed when used memory > 'maxmemory'.

i don't know how to solve this problem，please help me 

# Server
redis_version:3.2.100
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:dd26f1f93c5130ee
redis_mode:cluster
os:Windows
arch_bits:64
multiplexing_api:WinSock_IOCP
process_id:4128
run_id:8410720ced90d5a4bf3714864fa109e35ceb7c23
tcp_port:6379
uptime_in_seconds:5320
uptime_in_days:0
hz:10
lru_clock:15373287
executable:C:\Program Files\Redis\"C:\Program Files\Redis\redis-server.exe"
config_file:C:\Program Files\Redis\redis.windows-service.conf

# Clients
connected_clients:12
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:2951384
used_memory_human:2.81M
used_memory_rss:2950328
used_memory_rss_human:2.81M
used_memory_peak:9439760
used_memory_peak_human:9.00M
total_system_memory:0
total_system_memory_human:0B
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:5368709120
maxmemory_human:5.00G
maxmemory_policy:volatile-ttl
mem_fragmentation_ratio:1.00
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:170
rdb_bgsave_in_progress:0
rdb_last_save_time:1525322526
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:0
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_current_size:5313272
aof_base_size:1442103
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:30
total_commands_processed:74968
instantaneous_ops_per_sec:18
total_net_input_bytes:42628152
total_net_output_bytes:167191294
instantaneous_input_kbps:0.69
instantaneous_output_kbps:0.08
rejected_connections:0
sync_full:2
sync_partial_ok:0
sync_partial_err:2
expired_keys:1704
evicted_keys:0
keyspace_hits:3241
keyspace_misses:38
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:3000
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:2
slave0:ip=172.20.60.186,port=6380,state=online,offset=40055134,lag=0
slave1:ip=172.20.70.196,port=6380,state=online,offset=40055134,lag=0
master_repl_offset:40055134
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:39006559
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:16.83
used_cpu_user:17.22
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Cluster
cluster_enabled:1

# Keyspace
db0:keys=51,expires=6,avg_ttl=316485

**Comment by NickCraver** [comment]
I'm not sure what's being asked here - can you please post the error and stack trace you're getting?

**Comment by mgravell** [comment]
This sounds like a redis issue, not a StackExchange.Redis (client library) issue. I'd love to help, but I know nothing about this. You probably meant to file this somewhere else.
