### ISSUE TITLE
NRedisearch - AddSuggestion raises exception "Unable to format type for redis: System.Object[]"

### ISSUE THREAD

**Issue by mfatkhur** [StackExchange/StackExchange.Redis#829]
Hi,

I need to use auto suggestion feature of Redisearch, an exceptions **`Unable to format type for redis: System.Object[]`**
occured on line `client.AddSuggestion(element,100.0,false);`

StackTrace is here,

`at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor 1 processor, ServerEndPoint server)   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor 1 processor, ServerEndPoint server)   at StackExchange.Redis.RedisDatabase.Execute(String command, ICollection 1 args, CommandFlags flags)   at StackExchange.Redis.RedisDatabase.Execute(String command, Object[] args)   at NRediSearch.Client.AddSuggestion(String value, Double score, Boolean increment)   at UserQuery.Main()   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)   at System.Threading.ThreadHelper.ThreadStart()`

`DbSync.Execute` will raises an error on `AddSuggestion `method, 

this is code for `AddSuggestion` method,
 ```
public long AddSuggestion(string value, double score, bool increment = false)
        {
            object args = increment
                ? new object[] { _boxedIndexName, value, score, "INCR".Literal() }
                : new object[] { _boxedIndexName, value, score };
            return (long)DbSync.Execute("FT.SUGADD", args);
        }
```

this will fixed when implementation of `AddSuggestion `changed to this,

```
public long AddSuggestion(string value, double score, bool increment = false)
        {
            return (long)DbSync.Execute("FT.SUGADD", _boxedIndexName, value, score, increment ? "INCR".Literal() : "");
        }
```

</br>
</br>
and this is my code,

```
void Main()
{
	var redis = ConnectionMultiplexer.Connect("172.17.5.5:6379,allowAdmin=true");
	var db = redis.GetDatabase(0);

	var client = new Client("sug_lc_code", db);

	try { client.DropIndex(); } catch { } // reset DB
	
	var codes = Profile
		.Select(p => p.KodeEmiten.TrimEnd()).ToList();
	
	foreach (var element in codes)
	{
		client.AddSuggestion(element,100.0,false);
	}
	
	string code= "A";
	var data = client.GetSuggestions(code);
	data.Dump("data");
	
}
```
if this is BUG, need to be fixed in next release. 

currently my code worked after i change the original code as mentioned above.

Thanks,

**Comment by mgravell** [comment]
Thanks - the correct fix is:

    object args = ...

to

    object[] args = ...

Pushing to master now.
