### ISSUE TITLE
Dropping netstandard1.5 support (moving to netstandard2.0+ only)

### ISSUE THREAD

**Issue by NickCraver** [StackExchange/StackExchange.Redis#842]
We support `netstandard1.5` in current package versions because that's where the landscape was when .NET Core was coming up. Unfortunately though, at that period in time the cross-platform network situation was in flux. For example `Socket.BeginConnect()` isn't even a thing, because "sockets should be async!" (and they should...but that creates compat problems). These types of things were addressed in `netstandard2.0`. IMO, 2.0 is really a 1.0, that's where we got stability.

After going through hundreds of issues this weekend including connection quirks and Mono support, I think dropping `netstandard1.5` support is an immediate win in code complexity and reducing some logic paths by half. It also allows @mgravell a lot less headaches when simplifying the network layer on top of Pipelines in whole.

Note: us dropping support doesn't mean you can't use StackExchange.Redis anymore, it simply means you can't use newer versions until you do.

So, the questions:
- Who's still using `netstandard1.5`?
- Why?
- Are you planning to upgrade?

**Comment by mgravell** [comment]
100% agreement on "2.0" really being the first RTM, essentially the "1.0". Supporting pre-2.* is currently "kinda painful", and is going to become "prohibitively restrictive" *very* quickly.

**Comment by jonsagara** [comment]
We are, but we're upgrading to .NET Core 2.1 as soon as it's RTM. Dropping netstandard1.5 won't affect us.

**Comment by NickCraver** [comment]
I've opened a PR (#843) to show what this drop looks like. I'm working on it to see if it's a viable path to supporting Mono (easily) or not.

**Comment by NickCraver** [comment]
After chatting today with many people - we're going to go ahead with this. Merging #843 in shortly.

**Comment by benaadams** [comment]
Bumping major?

**Comment by NickCraver** [comment]
@benaadams I think the intent is to next do a 2.0 release on: Pipelines, cover all the missing APIs, and switch to NerdBank versioning. Working through it all now :)
