### ISSUE TITLE
ioBuffer Memory Issue

### ISSUE THREAD

**Issue by icyice80** [StackExchange/StackExchange.Redis#844]
Hi 
We are using the latest SE.Redis on our ASP.NET application. We use redis to store our products and they are stored in the hash. During the application starts, we load all the products at one go from redis. The size of the products is about 200-300 MB, and it is growing gradually. During the memory profiling (DotMemory), we spoted the possible issue below: 

After we call the hgetall, get fields and values out it, transform into our domain objects, the SE.Redis still holds some amount of memory, should it be removed? It seems the isobuffer out of physical connection still holds that byte array for no reason. Here is a screenshot of it.

![image](https://user-images.githubusercontent.com/5934998/40695513-596f99d4-6376-11e8-8f3f-f2ab326ac599.png)

 I have attached my sample app here (https://www.dropbox.com/s/gn0cslyyfxgj97x/RedisPerformanceTest.zip?dl=0): 

use /api/value/save to populate the data 
use /api/value/getall to get all the data, 

Please update the RedisCacha Class with your own redis endpoint. 

Thank you. 

Bing

**Comment by NickCraver** [comment]
Unfortunately, yes - what you're seeing is the same cause (but not as severe) as #358. The `ioBuffer` array will grow as large as the largest item to be read. It's only something that affects people moving very large object payloads, but it is an issue. There's no fix at the moment, it's a fundamental flow problem.

The good news is: we plan to address this next. This is part of the networking stack we're replacing which will result in less memory used and copied in general (thanks to new types in .NET itself, like `Span<T>`). Now we can pipeline this through without buffering it in a much more efficient way.

I don't have a suggestion for the moment (unless you can break this into multiple smaller calls), just letting you know: we're aware, and will be working on resolving this.

**Comment by icyice80** [comment]
Thank you so much for your quick reply. 
Breaking into multiple calls is what I have tested, so far so good. :)

**Comment by mgravell** [comment]
Closing; please see: https://github.com/StackExchange/StackExchange.Redis/issues/871
