### ISSUE TITLE
Unclear release notes documentation

### ISSUE THREAD

**Issue by Yonisha** [StackExchange/StackExchange.Redis#846]
From the [release notes](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/ReleaseNotes.md#125): 

> critical fix: "poll mode" was disabled in the build for net45/net60 - impact: IO jams and lack of reader during high load

What is "poll mode"? couldn't find any relevant documentation. Is this "critical fix" relevant for all usages with the .NET client or only for specific usage/mode?

**Comment by kierenj** [comment]
I guess you're not just randomly picking holes, so I guess you're experiencing an issue and wondering whether this will fix it?  What's the issue you're having?

(The release notes are pretty clear - the platforms impacted, the situation that occurs, etc)

**Comment by NickCraver** [comment]
@Yonisha indeed it'll help. "poll" means a threads continually reads the socket for data coming in, rather than waiting for the thread pool `async` continuations to happen on their own, which can be delayed into timeouts under heavy load. You'll definitely want to upgrade.
