### ISSUE TITLE
Get current configuration of notify-key-space events

### ISSUE THREAD

**Issue by maupatel1** [StackExchange/StackExchange.Redis#848]
Hi,

Is there any way to read the current status "notify-keyspace-events" configuration (whether is set or not) using Stackexchange.Redis client?

**Comment by NickCraver** [comment]
Yep! Note that this is per-server, so you'll want to use the `.ConfigGet()` API on `IServer`. Here's an example:
```c#
using (var conn = ConnectionMultiplexer.Connect("localhost,allowAdmin=True"))
{
	var server = conn.GetServer(conn.GetEndPoints(true)[0]);
	var config = server.ConfigGet("notify-keyspace-events").First();
	Console.WriteLine(config.Value);
}
```

**Comment by maupatel1** [comment]
Thanks for sharing an example. Is there any way to read the same configuration for "Azure Redis" server?

**Comment by NickCraver** [comment]
Closing this out to cleanup, answers above (thanks @JonCole!) :)
