### ISSUE TITLE
StringGetAsync is slower then StringGet

### ISSUE THREAD

**Issue by JedatKinports** [StackExchange/StackExchange.Redis#849]
With StringGetAsync the elapsed time is 1000ms and with StringGet it's 40ms.

Can anyone reproduce this?

I'm on a Windows 10 machine using .NET Core 2.0.

**Comment by NickCraver** [comment]
Do you have some example code?

**Comment by mgravell** [comment]
1000ms seems excessive even for `async`; how are you measuring this? the most common cause of this is thread-pool exhaustion, as historically we needed to kick async completions to the thread-pool to prevent it from stealing the reader thread. Now, from 2.0 the reader thread no longer exists; we might also be able to use the new tools to avoid the thread-pool for the completion queue - I'll have to have a look. But an example would *really really help*.

**Comment by mgravell** [comment]
I added a basic test to investigate this; my results:

    Sync: 0; Async: 0

There is no fundamental unexpected delta here between sync and async - except for general async overhead, which should be minimal. I'm happy to investigate this, but we'd need a repro case. Closing for now; will reopen if example supplied.

**Comment by JedatKinports** [comment]
I have tested this again today and the response times are almost the same. Must have been something wrong that day I guess. This "issue" can be closed.
