### ISSUE TITLE
Thread with maxStackSize

### ISSUE THREAD

**Issue by gtrfan34** [StackExchange/StackExchange.Redis#851]
Hello! Is there any reason to set up maxStackSize in StackExchange.Redis/StackExchange.Redis/StackExchange/Redis/SocketManager.cs 145
`var dedicatedWriter = new Thread(writeAllQueues, 32 * 1024); // don't need a huge stack;`
We getting stackoverflow exception because of it.

**Comment by NickCraver** [comment]
Do you have a stack trace from your overflow? The writer just writes things out the queue, it definitely should not throw a StackOverflowException.

**Comment by gtrfan34** [comment]
I intercepted and modified IL code. Then I get stackoverflow. Do you use maxStackSize for some perfomance reason?

**Comment by NickCraver** [comment]
@gtrfan34 Yep, there's just no need to tie up resources. Though for context: this is a bit moot as we're changing how all this works right now over in the `pipelines` branch.

On the issue: if you're intercepting and changing the IL, all bets of any sanity are off. To be frank, that's just not a valid bug.
