### ISSUE TITLE
issue with SSL

### ISSUE THREAD

**Issue by shenda73** [StackExchange/StackExchange.Redis#854]
With SSL turned on, when running our load test with two or more users, we received errors like the following:
PushPub interrupted, trying again in 500ms. Error: SocketClosed on LPUSH 

With SSL turned off, there's no such error.

Could there be some threading issue with the SSL?

**Comment by mgravell** [comment]
Is the system under significant load at the time? And is this on Windows? The most likely cause is pool thread exhaustion - i.e. the thread-pool is saturated.

Without SSL enabled on Windows, we use a dedicated worker thread using socket poll to check for availability of data over a number of sockets, reading data once it is known available, and pushing it into the processing queue. However, once SSL (TLS) is involved, this ceases to be possible - with us instead turning to the async Stream read API (on `SslStream`). This means that we're slightly dependent on the thread-pool to service the socket's read continuation. This works fine most of the time, but if the system is busy with no available workers, it can stall the read pipe. This is doubly problematic if the IO completion is currently part of what it blocking the other workers (for example, they're doing lots of parallel "sync" calls over SE.Redis, monopolising the thread pool). The thread pool grows *painfully* slowly, so once it is saturated, it to mean big problems.

Is it possible this is the scenario at play here? We are currently doing a lot of work on the IO stack, and I'd like to understand the scenario more. In particular, I'm interested in how many underlying connections you are using. One very viable options would be for us to switch to a "thread per underlying connection" model in this scenario, with the non-async read API. It wouldn't be as scalable in terms of the upper limit on the number of connections, but it would be more scalable in terms of concurrent throughput.

The third option we're looking at is very different IO layers, building on top of much of the Kestrel has done for high performance scenarios. This is work I already have in progress, but again - is dependent on many moving pieces.

**Comment by cmecgiit** [comment]
switched to the team account for better visibility for my teammates.

Thanks for the prompt reply. Actually, we didn't have that much of a load when we saw the issue - we only had two test users trying to log on, which we don't think puts much pressure on the system. Though the environment we used was on a VM, we didn't believe such low load would exhaust the thread pool. In addition, we saw the error within few seconds of starting the load testing. It seems more like a race condition issue than a resource depletion issue. And as for the underlying connections, we only have one at a time.

Hope the info is helpful.

**Comment by mgravell** [comment]
We have significantly reworked the network code for 2.0 - a key scenario here is TLS (which required a different threading model), so: I think it makes sense to close this and re-evaluate in the context of 2.0: https://github.com/StackExchange/StackExchange.Redis/issues/871
