### ISSUE TITLE
IConnectionMultiplexer.GetCounters not unit testable

### ISSUE THREAD

**Issue by lfoust** [StackExchange/StackExchange.Redis#855]
Since the ServerCounters class does not have a public constructor you cannot mock `IConnectionMultiplexer.GetCounters()` in unit tests. The solution would be to either add a public constructor to this class or to make the `IConnectionMultiplexer.GetCounters()` return an interface rather than a concrete class so that it could be easily mocked.

I don't mind creating a pull request for this but I wanted to get thoughts or workarounds first.

**Comment by NickCraver** [comment]
@mgravell Any issue with making `internal ServerCounters(EndPoint endpoint)` public?

**Comment by NickCraver** [comment]
This is now exposed in  the 2.0 (pipelines) branch as well as the `.Multiplexer` property on `IAsyncRedis` and friends being an `IConnectionMultiplexer` instead of a concrete `ConnectionMultiplexer`. This should round out being able to mock the primary pieces for testing.
