### ISSUE TITLE
Cannot create instance of RedisResult using an array

### ISSUE THREAD

**Issue by greathow** [StackExchange/StackExchange.Redis#856]
Currently, there is a function for creating a `RedisResult` from a single `RedisValue`:

```cs
public static RedisResult Create(RedisValue value) => new SingleRedisResult(value);
```

However, there is no corresponding functionality to create a `RedisResult` from a `RedisResult[]` or `RedisValue[]`.  This would be useful when creating unit tests, as it would allow mocking behavior where we expect the result to be castable to `RedisValue[]`

I'd propose adding a corresponding static function in `RedisResult` to allow this:
```cs
public static RedisResult Create(RedisResult[] values) => new ArrayRedisResult(values);
```
and/or
```cs
public static RedisResult Create(RedisValue[] values)
{
    RedisResult[] results = new RedisResult[values.Length];
    for (int i = 0; i < results.Length; i++)
    {
        results[i] = new SingleRedisResult(value);
    }

    return new ArrayRedisResult(results);
}

**Comment by mgravell** [comment]
makes sense; pushed to 2.0 branch - thanks, good suggestion

**Comment by ryandle** [comment]
@mgravell any concerns with a contribution to backport this to 1.x?

**Comment by mgravell** [comment]
Mostly my concern is that we're hoping to merge 2.0 in the not too distant,
making it redundant. If it would make you happy and it isn't going to make
merge hell, go for it. But hopefully with minimal stress!
