### ISSUE TITLE
Internal Error in ConnectionMultiplexer

### ISSUE THREAD

**Issue by annymsMthd** [StackExchange/StackExchange.Redis#86]
Hey guys. I'm getting a internal error with my logging plugged into ConnectionMultiplexer.InternalError

>System.NullReferenceException: Object reference not set to an instance of an object. at StackExchange.Redis.ConnectionMultiplexer.OnHeartbeat() in c:\TeamCity\buildAgent\work\58bc9a6df18a3782\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 859

This is in an environment in AWS. I was having issues with the master dropping and the multiplexer not reestablishing the connection. I then upgraded from version 1.0.312 to 1.0.330 and started receiving these errors in the logs. When it's in this state it will still run commands against redis just fine. Any idea what's going on?

**Comment by maulikhdave** [comment]
Urgent----------------------Urgent-------
Looking for Help 
Urgent----------------------------------------------------------------------------
Error, TagType=InfoTagModule=APPERROR$$$CRITICAL - APPERROR - Application_Error event - ErrorDetails - ** VP Error Report : Error: Timeout performing EVAL, inst: 0, mgr: ExecuteSelect, err: never, queue: 49, qu: 48, qs: 1, qc: 0, wr: 1, wq: 1, in: 0, ar: 0, IOCP: (Busy=0,Free=1000,Min=36,Max=1000), WORKER:(Busy=52,Free=32715,Min=36,Max=32767), clientName: ************
Source: StackExchange.Redis.StrongName  Stack Trace: at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) at Microsoft.Web.Redis.StackExchangeClientConnection.<>c__DisplayClass4.<Eval>b__3() at Microsoft.Web.Redis.StackExchangeClientConnection.RetryForScriptNotFound(Func`1 redisOperation) at Microsoft.Web.Redis.StackExchangeClientConnection.RetryLogic(Func`1 redisOperation) at Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs) at Microsoft.Web.Redis.RedisConnectionWrapper.TryUpdateAndReleaseLockIfLockIdMatch(Object lockId, ISessionStateItemCollection data, Int32 sessionTimeout) at Microsoft.Web.Redis.RedisSessionStateProvider.SetAndReleaseItemExclusive(HttpContext context, String id, SessionStateStoreData item, Object lockId, Boolean newItem) at System.Web.SessionState.SessionStateModule.OnReleaseState(Object source, EventArgs eventArgs) at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)  UserSession Items:User Key: 0 Currency Key: 3 Basket Key: 1454212 Date: 11 December 2015 Time: 05:30:24 URL: /CheckoutStep1.aspx File: /***.aspx ----------------------------Error-2-------------------------------- 

Urgent----------------------Urgent-------
Looking for Help 
Urgent----------------------------------------------------------------------------
