### ISSUE TITLE
ServiceStack.Redis AcquireLock no timeout exception happens

### ISSUE THREAD

**Issue by gregoks** [StackExchange/StackExchange.Redis#861]
Hi,

I'm trying to understand the AcquireLock timeout logic. I've tried running the code from the example:

https://github.com/ServiceStack/ServiceStack.Redis/wiki/RedisLocks

```
try
{
	using (var newClient = new RedisClient(TestConfig.SingleHost))
	{
		//Attempt to acquire a lock with a 2 second timeout
		using (newClient.AcquireLock("testlock", waitFor))
		{
			//If lock was acquired this would be incremented to '2'
			redisClient.Increment("atomic-counter"); 
		}
	}
}
catch (TimeoutException tex)
{
	var timeTaken = DateTime.Now - now;
	Console.WriteLine("After '{0}', Received TimeoutException: '{1}'", timeTaken, tex.Message);

	var counter = redisClient.Get<int>("atomic-counter");
	Console.WriteLine("atomic-counter remains at '{0}'", counter);
}
```

but as the explanation points out, if you specify a TimeOut, the client will treat the lock as invalid once the timeout expires, and thus grab the lock.
So when will the timeoutException happen?
I've tried running the code and indeed, after the timeout occurs, lock is being grabbed and no exception happens.

Can you please advise?

Thx,

Greg

**Comment by gregoks** [comment]
I will just add that the example works if I call acquireLock without timeout first and then try to call acquireLock with timeout it gets to timeoutException but if I try to call the following code that exists in a Web API for 2 different API calls, then exception doesnt happen:
```

try
            {
             
                using (var redisClient = new RedisClient(_redisEndPoint))
                {
                    using (redisClient.AcquireLock(key, TimeSpan.FromSeconds(1)))
                    {
                        redisClient.IncrementValue("dummy-counter");
                        _logger.Info("entered redis");

                        Thread.Sleep(15000);
                    }
                }

                _logger.Info("left redis");
            }
            catch (TimeoutException ex)
            {
                _logger.Error(ex, "");
            }
```

**Comment by kierenj** [comment]
I think you may have the wrong repo? This is StackExchange.Redis, not ServiceStack ?

**Comment by mgravell** [comment]
Closing. With the greatest will in the world, we're not well placed to help you. This is one for https://github.com/ServiceStack/ServiceStack (/cc @mythz)
