### ISSUE TITLE
I want to read all keys of redis cache

### ISSUE THREAD

**Issue by Itsathere** [StackExchange/StackExchange.Redis#863]
I wanna get all redis cache keys and data. Somehow if I will able to get all keys then I can read data with respect to key. But if I will get one method to get all keys and data at the same time then it would be fine for me.

If anybody have any idea about kindly share it.

Thanks

**Comment by mgravell** [comment]
That isn't an inbuilt feature of redis, but I guess you can use Keys from
the IServer API and then for each let: StringGet. You could probably LINQ
it nicely - something like:

var all = from key in server.Keys()
               select new { key, value = db.StringGet(key)}

**Comment by NickCraver** [comment]
Answered above, `KEYS` (a scan underneath the covers in any recent version of redis server) is the way to go. Closing out to cleanup.
