### ISSUE TITLE
StackExchange for .net framework 4.6.2 or higher

### ISSUE THREAD

**Issue by allwinrajeshpaul** [StackExchange/StackExchange.Redis#865]
Hello,

Currently we are using StackExchange.Redis version (v1.1.605) with .net framework version (v4.5.1). We are in the process to upgrade our .net framework to version (v4.6.2), while doing that we are getting the below error. But, even after upgrading to latest stackexchange.redis version available through nuget doesn't helps resolve the issue. Question is, how to achieve stackexchange.redis for .net framework v4.6.2. Please advice.

ERROR:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Some NuGet packages were installed using a target framework different from the current target framework and may need to be reinstalled. 
Visit http://docs.nuget.org/docs/workflows/reinstalling-packages for more information.  Packages affected: StackExchange.Redis.StrongName

**Comment by mgravell** [comment]
I have no idea what that nuget error means, but it sounds like nuget is unhappy. I would start by uninstalling SE.Redis from your solution, and anything else that looks suspicious - especially anything to do with "Task" or "ValueTuple" (these have been notoriously problematic for nuget, nothing to do with SE.Redis). Then: I'd close the IDE, reopen the IDE, and re-add the package.

Fundamentally, there shouldn't *actually* be anything you need to do here - the existing packages should be just fine on 4.6.2 (we use 4.6.2!) - but sometimes nuget does nuget things.

Side note: we're currently working on v2 which, among other things, will tidy up the packaging story *a lot*; it looks likely that v2 will only target netstandard2.0 - which is fine for .NET 4.6.1 or above (so: that would be fine for you). We're also fixing the strong-name/non-strong-name error of the past, so everything would move to a single package (StackExchange.Redis, which will be strong-named).

**Comment by mgravell** [comment]
Note: the link in the error message is also quite useful

**Comment by mgravell** [comment]
Closing as I don't think this is a library issue; sounds like an IDE / nuget issue, where the fix is: to uninstall and reinstall the library as per the linked guidance.
