### ISSUE TITLE
Mono - NuGet, Can we get a new version so that it works from there

### ISSUE THREAD

**Issue by jacobvp** [StackExchange/StackExchange.Redis#870]
Hi,

I've read in other issue that the current master works under Mono. I have confirmed this works by downloading a zip and building the project then manually including the .dll.

The 1.2.6 version in NuGet however gives the following error:

```
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. 
  at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl (System.Func`1[TResult] multiplexerFactory, System.IO.TextWriter log) [0x0008f] in <3c6615c26745427097f34fa88a9ec796>:0 
  at StackExchange.Redis.ConnectionMultiplexer.Connect (System.String configuration, System.IO.TextWriter log) [0x0000d] in <3c6615c26745427097f34fa88a9ec796>:0 
```

The same happens on either of the alpha releases

**Comment by mgravell** [comment]
In principle: yes; just trying to find ETA on the other things we want for the next 1.* release.

**Comment by NickCraver** [comment]
Also adding this to 2.0 milestone, so we ensure the new pipelines implementation continues working on Mono in 2.x (I'll tag it in #528 as well). I'll take on testing there as I'm already setup for it on the laptop.

**Comment by JacobvanP** [comment]
@NickCraver testing a bit with the 2.0.0-alpha35 package on nuget led to this (interesting issue):

The stringset command behaves weird on very long values (found this out when inserting a json-snippet into a key value pair)

The following is inserted using StringSet with key "PPKosten:TableInformation", a never finishing task (await never returns) occurs when using the Async variant (StringSetAsync). 
1) a string of length <= 512 **No issue**
2) a string of length == 513 **Insert but replaces last few characters with: \r\n*1\r\n$4\r\nPING**
3) a string of length >= 514 **Timeout**

I suspect this to have to do something with buffersizes, but upping my write buffer on the connection didn't seem to solve the issue.

All cases work fine when building the master branch (using mono 5.12.0.226) -> including the netstandard2.0/stackexchange.redis.dll.

The .net4.5 and .net4.6 dlls also work when build manually

**Comment by JacobvanP** [comment]
extra question since, as far as I'm aware, it's adding just a few lines to the .nuspec file:
Could we get the .net45 and .net46 libraries added to the nuget release too (could help our side with backwards compatibility).

If not not a big deal.

**Comment by NickCraver** [comment]
@JacobvanP Thanks for the info! I'll try to replicate on the laptop here soon. On the library front: we won't be adding back the `net45` or `net46` builds as with `netstandard` they *shouldn't* be needed and are a burden to support (and they lack some APIs we need). With just 1 build life is a lot simpler and more efficient in most ways. For users unable to be on a `netstandard2`+ platform, the 1.x releases will remain forever available.

**Comment by NickCraver** [comment]
StackExchange.Redis v2 is now RTM, this release should run without issue on Mono. We did end up building `net462` and `ne472` due to binding redirect and `netstandard` insanity beyond our control for the same of consumers.

Release notes are up at: https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes
NuGet up at: https://www.nuget.org/packages/StackExchange.Redis

Closing this out to cleanup, but please file an issue if you run into one!
