### ISSUE TITLE
Is a new connection created for each pub/sub channel subscribed?

### ISSUE THREAD

**Issue by shravan2x** [StackExchange/StackExchange.Redis#872]
As the title asks, is a new connection created for each pub/sub channel subscribed? How about when publishing to multiple channels?

This might be useful to add to the docs.

**Comment by NickCraver** [comment]
Nope, no new connections. As the docs already note: you create and use one `ConnectionMultiplexer` and it handles all this internally. In total there are 2 connections to redis: 1 every non-subscriber operation, and 1 more for subscriber pub/sub operations.

**Comment by shravan2x** [comment]
Interesting, are more subscriber connections created if the bandwidth is required?

**Comment by NickCraver** [comment]
@shravan2x No new connections are ever created, only restored if broken. Redis is processing them in a single-threaded-behavior style, and the client must also do so to have the order maintained. From redis's point of view, 2 connections are 2 clients. *If* we connected twice, we'd just get every message twice, or we'd be randomly choosing how to shard subscriptions and have no real knowledge of how we're balancing. Given the client and server are in the same places respectively, adding a connection isn't going to add more bandwidth unless you're in a high latency/TCP window constrained environment. If that's the case, it'd only matter for very large payloads in which case...lots of bad things are being combined and the situation should really be evaluated at a higher level before this is an issue.

**Comment by shravan2x** [comment]
This was all really good to know, could it be added to the docs?

**Comment by NickCraver** [comment]
Sure, we can look at noting the behavior with some doc updates we'll do in 2.0. Tagging it for that pass.

**Comment by mgravell** [comment]
At the moment I think this is "undefined". I agree it is something that
should be handled better. Let me refamiliarize myself with that area. I
wonder also whether the new "streams" support might be useful for your
scenario.

**Comment by NickCraver** [comment]
This is improved since #1947 - the command returns once actually subscribed (unless `FireAndForget`) and should behave in the expected way now.
