### ISSUE TITLE
Redis Remove Key By Pattern Issue

### ISSUE THREAD

**Issue by tsdev1** [StackExchange/StackExchange.Redis#873]
I am working for a project which has around 200K Keys (Redis-String Keys) generated. I need to remove keys when users are performing insert/update/delete on any product. When I am going to remove keys by pattern Scan command is taking some more time. Slowlog is logging many SCAN Command.
I thought,
1. To create multiple databases and flush database as per requirement or
2. Scan the particular database for keys and batch delete.
3. Scan the particular database for keys and delete keys one by one (using for loop).
Here, flushing database is locking redis and I am getting a timeout in Redis. Scanning keys by the pattern in the particular database are sometimes taking much time.
Below is my code:

```
var server = _connectionWrapper.GetServer(endPoint);
        try
        {
          if (ConfigItems.RedisKeyFlushBy == 1) -- Using Flush DB
          {
            server.FlushDatabase(GetDatabase(dbId));
          }
          else if (ConfigItems.RedisKeyFlushBy == 2) -- Using Batch Delete
          {
            var keys = server.Keys(database: GetDatabase(dbId));            
            try
            {
              _db.KeyDelete(keys.ToArray());
            }
            catch (Exception ex)
            {
            }
          }
          else if (ConfigItems.RedisKeyFlushBy == 3) -- Using One by One Delete
          {
            var keys = server.Keys(database: GetDatabase(dbId));
            try
            {
              foreach (var key in keys)
              {
                Remove(key);
              }
            }
            catch (Exception ex)
            {
            }
          }

        }
```

Suggest me a better approach to do this.

**Comment by mgravell** [comment]
If all this data is semantically related and can die together, then: a single redis hash. So instead of

`key = value`

you you

`key, name0 = value0, name1 = value1, ..., name200000 = value200000`

(except stored efficiently)

Your `StringGet(name)` become `HashGet(parentKey, name)`, and when you want to nuke the entire lot: `KeyDelete(parentKey)`.

Does that work for you?

**Comment by tsdev1** [comment]
Thanks for your quick response.

This will work for some keys. Some keys (10K Keys can have same timeouts).

I have the different timeout for rest of the keys. All keys have some different timeouts. So Deleting all keys together (Using Hash) will not work for me.

**Comment by mgravell** [comment]
I guess if I had to choose between the other options: FLUSHDB is the lowest
impact - pick a DB that is *just* for this data. However it won't work on
cluster, so factor that into plans.

Otherwise:
I wouldn't use ToArray when iterating Keys - I'd probably iterate I to
pages and delete in pages of (that much), without ever calling ToArray or
ToList

**Comment by tsdev1** [comment]
FlushDB is working fine for my case. Are you sure FlushDB will not block my other redis connections? If it will take some more time then I will face timeout issues in next requests.
I didn't get your comments:
**"Otherwise:
I wouldn't use ToArray when iterating Keys - I'd probably iterate I to
pages and delete in pages of (that much), without ever calling ToArray or
ToList"**

I have other keys which needs to be deleted by pattern. If I am enabling code for removing pattern then facing timeout issues. Slowlog is showing scan commands which is taking more time.
Below is my code snippet to remove by pattern keys:

```
var keys = server.Keys(database: GetDB(pattern).Database, pattern: $"{pattern}*", pageSize: 5000); // I am not sure the use of pageSize here.
_db.KeyDelete(keys.ToArray());
```

Please suggest me the proper way to remove key by patterns.

**Comment by mgravell** [comment]
That's a huge varadic key delete. I'd be more inclined to do the foreach and key-delete each one sequentially. Less blocking. You could batch it into groups of say 10 or 50, but... I guess it comes down to whether you need a single atomic delete.

**Comment by mgravell** [comment]
`pageSize` exactly matches `COUNT` as described on [the `SCAN` documentation](https://redis.io/commands/scan). SE.Redis hides the details of the `SCAN` behind an iterator, with it (pre-)fecthing the next page as required, but : increasing `pageSize` will result in fewer pages with higher impact each - the use of `foreach` will be identical either way, though. I would **not** use `pageSize : 5000` - maybe `250` is fine? changing that should drop your `slowlog` hits significantly.

**Comment by mgravell** [comment]
Use of a wildcard in the call to `Keys` will reduce the data transferred from server to client, so if you **can** filter (even if not perfect) via a wildcard here: definitely do that.

**Comment by mgravell** [comment]
I'm considering this a request for guidance that has been provided, so I'm considering this "complete". If I've missed something, let me know.

**Comment by tsdev1** [comment]
I have applied your suggested changes and now getting very less items in slowlog. We can say 10 items per hour approx. I am hoping this solution will work when we will get the double traffic in festival season, too.

**Comment by Jerome2606** [comment]
@tsdev1 Can you provide the code you are using for deleting a particular namespace ? I would be interested to look into for my case.

Thanks

**Comment by mdaijaj** [comment]
how to move all key in redis using nodejs
