### ISSUE TITLE
Error: Command cannot be issued to a slave: DBSIZE

### ISSUE THREAD

**Issue by oumantic** [StackExchange/StackExchange.Redis#876]
precondition:
1.  3 machines, 3 sentinel, 3 redis instances (1 master, 2 slaves).
2.  1 master, 2 slaves. checked the master and slave infos, they were all right.
3.  checked my sentinel info,  the master info / slaves count also right.
4.  write data to db0~db4 of master, and data have been synchronous to slaves.

use below c# code in my SDK to get Db size of redis from master server:
`internal long GetDbSize(CommandFlags flags){
            var aServer = GetServer();
            return aServer.DatabaseSize(Setting.DatabaseId, flags);   
  }
`

For db0, my c# SDK throw below exception:
Exception: StackExchange.Redis.RedisCommandException: Command cannot be issued to a slave: DBSIZE
   at StackExchange.Redis.ConnectionMultiplexer.TryPushMessageToBridge[T](Message message, ResultProcessor`1 processor, ResultBox`1 resultBox, ServerEndPoint& server)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisServer.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at Moodys3.WSPlatform.BizCore.ExcelAddin.RedisService.Common.RedisHelper.GetDbSizeFromWriteServer(String theServiceName)

But for db1~db3, it return correct number.

why it raised a error related to "slave" when i get db size from master ?
Could someone give me any suggestion or solution? thank you very much.

**Comment by Dan-Coleman** [comment]
Hi oumantic,

How did you fix this?

Dan

**Comment by mgravell** [comment]
This one must have slipped past me.when were doing all the 2.* Work. This seems odd and unexpected - I'll take a look.

**Comment by mgravell** [comment]
Sorry for delay!

**Comment by Dan-Coleman** [comment]
Hi Marc,

I found my issue, was unrelated to this. Somehow managed to get two redis servers both as slaves so when I did conn.GetServers() I got two servers both with IsSlave=true!

Perhaps a validation to check that there is at least 1 master before running the commands?

Appreciate the reply.

Dah

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mgravell** [comment]
What's confusing me, however, is that the client doesn't block this command on replicas... basically, it comes down to the `IsMasterOnly` method, which returns `false` for `DBSIZE`. So... I'm confused how you saw this *at all* ?
