### ISSUE TITLE
Weird slowness with newest (1.0.330) version when upgrading from 1.0.328

### ISSUE THREAD

**Issue by nmehlei** [StackExchange/StackExchange.Redis#88]
Yesterday I tried to update the StackExchange.Redis dependency in my azure-based web role from version 328 to 330. Following this update, the whole web application behaved extremely slow with response latencies upwards of a few seconds instead of, for example, 50ms. It took a while to find the culprit, but it only occured with version 330, not with 328. 
Is anyone else noticing problems with this version? The problem occurs only inside my azure deployment (with network-connected redis instance), not (or at least not noticeably) locally with a locally-connected redis instance. Skimming through the latest commits, I did not find anything specific that could be related to this, but it could possibly be loosely related to the timeout and connectivity changes.

**Comment by NickCraver** [comment]
@nmehlei there have been several fixes since this issue around threading - is it still an issue today?

**Comment by baywet** [comment]
Hi,
I'm still having an issue. As soon as a Task.Wait() is called within the context of an asp.net mvc 5 application, it hangs. This is probably because of a combination of the way the Task Scheduler is implemented for asp.net and of the communication thread in the connector.
The reason I'm doing that is because we still have no async action filter in mvc5 and I want to cache auth related stuff.

**Comment by NickCraver** [comment]
@baywet a Tas.Wait() can easily call deadlocks, especially in an ASP.NET application. You want to `async` all the way up the chain here for proper handling. If you *must* call synchronously to SE.Redis, then use the synchronous APIs rather than waiting on the asynchronous APIs.

**Comment by baywet** [comment]
Hi @nickcraver,
Thanks for the answer. That's what I ended up doing. The drawback is I have twice the methods for my caching infrastructure service but that's fine.

**Comment by NickCraver** [comment]
@baywet Thanks for the update, closing this out to cleanup :)
