### ISSUE TITLE
removing single unhealthy server is possible?

### ISSUE THREAD

**Issue by makkaba** [StackExchange/StackExchange.Redis#881]
situation:
- ASP.NET server app connected with 3 replication redis servers.(called A, B, C)
- one replication server C is under not working status.

want to do:
- remove connection only with C server endpoint while running.

is it possible?

**Comment by mgravell** [comment]
The inelegant but simple answer might be : swap the multiplexer for one
with a configuration that doesn't include C. I assume you're looking for
more elegant than that? However: is it actually causing a problem having C?
Unless I'm mistaken, the worst that should happen here is that the
heartbeat code keeps trying to connect to C,. It no commands should be
routed there. Is something worse happening?

**Comment by makkaba** [comment]
thanks for reply.

you mean `StackExchange.Redis` provides heartbeat check to every server regularly?
and if heartbeat is fails, no command will not be routed to C server. right?

**Comment by mgravell** [comment]
Ah, right. Yes, the library tries to understand which connections are "up"
and won't send messages to a server that it knows isn't responding.

**Comment by makkaba** [comment]
thanks a lot! 
i will close this issue.
