### ISSUE TITLE
ConnectionCounters.ResponsesAwaitingAsyncCompletion is very big

### ISSUE THREAD

**Issue by pengweiqhca** [StackExchange/StackExchange.Redis#882]
Sometime when my asp.net application load very low, but ConnectionCounters.ResponsesAwaitingAsyncCompletion is very big(>50), all redis operation very slow. What reason is caused?

{"PendingUnsentItems":0,"ResponsesAwaitingAsyncCompletion":73,"SentItemsAwaitingResponse":0,"TotalOutstanding":73}

MinThread 600 600
CPU < 30%
Threading < 200
Memory < 40%
Concurrent Request < 10

**Comment by pengweiqhca** [comment]
1.2.6

**Comment by mgravell** [comment]
That is probably due to task activation stealing a thread. The code
involved here has been rewritten for 2.0 and works very differently from
2.0 onwards, which should be available soon - see
https://github.com/StackExchange/StackExchange.Redis/issues/871

**Comment by mgravell** [comment]
Given the complete rewrite of this area, I'm going to concluded that we're not going to do any more on this in 1.*, and that this is resolved in 2.* (to be released soon). See the linked post for more detail.
