### ISSUE TITLE
better documentation on optimistic locking with transactions

### ISSUE THREAD

**Issue by eli-darkly** [StackExchange/StackExchange.Redis#885]
Hi-
I'm having some trouble understanding how `CreateTransaction` and `AddCondition` are supposed to be used to get the equivalent of the following Redis usage:

1. Set a WATCH on hash key X.
2. Start a transaction (MULTI).
3. Read subkey Y of hash X and unmarshal the value into some object.
4. If the object's "version" property is less than Z, update the object (HSET) to version Z.
5. Try to execute the transaction.

In this example, I want the transaction to fail if key X has been modified in any way since the WATCH. But I've had no luck trying to implement this with StackExchange.Redis, because (as far as I can tell) the WATCH does not get issued at the time I open the transaction; instead, the library seems to wait until I call `Execute` and then do the WATCH, MULTI, HSET, and EXEC all at that point. The result is that if someone else modified the key after step 3, I won't know about it.

**Comment by mgravell** [comment]
This is as expected. Essentially, the problem is your step 3. You cannot get **any** value inside a MULTI. It simply isn't possible: the server will respond QUEUED. The way SE.Redis shims over this is by allowing assertions to be verified inside a WATCH, which is what Conditions allows, but: it can't afford to allow you to block the pipe while doing this, so you can't issue arbitrary operations - it needs to be things that SE.Redis has known implementations for.

To be honest, MULTI/EXEC is hard. It is complicated, and non-intuitive. Most people find it easier to write Lua scripts instead, via ScriptEvaluate. You can do most things in scripts much easier than you could in MULTI/EXEC, while still having uninterrupted server time so you don't need to worry about competing commands. So my advice here would be : use ScriptEvaluate instead.

**Comment by eli-darkly** [comment]
Sorry... I wrote out my example wrong, steps 2 and 3 should be swapped. I'm not reading the value inside of the transaction - but I am reading it after I do the WATCH. My understanding was that any external change to the key after I set the WATCH should cause the subsequent transaction to fail; if that's not right, then I'm not sure how WATCH would be useful for anything at all.

**Comment by eli-darkly** [comment]
As for using a Lua script - I think there are two problems with that in our use case. One is that (at least in our current architecture) the version property that we use for optimistic locking is inside a JSON object, so we would need to be able to parse JSON inside of Lua, which does not seem to be straightforward. The other is, Lua scripts aren't guaranteed to run atomically with respect to other people's Redis connections, are they? That is, if I have a script that says "1. get the old value, 2. update the value if the version property < X" I would still need to be able to know that no one can get in between 1 & 2.

**Comment by eli-darkly** [comment]
In any case, I see what you're saying about the problem with using WATCH on a shared connection. I really wish StackExchange.Redis provided the option of using a connection pool instead, but oh well.

**Comment by mgravell** [comment]
Right; so - with the revised step order, the closest you can get in SE.Redis is:

1. Get the existing value and make a decision (update the object (HSET) to version Z)
2. Set a WATCH on the key
3. Get the existing value and ensure it is still the value we thought it was in 1
4. Start a transaction (MULTI).
5. Update the object (HSET) to version Z.
6. Try to execute the transaction.

Noting that if the assertion from fails, SE.Redis will abort the transaction, and if the key is touched between 2 and 6, redis will abort the transaction. In SE.Redis terms this is:

```
bool success;
do {
  var someVal = db.HashGet(...); // 1 (not shown: making some decision based on that value)
  var tran = db.CreateTransaction(); // primes for 4 (not issued yet)
  tran.AddCondition(Condition.HashEquals(...)); // primes for 2 and 3 (not issued yet)
  tran.HashSetAsync(....); // primes for 5 (not issued yet)
  success = tran.Execute(); // issues 2, 3, 4, 5, and 6
} while (!success);
```

So; that's "how" - does that clarify things? On your second point: Lua scripts run atomically - see https://redis.io/commands/eval#atomicity-of-scripts, or to repeat it here:

> Redis guarantees that a script is executed in an atomic way: no other script or Redis command will be executed while a script is being executed. This semantic is similar to the one of MULTI / EXEC. From the point of view of all the other clients the effects of a script are either still not visible or already completed.

**Comment by mgravell** [comment]
> I really wish StackExchange.Redis provided the option of using a connection pool instead, but oh well.

Maybe we can. It won't be for 2.0, but 2.1 maybe? Note: this is something I've been thinking about, but haven't put any code down. It might not happen at all.

https://github.com/StackExchange/StackExchange.Redis/issues/886

**Comment by eli-darkly** [comment]
Thanks for the detailed reply! That does clear things up for me a lot - I had gotten hung up on wanting to check for that specific version property in the JSON, but checking for equality of the whole object with `HashEquals` should work just as well. Also, I don't know where I got the idea that Lua scripts were not atomic, so that's a relief (although I still want to avoid Lua if possible in this case).
