### ISSUE TITLE
can use StackExchange.Redis  in .net core 2.1 mvc?

### ISSUE THREAD

**Issue by MulderLiu** [StackExchange/StackExchange.Redis#892]
It's good to use a subscription in a console program

The same config configuration can't subscribe to data at MVC

```
   using (ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("192.168.2.XX:6379,password=XX"))
                {
                    ISubscriber sub = redis.GetSubscriber();   

                    sub.Subscribe("XX", (c, m) =>
                    {
                        // no data
                    });
                }
```

**Comment by mgravell** [comment]
The callback from `Subscribe` will only be invoked as data comes in (via `publish` at the redis level) matching the `xx` channel. However, if you dispose (via `using`) the multiplexer immediately, all the connections will be severed long before there's a chance for data to arrive. The multiplexer must be retained and left open for `Subscribe` to work. It is fine to dispose it, but only when you're actually done with it.

**Comment by MulderLiu** [comment]
@mgravell  Thank you for your answer. I have removed "using" and now work OK !  thanks

**Comment by NickCraver** [comment]
Glad you're sorted! Closing out to cleanup :)
