### ISSUE TITLE
Performance 1.2.6 vs 2.0.0-alpha.206

### ISSUE THREAD

**Issue by paveliak** [StackExchange/StackExchange.Redis#898]
I wrote simple test program that writes 100K keys into a Redis running on localhost and then queries them back in random order. With 1.2.6 write and read part each completes in about 5 seconds on my machine. When using 2.0 alpha execution time doubles to ~11 seconds (for each part).

Do you have any performance results from the 2.0? How does is stack against the 1.2.6?

Thanks,
Pavel

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using StackExchange.Redis;

namespace RedisTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var mux = ConnectionMultiplexer.Connect("localhost:6379");
            var db = mux.GetDatabase();

            int max = 100000;

            var sw = Stopwatch.StartNew();

            for (int i = 0; i < max; ++i)
            {
                db.StringSet(i.ToString(), i);
            }

            Console.WriteLine($"DONE {sw.ElapsedMilliseconds}");

            Console.WriteLine("Sampling");

            sw.Restart();
            var rnd = new Random();

            for (int i = 0; i < max; ++i)
            {
                var r = rnd.Next(0, max - 1);

                var rv = db.StringGet(r.ToString());
                if (rv != r)
                {
                    throw new Exception($"Unexpected {rv}, expected {r}");
                }
            }

            Console.WriteLine($"DONE {sw.ElapsedMilliseconds}");
        }
    }
}
```

**Comment by mgravell** [comment]
my testing locally has reliably shown similar or better performance in 2.0, but I'll run your example above when I get a moment. However! An important question: where is your server in relation to the client? is this cloud? WAN? LAN? localhost?

**Comment by paveliak** [comment]
It's on localhost running the server from Redis-64 nuget package.

**Comment by mgravell** [comment]
Additional question: what runtime are you using, so I can try to repro?
.net framework? (If so, which version?) Or netcoreapp? (Ditto re version )

**Comment by paveliak** [comment]
My VStudio project targets .NET Framework 4.6.1

**Comment by mgravell** [comment]
Current numbers do indeed reflect a perf regression; let's keep this open and we can have another look at it; numbers:

v1.2.7-alpha-00002

      Method |  Job | Runtime |     Mean |      Error |    StdDev |     Op/s |  Gen 0 |  Gen 1 | Allocated |
------------ |----- |-------- |---------:|-----------:|----------:|---------:|-------:|-------:|----------:|
        Load |  Clr |     Clr | 70.43 us |  4.7195 us | 1.2259 us | 14,199.1 | 0.0300 |      - |     241 B |
   LoadAsync |  Clr |     Clr | 65.54 us |  0.7460 us | 0.1938 us | 15,258.1 | 0.0600 | 0.0100 |     398 B |
      Sample |  Clr |     Clr | 60.35 us |  2.9537 us | 0.7672 us | 16,570.7 | 0.0300 |      - |     257 B |
 SampleAsync |  Clr |     Clr | 44.80 us |  1.0942 us | 0.2842 us | 22,322.1 | 0.0600 | 0.0100 |     422 B |
        Load | Core |    Core | 72.39 us |  5.7257 us | 1.4872 us | 13,813.6 | 0.0600 |      - |     144 B |
   LoadAsync | Core |    Core | 81.61 us | 10.3804 us | 2.6963 us | 12,254.0 | 0.0800 |      - |       0 B |
      Sample | Core |    Core | 64.41 us |  6.5475 us | 1.7007 us | 15,524.8 | 0.0600 |      - |     200 B |
 SampleAsync | Core |    Core | 58.75 us |  7.9246 us | 2.0584 us | 17,022.6 | 0.0800 |      - |       0 B |

net47, v2.* (head)


      Method |  Job | Runtime |     Mean |     Error |    StdDev |     Op/s |  Gen 0 |  Gen 1 | Allocated |
------------ |----- |-------- |---------:|----------:|----------:|---------:|-------:|-------:|----------:|
        Load |  Clr |     Clr | 96.93 us | 19.110 us | 4.9637 us | 10,316.9 | 0.0500 |      - |     375 B |
   LoadAsync |  Clr |     Clr | 91.28 us |  3.617 us | 0.9394 us | 10,955.0 | 0.0800 | 0.0100 |     534 B |
      Sample |  Clr |     Clr | 85.18 us | 17.755 us | 4.6117 us | 11,739.8 | 0.0500 |      - |     374 B |
 SampleAsync |  Clr |     Clr | 72.58 us |  4.737 us | 1.2303 us | 13,777.0 | 0.0800 | 0.0100 |     560 B |
        Load | Core |    Core | 98.84 us |  7.999 us | 2.0777 us | 10,117.0 | 0.0300 |      - |     192 B |
   LoadAsync | Core |    Core | 89.45 us |  1.668 us | 0.4332 us | 11,180.0 | 0.0500 |      - |       0 B |
      Sample | Core |    Core | 84.55 us | 20.619 us | 5.3558 us | 11,827.8 | 0.0300 |      - |     160 B |
 SampleAsync | Core |    Core | 71.92 us |  6.781 us | 1.7612 us | 13,904.2 | 0.0500 |      - |       0 B |

**Comment by mgravell** [comment]
updated numbers - both sets are updated to reflect same test conditions, but starting to look much more comparable, and I know there's something I'm still chasing down in the async completion path:

v1

|      Method |  Job | Runtime |     Mean |      Error |    StdDev |     Op/s |  Gen 0 |  Gen 1 | Allocated |
|------------ |----- |-------- |---------:|-----------:|----------:|---------:|-------:|-------:|----------:|
|        Load |  Clr |     Clr | 79.91 us | 26.0719 us | 6.7721 us | 12,513.8 | 0.0300 |      - |     242 B |
|   LoadAsync |  Clr |     Clr | 75.45 us |  1.3129 us | 0.3410 us | 13,253.0 | 0.0600 | 0.0100 |     397 B |
|      Sample |  Clr |     Clr | 96.83 us | 24.8231 us | 6.4477 us | 10,327.8 | 0.0300 |      - |     257 B |
| SampleAsync |  Clr |     Clr | 57.82 us |  6.2050 us | 1.6117 us | 17,295.2 | 0.0600 | 0.0100 |     422 B |
|        Load | Core |    Core | 82.94 us |  8.8931 us | 2.3100 us | 12,057.6 | 0.0600 |      - |     144 B |
|   LoadAsync | Core |    Core | 79.69 us |  0.9691 us | 0.2517 us | 12,548.9 | 0.0800 |      - |       0 B |
|      Sample | Core |    Core | 77.48 us |  1.8179 us | 0.4722 us | 12,906.1 | 0.0600 |      - |     200 B |
| SampleAsync | Core |    Core | 73.79 us |  6.6549 us | 1.7286 us | 13,551.9 | 0.0800 |      - |       0 B |

v2

|      Method |  Job | Runtime |     Mean |      Error |     StdDev |     Op/s |  Gen 0 |  Gen 1 | Allocated |
|------------ |----- |-------- |---------:|-----------:|-----------:|---------:|-------:|-------:|----------:|
|        Load |  Clr |     Clr | 79.80 us |  9.7081 us |  2.5216 us | 12,531.5 | 0.0600 |      - |     402 B |
|   LoadAsync |  Clr |     Clr | 89.28 us |  4.8278 us |  1.2540 us | 11,200.5 | 0.0800 | 0.0100 |     560 B |
|      Sample |  Clr |     Clr | 94.56 us | 65.3176 us | 16.9660 us | 10,574.9 | 0.0600 |      - |     401 B |
| SampleAsync |  Clr |     Clr | 72.24 us |  0.9591 us |  0.2491 us | 13,843.7 | 0.0900 | 0.0100 |     585 B |
|        Load | Core |    Core | 88.23 us | 16.9317 us |  4.3980 us | 11,333.6 | 0.0300 |      - |     192 B |
|   LoadAsync | Core |    Core | 83.28 us |  7.0508 us |  1.8314 us | 12,007.4 | 0.0500 |      - |       0 B |
|      Sample | Core |    Core | 96.46 us | 36.3542 us |  9.4429 us | 10,367.0 | 0.0300 |      - |     160 B |
| SampleAsync | Core |    Core | 74.10 us | 18.2159 us |  4.7315 us | 13,496.0 | 0.0500 |      - |       0 B |

**Comment by NickCraver** [comment]
@mgravell another perf related - can we close this out? Not sure if we still have the logic for the number anywhere but it'd be awesome if we could do apples on the latest client. Happy to run it here if so, but won't be apples...
