### ISSUE TITLE
StackExchange.Redis and Elasticcache Redis

### ISSUE THREAD

**Issue by kludgeDan** [StackExchange/StackExchange.Redis#906]
Hello,

I was wondering if this was compatible with AWS Elasticcache Redis? I have tried to connect to a cluster I have setup in AWS from a console app which is running in an EC2 instance (both are in the same security group) with no success. Here is a sample of the repo I have

 public class RedisRepository<T> : IRedisRepository<T>
        where T : Entity
    {
        private static readonly Lazy<ConnectionMultiplexer> LazyConnection;

        static RedisRepository()
        {
            ConfigurationOptions option = new ConfigurationOptions
            {
                SyncTimeout = 500000,
                EndPoints =
                {
                    { "xxx.cache.amazonaws.com", 6379 }
                },
                AbortOnConnectFail = false
            };

            LazyConnection = new Lazy<ConnectionMultiplexer>(() => ConnectionMultiplexer.Connect(option));
        }

        public static ConnectionMultiplexer Connection => LazyConnection.Value;

        public static IDatabase RedisCache => Connection.GetDatabase();

        public bool Add(T entity)
        {
            var result = RedisCache.StringSet(entity.Id.ToString(), JsonConvert.SerializeObject(entity));
            return result;
        } 

Here is the exception I am gettting:
Starting
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: SET 8f7d6d5b-663d-4102-a860-eeba8a75d45f; UnableToConnect on xxx.cache.amazonaws.com:6379/Interactive, origin: ResetNonConnected, input-buffer: 0, outstanding: 0, last-read: 5s ago, last-write: 5s ago, unanswered-write: 97036s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 5s ago ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on redisdev-001.redisdev.xm7mgz.use1.cache.amazonaws.com:6379/Interactive, origin: ResetNonConnected, input-buffer: 0, outstanding: 0, last-read: 5s ago, last-write: 5s ago, unanswered-write: 97036s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 5s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2027
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at Infrastructure.Redis.RedisRepository`1.Add(T entity) in c:\users\dfavano\source\repos\RedisConsole\RedisConsole\RedisRepository.cs:line 34
   at RedisConsole.Program.Main(String[] args) in c:\users\dfavano\source\repos\RedisConsole\RedisConsole\Program.cs:line 16

I am not sure why it's adding interactive at the end of the cluster endpoint.
I can supply more or put the whole console app up in github if needed. The app is written using Asp Core 2.1.

Thanks!

Dan

**Comment by martincostello** [comment]
It is compatible, we use it in production applications in AWS.

You may need to set `ConfigurationOptions.Ssl` to true to establish a connection if it has been setup to only support connection over TLS.

**Comment by NickCraver** [comment]
Glad you're sorted :) Closing out to cleanup!

**Comment by rahulNandan** [comment]
Hi kludgedan,

I am also facing similar issue in our aws environment will you be able to tell me what all port were set in the SG to get this working?
