### ISSUE TITLE
Thread freezed on "ConnectionMultiplexer.GetDatabase().ListLeftPop(RedisKey)" after several empty retrieves

### ISSUE THREAD

**Issue by Ryujose** [StackExchange/StackExchange.Redis#908]
Hello community.

I'm performing some tests to check the realiability and I've seen on one of my tests that after performing 35 petitions with "ConnectionMultiplexer.GetDatabase().ListLeftPop(RedisKey)" with empty results the thread was freezed in a console test with a for statement.

I don't know why this happened, for the moment I'm going to lua with ScriptEvaluate.

Note: The server was up and running.

Regards.

**Comment by mgravell** [comment]
It definitely wasn't ListLeftPopAsync? (I'm trying to think how such a scenario could happen...)

**Comment by NickCraver** [comment]
@Ryujose can you please share the code that had this issue? Like Marc, my gut reaction is this seems like an `async` hang/deadlock somewhere...but we'd need to see some code to help!

**Comment by Ryujose** [comment]
Hello @NickCraver. Sorry for the late update.

For what I remember we had done a simple implementation with this method. 

The only important thing as observation that I can tell you is that it was used with a lot of hits, because data is coming from a communication protocol with a framework named QuickFix.

Maybe if the method is stressed it will happen the same?

Note: The app is up and running without problem with ScriptEvaluate.

**Comment by NickCraver** [comment]
I didn't catch the follow-up message here - going to close this out to tidy since it was likely very implementation specific and...we don't have the specifics, combined with the fact you're up and running.

For anyone hitting something like this: please open an issue with your usage example and we'll take a look!
