### ISSUE TITLE
StackExchange.Redis.ConnectionMultiplexer Exceptions on APP Pool Recycle

### ISSUE THREAD

**Issue by cameronharp** [StackExchange/StackExchange.Redis#911]
# Issue
IIS has a default for recycling the APP Pool every 29 hours. When the APP Pool is recycled our API becomes unworkable till we force an IIS reset (after the APP Pool refresh). Once we do a IIS rest the API works just fine till the next 29 hour recycle. We have taken dump files right after the APP Pool recycle and sent them over to Microsoft. They have reviewed the files and came back with the different exceptions.

## Configuration
Currently we are running with the following setup.

- IIS 10
- Windows SVR 2016
- .NET Core 1.1
- StackExchange.Redis.StrongName, nuget package version - 1.0.333

## Exceptions
Below is the response we got back from Microsoft of the different exceptions being thrown during the time of the APP Pool recycle and the IIS rest.

![stackexchange-redis-exceptions](https://user-images.githubusercontent.com/1463002/43854388-f3f43026-9aff-11e8-98e0-066ccf06c8d2.png)

**Comment by mgravell** [comment]
Is this a local redis? Or a cloud / hosted redis? Is TLS involved? Note:
the 2.0 work is imminent, which radically overhauls the network layer
specifically to improve .net core and TLS stability (either individually or
in combination).

**Comment by cameronharp** [comment]
I'm sorry I forgot to give more details in my issue. As for the redis cluster (High availability clusterd redis enterprise version) we are using it is on-prem so the cluster exists in the same data center but not on the same machine. TLS is not invloved on the communication from the API to redis but it is involved on the requests from the clients to the API. Please let me know if you need more details and I can provide whatever you need.

**Comment by NickCraver** [comment]
I noticed you're using a *very* old version of the library. 1.0.333 was released almost 4 years ago. A *lot* of fixes and changes have gone in (even more true to the upcoming 2.0 release available in alpha now).

If you can upgrade to the latest version (or 2.0 if able - it's strongly named in the main `StackExchange.Redis` package now). Realistically, there will be no fixes for the 1.0.333 release given it's been obsoleted many times now :)

**Comment by NickCraver** [comment]
I'm going to close this out as long-since-resolved, but if you're still have issues on a current version of the library I'm happy to reopen :)
