### ISSUE TITLE
Nuget v2alpha.281 broken with Pipeline sockets Unofficial 0.2.1-alpha90

### ISSUE THREAD

**Issue by imtrobin** [StackExchange/StackExchange.Redis#919]
Reporting, updated Pipeline and getting an error on connect 

Exception:Method not found: 'Void Pipelines.Sockets.Unofficial.DedicatedThreadPoolPipeScheduler..ctor(System.String, Int32, Int32, Int32, System.Threading.ThreadPriority)'.

Robin

**Comment by imtrobin** [comment]
I noticed there's a redis alpha435, I updated to that, and now there's an unable to load System.IO.Pipelines 4.0.0.0  error.

The above error is a dotnet 4.6.1 framework. 
I could get it working fine a net core 2.0 console project,

**Comment by mgravell** [comment]
The "current" build is [2.0.0-alpha.436](https://www.nuget.org/packages/StackExchange.Redis/2.0.0-alpha.436) which takes [0.2.1-alpha.92](https://www.nuget.org/packages/Pipelines.Sockets.Unofficial/0.2.1-alpha.92) of the pipelines lib. 

I'll spin up a 4.6.1 test here, but: it is entirely possible that baseline is 4.6.2 - isn't that the minimum for netstandard 2.0?

**Comment by mgravell** [comment]
cannot repro; it seems to work fine for me on net461:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.0.0-alpha.436" />
  </ItemGroup>
</Project>
```

with

```c#
static class Program
{
    static void Main()
    {
        using (var muxer = StackExchange.Redis.ConnectionMultiplexer.Connect("127.0.0.1"))
        {
            var db = muxer.GetDatabase();
            db.KeyDelete("foo");
            db.StringIncrement("foo");
            db.StringIncrement("foo");
            System.Console.WriteLine(db.StringGet("foo"));
        }
    }
}
```

(outputs `2`)

---

If I change to `net46`, then I get `NU1202`:

> Package StackExchange.Redis 2.0.0-alpha.436 is not compatible with net46 (.NETFramework,Version=v4.6). Package StackExchange.Redis 2.0.0-alpha.436 supports: netstandard2.0 (.NETStandard,Version=v2.0)

Can you re-check please?

**Comment by imtrobin** [comment]
Hi, I did a new test project, and it works fine.  I finally found the issue, nuget somehow added the wrong HintPath to the dll, all the installing and uninstalling must have confused it, I did manual hand edit until I compared with the new project, and found the missing ../
