### ISSUE TITLE
Swallowed exception when unable to connect

### ISSUE THREAD

**Issue by imtrobin** [StackExchange/StackExchange.Redis#921]
Hi, this is a library design issue. I see that the library catch the exception, but did not rethrow it.

I had a new project setup ,that was incorrect due to nuget, the actual problem when running was this exception but it was swallowed into Socket failure (which took me quite some time to figure why).

{"Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}

Also, the way the error callbacks setup is abit strange, I have to do Connect first before setting the callback, which means I could potentiall miss them out. Shouldn't it be setup callback first, then Connect.

```redis = ConnectionMultiplexer.Connect (config);
    // I could miss these callbacks.
    redis .ErrorMessage += ((object sender, RedisErrorEventArgs args)=> {});

Using 2.0.0 alpha 436

**Comment by mgravell** [comment]
Now I'm scratching my head trying to remember if/why we have a dependency on numerics. Thanks for the report, will look.

**Comment by NickCraver** [comment]
hmm, looks like [`System.IO.Pipelines`](https://www.nuget.org/packages/System.IO.Pipelines/) -> [`System.Memory`](https://www.nuget.org/packages/System.Memory/) -> [`System.Numerics.Vectors`](https://www.nuget.org/packages/System.Numerics.Vectors/) ...didn't expect that one either...

**Comment by imtrobin** [comment]
sorry I spoke too soon, my old project 4.6.1 also did not connect now, hmm. maybe the redis server is hosted after I start/stop too many times.

**Comment by mgravell** [comment]
I need to check whether if we add an explicit dependency rather than transitive dependencies, that allows the tooling to generate the right binding redirects. Need to play with it later.

**Comment by imtrobin** [comment]
Some more findings,
1. My old 4.6.1 project, works on Debug, not release
2. The new 4.6.1 sample, does not work on both debug/release
3. new dotnet core 2.1 sample, works fine on both debug/release

**Comment by mgravell** [comment]
Re the binding issue: apparently our best bet for fixing that is to add a net461 target, which ... is annoying. The error should be more obvious, though.
