### ISSUE TITLE
ConnectionRestored not fired 2.0.0alpha436

### ISSUE THREAD

**Issue by imtrobin** [StackExchange/StackExchange.Redis#922]
Hi, I'm doing a simple single server redis test. I can get two ConnectionFailed events when I stop the server, but when I start the redis again, I do not get ConnectionRestored  callbacks.  IsConnected returns true, and I can publish but no ConnectionRestored callbacks. Is that normal?

My config, 2.0.0alpha436
```
config.AbortOnConnectFail = true;
config.KeepAlive = 10;
config.SyncTimeout = 1000;
config.ReconnectRetryPolicy = new ExponentialRetry (5000); 
```

**Comment by mgravell** [comment]
Possibly we accidentally neutered this one when we were adding the
`[Conditional(...)]` to our trace events. I'll check later, thanks.

**Comment by imtrobin** [comment]
issue fixedwith 2.0.495,

**Comment by imtrobin** [comment]
Sorry, issue still present with 2.0.495

**Comment by mgravell** [comment]
then again I say:

> I can't repro this; I've added a test to specifically target this based on your code, and it works fine. Do you have any additional context that might help me investigate this?

**Comment by imtrobin** [comment]
Sample here.

https://filedn.com/l3TGy7Y83c247u0RDYa9fkp/temp/redis/testredis.zip

 I manually stop/start the redis server.

**Comment by NickCraver** [comment]
This whould be fixed in latest (verified locally just now) - is anyone hitting this in 2.0.601? Apologies for not follow-ing up on this earlier...I thought we had addressed the issue on it.
