### ISSUE TITLE
IProfiler missing in 2.0 and/or Profiling.md Needs Update

### ISSUE THREAD

**Issue by chrishiestand** [StackExchange/StackExchange.Redis#933]
Because of network issues when StackExchange.Redis 1.2.6 was consumed and run in linux dotnet, I am trying to test building against the pre release 2.0 pkg to see if the network issues are resolved.

However I can't currently compile because `IProfiler` from 1.2.6 is not available in 2.0. I'm assuming this is on purpose? If so, it would be great if the Profiling.md docs were updated to make the migration easier. https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Profiling.md

Apologies if I'm missing something obvious, I'm not a dotnet developer :-).

**Comment by mgravell** [comment]
You're absolutely right - we need to be much more explicit about this. I have split v1/v2, with the original page now just being a bridge to both. The v2 documentation is here: https://stackexchange.github.io/StackExchange.Redis/Profiling_v2.html

**Comment by chrishiestand** [comment]
Thanks @mgravell. That might be the fastest issue resolution I've experienced. Bravo and huzzah!
