### ISSUE TITLE
Why ISubscriber.Unsubscribe can throw an AggregateException?

### ISSUE THREAD

**Issue by lukas-ais** [StackExchange/StackExchange.Redis#934]
I found, that the implementation of ISubscriber.Unsubscribe may throw an `AggregateException` in case of communication issue with the Redis database.
For me, this is unexpected.

I have the following questions:

1. Is it ok for you (according your design) that an `AggregateException` is thrown? I would expected to receive only `RedisExceptions` in case of communication issues.
2. Do you plan to list expected exception in your API documentation? It would be great to have such list.

**Comment by mgravell** [comment]
agree that this isn't necessarily expected; have added a tweak that should limit this to scenarios where it can't be avoided (multiple inners, for example)

**Comment by bitbonk** [comment]
@mgravell Isn't that change made in 2b16da4 still somewhat incomplete? When I make a synchronous call to  `ISubscriber.Unsuscribe()` I don't think I'd ever expect an `AggregateException` even if there are multiple inner exceptions. I would expect a `RedisException`  (or derivate thereof) to be thrown (probably with the `AggregateException` as the inner exception).

**Comment by mgravell** [comment]
Not everything should be a redisexception. I can't comment on whether your
should be without hearing what exceptions (inside the aggregate) you're
currently seeing.
