### ISSUE TITLE
NRediSearch AggregationRequest fluent API issues

### ISSUE THREAD

**Issue by meybosdavy** [StackExchange/StackExchange.Redis#935]
Issue 1: 
To my opinion the fluent api executing should follow the order of the way it is build.

Eg: 
```
new AggregationRequest(query)
.Apply("projection", "alias1")
.Apply("projection", "alias2")
.GroupBy("@alias2", Reducers.Count().As("alias3"))
```

Now this is not the case. GROUPBY is always set in the execute message before APPLY.

Issue 2:
Also in AggregationRequest.cs in the SerializeRedisArgs method, I believe the rule
```
args.Add("APPLY".Literal());
```
should be inside the foreach
```
foreach (var e in _projections)
```
in case you want to use multple APPLY actions, like in the example above.

**Comment by mgravell** [comment]
Ultimately, NRediSearch is a 1:1 port of the JRediSearch API, trying to maintain the same expectations.

If I've failed at applying the same convention (so: the two are out of sync), I'd be very happy to fix them. But: I intentionally *don't* want much deviation between them. So; if this *isn't* a "behaves differently to JRediSearch", then: I'd rather this was discussed in the context of JRediSearch, with NRediSearch taking the lead from there.

Does that make sense?

So: is this a deviation from JRediSearch?

**Comment by meybosdavy** [comment]
Ok, I didn't know that. I understand completly. I've compared with JRediSearch and it is indeed the same.
I'll be closing this issue and will take the discussion over there.

**Comment by mgravell** [comment]
perfect; keep me informed of any outcomes from discussions there; very happy to adjust *to keep in sync*
