### ISSUE TITLE
Large Memory Footprint. Possible Memory Leak

### ISSUE THREAD

**Issue by cushind** [StackExchange/StackExchange.Redis#936]
I've been running an asp.net core app with StackExchange.Redis v1.2.6 and I've noticed that the app has a large memory footprint related to the number of concurrent requests and traffic. We are running the app on Kubernetes and scale on memory utilization. After heavy traffic our hpa scales up like expected. But each .net core app grows in memory utilization after continued traffic and the hpa will never scale back down. Our service must be able to handle about 50 concurrent requests.

I've noticed byte[] are allocated corresponding to the number of concurrent requests, and they take up a large amount of memory.

Results from profiling on windows after hitting the service with traffic:

- 5 Concurrent Requests:
![5_concurrent_requests](https://user-images.githubusercontent.com/35702025/44921125-e8128a80-acfe-11e8-8946-ec82d6c5f474.PNG)

- 30 Concurrent Requests:
![30_concurrent_requests](https://user-images.githubusercontent.com/35702025/44921148-f660a680-acfe-11e8-9a6d-0b5097291317.PNG)

Snapshots growing with continued traffic:
![snapshots](https://user-images.githubusercontent.com/35702025/44921189-155f3880-acff-11e8-9e78-bd60885cb295.png)

Code snippet from Startup.cs using dependency injection:
```
services.AddSingleton<Lazy<IConnectionMultiplexer>>( cli => 
{
    var options = cli.GetService<IOptions<MyOptions>>().Value;
    string redisConnectionString = options.RedisConnectionString;

    try {
        // Admin needed to clear cache.
        Lazy<IConnectionMultiplexer> lazyConnection = new Lazy<IConnectionMultiplexer>(() =>
        {
            return ConnectionMultiplexer.Connect($"{redisConnectionString}, allowAdmin=true");
        });

        return lazyConnection;
    }
    catch (Exception e)
    {
        _logger.LogError($"Could not connect to redis cache: {e.Message}");
    }
    return null;
});
```

Is this the expected behavior of StackExchange.Redis or am I misunderstanding the results somehow? Why are these byte arrays hanging around after the service has responded to all requests?

Let me know if you need more details. Thanks.

**Comment by cushind** [comment]
Closed because duplicate of https://github.com/StackExchange/StackExchange.Redis/issues/844. This seems to still be an issue in 1.2.6

**Comment by mgravell** [comment]
You'll be pleased to hear that 2.* should behave very differently here - we
don't do any ahead-of-time encoding, so : no extra byte arrays are
allocated; 2.* also makes extensive use of pooled buffers on the receive
loop. Lots of gains. I was expecting to release 2.* this week, but I held
off while I chased down a few final things.

**Comment by cushind** [comment]
@mgravell Awesome thank you. I'll switch over to 2 at that time. For now we have workarounds to resolve the issue.

**Comment by AntyaDev** [comment]
Hi @gitclonedcush 
What was your workaround?

**Comment by johnny-ark** [comment]
interested as well, same issue

**Comment by mgravell** [comment]
On the general RedisValue / byte[] usage: there is an alternative API in some cases - for example StringGetLease, which when used correctly (remembering to dispose etc): is roughly allocation-free. I you're hitting pain from the internal IO layer: I'm working on that currently.
