### ISSUE TITLE
Possible memory leak in Ping

### ISSUE THREAD

**Issue by dwilliss** [StackExchange/StackExchange.Redis#937]
We're using a Steeltoe.Connector to connect to Redis.  Part of this provides an IHealthContributor which gets called every 30 seconds and calls the Ping method on a RedisDatabase object.  This is causing a memory leak in our programs.  If I comment out the call to Ping in the Steeltoe health contributor, the memory leak goes away.

I looked at the code for what Ping does and nothing jumped out at me, but I'm not familiar enough with this code.

**Comment by dwilliss** [comment]
I should mention: this is using version 1.2.6.  I also tried 1.2.7-alpha-00002.

**Comment by mgravell** [comment]
Question: is the connection already existing and reused? Or are you creating a new connection per ping? Is it possible to see the core that you're running that does this ping? Also: what symptom are you seeing that makes you suspect a memory leak?

**Comment by dwilliss** [comment]
In Cloud Foundry Apps Manager, there's a button to view metrics which charts memory usage, cpu and a few other things.  I'd send a screenshot, but I'm at home now and only have access from my work computer.  Anyway, with the Redis health contributor enabled, the memory graph looks like a sawtooth.  It increases over time to a certain point and then CF restarts the app which resets it back to the baseline.  Without the Redis health contributor enabled, it just stays a steady horizontal line,  (This is an app instance which nothing is hitting except the Cloud Foundry health checks).

The code that is hitting it is in the Steeltoe.Contributors package.  The Source on git is here: https://github.com/SteeltoeOSS/Connectors/blob/dev/src/Steeltoe.CloudFoundry.ConnectorBase/Cache/RedisHealthContributor.cs

**Comment by mgravell** [comment]
Wow, that's all kinds of ugly. Kinda hard to tell from that spaghetti what
gets created when! I guess they were trying to avoid hard library
dependencies, but... wow.

**Comment by NickCraver** [comment]
@dwilliss Our 2.0 RTM release is now available on NuGet, can you try using that and see if you still see memory issues? Lots of changes to the pipe there.

**Comment by dwilliss** [comment]
I just pulled that in and rebuilt using 2.0.  I've pushed it and will check back in a few hours or tomorrow morning to see how it's doing.

**Comment by dwilliss** [comment]
It seems to have worked.   Here's a graph showing the memory usage yesterday.

![image](https://user-images.githubusercontent.com/1755696/45160869-1afdc800-b1b0-11e8-94db-2196b4673e67.png)

As you can see, it only gets to just above 30% and then drops down, presumably because garbage collection kicks in (although one of those dips is because some health check took more than one second causing Cloud Foundry to recycle the app).

Here's what it looked like before:
![image](https://user-images.githubusercontent.com/1755696/45161470-8ac08280-b1b1-11e8-9ad7-434ff9a0e623.png)

Memory usage used to reach 80 to 90%, and each of those dips was a crash.

**Comment by dwilliss** [comment]
Of course, now I need new versions of Microsoft.Extensions.Caching.Redis and Microsoft.Web.RedisSessionStateProvider that reference this new version.  Looks like Microsoft has that scheduled for their 3.0 release.

I think I'll have to just disable the health contributor for now :disappointed:

**Comment by NickCraver** [comment]
@dwilliss Thanks for the update! We'll help poke the Microsoft folks to update (they're pushing for it in 2.2), and happy to help poke wherever needed for other libraries. I'm going to close this out since this particular issue is fixed and we'll keep going with the others.
