### ISSUE TITLE
KEYS and ARGS table are empty when EVALSHA'ing a preloaded script?

### ISSUE THREAD

**Issue by btodts** [StackExchange/StackExchange.Redis#939]
Consider the following Lua script:

````lua
if redis.call('exists', KEYS[1]) == 0 then
    redis.call('hmset', KEYS[1], unpack(ARGV))
end
````

I can't seem to get this to play nice when preloading the script and using the `ScriptEvaluateAsync` api. For some reason, the KEYS and ARGV tables are empty.

The code I'm using (simplified, of course):

````c#
// HmsetnxScript is a const string containing the aforementioned Lua script
var preloadedScript = await LuaScript.Prepare(HmsetnxScript)
     .LoadAsync(_redis.GetServer("127.0.0.1:6379"));

await db.ScriptEvaluateAsync(
    preloadedScript,
    new
    {
         key = (RedisKey) "SomeKey",
         valueFoo= (RedisValue) "Foo",
         valueBar = (RedisValue) "Bar"
     },
     CommandFlags.FireAndForget);
````
When monitoring redis, it prints the following output:
![2018-09-04 15_31_16-opdrachtprompt - docker exec -it redis-m4 _bin_bash](https://user-images.githubusercontent.com/12234350/45034381-aa439800-b057-11e8-98f2-8a9349e30ceb.png)
As you can see, no keys or arguments are passed to the `EVALSHA` command.

Note that this works perfectly fine when just evaluating a string, without preloading:

````c#
var fooValues = new[] {"valueFoo", "Foo", "valueBar", "Bar"};

await db.ScriptEvaluateAsync(
    HmsetnxScript,
    new RedisKey[] { key.ToString() },
    Array.ConvertAll(fooValues, value => (RedisValue)value),
    CommandFlags.FireAndForget);
````

![2018-09-04 15_38_22-opdrachtprompt - docker exec -it redis-m4 _bin_bash](https://user-images.githubusercontent.com/12234350/45034749-9ea4a100-b058-11e8-8db1-e8bbbfdfbbe0.png)

What is the correct usage of the API to get this to work with preloaded scripts?

**Comment by mgravell** [comment]
When using `LuaScript.Prepare`, the API expects to *basically* do a pseudo-Lua substitution something more like SQL, i.e. `@key` in your script would be replaced with `KEYS[1]`. In your case, I would advise *against* this, because of your `unpack` usage - which isn't going to be a good fit for this kind of substituted usage.

**Comment by mgravell** [comment]
summary: **in this case** - I would use the "Note that this works perfectly fine when just evaluating a string, without preloading" code.
