### ISSUE TITLE
NRediSearch paging fails on pagesize 20

### ISSUE THREAD

**Issue by meybosdavy** [StackExchange/StackExchange.Redis#940]
I believe there is an issue with the .Boxed() method in Literals.cs when the property has value 20. This will cause an "Index was outside the bounds of the array" error.
          
```
                args.Add("LIMIT".Literal());
                args.Add(_paging.Offset.Boxed());
                args.Add(_paging.Count.Boxed());
```

**Comment by mgravell** [comment]
You're absolutely right; thanks - fixed in the code
