### ISSUE TITLE
Cannot upgrade from deprecated StrongName 1.2.7 to 2.0 in ASP.NET Core app

### ISSUE THREAD

**Issue by KeithHenry** [StackExchange/StackExchange.Redis#942]
Upgrading from `StackExchange.Redis.StrongName` 1.7 to `StackExchange.Redis` 2.0 causes lots of errors like this:

> The type 'RedisKey' exists in both 'StackExchange.Redis.StrongName, Version=1.2.6.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46'

This is because  `Microsoft.Extensions.Caching.Redis` still points to `StackExchange.Redis.StrongName`

**Comment by KeithHenry** [comment]
There appears to be a workaround in https://github.com/NuGet/Home/issues/4989#issuecomment-311042085 - though that gets it to compile it also immediately crashes (doesn't even get to `Program.Main`) so I'm not sure it's a fix.

**Comment by mgravell** [comment]
Yes. You won't be able to update *until* any libs you're using have also updated. I would not advise any "workaround" here. The "fix" is : wait for any intermediate libraries to update.

**Comment by KeithHenry** [comment]
Ok, I'll stick with the previous version until https://github.com/aspnet/Caching/issues/410 is resolved.
