### ISSUE TITLE
It can delete the key with a wildcard

### ISSUE THREAD

**Issue by JHeLiu** [StackExchange/StackExchange.Redis#944]
Can it use a wildcard to delete a key? Because I have encountered such a problem? Can redis itself be implemented like this? Can this library be ok?
`key:names:*`

**Comment by mgravell** [comment]
There is no redis feature that provides this, so there is no direct library
feature that exposes it.

Options:

- if you just want to clean up  existing data: useYS/SCAN (on IServer) to
enable unumerate the filtered keys, issuing key deletes for each
- if you need to continue doing this: consider using a "hash" - a single
key with multiple key/value pairs. Then just issue a single key deletes for
the entire hash

**Comment by JHeLiu** [comment]
@mgravell  3 Q
