### ISSUE TITLE
TryParse() on RedisValue missing in 2.0

### ISSUE THREAD

**Issue by rmja** [StackExchange/StackExchange.Redis#946]
I am upgrading to 2.0 and have found that the `TryParse()` methods on `RedisValue` have been removed. I have used these do distinguish between double and string values. Is there an equivalent in 2.0 except from e.g.  `double.TryParse(redisValue.ToString(), out var numberValue)`?

**Comment by mgravell** [comment]
I don't remember removing anything, but will check when at keyboard

**Comment by mgravell** [comment]
These have been resurrected and will be included next build; I'm really sorry about that - I don't know how that happened!

**Comment by mgravell** [comment]
should be available in https://www.nuget.org/packages/StackExchange.Redis/2.0.505
