### ISSUE TITLE
Redis Timeouts in 1.2.6

### ISSUE THREAD

**Issue by markostus** [StackExchange/StackExchange.Redis#947]
Hi,

We have been hampered by a high number of timeouts in our solution, as such we reviewed the timeout pages and other resources we could find and implemented some changes to allow minthreads to be changed on our application.

Unfortunately we started to hit timeouts again almost straight away.  I include the error messages below, in case you can advise on this specific scenarios.

At the time, network and CPU do not seem to be impacted greatly.  Memory usage by our application does seem to be very high at this time, and resetting the service removes the timeouts from the logs.

Redis is MSOpentech port and resides on the same machine and is utilising approx 80MB Memory at the time of the timeouts occurring and appears to be fully functional, with nothing reported in the SLOWLOG.

Any advice you can offer as to where to look, would be greatly appreciated.

Example 1:
EXCEPTION: StackExchange.Redis.RedisTimeoutException: Timeout performing GET *REMOVED*, inst: 0, mgr: ExecuteSelect, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: *REMOVED*, serverEndpoint: 127.0.0.1:6379, keyHashSlot: 9221, IOCP: (Busy=11,Free=989,Min=50,Max=1000), WORKER: (Busy=0,Free=32767,Min=50,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)

Example 2:
EXCEPTION: StackExchange.Redis.RedisTimeoutException: Timeout performing GET *REMOVED*, inst: 71, mgr: ProcessReadQueue, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 1, clientName: *REMOVED*, serverEndpoint: 127.0.0.1:6379, keyHashSlot: 2833, IOCP: (Busy=13,Free=987,Min=50,Max=1000), WORKER: (Busy=2,Free=32765,Min=50,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)

 Example 3:
_EXCEPTION: StackExchange.Redis.RedisTimeoutException: Timeout performing GET *REMOVED*, inst: 0, mgr: ProcessReadQueue, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 1, clientName: *REMOVED* serverEndpoint: 127.0.0.1:6379, keyHashSlot: 8762, IOCP: (Busy=9,Free=991,Min=50,Max=1000), WORKER: (Busy=6,Free=32761,Min=50,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)_

Many thanks

Mark

**Comment by mgravell** [comment]
2.0 addresses a wide range of network issues - it esssentially rewrites all the network code; I *strongly* recommend trying 2.0 if possible (assuming you aren't blocked by an intermediary library).

Those timeouts are *slightly* odd, though, because all the zeros... which suggests that literally nothing is happening; but ultimately, 2.0 exists to address network problems in 1.*  - see https://github.com/StackExchange/StackExchange.Redis/issues/871
