### ISSUE TITLE
Redis client is not able to recognise the connection failure when Ethernet cable is removed

### ISSUE THREAD

**Issue by JesvinJoseph** [StackExchange/StackExchange.Redis#951]
Hi,
I had hosted the Redis Server(4.0.11)  on a different machine and set the client KeepAlive to 20 seconds. When I removed the Ethernet cable of the system where the client is running, It is not able to recognise the connection failure. ie, **ConnectionFailed** callback method is not executed.

```
static ConnectionMultiplexer redis;
public async Task InitRedis()
{
    Console.WriteLine("Initializing Redis");
    try
    {
        redis = await ConnectionMultiplexer.ConnectAsync("10.133.30.213:6379,abortConnect=false,keepAlive=20");
        if (redis.IsConnected)
        {
            Console.WriteLine("Connected to Redis");
        }
        else
        {
            Console.WriteLine("Redis connection failed");
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Redis: GetDataBase exception: {ex.Message}");
    }
    redis.ConnectionFailed += (s, e) =>
    {
        Console.WriteLine("Connection to Redis Failed! Retrying ...");
    };
    redis.ConnectionRestored += (s, e) =>
   {
       Console.WriteLine("Connection to Redis Restored! ");
   };
}
```

**Comment by mgravell** [comment]
Can I check: is this "isn't recognised immediately"? Or "isn't recognised
ever"?

**Comment by JesvinJoseph** [comment]
I waited for more than 15 minutes. I think it is not recognised ever.

**Comment by mgravell** [comment]
That's odd. We'll investigate. This *should* have been caught by the
heartbeat.

**Comment by NickCraver** [comment]
I believe this issue was fixed in later releases (we had a few issues around the heartbeat). Going to close this our for inactivity and point to related issue #1120 where a connection's bad state persisting is being addressed.
