### ISSUE TITLE
HashValue Condition Failing

### ISSUE THREAD

**Issue by cunningb** [StackExchange/StackExchange.Redis#952]
I've been having some issues with conditional transactions using StackExchange.Redis. Specifically when using a transaction with a `HashEqual`

My use case is multiple servers updating different fields of the same hash key. The documentation suggests that the HashEqual should cover this case, taking 3 arguments (`HashKey`,`HashField`, `HashValue`)

On the client end, the transaction is reported as failing, but the HashEqual condition is marked as satisfied.
On the redis server, the WATCH is being issued, another field in the hash is updated by a different server, and then an empty multi/exec is given. This is from my redis MONITOR:
```
<host-1> "SELECT" "0"
<host-1> "WATCH" "hash-test"
<host-1> "HGET" "hash-test" "e11a365c-702e-4450-b020-b8b76aaa8216"
    <host-2> "SELECT" "0"
    <host-2> "WATCH" "hash-test"
    <host-2> "HGET" "hash-test" "7bf656ff-e6e0-41ee-bfec-91a0e53a1253"
    <host-2> "MULTI"
    <host-2> "HSET" "hash-test" "7bf656ff-e6e0-41ee-bfec-91a0e53a1253" "c58987ce-dcb7-402b-a941-90b8c8d22d8c"
    <host-2> "EXEC"
<host-1> "MULTI"
<host-1> "EXEC"
```

The gist of the code that I'm using to recreate this issue is:
```c#
async Task update(int threadId, IDatabase redis)
{
    var HashKey = "hash-test";
    var HashField = Guid.NewGuid().ToString();
    var previousValue = Guid.NewGuid().ToString();

    await redis.HashSetAsync(HashKey, HashField, previousValue);

    while (true)
    {
        var transaction = redis.CreateTransaction();

        var conditionResult = transaction.AddCondition(Condition.HashEqual(HashKey, HashField, previousValue));

        var newValue = Guid.NewGuid().ToString();

        Console.WriteLine("[{0:D3}] Attempting to update hash value ({1}:{2}) from {3} -> {4}", threadId, HashKey, HashField, previousValue, newValue);

        transaction.HashSetAsync(HashKey, HashField, newValue);

        if (await transaction.ExecuteAsync())
        {
            previousValue = newValue;
        }
        else if (conditionResult.WasSatisfied)
        {
            Console.WriteLine("[{0:D3}] ============= Transaction failed, but the condition was satisfied", threadId);
            throw new Exception(string.Format("[{0:D3}] Transaction failed, but condition was satisfied", threadId));
        }

        await Task.Delay(250);
    }
}
```

From where I'm sitting, this looks like an issue with the StackExchange.Redis library, but if that's not the case then I would love to know what I could change to fix it.

I made a [reproduction project](https://github.com/cunningb/RedisTransactionError) where this issue occurs pretty consistently. This also seems to be a simliar issue to what [this user](https://stackoverflow.com/questions/52123957/transactions-failing-when-all-conditions-are-met-in-stackexchange-redis) was encountering

**Comment by mgravell** [comment]
> WATCH is being issued, another field in the hash is updated by a different server, 

And boom: the `EXEC` is toast. That's very intentional from the redis server design - and from a library perspective, it seems to be functioning perfectly: another connection wrote to a constrained key, so: a conflict occurred. Redis appplies conflicts at the key level, even for hashes - and specifically: even if the two connections are talking to different named values in the same hash: that's still a conflict.

 So: if you expect this kind of conflict, you have two options:

- loop until successful
- use Lua (ScriptEvaluate) instead of MULTI/EXEX

**Comment by mgravell** [comment]
Dammit, submitted too early! I meant to add: my recommendation here would be to use Lua : far easier to get right than multi/exec.

**Comment by cunningb** [comment]
That was my suspicion since the redis documentation for `WATCH` implies that it's only top level keys. I thought that since the library is issuing a `HGET` that it might be doing something extra under the hood, but I suppose that's just for the pre multi/exec validation.

Thanks for the speedy reply!
