### ISSUE TITLE
Slow-down because lock into ConnectionMultiplexer.ExecuteSyncImpl 

### ISSUE THREAD

**Issue by auriou** [StackExchange/StackExchange.Redis#953]
Hello, 
I use your library for a web API with strong traffic peaks. At this busy time, I spent a lot of time in the lock of the ExecuteSyncImpl method of the ConnectionMultiplexer class. 

I mostly use MGETs

Is it mandatory to make locks when we get keys on Redis, how can I optimize that.

Stack trace into Dynatrace :
![image](https://user-images.githubusercontent.com/1873587/45622904-e75f4f80-ba85-11e8-9bd2-2c78e814311d.png)

```csharp
var source = ResultBox<T>.Get(null);
lock (source)
```

Thank you

**Comment by auriou** [comment]
Thanks, so there is no notion of connection pool, but it is possible to implement it using the Async methods of RedisDatabase.cs

I'm going to manage it in my library, which uses StackExchange.Redis.

I already implemented 
 - failover on httpcache, memorycache, OtherProviderCache
 - buffer local cache 
 - RedisProvider Round-Robin (4 servers redis master: twemproxy and sentinel systems do not not suitable for our administrators for reasons of SPoF and maintenance too complex).

Thank you for your work.

**Comment by auriou** [comment]
would it be possible for the HeartBeat to be public exposed so that it can be changed, 1 second it seems too short as interval

Into ConnectionMultiplexer.cs
```csharp
internal const int MillisecondsPerHeartbeat = 1000;
```

**Comment by mgravell** [comment]
it doesn't do everything every heartbeat. What would you propose changing it to, and why? there are already some controls that might do what you want...

**Comment by auriou** [comment]
it was mainly to limit network communication, I had limited it to 3 seconds in a production environment (e-commerce with a lot of traffic) without this generates problems

**Comment by leandro-toledo-uux** [comment]
@Auriou, I am facing a similar issue, believe it or not, I am suspecting from dynatrace monitoring the redis, it didn't get stucked when it was turned off. Did solve your problem just changing the network limit?

**Comment by auriou** [comment]
we grouped the calls that loaded object collections with MGETs, which greatly reduced our problem. But I still have optimization going through async if we have new problems.
@leandro-toledo-uux 
Personally I doubt that dynatrace blocks the process of lock.
Did you compare response time performance on load peaks?

On my side I coded load tests that I launched on my machine, and I had the same problem.

**Comment by leandro-toledo-uux** [comment]
My application started to slow down when it is up of 600 commands/sec, after a few minutes it started do respond in more than 30 seconds. Then my sentinel switch the master to slave and vice versa.

Also, 80% of the commands are de KEYS, I just found out it is not advised to be used in prod environment. I gonna change it in the application.

I'm going to create a load test, it is a nice hint.

Thanks

**Comment by NickCraver** [comment]
It looks like we're good here - if you're blocking on calls then yes, _you're blocking on calls_. For any high traffic scenario we highly recommend going full `async` (which seems to be case in new code here). Thanks for the updates all, closing to tidy up :)
