### ISSUE TITLE
Can I get the cache value to support generics?

### ISSUE THREAD

**Issue by ghd258** [StackExchange/StackExchange.Redis#954]
Can I get the cache value to support generics?

**Comment by mgravell** [comment]
Can you be more specific? We don't actually expose a specific "cache" API (although we may in some vFuture if the server roadmap goes as per discussions).

So: can you give an example of what you mean here?

**Comment by ghd258** [comment]
Can you support the generic type of C# before reading the value or writing it?

**Comment by ghd258** [comment]
created with IRedisClient.As<T>() - it returns a 'strongly-typed client' that provides a typed-interface for all redis value operations that works against any C#/.NET POCO type.

**Comment by mgravell** [comment]
`IRedisClient` sounds like ServiceStack. Are you sure you're talking about
the right lib in the right place?

**Comment by ghd258** [comment]
Make sure it's okay. The question is, can we implement the IRedisTypedClient functionality of Service Stack here?

**Comment by mgravell** [comment]
Can **you**? Quite possibly. It isn't an API I'm hugely familiar with, but I'm sure it is possible. It isn't something that we provide as part of this library, and it isn't something that I'm going to attempt to implement. It sounds theoretically possible, but it seems to be a very odd thing to want to do.

**Comment by ghd258** [comment]
Now, the question I'm facing is when I'm doing AOP facet caching, because the data returned by calling Redis can't tell what type you need to convert to a class if it's an object, and if you return a generic type that supports c#

**Comment by mgravell** [comment]
Yes, that's a fun problem. There are two usual approaches:

1. presume that the data will *only* ever be accessed via the typed API, and that the consumer always gets the type right - in which case there is nothing extra to store
2. store a composite serialization value, for example the fully qualified name of the type *followed by* the actual value

If you want to retain compatibility with how Service Stack does this, you'd need to check  which approach Service Stack uses - and if the second option: figure out exactly how Service Stack is encoding that data. But again, this isn't functionality of this library, and isn't a use-case we implement or directly support.

**Comment by ghd258** [comment]
My question is whether StackExchange.Redis can solve this problem.

**Comment by mgravell** [comment]
Re the code snippet above: I see nothing in there that pertains to SE.Redis; are you sure you're asking about the right library? Again: we are not Service Stack

**Comment by ghd258** [comment]
var cacheValue = _RedisService.Get(cacheKey);   
`using Microsoft.Extensions.Caching.Redis;
using Newtonsoft.Json;
using StackExchange.Redis;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using VOCs.FrameworkCore.Cache.Memory;

namespace VOCs.FrameworkCore.Cache.Redis
{
    public class RedisCacheService : ICacheService
    {
        protected IDatabase _cache;

        private ConnectionMultiplexer _connection;

        private readonly string _instance;

        private static ConcurrentDictionary<string, string> concurrentDictionary = new ConcurrentDictionary<string, string>();

        public RedisCacheService(RedisCacheOptions options, int database = 0)
        {
            _connection = ConnectionMultiplexer.Connect(options.Configuration);
            _cache = _connection.GetDatabase(database);
            _instance = options.InstanceName;
        }`
`public object Get(string key)
        {
            if (key == null)
            {
                throw new ArgumentNullException(nameof(key));
            }

            var value = _cache.StringGet(GetKeyForRedis(key));

            if (!value.HasValue)
            {
                return null;
            }


            return JsonConvert.DeserializeObject(value);
        }`

**Comment by mgravell** [comment]
>My question is whether StackExchange.Redis can solve this problem. 

SE.Redis provides a flat API that represents native redis features. You can store and retrieve arbitrary text or binary values, for example, which is what redis really "is".

What those values *are*: SE.Redis has virtually no interest or opinion.

So: could someone use SE.Redis to implement that interface? Sure, absolutely, as per the "1"/"2" options I listed previously. This, however, is not something that comes pre-built by the library authors.

So: yes, it is possible in theory for someone to do that; no "we" don't do it for you. If somebody wanted to write that as a utility layer and release it on nuget: good luck to them, but: it isn't something we'd do.

It would also get into other related topics such as the choice of serializer to use - again, something SE.Redis simply doesn't want to have an opinion about.

**Comment by mgravell** [comment]
If you can figure out a byte sequence or string that represents your data: SE.Redis will happily take care of storing and retrieving that.

**Comment by ghd258** [comment]
It's just a suggestion that the government can increase the convenience, that the government doesn't want to solve this problem even if I solve my own problem in other ways.

**Comment by mgravell** [comment]
My view here is that you kinda need to be using something and/or be a stakeholder to do anything like a half-decent job of implementing something. My problem is: I'm not a consumer of that ServiceStack API, and I have no particular need to be. I also don't want to add external dependencies to the core lib. So: I'm probably not well placed for trying to do that.

As I say: if somebody else wants to do the work of designing, implementing, testing and supporting that work - good luck to them. I'll happily amplify and announce their efforts on social media and, and sing their praises. But: it isn't something that I'm going to do, or add to the core library.

**Comment by ghd258** [comment]
You don't understand what I mean, maybe I don't know clearly, let you misunderstand, I am using StackExchange.Redis encountered problems I want to ask if you can solve se, for example, other frameworks have solutions, you are old It means that I got the wrong place. The problem I encountered was that when I used it as a cache aop or intercepted, se could not support generic types.

**Comment by mgravell** [comment]
> se could not support generic types.

SE also doesn't support non-generic types in this scenario. It supports BLOBs and CLOBs - the actual redis types. It is possible for a caller to add any layering they want over that, but: the caller will need to write the code to deal with that.

**Comment by ghd258** [comment]
string connStr = $"127.0.0.1:6371,pass=,poolsize=10,ssl=false,writeBuffer=10240,syncTimeout=60000";
CSRedis.CSRedisClient client = new CSRedis.CSRedisClient(connStr + ",defaultDatabase=1");

CSRedis.CSRedisClient.Serialize = obj => Newtonsoft.Json.JsonConvert.SerializeObject(obj);
CSRedis.CSRedisClient.Deserialize = (json, type) => Newtonsoft.Json.JsonConvert.DeserializeObject(json, type);

**Comment by NickCraver** [comment]
@ghd258 Can you please open a new issue with an explicit request? It sounds like what you want it a layer _on top of_ our library that does generic with a defined serializer/deserializer. Which is great! And those exist, but it's not functionality we are targeting for the core library at this time. We're happy for others to take that layer and use as a client :)
