### ISSUE TITLE
[Question] How does the Nuget package version 1.2.6 of StackExchange.Redis handle multiplexing and pipelining?

### ISSUE THREAD

**Issue by kristianjaeger** [StackExchange/StackExchange.Redis#956]
Are they configurable in the code?  Thank you.

I found the docs here - https://stackexchange.github.io/StackExchange.Redis/PipelinesMultiplexers but am unsure if they apply to 1.2.6.

**Comment by mgravell** [comment]
Yes, that document is foundational to the design of the lib and applies to all versions. If this ever fundamentally changes, we'll be sure to call it out explicitly.

**Comment by kristianjaeger** [comment]
Great! Thanks, @mgravell .  I appreciate the context.
