### ISSUE TITLE
Drastic Slowdown in Synchronous String SET/GET Operations

### ISSUE THREAD

**Issue by magmasystems** [StackExchange/StackExchange.Redis#958]
Hi,

I upgraded our application to use the latest StackExchange.Redis client (version 2.0.x). We have a test harness, and one of the tests is a stress test where we see how long it takes to insert and retrieve 100,000 strings that have unique keys. The basic logic of the test is:

for (i = 1 to 100000)
{
      string key = generate a random string key;
      database.StringSet(key, sampleValue);
      string testValue = database.StringGet(key);
}

We have noticed that there is a drastic reduction in performance with version 2.0.x. The test completes in 200% of the time that the same test using StackExchange.Redis 1.26 takes.

Any hints as to what may be causing this behavior?

Let me know if you need any more info from me.

Thanks,

Marc Adler
Chief Architect, ADP

**Comment by mgravell** [comment]
I assume this is `StringSet` ? I can take a look.

**Comment by magmasystems** [comment]
I edited the post. Thanks, Marc.

The test harness is too large to send to you guys, as it's part of a much larger framework that I wrote. The framework encapsulated a number of different caches, so it's hard to package a program up and send it to you. But the basic logic is replicated above. I am wondering is you have any performance tests that you have written that dones pretty much the same thing? 

If necessary, I can try to write the same app that just calls the StackExchange.Redis driver directly. Let me know.

**Comment by mgravell** [comment]
I have some perf tests, yes - they showed a *minor* slowdown in v2, not enough for me to be concerned - although I'm planning for 2.1 to be more perf-focused (2.0 is stability-focused). The more data points (such as this one) that I have to help me prioritise, the better - so: I can use this to help target my efforts.

**Comment by magmasystems** [comment]
One other tidbit of info that may or may not be important. These are tests that are running on my Windows Server 2008 R2 laptop, running the Windows version of Redis 3.2.

**Comment by magmasystems** [comment]
Marc, The next comment is the simple test program that I just wrote. On my Windows 2008 R2 VM and with Redis 3.2 for Windows, it took almost 5 minutes to insert and retrieve 100K strings. Let me know if you see something that is obviously wrong.

**Comment by magmasystems** [comment]
`using System;
using System.Diagnostics;

namespace StackExchange.Redis.Tests.Performance
{
    class Program
    {
        static void Main()
        {
            const int NUM_INSERTIONS = 100000;
            int matchErrors = 0;

            Stopwatch stopwatch = new Stopwatch();

            using (var connection = ConnectionMultiplexer.Connect("localhost"))
            {
                var database = connection.GetDatabase(0);

                stopwatch.Start();

                for (int i = 0; i < NUM_INSERTIONS; i++)
                {
                    var key = $"StackExchange.Redis.Test.{i}";
                    var value = i.ToString();

                    database.StringSet(key, value);
                    var retrievedValue = database.StringGet(key);

                    if (retrievedValue != value)
                        matchErrors++;

                    if (i > 0 && i % 1000 == 0)
                        Console.WriteLine(i);
                }

                stopwatch.Stop();
            }

            Console.WriteLine($"The time it took to insert {NUM_INSERTIONS} strings is {stopwatch.ElapsedMilliseconds/1000} seconds, and there were {matchErrors} retrieval errors");

            Console.WriteLine("Press ENTER to exit");
            Console.ReadLine();
        }
    }
}
`

**Comment by magmasystems** [comment]
Looks like #898 may be the same thing as mine. Very similar test programs.

**Comment by andrebires** [comment]
We're also experimenting an considerable increase of CPU usage after updating to 2.0 (at least 20%). I collected some performance traces in a server and got the following results:

![image](https://user-images.githubusercontent.com/1099597/46105091-7ae20000-c1ab-11e8-95e8-5222ccdc8a96.png)

The hotspots:
![image](https://user-images.githubusercontent.com/1099597/46105191-c09ec880-c1ab-11e8-960e-c75ffe94a72b.png)

In our case, we are using the asynchronous methods. Unfortunatelly I don't have a trace with the 1.2.6 version to compare, but I will try to investigate further.

**Comment by NickCraver** [comment]
I re-ran this benchmark on latest (upcoming 2.5.x release) and here's where we stand:
```lua
➜ dotnet run -c Release
Done. 76793 ms
Avg CPU: 1.0948224067581924
Lib Version: 1.2.6.0
➜ dotnet run -c Release
Done. 76672 ms
Avg CPU: 1.212586560190939
Lib Version: 1.2.6.0
➜ dotnet run -c Release
Done. 76299 ms
Avg CPU: 1.2941366746962346
Lib Version: 1.2.6.0
```
```lua
➜ dotnet run -c Release
Done. 84161 ms
Avg CPU: 0.8430855101891446
Lib Version: 2.5.39.49509
➜ dotnet run -c Release
Done. 84131 ms
Avg CPU: 0.8438956451736115
Lib Version: 2.5.39.49509
➜ dotnet run -c Release
Done. 84137 ms
Avg CPU: 0.9356477802172953
Lib Version: 2.5.39.49509
```
So overall yes it's about 10% slower than 1.2.6 (rather than 100% slower when this was opened), but also uses significantly less CPU. The 10% penalty is something we pay for 2.x being more correct than 1.2.6 was which could failure or mis-order in some scenarios - the trade-off is for correctness.

Given we're in a good state here, I'm going to finally close this out. I really appreciate the report and the repo samples here - hugely helpful in measuring these scenarios!
