### ISSUE TITLE
No connection is available to service this operation: HGET

### ISSUE THREAD

**Issue by grik001** [StackExchange/StackExchange.Redis#959]
Hi,

Feel free to delete this post if you believe it is not the correct place to post this. I am trying to use Redis Cache with Azure Functions.

I keep getting the following error: No connection is available to service this operation: HGET

I have tried using a static lazy connection or a connection per request. Almost all my calls get this error. I am using latest StackExchange.Redis for .Net 4.7. I am only sending a single message to Azure Functions so its not a matter of load and connection limit.

What I have also noticed is that the Save most of the time works, its always the Get that is failing(executing Save first then Get after using the same RedisCacheHelper instance with a static lazy loaded connection inside) Any idea what it might be?

Just some more info:

**Azure Function v1**

I am initializing my connection like this:

![image](https://user-images.githubusercontent.com/27157850/45919906-5204f680-be9d-11e8-80e9-d1aca8129568.png)

The above class I am only initializing once in the ctor of the Azure Function and re-using it so only 1 instance of this class exists.

I am calling the RedisCache like this:

![image](https://user-images.githubusercontent.com/27157850/45919931-a14b2700-be9d-11e8-8d80-f82268c559b9.png)

![image](https://user-images.githubusercontent.com/27157850/45919934-b0ca7000-be9d-11e8-8fb1-49a4ea2c378d.png)

AppInsight Logs:

![image](https://user-images.githubusercontent.com/27157850/45919968-13bc0700-be9e-11e8-9347-acb185ce0ba6.png)

![image](https://user-images.githubusercontent.com/27157850/45919973-28989a80-be9e-11e8-8b16-d9d862fe2816.png)

![image](https://user-images.githubusercontent.com/27157850/45919976-32ba9900-be9e-11e8-94bc-03ce0af6e565.png)

**Comment by NickCraver** [comment]
hmmmm, @mgravell Last command was an unanswered heartbeat here in all cases - looks connected to the other issue.

@grik001 Thanks, this report helps and we'll take a look this week!

**Comment by PankajRawat333** [comment]
**Below line of "Test Code" working in console application but not working with Azure Function.**

`IConnectionMultiplexer connection = ConnectionMultiplexer.Connect("**********rediscache.redis.cache.windows.net:6380,password=nFpm1oIiyP8ZiCxC/WMcxaFRzGo4yMgWDYZksQgqO4U=,ssl=True,abortConnect=False");
        IDatabase database = connection.GetDatabase();
        bool isConnected = connection.IsConnected;
        var test = database.HashExists("key", "fieldKey");
        database.HashSet("key", "fieldKey", "test");

        database.StringSet("Key", "Value");
        var result = database.StringGet("Key");
        connection.Close();`

Now I'm using StackExchange.Redis Nuget package to 1.2.6 in function app

**Comment by mgravell** [comment]
This sounds like an assembly binding problem in azure functions. I'm trying to set up a local repro. See also: https://github.com/StackExchange/StackExchange.Redis/issues/961

Hi; the Connect method has an optional log parameter; is there any chance you can use this parameter to see what it says? Typically by creating a `StringWriter`, passing it in, and calling `.ToString()` after the method has completed (success or failure)

**Comment by tinu73** [comment]
Having excately the same issue here. With StackExchange.Redis Nuget package 1.2.6 it works with Azure Function v1

**Comment by devcrp** [comment]
Looking forward to this issue to be fixed! 
We have an Azure Function that's responsible of reloading a few Redis keys and we're receiving this error. We're handling it via api calls from the function to an external webapp for now until this issue gets resolved.

**Comment by ymorrismc** [comment]
I am having the same issue using the latest of StackExchange.Redis Nuget package 2.0.6.1 in a .Net 4.7.2 console app.  Any update / workaround to this?  I noticed that IsConnected is false, and IsConnecting is true on the connection when below exception happens.  Sometimes IsConnecting is also false.  I have not had a successful connection at all.

_________________________________
Exception thrown: 'StackExchange.Redis.RedisConnectionException' in StackExchange.Redis.dll ("No connection is available to service this operation: GET somekey; UnableToConnect on mycache.redis.cache.windows.net:6380/Interactive, Initializing, last: ECHO, origin: BeginConnectAsync, outstanding: 0, last-read: 6s ago, last-write: 6s ago, unanswered-write: 28839s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, last-mbeat: 0s ago, global: 0s ago; IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=2044,Min=4,Max=2047), Local-CPU: n/a") Exception thrown: 'StackExchange.Redis.RedisConnectionException' in StackExchange.Redis.dll ("No connection is available to service this operation: GET somekey; UnableToConnect on mycache.redis.cache.windows.net:6380/Interactive, Initializing, last: ECHO, origin: BeginConnectAsync, outstanding: 0, last-read: 6s ago, last-write: 6s ago, unanswered-write: 28839s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, last-mbeat: 0s ago, global: 0s ago; IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=3,Free=2044,Min=4,Max=2047), Local-CPU: n/a") Hyperlink: Activate Historical Debugging	9.34s		[10616] Main Thread

**Comment by NickCraver** [comment]
Looks like we have another overlap with #1120 here - a fix is in progress in #1374 for the 2.1.x release. Consolidating down issues now, but a fix is in the works!
