### ISSUE TITLE
Cannot build in .net 4.0

### ISSUE THREAD

**Issue by JefStat** [StackExchange/StackExchange.Redis#96]
After adding stackexchange.redis via nuget I get the following build errors: 

1>  Restoring NuGet packages...
1>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
1>  All packages listed in packages.config are already installed.
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3268: The primary reference "StackExchange.Redis" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "StackExchange.Redis" or retarget your application to a framework version which contains "System.Runtime, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3268: The primary reference "StackExchange.Redis" could not be resolved because it has an indirect dependency on the framework assembly "System.Threading.Tasks, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "StackExchange.Redis" or retarget your application to a framework version which contains "System.Threading.Tasks, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

**Comment by anikethparmar** [comment]
Hello,

Was this ever resolved? I am facing the same issue. Please let me know for any possible solution.

Thanks in advance.

**Comment by Vijay27anand** [comment]
We have migrated our code to .Net 4.5 to work well. It does not work well with .net 4.0 website projects. So you have to convert to 4.5 or with .net 4.0 convert the website to project with csproj.

**Comment by anikethparmar** [comment]
Got it. I will give it a shot. Thanks for the prompt reply.

**Comment by mahdiahmadirad** [comment]
I had this issue (warning: MSB3268) in a <b>.net 4 class library</b> project (on VS 2013). please check the following steps. my problem solved:
1. check right versions in bindingRedirect of your app.config or web.config.
![4162015 507 pm](https://cloud.githubusercontent.com/assets/5328663/7180897/1e4d06e0-e45b-11e4-9201-0f33f7391231.png)

2.check if Microsoft.Bcl.Build msbuild target file imported to your project properly.
![4162015 512 pm](https://cloud.githubusercontent.com/assets/5328663/7180949/aba9f78c-e45b-11e4-83cb-36caa260e07a.png)

read this issue about installing nuget packages: https://nuget.codeplex.com/workitem/3072

hope checking these steps solve your problem.

**Comment by roadkill42** [comment]
Trying for 64 bit builds in Windows 7 and StackExchange.Redis_Net40 - or any StackExchange for that matter.
Could not even load several of the projects (Docs, ConnectionWatcher, BasicTest) because they required .Net 4.5 in the project files. Manually edited project file to 4.0 so they would at least load. Then found that .Net 4.5 specific calls (ZipArchive zip in ConnectionMultiplexoer.cs) were used when I tried to build using VS 2013. VS 2010 had 68 code errors in just the ConnectionMultiplexor, then quit. Looked at Microsoft.Bcl.Build 1.0.21 and it doesn't have any "<Import" commands in it. 
StackExchange.Redis that I am trying to build was downloaded from GitHub on April 27, 2015 as a zip file. I have not found where the version information is located, if in fact there is any.
Use of .Net 4.5 is not an option at this time and VS 2013 is not in active use for development  - maybe later this year.

**Comment by mgravell** [comment]
K, thanks. I'll fix that as part of the branch I'm working on currently.

**Comment by qcz** [comment]
Binding redirects are broken in the current version, or at least NuGet messes with it. NuGet installs 2.6.9.0 BCL assemblies, but StackExcange.Redis references the 2.6.10 ones so the project does not compile (it is a class library, not a web project).

To fix the problem, replace 
`<bindingRedirect oldVersion="0.0.0.0-2.6.9.0" newVersion="2.6.9.0" />`
binding redirects with
`<bindingRedirect oldVersion="0.0.0.0-2.6.10.0" newVersion="2.6.9.0" />`
in the app.config/web.config of your project and and in *every other* projects that references that assembly.

**Comment by orlycohen** [comment]
Hellow, 
I'm trying to type a simple code

 var conf = new ConfigurationOptions
                {
                    KeepAlive = 180,
                    Password = "",
                    // DefaultVersion = new Version("2.8.5"),
                    AllowAdmin = true,
                    EndPoints =
                    { 
                        {"localhost", 6379}
                    }
                };

            var connection = ConnectionMultiplexer.Connect(conf);

but in debug i getting the following :
"Could not load file or assembly 'System.Threading.Tasks, Version=2.6.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

I'm working with .net fraimwork 4.0.
when i downloaded Stackexchenge.Redis , It has automaticly dowloaded 
System.Threading.Tasks version 2.6.9 

How can I resolve this problem ?

**Comment by qcz** [comment]
@orlycohen See my comment above yours.

**Comment by orlycohen** [comment]
Thank you , 
can you post  a link to dll 'System.Threading.Tasks, Version=2.6.10.0 download
I cant find it on a web...

**Comment by qcz** [comment]
It is not required, just follow the instructions in my comment to fix the problem (starting with "To fix the problem")

**Comment by orlycohen** [comment]
Yes !!! It's worked ,
thank you very much : )

**Comment by hiraldesai** [comment]
@qcz - that fixes the broken build - but when I try to run the application I get manifest error.

**Comment by qcz** [comment]
@hiraldesai It works for me. I used this solution in many different types of .NET 4.0 projects (Console applications, WPF, WCF and ASP.net MVC projects). Just tried successfully with the latest packages from NuGet in a new console application.

What is the exact error message you got? Is the Copy Local property of the required assemblies (`System.IO`, `System.Runtime`, `System.Threading.Tasks`) set to true?

**Comment by hiraldesai** [comment]
@qcz - I got it to work by updating the Bcl to a version that references version 2.6.10 of `System.Threading.Tasks` and `System.Runtime`. Thanks for your help. By default when installing Redis package - it installs a Bcl version that has reference to 2.6.9.

**Comment by Wallonman** [comment]
@qcz : when you say replace by :
<bindingRedirect oldVersion="0.0.0.0-2.6.10.0" newVersion="2.6.10.0" />

you mean :
<bindingRedirect oldVersion="0.0.0.0-2.6.10.0" newVersion="2.6.9.0" />

?

**Comment by montoyaedu** [comment]
Hello,

I was facing the same problem.

Add a binding redirect was not enough.

As @qcz said, It installs 1.1.9 but references 1.1.10

I solved it by forcing an update of Bcl from 1.1.9 to 1.1.10 from nuget server

Hope it helps,

Edu

**Comment by pcooper** [comment]
With [NuGet 2.8 patch resolution changes](https://docs.nuget.org/release-notes/nuget-2.8#user-content-patch-resolution-for-dependencies), bcl and bcl.build won't automatically install to .10 and .21 respectively. I think the nuspec for SE.Redis could be updated to reflect the patch versions of bcl and bcl.build referenced in the net40 project file.

**Comment by mgravell** [comment]
The project.json for the next build has the references correct.

**Comment by NickCraver** [comment]
@pcooper can you please give 1.1.553-alpha a try?

**Comment by NickCraver** [comment]
This is fixed in current code, but support for .NET 4.0 will be removed in the 2.x versions (it's just too much to maintain at this point). Closing this out to cleanup, but anyone finding this: you'll be able to build from the 1.x tags currently in the repo which have .NET 4.0 support. Currently, current is 1.1.608.
