### ISSUE TITLE
VS 2015 (dotnet 4.7.2) not able to use Pipelines.Sockets.Unofficial and hence StackExchange.Redis. This is happening with version 2.*

### ISSUE THREAD

**Issue by sarveshmm** [StackExchange/StackExchange.Redis#963]
VS 2015 (dotnet 4.7.2) not able to use Pipelines.Sockets.Unofficial and hence StackExchange.Redis. This is happening with version 2.*
**It works on VS 2017 with dotnet 4.7.2.**
Package manager output :
Attempting to gather dependency information for package 'Pipelines.Sockets.Unofficial.1.0.0' with respect to project 'ConsoleApplication1', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 293.56 ms
Attempting to resolve dependencies for package 'Pipelines.Sockets.Unofficial.1.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Pipelines.Sockets.Unofficial.1.0.0'
Resolved actions to install package 'Pipelines.Sockets.Unofficial.1.0.0'
Retrieving package 'Pipelines.Sockets.Unofficial 1.0.0' from 'nuget.org'.
Install failed. Rolling back...
Package 'Pipelines.Sockets.Unofficial.1.0.0' does not exist in project 'ConsoleApplication1'
Package 'Pipelines.Sockets.Unofficial.1.0.0' does not exist in folder 'c:\users\user1\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
Executing nuget actions took 6.54 ms
Could not install package 'Pipelines.Sockets.Unofficial 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========
Time Elapsed: 00:00:02.3034721

**Comment by tcoj** [comment]
Hi,

I have same problem with VS 2015 .net 4.6.1:

"Could not install package 'Pipelines.Sockets.Unofficial 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Any news about this?

**Comment by mgravell** [comment]
@tcoj that's a different issue; I've added an explicit net461 target in 1.0.6, and I'm updating SE.Redis to target 1.0.6

**Comment by mgravell** [comment]
@sarveshmm I have very limited options there - I can't change how the nuget tool works internally... it might be that the dependency fixes I'm working on currently help with that, though

**Comment by tcoj** [comment]
Thanks this solved my problem too.

**Comment by sarveshmm** [comment]
@mgravell Issue is resolved with version 2.0.210
