### ISSUE TITLE
SocketFailure on node/Interactive

### ISSUE THREAD

**Issue by dream-y** [StackExchange/StackExchange.Redis#966]
when i invoke ConnectionMultiplexer.Connect with stackexchange.redis v2.0.510,
exception ocuurs just like that:
StackExchange.Redis.RedisConnectionException: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). SocketFailure on 192.168.87.56:6379/Interactive, Initializing, last: NONE, origin: ConnectedAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, unanswered-write: 268883s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.510.12816。

**Comment by mgravell** [comment]
Please try 513 - this is most likely an assembly binding problem, which 513
should address

**Comment by dream-y** [comment]
Thanks a lot.
