### ISSUE TITLE
RedisConnectionException in a tight loop (2.0.505)

### ISSUE THREAD

**Issue by kierenj** [StackExchange/StackExchange.Redis#968]
Hi! Having some good success with v2, thank you very much :)
However, a couple of times we've run into a situation where we get lots and lots of `StackExchange.Redis.RedisConnectionException`.

It's in a worker process loop, which is in prod in a tight while loop at present (my bad) - in a new version we use Polly to do some traffic calming.

The app is running on an Azure App Service and it's a Redis Cache on Azure too.  Other apps in the same region, etc, can all connect to the server just fine.  The exceptions are thrown basically until process restart.

Exception details here: https://gist.github.com/kierenj/2e4eb49b17f38596a0327b745d67dee6

Anything I can do to help diagnose?

**Comment by kierenj** [comment]
Very strange, this does seem to keep happening.  A process restart lets it connect again - really seems like a client library error right now?

**Comment by kierenj** [comment]
It's not glamorous or particularly interesting, but is still happening repeatable for us, unfortunately.  The client doesn't appear to attempt to reconnect.  Anything I can do to help diagnose?

**Comment by NickCraver** [comment]
@kierenj This sounds a lot like port exhaustion from the description, can you get a `netstat` dump when it happens?

**Comment by kierenj** [comment]
Ah, fantastic idea, I felt it might be *something* like that, out of handles, some fairly low level socket error.  `netstat` isn't allowed on App Services but it looks like they have a feature for it, https://blogs.msdn.microsoft.com/appserviceteam/2018/01/18/exciting-new-features-in-app-service-diagnostics/ .  I'll report back here when it next occurs.  Sharing this link in case it helps another in the meantime.

**Comment by NickCraver** [comment]
@kierenj Did you have any lock here? Checking up on older issues.

**Comment by kierenj** [comment]
Hi, I’m not sure since we have an auto-restart thing going on now, so I’ll have to check the logs. I’ll be able to do that Monday. Thank you!
