### ISSUE TITLE
Can concurrent execution of large concurrent requests change to parallel execution?

### ISSUE THREAD

**Issue by ghd258** [StackExchange/StackExchange.Redis#970]
Can concurrent execution of large concurrent requests change to parallel execution?

**Comment by mgravell** [comment]
Not currently, unless you maintain your own pool of muxers.

I did recently put some serious thought into maintaining a pool internally
- it is definitely something I'm open to significant changes to. Now that
we've cleaned up the network code, this would be much more viable than it
used to be in 1.*

**Comment by NickCraver** [comment]
Closing out to cleanup
