### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException with v2.0.510

### ISSUE THREAD

**Issue by dream-y** [StackExchange/StackExchange.Redis#971]
In the v 1.2.6, we meet a lot of timeout issues,  for that, we upgrade to v 2.0.510, but still occurs a lot of timeout issues, like below:
Example 1:
`StackExchange.Redis.RedisTimeoutException: Timeout performing HMGET Base:fes:car (5000ms), inst: 0, qs: 2, in: 0, serverEndpoint: 172.17.6.193:7009, mgr: 10 of 10 available, clientName: 172-17-4-80, PerfCounterHelperkeyHashSlot: 1678, IOCP: (Busy=40,Free=960,Min=10,Max=1000), WORKER: (Busy=0,Free=32767,Min=20,Max=32767), v: 2.0.510.12816 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   在 StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 EP.Base.DataTool.DataRedis.RedisHelper.HashGet[T](String keySpace, String key, String[] arrFields)
   在 FES.Common.Data.RedisBase.HashGet[T](String key, List`1 listFieldId)` 

Example 2:
`StackExchange.Redis.RedisTimeoutException: Timeout performing HMGET Base:fes:car (5000ms), inst: 0, qs: 1, in: 0, serverEndpoint: 172.17.6.193:7009, mgr: 10 of 10 available, clientName: 172-17-4-80, PerfCounterHelperkeyHashSlot: 1678, IOCP: (Busy=43,Free=957,Min=10,Max=1000), WORKER: (Busy=0,Free=32767,Min=20,Max=32767), v: 2.0.510.12816 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   在 StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   在 EP.Base.DataTool.DataRedis.RedisHelper.HashGet[T](String keySpace, String key, String[] arrFields)
   在 FES.Common.Data.RedisBase.HashGet[T](String key, List`1 listFieldId)`

Any advice can you offer, would be greatly appreciated!

**Comment by zhuyiif** [comment]
you have to use `ConnectTimeout`, `
       ConfigurationOptions config = new ConfigurationOptions {
            EndPoints =
{
                { xxx,xxx }
        },
            CommandMap = CommandMap.Create (new HashSet<string>
{ // EXCLUDE a few commands
        "INFO", "CONFIG", "CLUSTER",
        "PING", "ECHO", "CLIENT"
        }, available: false),
            ConnectTimeout = 999999999,
            SyncTimeout = 999999999,
            AllowAdmin = true,
            AbortOnConnectFail = false

        };`

**Comment by dream-y** [comment]
@zhuyiif

**Comment by dream-y** [comment]
About the timeout question, i found that the min io threads are smaller than the busy io threads:
`IOCP: (Busy=40,Free=960,Min=10,Max=1000)`

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.

**Comment by gkorland** [comment]
@dream-y did the upgrade to the new version solved your timeout issue?
