### ISSUE TITLE
ResultBox<T>.TryComplete(...) deadlocks with the GC

### ISSUE THREAD

**Issue by andreaskromann** [StackExchange/StackExchange.Redis#975]
This happened on one of our test-servers running Windows Server 2016,
CLR version 4.7.3190.0 and StackExchange.Redis version 2.0.505.18761.

The application was running as a windows service and it appeared to be stuck,
running at a constant 25% CPU on a VM with 4 virtual processors.

I made a dump of the process and ran an analysis. The majority of the threads
were waiting for GC to finish. But the GC could not start its work, because 1 thread
had pre-emptive GC disabled. This thread was doing this:

    ntdll!NtSetEvent+14    
    KERNELBASE!SetEvent+c    
    clr!CLREventBase::Set+2d    
    clr!ObjectNative::PulseAll+c470d    
    [[HelperMethodFrame_1OBJ] (System.Threading.Monitor.ObjPulseAll)] System.Threading.Monitor.ObjPulseAll(System.Object)    
    StackExchange.Redis.ResultBox`1[[System.Boolean, mscorlib]].TryComplete(Boolean)+12a    
    StackExchange.Redis.Message.TryComplete(Boolean)+52    
    StackExchange.Redis.PhysicalConnection.MatchResult(StackExchange.Redis.RawResult)+680    
    StackExchange.Redis.PhysicalConnection.ProcessBuffer(System.Buffers.ReadOnlySequence`1<Byte> ByRef)+286    
    StackExchange.Redis.PhysicalConnection+<ReadFromPipe>d__104.MoveNext()+637 

As I understand, this PulseAll call is made by ResultBox to signal to the
ConnectionMultiplexer that it is done. The ConnectionMultiplexer threads were
all suspended doing variations of this:

    ntdll!NtWaitForSingleObject+14    
    KERNELBASE!WaitForSingleObjectEx+8f    
    clr!CLREventWaitHelper2+3c    
    clr!CLREventWaitHelper+1f    
    clr!CLREventBase::WaitEx+7c    
    clr!SVR::GCHeap::WaitUntilGCComplete+2b    
    clr!Thread::RareDisablePreemptiveGC+180    
    clr!PendingSync::Restore+99    
    clr!Thread::DoAppropriateWait+1f9fe5    
    clr!CLREventBase::WaitEx+c4    
    clr!Thread::Block+27    
    clr!SyncBlock::Wait+19d    
    [[GCFrame]]    
    clr!ObjectNative::WaitTimeout+e1    
    [[HelperMethodFrame_1OBJ] (System.Threading.Monitor.ObjWait)] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)    
    StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[[StackExchange.Redis.RedisValue, StackExchange.Redis]](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor`1<StackExchange.Redis.RedisValue>, StackExchange.Redis.ServerEndPoint)+15f 

So the ConnectionMultiplexer is waiting for the GC, the GC is waiting for
the ResultBox and ResultBox is in some way stuck executing Monitor.PulseAll(this).

How can it get stuck? Looking at the code for SyncBlk in coreclr, it looks like
it is stuck inside this while loop:

    void SyncBlock::PulseAll()
    {
        CONTRACTL
        {
            INSTANCE_CHECK;
            NOTHROW;
            GC_NOTRIGGER;
            MODE_ANY;
        }
        CONTRACTL_END;

        WaitEventLink  *pWaitEventLink;

        while ((pWaitEventLink = ThreadQueue::DequeueThread(this)) != NULL)
            pWaitEventLink->m_EventWait->Set();
    }

That is as far as I have looked into this. I have other issues at work I have to
look at right now. I'm not sure if this is a .NET bug or if the pattern used in
StackExchange.Redis is broken.

**Comment by sbosman1** [comment]
I got the same problem the GC cannot Clear the connection.  Nothing is running on the server. .NET 4.6.2 running Windows 2016 DataCenter version.

000000caa773dc70 00007ffd3b337a4f KERNELBASE!WaitForMultipleObjectsEx+0xef, calling ntdll!NtWaitForMultipleObjects
000000caa773dca0 00007ffcd6e4ebbd (MethodDesc 00007ffcd6cb54b0 +0x68d StackExchange.Redis.PhysicalConnection.MatchResult(StackExchange.Redis.RawResult)), calling (MethodDesc 00007ffcd6cb5140 +0 StackExchange.Redis.PhysicalConnection.get_BridgeCouldBeNull())
000000caa773dd10 00007ffd3b337b53 KERNELBASE!WaitForMultipleObjectsEx+0x1f3, calling ntdll!RtlActivateActivationContextUnsafeFast
000000caa773ddd0 00007ffcd6e4d065 (MethodDesc 00007ffcd6cb54e0 +0x385 StackExchange.Redis.PhysicalConnection.ProcessBuffer(System.Buffers.ReadOnlySequence`1<Byte> ByRef)), calling (MethodDesc 00007ffcd6cb5a40 +0 StackExchange.Redis.RawResult.Recycle(Int32))
000000caa773ddf0 00007ffcd6e42027 (MethodDesc 00007ffcd54915a8 +0xf7 System.IO.Pipelines.Pipe.OnReadAsyncCompleted(System.Action`1<System.Object>, System.Object, System.Threading.Tasks.Sources.ValueTaskSourceOnCompletedFlags)), calling 00007ffd30a92850 (stub for System.Threading.Monitor.Exit(System.Object))
000000caa773de10 00007ffcd6e40758 (MethodDesc 00007ffcd5491528 +0x368 System.IO.Pipelines.Pipe.ReadAsync(System.Threading.CancellationToken)), calling 00007ffd30a92850 (stub for System.Threading.Monitor.Exit(System.Object))
000000caa773de50 00007ffcd6e41ff6 (MethodDesc 00007ffcd54915a8 +0xc6 System.IO.Pipelines.Pipe.OnReadAsyncCompleted(System.Action`1<System.Object>, System.Object, System.Threading.Tasks.Sources.ValueTaskSourceOnCompletedFlags)), calling (MethodDesc 00007ffcd5491558 +0 System.IO.Pipelines.Pipe.TrySchedule(System.IO.Pipelines.PipeScheduler, System.IO.Pipelines.CompletionData ByRef))
000000caa773de60 00007ffd2d57789d (MethodDesc 00007ffd2d276a38 +0xd System.Threading.HostExecutionContextManager.Capture()), calling (MethodDesc 00007ffd2d276a28 +0 System.Threading.HostExecutionContextManager.CheckIfHosted())
000000caa773def0 00007ffcd6e57aec (MethodDesc 00007ffcd6cca6b0 +0xec System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter[[System.IO.Pipelines.ReadResult, System.IO.Pipelines]].UnsafeOnCompleted(System.Action))
000000caa773df10 00007ffd2d5365e2 (MethodDesc 00007ffd2d108328 +0x22 System.Threading.ExecutionContext.FastCapture()), calling (MethodDesc 00007ffd2d108338 +0 System.Threading.ExecutionContext.Capture(System.Threading.StackCrawlMark ByRef, CaptureOptions))
000000caa773df70 00007ffd30c396be clr!WaitForMultipleObjectsEx_SO_TOLERANT+0x62, calling kernel32!WaitForMultipleObjectsEx
000000caa773dfa0 00007ffd30b42df6 clr!Thread::GetFinalApartment+0x1a, calling clr!Thread::GetApartment
000000caa773dfd0 00007ffd30c3951c clr!Thread::DoAppropriateWaitWorker+0x1e4, calling clr!WaitForMultipleObjectsEx_SO_TOLERANT
000000caa773e0d0 00007ffd30c39315 clr!Thread::DoAppropriateWait+0x7d, calling clr!Thread::DoAppropriateWaitWorker
000000caa773e150 00007ffd30b52b7f clr!CLREventBase::WaitEx+0xc4, calling clr!Thread::DoAppropriateWait
000000caa773e170 00007ffd30a951a1 clr!ClrFlsIncrementValue+0x29
000000caa773e190 00007ffd30c5183f clr!SyncBlockCache::LockHolder::LockHolder+0x1f, calling clr!CrstBase::CrstHolder::CrstHolder
000000caa773e1a0 00007ffd30a951f3 clr!CrstBase::Leave+0x65, calling clr!ClrFlsIncrementValue
000000caa773e1e0 00007ffd30b2f34f clr!Thread::Block+0x27, calling clr!CLREventBase::WaitEx
000000caa773e210 00007ffd30b2f31c clr!SyncBlock::Wait+0x19d, calling clr!Thread::Block
000000caa773e290 00007ffd2d513612 (MethodDesc 00007ffd2d28c568 +0x72 System.Threading.ExecutionContextSwitcher.Undo()), calling (MethodDesc 00007ffd2d108170 +0 System.Threading.ExecutionContext.OnAsyncLocalContextChanged(System.Threading.ExecutionContext, System.Threading.ExecutionContext))
000000caa773e350 00007ffd30b2f0c1 clr!ObjectNative::WaitTimeout+0xe1, calling clr!SyncBlock::Wait
000000caa773e440 00007ffd2d55e888 (MethodDesc 00007ffd2d0f6dd0 +0xb8 System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()), calling (MethodDesc 00007ffd2d0f6dd0 +0xd6 System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run())
000000caa773e488 00007ffd30b2f05b clr!ObjectNative::WaitTimeout+0x7b, calling clr!LazyMachStateCaptureState
000000caa773e4d0 00007ffcd6e2df54 (MethodDesc 00007ffcd6cd85a8 +0x84 Pipelines.Sockets.Unofficial.DedicatedThreadPoolPipeScheduler.RunWorkLoop()), calling (MethodDesc 00007ffd2d018190 +0 System.Threading.Monitor.Wait(System.Object, Int32, Boolean))
000000caa773e540 00007ffd2d5131f3 (MethodDesc 00007ffd2d108278 +0x163 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean))
000000caa773e610 00007ffd2d513084 (MethodDesc 00007ffd2d108268 +0x14 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)), calling (MethodDesc 00007ffd2d108278 +0 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean))
000000caa773e640 00007ffd2d513052 (MethodDesc 00007ffd2d108258 +0x52 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)), calling (MethodDesc 00007ffd2d108268 +0 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean))
000000caa773e690 00007ffd2debee0c (MethodDesc 00007ffd2d238000 +0x5c System.Threading.ThreadHelper.ThreadStart(System.Object)), calling (MethodDesc 00007ffd2d108258 +0 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object))
000000caa773e6a0 00007ffd30a97602 clr!SigPointer::PeekElemTypeNormalized+0x32, calling clr!SigPointer::PeekElemTypeClosed
000000caa773e6d0 00007ffd30a96bb3 clr!CallDescrWorkerInternal+0x83
000000caa773e710 00007ffd30a96a70 clr!CallDescrWorkerWithHandler+0x4e, calling clr!CallDescrWorkerInternal
000000caa773e720 00007ffd30b5d5b2 clr!ArgIteratorTemplate<ArgIteratorBase>::GetNextOffset+0xda, calling clr!MetaSig::GetElemSize
000000caa773e750 00007ffd30a9735d clr!MethodDescCallSite::CallTargetWorker+0xf8, calling clr!CallDescrWorkerWithHandler
000000caa773e790 00007ffd30b5d5fe clr!MetaSig::SkipArg+0x2e, calling clr!SigParser::SkipExactlyOne
000000caa773e850 00007ffd30b2efb9 clr!ThreadNative::KickOffThread_Worker+0x109, calling clr!MethodDescCallSite::CallTargetWorker
000000caa773eab0 00007ffd30a97b21 clr!ManagedThreadBase_DispatchInner+0x39
000000caa773eaf0 00007ffd30a97a90 clr!ManagedThreadBase_DispatchMiddle+0x6c, calling clr!ManagedThreadBase_DispatchInner
000000caa773eb10 00007ffd3b34e213 KERNELBASE!QuirkIsEnabled3+0x23, calling kernel32!QuirkIsEnabled3Worker
000000caa773eb40 00007ffd30a95af4 clr!CLRConfig::getQuirkEnabledAndValueFromWinDB+0xd9, calling clr!_security_check_cookie
000000caa773eb50 00007ffd30a9a350 clr!Thread::SetLastThrownObject+0x35, calling clr!StressLog::LogOn
000000caa773ebc0 00007ffd30a97651 clr!FrameWithCookie<DebuggerU2MCatchHandlerFrame>::FrameWithCookie<DebuggerU2MCatchHandlerFrame>+0x26, calling clr!Frame::Push
000000caa773ebe0 00007ffd30a9a270 clr!SystemDomain::GetAppDomainAtId+0x40, calling clr!AppDomain::CanThreadEnter
000000caa773ebf0 00007ffd30a979cd clr!ManagedThreadBase_DispatchOuter+0x75, calling clr!ManagedThreadBase_DispatchMiddle
000000caa773ec10 00007ffd30a951a1 clr!ClrFlsIncrementValue+0x29
000000caa773ec80 00007ffd30a9aa64 clr!ManagedThreadBase_DispatchInCorrectAD+0x15, calling clr!ManagedThreadBase_DispatchOuter
000000caa773ecb0 00007ffd30a9ab5e clr!Thread::DoADCallBack+0x278
000000caa773ece0 00007ffd3e34de98 ntdll!RtlpAllocateHeapInternal+0xf8, calling ntdll!RtlpLowFragHeapAllocFromContext
000000caa773edc0 00007ffd3df3a139 combase!_CoInitializeEx+0x1d9 [d:\rs1\onecore\com\combase\class\compobj.cxx:3812], calling combase!CoVrfNotifyCoInit [d:\rs1\onecore\com\combase\verifier\threadstate.cxx:489]
000000caa773ee10 00007ffd3df3a139 combase!_CoInitializeEx+0x1d9 [d:\rs1\onecore\com\combase\class\compobj.cxx:3812], calling combase!CoVrfNotifyCoInit [d:\rs1\onecore\com\combase\verifier\threadstate.cxx:489]
000000caa773ee70 00007ffd30a9aab3 clr!ManagedThreadBase_DispatchInner+0x2fd3, calling clr!Thread::DoADCallBack
000000caa773eeb0 00007ffd30a97a90 clr!ManagedThreadBase_DispatchMiddle+0x6c, calling clr!ManagedThreadBase_DispatchInner
000000caa773eec0 00007ffd30a951a1 clr!ClrFlsIncrementValue+0x29
000000caa773eee0 00007ffd30a950e6 clr!CrstBase::Enter+0x6a, calling ntdll!RtlTryEnterCriticalSection
000000caa773eef0 00007ffd30a951a1 clr!ClrFlsIncrementValue+0x29
000000caa773ef20 00007ffd30a954a7 clr!ThreadSuspend::UnlockThreadStore+0x53, calling clr!ClrFlsIncrementValue
000000caa773ef80 00007ffd30a97651 clr!FrameWithCookie<DebuggerU2MCatchHandlerFrame>::FrameWithCookie<DebuggerU2MCatchHandlerFrame>+0x26, calling clr!Frame::Push
000000caa773efb0 00007ffd30a979cd clr!ManagedThreadBase_DispatchOuter+0x75, calling clr!ManagedThreadBase_DispatchMiddle
000000caa773f040 00007ffd30a97b5f clr!ManagedThreadBase_FullTransitionWithAD+0x2f, calling clr!ManagedThreadBase_DispatchOuter
000000caa773f0a0 00007ffd30b2ee9b clr!ThreadNative::KickOffThread+0xdb, calling clr!ManagedThreadBase_FullTransitionWithAD
000000caa773f140 00007ffd30a95609 clr!operator delete+0x29
000000caa773f170 00007ffd30b42e8f clr!Thread::intermediateThreadProc+0x86
000000caa773f280 00007ffd3196d306 mscoree!calloc_impl+0x72, calling ntdll!RtlAllocateHeap
000000caa773f2e0 00007ffd316090a6 mscoreei!calloc_impl+0x5d, calling ntdll!RtlAllocateHeap
000000caa773f330 00007ffd316031bb mscoreei!operator delete+0x34, calling kernel32!HeapFreeStub
000000caa773f360 00007ffd31601f24 mscoreei!CLRRuntimeInfoImpl::`vector deleting destructor'+0x34, calling mscoreei!operator delete
000000caa773f370 00007ffd316040c9 mscoreei!__DllMainCRTStartup+0x98, calling mscoreei!DllMain
000000caa773f3a0 00007ffd31608a32 mscoreei!ComUtil::IUnknownCommon<ICLRRuntimeInfo,mpl::null_type,mpl::null_type,mpl::null_type,mpl::null_type,mpl::null_type,mpl::null_type,mpl::null_type,mpl::null_type,mpl::null_type>::Release+0x40
000000caa773f3d0 00007ffd31620d17 mscoreei!GetThunkUseState+0x167
000000caa773f410 00007ffd3ac1db2d windows_storage!DllMain+0x7d, calling windows_storage!ATL_DllMain
000000caa773f440 00007ffd3a9ca2ef windows_storage!__DllMainCRTStartup+0xfb, calling windows_storage!DllMain
000000caa773f490 00007ffd3e34de98 ntdll!RtlpAllocateHeapInternal+0xf8, calling ntdll!RtlpLowFragHeapAllocFromContext
000000caa773f4b0 00007ffd0956a65b Microsoft_VisualBasic_Activities_Compiler!__DllMainCRTStartup+0xa3, calling Microsoft_VisualBasic_Activities_Compiler!DllMain
000000caa773f4f0 00007ffd31620f39 mscoreei!CorDllMain+0x1f9, calling mscoreei!PEDecoder::HasManagedEntryPoint
000000caa773f500 00007ffd3e3437d6 ntdll!RtlDeactivateActivationContextUnsafeFast+0xf6, calling ntdll!_security_check_cookie
000000caa773f570 00007ffd31963a1b mscoree!CorDllMain_Exported+0xdb, calling ntdll!LdrpDispatchUserCallTarget
000000caa773f590 00007ffd3e33d514 ntdll!LdrpCallTlsInitializers+0x3c, calling ntdll!RtlReleaseSRWLockShared
000000caa773f5b0 00007ffd3e34389f ntdll!LdrpCallInitRoutine+0x4b
000000caa773f5d0 00007ffd3e3585c0 ntdll!LdrpReleaseLoaderLock+0x20, calling ntdll!RtlLeaveCriticalSection
000000caa773f5e0 00007ffd3e399f74 ntdll!LdrpDropLastInProgressCount+0x38, calling ntdll!RtlLeaveCriticalSection
000000caa773f610 00007ffd3e3412aa ntdll!LdrpInitializeThread+0x20a, calling ntdll!LdrpDropLastInProgressCount
000000caa773f680 00007ffd3e3411ec ntdll!LdrpInitializeThread+0x14c, calling ntdll!RtlActivateActivationContextUnsafeFast
000000caa773f688 00007ffd3e34121b ntdll!LdrpInitializeThread+0x17b, calling ntdll!RtlDeactivateActivationContextUnsafeFast
000000caa773f700 00007ffd3e398412 ntdll!_LdrpInitialize+0x8e, calling ntdll!NtTestAlert
000000caa773f780 00007ffd3e398338 ntdll!LdrInitializeThunk+0x18, calling ntdll!NtContinue
000000caa773fbf0 00007ffd30b42e6f clr!Thread::intermediateThreadProc+0x66, calling clr!_chkstk
000000caa773fc30 00007ffd3dc08364 kernel32!BaseThreadInitThunk+0x14, calling ntdll!LdrpDispatchUserCallTarget
000000caa773fc60 00007ffd3e38e851 ntdll!RtlUserThreadStart+0x21, calling ntdll!LdrpDispatchUserCallTarget

**Comment by mgravell** [comment]
This code was simplified and improved in r571 - so I'm going to close this one down. However, we're currently testing an unrelated performance change (re a race condition on the writer lock), so: I'd hold off for the *next* deploy before updating.
