### ISSUE TITLE
RedisChannel is not retrieving the matched pattern when I receive the delegate

### ISSUE THREAD

**Issue by joaoantunes** [StackExchange/StackExchange.Redis#976]
I'm implementing signalR that is feed by the Pub/Sub of Redis. To interact with Redis I've used StackExchange.Redis-1.2.6.

The issue here is that when I subscribe a pattern on the signalR hub I create a group with ConnectionId and topic that I'm interested and do the same on Redis Pub/Sub.

When I receive the message I need to trace back and notify all the interested subscribers, but the problem is that Redis is not giving me the matched pattern but the published topic instead.

Here is the code sample:

```csharp
        ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost");
        ISubscriber sub = redis.GetSubscriber();

        RedisChannel channelWithLiteral = new RedisChannel("messages", RedisChannel.PatternMode.Literal);
        sub.Subscribe(channelWithLiteral, (channel, message) => 
        {
            Console.WriteLine($"Literal -> channel: '{channel}' message: '{message}'");
        });

        RedisChannel channelWithPattern = new RedisChannel("mess*", RedisChannel.PatternMode.Pattern);
        sub.Subscribe(channelWithPattern, (channel, message) => 
        {
            Console.WriteLine($"Pattern -> channel: '{channel}' message: '{message}'");
        });

        sub.Publish("messages", "hello");
        Console.ReadLine();
```
The output is:

Literal -> channel: 'messages' message: 'hello'
Pattern -> channel: 'messages' message: 'hello'

What I was expecting/needed:

Literal -> channel: 'messages' message: 'hello'
Pattern -> channel: 'mess*' message: 'hello'

On [Redis PubSub documentation](https://redis.io/topics/pubsub) it says when using PSUBSCRIBE we are notified of both: original topic, and matched pattern.

[Here is an image with the example](https://i.stack.imgur.com/c5F9x.png)

Is there any way on StackExchange.Redis to receive the matched pattern?

obs: I've tried the above code with versions:
- StackExchange.Redis v2.0.515 
- StackExchange.Redis.StrongName v1.2.6
the results were the same.

**Comment by mgravell** [comment]
Right now, the only way to do this would be to "capture" the subscription channel when subscribing. However, I think I can see a way that we could add this - at least in 2.*; We could add extra overloads, so there would be a subscribe that takes the existing `Action<RedisChannel, RedisValue>`,and one that took `Action<RedisChannel, RedisChannel, RedisValue>`. I don't know how much this would complicate the internal code, though - I need to check.

**Comment by mgravell** [comment]
That won't "leak" as such - the subscription will keep the string reference
reachable via the captured state, but that's fine (you want the value). If
the delegate ever becomes collectable, the captured state will also be
collectable. So pretty much what you need

**Comment by NickCraver** [comment]
Closing out to cleanup!
