### ISSUE TITLE
How to retrieve multiple values in list if we pass multiple Keys in a list ?

### ISSUE THREAD

**Issue by Vijay27anand** [StackExchange/StackExchange.Redis#98]
I have a requirement of passing a List of keys and I need to get the list of values for that keys. Is it possible to retrieve bulk of key values?

   cache.Set("A", Object1);
   cache.Set("B", Object2);
    List<KeyValuePair<string, object>> redisbulkretrieve;
    List<string> sKeys = new List<string>();
    sKeys.Add("A");
    sKeys.Add("B");

 (List<KeyValuePair<string, object>>)cache.get(sKeys) --> doesnot work.. 

can you help how to retrieve multiple values as list if we pass multiple Keys as list.

**Comment by TranNghia1998** [comment]
> 
I used RedisValue[] StringGet(RedisKey[] keys, CommandFlags flags = CommandFlags.None);
with bulk record (>1milion) then it not work and show message "this operation would involve too many arguments mget"

**Comment by mgravell** [comment]
Well ... yes, don't do that. Batch your data into multiple calls with some reasonable number of keys per call. "Reasonable" depends on the size of each payload (there's a difference between fetching 1kB values vs 200MiB values), but I'd probably start with 1024 keys per call and see how it behaves.

**Comment by TranNghia1998** [comment]
> Well ... yes, don't do that. Batch your data into multiple calls with some reasonable number of keys per call. "Reasonable" depends on the size of each payload (there's a difference between fetching 1kB values vs 200MiB values), but I'd probably start with 1024 keys per call and see how it behaves.

I having issue copy database to server another. Can you solve help me?

**Comment by mgravell** [comment]
Is just coping the RDB file sufficient? If not: crawl the keyspace via GetServer() and .Keys(...), and for each key: use KeyDump[Async] and KeyTimeToLive[Async] on the source and KeyRestore[Async] on the target.
