### ISSUE TITLE
Handling connection string non-availability / changes

### ISSUE THREAD

**Issue by paulhickman-a365** [StackExchange/StackExchange.Redis#984]
I have a security requirement to store the connection string in Azure Key Vault, rather than having it stored locally, which means it may not be available at the time that the services built on top of StackExchange.Redis are initialised. It also means the connection string may be changed in KeyVault without the application restarting, and the use of primary / secondary connection strings.

Is there any recommended approach to dealing with the situation of the connection string becoming invalid during the lifetime of the multiplexer and fetching a new one, or quickly detecting the problem and recreating a new multiplexer promptly? I'm concerned that the internal re-connection mechanism may futilely attempt to re-established the failed connection in this scenario delaying the time before which my code could detect the problem and replace the multiplexer with a fresh one.

Ideally, I'd like to see the multiplexer extended so that the caller can dependency inject a connection string provider that is called to obtain a fresh connection string each time the multiplexer detects it is broken, rather than providing  a static string through an options object.

**Comment by NickCraver** [comment]
We don't support this (not do I think we _should_), if you want to replace the state of the ConnectionMultiplexer, you really just need to store the connection string => `ConnectionMultiplexer` relationship, and connect then swap the multiplexer out when the connection string changes.

Taking a dependency of opinion on any DI framework isn't wise for a client library. For example, how would you do this in SQL Server, MySQL, etc? They're all based on string connections which fetch from a pool based on that string and credential combo. I recommend the same small abstraction here and you could do the reference swap on change or on some timer checking it, etc.
