### ISSUE TITLE
Question: Is it recommended to use the Async methods in the StackExchange.Redis API

### ISSUE THREAD

**Issue by salzersoftware** [StackExchange/StackExchange.Redis#986]
Redis operations are extremely fast. I don't have the link to the Microsoft documentation where it specifies that you don't need to/shouldn't use async for operations under 50ms, but I recall hearing this point.

For this reason, should Async operations even be used? (In fast Redis environments)

**Comment by hartmannr76** [comment]
I think it depends. Theres a [SO question about this](https://stackoverflow.com/a/38119421/1251624) and it seems like the "under 50ms" guideline only applies to UI applications

**Comment by NickCraver** [comment]
It's all `async` under the covers in 2.x due to pipelines and generally how we pipeline data as a task stream of sorts (and this was already largely true in 1.x) - if you're in an `async` path, then yes - use the `async` methods and lighten your IO/thread load a bit.

**Comment by NickCraver** [comment]
Closing out to cleanup :)
