### ISSUE TITLE
Hangfire won't upgrade to 2.0 because of new throughput issues.

### ISSUE THREAD

**Issue by markalanevans** [StackExchange/StackExchange.Redis#990]
@mgravell  We use Hangfire in our project and it uses SE.Redis.1.26, the creator @odinserj noted that your 2.0 design decision version has some throughput side affects that have made him stay with 1.2.6 (discuss in a bit more detail here: https://github.com/HangfireIO/Hangfire/issues/1266#issuecomment-431259590 ).

We are just constantly experiencing timeout issues with it inside of Hangfire and just using 1.2.6.

We have now upgraded to 2.0 hoping that along with some timeout increases, the errors will go away.

I'm just wondering if there is something he doesn't understand about SE.Redis.2.0 and perhaps there isn't an issue.

**Comment by odinserj** [comment]
Oh, I believe it’s not Mark’s headache that HF isn’t updated to the newer version 😅 I’ve posted an update to the referenced issue.

**Comment by mgravell** [comment]
2.0.588 updates and fixes some major problems here; I can't make hangfire take it, but I've dropped a comment recommending they re-evaluate with 2.0.588. I think that's all I can do.
