### ISSUE TITLE
Redis Insert Huge data into MulptipleDb

### ISSUE THREAD

**Issue by narayannk** [StackExchange/StackExchange.Redis#991]
Hi Team,

We have working on a product where we have to keep huge set of data in redis.Is it possible to write extension method for the the getDatabase().Also want to know how to retrive records from a huge column .
NK

**Comment by NickCraver** [comment]
It's not recommend to store a huge data set as a single key (that's going to be a large payload across the network each fetch or update). If using Redis, I'd recommend looking into their data structures and seeing how to best take advantage of them with much smaller deltas across the network. Here's a good intro: https://redis.io/topics/data-types-intro
