### ISSUE TITLE
Keyspace notifications not working on linux (.netcore)

### ISSUE THREAD

**Issue by ghost** [StackExchange/StackExchange.Redis#993]
Simple app using azure redis. Works fine on windows and windows containers. Running on linux or linux containers you never receive keyspace notifications.

```c#
var connection = StackExchange.Redis.ConnectionMultiplexer.Connect(Configuration["RedisEndpoint"]);
                int db = int.Parse(Configuration["RedisDB"]);
                StackExchange.Redis.IDatabase cache = connection.GetDatabase(db);
                var subscriber = connection.GetSubscriber();
                string notificationChannel = "__keyspace@" + db + "__:*";

                subscriber.Subscribe(notificationChannel, (channel, notificationType) =>
                {
                });
```

**Comment by NickCraver** [comment]
Are these configured in Azure? It looks like keyspace notifications are not enabled by default there - more info here: https://docs.microsoft.com/en-us/azure/redis-cache/cache-configure#keyspace-notifications-advanced-settings

**Comment by devkws** [comment]
Yes, they are in Azure in this particular instance, and i did configure keyspace notification as AKE. 
Though i did replicate with a Redis cache deployed in kubernetes as well. Again, this works fine on windows, in windows containers. But as soon as the same code runs on linux, notifications stopped coming in. I have switched to another client which works on both windows and linux for now, though i thought the bug should be reported.

**Comment by NickCraver** [comment]
Interesting - I've got no clue why there'd be a difference here but we'll take a look. Thanks a lot for the report and additional info!

**Comment by czaban** [comment]
This bug is present under .NET8/Linux with 2.8.16
