### ISSUE TITLE
Is it possible to connect using named pipes?

### ISSUE THREAD

**Issue by jbrunken** [StackExchange/StackExchange.Redis#999]
I'm currently working on a linux hosted ASP.NET core app and I have my local redis instance setup to use named pipes.   This is how I've been connecting with Node.js.

Does StackExchange.Redis support this?

I can't find any reference to it in the documentation.

Thanks!

**Comment by mgravell** [comment]
That isn't one I've looked at. If you can guide me on how to setup
something, I can investigate what would be involved? I think Unix sockets
work now, but we'd probably need a different pipeline provider for named
pipes. That's OK - I kinda enjoy writing pipeline providers :)

**Comment by jbrunken** [comment]
I apologize, it's actually unix sockets that I need.   I don't know why I was thinking named pipes.

How do I specify a unix socket in the config string?

**Comment by jbrunken** [comment]
That works great!  Thanks

In case anyone else is looking for this, I just used the following:
```
var options = new ConfigurationOptions();
options.EndPoints.Add(new UnixDomainSocketEndPoint("/tmp/redis.sock"));
```
